### ISSUE TITLE
Glorytun UDP can only connect to one openmptcprouter. I have two openmptcprouters. How to set them up? Thank you!

### ISSUE THREAD

**Issue by eirdgms** [Ysurac/openmptcprouter#1002]
Glorytun UDP can only connect to one openmptcprouter. I have two openmptcprouters. How to set them up? Thank you!

**Comment by gnosoz** [comment]
manually change the local ip ending to another number, you can do this via
the luci glorytun setup and it should work though i am not sure what you
plan to accomplish...

**Comment by Ysurac** [comment]
One Glorytun server can receive only one glorytun client.

**Comment by eirdgms** [comment]
thank you!
