### ISSUE TITLE
Failed to execute call dispatcher target

### ISSUE THREAD

**Issue by nileio** [Ysurac/openmptcprouter#101]
## Expected Behavior
no errors related to openmptcprouter.lua 
i assume this is the file responsible containing functions used by wizard and status, graph, etc

## Actual Behavior

the following errors appear in the system log (repeatedly)

Tue Jul  3 20:55:49 2018 daemon.err uhttpd[2431]: Failed to execute call dispatcher target for entry '/admin/system/openmptcprouter/interfaces_status'.
Tue Jul  3 20:55:49 2018 daemon.err uhttpd[2431]: The called action terminated with an exception:
Tue Jul  3 20:55:49 2018 daemon.err uhttpd[2431]: /usr/lib/lua/luci/controller/openmptcprouter.lua:519: attempt to concatenate local 'ifname' (a nil value)
Tue Jul  3 20:55:49 2018 daemon.err uhttpd[2431]: stack traceback:
Tue Jul  3 20:55:49 2018 daemon.err uhttpd[2431]: 	/usr/lib/lua/luci/controller/openmptcprouter.lua:519: in function 'callback'
Tue Jul  3 20:55:49 2018 daemon.err uhttpd[2431]: 	/usr/lib/lua/luci/model/uci.lua:251: in function 'foreach'
Tue Jul  3 20:55:49 2018 daemon.err uhttpd[2431]: 	/usr/lib/lua/luci/controller/openmptcprouter.lua:498: in function </usr/lib/lua/luci/controller/openmptcprouter.lua:368>
Tue Jul  3 20:55:49 2018 daemon.err uhttpd[2431]: 	(tail call): ?

## Steps to Reproduce the Problem

not sure if it has to do with my configuration. I checked the interfaces, labels, etc. everything seem to be ok

  1. default installation and configuraiton
  2. errors start appearing

## Specifications

  - OpenMPTCProuter version: v0.25
  - OpenMPTCProuter VPS version: latest
  - OpenMPTCProuter platform: (RPI3/x86_64) ; RPI2B

**Comment by Ysurac** [comment]
There is no ifname (real interface) defined for an interface that have multipath enabled.
The error is fixed in master tree, no more logs but an error displayed in status page.
