### ISSUE TITLE
Build ZBT-WE3526

### ISSUE THREAD

**Issue by JorgeMoort89** [Ysurac/openmptcprouter#1010]
Hi Ysurac,
I can't build OMR for ZBT-WE3526, are MIPS CPU compatible?

Thanks

**Comment by Ysurac** [comment]
No idea. I don't have any MIPS platform and I don't know any that have a fast enough CPU and enough flash available.

**Comment by JorgeMoort89** [comment]
Have I to select only target system, subtarget and profile on menuconfig?
Is steadily failing the build

**Comment by Ysurac** [comment]
Yes, some changes may also be needed for lan/wan name of ports.
This may be a package that fail, or something else. But it's not a supported platform and this seems to be a too slow/small platform for me to work in.

**Comment by JorgeMoort89** [comment]
I'm successfully building the image, but is too big to fit the 32MB flash on the router (about 35MB). How can I build a lighter image? For example I don't need OpenVPN or MLVPN

**Comment by Ysurac** [comment]
You can remove them in make menuconfig, you need to remove openmptcprouter-full first.
I will make a "openmptcprouter-light" when I will have some time for that ;)

**Comment by JorgeMoort89** [comment]
Just tested, but removing openmptcprouter-full remove all the other packages, which package are essential to build a working image?
Thanks a lot for the help :)
