### ISSUE TITLE
How could be possibile to setup port range in OMR-Bypass?

### ISSUE THREAD

**Issue by matfil92** [Ysurac/openmptcprouter#1014]
Hi,
I need to setup a port range in OMR-Bypass to force that specific port range will pass through specific interface. I've tried put i.e. 5060-5070 but doesn't work, in details it save the settings but in the same time will make ineffective all settings in the page. 

How could be possible to setup port range without wrote each port in single row? 

I need to add Zoom port or IP https://support.zoom.us/hc/en-us/articles/201458316-Network-Firewall-Settings-for-CRC 
but in both case I don't want to setup each IP in single row or each port in single row

**Comment by Ysurac** [comment]
Port range must be set like this: ```5060:5070```

**Comment by matfil92** [comment]
Also in dscp configuration ?

Inviato da iPhone

**Comment by Ysurac** [comment]
Yes.
Both (":" and "-") will be authorized in next release.
