### ISSUE TITLE
Test MultiPathTCP

### ISSUE THREAD

**Issue by ccmks** [Ysurac/openmptcprouter#1015]
Hello,

I would like to know if there is any way or tool to test if the ISP is not blocking MultiPatchTCP before deploy OpenMPTCPRouter. Please advise.

Thank you

**Comment by Ysurac** [comment]
[Tracebox](https://github.com/tracebox/tracebox) can be used: ```tracebox -v -i $INTERFACE -n -p IP/TCP/MSS/MPCAPABLE/WSCALE multipath-tcp.org```

**Comment by ccmks** [comment]
Is there any easy way? The method above requires linux or mac. How about test it from a smartphone?

**Comment by Ysurac** [comment]
Tracebox is available on android.

**Comment by ccmks** [comment]
I tried it and didn't work. Can you enlighten me on how to use it on Andorid?

**Comment by Ysurac** [comment]
No, I don't use it on Android.
