### ISSUE TITLE
Installation via sh failed python

### ISSUE THREAD

**Issue by PecaPit** [Ysurac/openmptcprouter#1023]
When trying to install  with a script debian9-x86_64.sh , an error occurs python 

-- pip3 install needed python modules
  Failed building wheel for uvloop

Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-                                                                                                                                                             install-5r8y0rnr/uvloop/setup.py';f=getattr(tokenize, 'open', open)(__file__);co                                                                                                                                                             de=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec')                                                                                                                                                             )" install --record /tmp/pip-record-gn39t90u/install-record.txt --single-version                                                                                                                                                             -externally-managed --compile" failed with error code 1 in /tmp/pip-install-5r8y                                                                                                                                                             0rnr/uvloop/

I tried to install on Debian 9/10, Ubuntu 18

Everywhere the same error referring to phyton

Hyper-V VPS 1Core/512Mb

**Comment by Ysurac** [comment]
As you can see in the doc, the VPS need to have at least 1024Mo RAM.
