### ISSUE TITLE
[FR] Status and bandwidth graph on top page or at least prominently linked.

### ISSUE THREAD

**Issue by Adorfer** [Ysurac/openmptcprouter#1028]
## Expected Behavior

Having the status pages linked directly/more prominently (not in 2nd row)

/cgi-bin/luci/admin/network/mptcp/bandwidth
/cgi-bin/luci/admin/system/openmptcprouter/status

## Current Behavior

you have to go to manually to 
"Network"/"mptcp" and then to the tab "bandwidth"
and 
"System" / "openmptcprouter" and then to tab "status"

## Possible Solution

Putting at least a link to both pages directly on 
/cgi-bin/luci/admin/status/overview 

Integration of thos data on the start page would be really appreciated, either top or bottom. 
plus a link there to the "bandwidth"-graph. Or even integrate that as well.
(example: Look on OVH-OTB design)

## Context (Environment)

- openmptcprouter v0.55beta4 
- openmptcprouter v0.54.7

**Comment by xabix** [comment]
Agreed this would be nice and handy as I often wonder how my 4g are doing so being able to overlook at those graphs would be great in one shot
