### ISSUE TITLE
Kernel and Syslog of router flooded with XHCI_HCD failed

### ISSUE THREAD

**Issue by DeeJayMX** [Ysurac/openmptcprouter#1033]
## Current Behavior
Log flooded with:

```
Wed May 20 15:34:00 2020 kern.err kernel: [862750.326947] xhci_hcd 0000:01:00.0: Ring expansion failed
Wed May 20 15:34:00 2020 kern.err kernel: [862750.332393] hub 1-1:1.0: activate --> -12
```
repeating every seconds

## Possible Solution
Really don't know as there is no USB device plugged in

## Steps to Reproduce the Problem
-Start the OMR
-Put Scaling governor in "performance" mode
-wait couples of hours

## Context (Environment)
It seems that is not disturbing the operation of the router but not a clean behavior too

## Specifications

  - OpenMPTCProuter v0.54.7 r0+12509-04a21c26a0
  - OpenMPTCProuter VPS v 0.1015 4.19.104-mptcp
  - OpenMPTCProuter platform: RPi 4B 4GB

**Comment by Ysurac** [comment]
It's a know RPI issue: https://github.com/raspberrypi/linux/issues/3479
