### ISSUE TITLE
Problem with starting Router on PC x86_64 and Raspberry3B+ and Virtualbox

### ISSUE THREAD

**Issue by anjszulc** [Ysurac/openmptcprouter#1034]
## Expected Behavior
The router should start up but stop at the command
8021q: adding VLAN 0 to HW filter on device wan2

## Current Behavior
hang on 8021q: adding VLAN 0 to HW filter on device wan2 

## Steps to Reproduce the Problem

 I try different images for x86 (DELL Optiplex with two ethernet cards
Rasp 3B+
Virtualbox 

 Image for VirtualBox
![Screenshot 2020-05-21 19 55 02](https://user-images.githubusercontent.com/65730071/82589824-01c3c780-9b9d-11ea-954e-792142d67fa3.png)

Rasp3B+ screen
![IMG-0026](https://user-images.githubusercontent.com/65730071/82591027-f7a2c880-9b9e-11ea-91b1-ac4827d1bc15.jpg)

## Context (Environment)
I install Server on Amazon EC2 and Vultr.com but can't run router.  

## Specifications

  - OpenMPTCProuter version: 0.54.7
  - OpenMPTCProuter VPS version: 0.1015 Ubuntu / 0.1015 Debian as backup
  - OpenMPTCProuter platform: RPI3/x86_64/VBOX x86_64

**Comment by Ysurac** [comment]
Press "Enter" to display the login. Interface is available by default at http://192.168.100.1/

**Comment by anjszulc** [comment]
ohh...shit... stupid me...

**Comment by Ysurac** [comment]
No problem, you are not the first. I know it can be strange when we know other Linux distribution :)
