### ISSUE TITLE
Traduction

### ISSUE THREAD

**Issue by Quenty-tolosan** [Ysurac/openmptcprouter#1035]
Bonjour,

j'ai vu des captures du logiciels en français et en anglais.
Je souhaiterais savoir s'il est possible de proposer une autre langue.
Je n'ai pas bien compris comment fonctionnait le système.

Merci !

**Comment by Ysurac** [comment]
Pour le moment en traduisant les .po dans les répertoire luci-app-*
Mais je vais prochainement ajouter un outils de traduction sur un serveur.

**Comment by Ysurac** [comment]
Un outils de tradition est maintenant disponible sur https://weblate.openmptcprouter.com/

**Comment by Quenty-tolosan** [comment]
Merci ! C'est possible d'ajouter l'occitan dans la liste des langues du projet ?

**Comment by Quenty-tolosan** [comment]
Merci ! C'est possible d'ajouter l'occitan dans la liste des langues du projet ?

**Comment by Ysurac** [comment]
Oui pas de soucis, il suffit de créer un compte dans weblate et de démarrer une nouvelle traduction.

**Comment by Quenty-tolosan** [comment]
Non je n'ai pas le bouton pour démarrer une nouvelle traduction =/

**Comment by Ysurac** [comment]
Tu dois l'avoir ici normalement : https://weblate.openmptcprouter.com/projects/omr/luciapplicationsopenmptcprouter/ sous la liste des langues.

**Comment by Quenty-tolosan** [comment]
J'ai envoyé une demande pour traduire OpenWrt en occitan :)
Je vais voir ce que mes mémoires de traductions peuvent me faire gagner comme temps :D

**Comment by Quenty-tolosan** [comment]
Salut @Ysurac sais-tu dire quand l'occitan sera intégré ?

**Comment by Ysurac** [comment]
J'essaye de bosser là dessus. C'est plus complexe du fait que l'Occitan n'est pas présent dans OpenWrt.
Je pense qu'au minimum il y aura le fichier base.po à traduire en plus, mais faut déjà que j'arrive à faire afficher des trucs en Occitan ;)

**Comment by Quenty-tolosan** [comment]
j'avais essayé d'ajouter l'occitan sur leur interface de traduction sans succès. Si tu as des contacts je suis preneur
