### ISSUE TITLE
How to access the NAS through the 4G connection?

### ISSUE THREAD

**Issue by Xamamule** [Ysurac/openmptcprouter#1041]
I am a beginner on this subject. With several tutorials on the internet I tried several solutions which all failed.
I managed to aggregate two connections: FreeBox adsl and a 4G modem (4G-AC68U). Everything works perfectly.
Thanks to the community.
![Capture](https://user-images.githubusercontent.com/5912646/82990251-3059fc00-9ffc-11ea-9cd8-ab1ad460a841.PNG)
Now I am trying to access my Synology NAS from outside. To do this, I set up the firewall.
![Capture2](https://user-images.githubusercontent.com/5912646/82990333-541d4200-9ffc-11ea-8062-9eb9cb315782.PNG)
With ip of VPS, I can now access my NAS, but according to my tests only through the adsl (freebox).
Is it possible to use 4G also to access my NAS?
By reading tutorials, I understood that I had to configure OpenVpn on the VPS server, but I don't know how to do it? Can you help me ? Thank you

**Comment by Ysurac** [comment]
Please use the template when submitting an issue.
This use the VPN defined in the wizard, by default Glorytun TCP.
