### ISSUE TITLE
Display

### ISSUE THREAD

**Issue by ascomputer** [Ysurac/openmptcprouter#1044]
hello everyone ... with the raspberry 3+ is it possible to see the bandwith interfaces from the display?

**Comment by Ysurac** [comment]
no, or at least not easily. This would need something like xorg and a browser on the RPI.

**Comment by ascomputer** [comment]
this could be interesting for me ... if it is possible to make it on a 3.5 inch display and had only the possibility to visualize the speed of the single wan ... if you can I can leave you email contact for eventual estimate.
