### ISSUE TITLE
about the none encrypt method ,do you have a run in ss-3.2.0 version?

### ISSUE THREAD

**Issue by abilly007** [Ysurac/openmptcprouter#105]
## Expected Behavior

  In English please.

## Steps to Reproduce the Problem

  1. when i run in aes-256-cfb encrypt method both on VPS and router,they work well ,but just poor in performance. So, i try to change the encrypt method into none，and the key set to ''.
And then,the ss-server is running well, but the ss-local and ss-redir in the router cannot run on,and there nothing info log in the syslog.

can you have a try, or give me some suggestion.,thanks.

## Specifications

  - OpenMPTCProuter version: (Last is not a version)
  - OpenMPTCProuter VPS version: (Last is not a version)
  - OpenMPTCProuter platform: (RPI2/RPI3/x86/x86_64)

**Comment by Ysurac** [comment]
If you put something in the key field for shadowsocks this will work (must not be empty). It will be fixed in next release.

Without encryption you will not have really better performances. The problem must be elsewhere.
