### ISSUE TITLE
Pi-hole openmptcp 

### ISSUE THREAD

**Issue by yaya68** [Ysurac/openmptcprouter#1052]
Bonjour 

J’ai installer pi-hole sur un Raspberry je voudrais savoir comment changer le dns de openmptcp pour mettre l’adresse ip de pi hole 
Merci d’avance

**Comment by Ysurac** [comment]
Veuillez remplir le template lors de l'ouverture d'une issue. Ca me permet de tout de suite savoir les versions utilisées etc...
