### ISSUE TITLE
vlan on LAN

### ISSUE THREAD

**Issue by ctrlx83** [Ysurac/openmptcprouter#1054]
Bonjour à tous,

Je ne parviens pas à configurer une interface LAN avec un vlan.
Est ce qu'il y a une manipulation particulière à faire ou quelque chose à savoir ?

Merci à vous

**Comment by Ysurac** [comment]
Il ne faut pas que MacVLAN soit utilisé, car c'est déjà des VLANs.
Ensuite tout dépend de l'arch, si il y a un switch intégré comme les WRTx/BPI-R2/... ou pas.

**Comment by ctrlx83** [comment]
@Ysurac y a t il une mathode simple pour désactiver MacVLAN ?

merci

**Comment by Ysurac** [comment]
Dans réseau->Macvlan en supprimant les interfaces.

**Comment by ctrlx83** [comment]
@Ysurac 

ok merci
et ensuite pour assigner un vlan à une interface lan ?

**Comment by Ysurac** [comment]
en utilisant comme interface physique eth1.10 pour le vlan 10 par exemple.

**Comment by geekdomotique** [comment]
Bonjour, je souhaite aussi mettre en place un vlan pour du wifiguest, je vais dans réseau \ interface et la je ne sais plus quoi faire.... Faut-il ajouter une nouvelle interface ou éditer Lan-eth0 existante?
Merci d'avance pour ta réponse Ysurac

**Comment by Ysurac** [comment]
@geekdomotique wifi interne ? Ca dépend comment il a été configuré. Le plus simple dans ce cas est qu'il soit sur sa propre interface avec vlan.

**Comment by geekdomotique** [comment]
Pour être plus précis je souhaite que mon vlan50 (dédié wifiguest) soit aussi déclaré coté openmptprouteur, est ce par le macvlan qu'il faut passer ou alors créer une régle vlan, je suis perdu et ne sais pas comment faire...

**Comment by Ysurac** [comment]
il faut créer une interface basée sur, par exemple, eth0.50

**Comment by geekdomotique** [comment]
Je créé une nouvelle interface avec en nom : VLAN50 et protocole IPstatique, je bridge interface eth0 et après je ne vois pas ou je peux tague un vlan.... Help

**Comment by Ysurac** [comment]
Lors de l'édition d'une interface, dans l'onglet paramètres physique en créant une interface personnalisée nommée eth0.50, sans bridge.
