### ISSUE TITLE
change ip lan

### ISSUE THREAD

**Issue by ascomputer** [Ysurac/openmptcprouter#1055]
hello everyone I tried to change ip lan 192.168.100.1 with 192.168.50.1 both from the web and from ssh in this way uci set network.lan.ipaddr = '192.168.50.1' && uci commit && reboot
the ip is changed but I no longer have access to the web uci
Can anyone help me? Thanks

**Comment by vinceducat** [comment]
i suppose you change the ip from where you change the ip of omr before retrying to connect OMR, or renew DHCP leases ....

**Comment by ascomputer** [comment]
I made checks everything works if I put ip 192.168.50.1 but it doesn't work if I use 172.0.0.1
