### ISSUE TITLE
ip public

### ISSUE THREAD

**Issue by ascomputer** [Ysurac/openmptcprouter#1056]
having a vps with 8 public static ip and 8 client pc is it possible to assign a public ip for each client? thanks

**Comment by suyuan168** [comment]
You can use a separate eight ordinary routers to provide public static IP for Internet access devices. Or insert the network cable directly.

**Comment by Adorfer** [comment]
This issue looks for me like a duplicate of 
https://github.com/Ysurac/openmptcprouter/issues/1006

Correct?

**Comment by Ysurac** [comment]
True. I will try to centralize solutions on 1006 issue.
