### ISSUE TITLE
Openmtcprouter on virtualbox (macos) problem

### ISSUE THREAD

**Issue by constant1010** [Ysurac/openmptcprouter#106]
## Actual Behavior

I have test openmtcprouter with virtualbox.
Openmtcprouter can access  the internet with IP of vps (diagnostics) but no access from an other machine.
Bridge is ok, promiscuity all accept

## Specifications

  - OpenMPTCProuter version: v0.27
  - OpenMPTCProuter VPS version: v0.33
  - OpenMPTCProuter platform: vdi/vitualbox/mac os

**Comment by Ysurac** [comment]
Other machines are on the same network  as OpenMPTCProuter ? Can you ping OpenMPTCProuter from an other machine?

**Comment by constant1010** [comment]
Yes ,same network as OpenMtcprouter, Mac, and other machine.
Other machine can access at interface of Openmtcprouter.

**Comment by Ysurac** [comment]
So if OpenMPTCProuter is set as default route, this should work. OpenMPTCProuter status page is ok ?

**Comment by constant1010** [comment]
Status page is ok.
I thinks maybe mac os blocks access internet but I don't were
