### ISSUE TITLE
Channge DNS Server

### ISSUE THREAD

**Issue by LeprovostNoam** [Ysurac/openmptcprouter#1064]
## Expected Behavior
By default, openmptcprouter use the VPS as DNS server but i want to use 1.1.1.1 & 1.0.0.1

## Current Behavior
I've changed "transmissions DNS" input, but not working DNS_PROBE_FINISHED_BAD_CONFIG
<img width="1440" alt="Capture d’écran 2020-06-07 à 17 27 28" src="https://user-images.githubusercontent.com/38590140/83973297-bcfe9700-a8e5-11ea-8f64-3420dad42b80.png">

## Specifications

  - OpenMPTCProuter version:  openmptcprouter-v0.54.7
  - OpenMPTCProuter platform: Linksys WRT3200ACM

**Comment by LeprovostNoam** [comment]
adding 1.1.1.1#53 & 1.0.0.1#53 is not possible, only on "Domaine local"

**Comment by Ysurac** [comment]
You can set it as local server. It's an OpenWrt issue.
But why would anyone use Cloudfare DNS ? It's really strange...
Cloudfare DNS are used for OMR-Tracker, this can give some strange behaviour.

**Comment by Adorfer** [comment]
if you want do something fancy, use DoH and combine it with Pi-Hole.
https://openwrt.org/docs/guide-user/services/dns/doh_dnsmasq_https-dns-proxy

**Comment by LeprovostNoam** [comment]
> Vous pouvez le définir comme serveur local. C'est un problème OpenWrt.
> Mais pourquoi quelqu'un utiliserait-il Cloudfare DNS? C'est vraiment étrange ...
> Cloudfare DNS est utilisé pour OMR-Tracker, cela peut donner un comportement étrange.

c'est à dire un comportement étrange?

**Comment by Ysurac** [comment]
Dans certains cas une route directe via un WAN est créée en direction des IPs utilisées par OMR-Tracker. Donc lors de l'interrogation par un client vers ces IPs la connexion peut ne pas aboutir de temps en temps.

**Comment by LeprovostNoam** [comment]
D'accord, et bien je n'ai pas eue de problème encore. Le truc c'est que netflix me bloque si j'ai le dns de mon serveur google cloud et pas cloudflare.. J'avais le même problème avec speedify

**Comment by Ysurac** [comment]
Etrange ça, normalement netflix bloque par IP source.
Par défaut les serveurs DNS racines sont utilisés (donc pas ceux du VPS ou d'un FAI).
