### ISSUE TITLE
Qmi wont work well when signal changes

### ISSUE THREAD

**Issue by JesseYang2020** [Ysurac/openmptcprouter#1069]
There are two cases:
1. When the machine start up, if there is no signal, then qmi wont connect forever
2. When the machien start up, if there has good signal, then qmi will work well. But if it went to the bad signal place for some minutes, it will loss connect forever even you go back to the good signal place.

**Comment by suyuan168** [comment]
你应该检查omr-tracker设置。

**Comment by pylaterreur** [comment]
如果你写汉语，请也写法文还是英文. 谢谢你们  :p

**Comment by suyuan168** [comment]
You should check omr-tracker settings
