### ISSUE TITLE
RAM consumption problem

### ISSUE THREAD

**Issue by couili** [Ysurac/openmptcprouter#1073]
Hello,
I just got the fiber optic at home, so I ran the VPS script on a freshly installed Debian 10 on an ESXI. Everything works fine, but after a while, the RAM consumption becomes excessive, on my VPS at Scaleway, I didn't have this problem. Here, I have a constant consumption of 4GB of RAM, whereas when starting the machine the RAM consumption is less than 1GB of RAM.
I feel like the "omr-admin.py" script is running multiple times.

![image](https://user-images.githubusercontent.com/42115508/84900748-d3a5aa80-b0aa-11ea-9611-318640d584a9.png)

## Possible Solution
Reboot VPS

## Specifications

  - OpenMPTCProuter version: 0.54.7
  - OpenMPTCProuter VPS version: v0.1015
  - OpenMPTCProuter platform: x86_64

Can you please help me?

Thanks

**Comment by Ysurac** [comment]
You can check using ```ps aux | grep omr``` that there is only one script running. htop list all threads of a process.
There is many running threads in your case.

**Comment by couili** [comment]
Here is the result of the command :
![image](https://user-images.githubusercontent.com/42115508/84911364-55500500-b0b8-11ea-8502-1dc8a9c94fee.png)

**Comment by couili** [comment]
Hello,
After a day of operation, almost all of my RAM is in use
![image](https://user-images.githubusercontent.com/42115508/85001862-7bc37e00-b154-11ea-91aa-f85538db78c4.png)

**Comment by Ysurac** [comment]
What is the result of ```ps aux --sort=-%mem | head``` ?

**Comment by couili** [comment]
Here is the result of the command :
![image](https://user-images.githubusercontent.com/42115508/85016919-ef708580-b16a-11ea-9888-5b0abd40ac51.png)

**Comment by Ysurac** [comment]
Do you do some p2p ? or anything that is not browsing internet ?

**Comment by couili** [comment]
I do openvpn for telecommuting, as well as openvpn when I'm away from home to access my LAN, and I have cameras that I think work in P2P when we want to watch the images from outside, but we rarely watch.

**Comment by Ysurac** [comment]
I think it's related to tcp/udp buffer. This may be related to a MTU too high.
This should be better in next release.

**Comment by JorgeMoort89** [comment]
Hi Ysurac, where I can edit the size of those buffers?

**Comment by Ysurac** [comment]
This will be in next release, and it's in current snapshot VPS script and beta router release.

**Comment by couili** [comment]
Thanks for your help
