### ISSUE TITLE
How to test IPv6 has been supported？

### ISSUE THREAD

**Issue by abilly007** [Ysurac/openmptcprouter#108]
## Expected Behavior

  In English please.

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - OpenMPTCProuter version: (Last is not a version)
  - OpenMPTCProuter VPS version: (Last is not a version)
  - OpenMPTCProuter platform: (RPI2/RPI3/x86/x86_64)

**Comment by Ysurac** [comment]
In **System**->**OpenMPTCProuter**->**Status** page, this display your public IPv6 if it's working.

**Comment by abilly007** [comment]
1, myrouter status page as show below:
 ![status2](https://user-images.githubusercontent.com/37547039/43068881-323c37e0-8e5b-11e8-8c6a-e8334d818852.jpg)

2. there is a bit problem ,the status page show that my glory VPN down, in fact ,my glorytun VPN is running .i can ping success the glorytun vpn server 10.255.255.1 (by default configuraton) on the router, by cannot get the gateway from the interface omrvpn,is need to add the
 peeraddr or gateway 10.255.255.1 to the interface omrvpn config ?

![ping1](https://user-images.githubusercontent.com/37547039/43069474-b2091f96-8e5c-11e8-8cf5-19192466c7ff.png)

![config1](https://user-images.githubusercontent.com/37547039/43069356-62de7326-8e5c-11e8-90ce-0792c2cbad7f.png)

**Comment by Ysurac** [comment]
You should update to a newer OpenMPTCProuter version.

**Comment by abilly007** [comment]
so，i update to lastest version as bellow:
•OpenMPTCProuter version: (Last is not a version) v0.27
•OpenMPTCProuter VPS version: (Last is not a version) V0.34
•OpenMPTCProuter platform: (RPI2/RPI3/x86/x86_64) rpi2

and then, the status page cannot get nothing result  all the time, as show this :


![status10](https://user-images.githubusercontent.com/37547039/43112779-2e3de3dc-8ee7-11e8-8b01-9d97476b5f0c.png)

and i can get wan_addr and ss_addr by command line as :



![wget2](https://user-images.githubusercontent.com/37547039/43112955-d8b61410-8ee7-11e8-9bdb-aa177130c37c.jpg)

**Comment by abilly007** [comment]
so ,i update a lastest version of router as bellow:
•OpenMPTCProuter version: (Last is not a version) v0.27
•OpenMPTCProuter VPS version: (Last is not a version) v0.34
•OpenMPTCProuter platform: (RPI2/RPI3/x86/x86_64)rpi2
and the status page as show bellow:
![status11](https://user-images.githubusercontent.com/37547039/43113450-00d3df8e-8eea-11e8-9bb4-b57d4ec99aab.jpg)

**Comment by Ysurac** [comment]
2 problems:
* There is another IPv6 route that is announced on your network and received on wan1 and wan2
* On version 0.27 there is a check that OpenMPTCProuter can contact the VPS with IPv6 over the tunnel, the test is ok. But no public IPv6 is displayed so there is a problem on the VPS.

Shorewall6 is running on the VPS ? The VPS was rebooted after update ? The VPS have a public IPv6 address that is working ?

**Comment by abilly007** [comment]
so,
  1. i disable ipv6 dhcp on the two router that conected to the rpi2 with wan1 and wan2.
  2. the shorewall6 is running on the VPS, VPS is rebooted after update. but there is no public ipv6 address,i donot known how can i get a public ipv6 address on my vps?there just have a public ipv4 address.

beside,sometimes the status page is running all the time and get nothing result,why ?

**Comment by Ysurac** [comment]
1. Yes
2. If your VPS provider give IPv6 check with your provider how to set it. Else you can use something like he.net but I don't provide any help on this (and I don't recommend it).

For the empty result: No idea, I don't have the problem. Maybe a check not working well and that take too much time. Some fix on that will be available in next version.

**Comment by abilly007** [comment]
hi，Ysurac . i change a VPS that has i public ipv6 address.end then i ping ipv.google.com from openmptcprouter is success.but from the PC that connected to the openmptcprouter is failed.


![ipv6-ping](https://user-images.githubusercontent.com/37547039/43244401-030e06ce-909a-11e8-8e33-455295695472.png)

is missing some configuration on my router? i see the syslog have the item info:
daemon.warn odhcpd[1573]: A default route is present but there is no public prefix on eth0 thus we don't announce a default route!

is the problem i donot config a ipv6 router prefix in the omr-6in4 interface ? is that ,what ipv6 router prefix i should config ?

**Comment by Ysurac** [comment]
You need to check *Always announce default router* in *IPv6* tab of LAN interface (it's enabled by default).

**Comment by abilly007** [comment]
Thank you very much ,my router disable the Always announce default router of lan interface,and now it is ok after i enable .
