### ISSUE TITLE
about last version

### ISSUE THREAD

**Issue by zulu14** [Ysurac/openmptcprouter#1083]
hello, its not a issues, 
i follow the project, i actualy run OMR on 54.7, 
on the weboage is the "last" version,
I know I'm happy to be able to test the dev versions, like fixing nginx-ha for the vpn tunel error.
I could see on other thread that the 0.55-beta was evolved,
what is the latest version? who is special about V0.55?
thank you for your work on this wonderful project

**Comment by Ysurac** [comment]
Most new features are in first thread of https://github.com/Ysurac/openmptcprouter/issues/959
Else you can find detailed changes in https://github.com/Ysurac/openmptcprouter-feeds/commits/develop, https://github.com/Ysurac/openmptcprouter/commits/develop and https://github.com/Ysurac/openmptcprouter-vps-admin/commits/develop
There is also some new patches for Shadowsocks-libev in https://github.com/Ysurac/shadowsocks-libev/commits/master and some changes in VPS script that are not yet commited.
