### ISSUE TITLE
Hardware to be supported in the 0.55 release

### ISSUE THREAD

**Issue by Corrado56** [Ysurac/openmptcprouter#1084]
Hi, Just a question about the hardware to be supported in version 0.55
Linksys wrt3200ACM will still be supported ?
Any new hardware ?

Regards

**Comment by Ysurac** [comment]
Hi,
All hardware supported in 0.54 will still be supported in 0.55.
No new hardware supported, but if you have some suggestion...

**Comment by Corrado56** [comment]
![Raspberry stressato 1](https://user-images.githubusercontent.com/10588158/86445248-5452e080-bd12-11ea-9ab7-e87f2d6dbc7d.jpg)

I asked because my Raspberry is a bit stressed, I prefere RJ45 ports native on hardware, Linksys is not cheap, and I want to be sure will be supported in the future.

Thanks

**Comment by Ysurac** [comment]
If you have a switch, you don't need to use adapters on the Raspberry.

**Comment by Corrado56** [comment]
Does not work for me,  see #1075

**Comment by Ysurac** [comment]
yes true, sorry.
Even if I still don't understand why this work with adapters ;)

**Comment by bambuca** [comment]
I had problems with switch. ISP1 was using DHCP and the second (ISP2) don't. When I connected both into one switch then the DHCP was propagated to ISP2 and he was a bit angry.
