### ISSUE TITLE
Question: switching to mainline kernel

### ISSUE THREAD

**Issue by VoightKampff** [Ysurac/openmptcprouter#1085]
Looking at the LKML (linux kernel mailing list) it seems that the mainline kernel is getting more and more mptcp patches. However, I took a quick look at the source code and it seems to me that it's a completely new implementation compared to https://github.com/multipath-tcp/mptcp. Did you (@Ysurac) investigate whether switching from the forked kernel to mainline is looking like a viable option in the future?

**Comment by Ysurac** [comment]
I think mainstream MPTCP will not be used before next LTS kernel (or this will be a backport).
Latest MPTCP changes are available here: https://github.com/multipath-tcp/mptcp_net-next so there is still many changes each days...
I hope to begin first tests on x86_64 arch after next stable release.
