### ISSUE TITLE
Cannot access admin page on Raspberry Pi

### ISSUE THREAD

**Issue by ticanuk** [Ysurac/openmptcprouter#1088]
I have installed openmptcprouter on an SD card for my Pi. It has booted up with no errors. But I cannot connect in a browser to 192.168.100.1, I get this error on Chome:

`This site can’t be reached192.168.100.1 refused to connect.`

I've tried disconnecting my 4g mifi/dongle and just connecting direct to the switch via ethernet, but still nothing. 

I cannot connect to admin page, so I cannot get this set up locally. I have installed with no problems on my VPS

  - OpenMPTCProuter version: 0.54.7
  - OpenMPTCProuter VPS version: 0.1015
  - OpenMPTCProuter platform: RPI 4

**Comment by Ysurac** [comment]
You need to have no other DHCP server on the network and check that you client computer is not set with a static IP.
Else you can set your client computer with a static IP on the 192.168.100.x network.
