### ISSUE TITLE
Unable to connect on Virtualbox

### ISSUE THREAD

**Issue by rifaterdemsahin** [Ysurac/openmptcprouter#1094]
## Expected Behavior
I expect to be able to connect to OMR using internal networks in Virtualbox.
I expect to be able to connect to OMR using hostonly networks in my network

## Current Behavior
I can ping the box inside OMR
I cant reach from outside. it is a new setup there is not dhcp leases

## Possible Solution
If I can resolve the issue I would create a video on to do a fast setup in the virtual box where people can use it 

## Steps to Reproduce the Problem
Attached all the screenshots

## Context (Environment)
I am running the virtualbox in a skull canyon intel

## Specifications
I have 5 wan connections ( fiber,dsl,3 lte)

  - OpenMPTCProuter version: 0.54.7
  - OpenMPTCProuter VPS version: <!---not loaded yet
  - OpenMPTCProuter platform: <!--- (x86_64) intel skull canyon

Everything I have done in here with virtual machine image
https://drive.google.com/drive/folders/13GINYIwT2z8isNx6mNdgurzoe1Nbe1RM

**Comment by Ysurac** [comment]
How many interfaces did you set in virtualbox ?
Did you set interface as Server Intel PRO/1000 MT (82545EM) set to bridge with promiscous mode enabled ?

**Comment by rifaterdemsahin** [comment]
mate thanks for the ultrafast response . I did setup 5 interfaces
1 for internal network
1 host only network
3 for wan

**I have realized Missed the last letters on the nic type** / Intel PRO/1000 MT (82545EM) 
I moved from intel 82540 to 82545 now ( dont know why might be related to multi path tcp maybe )

Updated the scripts for the external card in the virtualbox with

> ` VBoxManage modifyvm "OpenMPTCP" --nic5 hostonly
VBoxManage modifyvm "OpenMPTCP" --nictype5 82545EM
VBoxManage modifyvm "OpenMPTCP" --hostonlyadapter5 enx000ec651112d
`

Still i am unable to access it.

**Comment by rifaterdemsahin** [comment]
I changed the network to 192.168.200.1

 i would revert that change. How can I debug OMR to see the issue?

![image](https://user-images.githubusercontent.com/5270036/87875418-f89e7d80-c9c8-11ea-8e16-a93e42ef024a.png)

**Comment by rifaterdemsahin** [comment]
I have decided to start from scratch and add the cards one by one. Would that help ?
![image](https://user-images.githubusercontent.com/5270036/87875471-4dda8f00-c9c9-11ea-9232-a67cd0adf556.png)

**Comment by rifaterdemsahin** [comment]
Maybe the internal network is causing the issue
![image](https://user-images.githubusercontent.com/5270036/87875536-b75a9d80-c9c9-11ea-8926-c23f267ea711.png)

**Comment by Ysurac** [comment]
On network adapter, the lan interface need to be attached to internal network if it's what you want.

**Comment by rifaterdemsahin** [comment]
I have created an internal network and i was expecting the client to see the server but that did not work.

I suspect it is related to hostonly adapter issue in virtualbox after the update i can only mention the network card on the cli and the UI throws the error

![image](https://user-images.githubusercontent.com/5270036/87875971-a8291f00-c9cc-11ea-89fe-940993feaf24.png)


If i want to bond like 600MBits with which hardware should i go for to have the least issues?

**Comment by rifaterdemsahin** [comment]
maybe today is not my day i am giving a break .
I found the thread here https://ltehacks.com/viewtopic.php?f=21&t=1078

Project looks promising. Keep up the great work and keep pedalling it would be great to be able to bond connections

**Comment by Ysurac** [comment]
I use virtualbox with internal network, one interface attached to internal network, others interfaces as bridge for a direct access to modem/box.

I don't have 600Mb/s to test speed for now, but I would say any x86_64 with AES hardware support will have no problem at all.

**Comment by rifaterdemsahin** [comment]
do you setup the host network adapter when you want to use the virtualbox as the router in the network ?
![image](https://user-images.githubusercontent.com/5270036/87876834-774be880-c9d2-11ea-9fda-67dff783dc33.png)

**Comment by Ysurac** [comment]
I don't use a host private network, only an internal network.

**Comment by rifaterdemsahin** [comment]
5 th time is the charm
![image](https://user-images.githubusercontent.com/5270036/87877969-4327f600-c9d9-11ea-95b9-97ab5c50ed29.png)


I have understood that if we do not setup correctly at the start the restart does not read the updated config.
So I created the machine from start and it worked ( that part needs to be updated i suppose as there can be hardware changes )
![image](https://user-images.githubusercontent.com/5270036/87878018-9306bd00-c9d9-11ea-9281-6b5295663460.png)

**Comment by Ysurac** [comment]
I don't know what you mean, the config can be updated.

**Comment by rifaterdemsahin** [comment]
I have tried many times with the original one. If I do not create the machine with 82545EM than i couldnt change and expect the router page to load. That was my case.
