### ISSUE TITLE
Some questions to mlvpn and DHCP

### ISSUE THREAD

**Issue by Jmmx1237** [Ysurac/openmptcprouter#1095]
Why is the mlvpn device automatically configured with DHCP, and where can i change the lease time, if this make sense? In the overview "status" the mlvpn is shown with the counting down lease time.

I disable DHCP on all devices, besides on the OMRVPN device, does the mlvpn establish the vpn connection over OMRVPN, i don't understand the purpose of OMRVPN.

And if the ISP connect to interface wan2 is down, i look at `uci/admin/system/openmptcprouter/status` and don't understand why wan2 Interface show me the WAN Ip of interface wan1, ok there is a warning "no ping..." but why there the same infos?

<a href="https://www.directupload.net" target="_blank"><img src="https://s12.directupload.net/images/200719/x7end8hy.jpg" title="Kostenlos Bilder und Fotos hochladen"></a>

Thanks a lot for the work on this projekt!

**Comment by ascomputer** [comment]
wan2 put it on a different network class example 192.168.0.x
