### ISSUE TITLE
Top Speeds with MpTCP

### ISSUE THREAD

**Issue by rifaterdemsahin** [Ysurac/openmptcprouter#1099]
## Expected Behavior
Aggregate all the bandwidth not reached
https://www.youtube.com/watch?v=5URNj8YexsY

## Current Behavior
Some form of aggregation is working

## Possible Solution
Have a panel on the dashboard to show active consumption of the bandwidth
I need to see if the VPS is the bottleneck.

## Steps to Reproduce the Problem

  Cloud Server at GCP
![image](https://user-images.githubusercontent.com/5270036/88488083-e1d8c780-cf82-11ea-9fd6-e99a991dfb5c.png)

5 Broadbands
1.Fiber Virgin FTTC ( 320 )
2.LTE Vodaphone ( 40 )
3.LTE Smarty ( 50 )
4.LTE Three ( 50 )
5.DSL Post Office  ( 10 )

Expected output 460 but getting 340
![image](https://user-images.githubusercontent.com/5270036/88488143-42680480-cf83-11ea-9352-152b9bba38cd.png)

## Context (Environment)
Running it on skull canyon intel with ESXI

## Specifications

  - OpenMPTCProuter version: Powered by openmptcprouter v0.54.7 r0+12509-04a21c26a0
  - OpenMPTCProuter VPS version:

**Comment by Adorfer** [comment]
please have look onto (cpu-) load and io-delay on the vps during testing (and make some tests e.g. via iperf3 (from a client-pc in lan and iperf3 hosted close to the your VPS), lasting for several mininutes, in order to get stable results.

**Comment by rifaterdemsahin** [comment]
Adorfer the KS for the update. I realized the VPS is in mountain view I should have selected London DC as I am in Cambridge uk.

Today wan2 stopped working. I have started getting errors
![Screenshot_20200727-074239](https://user-images.githubusercontent.com/5270036/88511989-b6cf9180-cfdd-11ea-8eec-f7d23eec3132.jpg)

**Comment by Ysurac** [comment]
wan2 gateway IP doesn't answer to ping. This can be a problem or not, some hardware block ICMP ping request.

**Comment by user747** [comment]
> io-delay on the vps during testing
what tool do you use for this

**Comment by rifaterdemsahin** [comment]
https://www.youtube.com/watch?v=5URNj8YexsY

Here is today.
I cant seem to see to utilise all the bandwidth

**Comment by Ysurac** [comment]
The VPN is used by default only for traffic that is not TCP. Enabling/disabling VPN should always be done via the wizard (else you can have more than one VPN enabled, and this can't work well).
Connection should also have low latency with the VPS if you want to get a good speed, it's not really the case here.

To optimize, you can try in Network->MPTCP to set scheduler to BLEST and Congestion control to Cubic, sometimes this help.

**Comment by rifaterdemsahin** [comment]
The VPN is used by default only for traffic that is not TCP.:: understood.I suspect 80 percent of traffic is TCP.

Enabling/disabling VPN should always be done via the wizard ::: ok

 Network->MPTCP to set scheduler to BLEST and Congestion control to Cubic, sometimes this help.

::; I will check this out. http://192.168.16.113/cgi-bin/luci/admin/network/mptcp


http://192.168.16.113/cgi-bin/luci/admin/services/iperf
this page displays 
Upload - Server: bouygues.iperf.fr - Sender: 316.61Mb/s - Receiver: 324.77Mb/s

But i do not see this in fast.com ^^^

**Comment by Ysurac** [comment]
Some test speed always give bad results. The best way to test is to download a file, on the router, via SSH, there is ```omr-test-speed``` (ctrl+c to stop test). It download a file from OVH.
I will add an internal speed test in OpenMPTCProuter in a next release.

**Comment by rifaterdemsahin** [comment]
Ysurac thanks for all the great work on this. If i add 3rd line would i improve due to the algorithm maybe 2 lines with mptcp is not the best. Is there a study on how many lines gives the best possible speed ?

**Comment by Ysurac** [comment]
The best is one line with max speed, but you can add up to 8 lines. Latency is important.

**Comment by rifaterdemsahin** [comment]
in the morning the speed was at 100 at night it goes to 400 ( using 2 lines)
![image](https://user-images.githubusercontent.com/5270036/88852806-b2c29000-d1e6-11ea-8bdc-56169fe8521b.png)

how do i debug the reason ?

**Comment by kevin39** [comment]
Hi,
Do not use fast.com.

As @Ysurac said, check your speed using CLI with `omr-test-speed`

While testing you can go to Network > MTCP > Bandwidth to Check which connections are used.

**Comment by rifaterdemsahin** [comment]
Kevin thanks for the response.

much better result on this page
http://192.168.16.113/cgi-bin/luci/admin/network/mptcp/bandwidth

![image](https://user-images.githubusercontent.com/5270036/88855131-4f3a6180-d1ea-11ea-8ef2-4f63af1641b8.png)

**Comment by Adorfer** [comment]
Just for reference: 
![grafik](https://user-images.githubusercontent.com/10302493/100488797-9b51d000-3110-11eb-95dd-ff0d24a3015f.png)

**Comment by TalalMash** [comment]
@rifaterdemsahin You can try Vulr hourly dedicated server to see if it's VPS processing bottleneck, no commitment or fixed pricing. I've only tested up to 300mbit.
