### ISSUE TITLE
The vps does not restarts after the refresh install on GCP

### ISSUE THREAD

**Issue by rifaterdemsahin** [Ysurac/openmptcprouter#1102]
## Expected Behavior
i should be able to connect.

this is what i get
![image](https://user-images.githubusercontent.com/5270036/88692028-82e78f80-d0f5-11ea-9db5-ac113c4b88fb.png)

## Specifications

  - OpenMPTCProuter VPS version: todays download....i cant locate the version not clear in the download and the log/

After the install developer should point the version number

  /!\ You need to reboot to enable MPTCP, shadowsocks, glorytun and shorewall /!\
------------------------------------------------------------------------------------
 After reboot, check with uname -a that the kernel name contain mptcp.
 Else, you may have to modify GRUB_DEFAULT in /etc/defaut/grub
====================================================================================

^^^ after this line

**Comment by rifaterdemsahin** [comment]
the vps is dead and i cant even ssh into it as well
![image](https://user-images.githubusercontent.com/5270036/88692307-d659dd80-d0f5-11ea-93f7-39e2c72e0c00.png)

**Comment by Ysurac** [comment]
Are you sure it is dead ? You seems to try to connect to it port 22, but after script install SSH is moved to port 65222 as said in documentation and at end of the script install.

**Comment by rifaterdemsahin** [comment]
Ysurac thanks for the fast response.

1. i should have opened the issue here https://github.com/Ysurac/openmptcprouter-vps
2.I did not read the documentation in that detail. (: lol i have killed 3 servers

**Comment by rifaterdemsahin** [comment]
now it started working that was my process all along
https://www.youtube.com/watch?v=FtgFZOplq0s&feature=youtu.be

Could be useful for someone who is more visual ^^^

**Comment by rifaterdemsahin** [comment]
this one is the part ( upload in progress) that i have solve  the connection issue

**Comment by Ysurac** [comment]
Videos seems to be marked as private ;)

**Comment by rifaterdemsahin** [comment]
i have unlisted them from private
![image](https://user-images.githubusercontent.com/5270036/88700563-c8f62080-d100-11ea-8e4a-dc4f1f5db07f.png)

this is the main video https://youtu.be/sVyzgs3HbCo
