### ISSUE TITLE
vpn server

### ISSUE THREAD

**Issue by wolfpcgr** [Ysurac/openmptcprouter#1104]
I would like to know if there is a way to create a vpn server for my network directly on the mptcp router and if so how do I do it. I would like to use open vpn if possible. 

## Specifications

  - OpenMPTCProuter version: < 0.54.7>
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter platform: <!x86_64 (RPI2/RPI3/x86/x86_64) -->

**Comment by Ysurac** [comment]
Yes it's possible using the web interface, create a new VPN and don't use tun0 as interface.

**Comment by tentious** [comment]
I also needed to accomplish this and also needed to route certain traffic through this VPN. To accomplish this, I added the domain to the OMR-Bypass with tun1 as interface, which worked to force the desired traffic through that VPN. Good luck!
