### ISSUE TITLE
Labels to be displayed in the bandwidths page

### ISSUE THREAD

**Issue by rifaterdemsahin** [Ysurac/openmptcprouter#1107]
it is confusing not having the labels to see the bandwidths
http://192.168.16.113/cgi-bin/luci/admin/network/mptcp/bandwidth
![image](https://user-images.githubusercontent.com/5270036/88958005-be21c400-d297-11ea-94b4-699464ed73ef.png)

Powered by openmptcprouter v0.54.7 r0+12509-04a21c26a0

**Comment by ascomputer** [comment]
it would be nice to have this screen on a 3.5 "display to see the single wan in real time :-)
