### ISSUE TITLE
kobo

### ISSUE THREAD

**Issue by philoun8** [Ysurac/openmptcprouter#1109]
Bonsoir a tous

est ce normal que certains sites ne sont pas accessibles, comme kobo.com? même apres avoir reglé dans Service / OMR-Bypass

![image](https://user-images.githubusercontent.com/56804198/88966895-55dddd00-d2ad-11ea-851d-4d8dfa010a3f.png)

**Comment by Ysurac** [comment]
Il faut plutôt mettre juste "kobo.com" dans les domaines à by-passer, ça permettra de bypasser aussi tous les sous-domaines (donc www. et autres). Pour certains sites d'autres domaines peuvent êtres à by-passer selon ce que donne les options développeur de ton navigateur web.

Quelques sites bloquent les IPs de la majorité des hébergeurs de VPS/dédié pour des raisons économiques/légales (par exemple netflix), suite à des abus (par exemple jeuxvideo.com) ou par incompétence des administrateurs (par exemple boulanger.com mais ça concerne pas mal de sites).

**Comment by philoun8** [comment]
netflix j'ai réussi a le contourner (pour le moment); juste de temps en temps un message comme quoi je possède un proxy!
par contre kobo, j'arrive a l'ouvrir un fois sur dix a peu près. ou alors je dérègle mes paramètres pc pour repasser en ip static sur le modem 4G

**Comment by Ysurac** [comment]
Pour kobo, en mettant juste "kobo.com" dans les domaines j'ai accès au site depuis un VPS scaleway.

**Comment by philoun8** [comment]
mon vps est chez ovh, je ne sais pas si ca change quelque chose!

**Comment by Ysurac** [comment]
Pas vraiment. Par contre il faut bien vérifier que le DNS utilisé sur l'ordinateur client est bien l'adresse IP d'OpenMPTCProuter.
Si l'adresse est en DHCP pas de soucis normalement.

**Comment by philoun8** [comment]
je viens de regarder boulanger.com et par contre chez moi aucun soucis

**Comment by Ysurac** [comment]
Ils bannissent pas toutes les plages d'IPs.
Pour que omr-bypass fonctionne il faut que la résolution du domaine se fasse en passant par OpenMPTCProuter, donc ça peut ne pas fonctionner juste après le changement du fait du cache DNS du navigateur.

**Comment by kevin39** [comment]
Il a laissé interface "Par défaut". Ca fait quoi l'option par défaut dans OMR Bypass ? 
J'ai tjrs sélectionné un WAN précis quand je l'ai pris...

**Comment by philoun8** [comment]
par défaut ca sélectionne toutes les interfaces

**Comment by philoun8** [comment]
par contre dans "Protocoles et services", je choisi qu'elle modem je veux selectionner.

![image](https://user-images.githubusercontent.com/56804198/88973703-d1dd2280-d2b7-11ea-8847-fe1eff9d511f.png)

**Comment by philoun8** [comment]
Bonjour
donc rapport ce matin, apres modif des parametres dns = les sites apparaissent bien.
merci
