### ISSUE TITLE
VPS Script install not complete

### ISSUE THREAD

**Issue by SoGooDFR** [Ysurac/openmptcprouter#111]
## Expected Behavior
Fresh Debian 9 install and execute : 
`wget -O - http://www.openmptcprouter.com/server/debian9-x86_64.sh | sh`
And after script we get : '/root/openmptcprouter_config.txt'

## Actual Behavior
No generate of /root/openmptcprouter_config.txt and not modify '/etc/motd'.
No changing default ssh port 22 to 65222.
Glorytun service isn't started.

Htop after script install and reboot:
![vps_script_htop](https://user-images.githubusercontent.com/8985130/43356130-57923148-926b-11e8-93b6-f785b3a173c0.png)

## Steps to Reproduce the Problem

  1. Fresh OS + OpenMPTCPRouter install on VPS.
  2. No generated files by script and no changing default ssh port.

## Specifications

  - OpenMPTCProuter VPS version: OpenMPTCProuter VPS 0.36.

**Comment by Ysurac** [comment]
I've no problem on updating but I will try on a new install

**Comment by PxxBxx** [comment]
BTW when upgrading, the script fails/stops when invoking : 
```
systemctl -q disable omr-6in4
```
I removed the line and was able to do the upgrade (I didn't have this service beforehand, I upgrades 0.37 to 0.37, in order to fetch the new shorewall conf)

**Comment by nicoz76** [comment]
same problem on a fresh install ( debian9 OVH ).

**Comment by nicoz76** [comment]
Good,   it's OK   after the install script now.
