### ISSUE TITLE
anonymize public ip's

### ISSUE THREAD

**Issue by philoun8** [Ysurac/openmptcprouter#1110]
Bonjour

je me demande a quoi sert la case a cocher "anonymyze public ip's" puisque meme cochée, mon ip visible reste celle de mon vps?

![image](https://user-images.githubusercontent.com/56804198/89018945-df78c380-d31c-11ea-9dc1-bffb8e527a84.png)

**Comment by Ysurac** [comment]
Elle permet de cacher les IPs dans la page status lors du prochain rafraîchissement.

**Comment by philoun8** [comment]
merci
