### ISSUE TITLE
proxmox

### ISSUE THREAD

**Issue by philoun8** [Ysurac/openmptcprouter#1111]
Bonjour

Est il possible de mettre openmptcprouter sur une VM ou CT proxmox? 
je possède un serveur proliant et j'ai test l'installation d'une image openmptcprouter wmvare mais je n'ai pas réussi a le faire fonctionner.

actuellement openmptcprouter tourne sur un raspberry pi 4b

![image](https://user-images.githubusercontent.com/56804198/89024412-5ade7300-d325-11ea-86f1-f3aece6f3065.png)

**Comment by Ysurac** [comment]
Oui ça fonctionne sous proxmox, à condition d'utiliser KVM et pas LXC.

**Comment by philoun8** [comment]
avec une image vmware?

**Comment by Ysurac** [comment]
Je sais que ça fonctionne avec une image raw, le reste je n'ai pas testé.

**Comment by Adorfer** [comment]
create a VM with a raw hdd (in the filesystem, not in ZFS etc)
you have to use an x64 images and unpack the "img.gz" file.
stop the vm (if started by accident), cp the unpacked image file over the /var/lib/vz/$id/$rawimagename. 
(you have to determine the $id from the VM number and the rawimage is the file you hopefully find exsting. Do not care about filesizes, just plain copy it over, the appropriate size will be detected by kvm during next start.

**Comment by faktori** [comment]
Bonjour,
Tu peux installer ubuntu 18.04 puis tu fait l'installation du script et voila :)

**Comment by philoun8** [comment]
Bonjour
de quel script tu parles Faktori?

**Comment by faktori** [comment]
Si vous avez choisi Debian :
wget -O - http://www.openmptcprouter.com/server/debian9-x86_64.sh | sh

Si vous avez choisi Ubuntu :
wget -O - http://www.openmptcprouter.com/server/ubuntu18.04-x86_64.sh | sh

**Comment by kevin39** [comment]
Non ne fais pas cela. C'est pour installer la partie serveur et non la partie routeur.
Si tu veux installer ton routeur dans une VM Proxmox, tu dois utiliser une VM (kvm).
Sois tu charge un disque raw sois tu convertis l'image ova/vmware. Ca devrait suffir.

Le wiki de Proxmox explique comment charger un disque ova/vmware.

**Comment by philoun8** [comment]
Bonjour

j'ai essayé avec un fichier kvm et en suivant les explications proxmox (de plusieurs façons) mais ca ne tourne pas normalement...

**Comment by faktori** [comment]
Ha oui je parle de la version serveur moi pas routeur 
Je pensais que tu parlais pour faire l'agregation 

désolé

**Comment by Adorfer** [comment]
o.k., we are now into the n-th loop of a) finding out out what the initial request was and b) explaining things which was not initally requested. 

@philoun8 for clairities sake: 
1) select a decent title! this is a bug report? a feature request? or (as i assume) a help/support request (you can still edit that)
2) please state what you try to do (setting up the routeur part in a proxmox vm or the server part in a proxmox vm?)
3) if it's not working please be specific with wout error message. _"does not turn"_ is not helpful. otherwise people will suggest: _"have you tried turning it off and on again?"_

**Comment by Eliasdevlb** [comment]
unpack the gz so you can have a .img file. Upload the image into proxmox using winscp or whatever you feel comfortable using. cd into the directory where you placed your file then use the following shell command (I am using openmptcprouter.img as the image name and I have vm id 101, please change accordingly)
qm importdisk 101 openmptcprouter.img local-lvm

**Comment by philoun8** [comment]
Merci beaucoup Eliasdevlb

**Comment by philoun8** [comment]
bonsoir a tous
j'ai repris mes investigations sur une vm proxmox en kvm et ca tourne nickel (enfin)…
par contre j'ai un soucis au niveau des carte physique reseau. je m'explique.
quand le serveur est démarré, je lance la vm openmptcprouter et je débranche mon raspberry qui contenait openmptcp jusqu'à maintenant. la vm prend la relève du rasp et tout fonctionne impeccable, même mieux qu'avec le rasp.
par contre si je reboot le serveur (proliant dl380gen6), la vm openmptcp prend le control de la carte physique et me bloque l'accès au webif et même ssh du serveur (qui est pourtant sur la même plage ip).
vu que le serveur a plusieurs cartes réseau j'ai donc attribuée une carte reseau juste a la vm openmptcprouter mais rien n'y fait!!!
si quelqu'un a une idée!!! merci

**Comment by Eliasdevlb** [comment]
You should set your boot order and boot delay. That should fix your issue.
