### ISSUE TITLE
Creation d'un wan3

### ISSUE THREAD

**Issue by faktori** [Ysurac/openmptcprouter#1113]
Bonjour,

Je test en ce moment le produit est le resultat sur 2 ADSL est parfait. J'ai réussi à mettre Netflix qui fonctionne 👍 
Par contre je voudrais rajouter un wan3 quand je le rajoute dans  Resau/interfaces et que je clique dans parametre physique je ne trouve pas comment créer l'interface physique Wan3

Je suis actuellement sur un Rasp PI 3B et un reseau local avec un switch 

Merci de votre aide

**Comment by Ysurac** [comment]
Pour créer un wan3 de type macvlan, le plus simple est de la faire via le wizard (Système->OpenMPTCProuter), en bas de la page basé sur eth0 (ça doit être le défaut).

**Comment by faktori** [comment]
Merci Ysurac mais le soucis j'ai testé me donne cela : ( voir photo ) je veux vraiment avoir 3 Wan alors que la , il pointe sur Lan et non un nouveau Wan(3)
<img width="1280" alt="wan3" src="https://user-images.githubusercontent.com/4162189/89118034-f47f5f00-d4a2-11ea-90d8-060533394eb4.png">

**Comment by faktori** [comment]
j ai mis deux connexions sur le meme wan cela fonctionne 👍

**Comment by Ysurac** [comment]
C'est pas une bonne idée. Il faut créer les macvlan via le wizard ou via Réseau->Macvlan (ça sera différent dans la prochaine version).
