### ISSUE TITLE
interface status

### ISSUE THREAD

**Issue by zulu14** [Ysurac/openmptcprouter#1114]
hello, my interface status no show graph , when i manyapy request the interface_status , the json output is absolutly not correct: 

the ouput are:     {"_":0}

do you have an idea ? (this is not a new instance, anything has been edited,

**Comment by Ysurac** [comment]
Please use the template and be more precise: which page ? Do you have any other working wan interface ?

**Comment by zulu14** [comment]
manual force the request http://192.168.100.1/cgi-bin/luci/admin/system/openmptcprouter/interfaces_status
the output was : {"_":0}

the theme are not changed, and he has any result obviously

**Comment by zulu14** [comment]
manual force the request http://192.168.100.1/cgi-bin/luci/admin/system/openmptcprouter/interfaces_status
the output was : {"_":0}

the theme are not changed, and he has any result
