### ISSUE TITLE
Connecting openmptcprouter without direct connection to the modem

### ISSUE THREAD

**Issue by rifaterdemsahin** [Ysurac/openmptcprouter#1116]
## Expected Behavior
I have a router in the middle which has 5 incoming connections.
Openmptcp machine has 2 network cards

## Current Behavior
I have added 5 virtual cards to the esxi mapping to one pyshical network card
![image](https://user-images.githubusercontent.com/5270036/89288715-02251800-d64e-11ea-8321-6ad957e4652e.png)

## Possible Solution
Is it possible to use the same network over the switch and let eth0 on the edge router to serve to omr that i can realize this is dedicated to one connection.

My rationale I need to fall back on the Edgerouter incase the OMR does not work. I am planning to add the OMR as a the main WAN port on the Edgerouter which consumes 5 connections over the edge router.

![image](https://user-images.githubusercontent.com/5270036/89289577-609ec600-d64f-11ea-9956-ed7e129e22cc.png)

**Comment by mehmetakifaksoy** [comment]
I am also interested to learn if that is possible

**Comment by Ysurac** [comment]
I don't understand exactly what you want, but if you want to have all connection on same switch then you need to have each modem/box in own subnet else you have to use vlan.
I don't understand what the edgerouter is made for in your configuration and how it can be used at fallback.

**Comment by Adorfer** [comment]
this sounds more like a question for a tutorial "How to virtualize network cards over vlan for VMs". 

In other words: No job for the openmptcprouter here: 
Everthing in terms of vlan tagging and vlan untagging sould be done in the hypervisor and the external vlan-switch.

**Comment by rifaterdemsahin** [comment]
`this sounds more like a question for a tutorial "How to virtualize network cards over vlan for VMs".
`
MAKES SENSE finally there is a usecase for vlans. if i can do it over the hypervisor that would be the dream come true,

https://kb.vmware.com/s/article/1004088
https://support.us.ovhcloud.com/hc/en-us/articles/360002411530-How-to-Deploy-VLANs-with-VMware-ESXi-6-5

**Comment by rifaterdemsahin** [comment]
![image](https://user-images.githubusercontent.com/5270036/89746453-93aee280-dab1-11ea-9275-0e9c176a44ec.png)


i neeed to find a way to attach a different vlan to each interface

**Comment by rifaterdemsahin** [comment]
late night could not sleep
![image](https://user-images.githubusercontent.com/5270036/89746615-965e0780-dab2-11ea-85ae-b512eb95ca8b.png)

**Comment by rifaterdemsahin** [comment]
Attached
![image](https://user-images.githubusercontent.com/5270036/89746629-a7a71400-dab2-11ea-9a23-6d5ce8a4c0d5.png)


![image](https://user-images.githubusercontent.com/5270036/89746653-c73e3c80-dab2-11ea-97ec-51b220554a79.png)

**Comment by rifaterdemsahin** [comment]
could not see the vlans in openmptcp
![image](https://user-images.githubusercontent.com/5270036/89746708-0ff5f580-dab3-11ea-89ff-6c63035c2ddf.png)
![Uploading image.png…]()

**Comment by rifaterdemsahin** [comment]
each one looks like a different card
![image](https://user-images.githubusercontent.com/5270036/89746872-e7bac680-dab3-11ea-97ae-a35eba399901.png)

**Comment by rifaterdemsahin** [comment]
Too tired After setting the Vlan IDs i cant login to the mptcp interface
![image](https://user-images.githubusercontent.com/5270036/89746938-41bb8c00-dab4-11ea-8f62-9b4c61471eee.png)

**Comment by rifaterdemsahin** [comment]
> and the external vlan-switch.
![image](https://user-images.githubusercontent.com/5270036/89747129-3157e100-dab5-11ea-923c-6d4f2ea0f411.png)

is this the external swith (the open openmptcp or are we talking about my layer 3 switch where i connect the cables for the router to the network

**Comment by rifaterdemsahin** [comment]
https://help.ui.com/hc/en-us/articles/360046144234-UniFi-Using-VLANs-with-UniFi-Switching#:~:text=VLANs%20can%20be%20used%20with,a%20network%20as%20VLAN%20only.

**Comment by rifaterdemsahin** [comment]
![image](https://user-images.githubusercontent.com/5270036/89747598-67966000-dab7-11ea-8a9f-5e8fd41bf08f.png)

**Comment by rifaterdemsahin** [comment]
still not sure if this is the way to go
![image](https://user-images.githubusercontent.com/5270036/89747629-898fe280-dab7-11ea-87f0-2d8bed17968d.png)

As how do i mention the vlan in openmptcp ?

**Comment by rifaterdemsahin** [comment]
![image](https://user-images.githubusercontent.com/5270036/89747723-edb2a680-dab7-11ea-9722-3e6249f8b1bf.png)

**Comment by rifaterdemsahin** [comment]
![image](https://user-images.githubusercontent.com/5270036/89747793-38342300-dab8-11ea-92e0-302b64618d2e.png)

**Comment by rifaterdemsahin** [comment]
![image](https://user-images.githubusercontent.com/5270036/89747832-60bc1d00-dab8-11ea-88e3-8fd7e52cd8bc.png)

**Comment by rifaterdemsahin** [comment]
now i cant login to openmptcp
![image](https://user-images.githubusercontent.com/5270036/89747887-aaa50300-dab8-11ea-9ce0-d42c61f2acfb.png)


![image](https://user-images.githubusercontent.com/5270036/89747917-cc05ef00-dab8-11ea-8c51-04392340de0d.png)

3.23 am i give up for today

**Comment by rifaterdemsahin** [comment]
I might need to tag the wan networks with vlans as well maybe but that is another question than me not being able to login to openmptcp

![image](https://user-images.githubusercontent.com/5270036/89748042-3b7bde80-dab9-11ea-81c4-1ccff8e2ddd0.png)

**Comment by Adorfer** [comment]
thanks for clarivication: 
You are looking for a _"how to virtualize network cards from an external VLAN switch into a VM"._ 

1) that is a generic concept which is not special to MPTCProuter
2) depending on the "detail level of howto" 
   -  that is totally specific for a hypervisor (kvm/proxmox is different than hyperv, is differnt than virtualbox etc
   -  that it totally specific for a given switch model/make

**Comment by Ysurac** [comment]
For the related OpenMPTCProuter part, I can only say, for hardware that doesn't have an internal switch, if you want a vlan, you need to use as physical interface, for example, eth0.3 to use vlan 3 of interface eth0.

**Comment by rifaterdemsahin** [comment]
`, if you want a vlan, you need to use as physical interface, for example, eth0.3 to use vlan 3 of interface eth0.`

thanks mate

**Comment by rifaterdemsahin** [comment]
I found this https://github.com/Ysurac/openmptcprouter/issues/168

I would try to edit /etc/config/network and /etc/init.d/network reload

Put added LAN interface in tagged port (id = 11)

config device 'LAN_VLAN42_dev'            
        option name 'LAN_VLAN42'          
        option type '8021q'         
        option ifname 'eth0'        
        option macaddr 'ce:20:fb:ad:90:ef'     
        option vid '11'

**Comment by Ysurac** [comment]
There is multiple way to add vlan. I gave the easier. In Network->Interfaces edit an interface and in physical settings you can set what you want.

**Comment by rifaterdemsahin** [comment]
i gave up working on my skull canyon the usb ethernet cards and ESXI is not stable so I am planning to buy
![image](https://user-images.githubusercontent.com/5270036/92244465-dd28fc80-eeba-11ea-8dfc-00cc40acfaac.png)

**Comment by rifaterdemsahin** [comment]
the cost is high if it does not work on this than it is a bummer
![image](https://user-images.githubusercontent.com/5270036/93526336-38350780-f92f-11ea-95e6-14da1eecafcd.png)

**Comment by Adorfer** [comment]
Can you please rephrase what this issue is actually about. 
In plus it would help to edit the title AND the first post of the issue. 
Just in order to get people on the right track, looking into this the first time.
