### ISSUE TITLE
Open question

### ISSUE THREAD

**Issue by Esysteme** [Ysurac/openmptcprouter#1117]
It's is possible to hosting website behind openmptcprouter ? 

Do you have any documentation on it ?

**Comment by Ysurac** [comment]
It's possible, you only need to forward port to host: https://github.com/Ysurac/openmptcprouter/wiki/Port-forwarding
Hosting on OpenMPTCProuter hardware can be made, but not a great idea.

**Comment by Esysteme** [comment]
thx

**Comment by Esysteme** [comment]
(just realiszed that i have to close )
