### ISSUE TITLE
Bypass all traffic from dedicated client(s)

### ISSUE THREAD

**Issue by PxxBxx** [Ysurac/openmptcprouter#112]
## Expected Behavior

_(not an issue, maybe an improvement/enhancement)_

I would like to dedicate some clients (eg. a chromecast, a mediacenter with netflix/prime/SVOD, ...) to bypass OMR functionnalities.
It could be done in specifying the MAC and/or IP of the client, and the interface/wan to use for the bypass.
All protocols from these client(s) should use the specified interface/wan.

## Actual Behavior

I have to specify each domain(s)/protocol(s) in OMR-Bypass, it's really hard to maintain with Netflix/Prime/... domains

I also tried (without success) to set specific DHCP leases in 192.168.1.0/24, but DHCP server is in 192.168.100.0/24 range, it should have worked (or not, it's tricky)
```
config host
	option name 'myMediaCenter'
	option dns '1'
	option ip '192.168.1.228'
	option gw '192.168.1.1'
	option leasetime '24h'
	option mac 'c4:86:e9:c6:da:25'
```

## Steps to Reproduce the Problem

(not a problem)

## Specifications

  - OpenMPTCProuter version: 0.29.1
  - OpenMPTCProuter VPS version: 0.39
  - OpenMPTCProuter platform: RPI3

**Comment by PxxBxx** [comment]
@Ysurac maybe this idea can be added in the current enhancement #93 ?

**Comment by PxxBxx** [comment]
Netflix protocol wasn't enough (without domain/IPs)
I tried adding all 106 IP subnets, but maybe the syntax wasn't good, because it didn't work, and UI was broken in OMR-Bypass page.
(eg. 23.246.0.0/18 as in https://bgp.he.net/AS2906#_prefixes)

But I just managed to do it this morning, including Webex(CiscoSpark), it seems to work, but it was pretty slow (maybe my wan...)

![image](https://user-images.githubusercontent.com/6170432/43385224-7168714c-93e0-11e8-8a24-2bb509af979d.png)

**Comment by fnoir** [comment]
Can you add more protocol / games ?

For exemple: Fortnite, PUBG, Overwatch, Ubisoft, Plex, Telegram...

**Comment by Ysurac** [comment]
Telegram is already available. Else I will add protocol/games when they are added to https://github.com/ntop/nDPI that is used here.

**Comment by Maudissure** [comment]
Plex is fully functionnal with OMR solution, no need to bypass.

**Comment by Ysurac** [comment]
Rules use DNS, so if your machine have DNS cache it's not immediately.
No idea for the stop working. All logs are in system log tab.

**Comment by KoRnEr007** [comment]
Have you got news about games for OMR-Bypass like Fortnite ?
Thanks

**Comment by Ysurac** [comment]
Only games supported by https://github.com/ntop/nDPI can be added.

**Comment by MrDaweb** [comment]
Depuis ce matin Netflix ne veut plus chez moi, je viens d'activer comme indiqué le OMR-Bypass, protocle Netflix et tous les domaines netflix indiqués au dessus, vidé le cache, redemarré l'OTB... Sans succès pour le moment. On va voir si cela vient plus tard... Obligé de passer manuellement mon pc sur une des passerelles pour que ca marche directement.

**Comment by MrDaweb** [comment]
Pour info, ca ne marche toujours pas ce matin en lecture en streaming. Par contre je peux lancer les téléchargement sur l'appli netflix W10, et les lire :D Bon on va contourner comme ça en attendant de trouver une solution ^^
