### ISSUE TITLE
Question - quota per user

### ISSUE THREAD

**Issue by stenkodo** [Ysurac/openmptcprouter#1122]
Hello,

Is there any way to create bandwidth quota per connected device ?
Is it being considered ?

Best regards

Thank's for openmptcprouter project !

**Comment by Ysurac** [comment]
Not supported for now.
It's not on todo list, can be added if needed by many users.

**Comment by gnosoz** [comment]
This feature is already there and you can just install luci-app-nft-qos,
luci-app-qos and trafficshaper
