### ISSUE TITLE
interface status BIS

### ISSUE THREAD

**Issue by zulu14** [Ysurac/openmptcprouter#1125]
hello,
why you close the last ticket,
after investigate, has found the ubus request for openmptcprouter data as no specify a timeout and the default timeout is to low to accept the wait for check when he has 8 modem and 2 vps, 

i think we need to edit the function interfaces_status to increase the timeout in the local mArray = ut.ubus("openmptcprouter", "status", {})

**Comment by Ysurac** [comment]
Because template is not used and you don't answer when I ask info. So same problem here. I can't help if I don't know version, arch,...
