### ISSUE TITLE
How to setup WIFI AP on linksys 3200

### ISSUE THREAD

**Issue by Corrado56** [Ysurac/openmptcprouter#1135]
## Expected Behavior
This is not an issue, it's an help request.

I am trying to define a WIFI AP on a linksys 3200 

## Current Behavior
I have activated the radio signal and associated to a Custom SSID. 
I succesfully connect to the Wifi, BUT "Internet not available".
![image](https://user-images.githubusercontent.com/10588158/90019673-0d5fef80-dcaf-11ea-97b2-c6c7f6f48315.png)

I have no idea how an interface should be created to associate the WIFI signal to the LAN side of the switch.

Please note that I had successful created a Client DHCP interface to add a phone on WAN side, this is not the problem I have now.

## Specifications

  - OpenMPTCProuter version: 0.55
  - OpenMPTCProuter VPS version:  Debian 10 mptcp 0.1017
  - OpenMPTCProuter platform: Linksys

**Comment by Ysurac** [comment]
The doc for RPI may help: https://github.com/Ysurac/openmptcprouter/wiki/Configure-Wifi
Else I will try to do a doc for WRT ;)

**Comment by Corrado56** [comment]
Hi Yannik, 
I made a lot of test following RPI documentation but without success. 
I defined the wifi_ap interface as static address with an ip 192.168.100.2 gateway 192.168.100.1 (the lan IP), **DHCP enabled**.
I was able to connect to the wifi, but the wifi interface of the local computer (the client) never received a valid IP from MPTCPRouter
![image](https://user-images.githubusercontent.com/10588158/90039845-7f443300-dcc7-11ea-92d7-82ee7403d425.png)
--
![image](https://user-images.githubusercontent.com/10588158/90039976-aac71d80-dcc7-11ea-8e6a-83d0bf5e2879.png)

**Comment by Ysurac** [comment]
If you set a static IP it's working ?

**Comment by Corrado56** [comment]
No
I tested both gateway 192.168.100.1 and .2
![image](https://user-images.githubusercontent.com/10588158/90042132-8caeec80-dcca-11ea-8fa5-b45a8e758153.png)

**Comment by Ysurac** [comment]
By following the RPI wifi guide I have a working AP on WRT3200ACM.
I think the problem is related to your wifi_ap interface configuration.

**Comment by Rwestrem** [comment]
I had to delete and then re add the ssid's from each radio in order to get an IP from wifi.  Wifi seems to drop data a lot though even after this fix.  It will stay connected but show no internet available then comes and goes.

**Comment by Corrado56** [comment]
Fixed with Rwestrem suggestion. (Thanks)
Deleting all the default SSID's, then recreating ex novo. 
And now I receive an IP from DHCP (!) and navigate

**Comment by Rwestrem** [comment]
> Fixed with Rwestrem suggestion. (Thanks)
> Deleting all the default SSID's, then recreating ex novo.
> And now I receive an IP from DHCP (!) and navigate

Is your wifi stable?  Mine was unstable so I used an AP instead.  If yours is stable I may investigate my setup.

**Comment by Corrado56** [comment]
It's actually stable, with the problem of issue #1152
