### ISSUE TITLE
Wifi as wan

### ISSUE THREAD

**Issue by Rwestrem** [Ysurac/openmptcprouter#1139]
## Expected Behavior
I would like to have my wan3 on openMPTCP Linksys wrt3200 wifi tether to my phone hotspot.  This is normally simple to do with just scanning the wifi and joining and creating a wwan.  Im not sure how the correct procedure to do this would be.

## Current Behavior

when joining a wifi network as wan it just creates a new wwan outside of the wizard.

**Comment by Rwestrem** [comment]
I figured it out.

**Comment by Adorfer** [comment]
Could you perhaps give a hint where to improve the documentation?
In order to prevent other people to trip over the same difficulty.

**Comment by Rwestrem** [comment]
> Could you perhaps give a hint where to improve the documentation?
> In order to prevent other people to trip over the same difficulty.

It was very simple.  I was just unfamiliar with the way to do it.  I didn't realize there was a way to just enable it in network/mptcp.
