### ISSUE TITLE
VPN Tunnel down

### ISSUE THREAD

**Issue by Maudissure** [Ysurac/openmptcprouter#114]
## Expected Behavior
VPN connection OK

## Actual Behavior
VPN tunnel down
SSH connexion down

## Steps to Reproduce the Problem
L'ensemble de l'installation VPS et routeur OK.

Connexion internet OK à partir des deux modem.

Message : VPN Tunnel down.
Impossible d'accéder ensuite au VPS via putty : connexion refusée (ok en direct hors routeur).

## Specifications

  - OpenMPTCProuter version: V0.29
  - OpenMPTCProuter VPS version: V0.39
  - OpenMPTCProuter platform: RPI3B+

**Comment by SoGooDFR** [comment]
Same for me, problem solved from lastest OpenMPTCProuter release : https://www.openmptcprouter.com/release/targets/

**Comment by Maudissure** [comment]
Après mise à jour en 0.29.1, même problème.

Je m’aperçois aussi que sur un test de débit, seul la connexion WAN2 (4G) est utilisée.

WAN1 : Maitre
WAN2 : Active

**Comment by Ysurac** [comment]
Quel est le VPN utilisé ? Il peut être nécessaire de le relancer sur le VPS.
La connection avec le RTT le plus faible est utilisée prioritairement par défaut.

**Comment by Ysurac** [comment]
Pour archive:
OpenVZ ne permet pas le changement de noyau donc MPTCP ne peut pas fonctionner.
GloryTun nécessite TUN, certainement désactivé dans le cas présent.
For archive:
OpenVZ doesn't permit kernel change, so no MPTCP support.
GloryTun need TUN support, was not activated.
