### ISSUE TITLE
DHCP over WiFi dosn't work on WRT32x @ v0.55 r0+14022-18b7d87a8f

### ISSUE THREAD

**Issue by Quark-Fusion** [Ysurac/openmptcprouter#1143]
DHCP work over LAN, but on WiFi it doesn't
Tested after resetting to defaults

**Comment by Ysurac** [comment]
DHCP work over wifi if it's enabled in Network->Interfaces then edit the interface and in "DHCP server" tab. You can follow RPI wifi doc, it's the same: https://github.com/Ysurac/openmptcprouter/wiki/Configure-Wifi

Please use template next time.

**Comment by Quark-Fusion** [comment]
bridge was not created for default wifi networks, although wifi is attached to lan in ui, for correct configuration default networks (openwrt) should be deleted and new created
