### ISSUE TITLE
ipv6 enabled in openmptcprouter but not working in wan

### ISSUE THREAD

**Issue by xillibit** [Ysurac/openmptcprouter#1147]
## Expected Behavior
ipv6 should work

## Current Behavior
In openmptcprouter ~0.55~ ~0.55.3~ 0.56.5 i have enabled ipv6, i have no errors displayed in the system state. But when checking ipv6 with https://ip.lafibre.info/ it said that it's not working : 

![image](https://user-images.githubusercontent.com/876395/90310283-6ec2d100-def0-11ea-91f0-3a79b5ed3ed1.png)

The system state : 

![image](https://user-images.githubusercontent.com/876395/90310301-8f8b2680-def0-11ea-81b7-ea1a3f3ce54b.png)

## Steps to Reproduce the Problem

  1. Enable ipv6 in LAN2 with is the LAN where computer are present and enable too ipv6 in wizard

## Specifications

  - OpenMPTCProuter version: ~0.55~ ~0.55.3~ 0.56.5
  - OpenMPTCProuter VPS version: ~0.1017~ 0.1022
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
Do you have an IPv6 on your client computer ?

**Comment by xillibit** [comment]
I have that on my computer on the LAN, so yes it has an ipv6 : 

![image](https://user-images.githubusercontent.com/876395/90312402-886e1380-df04-11ea-9457-952e210ed303.png)

**Comment by Ysurac** [comment]
No, it's should have an IP in fdxx range.
There is an issue in IPv6 RA, but I don't know which and I'm not able to reproduce it for now.

**Comment by xillibit** [comment]
What is IPv6 RA ?

I have just looked into interfaces, it seems to be reversed. The IPv6 with prefix fdxx is affected to LAN but it should be on LAN2, the LAN2 has the computers and the LAN has just the SFR box and the huawei B715-23c : 

![image](https://user-images.githubusercontent.com/876395/90313996-c7a26180-df10-11ea-8c57-a4f240fae312.png)

**Comment by Ysurac** [comment]
IPv6 RA = IPv6 Router Advertisements. The router send to everything that is connected the prefix and route.
But in your case, you need to configure IPv6 on LAN2 in General settings tab.

**Comment by xillibit** [comment]
For LAN2 this is the settings : 

![image](https://user-images.githubusercontent.com/876395/90314874-54501e00-df17-11ea-857e-01512dd6552f.png)

and : 

![image](https://user-images.githubusercontent.com/876395/90314878-5c0fc280-df17-11ea-9ead-af0fa1cea763.png)

For LAN it has IPv6 disabled and DHCP server disabled for IPv4 and IPv6 : 

![image](https://user-images.githubusercontent.com/876395/90314888-75187380-df17-11ea-9dd6-1c6a2e035ffe.png)

and : 

![image](https://user-images.githubusercontent.com/876395/90314893-7b0e5480-df17-11ea-8d44-ce3989e98d75.png)

**Comment by Ysurac** [comment]
As LAN2 as no IPv6 configured, this must be set in General settings tab (_Paramètres généraux_).

**Comment by xillibit** [comment]
I have configured like that : 

![image](https://user-images.githubusercontent.com/876395/90316524-0b9e6200-df23-11ea-9a9d-51b27e6383e0.png)

The computer on lan after renew the dhcp, it still get a fexx IPv6 : 

![image](https://user-images.githubusercontent.com/876395/90316552-34265c00-df23-11ea-85a8-a080a7230f66.png)

**Comment by Ysurac** [comment]
fe80 will always be here, it's available when IPv6 is enabled: it's a link local address.
fdxx are unique local address, used for a private IPv6 network.

You can try to set a IPv6 routed prefix, or disabling "builtin IPv6-management" and copy exactly LAN IPv6 config should work.

**Comment by Adorfer** [comment]
settings look right on the lan2. 
(it's actually really the same which i run here on my OMR system, despite it's LAN instead of LAN2)
![grafik](https://user-images.githubusercontent.com/10302493/90327618-a9327980-df95-11ea-82ea-5ccccef920a0.png)

due to some reason, your windows machine does not learn the prefix. 

please do this on your OMR (you have to replace "eth0" by the physical IF you are using for LAN2. 
(In case tcpdump is not installed, do a _"opkg update; opkg install tcpdump"_, i am not sure if it's included in the default distro)

`tcpdump -vvvv -ttt -i eth0 icmp6 and 'ip6[40] = 134' `

it should give after some 5-10 minutes(!) results like this, where you see the prefix you defined plus as well the name of the OMR defined in the setup (per default: "openmptcprouter")

![grafik](https://user-images.githubusercontent.com/10302493/90328694-aee08d00-df9e-11ea-9106-477880b4c7c1.png)

**Comment by xillibit** [comment]
By the way i have updated to 0.55.1. I'am don't know enough on IPv6 to be sure about IP set on each LAN

I don't know if it's related but the dhcp in IPv6 hasn't given an IPv6 : 

![image](https://user-images.githubusercontent.com/876395/90415433-5e0d8900-e0b1-11ea-96c3-af3f82a80f74.png)


> tcpdump -vvvv -ttt -i eth0 icmp6 and 'ip6[40] = 134'

It's eth1 the physical interface, so i have tried it but it has stopped by iteslf : 

![image](https://user-images.githubusercontent.com/876395/90415053-db84c980-e0b0-11ea-8433-37f471e929f4.png)

**Comment by Adorfer** [comment]
for note: On 0.55.2 i had to put "enable-ra" in the /etc/dnsmasq.conf to have working ipv6 router for windows-lan clients. 
(did not investigate further)

**Comment by Ysurac** [comment]
By default odhcpd is used for RA and DHCPv6, it's why it's not enabled in dnsmasq.

**Comment by Adorfer** [comment]
ok then, the odhcpd did not work on my setup.

**Comment by Ysurac** [comment]
I tested with a windows 10 image and I get an IPv6, so the client OS doesn't seems to be the problem.
Can you give me the result of ```uci show dhcp``` via SSH on the router of not working config ?

**Comment by Adorfer** [comment]
the full stuff is several hundred lines, but i guess we are looking for the odhcpd? 
in this case the "maindhcp=0" looks a bit strange for me. 

```
dhcp.odhcpd=odhcpd
dhcp.odhcpd.maindhcp='0'
dhcp.odhcpd.leasefile='/tmp/hosts/odhcpd'
dhcp.odhcpd.leasetrigger='/usr/sbin/odhcpd-update'
dhcp.odhcpd.loglevel='4'

```

**Comment by Ysurac** [comment]
I need also "dhcp.lan" entry.

**Comment by Adorfer** [comment]
```
dhcp.lan=dhcp
dhcp.lan.interface='lan'
dhcp.lan.start='100'
dhcp.lan.limit='150'
dhcp.lan.force='1'
dhcp.lan.ra_slaac='1'
dhcp.lan.ra_flags='managed-config' 'other-config'
dhcp.lan.ra_preference='high'
dhcp.lan.leasetime='17220'
dhcp.lan.dns='fd00:2283:524d::1'

```

**Comment by Ysurac** [comment]
In this config, "Router Advertisement-Service" is not set to "Server mode" in Network->interface->LAN, DHCP Server tab and IPv6 settings tab.

**Comment by xillibit** [comment]
> I tested with a windows 10 image and I get an IPv6, so the client OS doesn't seems to be the problem.
> Can you give me the result of `uci show dhcp` via SSH on the router of not working config ?

![image](https://user-images.githubusercontent.com/876395/93000583-a9d51600-f529-11ea-81d2-99e72d3ffbe1.png)

**Comment by xillibit** [comment]
I'am now on 0.57.3, my VPS is on scaleway it has an IPv6 :

![image](https://user-images.githubusercontent.com/876395/108599492-b63f8380-7391-11eb-822d-fd91f924eb81.png)


Can-i should use it under wizard in IPv6 Prefix ?

![image](https://user-images.githubusercontent.com/876395/108599451-81333100-7391-11eb-84a9-8facdc0380c4.png)

**Comment by Adorfer** [comment]
> But still not working :

windows will by default NOT use ipv6 if the networkrange is from the ULA-"fd..."-space. 

change the local range to a different block: 
https://openwrt.org/docs/guide-user/network/ipv6/ipv6.nat6#network

```

# Configure network
uci set network.globals.ula_prefix="$(uci get network.globals.ula_prefix | sed -e "s/^./d/")"
uci commit network
/etc/init.d/network restart
```

**Comment by xillibit** [comment]
I have applied the commands, after an `ipconfig /renew` i'am still with fd something 👍 

![image](https://user-images.githubusercontent.com/876395/108621569-b4c69780-7433-11eb-85dd-47265be599ce.png)

But now ipv6 is working : 

![image](https://user-images.githubusercontent.com/876395/108621610-e7709000-7433-11eb-8d85-de585d329ddc.png)

**Comment by xillibit** [comment]
I have time to time the IPv4 offline but i don't know why

**Comment by Adorfer** [comment]
can you a) please update the the issue name ("not working in wan" sounds misleading, since the OMR will not use ipv6 on any wan)
b) if you have ipv4 issues: please open a new issue, describing the problem, using the template.
