### ISSUE TITLE
Grub2 isnt autobooting to debian buster

### ISSUE THREAD

**Issue by Rwestrem** [Ysurac/openmptcprouter#1148]
## Expected Behavior

I have installed a fresh debian buster 10 and openmptc on a personal dedicated server which is a studio 1745 dell that will be at a remote location.  It should automatically boot into debian after reboot 
## Current Behavior

Instead of booting into debian it hangs on grub waiting for me to select debian.  I've tried many different settings in the grub files but no matter what it has to be manually hit.
## Possible Solution

I know this isn't a openmptc issue exactly but maybe someone had a solution. I wouldn't be opposed to running openmptcp vps on something like a pi4 instead if that is know to work better for this
## Steps to Reproduce the Problem

  1. 
  2.
  3.

## Specifications

  - OpenMPTCProuter version: 
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter platform:

**Comment by Ysurac** [comment]
On debian, grub2 configuration is in ```/etc/default/grub```.
OpenMPTCProuter can only work on x86_64, it should boot on the needed kernel automatically after reboot but as it's a custom install I can't test :)
