### ISSUE TITLE
FTP Port forwarding not working

### ISSUE THREAD

**Issue by Corrado56** [Ysurac/openmptcprouter#1151]
## Expected Behavior
I Expect when I connect VPS Public IP port 21, to redirect the call to a FTP server in the Lan side of the router 

## Current Behavior
After setting the port forwarding rule, something happen and a connection is made to the FTP server.
But the FTP server reports as the source of the connection the Wan master connection IP, instead of the VPS public ip.
And the connection then closes.

## Possible Solution
No idea.
No idea if this problem is related to port 21 and FTP, or is general from Port forwarding

## Steps to Reproduce the Problem
This is the configuration I have:
![image](https://user-images.githubusercontent.com/10588158/90344074-8ac09280-e016-11ea-926b-5038e0a29a5a.png)

  1. set the following port forward rule
![image](https://user-images.githubusercontent.com/10588158/90344100-b93e6d80-e016-11ea-9e27-73a584ff3d13.png)

  2. Connect FTP plain text. VPS public IP, port 21
![image](https://user-images.githubusercontent.com/10588158/90344169-4ed9fd00-e017-11ea-91dd-5c0d604e95c1.png)

  3. The FTP server reports Master Wan IP as the source, instead of the expected VPS IP
![image](https://user-images.githubusercontent.com/10588158/90344208-c576fa80-e017-11ea-830a-9d84eb20f628.png)
same result testing from FTP client
![image](https://user-images.githubusercontent.com/10588158/90344217-d9baf780-e017-11ea-8597-e76a2c6881da.png)

## Context (Environment)
I need to redirect connections from VPS Public IP to Lan computers / Printers

## Specifications

  - OpenMPTCProuter version:  0.55
  - OpenMPTCProuter VPS version: <0.1017
  - OpenMPTCProuter platform:  Linksys 3200

**Comment by Ysurac** [comment]
Did you try to add a SNAT rule ? Like this: https://github.com/Ysurac/openmptcprouter/wiki/Port-forwarding

**Comment by Corrado56** [comment]
Added this NAT rule
![image](https://user-images.githubusercontent.com/10588158/90395495-ee89a080-e094-11ea-8b1c-fcd89271a312.png)

No changes
![image](https://user-images.githubusercontent.com/10588158/90395555-0103da00-e095-11ea-947f-074871a090e2.png)

**Comment by Corrado56** [comment]
Added this NAT rule
![image](https://user-images.githubusercontent.com/10588158/90395643-255fb680-e095-11ea-8091-d141a546b6a8.png)

Nothing changes
![image](https://user-images.githubusercontent.com/10588158/90395727-46c0a280-e095-11ea-855c-0261c019f5af.png)

**Comment by Ysurac** [comment]
Strange. I don't know how it can get WAN IP, redirected traffic use OpenMPTCProuter VPN only.

**Comment by Corrado56** [comment]
Hi Yannick, I make more test and i suspect we have a problem with the outgoing traffic, not the incoming.
This is the full picture.
![image](https://user-images.githubusercontent.com/10588158/90498046-1e45b080-e148-11ea-9325-77df5e7b4dbd.png)
I am working on MY PC where a FTP client is installed.
When I contact a remote FTP server 188.14.xxx.xxx my PC present itself with the VPS ip address 195.231.xxx.xxx (correct)
![image](https://user-images.githubusercontent.com/10588158/90498573-ca879700-e148-11ea-8d4e-07b7b261fd8f.png)
When I contact FTP server 195.231.xxx.xxx (the VPS address) my PC present itself with the master WAN address (wrong), and i receive some connections error.
![image](https://user-images.githubusercontent.com/10588158/90499170-81841280-e149-11ea-837a-add2e29d7606.png)
**BUT**
If I contact FTP server 195.231.xxx.xxx (the VPS address) from a remote FTP client, I have no errors and could connect the nas1 without any problem, so incoming traffic is correctly forwarded to the NAS1.
So it seems that something is wrong when the FTP client is under the bonding. At this point I am not sure the outbound traffic ever reached the VPS IP, but I am not technical enough to evaluate this Hypothesis.

**Comment by Corrado56** [comment]
Hi Yannick, any news on this problem ? 
My FTP forwarding is actually stable and works well **>>  when the call arrives from internet <<**
But
I suppose the red box above should be treated ad a "black" box so any call from 192.168.100.xxx should exit from the VPS IP, then eventually reenter. I doesn't understand why the FTP server receive the master connection IP in this case.

**Comment by Ysurac** [comment]
VPS IP is bypassed, so when you want to reach VPS IP you use direct master WAN, this doesn't use the proxy/VPN.
I think a SNAT is needed on VPS side ;)
