### ISSUE TITLE
Problem of perf

### ISSUE THREAD

**Issue by vinceducat** [Ysurac/openmptcprouter#1158]
## Expected Behavior
have aggregation flow rate egal to sum of each flow  275 mb/s
[https://pic.nperf.com/r/3272421640973452-gjN3eSVk.png](url)
## Current Behavior
rate only half of the sum 77 mb/s
[https://pic.nperf.com/r/3272422147777817-zJoPjkvV.png](url)
## Possible Solution
want to have opinion about perf

## Context (Environment)

  - OpenMPTCProuter version: 0.55.1
  - OpenMPTCProuter VPS version: 0.1017
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
How many connections do you have ? what is the speed of each connection ? Did you test with ```omr-test-speed``` and ```omr-test-speed wan1``` via SSH on the router ?
And what is the platform ? What is the VPS ?

**Comment by vinceducat** [comment]
x86_64 for platform

I have 2 connection 
_ adsl wan 1 direct speed without pass  trought vps 1000k/s
_ 4g wan 2 direct test without pass  trought vps 350mb/s

test trought vps ans omr-test-speed
omr-test-speed  10M
omr-test-speed wan 2 1800k => strange :-(

**Comment by Ysurac** [comment]
So you seems to have a problem with wan2. omr-test-speed only download a file from OVH, directly when an interface is specified.
It's a dedicated ethernet card with an ethernet router or an USB LTE dongle ?

**Comment by vinceducat** [comment]
its dedicated ethernet card with internet router huawei b825 in ethernet

**Comment by Ysurac** [comment]
Check cables, try to plug it on wan1,...
Check kernel and system log of OpenMPTCProuter in state menu, maybe a problem with this connection is detected.

**Comment by vinceducat** [comment]
its not a problem of cable.. all test are made trought the same hardware, the only difference is passing throught or not the vps... but allways test pass trought OMR ...

it seems than my VPS is 100% load on the two vCPU in the milkywan perf1 vps... i ever change from bidouille to perf1 ... no more best perff :-(

**Comment by Ysurac** [comment]
With ```omr-test-speed wan2``` this doesn't use the VPS at all.
For the CPU load, check that AES is disabled on advanced checkbox in the OpenMPTCProuter wizard, milkywan VPS doesn't seems to support AES.
You can also disable encryption for testing at least.
And with htop (```apt-get install htop```) on the VPS you can check CPU load and what is using it.

**Comment by vinceducat** [comment]
i have chacha20 in the in the encryption.... must i disable it ?

**Comment by Ysurac** [comment]
To test if it's encryption that use all the CPU and so make everything slow: yes

**Comment by vinceducat** [comment]
does i have to reboot beetween each change ?

**Comment by Ysurac** [comment]
No, only validate the wizard.

**Comment by Ysurac** [comment]
So about 8Mb/s and 27Mb/s when encryption is disabled. Still not really good. And still high CPU usage.
Did you try with htop to check what is using so much CPU ?
What is the load on the VPS when it is idle ?

**Comment by vinceducat** [comment]
idle 2/5% ...

during omr-test-speed on the vps the first process loading cpu is ss-manager ... shadowsocks...

**Comment by vinceducat** [comment]
yes its ss-server...

Hugues from milkywan just now give me a vps which support aes-ni what was the best encryption type. ?

resultat of rate are really better :-)

**Comment by Ysurac** [comment]
Yes, I asked to him why AES was not activated and he moved your VPS on a host with AES.
Check in the wizard that AES-256-GCM is really used.
Rate shouldn't improve as encryption was disabled, but host CPU can be better too :)

**Comment by vinceducat** [comment]
thanks ;-)

aes-256-gcm enable in the wizard ;-)

**Comment by vinceducat** [comment]
@Ysurac  no idea about this difference ?

**Comment by Ysurac** [comment]
Difficult to compare vCPU, some can have more dedicated ressources...

**Comment by rifaterdemsahin** [comment]
I gave up the VGPUs last month and i will go for i5 with enough ram and nvme

Rationale : routers should be easy reset start stop...

my planned purchase
https://www.amazon.co.uk/gp/product/B076B6SWG5/ref=as_li_qf_asin_il_tl?ie=UTF8&tag=rifaterdemsah-21&creative=6738&linkCode=as2&creativeASIN=B076B6SWG5&linkId=7eb4dbb17a7cbf769408adc483f40887
