### ISSUE TITLE
unable to update port forward

### ISSUE THREAD

**Issue by zulu14** [Ysurac/openmptcprouter#1159]
hello, this issues is for all openmptcprouter version and vps tested, 
hardware rpi4

the port worward into the VPN to LAN now working alwas, sometimes its works , sometimes its not works, restart the vps or omr not solve the problem, the only things  into the syslog is "orm-vps: Remove old firewall rules"

**Comment by zulu14** [comment]
(all of the omr statuts are green)

**Comment by zulu14** [comment]
(the direct all port of vps to omr are activated)
(the disable of the port already into the firewall are desactivated)

thank you for your helping and aweseome software

**Comment by zulu14** [comment]
update: (sorry for the multiple post)
on bot the vps screen show " failed to start shorewall ipv4 firewall"

**Comment by zulu14** [comment]
![image](https://user-images.githubusercontent.com/11999989/90698967-5ea94980-e282-11ea-9ed3-342f5ad83fd8.png)

**Comment by zulu14** [comment]
![image](https://user-images.githubusercontent.com/11999989/90699185-ea22da80-e282-11ea-957f-c1a74dd633ec.png)

**Comment by zulu14** [comment]
i fixed the issues, when the ICMP protocol are select the shorewall not start (screen above) we need to unselect icmp on port forward to enable the shorewall

**Comment by Ysurac** [comment]
I will fix this for next release.
