### ISSUE TITLE
After a while only one Wan used - Corrected with a router reboot.

### ISSUE THREAD

**Issue by Maudissure** [Ysurac/openmptcprouter#116]
## Expected Behavior
All WAN used for connections

## Actual Behavior
After some time, only one Wan is used for connections. The two Wan are correctly connected to the VPS server but all the traffic is handled only by one Wan.

Usually the master Wan is the one that loose traffic. 

## Steps to Reproduce the Problem

  1. Reboot the router
  2. Wait some hours (don't know how many)
  3. Start a download or streaming and check on OMR utility --> One WAN used only.
  4. Reboot the router --> Two Wan are used.

## Specifications

  - OpenMPTCProuter version: 0.29.1
  - OpenMPTCProuter VPS version: 0.41
  - OpenMPTCProuter platform: RPI3 B+
  - Two WAN used (ADSL + 4G)

**Comment by Ysurac** [comment]
You can try OpenMPTCProuter 0.30
What error do you have in OpenMPTCProuter status page ?

**Comment by Maudissure** [comment]
Ok with version OMR 0.30/VPS 0.43.

I close.
