### ISSUE TITLE
dhcp in openmptcprouter as guest in virtualbox not working as expected

### ISSUE THREAD

**Issue by moham96** [Ysurac/openmptcprouter#1168]
## Expected Behavior
having openmptcprouter as a virtualbox guest and another windows guest on the same internal network should allow the windows machine to get an ip from the openmptcprouter and can ping the main gateway

## Current Behavior
The windows machine doesn't get an ip most of the times, sometimes it gets an ip but i can't ping the gateway ip(openmptcprouter ip) 

## Steps to Reproduce the Problem

  1.create two virtual machines (openmptcprouter using the efi vdi image and a windows 7 machine)
  2.set the first network interface of openmptcprouter in vbox settings to Internal network (intnet, intel pro 1000 mt server, promiscuous mode=Allow all)
  3. for the windows 7 machine add a second interface with the same settings as the above
  4. start the two machines and see if the interface in the windows machine gets an ip from the openmptcprouter dhcp server it should get an ip in the 192.168.100.0/24 network but it doesn't, some times it gets an ip but you can't ping the gateway from the windows machine

## Context (Environment)
My main system is manjaro linux, i tried to setup openmptcprouter environment for testing inside virtualbox, created two VMs (OMR and windows 7 machines) and put them on the same internal network expecting the windows machine to get an ip from the OMR instance but it doesn't or if it does sometimes it can't ping the main OMR ip

## Specifications

  - OpenMPTCProuter version: v0.55.2-r0+14198-da98603597
  - OpenMPTCProuter VPS version: N/A
  - OpenMPTCProuter platform: x86_64, Virtualbox efi image

**Comment by Adorfer** [comment]
what is the result of the suggested "tcpdump -i 1 -pvn port 67 and port 68"
1) on the OMR
2) on the windows machne. 

in other words: Please find out
- get DHCPreq lost
- get DHCPoffer lost
- get DHCPack lost
- where do you observe the sporadic loss?

**Comment by moham96** [comment]
Ok the problem is gone, the solution/workaround is :
1- had to reinstall the windows machine for some reason the old one had problems it seems.
2-it seems that if i add only one interface to OMR VM as an internal network it works fine and it is attached as eth0,
but if i add more interfaces(bridges) leaving the first interface as internal network then the naming order is changed and the second interface become `eth0` instead of `eth1` so i have to set the second interface to internal network so the OMR detect it as `eth0` and runs the dhcp server on it, and use the first adapter as a bridge interface like the rest. this is very strange why it changes the naming scheme?!

Regards
