### ISSUE TITLE
Raspberry AP wi-fi and LAN same IP

### ISSUE THREAD

**Issue by predino** [Ysurac/openmptcprouter#1171]
I have been using openMTPCProuter on a raspberry pi4 for several days and I am well connected with 2 modems in 4G + and my old Eolo line which I will soon give notice, (given the worsening of speed in recent times) for the moment I have aggregated them all together the results are good, I have made several tests to try to activate the wifi network as (AP Access point) keeping the same IP address with the LAN network without success is there any stratagem or will I necessarily have to connect an external AP? Thanks for the help

**Comment by shrireram** [comment]
@predino can you post the screenshot of your AP configuration page ?

**Comment by predino** [comment]
I performed some tests by activating the wifi as AP, but I saw that when I connected the wifi network gave me a different network address, in this way it does not see the devices connected to the local network at this point I deleted the configuration

**Comment by predino** [comment]
Maybe there is a way to let the 2 networks talk with different addresses, I am not able as a result I have connected an AP router
