### ISSUE TITLE
Aggregated connection not working

### ISSUE THREAD

**Issue by jhackeur** [Ysurac/openmptcprouter#1173]
## Expected Behavior
Aggregated connection for my ADSL, 4G, and second 4G access

## Current Behavior
My connection are not aggregated - only master connection is used

## Possible Solution
fix multipath vpn ?

## Steps to Reproduce the Problem

  1. connect my 3 access
  2. run a speedtest and see that bandwidth/latency are the same as "master" access only

## Context (Environment)
It's only a bandwidth issue, new design so was not work before.
If you have a look on the screenshot, you can see that my 3 access are working:
1/ if I connect my 3 access I got this:
![2020-08-24 07_59_03-OpenMPTCProuter - État - normal](https://user-images.githubusercontent.com/65120693/91014963-a1ed1a80-e5ea-11ea-9e92-3bbb03db2029.png)
![2020-08-24 07_59_55-SpeedTest-normal](https://user-images.githubusercontent.com/65120693/91014967-a285b100-e5ea-11ea-84b1-4e13e1b7ed93.png)
2/if I connect only ADSL I got this: 
![2020-08-24 08_05_55-OpenMPTCProuter - État - ADSL](https://user-images.githubusercontent.com/65120693/91014961-a1548400-e5ea-11ea-8a93-52eda4a96606.png)
![2020-08-24 08_06_39-SpeedTest-ADSL](https://user-images.githubusercontent.com/65120693/91014962-a1ed1a80-e5ea-11ea-82a0-c2abd6ad8eb4.png)
3/if I connect only 4G got this: 
![2020-08-24 08_02_00-OpenMPTCProuter - État - 4G](https://user-images.githubusercontent.com/65120693/91014968-a285b100-e5ea-11ea-9b2d-a62f6dda892d.png)
![2020-08-24 08_02_22-SpeedTest-4G](https://user-images.githubusercontent.com/65120693/91014956-9f8ac080-e5ea-11ea-9b65-a8877173ad43.png)
4/if I connect only 4G-BR200 got this: 
![2020-08-24 08_03_46-OpenMPTCProuter - État - 4G-BR200](https://user-images.githubusercontent.com/65120693/91014957-a0235700-e5ea-11ea-8a9d-e1a93b7da216.png)
![2020-08-24 08_04_21-SpeedTest-4G-BR200](https://user-images.githubusercontent.com/65120693/91014959-a0bbed80-e5ea-11ea-848a-bd58ac50cc2b.png)

The question is: why my access are not aggregated ?

## Specifications

  - OpenMPTCProuter version: v0.55.2
  - OpenMPTCProuter VPS version: 0.1017
  - OpenMPTCProuter platform: ESXI

**Comment by Ysurac** [comment]
Please reboot the VPS, it was updated but not rebooted: it seems to use an old kernel.
Check in Network->MPTCP and "MPTCP fullmesh" tab that all IPs are visible.
To test speed, use via SSH on the router ```omr-test-speed``` to test aggregated speed and ```omr-test-speed wan1``` to test wan1 speed (where wan1 is real interface name visible via ```ip link```). Test during 2 minutes and stop with Ctrl+C

**Comment by jhackeur** [comment]
Thanks for the answer!

I have rebooted both (server and router), but still have the same issue.
Regarding MPTCP fullmesh:
![2020-08-24 10_35_38-OpenMPTCProuter - MPTCP Fullmesh](https://user-images.githubusercontent.com/65120693/91022547-a79c2d80-e5f5-11ea-89c8-476fc276e6f0.png)

Please find below the omr-test-speed:
![2020-08-24 10_32_51-omr-test-speed](https://user-images.githubusercontent.com/65120693/91022418-79b6e900-e5f5-11ea-8c4c-2ae3aa3b8d11.png)

**Comment by Ysurac** [comment]
What is the result if you remove ADSL ?
What is your VPS provider ?

**Comment by jhackeur** [comment]
Here the result without ADSL (eth1):
![2020-08-24 10_32_51-omr-test-speed-withoutADSl](https://user-images.githubusercontent.com/65120693/91028844-55abd580-e5fe-11ea-9e5e-e7706bc47296.png)

I use an an ESX hosted on dedicated server provided by OneProvider

**Comment by Ysurac** [comment]
Can you check using htop on the router and on the VPS the CPU load and memory usage when omr-test-speed (only, no need to test ethX this time) is running ?

**Comment by jhackeur** [comment]
Here the result:
- for router side:
![2020-08-24 12_08_49-htop-router](https://user-images.githubusercontent.com/65120693/91032863-d8cf2a80-e602-11ea-86bc-d084bca66c07.png)
- for server side:
![2020-08-24 12_09_27-htop-server](https://user-images.githubusercontent.com/65120693/91032868-d967c100-e602-11ea-8b5e-3038fe7ece99.png)

**Comment by jhackeur** [comment]
I don't think this is related to perf issue, isn't ?
But if needed, I can add ressources.

**Comment by Ysurac** [comment]
This doesn't seems to be the problem.

**Comment by Ysurac** [comment]
There is no router/firewall like Cisco material somewhere on the path ?
Can you check latency from each wan to the VPS ip using ```ping -B -I eth1 -c 10 <vpsip>``` for each interface ?

**Comment by jhackeur** [comment]
Indeed there is firewalls involved in this design, please find below:
![2020-08-25 19_32_07-diagrams net](https://user-images.githubusercontent.com/65120693/91207874-be33a900-e709-11ea-9134-6a00cac00ab0.png)

Regarding the latency:
![2020-08-25 19_35_14-ping latency](https://user-images.githubusercontent.com/65120693/91208321-53cf3880-e70a-11ea-81a3-c272923177b9.png)
Second 4G access is down at this time... 

What I can't explain is: why each tunnel separately works fine but not works in aggregated mode ?
Any other check I can do ?

To be honnest I'm a security guys and not a network guys, and I don't really understand how multipath VPN dispatching works....

**Comment by Ysurac** [comment]
Multipath TCP add a multipath flag in TCP header, some firewall remove it.
And this may be the case here: https://supportcenter.checkpoint.com/supportcenter/portal?solutionid=sk114666

**Comment by jhackeur** [comment]
mmmmhhh indeed, seems to be stripped here.....
I double check this tomorrow and perform capture before and after firewall to track this flag - thanks a lot for this informations!

**Comment by jhackeur** [comment]
So for your record, Checkpoint firewall remove the flag - you point indeed the issue!
And it's not possible to allow this flag as Multipath VPN is considered as security issue by checkpoint...

So I bypass the firewall for test, and working as expected yet!

thanks again for your good job :)
