### ISSUE TITLE
OMR-Bypass by Source Mac broken in 0.55.2

### ISSUE THREAD

**Issue by jrvanator** [Ysurac/openmptcprouter#1174]
Source Mac OMR-Bypass broke in 0.55.2.  Was working in 0.55.1

Attempted all possible selections for interface, remained non-working.  

I went back to 0.55.1, it is working on that release.

**Comment by Ysurac** [comment]
This will be fixed in next release.

**Comment by Ysurac** [comment]
Fixed in 0.55.3
