### ISSUE TITLE
Impossible to block net access for a given device 

### ISSUE THREAD

**Issue by patimages** [Ysurac/openmptcprouter#1184]
## Expected Behavior
block net access for a given device 

## Current Behavior
Does not work as expected (as discussed in another forum)

## Steps to Reproduce the Problem

set up a rule to block internet access to a device using IP or MAC address

## Specifications

  - OpenMPTCProuter version: openmptcprouter v0.55.3 r0+14198-da98603597 / LuCI Master git-20.219.57394-35e2735
  - OpenMPTCProuter VPS version: 0.1017
  - OpenMPTCProuter platform: x86_64)

**Comment by Ysurac** [comment]
What is the result of ```tcpdump -i eth0 ether host <macaddress>``` from the router via SSH when you try to exit ?
There is also ```tcpdump -i eth0 -e``` that should show all traffic with mac addresses but can be really verbose.

**Comment by patimages** [comment]
Thanks ! What do you mean by "when you try to exit ?"

**Comment by Ysurac** [comment]
I mean when you try to exit to internet with the client that you want to block, so when you want to go to a website from this client.
