### ISSUE TITLE
Question: Custom domain for V2ray with self-signed TLS cert

### ISSUE THREAD

**Issue by milankragujevic** [Ysurac/openmptcprouter#1186]
I was wondering if it is possible to use a custom domain that doesn't exist for V2ray obfuscation (as far as I know, I can set VPS_DOMAIN env. variable) with a custom self-signed SSL certificate (I am not sure how to do that)?

**Comment by Ysurac** [comment]
Not possible. V2Ray TLS need an existing domain.

**Comment by milankragujevic** [comment]
It would be existing from the point of view of the router and the VPS, because it would be added artificially in the hosts file.

**Comment by Ysurac** [comment]
self-signed cert doesn't work to my knowledge, but I never tested.

**Comment by milankragujevic** [comment]
Yes, I tried it, doesn't work. Thank you anyway.
