### ISSUE TITLE
How to install CUPS (print server) on RPI version ?

### ISSUE THREAD

**Issue by NyKo24** [Ysurac/openmptcprouter#1188]
## Expected Behavior
I would like to use CUPS print server to share my printer

## Current Behavior
I use `p910nd`, it's work great, but I don't manage print queue and Air Print.

## Possible Solution
Build CUPS binary ? Create a build for openmptcprouter ?

## Specifications

  - OpenMPTCProuter version: 0.55.1
  - OpenMPTCProuter VPS version: 0.55.1
  - OpenMPTCProuter platform: RPI3

**Comment by Ysurac** [comment]
It's not really related to OpenMPTCProuter, more related to OpenWrt and I have no idea about this.
