### ISSUE TITLE
No Apple device can get IP thru DHCP server

### ISSUE THREAD

**Issue by Maudissure** [Ysurac/openmptcprouter#119]
## Expected Behavior
Apple devices get IP address from DHCP server

## Actual Behavior
None of my Apple devices get IP from DHCP server (iPhone, iPad, Apple TV)

## Specifications

  - OpenMPTCProuter version: 0.30
  - OpenMPTCProuter VPS version: 0.43
  - OpenMPTCProuter platform: RPI3B+

**Comment by Maudissure** [comment]
Oh well , just found it !

It's linked to IPV6, if IPV6 is turned off in Openmptcprouter advanced configuration interface, no Apple device can get an IP address from the DHCP server.

**Comment by Ysurac** [comment]
And devices other than Apple get IPv4 via DHCP ?

**Comment by Maudissure** [comment]
Yes all other devices get their IP .

**Comment by Ysurac** [comment]
You can try ```tcpdump -i eth0 -n port 67 or port 68```, on OpenMPTCProuter, this will monitor DHCP, and check if you see the iPad or Apple TV.

**Comment by Maudissure** [comment]
Sorry, i had to revert back to my load balancing network, i removed the Openmptcp router.

For now, i 'can't make tests anymore.

**Comment by Maudissure** [comment]
I think you should leave this point open, even if i can't test it, maybe
some peoples could do it with their apple devices.

Cordialement,

Emmanuel GELINEAU.

**Comment by rubaz100** [comment]
iPadOS works fine (works but not always just some connection freezes(?)
iPhone 7/iOS get a ip but dont have an internet connection. I dont know what to do.
Internet connection is not stable. Disconnected from the internet (not wifi or dhcp)

**Comment by Ysurac** [comment]
If it's not in DHCP, then it's not related to this issue, open a new one.
