### ISSUE TITLE
wildcard domain do not pass through OMR-Bypass

### ISSUE THREAD

**Issue by hambe76** [Ysurac/openmptcprouter#1193]
## Expected Behavior
 

subdomains from a recorded domain pass through OMR-Bypass

## Current Behavior

ASN and Domain not working

![image](https://user-images.githubusercontent.com/70482142/91669471-87003600-eb15-11ea-9a53-c4c32e7d4223.png)

## Possible Solution

Adding possibility to use * as wildcard before domain name or use regex (ex: ^([A-Za-z0-9.-]*\.)?example\.com\.?/ or ^([A-Za-z0-9.-]*\.)?ne?t?fli?x(img|ext|video)?\.(com|net)/ )

Or explain me how to have it working 😄 

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - OpenMPTCProuter version:  openmptcprouter v0.55.3 r0+14198-da98603597
  - OpenMPTCProuter VPS version:  OpenMPTCProuter VPS 0.1017
  - OpenMPTCProuter platform:  RPI4

**Comment by Ysurac** [comment]
It's working but OpenMPTCProuter IP must be used as DNS on the clients.

**Comment by hambe76** [comment]
OK used router's IP instead of unbound server in pi-hole
