### ISSUE TITLE
Gateway down error

### ISSUE THREAD

**Issue by Corrado56** [Ysurac/openmptcprouter#1196]
## Expected Behavior
Gateway Up

## Current Behavior
Look at this situation.
![image](https://user-images.githubusercontent.com/10588158/91864287-5680df00-ec70-11ea-8dd1-f9c661f18775.png)

I am trying to aggregate three LTE connection from different providers.
the modem type of connection "Ogilink_voda" and "Iliad" are the same (Huawei B535) with identical configuration except for the IP range
For some reason the connection "Iliad" is "Gateway down".
If I connect directly to the modem with WI-FI connection, I am connected to internet and navigate.
I have tried to reboot the Huawei Modem, the openMPTCP router, the VPS, but nothing happens
What are the possible causes for this error ? How could I indagate?

I am actually aggregating only two connections

## Specifications

  - OpenMPTCProuter version: 0.55.3
  - OpenMPTCProuter VPS version: 0.1017
  - OpenMPTCProuter platform: Linksys 3200

**Comment by Ysurac** [comment]
The gateway down is only a warning? Some ISP/dongle doesn't answer to ping on gateway so it's not a problem.
But in your case if it's the same modem as Ogilink then you should get same info with operator, lte power,...
How do you check that only two connections are aggregated ?

**Comment by Corrado56** [comment]
Speedtest using MPTCP router
![image](https://user-images.githubusercontent.com/10588158/91868563-2851ce00-ec75-11ea-8510-026607dc39b3.png)

Connecting the modem via Wi Fi
![image](https://user-images.githubusercontent.com/10588158/91868688-4e776e00-ec75-11ea-82bc-1ccf3e69dab7.png)

The iliad SIM is working, but I have no traffic on Iliad interface on MPTCP Router

**Comment by Ysurac** [comment]
Can you try, for about 2 minutes, to test via SSH on the router ```omr-test-speed``` and ```omr-test-speed wan1``` where wan1 is a real interface (visible via ```ip link```) on each wan interface ?

**Comment by Corrado56** [comment]
![image](https://user-images.githubusercontent.com/10588158/91877045-c2b60f80-ec7d-11ea-8b63-85d6c59c96a4.png)

![image](https://user-images.githubusercontent.com/10588158/91877059-cba6e100-ec7d-11ea-99fe-f77bae47211d.png)

**Comment by Ysurac** [comment]
What is the interface corresponding to lan4 ? Iliad ?

**Comment by Corrado56** [comment]
Hi Yannik,
FOUND !
I try to create a new interface WAN3 connected to phisical port LAN3
And this is the result:
![image](https://user-images.githubusercontent.com/10588158/91885922-d5821180-ec88-11ea-8fad-a2cd46657572.png)
What ? the same MAC on 2 interfaces ?
And the mac is equal to:
![image](https://user-images.githubusercontent.com/10588158/91886135-2eea4080-ec89-11ea-91bd-a8ecac1cb2dd.png)
So the culprit is: **THE WIZARD**
![image](https://user-images.githubusercontent.com/10588158/91886633-e8e1ac80-ec89-11ea-843c-179d479f4494.png)
When You create a new interface of type Static IP (other cases not tested), the wizard by default suggest the MAC of the Physical Port WAN (instead of a casual one), and If You don't change the suggestion You have a not working interface. 
After changing the MAC on Iliad interface:
![image](https://user-images.githubusercontent.com/10588158/91886774-1dedff00-ec8a-11ea-8ea2-296438562b27.png)

I like happy ends
