### ISSUE TITLE
OpenMPTCProuter v0.56 Release Candidate

### ISSUE THREAD

**Issue by Ysurac** [Ysurac/openmptcprouter#1201]
This issue is opened for OpenMPTCProuter 0.56.

**Changes:**
* V2Ray support for TCP and UDP (proxy can be selected in wizard between shadowsocks and v2ray)
* V2Ray reverse proxy support
* Domain support as VPS address
* NanoPi R2S official support
* Improvement on LTE dongle
* Kernel and packages update
* MLVPN will be back
* MPTCP update
* Dashboard with VPS info
* omr-test-speed with multiples locations servers
* Enable/disable rules in omr-bypass
* More complete LAN/WAN settings in wizard
* Some fixes

Server script must be updated: ```wget -O - http://www.openmptcprouter.com/server-test/debian10-x86_64.sh | sh```
Images : [https://download.openmptcprouter.com/develop/](https://download.openmptcprouter.com/develop/)

**OpenMPTCProuter v0.56 is compiling via Github Actions. If images are working without issues, this will be officially released this tuesday (2020/10/27 UTC timezone).**

**Comment by cr3ative** [comment]
Hello! The index page for me has two blank squares, and this file is missing when the page tries to load it - perhaps that's why?

`http://192.168.100.1/luci-static/resources/protocol/wwan.js`

Here is a screenshot:

![Screenshot 2020-10-27 at 12 57 20](https://user-images.githubusercontent.com/1850718/97304664-f5cae880-1853-11eb-8a66-12c0d0102b4c.png)

**Comment by Ysurac** [comment]
one square is for DHCP and the other is for wifi. They are blank when no data.
The wwan.js never existed, I have no idea why it's called (but it doesn't make any issue).

**Comment by cr3ative** [comment]
Ah okay! That makes sense. Thank you for clarifying!

**Comment by JeedHome44** [comment]
> Ah okay! That makes sense. Thank you for clarifying!

WARNING cr3ative! We can see your external IP adress to your VPS... Delete screenshot ;)

**Comment by cr3ative** [comment]
> > Ah okay! That makes sense. Thank you for clarifying!
> 
> WARNING cr3ative! We can see your external IP adress to your VPS... Delete screenshot ;)

Ehhh, maybe someone will be my friend this way. ;)

**Comment by JeedHome44** [comment]
is it used to switch to 0.56 if we have done 0.55 recently?

**Comment by Ysurac** [comment]
Changes are available on https://www.openmptcprouter.com/

**Comment by TalalMash** [comment]
I don't see that "MPTCP over VPN" OVPN protocol has been changed to udp from tcp, was it always udp? I've seen much better performance and no bufferbloat on heterogenous links with the latest release.

**Comment by Ysurac** [comment]
MPTCP over VPN always used OpenVPN in UDP mode.
