### ISSUE TITLE
2 keys usb 4G

### ISSUE THREAD

**Issue by CoSysopK** [Ysurac/openmptcprouter#1214]
## Actual Behavior

Par défaut, clé-usb1 se connecte sur wan1 et clé-usb2 se connecte sur wan2
Lorsque le routeur redémarre, volontairement ou à cause d'une coupure involontaire.
clé-usb1 se connecte sur wan2 et clé-usb2 se connecte sur wan1.
Comment dois-je faire pour que clé-usb1 se connecte toujours sur wan1 et clé-usb2 se connecte toujours sur wan2 ?
Y a-t-il un appareil à acquérir ?

## Steps to Reproduce the Problem

 1. Install image for Raspberry PI 3/3B+ (64-bit)
 2. Install VPS Debian 10 Buster x86_64
 3. Configure the router with the wan1 static and wan2 static
 4. Add the IP address VPS and, all the informations retrived on the VPS
 5. Two keys 4G on usb PI 3B

## Specifications

  - OpenMPTCProuter version: Version 0.55.3
  - OpenMPTCProuter VPS version: Version 0.1017
  - OpenMPTCProuter platform: RPI3B+ 64 bits

**Comment by Ysurac** [comment]
C'est en cours dév et test sur la branche develop.
C'est quoi comme clefs ?

**Comment by CoSysopK** [comment]
2 clés 4G Huawei E8372

**Comment by Ysurac** [comment]
En mode hi-link ? C'est ce que j'ai donc ça fonctionnera normalement correctement.

**Comment by CoSysopK** [comment]
Non, je n'ai pas ce mode par défaut sur mes clés 4G Huawei E8372.
Avez-vous un lien URL pour procéder à cette installation si cela s'avère possible?

**Comment by Ysurac** [comment]
Elles sont utilisées avec NCM alors ?

**Comment by CoSysopK** [comment]
Je viens de vérifier sur l'interface. Il n'y a rien de tout ça.
Je vous fournis quelques captures écrans si toutefois, ces réglages sont bons.

![001](https://user-images.githubusercontent.com/48426317/92601291-ec3def00-f2ac-11ea-8b67-ec567e91decd.png)
![002](https://user-images.githubusercontent.com/48426317/92601296-eea04900-f2ac-11ea-97fb-36380d5815b5.png)

**Comment by CoSysopK** [comment]
Y a-t-il un firmware à mettre à jour ?

**Comment by Ysurac** [comment]
Vu qu'il y a une interface, elles sont déjà en mode Hi-link :)
Donc quand elles sont branchées, une interface eth* est créée directement.

**Comment by CoSysopK** [comment]
Oui, j'ai mis eth1 sur wan1 et eth2 sur wan2. Mais lors d'un redémarrage du routeur, eth1 va se mettre sur wan2, et cela pose problème car je n'ai pas de réseau. Alors je dois faire un redémarrage manuel en laissant juste la clé 4G wan1 eth1, pour que le réseau fonctionne, alors je peux rebrancher la clé 4G wan2 eth2, et tout se configure bien comme il faut.
Le soucis, lorsque je suis absent, cela ne va pas se remettre bien comme il faut.

**Comment by Ysurac** [comment]
Oui, comme je l'ai dit la solution est en cours de développement dans la branche develop.

**Comment by CoSysopK** [comment]
d'accord, impeccable.
