### ISSUE TITLE
Port forwarding issue ?

### ISSUE THREAD

**Issue by jhackeur** [Ysurac/openmptcprouter#1215]
## Expected Behavior
Reach my web server via my VPS and OpenMPTCT router

## Current Behavior
I configure port forwarding based on this document:
https://github.com/Ysurac/openmptcprouter/wiki/Port-forwarding

However I'm not able to reach my webserver from my VPS public IP...

VPN is up
Redirects all ports from server to this router is checked
OpenMPTCP router IP: 192.168.89.101
WebServer IP: 192.168.89.33
![2020-09-09 15_14_01-OpenMPTCProuter - Port Forwards - LuCI](https://user-images.githubusercontent.com/65120693/92603096-32944d80-f2af-11ea-933d-4410617615fe.png)
![2020-09-09 15_14_08-OpenMPTCProuter - NAT Rules - LuCI](https://user-images.githubusercontent.com/65120693/92603101-332ce400-f2af-11ea-8f6a-3b6ad6d9ef1f.png)

## Possible Solution
Maybe a NAT issue ?

## Context (Environment)
I try to reach my web server from my public IP, currently trying with public port 8000 redirected to 80

## Specifications

  - OpenMPTCProuter version: v0.55.3 r0+14198-da98603597
  - OpenMPTCProuter VPS version: 0.1017 5.4.52-mptcp
  - OpenMPTCProuter platform: ESXI

**Comment by Ysurac** [comment]
Did you do what is in https://github.com/Ysurac/openmptcprouter/wiki/Port-forwarding#debug ?

**Comment by jhackeur** [comment]
Yes for all step!

Do we need to reboot or restart somes process ?
I can try to reboot both router and server later if needed ?

**Comment by kevin39** [comment]
SNAT too ?

**Comment by Ysurac** [comment]
So you see packets with tcpdump ? You can also run tcpdump on eth0 and see if it's correctly forwarded.

**Comment by jhackeur** [comment]
Yes and yes!

I performed a reboot of my openmptcp router, and it's working fine now. Maybe a NAT table has to be cleared or something like that, anyways, works fine :)
