### ISSUE TITLE
documentation request about log message

### ISSUE THREAD

**Issue by zulu14** [Ysurac/openmptcprouter#1216]
hi again thanx for this awesome software, 

i get this error: 
Wed Sep  9 19:27:04 2020 daemon.info glorytun[7370]: STOPPED tun0
Wed Sep  9 19:27:05 2020 daemon.err glorytun[7370]: XXXXX.65001: connected
Wed Sep  9 19:27:05 2020 daemon.err glorytun[7370]: XXXXX.65001: key exchange failed
Wed Sep  9 19:27:05 2020 daemon.info glorytun[7370]: STOPPED tun0
Wed Sep  9 19:27:06 2020 daemon.err glorytun[7370]: XXXXX.65001: connected
Wed Sep  9 19:27:06 2020 daemon.err glorytun[7370]: XXXXX.65001: key exchange failed

can you tell me how is the location files make the _log function of the error ?  (RPI4) 
im curious about how its works :p
have a nice day to you !

**Comment by zulu14** [comment]
hi , okay i have fix my issues, its not a general issues, d'ont worry, 
just question where the omr retrive all key by the api of vps ? (on the controller wizard_add, the key are get by the html , but you have a get request to vps (/config) with he token get by /token with the user and pass , im right?

**Comment by Ysurac** [comment]
"Key exchange failed" occurs with Glorytun TCP when the key is incorrect or sometimes when IP address change.

Yes, keys are retrieved from the VPS API via /config with a token.

**Comment by zulu14** [comment]
okay thanx for you kick answer, wich file make the request ?

**Comment by zulu14** [comment]
hi Ysurac I allow myself to revive you

**Comment by Ysurac** [comment]
openmptcprouter-vps service.
