### ISSUE TITLE
MTU issue

### ISSUE THREAD

**Issue by jhackeur** [Ysurac/openmptcprouter#1219]
## Expected Behavior
I'm currently facing to MTU issue. Without OpenMPTCP, I'm able to use MTU of 1480 for my 3 internet access.
With OpenMPTCP, I need to use less of 900...

## Current Behavior
VPN not working through OpenMPTCP

## Possible Solution
Absolutely no idea of what is the issue

## Steps to Reproduce the Problem
We can see the issue with a ping:
![2020-09-10 18_41_54-VL89-testhost - VMware Workstation](https://user-images.githubusercontent.com/65120693/92765227-7792af80-f395-11ea-84c7-04e757b74dca.png)

## Specifications

    OpenMPTCProuter version: v0.55.3 r0+14198-da98603597
    OpenMPTCProuter VPS version: 0.1017 5.4.52-mptcp
    OpenMPTCProuter platform: ESXI

**Comment by Ysurac** [comment]
Check MTU of all interfaces in status page. Check also OMRVPN interface MTU.

**Comment by jhackeur** [comment]
Thanks for this prompt reply!

On status page I have all working interfaces with more than 1440:
![2020-09-10 19_12_13-OpenMPTCProuter - Status - LuCI](https://user-images.githubusercontent.com/65120693/92769793-9dba4e80-f399-11ea-97b0-595dd183600c.png)
If I do the same test (ping) with MTU as 1440, it's working fine with all my internet access.

How can I check this point ?
" OMRVPN interface MTU" ?

**Comment by Ysurac** [comment]
Using ```ip a``` or ```ip link``` via SSH on the router. MTU should be on interface tun0 in most case.

**Comment by jhackeur** [comment]
![2020-09-10 19_51_14-root@OpenMPTCProuter_ ~](https://user-images.githubusercontent.com/65120693/92775820-fd672880-f39e-11ea-99de-64d1ff9900e5.png)

So 1500 - how this is possible with my at 1447 on one internet access ?

**Comment by Ysurac** [comment]
Hum, in fact I have same result when pinging google.fr, but no problem with 1.1.1.1. Can you check too ?

**Comment by jhackeur** [comment]
Same issue with 1.1.1.1:
![2020-09-10 22_30_57-C__WINDOWS_system32_cmd exe](https://user-images.githubusercontent.com/65120693/92800800-5346cb00-f3b5-11ea-9ab4-b8a5bb5931af.png)

My main problem is about establishing an IPSEC VPN inside OpenMPTCP, it's not related to pinging some random IP with specified MTU :)
So I suspect this issue is related to all destination IP (at least for me)...

**Comment by Ysurac** [comment]
You can try another VPN in System->OpenMPTCProuter wizard tab, and check advanced settings box.

**Comment by jhackeur** [comment]
I try this yesterday evening (A dead simple vpn and openvpn) -> exactly the same behavior.

I've already try to deploy another router and another server (on ESX hosted in another VPS provider) -> same behavior.
Unfortunately, when I disconnect all my 4G access and keep only my ADSL, I got the same behavior too.

I suspect the issue is related to OpenMPTCP router -> we got no answer when MTU is too large (ex: 900):
![2020-09-11 08_31_48-toto@EULUPCDWJ6JR2B_ ~](https://user-images.githubusercontent.com/65120693/92875676-8f0b8000-f409-11ea-969a-1669d15c820e.png)

Do you have the same behavior ?

**Comment by Ysurac** [comment]
I have same behavior, but it's also the case from any server without OpenMPTCProuter. Google seems to limit ICMP packet size.

**Comment by jhackeur** [comment]
Sorry but not really, as you can see here:
![2020-09-11 09_04_51-VL89-testhost - VMware Workstation](https://user-images.githubusercontent.com/65120693/92880037-e57abd80-f40d-11ea-9431-271faf0c86b9.png)

**Comment by Ysurac** [comment]
Check from the VPS.

**Comment by jhackeur** [comment]
Huummmm correct, seems to have an issue here...
Let me check with my provider and I come back to you with the feedback.

**Comment by Ysurac** [comment]
No issue with provider, I have the same result on all VPS/server from many provider. Google seems to limit ICMP packet size from some source, but it's not a problem. No issue with 1.1.1.1 (from cloudfare) for example.
So I don't think this is related to your IPsec problem.

**Comment by jhackeur** [comment]
Yes but with my VPS provider (Milkywan), I got this:
![2020-09-11 11_17_59-](https://user-images.githubusercontent.com/65120693/92901137-8a9e9180-f420-11ea-9cc8-ca23be3a0ce0.png)
Same result witj google, 1.1.1.1, and all other website I've tested.

And of course same result to my VPN destination, that's why I suspect this as my issue !

**Comment by jhackeur** [comment]
Ok so now it's solved for MTU part:
![2020-09-13 19_51_33-arthur@arthurd_ ~](https://user-images.githubusercontent.com/65120693/93024982-8e860b80-f5fa-11ea-846b-7918df196680.png)

My VPN is bringing up, I'm able to ping inside the tunnel, but no ways to got an tcp connection running fine inside this tunnel...
There is something to fine tune to be able to used IPSEC vpn inside OpenMPTCP link ?

**Comment by Ysurac** [comment]
The tunnel client is not installed on OpenMPTCProuter ? in this case nothing should be needed.

**Comment by jhackeur** [comment]
There is no real "client": this is a Site to site IPSEC VPN.

I've try few thing:
1/ initiate this VPN between Home (ADSL) -> Remote pfSense VPN -> Working fine
2/ initiate this VPN between Home (4G) -> Remote pfSense VPN -> Working fine
3/ initiate this VPN between Home (openMPTCP router) -- (openMPTCP server) -> Remote pfSense VPN -> VPN are bringed up, but TCP flow are not working

Do you have already experienced this king of issue ?
Maybe an issue with multipath and IPSEC/GRE ?

**Comment by Ysurac** [comment]
I just made a test with L2TP/IPsec and I have no issues.
There is no public server for GRE over IPsec, so more difficult to test.
You can ping over VPN ? UDP over the VPN is working ? TCP doesn't work at all ?

**Comment by jhackeur** [comment]
Yes I can ping, and UDP works fine but with slow bandwidth.
TCP doesn't work at all.

I can manage to provide you a termination server on my VPS if you want to proceed with more test ?

**Comment by Ysurac** [comment]
I think it's a firewall problem.

**Comment by jhackeur** [comment]
Maybe. However why I can get this working fine with my ADSL and 4G access but not via OpenMPTCP ?
I'm not saying that OpenMPTCP is in cause, I'm juste trying to find a solution.

Do you have an idea how troubleshoot this ?

**Comment by Ysurac** [comment]
Because same firewall is not used.
You can try to be really permissive in firewall and try remove syn flood protection in OpenMPTCProuter firewall.

**Comment by jhackeur** [comment]
I will try this and keep you informed.

Another strange point. Usually I use speed.ui.com to run a speedtest.
Similar behavior: it's working fine with all my internet access, but when I used it via OpenMPTCP I got this issue at the end:
![2020-09-17 08_28_13-VL89-testhost - VMware Workstation](https://user-images.githubusercontent.com/65120693/93428656-2405f180-f8c0-11ea-940b-92887c984809.png)

Do you have the same symptom ?
For you record, I have 2 OpenMPTCP router and 2 server : 1 on VM hosted by Milkywan, one other on a private server hosted at OneProvider -> same issue on both

**Comment by Ysurac** [comment]
I have no issue on a scaleway VM. Check in your browser developer tools, network tab what is the error code.

**Comment by jhackeur** [comment]
![2020-09-17 08_55_43-openmptcp](https://user-images.githubusercontent.com/65120693/93430987-cf647580-f8c3-11ea-8eb3-3cb30eecaa9f.png)

However no internet issue during the test, continuous ping still working fine...
I will try to order a scaleway VM for testing, hope this can solved all my issue, because I have few similar issue like this with other website (like my banking account disconnect me, ...) so not really stable for now.

**Comment by ragefan** [comment]
I have the same issue with Cisco VPN client.
