### ISSUE TITLE
Network / MPTCP / Bandwith strange behavior

### ISSUE THREAD

**Issue by Corrado56** [Ysurac/openmptcprouter#1221]
Hi, openmptcp 0.55.3 on Linksys 3200

This is the result of a speedtest:
![image](https://user-images.githubusercontent.com/10588158/92973886-527d6a00-f485-11ea-97c4-2578e358281e.png)
but after 3 minutes
![image](https://user-images.githubusercontent.com/10588158/92973945-6a54ee00-f485-11ea-8909-7969fff933f9.png)
the blue connection WAN2 is running quicker than the others.

Regards
Corrado

**Comment by Ysurac** [comment]
The issue is the graph or the speed ?

**Comment by Corrado56** [comment]
The issue is with the graph.
the blue area is moving left quicker that the other two. 
I have done only one speedtest. 
The graph above seems correct (3 connection bonded at the same time).  
in the graph below the blue connection appears to be done before the other two.
I am doing nothing only look at the graph for three minutes
It's an UI interface error, not a technical one.
