### ISSUE TITLE
Bug : Lors d'un ajout d'une interface 

### ISSUE THREAD

**Issue by AdrienDssy** [Ysurac/openmptcprouter#1224]
## Current Behavior
Quand j'ajoute une interface (peux importe que ce soit un nouveau WAN ou un MPTCP over VPN) ça retire les "anciennes interfaces" du pare-feu. Donc il faut les rajouter manuellement pour que ça re-fonctionne.
![image](https://user-images.githubusercontent.com/53304251/93013518-8b166400-f5a9-11ea-9127-2fb6f83fef9c.png)
![image](https://user-images.githubusercontent.com/53304251/93013567-e8121a00-f5a9-11ea-9f19-7cf4a3252160.png)
![image](https://user-images.githubusercontent.com/53304251/93013572-f2ccaf00-f5a9-11ea-8a90-6e48323247eb.png)
Toute fois le fait de le rajouter fait un autre "bug" j'ai l'impression
Pour le MPTCP over VPN c'est un partage de connexion via USB (Depuis mon téléphone, enfin j'ai l'impression que l'aggrégation ce fait pas et que j'ai seulement le débit de la box 4G (alors que les deux appareil ont le même débits))
## Specifications

 - OpenMPTCProuter version:  (0.55.3) 
 - OpenMPTCProuter VPS version:  (0.1017 5.4.52-mptcp)  
 - OpenMPTCProuter platform:  (x86_64)

**Comment by Ysurac** [comment]
L'interface est ajoutée via le wizard quand une seule interface physique est disponible ?

**Comment by AdrienDssy** [comment]
Via le Wizard

**Comment by Ysurac** [comment]
Je n'arrive pas à reproduire le soucis.

**Comment by AdrienDssy** [comment]
Je ne sais pas si c'est le fait que c'est du à des partages de connexion via mes téléphone mais j'y crois moyen

**Comment by Ysurac** [comment]
Par défaut une interface de type macvlan est crée, l'interface physique choisie est eth0 ou une autre interface ?

**Comment by AdrienDssy** [comment]
Selon l'appareil c'est soit eth5 pour l'IPhone ou usb0 pour mon Honor

**Comment by tboome33** [comment]
Perso, j'ai jamais réussi à ajouter le partage de connection d'un Iphone. Le DHCP ésotérique de l'Iphone semble metter la pagaille dans toutes les interfaces avec un retour en arrière impossible !!!

**Comment by AdrienDssy** [comment]
J'ai pas ce soucis personnellement mais j'ai plutôt l'impression que l'agrégation ce fait pas quand c'est un partage de connexion via USB (je constate que rien ne change alors que ça débite sur le forfait (4G Illimité le we))

**Comment by Ysurac** [comment]
Il faut vérifer dans Réseau->Interfaces que les interfaces ne sont pas de type macvlan (car pas besoin dans ce cas) et voir si l'interface est bien dans la zone "wan" niveau firewall.

**Comment by AdrienDssy** [comment]
Ils sont dans le wan j'ai revérifier et je dois aller où pour voir si c'est du macvlan ?

**Comment by Ysurac** [comment]
Dans l'onglet "Paramètres physiques" de l'interface.

**Comment by AdrienDssy** [comment]
C'est en mode normal

**Comment by AdrienDssy** [comment]
up :)
