### ISSUE TITLE
no server ping response after 1 seconds

### ISSUE THREAD

**Issue by bigcachetx** [Ysurac/openmptcprouter#1226]
## Expected Behavior
no server ping response after 1 seconds

## Current Behavior
Googled and it said this info just a notice and system will ok, but not really right

I run the speed test, only 1 - ATT works, the whole link lost when I unplug the ATT

## Possible Solution
I checked each line and can access internet 

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - OpenMPTCProuter version: 0.55.3
  - OpenMPTCProuter VPS version: 0.1017 5.4.52
  - OpenMPTCProuter platform: x86_64

**Comment by bigcachetx** [comment]
<img width="516" alt="2020-09-15_013738" src="https://user-images.githubusercontent.com/62531258/93175197-dd17d080-f6f4-11ea-97b6-508639141323.png">

**Comment by Ysurac** [comment]
Check that there is no firewall enabled on these devices.
You can also check using Network->MPTCP and MPTCP support check tab, or using via SSH on the router ```omr-tracebox <interface>```, if multipath is not blocked.

**Comment by bigcachetx** [comment]
Thanks, I found a modem lost signal, after reset, all come back.

But I found the MPT works on fast.com but not youtube.com, even slower than 1 line.

**Comment by Ysurac** [comment]
MPT ?
How do you test speed on youtube ?

**Comment by bigcachetx** [comment]
"stats for nerds" will give you the connection speed to youtube.

Normally it should be the same as fast.com but it's not, much slower than that.

<img width="890" alt="2020-09-16_072357" src="https://user-images.githubusercontent.com/62531258/93336833-e89af280-f7ed-11ea-9d3f-2f5478c41f97.png">
<img width="989" alt="2020-09-16_072506" src="https://user-images.githubusercontent.com/62531258/93336841-ea64b600-f7ed-11ea-88de-7bddef7fe35a.png">

**Comment by Ysurac** [comment]
There is no reason that speed from youtube can be the same as fast.com
Connection Speed provided by youtube is not accurate and is not mean to be.
Youtube also use Quic, when browser support it, that is based on UDP, so VPN must be up and work well.

**Comment by bigcachetx** [comment]
I just found I submit same issues "Streaming issues #1030 "

I run shadowsocks on computer, the youtube stream reach to 90Mbps.
Or I use only 1 WAN, the speed will went up. Don't know where is the problem.

US wireless carrier limit the streaming speed, but normally VPN will solve the problem, this is very weird!


<img width="966" alt="2020-09-17_122016" src="https://user-images.githubusercontent.com/62531258/93506189-89b6a580-f8e1-11ea-9434-119baf944558.png">

**Comment by Ysurac** [comment]
What do you mean by "I run shadowsocks on computer" ?

**Comment by bigcachetx** [comment]
I run shadowsocks proxy on computer, connect to VPS2 through OpenMPTCProuter.

Is this topo clear?
<img width="500" alt="2020-09-17_131623" src="https://user-images.githubusercontent.com/62531258/93511391-5d525780-f8e8-11ea-9efa-3afc41d9d0b7.png">

**Comment by bigcachetx** [comment]
With 2 or more WAN:
Youtube 5-15Mbps by  blue route
90Mbps by yellow route.

With only 1 WAN
Both route will reach maximum of WAN bandwidth

<img width="500" alt="2020-09-17_131623" src="https://user-images.githubusercontent.com/62531258/93511559-a5717a00-f8e8-11ea-928b-389b08f4549e.png">

**Comment by Ysurac** [comment]
And same issue if VPS 2 is used instead of VPS 1 ?

**Comment by bigcachetx** [comment]
Yes, same issue.

In fact, I have VPS3 earlier, after I submitted the ticket, I replaced VPS 3 with VPS1. But the same problem.

**Comment by bigcachetx** [comment]
I almost find out why!
I install ssr onVPS2 by myself which include BBR accelerate.
Is this the reason?

**Comment by Ysurac** [comment]
I don't think so.
Encryption is not disabled on shadowsocks in OpenMPTCProuter ?

**Comment by bigcachetx** [comment]
OK, finally I found different:

If I deploy shadowsocks client on router (anotherone openwrt router), the same youtube result;
If I run shadowsocks client on computer, then it runs well.

I believe it's shadowsocks not OpenMPTCProuter problem.

Do you take a test or not?

**Comment by Ysurac** [comment]
I don't have this issue, youtube use aggregation in my case, so it's difficult to test.
Did you try with another browser ?
