### ISSUE TITLE
agrégation fail

### ISSUE THREAD

**Issue by zulu14** [Ysurac/openmptcprouter#1228]
hello, i have juste added my last modem number 8, and my mptcp borken, my trafic only pass on WAN 1 (its not a bypass )

into my mptcp connection i have this : 
![image](https://user-images.githubusercontent.com/71033768/93245726-ffa8f880-f78b-11ea-9033-cbc436c5466d.png)

my status page say all are ok, the syslog not tel an key echange failure or other, 

my mptcp settings are: 
![image](https://user-images.githubusercontent.com/71033768/93245795-1cddc700-f78c-11ea-8e1c-330241a772c1.png)

thank you !

**Comment by zulu14** [comment]
update: after reboot of OMR, only one modem are into the mptcp connection, 

![image](https://user-images.githubusercontent.com/71033768/93246607-5105b780-f78d-11ea-8a15-f413471182a8.png)

**Comment by zulu14** [comment]
the status page are always all green for all modem

**Comment by Ysurac** [comment]
Please use template. I need to know release of router and VPS used.

**Comment by zulu14** [comment]
sorry,

my omr ver: 0.55.3
my vps ver: 0.1017

**Comment by Ysurac** [comment]
It's working with 7 modems but not with 8 ?
What do you have in Network->MPTCP, MPTCP Fullmesh tab ?

**Comment by zulu14** [comment]
![image](https://user-images.githubusercontent.com/71033768/93351144-a4354400-f839-11ea-972d-5a3c289fdfb6.png)

**Comment by Ysurac** [comment]
Wrong tab.

**Comment by zulu14** [comment]
sorry  for you:
![image](https://user-images.githubusercontent.com/71033768/93366118-00549400-f84b-11ea-80f7-e2623e5c1426.png)

**Comment by zulu14** [comment]
result mptcp_check of a agrégation fail modem (wan2) :
![image](https://user-images.githubusercontent.com/71033768/93366395-5fb2a400-f84b-11ea-9d3f-2bf7baa9c869.png)

**Comment by zulu14** [comment]
(i have extend my syslog page to 300 line, but, i cannot show you the syslog, its spam by this)
![image](https://user-images.githubusercontent.com/71033768/93367286-9806b200-f84c-11ea-9128-9b2f4d2c27c5.png)

**Comment by Ysurac** [comment]
I see only 7 modems in MPTCP fullmesh tab. What is the result of ```multipath``` command via SSH on the router ? And what is the missing interface in fullmesh tab ?

For the log error, it's strange. CPU frequency shouldn't change. Check in System->OpenMPTCProuter, advanced settings tab that Scaling governor is set to "performance" and that "Minimum scaling CPU frequency" and "Maximun scaling CPU frequency" are both set at "1500000".

**Comment by zulu14** [comment]
(when i apply its not update the CPUI params, (after F5 infact)) can i use the uci set and commit ? 

i have delete the modem number 8 to check if its rework but its no resume the agragtion, 
 

Multipath cmd: 
![image](https://user-images.githubusercontent.com/71033768/93369680-0731d580-f850-11ea-8911-e205384af9ee.png)

**Comment by zulu14** [comment]
SS just fell now,  ( Shadowsocks: Rules DOWN)  and re up few second after ( Shadowsocks: Rules UP)

and i have found this in log: 
Wed Sep 16 19:22:08 2020 kern.err kernel: [84573.859068] xhci_hcd 0000:01:00.0: Ring expansion failed

Wed Sep 16 19:23:35 2020 user.notice post-tracking-post-tracking: Can't find Shadowsocks, restart it...

**Comment by Ysurac** [comment]
After a "Ring expansion failed", that is a know RPI issue, USB is rebooted.
Try to reboot the router to fix aggregation.

**Comment by zulu14** [comment]
i have reboot, and its not solve the issues, (i have only wan1 traffic )

**Comment by zulu14** [comment]
![image](https://user-images.githubusercontent.com/71033768/93374174-a0fc8100-f856-11ea-921c-46b0e4e267c9.png)

**Comment by Ysurac** [comment]
When I check previous screen, I see that Multipath TCP path-manager is not set to fullmesh. It must be set to fullmesh for aggregation.

**Comment by zulu14** [comment]
okay i try it,

**Comment by zulu14** [comment]
great, its working, the issues are so dump ,
thanx you, 

juste a liitle question, somme time the key are not retrive , i need to manualy restart curseboxmaster-vps, i have open file an i do not understand wich function will be run when you restart the service into the controller or a the first boot

**Comment by Ysurac** [comment]
I don't know what you are talking about.

**Comment by zulu14** [comment]
sorry wrong post,
into the openmptcprouter-vps with function are run bu the restart  (/etc/init.d/openmptcprouter-vps restart)

**Comment by Ysurac** [comment]
If key are not retrieved at first launch, this service is restarted until it run correctly.
For info on what it does, check the source ;)

**Comment by zulu14** [comment]
okay thanks !

**Comment by zulu14** [comment]
good day to you !
