### ISSUE TITLE
[FeatureRequest] TTL Mod

### ISSUE THREAD

**Issue by juristoeckli** [Ysurac/openmptcprouter#1229]
## Expected Behavior

TTL increase on Wan

## Current Behavior

Please add the function to set an ttl offset. Some Mobile network providers use the TTL value to block or charge different for hotspot Data. if we can set the ttl to one higher tan normal it will look like data from the phone to the network provider.

**Comment by bigcachetx** [comment]
Add rules in network - Firewall - Custom Rules
XXXX is the number you want.

modprobe xt_HL 
modprobe xt_hl 
iptables -t mangle -A POSTROUTING -j TTL --ttl-set XXXXX

**Comment by Ysurac** [comment]
I added in develop branch the "sysctl net.ipv4.ip_default_ttl" setting.
I will add later change of TTL by interface.
