### ISSUE TITLE
Impossible de faire fonctionner openmptcprouter

### ISSUE THREAD

**Issue by skyfr54** [Ysurac/openmptcprouter#1230]
Hello, I followed all the tutorials as needed, I installed the vps and prepared the two routers (a livebox in 192.168.1.1 and a tplink mr600 in 192.168.3.1). The network card of the pc is correctly configured. Then I run openmptcprouter on raspberry and it gives me what is on the photos, is there something I forgot ??? If you need more info I will give it ... thank you in advance for helping me Nb I made a mistake for the name for vps but nothing changes and both wan's ping...Si vous pouviez me répondre en français ça serait top. Merci!

![network](https://user-images.githubusercontent.com/71438093/93466786-0bf89700-f8ed-11ea-86d6-e48b6e77ae5e.png)
![vps](https://user-images.githubusercontent.com/71438093/93466814-19158600-f8ed-11ea-9c29-668fff6d22cd.png)
![vps suite](https://user-images.githubusercontent.com/71438093/93466826-1d41a380-f8ed-11ea-8311-ecf76e9551ea.png)
![wan1](https://user-images.githubusercontent.com/71438093/93466842-23d01b00-f8ed-11ea-9482-17567ce94abd.png)
![wan2](https://user-images.githubusercontent.com/71438093/93466853-27fc3880-f8ed-11ea-9742-32525bb73104.png)

**Comment by Ysurac** [comment]
Ca aurait été mieux avec le template, notamment pour avoir les versions du VPS et du routeur ;)

Il faudrait via SSH sur le routeur, le résultat de ```ip a```, ```ip r``` et de ```ping 192.168.1.1```

**Comment by skyfr54** [comment]
C'est ok j'ai tout revu, reste à tester....
![final](https://user-images.githubusercontent.com/71438093/93479434-972d5900-f8fc-11ea-8137-fc255e89b6c8.png)
