### ISSUE TITLE
Question : Quel serveur DNS utilisé par défaut sur le routeur ?

### ISSUE THREAD

**Issue by AdrienDssy** [Ysurac/openmptcprouter#1238]
Hello, j'aimerais avoir quel serveur DNS utilisé par défaut sur le routeur ?
Car selon Discord c'est dû à un grand nombre de requêtes envoyés, j'ai 1 500 bots discord sur un serveur sans oublier d'autres requêtes qu'on effectue dans la famille

**Comment by Ysurac** [comment]
Les serveurs DNS racines.

**Comment by AdrienDssy** [comment]
D'accord et j'ai pas moyen de mettre ceux de Cloudflare ? :)

**Comment by Ysurac** [comment]
C'est dans la doc : https://github.com/Ysurac/openmptcprouter/wiki/Custom-DNS

**Comment by AdrienDssy** [comment]
C'est bien ce qu'il me semblais, merci
