### ISSUE TITLE
Sendbackup - Multiple servers

### ISSUE THREAD

**Issue by dragon2611** [Ysurac/openmptcprouter#1239]
## Expected Behavior

On Page cgi-bin/luci/admin/system/openmptcprouter/backup#

If there are multiple servers
Send backup should send to the server next to the button or at least the current primary server.

## Current Behavior
The Backup is sent to the first server on the list

openmptcprouter v0.55.3 r0+14198-da98603597

**Comment by Ysurac** [comment]
Backup should be sent to all servers.

**Comment by dragon2611** [comment]
Looks like it did but the UI isn't updated as logging in today shows it on both servers.

Sending a new backup makes the date change on the top server but not the 2nd one

**Comment by Ysurac** [comment]
True, date is not updated. I will fix that.

**Comment by Adorfer** [comment]
hups, observed that as well, forgot to report.
