### ISSUE TITLE
help.....

### ISSUE THREAD

**Issue by abilly007** [Ysurac/openmptcprouter#124]
## Expected Behavior

  In English please.

## Steps to Reproduce the Problem

  1. when the shadsocks is running, i ssh  intranet 172.171.48.0/20 machine ,and then connected failed.
    I think the destination ip of intranet 172.171.48.0/20  had beed redir to ss port,but i found the script 
    /usr/bin/ss-rules had contain the intranet 172.16.0.0/12 of o_dst_bypass_ ,and that had contain my intranet 172.171.48.0/20,I don't know why ?could you help me or give some guidance  ? thanks you .

## Specifications

  - OpenMPTCProuter version: (Last is not a version)
  - OpenMPTCProuter VPS version: (Last is not a version)
  - OpenMPTCProuter platform: (RPI2/RPI3/x86/x86_64)

**Comment by Ysurac** [comment]
From where do you try to connect ? OpenMPTCProuter or a client ? What is the IP of your client and OpenMPTCProuter ? Can you ping the machine from where you want to connect ?

**Comment by Ysurac** [comment]
You may have to config OpenMPTCProuter to allow traffic between your 2 networks.

**Comment by abilly007** [comment]
like the port forwarding configuration of OpenMPTCProuter ?i have to redir the external port 22  to port 22 of internal lan network  ?

**Comment by Ysurac** [comment]
No, it's traffic rules. You don't need port forwarding.
I don't know your OpenMPTCProuter configuration, I would need ```/etc/config/network``` and ```/etc/config/firewall``` (or ```uci show network``` and ```uci show firewall```) if you want more help.

**Comment by abilly007** [comment]
root@OpenMPTCProuter:~# uci show network
network.loopback=interface
network.loopback.ifname='lo'
network.loopback.proto='static'
network.loopback.ipaddr='127.0.0.1'
network.loopback.netmask='255.0.0.0'
network.loopback.multipath='off'
network.globals=globals
network.globals.ula_prefix='fd94:a94c:a8e0::/48'
network.globals.multipath='enable'
network.globals.mptcp_path_manager='fullmesh'
network.globals.mptcp_scheduler='default'
network.globals.mptcp_checksum='1'
network.globals.mptcp_syn_retries='30'
network.globals.mptcp_fullmesh_num_subflows='1'
network.globals.mptcp_fullmesh_create_on_err='1'
network.globals.mptcp_ndiffports_num_subflows='1'
network.globals.congestion='bbr'
network.lan=interface
network.lan.ifname='eth0'
network.lan.proto='static'
network.lan.ipaddr='192.168.100.1'
network.lan.netmask='255.255.255.0'
network.lan.ip6assign='60'
network.lan.metric='2048'
network.lan.multipath='off'
network.lan.ip4table='lan'
network.lan_rule=rule
network.lan_rule.lookup='lan'
network.lan_rule.priority='100'
network.wan1=interface
network.wan1.proto='static'
network.wan1.ip4table='wan'
network.wan1.multipath='master'
network.wan1.defaultroute='0'
network.wan1.type='macvlan'
network.wan1.ifname='wan1'
network.wan1.ipaddr='192.168.11.101'
network.wan1.netmask='255.255.255.0'
network.wan1.gateway='192.168.11.1'
network.wan2=interface
network.wan2.proto='static'
network.wan2.ip4table='wan'
network.wan2.multipath='on'
network.wan2.defaultroute='0'
network.wan2.type='macvlan'
network.wan2.ifname='wan2'
network.wan2.ipaddr='192.168.21.101'
network.wan2.netmask='255.255.255.0'
network.wan2.gateway='192.168.21.1'
network.wan1_dev=device
network.wan1_dev.name='wan1'
network.wan1_dev.type='macvlan'
network.wan1_dev.ifname='eth0'
network.wan1_dev.macaddr='auto1530800249'
network.wan2_dev=device
network.wan2_dev.name='wan2'
network.wan2_dev.type='macvlan'
network.wan2_dev.ifname='eth0'
network.wan2_dev.macaddr='auto1530800249'
network.@route6[0]=route6
network.@route6[0].interface='lan'
network.@route6[0].target='::/0'
network.omrvpn=interface
network.omrvpn.proto='dhcp'
network.omrvpn.ip4table='vpn'
network.omrvpn.multipath='off'
network.omrvpn.leasetime='12h'
network.omrvpn.mtu='1400'
network.omrvpn.ifname='tun0'
network.omr6in4=interface
network.omr6in4.proto='6in4'
network.omr6in4.ip4table='vpn'
network.omr6in4.multipath='off'
network.omr6in4.gateway='fe80::a00:1'
network.omr6in4.ip6addr='fe80::a00:2'
network.omr6in4.ipaddr='10.255.255.2'
network.omr6in4.peeraddr='10.255.255.1'
root@OpenMPTCProuter:~# 
root@OpenMPTCProuter:~# uci show firewall
firewall.@defaults[0]=defaults
firewall.@defaults[0].syn_flood='1'
firewall.@defaults[0].input='ACCEPT'
firewall.@defaults[0].output='ACCEPT'
firewall.@defaults[0].forward='REJECT'
firewall.@defaults[0].disable_ipv6='0'
firewall.@zone[0]=zone
firewall.@zone[0].name='lan'
firewall.@zone[0].network='lan'
firewall.@zone[0].input='ACCEPT'
firewall.@zone[0].output='ACCEPT'
firewall.@zone[0].forward='ACCEPT'
firewall.@zone[1]=zone
firewall.@zone[1].name='wan'
firewall.@zone[1].network='wan' 'wan6' 'wan1' 'wan2'
firewall.@zone[1].input='REJECT'
firewall.@zone[1].output='ACCEPT'
firewall.@zone[1].forward='REJECT'
firewall.@zone[1].masq='1'
firewall.@zone[1].mtu_fix='1'
firewall.@forwarding[0]=forwarding
firewall.@forwarding[0].src='lan'
firewall.@forwarding[0].dest='wan'
firewall.@rule[0]=rule
firewall.@rule[0].name='Allow-DHCP-Renew'
firewall.@rule[0].src='wan'
firewall.@rule[0].proto='udp'
firewall.@rule[0].dest_port='68'
firewall.@rule[0].target='ACCEPT'
firewall.@rule[0].family='ipv4'
firewall.@rule[1]=rule
firewall.@rule[1].name='Allow-Ping'
firewall.@rule[1].src='wan'
firewall.@rule[1].proto='icmp'
firewall.@rule[1].icmp_type='echo-request'
firewall.@rule[1].family='ipv4'
firewall.@rule[1].target='ACCEPT'
firewall.@rule[2]=rule
firewall.@rule[2].name='Allow-IGMP'
firewall.@rule[2].src='wan'
firewall.@rule[2].proto='igmp'
firewall.@rule[2].family='ipv4'
firewall.@rule[2].target='ACCEPT'
firewall.@rule[3]=rule
firewall.@rule[3].name='Allow-DHCPv6'
firewall.@rule[3].src='wan'
firewall.@rule[3].proto='udp'
firewall.@rule[3].src_ip='fc00::/6'
firewall.@rule[3].dest_ip='fc00::/6'
firewall.@rule[3].dest_port='546'
firewall.@rule[3].family='ipv6'
firewall.@rule[3].target='ACCEPT'
firewall.@rule[4]=rule
firewall.@rule[4].name='Allow-MLD'
firewall.@rule[4].src='wan'
firewall.@rule[4].proto='icmp'
firewall.@rule[4].src_ip='fe80::/10'
firewall.@rule[4].icmp_type='130/0' '131/0' '132/0' '143/0'
firewall.@rule[4].family='ipv6'
firewall.@rule[4].target='ACCEPT'
firewall.@rule[5]=rule
firewall.@rule[5].name='Allow-ICMPv6-Input'
firewall.@rule[5].src='wan'
firewall.@rule[5].proto='icmp'
firewall.@rule[5].icmp_type='echo-request' 'echo-reply' 'destination-unreachable' 'packet-too-big' 'time-exceeded' 'bad-header' 'unknown-header-type' 'router-solicitation' 'neighbour-solicitation' 'router-advertisement' 'neighbour-advertisement'
firewall.@rule[5].limit='1000/sec'
firewall.@rule[5].family='ipv6'
firewall.@rule[5].target='ACCEPT'
firewall.@rule[6]=rule
firewall.@rule[6].name='Allow-ICMPv6-Forward'
firewall.@rule[6].src='wan'
firewall.@rule[6].dest='*'
firewall.@rule[6].proto='icmp'
firewall.@rule[6].icmp_type='echo-request' 'echo-reply' 'destination-unreachable' 'packet-too-big' 'time-exceeded' 'bad-header' 'unknown-header-type'
firewall.@rule[6].limit='1000/sec'
firewall.@rule[6].family='ipv6'
firewall.@rule[6].target='ACCEPT'
firewall.@rule[7]=rule
firewall.@rule[7].name='Allow-IPSec-ESP'
firewall.@rule[7].src='wan'
firewall.@rule[7].dest='lan'
firewall.@rule[7].proto='esp'
firewall.@rule[7].target='ACCEPT'
firewall.@rule[8]=rule
firewall.@rule[8].name='Allow-ISAKMP'
firewall.@rule[8].src='wan'
firewall.@rule[8].dest='lan'
firewall.@rule[8].dest_port='500'
firewall.@rule[8].proto='udp'
firewall.@rule[8].target='ACCEPT'
firewall.@include[0]=include
firewall.@include[0].path='/etc/firewall.user'
firewall.@rule[9]=rule
firewall.@rule[9].target='ACCEPT'
firewall.@rule[9].name='Allow-All-LAN-to-VPN'
firewall.@rule[9].dest='vpn'
firewall.@rule[9].src='lan'
firewall.zone_vpn=zone
firewall.zone_vpn.name='vpn'
firewall.zone_vpn.masq='1'
firewall.zone_vpn.input='REJECT'
firewall.zone_vpn.forward='ACCEPT'
firewall.zone_vpn.output='ACCEPT'
firewall.zone_vpn.network='glorytun' 'omrvpn' 'omr6in4'
firewall.@rule[10]=rule
firewall.@rule[10].target='ACCEPT'
firewall.@rule[10].name='Allow-All-Ping'
firewall.@rule[10].proto='icmp'
firewall.@rule[10].dest='*'
firewall.@rule[10].src='*'
firewall.@rule[10].icmp_type='echo-request'
firewall.@rule[11]=rule
firewall.@rule[11].target='ACCEPT'
firewall.@rule[11].name='Allow-VPN-ICMP'
firewall.@rule[11].proto='icmp'
firewall.@rule[11].src='vpn'
firewall.@rule[12]=rule
firewall.@rule[12].target='ACCEPT'
firewall.@rule[12].name='Allow-Lan-to-Wan'
firewall.@rule[12].dest='wan'
firewall.@rule[12].src='lan'
firewall.allow_dhcp_request_vpn=rule
firewall.allow_dhcp_request_vpn.name='Allow-DHCP-Request-VPN'
firewall.allow_dhcp_request_vpn.src='vpn'
firewall.allow_dhcp_request_vpn.proto='udp'
firewall.allow_dhcp_request_vpn.dest_port='67'
firewall.allow_dhcp_request_vpn.target='ACCEPT'
firewall.allow_dhcp_request_vpn.family='ipv4'
firewall.ss_rules=include
firewall.ss_rules.path='/etc/firewall.ss-rules'
firewall.ss_rules.reload='1'
firewall.ss_rules6=include
firewall.ss_rules6.path='/etc/firewall.ss-rules6'
firewall.ss_rules6.reload='1'
firewall.@redirect[0]=redirect
firewall.@redirect[0].enabled='1'
firewall.@redirect[0].target='DNAT'
firewall.@redirect[0].src='vpn'
firewall.@redirect[0].dest='lan'
firewall.@redirect[0].proto='tcp'
firewall.@redirect[0].name='Web'
firewall.@redirect[0].src_dport='80'
firewall.@redirect[0].dest_ip='192.168.100.100'
firewall.@redirect[0].dest_port='80'
firewall.@redirect[1]=redirect
firewall.@redirect[1].enabled='1'
firewall.@redirect[1].target='SNAT'
firewall.@redirect[1].src='lan'
firewall.@redirect[1].dest='wan'
firewall.@redirect[1].src_dip='192.168.100.1'
firewall.@redirect[1].name='web'
firewall.@redirect[1].proto='tcp'
firewall.@redirect[1].dest_ip='192.168.100.100'
firewall.@redirect[1].dest_port='80'
root@OpenMPTCProuter:~#

**Comment by Ysurac** [comment]
No interface are configured in 172.171.48.0/20 network. I have no idea how anything in this network can be accessible from OpenMPTCProuter. You can do a ```traceroute 172.171.48.xx``` but even if this tell what is the route used, it's not a good configuration for a router... You need at least to add an interface in 172.171.48.0/20 network to OpenMPTCProuter.

**Comment by abilly007** [comment]
1. traceroute 172.171.48.xx  and ssh to the ip 172.171.48.xx from OpenMPTCProuter as fellow:

root@OpenMPTCProuter:~# traceroute 172.171.48.xx 

traceroute to 172.171.48.xx  (172.171.48.xx ), 30 hops max, 38 byte packets
 1  192.168.11.1  (192.168.11.1 )  0.752 ms  0.579 ms  0.540 ms
 2  *  *  *
 3  *  *  *
 4  *  *  *
 5  *  *  *
 6  *  *  *
 7  *  *  *
 8  *  *  *
 9  *  *  *
10  *  *  *
11  *  *  *
12  *  *  *
13  *  *  *
14  *  *  *
15  *  *  *
16  *  *  *
17  *  *  *
18  *  *  *
19  *  *  *
20  *  *  *
21  *  *  *
22  *  *  *
23  *  *  *
24  *  *  *
25  *  *  *
26  *  *  *
27  *  *  *
28  *  *  *
29  *  *  *
30  *  *  *

root@OpenMPTCProuter:~# ssh xxx@172.171.48.xx
xxx@172.171.48.xx's password: 
Welcome to Ubuntu 14.10 (GNU/Linux 3.16.0-36-generic x86_64)

 * Documentation:  https://help.ubuntu.com/ 


329 packages can be updated.
16 updates are security updates.

Your Ubuntu release is not supported anymore.
For upgrade information, please visit:
http://www.ubuntu.com/releaseendoflife 


New release '15.04' available.
Run 'do-release-upgrade' to upgrade to it.

Last login: Wed Aug  8 18:39:33 2018 from 172.171.52.xx 

xxx@openwrt-OptiPlex-3020:~$ 

2.  I don't quite understand why I have to add an interface in 172.171.48.0/20 network to OpenMPTCProuter.The two wan interfaces all can get to the 172.171.48.0/20 network.

**Comment by abilly007** [comment]
Ysurac ,is there any other idea ?

**Comment by Ysurac** [comment]
You can try to add a route to the network on the OMR, but this may not be enough.
