### ISSUE TITLE
WhatsApp Call Not Working

### ISSUE THREAD

**Issue by mack1726** [Ysurac/openmptcprouter#1240]
## Current Behavior
WhatsApp Call Not Working. When i stop Glorytun, whatsapp starts working

## Specifications

  - OpenMPTCProuter version: v0.55.3 r0+14198-da98603597
  - OpenMPTCProuter VPS version: V0.1017
  - OpenMPTCProuter platform: RPI4

**Comment by Ysurac** [comment]
Whatsapp doesn't have a call test, so it's difficult to really test.
It's possible that they banned IP range of your VPS provider.
This may also be a MTU problem, you can try with only one connection and check if this work or not.

**Comment by mack1726** [comment]
I ran tests, whatsapp call works when i disable vpn and set ss-redir for udp - unset. Can I fix this somehow? Thank you so much

**Comment by Ysurac** [comment]
Without VPN enabled, UDP use direct connection.

**Comment by xabix** [comment]
Hello,
what would make sense it's to find the URL used by WhatsApp app to established the calls. If you can do that then you can put this URL in OMR bypass and get it working.

if you find, let us know as I have the same issue :)

Merci
XabiX

**Comment by kevin39** [comment]
WhatsApp IP & ports are publicly available on facebook help center.

**Comment by xabix** [comment]
The IPs are given here: https://developers.facebook.com/docs/whatsapp/guides/network-requirements/?locale=fr_FR but would be easier and better to have directly the alias.

**Comment by xabix** [comment]
did anyone found a way to overcome this issue easily?

**Comment by zicochaos** [comment]
same issue here inbound calls not working 

dedicated server with hyper v 
router: rpi4

**Comment by Malaga82** [comment]
i'm using Google Duo and WhatsApp calling, no issues.
