### ISSUE TITLE
How to use vps like a web server ?

### ISSUE THREAD

**Issue by launux** [Ysurac/openmptcprouter#1249]
I just discover OpenMPTCProuter, it seems fantastic ! I whished use my webserver to test your solution.

OMR works fine, but all my websites are unavailable anymore.

How can I open ports on my vps ?

Thank you for your help.

**Comment by Ysurac** [comment]
On the VPS a firewall is configured by default. This use shorewall. You can check in ```/etc/shorewall/rules``` current rules and open port 80/443.

**Comment by launux** [comment]
Thank you very much, I didn't know Sharewall ! But I work with Docker and the opening of the ports is not enough...

**Comment by Ysurac** [comment]
I don't know what you mean, but if you installed OpenMPTCProuter under docker this can't work without using a kernel with MPTCP patch.
For Docker there is some configuration needed that you can see in Shorewall doc.

**Comment by launux** [comment]
I'm sorry OpenMPTCProuter works fine. On my vps, I had a apache server with redirect from http (80) to https (443) next a reverse proxy on a Docker container on another port (8001).

I am going to continue to investigate it.

Is there an option to uninstall the vps part ?

**Comment by Ysurac** [comment]
No, there is no option to uninstall VPS part.
