### ISSUE TITLE
Wireless/WiFi is not working nor detected

### ISSUE THREAD

**Issue by afriza** [Ysurac/openmptcprouter#125]
## Expected Behavior
  - Network > Wireless is there
  - `uci show wireless` shows something
  - WiFi is able to scan and connect
  - under overview, the following is displayed
![Wireless under Overview works](https://user-images.githubusercontent.com/68133/43829347-e47b2e64-9b28-11e8-8c40-0be30f2b9a30.png)

## Actual Behavior
  - Network > Wireless is missing on a cleanly formatted & flashed OpenMPTCProuter
  - `uci show wireless` shows `uci: Entry not found`
  -  when flashing v0.30.4 over v0.27 (_**v0.27 is last known with working WiFi**_), WiFi is not able to scan nor connect
    - the following is displayed under overview
![Wireless under Overview doesn't work](https://user-images.githubusercontent.com/68133/43829994-802f6036-9b2a-11e8-9cdd-e06826c422f6.png)

## Steps to Reproduce the Problem

  1. Flash OpenMPTCProuter version 0.29, 0.29.1, 0.30, 0.30.3 or 0.30.4
  2. try to connect to WiFi or do anything related to wireless

## Specifications

  - OpenMPTCProuter version: (0.29, 0.29.1, 0.30, 0.30.3, 0.30.4)
  - OpenMPTCProuter VPS version: (-)
  - OpenMPTCProuter platform: (RPI3B+)

**Comment by Ysurac** [comment]
Fixed in OpenMPTCProuter v0.31

**Comment by FunkeDope** [comment]
Wifi doesnt work at all on the latest build again. Rpi2 x86.
