### ISSUE TITLE
can't bridge wlan to lan

### ISSUE THREAD

**Issue by rjhollan** [Ysurac/openmptcprouter#1257]
## Expected Behavior
Enable wlan0 (Network > Wireless > Master > Enable), put on Network "lan" (bridges wlan0 and eth1.5).  Enable WiFi on laptop and get IP address, and route packets via wlan0.

## Current Behavior
Laptop gets IP address via DHCP, but can't see anything other than OpenMPTCP router (192.168.100.1).  Can't ping anything else ('no route to host').  

## Possible Solution
I've tried disabling IPv6, check firewall rules, etc.  With an ethernet cable in LAN1 port, everything works fine.  When connected to OpenWRT WiFi network, no route is available.  Default route on my laptop looks correct (tried "ifconfig en0 down; route flush; ifconfig en0 up" to reset but did not help).

## Steps to Reproduce the Problem
  1. enable Wireless on R7800 in OpenMPTCP web interface via LAN cable
  2. unplug LAN cable, join OpenWRT WiFi network
  3. ping 1.1.1.1 <---- fails

## Context (Environment)
Trying to bond multiple LTE connections on a Cradlepoint CBA850 into a single OpenMPTCP connection.  Works great with ethernet cable, but want to now extend to other (wireless) devices in the house.

## Specifications
  - OpenMPTCProuter 0.55.3 ro+14198-da98603597 / LuCi Master git-20.219.57394-35e2735
  - OpenMPTCProuter VPS version: openmptcprouter-v0.55.3-r0+14198-da98603597-x86-64-generic-ext4-combined
  - OpenMPTCProuter platform: ARMv7 (Netgear R7800)

**Comment by Ysurac** [comment]
Netgear R7800 is not a supported platform. I can't make any test on plateform I don't own.
