### ISSUE TITLE
Iphone USB Sharing

### ISSUE THREAD

**Issue by KaylFr** [Ysurac/openmptcprouter#1270]
## Expected Behavior
Connect iPhone USB Sharing connection

## Current Behavior
Connect an iphone by adding connection

## Context (Environment)
I followed the info from:
https://github.com/Ysurac/openmptcprouter/issues/606#issuecomment-523109105
On the iPhone at the top right I have the icon going to blue but it displays Gateway down in OMB

<img width="1005" alt="Capture d’écran 2020-10-01 à 19 14 55" src="https://user-images.githubusercontent.com/17416880/94842855-2cac0b00-041c-11eb-9bf2-c3817a27af91.png">
<img width="955" alt="Capture d’écran 2020-10-01 à 19 28 05" src="https://user-images.githubusercontent.com/17416880/94842922-3df51780-041c-11eb-95b5-8f170be74f65.png">

## Specifications

  - OpenMPTCProuter version: v0.55.3 r0+14198-da98603597
  - OpenMPTCProuter VPS version: 0.1017 5.4.52
  - OpenMPTCProuter platform: Raspberry  Pi 4

**Comment by KaylFr** [comment]
how to know the ip?

**Comment by Ysurac** [comment]
No idea, I don't have an iPhone.

**Comment by Mutanter** [comment]
double check your hotspot is active and the device is in trusted state
change the subnet to /28 (255.255.255.240)
reconnect your phone
