### ISSUE TITLE
WOL bloqué

### ISSUE THREAD

**Issue by JeedHome44** [Ysurac/openmptcprouter#1273]
Bonjour,

Y a-t-il une option à activer pour autoriser le WOL?

Mon Jeedom sur le même réseau LAN n'arrive pas à réveiller le PC.

J'ai pourtant bien renseigné l'IP interne et la passerelle

**Comment by Ysurac** [comment]
Merci d'utiliser le template lors de l'ouverture d'une issue...

Et vu que c'est sur le même réseau, la communication se fait directement sans passer par OMR.

**Comment by JeedHome44** [comment]
Je reviens aussi sur ce sujet.
C'est peut être aussi à cause de l'ipv6 que le WOL du PC était bloqué?

**Comment by Ysurac** [comment]
non
