### ISSUE TITLE
QUESTION:  use certain links more than others

### ISSUE THREAD

**Issue by tlkelley70** [Ysurac/openmptcprouter#1274]
I have searched and I cannot find an answer or a setting that could do this.  Basically I have two links that are limited and two that are not.  I would like to balance better the use of the two unlimited links so I retain the use of the two limited links longer as less data per day go over them.  I would give up some speed to ensure that I have this level of redundancy.  Is this possible?  So lets say I wanted 33% on one link 33% on another link, and 16.5% per the last two links each just as an example.

**Comment by Ysurac** [comment]
Links are used based on latency, so it's not possible to do what you want.

**Comment by tlkelley70** [comment]
Thanks for clarifying.
