### ISSUE TITLE
Help, how to configure LTE usb modem with  local web server inside?

### ISSUE THREAD

**Issue by openaspace** [Ysurac/openmptcprouter#1276]
Hi. 
Any help on how to configure an lte usb key that have a local web server with a web page for manage connection on 192.168.1.1?

Thank you.

**Comment by Malaga82** [comment]
do you mean access to the related modem webpages?
should work by default, i tried with a huawei usb lte modem, and i could access its pages without any route, and so it does with my current B535.
With fortigate and edgerouter i needed to do a route for that, but not for the omr.
For example, you should ping that IP, that should also be one of the interface ( wan? ) gateway.
