### ISSUE TITLE
Aggregation doesn't bounded

### ISSUE THREAD

**Issue by dettofatto** [Ysurac/openmptcprouter#1287]
## Expected Behavior
Two huawei 4g bounded, but the aggregation is limited to 1

## Specifications

  - OpenMPTCProuter version: 056b5, but also 055.3 (i've update for testing, but it is the same)
  - OpenMPTCProuter VPS version:  OpenMPTCProuter VPS 0.1018-test (before was 0.1017)
  - OpenMPTCProuter platform: pi4

omr-test-speed wan1 it is about  16.9M^C
omr-test-speed wan2 it is about 3M^C

Together is the same of wan1, but no data on wan2

**Comment by Ysurac** [comment]
Can you make a screenshot of status page ?

**Comment by Malaga82** [comment]
try to make MPTCP over VPN for the wan2, might be blocked by ISP.

**Comment by dettofatto** [comment]
![Screenshot_20201007-134245_VNC Viewer](https://user-images.githubusercontent.com/36331389/95326588-1f22d500-08a3-11eb-8a2b-e3dfba88bc79.jpg)

**Comment by Ysurac** [comment]
What is the result of a check for both interface in Network->MPTCP and "MPTCP Support Check" tab ?

**Comment by dettofatto** [comment]
![Screenshot_20201007-152016_VNC Viewer](https://user-images.githubusercontent.com/36331389/95336176-a9256a80-08b0-11eb-89eb-e1b6e2bdd1c6.jpg)

![Screenshot_20201007-151934_VNC Viewer](https://user-images.githubusercontent.com/36331389/95336231-b8a4b380-08b0-11eb-8af9-75019c91f7ea.jpg)

**Comment by Ysurac** [comment]
This seems to be ok.
What do you have in Network->MPTCP and MPTCP Fullmesh tab ?

**Comment by dettofatto** [comment]
Index, Address-ID, Backup, IP-address, if-idx
IPv4, next v4-index: 7
2, 3, 0, 192.168.8.2, 17
3, 4, 0, 192.168.10.2, 18
IPv6, next v6-index: 1

**Comment by Ysurac** [comment]
When you run ```omr-test-speed``` and you check MPTCP bandwidth graph, there is no traffic on wan2 ?

**Comment by dettofatto** [comment]
No... only few kb...

**Comment by Malaga82** [comment]
check with `omr-test-speed wan1` and `omr-test-speed wan2` if traffic is ok, then try my previous advice, make mptcp over vpn for the wan2 and check if aggregation works.

**Comment by dettofatto** [comment]
No, it is the same.
If i do omr-test-speed wan2 it is ok, but omr-test-speed it use only wan1...

**Comment by Malaga82** [comment]
Even with mptcp over vpn?
![image](https://user-images.githubusercontent.com/3518802/95510772-bb89cc00-09b6-11eb-95b1-2d665d7d927a.png)

**Comment by dettofatto** [comment]
I've seen that sometimes seems ok, with mptcp over vpn, but the speed is almost the same.
