### ISSUE TITLE
\OpenMPTCProuter\Status not working with IPV6 on in \OpenMPTCProuter\Advanced configuration menu

### ISSUE THREAD

**Issue by Maudissure** [Ysurac/openmptcprouter#129]
## Expected Behavior

 Getting status page loaded when IPV6 activated in \OpenMPTCProuter\Advanced configuration menu

## Actual Behavior

Status never show up.

If "Disable IPv6" box ticked, then status page works.

## Steps to Reproduce the Problem

  1.Disable IPv6 box unchecked : no status page loaded
  2.Disable IPv6 box checked : status page loaded normaly
 
## Specifications

  - OpenMPTCProuter version: 0.31
  - OpenMPTCProuter VPS version: 0.44
  - OpenMPTCProuter platform: RPI3B+

**Comment by Ysurac** [comment]
I can't reproduce the issue. What is the result of ```http://192.168.100.1/cgi-bin/luci/admin/system/openmptcprouter/interfaces_status``` (you must be logged before)

**Comment by Maudissure** [comment]
With "Disable IPv6" checked : 

**{"wans":[{"ifname":"wan1","ipaddr":"192.168.10.2","label":"wan1","wanip":"82.237.195.51","whois":"FR-PROXAD-ADSL","ipv6_discover":"NONE","status":"OK","link":"\/cgi-bin\/luci\/admin\/network\/network\/wan1","multipath":"master","multipath_available":"OK","gw_ping":"UP","name":"wan1","gateway":"192.168.10.1","server_ping":"UP","latency":"14"},{"ifname":"wan2","ipaddr":"192.168.11.2","label":"wan2","wanip":"37.169.23.237","whois":"FR-FREEMOBILE-20120308","ipv6_discover":"NONE","status":"OK","link":"\/cgi-bin\/luci\/admin\/network\/network\/wan2","multipath":"on","multipath_available":"OK","gw_ping":"UP","name":"wan2","gateway":"192.168.11.1","server_ping":"UP","latency":"36"},{"ifname":"wan3","ipaddr":"192.168.12.2","label":"wan3","wanip":"37.171.216.140","whois":"FR-FREEMOBILE-20120308","ipv6_discover":"NONE","status":"OK","link":"\/cgi-bin\/luci\/admin\/network\/network\/wan3","multipath":"on","multipath_available":"OK","gw_ping":"UP","name":"wan3","gateway":"192.168.12.1","server_ping":"UP","latency":"42"}],"tunnels":[],"openmptcprouter":{"local_addr":"192.168.1.2","dhcpd":{"lan":{"range_end":"192.168.1.249","dns":"192.168.1.2","router":"192.168.1.2","netmask":"255.255.255.0","range_start":"192.168.1.100","leasetime":"12h","interface":"lan"}},"remote_from_lease":true,"tun_state":"UP","remote_addr":"192.168.1.100","tun_service":true,"server_mptcp":"","tun6_state":"","service_addr":"51.254.127.83","remote_hostname":"PC_Bureau","dns":true,"socks_service_enabled":true,"socks_service":true,"ss_addr":"51.254.127.83","uptime":"2276.33","version":"\"v0.31\"","wan_addr6":"","ipv6":"disabled","tun_ip":"10.255.255.2","wan_addr":"51.254.127.83","loadavg":"0.07 0.26 0.25"}}**

With "Disable IPv6" unchecked : 

**Failed to execute call dispatcher target for entry '/admin/system/openmptcprouter/interfaces_status'.
The called action terminated with an exception:
/usr/lib/lua/luci/controller/openmptcprouter.lua:719: attempt to concatenate local 'j' (a table value)
stack traceback:
	/usr/lib/lua/luci/controller/openmptcprouter.lua:719: in function 'callback'
	/usr/lib/lua/luci/model/uci.lua:295: in function 'foreach'
	/usr/lib/lua/luci/controller/openmptcprouter.lua:584: in function </usr/lib/lua/luci/controller/openmptcprouter.lua:434>
	(tail call): ?**

**Comment by Maudissure** [comment]
Why did you closed the issue ?

**Comment by Ysurac** [comment]
I always close fixed bug ;)
This will be in next release.

**Comment by Maudissure** [comment]
Ah ok .

Cordialement,

Emmanuel GELINEAU.
