### ISSUE TITLE
can´t contact Server Admin Script (No result - No API script Answer)

### ISSUE THREAD

**Issue by rnunes77** [Ysurac/openmptcprouter#1294]
## Expected Behavior

Hello, when starting mptcprouter all arrows turn green, with the exception of Direct Output, which has a triangle with an exclamation mark, stating the following problem: can´t contact Server Admin Script (No result - No API script Answer)
## Current Behavior

The router is unable to contact the server
## Specifications

  - OpenMPTCProuter version: 0.55.1
  - OpenMPTCProuter VPS version: 0.1017
  - OpenMPTCProuter platform: Raspberry Pi 3 model B+

**Comment by rnunes77** [comment]
I took a look at the logs and I have received the following report: user.notice OMR-VPS: Can't get token, try later (can ping server, no API server answer)

**Comment by Ysurac** [comment]
The VPS was rebooted after script install ?

**Comment by rnunes77** [comment]
Yes, I restarted the VPS. Only the ports 65101, 65001 and ICMP are open, Do I need to open any more ports? I'm using Glorytun and I just put the keys for that service. Do I need to put the MLVPN and OpenVPN keys?

**Comment by Ysurac** [comment]
Port 65000 to 65535 needs to be open.
You can find all ports in https://github.com/Ysurac/openmptcprouter/wiki/Install-or-update-the-VPS
You need to put only API key, and all keys are retrieved from the API (when the API can be called).

**Comment by rnunes77** [comment]
Perfect! Ysurac.. thank you. After the changes, everthing works fine!

**Comment by mstrolo** [comment]
can this be also related??
![image](https://user-images.githubusercontent.com/7146444/160989952-b86b35c9-8c1c-4c62-ad67-5a8750144129.png)

i get this all the rime

**Comment by timbrookers** [comment]
> can this be also related?? ![image](https://user-images.githubusercontent.com/7146444/160989952-b86b35c9-8c1c-4c62-ad67-5a8750144129.png)
> 
> i get this all the rime

mstrolo was your question answered, or did you find the solution?
