### ISSUE TITLE
How latency for WAN interfaces is calculated and gateway ping?

### ISSUE THREAD

**Issue by Malaga82** [Ysurac/openmptcprouter#1298]
I have 2 WAN'S, one of them is 4G and must be over vpn for aggregation to work.
In this interface i saw latency over 100ms usally, while ping from the wan i have something like 15/16ms.
from omr:
![image](https://user-images.githubusercontent.com/3518802/95661426-9c627a00-0b2f-11eb-8cf7-7e68e530164e.png)
from lte h-monitor ping:
![image](https://user-images.githubusercontent.com/3518802/95661438-b4d29480-0b2f-11eb-9ea6-a12d65ba239e.png)

And sometimes it also shows "can't ping gateway", while ping from lte h-monitor is pinging correctly.
![image](https://user-images.githubusercontent.com/3518802/95661503-2ca0bf00-0b30-11eb-86a9-38473fb03f29.png)
![image](https://user-images.githubusercontent.com/3518802/95661522-4c37e780-0b30-11eb-87e1-cf97472e2346.png)
Is there anything for tuning this?
Just curiosity.

**Comment by Ysurac** [comment]
Nothing special here. It's only an ICMP ping done for status page and only an information.

**Comment by Malaga82** [comment]
The "No server ping" doesn't affect the bonding, right?

**Comment by Ysurac** [comment]
Not at all.
