### ISSUE TITLE
Cannot login to GUI after update to OMR v0.56beta9

### ISSUE THREAD

**Issue by h45h3ncryp73d** [Ysurac/openmptcprouter#1300]
## Expected Behavior
Should be able to login into GUI with existing username/password combination.

## Current Behavior
I've just updated OMR to 0.56beta9 for 0.55.3 and after reboot I cannot login to GUI anymore ... I don't get error about wrong password it simply redirects me to login form again and again. SSH seems to be intact.

## Possible Solution
Don't know. Could try to change root password via SSH - doesn't work ...

## Steps to Reproduce the Problem

  1. Upgrade from v0.55.3
  2. Try to log in.

## Specifications

  - OpenMPTCProuter version: 0.56beta9
  - OpenMPTCProuter VPS version: latest - can't tell as I cannot log in ...
  - OpenMPTCProuter platform: RPI4 x86_64

**Comment by Ysurac** [comment]
Try to refresh browser cache.

**Comment by h45h3ncryp73d** [comment]
> 
> 
> Try to refresh browser cache.

Funny ... That helped ... I tried in Chromium and Firefox and I had the same problem in both browsers ... So obviously clearing cache is necessary with this upgrade ... Thanks.

**Comment by Adorfer** [comment]
BTW: sometimes even refresh does not help: 
in this case: open "private browser window". It happens with several RouterUI-Pages, but Openwrt and it's forks are not exception.
