### ISSUE TITLE
VPN over OMR

### ISSUE THREAD

**Issue by ccmks** [Ysurac/openmptcprouter#1302]
I noticed that when I am using VPN behind my OMR, it doesn't do aggregation, such as OpenVPN, L2TP, SSTP, Softether, IPSec, and many more. It only pick one of active WAN connection to establish VPN connection. Do you know why it doesn't aggregate against VPN connection?

Thank you

**Comment by ccmks** [comment]
Anyone? Any answer?

**Comment by Ysurac** [comment]
This should work. If the VPN is over UDP, it use the VPN else it use shadowsocks. You can try another VPN.
You can also try snapshot release and try v2ray proxy.

**Comment by ccmks** [comment]
Where can I download the snapshot? I am using Hyper-V based router. Then how to use v2ray proxy and how does it work?

**Comment by Ysurac** [comment]
It's on the pinned issue: https://github.com/Ysurac/openmptcprouter/issues/1201
Then in wizard, advanced settings checkbox choose v2ray proxy.

**Comment by Adorfer** [comment]
>  VPN behind my OMR, it doesn't do aggregation

i can not confirme. here it still works on 2 OMRs. 


> Anyone? Any answer?

Issues not using the templates makes answering feel like shooting in the fog. perhaps the reason why so little replies yet
