### ISSUE TITLE
Adding ixgbevf driver

### ISSUE THREAD

**Issue by krissfr** [Ysurac/openmptcprouter#1308]
**Is this request related to a missing driver support for a particular hardware platform, SoC or board? Please describe.**
Hello,

i'm currently using the last 0.55 for x86_64 in a Proxmox virtual machine (qemu/kvm), with a virtio NIC and i work fine. But i wish to use the Virtual Function provided by my Intel dual 10Gb/s hypervisor NIC wich permit to dedicate a 10 Gb/s NIC.

The Virtual Function NIC need the ixgbevf driver in the Virtal Machine to be able to use the card.

**Describe why you are asking for this support?**
Can you please add Intel ixgbevf  driver in a next release ?

Thank you

Regards,

Christophe

**Comment by Ysurac** [comment]
This is added in develop branch, so this will be in next release.
