### ISSUE TITLE
Add new Interface

### ISSUE THREAD

**Issue by bobbykrin** [Ysurac/openmptcprouter#1311]
## Specifications

  - OpenMPTCProuter version: 
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter platform: 

**Hi all
How can i add a new Interface as i am already using 2 4g USB dongle and one Wifi.I want to add 3rd or 4th USB dongle.Is there any way ?**

**Comment by Ysurac** [comment]
You can add one in Network->Interfaces and click on "Add new interface"

**Comment by bobbykrin** [comment]
I tried to do as I add others but no success.I am not able to add more then 2 USB interfaces.

**Comment by Ysurac** [comment]
What is the error you have ?

**Comment by JeedHome44** [comment]
if I understand, to add a wifi interface like the connection sharing of a smartphone, so i need a wifi dongle on OMR by smartphone?

**Comment by bobbykrin** [comment]
> What is the error you have ?

when i try to add more then 2 USB Dongles the power of all dongles blinked and all of them restart constantly.

**Comment by Ysurac** [comment]
This looks like a power problem. Try to use a powered USB hub.

**Comment by bobbykrin** [comment]
Hi
Thanks for your guide.I use powered USB hub and its working great.4 Usb hub
and 1 hotspot.Brilliant.
Can I take WiFi output of Bonded network instead of using Ethernet cable
from Raspberry Pi?
