### ISSUE TITLE
why switched wan3 off?

### ISSUE THREAD

**Issue by ascomputer** [Ysurac/openmptcprouter#1313]
Sat Oct 24 14:29:05 2020 user.notice post-tracking-post-tracking: wan3 (eth3) switched off because ping from 192.168.8.100 error (80.67.169.12,80.67.169.40)
Sat Oct 24 14:29:06 2020 user.notice post-tracking-post-tracking: Delete default route via 192.168.8.1 dev eth3
Sat Oct 24 14:29:06 2020 user.notice post-tracking-post-tracking: Set server Server1 (95.141.XX.XX) default route 95.141.xx.xx nexthop via 192.168.43.1 dev wlan0 weight 1 nexthop via 192.168.11.1 dev eth4 weight 1

why switched wan3 off?

why do I report this error in the log and all of a sudden the wen 3 doesn't work for me anymore?
can someone help me understand? Thank you

**Comment by Adorfer** [comment]
looks like the OMR assumes that WAN3 can not reach the VPS (is offline, or provider has peering issues)

**Comment by Ysurac** [comment]
```wan3 (eth3) switched off because ping from 192.168.8.100 error (80.67.169.12,80.67.169.40)```
ICMP ping from wan3, that is eth3 and have ip 192.168.8.100, can't reach test ip 80.67.169.12 and 80.67.169.40. So it seems to be down.

**Comment by ascomputer** [comment]
Ok, but I don't know these test ip's can you remove and put different ip's?  if so where can i find them?  thank you for answering me

**Comment by Ysurac** [comment]
In Services->OMR-Tracker. But the problem was not the IPs, but the connection.

**Comment by ascomputer** [comment]
Yes, I agree with you that it is the connection ... I think that operator in this case has problems pinning to that ip and while on a different ip example google no ... I have to try ... thanks

**Comment by Ysurac** [comment]
Because you don't think at all that the connection had a problem ?

**Comment by ascomputer** [comment]
yes i think the connection had a problem.

**Comment by Adorfer** [comment]
To answer the initial question```

if the WAN3 connection had a problem 
  -> OMRtracker can not ping 'world' through WAN3 
  -> WAN3 is turned off for aggregation
OMR-tracker: keeps trying and if it detects world-connection on WAN3
- > reenable WAN3 for aggregation
```

**Comment by ascomputer** [comment]
Hi adorfer, I was doing a live streaming on Facebook and I had 3 4g connections (wan1 wan2 wan3) the wan3 as you saw in the log file is turned off.  Streaming on Facebook went on thanks to the other 2 wans.  but I think ... after an hour the wan3 did not restart even if the dongle was on and the public ip of wan3 was active ... I ask now It could be that the wan3 operator at that moment was having problems pinging that ip  control located in the omr-tracker?

**Comment by Adorfer** [comment]
It was turned off since the tracker considered the WAN3 having "not enough" connectivity. 
That's the function of the OMR-tracker. 

nevertheless: if the question is was it a) a false positive or b) a problem in the wan3/dialup-script, not returning online after a (short) problem: we can't say. Try to get more logs (pinging 8.8.8.8 via WAN3) next time it happens.

**Comment by ascomputer** [comment]
ok Adorfer, if it happens again I will try to get more info from log. thank you

**Comment by ascomputer** [comment]
however I want to say openmtptcp is currently with this version 0.55.3 r0 is very stable for what I do ... if we consider that when one connection stops and the others continue to work and a live stream does not drop. so honestly I have to say THANK YOU to those who designed all this ... then the details of perfecting it can be obtained slowly in the future. Thanks again to the designers.
