### ISSUE TITLE
Use wiregard instead of openvpn for mptcp over vpn 

### ISSUE THREAD

**Issue by brazzo97** [Ysurac/openmptcprouter#1314]
i found out using secondary modem with wireguard that using wireguard instead of openvpn helps a lot the reability of the connection , connection is more stable and vpn tunnel never goes down, this is needed by me because all the connection i have are 4g with high latency. if there is a way to do it with current version , or maybe could it be implemented ? Thanks

**Comment by Ysurac** [comment]
This need to bind to an interface, it's not easy with wireguard.

**Comment by brazzo97** [comment]
ok so cant be done ?

**Comment by Ysurac** [comment]
No idea. By default wireguard can't be binded to an interface, I don't know if there is another way to do that. Maybe...

**Comment by Adorfer** [comment]
this is a duplicate of https://github.com/Ysurac/openmptcprouter/issues/1252

**Comment by Malaga82** [comment]
it will be good, not to improve performance but for not reduce performance due to vpn ( with a vpn ping and bandwitdth are affected, since openvpn is not that light ).
