### ISSUE TITLE
Adding custom FFmpeg package including librtmp module

### ISSUE THREAD

**Issue by Mutanter** [Ysurac/openmptcprouter#1315]
**Is your feature request related to a problem? Please describe.**

My goal is to merge various RTMP inputs and use ffmpeg as mixer.
The two currently available FFmpeg versions in OMR are not compiled with the appropriate rtmp module (--enable-librtmp) and therefore not able to process RTMP inputs as expected. ([Operation not permitted](https://stackoverflow.com/questions/13138566/ffmpeg-windows-and-linux-version-operation-not-permitted-on-linux))

**Describe the solution you'd like**

There is a [prebuilt](https://github.com/openwrt/packages/pull/9475) FFmpeg openwrt [makefile](https://github.com/diizzyy/packages/blob/ffmpeg4-pkg/multimedia/ffmpeg4/Makefile#L69) that contains the appropriate librtmp module.
May it be possible to include the package in the standard repository of OMR?

Thanks in advanced!

**Comment by Ysurac** [comment]
I'm not sure this is really needed on a router.
This may be added, but I think I will add a new feeds for packets not directly related to OpenWrt.

**Comment by Mutanter** [comment]
Did you already started this mentioned and optional packet feed as i can't find the nginx nor the ffmpeg package in the current 56r0 anymore? Could also relate to the following error I get when retrieving the packet update:

Collected errors:
 * opkg_download: Failed to download http://packages.openmptcprouter.com/v0.56/aarch64_cortex-a72/luci/Packages.gz, wget returned 8.
 * opkg_download: Failed to download http://packages.openmptcprouter.com/v0.56/aarch64_cortex-a72/packages/Packages.gz, wget returned 8.
 * opkg_download: Failed to download http://packages.openmptcprouter.com/v0.56/aarch64_cortex-a72/base/Packages.gz, wget returned 8.
 * opkg_download: Failed to download http://packages.openmptcprouter.com/v0.56/aarch64_cortex-a72/routing/Packages.gz, wget returned 8.
 * opkg_download: Failed to download http://packages.openmptcprouter.com/v0.56/aarch64_cortex-a72/telephony/Packages.gz, wget returned 8.

Apart from the missing packages I rly like the 56.r0 so far!

**Comment by Ysurac** [comment]
I didn't yet made the optional feed, I will made some doc for new 0.56 features and I will work on this.
I fixed error on package update.
