### ISSUE TITLE
custom omr

### ISSUE THREAD

**Issue by zulu14** [Ysurac/openmptcprouter#1321]
hello, Ysurac

i have a question about the development of omr, you don't recompile a version with each test?

what tools / software did you use? do you use the feeds? I am a network engineer and I would be happy to contribute to the project. and initially try to find bugs and fix them.

have a nice day to you.

**Comment by Ysurac** [comment]
To compile I follow https://github.com/Ysurac/openmptcprouter/wiki/Create-image-for-unsupported-platform using custom OMR_FEED setting (there is many settings available for build.sh script).
When I need to test I recompile a new version (directly on the <platform>/source subdirectory via make) or copy changes directly on a running router (or I make changes on the router directly). Development tests are made under Virtualbox.

I don't use any special tools: a text-mode editor, git, sh,... I only use Linux as OS.

I use the feed I made and OpenWrt feeds.

I need to make a cleaner code on some part, but this will be done soon :)
