### ISSUE TITLE
How to enable a keep-alive ping to the VPS

### ISSUE THREAD

**Issue by Corrado56** [Ysurac/openmptcprouter#1324]
Hi, look at this screenshot
![image](https://user-images.githubusercontent.com/10588158/97480786-301baf00-1954-11eb-8536-129dc7628455.png)

What is the unit of measure ?
Where can I enable /disable Keep-alive messages ?

Thanks
Corrado Cavallini

**Comment by Ysurac** [comment]
It's ms.
You shouldn't change this setting.

**Comment by Corrado56** [comment]
ok, thanks
