### ISSUE TITLE
Update to 0.56.2 and 0.56.3 did no go well ?

### ISSUE THREAD

**Issue by G000R000** [Ysurac/openmptcprouter#1331]
Hello,

I'm a long time user of Openmptcprouter and i love it. This morning, i updated my raspberry3 to 0.56.2 (from 0.55.3).

I have 2 problems : 

1) I loose dhcp/internet on my computer randomly, it seems the Rasp is crashing, i have to reboot it,reset my network card, ipconfig /release /renew and it works and it works for a few minutes/hours

Sometimes, when i go on "Status", it seems that files are on lock : 
![image](https://user-images.githubusercontent.com/46853280/97783579-11f2c080-1b99-11eb-93eb-71943421fb40.png)
The output is not my VPS, i don't understand this IP. I then upgraded to 0.56.3 a few hours ago, same problem

On reboot, i got this before /release/renew, the version number are strange (0.56.3-bcexxxxx ?)

![image](https://user-images.githubusercontent.com/46853280/97783757-0c49aa80-1b9a-11eb-8203-a7f56a7035f4.png)

2) It seems i can't upgrade my VPS (Scaleway, debian 10) with command  "wget -O - https://www.openmptcprouter.com/server/debian10-x86_64.sh | sh"

It just run 1second and do nothing :
![image](https://user-images.githubusercontent.com/46853280/97783654-8a598180-1b99-11eb-9a07-80be9a90829d.png)

**Comment by Ysurac** [comment]
The release number on the router is not a problem (I will fix the display on another release) but the read only FS is a problem. Check that FS is really read only in State->Kernel log, and if it's the case try to write the image to a new SD card.
Else for errors on reboot, as it's said check time on router and VPS.

For the VPS as it seems to have a problem when checking about broken packages, try to do an ```apt-get update``` and if it's ok an ```apt-get upgrade```. If this changes nothing when you run the script again, try to reinstall the VPS.

**Comment by G000R000** [comment]
On the VPS, i did "apt-get update", than "apt-get upgrade" . The upgrade asked for a "dpkg --configure -a" that i did. Then did "apt-get upgrade" again. I rebooted and ran the script, and it worked ! the scripted updated a lot of stuff

For the raspberry, i did check in the kernel, it does seem in read-only
and i'm still randomly losing access to the RaspIP with ERR_CONNECTION_TIMED_OUT, then losing DHCP on the PC (i keep the IP but it's showing "not attributed by the router")

I'll buy a new SD card to test flashing it asap

![image](https://user-images.githubusercontent.com/46853280/97786890-dcf16880-1bae-11eb-9b27-cead4611ed1a.png)
![image](https://user-images.githubusercontent.com/46853280/97786933-1b872300-1baf-11eb-99d7-2afcc4bab16d.png)

**Comment by Ysurac** [comment]
You can try to write a new factory image to the SD, the SD is maybe not yet dead.
For the vmalloc problem, what is the image used ? It's a RPI4 ?

**Comment by G000R000** [comment]
It's a RPI3B, is used this file : openmptcprouter-v0.56.3-bce430e2-r0+14653-a439f1bb47-bcm27xx-bcm2709-rpi-2-ext4-sysupgrade.img

![image](https://user-images.githubusercontent.com/46853280/97788239-d5828d00-1bb7-11eb-9617-857b397a45b5.png)


I'll try to put a new image in SD, then restore settings maybe?

**Comment by Ysurac** [comment]
You should try 64bits image.
Yes you can put a new image and try to restore settings.

**Comment by G000R000** [comment]
ok i'm trying it now, i thought it was not compatible with "3B" seeing the title (Raspberry PI 3/3B+ (64-bits))

**Comment by G000R000** [comment]
I flashed the SD card with new factory image, than restored my settings. All is good !

Thanks again for your help, have a good night
