### ISSUE TITLE
[Feature] RPI4 booting headless

### ISSUE THREAD

**Issue by Adorfer** [Ysurac/openmptcprouter#1335]
OMR-version:  openmptcprouter v0.56.3-bce430e2

**problem:** 
current image for RaspberryPi-4 does require HDMI device plugged in, otherwise not booting. 

**solution:** 
modify "config.txt" in root of fat32-partition of SD-card. 
adding a line 
`hdmi_force_hotplug=1`
to config.txt
solves the problem. The Pi4 is running headless

**Comment by Ysurac** [comment]
Current image doesn't require HDMI device plugged in to boot.

**Comment by Adorfer** [comment]
can't reproduce anymore. closed.
