### ISSUE TITLE
Help me! ShadowSocks is not running

### ISSUE THREAD

**Issue by tomatojapan** [Ysurac/openmptcprouter#1341]
<img width="1048" alt="OpenMPTCProuter_-_ステータス_-_LuCI" src="https://user-images.githubusercontent.com/73946104/98115853-cb7bc980-1eea-11eb-82b0-70d38eb4df40.png">

添付のようなエラーが出ます。どうすればいいでしょうか？
I get an error like the attachment. What should i do?

**Comment by Ysurac** [comment]
Check that VPS admin key is good, that VPS was rebooted and if it's the case check State->System log.

**Comment by Adorfer** [comment]
i can just recommend to run the vps-script twice, with a reboot in between. Maybe not neccesary any more, but had been in the past, if was a "fresh debian".

**Comment by tomatojapan** [comment]
Thank you

I restarted my VPS and entered ShadowSocks Key, but I still get an error.

<img width="988" alt="OpenMPTCProuter" src="https://user-images.githubusercontent.com/73946104/98121927-48ab3c80-1ef3-11eb-9e7f-9b1ff32c7b46.png">

**Comment by zulu14** [comment]
check if you have any file in /tmp/etc/shadowsocks-libev/  (in the omr system, not vps)

**Comment by Ysurac** [comment]
The problem is not with shadowsocks but with the admin script that you can't contact. The only key needed is the "OpenMPTCProuter Server Key".
As I said, check State->System log to know why it's not possible to get a token.

**Comment by Ysurac** [comment]
Also one interface must be set as "Master" in the wizard.

**Comment by tomatojapan** [comment]
Thank you very much!!
It is worked!

<img width="997" alt="OpenMPTCProuter_-_ステータス_-_LuCI" src="https://user-images.githubusercontent.com/73946104/98125674-1223f080-1ef8-11eb-99f4-99a88608fd5b.png">

**Comment by tomatojapan** [comment]
Pocket WiFi 809SH does not recognize, is there a way to make it recognize?

**Comment by Ysurac** [comment]
No idea. You need to find the chipset used and then the needed driver.
