### ISSUE TITLE
How to get access to LTE modem from Internet

### ISSUE THREAD

**Issue by maximkabenin** [Ysurac/openmptcprouter#1346]
Hi, Installed this awesome solution at my parents country house and I need to get access to LTE modem web interface. Its connected via ethernet. 
I am in the city so for now I have access to VPS only.
Is there a way to somehow get access to modem's web UI from Internet? 
Also it would be nice to have access to OpenMPTCProuter from internet as well

**Comment by Ysurac** [comment]
The router have access to the modem, so you can do a port forward ( https://github.com/Ysurac/openmptcprouter/wiki/Port-forwarding ), but this open the modem interface on internet, you can restrict by IP but still not really good for security.
I think the best way is to use SSH port forwarding, this way you can have an encrypted tunnel between your computer and the modem interface.

**Comment by maximkabenin** [comment]
Thanks! Will try. In terms of SSH I just need to enable it for access from internet, right? 
The external IP would be the one that VPS has?

**Comment by Ysurac** [comment]
No, with SSH you can create the tunnel from your client to the modem, so at localhost.
You can use multiple SSH tunnel to access the router and then the modem, or use jumphost. I only use plain ssh on Linux, no idea about MobaXterm.

**Comment by maximkabenin** [comment]
I made settings like this. Its not working but I do not understand why 
![2020-11-29_14-55-07](https://user-images.githubusercontent.com/74040469/100541417-e83ebf00-3254-11eb-88b6-62699ef2deaa.png)
![2020-11-29_15-05-50](https://user-images.githubusercontent.com/74040469/100541415-e7a62880-3254-11eb-9a54-8df1857adc7c.png)
When I try to open MyVPS-IP:8094 I am transferred to url http://192.168.10.1/html/index.html?url=MyVPS-IP:8094
What am I doing wrong?

**Comment by Ysurac** [comment]
If you are transferred than redirection is working. Maybe a wrong configuration of the server on 192.168.10.1
