### ISSUE TITLE
hardware configuration

### ISSUE THREAD

**Issue by hi-wooya** [Ysurac/openmptcprouter#1349]
Hi，our hardware only 128MBye DDR，it can run openmptcprouter ？

**Comment by Adorfer** [comment]
OMR or VPS?

**Comment by hi-wooya** [comment]
OMR ，not VPS

**Comment by Ysurac** [comment]
No supported hardware have so little memory.
On a custom image, 128Mo seems really too short.

**Comment by hi-wooya** [comment]
OMR need minimum Memory（DDR）how many  ？

**Comment by hi-wooya** [comment]
our OMR just AP

**Comment by Ysurac** [comment]
May work with 256Mo, not sure. Should work with 512Mo. Work with 1024Mo

**Comment by Adorfer** [comment]
> OMR need minimum Memory（DDR）how many ？

I hardy doubt, that any ORM-platform still using DDR (and not  at least DDR3/DDR4) will fast enough for anything more than 50MBit/s total (with SQM enabled)
