### ISSUE TITLE
lost IPv6 after update to 0.56.4 0.1021 :-(

### ISSUE THREAD

**Issue by vinceducat** [Ysurac/openmptcprouter#1351]
## Expected Behavior

lost ipv6 connectity
## Current Behavior

lost the ipv6 connectivity after update omr from 0.56.3  to 0.56.4 and vps from 0.1020 to 0.1021
## Possible Solution

i dont no ;-)
## Steps to Reproduce the Problem

  1. update omr to 0.56.4
  2. update vps to 0.1021
  3. reboot omt and vps

## Specifications

  - OpenMPTCProuter version:  0.56.4
  - OpenMPTCProuter VPS version:  0.1021
  - OpenMPTCProuter platform: x86_64

**Comment by vinceducat** [comment]
[
![image](https://user-images.githubusercontent.com/18363979/98415579-d6b32e80-207d-11eb-956e-b4266f4e93dd.png)

**Comment by Ysurac** [comment]
You can try to validate the wizard again.

**Comment by Ysurac** [comment]
Check in Services->shadowsocks-libev that ss_redir local_address is "::".
Check on the VPS that you still have access to an IPv6 website with ```curl -6 www.google.com``` for example.

**Comment by vinceducat** [comment]
revalidate wizard many time ....

i will check for ss_redir and curl on vps ;-)

**Comment by vinceducat** [comment]
![ipv6_sho](https://user-images.githubusercontent.com/18363979/98441248-66e48880-20fd-11eb-953f-a1e19cea0bcc.jpg)

**Comment by vinceducat** [comment]
on vps
 
curl -6 www.google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="http://www.google.com/sorry/index?continue=http://www.google.com/&amp;q=EhAqAQT4DAwOGAAAAAAAAAABGJupmv0FIhkA8aeDSzdRXOCUJfuoWzAi-iAJNpNZp04kMgFy">here</A>.
</BODY></HTML>

**Comment by vinceducat** [comment]
` curl -6 www.google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="http://www.google.com/sorry/index?continue=http://www.google.com/&amp;q=EhAqAQT4DAwOGAAAAAAAAAABGJupmv0FIhkA8aeDSzdRXOCUJfuoWzAi-iAJNpNZp04kMgFy">here</A>.
</BODY></HTML>`

**Comment by vinceducat** [comment]
root@debian-2gb-nbg1-2:~# curl -6 www.google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="http://www.google.com/sorry/index?continue=http://www.google.com/&amp;q=EhAqAQT4DAwOGAAAAAAAAAABGJupmv0FIhkA8aeDSzdRXOCUJfuoWzAi-iAJNpNZp04kMgFy">here</A>.
</BODY></HTML>

**Comment by vinceducat** [comment]
for the moment just rool back to omr 0.56.3 and all is ok ;-)

**Comment by vinceducat** [comment]
and shadow param

![Sans titre](https://user-images.githubusercontent.com/18363979/98442313-1cb2d580-2104-11eb-9293-b4d5af1c3fe7.jpg)

**Comment by vinceducat** [comment]
@Ycarus i have a config with two vps, one in milkywan the other in hetzner

**Comment by Ysurac** [comment]
Do you get back IPv6 if you reboot the router ?

**Comment by vinceducat** [comment]
in 0.56.4 ? or in 0.56.3 ?

**Comment by vinceducat** [comment]
in 0.56.4 i try to reboot without best result ...

**Comment by vinceducat** [comment]
do you want a re upgrade to 0.56.4 ?

**Comment by Ysurac** [comment]
On 0.56.4, you can try to disable IPv6, save, and enable it again and save.
I will make some tests...

**Comment by vinceducat** [comment]
il will try this tomorrow needs a stable connection for this afternoon ... ;-)

**Comment by vinceducat** [comment]
reinstall 0.56.4 and always same pb even if i disable / enable ipv6 in the wizard...

**Comment by vinceducat** [comment]
erro reopen ..

**Comment by Ysurac** [comment]
I found the error. I compile a new snapshot and this should work this time.

**Comment by vinceducat** [comment]
ok i m waiting for the new snapshot ... ;-) Thanks
at this time 0.56.4 version date 07/11 ...

**Comment by vinceducat** [comment]
@Ysurac is the openmptcprouter-v0.56.4-r0+14653-a439f1bb47-x86-64-generic-ext4-combined.img.gz date 08/11 21:20 the last version ??

**Comment by vinceducat** [comment]
install this one seems to be good .... ;-) 

just to know what was the error ??

**Comment by Ysurac** [comment]
IPv6 route was not correctly added in some case.
Release v0.56.5 will be out tomorrow.

**Comment by vinceducat** [comment]
ok ;-)

**Comment by vinceducat** [comment]
seems to be ok with 0.56.5
