### ISSUE TITLE
Get WAN Public IP from omr router console

### ISSUE THREAD

**Issue by Malaga82** [Ysurac/openmptcprouter#1357]
Hello,
i see that from interface omr shows wan ip addresses, and i wish to grab them for some scripting.
I need 4G WAN in particular.
How can i retrieve them from console?
This is what i need:
![image](https://user-images.githubusercontent.com/3518802/98462631-ff3e4400-21b5-11eb-8b05-f48c91008fc0.png)

Thanks.
edit: if there are any api or anything else i can use fron LAN to retrieve them, it's well accepted.

**Comment by Ysurac** [comment]
On OpenMPTCProuter all data that are displayed in status page come from ubus: ```ubus call openmptcprouter status```.
This can be accessed via http, you an check OpenWrt doc for that.

**Comment by Malaga82** [comment]
Thanks, i think it's what i need.

**Comment by Malaga82** [comment]
i'm opening this for a question: is there a command to force re-check for the public IP it shows?
I have 4G connection and it's reporting a false, old ,public IP. But it's not getting updated.
Restarted but it still showing an old public ip for 4G connection.
I'm reading ASN, and this false reporting is an issue for some scripts, maybe someone can help me.

**Comment by Ysurac** [comment]
If external check are not disabled, IPs are updated about every hours.
To force update, ```uci del openmptcprouter.wan1.lc``` where "wan1" is the interface to force. IPs will be updated by scripts a few minutes after.

**Comment by Malaga82** [comment]
as always that command did the trick!
Are there side effects on launching the last command?
I explain a bit: when the 4G connection updates the IP i can get 2 different ASN, one is heavy filtered and high ping, the other is not filtered and much better ping, so when it comes, i must switch from the worst ASN to the other, and i have to be sure the IP get updated ASAP, launching then that command.
Thanks

**Comment by Ysurac** [comment]
It would be better to create a script and launch it via crontab that should be able to do that alone.

**Comment by Malaga82** [comment]
you mean crontab `uci del openmptcprouter.wan1.lc` ?

**Comment by Ysurac** [comment]
No. A crontab that check IP himself, check ASN, disconnnect/reconnect the 4G connection if needed.

**Comment by Malaga82** [comment]
i have that, but since `ubus call openmptcprouter status` got stuck with bad ip, i will rely on that `uci del ...` for updating the IP and then do all checks.
