### ISSUE TITLE
Loadbalancer multi VPS

### ISSUE THREAD

**Issue by kdecyllene** [Ysurac/openmptcprouter#1364]
Actuellement il est utilisé un VPS avec OpenMTCP mais  OVH ou Online prévois des maintenances coupant les VPS de manière temporaire . L'idée est donc de pouvoir mettre en oeuvre un loadbalancer permettant de basculer sur un autre VPS si celui ci est chargé ou indisponible . En infrastructure la concentration des services sur un seul point d'accès peut être un SPOF . Ce qui permettrai d'assurer la sécurité sur la connexion .

Merci

**Comment by Ysurac** [comment]
Il est déjà possible de configurer plusieurs VPS et de passer automatiquement à un autre en cas de défaillance.

**Comment by Randdrick** [comment]
Et ça marche très bien.
Par contre, il faut utiliser Shadowsocks comme proxy sur les serveurs, pour le moment.

**Comment by tboome33** [comment]
Bonsoir, c'est possible d'avoir un tuto pour configurer deux VPS ?

**Comment by Esysteme** [comment]
juste besoin de rajouter un serveur dans la page de config tout simplement

**Comment by tboome33** [comment]
Ah ok merci, et maintenant le contraire, utiliser un seul VPS pour deux installations ? Possible ?
