### ISSUE TITLE
Unable to move the image to the Router

### ISSUE THREAD

**Issue by rifaterdemsahin** [Ysurac/openmptcprouter#1368]
I downloaded this image to the USB

It booted up but it is missing many components and i was not sure how to move the image
https://twitter.com/rifaterdemsahin/status/1325909939521540097

Image I used
https://twitter.com/rifaterdemsahin/status/1325910424320012288

Script I could not trigger
https://twitter.com/rifaterdemsahin/status/1325911021840715783

I tried to move the image Error I got
https://twitter.com/rifaterdemsahin/status/1325915622778220545

Is there a way that has been done for this ? 

Device
This is the device i am installing on 
https://youtu.be/rfc2iSnOLsc

**Comment by rifaterdemsahin** [comment]
Also noted in twitter as a reference
https://twitter.com/rifaterdemsahin/status/1326538212722929667

**Comment by Ysurac** [comment]
Difficult to read...
So you can see boot screen but partitions are not mounted ? A driver may be needed but I would need more technical info about the device.

**Comment by rifaterdemsahin** [comment]
`Difficult to read`

Ok here are all the screenshots
Downloaded Image
![image](https://user-images.githubusercontent.com/5270036/98852879-40ea1b80-2450-11eb-82f0-88a56931edf7.png)

The machine starts like
![image](https://user-images.githubusercontent.com/5270036/98852930-52cbbe80-2450-11eb-9756-07fc16db9c5f.png)

**Comment by rifaterdemsahin** [comment]
`So you can see boot screen but partitions are not mounted ? `

I cant see the partitions:

A driver may be needed but I would need more technical info about the device.

Device
![image](https://user-images.githubusercontent.com/5270036/98853373-ef8e5c00-2450-11eb-9c18-7811edd56aab.png)

Manufacturer
https://protectli.com/vault-6-port/

**Comment by rifaterdemsahin** [comment]
Maybe i should install over ESXI ?
https://protectli.com/kb/how-to-install-esxi-on-the-vault/

**Comment by vinceducat** [comment]
thsi device seems ton support ubuntu and other distro... 

did you try EFI and non EFI img ...

try 0.56.5 

do you try to start OMR on a usb key ?

**Comment by vinceducat** [comment]
why not start this device on usb key like ubunut or other distro and transfert image to SSD
with

gunzip openmptcprouter-*.img.gz
dd bs=4M if=openmptcprouter-*.img of=/dev/sdX conv=fsync

**Comment by vinceducat** [comment]
https://protectli.com/kb/how-to-create-a-bootable-usb-drive-for-software-installation/

**Comment by vinceducat** [comment]
u seems to be log via SSH on OMR i dont understand why ???

**Comment by rifaterdemsahin** [comment]
> u seems to be log via SSH on OMR i dont understand why ???
> 
> why do you want to launch this script, to copy image u seems to be on an OMR working because u are log in ssh on OMR ...
> 
> my idea : launch your device with ubuntu / debian on a live usb.
> 
> get OMR img from the web site..
> 
> transfert the image to the ssd..
> 
> relaunch and select ssd in te boot

I tried and failed
https://twitter.com/rifaterdemsahin/status/1326667556535603200?s=19

![20201111_231856](https://user-images.githubusercontent.com/5270036/98876113-7a814d80-2475-11eb-9f80-708018dd40b5.jpg)

**Comment by rifaterdemsahin** [comment]
There is only one drive left
![16051375961551933502781396734576](https://user-images.githubusercontent.com/5270036/98876478-4bb7a700-2476-11eb-87f9-7b130a868e72.jpg)

MaYbe my image should not be the generic x64 one ?

**Comment by vinceducat** [comment]
Get the last on...

**Comment by rifaterdemsahin** [comment]
This also did not work
![Screenshot_20201111-233629_Chrome](https://user-images.githubusercontent.com/5270036/98876738-d00a2a00-2476-11eb-9462-49a95eda57ec.jpg)

**Comment by vinceducat** [comment]
https://www.openmptcprouter.com/download

**Comment by rifaterdemsahin** [comment]
![Uploading Screenshot_20201111-233925_Chrome.jpg…]()

**Comment by vinceducat** [comment]
If you create an usb omr usb under winfows with img and software like etcher is this usb key with omr start?

**Comment by vinceducat** [comment]
Under an usb live key with unbuntu is the ssd reconized? Is the sss active in bios?

**Comment by rifaterdemsahin** [comment]
Ssd active in bios
![-uz5ad1](https://user-images.githubusercontent.com/5270036/98877298-114f0980-2478-11eb-93a8-6f4de604ab15.jpg)

**Comment by rifaterdemsahin** [comment]
I did install Ubuntu to the ssd.
Ssd works on that box

**Comment by vinceducat** [comment]
So 1st is ssd 2nd is usb key ? Like 3rd

**Comment by rifaterdemsahin** [comment]
With usb omr the box starts but I can't find the ssd when I start with omr usb key.

Should I install debian 
And do
https://github.com/Ysurac/openmptcprouter/wiki/Create-image-for-unsupported-platform

**Comment by rifaterdemsahin** [comment]
P0 is the ssd

**Comment by vinceducat** [comment]
If you start a unbuntu live usb is the ssd reconized?

**Comment by rifaterdemsahin** [comment]
If you start a unbuntu live usb is the ssd reconized?

Yes

**Comment by vinceducat** [comment]
Is ubuntu reconized ssd?

**Comment by vinceducat** [comment]
So from ubuntu transfert omr img to the ssd...

**Comment by vinceducat** [comment]
What is the name of the device under ubuntu? Sdx? Sdb sdc??

**Comment by vinceducat** [comment]
Download img with wget of from the web browser under ubuntu...

Then i a terminal...

gunzip omr-*.img.gz
dd bs=4M if=omr-*.img of=/dev/sdX conv=fsync

**Comment by vinceducat** [comment]
Wtah was the result?

**Comment by rifaterdemsahin** [comment]
**Is ubuntu reconized ssd?**
yes I can install ubuntu on to the box

**So from ubuntu transfert omr img to the ssd...**
How can I transfer if it is a running image
I tried movinng the image with dd from usb key but that throw the errror or : unknow file system

**What is the name of the device under ubuntu? Sdx? Sdb sdc??**
sda5


**Wtah was the result?**
I ran dd bs=4M if=omr-.img of=/dev/sdX conv=fsync
I got After boot :  unknown file system

**Comment by rifaterdemsahin** [comment]
![Uploading Screenshot_20201111-233006_Twitter.jpg…]()

**Comment by rifaterdemsahin** [comment]
https://twitter.com/rifaterdemsahin/status/1326667556535603200?s=09

**Comment by rifaterdemsahin** [comment]
ubuntu sees sda5
![image](https://user-images.githubusercontent.com/5270036/98878887-026a5600-247c-11eb-8f14-3a9857314970.png)

 and dd command should have worked but i get
![image](https://user-images.githubusercontent.com/5270036/98878895-0e561800-247c-11eb-9b75-77d904fe479e.png)

**Comment by vinceducat** [comment]
I think hou mixed some... 

1st launcj ubunutu live usb... dont install ubuntu on ssd just launch.. in live usb start. You will have a system wotking... 
Dowload under ubunutu from website the img for x86-64 ... 

Open in uvuntu a terminql and gunzip and dd to the ssd. Shutdown rdmove usb restart.. and launch the system on the ssd

**Comment by rifaterdemsahin** [comment]
`I think hou mixed some...

1st launcj ubunutu live usb... dont install ubuntu on ssd just launch.. in live usb start. You will have a system wotking...
Dowload under ubunutu from website the img for x86-64 ...

Open in uvuntu a terminql and gunzip and dd to the ssd. Shutdown rdmove usb restart.. and launch the system on the ssd`

I did all proof
![Uploading image.png…]()

and i got the error
![image](https://user-images.githubusercontent.com/5270036/98879153-c08ddf80-247c-11eb-95fe-411404c75461.png)

**Comment by rifaterdemsahin** [comment]
maybe something wrong with the image.
I am too tired and need to go to sleep 

the VPS is runnning i would try to set the OMR if i can tomorrow.
Maybe installing debian is the way to go ?

**Comment by vinceducat** [comment]
After relaunch omr system will start on ssd....
After that system should be accessible ...throught browser via another machine on your networh

**Comment by vinceducat** [comment]
I think there is a problem du to your many try...probleme with grub.... not with omr ... because system stop in grub...  perhaps @Ysurac can help now....

**Comment by rifaterdemsahin** [comment]
`i could not move the image`
even though i thought i did or the image is corrupted
![image](https://user-images.githubusercontent.com/5270036/98879448-7c4f0f00-247d-11eb-84c7-5a9bc3d464de.png)

**Comment by vinceducat** [comment]
The error is ghat the dd command is sda not sda5 .....

**Comment by rifaterdemsahin** [comment]
I will try this one more time
https://protectli.com/kb/how-to-create-a-bootable-usb-drive-for-software-installation/

**Comment by vinceducat** [comment]
Try to replace sda5 by sda.....

**Comment by vinceducat** [comment]
> I will try this one more time
> https://protectli.com/kb/how-to-create-a-bootable-usb-drive-for-software-installation/

Try first to replace sda5 with sda😉

**Comment by rifaterdemsahin** [comment]
Also can't get the drive names
![Uploading 16051411108992433693950771969403.jpg…]()

**Comment by rifaterdemsahin** [comment]
> Try to replace sda5 by sda.....

I will give it a try

**Comment by vinceducat** [comment]
Please dont send so big image is difficilt to load for me...

**Comment by vinceducat** [comment]
Let me know if it is ok ..

**Comment by rifaterdemsahin** [comment]
Could be sda as spam is under sda

![16051416869131644440196065850290](https://user-images.githubusercontent.com/5270036/98880515-d18c2000-247f-11eb-8f54-fb60c4ccd683.jpg)

**Comment by vinceducat** [comment]
Sorry dont understand...

**Comment by vinceducat** [comment]
Just try the dd command with /dev/sda

**Comment by vinceducat** [comment]
Sda is your ssd 500Go and sdb your usb key 128Go right...

**Comment by rifaterdemsahin** [comment]
![16051420125198681384707492775681](https://user-images.githubusercontent.com/5270036/98880847-963e2100-2480-11eb-85d0-4b6fcf01ebce.jpg)

**Comment by rifaterdemsahin** [comment]
Sda worked i got stuck 

At something different i used the first efi image 
![16051421282067375071282724433390](https://user-images.githubusercontent.com/5270036/98880965-dac9bc80-2480-11eb-9acd-94fb36502801.jpg)

**Comment by vinceducat** [comment]
Its better..

**Comment by rifaterdemsahin** [comment]
Thanks  lot by the way

**Comment by vinceducat** [comment]
You have a probleme with efi in bios try to disable efi signature or option mike that...

**Comment by vinceducat** [comment]
Have you check that omr image is not corrupt after download with sha256 sum.. just ho be sur

**Comment by rifaterdemsahin** [comment]
From the boot sequence I selected uefi

And I now got stuck here

![16051425478687611712526709405848](https://user-images.githubusercontent.com/5270036/98881419-d81b9700-2481-11eb-949c-f85a900af342.jpg)

**Comment by vinceducat** [comment]
https://forums.gentoo.org/viewtopic-t-1112264-start-0.html leave efi boot but disable secure boot

**Comment by vinceducat** [comment]
> From the boot sequence I selected uefi
> 
> And I now got stuck here
> 
> ![16051425478687611712526709405848](https://user-images.githubusercontent.com/5270036/98881419-d81b9700-2481-11eb-949c-f85a900af342.jpg)

Is it starting or stop at this point

**Comment by vinceducat** [comment]
What are the efi option in the bios menu?

**Comment by rifaterdemsahin** [comment]
![20201112_010225](https://user-images.githubusercontent.com/5270036/98881837-d30b1780-2482-11eb-8398-237e2accd48b.jpg)
![Screenshot_20201112-010149_Chrome](https://user-images.githubusercontent.com/5270036/98881844-d4d4db00-2482-11eb-8792-45ed9db50132.jpg)
![Screenshot_20201112-010130_Chrome](https://user-images.githubusercontent.com/5270036/98881848-d56d7180-2482-11eb-8f96-a58fec725442.jpg)
![20201112_005951](https://user-images.githubusercontent.com/5270036/98881852-d56d7180-2482-11eb-9c97-018ea8b7dda8.jpg)
![20201112_005918](https://user-images.githubusercontent.com/5270036/98881857-d69e9e80-2482-11eb-8040-855bf85d8875.jpg)

**Comment by rifaterdemsahin** [comment]
Now I am stuck and it says booti  openmptcprouter
![16051430415616047423003143312118](https://user-images.githubusercontent.com/5270036/98881913-fcc43e80-2482-11eb-8dd6-3f2b5c151b7b.jpg)

**Comment by vinceducat** [comment]
Try to put efi and legacy... 

Have hou check that the omr image was not corrupt after download...to check if image is really good or not

**Comment by rifaterdemsahin** [comment]
Grub opened up at 3rd reset

![20201112_011236](https://user-images.githubusercontent.com/5270036/98882476-46f9ef80-2484-11eb-9bc8-321f3de9e839.jpg)
![20201112_011219](https://user-images.githubusercontent.com/5270036/98882479-48c3b300-2484-11eb-9b22-0f1d0abcb6d1.jpg)
![20201112_011150](https://user-images.githubusercontent.com/5270036/98882482-49f4e000-2484-11eb-95c2-7f4752580d5d.jpg)
![20201112_011131](https://user-images.githubusercontent.com/5270036/98882484-4a8d7680-2484-11eb-87bb-6658b857e283.jpg)
![20201112_011128](https://user-images.githubusercontent.com/5270036/98882486-4bbea380-2484-11eb-9eec-4c1e75f8e375.jpg)
![20201112_011112](https://user-images.githubusercontent.com/5270036/98882489-4cefd080-2484-11eb-8353-a395ef64a568.jpg)

**Comment by rifaterdemsahin** [comment]
Doing a checksum check

**Comment by rifaterdemsahin** [comment]
Looks the same will retry than go and sleep
![16051440178798590155692363946232](https://user-images.githubusercontent.com/5270036/98882917-431a9d00-2485-11eb-9cfa-0b16550d2968.jpg)

**Comment by rifaterdemsahin** [comment]
Now the router is in a loop of restarting and entering bios

![20201112_012741](https://user-images.githubusercontent.com/5270036/98883697-83c6e600-2486-11eb-8042-44b80c7bdf84.jpg)
![20201112_012651](https://user-images.githubusercontent.com/5270036/98883699-8590a980-2486-11eb-88f3-50dec08250b2.jpg)

**Comment by rifaterdemsahin** [comment]
I am contacting the manufacturer support@protectli.com

as it entered into a booting loop

**Comment by rifaterdemsahin** [comment]
![image](https://user-images.githubusercontent.com/5270036/98884554-36e40f00-2488-11eb-97eb-bafe1a1ab828.png)

**Comment by rifaterdemsahin** [comment]
after uploading defaults and reloading the router opened up. I will try to connect

**Comment by vinceducat** [comment]
> Sda worked i got stuck
> 
> At something different i used the first efi image
> ![16051421282067375071282724433390](https://user-images.githubusercontent.com/5270036/98880965-dac9bc80-2480-11eb-9acd-94fb36502801.jpg)

After re reading the post i think it was the best result you had. So the question is why this data corruption... 
Error in dd command... or other problem

**Comment by rifaterdemsahin** [comment]
I have solved after doing the sda update and the bios reset

now started setting the interfaces
https://twitter.com/rifaterdemsahin/status/1326791203602493440

**Comment by vinceducat** [comment]
> I have solved after doing the sda update and the bios reset
> 
> now started setting the interfaces
> https://twitter.com/rifaterdemsahin/status/1326791203602493440

What do you understand by sda update???
