### ISSUE TITLE
Can't access my VPS after VPS upgrade to 0.56

### ISSUE THREAD

**Issue by philby2530** [Ysurac/openmptcprouter#1371]
Good morning,
I tried to upgrade both de router and the VPS to the new 0.56 release 
After I upgraded the VPS (on Debian 10] and triggered a reboot (I had to enter the name of the machine as instructed).

Now, I cannot access anymore my Milkywan VPS.

Any hint on how I can investigate the issue?
Thanks for your help.
Philippe

**Comment by Ysurac** [comment]
If you can't access the VPS, contact Milkywan to check why.

**Comment by tekmedm** [comment]
I have same trouble on OVH.. seems than ssh login lost new install VPS won't repair trouble

**Comment by Ysurac** [comment]
On OVH you have access to a KVM, so you should be able to see what is the problem.

**Comment by philby2530** [comment]
My problem is resolved. Milkywan just reboot my VM. They had a small issue on their side that was preventing the correct reboot. SOlved for now. Thaks.

**Comment by tekmedm** [comment]
There is no problem reported, checked fs on rescue mode, changed password no, checked sshd configuration also 

Ssh : Permission denied, please try again.

debian@vps-xxxxxxxxxxxxxx.vps.ovh.net's password: 

 

 

De : "Ycarus (Yannick Chabanois)" <notifications@github.com>
Répondre à : Ysurac/openmptcprouter <reply@reply.github.com>
Date : vendredi 13 novembre 2020 à 10:22
À : Ysurac/openmptcprouter <openmptcprouter@noreply.github.com>
Cc : tekmedm <tekmed.m@gmail.com>, Comment <comment@noreply.github.com>
Objet : Re: [Ysurac/openmptcprouter] Can't access my VPS after VPS upgrade to 0.56 (#1371)

 

On OVH you have access to a KVM, so you should be able to see what is the problem.

**Comment by Ysurac** [comment]
As the initial issue is solved, you can open a new issue.
But this issue seems unrelated to OpenMPTCProuter, the only change on SSH is the port, no change on configuration or password.
