### ISSUE TITLE
Freeze on RPI3b+ step 802.1q: Adding Vlan 0 to HW Filter on device wan2

### ISSUE THREAD

**Issue by tekmedm** [Ysurac/openmptcprouter#1375]
## Possible Solution
First run for a fresh installed RPI 3b+, 16gb xD flash 
used openmptcprouter-v0.56.5-r0+14653-a439f1bb47-bcm27xx-bcm2710-rpi-3-ext4-sysupgrade.img.gz

## Steps to Reproduce the Problem
  1.flash xD
  2.connect RPI to power 
  3. first run freeze

## Context (Environment)
First run, installation from scratch

## Specifications

  - OpenMPTCProuter version: tried both 0.56.5 / 0.56.3 / 0.55.1 x86 or [x64](url)
  - OpenMPTCProuter VPS version: N/A
  - OpenMPTCProuter platform: RPI3+

here is screenshot : https://ibb.co/h7Dj8s9

**Comment by Ysurac** [comment]
Log seems ok, press a key and you should see login but the webpage should already be available at http://192.168.100.1/

**Comment by tekmedm** [comment]
haven’t connect keyboard, you’re right now working fine

Thanks Yannick.

 

Please what about my VPS ?

 

De : "Ycarus (Yannick Chabanois)" <notifications@github.com>
Répondre à : Ysurac/openmptcprouter <reply@reply.github.com>
Date : vendredi 13 novembre 2020 à 10:58
À : Ysurac/openmptcprouter <openmptcprouter@noreply.github.com>
Cc : tekmedm <tekmed.m@gmail.com>, Author <author@noreply.github.com>
Objet : Re: [Ysurac/openmptcprouter] Freeze on RPI3b+ step 802.1q: Adding Vlan 0 to HW Filter on device wan2 (#1375)

 

Log seems ok, press a key and you should see login but the webpage should already be available at http://192.168.100.1/

**Comment by tekmedm** [comment]
Not a bug, thanks Yannick

**Comment by tekmedm** [comment]
If VPS with Debian 10, freeze on reboot with a message about cirrus board..

**Comment by tekmedm** [comment]
Yannick,


I should reopen bug

After some reboot lost ip (DHCP failure I guess) and then I change to a 
fixed IP no success, no web interface now.

Kind regards,
Mehdi

**Comment by Ysurac** [comment]
Check that you don't have an IP conflict. If the router IP was not modified, and your client computer in same network, you can always ping 192.168.100.1
All DHCP server on the network must be disabled.

**Comment by tekmedm** [comment]
I found issue, no more trouble then
