### ISSUE TITLE
VPS provider : MVPS (confimed working)

### ISSUE THREAD

**Issue by kevin39** [Ysurac/openmptcprouter#1377]
Hi,
Wiki update suggestion.

I'm not related to this company, I'm just using them for many professional purposes.
I'm successfully testing MVPS since start of 2020. It works great. I'm using it as backup VPS and it saved me many times.

Thanks

**Comment by vinceducat** [comment]
what was the speed limit,
 not clear, is ipv64 ipv 6address ?

**Comment by kevin39** [comment]
IPv4 & IPv6 are both working.

My goal is not speed. Just test if you want to find the speed limit. 
On the cheapest VPS, I successfully reached 70-80mbs.

Check their website if you want more technical details.

**Comment by vinceducat** [comment]
_The uplink of our VPS is 1gbps shared. The guaranteed speed is 100Mbps for all our packages except the "VPS One" package for which the guaranteed speed is 70Mbps. If the allocated bandwidth is overused, the link will be limited to 1mbps permanently._

**Comment by vinceducat** [comment]
https://www.mvps.net/faq ... more detail

**Comment by Ysurac** [comment]
I added it to the list. Thanks
