### ISSUE TITLE
Assign ip for one lan

### ISSUE THREAD

**Issue by Roken120** [Ysurac/openmptcprouter#1379]
Hello,
Is possible to assign a ip to one client in lan ?

**Comment by Ysurac** [comment]
If you mean via DHCP, yes it's in Network->DHCP&DNS, and "Static leases"

**Comment by Roken120** [comment]
No, i can assign a public ip to a lan ip ?

**Comment by Ysurac** [comment]
LAN are by definition local.
But if you have a VPS with multiples IPs, you can output/input via one of these IP: https://github.com/Ysurac/openmptcprouter/wiki/VPS-Multi-IPs

**Comment by Adorfer** [comment]
i would like to have the public IP on the LAN (e.g. on "LAN2"), so that the machine uses the public IP on his interface. 
(and not using a private RFC1918 on it's interface)
