### ISSUE TITLE
Cost of Running a VPS

### ISSUE THREAD

**Issue by rifaterdemsahin** [Ysurac/openmptcprouter#1380]
It is 1 core Debian the main cost is the egress cost
Any work arounds for this ?

![image](https://user-images.githubusercontent.com/5270036/99183472-e7c20680-2733-11eb-9c5f-c424914dda04.png)
![image](https://user-images.githubusercontent.com/5270036/99183440-adf10000-2733-11eb-9d92-7a850d9c8868.png)

I did select GCP as it was easier to setup and it worked. The concern is the traffic is too expensive

**Comment by kevin39** [comment]
Hi,
As far I think, Cloud provider are not the best choice for this purpose. Same problem with AWS.

Renting a VPS or a dedicated server with your instances may be a cheapest solution.

**Comment by Ysurac** [comment]
True. The VPS part only use is the bandwidth, so you have to find a provider with unlimited traffic or with a high traffic limit. As you seems to be in UK, there is some.
Cloud platform are always really expensive, I still can't understand why AWS and GCP are so much used...

**Comment by Malaga82** [comment]
Well, you can rent a VPS like on vultr or digitalocean, there should be an UK location, or any other renter.
Just find one where you have best latency and down/up you need, on traffic maybe something like 2-5TB is enough.
Check the VPS IP is not banned on some services, it happens more often than you think.

**Comment by Adorfer** [comment]
This "cost" only applies to google cloud, correct?
So this ticket ist about google cloud? Or any cloud provider?
(i do not understand the goal of this issue. You did deliberatly did not follow the recommendations in the documentation and now you are looking at a 239gbp-bill?)

**Comment by Ysurac** [comment]
OVH and Hostworld seems to be available in UK with unlimited traffic.

**Comment by rifaterdemsahin** [comment]
I am right now turning off the GCP as it looks like i spend aroung
![image](https://user-images.githubusercontent.com/5270036/99190720-2b326a00-2760-11eb-9d75-e895a9520b3a.png)\
https://toolstud.io/data/bandwidth.php?compare=pci&speed=30&speed_unit=Mbps
9 TB per month which would run up to 1200 pounds..
I did catch it at 300. I had the free credits...still it sucks to lose them but that is cost of being an early adaptor.

OVH looks promising
![image](https://user-images.githubusercontent.com/5270036/99190781-6cc31500-2760-11eb-9555-9e469242b888.png)
https://www.ovh.com/manager/#/

**Comment by rifaterdemsahin** [comment]
got stuck at the fraud check would try them thoug and I would see the response times
![image](https://user-images.githubusercontent.com/5270036/99191236-4a7ec680-2763-11eb-9cec-5def8888b9c2.png)

**Comment by rifaterdemsahin** [comment]
I was able to work around the issue spending 2 hours plus 20 pounds with the team
https://twitter.com/rifaterdemsahin/status/1328024971407450114

I would also test the VPS support service. I dont expect a 24 hour return if they can it is great.

Compared 1o 1000 dollars 10 dollars cost on unlimited VPS would bd be great 

I would let the thread know about the performance

**Comment by rifaterdemsahin** [comment]
1200 dolar GCP Cost
![image](https://user-images.githubusercontent.com/5270036/99192069-b879bc80-2768-11eb-9ec8-be0bc3450566.png)

**Comment by rifaterdemsahin** [comment]
10 dollar VPS from hosting word speed
![image](https://user-images.githubusercontent.com/5270036/99192172-59687780-2769-11eb-88d3-7cc7fc8e0e3e.png)

**Comment by rifaterdemsahin** [comment]
@Ysurac if i have 2 VPS servers added how does that work?
Would I be able to failover to the other VPS or can I use them at the same time for some traffic?

**Comment by rifaterdemsahin** [comment]
Response was timely
![image](https://user-images.githubusercontent.com/5270036/99193266-d565be00-276f-11eb-946b-fbcf077fdcd5.png)

https://portal.hostworld.uk/viewticket.php?tid=371456&c=7o7X8ria

**Comment by Ysurac** [comment]
> @Ysurac if i have 2 VPS servers added how does that work?
> Would I be able to failover to the other VPS or can I use them at the same time for some traffic?

This only permit failover. Not possible to use them at the same time.

**Comment by rifaterdemsahin** [comment]
today the vps failed 
![image](https://user-images.githubusercontent.com/5270036/101934223-2f25a080-3bd5-11eb-8e87-ffb2646c8316.png)

maybe due to a bill
 it is better to have 2 VPS instead of one.
thanksfor the fail over functionality @Adorfer @Ysurac

**Comment by rifaterdemsahin** [comment]
cost is rising 
![image](https://user-images.githubusercontent.com/5270036/101934544-a52a0780-3bd5-11eb-964b-029c96abaa17.png)
