### ISSUE TITLE
the report missing 2 interfaces at reporting

### ISSUE THREAD

**Issue by rifaterdemsahin** [Ysurac/openmptcprouter#1382]
I expect to see 5 wan 1 lan

![image](https://user-images.githubusercontent.com/5270036/99195816-0221d180-2780-11eb-905a-34c8a48a1347.png)
![image](https://user-images.githubusercontent.com/5270036/99195822-064def00-2780-11eb-9bee-a8917de3d10f.png)

Also I cans ee the total of 5 interfaces

Powered by openmptcprouter v0.56.5 r0+14653-a439f1bb47

**Comment by Ysurac** [comment]
You have to add them if you want them in configuration tab.

**Comment by rifaterdemsahin** [comment]
lol that was an easy fix
![image](https://user-images.githubusercontent.com/5270036/99230080-c53cf580-27e6-11eb-9c3c-03c1a705e7ad.png)
