### ISSUE TITLE
speed is not ideal

### ISSUE THREAD

**Issue by logernLee** [Ysurac/openmptcprouter#1384]
I run this program on the mt7688(cpu:480MHz,  RAM:ddr2 256M,  flash:32M) board and compile the version of mini.During the test, I found that the overlay is not ideal, and even the speed of two network cards is not as fast as that of one network card. How can I solve these problems? Do you have any good suggestions.thank you.

**Comment by Ysurac** [comment]
The card is really slow. You can disable encryption but even with that this will never work well.

**Comment by logernLee** [comment]
How to disable encryption? And my print log always appears as follow:
Mon Nov 16 14:08:06 2020 daemon.warn odhcpd[3504]: A default route is present but there is no public prefix on lan thus we don't announce a default route!
Mon Nov 16 14:08:06 2020 daemon.err odhcpd[3504]: Failed to send to ff02::1%lan@eth0 (Permission denied)

Is it working properly?

**Comment by Ysurac** [comment]
In System->OpenMPTCProuter, "Advanced settings" checkbox

This is related to IPv6, this will be fixed in next release but this doesn't impact anything.

**Comment by logernLee** [comment]
Thank you for your reply.

**Comment by logernLee** [comment]
![error](https://user-images.githubusercontent.com/32033997/99517682-9ed7af80-29ca-11eb-9351-222f2169b56e.jpg)
there is something wrong in my web.
I can connect to VPN and proxy server with two 4G cards, but I can't connect to proxy server with three cards. What is the cause of this?
Could you tell me what happened?thank you.

**Comment by Ysurac** [comment]
Check log in State->System log.

**Comment by Adorfer** [comment]
What speed would you consider "ideal"? 
What is the speed you actually see currently "not ideal"?

**Comment by logernLee** [comment]
two 4G card should faster than one card

**Comment by Adorfer** [comment]
o.k, my misunderstanding! "card" does refer to USB-4G-modems!

what values do you get for 1 modem, 2 modem, 3 modem?
especially on LTE, if a cell is overloaded or the modems are "only 20cm apart" we saw, that the total bandwith "hard ceiling" for all adapters together. 

what does your mptcp-graph look like while doing tests?
do you see balaninc between adapters
![grafik](https://user-images.githubusercontent.com/10302493/99670673-2d9f0780-2a71-11eb-9a4a-a6d270fbe450.png)

**Comment by logernLee** [comment]
OK, I'll test it tomorrow. Thank you for your reply.

**Comment by logernLee** [comment]
The first picture is that I don't use the server (Download peak : 9.43mb/s, Upload peak: 2.26mb/s).

The second is a picture  using a card (Download peak : 5.05mb/s, Upload peak: 3.04mb/s),

The third is a picture using two cards (Download peak: 4.13mb/s, Upload peak: 4.35mb/s),

The fourth is a picture using three cards (Download peak: 3.06mb/s, Upload peak: 3.89mb/s).

eth0 is the network card that my device connects to the computer.

When I download, each card can also see traffic running.

![notUse](https://user-images.githubusercontent.com/32033997/99756261-b4162080-2b27-11eb-8bba-8af8a0dae658.png)
![oneCard_eth0_graph](https://user-images.githubusercontent.com/32033997/99756276-bd06f200-2b27-11eb-88f3-c8f85a7a65d5.png)
![twoCard_eth0_graph](https://user-images.githubusercontent.com/32033997/99756288-c42e0000-2b27-11eb-8d58-c8f99a186741.png)
![threeCard_eth0_graph](https://user-images.githubusercontent.com/32033997/99756358-efb0ea80-2b27-11eb-8368-357f3c443c1b.png)

**Comment by Adorfer** [comment]
sorry, you are looking into the wrong chart, please have look at the mptcp-stats, where you have "one color per WAN-interface".

**Comment by logernLee** [comment]
![Uploading N2QC6L)`JS(6EPRU63D@`VJ.png…]()

**Comment by logernLee** [comment]
![N2QC6L)`JS(6EPRU63D@`VJ](https://user-images.githubusercontent.com/32033997/99927973-3568ef80-2d82-11eb-8a23-fe42540f7826.png)

**Comment by Adorfer** [comment]
So the traffic looks well balanced between the LTE-radios.
if the total speed  "with 3" is like "with only one": Get at least 1m distance between the radios to reduce interference locally, let them look out of different windows of the building or try to point to different cell to towers. best: different Sim card with providers of really different networks (not just resellers of the same operator)

**Comment by logernLee** [comment]
but I use only one card:
![1](https://user-images.githubusercontent.com/32033997/99928984-6cd99b00-2d86-11eb-9dc5-7018a224552d.png)

**Comment by logernLee** [comment]
Is it the server problem？

**Comment by Adorfer** [comment]
I assume it's the cell or the consumer grade quality of the modems. (as stated in my previous comment)

**Comment by Ysurac** [comment]
For aggregation a proxy (by default Shadowsocks) and a VPN (by default glorytun TCP) are used. They are encrypted. And with the CPU of this board it's really limited. You can disable encryption in System->OpenMPTCProuter, "wizard" tab and "advanced settings" checkbox.
Check load average on the board during test, I think it's really high.

**Comment by logernLee** [comment]
thank you Ysurac,
Now I'm testing with another board(CPU:ipq4019).

**Comment by logernLee** [comment]
I use 4G modules(EC20),Dial with QMI. Connect to the board via USB.I don't know how to debug it(the cell or the consumer grade quality of the modems),Do you have any good suggestions, @Adorfer.
I've changed the cards of other operators, which seems to be useless.

**Comment by Adorfer** [comment]
what is the cpu load (graph) during the tests?
![grafik](https://user-images.githubusercontent.com/10302493/99944760-ba98d800-2d73-11eb-98fa-498351f09301.png)

**Comment by logernLee** [comment]
Is there a problem with the load?
![load](https://user-images.githubusercontent.com/32033997/99947462-fb641180-2db2-11eb-9661-750c2bb829b2.png)

**Comment by logernLee** [comment]
![cpuinfo](https://user-images.githubusercontent.com/32033997/99948279-33b81f80-2db4-11eb-9608-e5de853d4d64.png)

**Comment by Adorfer** [comment]
goal: 

  - on a single core CPU: never higher than 1
  - on a multicore-CPU: never higher than 50% of cores, since there is multicore-overhead

On a 4 core system: try to stay under load=2.

**Comment by logernLee** [comment]
OK,thanks for your reply.I tried to reduce the load.

**Comment by Adorfer** [comment]
?!? how? the load is caused by the traffic! You definitly need a faster system!

**Comment by Ysurac** [comment]
As I already said, possible to disable encryption, at least for testing.

**Comment by logernLee** [comment]
I've turned off encryption and SQM, but It's still the question.I'm trying other solutions.
