### ISSUE TITLE
Usage Information on Status Page

### ISSUE THREAD

**Issue by rifaterdemsahin** [Ysurac/openmptcprouter#1385]
**Is your feature request related to a problem? Please describe.**
I cant see how much the connection is getting utilized compared to other ones

**Describe the solution you'd like**
I need to see the ratio of the usage between each interface

**Describe alternatives you've considered**
add the last 5 minutes

**Additional context**
I do swap the interfaces and need to decide if the interfaces as i expect

**Comment by rifaterdemsahin** [comment]
![100 MB (1)](https://user-images.githubusercontent.com/5270036/99231519-a3dd0900-27e8-11eb-99e0-196de5b60890.png)

**Comment by Ysurac** [comment]
You can maybe use luci-app-nlbwmon or luci-app-statistics that can be installed via System->Software.

**Comment by rifaterdemsahin** [comment]
![image](https://user-images.githubusercontent.com/5270036/99235296-95452080-27ed-11eb-8f56-cf91f6134fda.png)


could not find it 

and how come i cant see the 480GB drive...
how do i extend the mount ?

**Comment by rifaterdemsahin** [comment]
![image](https://user-images.githubusercontent.com/5270036/99235512-d9d0bc00-27ed-11eb-92f9-3d6af7ea2aab.png)
![image](https://user-images.githubusercontent.com/5270036/99235549-e523e780-27ed-11eb-809f-46e2d123f4d2.png)

**Comment by rifaterdemsahin** [comment]
terminal also failed
![image](https://user-images.githubusercontent.com/5270036/99235735-1f8d8480-27ee-11eb-9c0a-d764030b26d9.png)

**Comment by rifaterdemsahin** [comment]
![image](https://user-images.githubusercontent.com/5270036/99235800-38963580-27ee-11eb-9c38-265fc0233392.png)

**Comment by rifaterdemsahin** [comment]
![image](https://user-images.githubusercontent.com/5270036/99235954-709d7880-27ee-11eb-979b-2250906c45f9.png)

**Comment by rifaterdemsahin** [comment]
collectd could be something differernt could not locate the luca one
![image](https://user-images.githubusercontent.com/5270036/99236099-a8a4bb80-27ee-11eb-8228-c4b28b47adf7.png)

**Comment by rifaterdemsahin** [comment]
![image](https://user-images.githubusercontent.com/5270036/99236256-e0136800-27ee-11eb-914c-60e8de5da250.png)
![image](https://user-images.githubusercontent.com/5270036/99236342-fc170980-27ee-11eb-8531-8640657e157f.png)

**Comment by rifaterdemsahin** [comment]
https://openwrt.org/packages/start
https://github.com/openwrt/luci/tree/master/applications/luci-app-nlbwmon


opkg install luci-app-nlbwmon
--

**Comment by rifaterdemsahin** [comment]
installed these 2 but no idea how to find them
![image](https://user-images.githubusercontent.com/5270036/99236746-7cd60580-27ef-11eb-9904-a7316dfd2707.png)

**Comment by rifaterdemsahin** [comment]
I need to find where this tab is
![image](https://user-images.githubusercontent.com/5270036/99237444-5ebcd500-27f0-11eb-857d-5269153453dd.png)

**Comment by rifaterdemsahin** [comment]
maybe a reboot needed

**Comment by Ysurac** [comment]
refresh page.

**Comment by rifaterdemsahin** [comment]
olaaa

![image](https://user-images.githubusercontent.com/5270036/99238123-44372b80-27f1-11eb-827c-cbe9ef12b3aa.png)

rebooted (👍 I should have refreshed lol

**Comment by rifaterdemsahin** [comment]
thanks @Ysurac 

you are the hero!
