### ISSUE TITLE
[Question] conf ipv6

### ISSUE THREAD

**Issue by Merrick28** [Ysurac/openmptcprouter#1386]
Hello, I'm quite a newbie concerning ipv6.
My vps has ipv6 activated, and I'd like to activate it on my router.

- is the ipv6 mandatory ? If yes, what should I use ? My ipv6 vps network ? Or another "random" ipv6 prefix ?

**Comment by Ysurac** [comment]
If you have a /48, /56,... you can use it as IPv6 prefix, else ULA IPv6 are used and prefix is generated.

**Comment by Merrick28** [comment]
Ok thanks, i will try.

**Comment by Adorfer** [comment]
It would be nice if "real v6 on OMR LAN" (instead of NAT7-ULA) would work work with /62 von VPS.

**Comment by Ysurac** [comment]
This can work I think. But when a proxy is used at output, this will still be VPS IP visible on Internet.

**Comment by Adorfer** [comment]
1) great
2) that is no issue for me. for methis is about clients prioritizing IPv4 over IP if they receive only ULA via RA.
