### ISSUE TITLE
master as he worst line

### ISSUE THREAD

**Issue by rifaterdemsahin** [Ysurac/openmptcprouter#1387]
does that matter ?

Can i select a different line and make it as default master ?

![image](https://user-images.githubusercontent.com/5270036/99249602-4c4b9700-2802-11eb-8a1b-f7c1ffab9f83.png)

I can just unplug it and move the FTTC fiber account to the first port if the first port is the master by default

**Comment by Ysurac** [comment]
Master should be set to the most stable interface even if it's the slower.
