### ISSUE TITLE
Many lines "list server '127.0.0.1#5353'" in /etc/config/dhcp

### ISSUE THREAD

**Issue by xabix** [Ysurac/openmptcprouter#1388]
## Expected Behavior
Hello

I see a lot of error messages like
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[22329]: exiting on receipt of SIGTERM
Mon Nov 16 14:43:17 2020 user.notice omr-bypass: OMR-ByPass is running
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: started, version 2.82 cachesize 150
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: DNS service limited to local subnets
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: compile time options: IPv6 GNU-getopt no-DBus UBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC no-ID loop-detect inotify dumpfile
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: using only locally-known addresses for domain test
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: using only locally-known addresses for domain onion
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: using only locally-known addresses for domain localhost
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: using only locally-known addresses for domain local
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: using only locally-known addresses for domain invalid
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: using only locally-known addresses for domain bind
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: using nameserver 127.0.0.1#5353
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: using nameserver 127.0.0.1#5353
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: using nameserver 127.0.0.1#5353
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: using nameserver 127.0.0.1#5353
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: using nameserver 127.0.0.1#5353
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: using nameserver 127.0.0.1#5353
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: using nameserver 127.0.0.1#5353
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: using nameserver 127.0.0.1#5353
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: using nameserver 127.0.0.1#5353
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: using nameserver 127.0.0.1#5353
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: using nameserver 127.0.0.1#5353
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: using nameserver 127.0.0.1#5353
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: using nameserver 127.0.0.1#5353
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: using nameserver 127.0.0.1#5353
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: using nameserver 127.0.0.1#5353
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: using nameserver 127.0.0.1#5353
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: using nameserver 127.0.0.1#5353
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: using nameserver 127.0.0.1#5353
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: using nameserver 127.0.0.1#5353
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: using nameserver 127.0.0.1#5353
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: using nameserver 127.0.0.1#5353
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: using nameserver 127.0.0.1#5353
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: using nameserver 127.0.0.1#5353
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: using nameserver 127.0.0.1#5353
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: using nameserver 127.0.0.1#5353
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: using nameserver 127.0.0.1#5353
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: using nameserver 127.0.0.1#5353
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: using nameserver 127.0.0.1#5353
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: using nameserver 127.0.0.1#5353
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: using nameserver 127.0.0.1#5353
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: using 93 more nameservers
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: read /etc/hosts - 4 addresses
Mon Nov 16 14:43:17 2020 daemon.info dnsmasq[27110]: read /tmp/hosts/dhcp.cfg01411c - 0 addresses
Mon Nov 16 14:43:18 2020 daemon.info glorytun: starting glorytun vpn instance vpn
Mon Nov 16 14:43:18 2020 user.notice omr-tracker: Launching...
Mon Nov 16 14:43:18 2020 user.notice omr-tracker: Launched
Mon Nov 16 14:43:18 2020 daemon.info omr-tracker-ss: Shadowsocks is up (can contact via http 1.1.1.1)
Mon Nov 16 14:43:19 2020 user.notice post-tracking-post-tracking: Tunnel up : Replace default route by 10.255.255.1 dev tun0

cat /etc/config/dhcp   

> config dnsmasq
>         option domainneeded '1'
>         option boguspriv '1'
>         option filterwin2k '0'
>         option localise_queries '1'
>         option rebind_localhost '1'
>         option local '/lan/'
>         option domain 'lan'
>         option expandhosts '1'
>         option authoritative '1'
>         option readethers '1'
>         option leasefile '/tmp/dhcp.leases'
>         option resolvfile '/tmp/resolv.conf.d/resolv.conf.auto'
>         option nonwildcard '1'
>         option localservice '1'
>         option noresolv '1'
>         option nonegcache '1'
>         list rebind_domain 'plex.direct'
>         option rebind_protection '0'
>         list server '127.0.0.1#5353'
>         list server '/use-application-dns.net/'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list server '127.0.0.1#5353'
>         list ipset '/googlevideo.com/omr_dscp-cs4,omr_dscp6-cs4'
>         list ipset '/nflxvideo.net/omr_dscp-cs4,omr_dscp6-cs4'
>         list ipset '/s3.ll.dash.row.aiv-cdn.net/omr_dscp-cs4,omr_dscp6-cs4'
>         list ipset '/d25xi40x97liuc.cloudfront.net/omr_dscp-cs4,omr_dscp6-cs4'
>         list ipset '/aiv-delivery.net/omr_dscp-cs4,omr_dscp6-cs4'
>         list ipset '/vevo.com/omr_dscp-cs4,omr_dscp6-cs4'
>         list ipset '/audio-fa.scdn.com/omr_dscp-cs4,omr_dscp6-cs4'
>         list ipset '/deezer.com/omr_dscp-cs4,omr_dscp6-cs4'
>         list ipset '/sndcdn.com/omr_dscp-cs4,omr_dscp6-cs4'
>         list ipset '/last.fm/omr_dscp-cs4,omr_dscp6-cs4'
>         list ipset '/v.redd.it/omr_dscp-cs4,omr_dscp6-cs4'
>         list ipset '/ttvnw.net/omr_dscp-cs4,omr_dscp6-cs4,omr_dscp-cs4,omr_dscp6-cs4'
>         list ipset '/googletagmanager.com/omr_dscp-cs2,omr_dscp6-cs2'
>         list ipset '/googleusercontent.com/omr_dscp-cs2,omr_dscp6-cs2'
>         list ipset '/google.com/omr_dscp-cs2,omr_dscp6-cs2'
>         list ipset '/fbcdn.net/omr_dscp-cs4,omr_dscp6-cs4,omr_dscp-cs2,omr_dscp6-cs2'
>         list ipset '/akamaihd.net/omr_dscp-cs2,omr_dscp6-cs2'
>         list ipset '/whatsapp.net/omr_dscp-cs2,omr_dscp6-cs2'
>         list ipset '/whatsapp.com/omr_dscp-cs2,omr_dscp6-cs2'
>         list ipset '/googleapis.com/omr_dscp-cs2,omr_dscp6-cs2'
>         list ipset '/1e100.net/omr_dscp-cs2,omr_dscp6-cs2'
>         list ipset '/hwcdn.net/omr_dscp-cs2,omr_dscp6-cs2'
>         list ipset '/download.qq.com/omr_dscp-cs1,omr_dscp6-cs1'
>         list ipset '/steamcontent.com/omr_dscp-cs1,omr_dscp6-cs1'
>         list ipset '/gs2.ww.prod.dl.playstation.net/omr_dscp-cs1,omr_dscp6-cs1'
>         list ipset '/dropbox.com/omr_dscp-cs1,omr_dscp6-cs1'
>         list ipset '/dropboxstatic.com/omr_dscp-cs1,omr_dscp6-cs1'
>         list ipset '/dropbox-dns.com/omr_dscp-cs1,omr_dscp6-cs1'
>         list ipset '/log.getdropbox.com/omr_dscp-cs1,omr_dscp6-cs1'
>         list ipset '/drive.google.com/omr_dscp-cs1,omr_dscp6-cs1'
>         list ipset '/drive-thirdparty.googleusercontent.com/omr_dscp-cs1,omr_dscp6-cs1'
>         list ipset '/docs.google.com/omr_dscp-cs1,omr_dscp6-cs1'
>         list ipset '/docs.googleusercontent.com/omr_dscp-cs1,omr_dscp6-cs1'
>         list ipset '/gvt1.com/omr_dscp-cs1,omr_dscp6-cs1'
>         list ipset '/mmg-fna.whatsapp.net/omr_dscp-cs1,omr_dscp6-cs1'
>         list ipset '/upload.youtube.com/omr_dscp-cs1,omr_dscp6-cs1'
>         list ipset '/upload.video.google.com/omr_dscp-cs1,omr_dscp6-cs1'
>         list ipset '/windowsupdate.com/omr_dscp-cs1,omr_dscp6-cs1'
>         list ipset '/update.microsoft.com/omr_dscp-cs1,omr_dscp6-cs1'
>         list ipset '/mafreebox.freebox.fr/omr_dst_bypass_wan1,omr6_dst_bypass_wan1'
>         list ipset '/tf1.fr/omr_dst_bypass_wan2,omr6_dst_bypass_wan2'
>         list ipset '/event.webinarjam.com/omr_dst_bypass_wan2,omr6_dst_bypass_wan2'
>         list ipset '/api.gcs.garmin.com/omr_dst_bypass_wan3,omr6_dst_bypass_wan3'
>         list ipset '/static.garmincdn.com/omr_dst_bypass_wan3,omr6_dst_bypass_wan3'
>         list ipset '/pkg.opnsense.org/omr_dst_bypass_wan2,omr6_dst_bypass_wan2'
> 
> config dhcp 'lan'
>         option interface 'lan'
>         option ra_slaac '1'
>         list ra_flags 'managed-config'
>         list ra_flags 'other-config'
>         option ignore '1'
>         option force '1'
>         option ra_default '1'
>         option dhcpv6 'server'
> 
> config dhcp 'wan'
>         option interface 'wan'
>         option ignore '1'
> 
> config odhcpd 'odhcpd'
>         option maindhcp '0'
>         option leasefile '/tmp/hosts/odhcpd'
>         option leasetrigger '/usr/sbin/odhcpd-update'
>         option loglevel '4'

## Steps to Reproduce the Problem

  1.Not sure but I believe that each time there is an update done the file gets added a new line?

## Specifications

  - OpenMPTCProuter version: v0.56.5 r0+14653-a439f1bb47
  - OpenMPTCProuter VPS version: 0.1022
  - OpenMPTCProuter platform: x86_64

I have remove the duplicates and now it looks like
![image](https://user-images.githubusercontent.com/394407/99261738-6777d000-281d-11eb-833d-516be96ed04d.png)

**Comment by Ysurac** [comment]
No, but possible it's due to an old bug that is now fixed.

**Comment by xabix** [comment]
thanks! Closing then if it shouldn't happen anymore :)
