### ISSUE TITLE
freebuffer full: reorder_buffer_size must be increased.

### ISSUE THREAD

**Issue by dettofatto** [Ysurac/openmptcprouter#1389]
## Current Behavior
In my status log I've a lot of " daemon.warn mlvpn[5102]: freebuffer full: reorder_buffer_size must be increased. "

I've switched to mlvpn, from glorytun tcp (that is ok.)
I don't have any other issues, but i can't read other infos

## Specifications

  - OpenMPTCProuter version: v0.56beta5-8398a092 r0+14639-2a90d308c7
  - OpenMPTCProuter VPS version: 0.1017
  - OpenMPTCProuter platform: RPI4

**Comment by Ysurac** [comment]
You can increase reorder buffer size in VPN->MLVPN

**Comment by dettofatto** [comment]
Yes! It was so simple...
Only for info mlvpn is much better on my 4g x2 line!
Thank you!
