### ISSUE TITLE
0.56.5 image for rpi4 seems to be corrupt

### ISSUE THREAD

**Issue by Fffrank** [Ysurac/openmptcprouter#1390]
## Expected Behavior

Tried to download the GZ archive and windows gives me an error while extracting. rpi4 downloads and unpacks but then the upgrade routine says its not a valid image.....

## Current Behavior

```
root@OpenMPTCProuter:/tmp# sysupgrade openmptcprouter-v0.56.5-r0\+14653-a439f1bb47-bcm27xx-bcm2709-r
pi-2-ext4-sysupgrade.img
Image metadata not found
Use sysupgrade -F to override this check when downgrading or flashing to vendor firmware
Reading partition table from bootdisk...
Reading partition table from image...
Image check failed.
```

## Steps to Reproduce the Problem

  1. wget https://download.openmptcprouter.com/release/v0.56.5/rpi2/targets/bcm27xx/bcm2709/openmptcprouter-v0.56.5
-r0+14653-a439f1bb47-bcm27xx-bcm2709-rpi-2-ext4-sysupgrade.img.gz
  2. gunzip *.gz
  3. sysupgrade openmptcprouter-v0.56.5
-r0+14653-a439f1bb47-bcm27xx-bcm2709-rpi-2-ext4-sysupgrade.img

## Specifications

  - OpenMPTCProuter version: 56.4
  - OpenMPTCProuter VPS version: 0.1021 5.4.74-mptcp
  - OpenMPTCProuter platform: RPI4B

**Comment by Ysurac** [comment]
You mustn't gunzip the image.
