### ISSUE TITLE
Port forwading

### ISSUE THREAD

**Issue by tekmedm** [Ysurac/openmptcprouter#1391]
I tried port forwarding to a server on lan for my webserver on local lan as described in existing documentation about that.
 title is Redirect port via VPN on OpenMPTCProuter
Example to redirect port 80 from the VPS to the IP 192.168.100.3 on the network

I can't seen any 192.168.100.3 ip address configuration only  192.168.100.16.. reproduce setup nothing routed.

All is up to date router and VPS.
Please help

**Comment by Ysurac** [comment]
I fixed the ip in the doc.

**Comment by tekmedm** [comment]
Please can you confirm by default zone source is always VPN ? 

 

De : "Ycarus (Yannick Chabanois)" <notifications@github.com>
Répondre à : Ysurac/openmptcprouter <reply@reply.github.com>
Date : mardi 17 novembre 2020 à 19:32
À : Ysurac/openmptcprouter <openmptcprouter@noreply.github.com>
Cc : tekmedm <tekmed.m@gmail.com>, Author <author@noreply.github.com>
Objet : Re: [Ysurac/openmptcprouter] Port forwading (#1391)

 

I fixed the ip in the doc.

**Comment by Ysurac** [comment]
yes, all forwarded traffic use VPN.

If you have issues, check https://github.com/Ysurac/openmptcprouter/wiki/Port-forwarding#debug

**Comment by tekmedm** [comment]
Thanks a lot Yannick

We have a huge disruption I’m trying to restore service using your amazing stuff  through 4G, we have 300Mbps link. 

Do you think I can also transfert OVH Toip Voice calls ad have a minimum quality  ? 

 

Regards,

Mehdi

 

De : "Ycarus (Yannick Chabanois)" <notifications@github.com>
Répondre à : Ysurac/openmptcprouter <reply@reply.github.com>
Date : mardi 17 novembre 2020 à 19:49
À : Ysurac/openmptcprouter <openmptcprouter@noreply.github.com>
Cc : tekmedm <tekmed.m@gmail.com>, Author <author@noreply.github.com>
Objet : Re: [Ysurac/openmptcprouter] Port forwading (#1391)

 

yes, all forwarded traffic use VPN.

If you have issues, check https://github.com/Ysurac/openmptcprouter/wiki/Port-forwarding#debug

**Comment by tekmedm** [comment]
Thanks Yannick

**Comment by Adorfer** [comment]
for the moment i can not get port-forwarding to work for ipv6. (for OMR55.3 it was working as far as i remember)
