### ISSUE TITLE
multiple LAN 

### ISSUE THREAD

**Issue by Maverick78de** [Ysurac/openmptcprouter#1395]
I was looking for a solution to setup an additional LAN (e.g. a guest network) on the router. I can add the Interfaces an configure them. I also can configure the firewall to seperate the 2 lan networks. But I can't find any solution to add an additional lan to the the settings wizzard. 
What other things are neccessary to do, to get a second lan network running?

**Comment by Maverick78de** [comment]
got it running

**Comment by davidmueller13** [comment]
How?

**Comment by BigFanOpenmptcprouter** [comment]
@Maverick78de I also would like to know how you set it up. I opened another issue https://github.com/Ysurac/openmptcprouter/issues/3609 asking basically for the same thing.
