### ISSUE TITLE
Question parametrage

### ISSUE THREAD

**Issue by constant1010** [Ysurac/openmptcprouter#14]
Bonjour,
J'attends avec impatience la nouvelle doc

Mais, n'etant pas à l'aise avec openwrt, j'aimerais connaitre le minimum de paramètre pour faire fonctionner le système, par exemple les différents endroit où rentrer l'ip du serveur vps, ou indiquer les dns, et s'il y a rentrer des paramètre sur le vps, une fois l'installation automatique faite.

Si vous avez un exemple de configuration assez détaillé, je suis preneur. (j'ai tenté la configuration sur le wiki mais en vain)

Merci et bravo pour le projet 
  - OpenMPTCProuter version: 0.11
  - OpenMPTCProuter VPS version: 0.7
  - Platform: debian 9 x64

**Comment by Ysurac** [comment]
Bonjour,

La configuration sur le wiki ( https://github.com/Ysurac/openmptcprouter/wiki/OpenMPTCProuter-configuration ) contient réellement le minimum nécessaire, il faut bien que tout soit activé et lancé. Pour le reste la configuration par défaut est bonne.

L'IP du VPS est donc à indiquer pour shadowsocks et eventuellement pour glorytun si on veut la redirection de port.
Pas besoin des DNS, par défaut on utilise les serveurs root.
Une fois l'installation du VPS faite, il n'y a plus rien à faire, sauf si on veut de la redirection de port.

Il y aura sur OpenMPTCProuter une configuration simplifiée quand l'ensemble des fonctionnalitées sera présente.
