### ISSUE TITLE
NETFLIX OMR-Bypass - FR

### ISSUE THREAD

**Issue by ThibautBascoulergue** [Ysurac/openmptcprouter#140]
## Expected Behavior

Hello,
I can not watch Netflix through 1and1 vps. I understand that we could use the tool omr-bypass but I can not find what to put in domain.
Prototcol I put Netflix and I tried putting domain netflix.com but it does not have the era to work.
I live in France. if anyone has an example I am a taker.

## Actual Behavior
![image](https://user-images.githubusercontent.com/42678960/44736914-d065b700-aaf0-11e8-9903-4bf6d216320e.png)

## Specifications

  - OpenMPTCProuter version: (33.2)
  - OpenMPTCProuter VPS version: (0.47)
  - OpenMPTCProuter platform: (x86_64)

**Comment by Ysurac** [comment]
Same as #112  and #134
