### ISSUE TITLE
Setup WIFI AP on RPI4

### ISSUE THREAD

**Issue by pbapba512** [Ysurac/openmptcprouter#1402]
I'm tried to setup a WIFI AP on my RPI4 according to the documentation. Probably its my fault, but its not works for me. I followed the documentation step-by-step. As I see well after the setup, my WIFI radio is running in Client mode, of course I setted up as Access point:

![image](https://user-images.githubusercontent.com/69822782/99859558-a943a600-2b90-11eb-994e-c78ab1abb145.png)
![image](https://user-images.githubusercontent.com/69822782/99859646-ead45100-2b90-11eb-9424-f244e1121ed7.png)
![image](https://user-images.githubusercontent.com/69822782/99859853-aa290780-2b91-11eb-91ed-e351e8ce2644.png)

The radio hardware is working anyway, its probably configuration error, but I can't figure out what is the problem. So my question is: how can I switch the radio to AP mode, instead of client mode?

thank you for your help!

  - OpenMPTCProuter version: v0.56.5
  - OpenMPTCProuter VPS version: 5.4.65-mptcp 0.1020
  - OpenMPTCProuter platform: RPI4, latest firmware (updated today)

**Comment by Adorfer** [comment]
wifi5 seems highly buggy, specially if you try anything above HT20. 
No idea what is broken, but is likely an OpenwRT issue, which is better adressed in the openwrt forums, since there are already a few threads about that.

**Comment by constant1010** [comment]
it works with this config of `/etc/config/wireless`

`config wifi-device 'radio0'
    option type 'mac80211'
    option path 'platform/soc/fe300000.mmcnr/mmc_host/mmc1/mmc1:0001/mmc1:0001:1'
    option legacy_rates '0'
    option country 'US'
    option hwmode '11g'
    option channel '7'
    option htmode 'HT20'
    option short_gi_40 '0'`

**Comment by pbapba512** [comment]
Thank you! Menawhile I found the solution, yes, its buggy. With legacy 2.4G settings works well. But all of other modes (N, 5G, etc) are broken.

Again, Adorfer and Constant1010, thank you for the help!

**Comment by pbapba512** [comment]
Today we did a 2 hours long SRT livestream via WIFI interface, and it was stable. So with legacy 2.4G settings works well, and all the others are broken, buggy. I close this issue, becuase its partially solved, but there is some bug with the RPI WIFI handling.
