### ISSUE TITLE
Layer 2 (TAP) Tunnel

### ISSUE THREAD

**Issue by Keksstar** [Ysurac/openmptcprouter#1407]
Hi there,

is it possible to create an Layer2 (so, TAP) Tunnel with OMR? If so, any advice on this how to do it? My final goal is to have an Layer2 tunnel between two OMRs and an server in the middle (so I could add more tunnels to the server if needed).

**Comment by ccmks** [comment]
I don't think it is possible. The tunneling is using L3 and L4 for MPTCP, so creating L2 wouldn't be possible
