### ISSUE TITLE
How to use iperf3 in OMR VPS?

### ISSUE THREAD

**Issue by ccmks** [Ysurac/openmptcprouter#1409]
I am trying to test my WAN connection speed against the VPS for OMR, how can I run iperf3? I saw the iperf3 is listening on port 65400. I am running windows machine to  run iperf3, but when I try to run iperf3 -c vps-ip-address -p 65400, I got error.

Please advise.

Thank you

**Comment by Ysurac** [comment]
The iperf server on the VPS part need a password and a key.
```omr-iperf``` is available on the router to simplify the usage.

**Comment by ccmks** [comment]
How can I iperf on specific WAN interface?

**Comment by ccmks** [comment]
The problem I have right now is I am trying to figure out what's bottleneck one of my WAN connection. My WAN5 is supposed to get 70 Mbps download, but when using OMR, only 5 Mbps being used. I would like to run iperf on WAN5 against the VPS to see if the connection between WAN5 to VPS is being throttle...

**Comment by ccmks** [comment]
If I do omr-test-speed eth5, it will get aggregate connection result. Plus omr-test-speed only run speedtest towards public server, not to my VPS

**Comment by Ysurac** [comment]
I forgot to bind to an interface for omr-test-speed, I will fix that for next release.
To test speed from VPS you can transfert a file with scp for example.
