### ISSUE TITLE
Add usb ethernet

### ISSUE THREAD

**Issue by PecaPit** [Ysurac/openmptcprouter#1410]
Hello, at first I had: PI 4B, 3 routers connected via a built-in ethernet adapter and through the same ethernet traffic went to consumers.
I decided to share the Internet to connect the Dlink DUB-1312 usb3.0 ethernet, and traffic to consumers through the built-in port, connect the adapter, everything worked fine at first, the adapter was detected by itself, I added an IP address to it, everything worked well, but for a while, PI 4B stopped responding to ping, reboot did not help, took out the USB-card did not help, and so it repeated 2 times, only reinstallation helped. Please advise what can be done, version v0.56.5

**Comment by Ysurac** [comment]
Why do you use a USB tio Ethernet adapter ?
I think the problem was a false network configuration that conflict with built-in port.
