### ISSUE TITLE
VOIP and Openmptcprouter

### ISSUE THREAD

**Issue by matthieu71000** [Ysurac/openmptcprouter#1412]
Hello,

I have a question about VOIP.

I am using OVH VOIP in SIP with g729 codec.
If I only use the OVH-ADSL line without Openmptcprouter I have no quality problem for calls.

When I use Openmptcprouter for my telephony, it is not correct.

My configuration: RPI3 + with ORANGE-ADSL, FREE-ADSL, OVH-ADSL and FREE-4G, with an OVH VPS.

Each ADSL gives DL: 13Mbits / UP: 950Mbits
4G gives: 60Mbits / 20 Mbits

I am using Glorytun TCP with ChaCha20 encryption.

First question, is it possible not to use encryption, and can this improve performance?
Second question, do you have any ideas for advice on how to properly configure the QOS for VOIP-OVH?

Thank you

Matthieu

**Comment by Adorfer** [comment]
ovh VPS without dedicated cpu cores suffer from heavy jitter

**Comment by matthieu71000** [comment]
> ovh VPS without dedicated cpu cores suffer from heavy jitter

ok so if I disable encryption, is it better ?

**Comment by Adorfer** [comment]
I would not expect that.
But if it helps, why not. Strange anyways!

**Comment by matthieu71000** [comment]
> I would not expect that.
> But if it helps, why not. Strange anyways!

No it's just a question, I don't test.
Do you think it could be better whith no encription ?

thanks

**Comment by ndaptardar** [comment]
I dont think there is a way to disable encryption on Glorytun ... but do check out and let us know

**Comment by Adorfer** [comment]
> Do you think it could be better whith no encription ?

No, i do not think so. 
I stand by my first reply.

**Comment by DeeJayMX** [comment]
Just use only your OVH ADSL for your voip with OMR Bypass
