### ISSUE TITLE
Boradband is not performing as good as 4G?

### ISSUE THREAD

**Issue by ndaptardar** [Ysurac/openmptcprouter#1414]
I have tried combining 3 4G connections, and they are doing OK. Am setting them as DHCP in wizard. Am getting 60%-90% of combined speed. All of the 3 4G give anywhere between 2-3Mbps to 8-10Mbps.
But when I am combining 2 broadbands on wifi (1 cable that gives 30Mbps, and 1 DSL that gives 6Mbps), I barely get 2-3Mbps combined. Any reason for this? Again I am using DHCP setting. I get same result when I combine broadband and 4G.

Any thoughts?

**Comment by Ysurac** [comment]
Using wifi is often a very bad idea.

**Comment by ndaptardar** [comment]
You mean WiFi of broadbands instead of wired broadband , right? Or WiFi in general, including 4G?

**Comment by Ysurac** [comment]
I was speaking about wifi of any WAN, but any connection that can lost many packets is a bad idea, so it's the same for a bad 4G.
Wifi often lost many packets, so it's why it's a bad idea in most case.
