### ISSUE TITLE
What is fastest VPN in OMR?

### ISSUE THREAD

**Issue by ndaptardar** [Ysurac/openmptcprouter#1415]
Which of below is fastest VPN in OMR when 4G connections combined?
- DSVPN
- Glorytun
- MLVPN
- OpenVPN
My experience is Glorytun is fastest, which is default VPN. But when I tested others, OepnVPN was slowest, others were close to Glorytun. Just wanted to confirm. Pl advise.

**Comment by TalalMash** [comment]
On frequent connection failovers/dropouts all except Glorytun TCP behave erratically.

**Comment by ndaptardar** [comment]
> On frequent connection failovers/dropouts all except Glorytun TCP behave erratically.
