### ISSUE TITLE
installation Orange Pi 3

### ISSUE THREAD

**Issue by Roman001006** [Ysurac/openmptcprouter#1417]
Hi, is there any support for Orange Pi 3 microcomputer? Will it be in the future? Thanks!
Orange Pi 3 website: www.orangepi.org

**Comment by Ysurac** [comment]
There is no support for Orange PI 3, and no idea for the future.
I only support hardware that I own (so it will only be supported if I receive a Orange PI 3 or if I buy one ;) ).

It's maybe possible to compile it yourself: https://github.com/Ysurac/openmptcprouter/wiki/Create-image-for-unsupported-platform

**Comment by Roman001006** [comment]
> Нет поддержки Orange PI 3 и нет никаких представлений о будущем.
> Я поддерживаю только оборудование, которое у меня есть (так что оно будет поддерживаться только в том случае, если я получу Orange PI 3 или куплю его;)).
> 
> Возможно, можно скомпилировать его самостоятельно: https://github.com/Ysurac/openmptcprouter/wiki/Create-image-for-unsupported-platform

If I install the x86 version on the micro sd card, It will work?

**Comment by Ysurac** [comment]
No. A dedicated image is needed (and Orange PI is based on ARM).

**Comment by Roman001006** [comment]
> Нет. Требуется специальный образ (и Orange PI основан на ARM).

thanks!
