### ISSUE TITLE
Will it work when 2 wlan have same ip?

### ISSUE THREAD

**Issue by ndaptardar** [Ysurac/openmptcprouter#1418]
Assume I have 2 usb WiFi adapters. Both connected to 2 different 4G hotspots of 2 android phones. As we know, android assigns ip from 192.168.43.x range since it’s hard coded in android. What will happen in below situations?

Situation 1 - same ip different gateway 
Wlan1 192.168.43.50
Wlan1 gateway 192.168.43.1
Wlan2 192.168.45.50
Wlan2 gateway 192.168.43.2

Situation 2 - same ip same gateway 
Wlan1 192.168.43.50
Wlan1 gateway 192.168.43.1
Wlan2 192.168.45.50
Wlan2 gateway 192.168.43.1

**Comment by Ysurac** [comment]
As it's not the same interface it may work.

**Comment by ndaptardar** [comment]
That's what I thought.
