### ISSUE TITLE
Firewall restriction from IP Source

### ISSUE THREAD

**Issue by mycanaletto** [Ysurac/openmptcprouter#1419]
Hello,
I've been a bit of a flirt without success.
I would like to create a rule to accept incoming traffic only from certain IP ranges (Cloudflare).

Ideally, I would have liked to do Geo IP but I don't think that's possible.

Merci ;-)

**Comment by kevin39** [comment]
Hi,
What's your problem with firewall rules ? What did you try ?

**Comment by mycanaletto** [comment]
Where do I put the authorized source IPs?

![image](https://user-images.githubusercontent.com/45459269/100228468-050c8700-2f23-11eb-9158-baf260bf8e7a.png)
Here I can't

**Comment by Ysurac** [comment]
In Advanced settings tab, source IP address.

**Comment by mycanaletto** [comment]
I must be awake badly again!!!

Thanks to you.

No Geo IP ideas?

**Comment by mycanaletto** [comment]
Except that in advanced the combo only shows internal IPs and it's not possible to add them.... (I would have to add all the CloudFlare ranges)
![image](https://user-images.githubusercontent.com/45459269/100229907-3ab26f80-2f25-11eb-9779-fd461a013254.png)

**Comment by kevin39** [comment]
I'm not sure to understand you correctly.
How do you want to filter if you do not want to enter IP ranges ?

Not tested but CIDR format seems to be allowed.

**Comment by Ysurac** [comment]
You can enter manually an ip at the end.
I don't remember if subnet is supported...
You can also directly edit ```/etc/shorewall/rules``` on the VPS (without putting comment at end of line). It may also support geoip, but I need to check if I added support in kernel for that...

**Comment by mycanaletto** [comment]
In the meantime it is not possible to use "Firewall - Custom Rules"?

**Comment by Ysurac** [comment]
no...
Changes in the router are applied in shorewall on the VPS, so traffic is blocked on VPS side and is not forwarded to the router when not needed.
And it's easy to edit shorewall rules, so why doing something more difficult that will give a bad result ?

**Comment by mycanaletto** [comment]
Yes it can be a solution.

But finally I send the port to a synology's reverse proxy which has a GeoIP blocker and where I can also easily add Cloudflare addresses.

In the absolute it would of course be better to be able to block in GeoIP on openMPTCP, but I know it's not simple, Unifi has been in beta on this subject for more than two years without making any progress for example...

Thanks for your work !
