### ISSUE TITLE
anyone can make sense of load averages?

### ISSUE THREAD

**Issue by rifaterdemsahin** [Ysurac/openmptcprouter#1422]
![image](https://user-images.githubusercontent.com/5270036/100468802-0aa5d080-30cd-11eb-8290-0ad20ef58dad.png)

**Comment by Ysurac** [comment]
http://letmegooglethat.com/?q=load+average

**Comment by Adorfer** [comment]
the load shows that you are using a far to fast CPU, a value up to 2 would be reasonable, 4 would be tolerable.
