### ISSUE TITLE
Question: How to compile your own kernel with MPTCP

### ISSUE THREAD

**Issue by benpro** [Ysurac/openmptcprouter#1424]
Hi there,

I would like to compile my own kernel with MPTCP patches for my Rasbperry Pi.
Why? Because I want to use the OpenWRT image into a LXC container on my RPi.
(I use my RPi as a desktop, and want to aggregate two WAN, without installing another machine).

I tried to find where and how the kernel is compiled for the OpenWRT image, but I did not found it.

Can you guide me?

Thanks,

**Comment by Ysurac** [comment]
There is a doc here: https://github.com/Ysurac/openmptcprouter-vps/wiki/Compile-kernel

**Comment by benpro** [comment]
Thanks did not see it.
Will explore that...
