### ISSUE TITLE
what happens if i give the OMR a different source

### ISSUE THREAD

**Issue by rifaterdemsahin** [Ysurac/openmptcprouter#1426]
instead of giving only one direct modem if i connect one line to another multiwan router.

OMR shows online on draytek but i am not sure. As now it has dsl and lte in a roundrobin version with sticky sessions

what is my down side ?

![image](https://user-images.githubusercontent.com/5270036/100556737-4a6ee280-329c-11eb-9aed-cbe900f65aff.png)

![image](https://user-images.githubusercontent.com/5270036/100556702-0bd92800-329c-11eb-8f68-f4040ca2cbaf.png)

Referenced multi wan router
https://www.broadbandbuyer.com/products/30263-draytek-v2862n-k/?gclid=Cj0KCQiAqo3-BRDoARIsAE5vnaLFHhU5wfZbdvATnT7TbD40_OrV-NWvz0k6QlMt4J06pNEtnG_ThcoaAlqWEALw_wcB

**Comment by Ysurac** [comment]
I'm not sure that load balancer will really work in this case, but you will tell me ;)

**Comment by AndreaLeidi** [comment]
![001](https://user-images.githubusercontent.com/44334873/100661510-db54c500-3353-11eb-8c79-ea7d4181eaa8.jpg)

![002](https://user-images.githubusercontent.com/44334873/100661573-f3c4df80-3353-11eb-9e9f-f57d8c708ab4.jpg)

Works like a charm on my Vigor 2926.

**Comment by rifaterdemsahin** [comment]
it does also work with my vigor as well.I think it is not healthy though right ?

**Comment by AndreaLeidi** [comment]
I see no other way if you want to add a bonding device to a LAN built around a Draytek load balancing router but for any reason you can't remove the existing hardware or change the wiring. 
The only unhealty result is adding a little more latency, I guess.
