### ISSUE TITLE
VMWare image failed booting on esxi

### ISSUE THREAD

**Issue by TRSATOC** [Ysurac/openmptcprouter#143]
When booting on esxi I have the following message:
```
SQUASHFS error: xz decompression failed, data probably corrupt
SQUASHFS error: squashfs_read_data failed to read block 0x6e

```
I've tried differents vmware image versions on the virtual machine configuration, conversions from vdi to vmdk, etc... always the same problem.
it will be nice to have a step by step process.

**Comment by Ysurac** [comment]
You can try to follow #87 but I can't provide support on VMWare, I only use Virtualbox.

**Comment by kamcio2603** [comment]
Vmware image works for me. Vmdk + IDE setup. Esxi 6.5 here.

**Comment by TRSATOC** [comment]
OK, I've find the problem.
I've followed the #87 but you need also to remove the floppy drive \o/ ... That was not mentioned

**Comment by TRSATOC** [comment]
@kamcio2603 I can't save anything on my VM, the change of the root password is not saved when I reboot.
And I always have some  SQUASHFS message like my first message on the thread:
![image](https://user-images.githubusercontent.com/31935453/44797505-a45d3b00-abaf-11e8-800b-bc605878e8fb.png)

**Comment by TRSATOC** [comment]
I'm using this controller others don't boot, sorry it's in french ;)
![image](https://user-images.githubusercontent.com/31935453/44798235-50535600-abb1-11e8-82ba-33109d671d9d.png)

**Comment by Scaff31** [comment]
J'ai une nouvelle procédure qui fonctionne mieux est adaptable a toutes les versions d'esxi (6.x)

1- Recupere l'image workstation
2- Upload le vmdk sur ton esxi
3- Connecte toi en SSH sur l'esxi puis converti le disque de workstation à ESXI
vmkfstools -i [workstation.vmdk] -d zeroedthick [esxi.vmdk]

4- Crée ta VM avec le disque que tu viens de convertir et tu n'aura plus de souci de squashfs

**Comment by TRSATOC** [comment]
Thank you so much!
That ok now!!!
