### ISSUE TITLE
Launch a call on Microsoft Teams breaks the network

### ISSUE THREAD

**Issue by ijaouani** [Ysurac/openmptcprouter#1431]
## Expected Behavior
To be able able to perform call on Microsoft Teams.

## Current Behavior
Everytime I launch a call (even with the test bot) the network stop to work :

![image](https://user-images.githubusercontent.com/27200712/101149292-04f54100-361f-11eb-9cd8-0a08b89b1085.png)

When I stop the call after a few seconds, all is green again.

## Specifications

- OpenMPTCProuter version: v0.56.5 r0+14653-a439f1bb47
- OpenMPTCProuter VPS version: 5.4.74-mptcp 0.1022
- OpenMPTCProuter platform: openmptcprouter-v0.56.5-r0+14653-a439f1bb47-x86-64-generic-ext4-combined-efi.ova

Any ideas ?

**Comment by Ysurac** [comment]
Check VPS cpu load and VPS access, it seems to not answer to ping. What is the provider ?

**Comment by ijaouani** [comment]
![image](https://user-images.githubusercontent.com/27200712/101153949-599bba80-3625-11eb-8016-af64d5d35aa7.png)

VPS : Debian hosted on Azure France Central Standard B1ms (1 vcpus, 2 GiB memory)
OpenMPTCProuter installed on Synology NAS via Virtual Manager.
4G BOX : MR600
ADSL: Orange BOX (Sosh)
DHCP disabled on both 4G box and ADSL box.

Connexions
NAS connected with LAN to orange box
4G Box connected with LAN to orange box
PC connected with LAN to orange box

**Comment by ijaouani** [comment]
The thing I don't get is it's really specific to this app. When I download a big file everything work as expected.
I also try from an other PC to be sure same behavior.

This is the logs :

Fri Dec  4 10:52:21 2020 daemon.info dnsmasq-dhcp[10810]: DHCPREQUEST(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed
Fri Dec  4 10:52:21 2020 daemon.info dnsmasq-dhcp[10810]: DHCPACK(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed DESKTOP-I2BFNTI
Fri Dec  4 10:52:22 2020 daemon.info dnsmasq-dhcp[10810]: DHCPREQUEST(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed
Fri Dec  4 10:52:22 2020 daemon.info dnsmasq-dhcp[10810]: DHCPACK(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed DESKTOP-I2BFNTI
Fri Dec  4 10:52:34 2020 daemon.info dnsmasq-dhcp[10810]: DHCPREQUEST(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed
Fri Dec  4 10:52:34 2020 daemon.info dnsmasq-dhcp[10810]: DHCPACK(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed DESKTOP-I2BFNTI
Fri Dec  4 10:52:35 2020 daemon.warn odhcpd[4388]: A default route is present but there is no public prefix on lan thus we don't announce a default route!
Fri Dec  4 10:52:35 2020 daemon.err odhcpd[4388]: Failed to send to ff02::1%lan@eth0 (Permission denied)
Fri Dec  4 10:52:35 2020 daemon.info dnsmasq-dhcp[10810]: DHCPREQUEST(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed
Fri Dec  4 10:52:35 2020 daemon.info dnsmasq-dhcp[10810]: DHCPACK(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed DESKTOP-I2BFNTI
Fri Dec  4 10:52:48 2020 daemon.info dnsmasq-dhcp[10810]: DHCPREQUEST(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed
Fri Dec  4 10:52:48 2020 daemon.info dnsmasq-dhcp[10810]: DHCPACK(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed DESKTOP-I2BFNTI
Fri Dec  4 10:52:51 2020 daemon.warn odhcpd[4388]: A default route is present but there is no public prefix on lan thus we don't announce a default route!
Fri Dec  4 10:52:51 2020 daemon.err odhcpd[4388]: Failed to send to ff02::1%lan@eth0 (Permission denied)
Fri Dec  4 10:52:51 2020 daemon.info dnsmasq-dhcp[10810]: DHCPREQUEST(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed
Fri Dec  4 10:52:51 2020 daemon.info dnsmasq-dhcp[10810]: DHCPACK(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed DESKTOP-I2BFNTI
Fri Dec  4 10:53:07 2020 daemon.warn odhcpd[4388]: A default route is present but there is no public prefix on lan thus we don't announce a default route!
Fri Dec  4 10:53:07 2020 daemon.err odhcpd[4388]: Failed to send to ff02::1%lan@eth0 (Permission denied)
Fri Dec  4 10:53:08 2020 daemon.info dnsmasq-dhcp[10810]: DHCPREQUEST(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed
Fri Dec  4 10:53:08 2020 daemon.info dnsmasq-dhcp[10810]: DHCPACK(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed DESKTOP-I2BFNTI
Fri Dec  4 10:53:10 2020 daemon.info dnsmasq-dhcp[10810]: DHCPREQUEST(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed
Fri Dec  4 10:53:10 2020 daemon.info dnsmasq-dhcp[10810]: DHCPACK(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed DESKTOP-I2BFNTI
Fri Dec  4 10:53:20 2020 daemon.info dnsmasq-dhcp[10810]: DHCPREQUEST(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed
Fri Dec  4 10:53:20 2020 daemon.info dnsmasq-dhcp[10810]: DHCPACK(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed DESKTOP-I2BFNTI
Fri Dec  4 10:53:22 2020 daemon.info dnsmasq-dhcp[10810]: DHCPREQUEST(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed
Fri Dec  4 10:53:22 2020 daemon.info dnsmasq-dhcp[10810]: DHCPACK(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed DESKTOP-I2BFNTI
Fri Dec  4 10:53:23 2020 daemon.warn odhcpd[4388]: A default route is present but there is no public prefix on lan thus we don't announce a default route!
Fri Dec  4 10:53:23 2020 daemon.err odhcpd[4388]: Failed to send to ff02::1%lan@eth0 (Permission denied)
Fri Dec  4 10:53:34 2020 daemon.info dnsmasq-dhcp[10810]: DHCPREQUEST(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed
Fri Dec  4 10:53:34 2020 daemon.info dnsmasq-dhcp[10810]: DHCPACK(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed DESKTOP-I2BFNTI
Fri Dec  4 10:53:37 2020 daemon.info dnsmasq-dhcp[10810]: DHCPREQUEST(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed
Fri Dec  4 10:53:37 2020 daemon.info dnsmasq-dhcp[10810]: DHCPACK(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed DESKTOP-I2BFNTI
Fri Dec  4 10:53:39 2020 daemon.warn odhcpd[4388]: A default route is present but there is no public prefix on lan thus we don't announce a default route!
Fri Dec  4 10:53:39 2020 daemon.err odhcpd[4388]: Failed to send to ff02::1%lan@eth0 (Permission denied)
Fri Dec  4 10:53:45 2020 daemon.info dnsmasq-dhcp[10810]: DHCPREQUEST(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed
Fri Dec  4 10:53:45 2020 daemon.info dnsmasq-dhcp[10810]: DHCPACK(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed DESKTOP-I2BFNTI
Fri Dec  4 10:53:49 2020 daemon.info dnsmasq-dhcp[10810]: DHCPREQUEST(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed
Fri Dec  4 10:53:49 2020 daemon.info dnsmasq-dhcp[10810]: DHCPACK(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed DESKTOP-I2BFNTI
Fri Dec  4 10:53:51 2020 daemon.info dnsmasq-dhcp[10810]: DHCPREQUEST(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed
Fri Dec  4 10:53:51 2020 daemon.info dnsmasq-dhcp[10810]: DHCPACK(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed DESKTOP-I2BFNTI
Fri Dec  4 10:53:55 2020 daemon.warn odhcpd[4388]: A default route is present but there is no public prefix on lan thus we don't announce a default route!
Fri Dec  4 10:53:55 2020 daemon.err odhcpd[4388]: Failed to send to ff02::1%lan@eth0 (Permission denied)
Fri Dec  4 10:53:58 2020 daemon.err /usr/bin/ss-redir[12258]: remote recv: Operation timed out
Fri Dec  4 10:54:00 2020 daemon.err /usr/bin/ss-redir[12258]: remote recv: Operation timed out
Fri Dec  4 10:54:00 2020 daemon.err /usr/bin/ss-redir[12258]: remote recv: Operation timed out
Fri Dec  4 10:54:07 2020 user.notice post-tracking-post-tracking: omrvpn down because gateway down
Fri Dec  4 10:54:07 2020 user.notice post-tracking-post-tracking: Tunnel down use ShadowSocks for UDP
Fri Dec  4 10:54:07 2020 user.notice Shadowsocks: Rules DOWN
Fri Dec  4 10:54:08 2020 user.notice Shadowsocks: Rules UP
Fri Dec  4 10:54:08 2020 user.notice Shadowsocks: Reload omr-bypass rules
Fri Dec  4 10:54:08 2020 user.notice omr-bypass: Starting OMR-ByPass...
Fri Dec  4 10:54:10 2020 user.notice omr-bypass: Reload dnsmasq...
Fri Dec  4 10:54:10 2020 daemon.info dnsmasq[10810]: read /etc/hosts - 4 addresses
Fri Dec  4 10:54:10 2020 daemon.info dnsmasq[10810]: read /tmp/hosts/dhcp.cfg01411c - 1 addresses
Fri Dec  4 10:54:10 2020 daemon.info dnsmasq-dhcp[10810]: read /etc/ethers - 0 addresses
Fri Dec  4 10:54:10 2020 user.notice omr-bypass: OMR-ByPass is running
Fri Dec  4 10:54:10 2020 daemon.notice netifd: Network device 'tun0' link is down
Fri Dec  4 10:54:10 2020 daemon.notice netifd: Interface 'omrvpn' has link connectivity loss
Fri Dec  4 10:54:10 2020 daemon.notice netifd: Interface 'omrvpn' is now down
Fri Dec  4 10:54:10 2020 daemon.info glorytun[15475]: STOPPED tun0
Fri Dec  4 10:54:10 2020 daemon.debug dnsmasq[10810]: stopped listening on tun0(#21): 10.255.255.2 port 53
Fri Dec  4 10:54:10 2020 daemon.info glorytun: starting glorytun vpn instance vpn
Fri Dec  4 10:54:10 2020 user.notice ModemManager: hotplug: remove network interface tun0: event processed
Fri Dec  4 10:54:10 2020 user.notice ModemManager: hotplug: event reported: action=remove, name=tun0, subsystem=net
Fri Dec  4 10:54:10 2020 daemon.info glorytun[16898]: INITIALIZED tun0
Fri Dec  4 10:54:10 2020 daemon.notice netifd: Interface 'omrvpn' is disabled
Fri Dec  4 10:54:10 2020 daemon.notice netifd: Interface 'omrvpn' is enabled
Fri Dec  4 10:54:10 2020 daemon.debug dnsmasq[10810]: listening on tun0(#22): fe80::61ef:8b97:58f0:a379%tun0 port 53
Fri Dec  4 10:54:10 2020 daemon.notice netifd: Interface 'omrvpn' is disabled
Fri Dec  4 10:54:10 2020 daemon.debug dnsmasq[10810]: stopped listening on tun0(#22): fe80::61ef:8b97:58f0:a379%tun0 port 53
Fri Dec  4 10:54:10 2020 daemon.notice netifd: Interface 'omrvpn' is enabled
Fri Dec  4 10:54:10 2020 daemon.notice netifd: Network device 'tun0' link is up
Fri Dec  4 10:54:10 2020 daemon.notice netifd: Interface 'omrvpn' has link connectivity
Fri Dec  4 10:54:10 2020 daemon.notice netifd: Interface 'omrvpn' is setting up now
Fri Dec  4 10:54:10 2020 daemon.notice netifd: Interface 'omrvpn' is now up
Fri Dec  4 10:54:11 2020 user.notice ModemManager: hotplug: add network interface tun0: event processed
Fri Dec  4 10:54:11 2020 user.notice ModemManager: hotplug: event reported: action=add, name=tun0, subsystem=net
Fri Dec  4 10:54:11 2020 user.notice ModemManager: hotplug: error: parent device sysfspath not found
Fri Dec  4 10:54:11 2020 daemon.warn odhcpd[4388]: A default route is present but there is no public prefix on lan thus we don't announce a default route!
Fri Dec  4 10:54:11 2020 daemon.err odhcpd[4388]: Failed to send to ff02::1%lan@eth0 (Permission denied)
Fri Dec  4 10:54:11 2020 user.notice firewall: Reloading firewall due to ifup of omrvpn (tun0)
Fri Dec  4 10:54:15 2020 user.notice post-tracking-post-tracking: Set ip route replace default scope global  nexthop via 192.168.1.1 dev wan1 weight 2 nexthop via 192.168.2.1 dev wan2 weight 1
Fri Dec  4 10:54:17 2020 daemon.err /usr/bin/ss-redir[12258]: remote recv: Operation timed out
Fri Dec  4 10:54:18 2020 daemon.info dnsmasq-dhcp[10810]: DHCPREQUEST(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed
Fri Dec  4 10:54:18 2020 daemon.info dnsmasq-dhcp[10810]: DHCPACK(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed DESKTOP-I2BFNTI
Fri Dec  4 10:54:18 2020 daemon.err /usr/bin/ss-redir[12258]: remote recv: Operation timed out
Fri Dec  4 10:54:19 2020 daemon.err /usr/bin/ss-redir[12258]: remote recv: Operation timed out
Fri Dec  4 10:54:19 2020 daemon.err /usr/bin/ss-local[12256]: getpeername: Socket not connected
Fri Dec  4 10:54:21 2020 daemon.info dnsmasq-dhcp[10810]: DHCPREQUEST(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed
Fri Dec  4 10:54:21 2020 daemon.info dnsmasq-dhcp[10810]: DHCPACK(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed DESKTOP-I2BFNTI
Fri Dec  4 10:54:21 2020 user.notice OMR-VPS: Can't get token, try later
Fri Dec  4 10:54:21 2020 user.notice omr-bypass: Starting OMR-ByPass...
Fri Dec  4 10:54:21 2020 daemon.err /usr/bin/ss-redir[12258]: remote recv: Operation timed out
Fri Dec  4 10:54:22 2020 user.notice omr-bypass: Reload dnsmasq...
Fri Dec  4 10:54:23 2020 daemon.info dnsmasq[10810]: read /etc/hosts - 4 addresses
Fri Dec  4 10:54:23 2020 daemon.info dnsmasq[10810]: read /tmp/hosts/dhcp.cfg01411c - 1 addresses
Fri Dec  4 10:54:23 2020 daemon.info dnsmasq-dhcp[10810]: read /etc/ethers - 0 addresses
Fri Dec  4 10:54:23 2020 user.notice omr-bypass: OMR-ByPass is running
Fri Dec  4 10:54:23 2020 daemon.debug dnsmasq[10810]: listening on tun0(#22): 10.255.255.2 port 53
Fri Dec  4 10:54:23 2020 user.notice mptcp: Reloading mptcp config due to ifup of omrvpn (tun0)
Fri Dec  4 10:54:27 2020 daemon.warn odhcpd[4388]: A default route is present but there is no public prefix on lan thus we don't announce a default route!
Fri Dec  4 10:54:27 2020 daemon.err odhcpd[4388]: Failed to send to ff02::1%lan@eth0 (Permission denied)
Fri Dec  4 10:54:28 2020 daemon.err /usr/bin/ss-redir[12258]: remote recv: Operation timed out
Fri Dec  4 10:54:29 2020 daemon.info omr-tracker-ss: Shadowsocks is down (can't contact via http 198.27.92.1, 151.101.129.164, 77.88.55.77)
Fri Dec  4 10:54:29 2020 user.notice Shadowsocks: Rules DOWN
Fri Dec  4 10:54:30 2020 daemon.info dnsmasq-dhcp[10810]: DHCPREQUEST(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed
Fri Dec  4 10:54:30 2020 daemon.info dnsmasq-dhcp[10810]: DHCPACK(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed DESKTOP-I2BFNTI
Fri Dec  4 10:54:32 2020 daemon.info dnsmasq-dhcp[10810]: DHCPREQUEST(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed
Fri Dec  4 10:54:32 2020 daemon.info dnsmasq-dhcp[10810]: DHCPACK(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed DESKTOP-I2BFNTI
Fri Dec  4 10:54:32 2020 daemon.err /usr/bin/ss-redir[12258]: remote recv: Operation timed out
Fri Dec  4 10:54:34 2020 daemon.err /usr/bin/ss-local[12256]: getpeername: Socket not connected
Fri Dec  4 10:54:35 2020 daemon.err /usr/bin/ss-redir[12258]: remote recv: Operation timed out
Fri Dec  4 10:54:38 2020 user.notice OMR-VPS: Can't get token, try later (can't ping server, no server API answer)
Fri Dec  4 10:54:40 2020 daemon.info omr-tracker-ss: Server (51.103.53.71) seems down, no answer to ping
Fri Dec  4 10:54:42 2020 daemon.info dnsmasq-dhcp[10810]: DHCPREQUEST(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed
Fri Dec  4 10:54:42 2020 daemon.info dnsmasq-dhcp[10810]: DHCPACK(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed DESKTOP-I2BFNTI
Fri Dec  4 10:54:43 2020 daemon.warn odhcpd[4388]: A default route is present but there is no public prefix on lan thus we don't announce a default route!
Fri Dec  4 10:54:43 2020 daemon.err odhcpd[4388]: Failed to send to ff02::1%lan@eth0 (Permission denied)
Fri Dec  4 10:54:44 2020 daemon.err /usr/bin/ss-redir[12258]: remote recv: Operation timed out
Fri Dec  4 10:54:44 2020 daemon.info dnsmasq-dhcp[10810]: DHCPREQUEST(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed
Fri Dec  4 10:54:44 2020 daemon.info dnsmasq-dhcp[10810]: DHCPACK(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed DESKTOP-I2BFNTI
Fri Dec  4 10:54:46 2020 daemon.err /usr/bin/ss-local[12256]: getpeername: Socket not connected
Fri Dec  4 10:54:49 2020 daemon.err /usr/bin/ss-redir[12258]: remote recv: Operation timed out
Fri Dec  4 10:54:54 2020 user.notice OMR-VPS: Can't get token, try later (can't ping server, no server API answer)
Fri Dec  4 10:54:54 2020 daemon.info dnsmasq-dhcp[10810]: DHCPREQUEST(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed
Fri Dec  4 10:54:54 2020 daemon.info dnsmasq-dhcp[10810]: DHCPACK(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed DESKTOP-I2BFNTI
Fri Dec  4 10:54:56 2020 daemon.info dnsmasq-dhcp[10810]: DHCPREQUEST(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed
Fri Dec  4 10:54:56 2020 daemon.info dnsmasq-dhcp[10810]: DHCPACK(eth0) 192.168.100.106 fc:f8:ae:60:c5:ed DESKTOP-I2BFNTI
Fri Dec  4 10:54:59 2020 daemon.warn odhcpd[4388]: A default route is present but there is no public prefix on lan thus we don't announce a default route!
Fri Dec  4 10:54:59 2020 daemon.err odhcpd[4388]: Failed to send to ff02::1%lan@eth0 (Permission denied)

**Comment by Ysurac** [comment]
I think Teams use UDP, it's why it's not the same problem when you download a file.
You can try to use enable SQM in the wizard and set download/upload speed.
It's still strange that the VPS doesn't answer to ping from the router...

**Comment by ijaouani** [comment]
I think I have an idea :

![image](https://user-images.githubusercontent.com/27200712/101157716-dc734400-362a-11eb-8a61-9998dcf805e0.png)

![image](https://user-images.githubusercontent.com/27200712/101157777-f6148b80-362a-11eb-9f75-af6482b2c4bb.png)

It seems that the root cause is the VPS. When I launch MS Teams seems the CPU reach the top and the vps is unreachable (even with SSH). But when I download a file only few percent. Maybe Standard B1ms (1 vcpus, 2 GiB memory) is not enough ?

**Comment by Ysurac** [comment]
I always had strange issues with Azure ;)
1 VCPU doesn't really say something, some provider share one core with 10 users (it's slow), some with 2 users (it's faster).

**Comment by ijaouani** [comment]
I have upgraded the size of the VM to Standard D2s v3 (2 vcpus, 8 GiB memory) and exactly the same problem. 
When I launch a call I have exacty the image I sent in my first message and as soon as I hang up :
Sometine few seconds later everything is green. 
Sometime the vps is stuck for a while :

![image](https://user-images.githubusercontent.com/27200712/101162743-02044b80-3633-11eb-86d6-53a3e341aab4.png)

I also try to enable SQM for ADSL as you suggested but does not help for what I can see.

Where can I find some logs for the vps side ?

**Comment by Ysurac** [comment]
In ```/var/log/daemon.log``` there is some log.
You have really high load average...

**Comment by ijaouani** [comment]
I finally find a workaround. I created a new VPS (still on Azure) but with Ubuntu 20-04 instead of the recommanded debian and the issue just disappeared. I will keep the issue open until I am sure of it and then I will take care of closing it.

Thank you really much Ysurac for your help on this. Really appreciate.
