### ISSUE TITLE
Bloquer web à un appareil du réseau

### ISSUE THREAD

**Issue by JeedHome44** [Ysurac/openmptcprouter#1432]
## Expected Behavior
Comment bloquer internet à un appareil sur le réseau LAN? 

## Specifications

  - OpenMPTCProuter version: 55.6
  - OpenMPTCProuter VPS version: 22
  - OpenMPTCProuter platform: Pi 4B 2Go

**Comment by Ysurac** [comment]
En lisant la doc : https://github.com/Ysurac/openmptcprouter/wiki/Block-client-Internet-access

**Comment by JeedHome44** [comment]
Merci.
En fait, je ne veux pas que l'appareil soit mis à jour automatiquement.
C'est donc ça pour chacun?

**Comment by JeedHome44** [comment]
Mais si je veux utiliser l'appareil qu'en local, je n'ai que la 2eme règle à faire non?

**Comment by Ysurac** [comment]
Non les 2 règles. Après tu peux ne pas définir la passerelle ou une autre passerelle sur chaque machine via DHCP ou en statique. Pas de route par défaut par le routeur, pas d'accès à Internet.
