### ISSUE TITLE
fresh update failed 

### ISSUE THREAD

**Issue by numerobis08** [Ysurac/openmptcprouter#1435]
## Expected Behavior
factory udpate

## Current Behavior
i made a fresh install on VPS and router and since that it doesn't work anymore ( since i re installed VPS i didn't forget to use the new generated KEY but it doesn't seems to work. 
i have the following message on the status page : 

![Capture d’écran 2020-12-06 à 01 16 01](https://user-images.githubusercontent.com/65051442/101268292-9f5d9d80-3761-11eb-99a6-92853d5619fd.png)

## Specifications

  - OpenMPTCProuter version: v0.56.5
  - OpenMPTCProuter VPS version: 0.1022
  - OpenMPTCProuter platform: (RPI4

**Comment by numerobis08** [comment]
update : 
it seems to be working better ( at least i do have now an internet connection ) but we the update it seems to have new parameters that i don't know how to handle. Here is below the new status i have : 

![Capture d’écran 2020-12-06 à 02 59 00](https://user-images.githubusercontent.com/65051442/101269417-05045680-376f-11eb-8ef2-c960cf32128b.png)

what is strange is that the SFR ADSL Box seems to have same WAN IP than the 4G connection. 
Here is below how i configured the 4G router and the SFR ADSL Box , have I done something wrong ?

![Capture d’écran 2020-12-06 à 03 01 45](https://user-images.githubusercontent.com/65051442/101269466-80660800-376f-11eb-9f49-3317254a76a3.png)


![Capture d’écran 2020-12-06 à 03 02 10](https://user-images.githubusercontent.com/65051442/101269475-8c51ca00-376f-11eb-8992-488e7e6c2167.png)

![Capture d’écran 2020-12-06 à 03 02 28](https://user-images.githubusercontent.com/65051442/101269482-94aa0500-376f-11eb-93fb-3171f72097a1.png)

**Comment by Ysurac** [comment]
wan1 and wan2 use same physical interface, in this case you must use Type MacVLAN.

**Comment by numerobis08** [comment]
> wan1 and wan2 use same physical interface, in this case you must use Type MacVLAN.

Hello Ysurac , 
The Rpi4 is connected to a switch on which both 4G router and SFR ADSL BOX are connected that’s why I thought I had to choose Eth0. 
For my understanding in which case should we use ETh0 ? What is MacVLAN ? 
Thanks 😊

**Comment by numerobis08** [comment]
> wan1 and wan2 use same physical interface, in this case you must use Type MacVLAN.

Hello i just did has you mentioned , and i works better (i read on GitHub the multipath should be set as master for the ADSL box as bitrate is more stable ( and set to "on" on the 4G router) , is that correct ? ) . just a question is it normal that time to times i have the following orange message regarding the VPS : 

![Capture d’écran 2020-12-06 à 11 58 32](https://user-images.githubusercontent.com/65051442/101278267-87fece80-37ba-11eb-9409-3b21aedd6f40.png)

because if i wait , it comes back to green as below (i'm using Firstheberg) : 

![Capture d’écran 2020-12-06 à 12 00 34](https://user-images.githubusercontent.com/65051442/101278302-bc728a80-37ba-11eb-95e9-dd4df63fa654.png)

annoter topic is it any issue if it mentions " votre IP n'a pas été attribuée par ce routeur" ? 

Merci d'avance

**Comment by Ysurac** [comment]
As it's indicated on the wizard, if you share same physical interface with multiples WAN, use MacVLAN. It's the default setting on a RPI.

**Comment by Ysurac** [comment]
For the message,this can happen if this take too much time. I have many issues with Firstheberg...

**Comment by numerobis08** [comment]
> For the message,this can happen if this take too much time. I have many issues with Firstheberg...

I think I’ll switch next month to Milkywan as I read good feedback.  
For multiparty the “master” should be on the adsl and only “on” on the 4G as it’s less stable ?

**Comment by Ysurac** [comment]
true, master should be the more stable connection.

**Comment by numerobis08** [comment]
Thanks a lot for the help :-) 
I think I can close that issue. 
Thank you
