### ISSUE TITLE
Configuration wizard and IPv6 dhcp server

### ISSUE THREAD

**Issue by vinux-code** [Ysurac/openmptcprouter#144]
## Expected Behavior

Use configuration wizard without modifying IPv6 dhcp server options.
IPv6 disabled in the wizard

## Actual Behavior

When we validate the configuration wizard, IPv4 DHCP server is always activated even if it was disabled before.

## Steps to Reproduce the Problem

  1. Disable IPV6 dhcp server in LAN interface settings
  2. Use Save & Apply in the wizard
  3. IPV6 dhcp server is enabled again in LAN interface settings

## Specifications

  - OpenMPTCProuter version: 0.34
  - OpenMPTCProuter VPS version: 0.47
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
Since 0.34.1, IPv6 DHCP is enabled if IPv6 is enabled in wizard page and disabled else.
So it's now fixed.
