### ISSUE TITLE
Reccurent gateway down (4G) 

### ISSUE THREAD

**Issue by ijaouani** [Ysurac/openmptcprouter#1444]
## Expected Behavior
No errors in System logs. Stable connexion. I often see gateay down for fews seconds and after some time becomes green again.

## Current Behavior

![image](https://user-images.githubusercontent.com/27200712/101609361-2c755080-3a07-11eb-94ab-6931311b41d8.png)

And 5 seconds after :

![image](https://user-images.githubusercontent.com/27200712/101609449-44e56b00-3a07-11eb-8bac-9db819269baf.png)

...
Wed Dec  9 09:04:33 2020 daemon.err odhcpd[4186]: Failed to send to ff02::1%lan@eth0 (Permission denied)
Wed Dec  9 09:04:49 2020 daemon.warn odhcpd[4186]: A default route is present but there is no public prefix on lan thus we don't announce a default route!
Wed Dec  9 09:04:49 2020 daemon.err odhcpd[4186]: Failed to send to ff02::1%lan@eth0 (Permission denied)
Wed Dec  9 09:05:05 2020 daemon.warn odhcpd[4186]: A default route is present but there is no public prefix on lan thus we don't announce a default route!
Wed Dec  9 09:05:05 2020 daemon.err odhcpd[4186]: Failed to send to ff02::1%lan@eth0 (Permission denied)
Wed Dec  9 09:05:21 2020 daemon.warn odhcpd[4186]: A default route is present but there is no public prefix on lan thus we don't announce a default route!
Wed Dec  9 09:05:21 2020 daemon.err odhcpd[4186]: Failed to send to ff02::1%lan@eth0 (Permission denied)
Wed Dec  9 09:05:37 2020 daemon.warn odhcpd[4186]: A default route is present but there is no public prefix on lan thus we don't announce a default route!
Wed Dec  9 09:05:37 2020 daemon.err odhcpd[4186]: Failed to send to ff02::1%lan@eth0 (Permission denied)
Wed Dec  9 09:05:53 2020 daemon.warn odhcpd[4186]: A default route is present but there is no public prefix on lan thus we don't announce a default route!
Wed Dec  9 09:05:53 2020 daemon.err odhcpd[4186]: Failed to send to ff02::1%lan@eth0 (Permission denied)
Wed Dec  9 09:06:09 2020 daemon.warn odhcpd[4186]: A default route is present but there is no public prefix on lan thus we don't announce a default route!
Wed Dec  9 09:06:09 2020 daemon.err odhcpd[4186]: Failed to send to ff02::1%lan@eth0 (Permission denied)
Wed Dec  9 09:06:25 2020 daemon.warn odhcpd[4186]: A default route is present but there is no public prefix on lan thus we don't announce a default route!
Wed Dec  9 09:06:25 2020 daemon.err odhcpd[4186]: Failed to send to ff02::1%lan@eth0 (Permission denied)

## Specifications

- OpenMPTCProuter version: v0.56.5 r0+14653-a439f1bb47
- OpenMPTCProuter VPS version: 5.4.74-mptcp 0.1022
- OpenMPTCProuter platform: openmptcprouter-v0.56.5-r0+14653-a439f1bb47-x86-64-generic-ext4-combined-efi.ova

VPS : Debian hosted on Azure France Central Standard B1ms (1 vcpus, 2 GiB memory)
OpenMPTCProuter installed on Synology NAS via Virtual Manager.
4G BOX : MR600
ADSL: Orange BOX (Sosh)
DHCP disabled on both 4G box and ADSL box.

Connexions
NAS connected with LAN to orange box
4G Box connected with LAN to orange box
PC connected with LAN to orange box

**Comment by Ysurac** [comment]
It's possible that 4G box filter some ICMP request.
Logs are not related, I will remove them in next release.
