### ISSUE TITLE
My connection is blocked?

### ISSUE THREAD

**Issue by KaylFr** [Ysurac/openmptcprouter#1446]
Hello

Here I will need some advice,

I installed OMR on a Raspberry Pi 4
- A 4G Router (MR600)
- A freebox

I reach 50Mbits / s, and when I add a connection to this configuration a 4G connection and well this speed does not increase at all

My VPS is a Milkywan (also test with an OVH VPS)

I wonder where it can come from, possibility of solving this "problem"?

Thanks in advance

// --------- French

Bonjour

Voila j'aurai besoin de conseil,

J'ai installer OMR sur un Raspberry Pi 4
- Un Routeur 4G (MR600)
- Une freebox

J'atteint 50Mbits/s, et lorsque j'ajoute une connection a cet configuration une connection 4G et bien ce debit n'augmente pas du tous

Mon VPS est un Milkywan (tester aussi avec un VPS OVH)

Je me demande d'ou cela peut il bien venir, possibilité de regler ce "probleme" ?

Merci d'avance

**Comment by Malaga82** [comment]
Hello,
in wizard try to check this:
![image](https://user-images.githubusercontent.com/3518802/101952181-86893800-3bf8-11eb-806a-615d622c5a2a.png)
then do a speedtest and check if speed is aggregated.
MPTCP could be blocked by ISP.

**Comment by KaylFr** [comment]
Hello

![Capture d’écran 2020-12-15 à 09 31 16](https://user-images.githubusercontent.com/17416880/102190451-55d72600-3eb8-11eb-9533-8350896d4a5d.png)


I have check this box

**Comment by Malaga82** [comment]
it's "normal", go to VPN, OpenVPN, you'll see a wan2 named VPN, stop and start it again.
then wait a bit.

**Comment by KaylFr** [comment]
after activating the VPN, my speed caps at 50Mbits

**Comment by KaylFr** [comment]
By cons when the 4G connection is alone (without VPN) the download goes up to 120Mbits (freebox connection deactivate)

**Comment by Malaga82** [comment]
in /network/mptcp/bandwidth there is a graph of both WANS: did you see traffic for both wan1 and wan2?
is multipath enabled for the wan2 in wizard ( wan1 is master )?
![image](https://user-images.githubusercontent.com/3518802/102409476-68a04680-3fef-11eb-938d-9fc5308ef388.png)
