### ISSUE TITLE
Certificate Expired - repo.openmptcprouter.com

### ISSUE THREAD

**Issue by tentious** [Ysurac/openmptcprouter#1449]
## Expected Behavior
Certificate should not be expired.

## Current Behavior
Certificate is expired.

When installing VPS script on debian 10 I get this error from APT:

Err:5 https://repo.openmptcprouter.com stretch Release
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 2001:41d0:2:7fc0::4 443]

## Possible Solution
Renew certificate for apt repo.

## Steps to Reproduce the Problem

Execute the VPS install script.

Or, go to https://repo.openmptcprouter.com/ via browser and view certificate - it expires 12/12/2020.

**Comment by Ysurac** [comment]
Fixed.
