### ISSUE TITLE
bug after restart rasberry

### ISSUE THREAD

**Issue by tallyhome** [Ysurac/openmptcprouter#1454]
## Expected Behavior

Hello,

I appeal to you because I dry.

I tried everything and I can't find any solutions ..

so VPS install OK

Rasberry facilities OK

![router-1_LI](https://user-images.githubusercontent.com/37673782/102083343-ac3e5900-3e13-11eb-9efe-2083dd699704.jpg)
<img width="819" alt="router-2-apres-reboot-rasbery" src="https://user-images.githubusercontent.com/37673782/102083351-b2ccd080-3e13-11eb-9c94-2c9e179a744b.png">

## Current Behavior

then I enter all the info everything works perfectly fine, but if I reboot the pi4 or if I turn it off and turn it on again nothing works.

If I flash the SD again and start again, I enter all the info and it works but if I reboot, nothing works.

## Specifications

  - OpenMPTCProuter version: 

I have tester
image ext4: openmptcprouter-v0.56.5-r0 + 14653-a439f1bb47-bcm27xx-bcm2709-rpi-2-ext4-factory.img.gz
and
image ext4: openmptcprouter-v0.56.5-r0 + 14653-a439f1bb47-bcm27xx-bcm2711-rpi-4-ext4-factory.img.gz

as well as this one on a PI3 B +
image ext4: openmptcprouter-v0.56.5-r0 + 14653-a439f1bb47-bcm27xx-bcm2709-rpi-2-ext4-factory.img.gz

and
image ext4: openmptcprouter-v0.56.5-r0 + 14653-a439f1bb47-bcm27xx-bcm2710-rpi-3-ext4-factory.img.gz

  - OpenMPTCProuter VPS version: 

I tested on a Debian 9
a Debian 10
Ubuntu 18
and Ubuntu 20

  - OpenMPTCProuter platform: 

testeur sur un RPI 4
et sur un RPI 3B +

**Comment by Ysurac** [comment]
In first screenshot, there is no VPS defined, on second screenshot there is many problems ;)
On RPI4, you should use only openmptcprouter-v0.56.5-r0 + 14653-a439f1bb47-bcm27xx-bcm2711-rpi-4-ext4-factory.img.gz image.
What is the status page info when everything work ?
What do you set in wizard page ?
What do you have in system log when you have issue ?

**Comment by tallyhome** [comment]
hi

so with a vps or not, the problem remains the same
I also did some tests with this image
  openmptcprouter-v0.56.5-r0 + 14653-a439f1bb47-bcm27xx-bcm2711-rpi-4-ext4-factory.img.gz

when everything works, it's screen 1
https://user-images.githubusercontent.com/37673782/102083343-ac3e5900-3e13-11eb-9efe-2083dd699704.jpg

for the screen wizard page:

[Log System.txt](https://github.com/Ysurac/openmptcprouter/files/5690289/Log.System.txt)
<img width="474" alt="config-freebox" src="https://user-images.githubusercontent.com/37673782/102109751-af960c80-3e34-11eb-9427-fd5897869ea4.png">
<img width="549" alt="config-Box4G" src="https://user-images.githubusercontent.com/37673782/102109770-b3c22a00-3e34-11eb-8b9a-7a2732cc4001.png">

**Comment by Ysurac** [comment]
In screenshot 1, it's not working as it's using direct output and not VPS.
How are connected the WANs ? it's strange to have wan1 and wan2 as real physical interface and not as MacVlan.

**Comment by ebuyfr** [comment]
Hello,
J'ai eu un gros problème de ce genre lors de la mise à jour en dernière version, au la première config WAN ça allait, dès que je faisait ma deuxième en brachant le câble je perdais la main, je ne me connectait même plus sur l'interface d'admin, même en rechargeant une config sauvegardée ça ne voulait pas. J'y ai passé la nuit, 4 réinstall from scratch, au grand regret de ma femme...
La solution que j'ai trouvée :  fresh install, supprimer toutes les interfaces de type WAN, les recréer à la main dans Interfaces (ne pas utiliser Wizard) puis les administrer dans le Wizard (j'ai rebooté entre chaque admin mais je ne sais pas si c'est vraiment nécessaire).
J'ai récupérer ma config et ça fonctionne à nouveau !!

Pour info j'ai une Freebox et j'ai trouvé une petite astuce qui m'embêtait auparavant concernant le lien entre le Player et le Server (Je gardais une @IP pour le Player dans la Freebox que je démarrais en premier avant de démarrer mon RasberryPi qui sert de serveur DHCP dans OpenMptcpRouter.)
J'ai entré dans Nom d'hôtes : mafreebox.freebox.fr = @IP du Server, la télé fonctionne !!
Pas les applications (erreur réseau) mais le principal c'est la télé ;)

**Comment by tallyhome** [comment]
look Movie 

New install on sdcard and new config 
for this test i just add freebox

https://drive.obione.net/drive/s/69yG6cC3gi0nE3e45YedyiHvTuBgCa

**Comment by Ysurac** [comment]
Please answer to questions...
Why do you set interface type as normal ? This can't work that way.

**Comment by tallyhome** [comment]
I go through the configuration wizard.
and on your site it is noted as normal.
that said, I just tested with MacVlan type and I have the same problem

**Comment by Ysurac** [comment]
It is not noted as normal in the documentation.
Try again with macvlan. Only set VPS IP, key, and WANs IPs/gateway.

**Comment by tallyhome** [comment]
<img width="453" alt="ServerVPS Obione" src="https://user-images.githubusercontent.com/37673782/102118951-af037300-3e40-11eb-8996-0c32be68269b.png">
<img width="427" alt="Wan-1 MacVLAN" src="https://user-images.githubusercontent.com/37673782/102118961-b296fa00-3e40-11eb-8e86-3856a8141422.png">

**Comment by tallyhome** [comment]
<img width="560" alt="result" src="https://user-images.githubusercontent.com/37673782/102119092-e114d500-3e40-11eb-9e5f-80a9c66a9d7c.png">

**Comment by Ysurac** [comment]
wlan0 as physical interface ? you use wifi now ? Why do you don't keep default configuration ?

**Comment by tallyhome** [comment]
I do nothing, it's your system which automatically puts in wlan0 the wan1 has disappeared.

**Comment by tallyhome** [comment]
[video-carte-reseau.zip](https://github.com/Ysurac/openmptcprouter/files/5690805/video-carte-reseau.zip)
Look video

**Comment by Ysurac** [comment]
As you can see in your own video, default physical interface is eth0.
A MacVLAN interface is a "virtual" interface based on a real physical interface. By default on RPI, as there is only one physical port, 2 MacVLANs interfaces WAN1 and WAN2 are created based on eth0. It's not possible to base a MacVLAN interface on a MacVLAN interface.

**Comment by tallyhome** [comment]
okay,
so i do what?

**Comment by ebuyfr** [comment]
Hey are you read my answer?
Go to Interfaces and delete all WANs.
Reboot. Go back to Interfaces and create them by hand without going through the Wizard. Use the Wan Interfaces created in Interfaces to add them with the Wizard and reboot.

**Comment by tallyhome** [comment]
ebuyfr and for interface physique a choose eth0?

**Comment by ebuyfr** [comment]
Yes and Type is MacVLAN

**Comment by tallyhome** [comment]
ok, another problem with this config.
look screen

MacVLAN and eth0
<img width="512" alt="eth0" src="https://user-images.githubusercontent.com/37673782/102124917-2c32e600-3e49-11eb-93d6-68eefe947266.png">

**Comment by ebuyfr** [comment]
at the top right, the changes are not applied!

**Comment by tallyhome** [comment]
samme problem

<img width="624" alt="eth0-2" src="https://user-images.githubusercontent.com/37673782/102127588-f98aec80-3e4c-11eb-80a8-906a3cdec65e.png">

**Comment by tallyhome** [comment]
<img width="588" alt="eth0-3" src="https://user-images.githubusercontent.com/37673782/102127750-2ccd7b80-3e4d-11eb-903a-26b7d9fdf7bc.png">

**Comment by Ysurac** [comment]
There is 2 issues here:
* You didn't set a VPS IP at first configuration, this disable the proxy. In the wizard check "advanced settings" checkbox and set proxy to shadowsocks (it's the default)
* Check router and VPS time, there is a time problem as it's said.

**Comment by tallyhome** [comment]
hi
i not proxy shadow
<img width="374" alt="not-proxy" src="https://user-images.githubusercontent.com/37673782/102128654-78ccf000-3e4e-11eb-9e75-597810d743bd.png">

**Comment by Ysurac** [comment]
Advanced settings checkbox in wizard.

**Comment by Randdrick** [comment]
Hi tallyhome,
if your RPI 4 lost his config after restart it's beacause you have a problem on your SDCARD. You must reinstall your RPI as if the first install.
To clean your partition, enter the following command on your RPi 4: ( see documentation : https://openwrt.org/docs/guide-user/troubleshooting/failsafe_and_factory_reset )

* firstboot -y && reboot now

Now, you can restore a backup if you have.

**Comment by tallyhome** [comment]
Ysurac : yes in the Advanced settings in the wizard.

I am not a proxy activated

and Randdrick 
i tested 2 sdcard and same problem

**Comment by Ysurac** [comment]
So, as I said, set proxy to "Shadowsocks" in the wizard instead of none (not advanced settings tab, it's advanced settings checkbox).
Also fix time on VPS and router.

**Comment by tallyhome** [comment]
ok, i fine for proxy 👍 and for 
how do we fix this problem
Large time difference between server and router

**Comment by tallyhome** [comment]
it seems to work.

now i have another question.
is it possible.

I have an internal network with synology rt1900a router.
or above everything is connected, printer, computer, tablet, phone, Nas, etc ...

is it possible to add internet access via OMR (on rpi4)

because I know that OMR has its own DHCP
