### ISSUE TITLE
Access to lan with vpn

### ISSUE THREAD

**Issue by Roken120** [Ysurac/openmptcprouter#1456]
In french : 
Bonjour,
Est-ce possible de faire un tunnel qui utiliser openmtprouter afin de d'avoir accès au lan de mon réseau avec un VPN de manière stable et fluide. J'ai fait un serveur openvpn mais celui est très lent en latence (j'ai plus de 100ms dans le tunnel) alors que j'ai deux 
fibre coaxial avec un ping de 22ms généralement, et le débit en upload et download est très très lent.
Pensez-vous que je puissent directement me brancher sur le serveur OpenMTPCRouter afin d'éviter ce problème la ?  (j'ai généralement maximum 30ms avec OpenMTPCRouter en pingant google ou autre)
In english : 
Hello,
Is it possible to make a tunnel which use openmtprouter in order to have access to the lan of my network with a VPN in a stable and fluid way. I made an openvpn server but the one is very slow in latency (I have more than 100ms in the tunnel) while I have two coaxial fiber with a ping of 22ms generally, and the upload and download speed is very very slow.
Do you think I can directly connect to the OpenMTPCRouter server in order to avoid this problem?

**Comment by Malaga82** [comment]
You can use an internal service that does VPN ( like wireguard ), open and forward the relative ports, that's work pretty fine.
If you want to use built-in capatabilities of omr-router to do that, i don't know, i prefer to not mess the router with services i can deploy somewhere else and could be unstable for omr-router.
