### ISSUE TITLE
update from 0.56.5 to 0.57 : version number noy updated

### ISSUE THREAD

**Issue by sirius5481** [Ysurac/openmptcprouter#1469]
## Expected Behavior

after update from 0.56.5 to 0.57 , message asking to update shoudn't be present in the web interface
## Current Behavior

"You have OpenMPTCProuter version 0.56.5 and version 0.57 is now available" still present after update
## Steps to Reproduce the Problem

  1. update with the zip file 0.57 in update section and keep parameters
  2. after reboot : web interface still asking to update
  3. ssh console show the goog 0.57 version

## Specifications

  - OpenMPTCProuter version:  0.56.5 to 0.57
  - OpenMPTCProuter VPS version:  0.1023
  - OpenMPTCProuter platform:  x86_64

**Comment by Ysurac** [comment]
It's a know issue. This will be solved in 0.57.1
