### ISSUE TITLE
Update 0.56.5 to 0.57 - Strange logs

### ISSUE THREAD

**Issue by Corrado56** [Ysurac/openmptcprouter#1470]
## Expected Behavior
No strange logs

## Current Behavior
After the update the OMR router starts correctly, but after few minutes I have continually those errors on System LOG
![image](https://user-images.githubusercontent.com/10588158/102923160-907c2800-448f-11eb-806a-36993e4ecc3a.png)

And those on Kernel LOG
![image](https://user-images.githubusercontent.com/10588158/102923206-a4278e80-448f-11eb-9acb-3a9d587a6e29.png)

BUT except for this strange log, the router is actually working well, and I am not blocked.

## Specifications

  - OpenMPTCProuter version:  0.57 
  - OpenMPTCProuter VPS version: 0.1023 
  - OpenMPTCProuter platform: Linksys3200ACM
  
Other info:
  - Sysupdate, not factory install + load configuration backup
  - Rebooted OMR manually after the update

**Comment by Ysurac** [comment]
It's related to wifi.

**Comment by Ysurac** [comment]
Changing some settings in wifi like "maximum transmit power" and "country" should remove the logs. I will check if I can reproduce and solve the issue (but maybe not before next year).

**Comment by Corrado56** [comment]
I tried to change some parameters without success, and the wireless is no more functioning.
those system log lines have some meaning to You ?
![image](https://user-images.githubusercontent.com/10588158/102944879-5c6b2c00-44bc-11eb-9d67-50bac7925724.png)

**Comment by Corrado56** [comment]
After a reboot wireless restarted and I have no more strange messages.
Ceased alarm
