### ISSUE TITLE
Feature Request: Example/how-to config for mobile road warrior setups (with streaming in mind)

### ISSUE THREAD

**Issue by rmoriz** [Ysurac/openmptcprouter#1471]
**Is your feature request related to a problem? Please describe.**

Mobile streaming ("IRL", field reporting) and broadcasting is becoming much more popular but using only one 4/5G link is not reliable enough. Various commercial solutions are bonding mobile links (usually 2-4 modems) with proprietary technology (e.g. "LiveU") or MPTCP+shadowsocks (Chinese vendors on AliExpress).

**Describe the solution you'd like**

An example config or how-to targeting the following scenario:

- Hardware, given RPi4 or some other device with a couple of USB ports and Wifi onboard
- internal Wifi acts as AP for wireless devices (smartphones, cameras)
- internal eth0 acts as interface for wired local client devices (e.g. wired laptops or additional local devices)
- upstream based on multiple 4/5G modems all connected via USB.

Bonus but maybe out of scope:
- use case specific options in luci related to video-streaming, e.g. RTMP forwarding using ffmpeg.
- USB HDMI encoder support (the cheap 1080p ones for 10$)

**Describe alternatives you've considered**
- popular but expensive commercial product: https://gosolo.tv/ (almost all larger Twitch IRL publishers seem to use it)
- see also: https://www.gunrun.tv/parts-list-lul
- might be an opportunity to create a paid product around your openmptcprouter project?

**Comment by suyuan168** [comment]
yes  i do ~
