### ISSUE TITLE
Missing ubuntu20.04-x86_64.sh

### ISSUE THREAD

**Issue by afrocubanito** [Ysurac/openmptcprouter#1472]
## Expected Behavior

Download Ubuntu shell script via wget

## Current Behavior

wget find nothing at this link https://www.openmptcprouter.com/server/ubuntu20.04-x86_64.sh

## Possible Solution

add ubuntu20.04-x86_64.sh in web folder https://www.openmptcprouter.com/server/

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Context (Environment)

Trying to update my VPS

## Specifications

  - OpenMPTCProuter version: 
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter platform:

**Comment by Ysurac** [comment]
Fixed.
But in fact all scripts are the same, the debian script work for ubuntu too ;)
