### ISSUE TITLE
Should i update ?

### ISSUE THREAD

**Issue by rifaterdemsahin** [Ysurac/openmptcprouter#1474]
knock on the wood (: it is working great the last 40 days

![image](https://user-images.githubusercontent.com/5270036/103070918-7ee36f00-45ba-11eb-982c-fc7da34455a2.png)

What do I get with the new update and should I also update the VPS as well ?

**Comment by rifaterdemsahin** [comment]
Where is the release notes?
not these?
https://github.com/Ysurac/openmptcprouter/commit/1222a62634a33b99caa2780701bddd4416c8ebcd

Maybe these
https://github.com/Ysurac/openmptcprouter/releases

Only git commit are here are there easy to read notes?
https://github.com/Ysurac/openmptcprouter/commit/0991afaa30505f48e55812f61545c9c563e56308

**Comment by Ysurac** [comment]
Release notes in on https://www.openmptcprouter.com/ as always.
Detailed changes are on https://github.com/Ysurac/openmptcprouter/commits/master and https://github.com/Ysurac/openmptcprouter-feeds/commits/master

**Comment by rifaterdemsahin** [comment]
my bad I should have scrolled
![image](https://user-images.githubusercontent.com/5270036/103154182-c79f5180-478d-11eb-9b54-c1dbeb2399f8.png)

idea: 
a dedicated page would be easier for us
![image](https://user-images.githubusercontent.com/5270036/103154236-f3bad280-478d-11eb-96bf-c50f4f4dadd2.png)
