### ISSUE TITLE
How to interpret the load average ?

### ISSUE THREAD

**Issue by rifaterdemsahin** [Ysurac/openmptcprouter#1481]
Start
![image](https://user-images.githubusercontent.com/5270036/103154142-9757b300-478d-11eb-8a09-2eba04d692f2.png)

after 40 days
![image](https://user-images.githubusercontent.com/5270036/103154139-9030a500-478d-11eb-972d-2245097ab9e1.png)

**Comment by Ysurac** [comment]
It's Linux load average. So https://en.wikipedia.org/wiki/Load_(computing) will give you a better answer than me.
