### ISSUE TITLE
Portforward Multi IP's

### ISSUE THREAD

**Issue by MTSmhas** [Ysurac/openmptcprouter#1482]
Hi i have a problem. The Multi IP OMR settings works. But how can i forward Ports to the VPS?

I have read all postings but i have nothing found to resolve my problem.

**Comment by MTSmhas** [comment]
I can go out with the second ip. But i can noting forward to the second ip.

**Comment by Ysurac** [comment]
How did you configure port forward ?

**Comment by MTSmhas** [comment]
![Unbenannt](https://user-images.githubusercontent.com/76729306/103277139-a1b1c100-49c8-11eb-904b-06b752f90bc3.JPG)
![Unbenannt2](https://user-images.githubusercontent.com/76729306/103277141-a24a5780-49c8-11eb-939d-73aaf9ce9fa4.JPG)

**Comment by MTSmhas** [comment]
![Unbenannt3](https://user-images.githubusercontent.com/76729306/103277300-ffdea400-49c8-11eb-8279-5ee9f9a732aa.JPG)
But i think the /etc/shorewall/rules are wrong...

**Comment by MTSmhas** [comment]
![Unbenannt4](https://user-images.githubusercontent.com/76729306/103277447-49c78a00-49c9-11eb-8f26-915a2feab4d8.JPG)
sry thats the correct screen.

**Comment by MTSmhas** [comment]
But now all Ports closed.

**Comment by MTSmhas** [comment]
But if I do the extern adresse to any is on all ip address the port 22 open.

**Comment by MTSmhas** [comment]
If i set the external IP from the server i have the same error

**Comment by MTSmhas** [comment]
![Unbenannt6](https://user-images.githubusercontent.com/76729306/103278089-ec343d00-49ca-11eb-9d90-4262109805c0.JPG)

**Comment by MTSmhas** [comment]
![Unbenannt8](https://user-images.githubusercontent.com/76729306/103278406-b6438880-49cb-11eb-9a7f-ea64ee2e09c7.JPG)
![Unbenannt9](https://user-images.githubusercontent.com/76729306/103278407-b6dc1f00-49cb-11eb-9410-d0152d214df3.JPG)
![Unbenannt10](https://user-images.githubusercontent.com/76729306/103278410-b6dc1f00-49cb-11eb-9d06-70f6bcf11b32.JPG)
This is my omrip1_rule

**Comment by Ysurac** [comment]
The correct way is to set external VPS ip as external IP., like this seems to be in last shorewall screen.
Shadowsocks is not used in redirection from VPS.

Can you ping from the VPS 10.255.249.6 ? If yes, what do you have using tcpdump on router side on the interface with this IP ?

**Comment by MTSmhas** [comment]
the ping from the vps is not working
![Unbenannt11](https://user-images.githubusercontent.com/76729306/103279142-78dffa80-49cd-11eb-88c9-4dc6ef58acd3.JPG)

**Comment by MTSmhas** [comment]
but i can ping the 192.168.1.13... 
![Unbenannt12](https://user-images.githubusercontent.com/76729306/103279273-b04ea700-49cd-11eb-902e-f14badb5f2f9.JPG)

**Comment by Ysurac** [comment]
ok, so it's the problem, the gre tunnel is not working.
What is the result of ```ip a``` on the router ?

**Comment by Ysurac** [comment]
And what is the VPN used ? (only glorytun TCP is tested for now)

**Comment by MTSmhas** [comment]
I use glorytun TCP

**Comment by MTSmhas** [comment]
root@USA-Router:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP,80000> mtu 65536 qdisc noqueue state UNKNOWN group                                                                                                                                                              default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ip6tnl0@NONE: <NOARP,80000> mtu 1452 qdisc noop state DOWN group default qlen                                                                                                                                                              1000
    link/tunnel6 :: brd ::
3: sit0@NONE: <NOARP,80000> mtu 1480 qdisc noop state DOWN group default qlen 10                                                                                                                                                             00
    link/sit 0.0.0.0 brd 0.0.0.0
4: eth0: <BROADCAST,MULTICAST,PROMISC,UP,LOWER_UP,80000> mtu 1500 qdisc fq_codel                                                                                                                                                              state UP group default qlen 1000
    link/ether 00:0c:29:03:d4:89 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.154/24 brd 192.168.1.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fddb:1d41:bbb3::1/60 scope global noprefixroute
       valid_lft forever preferred_lft forever
    inet6 fe80::20c:29ff:fe03:d489/64 scope link
       valid_lft forever preferred_lft forever
5: gre0@NONE: <NOARP,80000> mtu 1476 qdisc noop state DOWN group default qlen 10                                                                                                                                                             00
    link/gre 0.0.0.0 brd 0.0.0.0
6: gretap0@NONE: <BROADCAST,MULTICAST,80000> mtu 1462 qdisc noop state DOWN grou                                                                                                                                                             p default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
7: erspan0@NONE: <BROADCAST,MULTICAST,80000> mtu 1450 qdisc noop state DOWN grou                                                                                                                                                             p default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
8: ip6gre0@NONE: <NOARP,80000> mtu 1448 qdisc noop state DOWN group default qlen                                                                                                                                                              1000
    link/gre6 :: brd ::
9: teql0: <NOARP,80000> mtu 1500 qdisc noop state DOWN group default qlen 100
    link/void
10: wan1@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP                                                                                                                                                              group default qlen 100
    link/ether 5a:9a:c8:e3:f2:e9 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.114/24 brd 192.168.1.255 scope global wan1
       valid_lft forever preferred_lft forever
11: gre4-omrip3gre@NONE: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP,80000> mtu 128                                                                                                                                                             0 qdisc noqueue state UNKNOWN group default qlen 50
    link/gre 10.255.255.2 peer 206.221.178.45
    inet 10.255.249.14/30 brd 10.255.249.15 scope global gre4-omrip3gre
       valid_lft forever preferred_lft forever
17: gre4-omrip0gre@NONE: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP,80000> mtu 128                                                                                                                                                             0 qdisc noqueue state UNKNOWN group default qlen 50
    link/gre 10.255.255.2 peer 206.221.178.44
    inet 10.255.249.2/30 brd 10.255.249.3 scope global gre4-omrip0gre
       valid_lft forever preferred_lft forever
19: gre4-omrip2gre@NONE: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP,80000> mtu 128                                                                                                                                                             0 qdisc noqueue state UNKNOWN group default qlen 50
    link/gre 10.255.255.2 peer 206.221.178.43
    inet 10.255.249.10/30 brd 10.255.249.11 scope global gre4-omrip2gre
       valid_lft forever preferred_lft forever
20: gre4-omrip4gre@NONE: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP,80000> mtu 128                                                                                                                                                             0 qdisc noqueue state UNKNOWN group default qlen 50
    link/gre 10.255.255.2 peer 206.221.178.46
    inet 10.255.249.18/30 brd 10.255.249.19 scope global gre4-omrip4gre
       valid_lft forever preferred_lft forever
21: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP,80000> mtu 1500 qdisc fq_code                                                                                                                                                             l state UNKNOWN group default qlen 1000
    link/none
    inet 10.255.255.2 peer 10.255.255.1/32 scope global tun0
       valid_lft forever preferred_lft forever
22: gre4-omrip1gre@NONE: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP,80000> mtu 128                                                                                                                                                             0 qdisc noqueue state UNKNOWN group default qlen 50
    link/gre 10.255.255.2 peer 206.221.178.42
    inet 10.255.249.6/30 brd 10.255.249.7 scope global gre4-omrip1gre
       valid_lft forever preferred_lft forever

**Comment by MTSmhas** [comment]
![Unbenannt13](https://user-images.githubusercontent.com/76729306/103299889-e146d000-49fd-11eb-91a0-dfe451c69208.JPG)

**Comment by Ysurac** [comment]
Try to ping from the router 10.255.249.5, this should put gre tunnel up (this will be solved in next release).
Then check from VPS if you can ping 10.255.249.6 again, and check if port forward work or not.

**Comment by MTSmhas** [comment]
router:~# ping 10.255.249.5
PING 10.255.249.5 (10.255.249.5) 56(84) bytes of data.
64 bytes from 10.255.249.5: icmp_seq=1 ttl=64 time=0.123 ms
64 bytes from 10.255.249.5: icmp_seq=2 ttl=64 time=0.096 ms

**Comment by MTSmhas** [comment]
from router i can ping 10.255.249.5 this is already okay but i cant ping from vps the 10.255.249.6

**Comment by MTSmhas** [comment]
nmap -p22 -Pn 10.255.249.6
Starting Nmap 7.70 ( https://nmap.org ) at 2020-12-29 11:56 EST
Nmap scan report for 10.255.249.6
Host is up.

PORT   STATE    SERVICE
22/tcp filtered ssh

Nmap done: 1 IP address (1 host up) scanned in 2.30 seconds

**Comment by MTSmhas** [comment]
i think the firewall is the problem.

**Comment by MTSmhas** [comment]
But the curl ifconfig.me 206.221.178.42 is correct.

**Comment by MTSmhas** [comment]
oh it works... i have stoip the ss.rules and start again now works.

**Comment by MTSmhas** [comment]
Okay i hope you can fix this in the next release. But Thanks for all!!!!

**Comment by MTSmhas** [comment]
stop.... only the port in vpn is open not in the vps..

**Comment by MTSmhas** [comment]
so now ping run and ports closed... i dont understand thsi.

**Comment by MTSmhas** [comment]
okay i found the error. when i disable the ss.rules work the port forwarding but the ip from client change to the standart vps ip. I think the rules are not realy okay..

**Comment by Ysurac** [comment]
I updated the VPS script, instead of using GRE tunnel, this use the VPN for now.
Not ideal, but working for now.

**Comment by MTSmhas** [comment]
Okay can you tell me how the ip config in the vps is. I set the ips with eth0:1 eth0:2 etc

**Comment by MTSmhas** [comment]
Now works without errors. I have the vps reinstall and the ips to the eth0 added "ip addr add 10.1.102.60No works without inuse. I have the vps reinstall and the ips to the eth0 added "ip addr add 10.1.102.60/24 dev eth0" without a second eth0:0.
