### ISSUE TITLE
Question: Running an node script on openmptcprouter

### ISSUE THREAD

**Issue by ByteArrayException** [Ysurac/openmptcprouter#1489]
Hey,

is it possible to run an NodeJS Script on an machine (not vps)?

Best regards

**Comment by Ysurac** [comment]
You need to install node package.

**Comment by ByteArrayException** [comment]
First, thank you for your quick reply.
Would you have a sample command? I do not know BusyBox well.

**Comment by Ysurac** [comment]
Via the interface, in System->software, update package list and install node.
Or via ssh, using ```opkg update``` and ```opkg install node``` or something like that.

**Comment by ByteArrayException** [comment]
Okay, i will test that tomorrow, and if it works. i will close this issue. Thanks for your help.

**Comment by ByteArrayException** [comment]
Sorry for the late reply, but it works!
Thanks for your help.
Closed.
