### ISSUE TITLE
support for  Atheros AR7xxx/AR9xxx

### ISSUE THREAD

**Issue by kapook007** [Ysurac/openmptcprouter#149]
hello 
i try openmptcprouter is fully on x86-64.
but most router cpu is Atheros AR7xxx/AR9xxx  and openwrt user kernel 4.9.124
**openmptcprouter  only support kernel 4.14.67
would you please make support kernel 4.9.124 ?

thank you.

**Comment by Ysurac** [comment]
With kernel 4.14 I can use some latest MPTCP features. It's better to update to kernel 4.14.
Kernel 4.9 in OMR have MPTCP 0.93 support, but it's not tested at all.

All router with Atheros CPU that I know are too slow to support OpenMPTCProuter, but I'm open to suggestion.
