### ISSUE TITLE
High CPU with GRE UP

### ISSUE THREAD

**Issue by freakdude** [Ysurac/openmptcprouter#1498]
## Expected Behavior
In version v0.56.5 GRE tunnels were not automatically built and the CPU was much lower and could handle more connections. 

## Current Behavior

GRE tunnel interfaces are enabled by default and once they come up the CPU is above 50% and adding more WAN interfaces causes the CPU to max out. 
![Base config](https://user-images.githubusercontent.com/13693/103514494-5b2ded80-4e32-11eb-823f-6e6121ce0b7d.png)

## Possible Solution

Disable GRE interfaces. 
Delete GRE interfaces. 
![GRE Shutdown](https://user-images.githubusercontent.com/13693/103514530-70a31780-4e32-11eb-89d2-26b725a38c49.png)

## Steps to Reproduce the Problem

  1. Add WAN connection
  2. Set WAN connection as Master
  3. Connect to VPS
  4. Check CPU usage

## Context (Environment)

Using the Raspberry Pi 4 4gb model with the 64bit version of  v0.57.2. New install not an upgrade. 

## Specifications

  - OpenMPTCProuter version:  0.57.2
  - OpenMPTCProuter VPS version: 0.1023
  - OpenMPTCProuter platform: RPI4

**Comment by Ysurac** [comment]
GRE tunnels are created when multiples IPs are available on a VPS. I'm not able to reproduce this issue.
Check in State->System log and kernel log if you have something when CPU is high.
