### ISSUE TITLE
Question: How to access LuCI / SSH on openmptcprouter from the VPS?

### ISSUE THREAD

**Issue by reedog117** [Ysurac/openmptcprouter#150]
## Expected Behavior

I would like to access the web and SSH ports on the openmptcprouter from the Internet, preferably via a port forward from the VPS. Because all of the Internet connections in my particular instance are transient 4G connections, this seems like the easiest way to access it for monitoring/reconfiguration purposes from a device not connected to the LAN side.

How would I configure this?

## Specifications

  - OpenMPTCProuter version: openmptcprouter v0.34.3 r7288-a662d6f6bc
  - OpenMPTCProuter VPS version: 0.48
  - OpenMPTCProuter platform: RPi3B+ 64bit

**Comment by Ysurac** [comment]
You have to use https://github.com/Ysurac/openmptcprouter/wiki/Port-forwarding on VPS and open the port 80 on OpenMPTCProuter.
It's not a good idea to have OpenMPTCProuter wide open on internet.
