### ISSUE TITLE
unable to upgrade sysupgrade file RPI3+

### ISSUE THREAD

**Issue by shihan84** [Ysurac/openmptcprouter#1502]
when trying to upgrade sysupgrade error is showing

Upload request failed: I/O failure while writing temporary file

file: 
 openmptcprouter-v0.57.2-r0+15225-bfc433efd4-bcm27xx-bcm2709-rpi-2-ext4-sysupgrade.img.gz (2020/12/30

help needed

**Comment by Ysurac** [comment]
Filesystem can be read only or you have a problem with your SD card.

**Comment by shihan84** [comment]
hi ysurac
what should be the fix, how should i remove readonly.

thanks for reply

**Comment by Ysurac** [comment]
You can try a fsck, but I would backup configuration, use a new good SD card, write image on it and import old configuration.
And try to not do to much hard reboot.
