### ISSUE TITLE
Wifi invité bloqué sur le LAN

### ISSUE THREAD

**Issue by JeedHome44** [Ysurac/openmptcprouter#1503]
Bonjour,

J'avais fait un wifi invité sur mon point d'accès TP Link en lui interdisant le LAN et en lui autorisant seulement internet.

Je n'avais pas eu de la famille à la maison depuis l'installation de OMR.

Hier, ma belle sœur vient et me dit ne pas avoir internet sur le wifi invité.

Je vois que c'est vrai. Il est bloqué. Il n'est donc pas possible de créer un wifi invité sur un point d'accès du LAN OMR?

Quelle solution pour laisser aux invités un wifi qui ne donne aucun accès au LAN de la maison?

Il faut utiliser le wifi du Raspberry OMR?

Comment faire svp?

Merci

**Comment by vinceducat** [comment]
ton issue est un peu hors sujet et ne respecte pas la forme standard des issues.

mais pour t'eclairer, perso j utilise un AP netgear et je peux avoir un wifi general / un wifi invite avec omr .... 

la config de ton ap est sans doute a revoir...
