### ISSUE TITLE
How do you tell if your WAN connection supports Multipath?

### ISSUE THREAD

**Issue by topbilling** [Ysurac/openmptcprouter#1509]
I see there's an MPTCP Support Check tab, but sometimes the same connection will return results and sometimes it will hang.  Is this the best way to check?  Should I be looking at the logs instead?

**Comment by Ysurac** [comment]
It's the best way to check. It can also be executed via SSH or Services->Terminal using ```omr-tracebox```. There is also ```omr-mptcp-intf <yourwaninterface>``` that check using multipath-tcp.org website if mptcp is available but result can be false sometimes.

**Comment by topbilling** [comment]
Thank you!
