### ISSUE TITLE
MTU glorytun-udp QoS/SQM problem

### ISSUE THREAD

**Issue by SoGooDFR** [Ysurac/openmptcprouter#151]
## Expected Behavior
Can access to my nas from outside. 

## Actual Behavior
Actually port forwarding to ma nas (synology works, but when i use SSL i've ERR_TIMED_OUT on browser and glorytun-udp spam me : 
```
Tue Sep  4 19:06:09 2018 daemon.err glorytun-udp[4127]: mud_send: Message too large
Tue Sep  4 19:06:54 2018 daemon.err glorytun-udp[4127]: mud_send: Message too large
Tue Sep  4 19:06:54 2018 daemon.err glorytun-udp[4127]: mud_send: Message too large
Tue Sep  4 19:16:42 2018 daemon.err glorytun-udp[4127]: mud_send: Message too large
Tue Sep  4 19:16:44 2018 daemon.err glorytun-udp[4127]: mud_send: Message too large
Tue Sep  4 19:16:47 2018 daemon.err glorytun-udp[4127]: mud_send: Message too large
Tue Sep  4 19:16:51 2018 daemon.err glorytun-udp[4127]: mud_send: Message too large
Tue Sep  4 19:16:51 2018 daemon.err glorytun-udp[4127]: mud_send: Message too large
Tue Sep  4 19:16:52 2018 daemon.err glorytun-udp[4127]: mud_send: Message too large
Tue Sep  4 19:16:52 2018 daemon.err glorytun-udp[4127]: mud_send: Message too large
Tue Sep  4 19:16:52 2018 daemon.err glorytun-udp[4127]: mud_send: Message too large
Tue Sep  4 19:16:54 2018 daemon.err glorytun-udp[4127]: mud_send: Message too large
Tue Sep  4 19:17:03 2018 daemon.err glorytun-udp[4127]: mud_send: Message too large
Tue Sep  4 19:17:25 2018 daemon.err glorytun-udp[4127]: mud_send: Message too large
```
This is a MTU problem.
NAS MTU : 1500.

## Steps to Reproduce the Problem

  1. Fresh install.
  2. Make port forwarding rule to my nas.
  3. See the results.

## Specifications

  - OpenMPTCProuter version:  openmptcprouter v0.34.2 r7288-a662d6f6bc
  - OpenMPTCProuter VPS version: OpenMPTCProuter VPS 0.48
  - OpenMPTCProuter platform: x64 on VMM Synology.

**Comment by SoGooDFR** [comment]
Problem fixed:
Change settings in settings > glorytun > edit
--> Uncheck MTU auto.
--> add mtu field
--> 1400 (same as my 4G)

Done.

**Comment by SoGooDFR** [comment]
After investigation, my 4G use 1400 as MTU. By default, glorytun-udp use 1500 (supposed) and generate packet loss ~45-50%. After fix the glorytun-udp MTU on routeur config to 1400, the connection have no packet loss.

**Comment by Ysurac** [comment]
I will try to set correct MTU in next release. Need to test that.

**Comment by SoGooDFR** [comment]
Ok, after a new clean install, openmptcprouter detect my 4G connection with MTU 1495.. For me the best solution is to set MTU on router and the server grap automatically the value. This method give more flexibility i think.

**Comment by Ysurac** [comment]
True, there is a bug in interface MTU calculation. This will be fixed in next release.

**Comment by SoGooDFR** [comment]
Okay, after many tests, the activation of SQM on egress (outbound) cause this : 
`...
Thu Sep  6 00:44:49 2018 daemon.err glorytun-udp[4646]: mud_send: Message too large
...`

**Comment by Ysurac** [comment]
When it's activated on a wan interface ?

**Comment by SoGooDFR** [comment]
Yes, on wan1 (4G).
