### ISSUE TITLE
OpenWRT version for Raspberry Pi 4 Wireless AP support?

### ISSUE THREAD

**Issue by kevmo314** [Ysurac/openmptcprouter#1514]
Hi, what version of OpenWRT is bundled with OpenMPTCProuter? It seems that only the snapshot version correctly supports Raspberry Pi 4 (https://openwrt.org/toh/raspberry_pi_foundation/raspberry_pi).

I'm not able to see the AP set up through LuCI and I've tried manually editing configs based on suggestions online, but I'm wondering if the real problem is that the OpenWRT version flashed isn't new enough?

**Comment by Ysurac** [comment]
A version from OpenWrt develop branch. There is a doc to set an API using a RPI: https://github.com/Ysurac/openmptcprouter/wiki/Configure-Wifi

**Comment by kevmo314** [comment]
Ah interesting, thanks I missed that page!
