### ISSUE TITLE
how to create a subinterface on openmptcp router

### ISSUE THREAD

**Issue by kams19** [Ysurac/openmptcprouter#1515]
Hi,
I have two WAN interfaces which I want to bring to OpenMPTCP router as a single trunk interface. 
How do I create a trunk interfaces on OpenMPTCP router and how do I make two subinterfaces under that?
Appreciate all your help.
Thanks

**Comment by Ysurac** [comment]
You can use VLAN, for exemple to use VLAN 10 on interface eth0, you need to create a new interface based on eth0.10
