### ISSUE TITLE
How to change de OMR webgui listen port - comment changer le port de l'interface web d'OMR

### ISSUE THREAD

**Issue by FabriceC01** [Ysurac/openmptcprouter#1516]
Hello,
I'm discovering OMR installed yesterday and I'd like to modify the port (443) of the gui because I want to do a port forwarding on my public VPS IP port 443 on an other local IP than OMR.
I can't find how to do this (neither in gui nor a nginx.conf not found)
Can someone help me ?

Merci
Fabrice

**Comment by Ysurac** [comment]
In Services->uHTTPd
