### ISSUE TITLE
Configuring with a USB 4G LTE modem no connection

### ISSUE THREAD

**Issue by kevmo314** [Ysurac/openmptcprouter#1517]
## Expected Behavior

ping or wget should work. I get the impression that this is a rather silly misconfiguration, but I've been trying to figure it out for a while now and not sure what's wrong... :( would be really grateful for the help

## Current Behavior

`ping google.com` doesn't result in any output. However, I think my LTE modem has ICMP disabled. I also tried wget'ing an ip however it can't connect.

Network status:

![image](https://user-images.githubusercontent.com/511342/104133037-0f59d780-534f-11eb-9c6a-4274b1a14f98.png)

MPTCP interfaces:

![image](https://user-images.githubusercontent.com/511342/104133190-eede4d00-534f-11eb-8f32-aa1bb6d3765e.png)

USB interface:

![image](https://user-images.githubusercontent.com/511342/104133175-dd954080-534f-11eb-9f93-212934ed0ac7.png)

`ip r` output:

```
root@OpenMPTCProuter:~# ip r
default via 192.168.10.1 dev wan1
default via 192.168.10.1 dev wan1 metric 3
127.0.0.0/8 dev lo proto static scope link metric 5
192.168.10.0/24 dev wan1 scope link metric 3
192.168.10.0/24 dev usb0 proto static scope link metric 8
```

## Specifications

  - OpenMPTCProuter version: v0.57.3
  - OpenMPTCProuter VPS version: 5.4.81-mptcp
  - OpenMPTCProuter platform: RPI4

**Comment by Ysurac** [comment]
The interface is not working at all.
What is the dongle model ? Some create an ethernet interface (Huawei Hi-Link for example), some need to use modem manager protocol.

**Comment by kevmo314** [comment]
I have a ZTE MF833V. The dongle itself works on a windows machine (I'm able to connect, sim works and everything). I noticed it registers as a cdc_ether interface on the rpi. Is there more config needed/additional drivers I need to download?

**Comment by Ysurac** [comment]
For this dongle, as it's seems to be in right mode, you only need to set the interface as DHCP client. This should work.

**Comment by kevmo314** [comment]
I see, I switched it over to DHCP client:

![image](https://user-images.githubusercontent.com/511342/104133704-36b2a380-5353-11eb-9a8a-23e83dbee277.png)

and updated the gateway for the WAN:

![image](https://user-images.githubusercontent.com/511342/104133713-4336fc00-5353-11eb-97e6-81b85169d574.png)

However the status page/symptoms still are unchanged: 

![image](https://user-images.githubusercontent.com/511342/104133726-4df19100-5353-11eb-85e8-679d0a6ec000.png)

I also tried binding the WAN to 192.168.0.112 with no success.

Also, if the interface is on DHCP, wouldn't the WAN binding fail if the DHCP lease expires and the modem gets assigned to a new IP? Is there a way around that?

**Comment by Ysurac** [comment]
Because you modified wan1 interface, and by default it's a MacVLAN interface. You need to switch it to normal in "Physical settings" tab in Network->Interface

**Comment by kevmo314** [comment]
Hmm, so I did that, wan1 still doesn't seem to want to connect?

![image](https://user-images.githubusercontent.com/511342/104151097-1104b900-53aa-11eb-8735-8aa9db5706fb.png)

**Comment by Ysurac** [comment]
The physical interface can't be wan1, set it to usb0

**Comment by kevmo314** [comment]
Thanks for the help, once everything is configured I must say OpenMPTCProuter works exceptionally well! I'm using this for a small side business, hopefully I'll be in a position to contribute to your patreon soon :)
