### ISSUE TITLE
LTE display problem of USB modem

### ISSUE THREAD

**Issue by eirdgms** [Ysurac/openmptcprouter#1518]
Sometimes LTE is displayed, sometimes it is unrealistic. LTE display is abnormal.
![123](https://user-images.githubusercontent.com/29945000/104138929-a328b380-53e2-11eb-8c0a-269a94a41564.png)

**Comment by Ysurac** [comment]
Please use template.
And what is the dongle and protocol used ?

**Comment by suyuan168** [comment]
你用的是什么卡托？型号，品牌。提问要模板
