### ISSUE TITLE
version VPS 0.1022

### ISSUE THREAD

**Issue by Florent4223** [Ysurac/openmptcprouter#1522]
Hello

To ensure a certain stability I would like to stay for a while on version 0.1022 of the VPS (associated with OMR 0.56.5)

No problem downloading OMR version 0.56.5, on the other hand what is the link to redownload the script for VPS 0.1022?

thank you

**Comment by Ysurac** [comment]
By using https://github.com/Ysurac/openmptcprouter-vps/tree/v0.1022
But I don't provide any support on old release.
