### ISSUE TITLE
Kernel Not able to boot on kvmvps@serversgalore.com.au

### ISSUE THREAD

**Issue by metro2450** [Ysurac/openmptcprouter#1529]
## Expected Behavior
finish installation on vps, reboot into system, can provide service to routers

## Current Behavior
Boot stuck at "Finished update UTMP about system Boot/Shutdown. "

## Specifications
![vps](https://user-images.githubusercontent.com/70131352/104985764-cf3cd800-5a65-11eb-9cd7-2934df7aa1b4.PNG)
 KVM 1G RAM tried virtio driver and ide/intel pro 1000 all fail at boot

  - OpenMPTCProuter version: v0.57.3
  - OpenMPTCProuter VPS version: VPS 0.1014 on Ubuntu 20.4
  - OpenMPTCProuter platform: R2S

**Comment by Ysurac** [comment]
I think a module can't be loaded, but I can't really help here.
I would need to rent a VPS, they accept Paypal ?

**Comment by metro2450** [comment]
> I think a module can't be loaded, but I can't really help here.
> I would need to rent a VPS, they accept Paypal ?

Recommended install is on Debian as indicated in the documentation. Ubuntu install is working in most case but some strange install may cause issues.

_Originally posted by @Ysurac in https://github.com/Ysurac/openmptcprouter/issues/1504#issuecomment-755232581_

After read this I have reinstalled Debian 10 x64 and everything is working perfectly.  Thank you very much :-)

**Comment by Ysurac** [comment]
ok cool :)
I can add serversgalore.com.au as supported VPS so ? I don't have many in australia
