### ISSUE TITLE
installing on partaker c4

### ISSUE THREAD

**Issue by Aijno** [Ysurac/openmptcprouter#1539]
## Expected Behavior
i am trying to install openmptcprouter on nuc partaker c4 with freeBSD to bondig two lte connection.

## Current Behavior
i download this file image https://download.openmptcprouter.com/release/v0.57.3/x86_64/targets/x86/64/openmptcprouter-v0.57.3-r0+15225-bfc433efd4-x86-64-generic-ext4-combined-efi.img.gz mount it with etcher for linux, and boot from usb on the nuc, but it dont  install it. am i doing something wrong? ( sorry for my bad english, and for dumb question but on this argument i am really newbie)

## Specifications

Partaker C4 New NUC Mini PC, Celeron J3160 Quad Core, 4 Intel i210AT Nic, X86 Computer Soft Router, Linux Server AES-Ni
version of openmptcprouter is 0.57.3

**Comment by Ysurac** [comment]
Are you sure that this computer have EFI support and that you must use it ?
I don't understand what you do with the USB key ?
