### ISSUE TITLE
OMR-Bypass

### ISSUE THREAD

**Issue by sonnyxp2008** [Ysurac/openmptcprouter#1542]
health to you, i am new and only recently using omptcpr. I would like to know if there is a valid alternative to bypass some sites without changing the dns or mac address. in practice I want to pass netflix on my master regardless of mac or dns. Thanks and sorry for my english

**Comment by Ysurac** [comment]
Maybe by bypassing ASN.

**Comment by sonnyxp2008** [comment]
can you give me a quick tip on how to set it up?

**Comment by Ysurac** [comment]
You need to find AS used by Netflix using peeringdb.com for example and add them in OMR-Bypass ASN section.

**Comment by sonnyxp2008** [comment]
and by doing so, all traffic is diverted regardless of the dns entered? EXCELLENT, I try it, thanks

**Comment by sonnyxp2008** [comment]
ho provato tutto ma se non inserisco i dns non funziona

**Comment by sonnyxp2008** [comment]
i tried everything but if i don't insert the dns it doesn't work
