### ISSUE TITLE
VPS selection

### ISSUE THREAD

**Issue by rifaterdemsahin** [Ysurac/openmptcprouter#1543]
i was using hostworld.uk than switched to OVH but the connection started dropping yesterday
now I consider changing but how do I know it is the ISP, not my VPS code?

Errors i get
![image](https://user-images.githubusercontent.com/5270036/106123874-61be3500-6152-11eb-8756-cb1934860149.png)

![image](https://user-images.githubusercontent.com/5270036/106122440-9f21c300-6150-11eb-841e-701d1cbdb20a.png)

![image](https://user-images.githubusercontent.com/5270036/106122296-76013280-6150-11eb-8240-03d079d89598.png)

@Ysurac thanks for the anonymous IP feature mate...you are a life saver.

**Comment by rifaterdemsahin** [comment]
my alternatives
https://www.fasthosts.co.uk/virtual-private-servers

**Comment by kams19** [comment]
i am using fasthosts without any issues so far, its been more than 2 months. I have the cheapest VPS £1.20 per month with 512M RAM 1vCPU, it has unlimited data just that the bandwidth is 400M max

**Comment by rifaterdemsahin** [comment]
@kams19 thanks for the response. I need a Gigabit connection

**Comment by rifaterdemsahin** [comment]
why do started to get these error more and more ?
![image](https://user-images.githubusercontent.com/5270036/106206435-fc9d2a80-61b7-11eb-94a7-4038610a5e8d.png)

**Comment by Ysurac** [comment]
As always, read log in State->System log. This will tell you if a problem is detected and what is the problem.

**Comment by rifaterdemsahin** [comment]
makes sense
![image](https://user-images.githubusercontent.com/5270036/106291874-12f0c800-6244-11eb-9b21-a2aa09462d23.png)

**Comment by rifaterdemsahin** [comment]
I would love emoji support here (: maybe the only aspie in this thread is me

**Comment by Ysurac** [comment]
Many "Connection reset by peer"...
You can try another TCP Congestion Control in Network->MPTCP
