### ISSUE TITLE
upgrading from webui

### ISSUE THREAD

**Issue by rifaterdemsahin** [Ysurac/openmptcprouter#1544]
i picked the top x64 and flashing.
is that the way to go
![image](https://user-images.githubusercontent.com/5270036/106215480-fd8a8800-61c8-11eb-8ba4-f3d6aba381fb.png)
I got this
https://protectli.com/vault-6-port/

**Comment by rifaterdemsahin** [comment]
![image](https://user-images.githubusercontent.com/5270036/106215558-2579eb80-61c9-11eb-86cb-936302827000.png)
![image](https://user-images.githubusercontent.com/5270036/106215593-34f93480-61c9-11eb-8ffb-b6fc64febc99.png)

![Uploading image.png…]()

**Comment by rifaterdemsahin** [comment]
x86-64 (64-bits)
ext4 image (EFI): openmptcprouter-v0.57.3-r0+15225-bfc433efd4-x86-64-generic-ext4-combined-efi.img.gz (2021/01/05 - 69.40Mo - sha256sum)

**Comment by Ysurac** [comment]
As the platform doesn't seems to support EFI, it's not the good image.

**Comment by rifaterdemsahin** [comment]
it worked though and I am getting no issues today
which image is the better image?

![image](https://user-images.githubusercontent.com/5270036/106274458-37d94100-622c-11eb-929a-8c7da6bd76a5.png)
monitoring daily ˆˆˆ

**Suggestions**
1.it would be great if we have a daily VPS and OMR fail count in a page
2.If there is another dhcp the OMR should mention it in the console...it is hard to find other DHCPs in the network

**Comment by spacedream** [comment]
> Labels **question**

But what is your question was exactly? i not understand.

> it worked though and I am getting no issues today

if your question is not actual anymore please close your ticket, ty.
