### ISSUE TITLE
Can all the default server ports be changed before installation?

### ISSUE THREAD

**Issue by xdaviddx** [Ysurac/openmptcprouter#1548]
If I search and replace all ports in the server install script with different ports, will I be able to change all the default ports?  

The reason I'm asking is because I'm thinking about running multiple OMR server instances in docker containers.  To do this, I need the services to run on different ports so they don't conflict.  

The other option is to use bridge mode for docker and do NAT to map the ports to new port numbers.  I'm not sure if this will affect performance, so that's why I'm considering change the default ports inside the containers.

In either solution I would need to change for the OMR client to use.

Thanks.

**Comment by Ysurac** [comment]
It's not possible for now.
