### ISSUE TITLE
Very slow connection through mptcp with a specific interface/external connection

### ISSUE THREAD

**Issue by dur3x** [Ysurac/openmptcprouter#155]
In the past I had 3 ADSL box by the same internet provider but more recently I replaced one of my adsl box to another one (WAN2) which is by another provider (to have prodiver redundancy and also because the bandwith was better).
With the 3 old adsl box by the same ISP I got good result by using the wan1+wan2+wan3 but since I replaced/got a new box (wan2) it's just not usable. 
So currently I'm running with wan1+wan3 or just wan2.
I'm open to any suggestion/test :) I'm asking mylself if it's nothing linked to MTU because if I compare the different interface the wan2 has the bigger MTU:

wan1: MTU:1466
wan2: MTU:1500
wan3: MTU:1491

## Expected Behavior
Speed by using MPTCP with WAN1 + WAN2 + WAN3 > 100 kb/s

## Actual Behavior
WAN1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  1  100M    1 1777k    0     0  90994      0  0:19:12  0:00:20  0:18:52 70777

WAN2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 42  100M   42 42.4M    0     0  2175k      0  0:00:47  0:00:20  0:00:27 2092k

WAN3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 17  100M   17 17.6M    0     0   901k      0  0:01:53  0:00:20  0:01:33 1012k

WAN1+WAN2+WAN3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 10  100M   10 10.0M    0     0   100k      0  0:16:55  0:01:41  0:15:14 89467

WAN1+WAN3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 14  100M   14 14.1M    0     0   717k      0  0:02:22  0:00:20  0:02:02  815k

WAN2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 37  100M   37 37.2M    0     0  1826k      0  0:00:56  0:00:20  0:00:36 1520k

## Specifications

  - OpenMPTCProuter version: (Last is not a version) v0.34.1
  - OpenMPTCProuter VPS version: (Last is not a version) VPS 0.46
  - OpenMPTCProuter platform: (RPI2/RPI3/x86/x86_64) x86_64

**Comment by Ysurac** [comment]
What do you have in OpenMPTCProuter status page ?

**Comment by dur3x** [comment]
<img width="1161" alt="screen shot 2018-09-07 at 17 54 38" src="https://user-images.githubusercontent.com/5813331/45229801-3a3b4900-b2c7-11e8-82bf-f5d924176bb1.png">
If needed I can try to give you a full access to my openmptcprouter box :)

**Comment by dur3x** [comment]
<img width="1161" alt="screen shot 2018-09-07 at 17 54 38" src="https://user-images.githubusercontent.com/5813331/45230164-57244c00-b2c8-11e8-9b18-ae69f7bbd911.png">
If needed I can try to give you access to my openmptcprouter box :)

**Comment by Ysurac** [comment]
There is a small checkbox under status page to anonymize all :)
I don't see problems here... I think you put wan2 as backup because you have the problem, and it's "on" else ?
What is the result if you set, via SSH ```ifconfig wan2 mtu 1492``` ?

**Comment by dur3x** [comment]
It looks not linked to shadosocks or VPN because when I disabled everything on openmptcprouter and just use the "mptcp" I got the same problem.
For example with 

```
root@OpenMPTCProuter:~# curl http://multipath-tcp.org/snapshots/mptcp_2016_04_18.tar.gz > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  2  120M    2 3531k    0     0   146k      0  0:14:02  0:00:24  0:13:38 75557
```

So it's something else (or directly the mptcp itself?). 
Perhaps I should try to use something else than the openwrt image.

**Comment by Ysurac** [comment]
What is the result of ```omr-test-speed wan2``` ? (this run a test speed, but without using ShadowSocks and Glorytun)
You can also try to disable MPTCP in **Network**->**MPTCP**.

Do you have something in log ?

**Comment by dur3x** [comment]
>What is the result of omr-test-speed wan2 ? (this run a test speed, but without using ShadowSocks and Glorytun)
```
1: 192.168.20.1 
2: 192.168.0.1  [PARTIAL] +PartialTCP IP::TotalLength IP::TTL IP::CheckSum 
3: * 
4: 212.76.224.97  [PARTIAL] +PartialTCP IP::TotalLength IP::TTL IP::CheckSum 
5: 84.199.206.13 TCP::DataOffset TCP::WindowsSize TCP::CheckSum IP::TotalLength IP::TTL IP::CheckSum +TCPOptionMaxSegSize 
6: 213.224.254.185 TCP::DataOffset TCP::WindowsSize TCP::CheckSum IP::TotalLength IP::TTL IP::CheckSum +TCPOptionMaxSegSize 
7: 213.224.250.107  [PARTIAL] +PartialTCP IP::TotalLength IP::TTL IP::CheckSum 
8: 54.36.50.5 TCP::DataOffset TCP::WindowsSize TCP::CheckSum IP::TotalLength IP::TTL IP::CheckSum +TCPOptionMaxSegSize 
9: 91.121.131.27 TCP::DataOffset TCP::WindowsSize TCP::CheckSum IP::TotalLength IP::TTL IP::CheckSum +TCPOptionMaxSegSize 
10: * 
11: 178.33.103.224  [PARTIAL] +PartialTCP IP::TotalLength IP::TTL IP::CheckSum 
12: <vps_ip> TCP::SrcPort TCP::DstPort TCP::SeqNumber TCP::AckNumber TCP::DataOffset TCP::Flags TCP::WindowsSize TCP::CheckSum IP::TotalLength IP::Identification IP::TTL IP::CheckSum IP::SourceIP IP::DestinationIP +TCPOptionMaxSegSize TCPOptionMPTCPCapable::Sender's Key 

Result:
< Ethernet (14 bytes) :: DestinationMAC = 9a:26:36:e7:09:f8 , SourceMAC = 60:e3:27:be:91:7a , Type = 0x800 , >
< IP (20 bytes) :: Version = 4 , HeaderLength = 5 , DiffServicesCP = 0 , ExpCongestionNot = 0 , TotalLength = 56 , Identification = 0x0 , Flags = 2 , FragmentOffset = 0 , TTL = 53 , Protocol = 0x6 , CheckSum = 0xe52b , SourceIP = <vps_ip> , DestinationIP = 192.168.20.100 , >
< TCP (20 bytes) :: SrcPort = 65101 , DstPort = 37847 , SeqNumber = 3798694843 , AckNumber = 1454006752 , DataOffset = 9 , Reserved = 0 , Flags = ( SYN ACK ) , WindowsSize = 30260 , CheckSum = 0x4192 , UrgPointer = 0 , >
< TCPOptionMaxSegSize (4 bytes) :: Kind = 2 , Length = 4 , MaxSegSize = 1460 , >
< TCPOptionMPTCPCapable (12 bytes) :: Kind = 30 , Length = 12 , Subtype = 0 , Version = 0 , Checksum = 1 (Checksum Enabled) , Flags = 0 , Crypto = 1 (HMAC-SHA1) , Sender's Key = Sender's Key = 12691078937315602425 , >
```

Unfortunately nothing special in the logs.
