### ISSUE TITLE
Restore Debian 10 and uninstall openmptcprouter

### ISSUE THREAD

**Issue by dettofatto** [Ysurac/openmptcprouter#1558]
In my case I would restore debian 10 and uninstall openmptcprouter.
My vps hosting ask me money for restoring system.
Can I find any script or link, for make this possible?
Thank you, and I'm sorry for my stupid question.

**Comment by Ysurac** [comment]
Not possible.
As the script install shorewall, shadowsocks, openvpn,... It's not really possible to uninstall OMR. But services can be disabled using systemctl.

**Comment by dettofatto** [comment]
Ok, Thank you.
I love your work.
Thank you again.
