### ISSUE TITLE
2 vdsl + 1 4g problem

### ISSUE THREAD

**Issue by sonnyxp2008** [Ysurac/openmptcprouter#1559]
## Expected Behavior
insert a third WAN connection on omr

## Current Behavior
the 4g connection drops and does not recover anymore. if I use it on a normal pc or router it works fine

## Specifications

  - OpenMPTCProuter version: <0.57.3>
  - OpenMPTCProuter VPS version: <0.1024.5.4.86>
  - OpenMPTCProuter platform: <x86_64>

![omr](https://user-images.githubusercontent.com/78047559/106480595-d921fa80-64ab-11eb-9863-4583e79f5543.jpg)

**Comment by Ysurac** [comment]
Please use the template.

**Comment by sonnyxp2008** [comment]
Ysurac did you mean this model? Excuse me but I'm new around here

**Comment by Ysurac** [comment]
Yes.
You can check on State->System log if there is any info.
How is connected the 4g, to a own port or using macvlan or vlan ?

**Comment by sonnyxp2008** [comment]
these are the mistakes. I am currently using it with an upstream router. I have also tried everything to change the server where to send the pings.
Sun Jan 31 19:46:56 2021 user.notice post-tracking-post-tracking: 4g (eth2) switched off because ping from 192.168.0.102 error (1.1.1.1,8.8.4.4,1.1.1.1)
Sun Jan 31 19:46:56 2021 user.notice post-tracking-post-tracking: Delete default route via 192.168.0.1 dev eth2
Sun Jan 31 19:47:46 2021 daemon.err /usr/bin/ss-redir[13605]: server recv: Operation timed out
Sun Jan 31 19:47:56 2021 daemon.err /usr/bin/ss-redir[13604]: server recv: Operation timed out
Sun Jan 31 19:48:42 2021 daemon.err /usr/bin/ss-redir[13607]: send: Operation timed out
Sun Jan 31 19:48:43 2021 daemon.err /usr/bin/ss-redir[13604]: server recv: Host is unreachable
Sun Jan 31 19:50:50 2021 daemon.err /usr/bin/ss-redir[13604]: remote recv: Connection reset by peer
Sun Jan 31 19:51:36 2021 daemon.err /usr/bin/ss-redir[13604]: server recv: Operation timed out
Sun Jan 31 19:52:35 2021 daemon.err /usr/bin/ss-redir[13606]: server recv: Operation timed out
Sun Jan 31 19:53:06 2021 daemon.err /usr/bin/ss-redir[13604]: server recv: Host is unreachable
Sun Jan 31 19:54:47 2021 daemon.err /usr/bin/ss-redir[13605]: server recv: Host is unreachable
Sun Jan 31 19:54:58 2021 daemon.err /usr/bin/ss-redir[13606]: server recv: Host is unreachable
Sun Jan 31 19:55:00 2021 daemon.err /usr/bin/ss-redir[13606]: send: Connection reset by peer
Sun Jan 31 19:55:00 2021 daemon.err /usr/bin/ss-redir[13608]: send: Connection reset by peer

**Comment by Ysurac** [comment]
Can you do a ```ping -I 192.168.0.102 192.168.0.1``` via SSH or Services->Terminal on the router ?
If not, check 4G router IP.

**Comment by sonnyxp2008** [comment]
the ping is there, in truth as soon as I restart the antenna the connection appears up, after a few minutes it goes down. I am using a Mikrotik 4g antenna. Another fact is that I put a router upstream to see if I can surf safely. The fact is that as soon as I insert the cable to the assigned port, the connection is unstable. Only you tube opens and every now and then some speed tests start. If I unplug the cable from OMR everything works normally. I asked Mikrotik for assistance and they replied that there is no conflict. But I believe that there is something wrong or that does not support something.

**Comment by Ysurac** [comment]
Do you have something with ```ping -I 192.168.0.102 8.8.8.8``` ?
What are the references of the material ?

**Comment by sonnyxp2008** [comment]
then OMR ping side on 0.1 is ok 8.8.8.8 after 2-3 minutes it goes ko.
On a pc directly on a router that manages pc and OMR we have unstable connection if I connect the cable to OMR, unstable connection to the PC but from the pc I get the ping on 8.8.8.8 It is difficult for me to explain it to you because such a thing has never happened to me. The 0.1 router I put it just to see if the connection went ko. i could delete it but i have the same problem. Could it be an MPTCP problem between OMR and Mikrotik? believe me now I've gone crazy

**Comment by Ysurac** [comment]
If there is a firewall on miktotik or something that block MPTCP yes. There is an option that block MPTCP on some Cisco.

**Comment by sonnyxp2008** [comment]
I have disabled the firewall I have modified the nat but the results are bad. can't disable MPTCP on a single wan? Or any other solution is welcome

**Comment by Ysurac** [comment]
In Network->MPTCP you can disable MPTCP on a wan. You can try and then test ping 8.8.8.8, if same issue than it's not related to MPTCP.

**Comment by sonnyxp2008** [comment]
i think i don't understand, if i disable MPTCP on a single wan it obviously falls, i send you a picture of my current configuration
![Immagine](https://user-images.githubusercontent.com/78047559/106503527-0d0a1980-64c6-11eb-948a-f3be5e728879.png)

**Comment by Ysurac** [comment]
You can try to disable Multipath TCP on 4G interface. Then you will see if the interface can be used directly via the ping -I previous command or if the result is the same.

**Comment by sonnyxp2008** [comment]
So if I disable MPTCP on the wan we don't have any ping. Maybe I found the solution after a week and the problem lies in the NAT. As soon as I'm done freaking out I will write my configuration here so that someone can be of help as these MIkrotik antennas have become more commercial

**Comment by Ysurac** [comment]
You can also paste here the configuration (without keys/vps ip), available in System->OpenMPTCProuter, "show all settings" tab, so I can check if there is no error somewhere.

**Comment by sonnyxp2008** [comment]
nat refers to the mikrotik routerboard. Now due to an error I can no longer enter the Mikrotik interface. I should reset everything but it's cold now and I don't want to go up and reset the antenna. Tomorrow I will reset it and configure the NAT. I keep you updated
