### ISSUE TITLE
Error for cancel config in error on openmptcp 0.34.4

### ISSUE THREAD

**Issue by mykelinho** [Ysurac/openmptcprouter#157]
Expected Behavior
if error on configuration router openmptcprouter, impossible to cancel
impossible d'annuler les paramètres erronné après décompte des 30 secondes si erreur de config sur le routeur

Steps to Reproduce the Problem
connexion wifi to lan on rpi 3+

![image](https://user-images.githubusercontent.com/42909444/45186525-111aaa00-b22e-11e8-9618-9f43fd0baa03.png)

Specifications
OpenMPTCProuter version: openmptcprouter v0.34.4 r7298-f7413579c0 / LuCI Master (git-18.248.76017-8951f5f)
OpenMPTCProuter VPS version: OVH Debian 9
OpenMPTCProuter platform: RPI-3+

**Comment by mykelinho** [comment]
on 0.33 no problem, if problem configuration, it's possible to return on old config

**Comment by Ysurac** [comment]
No change about that in 0.34.x since 0.33.
Not able to reproduce this issue.
