### ISSUE TITLE
error -99

### ISSUE THREAD

**Issue by sonnyxp2008** [Ysurac/openmptcprouter#1573]
hi everyone, you know give me some indication about this error?

Mon Feb  8 14:32:46 2021 kern.err kernel: [579264.238842] __mptcp_init4_subsockets: token 0xfa8da51d bind() to 192.168.43.81 index 12 failed, error -99
Mon Feb  8 14:32:46 2021 kern.err kernel: [579264.486795] __mptcp_init4_subsockets: token 0xb1997929 bind() to 192.168.43.81 index 12 failed, error -99

**Comment by Ysurac** [comment]
Not possible to create subflow binded on 192.168.43.81 ip.

**Comment by sonnyxp2008** [comment]
excuse my ignorance but what is this flow?

**Comment by Ysurac** [comment]
With MPTCP, each network interface with an IP is called a subflow. It's a connection (that can have a different internet path) identified by source and destination IP addresses.

**Comment by sonnyxp2008** [comment]
so could this be the cause that the connection is not working? it gives me ping reply error after 1 second. I also tried other devices and mobiles. The problem remains

**Comment by Ysurac** [comment]
Yes it's possible.

**Comment by sonnyxp2008** [comment]
and how can I solve the problem? depends on what?

**Comment by Ysurac** [comment]
The problem is not this error, but the connection configuration.

**Comment by sonnyxp2008** [comment]
I also tried via mobile, the connection goes for about 30 seconds and then drops. I tried all the configurations but nothing to do
are you referring to the configuration of the omr?

**Comment by Ysurac** [comment]
yes, but open a new issue as it's not related to this kernel error, and I will need OMR versions and the result of ```uci show network``` via SSH or Services->Terminal.

**Comment by sonnyxp2008** [comment]
ok merci
