### ISSUE TITLE
please help not getting bonded speeds

### ISSUE THREAD

**Issue by Nickmcl024** [Ysurac/openmptcprouter#1575]

**Comment by Ysurac** [comment]
Please use the template when opening an issue.

**Comment by Nickmcl024** [comment]
what template do i use? 

super new to this and just wana test out the software for bonding

**Comment by Ysurac** [comment]
The template is the text you removed when you opened the issue that ask versions, platform,...
You can't expect to aggregate same speed on a RPI2B and a new x86_64 server, it's why I need some infos asked in template.
And as it's a speed problem, I would need some speed info ;)
To test aggregate speed you can use ```omr-test-speed``` on the router via SSH or Services->Terminal. To test speed for each wan ```omr-test-speed wan1``` (for the speed of wan1, check interfaces name using ```ip a```). You can stop speed after at least 2 minutes using "Ctrl+C".

**Comment by Nickmcl024** [comment]
## Expected Behavior
not getting bonded speeds 


## Current Behavior
wan1 200dl 100up
wan2 200dl 200up 

only getting max 200dl and 200up

## Specifications

  - OpenMPTCProuter version Kernel Version：5.4.83 
                                               
  - OpenMPTCProuter VPS version: 5.4.86-mptcp 0.1024
  - OpenMPTCProuter platform: <Model：Raspberry Pi 4 Model B Rev 1.2

-

**Comment by Nickmcl024** [comment]
i tested all it all in termail 

speeds are the same 
wan1 20MB
wan2 20MB

**Comment by Ysurac** [comment]
I still need ```omr-test-speed``` results.
But as it's a RPI4, doesn't expect too much speed. Check RPI load average and VPS load average.
You can also try to disable shadowsocks encryption in System->OpenMPTCProuter, "advanced settings" checkbox, to test if CPU limit speed.

**Comment by Adorfer** [comment]
>     * OpenMPTCProuter platform: <Model：Raspberry Pi 4 Model B Rev 1.2

200/200 is absolutly perfect for an RPI4. Sometimes 150MBit/s is the limit. 
You may disable SQM, but then the QoS will deteriorate.

**Comment by Nickmcl024** [comment]
Best server is http://speedtest.tele2.net/1000GB.zip, running test:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 1000G    0  996M    0     0  16.3M      0 17:23:47  0:01:00 17:22:47 17.0M
  0 1000G    0 1014M    0     0  16.3M      0 17:21:51  0:01:01 17:20:50 16.7M

  0 1000G    0 1033M    0     0  16.4M      0 17:19:35  0:01:02 17:18:33 16.8M

**Comment by Adorfer** [comment]
for faster speeds look for a processor with AES-NI. And network cards on exclusive pcie lanes, not a sigle shared one (for all IO) like on the rpi.

**Comment by Nickmcl024** [comment]
Hostname | OpenMPTCProuter
-- | --
Model | NF541 NF541
Architecture | Intel(R) Celeron(R) CPU J1900 @ 1.99GHz
Firmware Version | openmptcprouter v0.57.3 r0+15225-bfc433efd4 / LuCI Master git-20.339.75073-e54708a
Kernel Version | 5.4.83

did fresh install on a different system all stock settings just sent up the wans and vps 

speeds are 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 1000G    0  605M    0     0  14.1M      0 20:07:31  0:00:42 20:06:49 18.1M
curl: (18) transfer closed with 1073106473049 bytes remaining to read

**Comment by Nickmcl024** [comment]
are these setting corrects
MPTCP
Networks MPTCP settings. Visit http://multipath-tcp.org/pmwiki.php/Users/ConfigureMPTCP for help.
GLOBALS
Multipath TCP

enable
Multipath TCP checksum

disable
Multipath Debug

disable
Multipath TCP path-manager

default
Multipath TCP scheduler

default
Multipath TCP SYN retries
2
Congestion Control

bbr2

Default is bbr
Fullmesh subflows for each pair of IP addresses
1
Re-create fullmesh subflows after a timeout

enable
ndiffports subflows number
1
Interfaces Settings
LOOPBACK
Multipath TCP

disabled

One interface must be set as master
LAN
Multipath TCP

disabled

One interface must be set as master
WAN1
Multipath TCP

master

One interface must be set as master
WAN2
Multipath TCP

enabled

One interface must be set as master
OMRVPN
Multipath TCP

disabled

One interface must be set as master
OMR6IN4
Multipath TCP

disabled

One interface must be set as master

**Comment by Ysurac** [comment]
Wait about 2 minutes for a test.
Check VPS internet speed and load average on both.

You seems to have disabled aggregation in MPTCP settings. Multipath TCP path-manager should be fullmesh.

**Comment by Nickmcl024** [comment]
https://www.speedtest.net/result/10899616961.png

thats was it :) i never knew it had to be set to Multipath TCP path-manager should be fullmesh.

speeds are much better thanks 

how to i check vps loads and cpu . as well and loads on the pi4 

i did s speed test on the vps and it has 2000mbs so that side should be fine

**Comment by Ysurac** [comment]
fullmesh is the default setting.
To get load average, you can use ```cat /proc/loadavg``` via SSH, but it's also available on status page.

**Comment by Nickmcl024** [comment]
i promise i just did a fresh install on a pc and it was not on fullmesh  will now reset up the pi4 and test it with fullmesh , 
what is the best vpn setting to use for UDP streaming .

**Comment by Nickmcl024** [comment]
Hey so sometimes on the raspberry pi 4 the file system says read only and one can't change anything, I have to flash the SD card agian and set it up all again is this a problem on the pi

**Comment by Ysurac** [comment]
You can enable "Check filesystems before mount" in System->Mount Points
But best way is to use System->Shutdown to shutdown the RPI instead of removing power. RPI is very sensitive to power cut.

**Comment by Bumpalert** [comment]
> i promise i just did a fresh install on a pc and it was not on fullmesh will now reset up the pi4 and test it with fullmesh ,
> what is the best vpn setting to use for UDP streaming .
@Nickmcl024 nice to know if you have some observations. I am also testing youtu.be streaming using 4g dongles

**Comment by ithotline** [comment]
Is it possible to test omr-test-speed with smaller package from tele2.net? i want to test a 4g setup i'm working on but 1000GB would kill the 40GB dataplan i'm on.

Maybe 5MB test or something?

**Comment by Ysurac** [comment]
Ctrl+C to stop test.
