### ISSUE TITLE
No Keys after install

### ISSUE THREAD

**Issue by henry18hn** [Ysurac/openmptcprouter#1577]
## Expected Behavior =  Key issued after install to Vultr  & before reboot.

  = I should be able to receive key after install on Debian 10 vps

## Current Behavior
<I get error message > <No working domain detected not able to generate certificate for V2ray. You can set VPS_DOMAIN to a working domain if you want a certificate.>

## Specifications

  - OpenMPTCProuter version: <5.4.86>
  - OpenMPTCProuter VPS version: <0.1024-->
  - OpenMPTCProuter platform: <Debian 10 ,Vultr 1vCore 1024MB 25GB SSD /x86_64) -->

**Comment by Ysurac** [comment]
And what you have at the end of VPS script ?

**Comment by henry18hn** [comment]
<No working domain detected, not able to generate certificate for v2ray. You can set VPS_DOMAIN to a working domain if you want a certificate.>
   Thx, I must have accidentally deleted this part.

**Comment by henry18hn** [comment]
Should I post a pic of my screen? I'm very new to all this.

**Comment by Ysurac** [comment]
This is the latest message if it's not first time the script is launched.
Keys are in ```/root/openmptcprouter_config.txt```

**Comment by henry18hn** [comment]
Thanks, I got it going now.
