### ISSUE TITLE
USB connection sharing using an Android smartphone.

### ISSUE THREAD

**Issue by NicksQ69** [Ysurac/openmptcprouter#1584]
## Expected Behavior
My goal is to use my smartphone as a 4G modem and thus share the internet connection within the network to take advantage of aggregation.
I connected my smartphone to my Raspberry Pi 4 using a USB cable. This one is detected.
![Capture d’écran 2021-02-13 223424](https://user-images.githubusercontent.com/47458849/107862220-aa146d00-6e4b-11eb-89af-3e764833a07f.png)

Next, i go to: System > OpenMPTCProuter > Configuration Wizard.
I configure the new "usb0" interface.
![Capture d’écran 2021-02-13 223653](https://user-images.githubusercontent.com/47458849/107862284-037c9c00-6e4c-11eb-8614-bd30a51c07ca.png)

After this step, normally my aggregation system should benefit from the 4G connection in addition.

## Current Behavior
The aggregation system with the additional 4G does not work.
![Capture d’écran 2021-02-13 224246](https://user-images.githubusercontent.com/47458849/107862557-a84ba900-6e4d-11eb-93f3-c3552b81ce64.png)

## Specifications

  - OpenMPTCProuter version: v0.57.3
  - OpenMPTCProuter VPS version: 0.1024
  - OpenMPTCProuter platform: Raspberry PI 4B (64-bits)

**Comment by Ysurac** [comment]
How did you check that aggregation doesn't work ?

**Comment by NicksQ69** [comment]
EN : I performed a throughput test using the speedtest.net website. With the aggregation of my 2 ADSL WANs, I get a downstream rate of about 20 mbps. When I test my internet speed with my smartphone alone on the 4G, I get a downlink speed of 30 mbps. After setting up with my two ADSL lines and my smartphone (4G), I have a downstream rate of about 20 mbps as before for my two ADSL lines.

FR : J'ai réalisé un test de débit à l'aide du site internet speedtest.net. Avec l'agrégation de mes 2 WAN ADSL, j'obtiens un débit descendant de 20 mbps environ. Lorsque je teste mon débit internet avec mon smartphone seul sur la 4G, j'ai un débit descendant de 30 mbps. Après la mise en place avec mes deux lignes ADSL et celle de mon smartphone (4G), j'ai un débit descendant d'environ 20 mbps comme précédemment pour mes deux lignes ADSL.

**Comment by Ysurac** [comment]
Use ```omr-test-speed``` to test aggregated speed, and ```omr-test-speed wan1``` (for each interfaces), via SSH or Services->Terminal. Stop the speed test after at least 2 minutes using "Ctrl+C".

**Comment by NicksQ69** [comment]
I had a very strange reaction.
Here are the screenshots before connecting my smartphone to the usb port as a modem :
![Capture d’écran 2021-02-14 184702](https://user-images.githubusercontent.com/47458849/107884450-7ee65800-6ef5-11eb-91ad-10efc21555af.png)

![Capture d’écran 2021-02-14 184755](https://user-images.githubusercontent.com/47458849/107884463-8ad21a00-6ef5-11eb-8236-2d0b3ac17435.png)

![Capture d’écran 2021-02-14 184838](https://user-images.githubusercontent.com/47458849/107884479-93c2eb80-6ef5-11eb-934f-e243ca1d3179.png)

And below are the screenshots when I plugged my smartphone on the usb port as a modem :
![Capture d’écran 2021-02-14 184009](https://user-images.githubusercontent.com/47458849/107884501-b05f2380-6ef5-11eb-8de9-63ead8f9dbf8.png)

![Capture d’écran 2021-02-14 184515](https://user-images.githubusercontent.com/47458849/107884509-b8b75e80-6ef5-11eb-8bea-0fa94b398fd0.png)

![Capture d’écran 2021-02-14 184529](https://user-images.githubusercontent.com/47458849/107884515-bf45d600-6ef5-11eb-868c-d5ede62ae51e.png)

![Capture d’écran 2021-02-14 184323](https://user-images.githubusercontent.com/47458849/107884519-c53bb700-6ef5-11eb-9cf9-82cec8a4d5a0.png)

**Comment by Ysurac** [comment]
You need to run test at least 2 minutes.
The syntax error is a know issue on some site that happen when a website answer with multiple IPs, it's solved in develop branch so this will be solved in next release.
For the last test, your connection seems to block ping. You should use another way to test if interface is up/down for this connection in omr-tracker. You can also check State->System log log about omr-tracker, it may say that connection is detected as down.

**Comment by NicksQ69** [comment]
After adding it in OMR-Tracker, the result below (I did not understand everything) :
![Capture d’écran 2021-02-14 194349](https://user-images.githubusercontent.com/47458849/107885921-392d8d80-6efd-11eb-81a8-b0e5f1b0511c.png)

**Comment by Ysurac** [comment]
It still use ping method in omr-tracker.

**Comment by NicksQ69** [comment]
Yes that's right, I just corrected:
![image](https://user-images.githubusercontent.com/47458849/107886138-472fde00-6efe-11eb-997e-bb8dacb8c493.png)

**Comment by Ysurac** [comment]
httping doesn't seems to be better here... strange... you can disable omr-tracker for this connection only.

**Comment by NicksQ69** [comment]
Anyway, no improvement ... do you have an idea how to solve this problem?

**Comment by Ysurac** [comment]
You disabled omr-tracker on the connection only ? A least this should not switch off this connection.

**Comment by NicksQ69** [comment]
Yes I removed the usb0 interface on OMR-Tracker.
I'll try to do some more tests, but I'm swimming in the unknown.

**Comment by Ysurac** [comment]
removed ? It must be added and set to none.

**Comment by NicksQ69** [comment]
Yes it's true, I did it by reflex.

**Comment by NicksQ69** [comment]
I enabled the MPTCP over VPN option on the usb0 interface on the configuration wizard. And it seems to work now. I can't find the real download speed that my smartphone offers when I test the speed alone, but I gained like 6 mbps when downloading ... In my opinion the problem must come from my mobile provider.
![image](https://user-images.githubusercontent.com/47458849/107888125-05f1fb00-6f0b-11eb-858a-8a0e01d39e5d.png)

![Capture d’écran 2021-02-14 212509](https://user-images.githubusercontent.com/47458849/107888265-79940800-6f0b-11eb-8b28-39eacfe9b883.png)

**Comment by Ysurac** [comment]
It's possible that it blovk MPTCP, but this seems strange.
Who is the provider ?

**Comment by NicksQ69** [comment]
The provider is Bouygues Telecom.

**Comment by Ysurac** [comment]
There is no know limit on Bouygues Telecom.
What is the router/dongle used ? Does it have any internal firewall ?

**Comment by NicksQ69** [comment]
I tested on 3 other smartphones (based on Android) as a different brand modem, but we all have the same operator. And always the same problem.

**Comment by Ysurac** [comment]
Maybe blocked by IPv6 APN ? Try to force APN mmsbouygtel.com to IPv4 only on your phone.
