### ISSUE TITLE
Status page not displaying wan status if configured as DHCP client

### ISSUE THREAD

**Issue by rstanislav** [Ysurac/openmptcprouter#159]
Trunk version, in status page if wan interfaces configured as dhcp client (4g lte modems in hilink mode (cdc-ether devices), on status page it shows red status on wan interfaces with message "no gateway defined"

**Comment by Ysurac** [comment]
No support on trunk version...

An I don't see issue here. A gateway must be defined or retrieved.

**Comment by rstanislav** [comment]
Sorry for false info, this happened because i was unchecking option "Use default gateway" on dhcp enabled interfaces because i was thinking that it will break omr tracker logic, now i checked and its not affecting omr tracker logic and status page now displays status correctly.
