### ISSUE TITLE
DHCP Apipa IP / Router not reachable

### ISSUE THREAD

**Issue by iDustbin** [Ysurac/openmptcprouter#1590]
## Expected Behavior

Hi, i want to use an Banana PI R2, i flashed an SD Card, booted this Device.
I disabled WIfi on my PC and connected my PC over Ethernet to this Router.
Router starts up, blinks perm. Red.

My PC is defined as DHCP Client, unfortunately im receiving an APIPA IP ( 169.xxx.xxx.xxx ) also when im defining static IPs, the Router is not reachable ? 
Any Idea, any hint ? 

Best regards and thanks in advance

## Specifications

  - OpenMPTCProuter version: 
  - OpenMPTCProuter platform:

**Comment by Ysurac** [comment]
Use a static IP in 192.168.100.x network and check if you can ping the router. Make also sure you connect network on port labelled as "WAN".

**Comment by iDustbin** [comment]
👍 thank you
