### ISSUE TITLE
Managed DNSMasq / TFTPBoot

### ISSUE THREAD

**Issue by iDustbin** [Ysurac/openmptcprouter#1593]
Do you see any way to disable DNSMasq or Relay DNS/TFTP Requests in your Software ? 
Best regards and thanks in advance
Dustbin

**Comment by Ysurac** [comment]
In Network->DHCP&DNS, "DNS forwardings", you can transmit DNS queries to any DNS server.

**Comment by iDustbin** [comment]
> In Network->DHCP&DNS, "DNS forwardings", you can transmit DNS queries to any DNS server.

sry my fault: i meant dhcp requests.

thanks

**Comment by Adorfer** [comment]
i really do not get it. 
Please use the template to describe a) what the scenario is b) what the expected/wanted behaviour is and c) what the current behaviour is.
(For me it sounds like "i can not decide which of the different methods i should describe. at the moment i now at least 5 different methods how to achieve what you ask for. But probably one one of them is what you really need)
