### ISSUE TITLE
Hugh size v2rayError.log consume all disk space on VPS

### ISSUE THREAD

**Issue by Kalimeiro** [Ysurac/openmptcprouter#1596]
OMR 0.57.3 - RPI 4B
OMR VPS 0.1024

When i use V2ray, i see file in /tmp/v2rayError.log consume all disk space :

18:36:43 root@openmptcp-xxxxxxxx:/tmp$ df -h
Sys. de fichiers Taille Utilisé Dispo Uti% Monté sur
udev               983M       0  983M   0% /dev
tmpfs              200M     21M  179M  11% /run
/dev/vda1          6,9G    6,9G     0 100% /
tmpfs              998M       0  998M   0% /dev/shm
tmpfs              5,0M       0  5,0M   0% /run/lock
tmpfs              998M       0  998M   0% /sys/fs/cgroup
tmpfs              200M       0  200M   0% /run/user/1000

18:43:26 root@openmptcp-xxxxxxxx:/tmp$ tail -n 10 v2rayError.log
2021/02/16 15:53:20 [Info] [434818753] v2ray.com/core/proxy/vless/inbound: firstLen = 99
2021/02/16 15:53:20 [Info] [434818753] v2ray.com/core/proxy/vless/inbound: received request for tcp:82.64.XXX.XXX:445
2021/02/16 15:53:20 [Info] [434818753] v2ray.com/core/app/dispatcher: default route for tcp:82.64.XXX.XXX:445
2021/02/16 15:53:20 [Info] [434818753] v2ray.com/core/proxy/freedom: opening connection to tcp:82.64.XXX.XXX:445
2021/02/16 15:53:20 [Info] [434818753] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:82.64.XXX.XXX:445
2021/02/16 15:53:20 [Info] [810945769] v2ray.com/core/proxy/vless/inbound: firstLen = 99
2021/02/16 15:53:20 [Info] [810945769] v2ray.com/core/proxy/vless/inbound: received request for tcp:82.64.XXX.XXX:445
2021/02/16 15:53:20 [Info] [810945769] v2ray.com/core/app/dispatcher: default route for tcp:82.64.XXX.XXX:445
2021/02/16 15:53:20 [Info] [810945769] v2ray.com/core/proxy/freedom: opening connection to tcp:82.64.XXX.XXX:445
2021/02/16 15:53:20 [Info] [810945769] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:82.64.XXX.XXX:445

**Comment by Ysurac** [comment]
I will make it log less data in next release. For now you can remove the file.

**Comment by Kalimeiro** [comment]
Thanks.
