### ISSUE TITLE
How to setup with EasyTether (which does not allow ping?)

### ISSUE THREAD

**Issue by Fffrank** [Ysurac/openmptcprouter#1600]
Looking to use EasyTether as a usb connection but it does not allow ping.... Is it possible to set up and still detect if the connection is up/down?

**Comment by vinceducat** [comment]
no need of any apps on android..

search in the issue for Thethering....

**Comment by vinceducat** [comment]
https://github.com/Ysurac/openmptcprouter/issues?q=is%3Aissue+tethering

**Comment by vinceducat** [comment]
https://github.com/Ysurac/openmptcprouter/issues/1584

**Comment by Fffrank** [comment]
EasyTether prevents your provider from detecting tethered data.....

**Comment by Ysurac** [comment]
You can try DNS or HTTP mode in omr-tracker.

**Comment by vinceducat** [comment]
@Fffrank 

> EasyTether prevents your provider from detecting tethered data.....

could you explain ? OMR create VPN over the link

**Comment by mrconnerton** [comment]
I too would like to use EasyTether as one of my wan sources. Easytether provides the ability to use 4g lte data as "phone data" and not "hotspot" data that android tethering would do.
