### ISSUE TITLE
create a new server with the key of old server

### ISSUE THREAD

**Issue by MrTheSkream** [Ysurac/openmptcprouter#1601]
Hello,

i have a question,
Can we import the old openmptcprouter key to a new server in order to use the same key all the time ?

Thanks.

**Comment by Ysurac** [comment]
Yes if you modify API key in ```/etc/openmptcprouter-vps-admin/omr-admin-config.json```, but it's not a good security idea ;)

**Comment by MrTheSkream** [comment]
Okey thx
Security is not a problem, it just has to work ^^
