### ISSUE TITLE
 Control of Download and Upload rate

### ISSUE THREAD

**Issue by rnunes77** [Ysurac/openmptcprouter#1602]
## Expected Behavior

I am using 3 4G modems (individually powered) from different operators and all are recognized by the system. However, I realized that during use the balancing occurs in a strange way, honoring only one of the modems and leaving the other two almost unused. I would like to place a limit to see if this way the modems work more together, adding a link, bringing redundancy and load balancing.
## Current Behavior

I need to add links, have redundancy and load balancing
## Specifications

  - OpenMPTCProuter version: 57.3
  - OpenMPTCProuter VPS version: 0.1024
  - OpenMPTCProuter platform: RPI3

**Comment by Ysurac** [comment]
Wan connections are used based on latency and only when needed. It's not load balancing at all but aggregation.
In Network->MPTCP, "MPTCP scheduler" you can choose redundancy or load balancing mode that may give what you want but will be slower and use more data.

**Comment by rnunes77** [comment]
Thanks for listening! I would like to use for video transmission, I usually traffic videos with 6mbps bitrate, in your opinion what would be the best configuration to achieve a stable connection?

**Comment by Ysurac** [comment]
If you use UDP for transmission, then you try others VPN (like Glorytun UDP) in System->OpenMPTCProuter, "advanced settings" checkbox

**Comment by rnunes77** [comment]
![Screen Shot 2021-02-19 at 09 46 00](https://user-images.githubusercontent.com/70973089/108506751-13570e80-7298-11eb-9085-923daf8afd87.png)

Today I tried to change to UDP, but I started having problems with the VPN. I went back to GLORYTUN TCP and while using it I received poor connection information.

**Comment by Bumpalert** [comment]
> 
> 
> If you use UDP for transmission, then you try others VPN (like Glorytun UDP) in System->OpenMPTCProuter, "advanced settings" checkbox

@Ysurac  did you mean to enable "When proxy shadowsocks is used, use it for UDP if VPN down" setting for udp for streaming?

![image](https://user-images.githubusercontent.com/56679716/120526424-d225dd00-c3f6-11eb-9db5-b209ac9d6a8f.png)

**Comment by Ysurac** [comment]
No. I mean what I write. In wizard page, using advanced settings **checkbox**
