### ISSUE TITLE
Gateway down USB m.2 modem 

### ISSUE THREAD

**Issue by techdeisel** [Ysurac/openmptcprouter#1607]
## Expected Behavior
Stable connection and green check mark on each lte modem,
vps stays connected

## Current Behavior
unstable speeds, ping and connection
disconnects momentary lose of connection
modem pass traffic and seem stable an connected but
OMR doesn't seem to think so
and it doesn't seem to like the angry yellow check marks
## Specifications

  - OpenMPTCProuter version: v0.57.3 r0+15225-bfc433efd4
  - OpenMPTCProuter VPS version: 0.1024 5.4.86-mptcp
  - OpenMPTCProuter platform: RPI4 2gb

![bandwidth](https://user-images.githubusercontent.com/79303426/108488527-7cc22780-726e-11eb-9327-0add7e2b6118.jpg)
both modems have same mac address ?                                              Set MTU to 1420 both default to these values 
![SharedScreenshot](https://user-images.githubusercontent.com/79303426/108488538-7fbd1800-726e-11eb-8211-fbb652c5f3f4.jpg)
![image](https://user-images.githubusercontent.com/79303426/108488993-05d95e80-726f-11eb-9aec-0b1c360b01fd.png)
same modem from pic 2 wan2  just behind router with rooter/golden orb connected to RPI4 via switch

**Comment by henry18hn** [comment]
On mine it changed my Eth2 to eth2.1 during reboot, I went to the Wizard and changed protocol til I found the correct one. 
O am also using 2 Goldenorb/Rooter modems. O see you using ModemManger protocol, I'm using, DHCP. What changes using Modem Manager?

**Comment by techdeisel** [comment]
> 
> 
> On mine it changed my Eth2 to eth2.1 during reboot, I went to the Wizard and changed protocol til I found the correct one.
> O am also using 2 Goldenorb/Rooter modems. O see you using ModemManger protocol, I'm using, DHCP. What changes using Modem Manager?

not sure i cant use static or dhcp with a usb modem tho i think

**Comment by techdeisel** [comment]
> 
> 
> > On mine it changed my Eth2 to eth2.1 during reboot, I went to the Wizard and changed protocol til I found the correct one.
> > O am also using 2 Goldenorb/Rooter modems. O see you using ModemManger protocol, I'm using, DHCP. What changes using Modem Manager?
> 
> not sure i cant use static or dhcp with a usb modem tho i think,are you using a rpi4?and you using dhcp wiht usb modem?

using rpi4 yes cant use anything but modem manager
