### ISSUE TITLE
Accès interface depuis installation VirutalBox

### ISSUE THREAD

**Issue by beuhbeuh71** [Ysurac/openmptcprouter#1613]
Bonjour,
j'ai installé OpenMPTCProuter sur VirtualBox, mais je n'arrive pas à accéder à l'interface d'administration depuis l'adresse 192.168.100.1

J'ai activé le mode promiscuité, et utilisé l'interface Server Intel PRO/1000 MT (82545EM)

Comment dois-je faire pour accéder à l'interface d'admin ?
Merci.

**Comment by Ysurac** [comment]
Il faut avoir une IP sur le réseau 192.168.100.x
