### ISSUE TITLE
Is there a Python documentation for that？

### ISSUE THREAD

**Issue by Deep-sea-boy** [Ysurac/openmptcprouter#1616]
I did not find any Python files, how to operate? Python is not supported？

**Comment by Deep-sea-boy** [comment]
This is download image :
![image](https://user-images.githubusercontent.com/37582640/108652221-9083bd00-74fe-11eb-9596-4a0068b2d605.png)

Front-end developer 's files path is www/ ? 
Where is back-end developer ’s files path ?
What back-end language was the project developed in ？ Roff？R？Python？Java？PHP？...

**Comment by Ysurac** [comment]
Python is not used on router side because this take some space and OpenMPTCProuter can be installed on hardware with small flash. Python is used on server side.
lua is used as back-end language for the interface, and shell script for others parts.
in /www there is static files and javascript. Others interfaces files are ine /usr/lib/lua/luci.

**Comment by hesenkang** [comment]
Hello, how can the front end modify the management page? Or do some personalized customization?
It looks like automatically generated code.
Please help me. @Ysurac

**Comment by Deep-sea-boy** [comment]
where is the luci log file?
how can i print the log?

**Comment by Deep-sea-boy** [comment]
CRUD data's path? In Mysql or other config file?

**Comment by Deep-sea-boy** [comment]
![image](https://user-images.githubusercontent.com/37582640/108813409-f13cf380-75eb-11eb-9ecd-2986d7be1eea.png)
Both of this are modify  /etc/config files？

**Comment by Ysurac** [comment]
All log is available via ```logread```.
Yes these commands modify /etc/config files.

**Comment by hesenkang** [comment]
Hello, how can the front end modify the management page? Or do some personalized customization?
/www or  /usr/lib/lua/luci ?
It looks like automatically generated code.
Please help me. @Ysurac
