### ISSUE TITLE
add custom ip rule

### ISSUE THREAD

**Issue by changloong** [Ysurac/openmptcprouter#1617]
I try add extra ip rule into `firewall.user` and `rc.local`,   it get automatic removed after some time.

I think a place to call user defined ip rule will be very nice.

**Comment by Ysurac** [comment]
Rules should not be removed if they don't conflict with another rule. What is the rule ?

**Comment by changloong** [comment]
`ip rule add to some_ip lookup 10`

**Comment by changloong** [comment]
I need some suggestion on where is the script modify the ip rule, I want to modify it to apply my own rule.

**Comment by Ysurac** [comment]
If table 10 is used by OpenMPTCProuter then the rule can be removed. You can create another table.
