### ISSUE TITLE
Slow bandwidth

### ISSUE THREAD

**Issue by renaudbrion** [Ysurac/openmptcprouter#1618]
### Expected Behavior
---
Correct aggregation of the 8 providers

### Current Behavior
---
Weird comportment with my config. The bandwidth is more or less the same with 8 providers linked that 3 providers.

- 3 providers linked : +/- 36,55 Mb/s (ovh.net) 
- 8 providers linked : +/- 36,32 Mb/s (ovh.net)

### Possible Solution
---

### Context (Environment)
---
Specifications
OpenMPTCProuter version: 0.57.3
5.4.86-mptcp 0.1024

--
Thank you!
Kr, 
Renaud

**Comment by Ysurac** [comment]
Please use the template.
Check aggregated speed and speed of each link with ```omr-test-speed```,```omr-test-speed wan1```... (ctrl+c to stop after at least 2 minutes).
Check that your 8 providers doesn't share same antenna if it's LTE.

**Comment by renaudbrion** [comment]
Apologies for the template. Thank you for your answer. 
I've already tested this, all seem right.

**Comment by Kalimeiro** [comment]
Can you please send screen capture of System -> OpenMPTCProuter -> Status ? (check Anonymize Public IPs)

**Comment by renaudbrion** [comment]
Ty for the answer

![image](https://user-images.githubusercontent.com/8436072/108686590-ebfd7d00-74f5-11eb-8128-b2b092542af0.png)

**Comment by hairydogltd** [comment]
Is the OpenMPTCProuter running on hardware that is struggling to carry the traffic?

**Comment by renaudbrion** [comment]
It should be OK ? This is running on SSD. 
![Screenshot_20210223-205830](https://user-images.githubusercontent.com/8436072/108900854-6d4e3000-761a-11eb-9ac8-60432ab08a3f.jpg)

**Comment by hairydogltd** [comment]
I was mostly thinking about the speed of the network port(s)

**Comment by Bug-Storm** [comment]
Je imagine que vous avez un switch, si oui peut être le souci vient de là 😉...

Et si oui, est il aménageable ?

**Comment by hairydogltd** [comment]
The network port(s) on the OMR router have to handle all the internet traffic. If that port gets overloaded, that will limit the speed available.

**Comment by redkite127** [comment]
Hello, and thanks for all your replies so far.
I really doubt the network ports are overloaded. We use:
- One Gig port for reaching all WANs (over a dedicated VLAN, eth1.101, eth1.102, ...)
- One Gig port for the private lan

Here are two screenshot, the first with 5 WANs (4 enabled/one master) and the second with only 2 WANs.
- top left, first big iftop is eth0 (private lan)
- second row, first column is eth1
- then it's eth1.101, eth1.102, ...

![speed_tests_iftop_20210224](https://user-images.githubusercontent.com/634637/109053864-7b18b980-76dd-11eb-9f61-58ae798183ba.png)
![speed_tests_iftop_20210224 (only 2 WAN)](https://user-images.githubusercontent.com/634637/109053879-7e13aa00-76dd-11eb-9a51-49efaef4fc8f.png)

**Comment by redkite127** [comment]
I'm confused :confused: ... We moved to an other VPS (for geolocation issues) last week, and I haven't speedtested it yet assuming all VPS are having a descent speed nowadays... I've just done it at it's limited to... 39Mbps :facepalm: 

I immediately switched back to Google and it improved (still not ideal) here are the same screenshot, first one with 5 WANs, second with 2.
![speed_tests_iftop_20210224_GOOGLE](https://user-images.githubusercontent.com/634637/109062068-bb7d3500-76e7-11eb-977f-98d4ef79e4c6.png)
![speed_tests_iftop_20210224_GOOGLE (only 2 WAN)](https://user-images.githubusercontent.com/634637/109062080-be782580-76e7-11eb-9763-c99f4c58f9cb.png)

As you can see, we do reach 72 Mbps but it's still not that awesome comparing to the theoretical sum of throughputs.
![Screenshot_20210224_213652](https://user-images.githubusercontent.com/634637/109062655-7d344580-76e8-11eb-97da-61f57c5691bf.png)

I'm also suspecting some WANs (102,107,109), which are performing well alone, to be using/sharing the same bottleneck somewhere, when used simultaneously, none of them preform as well as alone... (a little bit like 4G problems)

Are you used to such a difference between theoretical sum of speed, what does it tend to be for you? (like ratio between theor/pratic)

**Comment by Bug-Storm** [comment]
Try to speed test with 3 wan, after 4wan etc..... And look up how much wan you don't have a speed limit 😉

**Comment by redkite127** [comment]
Yup, doing more speedtests and monitoring VLAN interfaces will helps... and having three connections struggling on the same bottleneck is just a waste of money ><
