### ISSUE TITLE
Lost graph!

### ISSUE THREAD

**Issue by hairydogltd** [Ysurac/openmptcprouter#1623]
I used to be able to see a graph of traffic, with each of the WAN connections shown on the same graph (different colours) but I can't find it any more.
//ip.address/cgi-bin/luci/admin/status/realtime/bandwidth seems to be the nearest to what I remember seeing, but that only shows me the graph of each connection individually.
Am I looing in the wrong place, or is there a setting to re-enable the multiple wan graph?

**Comment by Ysurac** [comment]
In Network->MPTCP, Bandwidth tab

**Comment by hairydogltd** [comment]
Thanks. That's what I was looking for.
There are so many places things can hide!
