### ISSUE TITLE
how can i install apt-get or yum ?

### ISSUE THREAD

**Issue by Deep-sea-boy** [Ysurac/openmptcprouter#1627]
i want to install python3-dev  
![image](https://user-images.githubusercontent.com/37582640/109099618-57498800-775e-11eb-9897-7c887ec61a1f.png)
 so i want to use tools like apt-get or yum

**Comment by Ysurac** [comment]
```opk update && opk install python3-dev```
OpenMPTCProuter is not based on Debian or Redhat, so there is no apt-get or yum and it's not possible to use them.
