### ISSUE TITLE
Webinterface: Possible to access via vps?

### ISSUE THREAD

**Issue by ByteArrayException** [Ysurac/openmptcprouter#1628]
Hey,

is it possible to access the luci interface on omr clientside via the vps serverside?

Best regards

**Comment by Ysurac** [comment]
Yes, by redirecting ports: https://github.com/Ysurac/openmptcprouter/wiki/Port-forwarding

**Comment by ByteArrayException** [comment]
Thanks! I will test this in the next days.
Thumbs up for this cool project! Keep it up!

Best regards
