### ISSUE TITLE
Shadowsocks is not running + Can't get public IP address from shadowsocks 

### ISSUE THREAD

**Issue by kinkyninja** [Ysurac/openmptcprouter#1629]
## Expected Behavior

This error should not occur. 
'Force retrieve keys' helps but only for the current session and after hardware reboot, it's needed again.  

As a fallback solution, I can execute 'Force retrieve settings' in command line after each reboot. 
Can you tell how to execute this from command line?

## Current Behavior

This error happens in ~50% of cases after rebooting the system (Raspberry Pi 4B + 4 modems). 
Internet starts lagging, seems like only 1 modem works when the problem is there. In ~50% cases everything works just fine. 

1 interface is master.

Checked other similar Issues here, but didn't find a solution. 

After pressing "Force retrieve all keys from server" and saving the problem goes away. 
But after the hardware reboot - it's still there, the problem occurs in 30%-50% cases. 

![image](https://user-images.githubusercontent.com/21219727/109175487-e5d9fb80-7796-11eb-8006-1f1a9dadc2bd.png)

## Specifications

  - OpenMPTCProuter version:  v0.57.3 r0+15225-bfc433efd4
  - OpenMPTCProuter VPS version:  5.4.86-mptcp 0.1024
  - OpenMPTCProuter platform: Raspberry Pi 4

**Comment by hairydogltd** [comment]
Why is the Raspberry Pi being rebooted? 
How are you rebooting it?

**Comment by Ysurac** [comment]
Check in State->Process what is using so much CPU.

**Comment by kinkyninja** [comment]
Btw, how do I "Force retrieve settings" via the command line?

**Comment by kams19** [comment]
i had similar issue, had to rebuild the openmptcp router - then it works fine.
