### ISSUE TITLE
[info]So someone used omr to create a business solution

### ISSUE THREAD

**Issue by Malaga82** [Ysurac/openmptcprouter#1631]
https://www.tomshw.it/hardware/unire-due-o-piu-connessioni-a-internet-uania-box/

They posted UI images and they are “similar” of what we have with omr, stripped with all nerd functions.
What do you think about it?
650€...meh
Would be interesting know what device they use as router 🤔

**Comment by Ysurac** [comment]
Not a problem. It's an italian partner and I made the changes :satisfied:

They use a really nice custom x86_64 based router.

There is a lot of business solutions that use OpenMPTCProuter without contacting me (they can if they follow licenses), at least it's not the case at all here.
