### ISSUE TITLE
MLVPN segfaulting missing config option "cleartext"

### ISSUE THREAD

**Issue by Himan2001** [Ysurac/openmptcprouter#1632]
With actual Intel x32 mlvpn is continously segfaulting when killed or restarted. This was not the case on the stable version on x32 architecure.

Feature-Request for MLVPN: A webbased option to set "cleartext_data=1" on server and clientside to archive a higher througput and have a much lower cpu usage.

**Comment by Ysurac** [comment]
What you call actual Intel x32 ? and stable version ?

**Comment by Himan2001** [comment]
I use a HP Thinclient t5740 with 2 GB ram and actual stable OMR Version.
further more i added an external vlan capable switch and use 3 vlans for 2x WAN in + 1xLAN out
