### ISSUE TITLE
Cannot access default gateways - Alpha version has bug with Masquerading

### ISSUE THREAD

**Issue by milankragujevic** [Ysurac/openmptcprouter#1634]
## Expected Behavior
I can access, from my PC, the web UI of all my modems, by visiting their IPs.

For example, modem 1 is on 192.168.1.1, modem 2 is on 192.168.8.1 and OMR is on 192.168.100.1

## Current Behavior
Packets to 192.168.0.0/16 are dropped. 

## Possible Solution
In firewall, click edit on WAN firewall zone, switch to tab *Advanced settings* and remove the destination "!192.168.0.0/16" from *Restrict Masquerading to given destination subnets* list.

![image](https://user-images.githubusercontent.com/7611163/109424845-f03e0480-79e5-11eb-95b5-5629deb10644.png)

After that it works fine. I am not sure if this will have negative impact on the network and OMR. 

## Steps to Reproduce the Problem

  1. Install alpha v0.58 on VPS and device
  2. Setup device so it has 2 modems
  3. Try to access any modem's web UI

## Context (Environment)
Default everything, retried multiple times. Traceroute shows no response after 192.168.100.1. 

I tried setting default routes, nothing helps unless Masquerading is enabled for LAN subnet by removing the rule !192.168.0.0/16 from WAN firewall zone. 

This is not a complaint, of course, I am aware this is alpha. Just letting you know that this is unexpected behavior since it is quite normal to access modem web UI from a computer behind OMR, and as such this should be fixed. It has worked until this alpha version, and I switch to alpha due to OMR-Bypass breaking and also problems with two or more ethernet adapters on the device mixing up on reboot, which was fixed in this alpha version. 

## Specifications

  - OpenMPTCProuter version: v0.58 ("openmptcprouter v0.57.3 r0+15829-482c9ff289", built 25-Feb-2021 17:07)
  - OpenMPTCProuter VPS version: Version 0.1025-test 5.4.100-mptcp
  - OpenMPTCProuter platform: RPI4 bcm2711

**Comment by Ysurac** [comment]
This will be removed.
