### ISSUE TITLE
ShadowSocks ne se lance plus

### ISSUE THREAD

**Issue by gblanchet03** [Ysurac/openmptcprouter#1638]
@Ysurac 
Après une mise à jour des packages ShadowSocks ne se lance plus.
Comment le relancer ?
Le journal system me dit régulièrement ceci 👍 
Mon Mar  1 08:19:11 2021 user.info : using tcp fast open
Mon Mar  1 08:19:11 2021 daemon.info /usr/bin/ss-redir[26615]: enable TCP no-delay
Mon Mar  1 08:19:11 2021 daemon.info /usr/bin/ss-redir[26615]: initializing ciphers... chacha20-ietf-poly1305
Mon Mar  1 08:19:11 2021 daemon.err /usr/bin/ss-redir[26615]: Invalid key for your chosen cipher!
Mon Mar  1 08:19:11 2021 daemon.err /usr/bin/ss-redir[26615]: It requires a 32-byte key encoded with URL-safe Base64
Mon Mar  1 08:19:11 2021 daemon.err /usr/bin/ss-redir[26615]: Generating a new random key: MjifvEg6v6PfcdHqDXSQ8w-GQnt6GRF93QogezHHea4=
Mon Mar  1 08:19:11 2021 daemon.err /usr/bin/ss-redir[26615]: Please use the key above or input a valid key
Le journal du noyau me dit ceci très régulièrement 👍 
[38860.517345] traps: logread[19598] general protection fault ip:7fa13ae2a4e9 sp:7ffc8a855de0 error:0 in libc.so[7fa13ade9000+49000]
Par contre ifconfig et route sont corrects.

**Comment by Ysurac** [comment]
Si c'est une mise à jour via la liste des paquets c'est normal.
La version de shadowsocks utilisée par OpenMPTCProuter est modifiée, donc une version classique a des chances de ne pas fonctionner.
