### ISSUE TITLE
Slow Bandwidth and iperf Problem

### ISSUE THREAD

**Issue by easycloudcompany** [Ysurac/openmptcprouter#1644]
Hi, on my installation seems the bandwidth is very slow and also the ping latency is haigh

I've seen similar issue here and i've tryed with iperf test on shell and on Webgui but it does not work  see following image

![image](https://user-images.githubusercontent.com/48676189/109804678-ce7d9100-7c22-11eb-9482-e4d0be5d750a.png)
![image](https://user-images.githubusercontent.com/48676189/109804738-e228f780-7c22-11eb-9d5e-cab2cf94f372.png)

and some time on bond-VPS there is an error  **"impossible obtain public IP by ShadowSocks!**

![network 2](https://user-images.githubusercontent.com/48676189/109805760-1fda5000-7c24-11eb-8720-f97a74384312.PNG)

My configuration is the following
System:

![system](https://user-images.githubusercontent.com/48676189/109805848-3aacc480-7c24-11eb-8f10-c319b8ee0e57.PNG)

**Comment by Ysurac** [comment]
Please use template.

There is no master interface defined, this must be the case.

For iPerf some servers can answer or not sometimes, they are limited.

To test speed, via SSH or Services->terminal there is ```omr-test-speed``` to test aggregated speed and ```omr-test-speed <wan>``` to test <wan> speed. After at least 2 minutes can be stopped via Ctrl+C.

For ping problem, you can enable SQM.

**Comment by easycloudcompany** [comment]
Thanks and sorry I'll use the template if needed in future.


BR
