### ISSUE TITLE
GL-MT300N-V2 Mini Smart Router

### ISSUE THREAD

**Issue by hairydogltd** [Ysurac/openmptcprouter#1652]
**Is this request related to a missing driver support for a particular hardware platform, SoC or board? Please describe.**

Request for a specific hardware platform

It seems to have at least some of OMR already. It is small, light, inexpensive and it looks useful

**Describe why you are asking for this support?**

I have one of these devices and it works well. 

**Additional context**

https://www.gl-inet.com/products/gl-mt300n-v2/

**Comment by Ysurac** [comment]
Really small flash, CPU and memory.

**Comment by hairydogltd** [comment]
Ah well, it was worth asking!
