### ISSUE TITLE
operation not supported error

### ISSUE THREAD

**Issue by Ajowan84** [Ysurac/openmptcprouter#1653]
![2021-03-05_213055](https://user-images.githubusercontent.com/42247038/110171219-b57c0800-7dfb-11eb-9f17-c9fd72ac9302.png)

I have a permanent error. See screenshot 
But OMPTCPR seems to be working fine

## Specifications

  - OpenMPTCProuter version:  openmptcprouter v0.57.3 r0+15225-bfc433e
  - OpenMPTCProuter VPS version: 0.1024 5.4.86-mptcp
  - OpenMPTCProuter platform: vmware ESX : openmptcprouter-v0.57.3-r0+15225-bfc433efd4-x86-64-generic-squashfs-combined.ova

**Comment by Ysurac** [comment]
It's a filesystem error and it's why I prefer ext4: I already had some strange error with squashfs images.

**Comment by Ajowan84** [comment]
OK.

And what is the better choice ?
openmptcprouter-v0.57.3-r0+15225-bfc433efd4-x86-64-generic-ext4-combined-efi.ova
or
openmptcprouter-v0.57.3-r0+15225-bfc433efd4-x86-64-generic-ext4-combined.ova

Thx

**Comment by Ysurac** [comment]
You don't need EFI for VMware.

**Comment by Ajowan84** [comment]
Thank you very much for these quick answers.

**Comment by Adorfer** [comment]
This messages appears when trying use a flash-filesystem on non-flash-drives (e.g. not supporting DISCARD operation)
normally all flash drives (emmc, spi, sata-SSD, NVRAM) should be able. If you use squashfs on a hypervisor, enable "discard" (or say "emulate SSD", if the option is named like that)

**Comment by Ajowan84** [comment]
@Adorfer thank you for that clarification !
