### ISSUE TITLE
Error in Realtime Traffic page when MPTCP is enabled via WiFi

### ISSUE THREAD

**Issue by afriza** [Ysurac/openmptcprouter#166]
## Expected Behavior

  Realtime Traffic page works as usual.

## Actual Behavior
[Realtime Traffic page](http://192.168.100.1/cgi-bin/luci/admin/network/mptcp/bandwidth) is not working
![realtime traffic page is not working](https://user-images.githubusercontent.com/68133/45413294-05ead280-b6a3-11e8-8f57-98340e7ec222.png)
```
Wed Sep 12 08:40:08 2018 daemon.err uhttpd[4219]: Failed to execute call dispatcher target for entry '/admin/network/mptcp/multipath_bandwidth'.
Wed Sep 12 08:40:08 2018 daemon.err uhttpd[4219]: The called action terminated with an exception:
Wed Sep 12 08:40:08 2018 daemon.err uhttpd[4219]: /usr/lib/lua/luci/controller/mptcp.lua:40: table index is nil
Wed Sep 12 08:40:08 2018 daemon.err uhttpd[4219]: stack traceback:
Wed Sep 12 08:40:08 2018 daemon.err uhttpd[4219]: 	/usr/lib/lua/luci/controller/mptcp.lua:40: in function 'callback'
Wed Sep 12 08:40:08 2018 daemon.err uhttpd[4219]: 	/usr/lib/lua/luci/model/uci.lua:295: in function 'foreach'
Wed Sep 12 08:40:08 2018 daemon.err uhttpd[4219]: 	/usr/lib/lua/luci/controller/mptcp.lua:35: in function </usr/lib/lua/luci/controller/mptcp.lua:31>
Wed Sep 12 08:40:08 2018 daemon.err uhttpd[4219]: 	(tail call): ?
```

## Steps to Reproduce the Problem

  1. Connect to WiFi as a client
  2. Enable Multipath on WiFi

## Specifications

  - OpenMPTCProuter version: (v0.35)
  - OpenMPTCProuter VPS version: (Last is not a version)
  - OpenMPTCProuter platform: (RPI2 binary on RPi3B+)

**Comment by Ysurac** [comment]
Fixed in latest release
