### ISSUE TITLE
Problem of traffic between the interface ==> a doubling of the bandwidth consumption

### ISSUE THREAD

**Issue by gmorlet** [Ysurac/openmptcprouter#1660]
## Expected Behavior
avoid unnecessary traffic (double incoming/outgoing traffic) to reduce bandwidth through the 4G modem

## Current Behavior
Here is my network plan: https://ibb.co/PF0W2MP

I have just ordered the installation of opentcprouter and the installation of an rpi with the home automation jeedom

on my lan 192.168.100.1
I have the jeedom rpi (192.168.100.140)

at the level of my 4G router I have a quota of 200Gb / Month and I notice a traffic of 20 to 40Gb / days while usually I am only between 5 and 10Gb

I installed bandwith monitor 
and I for a consumption of 20 Gb on a day I notice :
- 9 Go on the ip 192.168.8.2 or the passage by the Wan1
- 8 Gb for the jeedom interface

I may have some problems to set up the rule of bandwith monitor to have the detail per day but I do not know which interface to monitor (lan, wan, 2 in connection with the vpn I think)

I'm wondering how the path of a request and the feedback between the client, the physical router, the vps and the WAN works

my fear is that the signal goes through the wan twice

Ex
Request : Client, physical router, vps (but to access it, it must go through the wan in tunnel)

return return reverse path.

But what happens for a "local" traffic because my jeedom mainly processes sensors in the 192.168.100.X subnet and information with different home automation protocol.

Thank you for your help and information

P.S. : how to set up a tool and which one to see the traffic and record the logs 

Translated with www.DeepL.com/Translator (free version)
## Specifications

  - OpenMPTCProuter version: 0.57.3
  - OpenMPTCProuter VPS version: 0.1024 5.4.86-mptcp
  - OpenMPTCProuter platform: RPI4

**Comment by Ysurac** [comment]
local traffic doesn't use wan at all, local traffic on same subnet as the client doesn't even need the router.
You can install luci-app-statistics or luci-app-nlbwmon
