### ISSUE TITLE
No Server ping response after 1 second - When connected to one VPS and not the other

### ISSUE THREAD

**Issue by bnhf** [Ysurac/openmptcprouter#1665]
## Expected Behavior
Regardless of connected VPS, individual cellular links would respond to ping and there would be a green check mark next to the connection.

## Current Behavior
When switching between a VPS set up on Vultr, and my own private VPS, the same two cellular links fail to show a green check mark.  Instead, there's a yellow warning triangle and the message "No Server ping response after 1 second".  Seems like a given WAN link would either respond to a ping, or not, and would not be influenced by connections to different VPS's.

## Possible Solution
Unsure.

## Steps to Reproduce the Problem

For me, switching between the two VPS's I have configured reproduces the problem consistently.

## Context (Environment)

With the warning triangle, rather than a green check mark, it's harder to know for sure all is well with a given link.

## Specifications

  - OpenMPTCProuter version: v0.57.3 r0+15225-bfc433efd4
  - OpenMPTCProuter VPS version: v0.1024 5.4.74-mptcp
  - OpenMPTCProuter platform: x86_64)

When connected to my original Vultr VPS:

![screenshot-192 168 100 1-2021 03 14-12_28_56](https://user-images.githubusercontent.com/41088895/111080576-afa1b900-84c4-11eb-8baf-da1c10a9dd13.png)

When connected to my new private VPS, moments later, using the same two cellular links:

![screenshot-192 168 100 1-2021 03 14-12_23_28](https://user-images.githubusercontent.com/41088895/111080620-e4ae0b80-84c4-11eb-8a54-b70d0c4cfa8b.png)

**Comment by Ysurac** [comment]
And the server answer to ping from wans in less than 1 second ?

**Comment by bnhf** [comment]
> And the server answer to ping from wans in less than 1 second ?

Sounds like I've made bad assumption.  I've always assumed that the OpenMPTCProuter end was doing the pinging.  If it's the VPS doing the pinging, then what's happening makes sense.  Perhaps I need a more powerful VM, or dedicated machine, to run the VPS?  Also I imagine there's a way to prioritize my router traffic to and from my private VPS to improve ping times as well?

**Comment by Ysurac** [comment]
ping is done from router to VPS using each wan, but ping must be not blocked on VPS for that to work.

**Comment by bnhf** [comment]
> ping is done from router to VPS using each wan, but ping must be not blocked on VPS for that to work.

Thanks Yannick! In my case I had to allow ICMP "Echo Request" traffic to pass through my Ubiquiti USG firewall like so:

![screenshot-techie4hire duckdns org_8443-2021 03 14-15_27_21](https://user-images.githubusercontent.com/41088895/111084917-7116f900-84da-11eb-9806-108d78bf8c59.png)

Green check marks appeared almost immediately.
