### ISSUE TITLE
multisites avec rpi openmcprouter par site et un vps commun, réalisable ? avantages / inconvénients

### ISSUE THREAD

**Issue by gmorlet** [Ysurac/openmptcprouter#1667]
## Expected Behavior
Bonjour
Es-ce possible ? si oui Avantages et inconvénients de la proposition suivante 😀

ex 4 sites distintcts,
chaque site a pour l'exemple une connexion adsl ou fibre couplé avec une clé 4g
un rpi avec openmptcprouter
un VPS chez un prestataire avec l'autre partie d'openmptcprouter et pihole

peut on connecter chaque rpi de chaque site vers le même VPS

Cela permet d'avoir une seule IP public et une gestion centralisée pour pihole
ensuite mettre en place vpn donc chaque site doit avoir un sous réseau différent

après je ne sais pas trop les avantages et inconvénients, je me demande les possibilités d'openmptcprouter et si quelqu'un a déjà effectué cela pour avoir un retour

Merci

**Comment by Ysurac** [comment]
Duplicate of #1058 
Donc supporté via l'API mais non officiellement documenté pour le moment.
