### ISSUE TITLE
VPS disconnects when performing speedtest or heavy network task or randomly

### ISSUE THREAD

**Issue by imbdb** [Ysurac/openmptcprouter#1669]
## Expected Behavior
Should not disconnect when doing speedtest

## Current Behavior
Server disconnects when doing speedtest
I can see these in server logs
```
ss-server[2187]: server recv: Connection reset by peer
ss-server[2187]: server recv: Connection reset by peer
ss-server[2187]: server recv: Connection reset by peer
ss-server[2187]: server recv: Connection reset by peer
```

## Specifications

  - OpenMPTCProuter version: Version 0.56.4
  - OpenMPTCProuter VPS version: Debian 10 - Version 0.1024 5.4.86-mptcp
  - OpenMPTCProuter platform: Raspberry Pi4B
  
Note:  I am using 0.56.4 because I kept getting `VPN tunnel DOWN` plus random disconnections on the latest version of JAN 5 2021.

**Comment by Ysurac** [comment]
If the VPS disconnect, then it's a VPS problem.
If it's a connection problem between VPS and router, enable SQM on WANs interfaces in the wizard.

**Comment by imbdb** [comment]
thanks Yannick for your response.
VPS seems stable according to the logs and it will keep showing green until I do some work on the internet like opening a website or doing a speed test.

whenever I do a speedtest I below error on VPS
```
ss-server[2187]: server recv: Connection reset by peer
ss-server[2187]: server recv: Connection reset by peer
ss-server[2187]: server recv: Connection reset by peer
ss-server[2187]: server recv: Connection reset by peer
```

I cannot enable SQM because I am using 4G dongles for bonding.

**Comment by Ysurac** [comment]
You can try to enable SQM without setting a max speed.
This disconnect even for a simple website ? In this case you can try to disable TCP Fast Open in System->OpenMPTCProuter, "Advanced settings" tab.

**Comment by imbdb** [comment]
Still facing the issue.
Perhaps it not fault of OpenMPTCP router but result of low connection speeds on my 4G dongles (1-2Mbps only).

Thanks Yannick for creating this awesome project.
Will love to contribute in project,
