### ISSUE TITLE
where to download 0.58 

### ISSUE THREAD

**Issue by brazzo97** [Ysurac/openmptcprouter#1670]
hi i am not able to find the alpha 0.58 to download , is it out yet ? Thanks

**Comment by Ysurac** [comment]
Snapshot images are here: https://download.openmptcprouter.com/develop/5.4/

**Comment by brazzo97** [comment]
i cant find 0.58 snapshot in that directory , are they unavaible yet ?

**Comment by Ysurac** [comment]
Even if not labelled as 0.58, it's 0.58 alpha images.
