### ISSUE TITLE
VPS cannot be reached due to shorewall blocking

### ISSUE THREAD

**Issue by dur3x** [Ysurac/openmptcprouter#1671]
## Expected Behavior
Connection correctly established to VPS

## Current Behavior
Server started then ping & ssh works a while but quickly loose the connection with this in logs:

```
Mar 15 20:46:21 ks3374040 root: Shorewall started
Mar 15 20:46:21 ks3374040 kernel: [  431.938942] Shorewall:OUTPUT:REJECT:IN= OUT=eno0 SRC=X.X.X.X DST=Y.Y.Y.Y LEN=104 TOS=0x10 PREC=0x00 TTL=64 ID=37016 DF PROTO=TCP SPT=65222 DPT=4916 WINDOW=22 RES=0x00 ACK PSH URGP=0 
```
For info X.X.X.X is my VPS ip & Y.Y.Y.Y is my home ip

## Possible Solution
Current Workaround is to disable shorewall at boot but probably the best would be to understand what's wrong and why I'm completely rejected (ssh on port 65222 + icmp denied)

## Steps to Reproduce the Problem
Install fresh install in debian 9

## Context (Environment)
kimsufi install with debian 9

**Comment by Ysurac** [comment]
Debian 9 is migrated to Debian 10 by script, so you should install Debian 10.
You should check in /etc/shorewall/params.net that correct external interface was detected.

**Comment by dur3x** [comment]
I can confirm you that the script updated well the debian 9 into 10 :-)
Indeed the interface was wrong in /etc/shorewall/params.net
````
NET_IFACE=enp1s0
````
instead of
`````
NET_IFACE=eno0
`````

I suspect that enp1s0 was perhaps the interface name before the upgrade into debian 10.

Well as usual, you are the king and gave me a workaround very quicky ;-) I'm so excited to test this new setup !
