### ISSUE TITLE
Comment désactiver l'IPv6 ?

### ISSUE THREAD

**Issue by kdesroches89** [Ysurac/openmptcprouter#1672]
Bonjour,
Je ne souhaite pas utiliser d'IPv6 , comment désactiver l'IPv6 complètement ?

@Ysurac  Merci par avance pour l'aide

Merci
Kilian

**Comment by Ysurac** [comment]
L'IPv6 est désactivé par défaut.
Pour l'activer/désactiver, c'est dans Système->OpenMPTCProuter, et la case "paramètres avancés"

**Comment by kdesroches89** [comment]
C'est déja le cas mais j'ai quand même de l'IPv6 :

![Screenshot_2021-03-16 aghome - Paramètres avancés - LuCI](https://user-images.githubusercontent.com/75026748/111277008-42af3000-8638-11eb-8c19-ff328d361a65.png)

![Capture](https://user-images.githubusercontent.com/75026748/111277730-0cbe7b80-8639-11eb-8290-379aadcfc1fb.PNG)

**Comment by Ysurac** [comment]
Voir dans Réseau->Interfaces puis LAN, onglet "Serveur DHCP", puis "Paramètres IPv6" que tout est bien sur "désactivé".
Pour l'adresse 2a01:xxx elle peut provenir d'un autre matériel comme une freebox par exemple.

**Comment by kdesroches89** [comment]
C'est effectivement la freebox mais visiblement il faut relancer celle ci pour que OpenMTCPRouter prenne la main en amont . En cas de relance du routeur la freebox passe avant . La freebox n'a pas d'ipv6 activé , de dhcp6 actif ou de dns6 actif.

Merci @Ysurac
