### ISSUE TITLE
Incorrect Bandwidth in OpenMPTCP Graph

### ISSUE THREAD

**Issue by kams19** [Ysurac/openmptcprouter#1678]
![image](https://user-images.githubusercontent.com/75209712/111789601-3ab1f300-88b9-11eb-82c8-d385a7f3ec52.png)

Has anyone else had this and also the colours dont match to the legend.

**Comment by hairydogltd** [comment]
The individual WANs are shown stacked on top of each other, but there is no red line, and the total is not explicitly shown on the graph. But it is the top of the stack!
