### ISSUE TITLE
Message persistant du noyau

### ISSUE THREAD

**Issue by gblanchet03** [Ysurac/openmptcprouter#1679]
@Ysurac malgré une réinstallation complète et du routeur et du serveur (VPS détruit à Strasbourg) j'ai toujours ces messages du noyau sur OMR installé sur OTB+
[ 5285.897115] traps: logread[19845] general protection fault ip:7f04cfd2f4e9 sp:7ffc2a9f2220 error:0 in libc.so[7f04cfcee000+49000]
[11963.464398] traps: logread[20028] general protection fault ip:7f6e91dde4e9 sp:7fffd5fce2e0 error:0 in libc.so[7f6e91d9d000+49000]
J'ai lu qu'il s'agissait d'une erreur de gcc mais qu'est-ce qui a été mal compilé et qui renvoie cela de manière aléatoire ?
J'ai installé par cron un redémarrage du routeur à 4:30 mais ce matin j'ai à nouveau ces deux lignes.
Cordialement.
Gérard

**Comment by Ysurac** [comment]
oui déjà vu ces erreurs. Après ça concerne que logread, donc rien de grave.
