### ISSUE TITLE
Create a static route to use a local gateway and not the VPS

### ISSUE THREAD

**Issue by valent1ad** [Ysurac/openmptcprouter#1681]
## Expected Behavior
HI,
First of all thank you for your hard work on this project because for me it just worked out of the box with my Rapsberry PI 3 and a ovh VPS. It allowed me to aggregate my DSL connection and a 4G connection.

BUT :

I do need to use my DSL connection for a specific service and I do need to use my xDSL IP for a specific service and not the VPS IP.

Indeed I need to route all the traffic to that specific ip through my ISP box local gateway and not through the VPS.

Here is my configuration working perfectly well with OVH VPS 

![image](https://user-images.githubusercontent.com/67643215/111906587-77185700-8a51-11eb-8c27-2f5f171a7a99.png)

## Current Behavior
In order to force my https traffic to 51.15.XX.XX IP to be routed by 192.168.0.254 I created a static route under Network > Static Route:

![image](https://user-images.githubusercontent.com/67643215/111906659-df673880-8a51-11eb-9238-36372818d2c4.png)

When I do a regular traceroute I see it goes through local gateway 
![image](https://user-images.githubusercontent.com/67643215/111906862-1558ec80-8a53-11eb-88ac-0d2472679d28.png)

But when I do connect to this server in HTTPS .. my connection is refused because it comes from the VPS ...
I don't understand I'm stuck here.
![image](https://user-images.githubusercontent.com/67643215/111906882-37eb0580-8a53-11eb-83da-5646b1c144b9.png)

Do I miss something ? 

When I delete my static route I see that the traceroute goes to the gateway 10.255.255.1 (VPN) for non TCP connection

Thank you for your help
V.

## Specifications

  - OpenMPTCProuter version: v0.57.3 r0+15225-bfc433efd4
  - OpenMPTCProuter platform: raspberry pi 3

**Comment by Ysurac** [comment]
use omr-bypass for that.

**Comment by valent1ad** [comment]
thank you
