### ISSUE TITLE
Question concernant le GRE

### ISSUE THREAD

**Issue by AdrienDssy** [Ysurac/openmptcprouter#1682]
Bonjour,

Je compte up mon AS pour un "experimentlab" pour l'instant. Et j'ai essayer d'ouvrir les port de ma machine mikrotik (GRE compris) vers l'extérieur mais la connexion GRE ne s'effectue pas.

![image](https://user-images.githubusercontent.com/53304251/111978589-5e1cae00-8b04-11eb-9a74-bd16d2c8627f.png)

**Comment by Ysurac** [comment]
Je pense pas que GRE soit un protocol reconnu.
En tout pour vérifier que le port forward fonctionne: https://github.com/Ysurac/openmptcprouter/wiki/Port-forwarding#debug
