### ISSUE TITLE
Email notifications when WAN is offline

### ISSUE THREAD

**Issue by hrmtc** [Ysurac/openmptcprouter#1684]
Hi.

How can I configure email notifications when some of my configured WAN interfaces become offline?
What software package would help me to achive this?

Thanks!

**Comment by Ysurac** [comment]
You can check "Mail alert" in Services->omr-tracker on defaults section or by adding wan interfaces you want to be notified.
Mail configuration is in Services->E-Mail

**Comment by Kalimeiro** [comment]
And be sure to set in Settings ->DNS recursive -> DHCP -> WAN DNS to "Use upstream"
Then, set in interface WAN1 DNS of you'r ISP.

**Comment by Ysurac** [comment]
Should not be needed. By default root servers DNS are used and they are available when VPS is online or not and from every WANs.
The only (rare) case where this can be a problem is when external DNS is blocked by ISP.

**Comment by hrmtc** [comment]
> You can check "Mail alert" in Services->omr-tracker on defaults section or by adding wan interfaces you want to be notified.
> Mail configuration is in Services->E-Mail

Thanks! This seems to be exactly what I was looking for.
