### ISSUE TITLE
firewall doesn't work for open port 8080

### ISSUE THREAD

**Issue by mykelinho** [Ysurac/openmptcprouter#169]
Expected Behavior
firewall doesn't work for open port 8080

Steps to Reproduce the Problem
test firewall with adress 192.168.100.23
when i go to my ip public 54.xx.xx.xx:8080, doens't work

Specifications
OpenMPTCProuter version: openmptcprouter v0.34.4 r7298-f7413579c0 / LuCI Master (git-18.248.76017-8951f5f)
OpenMPTCProuter VPS version: OVH Debian 9
OpenMPTCProuter platform: RPI-3+

![image](https://user-images.githubusercontent.com/42909444/45601237-133cef80-ba0a-11e8-8f53-b2992bd1f0cb.png)

**Comment by Ysurac** [comment]
Did you follow the documentation https://github.com/Ysurac/openmptcprouter/wiki/Port-forwarding ?

**Comment by mykelinho** [comment]
sorry i have,'t read this documentation.
it's OK good!
thank you
