### ISSUE TITLE
install python3 package and access to rapsi-config for I2C activation

### ISSUE THREAD

**Issue by numerobis08** [Ysurac/openmptcprouter#1692]
Hello 
i would like to put the raspberry on which i have openmptcp installed into a rack with a small old screen to monitor temparatur e , load , ... 
for that i need to access to raps-config to activate I2C interface and have to run the following commands : 
sudo apt-get install python3-pip
sudo pip3 install adafruit-circuitpython-ssd1306
sudo apt-get install python3-pil
sudo apt-get install -y python-smbus
sudo apt-get install -y i2c-tools
sudo pip3 install psutil

-> i managed to connect in root via SSH but cannot run either "sudo raps-config " nor any of the commands above. 
error message : -ash sudo : not found. 

Can someone has an idea ?

**Comment by Ysurac** [comment]
OpenMPTCProuter is not based on raspbian or Debian, so apt is not available.
OpenMPTCProuter is based on OpenWrt and packet manager is opk
