### ISSUE TITLE
Monitoring Jeedom

### ISSUE THREAD

**Issue by JeedHome44** [Ysurac/openmptcprouter#1696]
**Is your feature request related to a problem? Please describe.**
 Faire un plugin Jeedom pour monitorer OMR sur Jeedom 

**Describe the solution you'd like**
 Cela permettrait d'automatiser le reboot d'un wan si problème... avoir des notifications autre que mail pour OMR par Jeedom...

J'ai déjà la Freebox et le routeur Huawei sur Jeedom. Il me manque OMR! 

**Describe alternatives you've considered**

**Additional context**

**Comment by Ysurac** [comment]
Je n'utilise pas Jeedom actuellement, donc il y a peu de chance que je fasse un plugin prochainement. Désolé.
Par contre il y a une API sur OpenMPTCProuter et j'ai l'intention de l'enrichir prochainement, donc faire ce genre de chose sera de plus en plus simple.

**Comment by JeedHome44** [comment]
Ah donc c'est possible de faire un script qui interroge toutes les minutes OMR et faire des script pour recharger un wan ou autre?

**Comment by Ysurac** [comment]
oui

**Comment by JeedHome44** [comment]
Ah tu as un lien pour ça? Ça m'intéresse de faire un virtuel Jeedom avec un cron 1 minute 😉

**Comment by Ysurac** [comment]
Tiens je peux ajouter une option pour redémarrer un wan quand down dans omr-tracker aussi...

**Comment by Ysurac** [comment]
La doc pour l'API: https://openwrt.org/docs/techref/ubus#access_to_ubus_over_http

**Comment by JeedHome44** [comment]
Oh donc on peut voir l'état de chacun des wan et le redémarrer? Ça serait juste top ça! Je vais potasser ca 😉

**Comment by JeedHome44** [comment]
Ah c'est pas une API OMR? C'est autre chose non?

Tu pourrais me donner un exemple pour que je comprenne mieux ce qu'il faut que je fasse?

Merci

**Comment by JeedHome44** [comment]
> Tiens je peux ajouter une option pour redémarrer un wan quand down dans omr-tracker aussi...

Donc OMR peut se charger tout seul de redémarrer un wan? c'est top ca! comment ca?

**Comment by Ysurac** [comment]
J'ai ajouté l'option dans la version beta, dans omr-tracker.

**Comment by JeedHome44** [comment]
ok la je vais regarder plus en détail l'api pour comprendre. ca a l'air assez complexe. tu saurais me donner un exemple d'appel d'info du wan1 par exemple par l'api?

**Comment by JeedHome44** [comment]
En gros, pour le monitoring sur jeedom, c'est juste voir l'état de chaque wan, du serveur et de OMR. et pouvoir agir dessus dans un premier temps. vois si ca marche comme ca déjà
