### ISSUE TITLE
Integrate  latest NodeJs support

### ISSUE THREAD

**Issue by rodhammond** [Ysurac/openmptcprouter#1697]
**Is your feature request related to a problem? Please describe.**
It would be nice to use the hardware crypto accelerator capabilities of my WRT3200ACM router with the openmptcprouter project.

**Describe the solution you'd like**
Integrate nodejs support using [ patrikx3/openwrt-insomnia] as a basis

**Comment by Ysurac** [comment]
I will not add nodejs on OpenMPTCProuter WRT arch. Image size is limited for WRT, I already disable some packages so not possible to add new ones.
