### ISSUE TITLE
VPN is not running, and Can't Contact Server Admin Script

### ISSUE THREAD

**Issue by NoShitSherlockium** [Ysurac/openmptcprouter#1702]
## Expected Behavior

VPN should be working, and it should be able to contact the admin script
## Current Behavior

It refuses to start any of the VPNs (I checked the keys), and says it cannot contact the server admin script, in the log it shows Connection refused on all of the vpns
## Specifications

  - OpenMPTCProuter version: 0.57.3 
  - OpenMPTCProuter VPS version: 0.1024 
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
Did you reboot VPS after install ?
What is the reason indicated in log for the server admin script contact problem ?

**Comment by blade5502** [comment]
Same issue here. Running latest server on Debian 10 and latest x86_64 client.

Logread shows omrvpn as connected
1daemon.notice netifd: Network device 'tun0' link is up
daemon.notice netifd: Interface 'omrvpn' has link connectivity
daemon.notice netifd: Interface 'omrvpn' is setting up now
daemon.notice netifd: Interface 'omrvpn' is now up

Bonding seems to work also, but webinterface states VPN not connected
![OpenMPTCProuter_-_Status_-_LuCI](https://user-images.githubusercontent.com/1372551/112873606-255f7480-90c2-11eb-850b-ccd07c6ad85e.png)
