### ISSUE TITLE
Linksys WRT1900AC V2 support

### ISSUE THREAD

**Issue by cryptofuture** [Ysurac/openmptcprouter#1704]
Comparing with WRT3200ACM would be any different to add support for  WRT1900AC v2?

I'm looking for images for WRT1900AC (V2 in my case). Basically hardware is not much different comparing with WRT3200, but those ones are more common and what important are much cheaper.

Could you give some instructions, how to make build for WRT1900AC V2, based on the process for the WRT3200, or just add its support, as well.

**Comment by Ysurac** [comment]
WRT1900AC have a really small flash (128MB) and a flash layout that give a really small rootfs.
To compile a custom image: https://github.com/Ysurac/openmptcprouter/wiki/Create-image-for-unsupported-platform
