### ISSUE TITLE
Need apk for smartphone

### ISSUE THREAD

**Issue by ssdeol84** [Ysurac/openmptcprouter#1706]
Hi sir thanks for a nice project. I've successfully installed a server which is not giving me access of mptcp with Shadowsocks on smartphone by using Shadowsocks app.

I'm successfully connected with server from client. But that doesn't aggregate my wifi and 4G network. Both my connection are enabled and also I've selected enabled mobile data always active in developers option in settings. But still my 4G data doesn't comes up while wifi is connected.

I request you to please make smartphone apk for android 11. Which can help to connect to mptcp server by both connections.

I've check one github in which there is a app multipath control apk. But that is very old and that is not working on android 11.

Please help me to fix it.

**Comment by Ysurac** [comment]
I don't understand what you mean with your smartphone. OpenMPTCProuter is an OS and it can't work on smartphone directly.

**Comment by ssdeol84** [comment]
Mptcp is already installed on a server and I'm connected to that same server with Shadowsocks client app in smartphone. But Shadowsocks is not having any feature to make both the wifi and 4G connection active. 

I need a patch or a app for smartphone that can get aggregate speed of both wifi and 4G

**Comment by Ysurac** [comment]
This doesn't work that way. OpenMPTCProuter have a server part and a router part.
Linux kernel must be patched to support MPTCP, I don't know if there is any Android phone that have Multipath TCP patch, for iPhone some have multipath tcp support but I don't know if this can work that way.

**Comment by ssdeol84** [comment]
Ok fine I understand bonding will not work on smartphone without patching the kernel.

But I use to connect my smartphone with Shadowsocks vpn server by using Shadowsocks client app.

I've put all the settings on client app but it's not connecting. Can you help me. I guess there is not problem with config file at server end.
This is my app snapshot

![Screenshot_20210410-221250.jpg](https://user-images.githubusercontent.com/69002306/114277775-44f38700-9a4a-11eb-8512-d1df9355ca6f.jpg)

**Comment by andykitcool** [comment]
I think ssdeol84 means that an app is needed to connect with openmptcprouter and aggregate 4G and WiFi signals of mobile phones. I found a similar application--> www.speedify.com , but the disadvantage is that they can only use their servers and need pay

**Comment by ssdeol84** [comment]
Yes but Shadowsocks client app does the same but only need to implement that same way

**Comment by Ysurac** [comment]
Shadowsocks doesn't do aggregation alone (without MPTCP).
For authentication you need to be able to enter a key, not a password. You app doesn't seems to support Shadowsocks key.

**Comment by ssdeol84** [comment]
Can we make changes in script by which we can also give authorisation through password also? In shadowsocks

There are several features in shadowsocks client app by which we can call sever user details by QR code, file and manual.

![Screenshot_20210416-211009.jpg](https://user-images.githubusercontent.com/69002306/115049460-5defb280-9ef8-11eb-9e28-b87009e40f0c.jpg)
