### ISSUE TITLE
Engarde Support

### ISSUE THREAD

**Issue by ricardoiarossi** [Ysurac/openmptcprouter#1710]
Hello guys, I would like to suggest to support Engarde(with wireguard) with OMR.
Ive tried many different configurations with OMR to use omr as pure failover, i dont mind about bandwidth. 
Even tought it worked, it wasnt really very reliable with some packets lost and some times without a clear reason losing tcp connections.
Now i did find this Engarde project, it works flawlessly as failover, not a single packet lost and extremely fast... 
For that reason I were thinking it would be awesome to have this tool integrated with omr so that I could use it on any device without setting up individually. 
Please take a look at their project, im sure you guys are gonna love it because it just works. Also, i saw that there are many other guys using omr looking for failover instead of bandwidth.
Love you guys, thank you for this amazing project. 

Engarde Project: https://github.com/porech/engarde

**Comment by suyuan168** [comment]
@Ysurac is cool~
UDP may be needed for this function~ For example, many broadcast productions now require UDP. But the original glorytun is limited. And the performance is not good. It would be great if you could switch here.
