### ISSUE TITLE
Failed to run openmptcprouter

### ISSUE THREAD

**Issue by blaines** [Ysurac/openmptcprouter#1712]
## Expected Behavior
I tried several of the x86-64 (64-bits) images along with the VPS version running in AWS. I was expecting the setup wizard to configure and connect to the server. I spent several hours attempting to debug the various VPN options, but ultimately was unsure how to configure, start, stop services. The system logs did not present any useful problem solving information, perhaps debugging logs should be enabled?

I hope you find my "failure" to test openmptcprouter helpful. I think an updated tutorial would be quite helpful.

A couple things that might be helpful in the future:
- Can the VPN run or be tested in isolation?
  - Is there any information that could be presented to the user about status or errors?
  - Can the server also show debugging or connectivity information? Perhaps a status tool.
- Can openmptcprouter be used in a basic router configuration? I was unable to achieve basic routing/gateway functionality and I believe the VPN or other services or configuration were preventing basic functionality.

## Current Behavior
When using the wizard I could not figure out how to get VPN connectivity. There were a number of VPN options, and it was unclear which options were required, and there was no debugging information or errors presented.

The OpenMPTCProuter system log appeared okay with only basic connectivity information.

I had a LAN/2xWAN configuration, using three network interfaces on my host. Both WAN presented with an IP address (192.168.88.X, 192.168.77.X), but were unable to establish internet connectivity. The LAN interface could hand out IP addresses via DHCP (192.168.100.X) but I could not connect to OpenMPTCProuter from other hosts.

I noted that although I had configured VPN options, Glorytun, MLVPN, etc using the information from the VPS - No tun0 interface was present on my host.

## Specifications
  - OpenMPTCProuter version: Virtualbox image (EFI): openmptcprouter-v0.57.3-r0+15225-bfc433efd4-x86-64-generic-ext4-combined-efi.vdi.gz (2021/01/05 - 69.34Mo - sha256sum)
  - OpenMPTCProuter VPS version: Linux ip-172-31-13-152 5.4.86-mptcp #1 SMP Mon Jan 4 16:33:37 UTC 2021 x86_64 GNU/Linux  - Running in AWS
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
There is no need to change VPN if you don't want to make some tests. All default configuration should work (Glorytun TCP by default with shadowsocks as proxy).
As you use virtualbox, did you follow virtualbox configuration in the doc ? I make all tests on virtualbox.
To configure you only need to enter informations in the wizard, nothing more.
