### ISSUE TITLE
Port forwarding for shadowsocks 

### ISSUE THREAD

**Issue by rsajadi63** [Ysurac/openmptcprouter#1717]
I have two openmptcprouter one I made it myself another buy from a company I set mine  like the one I bought from the company .the company use port forwardin and when I disable port forwarding check traffic throughout only one wan but when I enable port forwarding traffic throughout two wans so I configure mine similarly that but traffic throughout any wan when I disable port forward traffic throughout only one wan what should I do?i set two interfaces and shadowsocks lib manually

**Comment by rsajadi63** [comment]
![Uploading 80FFC52D-4DF2-4F9B-A6C2-938326824487.jpeg…]()

**Comment by rsajadi63** [comment]
This is my project

**Comment by Ysurac** [comment]
I don't see the image.

**Comment by rsajadi63** [comment]
![6B392FB4-5661-486C-A3DB-7404583914D5](https://user-images.githubusercontent.com/81741857/113619076-c4a9dc00-966d-11eb-9a83-aebf765d55ac.jpeg)

**Comment by rsajadi63** [comment]
This is my project raspberry pi 4 act as sender for video live stream to server with public ip 77.36.23x.xx that on it openmptcprouter script run i connect Rpi4 to Rpi 3 act as router (openmptcprouter )when I send stream to port 1935 server traffic throughout only via one wan i seen on router that I buy used port forward for port 1935 when I disable check box port forward traffic throughout only one wan I set port forward on mine but stream stops!!!

**Comment by rsajadi63** [comment]
![BD6B8A07-A6EF-45DC-8AF0-27F536F1E3D3](https://user-images.githubusercontent.com/81741857/113621274-b01b1300-9670-11eb-89ac-967b6705836a.jpeg)
![6CB9D9F1-89E3-4C4C-B194-33B83AECA5BD](https://user-images.githubusercontent.com/81741857/113621279-b3160380-9670-11eb-8428-42e7725bb073.jpeg)

**Comment by rsajadi63** [comment]
![E4A8A945-1BC5-474E-8850-71A175F5DB58](https://user-images.githubusercontent.com/81741857/113622435-3dab3280-9672-11eb-9c82-29db87910edf.jpeg)

**Comment by rsajadi63** [comment]
![039A486D-03A4-41AC-A977-5C70AB22B078](https://user-images.githubusercontent.com/81741857/113622856-c3c77900-9672-11eb-9186-7dc31961a68a.jpeg)

**Comment by rsajadi63** [comment]
This picture is mine

**Comment by rsajadi63** [comment]
What should I do?

**Comment by Ysurac** [comment]
I don't really understand what you try to do with the port forward.

**Comment by rsajadi63** [comment]
I want send data by my client that connected by Ethernet port  to my router (openmptcprouter )that have two usb 4g modem toward my server on port 1935 and I want openmptcprouter router close all other port and ip except server’s IP (77.36.23x.xxx)and port 1935

**Comment by Ysurac** [comment]
Your WAN firewall zone is empty in screenshots. Did you set any WAN ?

**Comment by rsajadi63** [comment]
I set everything up as I bought it

**Comment by rsajadi63** [comment]
Data send toward server only via one wan

**Comment by rsajadi63** [comment]
![59B9E7DB-4CDC-455D-BC88-C9E0A9AD76DC](https://user-images.githubusercontent.com/81741857/113760940-19ac2780-972c-11eb-83bb-c8500d583eb6.jpeg)

**Comment by rsajadi63** [comment]
If I send you kernel log and and system log you can see how it is set to work properly

**Comment by Ysurac** [comment]
WANs are in WAN firewall zone ? because it's not the case in screenshots.
What is the bandwidth of each wan ? Because WAN are used based on latency priority. So both WANs are used when lowest latency wan is saturated.

**Comment by rsajadi63** [comment]
For WANs are in WAN firewall zone I should where check?

**Comment by Ysurac** [comment]
In Network->Firewall, by editing zone and checking what interfaces are covered.
In your tests you don't seems to reach 4Mb/s on a WAN, so this can be logic.

**Comment by rsajadi63** [comment]
I set all the options like the one that works right and came to the conclusion that the problem is here
![D2604863-FF1F-485C-91EB-D258E844758F](https://user-images.githubusercontent.com/81741857/113767681-38162100-9734-11eb-91dc-b822f4ef58f2.jpeg)

**Comment by rsajadi63** [comment]
When I deactivate the checkboxes of both modems (mine and the one I bought) traffic throughout via on wan but when I active the checkboxes of both modem traffic divided between two wan for one I bought and work well but for mine traffic stop !!!!!!

**Comment by Ysurac** [comment]
Your rules mean that you forward traffic that enter port 1935 to port 2003 of the router.
Same for port 5001.

**Comment by rsajadi63** [comment]
The server on port 1935 is listening
I do not know port 5001 what it is and not important I need only port 1935

**Comment by rsajadi63** [comment]
Traffic enters the modem via LAN and must reach port 1935 of the server via a dual SIM card.

**Comment by rsajadi63** [comment]
They did not use the wizard and only set the shadowsocks

**Comment by rsajadi63** [comment]
One point, they have used version 54.7 could it be the cause of the problem ???

**Comment by rsajadi63** [comment]
Where is config file?

**Comment by Ysurac** [comment]
In System->OpenMPTCProuter, tab "Show all settings"
or via SSH in /etc/config
or via System->Backup and "Generate archive"

**Comment by rsajadi63** [comment]
Ok I compare them

**Comment by rsajadi63** [comment]
Tanks for your help my problem solved
