### ISSUE TITLE
IP V4 forwarding off by default ?

### ISSUE THREAD

**Issue by onemarcfifty** [Ysurac/openmptcprouter#1718]
## Expected Behavior

On a "naked" OpenMPTCPRouter install (i.e. no VPS configured so far) the expected behavior would be that the router acts like a "normal" OpenWrt Router, i.e. routes traffic from LAN to WAN

## Current Behavior

IP V4 forwarding is off, i.e. no internet connection from the LAN side

## Possible Solution

In a shell, type
`echo "1" >/proc/sys/net/ipv4/ip_forward
`
## Steps to Reproduce the Problem

  1. Install OpenMPTCPRouter, but don't configure VPS yet
  2. Connect a LAN client
  3. Try to ping a public IP, e.g. 8.8.8.8

## Specifications

  - OpenMPTCProuter version: v0.57.3 r0+15225-bfc433efd4 
  - OpenMPTCProuter VPS version: N/A
  - OpenMPTCProuter platform: WRT3200ACM

**Comment by Kalimeiro** [comment]
in System -> OpenMPTCProuter -> Wizard, you need to "disable server" called VPS by default or delete it (even if you haven't setup a vps)

**Comment by onemarcfifty** [comment]
Hi @Kalimeiro, many thanks - I had disabled the VPS - in fact that was the first thing I tried. I had not deleted it however. Still I am struggling to understand why IPV4 forwarding is off by default on a router.

**Comment by Ysurac** [comment]
IPv4 forwarding is enabled by default. At least it should and seems to be on a fresh x86_64 image.

**Comment by onemarcfifty** [comment]
I'll double check as soon as I can.
