### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by rstanislav** [Ysurac/openmptcprouter#172]
Hello! Something changed and build failing, i know you said that you use CI to test builds, but still maybe something missed.

Applying /root/openmptcprouter/rpi2/source/target/linux/brcm2708/patches-4.14/0999-cpu_errata_include.patch using plaintext:
patching file arch/arm64/kernel/cpu_errata.c
Hunk #1 FAILED at 16.
1 out of 1 hunk FAILED -- saving rejects to file arch/arm64/kernel/cpu_errata.c.rej

**Comment by Ysurac** [comment]
It's when the kernel is updated from OpenWRT. I use cache, so I don't update kernel at each release.
