### ISSUE TITLE
Shorter default DHCP leases - how?

### ISSUE THREAD

**Issue by hairy-dog** [Ysurac/openmptcprouter#1722]
If I set a fixed IP for a device on the lan, I can set a lease time, but all the automatic leases are set to 12 hours. 
I'd like to reduce this to 2 hours (at least for a little while). 
How can I do this?

**Comment by Ysurac** [comment]
In Network->Interfaces, edit LAN, "DHCP server" tab

**Comment by hairy-dog** [comment]
Thank you! Of course, the first time I tried that, I forgot to click the second Save button, so it didn't work. But then I got it right!
