### ISSUE TITLE
Point to point stream and aggregation with shadowsocks libev

### ISSUE THREAD

**Issue by rsajadi63** [Ysurac/openmptcprouter#1724]
I want send video stream by two USB modem for increases bandwidth (aggregation )I install openmptcprouter on raspberry pi with two USB modem plugged as router .
I have a server in another point run openmptcprouter script and connected to internet with high speed line . 
I use a PC as video sender .
I want video sender(PC) send video stream to my server with IP 77.36.23.xx and port 1935 .

I want the PC to only be able to send to my server and only the 1935 port( no other IP or port )and not be able to access the internet
 
 I use shadowsocks libev but traffic throughout only one wan!!!
Why???

**Comment by Ysurac** [comment]
It's the same as #1717
