### ISSUE TITLE
Design personal HTML pages 

### ISSUE THREAD

**Issue by rsajadi63** [Ysurac/openmptcprouter#1730]
## Current Behavior

It is possible manipulation of HTML pages ?
Is 192.168.100.8/cgi-bin/luci/admin in access and is it possible manipulation ?

## Specifications

  - OpenMPTCProuter version: 57.3
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter platform: RPI3

**Comment by Adorfer** [comment]
Yes!

**Comment by rsajadi63** [comment]
> Yes!

How can I ? Please describe the steps

**Comment by Adorfer** [comment]
edit files in /www/ on the OMR.

**Comment by rsajadi63** [comment]
> edit files in /www/ on the OMR.

Permission is denied!!

**Comment by Adorfer** [comment]
please use the template.

**Comment by rsajadi63** [comment]
> please use the template.

What is template?

**Comment by Adorfer** [comment]
https://github.com/Ysurac/openmptcprouter/issues/new/choose

**Comment by rsajadi63** [comment]
I use template please help me

**Comment by rsajadi63** [comment]
How can I change ‘openMPTCProuter’ that displayed at top of all pages where background color is blue?

**Comment by rsajadi63** [comment]
![BA29C63E-9799-4B8A-ACC4-62747E008822](https://user-images.githubusercontent.com/81741857/114230661-a8b87a00-998e-11eb-9d57-9a63e509bf4e.jpeg)

**Comment by Ysurac** [comment]
Find yourself in openmptcprouter-feeds repo, I will not help on this as it's not related to OpenMPTCProuter operation.
