### ISSUE TITLE
USB Stick for my windows PC

### ISSUE THREAD

**Issue by dooley1981** [Ysurac/openmptcprouter#1731]
What is the best USB stick for my windows computer to install the software on? I have acheap one now that was $8 for 32GB. Is it a benifit getting a more powerful stick?

**Comment by Ysurac** [comment]
32GB is not enough for x86_64 version.
But I don't understand when you say windows PC, OpenMPTCProuter is an OS so it can't run under windows, the only way to run it "under windows" is to use a VM.

**Comment by dooley1981** [comment]
I already have this setup on my pc. It's booting from the USB stick, not windows. You didn't, I do have a 64GB stick but my question is, will I get better performance with a faster stick.

**Comment by Ysurac** [comment]
No. OpenMPTCProuter doesn't read/write a lot to disk (and yes it's GB, I don't know why I was in MB).

**Comment by dooley1981** [comment]
Okay thanks. What's the minimum space needed on the stick?

**Comment by Ysurac** [comment]
About 1GB

**Comment by dooley1981** [comment]
Okay thanks
