### ISSUE TITLE
One USB modem connected but in status show two 

### ISSUE THREAD

**Issue by rsajadi63** [Ysurac/openmptcprouter#1737]
Look at this picture
![D2A87AA7-541A-4CE6-B926-7CBC99CF1C09](https://user-images.githubusercontent.com/81741857/114154414-a0802080-9935-11eb-9a52-e2c97ab92584.jpeg)
I connect only one USB modem dongle but state of wan2 is connected 
Operator is irancell !!!!!!

**Comment by Ysurac** [comment]
You really need to use template, for that doesn't open issue as question.
wan2 have a gateway that is same as wan1, it's why there is same info.
One interface must be set as multipath master.

**Comment by rsajadi63** [comment]
For use template I should delete all things are between <!   > and write mine question??

**Comment by Ysurac** [comment]
When you open an issue, you don't need to delete  (it's comments, they are not displayed), only put what you want under the titles like "## Expected Behavior" where you put what you expect,...

**Comment by rsajadi63** [comment]
Open this page for me when I want create a new issue 
![5D94FA8A-0D16-46F1-A30D-9B01FCBA192F](https://user-images.githubusercontent.com/81741857/114160947-b9d89b00-993c-11eb-9b4d-56c61bd1be90.jpeg)

**Comment by Ysurac** [comment]
Because it's not the correct type. Question are for "Ask a general question, not related to an OpenMPTCProuter install" as indicated.

**Comment by rsajadi63** [comment]
I should change type of request for example ‘help wanted’ ??

**Comment by Ysurac** [comment]
to get the template yes.
For issues already open that you want to add template, you can copy the template and edit your already existing issues with that.

**Comment by rsajadi63** [comment]
I done please help me for issues  #1732
