### ISSUE TITLE
Disable luci (web browser GUI)

### ISSUE THREAD

**Issue by rsajadi63** [Ysurac/openmptcprouter#1738]
## Expected Behavior
When clients type IP address of router in browser app GUI appears 

## Current Behavior
I want disable display luci for clients .
Is it possible??

## Specifications

  - OpenMPTCProuter version: 57.3
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter platform: 
RPI3

**Comment by suyuan168** [comment]
yes

**Comment by rsajadi63** [comment]
> yes

How can I do?

**Comment by hairy-dog** [comment]
Not tell clients the login password?
