### ISSUE TITLE
create read only to writable

### ISSUE THREAD

**Issue by rsajadi63** [Ysurac/openmptcprouter#1739]
## Current Behavior
file cascade.css in path /www/luci-static/openmptcprouter/cascade.css is read only .
how can i make it writable?

## Specifications

  - OpenMPTCProuter version: 57.3
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter platform: RPI3

**Comment by Adorfer** [comment]
it's writable for root. 
If not, it's probably your fs ist damaged.

**Comment by rsajadi63** [comment]
I log in as root but file is read only 
what should I do 
chmod 577 is correct?

**Comment by Ysurac** [comment]
As @Adorfer said, your filesystem is read only or damaged.
Backup config and reinstall router part.
