### ISSUE TITLE
MPTCTP bandwitdh page

### ISSUE THREAD

**Issue by ThibautBascoulergue** [Ysurac/openmptcprouter#174]
## Expected Behavior

  When i go to MPTCTP bandwitdh page, i see an error in system log.

## Actual Behavior

think a bug :)

## Steps to Reproduce the Problem

  1. Go to Network, MPTCTP and Bandwidth page

## Specifications

  - OpenMPTCProuter version: (36.2)
  - OpenMPTCProuter VPS version: (0.50)
  - OpenMPTCProuter platform: (x86_64 vmware)

![image](https://user-images.githubusercontent.com/42678960/45717525-85443e80-bb9a-11e8-88d8-12b817d8d79c.png)

**Comment by Ysurac** [comment]
Same as #166.
Seems to be not fixed... This will be fixed in next release.
