### ISSUE TITLE
Change title openmptcprouter on all pages

### ISSUE THREAD

**Issue by rsajadi63** [Ysurac/openmptcprouter#1744]
## Expected Behavior
openMPTCProuter shows on all pages where background color is blue

## Current Behavior
How can I change it ??

## Specifications

  - OpenMPTCProuter version: 57.3
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter platform: RPI3 a

**Comment by rsajadi63** [comment]
![F310C639-6C85-4BC5-A377-E458FA7BF3E0](https://user-images.githubusercontent.com/81741857/114258515-2ce51e80-99dc-11eb-808a-b971adfa1525.jpeg)

**Comment by Ysurac** [comment]
Please stop opening issues on customization. It's not related to OpenMPTCProuter operation.

**Comment by rsajadi63** [comment]
what should I do for customization I need that

**Comment by rsajadi63** [comment]
https://www.openmptcprouter.com/commercial
You mentioned it here

**Comment by Adorfer** [comment]
This is not how it works. 
either you understand why the linked "commercial" page applies for your request and act accordingling or you have to figure it out yourself. 
in other words: This is NOT a valid issue for this project.
