### ISSUE TITLE
Cisco Anyconnect not working 

### ISSUE THREAD

**Issue by ragefan** [Ysurac/openmptcprouter#1748]
## Expected Behavior
Connection to enterprise VPN with Cisco Any connect shall work Through openmptcprouter at home

Required config 

Protocol | Cisco AnyConnect Client Port
-- | --
TLS (SSL) | TCP 443
SSL Redirection | TCP 80
DTLS | UDP 443
IPsec/IKEv2 | UDP 500, UDP 4500

## Current Behavior

It fails to connect with v0.57.3 and latest beta of v.0.58

## Possible Solution

None? 
Was working with a successive version (intermediate build) to 0.57.3 and before 0.58 beta 1

## Steps to Reproduce the Problem

  1.start Cisco any connect client
  2.wait
  3.connection fails

## Specifications

  - OpenMPTCProuter version: 0.57.3
  - OpenMPTCProuter VPS version: v. 0.1024
  - OpenMPTCProuter platform: rpi3

**Comment by ragefan** [comment]
Seems to be due to MTU default mis-configuration.
Ping & connection is ok now with a lower MTU (default was 1500) but connection through IPSEC VPN is very very bad and not usuable.

**Comment by ragefan** [comment]
Tested with 0.58rc1 same results.
Using omrbypass on one 4g connection only does not solve the issue so not linked to vps. Using same connection without omr through shared wifi is working fine.

**Comment by docderwood** [comment]
Same issue for me.

**Comment by Ysurac** [comment]
Difficult to tests for me as I have no VPN using Cisco Anyconnect.

**Comment by ragefan** [comment]
How can we help?

**Comment by Ysurac** [comment]
By providing a Cisco Anyconnect access ;)
Else, did you try to use V2Ray as proxy in System->OpenMPTCProuter, "advanced settings" checkbox ?

**Comment by ragefan** [comment]
I will test that. Is there some logs we could collect?

**Comment by ragefan** [comment]
V2ray is already activated by default on my side

**Comment by ragefan** [comment]
Now Working with v.0.85.5...
