### ISSUE TITLE
Balancing Network Traffic

### ISSUE THREAD

**Issue by nibirrayy** [Ysurac/openmptcprouter#1751]
I have currently 4 modem connected to my raspberry pi 4 which is running openmptcprouter. The problem is when I stress the network only one line is used to transfer most of the date. Is there is a way to balance this out.

**Comment by Ysurac** [comment]
Usage of WANs is based on latency.

**Comment by nibirrayy** [comment]
is there is a way to turn that off. I am using round robin ans still it uses one connection

**Comment by Ysurac** [comment]
I will add an option to enable true round robin in next release so it will not fill the congestion window on all subflows.

**Comment by pbapba512** [comment]
True round robin can be a really usefull feature, for me it can be a big help for the livestreaming usecases! :)
The another big wish from me is the better 4G USB modem handling, with the .56 it worked well, but with .57 its broken (at least for me and with my Huawei sticks). So I'm really exciting and waiting for the .58 finl release with the new features. 

Thank you for your work, Ysurac!

**Comment by gsxryan** [comment]
Would that be 58/59 release?  will the current round robin option be changed, or will we look for a new option?

**Comment by Ysurac** [comment]
The option is "Fill the congestion window on all subflows for round robin" that should set to false for true round robin, in Network->MPTCP in v0.58*

**Comment by nibirrayy** [comment]
I am just commenting just keep this thread alive as the problem is still not completely fixed and I will like to give an update on the issue

currently round robin still heavily rely to latency from what I see on my day to day use. I have two LTE modem that I am combining and both have different providers.

Most of the time the provider which has less latency is still used to transfer more traffic instead of using pure round robin
I now have switched to zerotier to fixed this and from version 1.6.5 they also have multipathing support.

They have some really awesome way to force round robin by specifying parameters on asymmetric connections
check this link for more info about that
https://docs.zerotier.com/zerotier/multipath/#asymmetric-links

**Comment by r2d2land** [comment]
> I now have switched to zerotier to fixed this and from version 1.6.5 they also have multipathing support.

Are you using ZT with OMR?

If so, where would you apply the configuration.

If not,

Ysurac…can the ZeroTier package be added to the current release thru the gui without breaking OMR?

thanks
