### ISSUE TITLE
port forwarding problem

### ISSUE THREAD

**Issue by dtony83** [Ysurac/openmptcprouter#1762]
Good day,

I followed the documentation at https://github.com/Ysurac/openmptcprouter/wiki/Port-forwarding to open successfully port 80 or 22 on the router but if I try to open for example port 21 or another custom one, tools like https://www.yougetsignal.com/tools/open-ports/  or a telnet command say that the port is closed.

Any suggestion? Thanks.

**Comment by Ysurac** [comment]
All ports work the same way, so if you can open port 80 then this will work for port 21.
You can check Debug section of this wiki page.

**Comment by dtony83** [comment]
> All ports work the same way, so if you can open port 80 then this will work for port 21.
> You can check Debug section of this wiki page.

thanks for the reply but the issue is still ongoing; ![Immagine](https://user-images.githubusercontent.com/82816988/115481959-e69a8580-a24d-11eb-8a9a-f8795ca2423d.png)

port 80 open, port 3389 (or another one except 443) closed

i missed only the tcpdump step
