### ISSUE TITLE
Run openMPTCProuter on a laptop for testing?

### ISSUE THREAD

**Issue by oettinger31** [Ysurac/openmptcprouter#1766]
## Expected Behavior
Installation of openmptcprouter on a HP 635 Notebook PC with AMD E-350 (2x1,6GHz), single LAN port for testing.

## Current Behavior
I have not yet done anything with openmptcprouter. Can I install openmptcprouter on my above mentioned laptop for testing before buying dedicated hardware for that? Is the single Ethernet port an issue?

## Specifications

  - OpenMPTCProuter version: none
  - OpenMPTCProuter VPS version: none
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
You can install it on a laptop. You need to dd the image to hard disk or to an USB key.
Single Ethernet port is not an issue, MacVLAN is used to create some "virtual" interfaces.

**Comment by vinceducat** [comment]
Hello i have OMR with laptop and usb key work nice

**Comment by oettinger31** [comment]
Thank, got the laptop working as OMR :)
