### ISSUE TITLE
How to configure tap0 to work with OpenMPTCProuter ?

### ISSUE THREAD

**Issue by al5sources** [Ysurac/openmptcprouter#1768]
Hi, 
I'm attempting to bridge interfaces on OpenMPTCProuter and on VPS to run through it the l2 frames,
(to make a vlan)
I want to do something like 

   debian2 %# brctl addbr br0
   debian2 %# brctl addif br0 tap0
   debian2 %# brctl addif br0 eth1
   debian2 %# ip link set tap0 up
   debian2 %# ip link set br0 up

on both sides

So how should I use tap0 instead of tun0 to make a bridge ?

**Comment by Ysurac** [comment]
You need to set a new VPN with tap instead of tun. It's not supported by default.
OpenVPN can use tap or wireguard (but wireguard is not available by default on current stable release)
