### ISSUE TITLE
Zalando, MyCanal, SuperU, some websites are inaccessible

### ISSUE THREAD

**Issue by siliteofr** [Ysurac/openmptcprouter#1771]
Hi,

I am using an OVH VPS (the last OMR version and a VM locally), everything work great except when i try to browse some website.

My VPS IP is like this 51.38.XXX.XXX

And i can't login to myCanal (need to log on one of my access and go back to OMR after login), i show theses errors :

Access Denied
You don't have permission to access "http://pass.canal-plus.com/IdPOAuth2/auth/mycanal?" on this server.
Reference #18.8d73dd58.1619074161.7a0447

Access denied
This website is using a security service to protect itself from online attacks.

Ray ID: 643cea0b5b7fee2f
Timestamp: 2021-04-22 06:49:48 UTC
Your IP address: 51.38.XXX.XXX
Requested URL: www.coursesu.com/drive/home?gclid=EAIaIQobChMIjsbNraGR8AIVw4jVCh0SOAXnEAAYASAAEgJkP_D_BwE
Error reference number: 1020
Server ID: FL_19F261
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36 OPR/75.0.3969.171

Did you have another recommanded VPS?

**Comment by Ysurac** [comment]
Same sites also block Scaleway IPs and Firstheberg.
You can use omr-bypass to bypass VPS for these sites.

Small VPS providers can be less blocked if they have their own IP range, you can check on https://github.com/Ysurac/openmptcprouter/wiki/Install-or-update-the-VPS for a tested list.
