### ISSUE TITLE
Need to add ffmpeg and nginx rtmp lib so that we can add encoding part in router by add usb 3.0 capture card

### ISSUE THREAD

**Issue by ssdeol84** [Ysurac/openmptcprouter#1777]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Need bonding encoder by which we can Aggregation bandwidth with rtmp stream.
H.264

**Describe alternatives you've considered**

Enhance the bonding feature
Like other bonding encoders work like liveU solo,tvu and other solutions

**Additional context**

Please add this feature.

**Comment by Ysurac** [comment]
I don't know what you want exactly, but many packages are available in System->Software.

**Comment by suyuan168** [comment]
Currently, no consideration is given to embedding the video coding part in OMR.
OMR should only be a router.
If necessary, I will consider it later.

**Comment by Adorfer** [comment]
please do not add too many bells and whistles aside "beeing a mptcprouter".
