### ISSUE TITLE
Tuto pour création Vlan

### ISSUE THREAD

**Issue by guillaumed24** [Ysurac/openmptcprouter#1784]
Bonjour,

Est-il possible d'avoir un coup de main pour créer un vlan avec son propre dhcp ?

Merci.

**Comment by Ysurac** [comment]
Bonjour,
Pour créer les VLANs, il faut définir une nouvelle interfaces, dans Réseau->Interfaces, et utiliser en interface physique "eth0.200" pour le vlan 200 sur l'interface physique eth0.

**Comment by guillaumed24** [comment]
Ok et eth1.200 pour l'interface eth1 ?
J'utilise une ancienne overthebox. Comment je peux identifier les ports eth1.2.3.4..... ?

**Comment by Ysurac** [comment]
Oui exactement.
Pour identifier les ports, possible en branchant un câble sur chaque port un à un et en regardant les logs pour voir qui devient up.

**Comment by guillaumed24** [comment]
Les logs > états : journaux système ou un autre ?

**Comment by Ysurac** [comment]
Oui.
Il y a aussi via SSH sur le routeur, ```ethtool eth2``` avec l'information "Link detected".

**Comment by guillaumed24** [comment]
Parce que dans les logs quelque soit le port j'ai ca : 

Mon Apr 26 10:56:39 2021 daemon.info dnsmasq-dhcp[21729]: DHCPDISCOVER(eth0) 192.168.40.140 84:78:ac:a5:****
Mon Apr 26 10:56:39 2021 daemon.info dnsmasq-dhcp[21729]: DHCPOFFER(eth0) 192.168.40.140 84:78:ac:a5:****
Mon Apr 26 10:56:39 2021 daemon.info dnsmasq-dhcp[21729]: DHCPREQUEST(eth0) 192.168.40.140 84:78:ac:a5:****
Mon Apr 26 10:56:39 2021 daemon.info dnsmasq-dhcp[21729]: DHCPACK(eth0) 192.168.40.140 84:78:ac:a5:****

**Comment by Ysurac** [comment]
Si l'interface eth0 a le DHCP d'activer, normal. Le serveur DHCP est activé par défaut sur l'interface LAN.
