### ISSUE TITLE
Question about Perf from 2 different arch

### ISSUE THREAD

**Issue by vinceducat** [Ysurac/openmptcprouter#1792]
x64 i have two differente arch

1 new
Modèle：Quanmax Inc. QutePC-4100
Architecture：Intel(R) Core(TM) i3-3227U CPU @ 1.90GHz
Version du micrologiciel：openmptcprouter v0.57.3 r0+15225-bfc433efd4
ethernet card e1000e 
4Go RAM

2 old
Modèle：Packard Bell EasyNote LJ65
Architecture：Pentium(R) Dual-Core CPU T4400 @ 2.20GHz
Version du micrologiciel：openmptcprouter v0.57.3 r0+15225-bfc433efd4
ethernet Tigon 3
8Go  

the 1 arch seems to be less performante, for me is strange is the problem could come from ethernet card processor or RAM.

**Comment by Ysurac** [comment]
Yes it's strange. Maybe the higher frequency by core of arch2 help.

**Comment by vinceducat** [comment]
not a problem of ethernet card for you ?

**Comment by vinceducat** [comment]
other question on the arch1 i have 2 eth port can i put on the second (eth1] my adsl gateway in place of "macvlan" on the eth0

**Comment by Ysurac** [comment]
Yes you can use eth1 for any connection directly.

**Comment by vinceducat** [comment]
Just need to change in the wizard from MacVlan eth0 to normal Eth1... or need to creation interface first ?

**Comment by Ysurac** [comment]
Just need to change yes.

**Comment by vinceducat** [comment]
Thanks wiil try ;-)

**Comment by vinceducat** [comment]
seems to work but i have [   17.468749] r8169 0000:02:00.0 eth1: No native access to PCI extended config space, falling back to CSI
