### ISSUE TITLE
Want to access GUI of clients routers in VPS

### ISSUE THREAD

**Issue by ssdeol84** [Ysurac/openmptcprouter#1805]
## Expected Behavior

Can we access the GUI of all the connected mptcp routers on VPS ..also is there any command. By which we can know how many client routers are connected to this VPS?
## Specifications

  - OpenMPTCProuter version: 
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter platform:

**Comment by Ysurac** [comment]
If you use one user, only one router can connect on VPS without issues.

**Comment by ssdeol84** [comment]
Can we access the router remotely by loging on VPS server ??

**Comment by Ysurac** [comment]
Via the VPN and if port 80/443 is open on router.
