### ISSUE TITLE
Multi VPS

### ISSUE THREAD

**Issue by MTSmhas** [Ysurac/openmptcprouter#1807]
Hi i have found a problem with the multi IP.
With Only 2 IP's all work okay.
But if i use three or four IP's, with the correct forward and all settings, all maschines have the same external ip.

Can you help me?

**Comment by Ysurac** [comment]
Still not the template. I need releases versions of router, vps, arch,...

**Comment by MTSmhas** [comment]
openmptcprouter-v0.57.3-r0+15225-bfc433efd4-x86-64-generic-ext4-combined-efi.img.gz

**Comment by MTSmhas** [comment]
< OpenMPTCProuter VPS 0.1024 >

**Comment by Ysurac** [comment]
I think this should be fixed in v0.58, you can try v0.58rc2 here: https://github.com/Ysurac/openmptcprouter/issues/1619
