### ISSUE TITLE
Vps ne se reconnecte pas automatiquement en cas d'extinction 

### ISSUE THREAD

**Issue by montana013** [Ysurac/openmptcprouter#1808]
Bonjour,

J'ai un soucis si j'ai une coupure du raspberry et du switch lorsqu'il redémarre il ne se reconnecte pas automatiquement sur internet.
Je suis obligé à chaque fois de suivre cette procédure pour retrouver une connexion internet sur le routeur 4g-5g.
-1 débrancher du switch le rj45  allant vers le  raspberry 
-2 éteindre le switch et le raspberry (le routeur 4g reste allumé même si je le relance même soucis )
-3 attendre  15s que le raspberry se lance et que switch fonctionne 
-4 re brancher sur le switch le rj45 du raspberry et la internet fonctionne sur wifi et rj45  du routeur 4g

Du coup cela demande à chaque fois une action manuelle si le courant est coupé ou si le relance le vps via interface openmptcprouter.. plutôt embêtant si je dois relancer mon installation via internet (j'ai une prise connecté qui me permet de relancer mon installation en cas de problème )
Est ce que c'est normal ? Une configuration à faire peut-être sur openmptcprouter pour qu il se reconnecte au routeur 4g automatiquement?
Merci

**Comment by Ysurac** [comment]
OpenMPTCProuter se reconnecte automatiquement en cas de coupure.
Tout est en ethernet ?
Il faudrait vérifier les IPs sur le routeur 4G quand il y a un soucis.

**Comment by montana013** [comment]
Voici ma configuration 

<a href="https://ibb.co/FJ1ztZJ"><img src="https://i.ibb.co/DkFQnck/Screenshot-20210507-235115-Chrome.jpg" alt="Screenshot-20210507-235115-Chrome" border="0"></a>
<a href="https://ibb.co/g66VzNS"><img src="https://i.ibb.co/PttQwKc/Screenshot-20210507-234926-Chrome.jpg" alt="Screenshot-20210507-234926-Chrome" border="0"></a>
<a href="https://ibb.co/2NzWr1v"><img src="https://i.ibb.co/RyXYKk3/Screenshot-20210507-234751-Chrome.jpg" alt="Screenshot-20210507-234751-Chrome" border="0"></a>
<a href="https://ibb.co/F3SrVBS"><img src="https://i.ibb.co/9gFDtqF/Screenshot-20210507-234948-Chrome.jpg" alt="Screenshot-20210507-234948-Chrome" border="0"></a>

**Comment by montana013** [comment]
J'ai changé IP du routeur 4G  en 192.168.100.11  (au lieu de 192.168.8.1) mais cela ne change rien si j'éteins  mon raspberry et mon routeur 4g ainsi que switch , openmptcprouter ne detecte pas internet  quand je rallume tout.
 je suis connectés en rj45  au pc ou en wifi sur la tablette mais sans connexion internet et sans possiblé de me connecter a l'interface openmptcprouter  au 192.168.100.1

**Comment by Ysurac** [comment]
Et la connexion au routeur fonctionne ?
J'avoue que j'ai pas trop compris ton architecture du coup...

**Comment by montana013** [comment]
Oui biensur tout est rallume le routeur 4g est connecté  à l,antenne mais j'ai l'impression que openmptcprouter ne joue pas son rôle de DHCP 
J'ai fait un schéma de mon installation en bas à droite de la capture 
<a href="https://ibb.co/cQDZwb9"><img src="https://i.ibb.co/GRc89sD/Screenshot-20210509-220139-Chrome.jpg" alt="Screenshot-20210509-220139-Chrome" border="0"></a>
