### ISSUE TITLE
Bandwidth problem

### ISSUE THREAD

**Issue by Pokpok-sbo** [Ysurac/openmptcprouter#1814]
Hi all,
I've been testing Openmptcp for 1 week. I am very happy with the stability and the failover.
On the other hand, for the aggregation of the connections I have the impression that I am losing bandwidth.
I tested that with only one connection on the router. Here are the tests with the **omr-test-speed** and **omr-test-speed eth3** commands:
![image](https://user-images.githubusercontent.com/54711277/117549308-5bd5cb00-b042-11eb-93b9-d8a5b9c37fd2.png)

![image](https://user-images.githubusercontent.com/54711277/117549295-3779ee80-b042-11eb-99b1-ef1bb567d5ab.png)

We can see the two consecutive tests and the difference
![image](https://user-images.githubusercontent.com/54711277/117549254-fda8e800-b041-11eb-8140-732872af2c53.png)

What should I modify to correct this problem?

## Specifications

  - OpenMPTCProuter version: openmptcprouter v0.58rc2 r0+16336-b36068d35d
  - OpenMPTCProuter VPS version: 5.4.86-mptcp 0.1024
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
Everything is green in status page ? You seems to have only one interface used.

**Comment by Pokpok-sbo** [comment]
Yes I kept only one connection to see the difference

**Comment by Adorfer** [comment]
you shoud describe: 
  -  what the scenario is 
      - what OMR
      - what VPS
      - what WAN
  - what you would expect as result
  - the the actual result is (which you are disappointed with, which of the values)

**Comment by Pokpok-sbo** [comment]
I'm sorry, but it seems to me that I indicated the scenario at the bottom of my message.

Specifications
OpenMPTCProuter version: openmptcprouter v0.58rc2 r0+16336-b36068d35d
OpenMPTCProuter VPS version: 5.4.86-mptcp 0.1024
OpenMPTCProuter platform: x86_64

I just don't understand why my connection is around 50 Mbps and that when we go through the vpn we are at 10. So I think there is a parameter wrongly set. I'm just asking for help

**Comment by Adorfer** [comment]
the chart on the bottom of you issue say 66MBit/s, as WAN3 and as total, whic is perfect for a line specified as 50MBit/s!

**Comment by Ysurac** [comment]
@Pokpok-sbo You use 0.58rc2, you need to update also VPS with snapshot script and reboot to use new kernel.
Can you make a screenshot of OpenMPTCProuter status page and check in same bandwidth page what you have during an aggregation speed test ?

**Comment by Pokpok-sbo** [comment]
Hi,
to be sure I didn't forget or did anything wrong, I started all over again.
Here is the installation of the **vps**:
![instaserver1](https://user-images.githubusercontent.com/54711277/117563568-8ca01980-b0af-11eb-802a-4842de43292e.jpg)
omr-test-speed on **vps** :
![instaserver2](https://user-images.githubusercontent.com/54711277/117563620-c3762f80-b0af-11eb-8467-98cb9071f908.JPG)
Here is the installation of the **router**:

**Comment by Pokpok-sbo** [comment]
Hope this will help you find the problem.

I have the impression that there is really something limiting the bandwidth

**Comment by Ysurac** [comment]
You get 29.1Mo/s with omr-test-speed, so 29.1*8=232.8Mb/s. You should test more than 40s because this seems higher than what your connection can do.
In your speedtest I see a really big latency, there is a problem somewhere.

**Comment by Pokpok-sbo** [comment]
I did omr-test-speed on the **OVH vps** because I thought it was the origin of slowing down. We can see that it does not come from OVH.

Latency is normal for me. I am in Madagascar. The last test has roughly the same latency and the bandwidth is 7 times greater

**Comment by Ysurac** [comment]
You can try omr-iperf, this should test speed between router and VPS.

**Comment by Pokpok-sbo** [comment]
omr-iperf :
![Iperf Router](https://user-images.githubusercontent.com/54711277/117566405-258a6100-b0bf-11eb-8edf-bea6d00c1eba.png)

**Comment by Ysurac** [comment]
So speed between router and VPS is not really great.
You can try, in the wizard, in "advanced settings" checkbox to disable proxy and vpn, and try this test again.
If the speed is correct, try to enable only the proxy and try with v2ray.

**Comment by Pokpok-sbo** [comment]
v2ray
![image](https://user-images.githubusercontent.com/54711277/117567099-186f7100-b0c3-11eb-8e42-9dfcbdbe1785.png)

**Comment by Pokpok-sbo** [comment]
I did another test by plugging in directly to my box and doing a speedtest to OVH Gravelliles (my VPS host). Result : the bandwidth is pretty good. I really do not understand :(

![image](https://user-images.githubusercontent.com/54711277/117567792-7ea9c300-b0c6-11eb-82d0-1ff2cedb484b.png)

**Comment by Ysurac** [comment]
You should get a good speed between router and VPS...
You can try to change TCP congestion in Network->MPTCP, try BBR2 for example.

OVH speed test server can be optimized for speed test, no idea.

**Comment by Pokpok-sbo** [comment]
Hi !
After a good break! And a restart works much better.
![image](https://user-images.githubusercontent.com/54711277/117582948-4b3e5700-b10d-11eb-913d-e5f1b39e8d7b.png)

![image](https://user-images.githubusercontent.com/54711277/117583089-e8998b00-b10d-11eb-9160-6f867d48d6b1.png)

I only set Vray2 proxy and TCP congestion in Network-> MPTCP> BBR2

Many thanks for your help!

**Comment by Adorfer** [comment]
can you execute yabs.sh and post the result. 
is perhaps AES-NI disabled in the VPS?
https://github.com/masonr/yet-another-bench-script
