### ISSUE TITLE
VPS Scripts Error (Server issue resolved)

### ISSUE THREAD

**Issue by GTiDon** [Ysurac/openmptcprouter#1817]
Hello

I have tried the VPS setup script on Debian and it fails.
Then I tried the Ubuntu script, it also fails.

What are the requirements to successfully run the scripts on a clean server?

**Comment by Ysurac** [comment]
What is the error ?

**Comment by GTiDon** [comment]
I have just rebuilt a debian installation and running it again now. Will post the result. How do U copy the text in Putty?

**Comment by Ysurac** [comment]
No idea, I don't use Putty.

**Comment by GTiDon** [comment]
Setting up liberror-perl (0.17027-2) ...
Setting up libcurl4:amd64 (7.64.0-4+deb10u2) ...
Setting up git-man (1:2.20.1-2+deb10u3) ...
Setting up curl (7.64.0-4+deb10u2) ...
Setting up git (1:2.20.1-2+deb10u3) ...
Processing triggers for libc-bin (2.28-10) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for mime-support (3.62) ...
Install kernel linux-image-5.4.86-mptcp_1.16+9d3f35b
 !!! if kernel install fail run: dpkg --remove --force-remove-reinstreq linux-image-5.4.86-mptcp !!!
Selecting previously unselected package linux-headers-5.4.86-mptcp.
(Reading database ... 28704 files and directories currently installed.)
Preparing to unpack .../linux-headers-5.4.86-mptcp_1.16+9d3f35b_amd64.deb ...
Unpacking linux-headers-5.4.86-mptcp (1.16+9d3f35b) ...
Setting up linux-headers-5.4.86-mptcp (1.16+9d3f35b) ...
Examining /etc/kernel/header_postinst.d.
Selecting previously unselected package linux-image-5.4.86-mptcp.
(Reading database ... 49439 files and directories currently installed.)
Preparing to unpack .../linux-image-5.4.86-mptcp_1.16+9d3f35b_amd64.deb ...
Done.
Unpacking linux-image-5.4.86-mptcp (1.16+9d3f35b) ...
Setting up linux-image-5.4.86-mptcp (1.16+9d3f35b) ...

 Hmm. There is a symbolic link /lib/modules/5.4.86-mptcp/build
 However, I can not read it: No such file or directory
 Therefore, I am deleting /lib/modules/5.4.86-mptcp/build


 Hmm. The package shipped with a symbolic link /lib/modules/5.4.86-mptcp/source
 However, I can not read the target: No such file or directory
 Therefore, I am deleting /lib/modules/5.4.86-mptcp/source

Running depmod.
Examining /etc/kernel/postinst.d.
run-parts: executing /etc/kernel/postinst.d/apt-auto-removal 5.4.86-mptcp /boot/vmlinuz-5.4.86-mptcp
run-parts: executing /etc/kernel/postinst.d/initramfs-tools 5.4.86-mptcp /boot/vmlinuz-5.4.86-mptcp
update-initramfs: Generating /boot/initrd.img-5.4.86-mptcp
I: The initramfs will attempt to resume from /dev/null
I: Set the RESUME variable to override this.
Set MPTCP kernel as grub default...
--2021-05-10 15:31:44--  https://www.openmptcprouter.com/server/update-grub.sh
Resolving www.openmptcprouter.com (www.openmptcprouter.com)... 156.38.130.226
Connecting to www.openmptcprouter.com (www.openmptcprouter.com)|156.38.130.226|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 746 [application/octet-stream]
Saving to: '/tmp/update-grub.sh'

/tmp/update-grub.sh                                100%[=============================================================================================================>]     746  --.-KB/s    in 0s

2021-05-10 15:31:44 (7.89 MB/s) - '/tmp/update-grub.sh' saved [746/746]

sed: can't read /boot/grub/grub.cfg: No such file or directory

**Comment by Ysurac** [comment]
Are you sure you can use a custom kernel on your VPS ?

**Comment by GTiDon** [comment]
> Are you sure you can use a custom kernel on your VPS ?

Is there a way I can test. I am not sure of this

**Comment by Ysurac** [comment]
```hostnamectl``` can give you the used irtualization method

**Comment by GTiDon** [comment]
![image](https://user-images.githubusercontent.com/51342593/117668805-948eb500-b1a6-11eb-9975-10c3bf699b67.png)

**Comment by GTiDon** [comment]
Interesting. The server I am trying to run cant run this command. My other server does run it

**Comment by Ysurac** [comment]
The .84 vps should work (even if it have a old kernel that seems to be MPTCP kernel).
For the .77 vps check with ```uname -a``` what is the kernel.
Make sure you use a KVM cloud server and not a container VPS as it seems to be hostafrica provider.

If it's the case, KVM servers should allow a custom kernel. Check what you have in /boot partition: ```ls /boot```, if it's empty, try to mount it ```mount /boot``` if there is no error, this may solve the issue.

**Comment by GTiDon** [comment]
Thankyou. I am starting a new one

**Comment by GTiDon** [comment]
Thankyou. It seems to have installed the server now successfully on KVM server. I was going in circles for days trying
