### ISSUE TITLE
Install on Unsupported OpenWRT Router

### ISSUE THREAD

**Issue by GTiDon** [Ysurac/openmptcprouter#1818]
Hello

Is it possible to install Opem MPTCPRouter onto an unsupported router?

How do I set this up? I have OpenWRT running

**Comment by Ysurac** [comment]
You need to compile the image: https://github.com/Ysurac/openmptcprouter/wiki/Create-image-for-unsupported-platform
Then this may or not work.

**Comment by GTiDon** [comment]
Do I run these commands on the router? Then flash the firmware BIN it creates?

Sorry my Linux knowledge is very limited

**Comment by GTiDon** [comment]
But then how is it compiled for my specific device?

**Comment by GTiDon** [comment]
I am going over the Doc but dont understand it all.
I have built a linux VM and I have run the commands to install the tools (Some errors)

apt-get install busybox curl rsync build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler wget

I dont understand this next step?  WHat DO I enter for the platform? Which machine must this be run on?

# git clone https://github.com/Ysurac/openmptcprouter.git
# cd openmptcprouter
# git checkout master
# OMR_TARGET="myplatform" OMR_FEED_SRC="master" ./build.sh

**Comment by Ysurac** [comment]
It does cross compilation, so on the machine you want to use for compilation.
For the myplatform, you need to enter the platform you want to compile to, like x86_64 or rpi4.

**Comment by GTiDon** [comment]
It's a OpenWRT router I want to run it on

**Comment by Ysurac** [comment]
If it's not a supported arch, you need to know the arch used and then you will need to configure it manually with ```make menuconfig```, as indicated in the doc.

**Comment by GTiDon** [comment]
What Arch is this?

![image](https://user-images.githubusercontent.com/51342593/118275216-6ff84d00-b4c6-11eb-99f8-b1d15a94cf4c.png)

**Comment by GTiDon** [comment]
![image](https://user-images.githubusercontent.com/51342593/118276328-d336af00-b4c7-11eb-8106-2271529a2fc8.png)

**Comment by Ysurac** [comment]
It's a ZBT WE-826, so based on MT7620 on ramips arch.
But with a so slow CPU, so small flash and really small ram, I think this will be difficult to use OpenMPTCProuter.

**Comment by GTiDon** [comment]
I still want to test. It has 32Mb flash

Will it be possible?

**Comment by Ysurac** [comment]
I don't think, but you can test if you want ;)

**Comment by GTiDon** [comment]
Can you please help me with the cross platform build steps? I really don't understand from the documentation what I need to enter
![Uploading image.png…]()

**Comment by Ysurac** [comment]
I don't see the image.

**Comment by GTiDon** [comment]
I have selected the Arch on the list. Is there anything else I should select? what can I remove to make a lighter build?

![image](https://user-images.githubusercontent.com/51342593/118389759-b87d4b00-b62b-11eb-9ad8-4a3db1ba8ad2.png)


Then what should the config file be saved as?

![image](https://user-images.githubusercontent.com/51342593/118389718-7b18bd80-b62b-11eb-8ee3-cd37618030da.png)

**Comment by Ysurac** [comment]
You need at least to select Target, Subtarget and Target profile.
Keep default name for config.

**Comment by GTiDon** [comment]
What is the default name? There is no name when I click save. It asks as above

**Comment by Ysurac** [comment]
As above, and as default, it's ```.config```

**Comment by GTiDon** [comment]
I keep getting errors.

![image](https://user-images.githubusercontent.com/51342593/118801735-9ee53900-b8a1-11eb-89bf-2d6deb2ae646.png)

**Comment by Adorfer** [comment]
> Will it be possible?

No. flash and ram is both too small. and if you solder bigger on, then you will find a performance lower than 15MBit/s.

**Comment by GTiDon** [comment]
![image](https://user-images.githubusercontent.com/51342593/118816410-70238e80-b8b2-11eb-8817-1b45bf4dadb3.png)

**Comment by Bumpalert** [comment]
@Ysurac  I tried to build for rpi4 target to make sure environment is correct. But it failed as below complaining ab out libparam & kmod-mt6625l-wlan-gen2.Which packages need to be included to the dependency list?


-------------
Overriding core package 'umbim' with version from openmptcprouter
Done
Building openmptcprouter for the target rpi4
WARNING: Makefile 'package/utils/busybox/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/busybox/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/busybox/Makefile' has a build dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/policycoreutils/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/policycoreutils/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/policycoreutils/Makefile' has a build dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/wmt/Makefile' has a dependency on 'kmod-mt6625l-wlan-gen2', which does not exist
#
# configuration written to .config
#
WARNING: Makefile 'package/utils/busybox/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/busybox/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/busybox/Makefile' has a build dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/policycoreutils/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/policycoreutils/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/policycoreutils/Makefile' has a build dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/wmt/Makefile' has a dependency on 'kmod-mt6625l-wlan-gen2', which does not exist
time: target/linux/prereq#0.26#0.13#0.37
 make[1] world
 make[2] tools/compile
 make[3] -C tools/flock compile
 make[3] -C tools/xz compile
 make[3] -C tools/sed compile
 make[3] -C tools/patch compile
 make[3] -C tools/tar clean-build
 make[3] -C tools/tar compile
    ERROR: tools/tar failed to build.
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [/media/storage/openmptcprouter/rpi4/source/include/toplevel.mk:230: world] Error 1

**Comment by Bumpalert** [comment]
@Adorfer @Ysurac can you help where can I get libpam. I tried openwrt compiling to clear this dependency but didn't work.

**Comment by Ysurac** [comment]
@Bumpalert you don't need to solve the libpam warning to compile.
