### ISSUE TITLE
PI Install Trouble

### ISSUE THREAD

**Issue by GTiDon** [Ysurac/openmptcprouter#1819]
I thought I had success, but having trouble with setting the server on the Pi.
When I reboot all settings are gone

![image](https://user-images.githubusercontent.com/51342593/117703433-ee54a680-b1c9-11eb-867e-8ab1f291e245.png)

**Comment by Ysurac** [comment]
As indicated, your filesystem is readonly.
This can be after a power cut or due to a bad SD card. You need to install it again.

**Comment by GTiDon** [comment]
I have rebuilt the image on the SD Card. After adding the server now I get
![Uploading image.png…]()

**Comment by GTiDon** [comment]
Thankyou. After SD re imaged I have the PI connecting.
I did this one to learn and test.
But Ireally want to get it running on the Multi port OpenWRT Router and also I have a i5 Mini PC with 6 LAN ports I want to run it one. I still don't undertand how to compile the image or load it on the x86 pc
