### ISSUE TITLE
VPS with MultiIP - tunnel gre little bug - Shorewall

### ISSUE THREAD

**Issue by gnosoz** [Ysurac/openmptcprouter#1820]
## Current Behavior
When multiple IPv4 are set on the vps there is a little bit of hit&miss on regards with the correct exit IP utilized.
After several tests I think that this is caused by the shorewall/snat configuration which masks everything in the 10.255.0.0/16 therefore including the subnet utilized by the gre tunnels.
the rule in question is the following
**MASQUERADE  all  --  10.255.0.0/16        0.0.0.0/0**           
As iptables works based on the position of the rule and this config, whilst perfect for 1 IPv4, impedes the execution of the correct SNAT statement as can be shown in the extract below of the command iptables -t nat -L -n 

```
Chain ens18_masq (1 references)
target     prot opt source               destination         
MASQUERADE  all  --  10.255.0.0/16        0.0.0.0/0           
MASQUERADE  all  --  169.254.0.0/16       0.0.0.0/0           
MASQUERADE  all  --  172.16.0.0/12        0.0.0.0/0           
MASQUERADE  all  --  192.168.0.0/16       0.0.0.0/0           
SNAT       all  --  10.255.249.0/30      0.0.0.0/0            to:<IP1>
SNAT       all  --  10.255.249.4/30      0.0.0.0/0            to:<IP2>
SNAT       all  --  10.255.249.8/30      0.0.0.0/0            to:<IP3>
SNAT       all  --  10.255.249.12/30     0.0.0.0/0            to:<IP4>
SNAT       all  --  10.255.249.16/30     0.0.0.0/0            to:<IP5>
```

## Possible Solution
Due to the fact I only utilize glorytun_tcp I solved the problem changing the file /etc/shorewall/snat as follows:
**MASQUERADE		10.255.255.0/24**
Instead of the original which was 10.255.0.0/16

After this change I confirm that the rules work as a charm and in fact all curl tests from the vps binding to the 10.255.249.xx return the correct associated external IP

I am further testing to avoid that firewall changes router side affect this modification I inserted

## Steps to Reproduce the Problem

  1. create VPS with multiple ips
  2. install OMR-vps script & verify gre tunnels are establishe
  3. check with curl ipv4.openmptcprouter.com --interface <gre_IPx_local_address> 
  4. confirm that the address is always the master
  5. change /etc/shorewall/snat -- restart shorewall & retry step 3 to confirm now all addresses are correctly SNATted

## Context (Environment)
The result we are trying to achieve is to be able to forward the same port utilized for 5 different services / domains to different internal pc / subnets. These ports cannot be changed due to the type of program which is behind them and therefore the requiment is to have more IP which can then be routed accordingly 

## Specifications

  - OpenMPTCProuter version: v0.57.3 r0+15225-bfc433efd4
  - OpenMPTCProuter VPS version: 0.1024
  - OpenMPTCProuter platform: X86_64

**Comment by Ysurac** [comment]
I added the needed changes in VPS snapshot script.
