### ISSUE TITLE
Raspberry 3 interfaces

### ISSUE THREAD

**Issue by gianlucabarani** [Ysurac/openmptcprouter#1821]
Hi Raspberry 3 has 1 eth . I try to setup 2 Wan router to the same switch connected ETH Raspberry. But seem Only One work. It s because i Need several different interfaces? I try to setup vlmac but seems not work. So at the end with Raspberry i can connect 1 via USB , 2 via ETH and 3 via WiFi. Are there other option?

**Comment by Ysurac** [comment]
MacVLAN create "virtual" interfaces. 2 interfaces are created by default on RPI.
You don't need to add USB adapters (that work badly on RPI <4).

**Comment by gianlucabarani** [comment]
Ok when i create a MacVlan in phisical Tab What do i set? Leave blank or i set eth0? Thanks

**Comment by Ysurac** [comment]
Use eth0. You can also use the wizard.

**Comment by gianlucabarani** [comment]
Ok set eth0.1 but seem there Aren't packet TX and TX flowing in interfaces view. Packet flow Only of i set phisical interfaces eth0 sorry
![Screenshot_2021-05-12-20-37-53-033_com android chrome](https://user-images.githubusercontent.com/15262933/118027357-1d9e1b80-b362-11eb-9aa3-15e92b3b3c7e.jpg)

**Comment by Ysurac** [comment]
VLAN can't be used with MacVLAN.

**Comment by Ysurac** [comment]
You can use VLAN without using MacVLAN in this case.

**Comment by gianlucabarani** [comment]
Ok changing MacVlan to normal VLan packets now flowing only in One direction TX but i think that i set the same VLan tag on the Wan router Port side.

**Comment by gianlucabarani** [comment]
Ok i buy a Layer2 switch and work fine using VLan. Thanks.
