### ISSUE TITLE
Multiple clients to VPS

### ISSUE THREAD

**Issue by Dharun2308** [Ysurac/openmptcprouter#1823]
## Expected Behavior
I would like to connect more than one client to the same VPS. I had tried many ways, but couldn't solve the issue. Can anyone provide help in this?

## Current Behavior
Currently openMPTCProuter supports one client to VPS without a problem. Working great. 

## Specifications

  - OpenMPTCProuter version: v0.57.3 
  - OpenMPTCProuter VPS version: Debian 10 with latest VPS script
  - OpenMPTCProuter platform: RPI4

**Comment by Ysurac** [comment]
Duplicate of https://github.com/Ysurac/openmptcprouter/issues/1058
