### ISSUE TITLE
WAN port Priorities

### ISSUE THREAD

**Issue by GTiDon** [Ysurac/openmptcprouter#1827]
Hello

Is it possible to set priorities on WAN ports? Does the Port Metric work for this?

On my Viprinet bonder I can set weights per port to priorities

**Comment by Ysurac** [comment]
No. Priority is based on WAN latency.

**Comment by GTiDon** [comment]
It would be best for many to have control lover priorities.

I line to have fixed lines higher priority and uncapped LTe, while the more expensive ones lower even if they are faster.

**Comment by Ysurac** [comment]
Often fixed lines have a lower latency than LTE, so I don't think it's a real problem.
Fullmesh MPTCP doesn't support priority choice.
