### ISSUE TITLE
VPS LAN to OMR LAN Access

### ISSUE THREAD

**Issue by hrmtc** [Ysurac/openmptcprouter#1829]
## Expected Behavior
Being able to access the OMR LAN from the VPS LAN

## Current Behavior

I can't reach services on the OMR LAN side.

## Specifications

  - OpenMPTCProuter version: openmptcprouter v0.57.3 r0+15225-bfc433efd4 / LuCI Master git-20.339.75073-e54708a
  - OpenMPTCProuter VPS version: 0.1024 5.4.86-mptcp
  - OpenMPTCProuter platform: Raspberry Pi 3 Model B Plus Rev 1.3

## Comments
I would like to reach devices on the OMR LAN side from the VPS LAN.
I guess that I should configure some routes and shorewall rules but I don't know where to start.
Could someone help me to understand this, please?

Thanks!

**Comment by Ysurac** [comment]
On v0.58 you can access LAN from VPS by default, at least if you allow that from router firewall.

**Comment by hrmtc** [comment]
Thanks. 
v0.58 will be released soon?

**Comment by Ysurac** [comment]
I hope. For now there is 0.58rc2.
