### ISSUE TITLE
Pi BPI-R2 

### ISSUE THREAD

**Issue by kapook007** [Ysurac/openmptcprouter#183]
EMMC image: openmptcprouter-v0.37.3
SD image: openmptcprouter-v0.37.3

i have some problem 
i can not save any config  
when i reboot my Pi BPI-R2 router ,  no password root and go to default config!!!
same problem SD image and EMMC image
==!!

**Comment by Ysurac** [comment]
Read #180

**Comment by kapook007** [comment]
thank you
