### ISSUE TITLE
problem with firewall

### ISSUE THREAD

**Issue by matthieu71000** [Ysurac/openmptcprouter#1842]
Bonjour,

Régulièrement je suis obligé de purger le fichier /etc/shorewall/rules sur le VPS.

Les règles du NAT se multiplient, et fini par provoquer un crash.

ROUTEUR PI : 0.57.3
VPS : 0.1024 5.4.86

Merci

Par rappel votre post concernant mon problème :

_Originally posted by @Ysurac in https://github.com/Ysurac/openmptcprouter/issues/1400#issuecomment-731525872_

**Comment by Ysurac** [comment]
C'est normalement réglé en 0.58rc2 et VPS script 0.1025-test

**Comment by matthieu71000** [comment]
Parfait merci j'attend la release.

👍🏻
