### ISSUE TITLE
Why not an unptream kernel?

### ISSUE THREAD

**Issue by edo1** [Ysurac/openmptcprouter#1848]
It looks like the current stable kernel supports MPTCP, any reason to use out-of-tree MPTCP implementation?

**Comment by Ysurac** [comment]
Yes, current stable kernel doesn't support all MPTCP features and next upstream kernel still need some dev to be able to do fullmesh.

**Comment by edo1** [comment]
Where can I get more info about unsupported features in the mainline kernel?

**Comment by Ysurac** [comment]
https://github.com/multipath-tcp/mptcp_net-next/wiki
