### ISSUE TITLE
What does "additional latency" field do?

### ISSUE THREAD

**Issue by milankragujevic** [Ysurac/openmptcprouter#1855]
In Network > Interfaces > Edit on an Interface > Advanced Settings, there is an "Additional latency" field. What does it do? How should it be configured? 

![image](https://user-images.githubusercontent.com/7611163/119275188-dcd0bd00-bc13-11eb-9378-212d97257f8f.png)

**Comment by Bumpalert** [comment]
My understanding is we can add a latency to measured latency to make it less preferable interface on an mptcp environment

**Comment by milankragujevic** [comment]
Thank you for the explanation. @Ysurac can you confirm.

**Comment by Ysurac** [comment]
True, it's for that and to make tests where setting more latency can be needed.

**Comment by milankragujevic** [comment]
Thank you both.
