### ISSUE TITLE
How to get the wan signal strength and operator info from LTE modem?

### ISSUE THREAD

**Issue by gudokim** [Ysurac/openmptcprouter#1858]
![image](https://user-images.githubusercontent.com/32947362/119353446-dd358a80-bcdd-11eb-97d2-0a8248ab152b.png)

I have a project to get the modem info and would like to know how.

To get the wan signal strength and operator info from LTE hilink modem..
As I know , we can get info only via web from modems in the hilink mode.

Every E8372h-320 lte modem in the hilink mode has different password for log-in to get info.
I wonder how openmptcprouter can get the modem info without knowing password.

best regards,

**Comment by Ysurac** [comment]
This is the code that is used to get info from huawei: https://github.com/Ysurac/openmptcprouter-feeds/blob/develop/luci-app-openmptcprouter/root/bin/omr-huawei
These infos doesn't need any login.

**Comment by gudokim** [comment]
Wow~~ Thank you so much!!
