### ISSUE TITLE
SSL error when update

### ISSUE THREAD

**Issue by SoGooDFR** [Ysurac/openmptcprouter#186]
When update vps script we've got this:

```
ERROR: The certificate of ‘www.openmptcprouter.com’ is not trusted.
ERROR: The certificate of ‘www.openmptcprouter.com’ is not yet activated.
The certificate has not yet been activated
```

**Comment by Ysurac** [comment]
You should check date of your server. It's not a good idea to bypass certificate check.
What is the arch of the VPS and the Debian version used ?

**Comment by SoGooDFR** [comment]
`xxxx:~# date
Sat Feb 25 05:17:15 CET 2017
`
My host privider relocate my VPS in another DC, i suspect this error come from.
