### ISSUE TITLE
192.168.100.1 refused to connect.

### ISSUE THREAD

**Issue by Yersi88** [Ysurac/openmptcprouter#1861]
## Expected Behavior
web interface loads at 192.168.100.1

## Current Behavior

192.168.100.1 refused to connect. When trying to access router from web browser. When I try to ping 192.168.100.1 from cmd it responds. 
![image](https://user-images.githubusercontent.com/77145281/119414637-d14ec600-bce7-11eb-9c08-9feee8ca322e.png)

 computer is connected straight with ethernet cable to eth0 of OpenMPTCProuter box. IP of computer is set to 192.168.100.13.

## Specifications

  - OpenMPTCProuter version:  openmptcprouter-v0.57.3-r0+15225-bfc433efd4-x86-64-generic-ext4-combined-efi.img.gz 
  - OpenMPTCProuter VPS version: OpenMPTCProuter Server 0.1024 
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
Can you try to go on it with SSH (user root, no password by default and port 22) ?

**Comment by Yersi88** [comment]
> Can you try to go on it with SSH (user root, no password by default and port 22) ?

I tried to ssh into 192.168.100.1 but was not successful. 

I also noticed that pinging 192.168.100.1 still works when network cable is unplugged from PC, not sure what to think about that. (Computer is set up with gateway: 192.168.100.1, mask: 255.255.255.0 and ip: 192.168.100.13 )

Also, isn't it supposed to have DHCP server running as default? (It doesn't give IP address to PC when I plug PC's network card to eth0)

**Comment by Ysurac** [comment]
You seems to have something that answer at IP 192.168.100.1 but it's not OpenMPTCProuter.
Yes, OpenMPTCProuter have a DHCP server running as default.

**Comment by Yersi88** [comment]
> You seems to have something that answer at IP 192.168.100.1 but it's not OpenMPTCProuter.
> Yes, OpenMPTCProuter have a DHCP server running as default.

There shouldn't be anything with that address, I have all other network adapters disabled just the one that's connected directly to OpenMPTCProuter box is enabled. When I remove the manual ipv4 configuration than there's no response from 192.168.100.1

Why is the dhcp not working though? Maybe I'm doing something stupid. I just booted the OpenMPTCProuter  from usb stick and plugged in the network cable to eth0 and to my pc.

**Comment by hairy-dog** [comment]
I'd check the PC's network settings next.
"ipconfig /all"

**Comment by Yersi88** [comment]
> I'd check the PC's network settings next.
> "ipconfig /all"

![image](https://user-images.githubusercontent.com/77145281/119488339-5373d480-bd52-11eb-887d-65dea504e01a.png)

When IP is not set manually I get no IP from OpenMPTCProuter

**Comment by Ysurac** [comment]
Check that you don't have a firewall on your client PC.
Check also that ethernet connection is correct (right port on the router).
Check that router is really booted to OpenMPTCProuter and that there is no error.

**Comment by Yersi88** [comment]
> Check that you don't have a firewall on your client PC.
> Check also that ethernet connection is correct (right port on the router).
> Check that router is really booted to OpenMPTCProuter and that there is no error.


1. No firewall on client
2. I'm running it on mini pc which only has one ethernet port. 
3. 
![image](https://user-images.githubusercontent.com/77145281/119490188-78694700-bd54-11eb-862a-b727883e460c.png)

**Comment by Ysurac** [comment]
You can try to check IP on OpenMPTCProuter via ```ip a``` and set fixed IP on your client like before and try to ping it from the router.

**Comment by Yersi88** [comment]
> You can try to check IP on OpenMPTCProuter via `ip a` and set fixed IP on your client like before and try to ping it from the router.

![image](https://user-images.githubusercontent.com/77145281/119491774-39d48c00-bd56-11eb-86ac-1756a9d6bfc9.png)

![image](https://user-images.githubusercontent.com/77145281/119491852-5375d380-bd56-11eb-8e1c-bf8f91ff5d77.png)

Can't ping the client as well. This is odd.

**Comment by hairy-dog** [comment]
I wonder about the mention of connectify in the ipconfig results. Doest connectify use some network software in the background?

**Comment by hairy-dog** [comment]
The ipconfig screengrab was of a pc with no network cable connected.

**Comment by Yersi88** [comment]
> I wonder about the mention of connectify in the ipconfig results. Doest connectify use some network software in the background?

Connectify was running on different PC never on this one.



> The ipconfig screengrab was of a pc with no network cable connected.

Network cable is connected. But no ip allocated from OpenMPTCProuter.

You can see two network cards Ethernet and Ethernet 2. One is 'Media disconnected' the other one is connected to the OpenMPTCProuter direct via ethernet cable.

**Comment by Adorfer** [comment]
other approach: 
1) "ping 192.168.100.1"
2) "arp -a", look for the 192.168.100.1 and the IEEE/MAC associated. hopefully it's 68-1d-ef-22-f8-cf.

**Comment by hairy-dog** [comment]
I think the second connection in ipconfig is showing an IP that displays when no dhcp server has been found: effectively a network that is disconnected.
My suspicion is that the router is set to prevent clients contacting one another, and only connecting out to the internet. Can other devices on the network ping each other?

**Comment by Yersi88** [comment]
> I think the second connection in ipconfig is showing an IP that displays when no dhcp server has been found: effectively a network that is disconnected.
> My suspicion is that the router is set to prevent clients contacting one another, and only connecting out to the internet. Can other devices on the network ping each other?

There are no devices. It's my PC (client) connecter through ethernet cable straight to the PC where OpenMPTCProuter is running. One network adapter connected straight to other network adapter.

**Comment by Adorfer** [comment]
if you do not like to do the arp thing, please "tracert 192.168.100.1"

**Comment by flimo44** [comment]
Hello ,
On screem shoot i see your manuel Pc address set at  192.168.100.1  and gateway 192.168.100.1 ... The IP's are reversed I think, right?

**Comment by Ysurac** [comment]
True, error in Windows PC config here.

**Comment by Adorfer** [comment]
so either open the firwall on the PC to access the local webserver. 

Or change the address in the browser to 192.167.100.13 and change the IP in the OMR as well.

**Comment by Yersi88** [comment]
> True, error in Windows PC config here.

Indeed a really silly mistake! Thanks for all the support <3
