### ISSUE TITLE
utiliser la 2nde ligne seule si la connexion principale est down

### ISSUE THREAD

**Issue by gmorlet** [Ysurac/openmptcprouter#1862]
Bonjour,

est-il possible de configurer pour n'utiliser la seconde connexion internet que si la première est down.

explication : une connexion internet principale et une secours en domino 4G donc avec un volume de data limité.

Merci car je n'ai pas trouvé et j'ai cherché aussi sur le "forum" mais peut être pas les bons termes

**Comment by Ysurac** [comment]
Pour cela il faut définir l'interface en backup (ou "sauvegarder" en français).
