### ISSUE TITLE
link between wifi and lan interfaces

### ISSUE THREAD

**Issue by SylvainLegrand** [Ysurac/openmptcprouter#1869]
## Expected Behavior
I would like the wired and wifi networks to be linked.
For example, I would like to use a wifi printer from a computer connected to the wired network.

## Current Behavior
My wifi printer works well and I can use it from a phone or any devices connected to the wifi interface.
My computer reach the internet through the router but can't be link to any devices in the wifi interface.
It is as if I had built 2 different networks without any connection between them.

## Specifications

  - OpenMPTCProuter version: v0.57.3 r0+15225-bfc433efd4
  - OpenMPTCProuter VPS version: Server 0.1024
  - OpenMPTCProuter platform: RPI4/x86_64
 
  - Wifi configuration: Mode => Access point / Network => wifi
  - Wifi interface configuration: IPV4 192.168.100.2 / gateway 192.168.100.1 / type bridge / firewall settings => in the same zone with the lan interface
  - Lan interface: IPV4 192.168.100.1

Thanks for your help.

**Comment by Ysurac** [comment]
You can try to follow documentation: https://github.com/Ysurac/openmptcprouter/wiki/Configure-Wifi

**Comment by SylvainLegrand** [comment]
Hi,

I have already followed this documentation.
Can you take a look at the screenshots I made?

![4_Network_Interfaces_Wifi_physical_settings](https://user-images.githubusercontent.com/23272229/127454522-c0f09b3d-0e6a-42cc-8823-1a6fb560e050.png)
![0_Dashboard](https://user-images.githubusercontent.com/23272229/127454524-e93b077f-0e3d-46e3-a825-29ddc44706c7.png)
![1_Network_Wireless](https://user-images.githubusercontent.com/23272229/127454526-d7120386-285c-424e-af78-216c6cc5378e.png)
![2_Wireless_OpenWrt_configuration_general_setup](https://user-images.githubusercontent.com/23272229/127454527-4083c07e-8fb3-4ef6-8212-92388d9b8254.png)
![3_Network_Interfaces](https://user-images.githubusercontent.com/23272229/127454528-23560f0a-1e88-4f38-b915-686e7f9b8854.png)
![4_Network_Interfaces_Wifi_firewall_settings](https://user-images.githubusercontent.com/23272229/127454531-dfe253a6-f4be-4e37-a514-f7e092ed0584.png)
![4_Network_Interfaces_Wifi_general_settings](https://user-images.githubusercontent.com/23272229/127454533-5c2cb723-b890-49e9-9952-77e8f5351d63.png)

Thanks.

Sylvain Legrand.
