### ISSUE TITLE
OMR-BYPASS for Netflix Doesn't work anymore

### ISSUE THREAD

**Issue by Maudissure** [Ysurac/openmptcprouter#187]
## Expected Behavior

Netflix Access for all home clients

## Actual Behavior

Netflix geo-blocked for all clients

## Steps to Reproduce the Problem

  1.input of all settings for Netflix on OMR-Bypass utility (As described on issue #112)
  2.reboot OMR and clients
  3.No Netflix streaming access, proxy blocked

## Specifications

  - OpenMPTCProuter version: 0.38
  - OpenMPTCProuter VPS version: 0.55
  - OpenMPTCProuter platform: RPI3B+

**Comment by Maudissure** [comment]
After some times, Bypass works. I close.

**Comment by SoGooDFR** [comment]
I confirm that and extremely slow DNS resolution.
