### ISSUE TITLE
VPN in?

### ISSUE THREAD

**Issue by hairy-dog** [Ysurac/openmptcprouter#1874]
## Expected Behavior
I would like to connect a different network to my network , which is using OMR

## Current Behavior
I have OMR running well, combining several different internet connections.

I shall have a different building with a fast enough internet connection, not using OMR.

I would like to connect the two networks together using a VPN. I wonder if some of the work is already done in OMR, but I don't know.

## Specifications

  - OpenMPTCProuter version: openmptcprouter v0.57.3 r0+15225-bfc433efd4
  - OpenMPTCProuter VPS version: 5.4.86-mptcp 0.1024
  - OpenMPTCProuter platform: Raspberry Pi 4 Model B Rev 1.1

**Comment by Ysurac** [comment]
Several way, but the best is to install/configure VPN on the VPS side, then only some routes are needed.

**Comment by hairy-dog** [comment]
Is there an idiot's guide about how to do that? I don't want to break my working system!

**Comment by Ysurac** [comment]
No there is not. Wireguard is installed on VPS, you can use it but use another interface as wg0 used by OpenMPTCProuter.

**Comment by hairy-dog** [comment]
OK, thank you.

**Comment by Ysurac** [comment]
You can also use OpenVPN that is also installed by default, you only need to not use tun0 and tun1 as interface.
