### ISSUE TITLE
Big Time Difference between server and router & Ping Delay

### ISSUE THREAD

**Issue by satmarin** [Ysurac/openmptcprouter#1880]
Hi I have 2 questions:

1) Ping Delay
Due to the mobile nature of the 4G WAN connections used we sometimes get ping delay > 1sec.  
Is it correct that the gateway is not used when ping delay is > than 1 sec. as indicated in the OpenMPTCP status page.  And if so where can this delay be extended to 2 seconds?

2) Big Time Difference
We get message in openMPTCP status that there is a big time difference between VPS and router but server is on CEST (Brussels) and router is on Europe/Brussels. What is considered 'big time difference' and does it affect the links in any way?

Thanks
Michaël

  - OpenMPTCProuter version: openmptcprouter v0.57.3 r0+15225-bfc433efd4
  - OpenMPTCProuter VPS version: Version 0.1024 5.4.65-mptcp
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
1. It's only a warning in status page, so connection is still used. There is options to disable warning display in "Advanced settings" tab
2. Time diff is calculated on UTC, so if the message is displayed (when diff > 10s) then there is a problem and date/time must be fixed

**Comment by satmarin** [comment]
Thanks you for the fast response.  
1) OK
2) does it affect the connection when time difference is > 10sec but < 2 minutes ?  Maybe message could also indicate the time on both devices which might make it easier to troubleshoot.

**Comment by Ysurac** [comment]
Yes it affect the connection. I don't want to put too much data on status page ;)

**Comment by satmarin** [comment]
The router updates the time according to ntpdate correctly.  I am trying to update the VPS but it doesn't seem to have ntpdate.  What would be the best way to time sync the VPS?

**Comment by Ysurac** [comment]
I often use chrony to sync time on VPS.

**Comment by satmarin** [comment]
Excellent, worked perfectly.  Thank you Yannick
