### ISSUE TITLE
Run Client in kvm ?

### ISSUE THREAD

**Issue by Lukylix** [Ysurac/openmptcprouter#1884]
Is there a client img for kvm ? 
Can't get it to work on a nuc.

Existe t'il une image client compatible avec kvm.
Je n' arrive pas à créer de vm fonctionnelle avec les images pressentes sur le site.

**Comment by Lukylix** [comment]
Convert img
`qemu-img convert -O raw  openmptcprouter-v0.57.3-r0+15225-bfc433efd4-x86-64-generic-ext4-combined.vhdx openmptcprouter.img
`

**Comment by Adorfer** [comment]
why don't you just take the normal (kvm) image? 
just unzip the "-generic-ext4-combined.img.gz"  and here you have the .img!
