### ISSUE TITLE
wrt3200acm img erreur

### ISSUE THREAD

**Issue by phenix14000** [Ysurac/openmptcprouter#1887]
Bonjour Yannick,

J'ai essayé d'installer l'image "openmptcprouter-v0.57.3-r0+15225-bfc433efd4-mvebu-cortexa9-linksys_wrt3200acm-squashfs-factory.img" mais celle -ci ne fonctionne pas. Lors du reboot du routeur a la fin de l'installation, il est impossible de se connecter via n'importe quelle urls que ce soit celle de linksys ou celle de OMPTCPR. J'ai bien évidemment vérifier le hash de l'img avant d'installé.
Je suis obligé de faire un factory reset. Et donc dans l'impossibilité d'installer OMPTCPR.

Cordialement,
Xavier

**Comment by Ysurac** [comment]
Après l'installation il faut rebooter en appuyant sur le bouton I/O, puis la connexion se fait via le port Internet après un premier boot assez long.

**Comment by phenix14000** [comment]
Très bien je fais ça demain merci pour ton retour super rapide ;)
