### ISSUE TITLE
Erreur de certificat à la fin de l'installation

### ISSUE THREAD

**Issue by Rathorian** [Ysurac/openmptcprouter#1888]
Bonjour

J'ai installé une première fois sur un VPS OVH le script OpenMPTCProuter et à la fin j'ai toujours une erreur de certificat : 
```
[Wed Jun  9 14:08:10 CEST 2021] Create new order error. Le_OrderFinalize not found. {
  "type": "urn:ietf:params:acme:error:rateLimited",
  "detail": "Error creating new order :: too many certificates already issued for: ovh.net: see https://letsencrypt.org/docs/rate-limits/",
  "status": 429
}
[Wed Jun  9 14:08:10 CEST 2021] Please add '--debug' or '--log' to check more details.
[Wed Jun  9 14:08:10 CEST 2021] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
```

J'imagine que c'est parce que j'ai pas changé le nom du VPS et qui porte du coup le nom de domaine `ovh.net` mais est-ce bloquant pour la suite ?

Merci beaucoup

**Comment by Ysurac** [comment]
Non ce n'est pas bloquant pour la suite et c'est effectivement parce que le VPS porte le nom ovh.net.

**Comment by Rathorian** [comment]
> 
> 
> Non ce n'est pas bloquant pour la suite et c'est effectivement parce que le VPS porte le nom ovh.net.

Merci pour la réponse ultra rapide.

Je ferme le ticket.

Bonne journée
