### ISSUE TITLE
Lower latency vs Equal latency

### ISSUE THREAD

**Issue by milankragujevic** [Ysurac/openmptcprouter#1890]
I currently bond 3 WANs - DSL, DOCSIS over Wireless link and LTE. DOCSIS ping is 16ms, LTE 18-24ms and DSL can be either 6ms or 16ms.

I have the ability to ask the ISP to set VDSL profile to Interleave which increases the ping to 16ms - which is higher but in line with other connections. Alternatively, I can ask them to set it to Fast profile, which will decrease the ping to 6ms, compared to 16ms with DOCSIS and 20ms with LTE.

What is "better" - lower ping on master connection (which has the lowest speed of all 3 connections) or similar ping on all connections? 

I know for GRE tunnel bonding it is preferred to have the same ping on all interfaces, and deviations cause problems.

**Comment by Ysurac** [comment]
If you need lowest ping as possible, then it's better with lower ping, else it's better with similar ping and with as low as possible lost packets.
