### ISSUE TITLE
UPnP not working

### ISSUE THREAD

**Issue by hochsaison** [Ysurac/openmptcprouter#1894]
## Expected Behavior

UPnP Service is expected to work if enabled.

## Current Behavior

After enabling UPnP, the following error appears in the System log:
```
Fri Jun 11 16:19:49 2021 user.notice upnp daemon: external interface not found, not starting
Fri Jun 11 16:19:49 2021 daemon.warn miniupnpd[16433]: Cannot get IP address for ext interface . Network is down
Fri Jun 11 16:19:49 2021 daemon.notice miniupnpd[16433]: HTTP listening on port 5000
Fri Jun 11 16:19:49 2021 daemon.notice miniupnpd[16433]: HTTP IPv6 address given to control points : [fdc4:ede:25d7::1]
Fri Jun 11 16:19:49 2021 daemon.notice miniupnpd[16433]: Listening for NAT-PMP/PCP traffic on port 5351
Fri Jun 11 16:19:51 2021 daemon.err miniupnpd[16433]: upnp_event_recv: recv(): Connection reset by peer
Fri Jun 11 16:19:51 2021 daemon.err miniupnpd[16433]: upnpevents_processfds: 0x424440, remove subscriber uuid:077047f8-f56d-4a81-9463-0fb47ac42add after an ERROR cb: http://10.0.0.94:2869/upnp/eventing/bjgykidlgv
``` 

## Possible Solution

None.

## Steps to Reproduce the Problem

  1. Enable MiniUPnP on a fresh installation

## Context (Environment)

I have three DSL lines combined together and want to enable NAT an UPnP. No manual port forwardings. NAT is being shown as "moderate" on Xbox and other devices.

## Specifications

  - OpenMPTCProuter version: v0.57.3
  - OpenMPTCProuter VPS version: 0.1024
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
On release <0.58 you need to configure external IP on UPnP. You can follow OpenWrt documentation.
Should be configured in 0.58 by default.
Else you should never use UPnP as it's a big security hole ;)
