### ISSUE TITLE
How to upgrade?

### ISSUE THREAD

**Issue by hairy-dog** [Ysurac/openmptcprouter#1895]
## Expected Behavior
I want to upgrade a working connection to 0.58

## Current Behavior
When I log in to OMR it tells me I'm using 0.57.3 and 0.58 is available. It also tells me that I should update the VPS software.

Which should I update first? 

I am using my OMR connection as my connection to the internet, so I want to keep a connection working!.

## Specifications

  - OpenMPTCProuter version: 0.57/3
  - OpenMPTCProuter VPS version:  ?
  - OpenMPTCProuter platform:  RPi4

**Comment by Ysurac** [comment]
Upgrade VPS first, then update OMR.

**Comment by hairy-dog** [comment]
Thanks!
