### ISSUE TITLE
RPi 4 with v0.58 no wireless menu/interface

### ISSUE THREAD

**Issue by Andromeda1966** [Ysurac/openmptcprouter#1896]
Hi,
I have installed new v0.58 on a RPi 4.
No wireless interface is recognized neither wireless menu.
How can I install/enable it ?

Thanks

**Comment by Ysurac** [comment]
Please use the template.
On RPI4 you should have menu Network->Wireless. If not, did you do an update or fresh install ?

**Comment by Andromeda1966** [comment]
Sorry.
Wrong version downloaded.
