### ISSUE TITLE
Unable to Port forward when interface configure Macvlan 

### ISSUE THREAD

**Issue by mshost** [Ysurac/openmptcprouter#1898]
Port forwarding was stop to work since the change of wan interface from normal to Macvlan, but when again turn interface creation into normal mode then working port forward normally .
Can't find any solution to recover 
OMR 57.3 and 58 both tested
 Help wanted

**Comment by Ysurac** [comment]
Please use the template.
Port forward from what to where ?

**Comment by mshost** [comment]
Need to forward port of OMR (80) to access it's remotely

**Comment by Ysurac** [comment]
If you mean forward from the VPS, I tested and no problems. 
Did you follow the documentation ( https://github.com/Ysurac/openmptcprouter/wiki/Port-forwarding) ?
