### ISSUE TITLE
RPI3B+ file system go in readonly for no reason

### ISSUE THREAD

**Issue by WazoAkaRapace** [Ysurac/openmptcprouter#1899]
## Expected Behavior
The system should run and not reboot by itself

## Current Behavior
After a fresh install, the filesystem is going to read only mode for no reason (New SD Card, flashed with etcher, then old settings imported)
The interfaces keep logging me off.

## Possible Solution
I've tried to repare the filesystem, but after 10 minutes of runtime, it corrupted itself again.

## Steps to Reproduce the Problem

  1. Update from 0.57.X to 0.58.1

## Specifications

  - OpenMPTCProuter version: 0.58.1
  - OpenMPTCProuter VPS version: 0.1026
  - OpenMPTCProuter platform: RPI3

**Comment by Ysurac** [comment]
Try another SD card again, check power supply and temperature.
Check also State->kernel log.

**Comment by AlexFspb** [comment]
I have the same problem on RPI3 with 0.57.3, but it started to be "read only mode" in few days usually.
It was checked with 2 different SD cards

**Comment by Adorfer** [comment]
then check for the 2 remaining points.

**Comment by FermedePommerieux** [comment]
Same problem with a RPI4B 3 hours after upgrade to 0.58.2 from the last 0.57, power supply and temperature as usual.
RW after a reboot

**Comment by starkovv** [comment]
+1

Got the same issue on NanoPI R4S after 3 days from fresh install:
Filesystem is readonly
DNS issue: can't resolve hostname
Version 0.58.5

**Comment by FermedePommerieux** [comment]
This could happen when you install/upgrade with the wrong disk image.

**Comment by Adorfer** [comment]
or the 2 remaining points from above.

**Comment by mvmaksnet** [comment]
@Ysurac  how to check logs?
I am using rpi 3bplus. I made new image and connected 2 usb modems and after I added third after saving it says readonly. Power is not problem here, I have powered usb hub. What can be problem?

**Comment by treyguitar** [comment]
Have the same issue after power cycling, Kernel log says:
[   13.796332] EXT4-fs error (device mmcblk0p2): __ext4_new_inode:1114: comm uci: failed to insert inode 699: doubly allocated?
[   13.811393] EXT4-fs (mmcblk0p2): Remounting filesystem read-only

**Comment by Ysurac** [comment]
You can try (when not read only) to set in System->Mount points, "Check filesystems before mount" and "Run filesystem check" on each partition. This will be the default in next release.
