### ISSUE TITLE
omr-mtu decreasing mtu when not needed

### ISSUE THREAD

**Issue by TheCrach** [Ysurac/openmptcprouter#190]
Hello,

Would be good to add some settings or add extra checks on omr-mtu, it is decreasing the MTU every time there is some downtime on the connection while 1500 is still the best choice, I manually deleted "100% packet loss" from /bin/omr-mtu to avoid that.
Maybe add a previous status variable, if it worked before at 1500 there is no reason to decrease the MTU now

Thank you

**Comment by Ysurac** [comment]
Check is made only when connection is up but I will remove doing the check again if it already give a 1500 MTU before.

**Comment by kapook007** [comment]
my internet pppoe mtu is 1492
but glorytun ifconfig status mtu is 1500 is ok ?

OpenMPTCProuter v0.38 2018-10-11 17:14
