### ISSUE TITLE
V2ray + Wireguard

### ISSUE THREAD

**Issue by dragon2611** [Ysurac/openmptcprouter#1901]
on 0.58, I don't think V2ray is working with wireguard, just get connection refused errors if proxy is set to v2ray

**Comment by Ysurac** [comment]
Only shadowsocks is supported for now with MPTCP over VPN

**Comment by dragon2611** [comment]
Ah ok the reason for trying VPN was I kept getting http timeouts over starlink, wasn't sure if it was the CGN (Haven't got V6 working  yet)  Seems to be something not playing nice with v2ray as switched back to shadowsocks and it's happier now.
