### ISSUE TITLE
Bonding issue with 2 smart phones

### ISSUE THREAD

**Issue by goofguy1** [Ysurac/openmptcprouter#1903]
## Expected Behavior
TetheringWAN and TetheringWAN2 connections should be bonded together in aggregated mode, and not in failover mode

## Current Behavior
TetheringWAN and TetheringWAN2 are running in failover mode, so when WAN goes down WAN2 takes over with a short delay, instead of bonding the connections together. 

## Specifications

  - OpenMPTCProuter version:  OpenMPTCProuter v0.58.1 2021-06-15 04:55
  - OpenMPTCProuter VPS version:  OpenMPTCProuter VPS 0.1024
  - OpenMPTCProuter platform: RPI4/x86_64
![Rasppi multipath problem 2 no bond](https://user-images.githubusercontent.com/85950325/122077857-b0811880-ce2e-11eb-830b-80bd64893191.PNG)

**Comment by Ysurac** [comment]
How do you check that speed is not aggregated ? Did you try using via ssh "omr-test-speed" and check in MPTCP->Bandwidth tab ?

**Comment by goofguy1** [comment]
I was doing an RTMP test with my gopro and simulated a real world disconnect by unplugging a phone from USB tether and also tried ejecting the sim card tray to lose the connection but not the USB tether.

Both times resulted in livestream dropping connection instead of the 2nd phone taking over the load. Resulting in failover instead of aggregation as the signal came back up on the 2nd phone after 3-5 seconds

**Comment by Ysurac** [comment]
So no issues on aggregation, only on failover ?
Check log in State->System log.

**Comment by goofguy1** [comment]
Network bonding/aggregation isn't working, it results in failover

**Comment by Ysurac** [comment]
So did you try test I tell you ?
Did you check also MPTCP support of each WAN ?

**Comment by goofguy1** [comment]
![tethringwan settings](https://user-images.githubusercontent.com/85950325/122084299-48353580-ce34-11eb-8040-454b2fe4b111.PNG)
![tethringwan2 settings](https://user-images.githubusercontent.com/85950325/122084311-4bc8bc80-ce34-11eb-9159-7ed08fa23150.PNG)

Tested both on Enabled | Master + Backup | Master + Enabled | All instances resulted in failover. One sim card in the phone is carrying the other. Not aggregated.

**Comment by goofguy1** [comment]
![ssh test1](https://user-images.githubusercontent.com/85950325/122089735-a4e71f00-ce39-11eb-8e07-3e07d45b7b31.PNG)

**Comment by goofguy1** [comment]
2nd test with both tethering set to Enabled, First one was set to master + backup
![ssh test2 multipath set to enabled](https://user-images.githubusercontent.com/85950325/122090630-8cc3cf80-ce3a-11eb-85b1-44b8e27f53c0.PNG)

**Comment by Ysurac** [comment]
This doesn't seems to be aggregated. Did you check MPTCP support in Network->MPTCP of each WAN ?

**Comment by umekzg** [comment]
Mobile phones are on the same subnet.
DHCP pool is hardcoded in android tethering service.

**Comment by goofguy1** [comment]
> 
> 
> This doesn't seems to be aggregated. Did you check MPTCP support in Network->MPTCP of each WAN ?

I've checked, the settings are followed directly in the documentation



> 
> 
> Mobile phones are on the same subnet.
> DHCP pool is hardcoded in android tethering service.

so I have to swap to modems instead then? I can't use phones?

**Comment by gnosoz** [comment]
Correct, you can use only one android phone per time and the other sim cards must be utilized with simple usb routers that can be found anywhere for 40eur

**Comment by goofguy1** [comment]
> 
> 
> Correct, you can use only one android phone per time and the other sim cards must be utilized with simple usb routers that can be found anywhere for 40eur

Thank you, could you please link a few modems? I live in singapore and its hard to get unlocked modems so I can use worldwide sim cards when I travel to livestream. There's soo many to pick that I don't know which ones are compatible
