### ISSUE TITLE
Unable to update VPS

### ISSUE THREAD

**Issue by kams19** [Ysurac/openmptcprouter#1906]
HI there,

I am getting an error while updating the VPS using the Debian 10 script. I have updated my local router to v58.2 that went pretty smooth. I had restored the config from earlier version backup.

error:
Job for glorytun-tcp@tun0.service failed because a timeout was exceeded.
See "systemctl status glorytun-tcp@tun0.service" and "journalctl -xe" for details.
dpkg: error processing package omr-glorytun-tcp (--configure):
 installed omr-glorytun-tcp package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 omr-glorytun-tcp
E: Sub-process /usr/bin/dpkg returned an error code (1)

![image](https://user-images.githubusercontent.com/75209712/122411707-de747300-cf7c-11eb-94bd-945a3151008b.png)

I have tried running the script thrice with a reboot in between, but the error persists.
Let me know if you need any other logs/output?

**Comment by Ysurac** [comment]
And what do you have using ```journalctl -xe``` on the VPS after running the script ?

**Comment by kams19** [comment]
here are the contents -
Jun 17 14:25:22 localhost systemd[1]: Stopping OMR-Admin...
-- Subject: A stop job for unit omr-admin.service has begun execution
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A stop job for unit omr-admin.service has begun execution.
--
-- The job identifier is 1052.
Jun 17 14:25:25 localhost systemd[1]: omr-admin.service: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The unit omr-admin.service has successfully entered the 'dead' state.
Jun 17 14:25:25 localhost systemd[1]: Stopped OMR-Admin.
-- Subject: A stop job for unit omr-admin.service has finished
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A stop job for unit omr-admin.service has finished.
--
-- The job identifier is 1052 and the job result is done.
Jun 17 14:25:30 localhost systemd[1]: Reloading.
Jun 17 14:25:30 localhost systemd[1]: /lib/systemd/system/fail2ban.service:12: PIDFile= references path below legacy directory /var/run/, updating /var/run/fail2ban/fail2ban.pid → /run/fail2ban/fail2ban.pid;
Jun 17 14:25:30 localhost systemd[1]: Reloading.
Jun 17 14:25:31 localhost systemd[1]: /lib/systemd/system/fail2ban.service:12: PIDFile= references path below legacy directory /var/run/, updating /var/run/fail2ban/fail2ban.pid → /run/fail2ban/fail2ban.pid;
Jun 17 14:25:31 localhost systemd[1]: Reloading.
Jun 17 14:25:31 localhost systemd[1]: /lib/systemd/system/fail2ban.service:12: PIDFile= references path below legacy directory /var/run/, updating /var/run/fail2ban/fail2ban.pid → /run/fail2ban/fail2ban.pid;
Jun 17 14:25:31 localhost systemd[1]: Stopping Shadowsocks-Libev Custom Manager Service for manager...
-- Subject: A stop job for unit shadowsocks-libev-manager@manager.service has begun execution
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A stop job for unit shadowsocks-libev-manager@manager.service has begun execution.
--
-- The job identifier is 1053.
Jun 17 14:25:31 localhost systemd[1]: shadowsocks-libev-manager@manager.service: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The unit shadowsocks-libev-manager@manager.service has successfully entered the 'dead' state.
Jun 17 14:25:31 localhost systemd[1]: Stopped Shadowsocks-Libev Custom Manager Service for manager.
-- Subject: A stop job for unit shadowsocks-libev-manager@manager.service has finished
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A stop job for unit shadowsocks-libev-manager@manager.service has finished.
--
-- The job identifier is 1053 and the job result is done.
Jun 17 14:25:32 localhost systemd[1]: Stopping V2Ray Service...
-- Subject: A stop job for unit v2ray.service has begun execution
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A stop job for unit v2ray.service has begun execution.
--
-- The job identifier is 1054.
Jun 17 14:25:32 localhost systemd[1]: v2ray.service: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The unit v2ray.service has successfully entered the 'dead' state.
Jun 17 14:25:32 localhost systemd[1]: Stopped V2Ray Service.
-- Subject: A stop job for unit v2ray.service has finished
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A stop job for unit v2ray.service has finished.
--
-- The job identifier is 1054 and the job result is done.
Jun 17 14:25:32 localhost systemd[1]: Reloading.
Jun 17 14:25:32 localhost systemd[1]: /lib/systemd/system/fail2ban.service:12: PIDFile= references path below legacy directory /var/run/, updating /var/run/fail2ban/fail2ban.pid → /run/fail2ban/fail2ban.pid;
Jun 17 14:25:33 localhost systemd[1]: Reloading.
Jun 17 14:25:33 localhost systemd[1]: /lib/systemd/system/fail2ban.service:12: PIDFile= references path below legacy directory /var/run/, updating /var/run/fail2ban/fail2ban.pid → /run/fail2ban/fail2ban.pid;
Jun 17 14:25:33 localhost systemd[1]: Reloading.
Jun 17 14:25:34 localhost systemd[1]: /lib/systemd/system/fail2ban.service:12: PIDFile= references path below legacy directory /var/run/, updating /var/run/fail2ban/fail2ban.pid → /run/fail2ban/fail2ban.pid;
Jun 17 14:25:34 localhost systemd[1]: Stopping MLVPN connection to mlvpn0...
-- Subject: A stop job for unit mlvpn@mlvpn0.service has begun execution
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A stop job for unit mlvpn@mlvpn0.service has begun execution.
--
-- The job identifier is 1055.
Jun 17 14:25:34 localhost mlvpn0[693]: killed by signal SIGTERM, SIGQUIT or SIGINT
Jun 17 14:25:34 localhost systemd[1]: mlvpn@mlvpn0.service: Main process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- An ExecStart= process belonging to unit mlvpn@mlvpn0.service has exited.
--
-- The process' exit code is 'exited' and its exit status is 1.
Jun 17 14:25:34 localhost systemd-networkd[535]: mlvpn0: Lost carrier
Jun 17 14:25:34 localhost systemd-networkd[535]: mlvpn0: Failed to read net.ipv6.conf.mlvpn0.disable_ipv6 sysctl property: No such file or directory
Jun 17 14:25:34 localhost systemd-networkd[535]: mlvpn0: Failed to read net.ipv6.conf.mlvpn0.disable_ipv6 sysctl property: No such file or directory
Jun 17 14:25:34 localhost systemd-networkd[535]: mlvpn0: Failed to read net.ipv6.conf.mlvpn0.disable_ipv6 sysctl property: No such file or directory
Jun 17 14:25:34 localhost systemd-networkd[535]: mlvpn0: Failed to read net.ipv6.conf.mlvpn0.disable_ipv6 sysctl property: No such file or directory
Jun 17 14:25:34 localhost systemd[1]: mlvpn@mlvpn0.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The unit mlvpn@mlvpn0.service has entered the 'failed' state with result 'exit-code'.
Jun 17 14:25:34 localhost systemd[1]: Stopped MLVPN connection to mlvpn0.
-- Subject: A stop job for unit mlvpn@mlvpn0.service has finished
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A stop job for unit mlvpn@mlvpn0.service has finished.
--
-- The job identifier is 1055 and the job result is done.
Jun 17 14:25:34 localhost systemd[1]: Reloading.
Jun 17 14:25:34 localhost OMR-Service[71980]: Restart OMR-Admin
Jun 17 14:25:34 localhost systemd[1]: /lib/systemd/system/fail2ban.service:12: PIDFile= references path below legacy directory /var/run/, updating /var/run/fail2ban/fail2ban.pid → /run/fail2ban/fail2ban.pid;
Jun 17 14:25:34 localhost systemd[1]: Started OMR-Admin.
-- Subject: A start job for unit omr-admin.service has finished successfully
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A start job for unit omr-admin.service has finished successfully.
--
-- The job identifier is 1056.
Jun 17 14:25:35 localhost omr-service[711]: /usr/local/bin/omr-service: line 82: echo: write error: Device or resource busy

**Comment by Ysurac** [comment]
I need the same result just after running again vps update script, it should show errors related to Glorytun-TCP.

**Comment by kams19** [comment]
it didnt give errors at Glorytun-TCP this time , it stopped at ubond.

I ran the script again this time without rebooting vps and everything went well in the second go.
