### ISSUE TITLE
No Output, No server IP, No WAN IP, Can't get public IP from ShadowSocks

### ISSUE THREAD

**Issue by Yersi88** [Ysurac/openmptcprouter#1912]
## Expected Behavior

openmptcprouter displays green checkmark next to VPS

## Current Behavior

Everything actually appears to be working as expected but, Network Overview claims "No Output" next to VPS:
![image](https://user-images.githubusercontent.com/77145281/122790064-dd5e8100-d2af-11eb-8fed-5e731caf3f67.png)

DNS not working, browser not resolving web pages unless DNS is manually configured in windows.
I don't even know what this means. Please help

## Specifications

  - OpenMPTCProuter version: 0.57.3 
  - OpenMPTCProuter VPS version: VPS 0.1024
  - OpenMPTCProuter platform: x86_64

**Config:**

**Comment by Yersi88** [comment]
Correction, everything is not working. DNS not working, browser not resolving web pages unless DNS is manually configured in windows.

**Comment by Ysurac** [comment]
Update to latest release.

**Comment by Yersi88** [comment]
> Update to latest release.

Same after updating both router (restoring config) and vps + vps reboot

**Comment by Ysurac** [comment]
You should do a fresh VPS install because all your keys/VPS IP are public now, you didn't remove them before the past.
What is your country ? You are not in a country where shadowsocks can be blocked ?
Ports are open on VPS side ? Did you try with only one WAN ?
You can try another proxy by checking advanced setting box in wizard page.

**Comment by Yersi88** [comment]
> You should do a fresh VPS install because all your keys/VPS IP are public now, you didn't remove them before the past.
Haha That's a woopsie, I did fresh install now!
> What is your country ? You are not in a country where shadowsocks can be blocked ?
UK
> Ports are open on VPS side ? Did you try with only one WAN ?
> You can try another proxy by checking advanced setting box in wizard page.

It appears to be working correctly now. I reinstalled the router again and this time I didn't import my old config  but set everything up manually. Might be some weirdness in my old config but I don't really know why cause it was working good until today! 

Anyway, thank you very much for support. I really appreciate when you're doing here <3
