### ISSUE TITLE
No server IP, No public IP, Can't get public IP from ShadowSocks

### ISSUE THREAD

**Issue by Yersi88** [Ysurac/openmptcprouter#1916]
## Expected Behavior
Green checkmark next to VPS

## Current Behavior

Similar issue experienced yesterday on old version of OpenMPTCPRouter. 
![image](https://user-images.githubusercontent.com/77145281/122942515-2c6aeb80-d36e-11eb-8d37-4428d6f500ec.png)

Dashboards never loads
![image](https://user-images.githubusercontent.com/77145281/122942796-5de3b700-d36e-11eb-8cc0-f9703ba89f60.png)

DHCP + DNS not working on local network.

## Specifications

  - OpenMPTCProuter version: 0.58.4
  - OpenMPTCProuter VPS version: 0.1028 5.4.100-mptcp
  - OpenMPTCProuter platform: x86_64

**Comment by Yersi88** [comment]
**### Update:** 

When I installed new version of Router I made backup of default config. Restoring default config and setting up manually made the problem go away. 

Very strange, any idea what might be causing this?

**Comment by Ysurac** [comment]
Check State->System log

**Comment by Yersi88** [comment]
> Check State->System log

I will create log if it happens again! I don't think it will take long :(

**Comment by goggles24** [comment]
+1 I'm also seeing this. I will grab a log next time it occurs again.
I am also with Hostworld for my VPS, could be a factor.

**Comment by Yersi88** [comment]
I can confirm that this issue didn't manifest itself anymore.
