### ISSUE TITLE
Stabilize connection

### ISSUE THREAD

**Issue by ImprezyLive** [Ysurac/openmptcprouter#1927]
## Expected Behavior

I got 1 connection via cable (100/100Mb/s) and 4 modems LTE.
Bandwidth used is 6Mb/s, live stream.

Typing ping is 9-11ms via cable. 

## Current Behavior

But some times ping is 150ms.
I don't understand why Master device is changed from cable connection to modems.

Wed Jun 30 09:31:03 2021 user.notice post-tracking-post-tracking: Change master interface from wan3 (173 ms) to wan1 (38 ms)
Wed Jun 30 09:31:17 2021 user.notice post-tracking-post-tracking: Change master interface from wan1 (1000 ms) to wan4 (177 ms)
Wed Jun 30 09:31:39 2021 user.notice post-tracking-post-tracking: Change master interface from wan4 (330 ms) to wan2 (159 ms)
Wed Jun 30 09:33:55 2021 user.notice post-tracking-post-tracking: Change master interface from wan2 (147 ms) to wan1 (28 ms)
Wed Jun 30 09:35:06 2021 user.notice post-tracking-post-tracking: Change master interface from wan1 (228 ms) to wan3 (46 ms)
Wed Jun 30 09:36:52 2021 user.notice post-tracking-post-tracking: Change master interface from wan3 (164 ms) to wan1 (26 ms)
Wed Jun 30 09:38:03 2021 user.notice post-tracking-post-tracking: Change master interface from wan1 (229 ms) to wan3 (49 ms)
Wed Jun 30 09:39:47 2021 user.notice post-tracking-post-tracking: Change master interface from wan3 (155 ms) to wan1 (28 ms)
Wed Jun 30 09:40:59 2021 user.notice post-tracking-post-tracking: Change master interface from wan1 (228 ms) to wan3 (51 ms)

64 bytes from aafc88a28d9997374.awsglobalaccelerator.com (99.83.207.202): icmp_seq=201 ttl=115 time=13.2 ms
64 bytes from aafc88a28d9997374.awsglobalaccelerator.com (99.83.207.202): icmp_seq=202 ttl=115 time=9.70 ms
64 bytes from aafc88a28d9997374.awsglobalaccelerator.com (99.83.207.202): icmp_seq=203 ttl=115 time=11.2 ms
64 bytes from aafc88a28d9997374.awsglobalaccelerator.com (99.83.207.202): icmp_seq=204 ttl=115 time=9.17 ms
64 bytes from aafc88a28d9997374.awsglobalaccelerator.com (99.83.207.202): icmp_seq=205 ttl=115 time=10.3 ms
64 bytes from aafc88a28d9997374.awsglobalaccelerator.com (99.83.207.202): icmp_seq=206 ttl=115 time=10.9 ms
64 bytes from aafc88a28d9997374.awsglobalaccelerator.com (99.83.207.202): icmp_seq=207 ttl=115 time=10.8 ms
64 bytes from aafc88a28d9997374.awsglobalaccelerator.com (99.83.207.202): icmp_seq=208 ttl=115 time=9.79 ms
64 bytes from aafc88a28d9997374.awsglobalaccelerator.com (99.83.207.202): icmp_seq=209 ttl=115 time=9.32 ms
64 bytes from aafc88a28d9997374.awsglobalaccelerator.com (99.83.207.202): icmp_seq=210 ttl=115 time=19.1 ms
64 bytes from aafc88a28d9997374.awsglobalaccelerator.com (99.83.207.202): icmp_seq=211 ttl=115 time=11.9 ms
64 bytes from aafc88a28d9997374.awsglobalaccelerator.com (99.83.207.202): icmp_seq=212 ttl=115 time=10.9 ms
64 bytes from aafc88a28d9997374.awsglobalaccelerator.com (99.83.207.202): icmp_seq=213 ttl=115 time=12.3 ms
64 bytes from aafc88a28d9997374.awsglobalaccelerator.com (99.83.207.202): icmp_seq=214 ttl=115 time=10.5 ms

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Context (Environment)

Master interface is set to dynamic.
How get better and stable connection?

## Specifications

  - OpenMPTCProuter version: 0.58.2
  - OpenMPTCProuter VPS version: 0.1026
  - OpenMPTCProuter platform: RPI4

**Comment by Ysurac** [comment]
Ping use VPN, you can try another VPN in System->OpenMPTCProuter, wizard tab, advanced settings checkbox.
