### ISSUE TITLE
where is the config backup/restore?

### ISSUE THREAD

**Issue by hairy-dog** [Ysurac/openmptcprouter#1930]
## Expected Behavior
I want to restore a config backup I made

## Current Behavior
I can't remember where to go to load this backup
The backup on the server is corrupt, so I can't use that.

## Specifications

  - OpenMPTCProuter version: 0.58.4
  - OpenMPTCProuter VPS version: 10.26.54.100
  - OpenMPTCProuter platform: rpi4

**Comment by Ysurac** [comment]
In System->Backup / Flash firmware menu, Restore section.

**Comment by hairy-dog** [comment]
Oddly, when I was having problems (which led to reinstalling) it wasn't there! But it is there now, thank goodness.
