### ISSUE TITLE
Partition size

### ISSUE THREAD

**Issue by zabinskiwojciech** [Ysurac/openmptcprouter#1936]
## Expected Behavior
Is it possible to increase the partition of this router because I have 64MB on sda1 and 512MB on sda2 and the disk still has a lot of free.
I tried different ways but it failed, my machine is X64 server 2 x Xeon 12GB Ram HDD 500GB

## Specifications

  - OpenMPTCProuter version: openmptcprouter v0.57.3 r0
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
Duplicate of https://github.com/Ysurac/openmptcprouter/issues/1582
So use extroot like in OpenWrt doc or make a new image.
