### ISSUE TITLE
Port forwarding

### ISSUE THREAD

**Issue by Magnum1981** [Ysurac/openmptcprouter#1937]
## Expected Behavior
I have  an edgrouter behind the openmptcp router and a switch connected to the edgerouter. The switch is where all the devices I use at home including my NAS is connected. I want to forward all ports to the edgerouter so that I can access the apps on the NAS device . The edgerouter is currently in dhcp mode and it is issuing up addresses to all the devices. I just don't know how to go about achieving this because the apps on the NAS device have different ports and without knowing how to port forward I can't have access to them. 
I want a simple method of access the apps/dockers on my openmptcp router. I don't mind removing the edgerouter and just connecting a switch to the openmptcp router if that will solve the problem. 

## Specifications

  - OpenMPTCProuter version: 0.57.3
  - OpenMPTCProuter VPS version:  Vultr vps
  - OpenMPTCProuter platform: x86

**Comment by Ysurac** [comment]
You can redirect all ports (1-64999) using firewall but it's not a really good idea because traffic (legit or not) will go from VPS to the router and use bandwidth. You should really redirect only needed port using OpenMPTCProuter firewall.
