### ISSUE TITLE
Are there any easy way to get status of aggregate server, ethX current speed，etc. 

### ISSUE THREAD

**Issue by zxwanghongyi** [Ysurac/openmptcprouter#1943]
I want to get these status and display on my 1602lcd screen, are there any built in ways to get them?

**Comment by Ysurac** [comment]
Infos are available via ubus but you will need to do a script yourself for this screen.

**Comment by zxwanghongyi** [comment]
Thank you! I'm gonna look in to that, can you give a example of using ubus to show status of aggregate server connection and current download or upload speed of eth1?

**Comment by Ysurac** [comment]
For ubus doc: https://openwrt.org/docs/techref/ubus
For speed I don't think it's available directly, you may need to calculate it yourself.

**Comment by zxwanghongyi** [comment]
Thank you! I manage to get all the data I want from ubus and calculated the speed
