### ISSUE TITLE
Supermicro Atom board

### ISSUE THREAD

**Issue by gitxmax** [Ysurac/openmptcprouter#1950]
Hello,
I'm looking at low TDP boards out there and came across Supermicro A1SAM-2750F server board, which has Atom  C2550 8core-8 threads, Quad GbE LAN ports. It's for sale locally, for around $50 (minus Ram), so really tempting.
Just want to check, if there can be ay potential problems running the openmptcprouter on it, since the hardware is rather "exotic".
Thank you

**Comment by Ysurac** [comment]
Should work and CPU have AES-NI support that will help.
LAN ports should be supported by igb kernel module that is installed by default on OpenMPTCProuter.

**Comment by gitxmax** [comment]
Great then. I will certainly have more questions, when I receive it.
Thanks again
