### ISSUE TITLE
Second WAN aren't reachable by openmptcprouter

### ISSUE THREAD

**Issue by xillibit** [Ysurac/openmptcprouter#1955]
## Expected Behavior

The second wan should be reachable by openmptcprouter

## Current Behavior
I have done a clean install of openmptcprouter 0.58.5, the second isn't reachable by openmptcprouter. If i connet directly my PC on the huawei router, i can access the web interface on his IP: 192.168.8.1

![image](https://user-images.githubusercontent.com/876395/125588701-1f5864f7-b00f-4c5a-8a93-9032e8b62d1f.png)

## Specifications

  - OpenMPTCProuter version: 0.58.5
  - OpenMPTCProuter VPS version: 0.1026
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
wan2 is a macvlan interface ?
192.168.8.1 can be pinged or blocked by huawei modem ?

**Comment by xillibit** [comment]
It was macVLAN by default for wan2 and other wan, i don't changed it

I don't know why huawei B715-23c should block is own ip 192.168.8.1, i will try to connect a pc on huawei to check on the web interface

**Comment by xillibit** [comment]
I had disconnected the huawei router and reconnected now, it's works : 

![image](https://user-images.githubusercontent.com/876395/126870853-07171b3f-8978-4e61-8a84-c647720ecd87.png)
