### ISSUE TITLE
Multipath seems to be blocked on specific router only

### ISSUE THREAD

**Issue by GTiDon** [Ysurac/openmptcprouter#1985]
![image](https://user-images.githubusercontent.com/51342593/127003317-7aaee4f9-67f9-4e05-b24e-26296f140257.png)

Hello

I have this error only on my Mikrotik Router R11e
On my other Mikrotik SXT LTE routers I dont have this problem with the same Sim card

Does anyone know what configuration in the RouterOS setting can cause this problem?
I have tried with firewall disabled and reset to defaults. I still cant get connected

Thanks

**Comment by GTiDon** [comment]
Everytime I see this error the whois address is incorrect. It seems to pull from one of the other routers.

I suspect some sort of DNS issue?

**Comment by Ysurac** [comment]
Please use the template when you open an issue.
If you are on latest release, the check use interface detected public IP. Delay are possible before data is updated.
It's not related to DNS, and it's only a warning. If all is working there is no issues.
