### ISSUE TITLE
OpenMPTCPRouter slow Name Resolving?

### ISSUE THREAD

**Issue by xemles** [Ysurac/openmptcprouter#1986]
Hello,
I'm having troubles understanding why OpenMPTCPRouter is doing that to me:
Whenever I try to go to a website or anything, it takes sometimes up to 20 seconds to actually load it, or I might even have to start the request again.

I was wondering if there was anything to tweak regarding that because that's a really annoying issue... The speed is there, the ping averages 30-50ms on each of my 4Gs (there are 3), yet it seems like I have missed something.

The only settings I changed after reconfiguring, since I thought that was my issue, is switching Glorytun TCP to MLVPN since I had troubles with Discord.

I believe it's something related to DNS but DNS in a router are such an unknown thing to me...

So if anybody was able to help me, that'd be appreciated, thanks!

## Specifications

  - OpenMPTCProuter version: 0.58.5
  - OpenMPTCProuter VPS version: 0.1026
  - OpenMPTCProuter platform: Linksys WRT3200ACM

EDIT: Btw, here's what I mean when I say "the speed is there" [https://www.speedtest.net/result/11786878749](url)

**Comment by Ysurac** [comment]
For DNS, root servers DNS are used by default and this use VPN as it's UDP traffic in most cases.
Check that you don't have a WAN that announce it's own DNS if set as DHCP in Network->Interfaces if you didn't use the wizard to set them.
If it's not the case, you can set another DNS in Network->DHCP&DNS and remove "127.0.0.1#5353". Don't use "8.8.8.8, 4.4.4.4,1.1.1.1,..." as they are used by OMR-Tracker and this can give some strange result.

**Comment by xemles** [comment]
![image](https://user-images.githubusercontent.com/13338602/127771093-b1ab8da6-6647-436d-9ef4-cb94e83d1616.png)
Still seems to be the same, I have to refresh multiple times until it works...
The first case scenario didn't seem to apply so I did the second with these DNS
![image](https://user-images.githubusercontent.com/13338602/127771106-627195be-87af-408f-be20-9a003f24d641.png)
Yet it seems to make no difference

**Comment by Ysurac** [comment]
Check DNS used by your computer client.
Check also that DNS is always up in State->System log
