### ISSUE TITLE
Weird ping behavior

### ISSUE THREAD

**Issue by milankragujevic** [Ysurac/openmptcprouter#1988]
## Expected Behavior
Ping is constant.

## Current Behavior
Ping is relative constant but every few hours or so it will change to either be ~10ms or ~20ms. It then stays stable for some time at that number then changes again.

### Graph

![image](https://user-images.githubusercontent.com/7611163/127345109-cf63ed50-331c-4ff3-a658-59ebbd3b646c.png)

## Specifications

  - OpenMPTCProuter version: v0.58.5
  - OpenMPTCProuter VPS version: v0.1026
  - OpenMPTCProuter platform: RPI4B

**Comment by Ysurac** [comment]
Ping is always low priority. Changes can be due to own OpenMPTCProuter tests.
You can change VPN using advanced settings checkbox in wizard to sometimes have a stablest ping.
