### ISSUE TITLE
VPS multiple IP setup

### ISSUE THREAD

**Issue by SonicSteel** [Ysurac/openmptcprouter#1993]
## Expected Behavior
Attempting to set up multiple IP’s as shown in https://github.com/Ysurac/openmptcprouter/wiki/VPS-Multi-IPs

## Current Behavior
I am unsure of what method to use to get this option to come up automatically as shown in the wiki. I have a VPS hosted on OVH which I can assign multiple IP’s to.  Or if this can be set up manually.
VPS has a single NIC, /etc/network/interfaces is set for eth0 and eth0:0 to have different public IP’s
It is currently working great (though a bit slow) with a single IP.

## Specifications

  - OpenMPTCProuter version: 0.58.5
  - OpenMPTCProuter VPS version: current Debian 10 x86_64 version (pulled within last 12 hours)
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
IPs need to be configured before omr-admin is started on the VPS, so at boot. Then you can save&apply wizard again to get all you need on the router.

**Comment by SonicSteel** [comment]
I did a fresh install all around, this time configuring the additional IP's before running the VPS script.
Currently there are 10 additional IP's on the VPS (0.1026 5.4.100-mptcp)
I did the reboot after the script, connected a fresh install of OMR (0.58.5) to the VPS, and shadowsocks still only shows the default single rule
Remote Servers lists the same server twice as sss0 (enabled) and sss1 (disabled)

**Comment by Ysurac** [comment]
I will make tests.

**Comment by SonicSteel** [comment]
Just to add, I'm not sure if it's making the difference, but I have ifupdown2 installed.

I also tried 3 methods (separately) of attaching the IP's via /etc/network/interfaces:

```
iface eth0 inet static
    address x.x.x.x/32
    gateway x.x.x.x
    up   ip addr add x.x.x.x/32 dev $IFACE label $IFACE:0
    down ip addr del x.x.x.x/32 dev $IFACE label $IFACE:0
    up   ip addr add x.x.x.x/32 dev $IFACE label $IFACE:1
    down ip addr del x.x.x.x/32 dev $IFACE label $IFACE:1
```


```
auto eth0
allow-hotplug eth0
iface eth0 inet static
    address x.x.x.x/32
    gateway x.x.x.x

auto eth0:0
allow-hotplug eth0:0
iface eth0:0 inet static
    address x.x.x.x/32
```
    
  
```
auto eth0
allow-hotplug eth0
iface eth0 inet static
    address x.x.x.x/32
    gateway x.x.x.x

iface eth0 inet static
    address x.x.x.x/32

iface eth0 inet static
    address x.x.x.x/32
```

**Comment by Ysurac** [comment]
All IPs are public IPs ?

**Comment by SonicSteel** [comment]
Yes, all IP’s are public, and pingable when configured.
They are the additional IP’s you can order through OVH

**Comment by SonicSteel** [comment]
Just an update, I started using the image for 0.56.5 and it was working as expected.  I'll also do some additional testing with different versions.

**Comment by Ysurac** [comment]
I just tested on latest release on a fresh install and it's working as expected.

**Comment by SonicSteel** [comment]
I’ll give it another shot, having some trouble now with shadowsocks not starting
Is there a limit to additional IP’s that I’m passing maybe?

**Comment by SonicSteel** [comment]
With an excessive number of IP's, it seems to cause problems with the shadowsocks config.
A fresh install of 0.58.5 still doesn't pick up the additional IP's (testing with 17 total), but connecting 0.57.3 to the same VPS and it appears to work for me.
I'm not sure what I'm doing differently than you are, but unless there's features or stability in 0.58.5 that I'm missing out on, I think this will work for me for now.
