### ISSUE TITLE
Low quality LTE connection

### ISSUE THREAD

**Issue by ImprezyLive** [Ysurac/openmptcprouter#1996]
## Expected Behavior
I got low quality connection, ping is more like 60ms but some time is more like 1000ms.
Upload connection is 3-4 Mb/s, download lower <2 Mb/s, i got 3 modems, system restart connection every 15-30 seconds.

staying connected despite temporary problems

## Specifications

  - OpenMPTCProuter version: 
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter platform:  RPI4

**Comment by Ysurac** [comment]
Use the most stable connection as master.

**Comment by ImprezyLive** [comment]
Every connection is unstable, pings run from 60 ms to 20000ms.
Will speed limit help?
