### ISSUE TITLE
/proc/sys/net/ipv4/ip_forward   Zero at startup

### ISSUE THREAD

**Issue by highfreq** [Ysurac/openmptcprouter#1999]
I have /proc/sys/net/ipv4/ip_forward at zero after boot. My lan can't go outside untill i place ip_forward at 1.

How can i change default so that lan can reach outside by default?

Thank you

**Comment by Ysurac** [comment]
/proc/sys/net/ipv4/ip_forward is always set to 1. Please use template.

**Comment by highfreq** [comment]
I understand but what if now at each start it is at zero, is it possible to make it default to 1 again?

**Comment by Ysurac** [comment]
It's set via ```/etc/sysctl.d/10-default.conf```

**Comment by highfreq** [comment]
Thank you very much!!!
