### ISSUE TITLE
Add option to use VPN for UDP and ICMP

### ISSUE THREAD

**Issue by Ysurac** [Ysurac/openmptcprouter#20]
Add an option to enable or disable the use of the tunnel for UDP and ICMP when available.

**Comment by Ysurac** [comment]
In fact, VPN will be used for anything that is not TCP when it's up by default.

**Comment by Ysurac** [comment]
It's available since OpenMPTCProuter 0.12.1

**Comment by SPYFF** [comment]
Where can I find that option?

**Comment by Ysurac** [comment]
In the wizard, advanced setting, you can choose the VPN used or none.

**Comment by SPYFF** [comment]
Thank you!
