### ISSUE TITLE
An error message during the VPS installation 

### ISSUE THREAD

**Issue by jchuang1977** [Ysurac/openmptcprouter#2006]
## Expected Behavior
Install VPS should success without failure message.

## Current Behavior
But there is an error message during installation.

Setting up libonig5:amd64 (6.9.4-1) ...
Setting up python3-websockets (8.1-1) ...
Setting up python3-wsproto (0.15.0-3) ...
Setting up libjq1:amd64 (1.6-1ubuntu0.20.04.1) ...
Setting up jq (1.6-1ubuntu0.20.04.1) ...
Setting up python3-uvicorn (0.11.5-1) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
**-- pip3 install needed python modules
ERROR: netjsonconfig 0.9.1 has requirement jinja2<3.0,>=2.9, but you'll have jinja2 3.0.1 which is incompatible.**
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  omr-vps-admin
0 upgraded, 1 newly installed, 0 to remove and 11 not upgraded.
Need to get 21.2 kB of archives.
After this operation, 158 kB of additional disk space will be used.
Get:1 https://repo.openmptcprouter.com buster/main amd64 omr-vps-admin all 0.3+20210508 [21.2 kB]

## Possible Solution
I don't know.

## Steps to Reproduce the Problem
I run the script in my linode VPS ubuntu 20.04.

  1.    wget https://www.openmptcprouter.com/server/ubuntu20.04-x86_64.sh
  2.    sh ubuntu20.04-x86_64.sh
  3.

## Context (Environment)
It maybe affect the OMR router to working good.

## Specifications

  - OpenMPTCProuter version:  no
  - OpenMPTCProuter VPS version:     OMR_VERSION="0.1026"
  - OpenMPTCProuter platform:  no

**Comment by Ysurac** [comment]
This doesn't affect anything.
