### ISSUE TITLE
Issues with virtualbox

### ISSUE THREAD

**Issue by cro888888** [Ysurac/openmptcprouter#2007]
I had each IP limited at 50Mbps, I got two network cards, whenever I activate two cards at same time when I go 192.168.0.99(lan) on browser it stucks on 192.168.0.99 not entering 192.168.0.99/cgi-bin/luci.

And I cant load dashboard cuz boardinfo.release is undefined

And is it possible to use it without VPS? Or maybe set it up locally? And is single physical card with multiple virtual cards possible? Is that what MacVLAN does?

Update: pinging into VM works, pinging from VM doesn't

Here comes some screenshots
![set1](https://user-images.githubusercontent.com/25526755/128018099-7bb5c7e9-57e8-4f1a-adca-889ea48cf1e2.PNG)
![over1](https://user-images.githubusercontent.com/25526755/128018134-8577ddd7-8519-457b-967e-87d86cff4c60.PNG)

**Comment by Ysurac** [comment]
Please use the template.
Check that you use a bridge access and that you can ping lan ip.
VPS is needed to aggregate speed, without a VPS OpenMPTCProuter do some load balancing. The VPS must be somewhere where speed to internet is more than aggregated speed you can have, can't be local.
You often don't need macvlan in a vm, only create network card you need and bridge them. If you want to use macvlan on VM, set netword card as promiscuous.

**Comment by cro888888** [comment]
Ping into VM works, the other way doesn't
