### ISSUE TITLE
6in4 permission denied

### ISSUE THREAD

**Issue by zulu14** [Ysurac/openmptcprouter#2010]
## Expected Behavior
hello yannick, IPV6 6IN4 not working , but the interface are UP , the ipv4 tunnel are OK, proxy (SS) are OK 

## Current Behavior
ping 6in4-omr6in4 -> omr-6in4-user0: OK

ping omr-6in4-user0 -> 6in4-omr6in4: 100%packet loss or "invalid argument" if i not specifiy the interface in ping

ping  6in4-omr6in4 -> google ipv6 (ipv6 not domain) permission denied (user as root and try with sudo (seem to be a network denied)

## Specifications

  - OpenMPTCProuter version: 0.58.5
  - OpenMPTCProuter VPS version: 1026
  - OpenMPTCProuter platform: X86

![image](https://user-images.githubusercontent.com/71033768/128432972-33e08232-c631-46f5-a977-3fd72b73771d.png)
![image](https://user-images.githubusercontent.com/71033768/128432990-541777bd-028f-4323-ab3c-19497d596fe5.png)
![image](https://user-images.githubusercontent.com/71033768/128433023-b1eb0b20-7676-416c-a2b8-86c97143f729.png)
![image](https://user-images.githubusercontent.com/71033768/128433211-d3f416ae-2828-4faa-8ec2-5c591acc92bf.png)

**Comment by Ysurac** [comment]
IPv6 is enabled in wizard ?

**Comment by zulu14** [comment]
hello yannick, yes the ipv6 is enabled, in syslog we have the omr-6in4 log say its enabled

**Comment by zulu14** [comment]
have you already get the "permission denied" error when you dev the 6in4 system ?

**Comment by Ysurac** [comment]
What tis the result of ```ip -6 a``` and ```ip -6 r``` on the router via SSH ?
Check also that omr-6in4 is in correct firewall zone (vpn zone)

**Comment by zulu14** [comment]
6in4 are in VPN zone 
![image](https://user-images.githubusercontent.com/71033768/128508006-1c2793d9-504b-4e6a-81a5-9c64a5828ad2.png)

**Comment by zulu14** [comment]
i have this in log: 
![image](https://user-images.githubusercontent.com/71033768/128508624-aa9f5662-7e5a-4387-92e4-f9a066a667c6.png)

**Comment by zulu14** [comment]
(lan0 is a mcvlan of eth1)

**Comment by Ysurac** [comment]
There is no public/lan ipv6 on lan
check Network->Interfaces, LAN, DHCP Server tab, IPv6 settings

**Comment by zulu14** [comment]
![image](https://user-images.githubusercontent.com/71033768/128508961-fa7e6d6a-145c-476d-b482-5f32612f5226.png)

**Comment by Ysurac** [comment]
Seems to be ok, what you have in Network->Interfaces, Global network options tab as ULA-Prefix ?

**Comment by zulu14** [comment]
empty

**Comment by zulu14** [comment]
![image](https://user-images.githubusercontent.com/71033768/128509483-640b41cc-9ba1-452d-8834-8ed944c3b399.png)

**Comment by Ysurac** [comment]
It's the problem.
You should set something like "fd53:8a41:3f89::/48"

**Comment by zulu14** [comment]
okay, i have only 1 ipv6 from the vps,

i setup like this: 
![image](https://user-images.githubusercontent.com/71033768/128510195-8d075844-1b41-41ac-b689-c1f0d7841678.png)


if i ping test : 
![image](https://user-images.githubusercontent.com/71033768/128510391-5c65627e-e1aa-4054-8b55-e34bae96f3c4.png)

**Comment by zulu14** [comment]
(shorewall6 are OK and running )
ping ipv6.google.com on server side are OK

**Comment by Ysurac** [comment]
Check that you get an IPv6 on lan interface. If not, reboot.

**Comment by zulu14** [comment]
after reboot:

![image](https://user-images.githubusercontent.com/71033768/128511378-3bb5e79b-1765-4865-b1d1-d947d04790c2.png)


and same ping behavior

**Comment by Ysurac** [comment]
What do you have in "ip -6 r" now ? What is the default ipv6 route ?

**Comment by zulu14** [comment]
(tunnel: glorytun-TCP , proxy: SS , all wan are OK, proxy are OK, tunnel OK)

![image](https://user-images.githubusercontent.com/71033768/128512907-a885ae86-0e34-45ec-9d81-39618f68ec9a.png)

**Comment by zulu14** [comment]
PING Test:
![image](https://user-images.githubusercontent.com/71033768/128513197-4f6d4519-7e79-4e25-bbf6-62dc3a8127df.png)

**Comment by Ysurac** [comment]
Default IPv6 route seems to be missing

**Comment by Ysurac** [comment]
Route should be added via ```/bin/omr-6in4``` script. Doesn't seems to work in your case. I will check why...

**Comment by Ysurac** [comment]
What is the result of ```logread | grep omr6in``` ? (to check if script is sometimes running or not)
If empty, what is the result of ```/bin/omr-6in4``` ?

**Comment by zulu14** [comment]
hello yannick , sorry for the delay, 
after checking, 6in4 bin file are empty !, i download it from the feeds (probably a missclick from me :/ ) 

the "permission denied" disapear and now its accept the ping, but he have no answer (100% packet loss)

**Comment by zulu14** [comment]
hello yannick , sorry for the delay, 
after checking, 6in4 bin file are empty !, i download it from the feeds (probably a missclick from me :/ ) 

the "permission denied" disapear and now its accept the ping, but he have no answer (100% packet loss)

**Comment by zulu14** [comment]
he said in log (only one time): user.notice omr6in4: Set network for OMR 6in4 to local 10.255.255.2 peer 10.255.255.1

**Comment by zulu14** [comment]
hello yannick little up

**Comment by Ysurac** [comment]
I don't understand how you can have some empty file on your installation... What did you really do ?

**Comment by zulu14** [comment]
we have build from feeds (fork) and i check the commit, i have make a mistakes and i have deleted this files , its now fixed
but i have 100% packet loss

**Comment by Ysurac** [comment]
I don't support fork...
Check "ip r" and set default route.
