### ISSUE TITLE
Unable to install pihole as a non root user

### ISSUE THREAD

**Issue by storm1er** [Ysurac/openmptcprouter#2015]
## Expected Behavior

The pihole installation script work when not executed as root user.

## Current Behavior

On vps, execute `wget -O - http://www.openmptcprouter.com/server/omr-pihole.sh | sh` as a basic user.
![image](https://user-images.githubusercontent.com/9821946/128599081-ee9e0c87-86fe-455b-a5d0-094e6e11d3a2.png)

## Possible Solution

Add a check to the script so the user won't have to play the script again.

## Steps to Reproduce the Problem

Execute the vps script as dummy user.

## Context (Environment)

debian9

## Specifications

  - OpenMPTCProuter version: 0.58.5
  - OpenMPTCProuter VPS version: 0.1026
  - OpenMPTCProuter platform: RPI4

**Comment by Ysurac** [comment]
I just added a check that it's really launched as root user. Will be updated with CDN refresh.
