### ISSUE TITLE
Cannot access at 192.168.100.1

### ISSUE THREAD

**Issue by keisuke-na** [Ysurac/openmptcprouter#2019]
I used RPi4B.
I tried installation on document but not work.
Cannot access at 192.168.100.1 orz
I can see "This site can’t be reached" on my browser.

**Comment by Ysurac** [comment]
Check that you get an IP via DHCP on your client computer in 192.168.100.x. If not set a static IP in this network (not 192.168.100.1 already used by the router).

**Comment by keisuke-na** [comment]
RPi4B cannot get an 192.168.100.x. 
Should I install to VPS before access at 192.168.100.1?

**Comment by Ysurac** [comment]
OpenMPTCProuter have a fixed 192.168.100.1 and it's also a DHCP server that give IP on 192.168.100.x network.
When you set it cannot get an 192.168.100.x IP, you attached a screen to check that ?

**Comment by keisuke-na** [comment]
mmm...
Like this.
https://photos.app.goo.gl/9R4DKyvAmHtQBEKYA
What shoud I fix...

**Comment by Ysurac** [comment]
Make sure you used correct image to flash the sd card, then connect a computer to the RPI via ethernet cable directly.
Then check IP of your computer.

**Comment by keisuke-na** [comment]
oh...I misunderstood. 
I use correct image to flash the sd card.
But Can i ask that why dose RPi4B need ethernet?
I dont have ethernet... orz

**Comment by Ysurac** [comment]
RPI4 only listen on ethernet port by default.
Default user is "root" with empty password.

**Comment by keisuke-na** [comment]
Which mean MPTCProuter can't use the internet outside?
I want to try 4K streaming  from outside to Youtube with OBS.

**Comment by Ysurac** [comment]
I don't understand what you mean. OpenMPTCProuter is a router, so it route traffic. RPI have only one internet port so it must be connected to an ethernet switch. Wifi can be used as client or AP, but RPI wifi is often really bad.

**Comment by keisuke-na** [comment]
I have bad English. Im sorry.
Maybe I have misunderstood.
I've thought  that MPTCProuter has high speed features as internet connection when it has many 4G connection...

**Comment by Ysurac** [comment]
Yes OpenMPTCProuter aggregate internet connections.

**Comment by keisuke-na** [comment]
Can I use MPTCProuter outside as mobile hotspot??

**Comment by Ysurac** [comment]
Yes, but for configuration at least you need an ethernet cable.

**Comment by gsxryan** [comment]
RPI4 port will start as the default configuration port, plug your computer directly into the PI4 NIC.  You'll need a VLAN enabled switch to connect the PI4 to, and set your VLANS on the switch before enabling them on the RPI4. 

I plan to put together a video demonstrating how i set mine up soon.

FYI: Plan for these limits;
Wifi <200Mb
USBEth+PI4ETH: 300Mb
Eth+VLANs switch: 900Mb

**Comment by keisuke-na** [comment]
@Ysurac 
mmm... 
I cannot use MPTCProuter without ethernet cable as mobile hotspot, right?

**Comment by Ysurac** [comment]
@keisuke-na as I already said you can. But for first configuration you need to use a cable.

**Comment by keisuke-na** [comment]
Ok. I understand.
Thanks for advice!
