### ISSUE TITLE
some problems with debian 9.4 for VPS endpoint

### ISSUE THREAD

**Issue by dmnk** [Ysurac/openmptcprouter#202]
i've tried to use a debian-9.4-x86_64 but get stuck pretty soon.

packets have to be installed manually:

- libev-dev
- libsodium-dev

after that at least the debian9-x86_64-mlvpn.sh script runs till the end and presents the keys.

mlvpn.network file isn't in place, mlvpn_updown.sh is missing as well.

therefore on start of mlvpn no interface is created.

even when the two files are put in place by hand, the interface appears, but doesn't get an ip, nor does it provide dhcp leases for the connected openmptcprouter (the connections on L2 seem to work, as there are a lot keep-alive packets, when started manually with console output)

**Comment by joshuaeb09** [comment]
Debian 9.4 is not the latest stretch release.  Make sure you have the stretch base, security, and backport repos enabled, apt-get update, and then apt-get dist-upgrade.  Once completed reboot into your updated box before running the setup script. 

Here's an example from one of my testing VPS's, you can ignore the cloudmontoring repo as that is just the monitoring agent from the VPS provider.  Obviously you want to use the debain mirrors closest to your VPS's geographical location or if your provider has up-to-date mirrors those. 

root@mptcp-server:~# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.5 (stretch)
Release:        9.5
Codename:       stretch

root@mptcp-server:~# cat /etc/apt/sources.list
deb http://mirror.rackspace.com/debian stretch main
deb-src http://mirror.rackspace.com/debian stretch main

deb http://mirror.rackspace.com/debian-security/ stretch/updates main
deb-src http://mirror.rackspace.com/debian-security/ stretch/updates main

root@mptcp-server:~# cat /etc/apt/sources.list.d/*
deb https://stable.packages.cloudmonitoring.rackspace.com/debian-stretch-x86_64 cloudmonitoring main
deb http://deb.debian.org/debian stretch-backports main

**Comment by Ysurac** [comment]
I think you only want MLVPN, this configuration wasn't tested since a long time. For now it's unsupported, I need to modify MLVPN script a lot to support latest OpenMPTCProuter VPS script features.

**Comment by dmnk** [comment]
seems like i've been on 9.5, as there wasn't much fuzz when doing the last apt-get upgrade i didn't expect that.

well, then i'll try the larger script and report back.

**Comment by dmnk** [comment]
tried, & failed as well. however i've made some progress.

after the "install-reboot" i've been unable to connect to any port. checked the firewall config.
params.net contained "link".
changed that to venet0, after checking the value on a local debian 9 vm after running that script.
btw, the output of 
>ip -o -4 route show to default | awk '{print $5}' | tr -d "\n"

is

> default dev venet0 scope link

therefore the interface to go is the third not the 5th parameter

next problem: mptcp is still unavailable, highly propably because its a openvz legacy environment.

> Nov 01 20:11:50 aggregator glorytun-tcp-run[285]: couldn't set socket option `MPTCP_ENABLED (42)'

>Nov 01 20:11:50 aggregator ss-server[277]:  2018-11-01 20:11:50 ERROR: failed to enable multipath TCP: Protocol not available
Nov 01 20:11:50 aggregator ss-server[277]:  2018-11-01 20:11:50 ERROR: fast open is not supported on this platform
Nov 01 20:11:50 aggregator ss-server[277]:  2018-11-01 20:11:50 INFO: tcp server listening at 0.0.0.0:65101
Nov 01 20:11:50 aggregator ss-server[277]:  2018-11-01 20:11:50 INFO: tcp port reuse enabled

Status on the router is switching between 
> (X)MPTCP may not be enabled on the server

and
>/!\ VPN tunnel DOWN


Any hints what i'll have to to to MLVPN to get the L3 link & route up and running? As L2 seems to work.
Would openvz 7 change anything? my educated guess: no - as this doesn't allow custom kernels - no change in regard to openvz legacy.

**Comment by rstanislav** [comment]
Why are you trying to use MLVPN ? It gives very bad results compared to shadowsocks + glorytun/openvpn.

**Comment by dmnk** [comment]
should shadowsocks + glorytun work without MPTCP kernel support?

**Comment by Ysurac** [comment]
They can if MPTCP is disabled on each interface, but they will not provide aggregation. They are not needed if you want to use MLVPN.

**Comment by dmnk** [comment]
well aggregation is my main incentive, and as i've noticed some traffic shaping on the 2nd wan, i'd like to spit into their soup and don't show them what kind of traffic is on the line ;)

**Comment by Ysurac** [comment]
Shadowsocks and Glorytun TCP (and OpenVPN TCP) can't do aggregation without MPTCP.
Glorytun UDP and MLVPN can do aggregation without MPTCP, even if result is not as good as MPTCP :)

**Comment by dmnk** [comment]
i see my future myself upgrading to a heavy vm, if i don't get this up and running in the openvz environment ... ;)

**Comment by dmnk** [comment]
if i select glorytun udp the openmptcprouter status stays at vpn down.

i'm not entirely sure if i get the gateway setup, but essentially it should boil down to:
use the tunnel, otherwise fall back to the wan's. - right?

what might be the cause for not taking the first route, if the tunnel is up (and both sides can see / ping their respective partners VPN ip?) - talking about MLVPN again.

**Comment by Ysurac** [comment]
* Should be up if glorytun key is good
* right
* no idea, I can't reproduce the issue.

You used wizard to configure glorytun or MLVPN with an empty key for shadowsocks ? All WANs IP and gateway are set ?
