### ISSUE TITLE
Second LAN for modems

### ISSUE THREAD

**Issue by mycanaletto** [Ysurac/openmptcprouter#2022]
Hello,

I added a second ethernet card (eth1) on a second subnet (192.168.110.2/24) configured in static in LAN zone on firewall side. (openMPTCP in VM).

From this subnet I ping well this interface.

However, from MPTCP (ssh console) it is impossible to ping the modems on this subnet and therefore to configure them.

**Comment by Ysurac** [comment]
I don't understand, you say it's a LAN, why does it have modem on it ?
Check route and firewall if you can't ping a network.

**Comment by mycanaletto** [comment]
There were always modems on LAN (the only network card in openmptcp). I just added one on the other VLAN port to join another box.

**Comment by Ysurac** [comment]
You use MacVLAN or VLAN ?
You checked firewall zones ?

**Comment by mycanaletto** [comment]
I tested all possibilities and both network cards are in the LAN on the FW side

**Comment by Ysurac** [comment]
Please describe correctly your installation if you want some help. Make a schema or something like that.
For now I don't know what you have and what you want.

**Comment by mycanaletto** [comment]
Note that on another Linux I added a network card in the same way and everything is ok

2 network cards :
- LAN1 192.168.210.0/24 : LAN clients + 1 modem : ok
- LAN2 192.168.110.0/24 : LAN clients + 2 modems

![image](https://user-images.githubusercontent.com/45459269/129716064-f0817781-5759-4f60-908c-4377fe3ffd46.png)

**Comment by Ysurac** [comment]
This will not work really well this way.
LAN part is on same subnet as modems and multiple modems are on same subnet.
Check also wan2 and wan3 configuration (seems to be macvlan), they must be in WAN firewall zone.
VPS wasn't rebooted after update.

**Comment by mycanaletto** [comment]
It doesn't explain why in console mode I don't ping the lan2 and that the reverse is possible. Special fw rule ?

![image](https://user-images.githubusercontent.com/45459269/129717579-2b032e72-68b7-4b65-9b78-7f52365dc7a5.png)

![image](https://user-images.githubusercontent.com/45459269/129717439-978ee207-dcf9-417a-9cff-110c61eda6f2.png)

![image](https://user-images.githubusercontent.com/45459269/129717370-0043dc30-dbb3-42e1-a999-e9a115519dcc.png)

**Comment by mycanaletto** [comment]
In fact it works by itself, but under ESX, and as for the first LAN you must not forget to accept the Promiscuous mode...

![image](https://user-images.githubusercontent.com/45459269/129738011-13e9d745-7350-4b55-a218-d696e7c74b34.png)
