### ISSUE TITLE
Booting raspberry pi 4 from usb (connected to ssd)

### ISSUE THREAD

**Issue by hi10bha** [Ysurac/openmptcprouter#2024]
I am able to boot with the connected usb ssd to raspbian os without any issues, but I m not able to boot in OMR can someone throw some light on this , it starts to boot but does not come to the prompt nor m able to login . It halts at attached SCSI removable disk.  I am looking to use Argon one V2 housing if this works for me

**Comment by highfreq** [comment]
Asked the same 2 weeks ago, i would like to boot from usb stick, much more robust against readonly filesystem and much daster but i got no answer, if you find a solution please let me know.
I have OMR installed on an appliance that needs to be powered off not gracefully and i have to change SD once a week because of bad sectors.

**Comment by hi10bha** [comment]
Exactly the same reason I want to move to ssd

**Comment by Ysurac** [comment]
Please use templates...
You may need to update RPI firmware and modify /boot/cmdline.txt

**Comment by highfreq** [comment]
*UPDATE*
Updated bootloader this morning on rpi4 to latest and changed to sda2 in cmdline.txt and now everything is working.

Ysurac, is it possible on an Rpi4 to attach on the same ethernet port (the only one) , 2 lan gateways and local lan?
I tried following your how to and giving just ip and gateway ip to wan 1 and wan 2 in tutorial but it doesn't work, interface down.
Should i use vlan?

**Comment by Ysurac** [comment]
On RPI, by default MacVLAN is used. Make sure you doesn't change this (macvlan must be based on eth0 physical interface), then only IP and gateway settings are needed.

**Comment by highfreq** [comment]
So i have to select macvlan?

**Comment by Ysurac** [comment]
if you don't have any VLAN, yes, use MacVLAN

**Comment by highfreq** [comment]
I need to have 2 modems and regular lan on the same ethernet port, so i leave lan as it is and configure the 2 wans as macvlan?

**Comment by highfreq** [comment]
macvlans based on eth0 i guess?

**Comment by highfreq** [comment]
I made macvlans and it works, untill i reboot than the wan interface says Unknown error (DEVICE_CLAIM_FAILED). Maybe it is referred to eth0 wich i am using it in bridge with wlan0. Should i remove the bridge?

**Comment by hi10bha** [comment]
Where can I find cmdline.txt in openmptcp /boot

**Comment by hi10bha** [comment]
thanks for all the help Ysurac and highfreq thankyou very much I managed to get my ssd running

**Comment by jphgardner** [comment]
How did you get it working exactly?
