### ISSUE TITLE
How to boot Rpi4 from USB stick Tutorial

### ISSUE THREAD

**Issue by highfreq** [Ysurac/openmptcprouter#2026]
1 - Download and burn proper Rpi4 image
2 - In Boot edit cmdline.txt change the root device from mmcblk0p2 to sda2
3 - Exit and save

Now your Rpi4 should boot from USB, if it doesn't make a raspian SD and boot into the OS. From command line issue following: 

1 - **sudo rpi-eeprom-update** to see if there is a new eeprom version
2 - **sudo rpi-eeprom-update -d -a** to update

At the end of the update it'll ask to reboot, do it.

After reboot done power off and take SD out and put your OMR USB stick in and enjoy.

Hope it is clear :)

p.s. At the moment everything works as expected and quite a bit faster, even tried powering off and on removing cable 15-20 times and never got the readonly filesystem :)

**Comment by hi10bha** [comment]
<img width="1536" alt="Screenshot 2021-08-18 at 02 41 49" src="https://user-images.githubusercontent.com/79439995/129809479-5960f9be-dbc3-4303-a48a-f93de1277747.png">


it gets stuck at the above point in image and n not able to run your second command 
2 - sudo rpi-eeprom-sudo rpi-eeprom-update -d -a to update

**Comment by hi10bha** [comment]
thanks a lot, I managed. thanks
