### ISSUE TITLE
IPv6 Port Openning not Working

### ISSUE THREAD

**Issue by iamfreaky** [Ysurac/openmptcprouter#2027]
Expected Behavior

IPv6 Forwarding for a Webserver should work like IPv4
Current Behavior

IPv6 Does not work
Specifications

    OpenMPTCProuter version: v0.58.5 r0+16336-b36068d35d
    OpenMPTCProuter VPS version: 0.1026 5.4.100-mptcp
    OpenMPTCProuter platform: x86_64

In /etc/shorewall6/rules you can see a DNAT Rule after changing the Rules on the MPTCP Router.

Config Rule on Router

config rule
option src 'vpn'
option target 'ACCEPT'
option family 'ipv6'
list proto 'tcp'
option dest_port '80'
option name 'HTTP'
option dest 'lan'
list dest_ip 'IPv6 Address'

Config on VPS in /etc/shorewall6/rules

DNAT net vpn:$OMR_ADDR tcp 80 # OMR openmptcprouter redirect router 80 port tcp

Config on VPS IPv4 (IPv4 is working)

DNAT net vpn:$OMR_ADDR tcp 80 # OMR openmptcprouter redirect router 80 port tcp

Internet Access (IPv4 and IPv6) is completly working.

**Comment by Ysurac** [comment]
Already fixed in develop via https://github.com/Ysurac/openmptcprouter-feeds/commit/a7bfd7cac712c2144117c6d2193ad807bfffe76c
Fix will be available in next release.
