### ISSUE TITLE
new Mac OS bigger and Monterey versions issues

### ISSUE THREAD

**Issue by hi10bha** [Ysurac/openmptcprouter#2030]
## Expected Behavior

am not able to access internet on my bigsur and Monterey os

## Current Behavior

Am not able to surf internet on Macs running bigsur and Monterey, I can access internet on Catalina os through mptcp
I changed the glorytun to udp from tcp but still facing issues

## Specifications

  - OpenMPTCProuter version: 
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter VPS provider:
  - OpenMPTCProuter platform:

**Comment by finnschi** [comment]
i run bigsur and have no issues surfing? you need to do more troubleshooting  usually its a dhcp or dns issue

**Comment by hi10bha** [comment]
Thanks for the reply

I am able to access the router and it's set to dhcp and dns is set to 8.8.8.8 still am not able to access

**Comment by Ysurac** [comment]
You shouldn't modify DNS on OpenMPTCProuter.
Check:
* that you can ping OpenMPTCProuter IP from your clients. 
* if yes, check that you can access http://1.1.1.1/
* If yes, check a ```dig google.com``` result (if dig is available on macos)

**Comment by hi10bha** [comment]
that you can ping OpenMPTCProuter IP from your clients. ( yes ) I can log in to 192.168.100.1

if yes, check that you can access http://1.1.1.1/ (NO)
If yes, check a dig google.com result (if dig is available on macos)

**Comment by Ysurac** [comment]
So the problem is not related to DNS if you can go to http://1.1.1.1
Check status page, all should be green with VPS public IP displayed in VPS box.
If it's ok, check that you use OpenMPTCProuter IP as gateway. and that you can ```ping 1.1.1.1```

**Comment by hi10bha** [comment]
in Status box

Status box is all green , everything runs fine on my windows laptop, no issues at all. Mac with Catalina - am able to run when I switch glory tun to udp. but in BIG SUR and Monterey NO.
