### ISSUE TITLE
open port for nginx on vps

### ISSUE THREAD

**Issue by ascomputer** [Ysurac/openmptcprouter#2033]
hi all, is it possible to open port 8080 on the vps to use nginx?

**Comment by Ysurac** [comment]
Shorewall is used as firewall on the VPS side, so edit ```/etc/shorewall/rules``` and restart shorewall.

**Comment by ascomputer** [comment]
I entered this:
ACCEPT net $ FW tcp 8080
but the vps door is still closed, what do you suggest me to do?
