### ISSUE TITLE
Wifi bridging on Raspberry 4 with macvlan 

### ISSUE THREAD

**Issue by highfreq** [Ysurac/openmptcprouter#2035]
## Expected Behavior
Raspberry 4 with 2 macvlan routers on lan port and lan port connected to 2 local pc trough a switch. Would like to have wifi access to local lan to reach the 2 pc (i guess wifi bridge to local lan)

## Current Behavior
If i setup wifi access point and bridge it to lan than the macvlan interfaces say "cn't claim device", i guess it is because lan0 is now bridged.

## Specifications

 OMR  v0.58.5 on Raspberry 4

**Comment by highfreq** [comment]
No chance to have a little help?

**Comment by highfreq** [comment]
Guess not :)

**Comment by Ysurac** [comment]
Please use the full template and set correctly the release you use in specifications.
With macvlan I don't think bridge can work. But OpenMPTCProuter is a router, they don't need to be on same LAN to reach each others, you only need to set firewall correctly.

**Comment by highfreq** [comment]
Release is latest, installed 3 days ago.
So you mean i just activate wifi network and put it in lan zone of firewall?

**Comment by Ysurac** [comment]
As indicated in template, latest is not a release. And this doesn't help when someone check the issue 3 months later...

**Comment by highfreq** [comment]
Ok, sorry about it, edited first post.

**Comment by Ysurac** [comment]
This should work: https://github.com/Ysurac/openmptcprouter/wiki/Configure-Wifi

**Comment by highfreq** [comment]
Thank you, i followed it step by step and i can now connect to my wireless network, wich was added in the lan zone of the router. 
I can now ping router lan address but none of the pc attached to the lan itself.

**Comment by Ysurac** [comment]
You can try to create a new firewall zone for wifi interface, set it with same parameters as LAN zone and allow forward from this zone to LAN.

**Comment by highfreq** [comment]
done firewall zone same as lan but still can't ping lan pc. Can only ping router lan address.

**Comment by Ysurac** [comment]
Forward is allowed in firewall zone configuration?

**Comment by highfreq** [comment]
yes, all allowed

**Comment by highfreq** [comment]
wifi ---> lan      allowed allowed allowed

**Comment by highfreq** [comment]
Made a clean install and followed the guide and now everything works. 
Thank you very much.

**Comment by Ysurac** [comment]
Thanks for the feedback.
