### ISSUE TITLE
daemon.err /usr/bin/ss-redir[14425]: remote recv: Host is unreachable

### ISSUE THREAD

**Issue by kyouran38** [Ysurac/openmptcprouter#2036]
Hi I am opening this issue cos I have this log all the time :

Mon Aug 23 12:53:14 2021 daemon.err /usr/bin/ss-redir[14425]: remote recv: Host is unreachable
Mon Aug 23 12:53:14 2021 daemon.err /usr/bin/ss-redir[14425]: remote recv: Host is unreachable
Mon Aug 23 12:53:14 2021 daemon.err /usr/bin/ss-redir[14426]: remote recv: Host is unreachable
Mon Aug 23 12:53:14 2021 daemon.err /usr/bin/ss-redir[14425]: remote recv: Host is unreachable
Mon Aug 23 12:53:14 2021 daemon.err /usr/bin/ss-redir[14426]: remote recv: Host is unreachable
Mon Aug 23 12:53:14 2021 daemon.err /usr/bin/ss-redir[14425]: remote recv: Host is unreachable
Mon Aug 23 12:53:14 2021 daemon.err /usr/bin/ss-redir[14426]: remote recv: Host is unreachable
Mon Aug 23 12:53:14 2021 daemon.err /usr/bin/ss-redir[14426]: remote recv: Host is unreachable
Mon Aug 23 12:53:14 2021 daemon.err /usr/bin/ss-redir[14425]: remote recv: Host is unreachable
Mon Aug 23 12:53:14 2021 daemon.err /usr/bin/ss-redir[14425]: remote recv: Host is unreachable
Mon Aug 23 12:53:14 2021 daemon.err /usr/bin/ss-redir[14425]: remote recv: Host is unreachable
Mon Aug 23 12:53:14 2021 daemon.err /usr/bin/ss-redir[14425]: remote recv: Host is unreachable
Mon Aug 23 12:53:14 2021 daemon.err /usr/bin/ss-redir[14426]: remote recv: Host is unreachable
Mon Aug 23 12:53:14 2021 daemon.err /usr/bin/ss-redir[14426]: remote recv: Host is unreachable
Mon Aug 23 12:53:14 2021 daemon.err /usr/bin/ss-redir[14426]: remote recv: Host is unreachable
Mon Aug 23 12:53:14 2021 daemon.err /usr/bin/ss-redir[14426]: remote recv: Host is unreachable
Mon Aug 23 12:53:14 2021 daemon.err /usr/bin/ss-redir[14426]: remote recv: Host is unreachable
Mon Aug 23 12:53:14 2021 daemon.err /usr/bin/ss-redir[14425]: remote recv: Host is unreachable
Mon Aug 23 12:53:14 2021 daemon.err /usr/bin/ss-redir[14426]: remote recv: Host is unreachable

I also get those messages :

Mon Aug 23 13:02:24 2021 daemon.err /usr/bin/ss-local[14423]: getpeername: Socket not connected
Mon Aug 23 13:02:29 2021 daemon.err /usr/bin/ss-local[14423]: getpeername: Socket not connected
Mon Aug 23 13:02:34 2021 daemon.err /usr/bin/ss-local[14423]: getpeername: Socket not connected
Mon Aug 23 13:02:39 2021 daemon.err /usr/bin/ss-local[14423]: getpeername: Socket not connected
Mon Aug 23 13:02:43 2021 daemon.err /usr/bin/ss-local[14423]: getpeername: Socket not connected
Mon Aug 23 13:02:44 2021 daemon.err /usr/bin/ss-local[14423]: getpeername: Socket not connected
Mon Aug 23 13:02:45 2021 daemon.err /usr/bin/ss-local[14423]: getpeername: Socket not connected

My version of openmptcprouter v0.58.5 r0+16336-b36068d35d

My vps is azure and all port are open : 5.4.100-mptcp 0.1026

Local Server ! Raspberry Pi 3 Model B Plus Rev 1.3

Thanks

**Comment by Ysurac** [comment]
A host seems to be unreachable from VPS. For ss-local there is some connections problem to shadowsocks on the VPS.
