### ISSUE TITLE
Burn an image on new Raspberry 4 and connect to a new server.

### ISSUE THREAD

**Issue by highfreq** [Ysurac/openmptcprouter#2038]
Load an SD image on a new installation and connect it to a different server changing IP and keys, would it work? I have some port forwarding configured, would it keep it?
I would like to do it so that i can replicate my perfectly now functioning OMR with all the configurations i need.

## Current Behavior
Did not try yet

  - OpenMPTCProuter version: OMR v0.58.5 on Raspberry 4
  - OpenMPTCProuter VPS version: OMR v0.58.5 on Ubuntu 20
  - OpenMPTCProuter VPS provider: Aruba
  - OpenMPTCProuter platform: OpenMPTCProuter VPS 0.1026

**Comment by Ysurac** [comment]
Yes this should work.

**Comment by highfreq** [comment]
OMR will forward port forwarding configuration to new server trough api?

**Comment by Ysurac** [comment]
Yes. It's it's not done after wizard validation, this should be done a few minutes later.

**Comment by highfreq** [comment]
Ok great, i'll try it.

Thank you very much.
