### ISSUE TITLE
Mikrotik RB5009UG+S+IN

### ISSUE THREAD

**Issue by starkovv** [Ysurac/openmptcprouter#2040]
Hi,

Is it possible to port OMR to Mikrotik RB5009UG+S+IN?
https://mikrotik.com/product/rb5009ug_s_in

**Comment by Ysurac** [comment]
It's not supported by OpenWrt for now, so this would be difficult.

**Comment by kalashnikov2** [comment]
hi

mikrotik just "release" this
"Container is MikroTik's own implementation of Docker(TM), allowing users to run containerized environments within RouterOS. The container feature was added in RouterOS v7.1rc3. "

https://help.mikrotik.com/docs/display/ROS/Container

**Comment by Ysurac** [comment]
OpenMPTCProuter need a customized kernel, a container use host kernel.

**Comment by starkovv** [comment]
Do we have option to run MPTCP in userspace? 🤔
