### ISSUE TITLE
Support for EdgeRouter 4

### ISSUE THREAD

**Issue by swtw122** [Ysurac/openmptcprouter#2041]
Hi, is it possible to build a custom image for the EdgeRouter 4 which has a better cpu than the EdgeRouter X?

OpenWRT is running on EdgeRouter 4

Maybe we can together create support for this device.
I'll setup a buildsystem in the next days.

**Comment by Ysurac** [comment]
I can only officially support device that I own. And at 184€ it's a bit expensive for me now.

**Comment by iizotov** [comment]
where did you get up to @swtw122 - I have one I am happy to experiment on.

**Comment by iizotov** [comment]
So, I've successfully compiled and flashed the image to my EdgeRouter 4 and has been using it for a day - so far so good.
There are some issues with compiling ndpi-netfilter2, kmod-ipt-ndpi and iptables-mod-ndpi packages on mips64, so I just carefully removed them from all definitions before running `make menuconfig`

So far, so good.

**Comment by swtw122** [comment]
How did you successfully removed ndpi-netfilter2? Had the same issue and failed going on with that. Can you share a description or your image?

**Comment by iizotov** [comment]
did a manual grep through all the files under cd myplatform/source, painstakingly weeding out the dependencies...
Uploaded the images to https://github.com/iizotov/openmptcprouter-edgerouter-4/releases/tag/v0.58.5-f557cb00 - feel free to have a play

**Comment by fowlerovski** [comment]
@iizotov Thanks for sharing your work!
I bought an ER4 because of your post, and am moving toward setting everything up. 
Would you be willing to write a short how-to on setting up a new ER4 with this fw/config?

**Comment by fowlerovski** [comment]
@iizotov @swtw122 following up, after loading the .tar firmware and attempting to flash it, I receive the following error from the ER4 SSH:
`Checking upgrade image...Upgrade image does not support the device. Upgrade failed.`
This is a brand new ER4, with nothing done so far. 
Any advice for a relative newb to proceed forward?
Thanks

**Comment by drtechga** [comment]
any updates
