### ISSUE TITLE
x86 EFI - error disk (hd0,gpt1) not found - when USB Modem is connected

### ISSUE THREAD

**Issue by 5UP3RR3D** [Ysurac/openmptcprouter#2042]
I've tested two different x86 machines - supermicro E100-9AP & HPe proliant microserver gen10+ with 64bit EFI images. Both run into this error when USB Modems are connected. Without a modems connected OMR boots fine. In BIOS the internal drive which has OMR installed is the first & only boot option. looks like USB modems with mass storage messes up the drive schedule even when no storage is installed. Setting up a grub device.map with (hd0) = /dev/sda didn't work either.

**Comment by Ysurac** [comment]
Difficult to make any test for this. Check UEFI interface if you can set a priority.

**Comment by 5UP3RR3D** [comment]
Booting OMR in legacy mode works fine with  different modems plugged in at the same time (huawei, TPlink, ZTE). UEFI - no chance except using reFind instead of grub. I guess the openWRT - EFI boot option isn't as stable as it should be.

**Comment by Adorfer** [comment]
many USB-Radio-Modems contain a mass storage device, either a MicroSD slot or a fixed flash partition, sometimes r/w, sometimes read-only (ro) as CDrom-emulation. 
Depending on the mainboard bios this can totally mix up the SATA-Enumeration and boot devices order.
