### ISSUE TITLE
Re-create a (established) connection after path re-creation

### ISSUE THREAD

**Issue by dennydeutscher** [Ysurac/openmptcprouter#2043]
Hi!

I played a little with openmptcprouter to test the following condition: Main goal is to achieve a redundant internet connection with zero fail-over time.

I tested what's happening to a single connection (sending a stream to youtube) if a connection gets lost and come back after some time: I have a WAN connection and two WWAN devices (cdc-ether) Huawei Hi-Link LTE: When I disable mobile data on one LTE device (to simulate a loss of a internet connection or a bad cellular link) the stream still goes to youtube over the remaining connections, so far so good... 

The Problem I've seen: If the connection comes back online, the stream will not be send again over the reconnected path (until I restart the encoder which is streaming to youtube). Is there a way to auto recreate the connection?

Thank you, Denny

**Comment by Ysurac** [comment]
Connection should be back after some time. You can try another MPTCP scheduler in Network->MPTCP.

**Comment by Ysurac** [comment]
What do you have in Network->MPTCP, Globals part ?
BLEST is better in most case for me, but each case is different.

**Comment by dennydeutscher** [comment]
ATM it is on redundant

**Comment by Ysurac** [comment]
This may explain the issue, redundant is working so well.

**Comment by dennydeutscher** [comment]
okay so I will try BLEST... 

One more thing you should know:

As I went to WRT3200ACM I had to try various different setting because at the beginning the device crashed as soon as I upload more than 15 MBit/s oder LTE (cdc/ethe)... finally I had me to compile me a new image from your repository which seems to be stable (I don't know why, because I just compiled it without modifying anything).

**Comment by dennydeutscher** [comment]
Sorry mixed up the Issues (thought I was replying to the facebook issue)

I only switched to redundant after seeing the BLEST showing the behaviour I described above (but with the same result)
