### ISSUE TITLE
Configuration using CLI

### ISSUE THREAD

**Issue by eothein** [Ysurac/openmptcprouter#2050]
I wish to use OpenMPTCPRouter dynamically, is there a CLI with corresponding commands which can be used on the router? Is there any documentation for this? 

This way I can easily play around with different setups, without loading the web interface.

**Comment by highfreq** [comment]
I think you can do pretty much everything with luci commands from cli.

**Comment by eothein** [comment]
I'm not sure what luci commands are, is there some documentation somewhere (with examples?)

**Comment by Ysurac** [comment]
```ubus``` and ```uci``` commands are available on the router. There is some documentation on OpenWrt website.
For now all is not yet available via ubus, but all configuration can be modified via uci.
