### ISSUE TITLE
Question: Why android tethering triggers adb request?

### ISSUE THREAD

**Issue by storm1er** [Ysurac/openmptcprouter#2051]
Hi,

This is a simple question: when plugging in my android to add a connection, it triggers an adb request.
Why openmtcp would request an adb access?

I see it's not needed as I never accepted and the connection works, just wondering.

**Comment by eothein** [comment]
I don't think this has something to do with OpenMPTCPRouter: if your Android phone is in Developer modus, plugging in an USB cable will always trigger an adb request.

**Comment by storm1er** [comment]
You can easily test it with a windows laptop.

It will be triggered only after an adb server start (or any sub command that need a server start)

**Comment by storm1er** [comment]
Unless there's an adb server permanently running which feels kinda weird :/

**Comment by storm1er** [comment]
and will it add more features or data if I accept the request using my phone?
