### ISSUE TITLE
New forwarded ports configuration not pushed to primary VPS

### ISSUE THREAD

**Issue by sebvallee** [Ysurac/openmptcprouter#2054]
## Expected Behavior

Having new forwarded ports configuration pushed to all VPS in OMR configuration.

## Current Behavior

The new forwarded ports configuration is only pushed to the first VPS in the list, despite the master VPS is the second one.
Re-validating the wizard, with no modification on it, solve the problem, until next addition to the forwarded ports configuration.

## Possible Solution

Having new forwarded ports configuration pushed to all VPS in OMR configuration at creation, no matter which VPS is set as master.

## Steps to Reproduce the Problem

- Add 2 VPS on your OMR configuration
- Set second VPS on the list as master VPS
- Add a forwarded port on the OMR config
- Check on both VPS (in the /etc/shorewall/rules file), the rule is only on the first VPS, which is not the master one

## Context (Environment)

Not sure what to fill here.

## Specifications

- OpenMPTCProuter version: v0.58.5 r0+16336-b36068d35d
- OpenMPTCProuter VPS version: 0.1026
- OpenMPTCProuter VPS provider: Milkywan / Sapinet (not relevant to this issue)
- OpenMPTCProuter platform: x86_64
- Country: FR

**Comment by Ysurac** [comment]
What is the result, via SSH on the router, of ```/etc/init.d/openmptcprouter-vps set_vps_firewall``` and do you have error in log (```logread```) ?

**Comment by sebvallee** [comment]
No output on `/etc/init.d/openmptcprouter-vps set_vps_firewall` (exit code 0) and no error seen on `logread`

**Comment by sebvallee** [comment]
I forgot to mention but it's a fresh install (both vps and router)
