### ISSUE TITLE
SIP Phone Audio Problem

### ISSUE THREAD

**Issue by fzonno** [Ysurac/openmptcprouter#2055]
## Expected Behavior
Remote SIP phone
We have a SIP PBX (3CX) and some remote phone (STUN mode).

## Current Behavior
The remote phones register but there is no audio communication 
The phones use UDP/TCP 5060 for register and UDP ports 9000-10999 for audio
We have a pfSense firewall behind the openmtcprouter with a forward rule any/any.
The PBX ports test shows that there is a SIP ALG service active. It can be the problem. Any hints for deactivate it?
Any other service / port works perfectly (OpenVPN / HTTPS / SMTP / FTP etc.)

## Specifications

  - OpenMPTCProuter version: 0.58.5
  - OpenMPTCProuter VPS version: 0.1026.5.4.100
  - OpenMPTCProuter VPS provider: ServerPlan
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
You can try to disable "Automatic helper assignment" on VPN and WAN zone in firewall configuration.

**Comment by fzonno** [comment]
I disabled the Automatic helper assignment but the problem persists.
Any other clue?

**Comment by Ysurac** [comment]
No. To my knowledge there is no ALG service on OpenMPTCProuter or OpenWrt.

**Comment by fzonno** [comment]
I tryed without the pfsense (pbx directly connected to openmptcp but same result.
This is the result of the firewall check test
![image](https://user-images.githubusercontent.com/77583187/132377706-0209234c-7675-46dc-ac2d-ef3cb765aa4c.png)

**Comment by Ysurac** [comment]
Maybe the problem is on VPS side.
Can you try to remove sip related modules: ```modprobe -r nf_nat_sip``` and ```modprobe -r nf_conntrack_sip```
