### ISSUE TITLE
openmptcp as public server ip --> lan bridge

### ISSUE THREAD

**Issue by gitxmax** [Ysurac/openmptcprouter#2056]
Is it possible for the mptcp to act as a transparent bridge, so the mptcp router get's the public ip of the server.
My fiber modem is configured as a nat and the router get's the private ip which doesn't work for my particular purpose. The ISP I was unlucky enough to sign up a long contract with, refuses to switch the modem into the bridge mode. Was just thinking if this is possible to overcome with the openmptcp set up ..
Thank you

**Comment by Ysurac** [comment]
No it's not possible.

**Comment by gitxmax** [comment]
thank you
