### ISSUE TITLE
Kernel strange error + drop connection every refresh

### ISSUE THREAD

**Issue by SoGooDFR** [Ysurac/openmptcprouter#206]
## Actual Behavior

This is what happen during the DNS test on: https://ipleak.net/
After page refresh, the WAN2 (4G) drop.

On OpenMPTCProuter status page after refresh:
>openmptcprouter (XXXXXXXXX)MPTCP may not be enabled on the server.
>Multipath seems to be blocked on the connection - No Server ping response after 1 second

> Sat Nov  3 17:41:03 2018 daemon.notice netifd: Network device 'tun0' link is down
> Sat Nov  3 17:41:03 2018 daemon.notice netifd: Interface 'omrvpn' has link connectivity loss
> Sat Nov  3 17:41:03 2018 daemon.notice netifd: omrvpn (3048): udhcpc: received SIGTERM
> Sat Nov  3 17:41:03 2018 daemon.info glorytun-udp: starting glorytun-udp vpn instance vpn
> Sat Nov  3 17:41:03 2018 daemon.notice netifd: Network device 'tun0' link is up
> Sat Nov  3 17:41:03 2018 daemon.notice netifd: Interface 'omrvpn' has link connectivity
> Sat Nov  3 17:41:03 2018 daemon.notice netifd: Interface 'omrvpn' is setting up now
> Sat Nov  3 17:41:03 2018 daemon.err glorytun-udp[5851]: running on device tun0 as pid 5851
> Sat Nov  3 17:41:03 2018 daemon.notice netifd: omrvpn (5874): udhcpc: started, v1.28.3
> Sat Nov  3 17:41:03 2018 daemon.notice netifd: omrvpn (5874): udhcpc: sending discover
> Sat Nov  3 17:41:03 2018 daemon.notice netifd: Interface 'wan2' is now down
> Sat Nov  3 17:41:03 2018 kern.err kernel: [ 5273.171258] mptcp_init4_subsockets: token 0x3871a6b5 bind() to 192.168.8.100 index 39 failed, error -99
> Sat Nov  3 17:41:03 2018 daemon.notice netifd: Interface 'wan2' is disabled
> Sat Nov  3 17:41:03 2018 daemon.notice netifd: Interface 'wan2' has link connectivity loss
> Sat Nov  3 17:41:03 2018 daemon.notice netifd: Interface 'wan2' has link connectivity
> Sat Nov  3 17:41:03 2018 daemon.notice netifd: Interface 'wan2' is enabled
> Sat Nov  3 17:41:03 2018 daemon.notice netifd: Interface 'wan2' is setting up now
> Sat Nov  3 17:41:03 2018 daemon.notice netifd: Interface 'wan2' is now up

## Steps to Reproduce the Problem

  1. Fresh install
  2. Configure OMR-Bypass + SQM
  3. Open https://ipleak.net/.

## Specifications

  - OpenMPTCProuter version: 40.2
  - OpenMPTCProuter VPS version: 0.61
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
Can't reproduce the issue. What do you have in kernel log ?
The site is bypassed ?
Glorytun UDP is up at the same time, OMR is configured since a few second ?

**Comment by SoGooDFR** [comment]
Kernel:
> Sat Nov 3 17:41:03 2018 kern.err kernel: [ 5273.171258] mptcp_init4_subsockets: token 0x3871a6b5 bind() to 192.168.8.100 index 39 failed, error -99

Only netflix is bypassed. When i start the dns test this log lines appear:
> Sat Nov 3 17:41:03 2018 daemon.notice netifd: Network device 'tun0' link is down
> Sat Nov 3 17:41:03 2018 daemon.notice netifd: Interface 'omrvpn' has link connectivity loss
> Sat Nov 3 17:41:03 2018 daemon.notice netifd: omrvpn (3048): udhcpc: received SIGTERM
> Sat Nov 3 17:41:03 2018 daemon.info glorytun-udp: starting glorytun-udp vpn instance vpn
> Sat Nov 3 17:41:03 2018 daemon.notice netifd: Network device 'tun0' link is up
> Sat Nov 3 17:41:03 2018 daemon.notice netifd: Interface 'omrvpn' has link connectivity
> Sat Nov 3 17:41:03 2018 daemon.notice netifd: Interface 'omrvpn' is setting up now
> Sat Nov 3 17:41:03 2018 daemon.err glorytun-udp[5851]: running on device tun0 as pid 5851
> Sat Nov 3 17:41:03 2018 daemon.notice netifd: omrvpn (5874): udhcpc: started, v1.28.3
> Sat Nov 3 17:41:03 2018 daemon.notice netifd: omrvpn (5874): udhcpc: sending discover
> Sat Nov 3 17:41:03 2018 daemon.notice netifd: Interface 'wan2' is now down
> Sat Nov 3 17:41:03 2018 kern.err kernel: [ 5273.171258] mptcp_init4_subsockets: token 0x3871a6b5 bind() to 192.168.8.100 index 39 failed, error -99
> Sat Nov 3 17:41:03 2018 daemon.notice netifd: Interface 'wan2' is disabled
> Sat Nov 3 17:41:03 2018 daemon.notice netifd: Interface 'wan2' has link connectivity loss
> Sat Nov 3 17:41:03 2018 daemon.notice netifd: Interface 'wan2' has link connectivity
> Sat Nov 3 17:41:03 2018 daemon.notice netifd: Interface 'wan2' is enabled
> Sat Nov 3 17:41:03 2018 daemon.notice netifd: Interface 'wan2' is setting up now
> Sat Nov 3 17:41:03 2018 daemon.notice netifd: Interface 'wan2' is now up

**Comment by Ysurac** [comment]
This kernel error is not a problem : the interface is down, MPTCP can't use it. There is nothing more in kernel log ?

**Comment by SoGooDFR** [comment]
Nothing more.

**Comment by Ysurac** [comment]
So no idea. The interface is detected to be down by the kernel, check cable, switch,... if you use real interface.

**Comment by SoGooDFR** [comment]
I change internal ip to my 4G router and no problem at all.

**Comment by Ysurac** [comment]
Doesn't seems to be a software problem. 
If you have more logs, info or tests please reopen the issue.

**Comment by SoGooDFR** [comment]
Problem found ! My poor ADSL make this.
