### ISSUE TITLE
Robust 2 LTE modems connection

### ISSUE THREAD

**Issue by highfreq** [Ysurac/openmptcprouter#2060]
Is there a way with 2 lte modems to have the connection stay up if the master modem loses connection?

If slave connection is lost main connection stays up but if master goes down i lose it all. What should i do to have them stay up if master goes down?

**Comment by donbecker** [comment]
I have this exact same issue. I have 3 LTE modems connected. 
One is set to Multipath TCP: Master
The other two are set to Multipath TCP: Enabled

Is there any way to have the Master role switch to one of the Enabled if the Master goes down?

**Comment by Ysurac** [comment]
@donbecker No need to switch master, if master go down others connection should take the relay. Connection can be down when master is down for a short time because of some packet lost. MPTCP retry in Network->MPTCP can help.

**Comment by highfreq** [comment]
If master goes down it takes 20-30 seconds for my router to start using the other connection. Is this a normal switch time?

**Comment by Ysurac** [comment]
Check log.

**Comment by highfreq** [comment]
This is the 2 lines of log after switching off wan1 (master). Looks like wan2 goes offline too because it can't ping, but in reality it does ping.

Sat Sep 18 11:54:11 2021 user.notice post-tracking-post-tracking: wan1 (wan1) switched off because check error and ping from 192.168.10.2 error (1.1.1.1,4.2.2.1,8.8.8.8)
Sat Sep 18 11:54:11 2021 user.notice post-tracking-post-tracking: Delete default route via 192.168.10.1 dev wan1

**Comment by donbecker** [comment]
The few times that Master has gone offline, I lose all connectivity and it never seems to switch to using the remaining connections, I'll work on testing this further this week.

**Comment by gre2gor** [comment]
Anyone had succes on this?

**Comment by Ysurac** [comment]
When there is a problem, all infos are in system logs. So if master go down, you should see if VPN and proxy need to reconnect or not.

**Comment by highfreq** [comment]
> Anyone had succes on this?

I did not, from system log i can't see where my problem is. All i know is that if master goes down than all link goes down, partially defeating the reason i am using OMR in the first place.

**Comment by Ysurac** [comment]
Do you enabled SQM and set download/upload speed ?

**Comment by highfreq** [comment]
I didn't, does it have anything to do with link robustness?

**Comment by Ysurac** [comment]
SQM can avoid link saturation, so if ping doesn't work because all bandwidth is used this can help.

**Comment by highfreq** [comment]
It is not saturated at all, link just goes down when master link falls

**Comment by Ysurac** [comment]
You see all links down in system log with ping errors ?

**Comment by highfreq** [comment]
Sat Sep 18 11:54:11 2021 user.notice post-tracking-post-tracking: wan1 (wan1) switched off because check error and ping from 192.168.10.2 error (1.1.1.1,4.2.2.1,8.8.8.8)
Sat Sep 18 11:54:11 2021 user.notice post-tracking-post-tracking: Delete default route via 192.168.10.1 dev wan1

**Comment by Ysurac** [comment]
This doesn't really help to see an issue. wan1 is detected as down, I think you have more links than that.

**Comment by highfreq** [comment]
I have wan1 and wan2 on 2 lte modems.

**Comment by Ysurac** [comment]
So you said all links go down, you should have more logs with also wan2 down and VPN/Proxy down too.

**Comment by highfreq** [comment]
I said, when master goes down the slave link is unable to carry on with comunication, it tkes 20-30 seconds for link slave to pick up the link and start sending data. 
To make it short, if master goes down there is a link blackout of around 20-30 seconds, than comunication is restblished.

**Comment by Ysurac** [comment]
Again, check in log to find what go down: VPN or proxy. And you can try another VPN like glorytun UDP that may have no problem with master down.

**Comment by highfreq** [comment]
Ok, will try thank you
