### ISSUE TITLE
Policy-based routing for VPN and protocol

### ISSUE THREAD

**Issue by iizotov** [Ysurac/openmptcprouter#2065]
## Expected Behavior
I should be able to:
1. force-route traffic from certain LAN devices through an OpenVPN connection initiated from my router (I'm using PIA Openvpn) - similar to openwrt's vpn-policy-routing, e.g. devices 192.168.0.2 and 192.168.0.3 need to be routed through an OpenVPN interface.
2. be able to use openmptcprouter **only for UDP**, only for select devices on the network, e.g. 192.168.0.4 and 192.168.0.5. All non-UDP traffic should continue flowing through the master WAN. The use case here is video conferencing.

## Current Behavior
1. OpenVPN connection to PIA is established correctly but I'm unable to figure out a way how to set up policy routing for 192.168.0.2 and 192.168.0.3. OMR-Bypass does not support this yet (#2037), vpn-policy-routing does not work on openmptcprouter. 
2. Not able to achieve that with OMR-Bypass...

Any suggestions how I can achieve 1 and 2 via iptables?

Thanks!

**Comment by gnosoz** [comment]
You can try manually the following and see first that you achieve what you are looking for:
```
iptables -t nat -A POSTROUTING -s 192.168.0.4/32 -j SNAT --to <address of interface you wish to use>
iptables -t nat -A POSTROUTING -s 192.168.0.5/32 -j SNAT --to <address of interface you wish to use>
```

If result works you can simply add it via luci in https://routerIP/cgi-bin/luci/admin/network/firewall/snats this will make sure the rules still works after reboot
