### ISSUE TITLE
Debian 11 (bullseye) support

### ISSUE THREAD

**Issue by N3EOP** [Ysurac/openmptcprouter#2070]
Since Debian 11 is officially released as Stable, is official support coming?  The Debian 10 installer doesn't work.

Thanks.

**Comment by Ysurac** [comment]
Debian 11 will be supported in next release.

**Comment by N3EOP** [comment]
Thanks.

**Comment by HP-Basarab** [comment]
Hello, any news about this release?

**Comment by Ysurac** [comment]
When it will be ready. For now it's in beta.
