### ISSUE TITLE
Pi-hole installation on Openmptcprouter

### ISSUE THREAD

**Issue by jjak0b** [Ysurac/openmptcprouter#2071]
Is possibile to install a Pi-hole server into Openmptcprouter without the need of VPS, something like linked to virtual interface and setup as DNS ?

**Comment by Ysurac** [comment]
It's not possible to install it on the router. But you can install it on another VM/computer and set it as DNS ( https://github.com/Ysurac/openmptcprouter/wiki/Custom-DNS )

**Comment by jjak0b** [comment]
I thought so, but I was hoping I was wrong. thanks anyway
