### ISSUE TITLE
Building images for ipq40xx fails because of BBR2 missing

### ISSUE THREAD

**Issue by debiantippse** [Ysurac/openmptcprouter#2076]
Hey i'm currently trying to Build images for AVM Devices(Fritzbox 7530)

When i try to build an image it actually gaves me after a while this error here:
![grafik](https://user-images.githubusercontent.com/90697077/133257404-1aecb9d9-6787-4fa8-aa6e-ff05f51b3919.png)

Also at the beginning it starts with:

domenik@debian:~/openmptcprouter/ipq40xx/source$ scripts/feeds install -a -d y -f -p openmptcprouter
WARNING: Makefile 'package/utils/busybox/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/busybox/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/busybox/Makefile' has a build dependency on 'libpam', which does not exist
WARNING: Makefile 'package/boot/kexec-tools/Makefile' has a dependency on 'liblzma', which does not exist
WARNING: Makefile 'package/network/services/lldpd/Makefile' has a dependency on 'libnetsnmp', which does not exist
WARNING: Makefile 'package/utils/policycoreutils/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/policycoreutils/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/policycoreutils/Makefile' has a build dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/wmt/Makefile' has a dependency on 'kmod-mt6625l-wlan-gen2', which does not exist

Am i missing something here?

**Comment by Ysurac** [comment]
BBR2 should not be enabled on device without a 64bits CPU.

**Comment by debiantippse** [comment]
> 
> 
> BBR2 should not be enabled on device without a 64bits CPU.

Okay without BBR2 it should run just fine?

**Comment by Ysurac** [comment]
I have no idea, it's not a supported platform.
