### ISSUE TITLE
MPTCP fallback

### ISSUE THREAD

**Issue by danog** [Ysurac/openmptcprouter#208]
Hello,
Thank you for the work on this useful project.
I'd like to know if there's a way to force usage of MLVPN (or another non-MPTCP network merging alternative) if one of the connections or the server itself doesn't support MPTCP.
That'd be really nice, thanks.

## Specifications

  - OpenMPTCProuter version: (openmptcprouter v0.40.2 r7365-91a8bc1dd0)
  - OpenMPTCProuter VPS version: (OpenMPTCProuter VPS 0.62)
  - OpenMPTCProuter platform: (RPI3)

**Comment by Ysurac** [comment]
You can select the VPN (that support aggregation) you want (glorytun-udp or MLVPN) and disable shadowsocks if you want.
I will not use MLVPN or Glorytun UDP automatically if MPTCP is not working because detection of MPTCP support is not 100% reliable.
