### ISSUE TITLE
the load does not get seperated into multiple lines

### ISSUE THREAD

**Issue by rifaterdemsahin** [Ysurac/openmptcprouter#2081]
## Expected Behavior
I expect the load on each line. 
I should have 700 Down and 200 up

## Current Behavior
![image](https://user-images.githubusercontent.com/5270036/133753282-3c5d109a-325c-40f6-9811-04d4d411d327.png)
![image](https://user-images.githubusercontent.com/5270036/133753663-494df058-b7d9-4ddc-9e1f-e543ea87d9c7.png)

## Possible Solution
Separate the load to each connection

## Steps to Reproduce the Problem

  1. add 150 GB file in the network to sync it to the cloud
  2. Everything gets slowed down
  

## Context (Environment)
The internet has become not much slower.

## Specifications
don't know why it says proxy disabled.

![image](https://user-images.githubusercontent.com/5270036/133753498-db551021-dc74-4d65-9ca1-61537135e23c.png)

**Comment by Ysurac** [comment]
Please use the template, I need versions, platform,...
Proxy is disabled mean the proxy was disabled in advanced settings, in the wizard.
Without proxy this can't work correctly.

**Comment by rifaterdemsahin** [comment]
vps-ea15b92c (51.195.1xxxxxx)
Version 0.1023 5.4.100-mptcp
(Latest available version 0.1026)
Load: 0.76 0.67 0.57
 

OpenMPTCProuter 
(192.168.100.1)Proxy is DISABLEDVersion 0.58.5Load: 0.30 0.29 0.31Uptime: 41d 18h 23m 22slan address: 192.168.100.1lan range: 192.168.100.100 - 192.168.100.249

Is there a practical script/page where I can get all these information ? 
When I copy-paste ...it brings the html.

**Comment by rifaterdemsahin** [comment]
I had the old proxy server settings there for backup now removed it
![image](https://user-images.githubusercontent.com/5270036/133756571-c9fb9ea0-29b3-41fe-9a24-7751b71b7328.png)


now after removing the backup config I am back into action
I suspect that disabled server had a faulty code... which started affecting the system after 40 days...or after I updated the text.

now I remembered I updated the text...and I had a disabled server there...so there needs to be a unittest for that case.


![image](https://user-images.githubusercontent.com/5270036/133756879-0d05786c-ba82-4bc6-a887-206210312de0.png)

![image](https://user-images.githubusercontent.com/5270036/133756744-246297b5-fa84-4bc4-82ab-9a875cb99005.png)

**Comment by rifaterdemsahin** [comment]
![image](https://user-images.githubusercontent.com/5270036/133793506-271744a5-3d27-4b0f-86a1-d77f9ddf74c8.png)

now i see all the lines active
i need to have an open window for this
