### ISSUE TITLE
Vmware Network unreachable

### ISSUE THREAD

**Issue by bagou4502** [Ysurac/openmptcprouter#2090]
Hey i have a problem with last version of openmptcprouter with vmware workstation 16.
I can't find any way to provide internet connection to the vm
When i run ping (ip) i got : Network unreachable

**Comment by Ysurac** [comment]
You need to create interfaces you need or set interface in vmware as promiscuous.

**Comment by bagou4502** [comment]
![image](https://user-images.githubusercontent.com/53863206/134781788-4c13c0d5-1e41-4075-881f-dae33207f07b.png)
Actualy i have that in vmware workstation setting.
I have same problem with x86_64 img and virtualbox img.
My box use 192.168.0.1 to 192.168.0.254 can this be a problem?

But how i can create interface?

**Comment by bagou4502** [comment]
Update
Actualy openmptcprouter work but i cant connect openmptcprouter to my internet box
Here IS m'y setup
![P_20210925_210000](https://user-images.githubusercontent.com/53863206/134783300-2ea7f294-123b-41ba-a29d-6e3a022c7e83.jpg)
I have this config 
![Uploading P_20210925_210316.jpg…]()

**Comment by bagou4502** [comment]
Update :

ALL is good just need to see some things

First i have 50% of my vdsl how i can reduce this loss
Second some website like openmptcprouter.com doesn t work i think is a dns server problem but how i can resolve that
