### ISSUE TITLE
Excessive NAT connections, RAM leak?

### ISSUE THREAD

**Issue by gsxryan** [Ysurac/openmptcprouter#2097]
## Expected Behavior
There shouldn't be so many NAT connections persisting.  Seems to correlate with a memory leak / excessive RAM allocation.

## Current Behavior
Memory slowly climbing.
![Screenshot 2021-09-13 11 32 19 AM](https://user-images.githubusercontent.com/2055136/135383910-291477c7-9563-44ac-b7ee-600c332d5038.png)

Slow climb correlates with excessive NAT connections in ISP router table.  Hitting the ISP limit may be decreasing performance or causing other issues.
![Screenshot 2021-09-12 7 55 47 AM](https://user-images.githubusercontent.com/2055136/135384017-5a9499e3-c01e-431c-8e61-844d3247c677.png)

After rebooting:
![Screenshot 2021-09-12 8 34 43 AM](https://user-images.githubusercontent.com/2055136/135383931-eca26711-7720-4b85-bfa1-05ee3cbb65ad.png)

## Possible Solution
Workaround or bugfix for excessively created NAT connections.  They persist and have a very long TTL.  I attempted to reduce TTL in a few places in OMR, but no luck yet to help the issue.

## Steps to Reproduce the Problem

  1.  Wait for high uptime (2-3 days)
  2. Observe High RAM allocated
  3. Monitor ISP router for NAT connections in table.

## Context (Environment)
The performance of OMR's administration panel gets slower and slower as the RAM builds, and the NAT connections increase.  To make a change it takes 10x longer after high uptime, than after a fresh reboot.

## Specifications

  - OpenMPTCProuter version: openmptcprouter v0.58.5 r0+16336-b36068d35d
  - OpenMPTCProuter VPS version: 5.4.100-mptcp 0.1026
  - OpenMPTCProuter VPS provider: linode
  - OpenMPTCProuter platform: x64, proxmox, ubuntu
  - Country: USA

## Possible workaround?
Testing
Services > UPnP

Uncheck the following:
Enable UPnP functionality
Enable NAT-PMP functionality

**Comment by Ysurac** [comment]
UPnP is disabled by default, services are not running.
Where do you get NAT table from ?
You can change TTL in System->OpenMPTCProuter, "Advanced settings" tab.

**Comment by gsxryan** [comment]
> For the ss-redir problem, do you use P2P or have something that try to contact an IP that is not reachable ?

My UDM pro pings google DNS constantly, but can't find many entries in the NAT table for it.  I'll switch to the local address anyway

**Comment by gsxryan** [comment]
This is still an issue.  I'm currently bypassing all my IOT devices outside of MPTCP router to keep the NAT connections low.  I will need some more time to narrow down which device is causing this excess.
