### ISSUE TITLE
Prime video problem

### ISSUE THREAD

**Issue by bagou4502** [Ysurac/openmptcprouter#2103]
## Specifications

  - OpenMPTCProuter version: 5.4.100-mptcp 0.1026
  - OpenMPTCProuter VPS version: 0.1026.5.4.100-mptcp
  - OpenMPTCProuter VPS provider: OVHCloud
  - OpenMPTCProuter platform: x86

Hey i have a problem with amazon prime video when i go on primevideo i have that 
![image](https://user-images.githubusercontent.com/53863206/135716091-09fcbd14-66f8-4ac5-ad73-5a296a9596c6.png)

I have that in omr bypass section
![image](https://user-images.githubusercontent.com/53863206/135716117-c1976149-33be-4f6a-9cd9-b95558006faa.png)

But not work

**Comment by bagou4502** [comment]
on freebox its work but alexa not work and on pc not work

**Comment by Ysurac** [comment]
OMR-ByPass is made for that. VPS IP are often banned by Netflix, Amazon Video,...
You need to use a VPS that doesn't have IP banned (often small VPS provider), or use OMR-ByPass to use a dedicated connection but you will not have aggregated connection.

**Comment by bagou4502** [comment]
do you know french vps provider not banned?

**Comment by bagou4502** [comment]
and i see vpn i don t see ip banned men
