### ISSUE TITLE
How to see the active lines and the speeds from the command prompt in an active manner

### ISSUE THREAD

**Issue by rifaterdemsahin** [Ysurac/openmptcprouter#2106]
I CAN SSH AND HTOP ON THE DEBIAN
![image](https://user-images.githubusercontent.com/5270036/135810201-26f43d19-5e2f-4691-900f-49e9128e7ed6.png)

how can see the current use of my 4 connections in action?
Similar to this but with the bandwidth usage at the real time
![image](https://user-images.githubusercontent.com/5270036/135810379-f6c0ab66-f05d-4bc0-9561-787f8818448f.png)

The simpler version of this would work 
![image](https://user-images.githubusercontent.com/5270036/135810519-3c904519-3461-4dc8-9810-e99f19612121.png)

^^^ by the way I cant use this as the labels are not on top and I need to have a label field so I can understand which one working

**Comment by Ysurac** [comment]
I don't know what you want exactly, but like htop there is ```iftop``` installed by default on OpenMPTCProuter.
