### ISSUE TITLE
block BIT TORRENT

### ISSUE THREAD

**Issue by sonnyxp2008** [Ysurac/openmptcprouter#2107]
## Expected Behavior

block bittorrent forever

## Current Behavior

I don't know how to stop it permanently

## Specifications

  - OpenMPTCProuter version: v0.58rc5 r0+16336-b36068d35d
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter VPS provider:
  - OpenMPTCProuter platform:

**Comment by Ysurac** [comment]
For now there is now easy way. Maybe by adding an interface that do nothing and using omr-bypass to direct traffic to it.

**Comment by sonnyxp2008** [comment]
you know it is AS20440?
