### ISSUE TITLE
ERROR SERVER

### ISSUE THREAD

**Issue by sonnyxp2008** [Ysurac/openmptcprouter#2108]
Resolving www.openmptcprouter.com (www.openmptcprouter.com)... 95.141.xxx
Connecting to www.openmptcprouter.com (www.openmptcprouter.com)|95.141.xxx5|:4                                                                                                                                                             43... connected.
ERROR: The certificate of ‘www.openmptcprouter.com’ is not trusted.
ERROR: The certificate of ‘www.openmptcprouter.com’ has expired.

**Comment by Ysurac** [comment]
Duplicate of  #2105

**Comment by sonnyxp2008** [comment]
keeps giving the same problem debian 10
