### ISSUE TITLE
ORM Bybass VoWifi rule

### ISSUE THREAD

**Issue by AlexandreGagner** [Ysurac/openmptcprouter#2109]
Hello,

Anyone know what rules we can add in ORM Bybass to bypass "VoWifi" of iPhone/Cellphone ?
In french we call this "Appel Wifi".
Is this specific for each phone operator ?

It's very unstable when I use it on mptcp wifi, and work great on direct ISP (Orange).

Thanks in advance
Alexandre

**Comment by dcnowhere** [comment]
Hello, sae question for me :)

**Comment by AlexandreGagner** [comment]
J'ai appliqué les règles en OMG-DSCP, on va voir ce que ça donne :-) Car les ips et domaine c'était orange et ici ya plusieurs opérateur :-)
