### ISSUE TITLE
Another VPS that works for your "Install or Update the VPS" list of VPS Providers

### ISSUE THREAD

**Issue by beginrescueend** [Ysurac/openmptcprouter#2111]
I just wanted to let you know that Kamatera also works as a VPS provider. I have tested under Ubuntu 20.04 using your install script. https://www.kamatera.com/

I use the $4 / month plan (Type "A" / 1 CPU / 1G RAM / 20G SSD). It includes ~5T transfer / month at no additional charge and no throttling.

https://github.com/Ysurac/openmptcprouter/wiki/Install-or-update-the-VPS

I see "Powered by openmptcprouter v0.58.5 r0+16336-b36068d35d" in my web console - VPS server and client are at the same version.

**Comment by Ysurac** [comment]
Added.
Thanks
