### ISSUE TITLE
Question: How to properly use a captive portal?

### ISSUE THREAD

**Issue by reedog117** [Ysurac/openmptcprouter#212]
## Expected Behavior

Master interface connected to Wi-Fi adapter connected to captive portal. Would like to access captive portal through device and login so that Glorytun VPN/Shadowsocks can successfully connect

## Actual Behavior

Receive IP via DHCP. resolv.conf.auto file contains correct DNS entries. However can not connect to captive portal through LAN interface (DNS doesn’t seem to work). However running nslookup manually using the external DNS server from the device works (for the captive portal domain).

What settings need to be set to properly connect to a captive portal, login/accept terms, and connect to the Internet?

**Comment by Ysurac** [comment]
No idea. And no idea if it's possible. Captive portal often doesn't have all ports open... 
And settings can't be the same for all captive portal. No idea how your captive portal identify users...
