### ISSUE TITLE
Netgear WAC124 - compatible with omr

### ISSUE THREAD

**Issue by vinceducat** [Ysurac/openmptcprouter#2128]
**Is this request related to a missing driver support for a particular hardware platform, SoC or board? Please describe.**

**Describe why you are asking for this support?**

**Additional context**

i have netgear wac124 seems openwrt support this device, is OMR could support it and how can install omr

https://openwrt.org/toh/netgear/wac124

**Comment by Ysurac** [comment]
I only support device that I own.
And this device have a quite slow CPU, with small RAM, not sure this can run OMR in good conditions.
