### ISSUE TITLE
Support Driver for Microchip's LAN7800 USB 3.0 to GbE (Gigabit Ethernet Bridge)

### ISSUE THREAD

**Issue by riccardo1696** [Ysurac/openmptcprouter#2129]
**Is this request related to a missing driver support for a particular hardware platform, SoC or board? Please describe.**

https://wiki.seeedstudio.com/Dual-Gigabit-Ethernet-Carrier-Board-for-Raspberry-Pi-CM4/
The second Lan is on PCIE usb Microchip LAN7800 . Can you support eth1 with driver?

**Describe why you are asking for this support?**

with this support one could divide the WAN from the Lan

**Additional context**

**Comment by suyuan168** [comment]
CONFIG
ADD
CONFIG_USB_LAN78XX=y

**Comment by riccardo1696** [comment]
Ok but i must compile a new image of Openmptcprouter with this option or can i add a module to my istallation?
