### ISSUE TITLE
ping spike with glorytun TCP

### ISSUE THREAD

**Issue by SoGooDFR** [Ysurac/openmptcprouter#213]
## Expected Behavior

Talk on teamspeak without ping spike.

## Actual Behavior

When i use glorytun TCP, when I talk on teamspeak, the ping increases step by step from 50ms to 3000ms. This behavior only appear with glorytun-tcp and when i talk on teamspeak (upload).

## Aggregation details
Two 4G stable connections.

## Steps to Reproduce the Problem

  1. Fresh install on both
  2. Take popcorn and see the problem.

## Specifications

  - OpenMPTCProuter version: openmptcprouter v0.40.2 r7365-91a8bc1dd0
  - OpenMPTCProuter VPS version: 0.61
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
And no problems with glorytun UDP ?

**Comment by SoGooDFR** [comment]
No problem with Glorytun-UDP or SS-UDP.

**Comment by Ysurac** [comment]
I think this can be a MTU problem.

**Comment by linuzel** [comment]
I had the same issue, I solved by changing the congestion control (in MPTCP settings) from BBR to Cubic.
Everything seems fine now.

**Comment by SoGooDFR** [comment]
This is so weird. For 4G links, the best is BBR.

**Comment by dnwk** [comment]
What's the difference between BBR and Cubic? Is there any documentation on what they do?
