### ISSUE TITLE
USB Ethernet RPI3

### ISSUE THREAD

**Issue by Frisk-0** [Ysurac/openmptcprouter#2131]
Hello,

## Expected Behavior
RPI 3 has ethernet port limited to 100 mbits. I have an usb 3 to gigabit ethernet adapter and I know it's possible to get far better speed with it than the original ethernet port but it doesn't seem to work with omr

## Current Behavior
I cannot reach the router through the adapter,  there are lights up on the switch but no dhcp

## Specifications

  - OpenMPTCProuter version: 0.58.5
  - OpenMPTCProuter platform: RPI3

Thank you for your help

**Comment by Ysurac** [comment]
RP3 doesn't support USB3 and USB speed is shared with ethernet port.

**Comment by Frisk-0** [comment]
It's far better, no doubt and I do new with old. I find rpi4 pretty expensive and didn't want to get rid of my rpi3 just for that. The usb 2 bus speed limit fits my needs.
