### ISSUE TITLE
PB IP WAN ANSWER

### ISSUE THREAD

**Issue by fverryden** [Ysurac/openmptcprouter#2148]
Bonjour , 

Je sollicite votre aide afin de m’enlever une épine du pied.

La partie VPS fonctionne parfaitement et je vous en remercie.
J’ai 4 Liens (2 Fibres et deux ADSL) je souhaites pouvoir utiliser ces adresses IP de manières indépendantes mais qui pointent toutes vers une DMZ avec une adresse unique ( Pas de filtrage au niveau de l’OPENMTCP)

A ce jour j’ai mes ports qui sont bien ouverts . J’arrive a le vérifier sans problèmes mais lorsque je fais un dumptcp l’adresse de retour est forcément celle du VPS et cela me pose de sérieux soucis.
En effet les équipements qui interagissent avec les miens ont besoin de la même adresse de retour que celle ou ils m’on joins. Or a ce jour impossible malgré du nattage, de la mise en de l’OMR Bypass etc. …
Je sèche .

Auriez-vous des pistes a me donner ?

**Comment by Ysurac** [comment]
Si le lien est fournis par un routeur, le plus simple, vu que passer par OpenMPTCProuter n'est pas utile, est... de ne pas passer par OpenMPTCProuter.Tout brancher sur un switch manageable, utilisé des VLANs ou des sous réseaux différents et aucun soucis.
Sinon effectivement la configuration d'OpenMPTCProuter risque d'être plus complexe.
