### ISSUE TITLE
Install Mikrotik Re11-LTE Modem

### ISSUE THREAD

**Issue by GTiDon** [Ysurac/openmptcprouter#2149]
Hello

Please help to install this modem
Mikrotik Re11-LTE Modem

## Current Behavior
Currently I can detect the modem but OpenWRT says it is disabled and there is no network activity.
I tried using it with Modem Manager, UMTS/GPRS/EV-DO and NCM

## Specifications

  - OpenMPTCProuter version: openmptcprouter v0.58.5 r0+16336-b36068d35d
  - OpenMPTCProuter VPS version: 5.4.100-mptcp 0.1026
  - OpenMPTCProuter VPS provider:
  - OpenMPTCProuter platform: x86_64
  - 
  - ease do not attach text files) -->

**Comment by GTiDon** [comment]
![image](https://user-images.githubusercontent.com/51342593/139839977-1d5ce18c-c035-4a11-b020-b1f4560420b1.png)
![image](https://user-images.githubusercontent.com/51342593/139840030-2a801759-f378-47d3-aba9-0b876cd6f454.png)

**Comment by GTiDon** [comment]
![image](https://user-images.githubusercontent.com/51342593/139845781-baa0e065-6079-4007-998a-1cb806c175ff.png)

**Comment by Nickmcl024** [comment]
Any luck get getting these modems to work with it
