### ISSUE TITLE
Version check on router

### ISSUE THREAD

**Issue by kamcio2603** [Ysurac/openmptcprouter#215]
## Expected Behavior

  In English please.

## Actual Behavior
Version check is not working correctly :P 
https://gyazo.com/d6948e103acae4f0c10a9d03b57fb061

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - OpenMPTCProuter version:  v0.41 r7382-4f40d4ca73
  - OpenMPTCProuter VPS version: 0.64
  - OpenMPTCProuter platform: (x86_64)

**Comment by Ysurac** [comment]
I forget to update to latest version number.
Fixed.
