### ISSUE TITLE
Linksys WRT3200ACM interfaces

### ISSUE THREAD

**Issue by applamosca** [Ysurac/openmptcprouter#2154]
on the Linksys WRT3200ACM i can't set interfaces interfaces in bridge someone can help me
![tutorial](https://user-images.githubusercontent.com/12274601/140073124-965217cf-5846-4227-b56c-7c4366da3715.jpg)

**Comment by Ysurac** [comment]
Please use template.
If you can't set interface in bridge mode it's because you can't, it's not supported on this platform.

**Comment by applamosca** [comment]
I am following this video tutorial and it tells me to install this firmware, then to set the lan port in bridge.
Where am I wrong? can you help me I'm your supporter
![tutorial1](https://user-images.githubusercontent.com/12274601/140514433-93642945-8b33-4b6b-957a-c088926a4c7a.jpg)
![tutorial2](https://user-images.githubusercontent.com/12274601/140514438-fe9b2197-0c40-4c25-8730-bd90c508400b.jpg)
