### ISSUE TITLE
Glorytun - question

### ISSUE THREAD

**Issue by kamcio2603** [Ysurac/openmptcprouter#216]
## Expected Behavior

  Glorytun UDP running on all CPUs

## Actual Behavior
Glorytun UDP mode is using only one core of CPU.

## Steps to Reproduce the Problem

  1. Compile
  2. Run udp test
  3. 100% CPU of 1 core

## Specifications

 OpenMPTCProuter version: v0.41 r7382-4f40d4ca73
 OpenMPTCProuter VPS version: 0.64
 OpenMPTCProuter platform: (x86_64)

**Comment by Ysurac** [comment]
Glorytun UDP is not multithreaded. Nothing I can really do about that.
