### ISSUE TITLE
Raspberry GPIO Shutdown and power Up

### ISSUE THREAD

**Issue by GTiDon** [Ysurac/openmptcprouter#2168]
**Is your enhancement proposal related to a problem? Please describe.**

My Pi has corrupted its SD card after loosing power. This is a serious reliability issue for a headless unit.

**Describe the solution you'd like**

I am not sure if this function exists already. With Raspbian you can enable Power up and Shutdown with GPIO pins
Can this be done with OpenWRT?

**Describe alternatives you've considered**

**Additional context**

**Comment by Adorfer** [comment]
see https://forum.openwrt.org/t/how-to-make-gpio-shutdown-overlay-work/64088/2
