### ISSUE TITLE
Remove firewalls rules trough bash

### ISSUE THREAD

**Issue by bagou4502** [Ysurac/openmptcprouter#2173]
## Specifications

  - OpenMPTCProuter version: i can t get it because openmptcprouter was down
  - OpenMPTCProuter VPS version: i can t get it because openmptcprouter was down
  - OpenMPTCProuter VPS provider: hostmyserver
  - OpenMPTCProuter platform: x86

Hey i add recently a firewall rule on openmptcprouter panel for open a port but after that the panel was unreachable
How  i can remove this rule trough ssh or bash?

**Comment by Ysurac** [comment]
All configuration is available via SSH using ```uci```, it's also in /etc/config

**Comment by bagou4502** [comment]
yes but in where file i can remove this rule??

**Comment by bagou4502** [comment]
what file*

**Comment by bagou4502** [comment]
i can t see the openned port in ssh is very strange

**Comment by Ysurac** [comment]
```/etc/config/firewall```

**Comment by bagou4502** [comment]
> ```/etc/config/firewall```

I see notching about my port modification in this file...
