### ISSUE TITLE
Add serial ports to Raspberry 4 OMR

### ISSUE THREAD

**Issue by highfreq** [Ysurac/openmptcprouter#2174]
Anyone know how can serial ports be added to OMR on a raspberry 4?
Raspberry 4 has 5 serials that can be configured.
Is there anything special to OMR or i can just follow an openwrt tutorial on how to do it?

thanks

**Comment by Adorfer** [comment]
thats certainly an OpenWRT question. if it works for plain OpenWRT it will certainly work for OMR as well.

**Comment by highfreq** [comment]
I asked because on openwrt forum advice on adding serials simply editing the config.txt in /boot, but i don't have it in the image i used to install OMR.
Does it make any difference the type of image i use of the 2 available in the downloads?

**Comment by Ysurac** [comment]
There is a config.txt in /boot on RPI4 images.
