### ISSUE TITLE
Add zone dns to forward

### ISSUE THREAD

**Issue by ThibautBascoulergue** [Ysurac/openmptcprouter#2176]
Openmptcp version 0.58.5
VPS version : 0.10.26.5.4.100

Hello,

I want to add a forwarded zone ex: toto.ovh.fr to another dns server.

I have added this on my unound.conf "/var/lib/unbound/unbound.conf" from Luci interface but it doesn't work.

forward-zone:
  name: toto.ovh.fr
  forward-addr: 10.1.1.5@53
  forward-first: yes
  forward-tls-upstream: no

When i check with nslookup toto.ovh.fr, he returns "Non existent domain"

Thx

**Comment by Ysurac** [comment]
You can use the "DNS forwardings" field in Network->DHCP & DNS, setting something like "/toto.ovh.fr/10.1.1.5"
