### ISSUE TITLE
To see the action on the router using the terminal

### ISSUE THREAD

**Issue by rifaterdemsahin** [Ysurac/openmptcprouter#2178]
I wanna have a terminal monitor which show the real-time action
iftop and htop combo needed

Explained in detail here
https://youtu.be/cJku-LyvjoI

**Comment by rifaterdemsahin** [comment]
I tried the netdata without luck
PASS solution would be great
![image](https://user-images.githubusercontent.com/5270036/141663742-02e2f61f-c9ae-4d43-9fb9-b5d1388b8377.png)

**Comment by Ysurac** [comment]
OpenMPTCProuter is based on OpenWrt, there is a netdata package available. So you should be able to install it via ```opk update && opkg install netdata```.
If you have some certificate error, check https://github.com/Ysurac/openmptcprouter/issues/2099
