### ISSUE TITLE
Status interface down to email not work

### ISSUE THREAD

**Issue by ThibautBascoulergue** [Ysurac/openmptcprouter#218]
## Expected Behavior

  
After configuring the email part, there is an error when an interface falls on the msmtprc configuration file in /etc/msmtprc

## Actual Behavior

![image](https://user-images.githubusercontent.com/42678960/48573143-a790d900-e90b-11e8-8ad3-24fa8046e1ec.png)
## Steps to Reproduce the Problem
  
![image](https://user-images.githubusercontent.com/42678960/48573448-8381c780-e90c-11e8-8548-7c3e6a041567.png)

## Specifications

  - OpenMPTCProuter version: (0.41)
  - OpenMPTCProuter VPS version: (0.64)
  - OpenMPTCProuter platform: (x86_64)

**Comment by Ysurac** [comment]
Really ? an empty bug reports with no details ?

**Comment by ThibautBascoulergue** [comment]
lol sorry failed past :)

**Comment by ThibautBascoulergue** [comment]
nothing in log after restart or stop and start

**Comment by Ysurac** [comment]
What is the result of `uci show mail` ? (without secret info)

**Comment by ThibautBascoulergue** [comment]
![image](https://user-images.githubusercontent.com/42678960/48573893-f8093600-e90d-11e8-932e-2adac81e6754.png)

**Comment by Ysurac** [comment]
All seems good, you should have a `/etc/msmtprc`, at least when you run `/etc/init.d/msmtp restart`

**Comment by ThibautBascoulergue** [comment]
mmh :/ another problem :+1: 
![image](https://user-images.githubusercontent.com/42678960/48574194-d197ca80-e90e-11e8-8b60-a17daf27d2d5.png)

**Comment by Ysurac** [comment]
I think this time the problem is not on my side. Check your settings and if your VPS provider doesn't block some ports.

**Comment by ThibautBascoulergue** [comment]
ok thx

**Comment by Ysurac** [comment]
OpenMPTCProuter v0.41.1 will fix msmtprc creation.
I will try with a gmail account if it's working (on another provider than scaleway that blocks all smtp ports).

**Comment by ThibautBascoulergue** [comment]
ok fine
