### ISSUE TITLE
Aggregation fails when using modems with IPs in same subnet

### ISSUE THREAD

**Issue by SriramScorp** [Ysurac/openmptcprouter#2180]
When I use 3 USB modems with the same IP (192.168.42.1) and giving DHCP leases in the subnet 192.168.42.0/24, traffic flows only through one of the modems, based on the interface metric. The IP and DHCP range seems hardcoded in the modems and I'm unable to change them. Does aggregation work with this setup as long the interface IPs are unique? Or is it mandatory that each WAN interface should have IPs in unique subnet?

**Comment by SriramScorp** [comment]
@Ysurac Does [this](https://github.com/Ysurac/openmptcprouter/issues/1525#issuecomment-761763868) mean, aggregation works when using multiple modems with IPs in same network?

**Comment by Ysurac** [comment]
You can have multiple modems in same network if each modems are on dedicated interface.

**Comment by wlatic** [comment]
Going through an issue Im seeing and this may help.

Would a Vlan be counted as a dedicated network?

I've got 3 LTE connections all on the same provider and on the same tower (currently), the performance of a single connection is good and putting the 3 into load balancing causes a very unstable connection.
