### ISSUE TITLE
QoS availability

### ISSUE THREAD

**Issue by sadahsan** [Ysurac/openmptcprouter#2186]
Does the system support end to end QoS support through shadowsocks and glorutun TCP or does it respect ToS markings? or any of those are dropped when passing between router and VPS?

Many Thanks

**Comment by kencogit** [comment]
This interests me also if we have links that may vary or go up/down then there may be a need to prioritise one class of packet.

**Comment by edaspb** [comment]
Same here. I'm looking for the option to make shadowsocks-libev transparent for ToS. For now all ToS marks are dropped. I found this related issue https://github.com/shadowsocks/shadowsocks-libev/issues/2591. Looks like shadowsocks-libev originally considered ToS trans-passing but there is a bug in implementation.
