### ISSUE TITLE
will esspressobin image run on Gl.inetMV100?

### ISSUE THREAD

**Issue by packlet** [Ysurac/openmptcprouter#2188]
picked up a Gl.inet GL-MV1000 (Brume, no wifi.)  Looking to use it as VPN server and possibly OpenMTCPRouter.

 https://openwrt.org/toh/gl.inet/gl-mv1000

Marvell Armada 88F3720 (same as the ESPRESSObin)

Will the Espressobin image work on this?  or will it require a special build (ala 'unsupported platform')?

Thanx,  Paul.

**Comment by Ysurac** [comment]
It will require a special build.
If you don't want to aggregate, you can use OpenWrt directly and install needed VPN packages manually.
