### ISSUE TITLE
Wifi

### ISSUE THREAD

**Issue by Nadeistos** [Ysurac/openmptcprouter#219]
Hi,
All works fine in wired mode, network and internet works at full speed, but on a wifi connexion every thing is slow, even browse local networks is complicated... any tips ? :)

Thanks (et merci pour ton logiciel :) )

  - OpenMPTCProuter version: 0.41
  - OpenMPTCProuter VPS version: 0.64
  - OpenMPTCProuter platform: RPI3b+

**Comment by Ysurac** [comment]
Wifi is always slow ;)
This seems to be working for me. 
What are your wifi settings and your configuration of wifi interface ? (I should make a page on the wiki about that...)

**Comment by rstanislav** [comment]
RPI3b+ has very poor internal wifi, don't expect any good results from it..
