### ISSUE TITLE
SHADOWSOCKS VERSION 3.3.5-2 INSTALLATION ERROR

### ISSUE THREAD

**Issue by lferreira93** [Ysurac/openmptcprouter#2190]
## Expected Behavior
Completed the installation of VPS script.

## Current Behavior
During processing the script on Debian 10, the follwoing messages appeared and the script didnt complete.

"E: Version '3.3.5-2' for 'omr-shadowsocks-libev' was not found
root@VPS-OMR:/home/lferreira#"

## Specifications

  - OpenMPTCProuter version: v0.58.5 
  - OpenMPTCProuter VPS version: I dont know
  - OpenMPTCProuter VPS provider: Azure
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
Should be working now.
New packages for the next release removed current stable package.
