### ISSUE TITLE
Linksys WRT3200ACM don't work MPTCP over VPN with WireGUARD

### ISSUE THREAD

**Issue by mdiaco** [Ysurac/openmptcprouter#2193]
I've install Firmware Version：openmptcprouter v0.58.5 r0+16336-b36068d35d.
i have a configuration with 3 wan, one of them goes on LTE and the service provider blocks the MPTCP traffic.

To get around this problem, the MPTCP protocol encapsulated in a vpn is normally used.
The method that works best is with wireguard. I did a configuration test but it doesn't work due to lack of several packages

this is a System log:
Sun Nov 28 14:31:57 2021 daemon.err modprobe: 3 modules could not be probed
Sun Nov 28 14:31:57 2021 daemon.err modprobe: - libblake2s
Sun Nov 28 14:31:57 2021 daemon.err modprobe: - libchacha20poly1305
Sun Nov 28 14:31:57 2021 daemon.err modprobe: - wireguard
Sun Nov 28 14:31:57 2021 daemon.notice netifd: wgWAN2 (24128): Unable to modify interface: Protocol not supported
Sun Nov 28 14:32:02 2021 daemon.notice netifd: Interface 'wgWAN2' is now down
Sun Nov 28 14:32:02 2021 daemon.notice netifd: Interface 'wgWAN2' is setting up now
Sun Nov 28 14:32:02 2021 kern.warn kernel: [43874.349186] vmap allocation for size 20480 failed: use vmalloc=<size> to increase size
Sun Nov 28 14:32:02 2021 kern.warn kernel: [43874.357243] vmap allocation for size 20480 failed: use vmalloc=<size> to increase size

Any suggestions on how to fix this?
Thanks

**Comment by Ysurac** [comment]
Please use the template.

In this case vmalloc need to be increased or some module removed. I will check what is the better for this platform.
