### ISSUE TITLE
Forward ports

### ISSUE THREAD

**Issue by zal31** [Ysurac/openmptcprouter#220]
Hello, how i can redirect ports?
Exemple
IP VPS XX.XX.XX.XX:5000 to IP lan : 192.168.100.200:21

i have 3 client on lan with FTP server 

it's ok for redirect XX.XX.XX.XX:3000 to 192.168.100.200:3000 but if i try to change port it don't work

Thank you for help

**Comment by Ysurac** [comment]
Follow this: https://github.com/Ysurac/openmptcprouter/wiki/Port-forwarding

**Comment by zal31** [comment]
i do that and work fine if i redirect XX.XX.XX.XX:3000 to 192.168.100.200:3000 but if i try to change port it don't work

**Comment by Ysurac** [comment]
You only change internal port in firewall config ?

**Comment by zal31** [comment]
yes only internal (192.168.100.200), it doesn't work.

**Comment by Ysurac** [comment]
I need to see your config.
Can you give me the `/etc/config/firewall` or `uci show firewall` on OpenMPTCProuter ?
