### ISSUE TITLE
support for rb750gr3 ( mikrotik )

### ISSUE THREAD

**Issue by epictz06** [Ysurac/openmptcprouter#2200]
**Is this request related to a missing driver support for a particular hardware platform, SoC or board? Please describe.**

Hello , is there anyway to flash OMR on this router? i need only one shadowsocks package and mptcp enabled , i want to ask is it possible to flash OMR on this router?

**Comment by Ysurac** [comment]
It have a slow CPU and a small flash.
You can try to compile it yourself using https://github.com/Ysurac/openmptcprouter/wiki/Create-image-for-unsupported-platform

**Comment by thelastdreamer** [comment]
Hello, right now mikrotik support even containers or even direct openwrt with many models supported.

Is there any image which i can use to install?
It would be great if you create something like this for mikrotik since they are value for money.
