### ISSUE TITLE
Open port TCP / UDP

### ISSUE THREAD

**Issue by sonnyxp2008** [Ysurac/openmptcprouter#2201]
## Expected Behavior

Open port 3074 tcp and 3074 udp

## Current Behavior

I can't open any ports in firewall/Port Forwards
## Specifications

  - OpenMPTCProuter version: v0.58rc5 r0+16336-b36068d35d
  - OpenMPTCProuter VPS version: VPS 0.1026 
  - OpenMPTCProuter VPS provider: Aruba
  - OpenMPTCProuter platform: x86_64
![Immagine OMR PORT](https://user-images.githubusercontent.com/78047559/144503577-3f778936-ae81-434a-a8ec-525860941add.jpg)

**Comment by Ysurac** [comment]
Did you follow the debug of port forwarding doc ? https://github.com/Ysurac/openmptcprouter/wiki/Port-forwarding#debug
