### ISSUE TITLE
Raspberry CM4

### ISSUE THREAD

**Issue by highfreq** [Ysurac/openmptcprouter#2202]
Is OMR compatible with CM4?
Would like to use this:

https://raspberrypi.dk/en/product/iot-router-cm4-carrier-board-mini/?currency=EUR&gclid=CjwKCAiAwKyNBhBfEiwA_mrUMvrg6qncFkC4H2jH0LV1P9t4K36FO85Qz7z5X1oVDTlqikIXBpOIlhoCRQoQAvD_BwE

**Comment by Ysurac** [comment]
This may be supported in next release.

**Comment by highfreq** [comment]
When will new release be out?

**Comment by highfreq** [comment]
It would be great if it could be supported, it is small, powerful enough and with 2 ethernet ports.

**Comment by highfreq** [comment]
@Ysurac , have any news on CM4 support? Would like to use it on a new project.

**Comment by Ysurac** [comment]
Snapshot should support CM4

**Comment by highfreq** [comment]
Is it stable enough to be used?

Can i use emmc on board?

**Comment by highfreq** [comment]
Found the snapshots but a bit lost, would you mind give me a link for the correct image to be used?

thanks,

Corrado

**Comment by Ysurac** [comment]
I've a daily job, I answer on free time only...
Images are here: https://download.openmptcprouter.com/develop/5.4/rpi4/targets/bcm27xx/bcm2711/
Should be quite stable, OMR VPS snapshot may be needed too: `wget -O - http://www.openmptcprouter.com/server-test/debian10-x86_64.sh | sh`
It's not tested on CM4.

**Comment by highfreq** [comment]
@Ysurac VPS snapshot is the regular debian 10 vps, looks like so from the link you provided.

**Comment by Ysurac** [comment]
no, note the "server-test" in the link.

**Comment by highfreq** [comment]
Ooooops sorry, missed it, thanks

**Comment by kamileq** [comment]
So using some development version not the newest beta release to figure out it on RP CM4? Will it work with eMMC solution not microSD card?

**Comment by Ysurac** [comment]
Latest beta should work too.
