### ISSUE TITLE
Monitor and save WAN bandwidth 

### ISSUE THREAD

**Issue by eothein** [Ysurac/openmptcprouter#2207]
Using the Status->Real Time Graphs I'm able to monitor my WAN connections, however, I would like to see the raw data (i.e. using a CSV file) of a certain time period. 

Is there an easy way to do this?

**Comment by Ysurac** [comment]
For this graph, "luci-bwc" is used. There is also vnstat that is installed and can be easier to use.

**Comment by jjak0b** [comment]
> Using the Status->Real Time Graphs I'm able to monitor my WAN connections, however, I would like to see the raw data (i.e. using a CSV file) of a certain time period.
> 
> Is there an easy way to do this?

I usually use "nlbwmon".
I manually added some protocols names to port mapping but it helped me to investigate on bandwidth usages.
It could be improved a lot but does its work.
