### ISSUE TITLE
info hardware support

### ISSUE THREAD

**Issue by ascomputer** [Ysurac/openmptcprouter#2211]
**Is this request related to a missing driver support for a particular hardware platform, SoC or board? Please describe.**

hi, is it possible to use 4g modems on slots m2?
to be more precise I put the link of the modem I would like to buy

https://it.aliexpress.com/item/33042042400.html?src=google&src=google&albch=shopping&acnt=708-803-3821&slnk=&plac=&mtctp=&albbt=Google_7_shopping&albagn=888888&isSmbAutoCall=false&needSmbHouyi=false&albcp=9599454372&albag=98571474866&trgt=1478211641016&crea=it33042042400&netw=u&device=c&albpg=1478211641016&albpd=it33042042400&gclid=EAIaIQobChMIrPWd5Ibc9AIVD-ztCh0SPgN5EAQYASABEgKPvPD_BwE&gclsrc=aw.ds&aff_fcid=08326d5a1d8245a28fc337aa4f402c6e-1639236229978-01347-UneMJZVf&aff_fsk=UneMJZVf&aff_platform=aaf&sk=UneMJZVf&aff_trace_key=08326d5a1d8245a28fc337aa4f402c6e-1639236229978-01347-UneMJZVf&terminal_id=d67de2d1c53943e4bb47f15df2cb7061

thank you
**Describe why you are asking for this support?**
I ask this press to buy

**Additional context**

**Comment by Ysurac** [comment]
Yes it's possible, but this one is only an adapter.
