### ISSUE TITLE
Is there a way to have LTE not coming down?

### ISSUE THREAD

**Issue by highfreq** [Ysurac/openmptcprouter#2213]
VPS: OpenMPTCProuter VPS 0.1026 
Router: Raspberry 3 OpenMPTCProuter VPS 0.1026

I tried everything possible, all kind nof schedulers, all kind of congestion control. All proxies and all Vpn in every combination possible but there is no way to have the connection stay up when the master of the 2 modems comes down.

Every single time master modem comes down the connection comes down untill modems comes up again. This doesn't happen if slave modem comes down. One of the reason we use OMR is for redundancy but at the moment we have never had it working properly.
There is no way to have the connection stay up if master link comes down.

**Comment by cagnulein** [comment]
@highfreq I guess @Ysurac said that it should fix this in the next release 🤞
