### ISSUE TITLE
Netflix  does not work, omr bypass nok

### ISSUE THREAD

**Issue by jarod54490** [Ysurac/openmptcprouter#222]
## Expected Behavior

I try to play netflix on a smarttv with my network (openmptcprouter (adsl+4G) --> OVH vps server)
![capture d ecran 2018-11-23 a 11 16 15](https://user-images.githubusercontent.com/45286308/48938870-c6e2c400-ef12-11e8-8ca8-1f9da5b72e8c.png)

## Actual Behavior

I set omrbypass for Netflix protocol but it doen't work.
![capture d ecran 2018-11-23 a 11 11 37](https://user-images.githubusercontent.com/45286308/48938891-d6620d00-ef12-11e8-92c4-822d4d51c90d.png)

Netflix protocol always goes through mptcp

## Steps to Reproduce the Problem

  1.  OVH vps server located in Strasbourg (France)
  2. OMR-bypass set for NetFlix protocol

## Specifications

  - OpenMPTCProuter version: (v0.41.1 r7390)
  - OpenMPTCProuter VPS version: (0.64)
  - OpenMPTCProuter platform: (RPI3)

**Comment by Ysurac** [comment]
Try to add domains like in https://github.com/Ysurac/openmptcprouter/issues/112

**Comment by Ysurac** [comment]
Domain include anything that use this domain (so HTTP, HTTPS and anything on TCP, UDP,...).
So for netflix you need to set domains used by Netflix and the netflix protocol. It's all.
(In fact netflix protocol should bypass also domains, but this doesn't seems to work... I need to find a way to test that, I don't have netflix)

**Comment by PxxBxx** [comment]
Thanks a lot for this clarification.
Could you also indicate if there is a priority among all types of rules ? (domain, ip/subnet, dpi protocol)
For example, if I set
 - domain X -> wan1
 - ip Y -> wan2
 - protocol Z -> wan3

where will go the request made from Y, using domain X and protocol Z ?

(damn question)

**Comment by Ysurac** [comment]
Not really priority, but should be ip, domain and then protocol. It's the order of iptables rules ;)

**Comment by Ysurac** [comment]
In latest version, you now only need to select protocol netflix and all domains are bypassed too.

**Comment by jarod54490** [comment]
Thanks. I don't need it anymore. I switched my VPS from OVH to FIRSTHEBERG. My IP address is no longer blacklisted by netflix.
However, I think there is a bug in the latest version 0.42.7 with IPERF. With the web interface, I always have the message: error - the server is busy running a test. try again later

**Comment by Ysurac** [comment]
It's not a bug, servers are often busy. I will try to find more servers or an other way to test speed.

**Comment by jarod54490** [comment]
ok
