### ISSUE TITLE
Patreon never an answer

### ISSUE THREAD

**Issue by highfreq** [Ysurac/openmptcprouter#2220]
@Ysurac What is the point of giving direct message with a patreon subscription if you never answer?
Message sent a week ago, never an answer, what a joke.

**Comment by Ysurac** [comment]
I didn't receive any message from Patreon since september and only your today, seems that Patreon have an issue on sending message alert.
I'm often on IRC, available at https://www.openmptcprouter.com/irc, if you want direct answer.
