### ISSUE TITLE
Impossible de me connecter au VPS OVH depuis mon réseau interne sur OMR

### ISSUE THREAD

**Issue by mykelinho** [Ysurac/openmptcprouter#223]
OpenMPTCProuter v0.41 2018-11-12 18:19
OpenMPTCProuter VPS v0.64:
RPI3+
VPS OVH 

Bonjour,
Je ne peux plus me connecter à mon VPS depuis mon réseau WIFI/LAN lié au routeur OPENMTCPROUTER.
Sur putty, WinSCP... La connexion reste refusé.
Je peux me connecté uniquement sur un réseau externe à OMR (4G, ADSL...)
Est-ce un mauvais réglage dans OMR? Je n'ai pourtant touché à rien, mis à part avoir fait la dernière mise à jour.

**Comment by mykelinho** [comment]
effectivement, mais sur putty je tente de me connecter en direct avec l'ip de mon vps et le 65222 ça ne fonctionne pas, alors que si je me connecte à un réseau externe (exemple 4G) ça fonctionne

**Comment by Ysurac** [comment]
Et depuis OpenMPTCProuter `ssh -p 65222 tonip` ?

**Comment by Ysurac** [comment]
Tu essayes par l'IPv4 ou le nom ? Et c'est bien la même IPv4 qui est renseigné dans le wizard ?

**Comment by mykelinho** [comment]
j'essaye avec l'adresse IPv4 et c'est bien la même qui est inscrite dans le wizard

**Comment by Ysurac** [comment]
Je sais pas la. 
L'IP du VPS étant "bypasser" partout (sinon shadowsocks et le VPN ne peuvent pas se connecter dessus), et l'IP fonctionnant depuis OpenMPTCProuter (donc les routes sont bonnes)...
Pas de configuration "étrange" niveau firewall ?
Que donne un `traceroute ipduvps` depuis le client ? Normalement ça doit passer directement par un des WANs.

**Comment by mykelinho** [comment]
Niveau par feu j'ai ouvert le port 80 et 8080 sur 2 ips fixe de mes appareils, rien de plus
Voici le résultat du traceroute 
![image](https://user-images.githubusercontent.com/42909444/48973359-e9bdc700-f03d-11e8-989f-945e17c550f5.png)

**Comment by mykelinho** [comment]
et les configs du par feu 
![image](https://user-images.githubusercontent.com/42909444/48973363-170a7500-f03e-11e8-9e92-0aebfa47c6e0.png)
![image](https://user-images.githubusercontent.com/42909444/48973368-25589100-f03e-11e8-927c-0cb11ccacbd3.png)

![image](https://user-images.githubusercontent.com/42909444/48973381-6ea8e080-f03e-11e8-912f-bdf2acf2652a.png)

**Comment by Ysurac** [comment]
Le traceroute est pas bon : tu passes par le VPN.
Il me faudrait un `ip route`, normalement il y a une route vers l'ip de ton VPS avec une metric de 1, mais ça doit pas être le cas. Il faut que je trouve dans quel cas cette route n'est pas créé...

**Comment by mykelinho** [comment]
merci, quelle est la commande iproute IP ?

**Comment by Ysurac** [comment]
Sur OpenMPTCProuter par ssh, juste `ip route`. Ca donne toutes les routes :)

**Comment by mykelinho** [comment]
voici le résultat ci dessous, 
il semblerait que les 2 VPS que je possèdent soit utilisé alors que j'ai remplacer le OVH 54.xxx par Firstheberg 86.xxx
![image](https://user-images.githubusercontent.com/42909444/48978233-bf552380-f0a8-11e8-9eca-41e393a8d6ea.png)

**Comment by mykelinho** [comment]
j'ai finalement réinstallé l'image openmptcrouter sur mon raspberry et j'ai resaisi mes paramètres (dhcp, firewall)... et ça refonctionne bien.
C'était probablement du à une fausse manip je pense.

**Comment by vinceducat** [comment]
j ai le meme probleme a par une reinstallation comment faire
