### ISSUE TITLE
Support for mlx5 driver

### ISSUE THREAD

**Issue by benedikt-bartscher** [Ysurac/openmptcprouter#2231]
Hello there, i need a driver for my Mellanox ConnectX-4 network card. I am passing it via SRV-IOV to my openmptcprouter VM. I did some research and found the OpenWRT package "kmod-mlx5-core". Could you please add this package to the Openmptcprouter Repo so everyone can install it easy?

Keep the good work up, thank you very much!

**Comment by Ysurac** [comment]
The package kmod-mlx5-core is available in System->Software after updating list.

**Comment by benedikt-bartscher** [comment]
Probably not for bleeding edge versions, right? I get this error message:
"The installed version of package kernel is not compatible, require 5.4.106-1-53b4fb15… while 5.4.132-1-4282eeab… is installed."

**Comment by benedikt-bartscher** [comment]
I just tested the official release and the driver installed fine.
Sadly i am stuck on a boot loop now. While loading mlx5 on boot the QEMU VM directly crashes and reboots. I have SRV-IOV setup and all other VMs are doing fine with these settings. Any advice?

**Comment by benedikt-bartscher** [comment]
![image](https://user-images.githubusercontent.com/31854409/147757754-ef5cf6d3-194e-4de8-92e8-ec2fc1bf6fd6.png)

**Comment by benedikt-bartscher** [comment]
I just tried another Card from HP (qlogic chip). It needs kmod-qlcnic which is sadly not included in openmptcprouter :(
