### ISSUE TITLE
Conf OPEN VPN (OMR , VPS OVH, Freebox, Nas Synology) -pb conf

### ISSUE THREAD

**Issue by gmorlet** [Ysurac/openmptcprouter#2233]
## Expected Behavior
Hello, (i'm french)
I am trying to set up a VPN with OPENMPTCPROUTER in place.

OPENVPN
The VPN server is on the synology nas (I tried openvpn and ipsec which I had before).

In openmptcp router I went to :
- network
- firewall
- port forwarding

conf :
- openvpn
- UDP
- VPN ormvpn
- 1194
- lan
- nas ip 192.168.100.X
- nas port 1194

I installed the openvpn client on windows, in the config file I put the public ip of the VPS and I unchecked to activate : redirect-gateway def1

imported configuration file

but in the end it doesn't work, I must have missed some steps with openmptcprouter

Thanks

Translated with www.DeepL.com/Translator (free version)
## Specifications

  - OpenMPTCProuter version: 5.4.86-mptcp 0.1024
  - OpenMPTCProuter VPS version: 0.1024 5 4 86
  - OpenMPTCProuter VPS provider: OVH
  - OpenMPTCProuter platform: RPI 4

**Comment by Ysurac** [comment]
Try the debug part of this page https://github.com/Ysurac/openmptcprouter/wiki/Port-forwarding#debug
You use windows outside the OpenMPTCProuter network ?
