### ISSUE TITLE
MPTCP seems to be blocked 

### ISSUE THREAD

**Issue by patimages** [Ysurac/openmptcprouter#2242]
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/6791434/149150232-4d7d6ef4-6068-4f1a-9477-c32b7bae9124.png">

Hello, 
I have an issue with MPTCP (worked well for years) and it does seem that the MPCTP is not blocked by the provider so what could be my problem? FYI, I am on the latest versions of server and client. 
Merci encore !

**Comment by Ysurac** [comment]
Please use the template when you open an issue.
As you can see with MPTCP Support Check it's a false issue.

**Comment by patimages** [comment]
Sorry for missing out on the template (it has been a while since I had issues, I forgot the process: you did too good of a job :-D). 
This false issue leads to a dramatically reduced bandwidth (most of the bandwidth goes trough the slow DSL interface), any advice to recover ?

**Comment by patimages** [comment]
PS : the alerts just disappeared ... Any idea what was the problem ?

**Comment by Ysurac** [comment]
They way the test is now made may result in this problem if some packets are lost for example.

**Comment by patimages** [comment]
Got it : thanks again for the fastest support ever !
