### ISSUE TITLE
Openmptcp in OverTheBox Plus ?

### ISSUE THREAD

**Issue by Pokpok-sbo** [Ysurac/openmptcprouter#2244]
Hello !

I was wondering if anyone has ever tried installing OPEMPTCP in an "OverTheBox Plus"?
Otherwise do you think it is feasible?

Thank you

**Comment by Adorfer** [comment]
I can confirm, that at least one person has tried it, and technically it was running. 
(For the feasibilty can can not state, since this question is marked "otherwise"; but since the the first question is true, this one is not to be answered.)

**Comment by suyuan168** [comment]
Totally doable, I think OverTheBox Plus is based on an x86. So it can install Omr

**Comment by Adorfer** [comment]
> So it can install Omr

Yes, **installing** is no problem. 
Running it? see [#1551](https://github.com/Ysurac/openmptcprouter/issues/1551)
