### ISSUE TITLE
new version not working at all

### ISSUE THREAD

**Issue by mstrolo** [Ysurac/openmptcprouter#2247]
## Expected Behavior

Omr alpha 0.59 upgrade working

## Current Behavior

i have nothing that can connect 
cannot connect to the vps server and not to any LTE modem i have connected
![image](https://user-images.githubusercontent.com/7146444/149654685-62c5cbb3-2e43-4adc-af0a-18134d6be8aa.png)

## Specifications

  - OpenMPTCProuter version: openmptcprouter v0.58.5 r0+18442-02de391b08
  - OpenMPTCProuter VPS version: 0.1027-test 5.4.132-mptcp
  - OpenMPTCProuter VPS provider: y on server that i rented 
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
I don't know what you mean, there is no new release.
If you mean snapshot release, there is 2 snapshot based on 2 kernel that doesn't work the same way.

**Comment by mstrolo** [comment]
yes I have installed the snapshot

can you explain what does that means?

2 kernels

do you have any idea why its not working for me now?

**Comment by Ysurac** [comment]
no, I don't know what version you downloaded.
Snapshot are not mean to be stable, it's snapshot ;)

**Comment by mstrolo** [comment]
openmptcprouter v0.58.5 r0+18442-02de391b08
that one

so if i want to go back to the server version and openmptcp version that was stable just downgrade and run the script n the vps?

**Comment by mstrolo** [comment]
VPS version is 0.1027-test

can i downgrade it?

**Comment by mstrolo** [comment]
this is where am at now:

![image](https://user-images.githubusercontent.com/7146444/149657741-70e2b714-800f-4344-97e0-e90fc88238ce.png)

**Comment by Ysurac** [comment]
Yes you should use normal VPS script.
What is strange is that wan address you get are Private address...

**Comment by mstrolo** [comment]
from the lte modems?

**Comment by mstrolo** [comment]
now its good but i have other issue

every time am runing a test something else falls down

my log:

![image](https://user-images.githubusercontent.com/7146444/149761644-9b7070ae-480b-4f78-ab6b-6bcf5e00ec8a.png)

**Comment by Ysurac** [comment]
You may need to enable SQM with download and upload speed in wizard.

**Comment by mstrolo** [comment]
> You may need to enable SQM with download and upload speed in wizard.

did that but yet i have one of them falling down:

![image](https://user-images.githubusercontent.com/7146444/149827731-96f2d783-7655-441c-b5a3-7f8f74fc7e1c.png)


![image](https://user-images.githubusercontent.com/7146444/149827889-d217b013-bd41-44ab-80c6-d84283e332b7.png)

![image](https://user-images.githubusercontent.com/7146444/149827983-45d3e4a2-7dc0-4176-a934-86d16078f2a0.png)

**Comment by mstrolo** [comment]
changed the SQM and yet
![image](https://user-images.githubusercontent.com/7146444/149837761-42acf41c-8980-4d63-afa7-ef4d4fa5088d.png)

**Comment by hairy-dog** [comment]
There is something wrong with how your network settings are. On my system, I have wan1 with an IP address of 192.168.14.10, wan2 on 192.168.12.10 and want3 on 192.168.10.10 - each of them has a wan address allocated by their remote network.
In your earlier screen captures, your wan addresses were local addresses, which can never work. Now they look correct, but your ip addresses for them are in different ranges.
I suggest that you put that right first.
