### ISSUE TITLE
MPTCP ISSUE IF GATEWAY DOWN AND UP AGAIN

### ISSUE THREAD

**Issue by PunjabLive1** [Ysurac/openmptcprouter#2251]
## Expected Behavior

Hello
i am using openmptcprouter from the last 3 months for link aggregation up to 5 connections, Everything is working fine but I am facing one issue,  currently using 5 internet connections for bandwidth aggregation but if any connection is down for a few seconds then mptcp kick out those line from aggregating even if the line up again after few seconds,  then we have to Manually unplug rj45 cable from the router and plug again then it start aggregation again.         

## Specifications

  - OpenMPTCProuter version: 
  - V0.58.5
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter VPS provider:
  - GOOGLE CLOUD
  - OpenMPTCProuter platform:

**Comment by Ysurac** [comment]
Can you check what you have in Status->System log when this happen ?
