### ISSUE TITLE
wan or server keep turning off

### ISSUE THREAD

**Issue by mstrolo** [Ysurac/openmptcprouter#2252]
## Expected Behavior

when I am connecting all the Wans and the server they appear green and all fine
![image](https://user-images.githubusercontent.com/7146444/150593137-52d7e2d6-c200-4db8-bd01-075b8940aaae.png)

## Current Behavior
every time I am running a speed test something turns down and the system turns it off.

![image](https://user-images.githubusercontent.com/7146444/150593017-1257be2f-6ae9-4e26-b2a6-ce1e1c58a1de.png)
![image](https://user-images.githubusercontent.com/7146444/150593231-7a4fe4ef-6b8c-4598-9a22-3744a5b93728.png)
![image](https://user-images.githubusercontent.com/7146444/150593463-168008ea-c162-43ba-84d2-922e5757c549.png)

![image](https://user-images.githubusercontent.com/7146444/150593309-1f12a3bc-fd2a-4fd1-9008-1f2b3d3398cf.png)

## Specifications

  - OpenMPTCProuter version: 
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter VPS provider:
  - OpenMPTCProuter platform:

**Comment by Ysurac** [comment]
As you can see in log, ping from 10.100.102.90 to 1.1.1.1 for example is not working.
You can check yourself using "ping -B -I 10.100.102.90 1.1.1.1"
Check that ping is allowed, if it's not the case use another method in Services->OMR-Tracker

**Comment by mstrolo** [comment]
PING 1.1.1.1 (1.1.1.1) from 10.100.102.90 : 56(84) bytes of data.
64 bytes from 1.1.1.1: icmp_seq=1 ttl=58 time=15.4 ms
64 bytes from 1.1.1.1: icmp_seq=2 ttl=58 time=14.8 ms
64 bytes from 1.1.1.1: icmp_seq=3 ttl=58 time=14.1 ms
64 bytes from 1.1.1.1: icmp_seq=4 ttl=58 time=14.5 ms
64 bytes from 1.1.1.1: icmp_seq=5 ttl=58 time=14.8 ms
64 bytes from 1.1.1.1: icmp_seq=6 ttl=58 time=16.0 ms
64 bytes from 1.1.1.1: icmp_seq=7 ttl=58 time=16.6 ms
64 bytes from 1.1.1.1: icmp_seq=8 ttl=58 time=14.2 ms

**Comment by Ysurac** [comment]
At least sometimes packets are lost.
You can try to disable "Server http test" in Services->OMR-Tracker, this may help for wan2.
You should also update to latest stable release.

**Comment by mstrolo** [comment]
so i need to add wan2 in the omr-tracker
and disable the server http test?
