### ISSUE TITLE
Seamless failover of master connection on 2xLTE

### ISSUE THREAD

**Issue by highfreq** [Ysurac/openmptcprouter#2263]
## Expected Behavior

Connection stays up if one of the LTE links goes down 

I asked this about 10 times, it is not difficult, i just would like the 2 connections to be redundant somehow but i never got an answer. I already tried redundant as congestion control but it acts the same. Maybe i need 2 masters or 3 connections?

Basicly i need the connection to be fault tollerant on master link.

## Current Behavior

If Master goes down connection is lost for 15-20 seconds. Pinging tunnel from VPS times out for 15-20 seconds as soon as master link is disconnected.

## Specifications

2 x LTE modems
OpenMPTCProuter version: v0.58.5 r0+16336-b36068d35d
OpenMPTCProuter VPS version: 0.1026 5.4.100-mptcp
OpenMPTCProuter VPS provider: Aruba
OpenMPTCProuter platform: RPi4

**Comment by Ysurac** [comment]
Should be better in latest OpenMPTCProuter beta/snapshot.
Only one master must be defined.

**Comment by highfreq** [comment]
I defined only 1 master, is latest snapshot stable enough to be used in production?

**Comment by Ysurac** [comment]
Snapshot/beta is not yet ready for production, it still need more tests.

**Comment by highfreq** [comment]
when do you think it'll be out? more or less?

**Comment by Ysurac** [comment]
No idea, I hope soon...

**Comment by highfreq** [comment]
Ok, thanks :)

**Comment by highfreq** [comment]
Is multiple router on one VPS something that will be possible on next release?

**Comment by Ysurac** [comment]
No.

**Comment by TalalMash** [comment]
Seamless failover is working with openmptcprouter v0.59beta6-5.4 r0+16591-b4ea8e1089
A milestone passed :)
