### ISSUE TITLE
lost password for user interface

### ISSUE THREAD

**Issue by gmorlet** [Ysurac/openmptcprouter#2264]
Bonjour j'ai accès en root en ssh
mais sur l'interface web, il semble que j'ai modifié mon mot de passe du root ou qu'il soit modifié dans gestionnaire de mdp

comment réinitialiser le mot de pass root sans devoir tout refaire

Merci

**Comment by Ysurac** [comment]
Le mot de passe est normalement le même que celui via SSH.
Vous pouvez essayer avec un autre navigateur, ou virer le cache de l'interface web via SSH ```rm -fr /tmp/luci-*```
Sinon le mot de passe peut être au niveau de rpcd, ce que vous pouvez voir avec un ```uci show rpcd```
