### ISSUE TITLE
Second WAN aren't reachable by openmptcprouter

### ISSUE THREAD

**Issue by xillibit** [Ysurac/openmptcprouter#2268]
## Expected Behavior

The second wan should be reachable by openmptcprouter

## Current Behavior
The second wan isn't reachable by openmptcprouter, i have switched the sim card on the huawei fro a different mobile provider. If i connect directly my PC on the huawei router or on the freebox, i can access the web interface on his IP: 192.168.8.1

![image](https://user-images.githubusercontent.com/876395/153627882-85577d88-97ec-4fa2-81bc-7e276644d001.png)

![image](https://user-images.githubusercontent.com/876395/153627922-ddd5ee12-30bc-4a43-a5f8-7925efe755b6.png)

I had already encountered this issue in the past : https://github.com/Ysurac/openmptcprouter/issues/1955 but this time by rebooting the huawei it has no effect

## Specifications

  - OpenMPTCProuter version: 0.58.5
  - OpenMPTCProuter VPS version: 0.1026
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
The problem here is that pinging VPS via the huawei doesn't answer. You can try with a ```ping -B -I wan2 51.158.xxxx``` (use real VPS IP).
If ping is blocked on the connection, in services->omr-tracker, add wan2 in interface and use another type then ping.

**Comment by xillibit** [comment]
Yes ping was blocked : 
![image](https://user-images.githubusercontent.com/876395/153665928-63913d72-7c79-497e-8d92-f47008f352df.png)

I have added wan2, do-i tick enable ? It's here that i change the type from ping to something else ?
![image](https://user-images.githubusercontent.com/876395/153666159-83a76551-fa0e-481b-aef8-79fb3f1d341a.png)

**Comment by Ysurac** [comment]
yes, it's here that you have to change from ping to what you want. Make sure sure host can answer to the type you choose.

**Comment by xillibit** [comment]
I have tried in type httping and dns, the ping is still blocked. What do-you call the host ?

**Comment by Ysurac** [comment]
Ping will always be blocked as it's blocked by ISP or modem.
What is needed is to have a check that can detect when connection is up or down. If you don't care, you can set it to "None".
Hosts are the server used to do the check (ping/dns/http destination), it's called "Hôtes" in french.
With your settings, DNS check should work and you should no more have a red cross in status page (only the message).

**Comment by Ysurac** [comment]
Check Status->System log to find what is the problem exactly.

**Comment by xillibit** [comment]
You can find it here : https://gist.github.com/xillibit/6f5d05343a021b49346385cb84320b16

**Comment by xillibit** [comment]
Did-you have looked my system log ?

**Comment by Ysurac** [comment]
What is needed is when "omr-tracker" detect the interface as down.

**Comment by xillibit** [comment]
The interface wan2 is alwas down

**Comment by Ysurac** [comment]
This can be a status page error, did you check if aggregation work or not ?
And on system log I need what mentions "omr-tracker" or "post-tracking-post-tracking".

**Comment by xillibit** [comment]
My freebox was disconnecting re-synching between 20h15 and 21h30, i had no internet when the freebox was disconnected so no aggregation

I have found that part with menions of omr-tracker : 

Fri Mar  4 20:11:36 2022 daemon.info glorytun[8492]: STARTED tun0
Fri Mar  4 20:11:40 2022 daemon.err /usr/bin/ss-local[14682]: getpeername: Socket not connected
Fri Mar  4 20:11:41 2022 user.notice post-tracking-post-tracking: wan1 (wan1) switched off because check error, interface have no IPv6, interface have no IPv6 gateway and ping from 192.168.10.2 error (80.67.169.40,114.114.114.114,1.1.1.1)
Fri Mar  4 20:11:41 2022 user.notice post-tracking-post-tracking: Delete default route via 192.168.10.1 dev wan1
Fri Mar  4 20:11:43 2022 daemon.err /usr/bin/ss-local[14682]: getpeername: Socket not connected
Fri Mar  4 20:11:47 2022 daemon.err glorytun[8492]: read: Operation timed out
Fri Mar  4 20:11:47 2022 daemon.info glorytun[8492]: STOPPED tun0
Fri Mar  4 20:11:53 2022 daemon.err /usr/bin/ss-redir[14684]: remote recv: Operation timed out
Fri Mar  4 20:11:53 2022 daemon.err /usr/bin/ss-redir[14685]: remote recv: Operation timed out
Fri Mar  4 20:11:58 2022 daemon.info omr-tracker-ss: Shadowsocks sss0 is down (can't contact via http 151.101.129.164, 77.88.55.77, 1.1.1.1)
Fri Mar  4 20:11:58 2022 user.notice Shadowsocks: Rules DOWN
Fri Mar  4 20:12:03 2022 daemon.err /usr/bin/ss-local[14682]: getpeername: Socket not connected
Fri Mar  4 20:12:13 2022 daemon.err /usr/bin/ss-local[14682]: getpeername: Socket not connected
Fri Mar  4 20:12:13 2022 daemon.err /usr/bin/ss-redir[14684]: remote recv: Operation timed out
Fri Mar  4 20:12:14 2022 daemon.info omr-tracker-ss: Server sss0 (51.158.xxx.xxx) seems down, no answer to ping
Fri Mar  4 20:12:20 2022 daemon.err glorytun[8492]: 51.158.xxx.xxx.65001: connected
Fri Mar  4 20:12:20 2022 daemon.info glorytun[8492]: STARTED tun0
Fri Mar  4 20:12:21 2022 user.notice post-tracking-post-tracking: Tunnel up : Replace default route by 10.255.255.1 dev tun0
Fri Mar  4 20:12:22 2022 daemon.info omr-tracker-ss: Shadowsocks sss0 is up (can contact via http 74.82.42.42)
Fri Mar  4 20:12:22 2022 daemon.info omr-tracker-ss: Reload Shadowsocks rules
Fri Mar  4 20:12:22 2022 user.notice Shadowsocks: Rules UP

Fri Mar  4 20:02:34 2022 daemon.err /usr/bin/ss-local[14682]: fast_open_connect: Network unreachable
Fri Mar  4 20:02:39 2022 daemon.err /usr/bin/ss-local[14682]: fast_open_connect: Network unreachable
Fri Mar  4 20:02:41 2022 daemon.warn odhcpd[5625]: A default route is present but there is no public prefix on LAN2 thus we don't announce a default route!
Fri Mar  4 20:02:44 2022 daemon.err /usr/bin/ss-local[14682]: fast_open_connect: Network unreachable
Fri Mar  4 20:02:49 2022 daemon.err /usr/bin/ss-local[14682]: fast_open_connect: Network unreachable
Fri Mar  4 20:02:49 2022 user.notice post-tracking-post-tracking: wan1 (wan1) switched up
Fri Mar  4 20:02:49 2022 user.notice post-tracking-post-tracking: Set ip route replace default scope global  nexthop via 192.168.10.1 dev wan1 weight 2
Fri Mar  4 20:02:49 2022 daemon.err glorytun[8766]: 51.158.xxx.xxx.65001: connected
Fri Mar  4 20:02:49 2022 daemon.info glorytun[8766]: STARTED tun0
Fri Mar  4 20:02:53 2022 user.notice post-tracking-post-tracking: Tunnel up : Replace default route by 10.255.255.1 dev tun0
Fri Mar  4 20:02:54 2022 daemon.info omr-tracker-ss: Shadowsocks sss0 is up (can contact via http 77.88.55.77)
Fri Mar  4 20:02:54 2022 daemon.info omr-tracker-ss: Reload Shadowsocks rules
Fri Mar  4 20:02:54 2022 user.notice Shadowsocks: Rules UP
Fri Mar  4 20:02:54 2022 user.notice Shadowsocks: Reload omr-bypass rules
Fri Mar  4 20:02:54 2022 user.notice omr-bypass: Starting OMR-ByPass...
Fri Mar  4 20:02:54 2022 user.notice omr-bypass: Reload dnsmasq...
Fri Mar  4 20:02:55 2022 daemon.info dnsmasq[3681]: read /etc/hosts - 4 addresses
Fri Mar  4 20:02:55 2022 daemon.info dnsmasq[3681]: read /tmp/hosts/dhcp.cfg01411c - 1 addresses
Fri Mar  4 20:02:55 2022 daemon.info dnsmasq-dhcp[3681]: read /etc/ethers - 0 addresses
Fri Mar  4 20:02:55 2022 user.notice omr-bypass: OMR-ByPass is running
Fri Mar  4 20:06:19 2022 daemon.err /usr/bin/ss-local[14682]: remote_recv_cb_recv: Operation timed out
Fri Mar  4 20:06:22 2022 daemon.err glorytun[8766]: read: Operation timed out
Fri Mar  4 20:06:22 2022 daemon.info glorytun[8766]: STOPPED tun0
Fri Mar  4 20:06:22 2022 daemon.err glorytun[8766]: 51.158.xxx.xxxx.65001: connected

**Comment by Ysurac** [comment]
There is a problem yes, not the IPv6 but that there is no "IP WAN" so it seems that you don't get any IPv4. In this case OpenMPTCProuter can't use it over IPv4.
You may need to change APN on the modem configuration (or use IPv6 everywhere but not so easy...).

**Comment by xillibit** [comment]
The default APN profil on the Huawei was set on IPv4 and IPv6, i have changed it to IPv4 now it's working on OMR : 
![image](https://user-images.githubusercontent.com/876395/156877142-65519456-e3f6-4cdd-b66d-40f7247b39ab.png)
