### ISSUE TITLE
VPS in Cloud - which ports are required to be opened for inbound connections 

### ISSUE THREAD

**Issue by sadahsan** [Ysurac/openmptcprouter#2275]
Hi,

I would appreciate your advise that which ports (TCP, UDP, ICMP) should I open for the inbound connection on VPS running in cloud?

Thanks

**Comment by sadahsan** [comment]
Thank you, much appreciated.

**Comment by sadahsan** [comment]
I am planning to disable below services on VPS as I won't be using them, do see any problem with it?

dsvpn-server@dsvpn0.service
glorytun-udp@tun0.service
mlvpn@mlvpn0.service
openvpn@bonding1.service
openvpn@bonding2.service
openvpn@bonding3.service
openvpn@bonding4.service
openvpn@bonding5.service
openvpn@bonding6.service
openvpn@bonding7.service
openvpn@bonding8.service
openvpn@tun0.service
openvpn@tun1.service
wg-quick@wg0.service

Thanks

**Comment by sadahsan** [comment]
Thank you Sir.

**Comment by sadahsan** [comment]
Hi again,

I am following your instruction as below and it seems like UDP is still going via glorytun.

![image](https://user-images.githubusercontent.com/43149221/154689199-73505add-842d-401f-aecb-70ca09649298.png)

![image](https://user-images.githubusercontent.com/43149221/154689250-8b5e906e-1e5b-43e8-b852-9008227128be.png)

**Comment by Ysurac** [comment]
advanced settings checkbox in wizard, not the tab.
