### ISSUE TITLE
Routing does not work when using SRT

### ISSUE THREAD

**Issue by kzzanuda** [Ysurac/openmptcprouter#2277]
## Expected Behavior

Hi! Unfortunately, packet routing does not work when broadcasting over the SRT protocol. All the configuration recommendations for working with UDP were used, but this does not help.

## Current Behavior

When working with the Internet normally, it is clear that all 4 channels are used as intended. In the broadcast mode, the video stream ceases to be divided and works only on 1 channel. Tell me, what else could be the problem?
I used V2Ray with Glorytun UDP.

## Specifications

  - OpenMPTCProuter version: [v0.58.5](https://github.com/Ysurac/openmptcprouter/releases/tag/v0.58.5)
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter VPS provider:
  - OpenMPTCProuter platform: RPI3 B+
  -

**Comment by aircooled76** [comment]
I am interested in this topic.  Were you able to send a "normal" video stream like an RTMP stream correctly?

**Comment by kzzanuda** [comment]
> I am interested in this topic.  Were you able to send a "normal" video stream like an RTMP stream correctly?

I'm try send video by RTMP, but it's working every bit as.
