### ISSUE TITLE
Port Foward not working over IPV6

### ISSUE THREAD

**Issue by cfrstr** [Ysurac/openmptcprouter#2278]
## Expected Behaviour
When a traffic rule is added ports should open over ipv6. This is on v0.59beta2-5.4 so fixes from https://github.com/Ysurac/openmptcprouter/issues/2027 should be in the build according to github.

Traffic rule is 

config rule
        option name 'DMZ-IPV6'
        option src 'vpn'
        option dest 'dmz'
        option target 'ACCEPT'
        option family 'ipv6'
        list proto 'tcp'
        list proto 'udp'
        option src_port '22-60000'
        list dest_ip 'fdbe:4841:332a:0:1a31:bfff:fecc:704e/64'

## Current Behaviour

Ports unreachable and vps shorewall6 rules files doesn't change. IPv4 works fine and shorewall rules file is updated.

## Specifications

  - OpenMPTCProuter version: v0.59beta2-5.4
  - OpenMPTCProuter VPS version: OpenMPTCProuter VPS 0.1027-test
  - OpenMPTCProuter VPS provider: Linode
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
I see "src_port", should be "src_dport", I just tested and shorewall6 rules is updated.
