### ISSUE TITLE
Running VPS install script on existing server does not generate OpenMPTCProuter VPS key

### ISSUE THREAD

**Issue by dnwk** [Ysurac/openmptcprouter#228]
## Expected Behavior

  In English please.
When running the VPS install script for update, it should generate the VPS management key same as new install. 
## Actual Behavior
VPS management is either did not generate or not display to user. 

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - OpenMPTCProuter version: (Last is not a version)
  - OpenMPTCProuter VPS version: (Last is not a version)  Tested both Debian and Ubuntu
  - OpenMPTCProuter platform: (RPI2/RPI3/x86/x86_64)

**Comment by Ysurac** [comment]
True, I forget that. It's fixed now.
You can run the update script again or look at `/etc/openmptcprouter-vps-admin/omr-admin-config.json` for the key.
