### ISSUE TITLE
Can Network be monitored without Admin Login Access

### ISSUE THREAD

**Issue by GTiDon** [Ysurac/openmptcprouter#2281]
Hello

I need to let somebody monitor status/bandwidth etc my device but don't want them to have admin access? Can this be done ?

**Comment by Ysurac** [comment]
You can use SNMP or create an user in System->ACL

**Comment by GTiDon** [comment]
Thankyou I have just discovered the ACL options but I cant login with a new user I create. It just says "Invalid username and password Please try again"

I want a junior to use a web interface

**Comment by GTiDon** [comment]
If the user can just view http://10.0.21.1/cgi-bin/luci/admin/system/openmptcprouter/status thats all I need
