### ISSUE TITLE
V2Ray Not Running / Dropping Out - RPI4 - 0.58.5

### ISSUE THREAD

**Issue by jamesbrindle** [Ysurac/openmptcprouter#2282]
## Expected Behavior

Switch to V2Ray as the default proxy and it works - and be stable.

## Current Behavior

Either it never comes up (it just says 'V2Ray is not running') or it eventually comes up, and everything is OK for about 5 minutes, then it goes down again.

## Steps to Reproduce the Problem

On the luci interface, go to: 

`System -> OpenMTPCProuter -> (tab) Settings Wizard -> (check) -> Show advanced settings:`

Then switch 'Defaulf proxy' to 'V2Ray'.

Wait a good amount of time until everything has reloaded and see in the OpenMPTCProuter 'Status' section starts and you get a green 'tick' on both the VPS and OpenMPTCProuter. 

If after a good amount of time V2Ray is still not up and running, then perform a reboot and repeat.

## Context (Environment)

I'm trying to get V2Ray working so that:

a) I can acheive better WireGuard VPN speeds (to / from my LAN)
b) Better UDP speeds for things like streaming?

## Specifications

  - **OpenMPTCProuter version:** 0.58.5
  - **OpenMPTCProuter VPS version:** OpenMPTCProuter VPS 0.1026
  - **OpenMPTCProuter VPS provider:** OVHcloud
  - **OpenMPTCProuter platform:** RPI4
  - **Country:** UK
 
## Information

First off - **Thank you** for your time and effort getting this working. It's had a huge benefit for myself and many others... living in an area with poor internet speeds and without expert linux know-how. This was only dreamed about just a few years ago. I managed to get something up and running just using linux packages and scripts - But nothing on this level and it was time consuming!

I've been trying to get V2Ray working as the default proxy for a couple of weeks now. I've tried various things such as:

1. Removing all entries from the 'Port Forwards' section in the firewall - Just in case i'm having port conflicts
2. Changing the congestion algorythm (bb2, cubic)
3. Changing the TCP scheduler (BLEST, ECF, Round-Robin)
4. **A complete factory reset:**

I've tried re-flashing the SD card to stock factory and starting again - Thinking maybe something has gone wrong somewhere in my settings or something has become corrupted.... And strangely it does actually work for a short time... I then carefully start altering settings - Such as adding things to OMR bypass, adding a few port forwarding rules, adding DDNS, so that if OMR goes down my WAN services will still work, and sure enough, after a reboot I start facing the same V2Ray issues. I don't know what else to try.

It just says 'V2Ray not running'

![A test image](https://portfolio.jb-net.co.uk/shared/v2ray/v2ray-not-running2.jpg)

It looks as though V2Ray is constantly restarting, and taking its time coming up:

![A test image](https://portfolio.jb-net.co.uk/shared/v2ray/v2ray-not-running-top.jpg)

I'm aware I should attach 'text files' - I'm not sure if that means linking to them, or pasting them in this post, so I apologies if I've not done this properly, but here is the **System Log:**

[System Log Text File](https://portfolio.jb-net.co.uk/shared/v2ray/v2ray-not-running-system-log.txt)  *- hold CTRL to open in new tab*

And here is **'All Settings':**

[All Settings Text File](https://portfolio.jb-net.co.uk/shared/v2ray/v2ray-not-running-all-settings3.txt)  *- hold CTRL to open in new tab*

Any help would be much appreciated, and again, thank you!

**Comment by jamesbrindle** [comment]
Well... Don't all answer at once

**Comment by Ysurac** [comment]
You can check ```/var/log/daemon.log on VPS```.
An iptables rule seems to not apply correctly, did you install any additional package ?
You can also try latest beta.

**Comment by jamesbrindle** [comment]
Hey,

Thanks for that.

I have installed additional packages yes, these:

* GIT
* DDNS
* FTP Server
* Collectd - Statistics

I couldn't find anything particular in `/var/log/daemon.log` I'm afraid...

Also, I tried the latest beta. Everything was going OK and seemingly a lot quicker and smoother, but I then ran into the same issue when I began adding to the configs.

I have, however, managed to replicate the issue and I think I know vaguely what's causing it - It's the OMR-Bypass. Everything was going fine until I started to add rows into the OMR-Bypass config (via the Luci UI).

When I removed all items from OMR-Bypass, the problem went away.

It "seems" to be OK when adding full LAN IP addresses to ignore (my TV), but as soon as I start adding protocols and domains - the problem arises after a reboot.

This problem only seems to happen when the V2Ray proxy is used as the default.

Since OMR-Bypass is more important to me than the probable UDP performance gains from using V2Ray as opposed to shadowsocks, I've elected go back the 0.58.5 build and wait until a fix for this comes to fruition.

Thanks for your help, your software and your time.

**Comment by Ysurac** [comment]
Can you give me the result of ```uci show omr-bypass`` via SSH on the router part ?

**Comment by jamesbrindle** [comment]
Yep, no problem:

omr-bypass.all=interface
omr-bypass.m6replay=proto
omr-bypass.m6replay.url='m6web.fr' '6play.fr' '6cloud.fr'
omr-bypass.mycanal=proto
omr-bypass.mycanal.url='mycanal.fr' 'canal-plus.com' 'canalplus.com' 'canalplus-cdn.net' 'canalplus.pro' 'canal-plus.net'
omr-bypass.minecraft=proto
omr-bypass.minecraft.url='authserver.mojang.com'
omr-bypass.lesnumeriques=proto
omr-bypass.lesnumeriques.url='lesnumeriques.com' 'botscorner.com' 'app.botscorner.com'
omr-bypass.disneyplus=proto
omr-bypass.disneyplus.url='bamgrid.com' 'disney-plus.net'
omr-bypass.amazonvideo=proto
omr-bypass.amazonvideo.url='cloudfront.net' 'llnw.net'
omr-bypass.lo=interface
omr-bypass.lo.id='5'
omr-bypass.eth0=interface
omr-bypass.eth0.id='6'
omr-bypass.wan1=interface
omr-bypass.wan1.id='3'
omr-bypass.wan2=interface
omr-bypass.wan2.id='4'
omr-bypass.wan3=interface
omr-bypass.wan3.id='8'
omr-bypass.tun0=interface
omr-bypass.tun0.id='1200'
omr-bypass.wlan0=interface
omr-bypass.wlan0.id='11'
omr-bypass.WireGuardVPN=interface
omr-bypass.WireGuardVPN.id='8'
omr-bypass.WGVPN=interface
omr-bypass.WGVPN.id='10'
omr-bypass.@dpis[0]=dpis
omr-bypass.@dpis[0].proto='amazonvideo'
omr-bypass.@dpis[1]=dpis
omr-bypass.@dpis[1].proto='netflix'
omr-bypass.@dpis[2]=dpis
omr-bypass.@dpis[2].proto='disneyplus'
omr-bypass.@dpis[3]=dpis
omr-bypass.@dpis[3].proto='spotify'
omr-bypass.@ips[0]=ips
omr-bypass.@ips[0].ip='45.60.74.52'
omr-bypass.@ips[0].note='gov.uk'
omr-bypass.@ips[1]=ips
omr-bypass.@ips[1].ip='205.251.197.92'
omr-bypass.@ips[1].note='Netflix'
omr-bypass.@ips[2]=ips
omr-bypass.@ips[2].ip='205.251.192.81'
omr-bypass.@ips[2].note='Netflix'
omr-bypass.@ips[3]=ips
omr-bypass.@ips[3].note='Netflix'
omr-bypass.@ips[3].ip='205.251.194.147'
omr-bypass.@ips[4]=ips
omr-bypass.@ips[4].ip='205.251.199.192'
omr-bypass.@ips[4].note='Netflix'
omr-bypass.@ips[5]=ips
omr-bypass.@ips[5].ip='52.0.131.132'
omr-bypass.@ips[5].note='Netflix'
omr-bypass.@ips[6]=ips
omr-bypass.@ips[6].ip='3.221.228.214'
omr-bypass.@ips[6].note='Netflix'
omr-bypass.@ips[7]=ips
omr-bypass.@ips[7].ip='18.207.84.236'
omr-bypass.@ips[7].note='Netflix'
omr-bypass.@lan_ip[0]=lan_ip
omr-bypass.@lan_ip[0].ip='192.168.1.25'
omr-bypass.@lan_ip[0].note='GoogleTV'
omr-bypass.@macs[0]=macs
omr-bypass.@macs[0].mac='F8:4E:17:47:ED:D5'
omr-bypass.@macs[0].note='GoogleTV'
omr-bypass.@domains[0]=domains
omr-bypass.@domains[0].name='adnxs.com'
omr-bypass.@domains[1]=domains
omr-bypass.@domains[1].name='adobedtm.com'
omr-bypass.@domains[2]=domains
omr-bypass.@domains[2].name='alicdn.com'
omr-bypass.@domains[3]=domains
omr-bypass.@domains[3].name='aiv-cdn.net'
omr-bypass.@domains[4]=domains
omr-bypass.@domains[4].name='footprint.net'
omr-bypass.@domains[5]=domains
omr-bypass.@domains[5].name='aiv-delivery.net'
omr-bypass.@domains[6]=domains
omr-bypass.@domains[6].name='amazon.com'
omr-bypass.@domains[7]=domains
omr-bypass.@domains[7].name='amazonvideo.com'
omr-bypass.@domains[8]=domains
omr-bypass.@domains[8].name='turner.com'
omr-bypass.@domains[9]=domains
omr-bypass.@domains[9].name='netflix.com'
omr-bypass.@domains[10]=domains
omr-bypass.@domains[10].name='botscorner.com'
omr-bypass.@domains[11]=domains
omr-bypass.@domains[11].name='spotify.com'
omr-bypass.@domains[12]=domains
omr-bypass.@domains[12].name='akamaihd.net'
omr-bypass.@domains[13]=domains
omr-bypass.@domains[13].name='edgesuite.net'
omr-bypass.@domains[14]=domains
omr-bypass.@domains[14].name='mojang.com'
omr-bypass.@domains[15]=domains
omr-bypass.@domains[15].name='nr-data.net'
omr-bypass.@domains[16]=domains
omr-bypass.@domains[16].name='bamgrid.com'
omr-bypass.@domains[17]=domains
omr-bypass.@domains[17].name='botscorner.com'
omr-bypass.@domains[18]=domains
omr-bypass.@domains[18].name='btstatic.com'
omr-bypass.@domains[19]=domains
omr-bypass.@domains[19].name='registerdisney.go.com'
omr-bypass.@domains[20]=domains
omr-bypass.@domains[20].name='samsungcloudsolution.com'
omr-bypass.@domains[21]=domains
omr-bypass.@domains[21].name='smartadserver.com'
omr-bypass.@domains[22]=domains
omr-bypass.@domains[22].name='gigya.com'
omr-bypass.@domains[23]=domains
omr-bypass.@domains[23].name='amazonaws.com'
omr-bypass.@domains[24]=domains
omr-bypass.@domains[24].name='conviva.com'
omr-bypass.@domains[25]=domains
omr-bypass.@domains[25].name='cloudfront.net'
omr-bypass.@domains[26]=domains
omr-bypass.@domains[26].name='flashtalking.com'
omr-bypass.@domains[27]=domains
omr-bypass.@domains[27].name='omtrdc.net'
omr-bypass.@domains[28]=domains
omr-bypass.@domains[28].name='directvnow.com'
omr-bypass.@domains[29]=domains
omr-bypass.@domains[29].name='disney-plus.net'
omr-bypass.@domains[30]=domains
omr-bypass.@domains[30].name='onetrust.com'
omr-bypass.@domains[31]=domains
omr-bypass.@domains[31].name='bn5x.net'
omr-bypass.@domains[32]=domains
omr-bypass.@domains[32].name='disneyplus.com'
omr-bypass.@domains[33]=domains
omr-bypass.@domains[33].name='omtrdc.net'
omr-bypass.@domains[34]=domains
omr-bypass.@domains[34].name='disney.co.jp'
omr-bypass.@domains[35]=domains
omr-bypass.@domains[35].name='demdex.net'
omr-bypass.@domains[36]=domains
omr-bypass.@domains[36].name='dssott.com'
omr-bypass.@domains[37]=domains
omr-bypass.@domains[37].name='akamaized.net'
omr-bypass.@domains[38]=domains
omr-bypass.@domains[38].name='sascdn.com'
omr-bypass.@domains[39]=domains
omr-bypass.@domains[39].name='hulu.com'
omr-bypass.@domains[40]=domains
omr-bypass.@domains[40].name='huluad.com'
omr-bypass.@domains[41]=domains
omr-bypass.@domains[41].name='huluim.com'
omr-bypass.@domains[42]=domains
omr-bypass.@domains[42].name='hulustream.com'
omr-bypass.@domains[43]=domains
omr-bypass.@domains[43].name='nflxvideo.net'
omr-bypass.@domains[44]=domains
omr-bypass.@domains[44].name='newrelic.com'
omr-bypass.@domains[45]=domains
omr-bypass.@domains[45].name='maxmind.com'
omr-bypass.@domains[46]=domains
omr-bypass.@domains[46].name='lesnumeriques.com'
omr-bypass.@domains[47]=domains
omr-bypass.@domains[47].name='media-amazon.com'
omr-bypass.@domains[48]=domains
omr-bypass.@domains[48].name='spotify.com'
omr-bypass.@domains[49]=domains
omr-bypass.@domains[49].name='nflxext.com'
omr-bypass.@domains[50]=domains
omr-bypass.@domains[50].name='nflximg.com'
omr-bypass.@domains[51]=domains
omr-bypass.@domains[51].name='nflximg.net'
omr-bypass.@domains[52]=domains
omr-bypass.@domains[52].name='nflxsearch.net'
omr-bypass.@domains[53]=domains
omr-bypass.@domains[53].name='nflxso.net'
omr-bypass.@domains[54]=domains
omr-bypass.@domains[54].name='amazontrust.com'
omr-bypass.@domains[55]=domains
omr-bypass.@domains[55].name='primevideo.com'
omr-bypass.@domains[56]=domains
omr-bypass.@domains[56].name='zkcdn.net'
omr-bypass.@domains[57]=domains
omr-bypass.@domains[57].name='starott.com'
omr-bypass.@domains[58]=domains
omr-bypass.@domains[58].name='llnwd.net'
omr-bypass.@domains[59]=domains
omr-bypass.@domains[59].name='fast.com'
omr-bypass.@domains[60]=domains
omr-bypass.@domains[60].name='gov.uk'
omr-bypass.@domains[61]=domains
omr-bypass.@domains[61].name='service.gov.uk'
omr-bypass.@domains[62]=domains
omr-bypass.@domains[62].name='gstatic.com'
omr-bypass.@domains[63]=domains
omr-bypass.@domains[63].name='google-analytics.com'
omr-bypass.@domains[64]=domains
omr-bypass.@domains[64].name='queue-it.net'
omr-bypass.@dpis[4]=dpis
omr-bypass.@dpis[4].proto='deezer'
omr-bypass.@dpis[5]=dpis
omr-bypass.@dpis[5].proto='hulu'
omr-bypass.@domains[65]=domains
omr-bypass.@domains[65].name='national-lottery.co.uk'
omr-bypass.@domains[66]=domains
omr-bypass.@domains[66].name='ifttt.com'
omr-bypass.@ips[8]=ips
omr-bypass.@ips[8].ip='65.8.249.6'
omr-bypass.@ips[8].note='IFTTT'
omr-bypass.@ips[9]=ips
omr-bypass.@ips[9].ip='65.8.249.44'
omr-bypass.@ips[9].note='IFTTT'
omr-bypass.@ips[10]=ips
omr-bypass.@ips[10].ip='65.8.249.16'
omr-bypass.@ips[10].note='IFTTT'
omr-bypass.@ips[11]=ips
omr-bypass.@ips[11].ip='65.8.249.84'
omr-bypass.@ips[11].note='IFTTT'
omr-bypass.@ips[12]=ips
omr-bypass.@ips[12].ip='217.163.91.193'
omr-bypass.@ips[12].note='National Lottery'
omr-bypass.@ips[13]=ips
omr-bypass.@ips[13].ip='217.163.91.193'
omr-bypass.@ips[13].note='National Lottery'
omr-bypass.@ips[14]=ips
omr-bypass.@ips[14].ip='194.246.78.128'
omr-bypass.@ips[14].note='National Lottery'
omr-bypass.@asns[0]=asns
omr-bypass.@asns[0].asn='2906'
omr-bypass.@asns[0].note='Netflix'
omr-bypass.@asns[1]=asns
omr-bypass.@asns[1].asn='55095'
omr-bypass.@asns[1].note='Netflix'
omr-bypass.@asns[2]=asns
omr-bypass.@asns[2].asn='40027'
omr-bypass.@asns[2].note='Netflix'
omr-bypass.@asns[3]=asns
omr-bypass.@asns[3].asn='AS2906'
omr-bypass.@asns[3].note='Netflix'
omr-bypass.@asns[4]=asns
omr-bypass.@asns[4].note='Netflix'
omr-bypass.@asns[4].asn='AS55095'
omr-bypass.@asns[5]=asns
omr-bypass.@asns[5].asn='AS40027'
omr-bypass.@asns[5].note='Netflix'
omr-bypass.@asns[6]=asns
omr-bypass.@asns[6].asn='16509'
omr-bypass.@asns[6].note='Amazon'
omr-bypass.@asns[7]=asns
omr-bypass.@asns[7].asn='AS16509'
omr-bypass.@asns[7].note='Amazon'
omr-bypass.@asns[8]=asns
omr-bypass.@asns[8].asn='14618'
omr-bypass.@asns[8].note='HBOMAX'
omr-bypass.@asns[9]=asns
omr-bypass.@asns[9].asn='AS14618'
omr-bypass.@asns[9].note='HBOMAX'
omr-bypass.@asns[10]=asns
omr-bypass.@asns[10].asn='23286'
omr-bypass.@asns[10].note='Hulu'
omr-bypass.@asns[11]=asns
omr-bypass.@asns[11].asn='AS23286'
omr-bypass.@asns[11].note='Hulu'
omr-bypass.@asns[12]=asns
omr-bypass.@asns[12].asn='10753'
omr-bypass.@asns[12].note='National Lottery'
omr-bypass.@asns[13]=asns
omr-bypass.@asns[13].asn='AS10753'
omr-bypass.@asns[13].note='National Lottery'

**Comment by jamesbrindle** [comment]
I've been trying to analyse the system log a little more...

There definitely seems to be a bit of a cat and mouse scenario of 'Starting OMR-Bypass', then stating V2Ray, then OMR-Bypass failing, so stating OMR-Bypass again, then V2Ray going down... and so on:

```
Fri Mar  4 03:09:54 2022 user.notice omr-bypass: OMR-ByPass is running
Fri Mar  4 03:09:55 2022 daemon.info v2ray[13036]: V2Ray 4.35.1 (V2Fly, a community-driven edition of V2Ray.) OpenWrt R1 (go1.15.2 linux/arm64)
Fri Mar  4 03:09:55 2022 daemon.info v2ray[13036]: A unified platform for anti-censorship.
Fri Mar  4 03:09:55 2022 daemon.info v2ray[13036]: 2022/03/04 03:09:55 [Info] github.com/v2fly/v2ray-core/v4/main/jsonem: Reading config: /var/etc/v2ray/v2ray.main.json
Fri Mar  4 03:09:55 2022 user.notice v2ray: Rules DOWN
Fri Mar  4 03:09:55 2022 user.notice v2ray: Rules UP
Fri Mar  4 03:09:56 2022 user.notice v2ray: Reload omr-bypass rules
Fri Mar  4 03:09:56 2022 user.notice omr-bypass: Starting OMR-ByPass...
Fri Mar  4 03:10:00 2022 daemon.info omr-tracker-v2ray: V2Ray is up (can contact via http 77.88.55.77)
Fri Mar  4 03:10:57 2022 daemon.info dnsmasq-dhcp[9116]: DHCPDISCOVER(eth0) 7c:a6:b0:0e:50:a8
Fri Mar  4 03:10:57 2022 daemon.info dnsmasq-dhcp[9116]: DHCPOFFER(eth0) 192.168.1.146 7c:a6:b0:0e:50:a8
Fri Mar  4 03:10:57 2022 daemon.info dnsmasq-dhcp[9116]: DHCPREQUEST(eth0) 192.168.1.146 7c:a6:b0:0e:50:a8
Fri Mar  4 03:10:57 2022 daemon.info dnsmasq-dhcp[9116]: DHCPACK(eth0) 192.168.1.146 7c:a6:b0:0e:50:a8
Fri Mar  4 03:11:11 2022 daemon.info dnsmasq-dhcp[9116]: DHCPREQUEST(eth0) 192.168.1.190 14:eb:b6:58:da:7c
Fri Mar  4 03:11:11 2022 daemon.info dnsmasq-dhcp[9116]: DHCPACK(eth0) 192.168.1.190 14:eb:b6:58:da:7c Archer_AX73
Fri Mar  4 03:11:16 2022 user.notice omr-bypass: Reload dnsmasq...
Fri Mar  4 03:11:16 2022 daemon.info dnsmasq[9116]: read /etc/hosts - 4 addresses
Fri Mar  4 03:11:16 2022 daemon.info dnsmasq[9116]: read /tmp/hosts/dhcp.cfg01411c - 25 addresses
Fri Mar  4 03:11:16 2022 daemon.info dnsmasq-dhcp[9116]: read /etc/ethers - 0 addresses
Fri Mar  4 03:11:16 2022 user.notice omr-bypass: OMR-ByPass is running
Fri Mar  4 03:11:16 2022 user.notice v2ray: Reload omr-bypass rules
Fri Mar  4 03:11:16 2022 user.notice omr-bypass: Starting OMR-ByPass...
Fri Mar  4 03:11:17 2022 user.notice post-tracking-post-tracking: Can't find omr-bypass rules, restart omr-bypass...

.
.
.

Fri Mar  4 03:12:39 2022 user.notice omr-bypass: Starting OMR-ByPass...
Fri Mar  4 03:12:39 2022 daemon.err omr-tracker[20333]: iptables-restore: line 2 failed
Fri Mar  4 03:12:40 2022 daemon.err omr-tracker[20333]: iptables-restore: line 2 failed
Fri Mar  4 03:12:40 2022 user.notice post-tracking-post-tracking: Can't find V2Ray, restart it...

.
.
.

Fri Mar  4 03:12:59 2022 user.notice omr-bypass: OMR-ByPass is running
Fri Mar  4 03:13:00 2022 daemon.info v2ray[4801]: V2Ray 4.35.1 (V2Fly, a community-driven edition of V2Ray.) OpenWrt R1 (go1.15.2 linux/arm64)
Fri Mar  4 03:13:00 2022 daemon.info v2ray[4801]: A unified platform for anti-censorship.
Fri Mar  4 03:13:00 2022 daemon.info v2ray[4801]: 2022/03/04 03:13:00 [Info] github.com/v2fly/v2ray-core/v4/main/jsonem: Reading config: /var/etc/v2ray/v2ray.main.json
Fri Mar  4 03:13:00 2022 daemon.info v2ray: DNS disabled: main_dns
Fri Mar  4 03:13:00 2022 daemon.err omr-tracker[20335]: [info] DNS disabled: main_dns
Fri Mar  4 03:13:00 2022 daemon.info v2ray: Setting transparent proxy on port: 1897
Fri Mar  4 03:13:00 2022 daemon.err omr-tracker[20335]: [info] Setting transparent proxy on port: 1897
Fri Mar  4 03:13:00 2022 daemon.info v2ray: Transparent proxy mode: default
Fri Mar  4 03:13:00 2022 daemon.err omr-tracker[20335]: [info] Transparent proxy mode: default
Fri Mar  4 03:13:00 2022 user.notice v2ray: add rules
Fri Mar  4 03:13:00 2022 daemon.info dnsmasq-dhcp[3807]: DHCPREQUEST(eth0) 192.168.1.190 14:eb:b6:58:da:7c
Fri Mar  4 03:13:00 2022 daemon.info dnsmasq-dhcp[3807]: DHCPACK(eth0) 192.168.1.190 14:eb:b6:58:da:7c Archer_AX73
Fri Mar  4 03:13:01 2022 daemon.err omr-tracker[20335]: Flush terminated
Fri Mar  4 03:13:01 2022 daemon.err omr-tracker[20335]: ss-rules6: unknown option def
Fri Mar  4 03:13:01 2022 user.notice v2ray: Reload omr-bypass rules
Fri Mar  4 03:13:01 2022 user.notice omr-bypass: Starting OMR-ByPass...
Fri Mar  4 03:13:01 2022 daemon.info dnsmasq-dhcp[3807]: DHCPREQUEST(eth0) 192.168.1.190 14:eb:b6:58:da:7c
Fri Mar  4 03:13:01 2022 daemon.info dnsmasq-dhcp[3807]: DHCPACK(eth0) 192.168.1.190 14:eb:b6:58:da:7c Archer_AX73
Fri Mar  4 03:13:01 2022 daemon.info dnsmasq-dhcp[3807]: DHCPDISCOVER(eth0) 192.168.1.190 14:eb:b6:58:da:7c
Fri Mar  4 03:13:01 2022 daemon.info dnsmasq-dhcp[3807]: DHCPOFFER(eth0) 192.168.1.190 14:eb:b6:58:da:7c
Fri Mar  4 03:13:01 2022 daemon.info dnsmasq-dhcp[3807]: DHCPREQUEST(eth0) 192.168.1.190 14:eb:b6:58:da:7c
Fri Mar  4 03:13:01 2022 daemon.info dnsmasq-dhcp[3807]: DHCPACK(eth0) 192.168.1.190 14:eb:b6:58:da:7c Archer_AX73
Fri Mar  4 03:13:02 2022 daemon.err omr-tracker[20335]: iptables-restore: line 2 failed
Fri Mar  4 03:13:02 2022 daemon.err omr-tracker[20335]: iptables-restore: line 2 failed
Fri Mar  4 03:13:02 2022 daemon.err omr-tracker[20335]: iptables-restore: line 2 failed
Fri Mar  4 03:13:03 2022 daemon.err omr-tracker[20335]: iptables-restore: line 2 failed
Fri Mar  4 03:13:03 2022 daemon.err omr-tracker[20335]: iptables-restore: line 2 failed
Fri Mar  4 03:13:03 2022 daemon.err omr-tracker[20335]: iptables-restore: line 2 failed
Fri Mar  4 03:13:04 2022 daemon.err omr-tracker[20335]: iptables-restore: line 2 failed
Fri Mar  4 03:13:04 2022 daemon.err omr-tracker[20335]: iptables-restore: line 2 failed
Fri Mar  4 03:13:11 2022 user.notice post-tracking-post-tracking: Can't find V2Ray, restart it...
```

Not too sure what `iptables-restore: line 2 failed` is referring to either and also... Something that's repeating: when V2Ray as proxy: DHCPACK:

```
DHCPACK(eth0) 192.168.1.190 14:eb:b6:58:da:7c Archer_AX73
```

This is the router (Archer_AX73) in 'AP' mode, using just to supply wifi... Oddly though, I've assigned this AP a static IP of: 192.168.1.70... and I can access it on that IP, yet, OpenMPTCProuter is also giving it (DHCP) an IP address of 192.168.1.190... Not entirely sure why and I can't access it on that IP either... Don't know if it's at all related?

Kind regards,

Jamie
