### ISSUE TITLE
sinh viên

### ISSUE THREAD

**Issue by Dongca2201** [Ysurac/openmptcprouter#2283]
Tôi đang tìm hiểu về open MPTCProuter cho cân bằng tải và chưa tìm được 1 số tài liệu. Tôi muốn xin mọi người .
Ai có có thể gửi qua email: dongca293267@gmail.com
Tôi xin chân thành cảm ơn

**Comment by highfreq** [comment]
ggggggggggggghhhhhhhhhhhhhhbbbbbbbbbbbbbbbbbbbbbbbfffffffffffffffffffffffffffffffffffffccccccccccccccccccccccccccccxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeerrrrrrrrrrrrrrrrrrrrrrrrrrrrrrtttttttttttttttttttttttttttttttttttttttttt
