### ISSUE TITLE
Netgear Nighthawk X4S support displayed but no image found

### ISSUE THREAD

**Issue by alexandredubois** [Ysurac/openmptcprouter#2284]
Hello,

I saw in the [supported devices post](https://github.com/Ysurac/openmptcprouter/issues/1093) the Netgear Nighthawk X4S is listed, which is great because it seems to be pretty afordable (second hand device costs around 90euros only) but i can't find any matching image on [the dedicated page](https://www.openmptcprouter.com/download). 

Is it possible to have some help about this ? 

I saw the [create image section](https://github.com/Ysurac/openmptcprouter/wiki/Create-image-for-unsupported-platform) so i think with some hints i will be able to write a full tutorial for this model.

Regards,

Alexandre

**Comment by Ysurac** [comment]
It's supported in beta release (https://github.com/Ysurac/openmptcprouter/issues/2077), so this will be in next release.
