### ISSUE TITLE
With the right Hardware is 1G Fiber + 1.2G Cable bonding possible? 

### ISSUE THREAD

**Issue by mercuryyy** [Ysurac/openmptcprouter#2290]
Im looking into setting openmptcprouter up. 

Will it make sense to try and combin these 2 connection yes i know over kill.

I can get a VPS from google cloud with a 10G wan 
And then i'd need a 1U rack for the mptcp router with 4x 10G NIC or 4x 10G sfp+

But i mean will this even work? did anyone try and can post some results ?

Thank you.

**Comment by wlatic** [comment]
At that level you are probably best just using a normal router with policy based routing per protocol or internal IP address.

Failover will work ok, but there is a huge down side to having an external IP address being a VPS vs your normal residential IP.
