### ISSUE TITLE
Intel I225-V driver and MacVLAN

### ISSUE THREAD

**Issue by realspast** [Ysurac/openmptcprouter#2294]
Please add support for Intel I225-V (kmod-igc) 
and working MacVLAN on these NIC's.

**Comment by antonioscarpino** [comment]
I think it's a good thing since many board are based on this chip

**Comment by antonioscarpino** [comment]
I solved the problem by installing the kmod-igc module manually.

opkg update
opkg install kmod-igc

of course I was connected through a USB Nic recognized by Openmtcp to the Internet

**Comment by realspast** [comment]
I did it exactly like that but MacVLAN doesnt't work for me. Have you tried
it?

Antonio Scarpino ***@***.***> schrieb am Di., 24. Mai 2022,
18:17:

**Comment by ioogithub** [comment]
@realspast, @antonioscarpino : Did you guys also have to use the 5.15 kernel or does the regular image with with this driver?
