### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by darthclide** [Ysurac/openmptcprouter#2297]
## Expected Behavior
System log has normal reports on device activity.

## Current Behavior
System log is maxed out with only the following message:
daemon.err omr-tracker[29503]: mktemp: (null): No space left on device

## Possible Solution
It is somehow losing space somewhere, even though the software page shows 52% free space.

## Context (Environment)
My bandwidth page not longer functions, and I also can't troubleshoot other problems since the system log is filled with this message.

## Specifications

  - OpenMPTCProuter version: 0.59beta3-5.4
  - OpenMPTCProuter VPS version: 0.1027-test 5.4.100-mptcp
  - OpenMPTCProuter VPS provider: Vultr
  - OpenMPTCProuter platform: RPI4
  - Country: USA

**Comment by darthclide** [comment]
This is the result of the df command:
![image](https://user-images.githubusercontent.com/46735828/158881298-d88318f9-7fce-4fe1-b9b1-0a79aa295167.png)

**Comment by Ysurac** [comment]
It's fixed in snapshot, I will release a new beta.

**Comment by darthclide** [comment]
So that means I should wait until beta 4 for this to be fixed? Should I also update my VPS script again or has the "test" version not changed?

**Comment by Ysurac** [comment]
Yes, wait or use snapshot image.
VPS script was not updated for now.

**Comment by darthclide** [comment]
Well outside of me troubleshooting that iPad problem, the internet is working fine. So I think I can be patient for the next beta.
