### ISSUE TITLE
support some wifi6 (802.11ax) router

### ISSUE THREAD

**Issue by akofer** [Ysurac/openmptcprouter#2298]
Wifi6 (also called 802.11ax) is already supported by all mainstream router vendors and almost all new routers choose wifi6 as their unique selling proposition. It's better than old wifi5 routers.

Upstream OpenWRT already supported several wifi6 routers such as linksys E8450 and so on. Details are listed here https://openwrt.org/toh/views/toh_available_16128_ax-wifi .

So. I suggest adding an official binary image for a certain wifi6 router.

**Comment by Ysurac** [comment]
I only officially support router that I own (I need to make tests to be sure it's working and often make code changes).
You can compile it yourself using https://github.com/Ysurac/openmptcprouter/wiki/Create-image-for-unsupported-platform
