### ISSUE TITLE
1Gbps or More Aggregation

### ISSUE THREAD

**Issue by ccmks** [Ysurac/openmptcprouter#2299]
Has anyone ever achieved 1Gbps or more (assuming using 10Gbps VPS) aggregated speed on OMR? If so, I am curious about the minimum hardware requirement such as:

CPU
RAM
NIC

Thank you

**Comment by Adorfer** [comment]
1GBit is easy, 2GBit/s feasable, 10GBit/s: no idea. 

Take a look at https://github.com/Ysurac/openmptcprouter/issues/1108

**Comment by ccmks** [comment]
For 10Gbps, I am assuming only 5Gbps is being used effectively, as 10Gbps speed usually half-duplex connection...

**Comment by QatarMo** [comment]
![10g](https://user-images.githubusercontent.com/33218251/161755381-6451caa0-19c1-44dd-8571-75912a60c2c4.PNG)

10g vps

router
10900K
16gb
Intel X520-DA2
2x 1G down 512 up Wan's

**Comment by ccmks** [comment]
Is it 3X 1Gbps internet? Why is it not even close to 2.5Gbps?

How is the CPU load during the test?

**Comment by Llorx** [comment]
> > Is it 3X 1Gbps internet? Why is it not even close to 2.5Gbps?
> > How is the CPU load during the test?
> 
> yes they are 1Gbps each,,load is like 30% on max on both router and vps i do get over 2G sometimes but i guess its the latency,its rock stable been running this for over a year now ![load](https://user-images.githubusercontent.com/33218251/162911175-674d9fa0-07a7-4ce7-9863-3d0654b0c3fa.PNG)

Just to clarify. Individual tests give 100 ping and 1gb but a mptcp test give also 100 ping and only 2gb?

I'm asking because I thought that the loss in bandwidth was way less. Losing 33% of the bandwidth is a real bummer. Have you tried other configurations just in case?

**Comment by ccmks** [comment]
I haven't reach 1Gbps yet on aggregation, but so far only 180 Mbps and 300
Mbps I have seen being aggregated.

You also might need to check the connection between your ISP to your VPS to
see if you are getting full 1 Gbps.

Until now, I still don't know how to test for each individual ISP

**Comment by Ysurac** [comment]
ping is a problem to get a good speed. If you have a good VPS, connections with low latency and a router with a good CPU you can reach 1Gbps without problem.
If you mean testing speed between VPS and router, there is 2 way : ```omr-test-speed-server``` or ```omr-iperf``` that use iperf server installed on VPS side.

**Comment by Llorx** [comment]
@Ysurac so if you have a good CPU, ping variations shouldn't affect that much?

The problem I'm facing is saturated 4g. We stream sports events and some times there are more people than the 4g near stations can handle, so the ping and bandwidth fluctuates a lot. I want to use openmptcp with 4g, 5g and Starlink so when someone of them catches up, it works, but if I have 10mbps upload from Starlink and a fluctuating 4g, I don't want it to drop to 6mbps.

**Comment by Ysurac** [comment]
In all case ping variation affect speed.
SQM with SQM autorate should help for connection that fluctuates.

**Comment by Llorx** [comment]
Hm hmmmm. Ok, perfect! When I receive my router I'm going to do all the testing. Thank you!

**Comment by QatarMo** [comment]
> > > Is it 3X 1Gbps internet? Why is it not even close to 2.5Gbps?
> > > How is the CPU load during the test?
> > 
> > 
> > yes they are 1Gbps each,,load is like 30% on max on both router and vps i do get over 2G sometimes but i guess its the latency,its rock stable been running this for over a year now ![load](https://user-images.githubusercontent.com/33218251/162911175-674d9fa0-07a7-4ce7-9863-3d0654b0c3fa.PNG)
> 
> Just to clarify. Individual tests give 100 ping and 1gb but a mptcp test give also 100 ping and only 2gb?
> 
> I'm asking because I thought that the loss in bandwidth was way less. Losing 33% of the bandwidth is a real bummer. Have you tried other configurations just in case?

In my case Individual tests in a local test server have a ping of 2ms is 1gb/512 down/up speed and to the vps 100 is I have tested a lot and I think my bandwidth lose is due to ping/distance, no company lese vps with 10g nic locally so I had to look for the best ping vps

**Comment by Llorx** [comment]
Ohhh ok ok, I understand it now. Perfect, thank you for your reply @QatarMo !
