### ISSUE TITLE
Vue de synthèse des graphes de traffic

### ISSUE THREAD

**Issue by xslite** [Ysurac/openmptcprouter#23]
Hello,

une "live view" aggrégée des traffics provenant des différents WAN serait bien pratique !

Cela permettrait en un coup d'oeil de voir si tout fonctionne bien, et comment est réparti le flux entre les box/clés 4G.

![screenshot from 2018-03-26 16-20-35](https://user-images.githubusercontent.com/37269706/37912313-91e9109c-3112-11e8-86dc-52b3338fb79e.png)
![screenshot from 2018-03-26 16-20-18](https://user-images.githubusercontent.com/37269706/37912314-921b4c9c-3112-11e8-8599-520db5fe9fb5.png)
![screenshot from 2018-03-26 16-19-53](https://user-images.githubusercontent.com/37269706/37912315-924cd7ee-3112-11e8-803b-5984f1485c16.png)

**Comment by Ysurac** [comment]
C'est prévu.

**Comment by Ysurac** [comment]
Un graph est ajouté dans le menu **Réseau->MPTCP->Bandwidth**.
