### ISSUE TITLE
Can't seem to get Access Point working on RPI4B

### ISSUE THREAD

**Issue by beezlebuble** [Ysurac/openmptcprouter#2301]
Hi there,

Bizarre thing, I can only seem to get 'client mode' working on my RPI OMR. Works just like standard openwrt: scan, configure, deploy, 
However, when I try to create an access point it breaks the client (if i've set it up prior-to) and just does nothing.

![image](https://user-images.githubusercontent.com/101998650/159188927-f24118d0-fbae-4f3f-a1db-01c5cad6bae3.png)

As you can see in the pic, it says 'disabled' even though when you click into 'edit' it says enabled. Doesn't show up as an available network on any devices either.

![image](https://user-images.githubusercontent.com/101998650/159188993-3d25a77f-ea2f-4139-a036-552101318f63.png)
 
Saw that some other people have noted that rpi broadcoms aren't really opensource, and openwrt doesn't fully support, hope that's not the reason..

RPI 4B rev1.1
openmptcprouter v0.58.5 r0+16336-b36068d35d

**Comment by Ysurac** [comment]
https://github.com/Ysurac/openmptcprouter/wiki/Configure-Wifi
