### ISSUE TITLE
Ubiquiti ER-X Performance?

### ISSUE THREAD

**Issue by ccmks** [Ysurac/openmptcprouter#2304]
Hello,

I am planning to buy ER-X router for OMR router. How is the performance? What is the maximum aggregated speed it can handle?

Thank you

**Comment by Ysurac** [comment]
It's currently not stable: https://github.com/Ysurac/openmptcprouter/issues/1779
Maybe this will be better in next release...

**Comment by ccmks** [comment]
OK, I thought there was improvement since last issue. Thanks for the answer
