### ISSUE TITLE
WAN Priority over other

### ISSUE THREAD

**Issue by ccmks** [Ysurac/openmptcprouter#2305]
Hello, I have scenario of 4 WAN where I would like the OMR to prioritize WAN 1 when do aggregation over the other. The reason that because WAN 1 has the largest data cap compare to other WAN.

In current situation, when aggregated, it is tend to use WAN 2 connection much more than other WAN. Is there anyway to configure some weight or manipulation that OMR will always using WAN1 when do aggregation?

I am currently running on v0.58.5

Thank you

**Comment by ccmks** [comment]
![image](https://user-images.githubusercontent.com/49300986/159734850-e69cede5-34de-4eac-8a41-7b91f65485c8.png)

Please see this picture.

Thank you

**Comment by Ysurac** [comment]
WAN are used based on latency, WAN with lowest latency is used first.
There is an option in Network->Interface to add some latency on a WAN, but it's more for test than daily use.

**Comment by ccmks** [comment]
Upon checking, if lowest latency is being preferred, WAN3 should be the one being used most.

![image](https://user-images.githubusercontent.com/49300986/159736740-cfe7f8ba-7e37-4e4d-a399-789bb6fdeec0.png)

But in this case, it is using WAN2

**Comment by ccmks** [comment]
I tried to increase WAN2 additional latency to 30, so should it be showing 60ms on OMR status page?

**Comment by Ysurac** [comment]
1 ms is not a big difference, this can change all the times.
For wan3 and wan4, why does they have same ip and wan address ? provider do some CGNAT ?

Yes this should increase latency in status page (but I've not tested this since a long time...)

**Comment by ccmks** [comment]
For WAN3 and WAN4 is 2 separate line of ISP that happened to share public IP.

I have increased to 30ms on WAN2 but on status page it doesn't increase the value to 60ms, instead it is still at 30ms

**Comment by ccmks** [comment]
Besides manipulating the latency, is there any way to configure priority or weight on interface?

**Comment by Ysurac** [comment]
no, for now only latency is used for priority.

**Comment by ccmks** [comment]
Is there anyway to add request feature for this? This will be very helpful since we can decide which WAN we can manipulate, especially if the WAN has lower latency, but cost more to run due to metered data cap, and prefer other WAN that has higher latency but has more data cap.

**Comment by ccmks** [comment]
I do noticed that if I add latency, the latency will be increased once I reboot OMR. Is there anyway to take effect without rebooting OMR? Also, I tried to restart the interface still not increasing latency.

Thank you

**Comment by Ysurac** [comment]
I don't remember if I fixed this in develop branch, I will check.
Support for setting priority will not be in next release but it's on todo list, I think on 5.15 based release.

**Comment by ccmks** [comment]
Appreciate your support!
