### ISSUE TITLE
vps usage

### ISSUE THREAD

**Issue by pat1108** [Ysurac/openmptcprouter#2310]
Hello,
I have a quick question, is there a way to use vps for other functions?
Like ftp server or other? For my part 40 GB which are useless. "OVH"

Good day

**Comment by pat1108** [comment]
thank you
and for use as a web server or mail server?
Cordially

**Comment by Ysurac** [comment]
It's the same.

**Comment by pat1108** [comment]
thank you

**Comment by pat1108** [comment]
could you show me the command line to add to make an ftp server on port 2121 for example
thank you

**Comment by Ysurac** [comment]
If you look in the file you will see an example with port 65222, copy this line and change the port. You will need to reload shorewall after that (systemctl reload shorewall)
