### ISSUE TITLE
Can't contact Server Admin Script(No result)

### ISSUE THREAD

**Issue by timbrookers** [Ysurac/openmptcprouter#2316]
I had setup everything expect the yellow in the server status.

What shall i check and what could be the reason of i
![Screen Shot 2022-04-08 at 18 29 01](https://user-images.githubusercontent.com/13175563/162419144-3165601a-169a-410a-b2c7-0f0ad8ab24f7.png)
t

**Comment by Ysurac** [comment]
Please use the template.
