### ISSUE TITLE
Can't contact server admin script (no result)

### ISSUE THREAD

**Issue by timbrookers** [Ysurac/openmptcprouter#2317]
## Expected Behavior

I had setup the openmptcprouter successfully.

## Current Behavior

But the server status said "Can't contact server admin script (no result)".
All others are green.

## Specifications

  - OpenMPTCProuter version: 0.58.5
  - OpenMPTCProuter VPS version: 0.1026 5.4.100-mptcp
  - OpenMPTCProuter VPS provider: ionos.com
  - OpenMPTCProuter platform: x86_64 

![Screen Shot 2022-04-08 at 18 29 01](https://user-images.githubusercontent.com/13175563/162423335-4b4d2b09-c8fd-42a8-a326-1d80c3a54302.png)

**Comment by Ysurac** [comment]
I see that you have a high latency, this may be the reason why you get this message (it timeout for status page).
Else everything is working ? Do you have "openmptcprouter-vps" errors in Status->System log ?

**Comment by timbrookers** [comment]
Thank you for reply,
yes, it is working
the error is: 
daemon.err /usr/bin/ss-redir[4507]: remote recv: Connection reset by peer

**Comment by Ysurac** [comment]
This error is not related.
In system->OpenMPTCProuter, "Advanced settings" tab you can find "VPS checks timeout", you can try to increase it, this should fix status page display.

**Comment by timbrookers** [comment]
ok, i had change it to 20 from 1
now the status is saying localhost

**Comment by timbrookers** [comment]
![Screen Shot 2022-04-08 at 20 08 25](https://user-images.githubusercontent.com/13175563/162432578-175b8156-cbbc-4786-86b0-5e45d66cd7ee.png)

**Comment by Ysurac** [comment]
Ok, it's the hostname of your VPS. Stange hostname, but why not ;)

**Comment by timbrookers** [comment]
my download speed is about 102Mbps, but upload is 2.1Mbps
the both isp have download 80Mbps and upload 16Mbps
why it is so?

**Comment by Ysurac** [comment]
You can try to change TCP Congestion Control in Network->MPTCP
It's quite difficult to aggregate correctly connections with high latencies.

**Comment by timbrookers** [comment]
now i get this error: 
daemon.err /usr/bin/ss-local[4975]: getpeername: Socket not connected

**Comment by timbrookers** [comment]
apologies  for disturbing, but
i have new error, 
Can't get Public IP address from Shadowsocks

**Comment by timbrookers** [comment]
after restarting the server no issue

thank you
