### ISSUE TITLE
Not Found -  The requested URL / was not found on this server.

### ISSUE THREAD

**Issue by Yersi88** [Ysurac/openmptcprouter#2318]
## Expected Behavior

Page loads & CL login works 

## Current Behavior

Can't log in to webpage or to cl.

![image](https://user-images.githubusercontent.com/77145281/162612615-5e7f51ca-a573-47a2-9e2d-7d5de5750048.png)
![image](https://user-images.githubusercontent.com/77145281/162612644-b83814c9-7166-440d-8b55-4512be1c190e.png)

## Steps to Reproduce the Problem

  1. Wait for router to get randomly into this thate
  2. Try to visit the pager or log in through cl
  3. cry?

## Context (Environment)

Router will run just fine for a month or so and then randomly, I'm not able to log in both to website or to cl.

## Specifications

  - OpenMPTCProuter version: [v0.58.5 r0+16336-b36068d35d] 
  - OpenMPTCProuter VPS version: N/A
  - OpenMPTCProuter VPS provider: N/A
  - OpenMPTCProuter platform: x86_64 
  - Country: N/A

**Comment by Ysurac** [comment]
You have a FS problem. So you have power problem or you have a bad disk.
