### ISSUE TITLE
External ip login attempts.

### ISSUE THREAD

**Issue by kverkind** [Ysurac/openmptcprouter#2320]
## Expected Behavior
External login attemts blocked

## Current Behavior
In the system lof file we see (small extract)
Mon Apr 11 12:03:41 2022 authpriv.info dropbear[25170]: Child connection from 39.97.72.61:44568
Mon Apr 11 12:03:42 2022 authpriv.warn dropbear[25170]: Bad password attempt for 'root' from 39.97.72.61:44568
Mon Apr 11 12:03:43 2022 authpriv.info dropbear[25908]: Child connection from 39.97.72.61:45204
Mon Apr 11 12:03:43 2022 authpriv.info dropbear[25170]: Exit before auth from <39.97.72.61:44568>: (user 'root', 1 fails): Exited normally
Mon Apr 11 12:03:44 2022 authpriv.warn dropbear[25908]: Bad password attempt for 'root' from 39.97.72.61:45204
Mon Apr 11 12:03:45 2022 authpriv.info dropbear[25908]: Exit before auth from <39.97.72.61:45204>: (user 'root', 1 fails): Exited normally
Mon Apr 11 12:03:45 2022 authpriv.info dropbear[25975]: Child connection from 39.97.72.61:45842
Mon Apr 11 12:03:46 2022 authpriv.warn dropbear[25975]: Bad password attempt for 'root' from 39.97.72.61:45842
Mon Apr 11 12:03:47 2022 authpriv.info dropbear[25975]: Exit before auth from <39.97.72.61:45842>: (user 'root', 1 fails): Exited normally
Mon Apr 11 12:03:47 2022 authpriv.info dropbear[26728]: Child connection from 39.97.72.61:46604
Mon Apr 11 12:03:48 2022 authpriv.warn dropbear[26728]: Bad password attempt for 'root' from 39.97.72.61:46604
Mon Apr 11 12:03:49 2022 authpriv.info dropbear[27464]: Child connection from 39.97.72.61:47298
Mon Apr 11 12:03:49 2022 authpriv.info dropbear[26728]: Exit before auth from <39.97.72.61:46604>: (user 'root', 1 fails): Exited normally

## Specifications

  - OpenMPTCProuter version: openmptcprouter v0.58.5 r0+16336-b36068d35d
  - OpenMPTCProuter VPS version: 5.4.100-mptcp
  - OpenMPTCProuter VPS provider: Hetzner
  - OpenMPTCProuter platform: RPI4

SSH port has been changed. 
Using one port forwarding rule on port 80 to allow remote access of router.
Adding ip addresses to reject in firewall (works) but due to the amount of external attempts not maintainable
Is there a better solution ?

**Comment by kverkind** [comment]
Still open for suggestions. Best practices on firewall rules for OMR. Is there any documentation I can use?

**Comment by Ysurac** [comment]
Best pratices is to not forward port 80 to router, else you can get these attempts.
By default all remote access are blocked on router and VPS (only port > 65000 are opened for VPN, proxy, API,...).
If you need to access router from outside, you can do a SSH tunnel.

**Comment by kverkind** [comment]
So this means that section Redirect port via VPN on OpenMPTCProuter on https://github.com/Ysurac/openmptcprouter/wiki/Port-forwarding is not advisable?

**Comment by Ysurac** [comment]
There is no problem with this, but if you forward a port then it's open on Internet. It's always dangerous.
And opening any admin interface on internet is not a great idea, you can at least restrict access to some fixed public IP if you really need this.
