### ISSUE TITLE
Integrate a running-config and a startup-config

### ISSUE THREAD

**Issue by Ajowan84** [Ysurac/openmptcprouter#2323]
**Describe the solution you'd like**
Everything is in the title

**Comment by Ysurac** [comment]
Please use template.
This would need far more details...

**Comment by Ajowan84** [comment]
**Is your feature request related to a problem? Please describe.**
If I make a mistake when configuring the router, I can lose access to it

**Describe the solution you'd like**
During manipulation on the router, the configuration is written in the file running-config.
If an error is made and access is lost, simply restart the router physically to recover the configuration in startup-config

This solution exists on a multitude of hardware.
Switch, firewall, router...

Thank
