### ISSUE TITLE
How do you open port ranges in Google Cloud Platform?

### ISSUE THREAD

**Issue by dooley1981** [Ysurac/openmptcprouter#2329]
[Google Cloud Platform](https://cloud.google.com/) port range 0-65535 in UDP, TCP and ICMP must be opened

I guess it must be open to work with Openmptcprouter?

**Comment by Ysurac** [comment]
Port 65000-65535 are used by OpenMPTCProuter internal communications, others ports can be used if you redirect ports.
VPS part have a firewall installed and configured by default that block all port from 0 to 65000 (Only ICMP is authorized)

**Comment by dooley1981** [comment]
Okay so I shouldn't have to do anything for it to work with this software correct?

**Comment by Ysurac** [comment]
You only have to open ports, as they are closed by default on GCP

**Comment by dooley1981** [comment]
thanks

**Comment by Ysurac** [comment]
Try to connect to https;//<vpsip>:65500/ and check via ```ps aux | grep omr``` if omr-admin is running.
