### ISSUE TITLE
Connection is not stable and has high pings

### ISSUE THREAD

**Issue by mstrolo** [Ysurac/openmptcprouter#2330]
## Expected Behavior

Bonding is connected to the server and 3 wans.

## Current Behavior

the bond is not stable high pings and request time outs.

## Specifications

  - OpenMPTCProuter version: 
  - [Powered by openmptcprouter v0.58.5 r0+16336-b36068d35d](https://github.com/ysurac/openmptcprouter)
  - OpenMPTCProuter VPS version: 
  - 
![image](https://user-images.githubusercontent.com/7146444/163726614-be5427da-1d41-45bb-9774-881f4f07abff.png)

  - OpenMPTCProuter VPS provider:

  - OpenMPTCProuter platform: 
x86_64

![image](https://user-images.githubusercontent.com/7146444/163726572-bca08a51-f799-4f7c-845a-bcb75ac3fd3f.png)

**Comment by mstrolo** [comment]
i see this in the logs:

![image](https://user-images.githubusercontent.com/7146444/163726830-914d81f0-9a7f-4502-a410-0be9a295dabd.png)

![image](https://user-images.githubusercontent.com/7146444/163726866-875eb82e-c48f-465b-989f-d4aa456d58be.png)

**Comment by mstrolo** [comment]
this what happens when i run speed test:

![image](https://user-images.githubusercontent.com/7146444/163726986-8dc331c3-2a6c-406c-ade3-8b94859b6b4c.png)

**Comment by Ysurac** [comment]
Check in log the error, why the VPN is down, should be something like ping timeout on some IP.
Set also the more stable connection as master.

**Comment by mstrolo** [comment]
the VDSL is the master
