### ISSUE TITLE
Debian 10

### ISSUE THREAD

**Issue by dooley1981** [Ysurac/openmptcprouter#2332]
My server has Debian 9.3, Can I install the Debian 10 script?

**Comment by Ysurac** [comment]
The script update Debian 9 to Debian 10 before installing needed packages

**Comment by dooley1981** [comment]
by using this script?     wget -O - https://www.openmptcprouter.com/server/debian9-x86_64.sh | sh

**Comment by Ysurac** [comment]
Yes, it's in fact same script for all supported Linux distribution.

**Comment by dooley1981** [comment]
I am getting the certificate error so I ran the apt-get update && apt-get upgrade.  It didn't finish and it gave me this message.

cron (3.0pl1-128+deb9u2) stretch-security; urgency=medium

  * As a reasonable protective measure, crontabs are now limited to 10000 lines
    in length per crontab.
    The maintainers find it very unlikely that longer crontabs exist; however,
    if you do have a use case, please file a bug report with a brief rationale,
    and we will consider raising this limit.

**Comment by dooley1981** [comment]
Check user...
Check Linux version...
Check architecture...
Check virtualized environment
Check about broken packages...
Check if OpenMPTCProuter VPS is already installed...
Update mode
Remove lock and update packages list...
E: Command line option --allow-releaseinfo-change is not understood in combination with the other options



Now it thinks its already installed. anyway to remove it to start over?

**Comment by dooley1981** [comment]
fix it, got a better VPS
