### ISSUE TITLE
How to update for the compiled? and where is zimage file?

### ISSUE THREAD

**Issue by atyouspace** [Ysurac/openmptcprouter#2338]
I am compiling an new image for imx6 platform.
I have two questions:
**(1)
How can I follow the update (such as new beta version or release stable version) if I've already finished compiling the image?
When a new version is release, should I build it again like this?**

`git clone https://github.com/Ysurac/openmptcprouter.git`
`cd openmptcprouter`
`git checkout master`
`OMR_TARGET="myplatform" OMR_FEED_SRC="master" ./build.sh`
`make menuconfig `
`make `

**(2)**
**where is zimage?**
For imx6 platform, three files are required to program the development board, `uboot/zimage/rootfs`.
After I make, files are located in the directory `source/bin/targets/imx6/generic` is
|-- config.buildinfo
|-- feeds.buildinfo
|-- openmptcprouter-v0.59beta5-master-0a711336-r0+16520-864bba55d8-imx6-default.manifest
|-- openmptcprouter-v0.59beta5-master-0a711336-r0+16520-864bba55d8-imx6-default-rootfs.tar.gz
|-- packages
|-- sha256sums
|-- u-boot-apalis_imx6
|-- u-boot-mx6cuboxi
|-- u-boot-wandboard

## Specifications

  - OpenMPTCProuter version: v0.59beta5
  - OpenMPTCProuter platform: imx6

**Comment by Ysurac** [comment]
You may need to select image format via "make menuconfig".
I can't really help on unsupported platform ;)
