### ISSUE TITLE
Fix Netflix over OMR-Bypass

### ISSUE THREAD

**Issue by Ysurac** [Ysurac/openmptcprouter#234]
I can test for one month and try to fix it.
Answer to ping without problem, https not working.

**Comment by Ysurac** [comment]
Bug found ! It's a problem in iptables rules. Some rules seems to be added sometimes that make omr-bypass fail. Need to find what and when and will be fixed fast. A reboot fix problem for a little time...

**Comment by Ysurac** [comment]
Maybe not in iptables. Work when glorytun is stopped or when default route is not the vpn.
So this seems more like a route problem.

**Comment by Ysurac** [comment]
Working with a fresh configuration but some bugs found that can cause problems in some cases.

**Comment by Ysurac** [comment]
Fixed in latest release.

**Comment by cron410** [comment]
I'm able to use netflix without any custom bypass rules added. Only what you provide by default.
