### ISSUE TITLE
Additional help with OMR and pfSense

### ISSUE THREAD

**Issue by davidvermillion** [Ysurac/openmptcprouter#2343]
I'm trying to make pfSense work in front of OMR. I found this in the documentation:

```
On pfSense, add a WAN interface with OMR as the default gateway.
Disable Outbound NAT on pfSense.
On OMR, add static route(s) to your LAN network(s).
If you need port forwarding, redirect the needed ports to the target LAN hosts on OMR, then add a Pass WAN firewall rule on pfSense to allow inbound traffic to the target host and port.
```

Is there anyone who can give more information on how to do this?

- I've configured the LAN and WAN with the upstream gateway pointing to OMR (and internet works, its just double NATed) 
- As soon as I disable outbound NAT on pfSense, everything quits working, and I can't access LUCI on OMR
- I'm not sure what the static route on OMR is supposed to look like

<img width="1166" alt="Screen Shot 2022-05-02 at 8 49 38 PM" src="https://user-images.githubusercontent.com/22948770/166393888-9d9da29d-86c4-4991-860d-4f4ce4b9f7f4.png">

<img width="1166" alt="Screen Shot 2022-05-02 at 8 50 23 PM" src="https://user-images.githubusercontent.com/22948770/166393889-14d0103b-ef8d-475b-93f2-062c29eefbbc.png">

**Comment by davidvermillion** [comment]
@0xgrm It looks like you were the person that originally came up with this method. If you're still using this config, I'd appreciate any hints.

**Comment by 0xgrm** [comment]
I am not using OMR anymore, since I now have a 10 Gbps fiber connection. 😊

You must create a static route in OMR to your LAN network through your pfSense gateway.

If you don't do that OMR has no idea where to return the packets coming from your LAN network without NAT.
