### ISSUE TITLE
ddns client on WAN1 always get VPS public IP

### ISSUE THREAD

**Issue by hrmtc** [Ysurac/openmptcprouter#2347]
Hi. 

I'm trying to use ddns client to follow up my wan1's public IP.
Even when I have specified the right interface, I always get the VPS's public IP.

Also the same happens if I use curl command specifing the WAN1's interface:
```
/ # curl --interface 192.168.100.101 ifconfig.host
1.23.199.233 <--- VPS public IP
```
If I turn off the VPS, I get the right IP of WAN1 interface.

**How can I get the WAN1's public IP when the VPS is up?
Can I retrieve this info using other method?**

Thanks in advance.

```
root@OMR:~# cat /etc/config/ddns

config service 'ipv4ddns'
	option enabled '1'
	option lookup_host 'somehost.nsupdate.info'
	option use_ipv6 '0'
	option service_name 'nsupdate.info'
	option domain 'somehost.nsupdate.info'
	option username 'somehost.nsupdate.info'
	option password 'Password'
	option dns_server '8.8.8.8'
	option check_interval '5'
	option check_unit 'minutes'
	option force_unit 'minutes'
	option retry_unit 'seconds'
	option use_syslog '1'
	option ip_source 'interface'
	option ip_interface 'eth0.100'
	option interface 'eth0.100'
```

**Comment by Ysurac** [comment]
To get a wan ip there is the script ```omr-ip-intf```, for example ```omr-ip-intf wan1``` to get wan1 public ip.
