### ISSUE TITLE
Minimum setup to connect devices on two LAN

### ISSUE THREAD

**Issue by Div99** [Ysurac/openmptcprouter#235]
We have a basic setup, where we have two devices, both connected through 2 LAN networks on 2 different routers. There is no outside internet connection. (IPs are manually assigned, no DHCP)
We want the network packets to be sent over UDP.

What is the minimum setup required, to make the devices communicate using both links (Essentially achieve multipath routing)?

**Comment by Ysurac** [comment]
If you want UDP, you have to use Glorytun UDP or MLVPN. It's not the best way to aggregate links.

And if you have no outside internet connection OpenMPTCProuter and VPS part would need some configuration and I'm not sure it's really the best idea.

If you really really want to use UDP you can try to configure Glorytun UDP or MLVPN on the devices but it's really out of the scope of OpenMPTCProuter.
