### ISSUE TITLE
What version is MPTCP supported?

### ISSUE THREAD

**Issue by atyouspace** [Ysurac/openmptcprouter#2350]
Hi @Ysurac 

From [MPTCP](https://www.multipath-tcp.org), I found there are two different version V0 and V1.
But I'm no idea about the MPTCP version used in openmptcprouter. Where can I find the list?

Best regards

**Comment by Ysurac** [comment]
OpenMPTCProuter with 5.4 kernel use MPTCP v0, OpenMPTCProuter with 5.15 kernel use MPTCP v1

**Comment by Ysurac** [comment]
For OpenMPTCProuter yes as I use 5.15 kernel for MPTCP v1, so VPS need to be updated.
