### ISSUE TITLE
Running openmptcprouter as a docker image

### ISSUE THREAD

**Issue by MinhHieuDL** [Ysurac/openmptcprouter#2351]
## Current Behavior
I run the openmptcprouter as docker image, follow these steps below:
- Bring up a AWS lightsail with Debian 10 OS as a host machine
- Install the mptcp kernel for the host. Follow instruction from: http://multipath-tcp.org/pmwiki.php/Users/AptRepository
- Install docker on the host machine
- Follow the instruction from:  https://openwrt.org/docs/guide-user/virtualization/docker_openwrt_image. I imported the rootfs download from: https://download.openmptcprouter.com/refs/tags/v0.58rc5/5.4/x86/targets/x86/generic/
- Currently, i can start the image and run some basic commands like: cat /etc/banner, ifconfig, opkg update,...
- But, i observed a problem when try to restart  dropbear service (with my purpose that able to ssh to the container) that the ubus seem not work. I got the log error that: "Failed to connect to ubus" while run: "/etc/init.d/dropbear restart" 
- I notice that the error not happen when run with the openwrt image
- Do you have any suggestion for this issue. Thanks in advance!

## Specifications
  - Host machine: AWS lightsail: OS Debian 10 - kernel: 4.19.234.mptcp
  - OpenMPTCProuter version: v0.58rc5
  - OpenMPTCProuter platform: x86

**Comment by Ysurac** [comment]
Why do you use an old unstable release v0.58rc5 ?
The host kernel is not supported. OpenMPTCProuter need a 5.4 mptcp patched kernel (I also add some patches for tcp congestion control).
For your error check logs via logread.
