### ISSUE TITLE
Upgrading Server to beta

### ISSUE THREAD

**Issue by myshophosting** [Ysurac/openmptcprouter#2352]
Hi

I was able to successfully update my router (x86) Via System -> Sysupgrade - this went smoothly

however the VPS I'm not sure how to upgrade. Does it require an update or just the router?

**Comment by Ysurac** [comment]
Via System->Sysupgrade only stable release are available.
VPS need to be updated after each major version (0.54 to 0.55) or when it's indicated in the message on openmptcprouter.com

**Comment by myshophosting** [comment]
Hi!

Im at v0.59beta6-5.4 r0+16591-b4ea8e1089 - on my router.

However im not clear about the VPS - does it need updating ? I updated my router from v0.58.5 to the above, and am not sure if the VPS server at the DC needs a corresponding update or not?

**Comment by myshophosting** [comment]
on the dashboard it says: Version：5.4.100-mptcp 0.1026

**Comment by myshophosting** [comment]
Ahh - just found this: wget -O - http://www.openmptcprouter.com/server-test/debian10-x86_64.sh | sh
I will run this.

**Comment by myshophosting** [comment]
All fixed and udpated.
