### ISSUE TITLE
Driver for dexp at-uh002b

### ISSUE THREAD

**Issue by Silvanskii** [Ysurac/openmptcprouter#2354]
**Is this request related to a missing driver support for a particular hardware platform, SoC or board? Please describe.**

I ask you to add a dexp at-uh002b network card Now during its operation, I see an error and other interfaces stop working if it works
**Describe why you are asking for this support?**

Error -  get_registers -71
**Additional context**

**Comment by Ysurac** [comment]
Should be supported via "kmod-usb-net-rtl8152" package
