### ISSUE TITLE
sh: 301: grub-mkconfig: not found error

### ISSUE THREAD

**Issue by brackerp** [Ysurac/openmptcprouter#2358]
## Expected Behavior
Install MPTCP on fresh Debin 10 with no error 

## Current Behavior
Receved error "sh: 301: grub-mkconfig: not found"

## Steps to Reproduce the Problem

  1.Old VM at BuyVM reinstal Debin 10
  2.Start MPTCP script
  3.recieve error sh: 301: grub-mkconfig: not found error

## Context (Environment)
reintsall to see if repairs pihole install issue

## Specifications

  - OpenMPTCProuter version: 0.58.5
  - OpenMPTCProuter VPS version: Debian 10
  - OpenMPTCProuter VPS provider: BuyVm
  - OpenMPTCProuter platform: x86_64
  - Country: <USA

**Comment by Ysurac** [comment]
Should be fixed now. I made a typo when trying to fix strange BuyVm VPS installation...

**Comment by brackerp** [comment]
reninstalled debin 10
ran mptcp script
rebooted
no ssh at 65222 or 22

**Comment by Ysurac** [comment]
What do you have on console/KVM view from BuyVM ?

**Comment by brackerp** [comment]
At this time i have reinstalled in both buyvm and digitalocean and it installed correctly

**Comment by brackerp** [comment]
I was wrong 
tomeny vms open
digitalocean works right it has a static ip in interface config
buyvm uses dhcp the ip is lost apfter the script

this is before
root@localhost:~# hostname -I
205.185.122.203 10.255.254.1 10.255.251.1 10.255.255.1 64:ff9b::aff:fb01
root@localhost:~#
![Capture](https://user-images.githubusercontent.com/26222041/170182069-55d53544-c4a3-4178-ac47-053be93d02fd.PNG)
this is after

this a log fo the install

[logfileBvm220524.txt](https://github.com/Ysurac/openmptcprouter/files/8768038/logfileBvm220524.txt)

**Comment by Ysurac** [comment]
Strange, the firewall, shorewall, shouldn't block DHCP.
What is the interface name that have the public IP by default and what do you have in ```/etc/shorewall/params.net``` after installation ?

**Comment by brackerp** [comment]
the picture has the vnc ip and password
mptcp is the root pw

i got to go to work

**Comment by brackerp** [comment]
also i has installed the script in to a ubuntu  on this vm and it worked
fine

**Comment by Ysurac** [comment]
I don't have the VNC password and it should be send via mail (contact@openmptcprouter.com) and not in public ;)
I think buyvm ubuntu install is correct with grub package installed, this doesn't seems to be the case on debian10/11 now.
VPS are out of stock, so I can't do any real tests.

**Comment by brackerp** [comment]
in the png file i sent you in the previous email is the ip address and port
number and the password
i still have the admin console pw and will rebuild the vm once we are done
here is the ip out of the png file 209.141.63.46:10756
and pw AyrflXgh

**Comment by Ysurac** [comment]
I fixed the issue on your VPS, the script is not able to detect default interface.
What is the result of "ip -o -4 route show to default" before running the install script ?

**Comment by brackerp** [comment]
***@***.***:~# ip -o -4 route show to default
default via 205.185.122.1 dev eth0
***@***.***:~#

**Comment by brackerp** [comment]
i reinstalled debian on vm
i have not run script yet

the vnc is still valid and password is valid

**Comment by Ysurac** [comment]
ok, after reboot the default interface is "ens3", there is options "net.ifnames=0 biosdevname=0" in default /boot/grub/grub.cfg that I don't keep as I don't have default grub config files...
I will modify script but BuyVM are really doing a dirty install...

**Comment by Ysurac** [comment]
This time both release and beta scripts should work with BuyVM.

**Comment by brackerp** [comment]
looks like you got the script to install correctly
