### ISSUE TITLE
Please tell me which usb wifi adapter is compatible?

### ISSUE THREAD

**Issue by Silvanskii** [Ysurac/openmptcprouter#2371]
**Is this request related to a missing driver support for a particular hardware platform, SoC or board? Please describe.**

**Describe why you are asking for this support?**

**Additional context**

I bought an RTL8811 adapter, but it did not work, the interface did not appear. Can you tell me which chipset is fully compatible to create a WIFI access point for NanoPI4

**Comment by Ysurac** [comment]
OpenMPTCProuter support all adapters that OpenWrt support.
Ralink or Atheros based wifi adapter are know to work well.
(Personnally I use an external Wifi AP)
