### ISSUE TITLE
VPN-Glorytun_udp 

### ISSUE THREAD

**Issue by saurabh-benlycos** [Ysurac/openmptcprouter#2372]
## Expected Behavior
We are targeting UDP aggregation.

## Current Behavior
Whenever switching from glorytun-tcp to glorytun-udp the tunnel is going down.

## Specifications

  - OpenMPTCProuter version: 5.4.106 
  - OpenMPTCProuter VPS version: Debian 10 unamex64
  - OpenMPTCProuter VPS provider:Digital Ocean
  - OpenMPTCProuter platform: x86_64

**Comment by simonemessina92** [comment]
I've noticed that everytime I restart my linksys 3200 the tunnel get down always, and the omr can't enstablish the vpn tunnel. I basically have to check to force retrieve settings and after 1 maybe 2 times it work... still confused about the firewall option when v2ray is enable, but no one had answered me back.. hope it work for yo
![Immagine 2022-06-06 094047](https://user-images.githubusercontent.com/106303869/172117652-8960499e-68f0-4487-b548-432345544a56.png)
u
