### ISSUE TITLE
Why is v2ray talking directly to WAN IPs from VPS?

### ISSUE THREAD

**Issue by grapexy** [Ysurac/openmptcprouter#2373]
I see some kind of traffic leaving VPS from port 65228 with destination of each WAN IP every couple of minutes. I haven't looked into the packets yet, but is there an explanation of why that happens? Shouldn't v2ray only talk back to OMR via proxy?

OMR:  0.59beta6-5.4
VPS: 5.4.132-mptcp 0.1027-test

**Comment by Ysurac** [comment]
Please use the template.
I don't understand the problem, V2Ray is the proxy and there is direct connection to the server part on the VPS from client part on the router in both way.
