### ISSUE TITLE
support linux/arm64 platform as VPS

### ISSUE THREAD

**Issue by frhack** [Ysurac/openmptcprouter#2374]
Hi, nowadays the ARM architecture offers very cheap and powerful options in the cloud, like for example:

https://aws.amazon.com/en/ec2/graviton/

Oracle Ampere free tier (Free ARM Instance with 24 GB of RAM and 4 cores)

Would be very interesting to support the linux/arm64 platform

**Comment by Ysurac** [comment]
To use ARM architecture an ARM64 kernel must be build. There is no so any ARM64 VPS available yet to support and test this.
You can compile the kernel yourself following this doc: https://github.com/Ysurac/openmptcprouter-vps/wiki/Compile-kernel (you only need to update kernel release to latest 5.4 available)

**Comment by frhack** [comment]
> To use ARM architecture an ARM64 kernel must be build. There is no so any ARM64 VPS available yet to support and test this. You can compile the kernel yourself following this doc: https://github.com/Ysurac/openmptcprouter-vps/wiki/Compile-kernel (you only need to update kernel release to latest 5.4 available)

hi my free VPS on Oracle Cloud - seems ARM64:


```
uname -a
Linux vps 5.13.0-1028-oracle #33~20.04.1-Ubuntu SMP Mon May 2 03:56:22 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```


AArch64 or ARM64 is the 64-bit extension of the [ARM architecture](https://en.wikipedia.org/wiki/ARM_architecture).

**Comment by frhack** [comment]
I'm trying to recompile but the following patch is missing

https://github.com/Ysurac/openmptcprouter/raw/develop/root/target/linux/generic/hack-5.4/690-mptcp_trunk.patch

**Comment by frhack** [comment]
error:

```
exec make kpkg_version=13.018+nmu2 -f /usr/share/kernel-package/ruleset/minimal.mk debian APPEND_TO_VERSION=-mptcp  INITRD=YES


^CFailed to create a ./debian directory: No such file or directory at /usr/bin/make-kpkg line 970.
```

**Comment by Pako02** [comment]
when i try to compile the kernel i have an error. Can anyone help me?
![Immagine 2022-06-06 105854](https://user-images.githubusercontent.com/106958101/172130043-ac67c293-51aa-49a8-97ff-56cd91e35a4a.png)
