### ISSUE TITLE
3 wan connections and slower than expected

### ISSUE THREAD

**Issue by dooley1981** [Ysurac/openmptcprouter#2377]
I have 3 wan connections, 1 is T-Mobile home internet getting around 120Mbps down, Verizon home 5G internet 90Mbps down and Verizon sim in a Nighthawk M1 getting 130Mbps down. Why i'm I only getting 146Mbps down? I have gigabit cables and WiFi 6 routers.

**Comment by Ysurac** [comment]
Please use template, a lot of informations are missing to help.

**Comment by dooley1981** [comment]
what template?

**Comment by Ysurac** [comment]
When you use New issue, and the correct category, it's not the case here, you have a text: it's the template.
