### ISSUE TITLE
WAN connection completely drops out randomly 

### ISSUE THREAD

**Issue by DigitalLabs420** [Ysurac/openmptcprouter#2382]
Expected Behavior
The NIC that is attached to the OMR x86 VM via Proxmox should be able to ping the VDSL modem (WAN 4), and if that fails, falls over to WAN 5, which is a 4G connection. 

Current Behavior

However, during periods of very consistent throughout, VDSL being 25/6 Mbps, 4G being roughly 15/10 Mbps, achieving an aggregate throughout (With SQM QOS)  of 37.6 UP and 14 Down, all WAN connections will drop, causing a downtime of approximately 5-10s. 

Looking at the system logs, there's really nothing indicating any errors, mainly UDHCPC renews and such. 

I've swapped NICs and systems, instead of configuring Proxmox bridges, I've directly passed through the NIC ( which was suffering from severe ping spikes from the Router to the Modem (1ms to 50ms). But that doesn't seemed to have solved the issue.  

Steps Reproduce the Problem

It appears to be intermittent. (fun...) 

Context (Environment)

I'm attempting to achieve minimal downtime for my friend, who likes to stream and suffers from VDSL disconnects. The VDSL and 4G failover would be excellent; however, introducing a possibility of WAN completely disconnecting during his streaming would be disastrous. Previously, I used an Openwrt Router at home (ROOter), before testing MPTCProuter, and haven't experienced complete WAN disconnects until now. 

Summary: 
The aggregate WAN connection performs well, but will completely disconnect (both 4G and VDSL) intermittently. 

Specifications
  - OpenMPTCProuter version: openmptcprouter v0.58.5 r0+16336-b36068d35d / LuCI Master git-21.077.59320-d1bf56d
  - OpenMPTCProuter VPS version: Version 0.1026 5.4.100-mptcp
  - OpenMPTCProuter VPS provider: Binary Lane
  - OpenMPTCProuter platform: x86-64
  - Country: Australia 

Any insight would be immensely appreciated! This is a fascinating technology!

**Comment by Kalimeiro** [comment]
Same problem with latest snapshot 0.59 and latest VPS 0.1027, when the master connection failed, all connection will drop and causing a downtime.

**Comment by Ysurac** [comment]
@DigitalLabs420 when the wan connections are failing you should have something in Status->System log. How do you detect downtime ?
You have SQM set on which interface ? Did you set an upload and download speed ?

@Kalimeiro This is not related, open your own issue.

**Comment by DigitalLabs420** [comment]
Okay, just happened, these are the only new lines appearing in the syslog. 

I see that they're related to DHCP auto-renew, perhaps both WANs renew at the same time? 

![Packet Loss](https://user-images.githubusercontent.com/96904234/172814503-37114655-a00f-4a1e-b8da-7a2242390c70.jpg)
)

**Comment by DigitalLabs420** [comment]
In retrospect, it appears that when the master connection renews, the WAN goes completely down

**Comment by DigitalLabs420** [comment]
Interesting development, so it appears that the entire VM freezes or lags, which is causing this WAN disconnect.

**Comment by DigitalLabs420** [comment]
Okay, the disconnect happened again. 

Here's the logs: 
https://pastebin.pl/view/a418aecb

**Comment by DigitalLabs420** [comment]
@Ysurac, 

I believe line 682 - 685 is when the disconnect happened. 

If you require any further information, please feel free to ask

**Comment by Ysurac** [comment]
So many "remote recv: Host is unreachable" is not normal. You try to reach a site that doesn't exist so often ?
Ping use ICMP, so it's over VPN. This is not a real problem.

**Comment by DigitalLabs420** [comment]
I'm not the only user on the network, but the only applications I have running atm are a bunch of Chrome tabs. 

Also, with the disconnects, I did discover the message in the kernel: 
https://pastebin.pl/view/417864f4

**Comment by Ysurac** [comment]
And there is a problem in one log there is ss-redir problems, it's about shadowsocks, and in latest log it's about v2ray.
Check that you don't have both running if you set them manually.

**Comment by DigitalLabs420** [comment]
> And there is a problem in one log there is ss-redir problems, it's about shadowsocks, and in latest log it's about v2ray. Check that you don't have both running if you set them manually.

I was using V2RAY for a bit, but changed it over to ShadowSocks in the hopes of improving reliability. Apologies for the confusion. I've allocated 1.9GB of RAM to the Router, and I have 4 cores of a I5 7500 as to completely avoid system resource issues.

**Comment by DigitalLabs420** [comment]
@Ysurac, I'm collecting more information atm. So I'll hopefully have a bit more of an update soon.
