### ISSUE TITLE
Home page error and question

### ISSUE THREAD

**Issue by anti-spy** [Ysurac/openmptcprouter#2387]
Hello. After entering the password writes:
TypeError
boardinfo.release is undefined

what is the reason?

I want to use mini pc instead of VPS. Can I distribute the Internet through it through the terminal in the usual way?

**Comment by Ysurac** [comment]
This error is fixed in v0.59 beta.

You can use any x86_64 as VPS if it have a good internet connection an latency in a Datacenter or at another place.

**Comment by anti-spy** [comment]
Now:
/usr/lib/lua/luci/dispatcher.lua:427: /etc/config/luci seems to be corrupt, unable to find section 'main'
