### ISSUE TITLE
Erreur d'affichage dans le menu

### ISSUE THREAD

**Issue by Cmoi20** [Ysurac/openmptcprouter#24]
## Expected Behavior
dans l'onglet Status, le menu "vue d'ensemble" n'est pas correctement affiché.

## Actual Behavior
OpenMPTCProuter version 0.12.1-3

## Steps to Reproduce the Problem

  1. se connecter sur l'interface
  2. cliquer sur Status

## Specifications

  - OpenMPTCProuter version: 0.12.1-3
  - OpenMPTCProuter VPS version: 0.11
  - Platform: chrome sur macosx

PS : un énorme merci pour le travail fournis, si je peux aider a quoi que ce soit pour faire avancer ce projet, je serais ravis dans les limites de mes compétences (peut être compléter un peu la documentation ?).

**Comment by Ysurac** [comment]
"Nom d'hôtes" a le même soucis également. C'est un bug de OpenWrt. 
Pour le moment je me suis occupé que de mes propres bugs, mais effectivement il va falloir que je corrige celui ci et que je le soumette à OpenWrt.
