### ISSUE TITLE
When update OMR, my virtual interface for VPN SITE-TO-SITE lost her firewall zone.

### ISSUE THREAD

**Issue by Kalimeiro** [Ysurac/openmptcprouter#2402]
## Expected Behavior
New interfaces created and assigned to a firewall zone need to be keeped where upgrade OMR.

![image](https://user-images.githubusercontent.com/8118989/174659646-c84be965-fefa-4a46-ae3e-72bf2fcb8c2d.png)

## Current Behavior
My new interface "VPN" lost her firewall zone configuration when upgrade OMR.

![image](https://user-images.githubusercontent.com/8118989/174659510-c7ef41cc-b4d4-4c63-8096-ea642a9ac83d.png)

## Context (Environment)
The new interface and the firewall zone is for a VPN SITE-TO-SITE i have made with integrated OpenVPN, work great.

## Specifications

  - OpenMPTCProuter version: 0.59 beta 7
  - OpenMPTCProuter VPS version: 0.1027-test
  - OpenMPTCProuter VPS provider: OVH
  - OpenMPTCProuter platform: ALL RPI
  - Country: FR

**Comment by Ysurac** [comment]
What is the initial firewall zone ?

**Comment by Kalimeiro** [comment]
i use the same VPN zone of OMR for omrvpn and omr6in4

**Comment by Kalimeiro** [comment]
bug still exist with 0.59rc1

**Comment by Ysurac** [comment]
You should use another zone, VPN zone is really for internal usage, maybe I should rename it to InternalVPN or something like that.

**Comment by Kalimeiro** [comment]
ok but if i create/rename the zone name, i need to recreate most of NAT rules to have a good vpn site-to-site working, this is the reason i have set to the zone VPN.

**Comment by Kalimeiro** [comment]
i close the issue, i have spend some times to create correctly a new zone and it's ok after upgrade to the final release 0.59.1
