### ISSUE TITLE
MTU adjustments when VPS MTU is 1492 instead of 1500

### ISSUE THREAD

**Issue by milankragujevic** [Ysurac/openmptcprouter#2404]
I am hosting OMR server (VPS) on a residential GPON connection which has 1492 MTU because of PPPoE. 

On the client (router) side, combining LTE+VDSL, which means 1500 MTU and 1492 MTU for VDSL.

Are there any adjustments that can/should be made to the VPS (server) because it has special MTU - 1492, instead of generally 1500 bytes.

**Comment by Ysurac** [comment]
No change to MTU should be needed on VPS side, but check that MTU is correct on router side.

**Comment by milankragujevic** [comment]
MTU is correctly discovered to be 1492 on VDSL, and 1500 on LTE, on the router side. So, in that case, nothing further should be done?
