### ISSUE TITLE
iPhone not working in Raspberry Pi 3b+

### ISSUE THREAD

**Issue by nscpro** [Ysurac/openmptcprouter#2407]
Hi.

When I connect the iPhone to the Raspberry Pi USB port. The terminal indicates that the iPhone is connected and the iPhone has also pressed the Trust button. If I want to add an iPhone, I don't see USB0 in the selection. Also, my phone doesn't show that Personal Hotspot is in use, although it's always on.

What should I do to get the iPhone to work?

I'm using latest openmptcprouter 64-bit kernel in Raspberry Pi 3b+

**Comment by fsufyan** [comment]
I have been using iPhone usb tethering with raspberry pi 3B+ normally for weeks now.
The interface name will show as eth1 or something like, usb0 is for android phones.

Did you create the interface and set the mptcp option as (enabled) in advanced settings?

**Comment by vinceducat** [comment]
@nscpro  ther are some post in the issue about that, take a search ...

**Comment by nscpro** [comment]
thanks :)
