### ISSUE TITLE
Port forward rules file

### ISSUE THREAD

**Issue by Ajowan84** [Ysurac/openmptcprouter#241]
Hi,

## Expected Behavior
uncomment port forwarding on VPS rules file

## Actual Behavior
In the rules file on VPS, i uncomment the two last lines and restart shorewall.
After that, all is ok but after some time, the two lines are automatically commented

## Specifications
  - OpenMPTCProuter version: 0.43
  - OpenMPTCProuter VPS version: 0.77
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
This need to be changed in *System*->*OpenMPTCProuter* *Advanced settings* tab.
I need to update the documentation :)

**Comment by Ajowan84** [comment]
Thank you for this quick response.
And thank you for this great solution !!!
