### ISSUE TITLE
What is best low latency VPS service provider?  

### ISSUE THREAD

**Issue by nscpro** [Ysurac/openmptcprouter#2410]
I live in Estonia. Which VPS service provider would be the best choice that would have low latency. Since the goal is to use live broadcasts, it is important to ensure low latency. At the same time, there should not be a traffic limit, as live broadcasts use a lot of traffic. Also, the speed should be at least 1 Gb/s.

Thank you so much :)

**Comment by ImprezyLive** [comment]
the operator does not matter, because I know LTE or 5G does not give such a delay that it would be a problem with live transmission. eg webrtc, latency is around 350 ms, I doubt you would have an operator that has more latency apart from tooway satellite links.
