### ISSUE TITLE
Loosing LAN connection to OpenMPTCPROUTER randomly

### ISSUE THREAD

**Issue by ThibautSF** [Ysurac/openmptcprouter#2419]
## Expected Behavior

I have an OpenMPTCPROUTER Raspberry install + OVH VPS.
I have 1 ADSL BOX (wan1) and 1 HUAWEI 4G box (wan2). And also a deactivated future HUAWEI 4G box (wan3) (waiting for a sim of the correct size)
Only the ADSL box has its DHCP active (but all PC uses static ipv4).

Expected: PC should access the internet and/or local network 24H/7 (as it has been working for several months)

## Current Behavior

My PC (connected via Ethernet+CPL) loses internet connection and can't reach the Raspberry IP (192.168.100.1).
My IP is manually set to 192.168.100.100 (other PC in the house uses 101 & 102).
I can retrieve connexion by switching to the ADSL or 4G box only (192.168.1.1 or 192.168.2.1) with an IP set accordingly (192.168.1.1 or 192.168.2.1) so it's not my CPL network which crash/desync.

It was working ok for several months, but since yesterday morning I have had this random disconnection.
And it is purely lan stoping on 198.168.100.X

Note: looks to be similar to #1348

## Possible Solution

The only thing I found is hard reboot the raspberry (remove the power cable).

## Steps to Reproduce the Problem

Completely random, it can happen 1 min after the last reboot or even several hours.

## Specifications

  - OpenMPTCProuter version: v0.58.5 r0+16336-b36068d35d
  - OpenMPTCProuter VPS version: 0.1026.5.4.100-mptcp
  - OpenMPTCProuter VPS provider: OVH
  - OpenMPTCProuter platform: Raspberry Pi 2 Model B Rev 1.1
  - Country: France

Network view : 
![image](https://user-images.githubusercontent.com/9386581/177754684-1ee31551-23cb-4040-a745-05b2fcbff945.png)

Logs : (burns in 180 days)
https://pastebin.com/DDXpkDLL

Detailed parameters : (burns in 180 days)
https://pastebin.com/09c8iQLq

**Comment by Kalimeiro** [comment]
Same problem with RPI3B+ since many years ...

I have definitively switch to RPI4 and so far so good (and perf is really better)
