### ISSUE TITLE
Raspberry Pi VPS with Ubuntu instead of Raspberry OS

### ISSUE THREAD

**Issue by chop249** [Ysurac/openmptcprouter#2422]
## Expected Behavior

Raspberry Pi should act as a VPS, has anyone tried using the Ubuntu image for Pi instead of Raspberry OS? I've seen where people tried the Pi as a VPS but they don't state what OS they are using. 

## Current Behavior

Not applicable, I haven't tried setting up a VPS at all yet. 

## Specifications

  - OpenMPTCProuter version: 
  0.58.5
  - OpenMPTCProuter VPS version: 
  Has not been set up. 
  - OpenMPTCProuter VPS provider:
Hopefully self hosted on an RPi 3 or 4.
  - OpenMPTCProuter platform: 
  Going to run the OpenMPTCP on an RPi 3 or 4.

**Comment by Ysurac** [comment]
For any architecture that is not x86_64 the kernel need to be recompiled. I don't want to maintain multiples kernel for VPS.
This will be maybe easier with future kernel 5.15 based version.
