### ISSUE TITLE
Unable to ping VPS server but mptcp works (but unstable and slower)

### ISSUE THREAD

**Issue by samuelchrist** [Ysurac/openmptcprouter#2434]
## Expected Behavior
The server should be able to ping and get a response

## Current Behavior
Getting error when trying to ping the server
![Issue](https://user-images.githubusercontent.com/50905950/180484990-6c596624-771d-4d2a-a79e-200f574ddfc5.JPG)

## Specifications

  - OpenMPTCProuter version: v0.58.5
  - OpenMPTCProuter VPS version:  Ubuntu 20.04
  - OpenMPTCProuter VPS provider: Vultr
  - OpenMPTCProuter platform: RPI4B 8GB

**Comment by samuelchrist** [comment]
@Ysurac Thank you very much for developing OMR. I am new to OMR and would need your thought on this.

**Comment by Ysurac** [comment]
You can disable HTTP API test in System->OpenMPTCProuter, "advanced settings" tab "Disable server http test" checkbox
You can also increase "VPS checks timeout"

**Comment by samuelchrist** [comment]
Thank you for the revert @Ysurac. I tried but got the below error. 
![image](https://user-images.githubusercontent.com/50905950/180487508-37010dde-d66b-4ec9-99a9-de7af2987509.png)

**Comment by Ysurac** [comment]
Check Status->System log to know why it can't contact VPS API/why connections drop and check the API key used in wizard.

**Comment by samuelchrist** [comment]
![Uploading Server Side issue5.JPG…]()

**Comment by Ysurac** [comment]
You rebooted the VPS after install ?

**Comment by samuelchrist** [comment]
Yes @Ysurac Mutiple times

**Comment by Ysurac** [comment]
On the VPS, try a ```systemctl restart omr-admin```

**Comment by samuelchrist** [comment]
![image](https://user-images.githubusercontent.com/50905950/180494184-e0ce01b2-8acc-4712-8e49-d602221d18c1.png)

**Comment by Ysurac** [comment]
What you have in ```journalctl -xe``` and in ```/var/log/daemon.log``` ?

**Comment by samuelchrist** [comment]
![image](https://user-images.githubusercontent.com/50905950/180494614-6d7ad4f9-32ce-49f2-b993-90af7a78bc17.png)
![image](https://user-images.githubusercontent.com/50905950/180494730-ac9e13a2-3c28-4827-b37c-ee8e0bb5b17e.png)

**Comment by Ysurac** [comment]
What is the OS used on the VPS ?
I think there is a problem in ```/etc/openmptcprouter-vps-admin/omr-admin-config.json```

**Comment by samuelchrist** [comment]
@Ysurac  .Its Ubuntu 20.04

**Comment by Ysurac** [comment]
So it's the problem.
As it's a fresh install, you should reinstall from scratch.

**Comment by samuelchrist** [comment]
Thank you @Ysurac
