### ISSUE TITLE
No connections After update wrt3200acs

### ISSUE THREAD

**Issue by domoclick** [Ysurac/openmptcprouter#2436]
## Expected Behavior

I Just upgrade from v.0.58.5.r0, full working, to v.0.59.rc1.5.4 in my linksys wrt3200acm but after upgrade no internet connections and i cant ping anything, even 1.1.1.1 or 8.8.8.8. Wan seems to work because i see traffico in and out but i cant see any sites.

## Current Behavior

If i install a fresh versione 0.58, configure my wans, internet Is ok and everything work. I flash new firmware 0.59, configure my wans and nothing works, only lan side Is ok.
Can you help me please?

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - OpenMPTCProuter version: 
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter VPS provider:
  - OpenMPTCProuter platform: 
  - Country: 

## Specifications

  - OpenMPTCProuter version: 
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter VPS provider:
  - OpenMPTCProuter platform:

**Comment by Ysurac** [comment]
Would be better with a completed template...
What you have in status page ?

**Comment by domoclick** [comment]
hi, Ysurac and thanks for answer.

this is my working Dashboard
<img width="915" alt="image" src="https://user-images.githubusercontent.com/59266106/180659526-da2eb61b-81f6-459c-86b9-f20aaeac0190.png">

Then, i flash new version openmptcprouter-v0.59rc1-5.4-r0+16594-ce92de8c8c-mvebu-cortexa9-linksys_wrt3200acm-squashfs-sysupgrade, no keep setting, reconfigure my wan1 with static ip, i see my public ip, but i cant ping anything and no internet connection up.
<img width="923" alt="image" src="https://user-images.githubusercontent.com/59266106/180659844-6345bc2c-3297-4472-9feb-46b5463f2d69.png">






> Would be better with a completed template... What you have in status page ?

**Comment by Ysurac** [comment]
I would need to see the status page. In System->OpenMPTCProuter, "status" tab.

**Comment by domoclick** [comment]
Ysurac, i just rebooted my router and now it works!!
