### ISSUE TITLE
Gateway Down PPPOE Connection

### ISSUE THREAD

**Issue by andreaconfa** [Ysurac/openmptcprouter#2446]
Gateway UP

## The gateway setted up as PPPOE is showing as DOWN but is working correctly. If i set it as DHCP or static ip all is showed as good.
I have two identical VDSL connections from TIM (Italy) and on both i have this issue.
In the screenshot i setted up the first as PPPOE (gateway down warning) and the second one as static IP (working but not wat i want)
Found that when i set PPOE the default address 192.168.100.1 is assigned to the pppoe interface. how i change that keeping PPPOE?
Cannot set 192.168.100.1 ip addres on my uplink routers because its "Used internally to the router"

## Specifications

  - OpenMPTCProuter version: 0.58.5
  - OpenMPTCProuter VPS version: 0.1026 5.4.100-mptcp
  - OpenMPTCProuter VPS provider: Aruba IT
  - OpenMPTCProuter platform: x86_64

![image](https://user-images.githubusercontent.com/44619437/182026382-8cc4971e-7adc-43fd-b0e8-b7685f54d026.png)

**Comment by Ysurac** [comment]
Can you test 0.59rc1 https://github.com/Ysurac/openmptcprouter/issues/2077 ?

**Comment by andreaconfa** [comment]
how to update? i have to update both vpu and router?

> Can you test 0.59rc1 #2077 ?

**Comment by Ysurac** [comment]
Yes, update VPS and then the router using 5.4 based release.

**Comment by andreaconfa** [comment]
the script is telling me that the certificate is not trusted and expired

**Comment by Ysurac** [comment]
Update your VPS: ```apt-get update && apt-get upgrade```
If you still have the issue, or if you don't want to update it: ```apt-get install -y ca-certificates && sed -i '/^mozilla\/DST_Root_CA_X3/s/^/!/' /etc/ca-certificates.conf && update-ca-certificates -f```

**Comment by andreaconfa** [comment]
vps updated to Version 0.1027-test 5.4.207-mptcp

How to update Router?

**Comment by andreaconfa** [comment]
is possible to upload or update the files without re-flash the ssd?

**Comment by Ysurac** [comment]
https://github.com/Ysurac/openmptcprouter/wiki/Router-install#update

**Comment by andreaconfa** [comment]
updated bot vps and router but the issue still there

> Can you test 0.59rc1 #2077 ?

**Comment by andreaconfa** [comment]
can this issue be related to configuration error?

**Comment by Ysurac** [comment]
Maybe, I don't test PPPoE  I would need the result of ```uci show network``` via SSH or in System->OpenMPTCProuter, "Show all settings" tab line beginning with "network."
I also need the result of ```ip r```, ```ip a``` and ``ifstatus WAN_xxxx``` (replace xxx with the name of your WAN) via SSH.

I see the detected gateway is 192.168.100.1 when IP begin with 87.14.xxxx, maybe I detected wrongly the IP or gateway...

**Comment by andreaconfa** [comment]
uci show netork:
`network.loopback=interface
network.loopback.proto='static'
network.loopback.ipaddr='127.0.0.1'
network.loopback.netmask='255.0.0.0'
network.loopback.multipath='off'
network.loopback.device='lo'
network.loopback.metric='7'
network.globals=globals
network.globals.ula_prefix='fd04:a97c:d238::/48'
network.globals.multipath='enable'
network.globals.mptcp_path_manager='fullmesh'
network.globals.mptcp_scheduler='blest'
network.globals.mptcp_checksum='0'
network.globals.mptcp_debug='0'
network.globals.mptcp_syn_retries='2'
network.globals.mptcp_subflows='3'
network.globals.mptcp_add_addr_accepted='1'
network.globals.mptcp_add_addr_timeout='120'
network.globals.mptcp_fullmesh_num_subflows='1'
network.globals.mptcp_fullmesh_create_on_err='1'
network.globals.mptcp_ndiffports_num_subflows='1'
network.globals.mptcp_version='0'
network.globals.congestion='bbr2'
network.globals.mptcp_rr_cwnd_limited='Y'
network.globals.mptcp_rr_num_segments='1'
network.lan=interface
network.lan.proto='static'
network.lan.netmask='255.255.255.0'
network.lan.device='eth0'
network.lan.ifname='eth0'
network.lan.ipv6='0'
network.lan.delegate='0'
network.lan.addlatency='0'
network.lan.multipath='off'
network.lan.ip4table='lan'
network.lan.metric='8'
network.lan.label='LAN'
network.lan.defaultroute='0'
network.lan.peerdns='0'
network.lan.ipaddr='192.168.110.1'
network.lan_rule=rule
network.lan_rule.lookup='lan'
network.lan_rule.priority='100'
network.wan1=interface
network.wan1.device='eth1'
network.wan1.ip4table='wan'
network.wan1.multipath='master'
network.wan1.defaultroute='0'
network.wan1.addlatency='0'
network.wan1.ipv6='0'
network.wan1.metric='3'
network.wan1.peerdns='0'
network.wan1.pppd_options='persist maxfail 0'
network.wan1.proto='pppoe'
network.wan1.username='aliceadsl'
network.wan1.password='aliceadsl'
network.wan1.auth='both'
network.wan1.label='WAN_MANGIAGALLI'
network.wan1_dev=device
network.wan1_dev.name='eth1'
network.wan1_dev.txqueuelen='20'
network.wan2=interface
network.wan2.device='eth2'
network.wan2.ip4table='wan'
network.wan2.multipath='on'
network.wan2.defaultroute='0'
network.wan2.addlatency='0'
network.wan2.ipv6='0'
network.wan2.metric='4'
network.wan2.peerdns='0'
network.wan2.pppd_options='persist maxfail 0'
network.wan2.proto='pppoe'
network.wan2.username='aliceadsl'
network.wan2.password='aliceadsl'
network.wan2.auth='both'
network.wan2.label='WAN_CONFALONIERI'
network.wan2_dev=device
network.wan2_dev.name='eth2'
network.wan2_dev.txqueuelen='20'
network.wan3=interface
network.wan3.device='eth3'
network.wan3.ip4table='wan'
network.wan3.multipath='on'
network.wan3.defaultroute='0'
network.wan3.addlatency='0'
network.wan3.ipv6='0'
network.wan3.metric='5'
network.wan3.peerdns='0'
network.wan3.proto='dhcp'
network.wan3.label='WAN_LTE'
network.wan3_dev=device
network.wan3_dev.name='eth3'
network.wan3_dev.txqueuelen='20'
network.omrvpn=interface
network.omrvpn.device='tun0'
network.omrvpn.ip4table='vpn'
network.omrvpn.multipath='off'
network.omrvpn.leasetime='12h'
network.omrvpn.type='tunnel'
network.omrvpn.txqueuelen='100'
network.omrvpn.metric='1200'
network.omrvpn.proto='none'
network.omr6in4=interface
network.omr6in4.proto='6in4'
network.omr6in4.ip4table='vpn'
network.omr6in4.multipath='off'
network.omr6in4.ipaddr='10.255.255.2'
network.omr6in4.peeraddr='10.255.255.1'
network.omr6in4.auto='0'
network.omr6in4.metric='1201'
network.omr6in4.ip6addr='fe80::a00:2/126'
network.omr6in4.gateway='fe80::a00:1/126'
network.wan4_dev=device
network.wan4_dev.name='eth4'
network.lan_dev=device
network.lan_dev.name='eth0'
`

ip r
`default via 10.255.255.1 dev tun0
default metric 1
        nexthop via 192.168.100.1 dev pppoe-wan1 weight 2
        nexthop via 192.168.100.1 dev pppoe-wan2 weight 1
        nexthop via 192.168.103.1 dev eth3 weight 1
default via 192.168.100.1 dev pppoe-wan1 metric 3
default via 192.168.100.1 dev pppoe-wan2 metric 4
default via 192.168.103.1 dev eth3 metric 5
default via 10.255.255.1 dev tun0 metric 1200
10.255.255.1 dev tun0 proto kernel scope link src 10.255.255.2
10.255.255.2 dev tun0 scope link metric 1200
79.24.135.77 dev pppoe-wan1 scope link metric 3
79.24.135.101 dev pppoe-wan2 scope link metric 4
83.136.XXX.XXX metric 1
        nexthop via 192.168.100.1 dev pppoe-wan1 weight 10
        nexthop via 192.168.100.1 dev pppoe-wan2 weight 1
        nexthop via 192.168.103.1 dev eth3 weight 1
127.0.0.0/8 dev lo proto static scope link metric 7
192.168.100.1 dev pppoe-wan1 proto kernel scope link src 79.24.135.77
192.168.100.1 dev pppoe-wan2 proto kernel scope link src 79.24.135.101
192.168.103.0/24 dev eth3 scope link metric 5
`


ip a
`1: lo: <LOOPBACK,UP,LOWER_UP,80000> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ip6tnl0@NONE: <NOARP,80000> mtu 1452 qdisc noop state DOWN group default qlen 1000
    link/tunnel6 :: brd ::
3: sit0@NONE: <NOARP,80000> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
4: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP,80000> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 0c:c4:7a:ac:5e:3e brd ff:ff:ff:ff:ff:ff
    inet 192.168.110.1/24 brd 192.168.110.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::ec4:7aff:feac:5e3e/64 scope link
       valid_lft forever preferred_lft forever
5: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP,80000> mtu 1500 qdisc mq state UP group default qlen 20
    link/ether 0c:c4:7a:ac:5e:3f brd ff:ff:ff:ff:ff:ff
    inet6 fe80::ec4:7aff:feac:5e3f/64 scope link
       valid_lft forever preferred_lft forever
6: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP,80000> mtu 1500 qdisc mq state UP group default qlen 20
    link/ether 0c:c4:7a:ac:5e:40 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::ec4:7aff:feac:5e40/64 scope link
       valid_lft forever preferred_lft forever
7: eth3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 100
    link/ether 0c:c4:7a:ac:5e:41 brd ff:ff:ff:ff:ff:ff
    inet 192.168.103.117/24 brd 192.168.103.255 scope global eth3
       valid_lft forever preferred_lft forever
8: gre0@NONE: <NOARP,80000> mtu 1476 qdisc noop state DOWN group default qlen 1000
    link/gre 0.0.0.0 brd 0.0.0.0
9: gretap0@NONE: <BROADCAST,MULTICAST,80000> mtu 1462 qdisc noop state DOWN group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
10: erspan0@NONE: <BROADCAST,MULTICAST,80000> mtu 1450 qdisc noop state DOWN group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
11: ip6gre0@NONE: <NOARP,80000> mtu 1448 qdisc noop state DOWN group default qlen 1000
    link/gre6 :: brd ::
12: bond0: <BROADCAST,MULTICAST,MASTER,80000> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 5e:1e:a1:5b:78:50 brd ff:ff:ff:ff:ff:ff
13: teql0: <NOARP,80000> mtu 1500 qdisc noop state DOWN group default qlen 100
    link/void
14: eth4: <BROADCAST,MULTICAST,80000> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 50:3e:aa:08:ac:0d brd ff:ff:ff:ff:ff:ff
25: ifb4eth4: <BROADCAST,NOARP,80000> mtu 1500 qdisc noop state DOWN group default qlen 32
    link/ether 8e:e0:d6:c9:a7:a4 brd ff:ff:ff:ff:ff:ff
30: pppoe-wan1: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1492 qdisc fq_codel state UNKNOWN group default qlen 100
    link/ppp
    inet 79.24.135.77 peer 192.168.100.1/32 scope global pppoe-wan1
       valid_lft forever preferred_lft forever
31: pppoe-wan2: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1492 qdisc fq_codel state UNKNOWN group default qlen 100
    link/ppp
    inet 79.24.135.101 peer 192.168.100.1/32 scope global pppoe-wan2
       valid_lft forever preferred_lft forever
34: ifb4eth3: <BROADCAST,NOARP,80000> mtu 1500 qdisc noop state DOWN group default qlen 32
    link/ether 56:6d:d3:b8:83:ae brd ff:ff:ff:ff:ff:ff
35: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP,80000> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 100
    link/none
    inet 10.255.255.2 peer 10.255.255.1/32 scope global tun0
       valid_lft forever preferred_lft forever
    inet6 fe80::6b57:e469:f161:efb4/64 scope link stable-privacy
       valid_lft forever preferred_lft forever
38: ifb4pppoe-wan1: <BROADCAST,NOARP,80000> mtu 1500 qdisc noop state DOWN group default qlen 32
    link/ether 36:90:96:46:78:9e brd ff:ff:ff:ff:ff:ff
41: ifb4pppoe-wan2: <BROADCAST,NOARP,80000> mtu 1500 qdisc noop state DOWN group default qlen 32
    link/ether b6:77:41:c5:32:89 brd ff:ff:ff:ff:ff:ff
44: ifb4tun0: <BROADCAST,NOARP,80000> mtu 1500 qdisc noop state DOWN group default qlen 32
    link/ether be:0f:19:25:90:c4 brd ff:ff:ff:ff:ff:ff
`
ifstatus WAN_xxxx:
Not working no metter whic name i put in


> all

**Comment by Ysurac** [comment]
Should be ```ifstatus wan1```

**Comment by andreaconfa** [comment]
> Should be `ifstatus wan1`

reply updated with the output of the commands

**Comment by Ysurac** [comment]
I don't see any error here, it's only that 192.168.100.1 doesn't answer to ping. It's not a problem.
If you want to remove the warning in status page, you can check "Disable gateway ping" in System->OpenMPTCProuter, "Advanced settings" tab.

**Comment by andreaconfa** [comment]
> I don't see any error here, it's only that 192.168.100.1 doesn't answer to ping. It's not a problem. If you want to remove the warning in status page, you can check "Disable gateway ping" in System->OpenMPTCProuter, "Advanced settings" tab.

that make sense because in fact 192.168.100.1 is not the ip address of the gateway router where the PPPOE connection is established

**Comment by andreaconfa** [comment]
maybe is possible to change the gateway ip with  the correct one?

**Comment by andreaconfa** [comment]
how i rollback to the stable release fot he vps?

**Comment by Ysurac** [comment]
The gateway seems to be what is announced by the connection.
You can launch stable install script and this will rollback. But current VPS test release will be stable release really soon now.

**Comment by andreaconfa** [comment]
onother question
My setup io OPENMPTCROUTER -> Udm Pro - LAN

I have a DDNS the resolve to my WAN IP and not i setted up this DDNS with the IP of the VPS to be able to connect to my network. 
This works fine but when i'm inside my lan this stop working. How can i override the hostname to my local ip inside OPENMPTCROUTER ?

**Comment by Ysurac** [comment]
you can set a custom answer to a domain in Network->DHCP&DNS, "Addresses" field with for example "/myddns.domain.com/192.168.100.52"

**Comment by andreaconfa** [comment]
> you can set a custom answer to a domain in Network->DHCP&DNS, "Addresses" field with for example "/myddns.domain.com/192.168.100.52"

thankyou, i was able to make it work.

I'm experiencing another problem: From my UDM Pro i have a L2TP VPN that i use to connect to my LAN from the internet. Now with OpenMptcprouter it stopped working. I opened all the port's to the UDM via the port forwarding (the port forwarding is working bacause i can reach other services hosted bihind the udm)

Thanks

**Comment by andreaconfa** [comment]
Update: cannot connect to the UDM VPN also reaching it via one of the WAN ip addred without vpn tunnel to vps (other ports working fine)

**Comment by n4sty3us** [comment]
@andreaconfa Hi, I also have a TIM vdsl connection, I ask you how did you manage to create a pppoe wan?  I searched everywhere but couldn't find it
