### ISSUE TITLE
Rockchip RK3399 6 core 64 bit device

### ISSUE THREAD

**Issue by kwiwtov** [Ysurac/openmptcprouter#2451]
Hello! 
Thank you for such a great work!!!
I got a new device https://aliexpress.ru/item/1005003903758642.html on Rockchip RK3399 Soc.
Do you have image compatible to this device? 
Thank you!

**Comment by Ysurac** [comment]
The NanoPI R4S based on RK3399 is officially supported, but no idea if the image can work on this device or if you need to build a custom image ( https://github.com/Ysurac/openmptcprouter/wiki/Create-image-for-unsupported-platform ).
