### ISSUE TITLE
Port opening and forwarding in new build 0.59rc1 not working

### ISSUE THREAD

**Issue by iamdivyanshverma** [Ysurac/openmptcprouter#2457]
## Current Behavior
hi @Ysurac , I am following your configuration given on "https://github.com/Ysurac/openmptcprouter/wiki/Port-forwarding", I am trying to forward a webserver from my laptop to the vps server , below are the settings i am following , packet from the port 7104 is reaching till the tun0 of the OMR but after that it is not forwarding to the eth0 interface....

![apache_1](https://user-images.githubusercontent.com/98642986/183324920-2100653f-8c24-4bdf-a32c-26d55a3fd3a5.png)

![apache_2](https://user-images.githubusercontent.com/98642986/183325128-f3552078-fd6b-4119-bfe4-05463e63905a.png)

## Specifications

  - OpenMPTCProuter version: (v0.59rc1) 
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter VPS provider: Digital Ocean
  - OpenMPTCProuter platform: (RPI4)

**Comment by Ysurac** [comment]
You are redirecting traffic to 192.168.100.1 port 7104 and a SNAT rule for traffic to 192.168.100.248, but as traffic is redirected to 192.168.100.1 the SNAT rule is not used in this case. I think you want to forward to internal address 192.168.100.248 in the forward rule.

**Comment by iamdivyanshverma** [comment]
Hi @Ysurac ,
Yes, i want to forward it to internal address i.e 192.168.100.248...
