### ISSUE TITLE
Using a SONY camera PXW-X200 AND PXW-Z280

### ISSUE THREAD

**Issue by iamdivyanshverma** [Ysurac/openmptcprouter#2458]
## Current Behavior
HI @Ysurac I am using OMR router for UDP aggregation in a SONY camera ( PXW-X200 AND PXW-Z280) but in camera itself speed is coming in Kbps.
I am using 4 wan connections, collectively i am getting 40 - 50 Mbps.
Is there any specific configuration has to be done in the router in order to use feed cameras...?

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - OpenMPTCProuter version: v0.59rc1
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter VPS provider:
  - OpenMPTCProuter platform: RPI4
  - Country:INDIA

**Comment by Ysurac** [comment]
You can optimizations in the doc: https://github.com/Ysurac/openmptcprouter/wiki/Optimization
