### ISSUE TITLE
Disable Terminal Login without password

### ISSUE THREAD

**Issue by lars18th** [Ysurac/openmptcprouter#246]
Hi,

In a virtual environment is a huge security hole to leave the console open without a password.
**And now that's true bydefault!**

I recomend to change it, or with a GUI option, or by default.

You only need to edit `/etc/config/system` and change to:
```
option ttylogin '1'
```

Now by default this value is '0', and the login is fully open!

Please, consider it.
Regards.

Note: Read more at https://forum.openwrt.org/t/solved-serial-port-rs-232-securing-console-and-preventing-lockout/13081/4

**Comment by Ysurac** [comment]
True, it's default OpenWrt config. This will be fixed in next release.
