### ISSUE TITLE
Wiki doesn't mention Wireguard port on VPS

### ISSUE THREAD

**Issue by Steltek** [Ysurac/openmptcprouter#2463]
The documentation in the Wiki, specifically the page on the VPS, does not seem to list the Wireguard port (65311/udp):

https://github.com/Ysurac/openmptcprouter/wiki/Install-or-update-the-VPS

(Apologies if this is the wrong way to report that. I've not found out how to issue a pull request against Wiki documentation, hence why I'm opening this issue instead.

**Comment by Ysurac** [comment]
Fixed in the wiki.
Thanks
