### ISSUE TITLE
More documentation

### ISSUE THREAD

**Issue by yue2388253** [Ysurac/openmptcprouter#2470]
Hi, 

Is there any detailed documentation about technologies used in OMR?
The [wiki](https://github.com/Ysurac/openmptcprouter/wiki/Technologies) only mentioned some related technologies such as MPTCP, shadowsocks, etc.
It seems that there are various technologies available to be used for the traffic between OMR and the VPS (i.e., shadowsocks, Glorytun TCP, MLVPN, OpenVPN, etc.), while which one is the best is still unclear, although this may depend on the actual deployment environment.
Is there any technical reports on how to choose these technologies?

Best regards, 
Lam

**Comment by ben-ba** [comment]
can we reopen this issue?
