### ISSUE TITLE
Not able to download kmod-usb-dwc2 using luci in v0.59rc1 for rpi_cm4

### ISSUE THREAD

**Issue by iamdivyanshverma** [Ysurac/openmptcprouter#2478]
## Specifications

  - OpenMPTCProuter version: v0.59rc1
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter VPS provider:
  - OpenMPTCProuter platform: rpi-cm4

**Comment by Ysurac** [comment]
I don't make any support on old release candidate. Update to latest release.
