### ISSUE TITLE
Global Smart DNS configuration

### ISSUE THREAD

**Issue by kverkind** [Ysurac/openmptcprouter#2481]
Expected Behavior
Support SmartDNS

Current Behavior
Not known

Specifications
OpenMPTCProuter version: v0.58.5 r0+16336-b36068d35d
OpenMPTCProuter VPS version: OpenMPTCProuter VPS 0.1026
OpenMPTCProuter VPS provider: Hetzner
OpenMPTCProuter platform: Raspberry Pi 4 Model B Rev 1.2
Country: BE

Question: Is there a possibility to configure a global 'smart DNS'

**Comment by Ysurac** [comment]
In Network->DHCP&DNS replace "127.0.0.1#5353" by the DNS IP you want to use.
