### ISSUE TITLE
will it work on BananaPI with 4 LTE modems?

### ISSUE THREAD

**Issue by David-Afik** [Ysurac/openmptcprouter#2488]
Hello, 
I have a brand new BananaPI board 
if I install on the SD card this image:
`squashfs image: [openmptcprouter-v0.59-5.4-r0+16594-ce92de8c8c-mediatek-mt7623-bpi_bananapi-r2-squashfs-img.gz](https://download.openmptcprouter.com/release/v0.59/bpi-r2/targets/mediatek/mt7623/openmptcprouter-v0.59-5.4-r0+16594-ce92de8c8c-mediatek-mt7623-bpi_bananapi-r2-squashfs-img.gz) (2022/08/22 - 44.76Mo - [sha256sum](https://download.openmptcprouter.com/release/v0.59/bpi-r2/targets/mediatek/mt7623/openmptcprouter-v0.59-5.4-r0+16594-ce92de8c8c-mediatek-mt7623-bpi_bananapi-r2-squashfs-img.gz.sha256sum))`

do I need to do anything else?
meaning that after the installation will it work with 4 modems to the internet? 
or I missing something ?

I want to create a "Super" router with 4 modems  - is this the solution ?

Thanks ,

**Comment by Ysurac** [comment]
It depends on the max desired speed.
