### ISSUE TITLE
qmi modem ( mc7750 ) will not initialize

### ISSUE THREAD

**Issue by squeaky-geek** [Ysurac/openmptcprouter#2497]
PLEASE NOTE:
server is good, default setup ( using ethernet ports and dual GX440's ) works fine.
however, when the modems are migrated into the unit ( apu 3c4 );
1: "openwrt" sees them, connects + configures, INSTANTLY... ( no mptcp though *sad face* )
2: openmptcprouter ( OMR ) ( see images please ) refuses to handle them correctly ( appropriate modules, drivers, ect. seem to be listed + enabled ) the modems BOTH show as "qmi~wwan0" + "qmi~wwan1" however, see " issue " , please reference attached images.

build:
Pc Engines APU 3c4
2x Sierra Wireless MC7750 mPcie Modems
     ^- using qmi-utils OR Modem Manager

issue:
neither modem will receive ; gateway, IP, at first ONE would connect without gateway, now... neither modem is functioning correctly.
i am unable to " Force " the original situation of only one modem partially connecting.

steps taken so far:
sim swaps, ( i have 2 sets available, all 4 sim cards work elsewhere. )
[ reboot ] , [ update + reboot ] , [ change modem init wait-time ] , [ reset / start from scratch ] , [think bad hardware? ] 
>[ power off ] , [swap ssd to " openwrt" ] , openwrt boots and shows BOTH devices connected to carrier network grrrr...

so i try a FRESH opnmptcprouter install....  nope... issue persists ( is it possible using 2 of the same model modem is causing a conflict? )

images may give some insight, if logs are needed please advise how to create them, i have ssh available.
note: onemarcfifty sent me here, ONLY because the " default OpenWRT " sees the modems, he believes it is something to do with the init script, however i am a hardware guy, not a code guy... i promise i will do my best to follow your instruction, and if a tutorial is available please link, i am accustomed to doing extensive research. ( i have never coded for modems before :/ ) -thank you.

- i have more images upon request.

Model | PC Engines apu3
Architecture | AMD GX-412TC SOC
Target Platform | x86/64
Firmware Version | openmptcprouter v0.59-5.4 r0+16594-ce92de8c8c / LuCI openwrt-21.02 branch git-22.119.37126-a993714
Kernel Version | 5.4.194

![new_both_show](https://user-images.githubusercontent.com/65478629/187146300-05bb36a8-aae9-4012-9591-ee0c34a29230.JPG)
![on board](https://user-images.githubusercontent.com/65478629/187146301-10bccf6d-80a6-4faa-a46b-830c15f1d8b7.jpg)
![opnWRT_tekLager](https://user-images.githubusercontent.com/65478629/187146303-4e3d02c8-a750-42b8-9736-f098a2767be2.JPG)
![ethernet_gx-440](https://user-images.githubusercontent.com/65478629/187146306-d289a0f2-0b66-45a6-9d53-8e7883082874.JPG)
![in gx440s](https://user-images.githubusercontent.com/65478629/187146308-0dbc6ef2-30e7-483c-b693-0463491037ab.jpg)

**Comment by Ysurac** [comment]
MAC address seems to be the same for both modems.
Can you try to set only one modem first ?

**Comment by squeaky-geek** [comment]
> MAC address seems to be the same for both modems. Can you try to set only one modem first ?

I will attempt single modem install and report back.

**Comment by squeaky-geek** [comment]
please see images attached:

![single_modem](https://user-images.githubusercontent.com/65478629/187321231-d39c84c7-b978-46ca-9987-5d3da3e82d6f.JPG)
![modem_setting](https://user-images.githubusercontent.com/65478629/187321236-3ffd0803-a131-45fc-a845-3dee501bf3df.JPG)
![i_changed](https://user-images.githubusercontent.com/65478629/187321238-e9e43c5d-cef7-4141-8b3e-60374a06fb31.JPG)
![dynamic_after_gx440](https://user-images.githubusercontent.com/65478629/187321239-b536b450-fae3-4f86-82e6-47899508da32.JPG)
![wan1_internal_mc7750](https://user-images.githubusercontent.com/65478629/187321240-6b6f6ae3-b3b6-46cd-916c-7381d7d6edd9.JPG)

**Comment by squeaky-geek** [comment]
** both qmi AND modem manager have been tried with same error / issue

**Comment by squeaky-geek** [comment]
all screen caps so far:

![added force](https://user-images.githubusercontent.com/65478629/187321370-ad76437c-ffcb-4b47-a0f1-8ceca19670eb.JPG)
![after_force](https://user-images.githubusercontent.com/65478629/187321373-22391d3d-507a-463e-98ad-60a0fcd7ba05.JPG)
![after-reboot-again](https://user-images.githubusercontent.com/65478629/187321375-ac35007e-b628-46c8-b093-c92a9932fd1e.JPG)
![Capture1](https://user-images.githubusercontent.com/65478629/187321376-f06223a3-e956-4a0a-b17a-627cbcc69bd4.JPG)
![dmz instead](https://user-images.githubusercontent.com/65478629/187321377-99e96bb2-8fc3-4828-844c-647bba145bfe.JPG)
![fixed_one_maybe](https://user-images.githubusercontent.com/65478629/187321380-53e78d83-ac95-48ee-8e49-1a30b24d01c6.JPG)
![ifaces](https://user-images.githubusercontent.com/65478629/187321381-2138a658-d46d-428d-89ee-babec9ba3812.JPG)
![modem_dropped_but-why](https://user-images.githubusercontent.com/65478629/187321383-56db32c7-86f0-4ee8-a9ce-8959ed11a941.JPG)
![now-vpn-i-guess](https://user-images.githubusercontent.com/65478629/187321384-deb5815c-06ce-4ef2-a72a-9623af5b168e.JPG)
![omg-reboot-progress](https://user-images.githubusercontent.com/65478629/187321386-20b1317e-b94b-47e6-b2f3-7b0b326d6175.JPG)
![omr_client](https://user-images.githubusercontent.com/65478629/187321387-6ad6b288-cd3d-400c-a8a1-7a4956d90352.JPG)
![router1](https://user-images.githubusercontent.com/65478629/187321388-268b218e-d8cd-4fbe-80e0-3175d01f2a5f.JPG)
![router2](https://user-images.githubusercontent.com/65478629/187321390-a393c7a7-101a-43c2-9059-3134479c5f5c.JPG)
![router3](https://user-images.githubusercontent.com/65478629/187321391-d5525869-b590-4537-a57b-d743ab064ae6.JPG)
![setting1](https://user-images.githubusercontent.com/65478629/187321394-b524f763-d126-4766-bb95-7af8e96011d7.JPG)
![setting2](https://user-images.githubusercontent.com/65478629/187321395-0709dc80-a011-4a63-af94-1cb0b8982510.JPG)
![try2](https://user-images.githubusercontent.com/65478629/187321396-65ceaa5b-e386-408b-9958-fbbdfa87fcca.JPG)
![try2lan](https://user-images.githubusercontent.com/65478629/187321397-da238525-6bcc-4e40-87cd-34514a923bb8.JPG)
![try2wan1](https://user-images.githubusercontent.com/65478629/187321399-85085c77-724a-4d09-9121-83bd7eca9fb3.JPG)
![try2wan2](https://user-images.githubusercontent.com/65478629/187321401-a66d18a1-a7ac-400d-b633-6187baf40e61.JPG)
![wan1cap](https://user-images.githubusercontent.com/65478629/187321402-5c1ffdfc-e30c-477d-a2b6-f713e647b693.JPG)
![wan2cap](https://user-images.githubusercontent.com/65478629/187321405-b9800613-e33b-4a4e-a8e4-21042fc222e9.JPG)
![what-am-i-missing](https://user-images.githubusercontent.com/65478629/187321406-461ee695-e7a4-499f-bd1b-d23aa7052d9c.JPG)

**Comment by squeaky-geek** [comment]
Duplicate Mac address was from the OpenWRT screenshot** OpenWRT works with DUAL lte modems just fine, however, openmptcprouter does not.

**Comment by Ysurac** [comment]
Duplicate MAC can be a problem with OpenMPTCProuter.
Too many captures here... I really don't know what you are doing.
Use Network->Interfaces to configure the interface, ModemManager as protocol and if possible full path to the device (/sys/devices/platform/soc/20980000.usb/usb******) but ModemManager should directly show you device name (and will use full path). Use also IPv4 Only on IP Type. If you get gateway down in status page it's often not a problem.

**Comment by squeaky-geek** [comment]
something changed xD i am using modem manager with single modem and it is connected, i will attempt dual modem now.

**Comment by squeaky-geek** [comment]
see images: this is where I'm at. i dont understand the error displayed, i have not yet changed any advanced images
![overview_single](https://user-images.githubusercontent.com/65478629/187548384-ef06223f-7d4c-4e4e-bac4-7aeb9e9aac76.JPG)
![dual_not_working](https://user-images.githubusercontent.com/65478629/187548386-609aff56-694b-4d29-ada1-55d2b9af3741.JPG)
![what_does_this_mean](https://user-images.githubusercontent.com/65478629/187548388-e0de93fc-341c-4dd4-ade1-b527cbd66e17.JPG)

**Comment by squeaky-geek** [comment]
![Uploading im_trying.JPG…]()

**Comment by squeaky-geek** [comment]
> Duplicate MAC can be a problem with OpenMPTCProuter. Too many captures here... I really don't know what you are doing. Use Network->Interfaces to configure the interface, ModemManager as protocol and if possible full path to the device (/sys/devices/platform/soc/20980000.usb/usb******) but ModemManager should directly show you device name (and will use full path). Use also IPv4 Only on IP Type. If you get gateway down in status page it's often not a problem.

I have followed these instructions exactly and I now get a different error " mm teardown in progress " I have no idea what that means and google didn't help.

**Comment by squeaky-geek** [comment]
well... i feel like an idiot for not doing this first:
delete interfaces ... reboot ... recreate wan1 , recreate wan2 ... reboot ... wait ... and the're up!!   modem manager for the win.
thank you sir, qmi would not work for these modems, the solution for on board Sierra Wireless MC7750 is Modem Manager
