### ISSUE TITLE
"no token yet available" since 0.59.1 and 0.1028 update

### ISSUE THREAD

**Issue by vinceducat** [Ysurac/openmptcprouter#2507]
no token yet available since 0.59.1 and 0.1028 update
## Expected Behavior
since i update OMR and OMR vps to 0.59.1 and 0.1028 

## Current Behavior
now i have the default no token yet avaible on the status page in OMR

## Possible Solution
try relaunch vps script

## Steps to Reproduce the Problem

  1. update vps to 0.1028
  2. update OMR to 0.59.1
  3.

## Context (Environment)
there just an message OMR and OMR vps seems to be working well

## Specifications

  - OpenMPTCProuter version: 0.59.1
  - OpenMPTCProuter VPS version: 0.1028
  - OpenMPTCProuter VPS provider: milkywan
  - OpenMPTCProuter platform: x86_64
  - Country: france

**Comment by Ysurac** [comment]
Check Status->System log to know why it can't get a token.

**Comment by vinceducat** [comment]
sorry i reinstall from sractch the vps and its ok ...

**Comment by hairy-dog** [comment]
I am seeing the same problem. 

Mon Oct 31 23:31:26 2022 user.notice Shadowsocks: Rules DOWN
Mon Oct 31 23:31:28 2022 user.notice OMR-VPS: Can't get vps token, try later (can ping server vps on 85.x.x.x, no server API answer on 85.x.x.x)

I have tried reinstalling the VPS but without wiping it first. It didn't help.

I think I shall have to try a clean start tomorrow by wiping the VPS and installing from scratch unless there any other things I could try.

**Comment by Ysurac** [comment]
@hairy-dog you should read this issue: https://github.com/Ysurac/openmptcprouter/issues/2605 and if it's not the same open a new issue.

**Comment by hairy-dog** [comment]
A clean install of the VPS fixed the problem. Seems like an upgrade had left something a bit wrong.

**Comment by Fffrank** [comment]
I've had the same issue with an upgrade.  Starting from scratch with a clean VPS install also fixed it.
