### ISSUE TITLE
Can't install new packages on Raspberry Pi 3B+, incompatible with the architectures issue

### ISSUE THREAD

**Issue by fsufyan** [Ysurac/openmptcprouter#2511]
## Expected Behavior
Installing new packages should succeed.

## Current Behavior
This message appears:
![Screenshot 2022-09-04 at 11 26 32](https://user-images.githubusercontent.com/36089616/188306906-019be26e-2bb7-4f20-b63a-8b6cb1f9756d.png)

## Specifications
![Screenshot 2022-09-04 at 11 21 47](https://user-images.githubusercontent.com/36089616/188307027-d72be49d-8173-4a0d-befb-d3384c874666.png)

**Comment by Ysurac** [comment]
I'm not able to reproduce the problem on a RPI4, can you check path in System->Software, "opkg configuration" ?

**Comment by fsufyan** [comment]
This is the opkg configuration:
![Screenshot 2022-09-04 at 16 22 39](https://user-images.githubusercontent.com/36089616/188318399-5dfe503f-b0e2-48f5-9076-ff68b7a3847f.png)

**Comment by Ysurac** [comment]
You are using 64 bits image ?
libc is a base package, can you check the release you have in installed tab ?

**Comment by fsufyan** [comment]
I downoaded the upgrade from this [link](https://download.openmptcprouter.com/release/v0.59.1/rpi3/targets/bcm27xx/bcm2710/openmptcprouter-v0.59.1-5.4-r0+16594-ce92de8c8c-bcm27xx-bcm2710-rpi-3-squashfs-sysupgrade.img.gz).

The other strange issue i have is that there is no installed packages shown on the opkg installed tab:
![Screenshot 2022-09-05 at 00 26 25](https://user-images.githubusercontent.com/36089616/188335779-d500eb3e-8c92-4750-8715-727ff2713251.png)

**Comment by fsufyan** [comment]
This is the architecture when logging in router through terminal
![Screenshot 2022-09-05 at 20 41 02](https://user-images.githubusercontent.com/36089616/188501433-3607d3e0-8c97-4b47-b235-ea07e1a46771.png)

**Comment by fsufyan** [comment]
Flashed the pi without a sysupgrade image and now working, i guess something happened during the upgrade to v0.59.
