### ISSUE TITLE
Some data is missing when uploading data via FTP.

### ISSUE THREAD

**Issue by skmshd** [Ysurac/openmptcprouter#2512]
I created a file with 10000 lines of 0123456789 (file size: 110000byte) and uploaded it via passive FTP to check FTP behavior.
I don't know why but I observed missing data sometimes, and want to know how to fix it.

## Expected Behavior
Of course I expect to upload the file without any issues.

## Current Behavior
However, what I observed was the uploaded file had some missing data almost everytime. There is my test results:
- 1st: 66112byte
- 2nd: 109720byte
- 3rd: 110000byte
- 4th: 101712byte
- 5th: 107504byte

BTW, I used BYPASS option to bypass "fpt_control" and "ftp_data", but it didn't work. If I enabled this, I always see "Data connection timed out." error.

## Specifications

  - OpenMPTCProuter version: v0.58.5 r0
  - OpenMPTCProuter VPS version: 0.1026.5.4.100-mptcp
  - OpenMPTCProuter VPS provider: vultr
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
Update to latest release.
ByPass by service/protocol doesn't always work.

**Comment by skmshd** [comment]
Thanks, sure, I will try the latest version and share result here.

**Comment by skmshd** [comment]
Hi, I have updated to the latest version (v.0.59.1-54) but the same issue exists.. Anything else I can try to fix this?

**Comment by Ysurac** [comment]
Did you try to bypass the FTP server IP ?

**Comment by skmshd** [comment]
Hi Ysurac, thanks for your advice, IP based by-pass worked! Thanks, so I will close this, but one question.

The issue I reported (missing data), is this expected behavior ?
