### ISSUE TITLE
How to enable bonding for UDP traffic (eg. video streaming)

### ISSUE THREAD

**Issue by donnierisk** [Ysurac/openmptcprouter#2519]
## Expected Behavior
We expected that internet speed will be aggregated for streaming a video up, we have 2 4G connections an a fibre. 

## Current Behavior
When fibre is 'enabled' it is used when we upload video, even though one of the others are set as master. Once fibre is disabled, it'll use internet over only one of the links, never sharing the load between them.

So essentially it only ever uses one of the devices' internet. 

## Specifications
  - OpenMPTCRouter version 0.59-5.4
  - OpenMPTCProuter VPS version: v0.1026
  - OpenMPTCProuter VPS provider: AWS?
  - OpenMPTCProuter platform: x86_64
  - Country: South Africa
  - 
Default proxy is shadow socks
Default VPN is glorytun TCP

**Comment by Ysurac** [comment]
You can follow https://github.com/Ysurac/openmptcprouter/wiki/Optimization
Load is not really shared between interfaces, interfaces are used when an interface is already fully used.
