### ISSUE TITLE
Unable to access the Luci web panel of the raspberry router

### ISSUE THREAD

**Issue by bluenor** [Ysurac/openmptcprouter#2526]
**Hello everyone Thank you so much for giving us the opportunity to take advantage of this fantastic project.**

For a while now, although it makes me connect to the internet, I can no longer access the web control panel of my raspberry router at 192.168.100.1 after login i can see only this

![Immagine](https://user-images.githubusercontent.com/20545811/189163951-60431e0d-afb1-4fca-a588-1aa7390a1366.png)

I have tried restarting the router but the problem persists. I don't know how to debug and I don't know how to check the logs to see what's wrong.

**Comment by Ysurac** [comment]
Please complete the template when you open an issue.

Log are available via ssh using "logread".
Did you try another browser or a reboot ?

**Comment by bluenor** [comment]
Yes you are right sorry.

1. Logs are available and i attach the file of log in this reply.
2. I tried another browser and nothing to do sadly.
[tmp.log](https://github.com/Ysurac/openmptcprouter/files/9543018/tmp.log)

thank you.
