### ISSUE TITLE
Incorrect view of one box in the OMR Status(Luci)

### ISSUE THREAD

**Issue by Jacques-F** [Ysurac/openmptcprouter#2528]
## Expected Behavior

In the system / openmptcprouter / status view, all boxes give Name and local IP in the view.
I have 2 boxes (one ADSL and one 4G) and only the 4G box give a correct IP address.

## Current Behavior

In the system / openmptcprouter / status view, my Box has a false local IP.
I have 2 boxes (one ADSL and one 4G) and the first box give as IP address the 2 IP of DNS servers.
This 2 addresses are défined as static routes in the OMR configuration.

## Possible Solution

The name "Livebox (80.10.246.13081.253.149.1) is make with the 1st specific DNS server for Orange network, and whith the 2nd without space.
For sending mails with my postfix server, I must route the DNS query about SMTP to this DNS. If I use public DNS, I receive another IP address. For this, I declare spécific routes for this 2 servers (each server was routed to Livebox address).
## Steps to Reproduce the Problem

  1. Declare one box in the interface
  2. Manage one or more static routes through with address
  3. See the new name of the box in the page

## Specifications

  - OpenMPTCProuter version: 0.58.5 
  - OpenMPTCProuter VPS version: 0.1027 
  - OpenMPTCProuter VPS provider: IONOS
  - OpenMPTCProuter platform: RPI4b 
  - Country: France 

![OpenMPTCProuter-État-LuCI](https://user-images.githubusercontent.com/20790466/189450640-e2c9e6a5-79eb-4dba-9287-5e7f3001d31a.jpg)

**Comment by Ysurac** [comment]
Can you update to latest release ? and if you have still the case I will need the result of "uci show network" and "ifstatus Livebox"

**Comment by Jacques-F** [comment]
Hi,
You can close this bug... It's OK with the 0.59.1
Thanks for this program.

Jacques
