### ISSUE TITLE
VPS server - two aggregations (backup)

### ISSUE THREAD

**Issue by MrDaweb** [Ysurac/openmptcprouter#253]
Hello,

This is not a bug, but a question :)

I just saw this new backup VPS server function. So I ask myself a question: I am currently using two instalaltions with openmptcrouter.

So with two VPS behind, one for each cnnexion.
But technically is it that I could use the servers of one connection as a backup of the other? Or would that pose technical concerns?

**Comment by Ysurac** [comment]
A VPS can't be used by more than one OpenMPTCProuter a the same time for now.
