### ISSUE TITLE
[BUG] [0.59.1] Unable to disable v2ray UDP

### ISSUE THREAD

**Issue by Kalimeiro** [Ysurac/openmptcprouter#2531]
## Expected Behavior
In "System" -> OpenMPTCProuter" -> "Advanced Settings", when disable v2ray UDP and save & apply, it will be really disabled.

## Current Behavior
when disabled v2ray UDP and save & apply, checkbox is selected and v2ray UDP isn't disabled.

## Possible Solution
check typo.

## Specifications
  - OpenMPTCProuter version: 0.59.1
  - OpenMPTCProuter VPS version: 0.1028
  - OpenMPTCProuter VPS provider: OVH
  - OpenMPTCProuter platform: RPI4
  - Country:  FR

![image](https://user-images.githubusercontent.com/8118989/189528179-7c5e53ad-2305-4dc1-a768-68921b9c1544.png)

**Comment by Ysurac** [comment]
There is a typo, this will be fixed in next release.
