### ISSUE TITLE
[BUG] [VPS 0.1028] params.vpn on shorewall not update correctly when changing VPN.

### ISSUE THREAD

**Issue by Kalimeiro** [Ysurac/openmptcprouter#2532]
## Expected Behavior

When change VPN between OMR and VPS on Wizard, the file /etc/shorewall/params.vpn on VPS need to be updated correctly.

## Current Behavior
When change VPN, like Glorytun UDP to Glorytun TCP, the VPS_ADDR var contain the IP of Glorytun UDP (10.255.254.1) instead Glorytun TCP (10.255.255.1) the VPS_IFACE var is define as "gt-udp-tun0" instead "gt-tun0" and the OMR_ADDR var is the only one correct (10.255.255.2)

## Specifications

  - OpenMPTCProuter version: 0.59.1
  - OpenMPTCProuter VPS version: 0.1028
  - OpenMPTCProuter VPS provider: OVH
  - OpenMPTCProuter platform: RPI4
  - Country: FR

![image](https://user-images.githubusercontent.com/8118989/189528453-64d8246f-d9ac-4593-9f60-fff5c88071ef.png)

![image](https://user-images.githubusercontent.com/8118989/189528487-aad04215-fc6b-429a-ba69-e2fbbb1d82ae.png)

**Comment by Ysurac** [comment]
VPS_ADDR and VPS_IFACE are not used, so they are not updated.

**Comment by Kalimeiro** [comment]
Ok you need to delete this var if unused, i close this issue.
