### ISSUE TITLE
[BUG] [0.59.1] multiple pending changes in "System" -> "Recursive DNS"

### ISSUE THREAD

**Issue by Kalimeiro** [Ysurac/openmptcprouter#2533]
See #2454 

## Expected Behavior
when we "save & apply" all parameters on menu "services" -> "recursive DNS", will be really save & apply.

## Current Behavior
When go to menu "services" -> "recursive DNS" and do nothing but just "save & apply", you will see an "unsaved changes : 7" 

uci del unbound.ub_main.iface_lan
uci add_list unbound.ub_main.iface_lan='LAN_PRIVE'
uci add_list unbound.ub_main.iface_lan='LAN_TV'
uci add_list unbound.ub_main.iface_lan='lan'
uci del unbound.ub_main.iface_wan
uci add_list unbound.ub_main.iface_wan='wan1'
uci add_list unbound.ub_main.iface_wan='wan2'

it's repeatable endlessly.

## Specifications

  - OpenMPTCProuter version: 0.59.1
  - OpenMPTCProuter VPS version: 0.1028
  - OpenMPTCProuter VPS provider: OVH
  - OpenMPTCProuter platform: RPI4
  - Country: FR

**Comment by Ysurac** [comment]
Should be already "fixed" for new install, not for update.
