### ISSUE TITLE
[BUG] [0.59.1] unsaved openvpn changes when sysupgrade

### ISSUE THREAD

**Issue by Kalimeiro** [Ysurac/openmptcprouter#2534]
See #2456 

## Expected Behavior
when we "save" in menu "VPN" -> "OPENVPN", will be really save one time.

## Current Behavior
When go to menu "VPN" -> "OPENVPN", juste click on "save" and you'll see an unsaved changes

uci del openvpn.omr.enabled

## Specifications

  - OpenMPTCProuter version: 0.59.1
  - OpenMPTCProuter VPS version: 0.1028
  - OpenMPTCProuter VPS provider: OVH
  - OpenMPTCProuter platform: RPI4
  - Country: FR

**Comment by Ysurac** [comment]
will be fixed in next release
