### ISSUE TITLE
Multiple OMR Single VPS

### ISSUE THREAD

**Issue by ccmks** [Ysurac/openmptcprouter#2536]
Does this configuration supported where there is only 1 VPS, but have multiple OMR on different location trying to connect to same VPS?

Thank you

**Comment by suyuan168** [comment]
Currently not supported, there are development plans in the future. Thanks for supporting OMR.

**Comment by squeaky-geek** [comment]
as of 12-05-2022 this ( if i understand correctly ) does function... just make sure your server ( vps ) has enough bandwith ..

dual OMR clients using the same key and server ip

client 1 >  
                       [ same vps ]  > internet
client 2 >

now what would be cool is if the clients could share resources ( point to multi point VPN )
