### ISSUE TITLE
Failed update to 0.59.1

### ISSUE THREAD

**Issue by islander261** [Ysurac/openmptcprouter#2537]
## Expected Behavior

OMR should work after update to 0.59.1 and 0.1028 on VPS. Updated VPS first from terminal then reboot and then updated OMR from System > Sysupgrade on GUI. Both OMR and VPS rebooted multiple times in attempt to get things working.

## Current Behavior

OMR doesn't connect to VPS.
![Screenshot from 2022-09-12 09-29-59](https://user-images.githubusercontent.com/35109491/189956758-4b57aaac-78d7-43d6-b52d-8d426836fce1.png)

![status_system_log](https://user-images.githubusercontent.com/35109491/189956881-8f5499ac-f9ae-40fc-9eda-d72cc7109a7c.png)
![Screenshot from 2022-09-12 09-35-02](https://user-images.githubusercontent.com/35109491/189957051-badf2232-1c72-450c-a007-604f7325e5b5.png)

![Screenshot from 2022-09-13 09-22-21](https://user-images.githubusercontent.com/35109491/189957115-16dd4da1-3cdc-482d-8e95-76e595586926.png)

## Specifications

  - OpenMPTCProuter version: 0.59.1-5.4
  - OpenMPTCProuter VPS version: Can't tell OMR and VPS report different versions
  - OpenMPTCProuter VPS provider:Vultr
  - OpenMPTCProuter platform: RPI4

**Comment by Ysurac** [comment]
VPS release is the one displayed on VPS, the router get the version from the API, it can't connect to API, so...
Check that server API key defined in the wizard is the same in ```/etc/openmptcprouter-vps-admin/omr-admin-config.json```, "openmptcprouter" section as "user_password".

**Comment by islander261** [comment]
Ok, key reported on VPS in root@lopezcloud:~# openmptcprouter_config.txt (the one I have set in OMR) is not the same as the one in root@lopezcloud:/etc/openmptcprouter-vps-admin/omr-admin-config.json. Which one should I change? TIA

**Comment by Ysurac** [comment]
The key in the json is the only one read by the API, the txt is only for information.
Both key should be same, but maybe an error somewhere...

**Comment by islander261** [comment]
Thank you, all is working correctly now when using correct key.

**Comment by Ysurac** [comment]
ok, now I need to be able to reproduce this issue to solve it...
