### ISSUE TITLE
Two server is possible ?

### ISSUE THREAD

**Issue by Roken120** [Ysurac/openmptcprouter#254]
Is possible to use two vps server ?

**Comment by Ysurac** [comment]
Yes since latest version.
If a server is set as "backup" then it will be used only if the other server is down.
If no server is set as "backup" then round-robin will be used (can be fun but not sure if it's really usable).

**Comment by Roken120** [comment]
Ok thank and i cave one question 
La possible to use alias ip for one machine in m'y network 
In french
Et il possible de rajouter le support d'ip additionnelles pour le dédié à une machine dans le réseaux ?

**Comment by Ysurac** [comment]
Tout est toujours possible mais ça sort un peu des attributions d'OpenMPTCProuter.
En redirigeant les ports pour l'IP en questions vers OMR puis d'OMR vers la machine il n'y a de raison, mais c'est pas top. Sinon faut faire un VPN entre la machine et le VPS directement.

**Comment by Roken120** [comment]
Car j'aimerai faire de l'auto hébergement en gros acheter un serveur dédié avec IP additionnel et après relier une ip à une machine sans qu'il a de réseaux local si tu voit un peu ce que je veut dire.
