### ISSUE TITLE
Atheros AR7xxx/AR9xxx  build  netfilter2  error

### ISSUE THREAD

**Issue by kapook007** [Ysurac/openmptcprouter#255]
scripts/Makefile.build:328: recipe for target '/tmp/openwrt-master/build_dir/target-mips_24kc_musl/linux-ar71xx_generic/ndpi-netfilter2-a360566/ndpinetfilter/src/../../src/lib/protocols/fiesta.o' failed

This problem is only Atheros AR7xxx/AR9xxx  cpu.

openmptcp v0.44
openwrt 4.14.82

**Comment by Ysurac** [comment]
The arch doesn't support some value/function used by nDPI, this would need some patches. But for now AR7xxxx and AR9xxx are not supported arch so it's not high priority on todo list ;)
