### ISSUE TITLE
Only http/https traffic going through OMR on wrt3200acn

### ISSUE THREAD

**Issue by Sparhawk76** [Ysurac/openmptcprouter#2557]
I installed OMR on my wrt3200acn, and was able to set up connection to my VPS, and it successfully routes http/https traffic, speedtest.net results showed it uses both connections, but any other traffic just gets dropped. Ping, SSH (to my VPS), and IRC all don't work from my laptop. If I ssh into OMR, I can run ping and ssh to outside hosts properly from the router.

**Comment by Ysurac** [comment]
Check System->OpenMPTCProuter, status page. I think you have an issue with VPN part that is used by default for any traffic that is not TCP.
