### ISSUE TITLE
New 5G Modem RM520N-GL

### ISSUE THREAD

**Issue by psfabio** [Ysurac/openmptcprouter#2559]
Hi, i´m been using a LTE Cat 12 Modem (Quectel Em12-G) with OpenMPTCProuter, in qmi mode, and everything works fine.

Recently i bought a new 5G modem (Quectel RM-520N-GL), but both drivers/net/usb/qmi_wwan.c and drivers/usb/serial/option.c aren´t prepared for this new modem.

I fond on the internet two patches for this drivers:
https://lore.kernel.org/linux-usb/tencent_23054B863154DC02C6E98E5942416BFC200A@qq.com/
https://lore.kernel.org/linux-usb/tencent_E50CA8A206904897C2D20DDAE90731183C05@qq.com/

But i don´t know how to patch them on OpenMPTCProuter installation. I even don´t know if it is a difficult task.

If someone could give me a direction.. is it necessary compile all installation again? or is it possible to make a module or something?

Thanks a lot.

**Comment by psfabio** [comment]
wow. that was fast..
Thank you so much.

**Comment by Ysurac** [comment]
Images are available here: https://snapshots.openmptcprouter.com/

**Comment by eirdgms** [comment]
Recently i bought a new 5G modem (Quectel RM-500U), but both drivers/net/usb/qmi_wwan.c and drivers/usb/serial/option.c aren´t prepared for this new modem.
