### ISSUE TITLE
Dynamic master interrupts connection on switch ?

### ISSUE THREAD

**Issue by ByteArrayException** [Ysurac/openmptcprouter#2566]
## Expected Behavior
The dynamic change works flawlessly without dropouts.

## Current Behavior
When changing the master, all connections are briefly disconnected and reconnected.

## Specifications

  - OpenMPTCProuter version: v0.58.5
  - OpenMPTCProuter VPS version: v0.1026
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
Use "Balancing mode", this work better than "dynamic change".

**Comment by ByteArrayException** [comment]
Thanks for the quick reply! :)
I have the feeling that with the "Balancing" mode the entire connection drops briefly when the master statically defined in the config has no more connection, or is that not so?

**Comment by ccmks** [comment]
I also noticed that if I am on Balancing mode, if the master connection is down, it the OMR will not have internet for short moment.

How long does it take the transition when master is failing?

**Comment by Ysurac** [comment]
This shouldn't be the case but this can happen. It's often the VPN that is failing. You can check in Status->System log.
