### ISSUE TITLE
VPS pool

### ISSUE THREAD

**Issue by mycanaletto** [Ysurac/openmptcprouter#257]
Hello,
Do you think it will be possible to "pool" the VPS side to allow several MPTCP routers to use it for outgoing frafic? What happens if you use keys on multiple routers?

**Comment by Ysurac** [comment]
no. It will not work. Multiple client on VPS will be supported, but not for now.

**Comment by mycanaletto** [comment]
Merci pour l’info et bravo pour le projet 😊

https://www.canaletto.fr/post/mptcp-vs-dual-wan

**Comment by mycanaletto** [comment]
Bonjour Yannick,

Avec deux VDSL, j’ai toujours le up qui s’effondre rapidement (le VPS est dans une VM dans un datacenter avec 1 Gbit/s)

Une idée ?

Merci, lionel


[cid:image001.png@01D49D68.80738140]

**Comment by mycanaletto** [comment]
Bonjour,
Comment générer de nouvelles clés sur le VPS ? (mon idée étant de dupliquer la VM du VPS en changeant son IP publique plutôt que de la recréer...).
