### ISSUE TITLE
MPTCP-next vs MPTCP

### ISSUE THREAD

**Issue by ByteArrayException** [Ysurac/openmptcprouter#2571]
Hi!
What is the basic advantage of the MPTCP-next kernel over the "traditional" one? Is this some kind of further development (performance or similar) because the old one will be discontinued soon?

**Comment by Ysurac** [comment]
Better info than I would say: https://github.com/multipath-tcp/mptcp_net-next/wiki
So, for now MPTCP-next, used in 5.15 based release of OpenMPTCProuter, have, in OpenMPTCProuter, less features than the 5.4 based release. Only Fullmesh MPTCP scheduler is available. For performances, this need more tests.
