### ISSUE TITLE
Is Banana Pi M2 Plus supported?

### ISSUE THREAD

**Issue by mahdiyari** [Ysurac/openmptcprouter#2575]
This board has 1Gbit ethernet and is very cheap compared to raspberry pi (5-6 times cheaper where I am). Can I buy and use it as my OMR?
I didn't see any mentions about this board on here so hence the issue.
I never had a router nor installed one. Complete newbie here.

I did find this on OpenWrt https://openwrt.org/toh/sinovoip/banana_pi_m2_plus

I really appreciate what you do here. Great job.

Update:
As an alternative Firefly RK3328-CC board is also available.

**Comment by Ysurac** [comment]
I only support hardware that I own.
I can buy them but I'm not sure CPU of these boards have speed of a RPI4, I would need to find a hardware tests.
Actually x86_64 based board can be cheaper than a RPI4 (and far better).

**Comment by mahdiyari** [comment]
I can buy and test the BPI-M2+
Can I install OMR myself on them?

**Comment by mahdiyari** [comment]
Excuse my ignorance. I didn't understand what you meant by x86_64 boards at first. I will look for those. If I understand correctly the non-arm cpus like intel etc.

**Comment by mahdiyari** [comment]
Will this work? https://support.hp.com/us-en/document/c04356040
Or I need to AIM for a minimum CPU speed/core
