### ISSUE TITLE
No Wireless AP option

### ISSUE THREAD

**Issue by squeaky-geek** [Ysurac/openmptcprouter#2576]
please see link, and image. this is on a pc engines APU3c4 ( APU4c4 ) with a sierra wireless mc7750, a quectel ep06-a and a Compex WLE600VX wifi card, there does not seem to be an option in the web gui to setup a wifi network OR connect to a wifi network as a wan bonding channel...  thanks for reading.
![no_wifi](https://user-images.githubusercontent.com/65478629/192180738-0446fd8c-f498-4e8e-8c21-221e2c16c696.JPG)
this is the link:
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiv_vPssbH6AhWXg2oFHbCWDX8QFnoECBMQAQ&url=https%3A%2F%2Fgithub.com%2FYsurac%2Fopenmptcprouter%2Fwiki%2FConfigure-Wifi&usg=AOvVaw2QUsD1CYOUuf3vdd5W_mUl  however this article mentions the pi4

edit: the quectel is not detected , figure ill ask if it is supported  google has provided no answer for that model.  thanks again.

**Comment by vinceducat** [comment]
can u use the template please
