### ISSUE TITLE
Network Status shows both WANs down (ICMP Failing?), but, I can route traffic successfully to Internet

### ISSUE THREAD

**Issue by yamasaki760** [Ysurac/openmptcprouter#2578]
## Expected Behavior

In the Server Setup Wizard, after I enter my 2 WANs (LTE Modems) configuration information and my VPS Server Configuration Information, I expect all status to be GREEN in the Network Status section that shows if everything is up and running correctly.  OMR appears to be working (I think), as, I can connect to and navigate to sites on the Internet while connected to OMR BR-LAN network.

## Current Behavior

Right now, in Network Status, it shows both of my WANs are listed as DOWN on the Network Status page.  I believe this is because ICMP is not able to communicate between OMR router and the WAN IP addresses.  

  - WAN1 IP address of Local OMR Interface: 192.168.101.2
  - WAN1 IP address on LTE Modem Interface: 192.168.101.1
  - WAN2 IP address of Local OMR Interface: 192.168.103.2
  - WAN2 IP address on LTE Modem Interface: 192.168.103.1

### From OMR Terminal:

- I **CAN** ping my VPS Server on AWS:
`root@OpenMPTCProuter:~# ping 52.90.105.59
PING 52.90.105.59 (52.90.105.59) 56(84) bytes of data.
64 bytes from 52.90.105.59: icmp_seq=1 ttl=62 time=77.3 ms
64 bytes from 52.90.105.59: icmp_seq=2 ttl=62 time=102 ms
64 bytes from 52.90.105.59: icmp_seq=3 ttl=62 time=71.1 ms
64 bytes from 52.90.105.59: icmp_seq=4 ttl=62 time=72.8 ms`

- I **CANNOT** ping WAN1 IP gateway address:
`root@OpenMPTCProuter:~# ping 192.168.101.1
PING 192.168.101.1 (192.168.101.1) 56(84) bytes of data.
From 192.168.101.2 icmp_seq=1 Destination Host Unreachable
From 192.168.101.2 icmp_seq=2 Destination Host Unreachable
From 192.168.101.2 icmp_seq=3 Destination Host Unreachable
From 192.168.101.2 icmp_seq=4 Destination Host Unreachable
From 192.168.101.2 icmp_seq=5 Destination Host Unreachable
^C
--- 192.168.101.1 ping statistics ---
6 packets transmitted, 0 received, +5 errors, 100% packet loss, time 5084ms`

- I **CANNOT** ping WAN2 IP gateway address:
`root@OpenMPTCProuter:~# ping 192.168.103.1
PING 192.168.103.1 (192.168.103.1) 56(84) bytes of data.
From 192.168.103.2 icmp_seq=1 Destination Host Unreachable
From 192.168.103.2 icmp_seq=2 Destination Host Unreachable
From 192.168.103.2 icmp_seq=3 Destination Host Unreachable
From 192.168.103.2 icmp_seq=4 Destination Host Unreachable
From 192.168.103.2 icmp_seq=5 Destination Host Unreachable
From 192.168.103.2 icmp_seq=6 Destination Host Unreachable
^C
--- 192.168.103.1 ping statistics ---
6 packets transmitted, 0 received, +6 errors, 100% packet loss, time 5134ms`

  - OMR Network Status Error Messages For WAN1 and WAN2:

`Gateway DOWN
No Server ping response after 1 second
Bridge can't have multipath enabled
`

## Specifications

  - OpenMPTCProuter version: v0.59.1-5.4 r0+16594-ce92de8c8c
  - OpenMPTCProuter VPS version: 5.4.207-mptcp 0.1028
  - OpenMPTCProuter VPS provider: aws
  - OpenMPTCProuter platform: Linksys WRT3200ACM AC3200

**Comment by Ysurac** [comment]
The gateway down is only a warning, this break nothing if gateway doesn't answer to ping. But, with default settings, VPS must be pingable from WANs, ```ping -B -I wan1 <vpsip>```, else you need to modify Services->OMR-Tracker to use another method than ping.
Also, as indicated, bridge can't have multipath enabled.

**Comment by yamasaki760** [comment]
Thank you for the quick reply!  I wasnt sure if that ping test was going to mess anything else up.  

I switched my interfaces from BRIDGE to NORMAL and my speeds doubled. 

Thank you again for all you do for us.  This is a great project!!
