### ISSUE TITLE
Vultr VPS with ring Cameras

### ISSUE THREAD

**Issue by dooley1981** [Ysurac/openmptcprouter#2581]
Have anybody use Vultr VPS with ring cameras? It will work if my phone is not connected to Wi-Fi and away from home. When i'm home on the same Wi-Fi network as ring cameras, it can't connect.

**Comment by iambenmitchell** [comment]
I had this problem. It ended up solving itself after an hour. I think the camera has to open some ports

**Comment by winkmichael** [comment]
Make sure UPNP support is enabled.
