### ISSUE TITLE
Banana Pi BPI not save the modified configuration?

### ISSUE THREAD

**Issue by BBGScc** [Ysurac/openmptcprouter#2585]
there is a problem saving the changes I made to the configuration of the system. But, after restarting, the saved configuration is lost even though the system indicates it was saved.

**Comment by Ysurac** [comment]
Try to update to latest release.

**Comment by BBGScc** [comment]
ok,Thanks.
You are my hero






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Ysurac/openmptcprouter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月1日(星期六) 凌晨2:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Ysurac/openmptcprouter] Why does the Banana Pi BPI-R64 system start, but not save the modified configuration? (Issue #2585)





 
Try to update to latest release.

**Comment by BBGScc** [comment]
Ysurac，Can&nbsp;I add you a WeChat？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Ysurac/openmptcprouter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月1日(星期六) 凌晨2:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Ysurac/openmptcprouter] Why does the Banana Pi BPI-R64 system start, but not save the modified configuration? (Issue #2585)





 
Try to update to latest release.
