### ISSUE TITLE
Belkin RT3200/Linksys E8450 WIFI6 router support

### ISSUE THREAD

**Issue by himekifee** [Ysurac/openmptcprouter#2597]
The board has had official OpenWRT release support since 22.03.0. As it uses the same SoC as `bananapi-r64`, I tried to compile with the same config and kernel 5.15, and it turned out to be partially working. By partially working, I mean it all works well except the MPTCP part. I saw some comments and am now thinking it could be the embedded MPTCP scheduler is not capable enough. I can help with testing and debugging if you would like to support the device.

**Comment by Ysurac** [comment]
I don't understand what you mean.
5.15 based releases use in-kernel MPTCP and need VPS 5.15 script.
You can check on router part if MPTCP work using "multipath" command or "ip mptcp endpoint"

**Comment by jakiejj** [comment]
I was able to build and install OMR by adding this config: https://github.com/jakiejj/openmptcprouter/blob/456f049cb87975a70d4205a289917070cfe5eb85/config-e8450

However the router does not recognize any wan (tried ether port and usb tether). Also couldn't get any ip assign on wifi connections.

How should I test the build formally? I am pretty new to this, but I'm will to spend some time to make this router work if somebody can spend some guidance. 
thanks!

**Comment by factoidforrest** [comment]
@jakiejj Did you ever get anywhere with this router? The thing is super common as kind of the go-to cheap and powerful openwrt router. I've got one. 

@himekifee do you mind sharing your build config? seems like maybe you got a little further along, as you actually had a successful build, minus MPTCP.

I'm trying to compile at the moment.

**Comment by jakiejj** [comment]
@factoidforrest no time to dig more all by myself, and using regular openwrt now...

**Comment by himekifee** [comment]
Unfortunately, it was not in my interest anymore, so I deleted all files related to that. Good luck with it

**Comment by factoidforrest** [comment]
Welp, I got it to build but upon flashing, the router doesn't seem to be doing DHCP or any of its routerly duties so I think it's broken somehow. Is there any way to make the build use a certain version of openwrt? Is it possible to build with [23.05.3](https://openwrt.org/releases/23.05.3)

**Comment by jakiejj** [comment]
btw, beware of rt3200 OKD. iirc, the trunk is not safe.

**Comment by factoidforrest** [comment]
Yeah, I saw that note in the wiki, thank you. 23.05 _is_ safe, though. Been running it for years. I definitely don't want to build against latest openwrt. I am hoping @Ysurac can fill me in if it's possible to build against an older version of OpenWRT like that with the MPTCP build system. I haven't tracked down the part where it chooses what openwrt branch to pull but maybe I can find it in there myself and change it. 

I've at least got the kernel right (5.15) but not the OpenWRT version.  

This is kind of a funny router, it's both pretty popular because it's quite cheap and fast, and also a somewhat troubled device when it comes to OpenWRT

**Comment by Ysurac** [comment]
6.6 is build on fixed commit on OpenWRT main branch.
Kernel 5.15 is not supported anymore (too missing part for MPTCP)

**Comment by factoidforrest** [comment]
Oh, i see! Thanks @Ysurac! Well, looks like that ends the dream of building for this router, no fault of the project. I'll upgrade to a supported device before I try to bond my two LTE connections. Thanks!

**Comment by jakiejj** [comment]
@factoidforrest have you tried with kernel 6+?

**Comment by factoidforrest** [comment]
No, I didn't try. I figured running 6.1 on this router was a bad idea given that a lot of people seem to be warning against it, in general

**Comment by jakiejj** [comment]
The regular openwrt build with kernel 6 works fine for me though. as long as one doesn't use ubi2 which kinda correlates the OKD. Do you mind referencing those warnings?
