### ISSUE TITLE
Shadowsocks is not running (empty key) and Can't connect with server, on RPI 4 

### ISSUE THREAD

**Issue by atyouspace** [Ysurac/openmptcprouter#2605]
I get an error like the capture. What should I do?
![image](https://user-images.githubusercontent.com/4992828/194982171-7a2e1cbb-e0f1-49e8-8a5a-25f53aa654f1.png)

I check that VPS admin key is good, that VPS was rebooted and I check State->System log.
![image](https://user-images.githubusercontent.com/4992828/194982778-15914190-5a8b-44da-8624-05693c106d10.png)

**Comment by Ysurac** [comment]
Please use the template when you open an issue.

Check that you rebooted the VPS after install, if yes check the result of ```systemctl start omr-admin``` on the VPS.

**Comment by atyouspace** [comment]
> 
I reboot VPS, and check the results of `systemctl start omr-admin`, as followed,

root@iZ2zedyc2xu82zjw70o2s5Z:~# systemctl start omr-admin
Job for omr-admin.service failed because the control process exited with error code.
See "systemctl status omr-admin.service" and "journalctl -xe" for details.

**Comment by Ysurac** [comment]
```pip3 install starlette```

**Comment by Ysurac** [comment]
try ```pip3 install fastapi```

**Comment by atyouspace** [comment]
> 

Its done. Why we need install fastapi?

**Comment by Ysurac** [comment]
Because VPS API use FastAPI

**Comment by hairy-dog** [comment]
I had this problem and wiing the vps then reistalling it fixed the problem.
