### ISSUE TITLE
Сompatible wifi devices with openmptcprouter, real test.

### ISSUE THREAD

**Issue by Silvanskii** [Ysurac/openmptcprouter#2607]
**I checked several WIFI devices for OS compatibility. If you have any questions or test suggestions I can help.** 
**Here are my results:**
1 MT7601 - doesn’t work
2 RTL8812 - doesn’t work
3 RTL8811 - doesn’t work
4 AR9271 - work as client 2.4Ghz, ap doesn’t work
5 usb3.0 RTL8812BU - doesn’t work
6 usb3.0 MT7612U - work as client 5Ghz , ap doesn’t work(sometimes work after install driver, but not stable)
7 MT7610U - after install driver work as client 2.4 and 5Ghz, ap work  2.4 GHz, 5Ghz doesn’t work
8 RT3572 - work
9 RTL8192CU - work only as client 2.4Ghz
10 RT5572 - work, sometimes bag
11 usb3.0 RTL8812AU/RTL8812BU - doesn’t work

I bought devices based on the OpenWRT compatibility table. As you can see a lot of devices work. Don't make these mistakes
https://github.com/morrownr/USB-WiFi/blob/main/home/USB_WiFi_Chipsets.md

**Comment by BBGScc** [comment]
RTL8821CE - doesn’t work
