### ISSUE TITLE
IPv4 address not assigned when connected with AP

### ISSUE THREAD

**Issue by atyouspace** [Ysurac/openmptcprouter#2609]
## Expected Behavior
IPv4 address is assigned.

## Current Behavior
My Openmptcprouter board has connected with ap router, however, no IPv4 address is assigned.

wlan0 Link encap:Ethernet HWaddr 34:82:4A:0B:B7:D8
inet6 addr: fe80::3682:4aff:fe0b:b7d8/64 Scope:Link
UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
RX packets:487 errors:0 dropped:0 overruns:0 frame:0
TX packets:37 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:1000
RX bytes:121090 (118.2 KiB) TX bytes:4587 (4.4 KiB)

In addition, I connect my PC with my Openmptcprouter board directly using a network cable, however, no IPv4 address is assigned to my PC.

eth1 Link encap:Ethernet HWaddr 00:A0:C9:00:00:02
inet6 addr: fe80::2a0:c9ff:fe00:2/64 Scope:Link
UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
RX packets:154 errors:0 dropped:0 overruns:0 frame:0
TX packets:576 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:1000
RX bytes:49588 (48.4 KiB) TX bytes:195424 (190.8 KiB)
Memory:1100000-117ffff

I check service,

/etc/init.d/dnsmasq enabled running
/etc/init.d/odhcpd enabled running

## Specifications

  - OpenMPTCProuter version: 0.59

**Comment by Ysurac** [comment]
For the AP, you mean getting IP from the router ? In this case the interface on OpenMPTCProuter must be set as DHCP client. If it's to provide a WAN in never a good idea to use WIFI due to the unstable latency.
To get IP for your client PC, check that the interface on OpenMPTCProuter is set as DHCP server in Network->Interface.
