### ISSUE TITLE
Upgrade from 0.58.2 to 0.59.1 fail on pi3

### ISSUE THREAD

**Issue by delferius** [Ysurac/openmptcprouter#2613]
## Expected Behavior

Upgrade sucess
## Current Behavior

Openmptcp ext4 file system corrupted on restart.
Configuration backup import on fresh 0.59.1 install fail too

## Context (Environment)
PI3b+ and openmptcp 0.58.2

**Comment by Ysurac** [comment]
The ext4 corrupted is not related to the update, but to a power shutdown, a bad SD card,...
Configuration import should work, what is the error ?
