### ISSUE TITLE
Getting signal info and cell info from RUTX12

### ISSUE THREAD

**Issue by highfreq** [Ysurac/openmptcprouter#2626]
Anybody knows how i can get signal and carrier infos from the 2 modems inside the RUTX12?

**Comment by highfreq** [comment]
If i use:  uqmi -d /dev/cdc-wdm0 --get-signal-info i get the info i need but the signal and other info disappear from the MPTCP web page system->openmptcprouter->status. Any other way to do it?

**Comment by Ysurac** [comment]
By default ModemManager is used, so it's available with ```mmcli```

**Comment by marccolemont** [comment]
Highfreq, did you get it to work? Have the same unit, configured SIMs with ModemManager, but it doesn't work here.

**Comment by highfreq** [comment]
Yes, it works perfect. Didn't have to configure anything with modemmanager. What doesn't work on yours?

**Comment by highfreq** [comment]
> By default ModemManager is used, so it's available with `mmcli`

Thanks, it worked!!!
