### ISSUE TITLE
Linksys WRT32X - Firmware upload failed

### ISSUE THREAD

**Issue by n4sty3us** [Ysurac/openmptcprouter#2629]
## Expected Behavior
Hello, I've Linksys WRT32X (with the latest OEM firmware - before the current firmware, previous router’s owner have installed DD-WRT) on which I want to install the firmware OpenMPTCProuter. I downloaded the latest version available for my router from the website: openmptcprouter-v0.59.1-5.4-r0+16594-ce92de8c8c-mvebu-cortexa9-linksys_wrt32x-squashfs-factory.img

## Current Behavior
When uploading the image, I get the following error: Firmware upload failed

![Immagine 2022-10-29 151216](https://user-images.githubusercontent.com/116958606/198834312-e2f172cf-001d-4543-a6d2-a84d5064a8b6.png)

If I try to install the latest version of OpenWRT (openwrt-22.03.2-mvebu-cortexa9-linksys_wrt32x-squashfs-factory.img), I don't have any problems.
Could I have information on how to solve the problem? Thank you!!!

## Specifications

  - OpenMPTCProuter version: v0.59.1-5.4
  - OpenMPTCProuter platform: Linksys WRT32X

**Comment by Ysurac** [comment]
You can try to update from OpenWRT (without keeping settings).
As firmware upload failed, this may be because there is not enough free space.

**Comment by n4sty3us** [comment]
@Ysurac thank you so much for the support!!! If I understand correctly, I update the OEM firmware with OpenWRT. After I update the OpenWRT firmware with the OpenMPTCProuter firmware ... is it correct?

I have two questions for you:
- To switch from OpenWRT to OpenMPTCProuter can be done from GUI or command line?
- Which image should I use? (openmptcprouter-v0.59.1-5.4-r0+16594-ce92de8c8c-mvebu-cortexa9-linksys_wrt32x-squashfs-factory.img or openmptcprouter-v0.59.1-5.4-r0+16594-ce92de8c8c-mvebu-cortexa9-linksys_wrt32x-squashfs-sysupgrade.bin)

Thanks
