### ISSUE TITLE
Provide minicom package

### ISSUE THREAD

**Issue by NKnusperer** [Ysurac/openmptcprouter#2634]
**Is your feature request related to a problem? Please describe.**
Most LTE modem cards support AT commands to communicate directly with the device for low-level configuration via an exposed serial port (`/dev/ttyUSB*`). To my knowledge OMR currently does not provide any terminal emulator to communicate with such an interface except using `socat` or plain `echo` which is not really a nice experience for humans.

**Describe the solution you'd like**
Include minicom with the base OMR distribution or as an optional package to install.
https://openwrt.org/packages/pkgdata/minicom

**Comment by Ysurac** [comment]
minicom is already available to install via System->Software.

**Comment by NKnusperer** [comment]
True, I did not updated the software list first.
