### ISSUE TITLE
OpenVPN server behind OpenMPTCProuter not accessible

### ISSUE THREAD

**Issue by FelR** [Ysurac/openmptcprouter#2637]
## Expected Behavior
An opnSense firewall is running behind the OpenMPTC router, which also serves as a VPN server for mobile users and site-2-site connections.

Both outgoing OpenVPN connections and incoming connections should be able to pass through the tunnel transparently.

## Current Behavior
Currently, only outgoing connections where the server acts as an OpenVPN client work. Incoming connections are not forwarded to the server. 

UDP based OpenVPN is used. A network capture does not show any relevant packets on the LAN side of the OpenMPTC router. The configuration files on the VPS appear to be correct. Both the "Redirect all ports from VPS to OpenMPTCProuter" setting and forwarding the specific port have been tested. Port forwarding in general is set correctly, other forwards (e.g. TCP/80 or TCP/443) work without problems.

## Specifications

  - OpenMPTCProuter version: 0.59.1-5.4
  - OpenMPTCProuter VPS version: 0.1028 5.4.207-mptcp
  - OpenMPTCProuter VPS provider: netcup (Germany)
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
Check shorewall configuration on VPS, and try a tcpdump on VPS to check if there is incoming traffic.
