### ISSUE TITLE
Netflix login not working (incorrect password)

### ISSUE THREAD

**Issue by NKnusperer** [Ysurac/openmptcprouter#2640]
## Expected Behavior
I should be able to use Netflix using the following OMR-Bypass:
`Protocols and services` -> `netflix`.

## Current Behavior
When trying to login it fails with `Incorrect password`.
Switching the network connection from OMR to my current router the login works fine.
Did someone observed this behavior too or has a working installation and can share the required OMR-Bypass rules?

### Update
Looks like this is only happening when IPv6 is enabled.
This has already been observed in #2215.
So the real question is: What is the right way to implement this in a dual-stack environment?
I guess we have to create two interfaces on the same network, one with DHCP and another one with DHCPv6.
Then create a second OMR-Bypass rule for the IPv6  interface.
Is this right?
Also, is OMR aware that they both share the same underlying internet uplink or will this cause some other trouble because now I'm "stacking" a bonded connection?

Another question: what will happen if the interface for OMR-Bypass goes down?
Will it fallback to the VPS (undesirable) are can we configure this in a way that another direkt connection is used (eg. LTE)?

## Specifications

  - OpenMPTCProuter version: 0.59.1-5.4
  - OpenMPTCProuter VPS version: 0.1028 5.4.207-mptcp
  - OpenMPTCProuter VPS provider: Hetzner
  - OpenMPTCProuter platform: RPI4

**Comment by Ysurac** [comment]
I don't really understand what you mean. Can you put a screenshot of status page ?
