### ISSUE TITLE
Impossible de contacter le script administrateur (no token yet available)

### ISSUE THREAD

**Issue by Copinmalin** [Ysurac/openmptcprouter#2642]
## Expected Behavior

Everything seems working, but I have this issue on VPS view : 

Impossible de contacter le script d'administration du serveur (no token yet available)
![image](https://user-images.githubusercontent.com/4174888/200162728-b8b6930a-6786-4625-99d7-94fa7187ee49.png)

## Current Behavior

System log :  

`OMR-VPS: Can't get vps token, try later (can ping server vps on 51.xxx, server API answer on 51.xxx)`

API Key exist in VPS config

## Specifications

  - OpenMPTCProuter version:  0.59.1-5.4
  - OpenMPTCProuter VPS version:  0.1028
  - OpenMPTCProuter VPS provider: OVH
  - OpenMPTCProuter platform: Raspberry Pi 4 Model B Rev 1.4

**Comment by Ysurac** [comment]
Check that you set correctly API key and that it is the same in /etc/openmptcprouter-vps-admin/omr-admin-config.json

**Comment by Copinmalin** [comment]
Many thanks @Ysurac , you are a boss 

server key was configured with API keys !
