### ISSUE TITLE
Notifications when a line goes down

### ISSUE THREAD

**Issue by iambenmitchell** [Ysurac/openmptcprouter#2645]
**Is your feature request related to a problem? Please describe.**

Sometimes one of my connections will go down and the ISP router will need rebooting. But I don't find out until I notice the connection is slow
**Describe the solution you'd like**

I would like the ability to be notified via email or something similar when a connection goes down. 
**Describe alternatives you've considered**

I've thought about running a speed test on a device even 5 minutes but this is inefficient 
**Additional context**

**Comment by Ysurac** [comment]
It's in Services->OMR-Tracker, "Mail alert" checkbox. Mail configuration is in Services->E-mail.

**Comment by JRTechServices** [comment]
I am having an issue receiving the mail alert for ISP failure. I am testing by unplugging eth and shutting down vps.    

smtp.mailserver.com
587
Check Box checked TLS
Check Box checked STARTTLS
username redacted@domain.com 
password redacted 
From redacted@domain.com 
To redacted
To 

Mail alert Check box checked. Under Default Settings & Under ORMVPN 

Latest version of OMR, Let me know how I can help.
