### ISSUE TITLE
Zoom app problem

### ISSUE THREAD

**Issue by mvmaksnet** [Ysurac/openmptcprouter#2647]
I tried use openmptcp with zoom app, but there are some problems , it looks like connection is changing constantly (I can see zoom stats on other side pc which is also on zoom). Streaming with vmix and obs is ok and it bonds connections very good, but zoom have problem.

I saw this in sys log but dont know what is problem...
mptcp_init4_subsockets: token 0xc8fafd5e bind() to 10.255.254.2 index 24 failed, error -99

  - OpenMPTCProuter version: 0.59.1
  - OpenMPTCProuter VPS version: 0.1028
  - OpenMPTCProuter VPS provider: Maksnet
  - OpenMPTCProuter platform: raspberry pi 3 b+

**Comment by Ysurac** [comment]
Please use template when you open an issue.

What is the VPN used ?

**Comment by mvmaksnet** [comment]
Glorytun tcp

**Comment by Ysurac** [comment]
"10.255.254.2" in log is Glorytun UDP, did you try with it ?
Do you have same problem if you use omr-bypass to bypass zoom connection ?
