### ISSUE TITLE
OMR Bypass via ASN

### ISSUE THREAD

**Issue by max4186** [Ysurac/openmptcprouter#265]
Suggestion:

Currently OMR Bypass supports Domains, IP's, MAC, Protocols and Source IP addresses - it'd be nice if you could create a bypass for all IP addresses under a specific network ASN so you wouldn't need to go through adding specific ranges for a company for example.

Best way of doing it in my opinion would be to mass search a WHOIS DB once an ASN has been added and keep it locally stored in a list, rescanning at a time period set (for example 24 hours) to remove or add new IP's under the ASN - this would prevent the need to constantly query a DB and keep load times low.

**Comment by Ysurac** [comment]
Done in latest version, for now this is only updated when omr-bypass is restarted. I will change that in a next version.

**Comment by ThibautBascoulergue** [comment]
What should we put in the field of ASN, Netflix or the corresponding ASN number?

**Comment by max4186** [comment]
Works fantastically, good work Ysurac!

For the more stupid of us, you might want to add a note to not add AS infront of the number as (unless it supports having AS, I don't know).

**Comment by Ysurac** [comment]
Update via cron will be added in next release. Added in develop branch.
