### ISSUE TITLE
Intel I225-V ETH controller issue

### ISSUE THREAD

**Issue by iz2qcp** [Ysurac/openmptcprouter#2655]
I have a problem with some PCs that have INTEL I225-V Ethernet Controller. DHCP client does not work on any network card. network cards keep shutting down in a loop.

I was unable to fix the issue.

**Comment by Network-Traditions** [comment]
Take a look at #2584.

**Comment by khdegraaf** [comment]
I believe the ultimate cause of this issue is outlined in https://github.com/Ysurac/openmptcprouter/issues/3005. I found a fix/work-around for anyone interested in this. This hardware does work properly in OpenWrt 21.02.07 with Linux kernel 5.4.238 and is stable even when using dhcp there.
