### ISSUE TITLE
cznic_turris-omnia-initramfs-kernel.bin

### ISSUE THREAD

**Issue by MTSmhas** [Ysurac/openmptcprouter#2657]
**Is this request related to a missing driver support for a particular hardware platform, SoC or board? Please describe.**

**Describe why you are asking for this support?**

**Additional context**

Hi can you Build a Image for this device -> https://openwrt.org/toh/turris/turris_omnia
or a description of how to install it on openwrt. 

Thanks

**Comment by Ysurac** [comment]
You can build it yourself: https://github.com/Ysurac/openmptcprouter/wiki/Create-image-for-unsupported-platform
(I only support officially platform that I own)

**Comment by MTSmhas** [comment]
This dont work but we have build a own image with openwrt and your feeds and this works, but we have a bug on all devices... after we start a speedtest on speedtest.net is the Admin Script not available for 2 seconds and the omr track restart the connections.

**Comment by Ysurac** [comment]
OpenMPTCProuter is not only the feed, there is MPTCP patch and configuration in the build repo, without this you can't get any aggregation.

**Comment by MTSmhas** [comment]
yes we have hack the kernel... now the error is on your last build available. And it is only if the upload test run.
![upload](https://user-images.githubusercontent.com/76729306/203957130-aac68590-af8f-483c-9617-eeee200b19e0.JPG)

**Comment by MTSmhas** [comment]
we have the error on your original x86 original build. and on own custom build.

**Comment by Ysurac** [comment]
You need to enable SQM and set download/upload speed.

**Comment by MTSmhas** [comment]
Ok on which device? SQM is enable.

**Comment by Ysurac** [comment]
On all devices, if there is no changes, set a lower upload speed.

**Comment by MTSmhas** [comment]
Okay we test it. Thanks ;)

**Comment by MTSmhas** [comment]
Okay we test it. Thanks ;)

**Comment by MTSmhas** [comment]
Perfect thanks it work. oh man so simple xD
