### ISSUE TITLE
WireGuard implementation

### ISSUE THREAD

**Issue by max4186** [Ysurac/openmptcprouter#266]
Suggestion:

Implement the following VPN method, not sure if this is actually possible with bonding however.

https://www.wireguard.com/

**Comment by Ysurac** [comment]
It's an UDP VPN, so can't be used to aggregate connection with MPTCP.
So, for now, I will not add it. I add only VPN method that can do aggregation.

**Comment by rmoriz** [comment]
The WireGuard author claims that he was able to run it over MPTCP a couple of years ago successfully https://lists.zx2c4.com/pipermail/wireguard/2017-November/001887.html
