### ISSUE TITLE
GPIO: write error: Device or resource busy

### ISSUE THREAD

**Issue by atyouspace** [Ysurac/openmptcprouter#2662]
## Expected Behavior
Control GPIO for LED

## Current Behavior
When I send `echo 4 > /sys/class/gpio/export`
The GPIO can not be used. "write error: Device or resource busy"

Is there any modules using the corresponding GPIO?
How to solve it?

## Specifications

  - OpenMPTCProuter version: 0.59.1
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter VPS provider:
  - OpenMPTCProuter platform: ARM

**Comment by Ysurac** [comment]
I don't know what is the platform used, but the GPIO can be used by a driver.

**Comment by atyouspace** [comment]
Yes, some drivers will use GPIO.
