### ISSUE TITLE
Le VPN ne répond pas

### ISSUE THREAD

**Issue by DrGonzo76520** [Ysurac/openmptcprouter#2675]
## Expected Behavior
the VPN is not responding (

## Current Behavior

high latency when VPN is not connected (VPN connects and disconnects )

## Specifications

  - OpenMPTCProuter version: 0.59.1-5-4  (message present latest version available 0.58.5 ?)
  - OpenMPTCProuter VPS version: 0.1026
  - OpenMPTCProuter VPS provider: OVH
  - OpenMPTCProuter platform: RPI3B+

**Comment by Ysurac** [comment]
You need to update VPS.
Then if you still have problem, check in Status->System log why the VPN disconnect.
