### ISSUE TITLE
OpenVPN Client

### ISSUE THREAD

**Issue by wouam31200** [Ysurac/openmptcprouter#2682]
Hello,
I have a problem with OpenVPN client.
I would like to be able to take remote control of OMR from my OpenVPN server.

  - OpenMPTCProuter version: openmptcprouter v0.59.1-5.4 r0+16594-ce92de8c8c
  - OpenMPTCProuter VPS version: 0.1026 5.4.100
  - OpenMPTCProuter VPS provider: ovh
  - OpenMPTCProuter platform: PC

As soon as I launch OpenVPN client, the connection is OK.
But I lose the connection to the VPS.

Network overview:
- VPN tunnel DOWN
- No public IP address detected

System Log:
```
Sat Nov 26 17:16:36 2022 user.notice post-tracking-post-tracking: Tunnel up : Replace default route by 10.255.255.1 dev tun0
Sat Nov 26 17:16:46 2022 user.notice post-tracking-post-tracking: Tunnel up : Replace default route by 10.255.255.1 dev tun0
Sat Nov 26 17:16:56 2022 user.notice post-tracking-post-tracking: Tunnel up : Replace default route by 10.255.255.1 dev tun0
```

In Shadowsocks-libev / Redir Rules / ss_rules / Destination Settings / Dot ip/net bypass I added the ip address of my OpenVPN server.
An idea?
Thanks

**Comment by Kalimeiro** [comment]
It's clearly not the right way.

You need to add your openvpn server in OMR to the "VPN" -> "OpenVPN" Section.
