### ISSUE TITLE
Is there a way to view stats/control remotely?

### ISSUE THREAD

**Issue by adamb** [Ysurac/openmptcprouter#2685]
I would like to see the bandwidth stats remotely.  I was thinking I could push them to an outside web server maybe.  Would it be better to put a script on the OMR box or is there some way to get these stats from the VPS side?

I'm trying to build a dashboard for my 'smart home' and this would be nice to have included.

I would also like to be able to troubleshoot the connection remotely.  I suppose I can ssh to the VPS but then how do I get to the OMR box from there?

**Comment by Ysurac** [comment]
SNMP is available on the router part.
To SSH to the router part from VPS part, you need to open port in firewall from VPN zone.
