### ISSUE TITLE
ISO file

### ISSUE THREAD

**Issue by rsajadi63** [Ysurac/openmptcprouter#2688]
## Specifications

  - OpenMPTCProuter version: 
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter VPS provider:
  - OpenMPTCProuter platform: 
RPI4
 
Hi guys I install Esxi on Raspberry pi 4 how can I install openmptcprouter img (ISO unavailable ) on one of the VM? is a way for converting img into iso file??

**Comment by Kalimeiro** [comment]
Ahem ... you have all needed files in the download section of omr website.

ESXI is Vmware, so you need to download Vmware image file.
