### ISSUE TITLE
"Can't contact server admin script" error

### ISSUE THREAD

**Issue by mathchab** [Ysurac/openmptcprouter#269]
## Expected Behavior

Internet access works from the local network

## Actual Behavior

Internet is inaccessible from the local network.
Connection of the 4G gateways works.

No problem for 2 weeks, no configuration changes since.
VPS and router updated, the problem persists.

The local network is accessible from the outside.

-> Two error messages in the openMPTCPRouter state alternate with OK status
"Can't contact server admin script" ; "can't get public ip adress from shadowsocks"

Error
![image](https://user-images.githubusercontent.com/46020582/50277184-03d3a500-0444-11e9-9ea5-e207214dc8ee.png)

OK status
![image](https://user-images.githubusercontent.com/46020582/50276964-8dcf3e00-0443-11e9-8a2a-e0eafe0c44e2.png)

## Specifications

  - OpenMPTCProuter version: v0.44.5 r7416-50789acf4e
  - OpenMPTCProuter VPS version: v0.80 (OVH VPS)
  - OpenMPTCProuter platform:  Raspberry Pi 3+ x86_64

**Comment by Ysurac** [comment]
You should check system log to see if there is any problems here.

**Comment by mathchab** [comment]
Thanks for the reply, sorry for my bad english.

I have these lines in the system logs, they repeat themselves :

`Thu Dec 20 10:58:45 2018 daemon.info omr-tracker-ss: Shadowsocks is down (can't contact 212.27.xx.xx, 104.xx.x.x, 103.224.xxx.xxx, 198.27.xx.x)
Thu Dec 20 10:58:45 2018 user.notice Shadowsocks: Rules DOWN
Thu Dec 20 10:58:50 2018 kern.crit kernel: [ 5851.045891] Under-voltage detected! (0x00050005)
Thu Dec 20 10:58:54 2018 kern.warn kernel: [ 5855.205852] rpi_firmware_get_throttled: 23 callbacks suppressed
Thu Dec 20 10:58:54 2018 kern.info kernel: [ 5855.205856] Voltage normalised (0x00000000)
Thu Dec 20 10:59:03 2018 kern.crit kernel: [ 5863.525886] Under-voltage detected! (0x00050005)
Thu Dec 20 10:59:05 2018 daemon.err /usr/bin/ss-local[4609]: getpeername: Socket not connected
Thu Dec 20 10:59:10 2018 daemon.err /usr/bin/ss-local[4609]: getpeername: Socket not connected
Thu Dec 20 10:59:13 2018 kern.info kernel: [ 5873.925850] Voltage normalised (0x00000000)`

The voltage problem must not have a link (yet my power supply is a 10W).
An idea ?

**Comment by Ysurac** [comment]
I think the under voltage is the problem here. Do you have something on USB ports ?
The "shadowsocks is down" is detected via omr-tracker, this test to contact some ip via http and if no answer then I remove shadowsocks rules and this should use VPN (if it is up).

**Comment by mathchab** [comment]
No other device on the Pi, iPad Pro 10W USB adapter for power and Ethernet to the switch. This from the beginning, no problem until then.

In Service/Shadowsocks/Local Instances I have this rules set to disable :

![image](https://user-images.githubusercontent.com/46020582/50278849-7b0b3800-0448-11e9-9378-8e78a7fac991.png)

**Comment by Ysurac** [comment]
Yes, this rule is not needed.

**Comment by Roken120** [comment]
I have the same problem and i have vpn tunnel down

**Comment by c1ngular** [comment]
i have seen same notice since my latest re-stallation/re-configuration of my RPI-3b , THOUGH , i still got my internet access without problems .

i am using my RPI-3b with a switch connecting to 2 modems , i have shadowsocks and glorytunTCP enabled on my PI , all seems doing fine , and i don't see any error/warning from system log , the only error i saw my last time is something like "/usr/bin/ss-redir[***]: recv error , connection reset by peer ", this log has gone after reboot .
