### ISSUE TITLE
Send and receive sms messages on RUTX12

### ISSUE THREAD

**Issue by highfreq** [Ysurac/openmptcprouter#2695]
I would need to send/receive some sms from modems on RUTX12, is it possible if running OMR?

**Comment by Ysurac** [comment]
It's possible in command line using ModemManager: https://manpages.ubuntu.com/manpages/bionic/en/man8/mmcli.8.html#examples and a good example to read a received SMS: https://gist.github.com/FinnWoelm/3396d09eec2ce1ba676b789308b345c1

I will add a web interface in OpenMPTCProuter.

**Comment by highfreq** [comment]
thanks.

**Comment by highfreq** [comment]
If you add it for my use don't bother, i need to send sms from a service i run, i'll do it in ssh, no prob.
