### ISSUE TITLE
IPv6 Firewall Setting for Passtrough

### ISSUE THREAD

**Issue by iamfreaky** [Ysurac/openmptcprouter#2702]
## Expected Behavior
IPv6 Traffic should be allowed trought if you set up the firewall correctly 

## Current Behavior
Traffic gets blocked even if you set up the firewall correctly. 

## Specifications

  - OpenMPTCProuter version: v0.59.1-5.4 r0+16594-ce92de8c8c
  - OpenMPTCProuter VPS version: 0.1028
  - OpenMPTCProuter VPS provider: BuyVM, No Image Install, manual install works fine. 
  - OpenMPTCProuter platform: x86_64

```
/etc/shorewall6/rules

#       Don't allow connection pickup from the net
#
#Invalid(DROP)   net             all             tcp
ACCEPT          net             vpn             tcp

```
```
/etc/shorewall6/policy

#SOURCE         DEST            POLICY          LOG LEVEL       LIMIT:BURST

vpn             all             ACCEPT
fw              all             ACCEPT
#net             all             DROP
net             all             ACCEPT

```
I changed the config on the VPS for IPv6 Packets going to the omr6in4 tunnel. I can see IPv6 Traffic on the omr6in4 on the OpenMPTCP Router. There is a Static Route for the Global IPv6 Address. The whole Setup is behind a pfsense Box. 

Settings on the OpenMPTCP Router Firewall. 

```
/etc/config/firewall
config rule
        list proto 'all'
        option src 'vpn'
        option dest 'lan'
        option name 'Allow-Input-From-VPN-to-pfSense'
        option family 'ipv6'
        list dest_ip '2XXXXXXXX:1000::/52' -> In My Config of course the whole subnet ist standing there. ( I Also tried die direct IP Adress but this didnt work)
        option target 'ACCEPT'
```

**Comment by Ysurac** [comment]
You need to set DMZ option or specify a port or port range.
