### ISSUE TITLE
Accept external connections only from specific addresses

### ISSUE THREAD

**Issue by highfreq** [Ysurac/openmptcprouter#2710]
@Ysurac i would need a little help to have shorewall on VPS to accept connections for port forwarding only from two specific IP addresses. Could you please help me out?
Basicly i want to enable only my office and home public ip to be forwarded to the modem when i try to connect to any port.

**Comment by Kalimeiro** [comment]
on OMR you need to go to network -> firewall then edit the rulest, go to advanced settings and add ip source to filter only the ip allowed to connect to this port.

it's not possible to add multiple ip source to one rule, so you need to create a second rule to filter another ip source.

**Comment by highfreq** [comment]
Thank you, will try and report back. So nothing needs to be done on the VPS, i can configure on OMR and it'll apply on the server.

**Comment by highfreq** [comment]
@Kalimeiro looked a bit around, do you mean inside the  port forward rule, i need to add the filter?

**Comment by Ysurac** [comment]
Here:
![image](https://user-images.githubusercontent.com/6342954/210130264-526a1127-11e5-4340-99a8-4db57e67dc9a.png)

**Comment by highfreq** [comment]
Found it when kalimeiro pointed it to me, thank you.

**Comment by highfreq** [comment]
Hello, would like to know if you think it is possible a porting to the attached hardware. Obviously paying your time.


https://www.microhardcorp.com/DX2.php￼
