### ISSUE TITLE
Router not giving internet

### ISSUE THREAD

**Issue by Roc2707** [Ysurac/openmptcprouter#2712]
## Expected Behavior
Wish it would work

## Current Behavior
The server is installed on vmware. The server connects to the VPS, the server's local address is 192.168.88.38. If I set the default IP gateway server address (192.168.88.38), then there is no Internet, as if the server is not a gateway.
![openmptcp](https://user-images.githubusercontent.com/79087974/209906789-5b2f77c1-f32f-4116-85ac-ddb75300e93c.png)
The server works, but if you select it as a gateway, then the Internet does not give.

## Specifications

  - OpenMPTCProuter version: 0.59.1-5.4
  - OpenMPTCProuter VPS version: 0.1028 5.4.207-mptcp
  - OpenMPTCProuter VPS provider:
  - OpenMPTCProuter platform: x86_64 vmware

**Comment by Roc2707** [comment]
If I do a ping for example 8.8.4.4 then it reports that "Timeout has expired"

**Comment by Kalimeiro** [comment]
please configure correctly your OMR, your wan settings is wrong/strange/same subnet/...

**Comment by Ysurac** [comment]
Why wan1 and wan2 use same gateway ? It's possible and seems to work as you get 2 different public IP. 
You also seems to have all WANs and LAN in same subnet, this is not a good idea.
