### ISSUE TITLE
Ububtu Edge router SSH credentials

### ISSUE THREAD

**Issue by lew-hand** [Ysurac/openmptcprouter#2719]
## Expected Behavior

Hi

I have a Edgerouter X and I flashed the minimal image from the guide here https://github.com/Ysurac/openmptcprouter/wiki/Router-install

When I go to SSH for the next step to load the other image the default Edgerouter credentials no longer work and are not listed in the guide.

**Comment by Ysurac** [comment]
Default password is ubnt

**Comment by lew-hand** [comment]
Thanks for the reply

Thats why I tried username ubnt
Password: ubnt

**Comment by citykidz** [comment]
I've got the same device - you're saying ubnt/ubnt doesn't work after the software install?
