### ISSUE TITLE
Multiple network interfaces in VPS

### ISSUE THREAD

**Issue by sinlam** [Ysurac/openmptcprouter#2722]
Hi all,
  Is it possible to have multiple network interfaces in VPS host? For example in the Ubuntu-based VPS, it has Wifi, Ethernet and 5G connections, if one of the connections drops in VPS, I hope the connection to MPTCP Router is still maintained.

Another related question is in MPTCP Router, I can only specify one VPS address (single interface) in the Settings. Is it possible to specify multiple interfaces of the same VPS host?

Hope to hear from you soon, thanks for the nice project.

**Comment by Ysurac** [comment]
It's not supported. VPS script is designed for a VPS in a datacenter.

**Comment by sinlam** [comment]
Thanks for the info!
