### ISSUE TITLE
5.15+ Kernel w/o Upstream MPTCP?

### ISSUE THREAD

**Issue by virtuallynathan** [Ysurac/openmptcprouter#2736]
I'm using a Celeron J6413 System with I225/I226 2.5GbE NICs, which are supported in Kernel 5.15+, so I'm using the upstream build, but having a lot of issues. Would be great to have a 5.15+ kernel build w/o Upstream MPTCP.

Thanks!

**Comment by Ysurac** [comment]
Latest supported kernel by MPTCP out of tree is 5.4.
I225/I226 work on 5.4 when you don't use DHCP or if you force link.

**Comment by virtuallynathan** [comment]
Ah ok, that makes sense. I wasn't able to see any interfaces on 5.4, so I'll wait for a 6.1.x build, thanks!
