### ISSUE TITLE
VPS Failover not working?

### ISSUE THREAD

**Issue by max4186** [Ysurac/openmptcprouter#274]
## Expected Behavior

VPS to switch from primary to failover VPS.

## Actual Behavior

VPS goes offline, does not switch to failover.

## Specifications

  - OpenMPTCProuter version: v0.44.5
  - OpenMPTCProuter VPS version: 0.80
  - OpenMPTCProuter platform: RPI 3 64bit

**Comment by Ysurac** [comment]
True, a stupid bug make changes from OpenMPTCProuter to VPS not working.
This will be fixed in next release (that should be out soon).
