### ISSUE TITLE
How to test each WAN to VPS?

### ISSUE THREAD

**Issue by ccmks** [Ysurac/openmptcprouter#2741]
How can I test each WAN to my VPS? I want to know if each of my ISP is throttling connectivity to VPS.

If I run omr-test-speed ethX - it will be going to datacenter based on the lowest ping, I can't use that to test to my VPS.

Thank you

**Comment by Ysurac** [comment]
There is ```omr-test-speed-server ethX``` but it doesn't always work great. Or ```omr-iperf``` that use iperf3 server installed on VPS side.

**Comment by ccmks** [comment]
Thank you for your response

How can I use iperf for each individual WAN?

Thank you
