### ISSUE TITLE
Language and VPN usage

### ISSUE THREAD

**Issue by bluenor** [Ysurac/openmptcprouter#2742]
Hello, a very strange thing happens to me, when I connect to google and some other site that does language detection, it shows me the text translated into Russian as if my ip was Russian but in fact my ip and my browser are in Italian.

With iftop also on the server that acts as my vpn, I notice that there are connections from strange ip addresses with which I am not connecting. Is there a log where I can see if there are connections with key exchanges to see if anyone else is using my vpn?

Thank you for your answer

**Comment by Ysurac** [comment]
This may be related to your VPS IP that was a Russian IP and some websites doesn't update IP localization so often.

On router part, there is Status->Realtime Graphs, "Connection" tab. On VPS there is /var/log/daemon.log.
Some connections are made by Services->OMR-Tracker to check if proxy is up.
