### ISSUE TITLE
OpenMPTCProuter v0.59.2 alpha

### ISSUE THREAD

**Issue by Ysurac** [Ysurac/openmptcprouter#2747]
OpenMPTCProuter v0.59.2 alpha snapshot release is available with 3 Linux kernel : 5.4, 5.15 and 6.1.

5.4 is the "stable" branch with fullmesh, redundancy,... It use the out of tree MPTCP release.
5.15 and 6.1 kernel only support fullmesh for now, so can only aggregate all connections. It use MPTCP upstream version. Only a few platforms are available on 6.1 for now.

All release are available on https://snapshots.openmptcprouter.com/

Detailed changelog will be available here soon.

It's an alpha release, so can have many bug and some features are missing for final release.

You MUST update VPS with this script: 

-  For router with kernel 5.4: ```wget -O - http://www.openmptcprouter.com/server-test/debian.sh | sh```
- For router with kernel 5.15: ```wget -O - http://www.openmptcprouter.com/server-test/debian.sh | UPSTREAM="yes" sh```
- For router with kernel 6.1: ```wget -O - http://www.openmptcprouter.com/server-test/debian.sh | UPSTREAM6="yes" sh``` (only Debian is supported and this will update Debian to Debian Bookworm 12) **Work on x86_64 and arm64 at least.**

**6.1 is not a release, it's not tested, it's only a compilation test for now due to major changes**

**Comment by NKnusperer** [comment]
Can you please elaborate what `only support fullmesh` means practical speaking?
eg. losing the master connection is not supportend or bypass rules are not working?
Looking forward for v6.1 kernel because of hardware support.

**Comment by JRTechServices** [comment]
Thank you Ysurac for all of your hard work.

**Comment by fareign** [comment]
<img width="911" alt="微信图片_20230309084544" src="https://user-images.githubusercontent.com/15459/223885986-67a2e929-9e00-4945-93a4-8b3a668954dd.png">
I sovled vnstat2 cant display image in 5.15 kernel.but I dont know why.

1. remove vnstat2
2. install vnstat
3. remove vnstat
4. install vnstat2 then is ok.

maybe some conflict with vnstat.

**Comment by Steltek** [comment]
Tried 5.15, but couldn't install keepalived due to missing dependencies. (Without it my other router takes over.)

**Comment by metro2450** [comment]
Hi Ysurac,

Thank you for the wonderful project.
May I know if there is a plan to move the project base to the new openwrt 23.05 release with 5.15 kernel and provide more device support since MPTCPv1 is supported in 5.15 kernel out of box?
https://openwrt.org/releases/23.05/

**Comment by Ysurac** [comment]
Not really, but there is plan to move to latest OpenWRT and use 6.1 kernel. Most arch are already supported on develop branch.
On next release 6.1 will be official release and 5.4 for legacy release (and unsupported arch on 6.1)
5.15 doesn't give a really good result.

**Comment by vempire-ghost** [comment]
In the last snapshot from de v0.59.2 alpha the proxy is not showing when v2ray is selected and the system log is always blank.
![image](https://github.com/Ysurac/openmptcprouter/assets/132581535/62e70c0d-c344-4aa8-9b35-3708dbbea1f7)
![image](https://github.com/Ysurac/openmptcprouter/assets/132581535/e56b428b-fe8b-41c3-8841-cf1961bdf37a)

**Comment by hle5128** [comment]
i notce that you haev 6.1 target Ipq807x chip, is that mean I can test the gl slate Issue: https://github.com/Ysurac/openmptcprouter/issues/2415

**Comment by Ysurac** [comment]
Support was tested with qnap-301w (platform is qualcommax), GL-AXT1800 is still not supported by OpenWRT and I don't have the device so I can't add/test support.

**Comment by hle5128** [comment]
> Support was tested with qnap-301w (platform is qualcommax), GL-AXT1800 is still not supported by OpenWRT and I don't have the device so I can't add/test support.

Have you check here? It supported here:

https://forum.gl-inet.com/t/gl-inet-ax1800-openwrt-firmware/19447/257

**Comment by Ysurac** [comment]
There is no official support. So it's not always easy to add without the device as I may have to changes somes patches, change kernel config,...
