### ISSUE TITLE
No Aggregation / slow speed

### ISSUE THREAD

**Issue by psylou** [Ysurac/openmptcprouter#2748]
## Expected Behavior

2 WAN's should get aggregated to about 1000Mbit/s

## Current Behavior

WAN1 uses almost full speed but WAN2 about 5% and I get about 200 Mbps together
WAN1 is 250/40
WAN2 is 750/40
Router has 4 Cores / 4 GB
VPS has 4 Cores / 8 GB

![image](https://user-images.githubusercontent.com/8116196/215347530-92eba49e-f82d-4a82-a120-507b80685b9f.png)

omr-test-speed
![image](https://user-images.githubusercontent.com/8116196/215346722-816bce8f-32c2-4a7f-8f6a-ddd2c82031c5.png)

![image](https://user-images.githubusercontent.com/8116196/215347280-0d7e015f-2ac3-46f4-8679-3be84add3df7.png)

omr-test-speed eth1 (WAN2)
![image](https://user-images.githubusercontent.com/8116196/215346782-d4fe2005-8eb2-497d-a8ff-14bc4ad2d908.png)

omr-test-speed eth2 (WAN1)
![image](https://user-images.githubusercontent.com/8116196/215346881-3289418e-02fd-4940-a122-68ee2980e870.png)

## Specifications

  - OpenMPTCProuter version: openmptcprouter v0.59.1-5.15  
  - OpenMPTCProuter VPS version: openmptcprouter v0.59.1-5.15 
  - OpenMPTCProuter VPS provider: 1blu
  - OpenMPTCProuter platform: x86_64 Proxmox VirtIO NICs

**Comment by Ysurac** [comment]
5.15 based release is still an alpha version.
omr-test-speed should be run at least 2 minutes to get a real result.

**Comment by psylou** [comment]
Thank you for replying. But I need the upstream aggregation. Actually I switched to your 6.1 alpha release and it seems to be working there. My interfaces have very different latencys. Any way to let VoIP or games go over one interface but still use the vpn?

**Comment by AyberkAltuntop** [comment]
Hello,
The same applies to me, I connect 3 wans, 1.000/100, 80/8 and one variable speed cellular connection. In my tests I could not exceed 250 Mbps download 100 upload. 

Where should I look? 

When I test the VPS and wans one by one, it gives the values that should be.

**Comment by Ysurac** [comment]
@AyberkAltuntop please open a new issue, and if you use 5.15 release: don't use it.

**Comment by AyberkAltuntop** [comment]
Thank you for your answer. I reinstalled my VPS as kernel 6.1 with Debian 12. I ordered Qnap Qhora 301-w for the router. 

I will test it again during the week and if my problem persists I will open a new topic. 

By the way, this is a very nice and successful job, thank you for giving it to us.
