### ISSUE TITLE
build image warning,how to solve it

### ISSUE THREAD

**Issue by fareign** [Ysurac/openmptcprouter#2750]
root@VM-0-12-debian:~/openmptcprouter/x86_64/5.4/source# ./scripts/feeds install bmx7
WARNING: Makefile 'package/feeds/packages/bmx7-dnsupdate/Makefile' has a dependency on 'bmx7', which does not exist
WARNING: Makefile 'package/feeds/packages/bmx7-dnsupdate/Makefile' has a dependency on 'bmx7-json', which does not exist
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'kmod-cdrom', which does not exist
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'kmod-cdrom', which does not exist
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'kmod-cdrom', which does not exist
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'kmod-cdrom', which does not exist
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'kmod-ledtrig-audio', which does not exist
WARNING: Makefile 'package/feeds/luci/luci-app-ahcp/Makefile' has a dependency on 'ahcpd', which does not exist
WARNING: Makefile 'package/feeds/luci/luci-app-babeld/Makefile' has a dependency on 'babeld', which does not exist
WARNING: Makefile 'package/feeds/luci/luci-app-bmx7/Makefile' has a dependency on 'bmx7', which does not exist
WARNING: Makefile 'package/feeds/luci/luci-app-bmx7/Makefile' has a dependency on 'bmx7-json', which does not exist
WARNING: Makefile 'package/feeds/luci/luci-app-olsr/Makefile' has a dependency on 'olsrd', which does not exist
WARNING: Makefile 'package/feeds/luci/luci-app-olsr/Makefile' has a dependency on 'olsrd-mod-jsoninfo', which does not exist
WARNING: Makefile 'package/feeds/luci/luci-app-olsr-services/Makefile' has a dependency on 'olsrd', which does not exist
WARNING: Makefile 'package/feeds/luci/luci-app-olsr-services/Makefile' has a dependency on 'olsrd-mod-nameservice', which does not exist
WARNING: Makefile 'package/feeds/luci/luci-app-olsr-viz/Makefile' has a dependency on 'olsrd', which does not exist
WARNING: Makefile 'package/feeds/luci/luci-app-olsr-viz/Makefile' has a dependency on 'olsrd-mod-txtinfo', which does not exist
WARNING: Makefile 'package/feeds/luci/luci-nginx/Makefile' has a dependency on 'nginx-mod-luci', which does not exist
WARNING: Makefile 'package/feeds/luci/luci-ssl-nginx/Makefile' has a dependency on 'nginx-mod-luci-ssl', which does not exist
WARNING: Makefile 'package/feeds/openmptcprouter/openmptcprouter-full/Makefile' has a dependency on 'kmod-crypto-lib-blake2s', which does not exist
WARNING: Makefile 'package/feeds/packages/prometheus-node-exporter-lua/Makefile' has a dependency on 'bmx6', which does not exist
WARNING: Makefile 'package/feeds/packages/prometheus-node-exporter-lua/Makefile' has a dependency on 'bmx6-json', which does not exist
WARNING: Makefile 'package/feeds/packages/prometheus-node-exporter-lua/Makefile' has a dependency on 'bmx7', which does not exist
WARNING: Makefile 'package/feeds/packages/prometheus-node-exporter-lua/Makefile' has a dependency on 'bmx7-json', which does not exist
WARNING: Makefile 'package/utils/wmt/Makefile' has a dependency on 'kmod-mt6625l-wlan-gen2', which does not exist
WARNING: No feed for package 'bmx7' found

**Comment by Ysurac** [comment]
ignore them.
