### ISSUE TITLE
no ping response from server after one minute

### ISSUE THREAD

**Issue by leoxyt** [Ysurac/openmptcprouter#2753]
when I connect the linkem connection it gives me the error "no ping response from server after one minute" how can I fix it?

**Comment by Ysurac** [comment]
Please use the template...
Check that you can ping server IP from your connections (ping -B -I wan1 <serverip>).
If not, check that ping is not blocked on VPS side by a firewall and check that ping is not blocked on your connections.
If it's blocked somewhere and you can't change that, change the method used by OMR-Tracker in Services->OMR-Tracker.
