### ISSUE TITLE
how to config Glorytun udp aggregation on both openrmprouter and vps side

### ISSUE THREAD

**Issue by hewenhao2008** [Ysurac/openmptcprouter#276]
## Expected Behavior
    All udp triaffic can be  proxyed by glortun server (on VPS) with mulit-path feature .

## Actual Behavior
    How to config the glortun clien on router side and glortun server on VPS side, and how to test?

**Comment by Ysurac** [comment]
It's the default behavior.
You can choose the VPN used in OpenMPTCProuter wizard page, by default Glorytun TCP, so using MPTCP to aggregate, is used.
