### ISSUE TITLE
General Protection Faults

### ISSUE THREAD

**Issue by HarlekinSimplex** [Ysurac/openmptcprouter#2764]
Hi all,
I run OMR on a i7 barebone for a couple of weeks now, and the service seems to be working more ore less flawless.
How ever occationly I exeperience unexpected disconnects of teams sessions, which should not happen with that one...

No clue if it is related or maybe the root cause, looking at the proxmox console of the OMR VM, I can seen a lot of logread general protection fault messages in libc.so.

![image](https://user-images.githubusercontent.com/7103664/216814710-c85a245a-461e-4fc0-a748-eaaf6a380d59.png)

I run OMR openmptcprouter v0.59.1-5.4 r0+16594-ce92de8c8c with VPS 0.1028 5.4.207-mptcp.
OMR runs within a VM under Proxmox 7.3-4 on an 8x11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (1 Socket) with 6x2.5GBit Intel Ethernet ports.

![image](https://user-images.githubusercontent.com/7103664/216815988-6f3e649c-6588-4abd-894b-29640dae6857.png)

The VPS is a Hetzner Cloud CX11 at their Datacenter at Falkenstein. As backup there is a similar standby VPS set up and configured at the Hetzner Datacenter in Helsinki.

![image](https://user-images.githubusercontent.com/7103664/216815556-c6dbe702-75d3-4a7f-b5d8-a9f4e1e16e36.png)

I've configured two WAN Interfaces. One connected to a FRITZ!Box 6890 LTE providing T-DSL with LTE as Backup (192.168.2.x) and the second WAN is connected to a TP-Link RE 450 that provides access to Starlink Mobil (192.168.1.x).

![image](https://user-images.githubusercontent.com/7103664/216815588-c1d635b6-a7d3-4a35-bbe3-4a08cab438ed.png)

On the LAN side (192.168.10.x) I run pfSense (rel-1.16.0-0-gd239552ce722-prebuilt.qemu.org) as Perimeter FW into my LAN.

![image](https://user-images.githubusercontent.com/7103664/216815896-41029a31-8c78-426c-ad82-4394959df7ca.png)

The whole system runs well. All failover scenarios, including VPS fail, are tested regularily and found working properly except those unexpected disconnects during normal work hours.

Any idea what causes those general protection faults, and what to do to solve their root cause?

Cheers
Harlekin

**Comment by Ysurac** [comment]
logread general protection fault is a know issue, but this doesn't affect anything, only log.
For disconnection you should check log (when there is not a crash of logread), omr-tracker should give some info.
