### ISSUE TITLE
new version not working

### ISSUE THREAD

**Issue by kapook007** [Ysurac/openmptcprouter#277]
hello
my system  is x86 cpu.
OpenMPTCProuter v.0.38  and  VPS v0.64   is  working successful.

i flash OpenMPTCProuter to v.044 and  VPS v0.77 have some problem.

1. OpenMPTCProuter can not ping glorytun vps gateway ( 10.255.255.1)
2. Network overview  wan1-wan5 show "multipath seems to be blocked on the connection"

but only tcp  shadowsocks  can run  successful.
my key shadowsocks  and   glorytun is correct.

**Comment by Ysurac** [comment]
Latest version are OpenMPTCProuter 0.44.5 and OpenMPTCProuter VPS 0.80. You should update.

**Comment by kapook007** [comment]
WOW  thank you

**Comment by kapook007** [comment]
OpenMPTCProuter 0.44.5 and OpenMPTCProuter VPS 0.80. 
smae problem
OpenMPTCProuter can not ping glorytun vps gateway ( 10.255.255.1)

**Comment by Ysurac** [comment]
You should check OpenMPTCProuter log.

**Comment by kapook007** [comment]
my OpenMPTCProuter VPS  is behind nat
now i forward port 65101 and 65001

how many  rang forward port ?

**Comment by Ysurac** [comment]
All ports used are here: https://github.com/Ysurac/openmptcprouter/wiki/Install-or-update-the-VPS

**Comment by kapook007** [comment]
thank you
