### ISSUE TITLE
VPN to access on my local lan ?

### ISSUE THREAD

**Issue by jedrosik** [Ysurac/openmptcprouter#2777]
Hello ,

How can i make a vpn for acces on my lan ?
Did you have any information, video , tuto ?

i'll would like to use wireguard but i don't know how ...

i'm on VPS debian and openmtcprouter : 59.1

Thanks a lot :))

**Comment by Ysurac** [comment]
Doc is not yet ready, but on the VPS in /root/wireguard-client.conf there is a wireguard config for that.
Not sure it's enough, it may need more settings...

**Comment by highvolt-dev** [comment]
@jedrosik I got wireguard working and gave detailed instructions here: https://github.com/Ysurac/openmptcprouter/issues/2123#issuecomment-1474938197
