### ISSUE TITLE
 startup  openmptcprouter doesnt work on kernel 5.15 6.1

### ISSUE THREAD

**Issue by fareign** [Ysurac/openmptcprouter#2780]
0.59.1 kernel 5.15 and 6.1
also vnStat can't work.
if I run it ,
the log is: daemon.err rmmod: module is not loaded

**Comment by Ysurac** [comment]
use template...
I don't know arch, there is no 0.59.1 on 6.1 kernel,...

**Comment by fareign** [comment]
v0.59.1-5.15-r0+20029-3c06a344e9-x86-64
