### ISSUE TITLE
v0.59.1-5.15-r0+20029-3c06a344e9-x86-64

### ISSUE THREAD

**Issue by fareign** [Ysurac/openmptcprouter#2781]
use template...
I don't know arch, there is no 0.59.1 on 6.1 kernel,...

_Originally posted by @Ysurac in https://github.com/Ysurac/openmptcprouter/issues/2780#issuecomment-1433593181_
            
hehe,you don't know arch 0.59.1?
where do close the issue quickly?
Or you don't want to solve the problem？

**Comment by fareign** [comment]
<img width="740" alt="00001" src="https://user-images.githubusercontent.com/15459/219523623-45cd4a48-977e-4482-90aa-6514bc3a661f.png">
<img width="716" alt="00002" src="https://user-images.githubusercontent.com/15459/219523652-bf1b1acf-6d88-41b9-8745-2979ccbb48e5.png">
<img width="716" alt="0000" src="https://user-images.githubusercontent.com/15459/219523662-cf0ebf36-3d01-4150-bdd0-a922081bfbf8.png">

**Comment by fareign** [comment]
<img width="630" alt="00003" src="https://user-images.githubusercontent.com/15459/219534712-b2f15d20-6e45-4003-a514-55927b6cc9db.png">
 I solved it.

**Comment by Ysurac** [comment]
Please... use template when you open an issue...
I don't want to miss lot of time asking always same questions like version, on what architecture,...
If you solved it, this is close.
