### ISSUE TITLE
Openvpn on openmtcprouter

### ISSUE THREAD

**Issue by kverkind** [Ysurac/openmptcprouter#2782]
## Expected Behavior
VPS is not in my country and want to use a VPN provider (SurfShark) providing ip in own country

## Current Behavior
I have openvpn upload to upload config and did set user/pass
I get an authentication error.
Is there a guide on how to configure (if possible) an ovpn on the modem in order to mask vps location?

## Specifications

  - OpenMPTCProuter version: openmptcprouter v0.59.1-5.4 r0+16594-ce92de8c8c
  - OpenMPTCProuter VPS version: OpenMPTCProuter VPS 0.1028
  - OpenMPTCProuter VPS provider: Hetzner
  - OpenMPTCProuter platform:  RPI4

**Comment by Ysurac** [comment]
In your case VPN should be installed on VPS side.
