### ISSUE TITLE
libustream-wolfssl package error while building custom image using image builder

### ISSUE THREAD

**Issue by iamdivyanshverma** [Ysurac/openmptcprouter#2783]
HP-Z640-Workstation:~/divyansh/custom_build/bloom/rootfspack/openmptcprouter/rpi4/5.4/source/bin/targets/bcm27xx/bcm2711/openmptcprouter-imagebuilder-v0.59-5.4-bcm27xx-bcm2711.Linux-x86_64$ make image PROFILE="rpi-4" FILES="files"
Building images for bcm27xx - Raspberry Pi 4B/400/4CM (64bit)
Packages: base-files busybox ca-bundle cypress-firmware-43455-sdio cypress-nvram-43455-sdio-rpi-4b dnsmasq dropbear e2fsprogs firewall fstools ip6tables iptables iwinfo kernel kmod-brcmfmac kmod-fs-vfat kmod-ipt-offload kmod-nls-cp437 kmod-nls-iso8859-1 kmod-usb-hid libc libgcc libustream-wolfssl logd mkf2fs mtd netifd odhcp6c odhcpd-ipv6only opkg partx-utils ppp ppp-mod-pppoe procd uci uclient-fetch urandom-seed wpad-basic-wolfssl

Package list missing or not up-to-date, generating it.

Building package index...
Downloading file:packages/Packages
Updated list of available packages in /home/benlycos/divyansh/custom_build/bloom/rootfspack/openmptcprouter/rpi4/5.4/source/bin/targets/bcm27xx/bcm2711/openmptcprouter-imagebuilder-v0.59-5.4-bcm27xx-bcm2711.Linux-x86_64/build_dir/target-aarch64_cortex-a72_musl/root-bcm27xx/../../../../../../../../../../../../../../../../../../home/benlycos/divyansh/custom_build/bloom/rootfspack/openmptcprouter/rpi4/5.4/source/bin/targets/bcm27xx/bcm2711/openmptcprouter-imagebuilder-v0.59-5.4-bcm27xx-bcm2711.Linux-x86_64/dl/imagebuilder
Downloading file:packages/Packages.sig
Signature check passed.

Installing packages...
Installing libc (1.1.24-3) to root...
Installing libgcc1 (8.4.0-3) to root...
Downloading file:packages/libgcc1_8.4.0-3_aarch64_cortex-a72.ipk
Configuring libgcc1.
Configuring libc.
Installing kernel (5.4.225-1-92b7b9c4282a058a5ef043e8abcd8576) to root...
Configuring kernel.
Installing base-files (1449-r0+16819-1b6e9b3f64) to root...
Downloading file:packages/base-files_1449-r0%2b16819-1b6e9b3f64_aarch64_cortex-a72.ipk
Installing libubox20210516 (2021-05-16-b14c4688-2) to root...
Downloading file:packages/libubox20210516_2021-05-16-b14c4688-2_aarch64_cortex-a72.ipk
Installing libuci20130104 (2021-04-14-4b3db117-5) to root...
Downloading file:packages/libuci20130104_2021-04-14-4b3db117-5_aarch64_cortex-a72.ipk
Installing libnl-tiny1 (2020-08-05-c291088f-2) to root...
Downloading file:packages/libnl-tiny1_2020-08-05-c291088f-2_aarch64_cortex-a72.ipk
Installing libubus20210630 (2021-06-30-4fc532c8-2) to root...
Downloading file:packages/libubus20210630_2021-06-30-4fc532c8-2_aarch64_cortex-a72.ipk
Installing libjson-c5 (0.15-2) to root...
Downloading file:packages/libjson-c5_0.15-2_aarch64_cortex-a72.ipk
Installing libblobmsg-json20210516 (2021-05-16-b14c4688-2) to root...
Downloading file:packages/libblobmsg-json20210516_2021-05-16-b14c4688-2_aarch64_cortex-a72.ipk
Installing ubusd (2021-06-30-4fc532c8-2) to root...
Downloading file:packages/ubusd_2021-06-30-4fc532c8-2_aarch64_cortex-a72.ipk
Installing ubus (2021-06-30-4fc532c8-2) to root...
Downloading file:packages/ubus_2021-06-30-4fc532c8-2_aarch64_cortex-a72.ipk
Installing jshn (2021-05-16-b14c4688-2) to root...
Downloading file:packages/jshn_2021-05-16-b14c4688-2_aarch64_cortex-a72.ipk
Installing netifd (2021-07-26-440eb064-1) to root...
Downloading file:packages/netifd_2021-07-26-440eb064-1_aarch64_cortex-a72.ipk
Installing jsonfilter (2018-02-04-c7e938d6-1) to root...
Downloading file:packages/jsonfilter_2018-02-04-c7e938d6-1_aarch64_cortex-a72.ipk
Installing usign (2020-05-23-f1f65026-1) to root...
Downloading file:packages/usign_2020-05-23-f1f65026-1_aarch64_cortex-a72.ipk
Installing openwrt-keyring (2021-02-20-49283916-2) to root...
Downloading file:packages/openwrt-keyring_2021-02-20-49283916-2_aarch64_cortex-a72.ipk
Installing ubox (2020-10-25-9ef88681-2) to root...
Downloading file:packages/ubox_2020-10-25-9ef88681-2_aarch64_cortex-a72.ipk
Installing fstools (2021-01-04-c53b1882-1) to root...
Downloading file:packages/fstools_2021-01-04-c53b1882-1_aarch64_cortex-a72.ipk
Installing fwtool (2019-11-12-8f7fe925-1) to root...
Downloading file:packages/fwtool_2019-11-12-8f7fe925-1_aarch64_cortex-a72.ipk
Installing busybox (1.33.2-2) to root...
Downloading file:packages/busybox_1.33.2-2_aarch64_cortex-a72.ipk
Installing ca-bundle (20210119-1) to root...
Downloading file:packages/ca-bundle_20210119-1_all.ipk
Installing cypress-firmware-43455-sdio (5.10.9-2022_0909-1) to root...
Downloading file:packages/cypress-firmware-43455-sdio_5.10.9-2022_0909-1_aarch64_cortex-a72.ipk
Installing cypress-nvram-43455-sdio-rpi-4b (2019-09-03-e7b78df2-2) to root...
Downloading file:packages/cypress-nvram-43455-sdio-rpi-4b_2019-09-03-e7b78df2-2_aarch64_cortex-a72.ipk
Installing dnsmasq-full (2.85-9) to root...
Downloading file:packages/dnsmasq-full_2.85-9_aarch64_cortex-a72.ipk
Installing libgmp10 (6.2.1-1) to root...
Downloading file:packages/libgmp10_6.2.1-1_aarch64_cortex-a72.ipk
Installing libnettle8 (3.6-1) to root...
Downloading file:packages/libnettle8_3.6-1_aarch64_cortex-a72.ipk
Installing kmod-nf-reject (5.4.225-1) to root...
Downloading file:packages/kmod-nf-reject_5.4.225-1_aarch64_cortex-a72.ipk
Installing kmod-nf-ipt (5.4.225-1) to root...
Downloading file:packages/kmod-nf-ipt_5.4.225-1_aarch64_cortex-a72.ipk
Installing kmod-ipt-core (5.4.225-1) to root...
Downloading file:packages/kmod-ipt-core_5.4.225-1_aarch64_cortex-a72.ipk
Installing kmod-nfnetlink (5.4.225-1) to root...
Downloading file:packages/kmod-nfnetlink_5.4.225-1_aarch64_cortex-a72.ipk
Installing kmod-ipt-ipset (5.4.225-1) to root...
Downloading file:packages/kmod-ipt-ipset_5.4.225-1_aarch64_cortex-a72.ipk
Installing libnfnetlink0 (1.0.1-4) to root...
Downloading file:packages/libnfnetlink0_1.0.1-4_aarch64_cortex-a72.ipk
Installing kmod-nf-conntrack (5.4.225-1) to root...
Downloading file:packages/kmod-nf-conntrack_5.4.225-1_aarch64_cortex-a72.ipk
Installing kmod-ipt-conntrack (5.4.225-1) to root...
Downloading file:packages/kmod-ipt-conntrack_5.4.225-1_aarch64_cortex-a72.ipk
Installing kmod-nf-conntrack-netlink (5.4.225-1) to root...
Downloading file:packages/kmod-nf-conntrack-netlink_5.4.225-1_aarch64_cortex-a72.ipk
Installing libmnl0 (1.0.4-2) to root...
Downloading file:packages/libmnl0_1.0.4-2_aarch64_cortex-a72.ipk
Installing libnetfilter-conntrack3 (1.0.8-1) to root...
Downloading file:packages/libnetfilter-conntrack3_1.0.8-1_aarch64_cortex-a72.ipk
Installing dropbear (2020.81-2) to root...
Downloading file:packages/dropbear_2020.81-2_aarch64_cortex-a72.ipk
Installing e2fsprogs (1.45.6-2) to root...
Downloading file:packages/e2fsprogs_1.45.6-2_aarch64_cortex-a72.ipk
Installing libpthread (1.1.24-3) to root...
Downloading file:packages/libpthread_1.1.24-3_aarch64_cortex-a72.ipk
Installing librt (1.1.24-3) to root...
Downloading file:packages/librt_1.1.24-3_aarch64_cortex-a72.ipk
Installing libuuid1 (2.36.1-2) to root...
Downloading file:packages/libuuid1_2.36.1-2_aarch64_cortex-a72.ipk
Installing libblkid1 (2.36.1-2) to root...
Downloading file:packages/libblkid1_2.36.1-2_aarch64_cortex-a72.ipk
Installing libcomerr0 (1.45.6-2) to root...
Downloading file:packages/libcomerr0_1.45.6-2_aarch64_cortex-a72.ipk
Installing libss2 (1.45.6-2) to root...
Downloading file:packages/libss2_1.45.6-2_aarch64_cortex-a72.ipk
Installing libext2fs2 (1.45.6-2) to root...
Downloading file:packages/libext2fs2_1.45.6-2_aarch64_cortex-a72.ipk
Installing firewall (2021-03-23-61db17ed-1.1) to root...
Downloading file:packages/firewall_2021-03-23-61db17ed-1.1_aarch64_cortex-a72.ipk
Installing libxtables12 (1.8.7-1) to root...
Downloading file:packages/libxtables12_1.8.7-1_aarch64_cortex-a72.ipk
Installing libip4tc2 (1.8.7-1) to root...
Downloading file:packages/libip4tc2_1.8.7-1_aarch64_cortex-a72.ipk
Installing libip6tc2 (1.8.7-1) to root...
Downloading file:packages/libip6tc2_1.8.7-1_aarch64_cortex-a72.ipk
Installing kmod-nf-conntrack6 (5.4.225-1) to root...
Downloading file:packages/kmod-nf-conntrack6_5.4.225-1_aarch64_cortex-a72.ipk
Installing kmod-nf-nat (5.4.225-1) to root...
Downloading file:packages/kmod-nf-nat_5.4.225-1_aarch64_cortex-a72.ipk
Installing kmod-ipt-nat (5.4.225-1) to root...
Downloading file:packages/kmod-ipt-nat_5.4.225-1_aarch64_cortex-a72.ipk
Package fstools (2021-01-04-c53b1882-1) installed in root is up to date.
Installing ip6tables (1.8.7-1) to root...
Downloading file:packages/ip6tables_1.8.7-1_aarch64_cortex-a72.ipk
Installing kmod-nf-reject6 (5.4.225-1) to root...
Downloading file:packages/kmod-nf-reject6_5.4.225-1_aarch64_cortex-a72.ipk
Installing kmod-nf-ipt6 (5.4.225-1) to root...
Downloading file:packages/kmod-nf-ipt6_5.4.225-1_aarch64_cortex-a72.ipk
Installing kmod-ip6tables (5.4.225-1) to root...
Downloading file:packages/kmod-ip6tables_5.4.225-1_aarch64_cortex-a72.ipk
Installing iptables (1.8.7-1) to root...
Downloading file:packages/iptables_1.8.7-1_aarch64_cortex-a72.ipk
Package iptables (1.8.7-1) installed in root is up to date.
Installing iwinfo (2022-08-19-0dad3e66-1) to root...
Downloading file:packages/iwinfo_2022-08-19-0dad3e66-1_aarch64_cortex-a72.ipk
Installing libiwinfo-data (2022-08-19-0dad3e66-1) to root...
Downloading file:packages/libiwinfo-data_2022-08-19-0dad3e66-1_aarch64_cortex-a72.ipk
Installing libiwinfo20210430 (2022-08-19-0dad3e66-1) to root...
Downloading file:packages/libiwinfo20210430_2022-08-19-0dad3e66-1_aarch64_cortex-a72.ipk
Package kernel (5.4.225-1-92b7b9c4282a058a5ef043e8abcd8576) installed in root is up to date.
Installing kmod-brcmfmac (5.4.225+5.10.157-1-1) to root...
Downloading file:packages/kmod-brcmfmac_5.4.225%2b5.10.157-1-1_aarch64_cortex-a72.ipk
Installing iw (5.9-8fab0c9e-3) to root...
Downloading file:packages/iw_5.9-8fab0c9e-3_aarch64_cortex-a72.ipk
Installing wireless-regdb (2022.08.12-1) to root...
Downloading file:packages/wireless-regdb_2022.08.12-1_all.ipk
Installing kmod-cfg80211 (5.4.225+5.10.157-1-1) to root...
Downloading file:packages/kmod-cfg80211_5.4.225%2b5.10.157-1-1_aarch64_cortex-a72.ipk
Installing kmod-brcmutil (5.4.225+5.10.157-1-1) to root...
Downloading file:packages/kmod-brcmutil_5.4.225%2b5.10.157-1-1_aarch64_cortex-a72.ipk
Installing kmod-mmc (5.4.225-1) to root...
Downloading file:packages/kmod-mmc_5.4.225-1_aarch64_cortex-a72.ipk
Installing kmod-nls-base (5.4.225-1) to root...
Downloading file:packages/kmod-nls-base_5.4.225-1_aarch64_cortex-a72.ipk
Installing kmod-usb-core (5.4.225-1) to root...
Downloading file:packages/kmod-usb-core_5.4.225-1_aarch64_cortex-a72.ipk
Installing brcmfmac-firmware-usb (20211216-1) to root...
Downloading file:packages/brcmfmac-firmware-usb_20211216-1_aarch64_cortex-a72.ipk
Installing kmod-fs-vfat (5.4.225-1) to root...
Downloading file:packages/kmod-fs-vfat_5.4.225-1_aarch64_cortex-a72.ipk
Installing kmod-nls-cp437 (5.4.225-1) to root...
Downloading file:packages/kmod-nls-cp437_5.4.225-1_aarch64_cortex-a72.ipk
Installing kmod-nls-iso8859-1 (5.4.225-1) to root...
Downloading file:packages/kmod-nls-iso8859-1_5.4.225-1_aarch64_cortex-a72.ipk
Installing kmod-nls-utf8 (5.4.225-1) to root...
Downloading file:packages/kmod-nls-utf8_5.4.225-1_aarch64_cortex-a72.ipk
Installing kmod-ipt-offload (5.4.225-1) to root...
Downloading file:packages/kmod-ipt-offload_5.4.225-1_aarch64_cortex-a72.ipk
Installing kmod-nf-flow (5.4.225-1) to root...
Downloading file:packages/kmod-nf-flow_5.4.225-1_aarch64_cortex-a72.ipk
Package kmod-nls-cp437 (5.4.225-1) installed in root is up to date.
Package kmod-nls-iso8859-1 (5.4.225-1) installed in root is up to date.
Installing kmod-usb-hid (5.4.225-1) to root...
Downloading file:packages/kmod-usb-hid_5.4.225-1_aarch64_cortex-a72.ipk
Installing kmod-input-core (5.4.225-1) to root...
Downloading file:packages/kmod-input-core_5.4.225-1_aarch64_cortex-a72.ipk
Installing kmod-input-evdev (5.4.225-1) to root...
Downloading file:packages/kmod-input-evdev_5.4.225-1_aarch64_cortex-a72.ipk
Installing kmod-hid (5.4.225-1) to root...
Downloading file:packages/kmod-hid_5.4.225-1_aarch64_cortex-a72.ipk
Installing kmod-hid-generic (5.4.225-1) to root...
Downloading file:packages/kmod-hid-generic_5.4.225-1_aarch64_cortex-a72.ipk
Package libc (1.1.24-3) installed in root is up to date.
Package libgcc1 (8.4.0-3) installed in root is up to date.
Unknown package 'libustream-wolfssl'.
Installing logd (2020-10-25-9ef88681-2) to root...
Downloading file:packages/logd_2020-10-25-9ef88681-2_aarch64_cortex-a72.ipk
Installing mkf2fs (1.14.0-1) to root...
Downloading file:packages/mkf2fs_1.14.0-1_aarch64_cortex-a72.ipk
Installing libf2fs6 (1.14.0-1) to root...
Downloading file:packages/libf2fs6_1.14.0-1_aarch64_cortex-a72.ipk
Installing mtd (26) to root...
Downloading file:packages/mtd_26_aarch64_cortex-a72.ipk
Package netifd (2021-07-26-440eb064-1) installed in root is up to date.
Installing odhcp6c (2021-01-09-53f07e90-16) to root...
Downloading file:packages/odhcp6c_2021-01-09-53f07e90-16_aarch64_cortex-a72.ipk
Installing odhcpd-ipv6only (2021-07-18-bc9d317f-3) to root...
Downloading file:packages/odhcpd-ipv6only_2021-07-18-bc9d317f-3_aarch64_cortex-a72.ipk
Installing opkg (2021-06-13-1bf042dd-2) to root...
Downloading file:packages/opkg_2021-06-13-1bf042dd-2_aarch64_cortex-a72.ipk
Installing libuclient20201210 (2021-05-14-6a6011df-1) to root...
Downloading file:packages/libuclient20201210_2021-05-14-6a6011df-1_aarch64_cortex-a72.ipk
Installing uclient-fetch (2021-05-14-6a6011df-1) to root...
Downloading file:packages/uclient-fetch_2021-05-14-6a6011df-1_aarch64_cortex-a72.ipk
Installing partx-utils (2.36.1-2) to root...
Downloading file:packages/partx-utils_2.36.1-2_aarch64_cortex-a72.ipk
Installing libsmartcols1 (2.36.1-2) to root...
Downloading file:packages/libsmartcols1_2.36.1-2_aarch64_cortex-a72.ipk
Installing ppp (2.4.8.git-2020-10-03-3) to root...
Downloading file:packages/ppp_2.4.8.git-2020-10-03-3_aarch64_cortex-a72.ipk
Installing kmod-lib-crc-ccitt (5.4.225-1) to root...
Downloading file:packages/kmod-lib-crc-ccitt_5.4.225-1_aarch64_cortex-a72.ipk
Installing kmod-slhc (5.4.225-1) to root...
Downloading file:packages/kmod-slhc_5.4.225-1_aarch64_cortex-a72.ipk
Installing kmod-ppp (5.4.225-1) to root...
Downloading file:packages/kmod-ppp_5.4.225-1_aarch64_cortex-a72.ipk
Installing ppp-mod-pppoe (2.4.8.git-2020-10-03-3) to root...
Downloading file:packages/ppp-mod-pppoe_2.4.8.git-2020-10-03-3_aarch64_cortex-a72.ipk
Installing kmod-pppox (5.4.225-1) to root...
Downloading file:packages/kmod-pppox_5.4.225-1_aarch64_cortex-a72.ipk
Installing kmod-pppoe (5.4.225-1) to root...
Downloading file:packages/kmod-pppoe_5.4.225-1_aarch64_cortex-a72.ipk
Installing procd (2021-03-08-2cfc26f8-2) to root...
Downloading file:packages/procd_2021-03-08-2cfc26f8-2_aarch64_cortex-a72.ipk
Installing libjson-script20210516 (2021-05-16-b14c4688-2) to root...
Downloading file:packages/libjson-script20210516_2021-05-16-b14c4688-2_aarch64_cortex-a72.ipk
Installing uci (2021-04-14-4b3db117-5) to root...
Downloading file:packages/uci_2021-04-14-4b3db117-5_aarch64_cortex-a72.ipk
Package uclient-fetch (2021-05-14-6a6011df-1) installed in root is up to date.
Installing urandom-seed (3) to root...
Downloading file:packages/urandom-seed_3_aarch64_cortex-a72.ipk
Installing getrandom (2020-10-25-9ef88681-2) to root...
Downloading file:packages/getrandom_2020-10-25-9ef88681-2_aarch64_cortex-a72.ipk
Installing wpad-basic-wolfssl (2020-06-08-5a8b3662-41) to root...
Downloading file:packages/wpad-basic-wolfssl_2020-06-08-5a8b3662-41_aarch64_cortex-a72.ipk
Installing hostapd-common (2020-06-08-5a8b3662-41) to root...
Downloading file:packages/hostapd-common_2020-06-08-5a8b3662-41_aarch64_cortex-a72.ipk
Installing libwolfssl5.5.3.99a5b54a (5.5.3-stable-1) to root...
Downloading file:packages/libwolfssl5.5.3.99a5b54a_5.5.3-stable-1_aarch64_cortex-a72.ipk
Configuring libnl-tiny1.
Configuring libubox20210516.
Configuring libuci20130104.
Configuring libubus20210630.
Configuring libiwinfo-data.
Configuring libiwinfo20210430.
Configuring iwinfo.
Configuring libpthread.
Configuring librt.
Configuring libuuid1.
Configuring libf2fs6.
Configuring mkf2fs.
Configuring libuclient20201210.
Configuring uclient-fetch.
Configuring opkg.
Configuring kmod-nls-base.
Configuring kmod-usb-core.
Configuring libjson-c5.
Configuring libblobmsg-json20210516.
Configuring ubusd.
Configuring ubus.
Configuring iw.
Configuring jsonfilter.
Configuring busybox.
Configuring kmod-nfnetlink.
Configuring kmod-nf-reject6.
Configuring kmod-nf-conntrack.
Configuring kmod-nf-flow.
Configuring kmod-lib-crc-ccitt.
Configuring getrandom.
Configuring libwolfssl5.5.3.99a5b54a.
Configuring kmod-slhc.
Configuring kmod-ppp.
Configuring kmod-pppox.
Configuring kmod-pppoe.
Configuring hostapd-common.
Configuring wpad-basic-wolfssl.
Configuring kmod-nf-reject.
Configuring kmod-nf-ipt.
Configuring kmod-ipt-core.
Configuring kmod-ipt-conntrack.
Configuring jshn.
Configuring netifd.
Configuring usign.
Configuring openwrt-keyring.
Configuring ubox.
Configuring fstools.
Configuring fwtool.
Configuring base-files.
Configuring kmod-nf-nat.
Configuring kmod-input-core.
Configuring libjson-script20210516.
Configuring libblkid1.
Configuring libsmartcols1.
Configuring partx-utils.
Configuring procd.
Configuring libnfnetlink0.
Configuring kmod-nf-conntrack-netlink.
Configuring libmnl0.
Configuring libnetfilter-conntrack3.
Configuring kmod-input-evdev.
Configuring kmod-hid.
Configuring kmod-hid-generic.
Configuring kmod-usb-hid.
Configuring libxtables12.
Configuring kmod-nls-cp437.
Configuring kmod-nls-iso8859-1.
Configuring kmod-nls-utf8.
Configuring kmod-fs-vfat.
Configuring libip4tc2.
Configuring libip6tc2.
Configuring kmod-nf-conntrack6.
Configuring kmod-ipt-nat.
Configuring firewall.
Configuring kmod-mmc.
Configuring kmod-nf-ipt6.
Configuring kmod-ip6tables.
Configuring odhcp6c.
Configuring cypress-firmware-43455-sdio.
Configuring uci.
Configuring dropbear.
Configuring libgmp10.
Configuring mtd.
Configuring odhcpd-ipv6only.
Configuring wireless-regdb.
Configuring kmod-cfg80211.
Configuring kmod-brcmutil.
Configuring brcmfmac-firmware-usb.
Configuring kmod-brcmfmac.
Configuring urandom-seed.
Configuring libcomerr0.
Configuring ppp.
Configuring libnettle8.
Configuring logd.
Configuring iptables.
Configuring libss2.
Configuring libext2fs2.
Configuring e2fsprogs.
Configuring cypress-nvram-43455-sdio-rpi-4b.
Configuring kmod-ipt-ipset.
Configuring ip6tables.
Configuring ca-bundle.
Configuring kmod-ipt-offload.
Configuring ppp-mod-pppoe.
Configuring dnsmasq-full.
Collected errors:
 * opkg_install_cmd: Cannot install package libustream-wolfssl.
make[2]: *** [Makefile:167: package_install] Error 255
make[1]: *** [Makefile:122: _call_image] Error 2
make: *** [Makefile:240: image] Error 2

  - OpenMPTCProuter version: 0.59
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter VPS provider:
  - OpenMPTCProuter platform: rpi-cm4

**Comment by Ysurac** [comment]
Custom build are not supported.
And you should follow the doc : https://github.com/Ysurac/openmptcprouter/wiki/Create-image-for-unsupported-platform
You can also check the workflow used for github action: https://github.com/Ysurac/openmptcprouter-feeds/blob/develop/.github/workflows/main.yml
