### ISSUE TITLE
vps doesn't install on amazon aws ec2

### ISSUE THREAD

**Issue by rdmitry0911** [Ysurac/openmptcprouter#2788]
## Expected Behavior

After installing and final rebooting vps is up and running
## Current Behavior

After installing vps on basic t2.micro instance in amazon aws ec2 with ubuntu server 20.04 and rebooting I can't connect to the instance neither via ssh nor via session manager. Looks like system hangs on booting
## Specifications

  - OpenMPTCProuter version: n/a
  - OpenMPTCProuter VPS version: OpenMPTCProuter Server 0.1028
  - OpenMPTCProuter VPS provider: amazon aws ec2
  - OpenMPTCProuter platform:  x86_64

**Comment by Ysurac** [comment]
Make sure you opened ports range on AWS firewall. SSH should then be accessible via port 65222.

**Comment by rdmitry0911** [comment]
The port range 0-65535 is opened for both tcp and udp. icmp all protocols is allowed as well according to recommendations for aws from [here](https://github.com/Ysurac/openmptcprouter/wiki/Install-or-update-the-VPS)

**Comment by rdmitry0911** [comment]
> ## Expected Behavior
> 
> After installing and final rebooting vps is up and running
> ## Current Behavior
> 
> After installing vps on basic t2.micro instance in amazon aws ec2 with ubuntu server 20.04 and rebooting I can't connect to the instance neither via ssh nor via session manager. Looks like system hangs on booting
> ## Specifications
> 
>     * OpenMPTCProuter version: n/a
> 
>     * OpenMPTCProuter VPS version: OpenMPTCProuter Server 0.1028
> 
>     * OpenMPTCProuter VPS provider: amazon aws ec2
> 
>     * OpenMPTCProuter platform:  x86_64

I've just checked and it tuned out that UPSTREAM version of vps works in Amazon aws. I would add a note in the vps installation guide about this.

**Comment by Ysurac** [comment]
Upstream release only work with OpenMPTCProuter 5.15/6.1 based release that are in test.

**Comment by rdmitry0911** [comment]
> Upstream release only work with OpenMPTCProuter 5.15/6.1 based release that are in test.

What is the difference between upstream and regular release, that prevents the system from booting up in amazon aws?

**Comment by rdmitry0911** [comment]
> Upstream release only work with OpenMPTCProuter 5.15/6.1 based release that are in test.

BTW, debian 11 regular vps install script works fine in amazon aws Only ubuntu 20.04 has problems so far.
