### ISSUE TITLE
VPS install stop nofirewall.patch - Not Found

### ISSUE THREAD

**Issue by RoFiTech** [Ysurac/openmptcprouter#2789]
## Current Behavior

The Install on VPS stop due to failed download for nofirewall.patch.

## Steps to Reproduce the Problem

  1. Debian 11 VPS
  2. run wget -O - http://www.openmptcprouter.com/server/debian-x86_64.sh | UPSTREAM="yes" sh

## Context (Environment)

HEAD is now at 3b99d2e Bump
--2023-03-04 10:34:26--  https://github.com/Ysurac/openmptcprouter-feeds/raw/develop/dsvpn/patches/nofirewall.patch
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-03-04 10:34:27 ERROR 404: Not Found.

## Specifications

  - OpenMPTCProuter version: 0.59.1
  - OpenMPTCProuter VPS version: 0.59.1
  - OpenMPTCProuter VPS provider: Netcup
  - OpenMPTCProuter platform: x86_64 - Proxmox
  - Country: Austria

**Comment by Ysurac** [comment]
Fixed

**Comment by RoFiTech** [comment]
thank you!
