### ISSUE TITLE
OpenMPTCPRouter user

### ISSUE THREAD

**Issue by slipperyrails** [Ysurac/openmptcprouter#2798]
## Expected Behavior
Run server side install debian-x86_64.sh; reboot VPS.
Copy ***openmptcprouter_config.txt***
Edit settings on client side OpenMPTCPRouter Wizard
Username: openmptcprouter
Expected behavior, user `openmptcprouter` will be created on VPS?

## Current Behavior
User `openmptcprouter` does not exist on server 
Also: user.notice OMR-VPS: Can't get vps token, try later (can ping server vps on xx.xx.xx.xx, no server API answer on xx.xx.xx.xx, custom username)
Simply trying to connect the dots

## Specifications
  - OpenMPTCProuter version: openmptcprouter v0.59.1-5.4 r0+16594-ce92de8c8c
  - OpenMPTCProuter VPS version: OpenMPTCProuter Server 0.1028
  - OpenMPTCProuter VPS provider: Google Cloud
  - OpenMPTCProuter platform: x86_64
`uname -a`
Linux instance-1 5.4.207-mptcp #1 SMP Sun Jul 24 14:39:44 UTC 2022 x86_64 GNU/Linux

**Comment by Ysurac** [comment]
User "openmptcprouter" is a VPS API user.
Check that you use use correct server key.
