### ISSUE TITLE
Add a way to update

### ISSUE THREAD

**Issue by Ysurac** [Ysurac/openmptcprouter#28]
Add an easy way to update OpenMPTCProuter and OpenMPTCProuter VPS script.

**Comment by lars18th** [comment]
Hi @Ysurac ,

Perhaps, the first goal can be a simple "backup/restore of config" (for both, the client and the VPS server). This will simplifies a lot any manual upgrade.

Regards.

**Comment by nicoz76** [comment]
Bonjour,  je rebondis sur cette fonctionnalités qui serait la bienvenue.

coté VPS ,  quand une nouvelle release sort,  il faut  réinstaller complétement le VPS et relancer le script ,  ou bien  seulement relancer le script ?


bon travail Ysurac.
