### ISSUE TITLE
Extreme CPU Usage omr-admin.py

### ISSUE THREAD

**Issue by aquafix** [Ysurac/openmptcprouter#2801]
## Expected Behavior
lower cpu usage

## Current Behavior
script seems to constantly restart and can consume up to 80% cpu accross 3vcpu at 2.6ghz... ssd nvme,
i disabled v2ray and shadowsocks obsfucation/encryption but it still seems to be rather high hitting some 60%.

I resolved all errors thrown via tail -f /var/log/syslog and would like to know some more specifics as to why this might be happening without having to dive into the .py itself.

## Specifications

  - OpenMPTCProuter VPS version: < OpenMPTCProuter VPS 0.1028 >

  - OpenMPTCProuter VPS provider: ubuntu
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
What is the VPS provider ?
Debian is far more tested than Ubuntu.
