### ISSUE TITLE
ISP block traceroute

### ISSUE THREAD

**Issue by kapook007** [Ysurac/openmptcprouter#281]
Some isp block traceroute .

C:\Users\goo>ping google.com
Pinging google.com [172.217.31.78] with 32 bytes of data:
Reply from 172.217.31.78: bytes=32 time=73ms TTL=49
Reply from 172.217.31.78: bytes=32 time=63ms TTL=49

C:\Users\goo>tracert google.com
Tracing route to google.com [172.217.31.78]
over a maximum of 30 hops:
  1    24 ms    18 ms    18 ms  www.huaweimobilewifi.com [192.168.15.1]
  2     *        *        *     Request timed out.
  3     *        *        *     Request timed out.
  4     *        *        *     Request timed out.

in openmptcp status this wan show old ipaddress  not present ipaddress and no error status 
this wan can connet shadowsock  at port 65101

but shadowsock can not run on this wan .

v0.44.5    vps0.80

**Comment by Ysurac** [comment]
Seems strange that ping is working and traceroute not working...
This shouldn't make problems for ShadowSocks, but shadowsocks can be detected and blocked when used without obfs.
WAN IP address is updated every hours only.
