### ISSUE TITLE
RPI4 only Radio0 is visible 

### ISSUE THREAD

**Issue by iamdivyanshverma** [Ysurac/openmptcprouter#2813]
## Current Behavior

Hi @Ysurac , Im using RPI4 , for wireless only 1 radio is available that is Radio0 , i cannot find Radio1 in the wireless section ..
I did check dmesg an i can see 3 nodes getting detected that is :-

1). mmc1:0001:1 (for wifi)
2). mmc1:0001:2 (for wifi)
3). mmc1:0001:3 (for BT)

********************************************************************************************
********************************************************************************************

root@OpenMPTCProuter:~# dmesg | grep brcm
[    0.104449] brcm-pcie fd500000.pcie: host bridge /scb/pcie@7d500000 ranges:
[    0.104477] brcm-pcie fd500000.pcie:   No bus range found for /scb/pcie@7d500000, using [bus 00-ff]
[    0.104514] brcm-pcie fd500000.pcie:      MEM 0x0600000000..0x0603ffffff -> 0x00f8000000
[    0.104547] brcm-pcie fd500000.pcie:   IB MEM 0x0000000000..0x00ffffffff -> 0x0400000000
[    0.170428] brcm-pcie fd500000.pcie: link up, 5 GT/s x1 (SSC)
[    0.170581] brcm-pcie fd500000.pcie: PCI host bridge to bus 0000:00
**_[   10.861098] brcmfmac mmc1:0001:1: no of_node; not parsing pinctrl DT
[   10.861193] brcmfmac mmc1:0001:2: no of_node; not parsing pinctrl DT**__**
[   10.864556] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
[   11.132509] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
[   11.146617] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM4345/6 wl0: Apr 15 2021 03:03:20 version 7.45.234 (4ca95bb CY) FWID 01-996384e2
**_[   11.182040] brcmfmac mmc1:0001:3: no of_node; not parsing pinctrl DT_**
[   11.182173] usbcore: registered new interface driver brcmfmac

*********************************************************************************************
*********************************************************************************************

so if i check in /sys/devices***** for mmc1:0001:1,  i can see phy got register

root@OpenMPTCProuter:/sys/devices/platform/soc/fe300000.mmcnr/mmc_host/mmc1/mmc1:0001/mmc1:0001:1# ls -lah
drwxr-xr-x    5 root     root           0 Jan  1  1970 .
drwxr-xr-x    6 root     root           0 Jan  1  1970 ..
-r--r--r--    1 root     root        4.0K May 17 22:29 class
--w-------    1 root     root        4.0K May 17 22:29 coredump
-r--r--r--    1 root     root        4.0K May 17 22:11 device
lrwxrwxrwx    1 root     root           0 May 17 22:11 driver -> ../../../../../../../../bus/sdio/drivers/brcmfmac
drwxr-xr-x    3 root     root           0 May 17 22:11 ieee80211
-r--r--r--    1 root     root        4.0K May 17 22:29 modalias
drwxr-xr-x    3 root     root           0 May 17 22:11 net
drwxr-xr-x    2 root     root           0 May 17 22:29 power
lrwxrwxrwx    1 root     root           0 May 17 22:11 subsystem -> ../../../../../../../../bus/sdio
-rw-r--r--    1 root     root        4.0K May 17 22:29 uevent
-r--r--r--    1 root     root        4.0K May 17 22:11 vendor

But if i check in /sys/devices***** for mmc1:0001:2,  nothing got register

root@OpenMPTCProuter:/sys/devices/platform/soc/fe300000.mmcnr/mmc_host/mmc1/mmc1:0001/mmc1:0001:2# ls -lah
drwxr-xr-x    3 root     root           0 Jan  1  1970 .
drwxr-xr-x    6 root     root           0 Jan  1  1970 ..
-r--r--r--    1 root     root        4.0K May 17 22:30 class
--w-------    1 root     root        4.0K May 17 22:30 coredump
-r--r--r--    1 root     root        4.0K May 17 22:30 device
lrwxrwxrwx    1 root     root           0 May 17 22:30 driver -> ../../../../../../../../bus/sdio/drivers/brcmfmac
-r--r--r--    1 root     root        4.0K May 17 22:30 modalias
drwxr-xr-x    2 root     root           0 May 17 22:30 power
lrwxrwxrwx    1 root     root           0 May 17 22:30 subsystem -> ../../../../../../../../bus/sdio
-rw-r--r--    1 root     root        4.0K May 17 22:30 uevent
-r--r--r--    1 root     root        4.0K May 17 22:30 vendor

## Expected Behaviour
I want to use 2 Radios with 2 different SSID's 

## Specifications

  - OpenMPTCProuter version: 0.59rc3
  - OpenMPTCProuter VPS version: 0.1027
  - OpenMPTCProuter VPS provider: Digital Ocean
  - OpenMPTCProuter platform: RPI4
  - Country: India

**Comment by Ysurac** [comment]
RPI chipset doesn't allow dual band or multi mode and have very low capacity.
