### ISSUE TITLE
Random slow performance, reboot solves it.

### ISSUE THREAD

**Issue by IVCrossway** [Ysurac/openmptcprouter#2815]
## Expected Behavior
Boding speed should be around 160 down - 40 up.

## Current Behavior
Download speed is about 30/40 mbps, upload is terrible 1~5mbps.
Rebooting OMR solves the problem.
This happened before, but only once/twice a month. But in the last period it's becoming more frequent.

## Specifications

  - OpenMPTCProuter version: 0.59.1-5.4
  - OpenMPTCProuter VPS version: 0.1028 5.4.207-mptcp
  - OpenMPTCProuter VPS provider: Aruba (Italy)
  - OpenMPTCProuter platform: Lenovo ThinkCenter Tiny M710q

Log file: https://pastebin.com/0hKkTRge

![1a](https://user-images.githubusercontent.com/81245485/230651208-7e9da94b-2c55-4dec-9545-2a34c46105a4.PNG)
![2a](https://user-images.githubusercontent.com/81245485/230651210-769da624-c031-4b21-97e0-85421845b6af.PNG)
![3a](https://user-images.githubusercontent.com/81245485/230651216-505d0dee-b441-496c-a23d-360cc15ce95b.PNG)
![4a](https://user-images.githubusercontent.com/81245485/230651224-60d37e15-32a2-4519-bda9-4d7d8bf5ce84.PNG)
![6a](https://user-images.githubusercontent.com/81245485/230651241-4ce9004e-0589-4d10-9b8d-70c3119b06ba.PNG)
![7a](https://user-images.githubusercontent.com/81245485/230651398-524dc74e-c850-44ae-9d64-88c6a440da1c.PNG)

**Comment by Ysurac** [comment]
This is the issue:
```
MPTCP: out of memory: force closing socket
Fri Apr  7 17:18:14 2023 kern.info kernel: [165709.321383] TCP: too many orphaned sockets
```
Do you use some p2p or anything that can create many connections ?
How much RAM do you have ?

**Comment by IVCrossway** [comment]
> 

The only "intensive" network activity I do is sync files from my pc to Onedrive using Rclone, but it only transfers 4 files at a time. The mini pc hosting OMR is equipped with 4gb of ram

**Comment by winkmichael** [comment]
Are you out of memory, can you create a swap drive?

**Comment by IVCrossway** [comment]
Yes, I've got plenty of ssd space free to create a swap file, but the problem is that when this happens the ram is not even full... I've never seen OMR using more than 1GB of ram

**Comment by Ysurac** [comment]
Via SSH on the router, what is the result of ```sysctl net.ipv4.tcp_mem```, ```sysctl net.ipv4.tcp_max_orphans```, ```sysctl net.ipv4.tcp_keepalive_time```, ```net.ipv4.tcp_keepalive_intvl``` and ```sysctl net.ipv4.tcp_keepalive_probes``` ?

**Comment by IVCrossway** [comment]
```
root@omr:~# sysctl net.ipv4.tcp_mem
net.ipv4.tcp_mem = 8092 131072  67108864
```

```
root@omr:~# sysctl net.ipv4.tcp_max_orphans
net.ipv4.tcp_max_orphans = 16384
```

```
root@omr:~# sysctl net.ipv4.tcp_keepalive_time
net.ipv4.tcp_keepalive_time = 7200
```

```
root@omr:~# sysctl net.ipv4.tcp_keepalive_intvl
net.ipv4.tcp_keepalive_intvl = 75
```

```
root@omr:~# sysctl net.ipv4.tcp_keepalive_probes
net.ipv4.tcp_keepalive_probes = 9
```
