### ISSUE TITLE
Create image for unsupported platform  

### ISSUE THREAD

**Issue by lkx2023** [Ysurac/openmptcprouter#2817]
## Expected Behavior
i want to Create image for unsupported platform by 'https://github.com/Ysurac/openmptcprouter/wiki/Create-image-for-unsupported-platform'.

## Current Behavior
There is an error after entering this command：{ OMR_TARGET="rpi4" OMR_FEED_SRC="master" ./build.sh }. the error is { fatal: unable to access 'https://github.com/openwrt/openwrt/': gnutls_handshake() failed: Error in the pull function} 

## Specifications

  - OpenMPTCProuter version: v0.59.1
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter VPS provider:
  - OpenMPTCProuter platform: RPI4

**Comment by Ysurac** [comment]
You have a problem on your compile platform that can't access https://github.com

You can try to update the system.
