### ISSUE TITLE
Support For Ralink 3062F

### ISSUE THREAD

**Issue by eyramm** [Ysurac/openmptcprouter#2819]
## Expected Behavior
I have a number of Ethernet PCI Cards installed on my desktop which is running OMR
When I added a Wireless PCI Card running on Ralink 3062F Chipset, it fails to show in OMR. 

## Current Behavior
I'm unable to use my Ralink 3062F PCI Wireless Card for OMR. It doesn't show it detect

## Specifications

I have a guide on how to install it (https://askubuntu.com/questions/84959/how-do-i-get-a-ralink-rt3060-wireless-card-working)
But I can't because make, apt, an some other packages are not working.

**Comment by Ysurac** [comment]
OpenMPTCProuter is based on OpenWRT, not ubuntu, you need to install "kmod-rt2x00-pci" package via System->Software. Press "Update lists..." button to download the list of available packages.
