### ISSUE TITLE
Server Keeps disconnecting after multiple reboot

### ISSUE THREAD

**Issue by iamdivyanshverma** [Ysurac/openmptcprouter#2820]
## Current Behavior
Hi @Ysurac , I have noticed that my server gets disconnected automatically. I tried pinging the public IP but no response if i reboot the server from the console ping comes back but not staying for long, but when I try to access the server from the console sometimes I am able to log in sometimes not. I am using Digital Ocean & Vulture on both servers I am noticing this issue for 1 week.

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - OpenMPTCProuter version: 0.59rc3
  - OpenMPTCProuter VPS version: 0.1027
  - OpenMPTCProuter VPS provider: Digital Ocean
  - OpenMPTCProuter platform: RPI4
  - Country: India

**Comment by Ysurac** [comment]
Do you have a kernel panic on the VPS ? Can you try to login via provider console ?
You should update VPS and router.
I own a VPS in Digital Ocean and one at Vultr and I have no problems for now. They are installed under Debian 11 ?
