### ISSUE TITLE
4 or 5G USB dongle

### ISSUE THREAD

**Issue by djatomix** [Ysurac/openmptcprouter#2822]
Good morning

I'm currently looking for a 4G or 5G USB dongle to add to the OMR setup I just ran in x86_64. 
(if possible, on Amazon FR shop)

I saw the EM7565 modules: https://www.amazon.fr/gp/product/B0BQFNQQMW/ref=ox_sc_act_title_1?smid=A2GY03IJEBMI1H&psc=1
and this box: https://www.amazon.fr/gp/product/B09HY1XSWF/ref=ox_sc_act_title_5?smid=A2GNN9CKTV5QUI&psc=1

What do you think ?

Thanks in advance.

(sorry for my English, I go through a translator...)

  - OpenMPTCProuter version: v0.59.1-5.4-r0+16594
  - OpenMPTCProuter VPS provider: OVH
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
I have no idea about these. 
I have an old Huawei E5186s-22a and some Huawei E8372h-155 USB dongle. Both are working correctly in France.

**Comment by ZonaLTE** [comment]
I made such a board, and I'm trying various modems...
![IMG_9930](https://user-images.githubusercontent.com/131384644/233415891-3faf42b1-46c4-455c-8a37-abdc6951a222.JPG)

**Comment by dfadev** [comment]
I use two of these:
https://www.aliexpress.us/item/3256804396044925.html

These probably work too:
https://www.aliexpress.us/item/3256804442228703.html
