### ISSUE TITLE
shadowsocks v2ray plugin is missing in OMR 0.59.2 alpha

### ISSUE THREAD

**Issue by Kalimeiro** [Ysurac/openmptcprouter#2828]
## Specifications

  - OpenMPTCProuter version: 0.59.2 ALPHA release 25/04/2023
  - OpenMPTCProuter VPS version: 0.1029-test
  - OpenMPTCProuter VPS provider: OVH
  - OpenMPTCProuter platform: x86_64
  - Country: FR

![image](https://user-images.githubusercontent.com/8118989/234153732-899f4fad-8a92-440f-9708-65b1ea3e23f4.png)

**Comment by Ysurac** [comment]
v2ray-plugin will not be available on next release.

**Comment by kmrinal** [comment]
@Ysurac Does that mean UDP traffic will be handled differently now?
