### ISSUE TITLE
Multipath stopped working after vps provider change

### ISSUE THREAD

**Issue by 701789262a** [Ysurac/openmptcprouter#2829]
## Expected behaviour:
When the VPS server is changed, everything should work like before.

## Current Behavior
OpenMPTCP router seems to ignore one WAN connection or the other, like in failover mode, but MPTCP is enabled and both connection are enabled.
If I disable one WAN network, it continue to use that network until a reboot is issued or the config for that connection are invalidated and only then it starts working on the other WAN network

## Specifications

  - OpenMPTCProuter version: v0.59.1
  - OpenMPTCProuter VPS version: 0.1028
  - OpenMPTCProuter VPS provider: SeFlow
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
What you mean by VPS provider change ?
