### ISSUE TITLE
Issue Port Forward

### ISSUE THREAD

**Issue by bran2000** [Ysurac/openmptcprouter#283]
<img width="624" alt="capture" src="https://user-images.githubusercontent.com/9639346/50545578-739e1880-0c18-11e9-93f8-983e48058509.PNG">
<img width="629" alt="capture2" src="https://user-images.githubusercontent.com/9639346/50545579-7436af00-0c18-11e9-8a12-f87809d4216d.PNG">

  Hi,

Firstable, thanks for your work ! it's amazing !
Last thing, i met a problem to access outside to my synology nas with my public ip (VPS OVH) : 5x.XX.XX.XX and the port 5000

When i did this with my browser : http://5x.XX.XX.XX:5000 it's not working, i have the message time out.

i followed your [tutorial](https://github.com/Ysurac/openmptcprouter/wiki/OpenMPTCProuter-configuration) it's not working 

  1. Forward to	Enable	
IPv4-tcp
From any host in vpn
Via any router IP at port 5000	
IP 192.168.100.57, port 5000 in lan	
Enable NAT Loopback (untick)

  2. Sources NAT
Any tcp
From any host in vpn
To IP 192.168.100.57, port 5000 in lan	
Rewrite to source IP 192.168.100.1	

For information i rebooted both (the client and the server after changes)

any idea ? i guess i missed something but i don't know where ?

Thanks

## Specifications

  - OpenMPTCProuter version: v0.44.5
  - OpenMPTCProuter VPS version: OpenMPTCProuter VPS 0.81
  - OpenMPTCProuter platform: (RPI3)

**Comment by Ysurac** [comment]
You redirected all ports from VPS to OpenMPTCProuter ? (Use the checkbox in System->OpenMPTCProuter then Advanced settings tab.)

**Comment by bran2000** [comment]
thanks i guess it was this i tick this field : Redirects all ports from VPS to OpenMPTCProuter
one last question : if i want to access to the admin console Openmptcprouteur outside , i guess i shoud do the same but with the port 80 ?

**Comment by Ysurac** [comment]
True, you have to accept input traffic from VPN to port 80 of OpenMPTCProuter in firewall rules.

**Comment by bran2000** [comment]
thanks for your quick reply, can i activate a login/password to access to admin console ?

**Comment by Ysurac** [comment]
Yes in System->Admin

**Comment by bran2000** [comment]
great Thanks for your help again !
