### ISSUE TITLE
0.59.2 alpha is smaller than before?

### ISSUE THREAD

**Issue by fareign** [Ysurac/openmptcprouter#2830]
openmptcprouter-v0.59.2alpha-6.1-r0+22580-e11d00d44c-x86-64-generic-ext4-combined-efi.img.gz   12.3 MiB

openmptcprouter-v0.59.2alpha-5.15-r0+22580-e11d00d44c-x86-64-generic-ext4-combined-efi.img.gz   56.1 MiB

what's happen?

**Comment by Ysurac** [comment]
For now it's only compilation tests.
