### ISSUE TITLE
Script for beta versions?

### ISSUE THREAD

**Issue by iambenmitchell** [Ysurac/openmptcprouter#2834]
If I were to use the beta 6.1 version of OMR from https://snapshots.openmptcprouter.com/6.1/
what script do I use with it? I assume the default one wouldn't work as it is out of date? 

Or do I just use 

wget -O - https://www.openmptcprouter.com/server/debian-x86_64.sh | sh

**Comment by Ysurac** [comment]
For the 6.1: ```wget -O - http://www.openmptcprouter.com/server-test/debian-x86_64.sh | UPSTREAM6="yes" sh```
But it's still in alpha state, for now I'm working on compilation so it's not tested at all.

**Comment by Kalimeiro** [comment]
I'm agree with @Ysurac, for now 6.1 work only with one connection, it not agregate all wan.
