### ISSUE TITLE
Setting up Teltonika RUTX09 for OpenMPTCProuter

### ISSUE THREAD

**Issue by andreamichelon** [Ysurac/openmptcprouter#2835]
## Expected Behavior
Trying to set up two Teltonika RUTX09 to connect to OpenMPTCProuter. I have setup the Teltonika using a static IP and disabling the DHCP.
<img width="585" alt="Screenshot 2023-04-28 at 00 54 21" src="https://user-images.githubusercontent.com/74050120/235036016-bae9aa26-c4f1-479a-8583-ca56d962ae5b.png">

## Current Behavior
On OpenMPTCProuter I get No Server ping response after 1 second. This is how is setup.

![Screenshot 2023-04-28 at 03 01 52](https://user-images.githubusercontent.com/74050120/235036630-0cf6a776-0b45-4ab8-a178-2045569d8203.png)
![Screenshot 2023-04-28 at 03 02 04](https://user-images.githubusercontent.com/74050120/235036639-c0befd96-3617-44ac-bf05-d410c8fdb147.png)

## Specifications

  - OpenMPTCProuter version: v0.59.1-5.4
  - OpenMPTCProuter VPS version: v0.59.1-5.4
  - OpenMPTCProuter VPS provider: DigitalOcean
  - OpenMPTCProuter platform: x86_64

Thank you for your help

**Comment by Ysurac** [comment]
Configuration seems to be ok, make sure "Use default gateway" is disabled in advanced settings tab of interface config.
You should use the wizard to configure interfaces/key/...

**Comment by andreamichelon** [comment]
Hi Yusrac, I managed to solve the issue. It was a wrong setting in the Teltonika.

Now, everything seems to work apart from the VPS, where I get:

Can't get public IP address from ShadowSocks

<img width="520" alt="Screenshot 2023-04-29 at 02 47 10" src="https://user-images.githubusercontent.com/74050120/235277964-8f8631ec-a333-47d8-b7d7-b33689cc271a.png">

I tried to look on the forum for a possible solution, but I couldn't find a straight answer. 
VPS is on a Digital Ocean droplet with a Derbian 11 x68
Version is VPS 0.1028

Can you help? Thank you,

**Comment by Ysurac** [comment]
The VPS kernel is not the good one, did you reboot the VPS after script installation ?

**Comment by andreamichelon** [comment]
Yes, I did. What can I do to give you a better picture of the problem?

**Comment by Ysurac** [comment]
What is the result of ```uname -a``` on the VPS ?

**Comment by Ysurac** [comment]
I just launched the script on a Digital Ocean droplet with Debian 11 x86_64 and after reboot I get the correct kernel: ```Linux debian-s-1vcpu-512mb-10gb-fra1-01 5.4.207-mptcp```

**Comment by andreamichelon** [comment]
Hi Ysurac, sorry for the late reply. Running `uname -a` I get:
`Linux omptcpr-VPS 5.10.0-11-amd64 #1 SMP Debian 5.10.92-2 (2022-02-28) x86_64 GNU/Linux`

**Comment by Ysurac** [comment]
Try to run the VPS install script again.
