### ISSUE TITLE
v2ray-plugin will not be available on next release.

### ISSUE THREAD

**Issue by kmrinal** [Ysurac/openmptcprouter#2837]
v2ray-plugin will not be available on next release.

_Originally posted by @Ysurac in https://github.com/Ysurac/openmptcprouter/issues/2828#issuecomment-1522260057_

@Ysurac Does that mean UDP traffic will be handled differently now?

**Comment by Kalimeiro** [comment]
As has always been the case, UDP goes through the VPN, so through GloryTun.

**Comment by Ysurac** [comment]
v2ray-plugin is only used to obfuscate ShadowSocks traffic. It's not related to v2ray proxy that will still be available.

**Comment by kmrinal** [comment]
Ok, thank you for the clarification @Ysurac .

**Comment by kmrinal** [comment]
@Kalimeiro You can proxy UDP traffic as well, if V2Ray is used for proxy.

**Comment by Kalimeiro** [comment]
> @Kalimeiro You can proxy UDP traffic as well, if V2Ray is used for proxy.

I know, but it's bogus with 0.59.2 alpha.
