### ISSUE TITLE
Version display in router status

### ISSUE THREAD

**Issue by trassiorf** [Ysurac/openmptcprouter#284]
Hi 
Why I have a VPS version on 0.82 after update VPS while status display last version is 0.83 ?
See screenshot 
![capture d ecran-6](https://user-images.githubusercontent.com/10478846/50546555-a43a7e00-0c29-11e9-9ba0-1c880789193e.png)

## Specifications

  - OpenMPTCProuter version: (Last is not a version) 0.44.5
  - OpenMPTCProuter VPS version: (Last is not a version) 0.82
  - OpenMPTCProuter platform: (RPI2/RPI3/x86/x86_64) RPI3 B+

**Comment by Ysurac** [comment]
Because latest version is 0.83 now :)

**Comment by trassiorf** [comment]
Launching the script : # sh debian9-x86_64.sh at 15:52 this day
I stay on version 0.82

**Comment by Ysurac** [comment]
On the VPS you should have version 0.83, even if status is not updated every minutes...

**Comment by trassiorf** [comment]
Well, I did not update the script.
Now the version is 0.83 after the last compilation phase.
Thank you
