### ISSUE TITLE
0.59.2 alpha lost ipv6 when switch to v2ray

### ISSUE THREAD

**Issue by KaleiRo** [Ysurac/openmptcprouter#2840]
## Expected Behavior

ipv6 need to works with v2ray like shadowsocks

## Current Behavior

when switch proxy to v2ray, ipv6 is not reachable. when switch back to shadowsocks, all is ok.

## Possible Solution / Steps to Reproduce the Problem

need to check script, one solution to manually get ipv6 is :

- switch to v2ray
- wait the message 'no ipv6" in "status" page of openmptcprouter
- go to "advanced parameters"
- disable ipv6
- wait all is green on "status" page
- re enable ipv6 on "advanced parameters" and wait few minutes
- ipv6 is ok.

if you reboot, you lost ipv6 and need to disable/enable ipv6 in "advanced parameters" to works.

## Specifications

  - OpenMPTCProuter version: 0.59.2 alpha 02/05/2023
  - OpenMPTCProuter VPS version: 0.1029-test
  - OpenMPTCProuter VPS provider: OVH
  - OpenMPTCProuter platform: RPI4/X86_64
  - Country: FR

**Comment by Ysurac** [comment]
For now, v2ray doesn't work with 6.1 kernel.
And as I already said nothing work at all as it's only compilation tests.

**Comment by Kalimeiro** [comment]
i always use 5.4 kernel. 5.15 and 6.1 not working for me.
