### ISSUE TITLE
2x4g LTE MPTCP

### ISSUE THREAD

**Issue by MuFFkiNs** [Ysurac/openmptcprouter#2843]
-= Expected Behavior=-

Am wanting to boost throughput by using 2x4g networks together, and then passing openMPTCPRouter through OPNSense and onto clients.

 -=Current Behavior=-

Can't seems aggregate the modems, only seeing one modem doing work
System_log Loops the following
Tue May  9 12:06:29 2023 user.notice omr-bypass: OMR-ByPass is running
Tue May  9 12:06:36 2023 daemon.info omr-tracker-ss: Reload Shadowsocks rules
Tue May  9 12:06:36 2023 user.notice Shadowsocks: Rules UP
Tue May  9 12:06:36 2023 user.notice Shadowsocks: Rules not applied
Tue May  9 12:06:36 2023 user.notice Shadowsocks: Reload omr-bypass rules
Tue May  9 12:06:36 2023 user.notice omr-bypass: Starting OMR-ByPass...
Tue May  9 12:06:36 2023 user.notice omr-bypass: OMR-ByPass is running
Tue May  9 12:06:43 2023 daemon.info omr-tracker-ss: Reload Shadowsocks rules
Tue May  9 12:06:43 2023 user.notice Shadowsocks: Rules UP
Tue May  9 12:06:43 2023 user.notice Shadowsocks: Rules not applied
Tue May  9 12:06:43 2023 user.notice Shadowsocks: Reload omr-bypass rules
Tue May  9 12:06:43 2023 user.notice omr-bypass: Starting OMR-ByPass...
Tue May  9 12:06:43 2023 user.notice omr-bypass: OMR-ByPass is running

MPTCP Support check gives the following

Wan1
![MPTCP Support Check WAN 1](https://github.com/Ysurac/openmptcprouter/assets/51464309/83ed9049-15c2-41ed-bc35-595cd3f777f7)

Wan 2
![MPTCP Support Check WAN 2](https://github.com/Ysurac/openmptcprouter/assets/51464309/39eeaeb1-89a8-406d-828b-c04059471bce)

-=Specifications=-

2x4G LTE Modems , both are hewawei B256 65a
Both Data sims are from the same ISP and at times are capable of upto 250/40 each
Btoh Sims use the same APN

OpenMPTCPRouter_v0.59.1-5.4 r0+16594-ce92de8c8c
OMR Running in proxmox from mounted USB 
1x NIC For LAN
1x NIC for WANs

VPS is from VULTr, Debian 11, MPTCP Version 0.1028 15.57

Wan 1 Interface 
![Wan 1 Interface](https://github.com/Ysurac/openmptcprouter/assets/51464309/f40a9fe6-5b58-445f-b19a-f2252eae87ea)

Wan 2 Interface
[](url)
![Wan 2 interface](https://github.com/Ysurac/openmptcprouter/assets/51464309/f9fae1ca-19b2-4c4c-a97d-7435ea816e93)

-=HAVE TRIED=-
Tried running MPTCP through to VPN and various configs, can't recall everything i've tried after a week of on and off fiddling with it.

Would love some insight into if i'm doing something wrong or if it's flat out not possible, by no means a pro so please bear with me, any help is greatly appreciated.

Cheers, Stephen

**Comment by MuFFkiNs** [comment]
After more searching i found that VPS was 5.15 and the router was 5.4, after fixing that up it now works but is quite poor performance say like 140-160/30-40. Will tinker around some more and see how it goes.

**Comment by MuFFkiNs** [comment]
After two weeks of trail and error, i'm give up and dip lol, it's a good idea in theory, just doesn't seem too good with 2x4g LTE, even with the tower 200m line of site, performance is worse than one single 4G LTE and that with the VPS 80km away.

Was plagued with DNS issues, discord and streaming services were no good, tried a few games with no luck at all. Can say i had hella fun doing it though, was good to experiment with the network topology of it all, and i'm sure with the right case scenarios and configs you'd see far better results than i did. But for me i'm heading back to OPNSense and Dual wan, easy to setup, might not boost speeds but its 2x 250/40 over multiple clients and on a 1:1 config it still shares bandwidth over the two data sims. 

Cheers for the experience and much kudos on what this router can do
Stephen

**Comment by EhsanVahab** [comment]
> OPNSense

Hi dear
I have the same problem too.
it seems openmptcprouter is on the experimental stage and still is good just in theory.
I wonder would it be possible to share some links about OPNSense and Dual wan to aggregate two sim cards network data?
I need to stream Sony 4K camera over the internet. could you please share your valuable experince?
