### ISSUE TITLE
4g PCIe HAT Settings

### ISSUE THREAD

**Issue by sedale33** [Ysurac/openmptcprouter#2849]
I'm trying to use 2 PCIe HATs that communicates with the raspberry pi using USB and is powered by the same USB. When connected to the RPi one shows up as wwan0 under Device settings. What are the settings needed to setup the HATs as modems for the OMR?

**Comment by Ysurac** [comment]
By using ModemManager protocol, via the wizard or via Network->Interfaces.

**Comment by sedale33** [comment]
I was able to add the interface using Network -> Interfaces. I'm not seeing a connection to the service provider. Are there other settings that needs to be configured? Do I need to change the settings for wan1/2?
