### ISSUE TITLE
RM520N-GL not show up as /dev/cdc-wdm0

### ISSUE THREAD

**Issue by gizze59** [Ysurac/openmptcprouter#2850]
I try to add a RM520N-GL as USB-modem on my RPI4b running Openmptcprouter 5.4.207-mptcp 0.1028, but it seems I missing some drivers.
#dmesg
[ 6447.863213] usb 2-2: New USB device found, idVendor=2c7c, idProduct=0801, bcdDevice= 5.04
[ 6447.871397] usb 2-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 6447.878538] usb 2-2: Product: RM520N-GL
[ 6447.882365] usb 2-2: Manufacturer: Quectel
[ 6447.886461] usb 2-2: SerialNumber: 611e33db
[ 6447.890824] usb 2-2: no of_node; not parsing pinctrl DT
#usbmode -l

#cat /sys/kernel/debug/usb/devices

T: Bus=02 Lev=01 Prnt=01 Port=01 Cnt=01 Dev#= 2 Spd=5000 MxCh= 0
D: Ver= 3.20 Cls=00(>ifc ) Sub=00 Prot=00 MxPS= 9 #Cfgs= 1
P: Vendor=2c7c ProdID=0801 Rev= 5.04
S: Manufacturer=Quectel
S: Product=RM520N-GL
S: SerialNumber=611e33db
C:* #Ifs= 5 Cfg#= 1 Atr=a0 MxPwr=896mA
I:* If#= 0 Alt= 0 #EPs= 2 Cls=ff(vend.) Sub=ff Prot=30 Driver=(none)
E: Ad=01(O) Atr=02(Bulk) MxPS=1024 Ivl=0ms
E: Ad=81(I) Atr=02(Bulk) MxPS=1024 Ivl=0ms
I:* If#= 1 Alt= 0 #EPs= 3 Cls=ff(vend.) Sub=00 Prot=40 Driver=(none)
E: Ad=83(I) Atr=03(Int.) MxPS= 10 Ivl=32ms
E: Ad=82(I) Atr=02(Bulk) MxPS=1024 Ivl=0ms
E: Ad=02(O) Atr=02(Bulk) MxPS=1024 Ivl=0ms
I:* If#= 2 Alt= 0 #EPs= 3 Cls=ff(vend.) Sub=00 Prot=00 Driver=(none)
E: Ad=85(I) Atr=03(Int.) MxPS= 10 Ivl=32ms
E: Ad=84(I) Atr=02(Bulk) MxPS=1024 Ivl=0ms
E: Ad=03(O) Atr=02(Bulk) MxPS=1024 Ivl=0ms
I:* If#= 3 Alt= 0 #EPs= 3 Cls=ff(vend.) Sub=00 Prot=00 Driver=(none)
E: Ad=87(I) Atr=03(Int.) MxPS= 10 Ivl=32ms
E: Ad=86(I) Atr=02(Bulk) MxPS=1024 Ivl=0ms
E: Ad=04(O) Atr=02(Bulk) MxPS=1024 Ivl=0ms
I:* If#= 4 Alt= 0 #EPs= 3 Cls=ff(vend.) Sub=ff Prot=ff Driver=(none)
E: Ad=88(I) Atr=03(Int.) MxPS= 8 Ivl=32ms
E: Ad=8e(I) Atr=02(Bulk) MxPS=1024 Ivl=0ms
E: Ad=0f(O) Atr=02(Bulk) MxPS=1024 Ivl=0ms

I guess i need a new driver for my modem ?

**Comment by psfabio** [comment]
which version of router are you using? i think that only new alpha snapshots (not yet release) verions have support for this modem.

**Comment by gizze59** [comment]
As I wrote, I am using a Raspberry 4b as router flash with latest OMR image

**Comment by psfabio** [comment]
the last release? v0.59.1?
support of this modem was added after this release.
for now you need to use the 0.59.2alpha (test images) until the next release.

**Comment by gizze59** [comment]
Thanks for your update.
Where can I download test images (0.59.2alpha) for Raspberry PI 4B?

**Comment by psfabio** [comment]
rpi4 kernel 5.4 bcm2711
https://snapshots.openmptcprouter.com/5.4/rpi4/targets/bcm27xx/bcm2711/

or search your version on:
https://snapshots.openmptcprouter.com/

**Comment by gizze59** [comment]
I can confirm that modem works in 0.59.2alpha on RPI 4b
Thanks for your support

**Comment by ollea** [comment]
I tried to connect RM520N-GL on a Raspberry CM4-DUAL-ETH-4G/5G-BOX but it's neither detected on openmptcprouter-v0.61-snapshot-5.4 nor openmptcprouter-v0.61-snapshot-6.6.
How did you managed to connect the modem on USB?
