### ISSUE TITLE
SQM Autorate with strange behavior. (LTE/5G)

### ISSUE THREAD

**Issue by psfabio** [Ysurac/openmptcprouter#2851]
## Expected Behavior
sqm-autorate should adjust the sqm values (both download and upload) meassuring both rtt and load of a connection.

## Current Behavior
apparently the sqm-autorate is only adjusting the download values and with a strange behavior.
No matter which connection (3G/LTE/5G) or which settings i´m using  the autorate always sit down the sqm below the minimum (about 1 or 2mbps) 

## Possible Solution
maybe some missing configuration on wizard? or some problem with autorate repository? but i really don´t know.

## Steps to Reproduce the Problem
  1. enable both SQM and SQM autorate of an interface on wizard and set download and upload speed.
  2. monitor on terminal the behaviour of SQM values with the command "tc qdisc |  grep cake"
  3. additionally you can use speedtest to see the values in practice..

## Context (Environment)
i´m trying to use this feature to reduce vps disconnections caused for high load or spikes on variable speed connections (3G/LTE/5G)

## Specifications
  - OpenMPTCProuter version: openmptcprouter v0.59.2alpha-5.4 r0+16819-1b6e9b3f64 
  - OpenMPTCProuter VPS version: 5.4.207-mptcp 0.1029-test
  - OpenMPTCProuter VPS provider: Oracle
  - OpenMPTCProuter platform:  x86_64
  - Country: Brazil

tc qdisc command showing that autorate is only active on Downloads:
![autorate_changing_download](https://github.com/Ysurac/openmptcprouter/assets/6061933/4bf986b1-c9a5-4573-9182-ae26d2c6bc11)
dev wwan0 (upload interface) didn´t change only dev ifb4wwan0 (download) changes.

![autorate_minimum_download](https://github.com/Ysurac/openmptcprouter/assets/6061933/e14f46fb-13bb-4872-8a45-d2ebbc032118)
after a few minutes the download rate always down (below minimum setting on wizard)

and there is another strange behaviour:
![autorate_spike_another_connection](https://github.com/Ysurac/openmptcprouter/assets/6061933/22ab4dae-7561-491c-bf72-40e12ffd29b2)
If i add another connection (with sqm off) the sqm download rate of wwan0 (in this case) spikes up (and maybe lose your function because free up all download available of that given interface)

Example of speedtest (5G connection) with sqm off:
![speedtest-nosqm](https://github.com/Ysurac/openmptcprouter/assets/6061933/0f012255-786f-41c3-a599-507b562649e0)

Example of speedtest (5G connection) with sqm on after a few minutes:
![speed-sqm_down](https://github.com/Ysurac/openmptcprouter/assets/6061933/cf80b434-8960-4a38-b023-32b7ced0ebe2)

* the same behaviour is observed both with vps or with vsp bypassed
* the same behaviour is observed with high, medium and low values setted on sqm autorate Download speed and Upload speed on wizard.
*i also tried change some settings on Network/SQM QOS menu like delay threshold and others with the same results

obs: if you change values in network/sqm menu you need to made any change on wizard too in order that changes really apply.

and another small observation: if you disable sqm-autorate on wizard even if you reboot, will be a lot of erros in system log:
then you need to turn the services off on system/startup
![autorate_syslog](https://github.com/Ysurac/openmptcprouter/assets/6061933/cef5d6e6-8e06-4dca-b78d-a7f08c3b25a8)

Please let me know if i can do more tests or something.

thanks a lot.

**Comment by Ysurac** [comment]
I checked and it's in fact not working at all.
I'm working to fix this.

**Comment by psfabio** [comment]
Great. if i can help with something, let me know.. i have a bunch of connections types. (cable/LTE/5G/etc)

**Comment by Ysurac** [comment]
You can try latest snapshot.

**Comment by psfabio** [comment]
Ok, i will test and let you know.
Thanks

**Comment by psfabio** [comment]
Hi @Ysurac, i think the autorate it is not working very well yet:
- it still is reducing (sometimes) bandwith below the minimum (even on a cable connection).
- it is not rising up to the maximum download on load with good connections (base download it is the maximum that the script rise)
- it is not working on uploads (i only can see the tun0 upload interface (activated per default) sometimes variating)
- if i change some value on Network-SQM QOS it stop to work. Then i need to make some change on wizard.
- it still not stoping if i disable it on wizard:
i get this message on logread (i´m testing your last commit):
daemon.err cake-autorate_launcher.sh[12443: /usr/share/sqm-autorate/cake-autorate.sh: line 91: proc_pids[intercept_stderr]: unbound variable.

Thanks a lot.
