### ISSUE TITLE
ethernet port sequence

### ISSUE THREAD

**Issue by bladeHP** [Ysurac/openmptcprouter#2857]
HI,
I installed several openMPTCProuters on x86_64 pc of different brands, the latest minipc intel celeron J4125 4Gb Ram 4 ETH intel 2.5 Gbit/s has 2 WAN ports turned upside down.
the sequence is ETH0 ETH1 ETH3 ETH2.
consequently also inside openMPTCProuter it becomes LAN, WAN1, WAN3,WAN2.
Is there a way to "turn" the ports correctly?
I would like to have the sequence ETH0,ETH1,ETH2,ETH3, so in openMPTCProuter they should be LAN,WAN1,WAN2,WAN3.

Thank you

**Comment by Ysurac** [comment]
You can attribute any interfaces to WAN* ports.
Else you can rename eth* interfaces using ```ip link set <currentname> name <newmname>```
