### ISSUE TITLE
Fichiers en lecture seule

### ISSUE THREAD

**Issue by JeedHome44** [Ysurac/openmptcprouter#2858]
Bonjour,

J'ai ce message ce matin après une coupure de courant:
![image](https://github.com/Ysurac/openmptcprouter/assets/41892950/a86bcbdb-4ae5-46d3-bb21-f1b6e5f03fe5)

Est-ce la carte SD qui ne veut pas être en écriture ?

**Comment by Ysurac** [comment]
Oui, possible d'essayer via SSH sur le routeur :
```
e2fsck -y /dev/mmcblk0p2
reboot
```

**Comment by JeedHome44** [comment]
Ça va avoir quel effet ?

**Comment by JeedHome44** [comment]
> Oui, possible d'essayer via SSH sur le routeur :
> 
> ```
> 
> e2fsck -y /dev/mmcblk0p2
> 
> reboot
> 
> ```

Ça a marché. Merci beaucoup.
Je peux changer à nouveau les paramètres.
