### ISSUE TITLE
rpi4 custom image build error

### ISSUE THREAD

**Issue by bluisana** [Ysurac/openmptcprouter#2861]
## Expected Behavior
I am trying to build a custom image for rpi4. 

This is the build command I am using. 

OMR_TARGET="rpi4" OMR_FEED_SRC="v0.59.2alpha"

## Current Behavior
The build fails here. 

mptcprouter/rpi4/5.4/source/dl" "ndisc6_1.0.3.orig.tar.bz2" "0f41d6caf5f2edc1a12924956ae8b1d372e3b426bd7b11eed7d38bc974eec821" "" "http://deb.debian.org/debian/pool/main/n/ndisc6"    '
+ curl -4 -f --connect-timeout 20 --retry 5 --location --insecure http://deb.debian.org/debian/pool/main/n/ndisc6/ndisc6_1.0.3.orig.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Download failed.
+ curl -4 -f --connect-timeout 20 --retry 5 --location --insecure https://sources.cdn.openwrt.org/ndisc6_1.0.3.orig.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 
Download failed.
+ curl -4 -f --connect-timeout 20 --retry 5 --location --insecure https://sources.openwrt.org/ndisc6_1.0.3.orig.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Download failed.
+ curl -4 -f --connect-timeout 20 --retry 5 --location --insecure https://mirror2.openwrt.org/sources/ndisc6_1.0.3.orig.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Download failed.

curl: (22) The requested URL returned error: 404 Not Found
Download failed.
No more mirrors to try - giving up.

**Comment by Ysurac** [comment]
This is fixed in develop branch.

**Comment by bluisana** [comment]
Thanks Ysurac, 

Now I get an error about file changes in my branch when trying to build but when I do a git diff it doesn't show any changes.  I am assuming that the build script in develop is checking out a different branch?  How do I fix this? 

$git checkout develop
$OMR_TARGET="rpi4" OMR_FEED_SRC="develop" ./build.sh V=s
error: Your local changes to the following files would be overwritten by checkout:
        include/kernel-version.mk
        include/netfilter.mk
        package/base-files/files/bin/config_generate
        package/kernel/linux/modules/crypto.mk
        package/kernel/linux/modules/fs.mk
        package/kernel/linux/modules/netfilter.mk
        package/kernel/linux/modules/netsupport.mk
        package/kernel/linux/modules/other.mk
        scripts/download.pl
        target/linux/generic/config-5.4
        target/linux/generic/pending-5.4/640-netfilter-nf_flow_table-add-hardware-offload-support.patch
        target/linux/generic/pending-5.4/645-netfilter-nf_flow_table-rework-hardware-offload-time.patch
Please commit your changes or stash them before you switch branches.
Aborting

**Comment by Ysurac** [comment]
```rm -rf rpi4```

**Comment by bluisana** [comment]
I finally got everything to compile but there is just a packages and targets folder in my source/bin folder.  Is this supposed to create the full image file or do I have to take some further manual steps to do that?  

One thing I noticed was that I have quite a few folders with dump.txt files in the logs directory.  These seem to be associated with package or dependency errors.  Are these normal to run into during a build?

**Comment by Ysurac** [comment]
Images should be in rpi/6.1/bin/targets/bcm27xx/bcm2711/ if compilation work successfully.
dump.txt are normal.

**Comment by Ysurac** [comment]
you need to add ```OMR_KERNEL="6.1"``` to the command line.

**Comment by bluisana** [comment]
Thanks, 

This image finally recognized all of the ethernet adapters on my PI :).  The testing will begin shortly :).
