### ISSUE TITLE
Installation OMR KERNEL 6.1

### ISSUE THREAD

**Issue by Henrb** [Ysurac/openmptcprouter#2862]
Bonsoir,

Je tente d'installer OMR avec le Kernel 6.1 mais je ne parviens pas a faire fonctionner la VM, de l'aide serait la bien venu.
Voici l'erreur :
![IMG_2937](https://github.com/Ysurac/openmptcprouter/assets/88949192/eab9c48d-6ff7-4ecb-b727-dd647a700064)

**Comment by Ysurac** [comment]
Il n'y a pas vraiment d'erreur là. En pressant "Entrée" ça affiche quelque chose ?
C'est quelle image exactement ?

**Comment by Henrb** [comment]
> Il n'y a pas vraiment d'erreur là. En pressant "Entrée" ça affiche quelque chose ? C'est quelle image exactement ?

Désoler je ne vois vraiment pas comment me débloquer, le shell me dit busy box built-in shell ? Une idée ? 
Merci par avance

**Comment by Henrb** [comment]
Re, j'ai avancer un peu je suis bloquer ici maintenant IMG_2963.HEIC

**Comment by Ysurac** [comment]
Il y a un souci sur la dernière image, je travaille dessus.

**Comment by Henrb** [comment]
Ok, merci pour le retour. Tiens nous au courant, pour la version la : http://www.openmptcprouter.com/download il y a le package .ova, serait il possible de l'avoir sur la version 6.1 ?

**Comment by Kalimeiro** [comment]
> 

Salut, as-tu fait un essai pour vérifier que l'agrégation se fait bien avec le noyau 6.1, car dans mes précédents essais, c'était négatif, il n'y avait que la connexion "master" qui fonctionnait, les autres liens n'étaient pas agrégés.
