### ISSUE TITLE
where is the sysytemlog in 0.59.2 ?how to checkout it.

### ISSUE THREAD

**Issue by fareign** [Ysurac/openmptcprouter#2866]
## Current Behavior

 In Status->System log is disappear. 
the chages log  Config :Use Busybox Syslogd instead of OpenWRT logd
but I cant find it.

## Specifications

  - OpenMPTCProuter version: 0.59.2
  - OpenMPTCProuter VPS version: 0.1028
  - OpenMPTCProuter VPS provider:aliyun
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
There is no 0.59.2 release yet. If you mean snapshot image, it's still an alpha release, changes are made every days and it's not yet fully tested.

**Comment by fareign** [comment]
> There is no 0.59.2 release yet. If you mean snapshot image, it's still an alpha release, changes are made every days and it's not yet fully tested.

I know is alpha ,but I want to see the syslog and I cant find it .help me.

**Comment by Ysurac** [comment]
You can use ```logread``` command via SSH.
This will be fixed in web interface, system log menu, in next image build.

**Comment by vempire-ghost** [comment]
Can you fix the logs in the 5.4 kernel too pls?

**Comment by Kalimeiro** [comment]
It's fixed since latest snapshot.

**Comment by vempire-ghost** [comment]
![image](https://github.com/Ysurac/openmptcprouter/assets/132581535/3b7a0397-b4d4-40bf-8806-49576f00852d)
Its still broken in the 5.4 kernel, they only fixed in the 6.1.

**Comment by Kalimeiro** [comment]
![image](https://github.com/Ysurac/openmptcprouter/assets/8118989/df5690b7-75c6-477f-9ae5-b1026bce2c98)

**Comment by vempire-ghost** [comment]
How strange, I'm using the x86_x64 image in VirtualBox, are you using it too?

**Comment by Kalimeiro** [comment]
I'm using x86_64 image on a local dedicated server (Ryzen 5 5600G + SFP+ x 2 pci-e card + 2.5Gbps x 4 pci-e card).
I'm always using latest snapshot when available for help to debug.
I thinks your problem is somewhere in virtualbox.

**Comment by vempire-ghost** [comment]
Indeed, the snapshots for VirtualBox with kernel 6.1 have the system log working, but the ones with kernel 5.4 don't. It may be something specific to this image that is still bugged. If Ysurac could take a look, I would appreciate it. I would like to go back to using the latest versions for testing, but it's difficult without the log.

**Comment by Ysurac** [comment]
It's working also with 5.4 kernel.
