### ISSUE TITLE
log ERROR 

### ISSUE THREAD

**Issue by renaudadu** [Ysurac/openmptcprouter#287]
hello, i have noticed this message in the vps log :
Jan  1 20:39:50 scw-ef65ea ss-server[475]:  2019-01-01 20:39:50 ERROR: remote recv: Connection reset by peer
Jan  1 21:39:51 scw-ef65ea ss-server[475]:  2019-01-01 21:39:51 ERROR: remote recv: Connection reset by peer
Jan  1 23:12:12 scw-ef65ea ss-server[475]:  2019-01-01 23:12:12 ERROR: remote recv: Connection reset by peer
Jan  2 02:10:44 scw-ef65ea ss-server[475]:  2019-01-02 02:10:44 ERROR: remote recv: Connection reset by peer
Jan  2 03:14:11 scw-ef65ea ss-server[475]:  2019-01-02 03:14:11 ERROR: remote recv: Connection reset by peer
Jan  2 05:59:59 scw-ef65ea ss-server[475]:  2019-01-02 05:59:59 ERROR: server recv: Connection reset by peer

have an idea ?

## Specifications

  - OpenMPTCProuter version: (0.44.5)
  - OpenMPTCProuter VPS version: (0.83) scaleway
  - OpenMPTCProuter platform: RPI3

**Comment by Ysurac** [comment]
It's not really an error.
This means the remote server close the TCP connection with a RESET, which can be caused by timeout or network issue.
