### ISSUE TITLE
Content of .sh script is html with "Coming soon."

### ISSUE THREAD

**Issue by open4user** [Ysurac/openmptcprouter#2872]
Trying to set up the server side (ubuntu 20.04)

I am using 
wget --no-check-certificate https://www.openmptcprouter.com/server/ubuntu20.04-x86_64.sh
as an option without "--no-check-certificate" doesn't work 

sh ubuntu20.04-x86_64.sh
returns some kind of redirect error

I opened the script as 
nano ubuntu20.04-x86_64.sh

and the content is an html file with "Coming soon." text
Same for other scripts like "debian-x86_64.sh"

At the same time I see that https://www.openmptcprouter.com/server/ubuntu20.04-x86_64.sh opened directly in a browser is a valid script. 

Am I missing something during the server side installation?

**Comment by Ysurac** [comment]
What is the result of ```ping -c 3 www.openmptcprouter.com``` from the VPS ?
What is the result of ```curl https://google.com``` (You should get a 301 Moved) ?
What is the VPS provider ?

**Comment by open4user** [comment]
I believe, the issue was in broken browser console on VPS side. Did the same via Putty and all worked well.

Would appreciate some more help as I am having:

"Can't contact Server Admin Script (No token yet available)":
"user.notice OMR-VPS: Can't get vps token, try later (can ping server vps on [real VPS ip here], server API answer on [real VPS ip here])"

What I already did: 

Full server update (with reboot), ip r returns some results, shadowsocks and omr are in "active" status.
All keys from /root/openmptcprouter_config.txt are set in Advanced Settings and are correct.
omr-test-speed (eth1/eth2) returns some results, download speed is less than 1Mbps but I assume those are just mobile networks issues (upload speed is ~35Mpbs though), changing modems to different manufacturers increases the download speed (to ~15Mbps) but doesn't solve the "No token yet available" issue.

What I haven't tried: 

Services -> shadowsocks-libev are all default (don't know if anything needs to be changed).
V2Ray, as I have no idea if it's needed (and if yes, where to get "V2Ray user id" as just changing to V2Ray from Shadowsocks (and removing or not removing ShadowSocks key) doesn't work.


VPS is a local provider. 
Extended details are below, including screenshots.

-------------

Did a full server part update:

apt-get update && apt-get upgrade
wget https://www.openmptcprouter.com/server/ubuntu20.04-x86_64.sh
sh ubuntu20.04-x86_64.sh

reboot after the update

----------------------

SSH from the router:

root@OpenMPTCProuter: ip r
default via 10.255.255.1 dev tun0 
default via 192.168.10.1 dev eth1 metric 1 
default via 192.168.10.1 dev eth1 metric 7 
default via 192.168.11.1 dev eth2 metric 8 
default via 10.255.255.1 dev tun0 metric 1200 
10.255.255.1 dev tun0 proto kernel scope link src 10.255.255.2 
10.255.255.2 dev tun0 scope link metric 1200 
127.0.0.0/8 dev lo proto static scope link metric 5 
[real VPS ip here] metric 1 
        nexthop via 192.168.10.1 dev eth1 weight 10 
        nexthop via 192.168.11.1 dev eth2 weight 1 
192.168.10.0/24 dev eth1 scope link metric 7 
192.168.11.0/24 dev eth2 scope link metric 8 


------------------

systemctl status shadowsocks-libev-manager@manager.service
● shadowsocks-libev-manager@manager.service - Shadowsocks-Libev Custom Manager >
     Loaded: loaded (/lib/systemd/system/shadowsocks-libev-manager@.service; en>
     Active: active (running) since Mon 2023-07-24 20:53:53 BST; 1min 55s ago
   Main PID: 460 (ss-manager)
      Tasks: 2 (limit: 1128)
     Memory: 5.3M
     CGroup: /system.slice/system-shadowsocks\x2dlibev\x2dmanager.slice/shadows>
             ├─460 /usr/bin/ss-manager -c /etc/shadowsocks-libev/manager.json ->
             └─466 ss-server --manager-address 127.0.0.1:8839 -f /root/.shadows>

Jul 24 21:20:21 ss-server[466]: getpeername: Transport endpoint is not connected
Jul 24 21:20:24 ss-server[466]: getpeername: remote recv: Connection reset by peer

-----------------

systemctl status omr-admin.service
● omr-admin.service - OMR-Admin
     Loaded: loaded (/lib/systemd/system/omr-admin.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2023-07-24 20:53:52 BST; 43min ago
   Main PID: 418 (python3)
      Tasks: 2 (limit: 1128)
     Memory: 49.3M
     CGroup: /system.slice/omr-admin.service
             └─418 python3 /usr/local/bin/omr-admin.py

Jul 24 20:53:52 systemd[1]: Started OMR-Admin.
root@111111:~#

----------------

root@OpenMPTCProuter:~# omr-test-speed eth1
Select best test server...
host: speedtest.milkywan.fr - ping: 69
.....
Best server is http://sto.download.datapacket.com/10000mb.bin, running test:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 9536M    0 10.5M    0     0  97378      0 28:31:32  0:01:53 28:29:39  102k

----------------

root@OpenMPTCProuter:~# omr-test-speed eth2
Select best test server...
host: speedtest.frankfurt.linode.com - ping: 51
host: speedtest.milkywan.fr - ping: 71
......
Best server is http://war.download.datapacket.com/10000mb.bin, running test:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 9536M    0 10.8M    0     0  30805      0 90:10:22  0:06:08 90:04:14 41242

---------------

root@OpenMPTCProuter:~# omr-test-speed
Select best test server...
host: speedtest.milkywan.fr - ping: 74
......
Best server is http://speedtest.frankfurt.linode.com/garbage.php?ckSize=10000, running test:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 20.2M    0 20.2M    0     0  67783      0 --:--:--  0:05:12 --:--:-- 72813

![1](https://github.com/Ysurac/openmptcprouter/assets/138617449/dcb0b98f-a3e8-461d-9d1f-2c8f8be56b7f)
![2](https://github.com/Ysurac/openmptcprouter/assets/138617449/e33e361a-49e7-4166-9a3e-def2c4787e61)

**Comment by open4user** [comment]
@Ysurac, would appreciate some help with above.

**Comment by Ysurac** [comment]
Can you check the result of ```ps aux | grep omr``` ? you should get some "omr-admin.py" entry.
If not, try a ```systemctl start omr-admin```.

**Comment by open4user** [comment]
@Ysurac, I replaced a VPS provider and did all the steps again:

ubuntu20.04
apt-get update && apt-get upgrade
install the script, reboot

Couldn't login to SSH to new 65222 port, admins mentioned that they had to do:

"Might be a conflict with existing package:
cloud-init : Depends: python3-oauthlib but it is not going to be installed
did a re-install using the following: 
apt --fix-broken install cloud-init"

after that I successfully connected to VPS, configured the router and now see correct set up on both router's "Dashboard" and "Status" tabs.

Might not be related, but maybe there are some unresolved Python3 related conflicts between existing ubuntu20.04-x86_64.sh and packages on the updated Ubuntu20.04 server?


-------------------------

Having a terrible speed on the new VPS though (less than 1Mbps), same SIM cards (both of them) work on ~35Mbps speed in the same modem (but with DHCP enabled) that I am using for openmptcprouter configuration. So the issue is not with modems/SIM cards, but somewhere in the server or router configurations (will try to investigate it first, before asking for additional help).

Same steps (plus what you mentioned above) did nothing on my old VPS (all posts above), at this point won't probably try to investigate it as new VPS configuration looks working, except for the terrible <1Mbps speed.

**Comment by Ysurac** [comment]
You should use Debian on the VPS.
I don't use cloud-init and cloud-init should only be used at VPS installation by the provider, no idea why this can make a problem after...

You can try to disable encryption in the wizard, at least this can check if there is no filters on ISP or VPS side on encrypted connections.
