### ISSUE TITLE
Recommended raspberry pi hardware

### ISSUE THREAD

**Issue by amarmashruwala** [Ysurac/openmptcprouter#2873]
Hi there. 

There are a few raspberry pi images. 
Can you provide the recommended RPi hardware that works best please? 

Thank you

**Comment by Ysurac** [comment]
RPI4 work correctly.
Else a x86_64 barebone with AES-NI give good results.

**Comment by amarmashruwala** [comment]
Thank you. 

Will the raspberry pi 4 with 1 GB ram work well or will I need more RAM?

**Comment by Ysurac** [comment]
I have a RPI 4 with 2Go and it's using about 150Mo in normal use.

**Comment by amarmashruwala** [comment]
Thank you for the information
