### ISSUE TITLE
Support for RAID Controllers

### ISSUE THREAD

**Issue by marius137** [Ysurac/openmptcprouter#2879]
When I tried running OMR on an HP DL380G6 with both the integrated HP P410 raid controller and a random Adaptec Raid controller the boot hangs at `waiting for root device PARTUUID=`.

**Comment by Ysurac** [comment]
What is the version tested ?

**Comment by marius137** [comment]
I tried the ext4 non-uefi version downloaded today

[openmptcprouter-v0.59.1-5.4-r0+16594-ce92de8c8c-x86-64-generic-ext4-combined.img.gz](https://download.openmptcprouter.com/release/v0.59.1/x86_64/targets/x86/64/openmptcprouter-v0.59.1-5.4-r0+16594-ce92de8c8c-x86-64-generic-ext4-combined.img.gz)

**Comment by Ysurac** [comment]
Can you try snapshot image ? https://snapshots.openmptcprouter.com/6.1/x86_64/targets/x86/64/
If this is still not working, do you know needed modules ?

**Comment by marius137** [comment]
sorry for the late reply, I couldn't try the snapshot as I needed the hardware, but I did some more digging and it seems that openwrt in general doesn't play nice with raid controllers. I ended up just using the normal sata ports on the mainboard and a single drive without raid.

I am closing the issue because this probably is an openwrt issue, and not really OMR related
