### ISSUE TITLE
Support ECC Memory

### ISSUE THREAD

**Issue by Kalimeiro** [Ysurac/openmptcprouter#2880]
Hi, we have servers with ecc memory and memory working in non-ecc mode. it's possible to enable them for intel/amd ?

Actually, i can't see EDAC loaded in dmesg and "dmidecode --type memory" show None in "Error Correction Type" instead "Multi-bit ECC"

Thanks.

**Comment by Kalimeiro** [comment]
I use only 5.4 kernel because on 6.1 agregation not working.

**Comment by Ysurac** [comment]
Aggregation is working on 6.1, 5.4 kernel will be put as legacy/deprecated.

**Comment by Kalimeiro** [comment]
Je suis désolé de te contredire, mais l'agrégation avec le noyau 6.1 ne fonctionne pas du tout, il n'y a que l'interface MASTER qui est utilisé.

De plus, la redirection de port ne fonctionne plus et je suis en train de chercher quel est le problème depuis hier soir.

**Comment by Kalimeiro** [comment]
ok i'm testing 6.1 kernel and agregation is working now, be careful to set mptcp version 1 and not version 0 when switch in 6.1 kernel.

the latest snapshot not integrate edac_mc module.
