### ISSUE TITLE
Multiple Client on VPS

### ISSUE THREAD

**Issue by MrTheSkream** [Ysurac/openmptcprouter#289]
Hello,

Is it possible to put multiple client (Raspberry) on a single server?

Thank you in advance,
Cordially.

## Specifications

  - OpenMPTCProuter version: v0.44.5
  - OpenMPTCProuter VPS version: v0.79
  - OpenMPTCProuter platform: (RPI3)

**Comment by Ysurac** [comment]
Not yet.
