### ISSUE TITLE
Getaway Down for DW5821e

### ISSUE THREAD

**Issue by madspeed** [Ysurac/openmptcprouter#2897]
Hello!
I am consistently having problem with USB modem DW5821e.

I have connected it using modemmanager, but it is always telling that the gateway is down. It the same time I have internet access, but when I connect the second modem the Dl speed reduces instead of increasing. I suppose that this problem may be caused as OMR thinks that main gateway is down.
![Снимок экрана 2023-07-26 112053](https://github.com/Ysurac/openmptcprouter/assets/61581394/2b37d6b2-14ad-4478-8d95-75ddbba3cbe8)
![Снимок экрана 2023-07-26 111918](https://github.com/Ysurac/openmptcprouter/assets/61581394/402998ab-0b5b-459e-b553-a93b84486ebe)

**Comment by Ysurac** [comment]
Gateway down is only a warning, only that gateway doesn't answer to ping. As you have connection, no issue here.
For the slowest speed when both modem connected, I need to know if you use same operator.
You also have an issue on VPS side: it's not using the good kernel, so no aggregation possible here. It's should use "5.4.*-mptcp" kernel. Did you reboot after VPS script launch ?

**Comment by madspeed** [comment]
Thank you for a prompt reply!
I am using the same operator in both modems.
What should I do with VPS side? I have tried to reboot, still "Version 0.1028 5.10.0-21-amd64"

**Comment by Ysurac** [comment]
On the VPS, check kernel with ```uname -a```, version displayed in status page can take some time before update.
If it's also 5.10, what is the OS installed on the VPS (should be a Debian) ? And what is the VPS provider ?

**Comment by madspeed** [comment]
Linux localhost 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU
Debian 11
VPS is REG.RU

**Comment by Ysurac** [comment]
I will not be able to test on this provider.
What do you have in ```/boot/grub/grub.cfg```, in ```/etc/default/grub``` and the result of ```ls /boot/``` ?

**Comment by madspeed** [comment]
I can deploy a new server with debian 11 for you for tests, ok?
![Снимок экрана 2023-07-26 144850](https://github.com/Ysurac/openmptcprouter/assets/61581394/61e62f0e-1f66-4ce3-94b4-82574b625f8c)
![Снимок экрана 2023-07-26 144544](https://github.com/Ysurac/openmptcprouter/assets/61581394/b8926e89-7fba-48c6-aa8c-a5d64c4f2579)
![Снимок экрана 2023-07-26 144440](https://github.com/Ysurac/openmptcprouter/assets/61581394/76ebb0f7-5fb8-42a4-834a-53f801f56808)

**Comment by Ysurac** [comment]
I only need the full content of ```/boot/grub/grub.cfg``` file to check if entry "1>6" is the correct one or if it's the wrong kernel.

**Comment by Ysurac** [comment]
Maybe you have a ```/boot/grub2``` directory ? But you must have a grub.cfg with more than that. Do a ```cat /boot/grub*/grub.cfg```

**Comment by madspeed** [comment]
You are right, here is the full grub.cfg:
![photo_2023-07-27_09-19-24](https://github.com/Ysurac/openmptcprouter/assets/61581394/87681cd3-e7a5-4431-89d9-0e4c0b62eda1)

**Comment by madspeed** [comment]
You were right, it was not full file. Here is full grub.cfg:
[grub.txt](https://github.com/Ysurac/openmptcprouter/files/12180034/grub.txt)

**Comment by Ysurac** [comment]
The grub.cfg is correct, it should use the right entry.
Check if the VPS is configured to boot from kernel on disk, some VPS can boot from a network kernel.
Check if you can get a VPS Console access to see Grub boot menu when the VPS is starting.

**Comment by madspeed** [comment]
could you please give commands to check it?

**Comment by Ysurac** [comment]
No commands here, you need to check via your VPS provider interface.
Configuration on the VPS is correct.

**Comment by madspeed** [comment]
Do I understand it correctly that VPS debian 11 kernel should be 5.4+smth...?

**Comment by Ysurac** [comment]
Yes

**Comment by madspeed** [comment]
Reinstalled the VPS, now everything is good with kernel.
Decided to test aggregation, but now have problems with DW5821e, the modemmanager fails after several minutes of work and does not reconnect. If I remove second modem (wan2), everything is good and dl speed is higher.
![Снимок экрана 2023-07-27 122301](https://github.com/Ysurac/openmptcprouter/assets/61581394/1393af8a-0fd7-4fa1-a767-fa357f41352e)

**Comment by Ysurac** [comment]
Can you check in menu Status->System logs what ModemManager is saying ?

**Comment by madspeed** [comment]
and after reconnect
[log.txt](https://github.com/Ysurac/openmptcprouter/files/12182360/log.txt)

**Comment by Ysurac** [comment]
It's seems that there is some USB problems. Do you use a powered USB hub ?

**Comment by madspeed** [comment]
modems are plugged into rpi4, no hubs

**Comment by Ysurac** [comment]
I think it's the problem: RPI4 is really bad to give enough power to some USB device. You should try with a powered USB hub.
