### ISSUE TITLE
The modems are not being aggregated

### ISSUE THREAD

**Issue by sanfweb** [Ysurac/openmptcprouter#2898]
Hi!

Please help me understand why the internet is not being aggregated.

I am using a Raspberry Pi 4 with openmptcprouter v0.59.1-54 r0+16594-ce92de8c8c installed and a VPS with 5.4.207-mptcp 0.1028. I have two Fibocom L850-GL modems connected via USB adapters 3.0

![scren01](https://github.com/Ysurac/openmptcprouter/assets/34582114/8cea8a49-5891-47bb-840f-3fef89d0644a)

When I measure the speed of the first modem (omr-test-speed eth4), I get a result of 16M, sometimes a bit higher.

![scren02](https://github.com/Ysurac/openmptcprouter/assets/34582114/0429a11d-c178-425c-baaf-ea8789729a7c)

When I measure the speed of the second modem (omr-test-speed eth1), I get a result of 13M, sometimes slightly higher.

![scren03](https://github.com/Ysurac/openmptcprouter/assets/34582114/6b4f93b2-e5df-41db-8b5f-08b8ae463dd3)

However, when I measure the aggregated speed (omr-test-speed), I get a result of 16M, sometimes a bit higher, and this doesn't seem like aggregation.

![scren04](https://github.com/Ysurac/openmptcprouter/assets/34582114/84913604-a922-4f57-881f-76956363eff3)

Please help me understand what I'm doing wrong and where the problem might be.
Thank you very much!

**Comment by Ysurac** [comment]
To check if you have aggregation, look at bandwidth tab in System->MPTCP.
Modems are on different ISP ?

**Comment by sanfweb** [comment]
I used two modems with the same providers, is it not possible to achieve aggregation in this case?

**Comment by sanfweb** [comment]
I conducted a new experiment, I added one more modem, so now I have three, each with a different provider.

![photo_2023-07-28_13-48-06](https://github.com/Ysurac/openmptcprouter/assets/34582114/768c2b25-bc8a-481e-b3b1-49270b061607)

I went to the bandwidth section and initiated a speed test using speedtest in another window. In the bandwidth section, I see that two providers are being aggregated, but the third one is not.

![photo_2023-07-28_12-37-41](https://github.com/Ysurac/openmptcprouter/assets/34582114/cb8ad69a-e4f8-45af-9a48-952b11866d71)

**Comment by Ysurac** [comment]
If your VPS provider can provide more than 300Mb/s, possible that this provider filter MPTCP, you can check by disabling another connection and test again.

**Comment by sanfweb** [comment]
> 

I will clarify the limitation and conduct the experiment as you suggested.

**Comment by sanfweb** [comment]
I mentioned earlier about using multiple modems with the same provider, does aggregation not occur in this case.

This happens only when there are two modems with the same provider, or if, for example, I take four modems, and two of them have the same provider, will it work?

**Comment by Ysurac** [comment]
When using same provider the problem is the antenna that often have a limited bandwidth available shared between all customer. With 2 modems using same provider you are sharing same bandwidth.

**Comment by sanfweb** [comment]
Seems like the issue indeed lies in MPTCP being blocked by one of the providers. Thank you!
