### ISSUE TITLE
openmptcprouter cant enable in startup  kernel 5.15 6.1

### ISSUE THREAD

**Issue by fareign** [Ysurac/openmptcprouter#2903]
## Possible Solution

 I change START=5 to START=05. it can work
if I change it before complie. the file have no excute right. I dont know why.

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - OpenMPTCProuter version: 0.59.2 alpha 5.15
  - OpenMPTCProuter VPS version: 0.1029test
  - OpenMPTCProuter VPS provider:
  - OpenMPTCProuter platform: x86_64
  - Country: cn

<img width="790" alt="微信图片_20230728091142" src="https://github.com/Ysurac/openmptcprouter/assets/15459/ba20b29a-eb8f-4571-a965-d470331393fe">

**Comment by Ysurac** [comment]
This will be fixed in next snapshot. Thanks.
