### ISSUE TITLE
Device won´t save after hitting apply (Quectel RM500Q-AE)

### ISSUE THREAD

**Issue by Keksstar** [Ysurac/openmptcprouter#2907]
## Expected Behavior
Interface Setup should save the selected modem.

## Current Behavior
When selecting an modem (Quectel RM500Q) in the interface setup it won´t save it when hitting apply. It´s reverting back to it´s previous value. Therefore the modem can´t be used.

## Specifications
  - OpenMPTCProuter version: 5.4.207-mptcp 0.1028
  - OpenMPTCProuter VPS version: not needed
  - OpenMPTCProuter VPS provider: not needed
  - OpenMPTCProuter platform: Raspberry Pi 4 Model B Rev 1.5

System Log: https://pastebin.com/QQTqzLGz
Kernel Log: https://pastebin.com/E9e066a0 
 
This it what happens: Selecting the USB modem here. And hitting apply....
![grafik](https://github.com/Ysurac/openmptcprouter/assets/15065206/628c1a7b-02a2-4314-b33e-27ce61bf592a)

After saving I go back there and the value isn´t saved....
![grafik](https://github.com/Ysurac/openmptcprouter/assets/15065206/c842fa72-d54a-47a8-b93b-ed72eb9d0c65)

**Comment by Ysurac** [comment]
It seems that there is some issue with your filesystem: "SQUASHFS error: Unable to read fragment cache entry"

**Comment by Keksstar** [comment]
@Ysurac see #2896

**Comment by Keksstar** [comment]
After solving the issue with EXT4 on Raspberry... It still isn´t working...
![grafik](https://github.com/Ysurac/openmptcprouter/assets/15065206/550c91cb-b8b3-41dc-8a26-10586e2f242d)

Rebooting brings different results: Sometimes it gets an connection for a very short time on one of the modems. But most of the time it didn´t.

Wondering is this modem is supported as I read about an Quectel RM520, which was supported in the alpha release - which I´m not using currently? There isn´t that much of an big difference, as both speak QMI.

**Comment by Ysurac** [comment]
What do you have in system logs now ?

**Comment by kpma1985** [comment]
sounds like read only
