### ISSUE TITLE
HOW to solve  couldn't set socket option `TCP_KEEPCNT TCP_KEEPIDLE

### ISSUE THREAD

**Issue by fareign** [Ysurac/openmptcprouter#2911]
## Expected Behavior
Aug  2 13:50:25 OpenMPTCProuter daemon.info glorytun[8275]: STOPPED tun0
Aug  2 13:50:26 OpenMPTCProuter daemon.err glorytun[8275]: 8.**.71.*.65001: connected
Aug  2 13:50:26 OpenMPTCProuter daemon.err glorytun[8275]: couldn't set socket option `TCP_KEEPCNT'
Aug  2 13:50:26 OpenMPTCProuter daemon.err glorytun[8275]: couldn't set socket option `TCP_KEEPIDLE'
Aug  2 13:50:26 OpenMPTCProuter daemon.err glorytun[8275]: couldn't set socket option `TCP_KEEPINTVL'
Aug  2 13:50:26 OpenMPTCProuter daemon.err glorytun[8275]: couldn't set socket option `TCP_USER_TIMEOUT'
Aug  2 13:50:36 OpenMPTCProuter daemon.err glorytun[8275]: 8.*.71.*.65001: key exchange failed
Aug  2 13:50:36 OpenMPTCProuter daemon.info glorytun[8275]: STOPPED tun0
Aug  2 13:50:37 OpenMPTCProuter daemon.err glorytun[8275]: 8.***.71.**.65001: connected
Aug  2 13:50:37 OpenMPTCProuter daemon.err glorytun[8275]: couldn't set socket option `TCP_KEEPCNT'
Aug  2 13:50:37 OpenMPTCProuter daemon.err glorytun[8275]: couldn't set socket option `TCP_KEEPIDLE'
Aug  2 13:50:37 OpenMPTCProuter daemon.err glorytun[8275]: couldn't set socket option `TCP_KEEPINTVL'
Aug  2 13:50:37 OpenMPTCProuter daemon.err glorytun[8275]: couldn't set socket option `TCP_USER_TIMEOUT'
Aug  2 13:50:37 OpenMPTCProuter daemon.info glorytun[8275]: STARTED tun0

## Current Behavior

this erro is important or not. or it is hard to solve.
this happen to kernel 5.15 and 6.1
kernel 5.15 has one more  TCP_nodelay

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - OpenMPTCProuter version: kernel 5.15 and 6.1
  - OpenMPTCProuter VPS version: 0.1029test
  - OpenMPTCProuter VPS provider:aliyun
  - OpenMPTCProuter platform:  x86_64 
  - Country: cn

**Comment by Ysurac** [comment]
It's not a problem.
I disabled these logs in latest snapshot.
