### ISSUE TITLE
Port Forwarding, how to forward from OMR VPS to a web server behind another LAN Router

### ISSUE THREAD

**Issue by ioogithub** [Ysurac/openmptcprouter#2916]
I want to open forward port 80 from the `VPN` to `OMR` to a `Web server.` `Web server` is behind another OpenWrt `LAN Router`:
Web site:80 -> VPS:80 -> OMR:80 -> Lan Router:80 -> Web server

## Current Behavior

Packets are forwarded from VPS to the OMR VPS but they do not hit the LAN router (next hop)

- On OMR: `tcpdump -i tun0 port 80` I see the packets here.
- On OMR `tcpdump -i eth0 port 80` no packets here
- On LAN Router: `tcpdump -i eth1 port 80` where eth1 is the port on the LAN router which connects to OMR, no packets.
- One Web server: `tcpdump -i eth0 port 80`, no packets.

- I followed the guide here: https://github.com/Ysurac/openmptcprouter/wiki/Port-forwarding.
- I setup one Port forward rule and one SNAT rule. 
- This guide only shows how to setup an SNAT to forward when the webserver is on the same subnet as OMR.
- My webserver is on a different subnet.
- I modified the SNAT rule `destination address ` changed from webserver to IP address of the LAN router on the OMR subnet:

```
OMR                         LAN Router                  Web server
192.168.2.1 <-> 192.168.2.6 (WAN)| 192.168.1.1 (LAN) <-> 192.168.1.2

```
Question: Can I use SNAT like this to forward from OMR vps to LAN router interface or do I have to use another method to forward packets to the LAN router where the web server is connected.
- I also added a forward rule from LAN router to web server on LAN router but not

I spent many hours troubleshooting but  packets never make it past the OMR router. Please help.

## Debug:
- Check that the VPN is running in System->OpenMPTCProuter and Status tab. `Yes`
- Check on the VPS in /etc/shorewall/rules that rules you set are available `Yes`
- Check on the VPS in /etc/shorewall/params.vpn that OMR_ADDR is the router side VPN IP (10.255.255.2 for glorytun TCP, the default VPN) `Yes`
- Check on the router if packets are coming on port 8080 from the VPN for example: tcpdump -i tun0 port 8080 `Yes`

If all is ok, then packets come to the router. Set a SNAT rule if not already done else check your firewall rules. `Yes but packets don't make it to the next router.` Please help.

## Specifications
  - OpenMPTCProuter version: v0.59.1-5.4 r0+16594-ce92de8c8c](https://github.com/ysurac/openmptcprouter)
  - OpenMPTCProuter VPS version: don't know how to find this.
  - OpenMPTCProuter VPS provider: vultr
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
As you set it's on another subnet, destination answer to ping from the router ? If not, it must answer and you have to add a new LAN interface in the destination subnet.

**Comment by ioogithub** [comment]
Thank you for troubleshooting help. This is what I see from pings:

LAN router is a gateway between OMR router and LAN network. It has two IP addresses:
1. LAN IP address: 192.168.1.1
2. LAN router IP address on OMR network (aka WAN): 192.168.2.6
3. OMR router IP address is: 192.168.2.1

- from OMR router: ping LAN IP address: fail
- from OMR router: ping LAN OMR IP address: ok
- from OMR router: ping destination webserver: fail

> you have to add a new LAN interface in the destination subnet.
Do you mean add a LAN interface on the OMR router for the destination subnet?

The traffic already works going out of network. Computers on the destination subnet can go out to the internet and access websites. This works:
- PC -> LAN Router -> OMR (via VPN) -> VPS -> Website

Also, if I disable VPS and run OMR in direct  access mode this works:
- PC -> LAN router -> OMR -> WAN1 -> Website

Traffic coming in doesn't work:
- PC on Internet -> VPS -> OMR (via VPN) -> xx

I thought if the traffic can go out then it should be an issue with the firewall? If this is wrong thinking please let me know so I can start researching how to add  LAN interface as you said.

**Comment by Ysurac** [comment]
In all case OMR must be able to contact what you wxant to reach.
To add a new LAN interface this can be done using the wizard or in Network->Interface menu and set interface in LAN firewall zone.

**Comment by ioogithub** [comment]
okay thanks, I also tried to create a static route but this did not work:
- before the change `ping reply "4 packets transmitted, 0 received, 100% packet loss, time 3082ms`
- after the change I get 'From 192.168.2.6 icmp_seq=2 Destination Port Unreachable'
so I guess this approach didn't work.

I have been researching creating the interface.

The LAN router already has an IP address on the OMR network via the OMR DHCP (192.168.2.6). Will this be a conflict?
Do I need a new subnet IP range in the OMR network or do I use the same range of the LAN network?

For example:
- LAN subnet is: 192.168.1.x
- OMR is subnet is: 192.168.2.x
- so for this new interface do I have to make 192.168.3.x?

Also what do I put for the default gateway of this new interface? Should it be the IP address assigned by OMR DHCP for the IP address of the LAN router? 192.168.2.6 or something else?

**Comment by ioogithub** [comment]
I can ping the web server (192.168.1.2) form OMR!

I did it with two settings
1. static route: 192.168.1.0/24 to 192.168.2.6.
2. I had to modify wan zone on LAN router to forward traffic to destination WAN (it was blocked).

From OMR documentation I enables 2 rules:
1. Forward port rule, same settings as screenshot
3. SNAT rule with destination address as the www server (192.168.1.2).

Back to the original problem:
- OMR: tcpdump -i tun0 port 80 i see packets
- OMR: tcpdump -i eth0 port 80 no packets here
- LAN router :tcpdump -i eth1 port 80 no packets
- www server: tcpdump -i eth0 port 80 no packets

So the last hop I see packets in tun0 on OMR. If I look at eth0 which i the gateway port between OMR and LAN router no packets and no packets after this.

If I enter the VPN IP:80 into a web browser I get OMR login but really I want to forward the packets to the www server. I do not need OMR available on the internet. Now that I can ping the www how can I forward port 80 to the www server?

**Comment by ioogithub** [comment]
@Ysurac: Working on this all day no success.

I can `nc` connect from OMR to www, send messages and trace the packet every hop :

- On OMR: `nc 192.168.1.222 80`, connection established, send message
- On OMR: `tcpdump -i tun0 port 80`, see packet
- On LAN router (WAN): `tcpdump -i eth0 port 80`, see packet
- On LAN router (LAN): `tcpdump -i eth1 port 80`, see packet
- On `www: nc -l -p 80` get message

but when I implement the two rules from this page: https://github.com/Ysurac/openmptcprouter/wiki/Port-forwarding and do a curl http://domain:80 I can't get from OMR `tun0` to OMR `eth0`. It always stops here and I get served the OMR luci interface. If I change to another port 8000 I never get past tun0. I tried to disable the firewall, didn;t work. 

Why can an nc TCP packet work but curl request for webpage never gets past tun0. What else can I try?

**Comment by Ysurac** [comment]
I need the result of ```uci show firewall```, ```ip a``` and ```ip r``` via SSH from the router.

**Comment by ioogithub** [comment]
Thank you, here is what I have.
- 
## ip a
```
default via 10.255.255.1 dev tun0 
default metric 1 
        nexthop via 100.64.x.x dev eth1 weight 2 
        nexthop via 10.0.y.y dev eth2 weight 1 
default via 100.64.x.x dev eth1 metric 3 
default via 10.0.y.y dev eth2 metric 4 
default via 10.255.255.1 dev tun0 metric 1200 
10.0.0.0/24 via 10.0.y.y dev eth2 
10.0.0.0/24 dev eth2 scope link metric 4 
10.255.255.1 dev tun0 proto kernel scope link src 10.255.255.2 
10.255.255.2 dev tun0 scope link metric 1200 
b.b.b.b dev eth1 proto static scope link src a.a.a.a metric 3 
100.64.0.0/10 dev eth1 scope link metric 3 
127.0.0.0/8 dev lo proto static scope link metric 6 
c.c.c.c metric 1 
        nexthop via 100.64.x.x dev eth1 weight 10 
        nexthop via 10.0.y.y dev eth2 weight 1
192.168.1.2 via 192.168.2.aaa dev eth0 
```
- Note 1: I redacted the ip addresses:
Note 2: OMR: (192.168.2.1), LAN router (192.168.1.1 and 192.168.2.aaa),  www server (192.168.1.2)
- Note2: I set a static route 192.168.1.2 (www server on LAN) via 192.168.2.aaa (LAN router IP assigned by OMR DHCP), it is pingable.

## ip r
```
1: lo: <LOOPBACK,UP,LOWER_UP,80000> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ip6tnl0@NONE: <NOARP,80000> mtu 1452 qdisc noop state DOWN group default qlen 1000
    link/tunnel6 :: brd ::
3: sit0@NONE: <NOARP,80000> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
4: gre0@NONE: <NOARP,80000> mtu 1476 qdisc noop state DOWN group default qlen 1000
    link/gre 0.0.0.0 brd 0.0.0.0
5: gretap0@NONE: <BROADCAST,MULTICAST,80000> mtu 1462 qdisc noop state DOWN group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
6: erspan0@NONE: <BROADCAST,MULTICAST,80000> mtu 1450 qdisc noop state DOWN group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
7: ip6gre0@NONE: <NOARP,80000> mtu 1448 qdisc noop state DOWN group default qlen 1000
    link/gre6 :: brd ::
8: bond0: <BROADCAST,MULTICAST,MASTER,80000> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff
9: teql0: <NOARP,80000> mtu 1500 qdisc noop state DOWN group default qlen 100
    link/void 
10: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP,80000> mtu 1500 qdisc mq state UP group default qlen 100
    link/ether dd:dd:dd:dd:dd:dd brd ff:ff:ff:ff:ff:ff
    inet 192.168.2.1/24 brd 192.168.2.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 b1b1:b1b1:b1b1::1/60 scope global noprefixroute 
       valid_lft forever preferred_lft forever
    inet6 c1c1::c1c1:c1c1:c1c1:c1c1/64 scope link 
       valid_lft forever preferred_lft forever
11: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 100
    link/ether cc:cc:cc:cc:cc:cc brd ff:ff:ff:ff:ff:ff
    inet 100.64.x.x/10 brd 100.x.255.255 scope global eth1
       valid_lft forever preferred_lft forever
12: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 qdisc mq state UP group default qlen 100
    link/ether bb:bb:bb:bb:bb:bb brd ff:ff:ff:ff:ff:ff
    inet 10.0.y.y/24 brd 10.0.0.255 scope global eth2
       valid_lft forever preferred_lft forever
13: eth3: <BROADCAST,MULTICAST,80000> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether aa:aa:aa:aa:a:aa brd ff:ff:ff:ff:ff:ff
24: tun0: <POINTOPOINT,MULTICAST,NOARP,PROMISC,UP,LOWER_UP,80000> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 100
    link/none 
    inet 10.255.255.2 peer 10.255.255.1/32 scope global tun0
       valid_lft forever preferred_lft forever
    inet6 a1a1::a1a1:a1a1;a1a1:a1a/64 scope link stable-privacy 
       valid_lft forever preferred_lft forever
27: ifb4tun0: <BROADCAST,NOARP,80000> mtu 1500 qdisc noop state DOWN group default qlen 32
    link/ether ff:ff:ff:ff:ff:ff brd ff:ff:ff:ff:ff:ff
```
Note: Bonding 2 WAN connections.

## uci show firewall
```
firewall.@defaults[0]=defaults
firewall.@defaults[0].syn_flood='1'
firewall.@defaults[0].disable_ipv6='0'
firewall.@defaults[0].input='REJECT'
firewall.@defaults[0].output='REJECT'
firewall.@defaults[0].forward='REJECT'
firewall.zone_lan=zone
firewall.zone_lan.name='lan'
firewall.zone_lan.input='ACCEPT'
firewall.zone_lan.mtu_fix='1'
firewall.zone_lan.forward='ACCEPT'
firewall.zone_lan.output='ACCEPT'
firewall.zone_lan.network='lan' 'localNIC'
firewall.zone_lan.auto_helper='1'
firewall.zone_wan=zone
firewall.zone_wan.name='wan'
firewall.zone_wan.output='ACCEPT'
firewall.zone_wan.masq='1'
firewall.zone_wan.mtu_fix='1'
firewall.zone_wan.input='REJECT'
firewall.zone_wan.forward='REJECT'
firewall.zone_wan.auto_helper='1'
firewall.zone_wan.network='wan1' 'wan2'
firewall.@rule[0]=rule
firewall.@rule[0].target='ACCEPT'
firewall.@rule[0].name='Allow-Lan-to-Wan'
firewall.@rule[0].dest='wan'
firewall.@rule[0].src='lan'
firewall.@rule[0].proto='all'
firewall.@rule[0].extra='! -o test_vpn'
firewall.@rule[1]=rule
firewall.@rule[1].name='Allow-DHCP-Renew'
firewall.@rule[1].src='wan'
firewall.@rule[1].proto='udp'
firewall.@rule[1].dest_port='68'
firewall.@rule[1].target='ACCEPT'
firewall.@rule[1].family='ipv4'
firewall.@rule[2]=rule
firewall.@rule[2].name='Allow-Ping'
firewall.@rule[2].src='wan'
firewall.@rule[2].proto='icmp'
firewall.@rule[2].icmp_type='echo-request'
firewall.@rule[2].family='ipv4'
firewall.@rule[2].target='ACCEPT'
firewall.@rule[3]=rule
firewall.@rule[3].name='Allow-IGMP'
firewall.@rule[3].src='wan'
firewall.@rule[3].proto='igmp'
firewall.@rule[3].family='ipv4'
firewall.@rule[3].target='ACCEPT'
firewall.@rule[4]=rule
firewall.@rule[4].name='Allow-DHCPv6'
firewall.@rule[4].src='wan'
firewall.@rule[4].proto='udp'
firewall.@rule[4].dest_port='546'
firewall.@rule[4].family='ipv6'
firewall.@rule[4].target='ACCEPT'
firewall.@rule[5]=rule
firewall.@rule[5].name='Allow-MLD'
firewall.@rule[5].src='wan'
firewall.@rule[5].proto='icmp'
firewall.@rule[5].src_ip='fe80::/10'
firewall.@rule[5].icmp_type='130/0' '131/0' '132/0' '143/0'
firewall.@rule[5].family='ipv6'
firewall.@rule[5].target='ACCEPT'
firewall.@rule[6]=rule
firewall.@rule[6].name='Allow-ICMPv6-Forward'
firewall.@rule[6].src='wan'
firewall.@rule[6].dest='*'
firewall.@rule[6].proto='icmp'
firewall.@rule[6].icmp_type='echo-request' 'echo-reply' 'destination-unreachable' 'packet-too-big' 'time-exceeded' 'bad-header' 'unknown-header-type'
firewall.@rule[6].limit='1000/sec'
firewall.@rule[6].family='ipv6'
firewall.@rule[6].target='ACCEPT'
firewall.@rule[7]=rule
firewall.@rule[7].name='Allow-IPSec-ESP'
firewall.@rule[7].src='wan'
firewall.@rule[7].dest='lan'
firewall.@rule[7].proto='esp'
firewall.@rule[7].target='ACCEPT'
firewall.@rule[8]=rule
firewall.@rule[8].name='Allow-ISAKMP'
firewall.@rule[8].src='wan'
firewall.@rule[8].dest='lan'
firewall.@rule[8].dest_port='500'
firewall.@rule[8].proto='udp'
firewall.@rule[8].target='ACCEPT'
firewall.@rule[9]=rule
firewall.@rule[9].name='Support-UDP-Traceroute'
firewall.@rule[9].src='wan'
firewall.@rule[9].dest_port='33434:33689'
firewall.@rule[9].proto='udp'
firewall.@rule[9].family='ipv4'
firewall.@rule[9].target='REJECT'
firewall.@rule[9].enabled='0'
firewall.@include[0]=include
firewall.@include[0].path='/etc/firewall.user'
firewall.@include[0].reload='1'
firewall.@rule[10]=rule
firewall.@rule[10].target='ACCEPT'
firewall.@rule[10].name='Allow-All-LAN-to-VPN'
firewall.@rule[10].dest='vpn'
firewall.@rule[10].src='lan'
firewall.@rule[10].proto='all'
firewall.zone_vpn=zone
firewall.zone_vpn.name='vpn'
firewall.zone_vpn.masq='1'
firewall.zone_vpn.forward='ACCEPT'
firewall.zone_vpn.output='ACCEPT'
firewall.zone_vpn.mtu_fix='1'
firewall.zone_vpn.input='REJECT'
firewall.zone_vpn.network='omr6in4' 'omrvpn'
firewall.zone_vpn.auto_helper='1'
firewall.@rule[11]=rule
firewall.@rule[11].target='ACCEPT'
firewall.@rule[11].name='Allow-All-Ping'
firewall.@rule[11].proto='icmp'
firewall.@rule[11].dest='*'
firewall.@rule[11].src='*'
firewall.@rule[11].icmp_type='echo-request'
firewall.@rule[11].limit='1000/sec'
firewall.@rule[12]=rule
firewall.@rule[12].target='ACCEPT'
firewall.@rule[12].name='Allow-VPN-ICMP'
firewall.@rule[12].proto='icmp'
firewall.@rule[12].src='vpn'
firewall.@rule[13]=rule
firewall.@rule[13].target='ACCEPT'
firewall.@rule[13].name='ICMPv6-Lan-to-OMR'
firewall.@rule[13].src='lan'
firewall.@rule[13].family='ipv6'
firewall.@rule[13].proto='icmp'
firewall.@rule[13].limit='1000/sec'
firewall.@rule[13].icmp_type='echo-reply destination-unreachable echo-request router-advertisement router-solicitation time-exceeded'
firewall.omr_server=include
firewall.omr_server.path='/etc/firewall.omr-server'
firewall.omr_server.reload='1'
firewall.gre_tunnel=include
firewall.gre_tunnel.path='/etc/firewall.gre-tunnel'
firewall.gre_tunnel.reload='0'
firewall.ttl=include
firewall.ttl.path='/etc/firewall.ttl'
firewall.ttl.reload='1'
firewall.blockquicproxy=rule
firewall.blockquicproxy.name='Block QUIC Proxy'
firewall.blockquicproxy.proto='udp'
firewall.blockquicproxy.dest_port='443'
firewall.blockquicproxy.target='DROP'
firewall.blockquicproxy.src='lan'
firewall.blockquicall=rule
firewall.blockquicall.name='Block QUIC All'
firewall.blockquicall.proto='udp'
firewall.blockquicall.src='*'
firewall.blockquicall.dest='*'
firewall.blockquicall.dest_port='443'
firewall.blockquicall.target='DROP'
firewall.allowicmpipv6=rule
firewall.allowicmpipv6.proto='icmp'
firewall.allowicmpipv6.target='ACCEPT'
firewall.allowicmpipv6.src='wan'
firewall.allowicmpipv6.name='Allow IPv6 ICMP'
firewall.allowicmpipv6.family='ipv6'
firewall.allowicmpipv6.limit='1000/sec'
firewall.allowicmpipv6.icmp_type='neighbour-advertisement neighbour-solicitation router-advertisement router-solicitation'
firewall.allowdhcpv6546=rule
firewall.allowdhcpv6546.target='ACCEPT'
firewall.allowdhcpv6546.src='wan'
firewall.allowdhcpv6546.proto='udp'
firewall.allowdhcpv6546.dest_port='547'
firewall.allowdhcpv6546.name='Allow DHCPv6 (546-to-547)'
firewall.allowdhcpv6546.family='ipv6'
firewall.allowdhcpv6546.src_port='546'
firewall.allowdhcpv6547=rule
firewall.allowdhcpv6547.target='ACCEPT'
firewall.allowdhcpv6547.src='wan'
firewall.allowdhcpv6547.proto='udp'
firewall.allowdhcpv6547.dest_port='546'
firewall.allowdhcpv6547.name='Allow DHCPv6 (547-to-546)'
firewall.allowdhcpv6547.family='ipv6'
firewall.allowdhcpv6547.src_port='547'
firewall.v2ray=include
firewall.v2ray.path='/etc/firewall.v2ray-rules'
firewall.v2ray.reload='0'
firewall.omr_bypass=include
firewall.omr_bypass.path='/etc/firewall.omr-bypass'
firewall.omr_bypass.reload='0'
firewall.miniupnpd=include
firewall.miniupnpd.type='script'
firewall.miniupnpd.path='/usr/share/miniupnpd/firewall.include'
firewall.miniupnpd.family='any'
firewall.miniupnpd.reload='1'
firewall.ss_rules=include
firewall.ss_rules.path='/etc/firewall.ss-rules'
firewall.ss_rules.reload='1'
firewall.@zone[3]=zone
firewall.@zone[3].name='test_vpn'
firewall.@zone[3].input='ACCEPT'
firewall.@zone[3].output='ACCEPT'
firewall.@zone[3].forward='ACCEPT'
firewall.@zone[3].masq='1'
firewall.@zone[3].network='test_vpn'
firewall.@forwarding[0]=forwarding
firewall.@forwarding[0].src='test_vpn'
firewall.@forwarding[0].dest='wan'
firewall.@forwarding[1]=forwarding
firewall.@forwarding[1].src='lan'
firewall.@forwarding[1].dest='test_vpn'
firewall.@forwarding[2]=forwarding
firewall.@forwarding[2].src='lan'
firewall.@forwarding[2].dest='wan'
firewall.@forwarding[3]=forwarding
firewall.@forwarding[3].src='lan'
firewall.@forwarding[3].dest='vpn'
firewall.@zone[4]=zone
firewall.@zone[4].name='localNIC'
firewall.@zone[4].input='ACCEPT'
firewall.@zone[4].output='ACCEPT'
firewall.@zone[4].forward='ACCEPT'
firewall.@zone[4].network='localNIC'
firewall.@forwarding[4]=forwarding
firewall.@forwarding[4].src='localNIC'
firewall.@forwarding[4].dest='lan'
firewall.@forwarding[5]=forwarding
firewall.@forwarding[5].src='lan'
firewall.@forwarding[5].dest='localNIC'
firewall.@rule[19]=rule
firewall.@rule[19].name='Allow-All-LocalNIC-To-LAN'
firewall.@rule[19].proto='all'
firewall.@rule[19].src='localNIC'
firewall.@rule[19].target='ACCEPT'
firewall.@redirect[0]=redirect
firewall.@redirect[0].target='DNAT'
firewall.@redirect[0].name='www'
firewall.@redirect[0].proto='tcp'
firewall.@redirect[0].dest='lan'
firewall.@redirect[0].src='vpn'
firewall.@redirect[0].src_dport='80'
firewall.@redirect[0].dest_port='80'
firewall.@redirect[0].dest_ip='192.168.2.1'
firewall.@nat[0]=nat
firewall.@nat[0].name='www'
firewall.@nat[0].proto='tcp'
firewall.@nat[0].src='lan'
firewall.@nat[0].target='SNAT'
firewall.@nat[0].dest_port='80'
firewall.@nat[0].snat_ip='192.168.2.1'
firewall.@nat[0].dest_ip='192.168.1.2'
```
Note: This configuration following the doc, if I do curl www.host.com:80:
- OMR: `tcpdump -i tun0 port 80`, packet here <--- stops here
- OMR: `tcpdump -i eth0 port 80`, no packet
- LAN router WAN: no packet
- LAN router LAN: no packet
- www server: no packet
- www apache log: no hit

### 2nd solution try:
If I deactivate the SNAT rule and modify the Port forward from:
`firewall.@redirect[0].dest_ip='192.168.2.1'` to
`firewall.@redirect[0].dest_ip='192.168.1.2'`

I get this result:
- OMR: `tcpdump -i tun0 port 80`, packet here
- OMR: `tcpdump -i eth0 port 80`, packet here <---- stop here
- LAN router WAN `tcpdump -i eth1 port 80`: no packet
- LAN router LAN: no packet
- www server: no packet
- www apache log: no hit

The packet makes it one more hop, passed though OMR router WAN port but `tcpdump -i eth1 port 80` on the Openwrt LAN router never sees the packet, I don't know is it in a format the LAN router cannot accept? I tried setting various combination of port forward, traffic rule etc but it never gets to the www server.

I want to use the first solution from the OMR doc but the packet never leaves OMR.

Thanks for looking this over, I appreciate it.
