### ISSUE TITLE
VPN is closed and STOPPED tun0  Frequent with one wifi interface

### ISSUE THREAD

**Issue by fareign** [Ysurac/openmptcprouter#2917]
## Expected Behavior
I use WIFI MT7922AM as a interface to test if it can work well.
<img width="838" alt="02" src="https://github.com/Ysurac/openmptcprouter/assets/15459/1421f3da-36a7-4afc-8431-14e07c6d4720">

then I find Tun0 stopped frequent.

### routerlog

Aug  7 03:57:02 OpenMPTCProuter user.notice mptcp: Reloading mptcp config due to ifup of omrvpn (tun0)
Aug  7 03:57:02 OpenMPTCProuter daemon.err glorytun[15754]: 47.106.225.139.65001: connected
Aug  7 03:57:04 OpenMPTCProuter user.notice post-tracking-post-tracking: Set firewall on server vps
Aug  7 03:57:12 OpenMPTCProuter daemon.err glorytun[15754]: 47.106.225.139.65001: key exchange failed
Aug  7 03:57:12 OpenMPTCProuter daemon.info glorytun[15754]: STOPPED tun0
Aug  7 03:57:13 OpenMPTCProuter daemon.err glorytun[15754]: 47.106.225.139.65001: connected
Aug  7 03:57:23 OpenMPTCProuter daemon.err glorytun[15754]: 47.106.225.139.65001: key exchange failed
Aug  7 03:57:23 OpenMPTCProuter daemon.info glorytun[15754]: STOPPED tun0
Aug  7 03:57:24 OpenMPTCProuter daemon.err glorytun[15754]: 47.106.225.139.65001: connected
Aug  7 03:57:25 OpenMPTCProuter daemon.info glorytun[15754]: STARTED tun0
Aug  7 03:57:25 OpenMPTCProuter user.notice post-tracking-post-tracking: Tunnel up : Replace default route by 10.255.255.1 dev tun0
Aug  7 03:58:59 OpenMPTCProuter user.notice post-tracking-post-tracking: omrvpn down because gateway down
Aug  7 03:58:59 OpenMPTCProuter user.notice post-tracking-post-tracking: Glorytun VPN down, restart it
Aug  7 03:58:59 OpenMPTCProuter daemon.info glorytun: starting glorytun vpn instance vpn
Aug  7 03:59:04 OpenMPTCProuter daemon.info procd: Instance glorytun::instance1 pid 15754 not stopped on SIGTERM, sending SIGKILL instead
Aug  7 03:59:04 OpenMPTCProuter daemon.notice netifd: Network device 'tun0' link is down
Aug  7 03:59:04 OpenMPTCProuter daemon.notice netifd: Interface 'omrvpn' has link connectivity loss
Aug  7 03:59:04 OpenMPTCProuter daemon.notice netifd: Interface 'omrvpn' is now down
Aug  7 03:59:04 OpenMPTCProuter daemon.notice ttyd[13749]: [2023/08/07 03:59:04:9482] N: rops_handle_POLLIN_netlink: DELADDR
Aug  7 03:59:04 OpenMPTCProuter daemon.notice ttyd[13749]: [2023/08/07 03:59:04:9492] N: rops_handle_POLLIN_netlink: DELADDR
Aug  7 03:59:04 OpenMPTCProuter daemon.notice netifd: Interface 'omrvpn' is disabled
Aug  7 03:59:05 OpenMPTCProuter daemon.err glorytun[29797]: MPTCP upstream enabled
Aug  7 03:59:05 OpenMPTCProuter daemon.info glorytun[29797]: INITIALIZED tun0
Aug  7 03:59:05 OpenMPTCProuter daemon.notice netifd: Interface 'omrvpn' is enabled
Aug  7 03:59:05 OpenMPTCProuter daemon.notice netifd: Network device 'tun0' link is up
Aug  7 03:59:05 OpenMPTCProuter daemon.notice netifd: Interface 'omrvpn' has link connectivity 
Aug  7 03:59:05 OpenMPTCProuter daemon.notice netifd: Interface 'omrvpn' is setting up now
Aug  7 03:59:05 OpenMPTCProuter daemon.notice netifd: Interface 'omrvpn' is now up
Aug  7 03:59:05 OpenMPTCProuter user.notice firewall: Reloading firewall due to ifup of omrvpn (tun0)
Aug  7 03:59:05 OpenMPTCProuter user.notice firewall.omr-server: Firewall reload, set server part firewall reloading
Aug  7 03:59:05 OpenMPTCProuter daemon.notice ttyd[13749]: [2023/08/07 03:59:05:8422] N: rops_handle_POLLIN_netlink: DELADDR
Aug  7 03:59:05 OpenMPTCProuter user.notice mptcp: Reloading mptcp config due to ifup of omrvpn (tun0)
Aug  7 03:59:06 OpenMPTCProuter daemon.err glorytun[29797]: 47.106.225.139.65001: connected
Aug  7 03:59:14 OpenMPTCProuter user.notice post-tracking-post-tracking: Set firewall on server vps
Aug  7 03:59:16 OpenMPTCProuter daemon.err glorytun[29797]: 47.106.225.139.65001: key exchange failed
Aug  7 03:59:16 OpenMPTCProuter daemon.info glorytun[29797]: STOPPED tun0
Aug  7 03:59:17 OpenMPTCProuter daemon.err glorytun[29797]: 47.106.225.139.65001: connected
Aug  7 03:59:27 OpenMPTCProuter daemon.err glorytun[29797]: 47.106.225.139.65001: key exchange failed
Aug  7 03:59:27 OpenMPTCProuter daemon.info glorytun[29797]: STOPPED tun0
Aug  7 03:59:28 OpenMPTCProuter daemon.err glorytun[29797]: 47.106.225.139.65001: connected
Aug  7 03:59:28 OpenMPTCProuter daemon.info glorytun[29797]: STARTED tun0
Aug  7 03:59:28 OpenMPTCProuter user.notice post-tracking-post-tracking: Tunnel up : Replace default route by 10.255.255.1 dev tun0
Aug  7 04:03:47 OpenMPTCProuter user.notice post-tracking-post-tracking: omrvpn down because gateway down
Aug  7 04:03:47 OpenMPTCProuter user.notice post-tracking-post-tracking: Glorytun VPN down, restart it
Aug  7 04:03:47 OpenMPTCProuter daemon.info glorytun[29797]: STOPPED tun0
Aug  7 04:03:47 OpenMPTCProuter daemon.notice ttyd[13749]: [2023/08/07 04:03:47:2686] N: rops_handle_POLLIN_netlink: DELADDR
Aug  7 04:03:47 OpenMPTCProuter daemon.notice netifd: Network device 'tun0' link is down
Aug  7 04:03:47 OpenMPTCProuter daemon.notice netifd: Interface 'omrvpn' has link connectivity loss
Aug  7 04:03:47 OpenMPTCProuter daemon.notice netifd: Interface 'omrvpn' is now down
Aug  7 04:03:47 OpenMPTCProuter daemon.notice ttyd[13749]: [2023/08/07 04:03:47:2695] N: rops_handle_POLLIN_netlink: DELADDR
Aug  7 04:03:47 OpenMPTCProuter daemon.info glorytun: starting glorytun vpn instance vpn
Aug  7 04:03:47 OpenMPTCProuter daemon.notice netifd: Interface 'omrvpn' is disabled
Aug  7 04:03:47 OpenMPTCProuter daemon.err glorytun[26785]: MPTCP upstream enabled
Aug  7 04:03:47 OpenMPTCProuter daemon.info glorytun[26785]: INITIALIZED tun0
Aug  7 04:03:47 OpenMPTCProuter daemon.notice netifd: Interface 'omrvpn' is enabled
Aug  7 04:03:47 OpenMPTCProuter daemon.notice netifd: Network device 'tun0' link is up
Aug  7 04:03:47 OpenMPTCProuter daemon.notice netifd: Interface 'omrvpn' has link connectivity 
Aug  7 04:03:47 OpenMPTCProuter daemon.notice netifd: Interface 'omrvpn' is setting up now
Aug  7 04:03:47 OpenMPTCProuter daemon.notice netifd: Interface 'omrvpn' is now up
Aug  7 04:03:47 OpenMPTCProuter user.notice firewall: Reloading firewall due to ifup of omrvpn (tun0)
Aug  7 04:03:47 OpenMPTCProuter user.notice firewall.omr-server: Firewall reload, set server part firewall reloading
Aug  7 04:03:48 OpenMPTCProuter daemon.notice ttyd[13749]: [2023/08/07 04:03:48:1462] N: rops_handle_POLLIN_netlink: DELADDR
Aug  7 04:03:48 OpenMPTCProuter user.notice mptcp: Reloading mptcp config due to ifup of omrvpn (tun0)
Aug  7 04:03:48 OpenMPTCProuter daemon.err glorytun[26785]: 47.106.225.139.65001: connected
Aug  7 04:03:48 OpenMPTCProuter daemon.info glorytun[26785]: STARTED tun0
Aug  7 04:03:55 OpenMPTCProuter user.notice post-tracking-post-tracking: Set firewall on server vps
Aug  7 04:03:55 OpenMPTCProuter user.notice post-tracking-post-tracking: Tunnel up : Replace default route by 10.255.255.1 dev tun0
Aug  7 04:05:28 OpenMPTCProuter user.notice post-tracking-post-tracking: omrvpn down because gateway down
Aug  7 04:05:28 OpenMPTCProuter user.notice post-tracking-post-tracking: Glorytun VPN down, restart it
Aug  7 04:05:28 OpenMPTCProuter daemon.info glorytun: starting glorytun vpn instance vpn
Aug  7 04:05:33 OpenMPTCProuter daemon.info procd: Instance glorytun::instance1 pid 26785 not stopped on SIGTERM, sending SIGKILL instead
Aug  7 04:05:33 OpenMPTCProuter daemon.notice netifd: Network device 'tun0' link is down
Aug  7 04:05:33 OpenMPTCProuter daemon.notice netifd: Interface 'omrvpn' has link connectivity loss
Aug  7 04:05:33 OpenMPTCProuter daemon.notice netifd: Interface 'omrvpn' is now down
Aug  7 04:05:33 OpenMPTCProuter daemon.notice ttyd[13749]: [2023/08/07 04:05:33:7299] N: rops_handle_POLLIN_netlink: DELADDR
Aug  7 04:05:33 OpenMPTCProuter daemon.notice ttyd[13749]: [2023/08/07 04:05:33:7306] N: rops_handle_POLLIN_netlink: DELADDR
Aug  7 04:05:33 OpenMPTCProuter daemon.notice netifd: Interface 'omrvpn' is disabled
Aug  7 04:05:33 OpenMPTCProuter daemon.err glorytun[6402]: MPTCP upstream enabled
Aug  7 04:05:33 OpenMPTCProuter daemon.info glorytun[6402]: INITIALIZED tun0
Aug  7 04:05:33 OpenMPTCProuter daemon.notice netifd: Interface 'omrvpn' is enabled
Aug  7 04:05:33 OpenMPTCProuter daemon.notice netifd: Network device 'tun0' link is up
Aug  7 04:05:33 OpenMPTCProuter daemon.notice netifd: Interface 'omrvpn' has link connectivity 
Aug  7 04:05:33 OpenMPTCProuter daemon.notice netifd: Interface 'omrvpn' is setting up now
Aug  7 04:05:33 OpenMPTCProuter daemon.notice netifd: Interface 'omrvpn' is now up
Aug  7 04:05:34 OpenMPTCProuter user.notice firewall: Reloading firewall due to ifup of omrvpn (tun0)
Aug  7 04:05:34 OpenMPTCProuter user.notice firewall.omr-server: Firewall reload, set server part firewall reloading
Aug  7 04:05:34 OpenMPTCProuter daemon.notice ttyd[13749]: [2023/08/07 04:05:34:6183] N: rops_handle_POLLIN_netlink: DELADDR
Aug  7 04:05:34 OpenMPTCProuter user.notice mptcp: Reloading mptcp config due to ifup of omrvpn (tun0)
Aug  7 04:05:34 OpenMPTCProuter daemon.err glorytun[6402]: 47.106.225.139.65001: connected
Aug  7 04:05:34 OpenMPTCProuter daemon.info glorytun[6402]: STARTED tun0
Aug  7 04:05:35 OpenMPTCProuter user.notice post-tracking-post-tracking: Set firewall on server vps
Aug  7 04:05:43 OpenMPTCProuter user.notice post-tracking-post-tracking: Tunnel up : Replace default route by 10.255.255.1 dev tun0
Aug  7 04:07:41 OpenMPTCProuter user.notice post-tracking-post-tracking: omrvpn down because gateway down
Aug  7 04:07:41 OpenMPTCProuter user.notice post-tracking-post-tracking: Glorytun VPN down, restart it
Aug  7 04:07:41 OpenMPTCProuter daemon.info glorytun: starting glorytun vpn instance vpn
Aug  7 04:07:46 OpenMPTCProuter daemon.info procd: Instance glorytun::instance1 pid 6402 not stopped on SIGTERM, sending SIGKILL instead
Aug  7 04:07:46 OpenMPTCProuter daemon.notice netifd: Network device 'tun0' link is down
Aug  7 04:07:46 OpenMPTCProuter daemon.notice netifd: Interface 'omrvpn' has link connectivity loss
Aug  7 04:07:46 OpenMPTCProuter daemon.notice netifd: Interface 'omrvpn' is now down
Aug  7 04:07:46 OpenMPTCProuter daemon.notice ttyd[13749]: [2023/08/07 04:07:46:2500] N: rops_handle_POLLIN_netlink: DELADDR
Aug  7 04:07:46 OpenMPTCProuter daemon.notice ttyd[13749]: [2023/08/07 04:07:46:2509] N: rops_handle_POLLIN_netlink: DELADDR
Aug  7 04:07:46 OpenMPTCProuter daemon.notice netifd: Interface 'omrvpn' is disabled
Aug  7 04:07:46 OpenMPTCProuter daemon.err glorytun[20630]: MPTCP upstream enabled
Aug  7 04:07:46 OpenMPTCProuter daemon.info glorytun[20630]: INITIALIZED tun0
Aug  7 04:07:46 OpenMPTCProuter daemon.notice netifd: Interface 'omrvpn' is enabled
Aug  7 04:07:46 OpenMPTCProuter daemon.notice netifd: Network device 'tun0' link is up
Aug  7 04:07:46 OpenMPTCProuter daemon.notice netifd: Interface 'omrvpn' has link connectivity 
Aug  7 04:07:46 OpenMPTCProuter daemon.notice netifd: Interface 'omrvpn' is setting up now
Aug  7 04:07:46 OpenMPTCProuter daemon.notice netifd: Interface 'omrvpn' is now up
Aug  7 04:07:46 OpenMPTCProuter user.notice firewall: Reloading firewall due to ifup of omrvpn (tun0)
Aug  7 04:07:46 OpenMPTCProuter user.notice firewall.omr-server: Firewall reload, set server part firewall reloading
Aug  7 04:07:47 OpenMPTCProuter daemon.notice ttyd[13749]: [2023/08/07 04:07:47:1776] N: rops_handle_POLLIN_netlink: DELADDR
Aug  7 04:07:47 OpenMPTCProuter user.notice mptcp: Reloading mptcp config due to ifup of omrvpn (tun0)
Aug  7 04:07:47 OpenMPTCProuter daemon.err glorytun[20630]: 47.106.225.139.65001: connected
Aug  7 04:07:49 OpenMPTCProuter user.notice post-tracking-post-tracking: Set firewall on server vps
Aug  7 04:07:57 OpenMPTCProuter daemon.err glorytun[20630]: 47.106.225.139.65001: key exchange failed
Aug  7 04:07:57 OpenMPTCProuter daemon.info glorytun[20630]: STOPPED tun0
Aug  7 04:07:58 OpenMPTCProuter daemon.err glorytun[20630]: 47.106.225.139.65001: connected
Aug  7 04:08:08 OpenMPTCProuter daemon.err glorytun[20630]: 47.106.225.139.65001: key exchange failed
Aug  7 04:08:08 OpenMPTCProuter daemon.info glorytun[20630]: STOPPED tun0
Aug  7 04:08:09 OpenMPTCProuter daemon.err glorytun[20630]: 47.106.225.139.65001: connected
Aug  7 04:08:10 OpenMPTCProuter daemon.info glorytun[20630]: STARTED tun0
Aug  7 04:08:11 OpenMPTCProuter user.notice post-tracking-post-tracking: Tunnel up : Replace default route by 10.255.255.1 dev tun0
Aug  7 04:10:39 OpenMPTCProuter user.notice post-tracking-post-tracking: omrvpn down because gateway down
Aug  7 04:10:39 OpenMPTCProuter user.notice post-tracking-post-tracking: Glorytun VPN down, restart it
Aug  7 04:10:39 OpenMPTCProuter daemon.info glorytun: starting glorytun vpn instance vpn
Aug  7 04:10:44 OpenMPTCProuter daemon.info procd: Instance glorytun::instance1 pid 20630 not stopped on SIGTERM, sending SIGKILL instead
Aug  7 04:10:44 OpenMPTCProuter daemon.notice netifd: Network device 'tun0' link is down
Aug  7 04:10:44 OpenMPTCProuter daemon.notice netifd: Interface 'omrvpn' has link connectivity loss
Aug  7 04:10:44 OpenMPTCProuter daemon.notice netifd: Interface 'omrvpn' is now down
Aug  7 04:10:44 OpenMPTCProuter daemon.notice ttyd[13749]: [2023/08/07 04:10:44:8574] N: rops_handle_POLLIN_netlink: DELADDR
Aug  7 04:10:44 OpenMPTCProuter daemon.notice ttyd[13749]: [2023/08/07 04:10:44:8584] N: rops_handle_POLLIN_netlink: DELADDR
Aug  7 04:10:44 OpenMPTCProuter daemon.notice netifd: Interface 'omrvpn' is disabled
Aug  7 04:10:44 OpenMPTCProuter daemon.err glorytun[6325]: MPTCP upstream enabled
Aug  7 04:10:44 OpenMPTCProuter daemon.notice netifd: Interface 'omrvpn' is enabled
Aug  7 04:10:44 OpenMPTCProuter daemon.notice netifd: Network device 'tun0' link is up
Aug  7 04:10:44 OpenMPTCProuter daemon.notice netifd: Interface 'omrvpn' has link connectivity 
Aug  7 04:10:44 OpenMPTCProuter daemon.notice netifd: Interface 'omrvpn' is setting up now
Aug  7 04:10:44 OpenMPTCProuter daemon.notice netifd: Interface 'omrvpn' is now up
Aug  7 04:10:44 OpenMPTCProuter daemon.info glorytun[6325]: INITIALIZED tun0
Aug  7 04:10:45 OpenMPTCProuter user.notice firewall: Reloading firewall due to ifup of omrvpn (tun0)
Aug  7 04:10:45 OpenMPTCProuter user.notice firewall.omr-server: Firewall reload, set server part firewall reloading
Aug  7 04:10:45 OpenMPTCProuter daemon.notice ttyd[13749]: [2023/08/07 04:10:45:6830] N: rops_handle_POLLIN_netlink: DELADDR
Aug  7 04:10:45 OpenMPTCProuter user.notice mptcp: Reloading mptcp config due to ifup of omrvpn (tun0)
Aug  7 04:10:46 OpenMPTCProuter daemon.err glorytun[6325]: 47.106.225.139.65001: connected
Aug  7 04:10:46 OpenMPTCProuter user.notice post-tracking-post-tracking: Set firewall on server vps
Aug  7 04:10:56 OpenMPTCProuter daemon.err glorytun[6325]: 47.106.225.139.65001: key exchange failed
Aug  7 04:10:56 OpenMPTCProuter daemon.info glorytun[6325]: STOPPED tun0
Aug  7 04:10:57 OpenMPTCProuter daemon.err glorytun[6325]: 47.106.225.139.65001: connected
Aug  7 04:11:07 OpenMPTCProuter daemon.err glorytun[6325]: 47.106.225.139.65001: key exchange failed
Aug  7 04:11:07 OpenMPTCProuter daemon.info glorytun[6325]: STOPPED tun0
Aug  7 04:11:08 OpenMPTCProuter daemon.err glorytun[6325]: 47.106.225.139.65001: connected
Aug  7 04:11:18 OpenMPTCProuter daemon.err glorytun[6325]: 47.106.225.139.65001: key exchange failed
Aug  7 04:11:18 OpenMPTCProuter daemon.info glorytun[6325]: STOPPED tun0
Aug  7 04:11:19 OpenMPTCProuter daemon.err glorytun[6325]: 47.106.225.139.65001: connected
Aug  7 04:11:19 OpenMPTCProuter daemon.info glorytun[6325]: STARTED tun0
Aug  7 04:11:19 OpenMPTCProuter user.notice post-tracking-post-tracking: Tunnel up : Replace default route by 10.255.255.1 dev tun0

### VPS LOG
Aug  7 12:05:01 iZwz9j49zfsqj6oedh7guqZ CRON[77149]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Aug  7 12:05:07 iZwz9j49zfsqj6oedh7guqZ OMR-Service: No answer from VPN client end, restart Glorytun-TCP
Aug  7 12:05:07 iZwz9j49zfsqj6oedh7guqZ systemd[1]: Stopping Glorytun TCP on tun0...
Aug  7 12:05:07 iZwz9j49zfsqj6oedh7guqZ glorytun-tcp-run[60655]: INITIALIZED gt-tun0
Aug  7 12:05:07 iZwz9j49zfsqj6oedh7guqZ glorytun-tcp-run[60655]: STARTED gt-tun0
Aug  7 12:05:07 iZwz9j49zfsqj6oedh7guqZ glorytun-tcp-run[60655]: STOPPED gt-tun0
Aug  7 12:05:07 iZwz9j49zfsqj6oedh7guqZ glorytun-tcp-run[60655]: STARTED gt-tun0
Aug  7 12:05:07 iZwz9j49zfsqj6oedh7guqZ glorytun-tcp-run[60655]: STOPPED gt-tun0
Aug  7 12:05:07 iZwz9j49zfsqj6oedh7guqZ systemd-networkd[474]: gt-tun0: Link DOWN
Aug  7 12:05:07 iZwz9j49zfsqj6oedh7guqZ systemd-networkd[474]: gt-tun0: Lost carrier
Aug  7 12:05:07 iZwz9j49zfsqj6oedh7guqZ systemd[1]: glorytun-tcp@tun0.service: Succeeded.
Aug  7 12:05:07 iZwz9j49zfsqj6oedh7guqZ systemd[1]: Stopped Glorytun TCP on tun0.
Aug  7 12:05:07 iZwz9j49zfsqj6oedh7guqZ systemd[1]: glorytun-tcp@tun0.service: Consumed 3.168s CPU time.
Aug  7 12:05:07 iZwz9j49zfsqj6oedh7guqZ systemd[1]: Starting Glorytun TCP on tun0...
Aug  7 12:05:07 iZwz9j49zfsqj6oedh7guqZ glorytun-tcp-run[77215]: MPTCP upstream enabled
Aug  7 12:05:07 iZwz9j49zfsqj6oedh7guqZ systemd-networkd[474]: gt-tun0: Link UP
Aug  7 12:05:07 iZwz9j49zfsqj6oedh7guqZ systemd-networkd[474]: gt-tun0: Gained carrier
Aug  7 12:05:07 iZwz9j49zfsqj6oedh7guqZ systemd-networkd[474]: gt-tun0: Gained IPv6LL
Aug  7 12:05:07 iZwz9j49zfsqj6oedh7guqZ systemd-udevd[77212]: ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.
Aug  7 12:05:07 iZwz9j49zfsqj6oedh7guqZ systemd[1]: Started Glorytun TCP on tun0.
Aug  7 12:05:34 iZwz9j49zfsqj6oedh7guqZ glorytun-tcp-run[77215]: ::ffff:120.228.112.198.24205: connected
Aug  7 12:06:04 iZwz9j49zfsqj6oedh7guqZ ss-server[43626]: getpeername: Transport endpoint is not connected
Aug  7 12:06:39 iZwz9j49zfsqj6oedh7guqZ ss-server[43626]: getpeername: Transport endpoint is not connected
Aug  7 12:07:12 iZwz9j49zfsqj6oedh7guqZ systemd[1]: Created slice User Slice of UID 0.
Aug  7 12:07:12 iZwz9j49zfsqj6oedh7guqZ systemd[1]: Starting User Runtime Directory /run/user/0...
Aug  7 12:07:12 iZwz9j49zfsqj6oedh7guqZ systemd[1]: Finished User Runtime Directory /run/user/0.
Aug  7 12:07:12 iZwz9j49zfsqj6oedh7guqZ systemd[1]: Starting User Manager for UID 0...
Aug  7 12:07:12 iZwz9j49zfsqj6oedh7guqZ systemd[83285]: Queued start job for default target Main User Target.
Aug  7 12:07:12 iZwz9j49zfsqj6oedh7guqZ systemd[83285]: Created slice User Application Slice.
Aug  7 12:07:12 iZwz9j49zfsqj6oedh7guqZ systemd[83285]: Reached target Paths.
Aug  7 12:07:12 iZwz9j49zfsqj6oedh7guqZ systemd[83285]: Reached target Timers.
Aug  7 12:07:12 iZwz9j49zfsqj6oedh7guqZ systemd[83285]: Starting D-Bus User Message Bus Socket.
Aug  7 12:07:12 iZwz9j49zfsqj6oedh7guqZ systemd[83285]: Listening on GnuPG network certificate management daemon.
Aug  7 12:07:12 iZwz9j49zfsqj6oedh7guqZ systemd[83285]: Listening on GnuPG cryptographic agent and passphrase cache (access for web browsers).
Aug  7 12:07:12 iZwz9j49zfsqj6oedh7guqZ systemd[83285]: Listening on GnuPG cryptographic agent and passphrase cache (restricted).
Aug  7 12:07:12 iZwz9j49zfsqj6oedh7guqZ systemd[83285]: Listening on GnuPG cryptographic agent (ssh-agent emulation).
Aug  7 12:07:12 iZwz9j49zfsqj6oedh7guqZ systemd[83285]: Listening on GnuPG cryptographic agent and passphrase cache.
Aug  7 12:07:12 iZwz9j49zfsqj6oedh7guqZ systemd[83285]: Listening on debconf communication socket.
Aug  7 12:07:12 iZwz9j49zfsqj6oedh7guqZ systemd[83285]: Listening on D-Bus User Message Bus Socket.
Aug  7 12:07:12 iZwz9j49zfsqj6oedh7guqZ systemd[83285]: Reached target Sockets.
Aug  7 12:07:12 iZwz9j49zfsqj6oedh7guqZ systemd[83285]: Reached target Basic System.
Aug  7 12:07:12 iZwz9j49zfsqj6oedh7guqZ systemd[1]: Started User Manager for UID 0.
Aug  7 12:07:12 iZwz9j49zfsqj6oedh7guqZ systemd[1]: Started Session 7 of user root.
Aug  7 12:07:12 iZwz9j49zfsqj6oedh7guqZ systemd[83285]: Reached target Main User Target.
Aug  7 12:07:12 iZwz9j49zfsqj6oedh7guqZ systemd[83285]: Startup finished in 59ms.
Aug  7 12:07:14 iZwz9j49zfsqj6oedh7guqZ OMR-Service: Restart Glorytun-UDP
Aug  7 12:07:14 iZwz9j49zfsqj6oedh7guqZ systemd[1]: Stopping Glorytun UDP on tun0...
Aug  7 12:07:14 iZwz9j49zfsqj6oedh7guqZ systemd-networkd[474]: gt-udp-tun0: Lost carrier
Aug  7 12:07:14 iZwz9j49zfsqj6oedh7guqZ systemd[1]: glorytun-udp@tun0.service: Succeeded.
Aug  7 12:07:14 iZwz9j49zfsqj6oedh7guqZ systemd[1]: Stopped Glorytun UDP on tun0.
Aug  7 12:07:14 iZwz9j49zfsqj6oedh7guqZ systemd[1]: Starting Glorytun UDP on tun0...
Aug  7 12:07:14 iZwz9j49zfsqj6oedh7guqZ systemd-networkd[474]: gt-udp-tun0: Gained carrier
Aug  7 12:07:14 iZwz9j49zfsqj6oedh7guqZ glorytun-udp-run[83349]: running on device gt-udp-tun0 as pid 83349
Aug  7 12:07:14 iZwz9j49zfsqj6oedh7guqZ systemd[1]: Started Glorytun UDP on tun0.
Aug  7 12:07:22 iZwz9j49zfsqj6oedh7guqZ ss-server[43626]: getpeername: Transport endpoint is not connected
Aug  7 12:07:32 iZwz9j49zfsqj6oedh7guqZ ss-server[43626]: getpeername: Transport endpoint is not connected
Aug  7 12:08:08 iZwz9j49zfsqj6oedh7guqZ glorytun-tcp-run[77215]: ::ffff:120.228.112.198.24552: connected
Aug  7 12:08:08 iZwz9j49zfsqj6oedh7guqZ glorytun-tcp-run[77215]: ::ffff:120.228.112.198.24552: key exchange failed
Aug  7 12:08:09 iZwz9j49zfsqj6oedh7guqZ glorytun-tcp-run[77215]: ::ffff:120.228.112.198.23571: connected
Aug  7 12:08:09 iZwz9j49zfsqj6oedh7guqZ glorytun-tcp-run[77215]: ::ffff:120.228.112.198.23571: key exchange failed
Aug  7 12:08:10 iZwz9j49zfsqj6oedh7guqZ glorytun-tcp-run[77215]: ::ffff:120.228.112.198.23601: connected
Aug  7 12:08:21 iZwz9j49zfsqj6oedh7guqZ ss-server[43626]: remote recv: Connection reset by peer
Aug  7 12:10:00 iZwz9j49zfsqj6oedh7guqZ systemd[1]: Starting system activity accounting tool...
Aug  7 12:10:00 iZwz9j49zfsqj6oedh7guqZ systemd[1]: sysstat-collect.service: Succeeded.
Aug  7 12:10:00 iZwz9j49zfsqj6oedh7guqZ systemd[1]: Finished system activity accounting tool.
Aug  7 12:10:16 iZwz9j49zfsqj6oedh7guqZ OMR-Service: No answer from VPN client end, restart Glorytun-TCP
Aug  7 12:10:16 iZwz9j49zfsqj6oedh7guqZ systemd[1]: Stopping Glorytun TCP on tun0...
Aug  7 12:10:16 iZwz9j49zfsqj6oedh7guqZ glorytun-tcp-run[77215]: ::ffff:120.228.112.198.23601: shutdown

## Current Behavior

if I use a  cable to do the same thing,it works well. So the internet is OK

If I use wifi without OMR, it can work but not well ,some times like this. 
<img width="1193" alt="05" src="https://github.com/Ysurac/openmptcprouter/assets/15459/96f3ad07-32d3-4b54-9500-226a4748b868">

## Possible Solution

So I think there must are something with WIFI, and also something with OMR to improve this ERRO.

## Context (Environment)
wifi:MT7922AM
wifi driver:linux firmware 2023-0625,mt76 driver is 2023-05-13

all of setting is defaut

Push flow is SRT with 1080P 3mb

middle load ping from router
<img width="400" alt="03" src="https://github.com/Ysurac/openmptcprouter/assets/15459/c6d7b4a6-a11b-4319-bb3c-c8bb5a0ba76c">

idle ping from router
<img width="412" alt="04" src="https://github.com/Ysurac/openmptcprouter/assets/15459/1f6caa2d-053d-4ead-ac11-6c04dcb6ed5b">

another test:
if I close OMR, I do speedtest. it works well.
if open OMR do speedtest .then wifi will be broken down
<img width="543" alt="01" src="https://github.com/Ysurac/openmptcprouter/assets/15459/39ff2069-58c1-415d-a23e-8c8ded96f492">

## Specifications

  - OpenMPTCProuter version: 0.59.2 lastest 5.15 kernel
  - OpenMPTCProuter VPS version: 0.1029 upstream
  - OpenMPTCProuter VPS provider:aliyun
  - OpenMPTCProuter platform:  x86_64 
  - Country:cn

**Comment by Ysurac** [comment]
You should use 6.1 kernel on this alpha release, 5.15 kernel will not be a release.
Did you enabled SQM with download and upload speed ?

**Comment by fareign** [comment]
> You should use 6.1 kernel on this alpha release, 5.15 kernel will not be a release. Did you enabled SQM with download and upload speed ?

enabled SQM but not enable sqm-atuorate ,I speed not settinng is 0.

**Comment by fareign** [comment]
I test enable or disable sqm ,enable sqm-autorate or disable . is the same .
I think this may help us to find the reason which cause VPN dislink from VPS.
the ping  packages lost TX = 11059，RX = 11025，lost = 34 (0% ).
最短 = 0ms，最长 = 117ms，average = 4ms

**Comment by Ysurac** [comment]
Can be due to saturation of the link, it's what SQM is made for (with download/upload speed value set)
Can be due to driver bug (use 6.1 based alpha release)
Can be due to a bad wifi link

**Comment by fareign** [comment]
test with QCA6390 is OK.
 must be something with wifi. but wifi link looks well. 
if I use RTMP, nothing VPN also closed, but every works well .beacuase no traffic use VPN.
