### ISSUE TITLE
Multiple Instances of openmptcprouter in same subnet

### ISSUE THREAD

**Issue by iEddie-cmd** [Ysurac/openmptcprouter#2918]
Hi,
how can I achieve running multiple instances of openmptcprouter in same WAN subnet? Running multiple so far starts breaking openmptcprouter?
WAN Gateway down, Not pingable gateways,

root@OpenMPICProuter:™# [
45.9503061
mptcp_init4_subsockets: MPTCP subsocket connect() failed, error - 19
45.9509041
_mptcp_init4_subsockets: MPICP subsocket connect() failed, error -19
46.0561651
_mptcp_init4_subsockets: MPICP subsocket connect() failed, error -19
46.0567991
_mptcp_init4_subsockets: MPICP subsocket connect() failed, error
-19
77.4875481
mptcp_init4_subsockets: token 0x11610992 bind() to 10.255.247.3 index 41 failed, error -99

**Comment by Ysurac** [comment]
Please use the template when you open an issue (I need OpenMPTCProuter version/kernel, VPS version,...)
I also need a screenshot of System->OpenMPTCProuter, status tab, it will be easier to check what you have currently.
