### ISSUE TITLE
proxy encryption can't setting to aes-256-gcm 

### ISSUE THREAD

**Issue by fareign** [Ysurac/openmptcprouter#2919]
after this update
https://github.com/Ysurac/openmptcprouter-feeds/commit/8e2f33ac32df446f200c5e25a05fe454b64434c9

I test 5.15and 6.1 kernel.

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - OpenMPTCProuter version: 
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter VPS provider:
  - OpenMPTCProuter platform: 
  - Country:

**Comment by Ysurac** [comment]
It's a know problem, will be solved in next snapshot. It's a display issue.

**Comment by fareign** [comment]
OK,closed it
