### ISSUE TITLE
how to change this dns?

### ISSUE THREAD

**Issue by fareign** [Ysurac/openmptcprouter#2921]
## Expected Behavior
<img width="696" alt="06" src="https://github.com/Ysurac/openmptcprouter/assets/15459/583f608c-e694-41c4-8917-a93e3d5e33c3">

## Specifications

  - OpenMPTCProuter version: 
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter VPS provider:
  - OpenMPTCProuter platform:

**Comment by Ysurac** [comment]
They are used only for OMR-Tracker to check connection status.

**Comment by fareign** [comment]
> They are used only for OMR-Tracker to check connection status.

but I change all DNS in OMR-tracker which can't open or PING. not find this.

**Comment by Ysurac** [comment]
114dns is also used if you select China in the wizard, this can be modified in Network->DHCP&DNS, it's 114.114.114.114
For the 8.8.8.8, can be used by SQM-Autorate in snapshot.

**Comment by fareign** [comment]
I try to ping them,but none of them can reply.

<img width="696" alt="07" src="https://github.com/Ysurac/openmptcprouter/assets/15459/5522f680-6b19-4f50-95a7-1ba6ca54d43d">
<img width="474" alt="08" src="https://github.com/Ysurac/openmptcprouter/assets/15459/d23b7b03-d5f2-4ef1-b5f7-5ad9c5ab6d03">

**Comment by Ysurac** [comment]
makaki.miuku.net and time.neu.edu.cn are NTP time servers.

**Comment by fareign** [comment]
OK,thank you!
