### ISSUE TITLE
Name of wan interfaces.

### ISSUE THREAD

**Issue by psfabio** [Ysurac/openmptcprouter#2925]
## Expected Behavior
to know the correct form to describe the wan interfaces.

## Current Behavior
i don´t know if i could use any name for my wan interfaces

## Specifications

  - OpenMPTCProuter version: any verion

Hi, i would like to know if i need to name my wan interfaces by wan1, wan2, wan3, or i can use any name on interfaces ex usb0, usb1 etc.

I´m asking this because i saw in some of your codes, that you are using these names (wan1, wan2, etc)
ex: https://github.com/Ysurac/openmptcprouter-feeds/commit/c4328a5bdb2a8179f589931455d13cd4a2e8466c

i don´t know if i put any name, maybe i can mess with sqm configs etc.

Thanks a lot.

**Comment by Ysurac** [comment]
The code is for first boot initial configuration. Interfaces can have any name.

**Comment by psfabio** [comment]
thanks.
