### ISSUE TITLE
glorytun can't work for srt(UDP) at The lastest version with kernel 6.1

### ISSUE THREAD

**Issue by fareign** [Ysurac/openmptcprouter#2928]
after push SRT flow a few seconds. VPN adn VPS,broken down.

**Comment by Ysurac** [comment]
Please use the template when you open an issue.
Do you have SQM enabled with download and upload speed set ?

**Comment by Ysurac** [comment]
Do you mean Glorytun TCP or Glorytun UDP ? If glorytun TCP did you update VPS ?

**Comment by fareign** [comment]
is glorytun tcp.  I give up glorytun UDP, because it use more traffic than other VPN.
I find another thing.  glorytun tcp, openvpn tcp which need mptcp ,can not work on multipath,only one interface.
and glorytun udp,mlvpn.v2ray can work on multipath.
so there is something with mptcp?

**Comment by fareign** [comment]
<img width="1011" alt="09" src="https://github.com/Ysurac/openmptcprouter/assets/15459/2e4bc69c-3038-43e6-a3bc-cf77897382af">

**Comment by Ysurac** [comment]
Glorytun TCP is for now really slow and aggregate only sometimes. I need to find why...
For OpenVPN TCP, I didn't patch OpenVPN yet to add MPTCP support.

**Comment by fareign** [comment]
so now ss+mlvpn ,v2ray+mlvpn or openvpn. is the better choice.

**Comment by psfabio** [comment]
SRT works on UDP, you can try to use v2ray as proxy without any vpn.

**Comment by fareign** [comment]
> SRT works on UDP, you can try to use v2ray as proxy without any vpn.

thanks,V2ray now work well,but cant without VPN.must select one ,even if vpn not work.
I have to compare ss+vpn and V2ray.which is more satble.

**Comment by fareign** [comment]
mlvpn buffer size is an important setting ,if set 0, it may use more tracffic . set too high(8000) may cant work.
I test ,if buffer size is full. it may use more traffic.so it only use for small stream <3mb.
