### ISSUE TITLE
openVPN work very well now ,but sometimes it can't work after reboot.

### ISSUE THREAD

**Issue by fareign** [Ysurac/openmptcprouter#2930]
## Expected Behavior
after reboot,most time it can't work. must save and aply wizard .
I'm not sure there some reason a bout my interface boot later than mptcp.
this is the LOG. 

## Current Behavior
Aug 18 07:51:59 OpenMPTCProuter daemon.notice ttyd[17564]: [2023/08/18 07:51:59:2602] N:  Listening on port: 7681
Aug 18 07:51:59 OpenMPTCProuter daemon.notice procd: /etc/rc.d/S99v2ray: Flush terminated
Aug 18 07:51:59 OpenMPTCProuter daemon.info procd: - init complete -
Aug 18 07:52:00 OpenMPTCProuter daemon.notice netifd: Network device 'usb3' link is up
Aug 18 07:52:00 OpenMPTCProuter daemon.notice netifd: Interface 'wan2' has link connectivity 
Aug 18 07:52:00 OpenMPTCProuter daemon.notice netifd: Interface 'wan2' is setting up now
Aug 18 07:52:00 OpenMPTCProuter daemon.notice netifd: wan2 (17827): udhcpc: started, v1.36.1
Aug 18 07:52:00 OpenMPTCProuter daemon.err /usr/bin/ss-redir[11866]: fast_open_connect: Network unreachable
Aug 18 07:52:00 OpenMPTCProuter daemon.notice netifd: wan2 (17827): udhcpc: broadcasting discover
Aug 18 07:52:00 OpenMPTCProuter daemon.notice netifd: wan1 (13652): udhcpc: broadcasting discover
Aug 18 07:52:00 OpenMPTCProuter daemon.notice netifd: wan1 (13652): udhcpc: broadcasting select for 192.168.220.39, server 192.168.220.1
Aug 18 07:52:00 OpenMPTCProuter daemon.notice netifd: wan1 (13652): udhcpc: lease of 192.168.220.39 obtained from 192.168.220.1, lease time 43200
Aug 18 07:52:00 OpenMPTCProuter daemon.notice netifd: Interface 'wan1' is now up
Aug 18 07:52:01 OpenMPTCProuter daemon.err /usr/bin/ss-redir[11866]: fast_open_connect: Network unreachable
Aug 18 07:52:01 OpenMPTCProuter daemon.err /usr/bin/ss-redir[11866]: fast_open_connect: Network unreachable
Aug 18 07:52:01 OpenMPTCProuter daemon.info [6034]: <info>  [device /sys/devices/pci0000:00/0000:00:15.0/usb1/1-1/1-1.3] creating modem with plugin 'quectel' and '5' ports
Aug 18 07:52:01 OpenMPTCProuter daemon.info [6034]: <info>  [base-manager] modem for device '/sys/devices/pci0000:00/0000:00:15.0/usb1/1-1/1-1.3' successfully created
Aug 18 07:52:01 OpenMPTCProuter daemon.err /usr/bin/ss-redir[11866]: fast_open_connect: Network unreachable
Aug 18 07:52:01 OpenMPTCProuter daemon.err /usr/bin/ss-redir[11866]: fast_open_connect: Network unreachable
Aug 18 07:52:02 OpenMPTCProuter daemon.err /usr/bin/ss-local[11864]: fast_open_connect: Network unreachable
Aug 18 07:52:02 OpenMPTCProuter daemon.err [6034]: <error> gsm_def_char_to_utf8: assertion 'gsm < GSM_DEF_ALPHABET_SIZE' failed
Aug 18 07:52:02 OpenMPTCProuter daemon.warn [6034]: <warn>  [modem3/sim1] couldn't load operator name: Invalid conversion from GSM to UTF-8: Invalid conversion from GSM7
Aug 18 07:52:02 OpenMPTCProuter daemon.warn [6034]: <warn>  [modem3/sim1] couldn't load list of emergency numbers: uninitialized emergency numbers list
Aug 18 07:52:02 OpenMPTCProuter daemon.warn [6034]: <warn>  [modem3/sim1] couldn't load GID1: Unknown error
Aug 18 07:52:02 OpenMPTCProuter daemon.warn [6034]: <warn>  [modem3/sim1] couldn't load GID2: Unknown error
Aug 18 07:52:02 OpenMPTCProuter daemon.err /usr/bin/ss-redir[11865]: fast_open_connect: Network unreachable
Aug 18 07:52:02 OpenMPTCProuter daemon.info [6034]: <info>  [modem3] state changed (unknown -> disabled)
Aug 18 07:52:02 OpenMPTCProuter daemon.err /usr/bin/ss-redir[11865]: fast_open_connect: Network unreachable
Aug 18 07:52:02 OpenMPTCProuter daemon.err /usr/bin/ss-redir[11866]: fast_open_connect: Network unreachable
Aug 18 07:52:03 OpenMPTCProuter daemon.notice netifd: wan2 (17827): udhcpc: broadcasting discover
Aug 18 07:52:03 OpenMPTCProuter daemon.err /usr/bin/ss-redir[11865]: fast_open_connect: Network unreachable
Aug 18 07:52:03 OpenMPTCProuter daemon.err /usr/bin/ss-redir[11865]: fast_open_connect: Network unreachable
Aug 18 07:52:03 OpenMPTCProuter daemon.warn openvpn(omr)[11332]: WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
Aug 18 07:52:03 OpenMPTCProuter daemon.warn openvpn(omr)[11332]: NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Aug 18 07:52:03 OpenMPTCProuter daemon.notice openvpn(omr)[11332]: TCP/UDP: Preserving recently used remote address: [AF_INET]120.24.69.251:65301
Aug 18 07:52:03 OpenMPTCProuter daemon.notice openvpn(omr)[11332]: Attempting to establish TCP connection with [AF_INET]120.24.69.251:65301 [nonblock]
Aug 18 07:52:03 OpenMPTCProuter daemon.err openvpn(omr)[11332]: TCP: connect to [AF_INET]120.24.69.251:65301 failed: Network unreachable
Aug 18 07:52:03 OpenMPTCProuter daemon.notice openvpn(omr)[11332]: SIGUSR1[connection failed(soft),init_instance] received, process restarting
Aug 18 07:52:04 OpenMPTCProuter daemon.err /usr/bin/ss-redir[11865]: fast_open_connect: Network unreachable
Aug 18 07:52:04 OpenMPTCProuter daemon.err /usr/bin/ss-redir[11866]: fast_open_connect: Network unreachable
Aug 18 07:52:04 OpenMPTCProuter user.notice post-tracking-post-tracking: wan1 (usb1) switched up
Aug 18 07:52:04 OpenMPTCProuter daemon.err /usr/bin/ss-redir[11865]: fast_open_connect: Network unreachable
Aug 18 07:52:04 OpenMPTCProuter daemon.err /usr/bin/ss-redir[11866]: fast_open_connect: Network unreachable
Aug 18 07:52:04 OpenMPTCProuter daemon.info [6034]: <info>  [device /sys/devices/pci0000:00/0000:00:15.0/usb1/1-1/1-1.4] creating modem with plugin 'quectel' and '5' ports
Aug 18 07:52:04 OpenMPTCProuter daemon.info [6034]: <info>  [base-manager] modem for device '/sys/devices/pci0000:00/0000:00:15.0/usb1/1-1/1-1.4' successfully created
Aug 18 07:52:04 OpenMPTCProuter daemon.warn [6034]: <warn>  [modem4] Failed to find usable modem character set, let it to UNKNOWN
Aug 18 07:52:04 OpenMPTCProuter daemon.info [6034]: <info>  [modem4] state changed (unknown -> locked)
Aug 18 07:52:04 OpenMPTCProuter daemon.warn [6034]: <warn>  [modem4] modem couldn't be initialized: Couldn't check unlock status: SIM not inserted
Aug 18 07:52:04 OpenMPTCProuter daemon.info [6034]: <info>  [modem4] state changed (locked -> failed)
Aug 18 07:52:04 OpenMPTCProuter daemon.warn [6034]: <warn>  [modem4] error initializing: Modem in failed state: sim-missing
Aug 18 07:52:06 OpenMPTCProuter daemon.err /usr/bin/ss-redir[11865]: fast_open_connect: Network unreachable
Aug 18 07:52:06 OpenMPTCProuter daemon.notice netifd: wan2 (17827): udhcpc: broadcasting select for 192.168.223.37, server 192.168.223.1
Aug 18 07:52:06 OpenMPTCProuter daemon.notice netifd: wan2 (17827): udhcpc: lease of 192.168.223.37 obtained from 192.168.223.1, lease time 43200
Aug 18 07:52:06 OpenMPTCProuter daemon.notice netifd: Interface 'wan2' is now up
Aug 18 07:52:06 OpenMPTCProuter daemon.err /usr/bin/ss-redir[11866]: fast_open_connect: Network unreachable
Aug 18 07:52:06 OpenMPTCProuter daemon.err /usr/bin/ss-redir[11866]: fast_open_connect: Network unreachable
Aug 18 07:52:07 OpenMPTCProuter daemon.err /usr/bin/ss-local[11864]: fast_open_connect: Network unreachable
Aug 18 07:52:07 OpenMPTCProuter daemon.info omr-tracker-ss: Shadowsocks sss0 is down (can't contact via http 1.0.0.1, 212.27.48.10, 198.27.92.1)
Aug 18 07:52:07 OpenMPTCProuter user.notice Shadowsocks: Rules DOWN
Aug 18 07:52:08 OpenMPTCProuter daemon.warn openvpn(omr)[11332]: WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
Aug 18 07:52:08 OpenMPTCProuter daemon.warn openvpn(omr)[11332]: NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Aug 18 07:52:09 OpenMPTCProuter daemon.notice openvpn(omr)[11332]: TCP/UDP: Preserving recently used remote address: [AF_INET]120.24.69.251:65301
Aug 18 07:52:09 OpenMPTCProuter daemon.notice openvpn(omr)[11332]: Attempting to establish TCP connection with [AF_INET]120.24.69.251:65301 [nonblock]
Aug 18 07:52:09 OpenMPTCProuter daemon.err openvpn(omr)[11332]: TCP: connect to [AF_INET]120.24.69.251:65301 failed: Network unreachable
Aug 18 07:52:09 OpenMPTCProuter daemon.notice openvpn(omr)[11332]: SIGUSR1[connection failed(soft),init_instance] received, process restarting
Aug 18 07:52:10 OpenMPTCProuter user.notice post-tracking-post-tracking: wan2 (usb3) switched up
Aug 18 07:52:11 OpenMPTCProuter user.notice omr-bypass: Starting OMR-ByPass...
Aug 18 07:52:12 OpenMPTCProuter user.notice firewall: Reloading firewall due to ifup of wan1 (usb1)
Aug 18 07:52:12 OpenMPTCProuter user.notice post-tracking-post-tracking: Change in routes, set ip route replace default scope global  nexthop via 192.168.220.1 dev usb1 weight 100 nexthop via 192.168.223.1 dev usb3 weight 1 (omrvpn_intf: tun0)
Aug 18 07:52:12 OpenMPTCProuter user.notice post-tracking-post-tracking: Reload MPTCP config for usb1
Aug 18 07:52:12 OpenMPTCProuter user.notice firewall.omr-server: Firewall reload, set server part firewall reloading
Aug 18 07:52:12 OpenMPTCProuter user.notice post-tracking-post-tracking: Reload MPTCP config for usb3
Aug 18 07:52:12 OpenMPTCProuter user.notice omr-bypass: OMR-ByPass is running
Aug 18 07:52:13 OpenMPTCProuter user.notice Shadowsocks: Rules UP
Aug 18 07:52:13 OpenMPTCProuter user.notice post-tracking-post-tracking: Multipath usb1 switched to on (from off)
Aug 18 07:52:13 OpenMPTCProuter user.notice Shadowsocks: Reload omr-bypass rules
Aug 18 07:52:13 OpenMPTCProuter user.notice omr-bypass: Starting OMR-ByPass...
Aug 18 07:52:13 OpenMPTCProuter user.notice post-tracking-post-tracking: Multipath usb3 switched to on (from off)
Aug 18 07:52:14 OpenMPTCProuter user.notice omr-bypass: OMR-ByPass is running
Aug 18 07:52:14 OpenMPTCProuter user.notice mptcp: Reloading mptcp config due to ifup of wan1 (usb1)
Aug 18 07:52:15 OpenMPTCProuter user.notice firewall.omr-server: Firewall reload, set server part firewall reloading
Aug 18 07:52:15 OpenMPTCProuter user.notice firewall: Reloading firewall due to ifup of wan2 (usb3)
Aug 18 07:52:15 OpenMPTCProuter daemon.info unbound: [11111:0] info: generate keytag query _ta-4f66. NULL IN
Aug 18 07:52:15 OpenMPTCProuter user.notice post-tracking-post-tracking: New public ip detected for wan1 (usb1): 223.147.11.26
Aug 18 07:52:15 OpenMPTCProuter user.notice post-tracking-post-tracking: Reload MPTCP for usb1
Aug 18 07:52:15 OpenMPTCProuter user.notice firewall.omr-server: Firewall reload, set server part firewall reloading
Aug 18 07:52:15 OpenMPTCProuter user.notice post-tracking-post-tracking: New public ip detected for wan2 (usb3): 223.153.68.241
Aug 18 07:52:16 OpenMPTCProuter user.notice post-tracking-post-tracking: Reload MPTCP for usb3
Aug 18 07:52:16 OpenMPTCProuter user.notice mptcp: Reloading mptcp config due to ifup of wan2 (usb3)
Aug 18 07:52:19 OpenMPTCProuter daemon.warn openvpn(omr)[11332]: WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
Aug 18 07:52:19 OpenMPTCProuter daemon.warn openvpn(omr)[11332]: NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Aug 18 07:52:19 OpenMPTCProuter daemon.notice openvpn(omr)[11332]: TCP/UDP: Preserving recently used remote address: [AF_INET]120.24.69.251:65301
Aug 18 07:52:19 OpenMPTCProuter daemon.notice openvpn(omr)[11332]: Attempting to establish TCP connection with [AF_INET]120.24.69.251:65301 [nonblock]
Aug 18 07:52:19 OpenMPTCProuter daemon.notice openvpn(omr)[11332]: TCP connection established with [AF_INET]120.24.69.251:65301
Aug 18 07:52:19 OpenMPTCProuter daemon.warn openvpn(omr)[11332]: Note: enable extended error passing on TCP/UDP socket failed (IP_RECVERR): Not supported (errno=95)
Aug 18 07:52:19 OpenMPTCProuter daemon.notice openvpn(omr)[11332]: TCP_CLIENT link local: (not bound)
Aug 18 07:52:19 OpenMPTCProuter daemon.notice openvpn(omr)[11332]: TCP_CLIENT link remote: [AF_INET]120.24.69.251:65301
Aug 18 07:52:19 OpenMPTCProuter daemon.warn openvpn(omr)[11332]: WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1551', remote='link-mtu 1559'
Aug 18 07:52:19 OpenMPTCProuter daemon.warn openvpn(omr)[11332]: WARNING: 'auth' is used inconsistently, local='auth [null-digest]', remote='auth SHA1'
Aug 18 07:52:19 OpenMPTCProuter daemon.notice openvpn(omr)[11332]: [server] Peer Connection Initiated with [AF_INET]120.24.69.251:65301
Aug 18 07:52:19 OpenMPTCProuter daemon.warn openvpn(omr)[11332]: sitnl_route_save: rtnl: can't get ifname for index 0: No such device or address (errno=6)
Aug 18 07:52:19 OpenMPTCProuter daemon.notice openvpn(omr)[11332]: TUN/TAP device tun0 opened
Aug 18 07:52:19 OpenMPTCProuter daemon.notice openvpn(omr)[11332]: net_iface_mtu_set: mtu 1500 for tun0
Aug 18 07:52:19 OpenMPTCProuter daemon.notice openvpn(omr)[11332]: net_iface_up: set tun0 up
Aug 18 07:52:19 OpenMPTCProuter daemon.notice openvpn(omr)[11332]: net_addr_ptp_v4_add: 10.255.252.6 peer 10.255.252.5 dev tun0
Aug 18 07:52:19 OpenMPTCProuter daemon.notice netifd: Interface 'omrvpn' is enabled
Aug 18 07:52:19 OpenMPTCProuter daemon.notice netifd: Network device 'tun0' link is up
Aug 18 07:52:19 OpenMPTCProuter daemon.notice netifd: Interface 'omrvpn' has link connectivity 
Aug 18 07:52:19 OpenMPTCProuter daemon.notice netifd: Interface 'omrvpn' is setting up now
Aug 18 07:52:19 OpenMPTCProuter daemon.notice openvpn(omr)[11332]: /usr/libexec/openvpn-hotplug up omr tun0 1500 1626 10.255.252.6 10.255.252.5 init
Aug 18 07:52:19 OpenMPTCProuter daemon.notice netifd: Interface 'omrvpn' is now up
Aug 18 07:52:19 OpenMPTCProuter user.notice firewall: Reloading firewall due to ifup of omrvpn (tun0)
Aug 18 07:52:20 OpenMPTCProuter user.notice firewall.omr-server: Firewall reload, set server part firewall reloading
Aug 18 07:52:20 OpenMPTCProuter user.notice mptcp: Reloading mptcp config due to ifup of omrvpn (tun0)
Aug 18 07:52:20 OpenMPTCProuter daemon.info unbound: [11111:0] info: service stopped (unbound 1.17.1).
Aug 18 07:52:20 OpenMPTCProuter daemon.info unbound: [11111:0] info: server stats for thread 0: 184 queries, 0 answers from cache, 184 recursions, 0 prefetch, 0 rejected by ip ratelimiting
Aug 18 07:52:20 OpenMPTCProuter daemon.info unbound: [11111:0] info: server stats for thread 0: requestlist max 11 avg 0.929348 exceeded 0 jostled 0
Aug 18 07:52:20 OpenMPTCProuter daemon.info unbound: [11111:0] info: average recursion processing time 0.170920 sec
Aug 18 07:52:20 OpenMPTCProuter daemon.info unbound: [11111:0] info: histogram of recursion processing times
Aug 18 07:52:20 OpenMPTCProuter daemon.info unbound: [11111:0] info: [25%]=0.00131021 median[50%]=0.00160278 [75%]=0.00189535
Aug 18 07:52:20 OpenMPTCProuter daemon.info unbound: [11111:0] info: lower(secs) upper(secs) recursions
Aug 18 07:52:20 OpenMPTCProuter daemon.info unbound: [11111:0] info:    0.000512    0.001024 1
Aug 18 07:52:20 OpenMPTCProuter daemon.info unbound: [11111:0] info:    0.001024    0.002048 161
Aug 18 07:52:20 OpenMPTCProuter daemon.info unbound: [11111:0] info:    0.065536    0.131072 1
Aug 18 07:52:20 OpenMPTCProuter daemon.info unbound: [11111:0] info:    0.131072    0.262144 4
Aug 18 07:52:20 OpenMPTCProuter daemon.info unbound: [11111:0] info:    0.262144    0.524288 2
Aug 18 07:52:20 OpenMPTCProuter daemon.info unbound: [11111:0] info:    0.524288    1.000000 3
Aug 18 07:52:20 OpenMPTCProuter daemon.info unbound: [11111:0] info:    1.000000    2.000000 5
Aug 18 07:52:20 OpenMPTCProuter daemon.info unbound: [11111:0] info:    2.000000    4.000000 7
Aug 18 07:52:21 OpenMPTCProuter daemon.notice unbound: [32418:0] notice: init module 0: validator
Aug 18 07:52:21 OpenMPTCProuter daemon.notice unbound: [32418:0] notice: init module 1: iterator
Aug 18 07:52:21 OpenMPTCProuter daemon.info unbound: [32418:0] info: start of service (unbound 1.17.1).
Aug 18 07:52:22 OpenMPTCProuter daemon.info unbound: [32418:0] info: generate keytag query _ta-4f66. NULL IN
Aug 18 07:52:24 OpenMPTCProuter daemon.notice openvpn(omr)[11332]: Initialization Sequence Completed
Aug 18 07:52:30 OpenMPTCProuter daemon.info omr-tracker-ss: Shadowsocks sss0 is down (can't contact via http 1.0.0.1, 212.27.48.10, 198.27.92.1, 151.101.129.164)
Aug 18 07:52:30 OpenMPTCProuter user.notice Shadowsocks: Rules DOWN
Aug 18 07:52:36 OpenMPTCProuter daemon.err uhttpd[5799]: [info] luci: accepted login on /admin/status/logs for root from 192.168.100.137
Aug 18 07:52:40 OpenMPTCProuter daemon.info omr-tracker-ss: Shadowsocks sss0 is up (can contact via http 77.88.55.77)
Aug 18 07:52:40 OpenMPTCProuter daemon.info omr-tracker-ss: Reload Shadowsocks rules
Aug 18 07:52:40 OpenMPTCProuter user.notice Shadowsocks: Rules UP
Aug 18 07:52:40 OpenMPTCProuter user.notice Shadowsocks: Reload omr-bypass rules
Aug 18 07:52:40 OpenMPTCProuter user.notice omr-bypass: Starting OMR-ByPass...
Aug 18 07:52:41 OpenMPTCProuter user.notice omr-bypass: OMR-ByPass is running

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - OpenMPTCProuter version: 0.59.2alpha 6.1kernel 2003-8-17
  - OpenMPTCProuter VPS version: 0.1029test
  - OpenMPTCProuter VPS provider:aliyun
  - OpenMPTCProuter platform:  x86_64
  - Country: cn

**Comment by fareign** [comment]
I roll back MPTCP 50 to 90.it may ok now.

**Comment by Ysurac** [comment]
Should be better now: OpenVPN was started before MPTCP was enabled, now I enable MPTCP via sysctl and this should fix this problem (and maybe some others problems).

**Comment by fareign** [comment]
@Ysurac this problem also exist
