### ISSUE TITLE
Can't forward ports

### ISSUE THREAD

**Issue by DarthVaderFR** [Ysurac/openmptcprouter#2937]
## Expected Behavior
Hello, again, (and sorry if my english is not perfect, i'm French)

I'm trying to forward some ports to my NAS, and i tried to follow different steps of your tutorials, in different ways, i'm not managing to forward them.

First i tried to directly redirect them from the port forwardings straight from the VPS to the device : NOK
Then i tried to use the SNAT on the same ports : NOK
I decided to restart the router, and it crashed completely.
I reinstalled and reconfigured everything from scratch because i didn't save anything
I retried the same thing : NOK
I tried the ports from the VPS to the router ip : NOK
Then i recreated the SNAT with th router ip : NOK

I tried to check the conf fil on the VPS you mentionned in the tutorial : /etc/shorewall/rules
Rules are not written.
I tried to switch all ports to the router : nothing happened neither
I rechecked that file, and the lines mentionned all the ports below 65000 redirected to the router still are in comments mode.

I have the feeling that the file can't be written, but no error on the router interface when i save and apply the configuration

## Current Behavior

I can't reach the web interface of my NAS, and my different web services on it are down.

## Specifications

  - OpenMPTCProuter version: 0.59.1-5.4.r0
  - OpenMPTCProuter VPS version: Debian 11 / server 0.1028 5.4.207-mtcp
  - OpenMPTCProuter VPS provider: Firstheberg
  - OpenMPTCProuter platform: RPI4B

**Comment by Ysurac** [comment]
All is screen in status page without errors ?
What is the result of ```uci show firewall``` from the router via SSH ?

**Comment by DarthVaderFR** [comment]
Hello and thanks for your help.

Here is the result of the command :

oot@OpenMPTCProuter:~# uci show firewall
firewall.@defaults[0]=defaults
firewall.@defaults[0].syn_flood='1'
firewall.@defaults[0].forward='REJECT'
firewall.@defaults[0].input='REJECT'
firewall.@defaults[0].output='REJECT'
firewall.zone_lan=zone
firewall.zone_lan.name='lan'
firewall.zone_lan.input='ACCEPT'
firewall.zone_lan.output='ACCEPT'
firewall.zone_lan.forward='ACCEPT'
firewall.zone_lan.mtu_fix='1'
firewall.zone_lan.auto_helper='1'
firewall.zone_lan.network='lan'
firewall.zone_wan=zone
firewall.zone_wan.name='wan'
firewall.zone_wan.input='REJECT'
firewall.zone_wan.output='ACCEPT'
firewall.zone_wan.forward='REJECT'
firewall.zone_wan.masq='1'
firewall.zone_wan.mtu_fix='1'
firewall.zone_wan.auto_helper='1'
firewall.zone_wan.network='wan1' 'iPhoneAlexandre'
firewall.@forwarding[0]=forwarding
firewall.@forwarding[0].src='lan'
firewall.@forwarding[0].dest='wan'
firewall.@rule[0]=rule
firewall.@rule[0].name='Allow-DHCP-Renew'
firewall.@rule[0].src='wan'
firewall.@rule[0].proto='udp'
firewall.@rule[0].dest_port='68'
firewall.@rule[0].target='ACCEPT'
firewall.@rule[0].family='ipv4'
firewall.@rule[1]=rule
firewall.@rule[1].name='Allow-Ping'
firewall.@rule[1].src='wan'
firewall.@rule[1].proto='icmp'
firewall.@rule[1].icmp_type='echo-request'
firewall.@rule[1].family='ipv4'
firewall.@rule[1].target='ACCEPT'
firewall.@rule[2]=rule
firewall.@rule[2].name='Allow-IGMP'
firewall.@rule[2].src='wan'
firewall.@rule[2].proto='igmp'
firewall.@rule[2].family='ipv4'
firewall.@rule[2].target='ACCEPT'
firewall.@rule[3]=rule
firewall.@rule[3].name='Allow-DHCPv6'
firewall.@rule[3].src='wan'
firewall.@rule[3].proto='udp'
firewall.@rule[3].dest_port='546'
firewall.@rule[3].family='ipv6'
firewall.@rule[3].target='ACCEPT'
firewall.@rule[4]=rule
firewall.@rule[4].name='Allow-MLD'
firewall.@rule[4].src='wan'
firewall.@rule[4].proto='icmp'
firewall.@rule[4].src_ip='fe80::/10'
firewall.@rule[4].icmp_type='130/0' '131/0' '132/0' '143/0'
firewall.@rule[4].family='ipv6'
firewall.@rule[4].target='ACCEPT'
firewall.@rule[5]=rule
firewall.@rule[5].name='Allow-ICMPv6-Forward'
firewall.@rule[5].src='wan'
firewall.@rule[5].dest='*'
firewall.@rule[5].proto='icmp'
firewall.@rule[5].icmp_type='echo-request' 'echo-reply' 'destination-unreachable' 'packet-too-big' 'time-exceeded' 'bad-header' 'unknown-header-type'
firewall.@rule[5].limit='1000/sec'
firewall.@rule[5].family='ipv6'
firewall.@rule[5].target='ACCEPT'
firewall.@rule[6]=rule
firewall.@rule[6].name='Allow-IPSec-ESP'
firewall.@rule[6].src='wan'
firewall.@rule[6].dest='lan'
firewall.@rule[6].proto='esp'
firewall.@rule[6].target='ACCEPT'
firewall.@rule[7]=rule
firewall.@rule[7].name='Allow-ISAKMP'
firewall.@rule[7].src='wan'
firewall.@rule[7].dest='lan'
firewall.@rule[7].dest_port='500'
firewall.@rule[7].proto='udp'
firewall.@rule[7].target='ACCEPT'
firewall.@rule[8]=rule
firewall.@rule[8].name='Support-UDP-Traceroute'
firewall.@rule[8].src='wan'
firewall.@rule[8].dest_port='33434:33689'
firewall.@rule[8].proto='udp'
firewall.@rule[8].family='ipv4'
firewall.@rule[8].target='REJECT'
firewall.@rule[8].enabled='false'
firewall.@include[0]=include
firewall.@include[0].path='/etc/firewall.user'
firewall.@include[0].reload='1'
firewall.@rule[9]=rule
firewall.@rule[9].enabled='1'
firewall.@rule[9].target='ACCEPT'
firewall.@rule[9].name='Allow-All-LAN-to-VPN'
firewall.@rule[9].dest='vpn'
firewall.@rule[9].src='lan'
firewall.@rule[9].proto='all'
firewall.zone_vpn=zone
firewall.zone_vpn.name='vpn'
firewall.zone_vpn.masq='1'
firewall.zone_vpn.input='REJECT'
firewall.zone_vpn.forward='ACCEPT'
firewall.zone_vpn.output='ACCEPT'
firewall.zone_vpn.mtu_fix='1'
firewall.zone_vpn.auto_helper='1'
firewall.zone_vpn.network='omrvpn' 'omr6in4'
firewall.@rule[10]=rule
firewall.@rule[10].enabled='1'
firewall.@rule[10].target='ACCEPT'
firewall.@rule[10].name='Allow-All-Ping'
firewall.@rule[10].proto='icmp'
firewall.@rule[10].dest='*'
firewall.@rule[10].src='*'
firewall.@rule[10].icmp_type='echo-request'
firewall.@rule[10].limit='1000/sec'
firewall.@rule[11]=rule
firewall.@rule[11].enabled='1'
firewall.@rule[11].target='ACCEPT'
firewall.@rule[11].name='Allow-VPN-ICMP'
firewall.@rule[11].proto='icmp'
firewall.@rule[11].src='vpn'
firewall.@rule[12]=rule
firewall.@rule[12].enabled='1'
firewall.@rule[12].target='ACCEPT'
firewall.@rule[12].name='Allow-Lan-to-Wan'
firewall.@rule[12].dest='wan'
firewall.@rule[12].src='lan'
firewall.@rule[12].proto='all'
firewall.@rule[13]=rule
firewall.@rule[13].enabled='1'
firewall.@rule[13].target='ACCEPT'
firewall.@rule[13].name='ICMPv6-Lan-to-OMR'
firewall.@rule[13].src='lan'
firewall.@rule[13].family='ipv6'
firewall.@rule[13].proto='icmp'
firewall.@rule[13].limit='1000/sec'
firewall.@rule[13].icmp_type='echo-reply destination-unreachable echo-request router-advertisement router-solicitation time-exceeded'
firewall.omr_server=include
firewall.omr_server.path='/etc/firewall.omr-server'
firewall.omr_server.reload='1'
firewall.gre_tunnel=include
firewall.gre_tunnel.path='/etc/firewall.gre-tunnel'
firewall.gre_tunnel.reload='0'
firewall.ttl=include
firewall.ttl.path='/etc/firewall.ttl'
firewall.ttl.reload='1'
firewall.fwlantovpn=forwarding
firewall.fwlantovpn.src='lan'
firewall.fwlantovpn.dest='vpn'
firewall.blockquicproxy=rule
firewall.blockquicproxy.name='Block QUIC Proxy'
firewall.blockquicproxy.proto='udp'
firewall.blockquicproxy.dest_port='443'
firewall.blockquicproxy.target='DROP'
firewall.blockquicproxy.src='lan'
firewall.blockquicall=rule
firewall.blockquicall.name='Block QUIC All'
firewall.blockquicall.proto='udp'
firewall.blockquicall.src='*'
firewall.blockquicall.dest='*'
firewall.blockquicall.dest_port='443'
firewall.blockquicall.target='DROP'
firewall.allowicmpipv6=rule
firewall.allowicmpipv6.proto='icmp'
firewall.allowicmpipv6.target='ACCEPT'
firewall.allowicmpipv6.src='wan'
firewall.allowicmpipv6.name='Allow IPv6 ICMP'
firewall.allowicmpipv6.family='ipv6'
firewall.allowicmpipv6.limit='1000/sec'
firewall.allowicmpipv6.icmp_type='neighbour-advertisement neighbour-solicitation router-advertisement router-solicitation'
firewall.allowdhcpv6546=rule
firewall.allowdhcpv6546.target='ACCEPT'
firewall.allowdhcpv6546.src='wan'
firewall.allowdhcpv6546.proto='udp'
firewall.allowdhcpv6546.dest_port='547'
firewall.allowdhcpv6546.name='Allow DHCPv6 (546-to-547)'
firewall.allowdhcpv6546.family='ipv6'
firewall.allowdhcpv6546.src_port='546'
firewall.allowdhcpv6547=rule
firewall.allowdhcpv6547.target='ACCEPT'
firewall.allowdhcpv6547.src='wan'
firewall.allowdhcpv6547.proto='udp'
firewall.allowdhcpv6547.dest_port='546'
firewall.allowdhcpv6547.name='Allow DHCPv6 (547-to-546)'
firewall.allowdhcpv6547.family='ipv6'
firewall.allowdhcpv6547.src_port='547'
firewall.v2ray=include
firewall.v2ray.path='/etc/firewall.v2ray-rules'
firewall.v2ray.reload='0'
firewall.omr_bypass=include
firewall.omr_bypass.path='/etc/firewall.omr-bypass'
firewall.omr_bypass.reload='0'
firewall.miniupnpd=include
firewall.miniupnpd.type='script'
firewall.miniupnpd.path='/usr/share/miniupnpd/firewall.include'
firewall.miniupnpd.family='any'
firewall.miniupnpd.reload='1'
firewall.ss_rules=include
firewall.ss_rules.path='/etc/firewall.ss-rules'
firewall.ss_rules.reload='1'
firewall.@redirect[0]=redirect
firewall.@redirect[0].target='DNAT'
firewall.@redirect[0].name='NAS'
firewall.@redirect[0].src_dport='1980'
firewall.@redirect[0].dest='lan'
firewall.@redirect[0].dest_port='5001'
firewall.@redirect[0].src='vpn'
firewall.@redirect[0].dest_ip='192.168.100.1'
firewall.@redirect[1]=redirect
firewall.@redirect[1].target='DNAT'
firewall.@redirect[1].src='vpn'
firewall.@redirect[1].src_dport='1950'
firewall.@redirect[1].dest='lan'
firewall.@redirect[1].dest_port='5000'
firewall.@redirect[1].dest_ip='192.168.100.1'
firewall.@redirect[2]=redirect
firewall.@redirect[2].target='DNAT'
firewall.@redirect[2].name='rustdesk'
firewall.@redirect[2].src='vpn'
firewall.@redirect[2].src_dport='21116'
firewall.@redirect[2].dest='lan'
firewall.@redirect[2].dest_port='21116'
firewall.@redirect[2].dest_ip='192.168.100.1'
firewall.@redirect[3]=redirect
firewall.@redirect[3].target='DNAT'
firewall.@redirect[3].name='rustdesk'
firewall.@redirect[3].proto='tcp'
firewall.@redirect[3].src_dport='21119'
firewall.@redirect[3].dest='lan'
firewall.@redirect[3].dest_port='21119'
firewall.@redirect[3].src='vpn'
firewall.@redirect[3].dest_ip='192.168.100.1'
firewall.@redirect[4]=redirect
firewall.@redirect[4].target='DNAT'
firewall.@redirect[4].name='rustdesk'
firewall.@redirect[4].proto='tcp'
firewall.@redirect[4].src_dport='21118'
firewall.@redirect[4].dest_port='21118'
firewall.@redirect[4].src='vpn'
firewall.@redirect[4].dest='lan'
firewall.@redirect[4].dest_ip='192.168.100.1'
firewall.@redirect[5]=redirect
firewall.@redirect[5].target='DNAT'
firewall.@redirect[5].name='rustdesk'
firewall.@redirect[5].proto='tcp'
firewall.@redirect[5].src='vpn'
firewall.@redirect[5].src_dport='21117'
firewall.@redirect[5].dest='lan'
firewall.@redirect[5].dest_port='21117'
firewall.@redirect[5].dest_ip='192.168.100.1'
firewall.@redirect[6]=redirect
firewall.@redirect[6].target='DNAT'
firewall.@redirect[6].name='rustdesk'
firewall.@redirect[6].proto='tcp'
firewall.@redirect[6].src='vpn'
firewall.@redirect[6].src_dport='21115'
firewall.@redirect[6].dest='lan'
firewall.@redirect[6].dest_port='21115'
firewall.@redirect[6].dest_ip='192.168.100.1'
firewall.@redirect[7]=redirect
firewall.@redirect[7].target='DNAT'
firewall.@redirect[7].name='openvpn'
firewall.@redirect[7].proto='udp'
firewall.@redirect[7].src='vpn'
firewall.@redirect[7].src_dport='1194'
firewall.@redirect[7].dest='lan'
firewall.@redirect[7].dest_port='1194'
firewall.@redirect[7].dest_ip='192.168.100.1'
firewall.@redirect[8]=redirect
firewall.@redirect[8].target='DNAT'
firewall.@redirect[8].name='mail'
firewall.@redirect[8].proto='tcp'
firewall.@redirect[8].src='vpn'
firewall.@redirect[8].src_dport='995'
firewall.@redirect[8].dest='lan'
firewall.@redirect[8].dest_port='995'
firewall.@redirect[8].dest_ip='192.168.100.1'
firewall.@redirect[9]=redirect
firewall.@redirect[9].target='DNAT'
firewall.@redirect[9].name='mail'
firewall.@redirect[9].proto='tcp'
firewall.@redirect[9].src='vpn'
firewall.@redirect[9].src_dport='993'
firewall.@redirect[9].dest='lan'
firewall.@redirect[9].dest_port='993'
firewall.@redirect[9].dest_ip='192.168.100.1'
firewall.@redirect[10]=redirect
firewall.@redirect[10].target='DNAT'
firewall.@redirect[10].name='mail'
firewall.@redirect[10].proto='tcp'
firewall.@redirect[10].src='vpn'
firewall.@redirect[10].src_dport='587'
firewall.@redirect[10].dest='lan'
firewall.@redirect[10].dest_port='587'
firewall.@redirect[10].dest_ip='192.168.100.1'
firewall.@redirect[11]=redirect
firewall.@redirect[11].target='DNAT'
firewall.@redirect[11].name='mail'
firewall.@redirect[11].proto='tcp'
firewall.@redirect[11].src='vpn'
firewall.@redirect[11].src_dport='465'
firewall.@redirect[11].dest='lan'
firewall.@redirect[11].dest_port='465'
firewall.@redirect[11].dest_ip='192.168.100.1'
firewall.@redirect[12]=redirect
firewall.@redirect[12].target='DNAT'
firewall.@redirect[12].name='mail'
firewall.@redirect[12].proto='tcp'
firewall.@redirect[12].src='vpn'
firewall.@redirect[12].src_dport='25'
firewall.@redirect[12].dest='lan'
firewall.@redirect[12].dest_port='25'
firewall.@redirect[12].dest_ip='192.168.100.1'
firewall.@redirect[13]=redirect
firewall.@redirect[13].target='DNAT'
firewall.@redirect[13].name='NAS'
firewall.@redirect[13].src='vpn'
firewall.@redirect[13].src_dport='32400'
firewall.@redirect[13].dest='lan'
firewall.@redirect[13].dest_port='32400'
firewall.@redirect[13].proto='tcp' 'udp'
firewall.@redirect[13].dest_ip='192.168.100.1'
firewall.@redirect[14]=redirect
firewall.@redirect[14].target='DNAT'
firewall.@redirect[14].name='NAS'
firewall.@redirect[14].src='vpn'
firewall.@redirect[14].src_dport='5353'
firewall.@redirect[14].dest='lan'
firewall.@redirect[14].dest_port='5353'
firewall.@redirect[14].proto='tcp' 'udp'
firewall.@redirect[14].dest_ip='192.168.100.1'
firewall.@redirect[15]=redirect
firewall.@redirect[15].target='DNAT'
firewall.@redirect[15].name='NAS'
firewall.@redirect[15].proto='tcp'
firewall.@redirect[15].src='vpn'
firewall.@redirect[15].src_dport='443'
firewall.@redirect[15].dest='lan'
firewall.@redirect[15].dest_port='443'
firewall.@redirect[15].dest_ip='192.168.100.1'
firewall.@redirect[16]=redirect
firewall.@redirect[16].target='DNAT'
firewall.@redirect[16].name='NAS'
firewall.@redirect[16].src='vpn'
firewall.@redirect[16].src_dport='6001-6010'
firewall.@redirect[16].dest='lan'
firewall.@redirect[16].dest_port='6001-6010'
firewall.@redirect[16].dest_ip='192.168.100.1'
firewall.@redirect[17]=redirect
firewall.@redirect[17].target='DNAT'
firewall.@redirect[17].name='NAS'
firewall.@redirect[17].proto='tcp'
firewall.@redirect[17].src='vpn'
firewall.@redirect[17].src_dport='443'
firewall.@redirect[17].dest='lan'
firewall.@redirect[17].dest_port='443'
firewall.@redirect[17].dest_ip='192.168.100.1'
firewall.@redirect[18]=redirect
firewall.@redirect[18].target='DNAT'
firewall.@redirect[18].name='NAS'
firewall.@redirect[18].proto='tcp'
firewall.@redirect[18].src='vpn'
firewall.@redirect[18].src_dport='80'
firewall.@redirect[18].dest='lan'
firewall.@redirect[18].dest_port='80'
firewall.@redirect[18].dest_ip='192.168.100.1'
firewall.@nat[0]=nat
firewall.@nat[0].name='NAS'
firewall.@nat[0].proto='tcp'
firewall.@nat[0].src='lan'
firewall.@nat[0].src_port='80'
firewall.@nat[0].dest_port='80'
firewall.@nat[0].target='SNAT'
firewall.@nat[0].snat_ip='192.168.100.1'
firewall.@nat[0].dest_ip='192.168.100.139'
firewall.@nat[1]=nat
firewall.@nat[1].name='NAS'
firewall.@nat[1].proto='tcp' 'udp'
firewall.@nat[1].src='lan'
firewall.@nat[1].src_port='1980'
firewall.@nat[1].dest_port='5001'
firewall.@nat[1].target='SNAT'
firewall.@nat[1].snat_ip='192.168.100.1'
firewall.@nat[1].dest_ip='192.168.100.139'
firewall.@nat[2]=nat
firewall.@nat[2].name='NAS'
firewall.@nat[2].proto='tcp' 'udp'
firewall.@nat[2].src='lan'
firewall.@nat[2].src_port='5001'
firewall.@nat[2].dest_port='5001'
firewall.@nat[2].target='SNAT'
firewall.@nat[2].snat_ip='192.168.100.1'
firewall.@nat[2].dest_ip='192.168.100.139'
firewall.@nat[3]=nat
firewall.@nat[3].name='NAS'
firewall.@nat[3].proto='tcp' 'udp'
firewall.@nat[3].src='lan'
firewall.@nat[3].src_port='1950'
firewall.@nat[3].dest_port='5000'
firewall.@nat[3].target='SNAT'
firewall.@nat[3].snat_ip='192.168.100.1'
firewall.@nat[3].dest_ip='192.168.100.139'
firewall.@nat[4]=nat
firewall.@nat[4].name='NAS'
firewall.@nat[4].proto='tcp' 'udp'
firewall.@nat[4].src='lan'
firewall.@nat[4].src_port='5000'
firewall.@nat[4].dest_port='5000'
firewall.@nat[4].target='SNAT'
firewall.@nat[4].snat_ip='192.168.100.1'
firewall.@nat[4].dest_ip='192.168.100.139'
firewall.@nat[5]=nat
firewall.@nat[5].name='NAS'
firewall.@nat[5].proto='tcp' 'udp'
firewall.@nat[5].src='lan'
firewall.@nat[5].src_port='32400'
firewall.@nat[5].dest_port='32400'
firewall.@nat[5].target='SNAT'
firewall.@nat[5].snat_ip='192.168.100.1'
firewall.@nat[5].dest_ip='192.168.100.139'
firewall.@nat[6]=nat
firewall.@nat[6].name='NAS'
firewall.@nat[6].proto='tcp' 'udp'
firewall.@nat[6].src='lan'
firewall.@nat[6].src_port='5353'
firewall.@nat[6].dest_port='5353'
firewall.@nat[6].target='SNAT'
firewall.@nat[6].snat_ip='192.168.100.1'
firewall.@nat[6].dest_ip='192.168.100.139'
firewall.@nat[7]=nat
firewall.@nat[7].name='NAS'
firewall.@nat[7].proto='tcp' 'udp'
firewall.@nat[7].src='lan'
firewall.@nat[7].src_port='443'
firewall.@nat[7].dest_port='443'
firewall.@nat[7].target='SNAT'
firewall.@nat[7].snat_ip='192.168.100.1'
firewall.@nat[7].dest_ip='192.168.100.139'
firewall.@nat[8]=nat
firewall.@nat[8].name='NAS'
firewall.@nat[8].proto='tcp' 'udp'
firewall.@nat[8].src='lan'
firewall.@nat[8].src_port='6001-6010'
firewall.@nat[8].dest_port='6001-6010'
firewall.@nat[8].target='SNAT'
firewall.@nat[8].snat_ip='192.168.100.1'
firewall.@nat[8].dest_ip='192.168.100.139'
root@OpenMPTCProuter:~# 

Here is the screen of the status. Seems no problem there

<img width="962" alt="image" src="https://github.com/Ysurac/openmptcprouter/assets/142060394/68903829-6985-486f-9e8e-7b6e7a6372f0">

**Comment by Ysurac** [comment]
So not any related rule in /etc/shorewall/rules ?
What do you have in /var/log/daemon.log on the VPS related to omr-admin ?
What is the result of ```/etc/init.d/openmptcprouter-vps set_firewall``` on the router, via SSH ?

**Comment by DarthVaderFR** [comment]
Hello, and thanks for helping me.

Here are the answers for the questions :

So not any related rule in /etc/shorewall/rules ?
Nop ☹

![image](https://github.com/Ysurac/openmptcprouter/assets/142060394/c7056e5d-b10d-4867-b6f9-6a307eb1ad40)


What do you have in /var/log/daemon.log on the VPS related to omr-admin ?

Start/stop service excepted i only have this : 
 
![image](https://github.com/Ysurac/openmptcprouter/assets/142060394/f2a55cc6-71ab-4835-ac86-d6953ea61258)


What is the result of /etc/init.d/openmptcprouter-vps set_firewall on the router, via SSH ?

![image](https://github.com/Ysurac/openmptcprouter/assets/142060394/4ff64e23-6fed-4280-80cc-1f7242ae7abc)
 

Thank you again

**Comment by Ysurac** [comment]
ok, the problem is on VPS side. It seems that you have a problem with ```/etc/openmptcprouter-vps-admin/omr-admin-config.json``` file. I think it's empty, can you check ?
If it's the case you will have to remove this file, run script again using "OMR_ADMIN_PASS=xxx" parameter where xxx is your current VPS key.
I will add automatic backup of this file, I think API was not able to write file to disk correctly.

**Comment by DarthVaderFR** [comment]
actually it's not empty, but is it complete ? :

<img width="628" alt="image" src="https://github.com/Ysurac/openmptcprouter/assets/142060394/84043b60-ba8d-4afb-8588-738dd43e40b0">
 (i removed what i thought sensitive)

**Comment by Ysurac** [comment]
Yes it's correct but missing vpn and proxy information.
What do you have when you run via SSH on the VPS ```systemctl restart omr-admin``` and on the router via SSH the correct command (sorry) ```/etc/init.d/openmptcprouter-vps set_vps_firewall``` ? and then check end of log on VPS using ```journalctl -u omr-admin``` ?

**Comment by DarthVaderFR** [comment]
I think that i was at the end :

<img width="1018" alt="image" src="https://github.com/Ysurac/openmptcprouter/assets/142060394/9046f0ae-664f-45ec-bf69-9b8bff91502b">

**Comment by Ysurac** [comment]
There is something strange... Can you give me the result of ```mount``` via SSH on the VPS ?

**Comment by DarthVaderFR** [comment]
here is the result :

<img width="798" alt="image" src="https://github.com/Ysurac/openmptcprouter/assets/142060394/e195e928-ddf5-45b0-87b3-260023969514">

**Comment by Ysurac** [comment]
partition "/" is read only. This explain all problems.
I've had these problems on FirstHeberg before...
You can reboot the server or maybe a ```mount -o remount,rw /``` may work.

**Comment by DarthVaderFR** [comment]
reboot has solved my problem to access to my NAS from the exterior. BIG THANK YOU AGAIN.

But, (always a but ^^) it seems that download station on my NAS, is unable to download anything via HTTP(S) any idea ? I'm guessing that it uses 80/443 forwarded but... Still not connecting. And i think that the problem maybe be the same for my rustdesk server. I can't remote access to/from the internet.

**Comment by DarthVaderFR** [comment]
Hello,

I've solved my problem, i don't know how really i've managed but one of the problem came from a third party provider who doesn't accept ip adress from VPS.

**Comment by Ysurac** [comment]
Yes, it's often the case... They use some block list that have most VPS ranges.

**Comment by DarthVaderFR** [comment]
Hello,

This is me again, stil trying to bypass that restriction, and i maybe found a way. I have a VPN plan with ExpressVPN, that allows me to get an openvpn fil to import inside of a router or linux etc... I've added to the router, i've managed to activate it, but i'm lonsing the connection. I'm trying the doc about the VPN but i don't. Could you help me with please ? What should i configure in the Services->Shadowsocks-libev->Redir rules->Destinations settings if i have anything to configure there ?

Thanks

**Comment by Ysurac** [comment]
You can also services->OMR-ByPass to exit directly via a connection based on IP/domain/ASN/...

**Comment by DarthVaderFR** [comment]
But if i do that, i'm losing the agreagation right ?

**Comment by Ysurac** [comment]
Yes.
Else you need to find a VPS that doesn't have IP blocked, not really easy...
