### ISSUE TITLE
Wireguard Client on Openmptcrouter not work

### ISSUE THREAD

**Issue by MTSmash-TMP-Networks** [Ysurac/openmptcprouter#2940]
I have the following problem. I am using OpenMPTCProuter for site-to-site networking. It works fine when I use one OpenMPTCProuter as a server and a normal OpenWRT device as a client. However, when I try to connect two OpenMPTCProuters, the client does not initiate the connection. The wg0 adapter only turns on once and then turns off again. Can someone help me?
With OpenVPN everything works normally, but it's unfortunately too slow.

**Comment by Ysurac** [comment]
Please use template when you open an issue.

wg0 interface is used internally, you should use another interface.

**Comment by MTSmhas** [comment]
Okay i have test with tun5 as name but don't work. It is the OpenMPTCProuter v0.59.1 x86 - 5.4

**Comment by MTSmhas** [comment]
The First Router Open the Server. That's no problem. But the client with mptcp don't connect. I found a problem from wirguard with mwan3... i think the probelm is the similar: https://forum.openwrt.org/t/cant-get-wireguard-to-work-with-mwan3/80198

**Comment by MTSmhas** [comment]
The mptcpovervpn option cant break a second client? that would be an idea that the script overwrites the client.

**Comment by MTSmhas** [comment]
https://github.com/Ysurac/openmptcprouter/issues/2606  This is the error

**Comment by MTSmhas** [comment]
Mon Aug 28 11:54:48 2023 daemon.notice netifd: Interface 'tun5' is setting up now
Mon Aug 28 11:54:48 2023 daemon.warn [8841]: <warn>  [tun5] invalid sysfs path read for net/tun5
Mon Aug 28 11:54:48 2023 daemon.warn [8841]: <warn>  [base-manager] couldn't handle kernel event: device net/tun5 not found
Mon Aug 28 11:54:49 2023 daemon.notice netifd: Interface 'tun5' is now down

**Comment by MTSmhas** [comment]
okay i found the problem the omr-tracker del the wireguard connection.

**Comment by MTSmhas** [comment]
@Ysurac 
now we have a working connection.
But one error ;) 
Mon Aug 28 19:01:44 2023 user.notice OMR-VPS: Setting server config error, try again
Mon Aug 28 19:01:48 2023 user.notice OMR-VPS: Setting server config error, try again

Can you tell me where a this command?

**Comment by MTSmhas** [comment]
Is this message from vps or router?

**Comment by Ysurac** [comment]
Can you make a doc or changes in default config you made ? Maybe I can make this changes as default and this may help

**Comment by MTSmhas** [comment]
We Build a luci app for your Router. That makes it easier. But give me some more time. There are too many changes and too difficult for normal users. To write a doc. ^^
