### ISSUE TITLE
Update OpenVPN and MPTCP patch build erro

### ISSUE THREAD

**Issue by fareign** [Ysurac/openmptcprouter#2946]
## Expected Behavior
https://github.com/Ysurac/openmptcprouter-feeds/commit/da1744ae8a9c5fe571391fc91d252a897545c10d

Applying ./patches/900-add_mptcp_support.patch using plaintext: 
patching file configure.ac
Hunk #1 succeeded at 320 with fuzz 1 (offset 27 lines).
Hunk #2 succeeded at 907 with fuzz 2 (offset 55 lines).
patching file src/openvpn/init.c
Hunk #1 FAILED at 3449.
1 out of 1 hunk FAILED -- saving rejects to file src/openvpn/init.c.rej
patching file src/openvpn/options.c
Hunk #1 FAILED at 130.
Hunk #2 FAILED at 903.
Hunk #3 succeeded at 5317 with fuzz 1 (offset -3517 lines).
2 out of 3 hunks FAILED -- saving rejects to file src/openvpn/options.c.rej
patching file src/openvpn/options.h
Hunk #1 FAILED at 430.
1 out of 1 hunk FAILED -- saving rejects to file src/openvpn/options.h.rej
patching file src/openvpn/ps.c
Hunk #1 succeeded at 47 with fuzz 2 (offset 8 lines).
Hunk #2 FAILED at 435.
1 out of 2 hunks FAILED -- saving rejects to file src/openvpn/ps.c.rej
patching file src/openvpn/socket.c
Hunk #1 succeeded at 44 with fuzz 2 (offset -11 lines).
Hunk #2 succeeded at 1130 with fuzz 2 (offset 31 lines).
Hunk #3 FAILED at 1175.
Hunk #4 FAILED at 1930.
Hunk #5 FAILED at 1959.
Hunk #6 FAILED at 2344.
4 out of 6 hunks FAILED -- saving rejects to file src/openvpn/socket.c.rej
patching file src/openvpn/socket.h
Hunk #1 FAILED at 120.
Hunk #2 FAILED at 315.
Hunk #3 succeeded at 479 with fuzz 2 (offset 3 lines).
2 out of 3 hunks FAILED -- saving rejects to file src/openvpn/socket.h.rej
Patch failed!  Please fix ./patches/900-add_mptcp_support.patch!

## Specifications

  - OpenMPTCProuter version: 
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter VPS provider:
  - OpenMPTCProuter platform: 
  - Country:

**Comment by Ysurac** [comment]
As you can see on Github-Actions: https://github.com/Ysurac/openmptcprouter-feeds/actions/runs/6029053154 the patch can be applied. Delete your platform subdirectory and run build.sh again.
