### ISSUE TITLE
Enable SQM + Enable SQM autorate

### ISSUE THREAD

**Issue by h45h3ncryp73d** [Ysurac/openmptcprouter#2950]
Even after reading all the OpenWRT docs I'm still not sure if "Enable SQM autorate" is a standalone option/feature (from my understanding it is, but I might be wrong) or does it require "Enable SQM" option to be enabled along with it?
Anyway I completely understand SQM autorate is a work in progress and I really hope to see it improved.

**Comment by Ysurac** [comment]
SQM autorate need enable SQM.
