### ISSUE TITLE
StarLink + Freebox

### ISSUE THREAD

**Issue by bagou4502** [Ysurac/openmptcprouter#2951]
## Expected Behavior

Hello, I try to use OpenMpTCPRouter with a Freebox and a Starlink connexion.
Both are connected to my vps but we loose 88mbits (download) at the end.
For explain here are the speedtest with OpenMpTCPRouter:
![image](https://github.com/Ysurac/openmptcprouter/assets/53863206/54862ee4-9e99-45aa-bceb-f30e8dac17a1)
Here is the speedtest with Starlink:
![image](https://github.com/Ysurac/openmptcprouter/assets/53863206/b0662054-3b5a-4e3f-93e7-7f1153d3a9a8)
Here is the connexion with the Freebox:
![image](https://github.com/Ysurac/openmptcprouter/assets/53863206/6b7cabbe-8c1f-4078-8bf4-f8e259e9883c)
And also the speedtest from the VPS:
![image](https://github.com/Ysurac/openmptcprouter/assets/53863206/9b40cbe7-6ddd-4a1f-af5c-3d941c46d15b)

but 56+125=181 and 181-93=88mbits.
This is a problem and I try to understand from where this can come.
![image](https://github.com/Ysurac/openmptcprouter/assets/53863206/9ec11118-d01f-422f-94e9-da47f3e62e2f)

## Specifications

  - OpenMPTCProuter version: v0.59.1-5.4
  - OpenMPTCProuter VPS version: OpenMPTCProuter VPS 0.1028
  - OpenMPTCProuter VPS provider: HostMyServers
  - OpenMPTCProuter platform: RPI4

**Comment by Ysurac** [comment]
Can you test using ```omr-test-speed eth2```, ```omr-test-speed wan2``` and ```omr-test-speed``` (for at least 1 minute, Ctrl+C to stop) ? You can also try ```omr-test-speed``` on the VPS.
Starlink doesn't provide a connection with a stable speed/latency and sometimes seems to give some strange results in speedtests.
You loose also some speed with the encryption (but not as much).

**Comment by Xenon69** [comment]
Hello,
I experienced same problem, not yet resolved.
What device do you use for OMR (Raspberry pi, or other)?
If Raspberry pi, how did you connect starlink ethernet?
