### ISSUE TITLE
Next Release when?

### ISSUE THREAD

**Issue by ccmks** [Ysurac/openmptcprouter#2957]
Hi,

When would be the next release for OMR? I see that the latest release was on August 30, 2022 last year and there has no update ever since

Thank you

**Comment by Ysurac** [comment]
Work is made in develop branch and snapshots are made after each changes.
A beta for next release should be out this week.

**Comment by fareign** [comment]
ss is not statible.status offen become yellow.

**Comment by Ysurac** [comment]
@fareign can you open an issue ? Add system log and screenshot of status page when it's yellow.

**Comment by fareign** [comment]
<img width="590" alt="19" src="https://github.com/Ysurac/openmptcprouter/assets/15459/e4a8e122-b234-4fd8-8249-f0483375e12c">

**Comment by fareign** [comment]
I'M not sure is one of interface cause this or some other settings. V2ray sometime have socket not connected. but network still 
you know me test a long long time. there also a lot of  "Connection reset by peer" I know it is not real erro.but 5.4 kernel VPS may have less this erro. 

Sep 14 02:38:04 iZj6cbfmkgkw74ryinmu3uZ ss-server[874]: getpeername: Transport endpoint is not connected
Sep 14 02:38:02 iZj6cbfmkgkw74ryinmu3uZ omr-service[18265]: Error: Nexthop device required for onlink.
Sep 14 02:37:59 iZj6cbfmkgkw74ryinmu3uZ ss-server[874]: remote recv: Connection reset by peer
Sep 14 02:37:59 iZj6cbfmkgkw74ryinmu3uZ ss-server[874]: remote recv: Connection reset by peer
Sep 14 02:37:55 iZj6cbfmkgkw74ryinmu3uZ ss-server[874]: remote recv: Connection reset by peer
Sep 14 02:37:54 iZj6cbfmkgkw74ryinmu3uZ ss-server[874]: remote recv: Connection reset by peer
Sep 14 02:37:53 iZj6cbfmkgkw74ryinmu3uZ ss-server[874]: remote recv: Connection reset by peer
Sep 14 02:37:51 iZj6cbfmkgkw74ryinmu3uZ ss-server[874]: remote recv: Connection reset by peer
Sep 14 02:37:51 iZj6cbfmkgkw74ryinmu3uZ ss-server[874]: remote recv: Connection reset by peer
Sep 14 02:37:51 iZj6cbfmkgkw74ryinmu3uZ ss-server[874]: remote recv: Connection reset by peer
Sep 14 02:37:51 iZj6cbfmkgkw74ryinmu3uZ omr-service[17602]: Error: Nexthop device required for onlink.
Sep 14 02:37:51 iZj6cbfmkgkw74ryinmu3uZ ss-server[874]: remote recv: Connection reset by peer
Sep 14 02:37:50 iZj6cbfmkgkw74ryinmu3uZ ss-server[874]: remote recv: Connection reset by peer
Sep 14 02:37:50 iZj6cbfmkgkw74ryinmu3uZ ss-server[874]: remote recv: Connection reset by peer
Sep 14 02:37:46 iZj6cbfmkgkw74ryinmu3uZ ss-server[874]: remote recv: Connection reset by peer
Sep 14 02:37:43 iZj6cbfmkgkw74ryinmu3uZ ss-server[874]: remote recv: Connection reset by peer
Sep 14 02:37:43 iZj6cbfmkgkw74ryinmu3uZ ss-server[874]: remote recv: Connection reset by peer
Sep 14 02:37:40 iZj6cbfmkgkw74ryinmu3uZ omr-service[16939]: Error: Nexthop device required for onlink.
Sep 14 02:37:40 iZj6cbfmkgkw74ryinmu3uZ ss-server[874]: remote recv: Connection reset by peer
Sep 14 02:37:31 iZj6cbfmkgkw74ryinmu3uZ ss-server[874]: remote recv: Connection reset by peer
Sep 14 02:37:29 iZj6cbfmkgkw74ryinmu3uZ omr-service[16276]: Error: Nexthop device required for onlink.
Sep 14 02:37:26 iZj6cbfmkgkw74ryinmu3uZ ss-server[874]: remote recv: Connection reset by peer
Sep 14 02:37:25 iZj6cbfmkgkw74ryinmu3uZ ss-server[874]: remote recv: Connection reset by peer
Sep 14 02:37:24 iZj6cbfmkgkw74ryinmu3uZ ss-server[874]: remote recv: Connection reset by peer
Sep 14 02:37:23 iZj6cbfmkgkw74ryinmu3uZ ss-server[874]: remote recv: Connection reset by peer
Sep 14 02:37:23 iZj6cbfmkgkw74ryinmu3uZ ss-server[874]: remote recv: Connection reset by peer
Sep 14 02:37:18 iZj6cbfmkgkw74ryinmu3uZ ss-server[874]: remote recv: Connection reset by peer

**Comment by Ysurac** [comment]
Please open a new issue, it's not related to the original question.
