### ISSUE TITLE
Upload speed not aggregated

### ISSUE THREAD

**Issue by ccmks** [Ysurac/openmptcprouter#2959]
## Current Behavior
Download is aggregated, but not the upload, When test the upload, it only shows single connection being used

## Specifications

  - OpenMPTCProuter version: v0.59.1-5.4 
  - OpenMPTCProuter VPS version: 0.1028 5.4.207
  - OpenMPTCProuter VPS provider: melbicom SG
  - OpenMPTCProuter platform: x86 Hyper-V

Is this really normal, or it is just my OMR is not doing it right?

Thank you

**Comment by Ysurac** [comment]
It's not normal, upload should be aggregated too.
You can try latest snapshot: https://github.com/Ysurac/openmptcprouter/wiki/Snapshots

**Comment by ccmks** [comment]
Ok, thank you
