### ISSUE TITLE
No IPV6 support on lastest version (0.45.5)

### ISSUE THREAD

**Issue by Vinc32du44** [Ysurac/openmptcprouter#296]
## Actual Behavior

No IPV6 access from router to VPS (Scaleway)

## Steps to Reproduce the Problem

  1. Update to last VPS version to 0.87 and reboot
  2. Update OpenMPTCProuter to  0.45.5 and reboot
  3. Keeping same configuration

## Specifications

   - OpenMPTCProuter version: 0.45.5
   - OpenMPTCProuter VPS version: 0.87
   - OpenMPTCProuter platform: x86_64

**Comment by PxxBxx** [comment]
Hello, I have the same issue, but I have no clue how to debug/trace it.
With 0.44.5 I didn't have the "No IPV6 access" in the status page.
With 0.45.6, it appeared.
(Scaleway too)
