### ISSUE TITLE
Multipath TCP path-manager Binders does not aggregate connections.

### ISSUE THREAD

**Issue by vempire-ghost** [Ysurac/openmptcprouter#2963]
## Current Behavior
Multipath TCP path-manager Binders dont work.

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Context (Environment)
Using the Binder path manager does not aggregate connections; when selected, it only utilizes the Master connection, even when using the Redundant scheduler.

## Specifications

  - OpenMPTCProuter version: openmptcprouter v0.60beta1-5.4 r0+16862-170d9
  - OpenMPTCProuter VPS version: 5.4.207-mptcp 0.1029-test
  - OpenMPTCProuter VPS provider: Google Cloud
  - OpenMPTCProuter platform: x86_64
  - Country: Brazil

**Comment by Ysurac** [comment]
Binder path manager require to have "Loose Source and Record Route" (LSRR) supported on the local network. When it's not the case all packets are routed over the same initially chosen path.

**Comment by vempire-ghost** [comment]
Thank you, its something physical on my routers or a configuration? How can I see and enable this in my network?

**Comment by Ysurac** [comment]
It's routers configuration on all network path, it's disabled on most networks for security reason (an attacker can spoof an IP receive spoofed packets for this IP) and not useful for general operation. It's only for some specific cases like when we want to implement mobility in IP networks.
