### ISSUE TITLE
sometimes "OMR-VPS: Setting server config error, try again" need a few times to recovery

### ISSUE THREAD

**Issue by fareign** [Ysurac/openmptcprouter#2966]
## Expected Behavior
Sep 21 04:53:15 OpenMPTCProuter user.notice firewall.omr-server: Firewall reload, set server part firewall reloading
Sep 21 04:53:16 OpenMPTCProuter daemon.notice ttyd[4936]: [2023/09/21 12:53:16:1716] N: rops_handle_POLLIN_netlink: DELADDR
Sep 21 04:53:16 OpenMPTCProuter user.notice mptcp: Reloading mptcp config due to ifup of omrvpn (tun0)
Sep 21 04:54:12 OpenMPTCProuter user.notice OMR-VPS: Setting server config error, try again
Sep 21 04:56:34 OpenMPTCProuter daemon.err glorytun[24722]: 120.79.91.38.65001: connected
Sep 21 04:56:34 OpenMPTCProuter daemon.err glorytun[24722]: couldn't set socket option `TCP_KEEPCNT'
Sep 21 04:56:34 OpenMPTCProuter daemon.err glorytun[24722]: couldn't set socket option `TCP_KEEPIDLE'
Sep 21 04:56:34 OpenMPTCProuter daemon.err glorytun[24722]: couldn't set socket option `TCP_KEEPINTVL'
Sep 21 04:56:34 OpenMPTCProuter daemon.err glorytun[24722]: couldn't set socket option `TCP_USER_TIMEOUT'
Sep 21 04:56:34 OpenMPTCProuter daemon.info glorytun[24722]: STARTED tun0
Sep 21 04:56:35 OpenMPTCProuter user.notice post-tracking-001-post-tracking: Tunnel up : Replace default route by 10.255.255.1 dev tun0
Sep 21 04:57:11 OpenMPTCProuter user.notice OMR-VPS: Setting server config error, try again

## sometimes may cause this
1.wizard setting
2.first use
3.one of interface not steable.

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - OpenMPTCProuter version: 0.6beta 6.1kernel
  - OpenMPTCProuter VPS version: 0.1029test upstream
  - OpenMPTCProuter VPS provider:
  - OpenMPTCProuter platform:  x86_64 
  - Country: cn

**Comment by Ysurac** [comment]
It use master connection to contact the VPS, and retry until it's ok. Master connection should be the more stable connection.
