### ISSUE TITLE
UDP traffice may cause high time delay

### ISSUE THREAD

**Issue by fareign** [Ysurac/openmptcprouter#2967]
## RTMP push and pull
 
<img width="1283" alt="20" src="https://github.com/Ysurac/openmptcprouter/assets/15459/244262c3-691c-4ad1-acb3-6b86a54f38f5">

## SRT Push
 
<img width="722" alt="21" src="https://github.com/Ysurac/openmptcprouter/assets/15459/907fce48-5dc1-4bd9-acf4-12a11badc2e0">

## Possible Solution
 
every mode is  about the same result.
I think it may something relate to 4G or 5G . or some other reason

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - OpenMPTCProuter version: 0.6beta 6.1 kernel
  - OpenMPTCProuter VPS version: 0.1029test upstream
  - OpenMPTCProuter VPS provider:aliyun
  - OpenMPTCProuter platform:  x86_64 
  - Country: CN

**Comment by Ysurac** [comment]
What is the VPN used ? The default VPN, Glorytun TCP doesn't have a very stable latency when it's used.

**Comment by fareign** [comment]
every VPN try. V2ray ,try. almost the same result.

**Comment by Ysurac** [comment]
Then this can be due to bandwidth saturation, you can use SQM that try to solve this.

**Comment by fareign** [comment]
@Ysurac is V2ray default UDP use openvpn? I found v2ray config file key is openvpn

"certificateFile":"/etc/openvpn/ca/pki/issued/server.crt"
keyFile":"/etc/openvpn/ca/pki/private/server.key"

**Comment by fareign** [comment]
I think the main reason is telecom operators speed limit for UDP traffic,UDP2Raw-tunnel and updspeed.may  do something help?

**Comment by Ysurac** [comment]
Glorytun-TCP, and V2Ray if enabled for UDP in advanced settings tab, both fo UDP over TCP. So even if operators limit UDP traffic this will work.
V2Ray and OpenVPN share same keys, because it's easier to have a single key pair.
