### ISSUE TITLE
Since last router update : Can't contact server admin script

### ISSUE THREAD

**Issue by trassiorf** [Ysurac/openmptcprouter#297]
![capture](https://user-images.githubusercontent.com/10478846/50765969-e55d0e80-1277-11e9-9d78-1daca05d54ac.JPG)
Since update of router I have always this message "Can't contact server admin script" 

## Specifications

  - OpenMPTCProuter version: (Last is not a version) 0.45.3
  - OpenMPTCProuter VPS version: (Last is not a version) 0.82
  - OpenMPTCProuter platform: (RPI2/RPI3/x86/x86_64) RPI3

**Comment by Ysurac** [comment]
You should update VPS too.

**Comment by trassiorf** [comment]
No Why it's necessary

**Comment by trassiorf** [comment]
Excuse me the last version of my vps is 0.83 and not 0.82

**Comment by trassiorf** [comment]
OpenMPTCProuter version: (Last is not a version) 0.45.3
    OpenMPTCProuter VPS version: (Last is not a version) 0.83
    OpenMPTCProuter platform: (RPI2/RPI3/x86/x86_64) RPI3 B+

**Comment by Ysurac** [comment]
Yes, update is needed to have all fully working.

**Comment by trassiorf** [comment]
Same thing after update restart of VPS & ROUTER

Curiously I always have to restart the service "Glorytun" by hand

Is it normal for this option (ss_tunnel.dns) to be disabled by default?
![capture](https://user-images.githubusercontent.com/10478846/50767816-95ce1100-127e-11e9-902a-514ee39ba8bc.JPG)

**Comment by trassiorf** [comment]
root@scw-1839b3:~# ps aux | grep omr
root       522  0.0  0.3  19840  3576 ?        Ss   11:53   0:13 /bin/bash /usr/local/bin/omr-service
root       855  0.1  3.1  91016 31948 ?        Ss   11:53   0:25 python3 /usr/local/bin/omr-admin.py
it's ok for running service
Not error in /var/log/daemon.log related to omr-admin.py

**Comment by Ysurac** [comment]
You checked that correct key is used ?
I will release a new version with a more detailed message :)

**Comment by trassiorf** [comment]
Since updating the vps I can not log into ssh on vps anymore from the router.
I have to connect from another adsl box
The keys are identical to the first configuration.
The data was saved and restored identically.
I will test on another vps
I will choose a Kimsufi instead of the Scaleway

**Comment by trassiorf** [comment]
Question : 
Différence entre Glorytun et MLVPN ?
Sont-ils indépendants au niveau fonctionnement ?
Le focntionnement est ok sur Kimsufi 
![capture d ecran-9](https://user-images.githubusercontent.com/10478846/50783214-751bb080-12aa-11e9-89f6-5d8efd01ce99.png)
Mais maintenant j'ai le message "VPN TUNNEL DOWN"

**Comment by Ysurac** [comment]
Par défaut Glorytun TCP est utilisé. Il profite de MPTCP pour l'agrégation.
Glorytun UDP permet l'agrégation de lui même en utilisant UDP.
MLVPN utilise aussi UDP et fait également l'agrégation de lui même.
Chaque VPN est indépendant.

**Comment by trassiorf** [comment]
Bon étrange fonctionnement ok après seconde réécriture d'image routeur 
J'ai pas tout compris mais ça fonctionne :)
![capture d ecran-10](https://user-images.githubusercontent.com/10478846/50784905-579d1580-12af-11e9-93cd-5f015051b1a3.png)

**Comment by Ysurac** [comment]
Il y a un script sur le VPS qui vérifie si le VPN fonctionne, si il fonctionne pas depuis un certain temps il est relancé côté serveur. Donc parfois les soucis se règlent tout seul :)

**Comment by trassiorf** [comment]
Le VPS est-il uniquement atteignable en ssh via l'ip du vpn ??  10.255.255.1 par ce qu'en utilisant cette $ip ça fonctionne bien.
En ce qui concerne les 2 différent VPN (Glorytun & MLVPN) quels avantages à tirer de l'un vis à vis de l'autre ?

**Comment by Ysurac** [comment]
Non, il est accessible via son IP directement.
Un ```ip route``` sur OpenMPTCProuter doit permettre de voir des routes directes vers le VPS. Son IP est également "bypassée" dans ```ipset list```. Si tout est bon, ça peut être le serveur qui bloque via un fail2ban ou autre...

Sinon les VPNs c'est une question de choix, certains peuvent fonctionner mieux que d'autres dans certains cas.

**Comment by trassiorf** [comment]
Une  question comment puis-je forcer simplement la résolution vers les dns opendns ?

**Comment by Ysurac** [comment]
Dans réseau->DHCP puis *transmissions DNS*.
Mais c'est souvent une mauvaise idée d'utiliser OpenDNS ;)

**Comment by trassiorf** [comment]
Pourquoi c'est une mauvaise idée pour opendns ?
Les résolvers utilisés en temps sont par défaut ceux du serveur VPS ? ou ceux du fournisseurs d'accès ?

**Comment by Ysurac** [comment]
Opendns est un DNS menteur qui vend les données liées aux requêtes.
Par défaut les DNS racines sont utilisés.

**Comment by trassiorf** [comment]
Je cherche à protéger mes enfants et je ne voyais qu' Opendns pour les protéger
Donc DNS racines c'est ceux du fournisseur d’accès je pense ? donc par défaut les requêtes sont tracées

**Comment by Ysurac** [comment]
Il y a peut être un paquet openwrt qui fait ça mieux... Je n'ai jamais eu cette problématique.
