### ISSUE TITLE
Need Help to OMR Bypass

### ISSUE THREAD

**Issue by anti-spy** [Ysurac/openmptcprouter#2971]
I have a server. Now I need to make sure that the torrent client bypasses the VPN. I added ports (source port) tcp 16881 and udp 6881 to the bypass. (These ports are specified in the client settings). I also added bittorrent to the bypass at the very bottom of the settings page. This doesn't help either. If I add the server's IP address to the bypass, then it starts to work as it should, but I lose the forwarded ports to this server.

Here is the output of the netstat command on my server:

tcp        0      0 0.0.0.0:16881           0.0.0.0:*               LISTEN      29721/transmissiond 
tcp6       0      0 :::16881                :::*                    LISTEN      29721/transmissiond 
udp        0      0 0.0.0.0:6881            0.0.0.0:*                           29721/transmissiond

**Comment by Ysurac** [comment]
Please use the template when you open an issue.

Port 16881 and 6881 seems to be listen port on your server. I'm not sure to understand: your bittorrent server is on your LAN and you want to bypass bittorrent for this server on LAN ? No real choices then to bypass the IP or MAC, as source ports used can be random ports.
