### ISSUE TITLE
Update to 0.45.2 fail

### ISSUE THREAD

**Issue by mycanaletto** [Ysurac/openmptcprouter#298]
Hello,
The update of the router in 0.44.5 in 0.45.1 or 2 is not going well. The router reboots but it is impossible to connect to the interface or the internet. Restoration from ok from Veeam 
![mptcpup](https://user-images.githubusercontent.com/45459269/50770051-33790e80-1286-11e9-9c2c-f123a3843e5a.jpg)
in 44.5.

## Steps to Reproduce the Problem

  1.Update from the interface (write firmware)
  2.Reboot OK
  3.Hight CPU

## Specifications

  - OpenMPTCProuter version: 0.44.5
  - OpenMPTCProuter VPS version: 0.87
  - OpenMPTCProuter platform: ESXi

**Comment by Ysurac** [comment]
You decompressed the image before update ? Else this fail from unknow reason...

**Comment by mycanaletto** [comment]
No, as usual I directly upload the file: openmptcprouter-v0.45.3-r08982-a54129d8aa-x86-64-combined-squashfs.img.gz

**Comment by Ysurac** [comment]
I'm not able to reproduce the issue on virtualbox.
Do you have something on ESXi console ?

**Comment by Ysurac** [comment]
Update from <0.45 seems to fail. I try to find why.

**Comment by mycanaletto** [comment]
I have nothing on the console after the update if it is a hight cpu. I'm not sure I have SSH access either. What can I do on the console to help you?

**Comment by Ysurac** [comment]
I hope this will be better in next version that is compiling...

**Comment by mycanaletto** [comment]
0.45.6 is OK ?

**Comment by Ysurac** [comment]
If you want to update via the interface no. You can save the config and import it again in new version.
