### ISSUE TITLE
Xray dont work on the VPS

### ISSUE THREAD

**Issue by vempire-ghost** [Ysurac/openmptcprouter#2983]
## Current Behavior
Xray dont work on the VPS

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Context (Environment)
On the router side the log show this.
Oct  2 21:07:16 OpenMPTCProuter daemon.info omr-tracker-xray: xray is down (can't contact via http 1.0.0.1, 212.27.48.10, 198.27.92.1)

On the vps side when i run this command **xray -version** I get this 
xray: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by xray)
xray: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by xray)

## Specifications

  - OpenMPTCProuter version: openmptcprouter v0.60beta1-5.4 r0+16862-170d9 **Snaptshot from 01 october.**
  - OpenMPTCProuter VPS version: 5.4.207-mptcp 0.1029-test **Updated with the teste-server script**
  - OpenMPTCProuter VPS provider: GCP
  - OpenMPTCProuter platform: x86_64
  - Country: Brazil

**Comment by Ysurac** [comment]
What is the OS and version on the VPS ?

**Comment by vempire-ghost** [comment]
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

**Comment by Ysurac** [comment]
It's compiled and tested on Debian 12, I think it's the problem. I will try.

**Comment by vempire-ghost** [comment]
Great, its better setup a new vps directly with 12 or can I upgrade my actual 11 to 12?

**Comment by vempire-ghost** [comment]
Xray is working great in the Debian 12, but the OMR is not showing the proxy traffic when using xray in the dashboard or in the Network Overview.

**Comment by Ysurac** [comment]
Should be fixed now.

**Comment by vempire-ghost** [comment]
Just need run the vps test script again?

What is better for 5.4 kernel, Debian 11 or 12? Or didn't matter?

**Comment by Ysurac** [comment]
Tests are made on Debian 12 with kernel 6.1.
I will maybe force Debian 12 upgrade for all (kernel 5.4 and 6.1) instead of maintaining several Debian versions...
