### ISSUE TITLE
HTTP GET request of interface latency

### ISSUE THREAD

**Issue by drtechga** [Ysurac/openmptcprouter#2985]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Hello can you get a HTTP GET Request for the interface latency to server as a http response?

**Describe alternatives you've considered**

**Additional context**
I use Bitfocus Companion for controlling and monitoring live stream operations and would be nice to get interface latency info.

**Comment by Ysurac** [comment]
Latency for each interface to the VPS is via an HTTP request to the VPS API and it's displayed in the status page of OpenMPTCProuter router part. It's done via a json using internal router API and can be retrieve via ubus command.
You can find more info on OpenWrt documentation for using ubus/API
