### ISSUE TITLE
VPS behind a dynamic public IP

### ISSUE THREAD

**Issue by Mariano245** [Ysurac/openmptcprouter#2993]
Hi, the public IP of my VPS server is not always the same. My OMR is sometimes in another city and I have to upload the new public IP. (Server IP). Is it possible to resolve this situation by using a hostname under a DNS service or by remotely logging into OMR via SSH over the Internet?

**Comment by Ysurac** [comment]
You can use a domain name using dynamic DNS, support of that should be better cince v0.60 beta 1.
