### ISSUE TITLE
VPS Snapshot Script Error

### ISSUE THREAD

**Issue by psfabio** [Ysurac/openmptcprouter#2994]
## Expected Behavior
Install VPS Script

## Current Behavior
There is an error on install script.

## Steps to Reproduce the Problem

got http://www.openmptcprouter.com/server-test/debian-x86_64.sh and install.

## Specifications

  - OpenMPTCProuter VPS version: script got 10/10/2023
  - OpenMPTCProuter VPS provider: Oracle

tested both on ubuntu and debian 12
kernel 5.4

error message:

`
Selecting previously unselected package shadowsocks-go.
(Reading database ... 206310 files and directories currently installed.)
Preparing to unpack .../shadowsocks-go-1.8.0-amd64.deb ...
Unpacking shadowsocks-go (1.8.0) ...
Setting up shadowsocks-go (1.8.0) ...

Configuration file '/etc/shadowsocks-go/server.json', does not exist on system.
Installing new config file as you requested.

Configuration file '/etc/shadowsocks-go/upsks.json', does not exist on system.
Installing new config file as you requested.
Created symlink /etc/systemd/system/multi-user.target.wants/shadowsocks-go.service -> /lib/systemd/system/shadowsocks-go.service.
--2023-10-10 14:21:22--  https://www.openmptcprouter.com/server-test/shadowsocks-go.server.json
Resolving www.openmptcprouter.com (www.openmptcprouter.com)... 193.162.131.1
Connecting to www.openmptcprouter.com (www.openmptcprouter.com)|193.162.131.1|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 990 [application/json]
Saving to: '/etc/shadowsocks-go/server.json'

/etc/shadowsocks-go/server.json       100%[========================================================================>]     990  --.-KB/s    in 0s

2023-10-10 14:21:22 (166 MB/s) - '/etc/shadowsocks-go/server.json' saved [990/990]

jq: error: syntax error, unexpected $end, expecting QQSTRING_TEXT or QQSTRING_INTERP_START or QQSTRING_END (Unix shell quoting issues?) at <top-level>, line 1:
del(.users[0].openmptcprouter."shadowsocks-go)
jq: 1 compile error
`

**Comment by Ysurac** [comment]
Should be fixed.

**Comment by psfabio** [comment]
thanks as always.. :-)

**Comment by psfabio** [comment]
Hi  @Ysurac again.

With today (25/10/23)  http://www.openmptcprouter.com/server-test/debian-x86_64.sh script, a got a new error:

Resolving www.openmptcprouter.com (www.openmptcprouter.com)... 193.162.131.1
Connecting to www.openmptcprouter.com (www.openmptcprouter.com)|193.162.131.1|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1232 (1.2K) [application/json]
Saving to: '/etc/xray/xray-vless-reality.json'

/etc/xray/xray-vless-reality.j 100%[===================================================>]   1.20K  --.-KB/s    in 0s

2023-10-25 20:31:14 (79.2 MB/s) - '/etc/xray/xray-vless-reality.json' saved [1232/1232]

/usr/bin/xray: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/bin/xray)
/usr/bin/xray: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/bin/xray)
ubuntu@omr2:~$


this one was tested on Ubuntu 20.04.6 LTS.
I was trying to update because i was using a snapshot script created about two weeks ago.

Thanks

**Comment by Ysurac** [comment]
Yes for now Snapshot script only support Debian 12.
I will check to compile XRAY on previous OS releases.

**Comment by Ysurac** [comment]
Should be fixed now.

**Comment by psfabio** [comment]
Yes! It is working now.

I´m using Ubuntu because i usually use Oracle Cloud.. they didn´t offer Debian images, so you need to use custom images to use Debian.

I like to test your new snapshots, and it is easy for me to use Ubuntu.

Thanks again.
