### ISSUE TITLE
Update to MPTCPv0.93?

### ISSUE THREAD

**Issue by dtczhl** [Ysurac/openmptcprouter#3]
I find that the MPTCP v0.93 (based on Linux 4.9) is published. I am wondering whether you consider to adopt Linux 4.9 and MPTCP v0.93?

I like Linux 4.9 based LEDE than 4.4 LEDE is that it supports new 802.11ac NICs, such as QCA9888, which is not supported in 4.4. And also 4.9 comes with tools that I like, e.g., bash, vim, etc. 

Thanks.

**Comment by Ysurac** [comment]
If all can be patched, compiled and work well, an alpha version can be available next week, else this will take more time.

**Comment by dtczhl** [comment]
Thanks. I am looking forward to it.
