### ISSUE TITLE
uhttpd Redirect all HTTP to HTTPS setting does not work, logins are always redirected to https, work around needed.

### ISSUE THREAD

**Issue by ioogithub** [Ysurac/openmptcprouter#3000]
## Expected Behavior
omr should obey the setting: `Redirect all HTTP to HTTPS`

The default is 0 = off, and this is what I want:

uci show uhttpd
`uhttpd.main.redirect_https='0'`

this doesn't work, load the webpage http://routerip and it will always redirect to https:/routerip. There is no way to access the router from http.

[Ysurac](https://github.com/Ysurac) Please let me know how I can work around this bug and get http access working for local LAN application.

## Current Behavior
Always redirect to https

## Possible Solution
needs to be fixed, omr should obey the settings

## Context (Environment)
This is a problem because the https uses an invalid (self-signed) certificate. This stops browsers auto-login services from working so it is difficult to get an autologin (does not work) for omr to use in a kiosk setting to display a console dashboard.

If you are forcing a self-signed certificate, at lease give a way to turn it off by omr respecting the setting: `uhttpd.main.redirect_https='0'`

## Specifications
  - OpenMPTCProuter version: v0.59.1-5.4 r0+16594-ce92de8c8c
  - OpenMPTCProuter VPS version: VPS 0.1028
  - OpenMPTCProuter VPS provider:
  - OpenMPTCProuter platform: x86_64)

**Comment by Ysurac** [comment]
It's already working. Did you try a ```curl http://routerip``` (or curl.exe under Windows) ?
