### ISSUE TITLE
Speed expectation for N100/N5105?

### ISSUE THREAD

**Issue by sanvit** [Ysurac/openmptcprouter#3001]
Is anyone using N100/N5105 based hardware for OMR?
It seems like those are the easiest to get with 2.5G interface at AliExpress.
Thinking of bonding 2 5G connection each giving 1~1.5Gbps, and was wondering if the CPU will be sufficient enough to bond it to 2.5G

Any inputs will be appreciated!

**Comment by kpma1985** [comment]
i got 1300Mps 
1000 vodafone germany
100 telekom germany
5G/ LTE by mobile network
