### ISSUE TITLE
Import/Export rules to/from omr-bypass and port forwarding

### ISSUE THREAD

**Issue by Kalimeiro** [Ysurac/openmptcprouter#3006]
Hi,

All is in the title.

It will be great to have the possibility to export and/or import rules from/to omr-bypass and port forwarding on the router parts.

**Comment by Ysurac** [comment]
All rules are in ```/etc/config/omr-bypass``` and ```/etc/config/firewall```. Maybe in a long future via the web interface...

**Comment by ioogithub** [comment]
> All rules are in `/etc/config/omr-bypass` and `/etc/config/firewall`. Maybe in a far future via the web interface...

I have had this issue as well. Is it possible to copy and paste these files from one installation to another, will this mess up the iptables-save and restore functionality?
