### ISSUE TITLE
No Route on Discord servers following most recent updates

### ISSUE THREAD

**Issue by max4186** [Ysurac/openmptcprouter#301]
## Expected Behavior

To be able to connect to a Discord voice call.

## Actual Behavior

Continuous 'No Route' error.

I've tried switching between GloryTUN TCP, UDP and then MLVPN and OpenVPN but unfortunately nothing changes it. I've just rebooted both my Pi and the VPS and this let me connect in the end but this also happened yesterday.

**Comment by Ysurac** [comment]
I would need VPS version and OMR version.

**Comment by max4186** [comment]
OpenMPTCProuter VPS 0.87

I'm not sure where to check the OMR version?
