### ISSUE TITLE
Documentation about command line for OMR Router

### ISSUE THREAD

**Issue by vempire-ghost** [Ysurac/openmptcprouter#3016]
There is a documentation where I can see all the supported command lines to configure OMR router? I don't find in the wiki.

**Comment by Ysurac** [comment]
What do you mean ?
All configuration is in ```/etc/config``` and can be edited via ```uci``` command.

**Comment by vempire-ghost** [comment]
I didn't know that the command was as it was in the settings. Thank you very much.
