### ISSUE TITLE
Incredibly high latency when watching YouTube

### ISSUE THREAD

**Issue by max4186** [Ysurac/openmptcprouter#302]
## Expected Behavior

 Normal latency.

## Actual Behavior

Incredibly high latency.

Picture of going from 20ms average to 2000ms as soon as I start a YT video:

https://i.cyrex.io/Qe88nm0.png

**Comment by ThibautBascoulergue** [comment]
Have you check the TCP congestion control from vps and mptcp router ?

**Comment by Ysurac** [comment]
True, this should be BBR.
I would also need version of VPS and OMR.

**Comment by max4186** [comment]
OpenMPTCProuter VPS 0.87

Not sure where to find OMR version

net.ipv4.tcp_congestion_control = bbr
