### ISSUE TITLE
VPN with OpenVPN not running on the router part

### ISSUE THREAD

**Issue by KaleiRo** [Ysurac/openmptcprouter#3021]
## Expected Behavior

openvpn works.

## Current Behavior

Error in syslog on a deprecated option (ncp_disable), VPN not working, we need to modify the conf and uncheck ncp_disable to work.

## Specifications

  - OpenMPTCProuter version:  v0.60beta1-6.1 r0+24041-74e7f8ebbd
  - OpenMPTCProuter VPS version: 0.1029-test
  - OpenMPTCProuter VPS provider: OVH
  - OpenMPTCProuter platform: all
  - Country: fr

**Comment by Ysurac** [comment]
On an imported configuration ? I will force remove of this option if already exist.
