### ISSUE TITLE
interface

### ISSUE THREAD

**Issue by Doraemon309** [Ysurac/openmptcprouter#3025]
I wonder if kmod-mlx4 or kmod-mlx5 is available in the interface?

**Comment by Ysurac** [comment]
It's available in software packages list System->Software.

**Comment by Doraemon309** [comment]
> It's available in software packages list System->Software.

Yes I know it!
I mean is the kmod-mlx package already installed or do you have to install it yourself?

**Comment by Ysurac** [comment]
Packages are not installed by default.

**Comment by Doraemon309** [comment]
> Packages are not installed by default.

Do you have a schedule for the next release? Can you add a network interface?

**Comment by Ysurac** [comment]
Why ? It's the only interface available on your platform ? What is the model ?

**Comment by Doraemon309** [comment]
> Why ? It's the only interface available on your platform ? What is the model ?

Well, it must be said that nowadays the encapsulation into sfp makes the x86 model compact!
Maybe that makes you wonder about the upcoming versions!
