### ISSUE TITLE
OMR doesn't connect VPS with "can't contact server asmin script" error 

### ISSUE THREAD

**Issue by Chatissimus** [Ysurac/openmptcprouter#3027]
## Expected Behavior
OMR is connecting to the VPS

## Current Behavior
an error "can't contact server admin script" is displayed
the VPS section is no more displayed on settings wizard 

## Specifications

  - OpenMPTCProuter version: 0.59.1-5.4
  - OpenMPTCProuter VPS version: 0.1028
  - OpenMPTCProuter VPS provider: Milkywan
  - OpenMPTCProuter platform: RPI4

![2023-11-06-21-21-03-chrome-OpenMPTCProuter_-_Status_-_LuCI_-_Google_Chrome-pc7Jtp](https://github.com/Ysurac/openmptcprouter/assets/62938061/c0d3563d-d08b-4d60-94d2-19532738effe)
![2023-11-06-21-33-37-chrome-OpenMPTCProuter_-_Settings_Wizard_-_LuCI_-_Google_-keIQfm](https://github.com/Ysurac/openmptcprouter/assets/62938061/de681574-c24a-4406-8ea1-da9decd23c9e)

**Comment by Ysurac** [comment]
Strange, it's a personalized image ?
What do you have, via SSH on the router, if you do a ```uci show openmptcprouter``` ?

**Comment by Chatissimus** [comment]
Hello, 
No , strait one, it was working for month since last update.
according log of my NAS, 3 unexpected power shutdown happened last week ... (I was off for 2 weeks)
I think SD card is crappy 

```
root@OpenMPTCProuter:~# uci show openmptcprouter
uci: Entry not found
```

**Comment by Ysurac** [comment]
Yes, seems to be a dead SD card. You can try a fsck on it but not sure this will solve something.
