### ISSUE TITLE
BBRv2 on Kernel 5.4

### ISSUE THREAD

**Issue by psfabio** [Ysurac/openmptcprouter#3028]
Is the bbrv2 no longer supported on kernel 5.4?

Thanks

![bbr](https://github.com/Ysurac/openmptcprouter/assets/6061933/ba8cca6d-2bfc-45b8-acc6-4b34b667a278)

**Comment by Ysurac** [comment]
Should still be available on 5.4. What is the image used ?

**Comment by psfabio** [comment]
I noticed in the last few snapshots.
This screenshot is from the november 5 snapshot... build (x86_64, 5.4)

**Comment by Ysurac** [comment]
Should be fixed in next snapshot. Thanks for report.

**Comment by psfabio** [comment]
thank you.
