### ISSUE TITLE
proxy and vps status become yellow cant turn to green if not setup wizard

### ISSUE THREAD

**Issue by fareign** [Ysurac/openmptcprouter#3032]
no token yet avalilable.

if not setup wizard ,it never turn to green. although the net status is good.

is some relate to this err?

Nov  8 18:42:33 OpenMPTCProuter daemon.err omr-tracker-xray[26434]: sh: missing ]
Nov  8 18:42:33 OpenMPTCProuter daemon.err omr-tracker-xray[26434]: sh: missing ]

## Specifications

  - OpenMPTCProuter version:snapshots the latest 6.1kernel
  - OpenMPTCProuter VPS version: 0.1029 test upstream
  - OpenMPTCProuter VPS provider:
  - OpenMPTCProuter platform: x86_64
  - Country: cn

**Comment by Ysurac** [comment]
I don't know what you mean by "no setup wizard" ? It's after an initial configuration and a failure of proxy ? What do you have in system log else ?

**Comment by Ysurac** [comment]
And what is the proxy and protocol used ?

**Comment by fareign** [comment]
Nov  8 20:26:48 OpenMPTCProuter daemon.info omr-tracker-xray: xray is up (can contact via http 49.7.115.41)
Nov  8 20:26:48 OpenMPTCProuter user.notice omr-tracker: Launching...
Nov  8 20:26:55 OpenMPTCProuter user.notice omr-tracker: Launched
Nov  8 20:26:57 OpenMPTCProuter daemon.info omr-tracker-xray: xray is up (can contact via http 49.7.115.41)
Nov  8 20:27:21 OpenMPTCProuter daemon.err omr-tracker-xray[16520]: sh: missing ]
Nov  8 20:27:21 OpenMPTCProuter daemon.err omr-tracker-xray[16520]: sh: missing ]

no erro log ,because it work well ,only status yellow.
<img width="952" alt="22" src="https://github.com/Ysurac/openmptcprouter/assets/15459/f45b8297-eda8-41dd-8ab9-efe335afb34e">

**Comment by fareign** [comment]
proxy is xray trojan,v2ray has the same problem

**Comment by fareign** [comment]
I test  ss is the same.

**Comment by fareign** [comment]
if I save and apply openmptcprouter wizard.it become green ,and afew seconds late become yellow . thoes interface is green.it nerver turn to green. you can test with no very good internet.

**Comment by fareign** [comment]
if i remove the 4G antenna,status will change. so the status is working.
but I install the antenna back, the 4G working. the status become (NO token yet avaliable) not green 
@Ysurac

**Comment by fareign** [comment]
[Fix when VPS contact is a DNS](https://github.com/Ysurac/openmptcprouter-feeds/commit/5b32c33c0530b3fce4951d5807b6bcc62c3379ef)  Maybe is this fix.

**Comment by fareign** [comment]
[Restart missing WAN tracker when needed](https://github.com/Ysurac/openmptcprouter-feeds/commit/510c13a8419af0046e992ba6639cc8a6b29cfd57)  is this update
