### ISSUE TITLE
Best support of VLAN

### ISSUE THREAD

**Issue by KaleiRo** [Ysurac/openmptcprouter#3034]
When i use, for exemple, an Raspberry PI for router, or another router with only one ethernet port, i need to use VLAN between each WAN BOX and the OMR ROUTER for multiple reason (logic, good practices, security, better management, ...)

But scripts of OMR have bugs since few times, it works better if i have a router with dedicated ports for LAN or WAN.

An recent exemple in syslog with post-tracking script :

Nov 10 18:42:54 xxx-openmptcp user.notice mptcp: Reloading mptcp config due to ifup of wan1 (eth0.3)
Nov 10 18:42:58 xxx-openmptcp user.notice post-tracking-001-post-tracking: Reload MPTCP config for eth0.2
Nov 10 18:42:59 xxx-openmptcp user.notice post-tracking-001-post-tracking: Multipath eth0.2 switched to on (from off)
Nov 10 18:43:00 xxx-openmptcp user.notice post-tracking-001-post-tracking: Reload MPTCP config for eth0.3
Nov 10 18:43:01 xxx-openmptcp user.notice post-tracking-001-post-tracking: Multipath eth0.3 switched to on (from off)
Nov 10 18:43:04 xxx-openmptcp user.notice post-tracking-001-post-tracking: Reload MPTCP config for eth0.2
Nov 10 18:43:05 xxx-openmptcp user.notice post-tracking-001-post-tracking: Multipath eth0.2 switched to on (from off)
Nov 10 18:43:06 xxx-openmptcp user.notice post-tracking-001-post-tracking: Reload MPTCP config for eth0.3
Nov 10 18:43:07 xxx-openmptcp user.notice post-tracking-001-post-tracking: Multipath eth0.3 switched to on (from off)
Nov 10 18:43:09 xxx-openmptcp user.notice post-tracking-001-post-tracking: Reload MPTCP config for eth0.2
Nov 10 18:43:10 xxx-openmptcp user.notice post-tracking-001-post-tracking: Multipath eth0.2 switched to on (from off)

on the OMR WIZARD, we don't have the possibility to set VLAN ID with MacVLAN mode, so we need to set VLAN ID directly in the interface after the wizard.

The QoS-SQM doesn't work with VLAN interface, one rule is apply on all interfaces.

**Comment by Ysurac** [comment]
It's a bug not an enhancement. I would need to know the version used (snapshot I think).

For MacVLAN, VLAN are not supported because it's already some sort of VLAN.
I would need the result of ```multipath``` command via SSH from the router

I will check for QoS-SQM but did you mean with or without sqm-autorate enabled or both ?
