### ISSUE TITLE
How to build with preinstalled packages?

### ISSUE THREAD

**Issue by GermanAizek** [Ysurac/openmptcprouter#3039]
I just tried another Card from HP (qlogic chip). It needs kmod-qlcnic which is sadly not included in openmptcprouter :(

_Originally posted by @benedikt-bartscher in https://github.com/Ysurac/openmptcprouter/issues/2231#issuecomment-1003110723_
            
Hi. How to build openmptcprouter with installed package `kmod-qlcnic` and `pciutils`?

**Comment by Ysurac** [comment]
To compile your own image, you can follow: https://github.com/Ysurac/openmptcprouter/wiki/Create-image-for-unsupported-platform
