### ISSUE TITLE
Raspberry Pi 3B generated problems, VPN TUNNEL DOWN, and OMR 6in4 NOip NO gateway

### ISSUE THREAD

**Issue by suyuan168** [Ysurac/openmptcprouter#304]
## Expected Behavior

   In English please.

## Actual Behavior
I am using Raspberry Pi 3B, broadband overlay appears, VPN TUNNEL DOWN

## Steps to Reproduce the Problem

   1.VPN TUNNEL DOWN
   2.OMR 6in4 NOip NO gateway

## Specifications

   - OpenMPTCProuter version: (Last is not a version)NEW
   - OpenMPTCProuter VPS version: (Last is not a version)NEW
   - OpenMPTCProuter platform: (RPI2/RPI3/x86/x86_64) PRI3B

**Comment by suyuan168** [comment]
![556](https://user-images.githubusercontent.com/3435645/50908557-e4d59b00-1464-11e9-9b13-adfb0846b6ef.jpg)
This is the status picture

**Comment by suyuan168** [comment]
![_20190109232220](https://user-images.githubusercontent.com/3435645/50908858-9248ae80-1465-11e9-855a-97e43386f8e7.png)
？

**Comment by suyuan168** [comment]
Glorytun  Glorytun can't run, always click start to stop

**Comment by Ysurac** [comment]
omr6in4 must have multipath disabled.
For the VPN, you should update and check the system log.

**Comment by suyuan168** [comment]
Download speed is particularly slow, isn't it broadband overlay? Upload speed looks normal
![_20190110103250](https://user-images.githubusercontent.com/3435645/50942295-1da45d00-14c3-11e9-8132-abcab3ad5f1f.png)

**Comment by suyuan168** [comment]
My single network card is over 20M.,Why is there so little after routing?

**Comment by trassiorf** [comment]
![tempsnip](https://user-images.githubusercontent.com/10478846/50956344-b9ca6600-14bb-11e9-8685-8941c78f30d4.png)
Same thing for me the download BP is very low.
Generally I have almost a BP at 60Mbps out of aggregation

Specifications

   - OpenMPTCProuter version: (Last is not a version) 0.45.6
   - OpenMPTCProuter VPS version: (Last is not a version) 0.87
   - OpenMPTCProuter platform: (RPI2/RPI3/x86/x86_64) RPI3 B+

**Comment by suyuan168** [comment]
Are you also RPI 3B? My remote server VPS port is 100M delayed by 30ms, and the local single 4G speed is 20M. After using two cards to aggregate, the speed is slower? Why is that? ?

**Comment by trassiorf** [comment]
Yes RPI 3B "+" local 4 G (WAN2) speed is over 60M (Day) over 80M (Night)
 I use only one network card this is default of RPI3 B+
Latency average on Scaleway VPS is on 36ms
WAN1 is on the switch with local $IP 192.168.11.1 BP below than 4.5Mbps
 Since version 0.45.6 WAN1 never go up

**Comment by suyuan168** [comment]
What is going on here? How to do? There seems to be no better solution to the problem now?

**Comment by trassiorf** [comment]
suyuan168 : "After using two cards to aggregate, the speed is slower? Why is that? ?" 
Why use 2 cards for aggregate ?
See only one is needed
https://docs.ovh.com/fr/overthebox/installation-manuelle-otb-intel/
![otb](https://user-images.githubusercontent.com/10478846/50958357-cdc49680-14c0-11e9-8363-72b0f5e127ba.JPG)

**Comment by suyuan168** [comment]
I am now more than 4G Huawei E8372

**Comment by trassiorf** [comment]
Ok no switch
I use old Huawei B593u12 so no problem for me

**Comment by suyuan168** [comment]
Thu Jan 10 17:32:14 2019 daemon.err glorytun[16955]: tun write: I/O error
![_20190110173225](https://user-images.githubusercontent.com/3435645/50959372-c2439080-14fd-11e9-9a7a-9b0c8745da6d.png)

**Comment by suyuan168** [comment]
there is a problem. After a few hours, I prompted daemon.err glorytun[16955]: tun write: I/O error

**Comment by suyuan168** [comment]
My Glorytun always stops unexpectedly. Need to start manually. Is this Glorytun UDP or TCP? How to set it up? Thu Jan 10 21:47:03 2019 daemon.info glorytun: starting glorytun vpn instance vpn
Thu Jan 10 21:47:03 2019 daemon.err glorytun[20922]: couldn't create tun device
Thu Jan 10 21:47:13 2019 daemon.info glorytun: starting glorytun vpn instance vpn
Thu Jan 10 21:47:13 2019 daemon.err glorytun[21333]: couldn't create tun device
Thu Jan 10 21:47:15 2019 daemon.err /usr/bin/ss-local[17691]: ​​getpeername: Socket not connected
Thu Jan 10 21:47:43 2019 daemon.err glorytun[22004]: couldn't create tun device
Thu Jan 10 21:48:12 2019 daemon.info glorytun: starting glorytun vpn instance vpn
Thu Jan 10 21:48:12 2019 daemon.err glorytun[22610]: couldn't create tun device
Thu Jan 10 21:48:14 2019 daemon.info glorytun: starting glorytun vpn instance vpn
Thu Jan 10 21:48:14 2019 daemon.err glorytun[22699]: couldn't create tun device
Thu Jan 10 21:48:15 2019 daemon.info glorytun: starting glorytun vpn instance vpn
Thu Jan 10 21:48:15 2019 daemon.err glorytun[22809]: couldn't create tun device
Thu Jan 10 21:48:17 2019 daemon.err /usr/bin/ss-local[17691]: ​​getpeername: Socket not connected

error. And MLVPN is also in the DOWN state. How is it unstable? How can I solve it?

**Comment by trassiorf** [comment]
Have you test ? : The permutation of Glorytun protocol tcp to udp then restart service

**Comment by suyuan168** [comment]
Tested or stopped abnormally. I think it has something to do with this MPTCP---settings---Congestion Control. But I don't know how to set it up.

**Comment by Ysurac** [comment]
I will try to reproduce this issue.

**Comment by suyuan168** [comment]
> I will try to reproduce this issue.

Thank you
