### ISSUE TITLE
image build question

### ISSUE THREAD

**Issue by longxisutdio** [Ysurac/openmptcprouter#3041]
I use the command below to build image follow the instrustion  https://github.com/Ysurac/openmptcprouter/wiki/Create-image-for-unsupported-platform

OMR_TARGET="r5s" OMR_FEED_SRC="master" ./build.sh -j1 V=sc

So what should I do next?

raceback (most recent call last):
  File "scripts/dtc/pylibfdt/setup.py", line 23, in <module>
    from setuptools import setup, Extension
ModuleNotFoundError: No module named 'setuptools'
make[6]: *** [scripts/dtc/pylibfdt/Makefile:33: rebuild] Error 1
make[5]: *** [scripts/Makefile.build:397: scripts/dtc/pylibfdt] Error 2
make[4]: *** [Makefile:2003: scripts_dtc] Error 2
make[4]: Leaving directory '/home/longxi/openmptcprouter/r5s/5.4/source/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r5s-rk3568/u-boot-2023.04'
make[3]: *** [Makefile:325: /home/longxi/openmptcprouter/r5s/5.4/source/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r5s-rk3568/u-boot-2023.04/.built] Error 2
make[3]: Leaving directory '/home/longxi/openmptcprouter/r5s/5.4/source/package/boot/uboot-rockchip'
time: package/boot/uboot-rockchip/nanopi-r5s-rk3568/compile#4.11#2.20#11.07
    ERROR: package/boot/uboot-rockchip failed to build (build variant: nanopi-r5s-rk3568).
make[2]: *** [package/Makefile:116: package/boot/uboot-rockchip/compile] Error 1
make[2]: Leaving directory '/home/longxi/openmptcprouter/r5s/5.4/source'
make[1]: *** [package/Makefile:110: /home/longxi/openmptcprouter/r5s/5.4/source/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/longxi/openmptcprouter/r5s/5.4/source'
make: *** [/home/longxi/openmptcprouter/r5s/5.4/source/include/toplevel.mk:230：world] 错误 2

**Comment by Ysurac** [comment]
It's seems that setuptools is missing for python, you should try to install it.
What is the distribution used ?
