### ISSUE TITLE
router for OpenMPTPRouter

### ISSUE THREAD

**Issue by Esysteme** [Ysurac/openmptcprouter#3047]
I just look on device supported and i saw : Teltonika RUTX12, just wow (more smaller with alim in 5V usb it was perfect ! but much better what i got with 3 box and lot of cables)

OpenMPTPRouter is able to manage 2 sim card in same time on this device ?

**Comment by Ysurac** [comment]
RUTX12 have 2 modems so both can be used at the same time with OpenMPTCProuter.
RUTX12 is not supported, for now, in future release using 6.1 kernel because my device used for tests is broken.

**Comment by Esysteme** [comment]
if i can help to support this device let me know. 


One more question how to block internet if we are not connected to VPS ?
