### ISSUE TITLE
Don't compile on kernel 6.6 with my additional drivers

### ISSUE THREAD

**Issue by GermanAizek** [Ysurac/openmptcprouter#3058]
Log in file: [log.txt](https://github.com/Ysurac/openmptcprouter/files/13531553/log.txt)
Running commands:
```
$ make menuconfig
$ make -j6 V=sc
```

**Comment by Ysurac** [comment]
Kernel 6.6 is not yet supported, it's only a test for now.
When you have error, compile again using ```make -j1 V=s```, else it's a nightmare to find where is the error.
In your log, this seems to be a problem to connect to github, so try again.

**Comment by GermanAizek** [comment]
@Ysurac `$ make -j1 V=s > log.txt` [log.txt](https://github.com/Ysurac/openmptcprouter/files/13535970/log.txt)

**Comment by Ysurac** [comment]
I forgot a patch, should be better now.
