### ISSUE TITLE
Teltonika RUTX12 

### ISSUE THREAD

**Issue by Esysteme** [Ysurac/openmptcprouter#3062]
I bought this routeur, if you need help to test don't hesitate.

if not supported why this image : (if i try i may broke my routeur ? i mean how to put original software if something wrong ?)

Teltonika RUTX12(may work on all RUTX series)
squashfs image: [openmptcprouter-v0.59.1-5.4-r0+16594-ce92de8c8c-ipq40xx-generic-teltonika_rutx-squashfs-sysupgrade.bin](https://download.openmptcprouter.com/release/v0.59.1/rutx/targets/ipq40xx/generic/openmptcprouter-v0.59.1-5.4-r0+16594-ce92de8c8c-ipq40xx-generic-teltonika_rutx-squashfs-sysupgrade.bin) (2022/08/29 - 50.25Mo - [sha256sum](https://download.openmptcprouter.com/release/v0.59.1/rutx/targets/ipq40xx/generic/openmptcprouter-v0.59.1-5.4-r0+16594-ce92de8c8c-ipq40xx-generic-teltonika_rutx-squashfs-sysupgrade.bin.sha256sum))

**Comment by Ysurac** [comment]
It's supported in current release, maybe also work in next kernel 5.4 based image but not on kernel 6.1 based image (at least for now).

**Comment by Esysteme** [comment]
if i can help for 6.1 let me know
