### ISSUE TITLE
install on RUTX12 

### ISSUE THREAD

**Issue by Esysteme** [Ysurac/openmptcprouter#3064]
I installed this file : openmptcprouter-v0.59.1-5.4-r0+16594-ce92de8c8c-ipq40xx-generic-teltonika_rutx-squashfs-sysupgrade.bin

directly to the interface of RUTX12 to upgrade firmware.

after sometime the leds bandwitch made like K2000, and then nothing. i got only the led of power and (right) led of rj45 when i connect a cable.

I tried to reset without success.

Any idea ?

**Comment by Ysurac** [comment]
Recovery should still work: https://wiki.teltonika-networks.com/view/RUTX12_Device_Recovery_Options (sometimes this doesn't work on first tries)
If I remember correctly, RUTX12 have 2 versions, I only support old version. And I also see in RUTX12 Teltonika page that they support others NAND, this can also be a problem.
