### ISSUE TITLE
Not possible to enable support for my network card

### ISSUE THREAD

**Issue by GermanAizek** [Ysurac/openmptcprouter#3065]
I'm trying to build openmptcprouter with support for my pci-e network card HP NC375T using tutorial on reddit page https://www.reddit.com/r/openwrt/comments/vpqtg2/get_netxen_nic_running/, but I can't find my network device in list. I maybe found only 2 devices from tutorial:

My steps:

![image](https://github.com/Ysurac/openmptcprouter/assets/21138600/76a154f2-5e37-4dc8-818b-fdac0314370b)

![image](https://github.com/Ysurac/openmptcprouter/assets/21138600/19ce6eb6-281d-421d-84aa-8fd7f3852740)

Tutorial steps:

![image](https://github.com/Ysurac/openmptcprouter/assets/21138600/d98c5bec-5ca0-4b9d-8686-5d418c4eaa77)

![image](https://github.com/Ysurac/openmptcprouter/assets/21138600/8891160c-29b4-479f-86df-dfa3c963a224)

![image](https://github.com/Ysurac/openmptcprouter/assets/21138600/cf55f69b-d1fd-4e51-8f12-4a588635d113)

![image](https://github.com/Ysurac/openmptcprouter/assets/21138600/43c45380-70f7-406f-807f-a1aa14f1e8b9)

**Comment by GermanAizek** [comment]
@Ysurac thank you very much for hotfix, I found original post tutorial on openwrt forum, only my network pci-e card has name in .config file (highlighted in the screenshot)
![image](https://github.com/Ysurac/openmptcprouter/assets/21138600/57393b6c-f3fa-43b8-878f-3738758ecedb)

**Comment by GermanAizek** [comment]
QLA3XXX I didn't see

**Comment by Ysurac** [comment]
If I understand correctly, should be supported by netxen-nic driver.

**Comment by GermanAizek** [comment]
I'm going to try to rebuild and test it now.

**Comment by GermanAizek** [comment]
> If I understand correctly, should be supported by netxen-nic driver.
@Ysurac, yes indeed this driver, the best support maintainer, but there is a problem when I use two network cards. Only one adds new interfaces, I looked through ifconfig, and other gives driver error `netxen_nic: failed card response code:0x14`

This print function in driver source code: https://github.com/torvalds/linux/blob/3f82f1c3a03694800a4104ca6b6d3282bd4e213d/drivers/net/ethernet/qlogic/netxen/netxen_nic_ctx.c#L62-L66
This code error in define: https://github.com/torvalds/linux/blob/3f82f1c3a03694800a4104ca6b6d3282bd4e213d/drivers/net/ethernet/qlogic/netxen/netxen_nic.h#L755

it's about a bad signature, but I don't understand.

there is no mention this problem on internet, I have different pci-express x16 ports, there should be no problems.

**Comment by GermanAizek** [comment]
@Ysurac I checked same behavior on corporate server, took HDD with openmptcp x86_64 image and two my network cards. When connecting one to PCIE on server, everything is fine and eth0-eth7 is detected. I have inner 4 lan ports on server and 4 external from PCIE network card, when connecting an additional PCIE network card for using 12 lan ports, ifconfig shows only eth0-eth3 and when starting openmptcp, he is shows `netxen_nic: failed card response code:0x14` again. Very unclear behavior, whether BIOS settings are to blame or something is missing from linux kernel.

**Comment by GermanAizek** [comment]
Users on forums write about `firmware_nextxen` package, I understand correctly that firmware network card needs to be updated only using package, not linux kernel driver, drivers do not know how to do this.

**Comment by GermanAizek** [comment]
![image](https://github.com/Ysurac/openmptcprouter/assets/21138600/0af658c3-f534-435f-9f0d-3a8413382229)

It has an NX3031 chipset, here user was prompted not only to enable the drivers, but also enable bnx2x firmware using make menuconfig

https://forum.openwrt.org/t/finding-the-right-kmod-module-for-netxen-nx3031/131263/1

![image](https://github.com/Ysurac/openmptcprouter/assets/21138600/7a0e3092-49b3-4cf4-a67b-6f445e4c357a)

**Comment by GermanAizek** [comment]
@Ysurac, there were no updates to driver code in linux 6.x kernel. Behavior driver is very strange.

**Comment by Ysurac** [comment]
Did you finally try on Debian ?

**Comment by GermanAizek** [comment]
> Did you finally try on Debian ?

on any linux, OMR image, this problem exists, but on windows, this driver works correctly with multiple network cards. there is no information netxen_nic driver error code. I tried google it, most likely I will have to ask on forums about errors driver code, I do not understand why "Bad Signature 0x14" error is being thrown. Advise me forum linux devices, I will write to them about problem. and it is desirable for us to create separate issue, this issue with addition driver has already been solved.

**Comment by GermanAizek** [comment]
> Did you finally try on Debian ?
This problem on any linux and OMR, but older version linux not tested.

**Comment by GermanAizek** [comment]
@Ysurac,
> If I understand correctly, should be supported by netxen-nic driver.

I decided to build 6.1 kernel with my drivers on network card and did not find them in make menuconfig. Did u patch and add only in 6.6?

**Comment by Ysurac** [comment]
It's directly in "Kernel modules" submenu for all kernels.

**Comment by GermanAizek** [comment]
> It's directly in "Kernel modules" submenu for all kernels.

and in "Ethernet Devices" submenu?

**Comment by Ysurac** [comment]
no, directly here, at the end.

**Comment by GermanAizek** [comment]
> no, directly here, at the end.

indeed, why did you decide to make it so hidden, would you put it in 'Network Devices' as all others.

**Comment by GermanAizek** [comment]
> Did you finally try on Debian ?

@Ysurac, I double-checked several network cards connected to pci-e and you won't believe it, they all create interfaces without problems on Debian 11 and Debian 12. here I attach my system logs and detailed information, including the kernel config. i.e. the problem exists in OMR, several network cards refuse to work with netxen_nic firmware. I don't have another pair network cards to make sure that problem is only with this firmware.

[hw_info_debian_11_5.10.txt](https://github.com/Ysurac/openmptcprouter/files/14544352/hw_info_debian_11_5.10.txt)

[hw_info_debian_12_6.5.txt](https://github.com/Ysurac/openmptcprouter/files/14544359/hw_info_debian_12_6.5.txt)

**Comment by Ysurac** [comment]
I would need a dmesg from debian 12 if possible to check what it is doing at boot.

**Comment by Ysurac** [comment]
Not needed. The firmware is missing: https://packages.debian.org/fr/sid/firmware-netxen
I will add this.

**Comment by GermanAizek** [comment]
> Not needed. The firmware is missing: https://packages.debian.org/fr/sid/firmware-netxen I will add this.

Do I need to rebuild with two checkboxes now? Network device and firmware?
