### ISSUE TITLE
Network/Interfaces do not working on last snapshot.

### ISSUE THREAD

**Issue by vempire-ghost** [Ysurac/openmptcprouter#3066]
## Expected Behavior
The Interface settings work when I open them.

## Current Behavior
The page doesn't load and only shows this error.
![image](https://github.com/Ysurac/openmptcprouter/assets/132581535/611f8043-5e05-4334-a1ef-e5d56835d5b3)

## Specifications

  - OpenMPTCProuter version: openmptcprouter v0.60beta1-5.4 r0+16862-170d9 snapshot from 06/12
  - OpenMPTCProuter VPS version: 5.4.207-mptcp 0.1029-test
  - OpenMPTCProuter VPS provider: GCP
  - OpenMPTCProuter platform: x86_64
  - Country: Brazil

**Comment by psfabio** [comment]
Hi Ysurac, this problem still persist on the latest snapshot (12/11/2023)
openmptcprouter v0.60beta1-5.4 r0+16862-170d9e447d
Thanks

**Comment by Ysurac** [comment]
I'm not able to reproduce the issue using same snapshot. Can you try to remove cookies and cache for OpenMPTCProuter IP in your browser ?
