### ISSUE TITLE
Shadowsocks error

### ISSUE THREAD

**Issue by MrTheSkream** [Ysurac/openmptcprouter#307]
Shadowsocks not running error

`user.notice post-tracking-post-tracking: Can't find Shadowsocks, restart it...`

You can check my config : http://92.243.18.28/cgi-bin/luci/

id : root
mdp : xxxxxxxx

## Steps to Reproduce the Problem

  1. Use Rapsberry
  2. Install version 45.6 of OpenMPTCProuter
  3. Setup Wizard (WAN and VPS)

## Specifications

  - OpenMPTCProuter version: 45.6
  - OpenMPTCProuter VPS version: 0.85
  - OpenMPTCProuter platform: RPI3 B+

**Comment by Roken120** [comment]
I have same error !!!! last version.

**Comment by Ysurac** [comment]
Dont put password in issues

**Comment by Ysurac** [comment]
I Will solve this bug tomorrow or this week end.

**Comment by Ysurac** [comment]
Same as #308
