### ISSUE TITLE
Error when opening luci.

### ISSUE THREAD

**Issue by vempire-ghost** [Ysurac/openmptcprouter#3070]
After the password on the luci screen, only show this error.
/usr/lib/lua/luci/controller/mptcp.lua:16: attempt to index upvalue 'uname' (a nil value)
stack traceback:
	/usr/lib/lua/luci/controller/mptcp.lua:16: in function 'v'
	/usr/lib/lua/luci/dispatcher.lua:1219: in function 'createtree'
	/usr/lib/lua/luci/dispatcher.lua:693: in function 'menu_json'
	/usr/lib/lua/luci/dispatcher.lua:794: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:479: in function </usr/lib/lua/luci/dispatcher.lua:478>

## Specifications

  - OpenMPTCProuter version: openmptcprouter v0.60beta1-5.4 r0+16862-170d9 10/12 snapshot
  - OpenMPTCProuter VPS version: 5.4.207-mptcp 0.1029-test
  - OpenMPTCProuter VPS provider:
  - OpenMPTCProuter platform: x86_64
  - Country:

**Comment by SonicFM** [comment]
Hi,
did you upgraded any packages via opkg?

Please ssh into you OMR and check if "luci-compat" package is installed. If not, do so.
