### ISSUE TITLE
Need Install Wireguard client on VPS Server

### ISSUE THREAD

**Issue by hle5128** [Ysurac/openmptcprouter#3076]
## Expected Behavior
We want to use a Wireguard client from a third party as a public IP instead VPS IP.

## Current Behavior
Currently, Wirguard Client on VPS only use 1 ether, not combined MPTCP

Is there a way we can route all traffic from MPTCP to the Wireguard client?

**Comment by Ysurac** [comment]
What do you mean ? You want to use Wireguard as exit point on VPS ? There is some issues already about that.
I hope to add support for Wireguard/OpenVPN clients on VPS as exit quite soon.
