### ISSUE TITLE
Trouble Building x86_64 Image with MT7922e Support on Kernel 6.1

### ISSUE THREAD

**Issue by LiuTangLei** [Ysurac/openmptcprouter#3083]
When using 'make menuconfig', I only found the option for 'mt7922-bt', which is for Bluetooth. I'm looking to enable support for WiFi, but couldn't find an option to enable it while trying to compile it myself.

Could you please advise me on what I should do? Thank you.

**Comment by Ysurac** [comment]
Maybe it's "MediaTek MT76x2 wireless driver" (mt76x2) kernel module. Should be ok if you enable mt76.

**Comment by LiuTangLei** [comment]
OMR_ALL_PACKAGES=yes fix my problem, thanks
