### ISSUE TITLE
Vps install fail

### ISSUE THREAD

**Issue by docblocxxx** [Ysurac/openmptcprouter#3084]
VPS Debian 11 snapshot cannot complete install, becase 
(50.1 MB/s) - '/etc/xray/xray-vless-reality.json' saved [1239/1239]
/usr/bin/xray: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/bin/xray)
/usr/bin/xray: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/bin/xray)
exit
 5.10.0-26-amd64 #1 SMP Debian 5.10.197-1 (2023-09-29) x86_64 GNU/Linux

It happened after the last update snapshot

**Comment by Ysurac** [comment]
I compiled it on Debian 12, I will compile it again for older release.

**Comment by Ysurac** [comment]
Should be better now.
