### ISSUE TITLE
What is limit on count WAN connections?

### ISSUE THREAD

**Issue by GermanAizek** [Ysurac/openmptcprouter#3090]
@Ysurac Hello, I am interested in question why openmptcprouter is limited to 4 wan connections, what explains this problem?
There are no restrictions themselves programmatically, but I read issues and everyone is talking about real limit 4 connections.

**Comment by Ysurac** [comment]
There is currently a limit of 8 addresses.

**Comment by GermanAizek** [comment]
> There is currently a limit of 8 addresses.

Is it possible to manually fixed and increase to 12, is this due to the unstable network operations in kernel?

**Comment by Ysurac** [comment]
It's due to MPTCP internal Path Manager limit of subflows numbers.
The number is already increased in current 5.4 kernel release to 16 subflows for x86 and x86_64.
It's not yet increased for 6.1 snapshot release.

**Comment by GermanAizek** [comment]
> It's due to MPTCP internal Path Manager limit of subflows numbers. The number is already increased in current 5.4 kernel release to 16 subflows for x86 and x86_64. It's not yet increased for 6.1 snapshot release.

thanks for detailed answer, I built 6.6 kernel so there should be a maximum 16 wan connections, but I already see that you have version 6.7 available, what are major differences between them?

**Comment by Ysurac** [comment]
Even for 6.6 or 6.7 it's still limited to 8 subflows.
The current 6.7 is for test only, based on MPTCP_net-next branch. I'm using it to test BPF.
I've not yet checked changelog between 6.6 and 6.7 as 6.7 is still a Release Candidate.

**Comment by GermanAizek** [comment]
> Even for 6.6 or 6.7 it's still limited to 8 subflows.

this is bad, but I hope something will change in this direction.
