### ISSUE TITLE
OpenMPTCProuter 0.60 kernel 5.4 and Hyper-V VHDX

### ISSUE THREAD

**Issue by aydinj** [Ysurac/openmptcprouter#3098]
## Expected Behavior

OpenMPTCProuter 0.60 router with kernel 5.4 should have Hyper-V or VHDX version. 
## Current Behavior

In both Snapshots and Beta 1 router releases, the VHDX version for hyper-v should be included. However, in the the 6.1 kernel, it is present. 
## Steps to Reproduce the Problem

  1. Click on the link  https://download.openmptcprouter.com/release/v0.60beta1-5.4/ or https://github.com/Ysurac/openmptcprouter/wiki/Snapshots
  2.
  3.

## Specifications

  - OpenMPTCProuter version: 
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter VPS provider:
  - OpenMPTCProuter platform: 
  - Country:

**Comment by Ysurac** [comment]
It will be made on release for 5.4, it's not in OpenWRT old base used for 5.4 kernel.
