### ISSUE TITLE
Bug in VPS script : need "patch" package !

### ISSUE THREAD

**Issue by xslite** [Ysurac/openmptcprouter#31]
Bonjour,

et encore merci, comme d'habitude, pour ces nouvelles releases très fréquentes qui font évoluer OpenMPTCPRouteur si rapidement, bravo Ysurac !

Alors un petit bug dans le script VPS, qui empêche son bon déroulement jusqu'à la fin (méthode anti-newbie ?) 
Il manque en effet le package "patch" pour pouvoir appliquer le patch NOCRYPTO.

Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/Ysurac/openmptcprouter-feeds/master/shadowsocks-libev/patches/020-NOCRYPTO.patch [following]
--2018-03-31 12:36:49--  https://raw.githubusercontent.com/Ysurac/openmptcprouter-feeds/master/shadowsocks-libev/patches/020-NOCRYPTO.patch
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 25407 (25K) [text/plain]
Saving to: ‘020-NOCRYPTO.patch’

020-NOCRYPTO.patch               100%[========================================================>]  24.81K  --.-KB/s    in 0.001s

2018-03-31 12:36:49 (28.1 MB/s) - ‘020-NOCRYPTO.patch’ saved [25407/25407]

sh: 32: patch: not found

**Comment by Ysurac** [comment]
C'est ajouté, je pensais pas que la moindre installation de Debian n'est pas patch déjà ;)
