### ISSUE TITLE
How to solve the problem of recompiling from beginning by running 'make'

### ISSUE THREAD

**Issue by atyouspace** [Ysurac/openmptcprouter#3101]
## Expected Behavior
Running `make -j1 V=s`, recompiling from the beginning is not needed. Because I only did minor revision.

## Current Behavior
Every time I run make, recompile rather than compiling the modified files. I did not modify the Makefile. How to solve this problem?

## Specifications

  - OpenMPTCProuter version: --- 0.6beta1 --
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter VPS provider:
  - OpenMPTCProuter platform: --- imx6 --

**Comment by Ysurac** [comment]
You can do a ```make -j$(nproc)```, it's faster than a -j1. It's not recompiling from beginning if run in source directory.
You can also compile a specific package with ```make package/network/utils/nftables/compile``` for example and install it with ```make package/install && make target/install```

**Comment by atyouspace** [comment]
> You can do a `make -j$(nproc)`, it's faster than a -j1. It's not recompiling from beginning if run in source directory. You can also compile a specific package with `make package/network/utils/nftables/compile` for example and install it with `make package/install && make target/install`

Does it have anything to do with whether the platform is not supported?
I found `rm -f ...` will run firstly after `make`

**Comment by Ysurac** [comment]
This doesn't have to do anything with supported or not supported platform.
If you do only a make some part are recompiled and some not. It use OpenWRT build system.
