### ISSUE TITLE
which defconfig file is related with `make`

### ISSUE THREAD

**Issue by atyouspace** [Ysurac/openmptcprouter#3105]
## Current Behavior
wl18xx wifi module is used on the imx6 board, however, this wl18xx wifi doesn't work.
I found one solution from TI official, we have to compile the driver and patch kernel.
wl18xx WLAN functionality requires certain settings to be enabled in the kernel configuration by `./verify_kernel_config.sh <def_config file>`
There are lots of defconfig files under this folder, `kernel/arch/arm/configs/`. I would like to know which one is for imx6.
imx_v4_v5_defconfig
imx_v6_v7_defconfig

## Specifications

  - OpenMPTCProuter version: --- (0.6beta1) --
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter VPS provider:
  - OpenMPTCProuter platform: --- (imx6) --

**Comment by Ysurac** [comment]
imx6 is not supported by OpenMPTCProuter, and is not yet supported on kernel 6.1 by OpenWRT.
In any case, the config file really used should be here: https://github.com/openwrt/openwrt/tree/main/target/linux/imx
defconfig files are not used.
