### ISSUE TITLE
A router only stops working if I use it together with openmptcp

### ISSUE THREAD

**Issue by bluenor** [Ysurac/openmptcprouter#3113]
I'm having a strange problem, I have three routers, the second one I can't access anymore and the connection doesn't work when I put it as master, when I use omrbypass and whatnot. However, if I try to connect directly to the router with the router ip address it works perfectly. For example, I can't even access the 192.168.12.1 page which corresponds to the router's address when I'm connected to the 192.168.100.1 network which is the address of the raspberry. If I happen to reboot the raspberry where there is openmptcp router, for a moment I can access it but then the connection is like cut off. What could this be?

**Comment by Ysurac** [comment]
Please use template. I need OpenMPTCProuter version, VPS version,...

**Comment by Ysurac** [comment]
I don't really understand your problem. Can you make a plan or something ?
