### ISSUE TITLE
Add Wireguard as a VPN option.

### ISSUE THREAD

**Issue by vempire-ghost** [Ysurac/openmptcprouter#3116]
Today, OMR already has Wireguard, but it can only be used as MPTCP over VPN. Would it be possible to add it as a standalone VPN option alongside the others?

MLVPN and DSVPN have never worked whenever I've tested them. Glorytun is unstable and slow, while OPENVPN works but has significant latency.

**Comment by Ysurac** [comment]
Wireguard and OpenVPN UDP can't be aggregated.
The option will be added later on wizard page.

**Comment by vempire-ghost** [comment]
Ah, thank you. I thought Wireguard was aggregatable like OPENVPN TCP is.
