### ISSUE TITLE
Bananapi BPI-R2 No wifi network settings?

### ISSUE THREAD

**Issue by suyuan168** [Ysurac/openmptcprouter#312]
## Steps to Reproduce the Problem

  1.Download and install Banana Pi BPI-R2 (32-bit) (beta support)
  2.Go to the router management page
  3.Did not find the location of the wifi network

## Specifications
openmptcprouter v0.45.9 r0+9007-529c95cc15
![_20190112132926](https://user-images.githubusercontent.com/3435645/51069640-208f8100-166e-11e9-9f2d-011c38c56843.png)

**Comment by suyuan168** [comment]
hello??

**Comment by Ysurac** [comment]
You know it's not a chatroom ?
I need to check on the platform and to solve the issue.

**Comment by suyuan168** [comment]
> You know it's not a chatroom ?
> I need to check on the platform and to solve the issue.

Thank you very much, thank you. I apologize. What is the problem with broadband overlay? I am here 2 2M broadband should not be 40M? Why is it still 20M. Thank you for answering my question.

**Comment by Ysurac** [comment]
I have some problem with the BPI-R2 platform, it's why it's still in Beta support.
Some results are quite strange...
You can follow issue https://github.com/Ysurac/openmptcprouter/issues/180
There is also many bugs in latest OMR version, I'm trying to solve must of them, if then you get better result you can submit them in issue #180
