### ISSUE TITLE
How to continue build.sh instead of starting over？

### ISSUE THREAD

**Issue by atyouspace** [Ysurac/openmptcprouter#3125]
I want to create image for RPI4 platform, following [This](https://github.com/Ysurac/openmptcprouter/wiki/Create-image-for-unsupported-platform)
`git clone https://github.com/Ysurac/openmptcprouter.git`
`cd openmptcprouter`
`git checkout master`
`OMR_TARGET="rpi4" OMR_FEED_SRC="master" OMR_KERNEL="5.4" ./build.sh`
My question is that,
What should I do if this building process is interrupted unexpectedly in the middle?

## Specifications

  - OpenMPTCProuter version: v0.60beta1
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter VPS provider:
  - OpenMPTCProuter platform: RPI4

**Comment by Ysurac** [comment]
You can go in ```rpi4/5.4/source``` directory and do a ```make -j1 V=s``` to check what is the error.
