### ISSUE TITLE
Comment activer un DNS avec SSL sur le VPS OMR ?

### ISSUE THREAD

**Issue by JeedHome44** [Ysurac/openmptcprouter#3126]
Bonjour,

Je souhaite utiliser Google SmartHome mais pour cela, il faut obligatoirement un DNS HTTPS (les SSL auto certifié ne sont pas acceptés).

Y a-t-il une configuration OMR à faire pour utiliser un DNS OVH en HTTPS ?

Merci de votre aide.

**Comment by Ysurac** [comment]
OpenMPTCProuter utilise par défaut les DNS racines. Pour utiliser OMR-ByPass, l'IP d'OpenMPTCProuter doit être utilisé en tant que DNS.
Par contre pas possible d'avoir un certificat non auto signé facilement car la partie routeur n'est pas disponible en direct sur internet.
Je ne connais pas Google SmartHome et je ne sais pas si il y a une manière de contourner cette limitation.
