### ISSUE TITLE
How to change IP address WAN port on exit VPS?

### ISSUE THREAD

**Issue by GermanAizek** [Ysurac/openmptcprouter#3128]
@Ysurac very thx for active contibuting OpenMPTCProuter,
is it possible to do ip forwarding from router to VPS, with change to selected IP WAN in real time or with restart services?

**Comment by Ysurac** [comment]
What do you want to do exactly and why ?
It's possible that I didn't think about a corner case here...

**Comment by GermanAizek** [comment]
@Ysurac,
Are there 2 ISP providers, they come to openmptcprouter. Google IP Score rating on VPS is very bad, but he is very cheap, I am forced to constantly go through captchas and cloudflare waf, can I use cleaner IP of one of ISP providers?

**Comment by Ysurac** [comment]
You can use OMR-ByPass to use directly a WAN for specified sites/IPs.

**Comment by GermanAizek** [comment]
> OMR-ByPass
What is it and is there wiki or documentation on how to use it?

**Comment by GermanAizek** [comment]
@Ysurac, Do I understand correctly that I will have to list all visited sites with WAF captchas for OMR bypass?

**Comment by Ysurac** [comment]
You will have to list all captchas providers site. But in most case it's not necessary are there is not a lot of captchas providers and after a few times an IP is back in a "whitelist".

**Comment by GermanAizek** [comment]
> You will have to list all captchas providers site.

Where can I read about how to create this list, configure, what syntax should I use, etc.

**Comment by GermanAizek** [comment]
@Ysurac, how to use OMR-Bypass as example WAN0 - only SSH 22 and FTP 21 connection, WAN1 only HTTP 80 and HTTPS 443?

**Comment by GermanAizek** [comment]
the site filtering method does not help, there are too many sites that consider it easier for a robot to bypass the entire protocol
