### ISSUE TITLE
Configuration does not save for upload/download speed of a USB device

### ISSUE THREAD

**Issue by dnwk** [Ysurac/openmptcprouter#313]
Even though I typed in the information multiple times, whenever I reach the page, it still prompts me to enter it.
![Image of error](https://file.callhome.me/file/web-call/32.PNG)

## Specifications

  - OpenMPTCProuter version:  v0.45.9 r0+9007-529c95cc15
  - OpenMPTCProuter VPS version: 0.88
  - OpenMPTCProuter platform: Linksys WRT32X

**Comment by suyuan168** [comment]
me too

**Comment by Ysurac** [comment]
Should be fixed in latest release.

**Comment by dnwk** [comment]
This issue is still happening latest version 0.46.2

**Comment by dnwk** [comment]
Confirmed resolved in v0.46.3
