### ISSUE TITLE
How to install VPS on Windows?

### ISSUE THREAD

**Issue by GermanAizek** [Ysurac/openmptcprouter#3132]
@Ysurac,
is it possible to install openmptcp VPS on VDS with Windows. If there are no options, is only installing a virtual machine suitable?

**Comment by Ysurac** [comment]
OpenMPTCProuter is an OS, so if you want to run it under windows, you have to put it in a VM via Virtualbox for example.
Not sure on what can be done with WSL, but in any case it's not supported.

**Comment by GermanAizek** [comment]
@Ysurac,
you didn't understand, I want to use this as VPS Windows. is it possible? or was it not originally intended that way?
![image](https://github.com/Ysurac/openmptcprouter/assets/21138600/693742d2-ba6d-4531-add0-2515fa445b9e)

**Comment by Ysurac** [comment]
On the VPS only Debian 12 is supported. Not sure if WSL would also be possible but this is not supported and will not be supported.
