### ISSUE TITLE
use `external kernel tree` to make 

### ISSUE THREAD

**Issue by atyouspace** [Ysurac/openmptcprouter#3133]
I would like to enable external kernel tree to make. How to do that?
I use `Advanced configuration options (for developers) -->` `external kernel tree`
but I found it doesn't work, the zImage in new kernel tree folder didn't change.

## Specifications

  - OpenMPTCProuter version: --- 0.60beta1

**Comment by Ysurac** [comment]
An external kernel tree is used for kernel 6.7 tests: https://github.com/Ysurac/openmptcprouter
You can look on changes/config used in build.sh and 6.7 directory.
