### ISSUE TITLE
VPN is not running

### ISSUE THREAD

**Issue by WayLAN-2008** [Ysurac/openmptcprouter#3134]
## Expected Behavior
That the VPS works and that bonding is active

## Current Behavior
In my openMPTC router, it says the VPN is not running.
## Specifications

  - OpenMPTCProuter version: 
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter VPS provider :My own WIN10SERVER with Hyper-V Debian 10 install
  - OpenMPTCProuter platform: 

https://pastebin.com/A5nYpx5s

**Comment by WayLAN-2008** [comment]
Forgot to put the screenshot
![image](https://github.com/Ysurac/openmptcprouter/assets/110018993/9be350c7-0479-45ce-b34a-aaa2b4969b74)

**Comment by Ysurac** [comment]
It can't contact the VPS part:
* did you reboot VPS after script install ?
* can you go to https://<VPS_IP>:65500/ and get something ?

**Comment by WayLAN-2008** [comment]
Yes i get this
![Screenshot_20240125-061959.png](https://github.com/Ysurac/openmptcprouter/assets/110018993/92c6ea5f-7187-4d41-8255-ee541a2ec42f)

**Comment by WayLAN-2008** [comment]
What ports do i need to open. I did open 65101 and 65401 and 65500.

**Comment by Ysurac** [comment]
Open range 65000-65535
Else you have the list here: https://github.com/Ysurac/openmptcprouter/wiki/Install-or-update-the-VPS

**Comment by WayLAN-2008** [comment]
As soon as I am home I am going to try it out!

**Comment by WayLAN-2008** [comment]
It works now! It still says the VPN is not running but it works thanks!

**Comment by Ysurac** [comment]
VPN is used by default for UDP only. It should work.
You can check in Status->System log why it's not running.
