### ISSUE TITLE
omr-test-speedv6 can't run

### ISSUE THREAD

**Issue by rdmitry0911** [Ysurac/openmptcprouter#3140]
## Expected Behavior

omr-test-speedv6 gives an error
## Current Behavior

When run 
`omr-test-speedv6`
it produces error:
`/bin/omr-test-speedv6: line 40: syntax error: unexpected "fi"`
## Possible Solution

Delete line 40 from /bin/omr-test-speedv6
## Steps to Reproduce the Problem

  1. run omr-test-speedv6 from the shell
  2.
  3.

## Specifications

  - OpenMPTCProuter version:  [openmptcprouter v0.60beta1-6.1 r0+23789-ce6ad123e7]
  - OpenMPTCProuter VPS version: 0.1029-test 6.1.0-17-amd64
  - OpenMPTCProuter VPS provider: Hetzner
  - OpenMPTCProuter platform: x86_64
  - Country: Greece

**Comment by Ysurac** [comment]
Should be fixed in latest commit
