### ISSUE TITLE
Adding new target alias names for `aarch64_generic`

### ISSUE THREAD

**Issue by GermanAizek** [Ysurac/openmptcprouter#3141]
@Ysurac,
```
$ OMR_TARGET="arm64" OMR_FEED_SRC="master" OMR_KERNEL="5.4" ./build.sh
```

```
Target arm64 not found ! You have to configure and compile your kernel manually.
```

Maybe we should add alias target names aarch64_generic?
Example:
`arm64`, `aarch64` and `aarch64_generic`

according to code build.sh, it is necessary to set incomprehensible unknown `r2s` `r4s` for building.

![image](https://github.com/Ysurac/openmptcprouter/assets/21138600/9879ac52-23c6-42cf-bbe5-91f5ae74b878)

**Comment by Ysurac** [comment]
Generic ARM64 support is "armsr64", but I don't know what you want to do.
The OMR_REAL_TARGET is used only for packages feeds because they can be generic.

**Comment by GermanAizek** [comment]
I was trying to build Arm64 image on Arm64 host Ubuntu 20.04
