### ISSUE TITLE
SSH tunnel between OMR and the VPS.

### ISSUE THREAD

**Issue by vempire-ghost** [Ysurac/openmptcprouter#3153]
Is it possible to establish an SSH tunnel between OMR and the VPS to redirect TCP traffic through it instead of using a proxy or VPN?

**Comment by Ysurac** [comment]
Yes should be possible.

**Comment by vempire-ghost** [comment]
Can you add this option to OMR? Or do I need to use some extra app for this?

**Comment by Ysurac** [comment]
This will maybe be added later but I will need to patch OpenSSH for MPTCP support on >= 6.1 kernel
I think the best solution for OpenMPTCProuter is to configure the client as a SOCKS proxy, and this require OpenSSH. Dropbear is used instead of OpenSSH on OpenMPTCProuter for now.
