### ISSUE TITLE
image on ROCK pi 4 C+ --> Erreur DNS: impossible de resoudre des noms d'hotes

### ISSUE THREAD

**Issue by yannick2801** [Ysurac/openmptcprouter#3156]
Hi, 

what can i check to resolve this issue ? 
(my VPS works on an other support)

  - OpenMPTCProuter version: Linux OpenMPTCProuter 5.4.238 #0 SMP PREEMPT aarch64 GNU/Linux
  - OpenMPTCProuter VPS version: 0.1026 5.4.100
  - OpenMPTCProuter VPS provider:
  - OpenMPTCProuter platform: ROCK pi 4C+

image on ROCK pi 4 C+ --> **Erreur DNS: impossible de resoudre des noms d'hotes**

![image](https://github.com/Ysurac/openmptcprouter/assets/97221644/6f1873ad-c789-4f80-bbdf-2d1045b25405)

Thanks
BR
Yannick

**Comment by Ysurac** [comment]
It's not a supported platform.
Did you change DNS configuration ? Check what you have in Network->DHCP&DNS
Via SSH on te router check if ```ping 1.1.1.1``` is working, if yes check ```dig google.com``` check if you have an IP in results, if no, try ```dig google.com @1.1.1.1``` check if you have IP in results, and if yes check that dnsmasq and unbound are running (```ps l```)

**Comment by yannick2801** [comment]
hi, i don't think i have chnage DNS Configuration,
I have tryed does commands (you can see below): 
But on this router i have no answer to `ps 1`

![image](https://github.com/Ysurac/openmptcprouter/assets/97221644/54cc3396-ab8d-45af-8b42-afc550baaffe)

Thanks
BR
Yannick

**Comment by Ysurac** [comment]
Not ```ps 1``` but ```ps l```.
Make sure you didn't set any DNS on Network->Interfaces, and check if you don't have errors in Status->System log

**Comment by yannick2801** [comment]
in `ps l`, i haven't gor unbound, that's strange.

**Comment by yannick2801** [comment]
still de same : 
_Feb 12 12:27:10 OpenMPTCProuter user.notice unbound: default protocol configuration
Feb 12 12:27:10 OpenMPTCProuter user.notice unbound: default memory configuration
Feb 12 12:27:10 OpenMPTCProuter user.notice unbound: default recursion configuration
Feb 12 12:27:35 OpenMPTCProuter daemon.info procd: Instance unbound::unbound s in a crash loop 6 crashes, 0 seconds since last crash
Feb 12 12:28:06 OpenMPTCProuter user.notice unbound: default protocol configuration
Feb 12 12:28:06 OpenMPTCProuter user.notice unbound: default memory configuration
Feb 12 12:28:06 OpenMPTCProuter user.notice unbound: default recursion configuration
Feb 12 12:28:31 OpenMPTCProuter daemon.info procd: Instance unbound::unbound s in a crash loop 6 crashes, 0 seconds since last crash_

```
root@OpenMPTCProuter:~# /etc/init.d/unbound restart
unbound: default protocol configuration
unbound: default memory configuration
unbound: default recursion configuration
```

```
root@OpenMPTCProuter:~# uci show unbound
unbound.ub_main=unbound
unbound.ub_main.add_extra_dns='0'
unbound.ub_main.add_local_fqdn='1'
unbound.ub_main.add_wan_fqdn='0'
unbound.ub_main.dhcp_link='none'
unbound.ub_main.dhcp4_slaac6='0'
unbound.ub_main.dns64='0'
unbound.ub_main.dns64_prefix='64:ff9b::/96'
unbound.ub_main.domain='lan'
unbound.ub_main.domain_type='static'
unbound.ub_main.edns_size='1232'
unbound.ub_main.extended_stats='0'
unbound.ub_main.hide_binddata='1'
unbound.ub_main.interface_auto='1'
unbound.ub_main.listen_port='53'
unbound.ub_main.localservice='1'
unbound.ub_main.manual_conf='0'
unbound.ub_main.num_threads='1'
unbound.ub_main.protocol='default'
unbound.ub_main.query_minimize='0'
unbound.ub_main.query_min_strict='0'
unbound.ub_main.rate_limit='0'
unbound.ub_main.rebind_localhost='0'
unbound.ub_main.rebind_protection='1'
unbound.ub_main.recursion='default'
unbound.ub_main.resource='default'
unbound.ub_main.root_age='9'
unbound.ub_main.ttl_min='120'
unbound.ub_main.ttl_neg_max='1000'
unbound.ub_main.unbound_control='0'
unbound.ub_main.validator='0'
unbound.ub_main.validator_ntp='1'
unbound.ub_main.verbosity='1'
unbound.ub_main.iface_trig='lan' 'wan'
unbound.ub_main.iface_wan='wan'
unbound.auth_icann=zone
unbound.auth_icann.enabled='0'
unbound.auth_icann.fallback='1'
unbound.auth_icann.url_dir='https://www.internic.net/domain/'
unbound.auth_icann.zone_type='auth_zone'
unbound.auth_icann.server='lax.xfr.dns.icann.org' 'iad.xfr.dns.icann.org'
unbound.auth_icann.zone_name='.' 'arpa.' 'in-addr.arpa.' 'ip6.arpa.'
unbound.fwd_isp=zone
unbound.fwd_isp.enabled='0'
unbound.fwd_isp.fallback='1'
unbound.fwd_isp.resolv_conf='1'
unbound.fwd_isp.zone_type='forward_zone'
unbound.fwd_isp.zone_name='isp-bill.example.com.' 'isp-mail.example.net.'
unbound.fwd_google=zone
unbound.fwd_google.enabled='0'
unbound.fwd_google.fallback='1'
unbound.fwd_google.tls_index='dns.google'
unbound.fwd_google.tls_upstream='1'
unbound.fwd_google.zone_type='forward_zone'
unbound.fwd_google.server='8.8.4.4' '8.8.8.8' '2001:4860:4860::8844' '2001:4860:4860::8888'
unbound.fwd_google.zone_name='.'
unbound.fwd_cloudflare=zone
unbound.fwd_cloudflare.enabled='0'
unbound.fwd_cloudflare.fallback='1'
unbound.fwd_cloudflare.tls_index='cloudflare-dns.com'
unbound.fwd_cloudflare.tls_upstream='1'
unbound.fwd_cloudflare.zone_type='forward_zone'
unbound.fwd_cloudflare.server='1.1.1.1' '1.0.0.1' '2606:4700:4700::1111' '2606:4700:4700::1001'
unbound.fwd_cloudflare.zone_name='.'
unbound.fwd_adguard_family=zone
unbound.fwd_adguard_family.enabled='0'
unbound.fwd_adguard_family.fallback='1'
unbound.fwd_adguard_family.tls_index='dns-family.adguard.com'
unbound.fwd_adguard_family.tls_upstream='1'
unbound.fwd_adguard_family.zone_type='forward_zone'
unbound.fwd_adguard_family.server='176.103.130.132' '176.103.130.134'
unbound.fwd_adguard_family.zone_name='.'
unbound.fwd_adguard_standard=zone
unbound.fwd_adguard_standard.enabled='0'
unbound.fwd_adguard_standard.fallback='1'
unbound.fwd_adguard_standard.tls_index='dns.adguard.com'
unbound.fwd_adguard_standard.tls_upstream='1'
unbound.fwd_adguard_standard.zone_type='forward_zone'
unbound.fwd_adguard_standard.server='176.103.130.130' '176.103.130.131'
unbound.fwd_adguard_standard.zone_name='.'
unbound.fwd_cloudflare_family=zone
unbound.fwd_cloudflare_family.enabled='0'
unbound.fwd_cloudflare_family.fallback='1'
unbound.fwd_cloudflare_family.tls_index='family.cloudflare-dns.com'
unbound.fwd_cloudflare_family.tls_upstream='1'
unbound.fwd_cloudflare_family.zone_type='forward_zone'
unbound.fwd_cloudflare_family.server='1.1.1.3' '1.0.0.3'
unbound.fwd_cloudflare_family.zone_name='.'
unbound.fwd_cloudflare_malware=zone
unbound.fwd_cloudflare_malware.enabled='0'
unbound.fwd_cloudflare_malware.fallback='1'
unbound.fwd_cloudflare_malware.tls_index='security.cloudflare-dns.com'
unbound.fwd_cloudflare_malware.tls_upstream='1'
unbound.fwd_cloudflare_malware.zone_type='forward_zone'
unbound.fwd_cloudflare_malware.server='1.1.1.2' '1.0.0.2'
unbound.fwd_cloudflare_malware.zone_name='.'
unbound.fwd_odvr=zone
unbound.fwd_odvr.enabled='0'
unbound.fwd_odvr.fallback='1'
unbound.fwd_odvr.tls_index='odvr.nic.cz'
unbound.fwd_odvr.tls_upstream='1'
unbound.fwd_odvr.zone_type='forward_zone'
unbound.fwd_odvr.server='193.17.47.1' '185.43.135.1'
unbound.fwd_odvr.zone_name='.'
unbound.fwd_libredns=zone
unbound.fwd_libredns.enabled='0'
unbound.fwd_libredns.fallback='1'
unbound.fwd_libredns.tls_index='doh.libredns.gr'
unbound.fwd_libredns.tls_upstream='1'
unbound.fwd_libredns.zone_type='forward_zone'
unbound.fwd_libredns.server='116.202.176.26'
unbound.fwd_libredns.zone_name='.'
unbound.fwd_quad9_recommended=zone
unbound.fwd_quad9_recommended.enabled='0'
unbound.fwd_quad9_recommended.fallback='1'
unbound.fwd_quad9_recommended.tls_index='dns.quad9.net'
unbound.fwd_quad9_recommended.tls_upstream='1'
unbound.fwd_quad9_recommended.zone_type='forward_zone'
unbound.fwd_quad9_recommended.server='9.9.9.9' '149.112.112.112'
unbound.fwd_quad9_recommended.zone_name='.'
unbound.fwd_quad9_unsecured=zone
unbound.fwd_quad9_unsecured.enabled='0'
unbound.fwd_quad9_unsecured.fallback='1'
unbound.fwd_quad9_unsecured.tls_index='dns10.quad9.net'
unbound.fwd_quad9_unsecured.tls_upstream='1'
unbound.fwd_quad9_unsecured.zone_type='forward_zone'
unbound.fwd_quad9_unsecured.server='9.9.9.10' '149.112.112.10'
unbound.fwd_quad9_unsecured.zone_name='.'
unbound.fwd_quad9_ecs=zone
unbound.fwd_quad9_ecs.enabled='0'
unbound.fwd_quad9_ecs.fallback='1'
unbound.fwd_quad9_ecs.tls_index='dns11.quad9.net'
unbound.fwd_quad9_ecs.tls_upstream='1'
unbound.fwd_quad9_ecs.zone_type='forward_zone'
unbound.fwd_quad9_ecs.server='9.9.9.11' '149.112.112.11'
unbound.fwd_quad9_ecs.zone_name='.'
unbound.fwd_quad9_secured=zone
unbound.fwd_quad9_secured.enabled='0'
unbound.fwd_quad9_secured.fallback='1'
unbound.fwd_quad9_secured.tls_index='dns9.quad9.net'
unbound.fwd_quad9_secured.tls_upstream='1'
unbound.fwd_quad9_secured.zone_type='forward_zone'
unbound.fwd_quad9_secured.server='9.9.9.9' '149.112.112.9'
unbound.fwd_quad9_secured.zone_name='.'
root@OpenMPTCProuter:~#
```

**Comment by Ysurac** [comment]
There is a problem here: ```unbound.ub_main.listen_port='53'``` dnsmasq is already listening to this port, by default it's set to 5353 on OpenMPTCProuter.

**Comment by yannick2801** [comment]
Thanks

i have added those 2 lines : 
![image](https://github.com/Ysurac/openmptcprouter/assets/97221644/3eec0430-62a9-4b89-80fe-1a62c591b475)

seems better but i think i have an other probleme: 
![image](https://github.com/Ysurac/openmptcprouter/assets/97221644/6eb0f05a-a450-49e9-bb5a-d6c82a4fd720)

**Comment by Ysurac** [comment]
Did you also change port in Services->Recursive DNS to 5353 ?

**Comment by yannick2801** [comment]
perfect, thank you very mutch

**Comment by Trent63** [comment]
> Hi,
> 
> what can i check to resolve this issue ? (my VPS works on an other support)
> 
> * OpenMPTCProuter version: Linux OpenMPTCProuter 5.4.238 #0 SMP PREEMPT aarch64 GNU/Linux
> * OpenMPTCProuter VPS version: 0.1026 5.4.100
> * OpenMPTCProuter VPS provider:
> * OpenMPTCProuter platform: ROCK pi 4C+
> 
> image on ROCK pi 4 C+ --> **Erreur DNS: impossible de resoudre des noms d'hotes**
> 
> ![image](https://private-user-images.githubusercontent.com/97221644/303644620-6f1873ad-c789-4f80-bbdf-2d1045b25405.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxOTQzNTUsIm5iZiI6MTcwODE5NDA1NSwicGF0aCI6Ii85NzIyMTY0NC8zMDM2NDQ2MjAtNmYxODczYWQtYzc4OS00ZjgwLWJiZGYtMmQxMDQ1YjI1NDA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDE4MjA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkMDY5ZmJkNjU2ZWM0ZTMwMzg0ZTU4NmRhZDUwMmFkYWU4MDM2YTEzNjhiMmE0ZTAxYTQ1Yzg5NjU2YTYyNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iya2JrSwKTzFgu7u3QWZ9zmbMpaUHEiEi-rD1WmEOMA)
> 
> Thanks BR Yannick

Привет. Как с вами связаться напрямую? у меня есть вопрос по сборке OMR на RockPI
