### ISSUE TITLE
Certificate expired err

### ISSUE THREAD

**Issue by Fsoc1337** [Ysurac/openmptcprouter#3157]
## Current Behavior
trying to install VPS Script : 

```
Err:6 https://repo.openmptcprouter.com buster Release
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 169.150.247.37 443]
Get:7 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Hit:8 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease
Reading package lists... Done
E: The repository 'https://repo.openmptcprouter.com buster Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

## Specifications

  - OpenMPTCProuter version:
  - OpenMPTCProuter VPS version: Ubuntu 20.04 LTS
  - OpenMPTCProuter VPS provider: 
  - OpenMPTCProuter platform:

**Comment by Ysurac** [comment]
Try https://repo.openmptcprouter.com with a browser, then try via ```curl https://repo.openmptcprouter.com``` on the VPS.
Maybe a temporary problem on the CDN.
If it's not working, try to update Ubuntu (you should really use Debian...), it can have expired certificates.
