### ISSUE TITLE
Wrong wan addresses report on state page

### ISSUE THREAD

**Issue by Dragonox77** [Ysurac/openmptcprouter#3159]
Hello,
Thank you for your work.

## Expected Behavior

Get valid wan addresses report on the state page

## Current Behavior

Wan addresses are the same on wan1 & wan2

![image](https://github.com/Ysurac/openmptcprouter/assets/34002813/ecde9f61-abed-4ba1-9f07-9e155dc5d49e)

## Specifications

  - OpenMPTCProuter version: 0.59.1-5.4
  - OpenMPTCProuter VPS version: 0.1028 5.4.207-mptcp
  - OpenMPTCProuter VPS provider: OVH BareMetal
  - OpenMPTCProuter platform: x86_64
  - Country: FR

IPV6 is disabled on wan1 (orange), but I can't disable it on wan2 (starlink). IPV6 is disabled on the OMR router.

I also had to disable ping check on gateways because it keep saying unable to get answer from gateway. (sometimes on wan1, and sometimes on wan2) (my router is very slow, i only use it for testing purpose, so I assume this is the cause :D)

**Comment by Ysurac** [comment]
You use macvlan or vlan ? If not it's the problem.

**Comment by Dragonox77** [comment]
Thank you!
I can activate back the ping to the gateways, and it show no error, plus, WAN addresses are correct.
