### ISSUE TITLE
changing Shadowsocks encryption method everything time I change Wizard page. 

### ISSUE THREAD

**Issue by dnwk** [Ysurac/openmptcprouter#316]
Whenever I update anything on Wizard page, it will switch my Shadowsocks encryption method back to Chacha20. I have set encryption method to none. However, it will always be overridden by Wizard page. 

## Specifications

  - OpenMPTCProuter version:  v0.45.10 r0+9007-529c95cc15
  - OpenMPTCProuter VPS version: 0.88
  - OpenMPTCProuter platform: Linksys WRT32X

**Comment by Ysurac** [comment]
Fixed in latest release.

**Comment by dnwk** [comment]
When I upgrade to newer version of firmware, eventhough I check saved configuration, the encryption method still revert back to chacha20
