### ISSUE TITLE
Full speed of switch LAG not recognized by OMR

### ISSUE THREAD

**Issue by misterbond007** [Ysurac/openmptcprouter#3162]
Hi there! I run OMR on a virtual machine on my NAS. I have created two network interfaces in my Virtual Machine Manager on my NAS. The NAS is connected to the switch via a LAG (2 ports, each 1000 MBit/s, so 2000 MBit/s). The Virtual Machine Manager shows, that each created network has the full speed of my LAG (2000 MBit/s). 

In OMR, there are eth0 (VLAN 1), eth1 (VLAN 4) and bond. "bond" has no traffic. It seems that eth0 and eth1 have only 1000 MBit/s each. How can I set the full 2000 MBit/s speed in OMR?

## Specifications

  - OpenMPTCProuter version: 0.59.1-5.4 r0+16594
  - OpenMPTCProuter VPS version: 5.4.207-mptcp 0.1028
  - OpenMPTCProuter VPS provider: netcup
  - OpenMPTCProuter platform: Virtual machine on NAS

**Comment by Ysurac** [comment]
You can check via SSH on the router with ```ethtool``` the Speed configuration and available mode of an interface.

**Comment by misterbond007** [comment]
I receive the following information with ethtool eth0:
Settings for eth0:
Supported ports: [ ]
Supported link modes: Not reported
Supported pause frame use: No
Supports auto-negotiation: No
Supported FEC modes: Not reported
Advertised link modes: Not reported
Advertised pause frame use: No
Advertised auto-negotiation: No
Advertised FEC modes: Not reported
Speed: Unknown!
Duplex: Unknown! (255)
Port: Other
PHYAD: 0
Transceiver. internal
Auto-negotiation: off
Link detected: yes

**Comment by Ysurac** [comment]
You can check using ```dmesg``` command or "Status->Kernel log" that NICs are correctly detected with some drivers.

**Comment by misterbond007** [comment]
I only find one row with NIC: [    0.439268] VMware vmxnet3 virtual NIC driver - version 1.4.17.0-k-NAPI
The Kernel log is enclosed:
[kernellog.txt](https://github.com/Ysurac/openmptcprouter/files/14336907/kernellog.txt)
