### ISSUE TITLE
Pihold Install Fail

### ISSUE THREAD

**Issue by Mathiasb007** [Ysurac/openmptcprouter#3164]
## Steps to Reproduce the Problem

wget -O - http://www.openmptcprouter.com/server/omr-pihole.sh | sh

## Specifications

  - OpenMPTCProuter version: v.0.60beta1-5.4r0+16862-170d9e447d
  - OpenMPTCProuter VPS version: Version0.1029-test5.4.20-mptcp
  - OpenMPTCProuter VPS provider: Hertzner
  - OpenMPTCProuter platform: x86_64
  - Country: Germany

Run Pi-hole install script...

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [i] SELinux not detected
  [✓] Update local cache of available packages

  [✓] Checking apt-get for upgraded packages... 1 updates available
  [i] It is recommended to update your OS after installing the Pi-hole!

  [i] Checking for / installing Required dependencies for OS Check...
  [✓] Checking for grep
  [i] Checking for dnsutils (will be installed)
  [i] Waiting for package manager to finish (up to 30 seconds)
  [i] Processing apt-get install(s) for: dnsutils, please wait...
----------------------------------------------------------------------
E: Unable to correct problems, you have held broken packages.
Done
-------------------------------------------------------------------------------------------------------------------------------
OMR Pi-hole configuration...
sh: 35: cannot create /etc/pihole/setupVars.new.conf: Directory nonexistent
mv: cannot stat '/etc/pihole/setupVars.new.conf': No such file or directory
sh: 37: cannot create /etc/pihole/setupVars.conf: Directory nonexistent
Failed to restart pihole-FTL.service: Unit pihole-FTL.service not found.
Done
======================================================================================================================================
To use Pi-hole in OpenMPTCProuter, you need to 'Save & Apply' the wizard again in System->OpenMPTCProuter then reboot OpenMPTCProuter.
Web interface will be available on 10.255.255.1 if you use Glorytun TCP, 10.255.254.1 if you use Glorytun UDP.
======================================================================================================================================

**Comment by Ysurac** [comment]
This seems to be a problem in Pi-hole script. I checked and worked for me on Debian 12.
Can you try to launch it again ?
What is your Debian version ?
