### ISSUE TITLE
Add new VPS provider to wiki

### ISSUE THREAD

**Issue by darkman1983** [Ysurac/openmptcprouter#3165]
Hi, i found another VPS provider, which could be worth adding to wiki for Germany.
10 Gbits (shared) Port guaranteed 1 Gbits. Many other only advertise 1 Gbits, but you get like guaranteed 800 Mbits or lower.

Traffic for this one is unlimited.

https://ht-hosting.de/

Servers hosted in Frankfurt or Düsseldorf.

Greetings
Dark

**Comment by Ysurac** [comment]
Thanks, added to the list.
