### ISSUE TITLE
How to install NextCloud on OMR?

### ISSUE THREAD

**Issue by GermanAizek** [Ysurac/openmptcprouter#3167]
@Ysurac, sorry for spam issues.
Are repositories openwrt and `opkg install` command available?

**Comment by Ysurac** [comment]
It's not a good idea, OpenMPTCProuter is a router only.
If you really want that (you shouldn't), you can check OpenWRT for NextCloud install under OpenWRT, but there is no packages so OMR updates will not be easy with that. You can also use docker for that but this may make problems with routes part.

**Comment by GermanAizek** [comment]
I have a very powerful OMR configuration, it should not interfere. Do I understand correctly that it is desirable to have OMR as virtual machine?

**Comment by Ysurac** [comment]
You can put OMR in a VM (not a Docker container)
