### ISSUE TITLE
VPN down / OMR error

### ISSUE THREAD

**Issue by trassiorf** [Ysurac/openmptcprouter#317]
VPN tunnel down since 0.45.10
I can't stat Glorytun manually 

this is logs of system :
Mon Jan 14 09:02:59 2019 daemon.err omr-tracker-ss[12726]: Failed to establish connection
Mon Jan 14 09:03:13 2019 daemon.err omr-tracker-ss[12726]: Failed to establish connection
Mon Jan 14 09:03:26 2019 daemon.err omr-tracker-ss[12726]: Failed to establish connection
Mon Jan 14 09:03:40 2019 daemon.err omr-tracker-ss[12726]: Failed to establish connection
Mon Jan 14 09:03:54 2019 daemon.err omr-tracker-ss[12726]: Failed to establish connection
Mon Jan 14 09:04:07 2019 daemon.err omr-tracker-ss[12726]: Failed to establish connection
Mon Jan 14 09:04:21 2019 daemon.err omr-tracker-ss[12726]: Failed to establish connection
Mon Jan 14 09:04:34 2019 daemon.err omr-tracker-ss[12726]: Failed to establish connection

## Specifications

  - OpenMPTCProuter version: (Last is not a version) 0.45.10
  - OpenMPTCProuter VPS version: (Last is not a version) 0.88
  - OpenMPTCProuter platform: (RPI2/RPI3/x86/x86_64) RPI3B+
![capture d ecran](https://user-images.githubusercontent.com/10478846/51101685-e3e19800-17db-11e9-9ceb-1b447024fc4f.png)

**Comment by Ysurac** [comment]
Error ``` omr-tracker-ss[12726]: Failed to establish connection``` will be fixed in next version.
What is the VPN used ? (Glorytun TCP, Glorytun UDP, OpenVPN or MLVPN ?)

**Comment by trassiorf** [comment]
Solve my problem new flash without "keep settings" 
![capture d ecran-11](https://user-images.githubusercontent.com/10478846/51130181-b83ace00-182c-11e9-8ebb-68d4459f8dcb.png)

**Comment by trassiorf** [comment]
idem on version 0.45.10
![capture d ecran-12](https://user-images.githubusercontent.com/10478846/51130533-79f1de80-182d-11e9-84b3-9c9915046dea.png)

**Comment by trassiorf** [comment]
ok on Scaleway VPS also
![capture d ecran-13](https://user-images.githubusercontent.com/10478846/51131035-d30e4200-182e-11e9-9211-2e2e4f2c1f04.png)
