### ISSUE TITLE
Local routing - Cannot connect from wan1 or wan2 subnet to lan 

### ISSUE THREAD

**Issue by murateri75** [Ysurac/openmptcprouter#3175]
## Expected Behavior

Connect from one device within wan1 or wan2 (other than routers) to lan devices 
Ex : Synology with Surveillance station on wan1, cameras on lan (behind OpenMPTCP router) with ONVIF protocol (port 80)

## Current Behavior

Impossible to connect to IP Camera on lan from Synology on wan1 subnet

## Specifications

  - OpenMPTCProuter version:  openmptcprouter v0.59.1-5.4 r0+16594-ce92de8c8c
  - OpenMPTCProuter VPS version:  5.4.207-mptcp 0.1028
  - OpenMPTCProuter VPS provider: private
  - OpenMPTCProuter platform:  Raspberry Pi 4 Model B Rev 1.4

**Comment by murateri75** [comment]
I tried Port Forwarding in Firewall but without success

**Comment by Ysurac** [comment]
It's blocked by firewall. In anycase it's not a good idea.

**Comment by murateri75** [comment]
That was my assumption
So I need to move my Synology on the router lan correct ?

**Comment by murateri75** [comment]
I mean should be only routers on wan1 and wan2

**Comment by Ysurac** [comment]
On WAN* you should only have routers/modems/box.

**Comment by murateri75** [comment]
Understood
