### ISSUE TITLE
How to use Snowflake or Meek-Azure obfuscation technique instead obfs4 in OMR?

### ISSUE THREAD

**Issue by GermanAizek** [Ysurac/openmptcprouter#3177]
Among method choices was only obfs4, I have all its obfs4 bridges blocked by ISP provider. Snowflake and meek-azure is more hidden from DPI.

**Comment by GermanAizek** [comment]
@Ysurac, it should be configured in the same way as in openwrt?
https://forum.turris.cz/t/how-to-install-snowflake/18412/2

**Comment by Ysurac** [comment]
Yes, but it also needs to be patched to support MPTCP if it's no already supported.
