### ISSUE TITLE
OMR Weblate there is no way to register and login

### ISSUE THREAD

**Issue by GermanAizek** [Ysurac/openmptcprouter#3179]
@Ysurac,
There is no email in spam and inbox, it is not possible to register and login.

![image](https://github.com/Ysurac/openmptcprouter/assets/21138600/303f67d8-42e8-4ef6-abd1-e14c0dd17a92)

After trying to send request in contact form "500 error code"

![image](https://github.com/Ysurac/openmptcprouter/assets/21138600/f854997a-0132-40bd-afd5-2c929c1810b6)

**Comment by Ysurac** [comment]
I update weblate and fixed this problem.
