### ISSUE TITLE
Replace Simple-OBFS by Shadowsocks V2-Ray plugin

### ISSUE THREAD

**Issue by Ysurac** [Ysurac/openmptcprouter#318]
simple-OBFS is deprecated.
Use https://github.com/shadowsocks/v2ray-plugin instead.
Need to create packages, modify ShadowSocks interface and add support in VPS script.

**Comment by Vinc32du44** [comment]
Good news :-D
When will it be aproximately available ?

**Comment by Ysurac** [comment]
This will be difficult : I need to get v2ray compiling, and this need golang protobuf and golang go genproto. For now I have a circular dependency... I need to find how to make a working OpenWrt package from source.

**Comment by Ysurac** [comment]
For now, binary distribution of v2ray will be used.
So v2ray will be available on supported platform in next release (0.46).

**Comment by Vinc32du44** [comment]
v2ray plugin Ok but with this parameter activated i got "Can't get public IP adress from ShadowSocks" error on VPS.
I update both VPS and MPTCP ...
Do you have a suggest ;)
Thanks

**Comment by Ysurac** [comment]
VPS is updated and rebooted to latest version ?

**Comment by Vinc32du44** [comment]
Yes rebooted but not after activate v2ray Obfuscating option.
I'll try to reboot the VPS ;)

**Comment by Vinc32du44** [comment]
After reboot all is GooD :))) but always no IPV6.
All work fine ! Thanks Ycarus

**Comment by Ysurac** [comment]
Yes there is a bug in setting page that enable IPv6, this will be fixed in next release tomorrow.
