### ISSUE TITLE
rp-pppoe-server package not working

### ISSUE THREAD

**Issue by fhocorp** [Ysurac/openmptcprouter#3182]
## Current Behavior
The  PPPoE server not starting (no process found in process list) and following errors found in system logs : 

`invalid sysfs path read for net/ppp0
couldn't handle kernel event: device net/ppp0 not found`

## Steps to Reproduce the Problem

  1. Update the packages lists on openwrt
  2. install the package rp-pppoe-server package
  3. Setup the server following openwrt guide at : https://openwrt.org/user/ahorner/pppoe_server_guide
  4. Starting the server

## Context (Environment)
Using Roaring Pinguin PPPoe Server Package for creating a PPPoe server for specific LANs clients
Trying to use my openmtcp router as a backbone router and using my broadband router as client using PPPoE over VLAN 835

## Specifications

  - OpenMPTCProuter version: v0.59.1
  - OpenMPTCProuter VPS version:  v0.59.1
  - OpenMPTCProuter VPS provider: None
  - OpenMPTCProuter platform: x86_64
  - Country: France

Any help should be appreciated. At your disposal for further informations if required

**Comment by Ysurac** [comment]
Sorry but I never used rp-pppoe-server so I have no idea.
