### ISSUE TITLE
SQM QoS

### ISSUE THREAD

**Issue by Yessine1200** [Ysurac/openmptcprouter#3188]
Hello,
I want to understand exactly how to use SQM to improve QoS. In the wizard, there are two boxes: one to enable SQM and the other for SQM autorate. 
1. For the first one, do I need to modify the DL/UL traffic for the links I want to aggregate to avoid link saturation? 
2. For the tunnel created to aggregate the throughput, what values should I set? 
3. How can I prioritize UDP traffic?
<img width="662" alt="Capture d’écran 2024-03-01 à 10 00 27" src="https://github.com/Ysurac/openmptcprouter/assets/73882523/c9c57a71-a7bf-436e-a353-3395f5df00a4">

**Comment by Yessine1200** [comment]
I see in the documentation you sent: SQM is an integrated system that performs per-packet/per flow network scheduling, active queue length management (AQM), traffic shaping/rate limiting, and QoS (prioritization). If that true I can prioritize ? or I have to install other tool to do that ?

**Comment by Ysurac** [comment]
You can use DSCP for priority or install luci-app-qos instead of SQM.

**Comment by Yessine1200** [comment]
For example, If I priorise UDP trafic for video diffusion using DSCP: how OMR will react ? The traffic will be send over the link with lower latency ? and OMR will use openVPN(I mean the tunnel created between OMR and VPS) to send the trafic to the server (I am using v6.0beta2)?

**Comment by Yessine1200** [comment]
If I use SQM Autorate, OMR utilizes the defined algorithm to automatically detect the maximum/minimum speed based on latency and congestion, especially for mobile networks. My question is: Does SQM Autorate calculate the maximum speed periodically? Because, as you know, mobile networks are not stable in terms of latency and speed.
