### ISSUE TITLE
0.60beta2-6.1 now = Release Candidate?

### ISSUE THREAD

**Issue by winkmichael** [Ysurac/openmptcprouter#3189]
Hello Yannick,

Is the beta2 the now also the RC? https://download.openmptcprouter.com/release/v0.60beta2-6.1/ Or is there another link?

Thanks
Mike

**Comment by Ysurac** [comment]
I was updating the issue: https://github.com/Ysurac/openmptcprouter/issues/2961

**Comment by winkmichael** [comment]
Thanks, I'll install tonight.
