### ISSUE TITLE
DNS problem

### ISSUE THREAD

**Issue by renaudadu** [Ysurac/openmptcprouter#319]
hello,
i have a DNS problem
i use the openMPTCPROUTER DNS service and i have some resolving problem.
for some site it's working and other not.
i try with 1.1.1.1 or 8.8.8.8 dns it's working.
ss-redir for UDP : is unset.

where can i see where is the problem

## Specifications

  - OpenMPTCProuter version: (0.45.10)
  - OpenMPTCProuter VPS version: (0.88)
  - OpenMPTCProuter platform: (RPI3)

**Comment by Ysurac** [comment]
The VPN is working ?
You need also to have no DNS server defined for each WAN.

**Comment by renaudadu** [comment]
vpn is running
and no dns on each wan.

it's possble to forward dns request to google dns for example ?
if it's  possible omr bypass working ?

**Comment by Ysurac** [comment]
Yes in *Network->DHCP & DNS* and *DNS forwardings*
But some public DNS are used by OMR-Tracker to test if a WAN is up or down, this can cause some conflict in some cases.

**Comment by renaudadu** [comment]
ok thank.
i modify omr-tracker and i forward to my dns.
