### ISSUE TITLE
Display link parameter on OLED for raspberry pi 

### ISSUE THREAD

**Issue by R-sajadi** [Ysurac/openmptcprouter#3193]
## Expected Behavior

Display link parameter on OLED for raspberry pi  such as 
usb modem connected ? 
SIM Card inserted?
connect to the server?
bandwidth of each link?
Signal strength USB Modem?
## Current Behavior

Display in the web interface
## Specifications

  - OpenMPTCProuter version: 
 v0.59.1-5.4
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter VPS provider:
  Personal server Ubuntu on PC X86
  - OpenMPTCProuter platform: 
  RPI4

**Comment by Ysurac** [comment]
You need to do it yourself, it's not supported by OpenMPTCProuter for now (and would not be easy to make something generic...).

**Comment by fdyf520** [comment]
目前我已经实现该效果，需要可以联系，QQ480398986 联系
