### ISSUE TITLE
[offtop] Simple script build custom kernel like Openwrt build.sh, but for regular Debian

### ISSUE THREAD

**Issue by GermanAizek** [Ysurac/openmptcprouter#3196]
@Ysurac hi. Can you tell me if there is ready-made script that builds custom kernel like yours `build.sh` but only for regular Debian distr x86_64, you have convenient choice packages and firmware from Openwrt.

Example scripts:
https://github.com/Ysurac/openmptcprouter/blob/develop/build.sh
https://github.com/arvin-foroutan/build-ubuntu-kernel

**Comment by Ysurac** [comment]
No idea, I always patched/compiled my Debian kernel manually.
