### ISSUE TITLE
Public IPs from Cloud provider routed to cisco router

### ISSUE THREAD

**Issue by zee-shany** [Ysurac/openmptcprouter#3198]
hello,

Thanks for this great project and enhancment.

I'd like to check if its possible to route a /30 public IP block and /29 public IP block to a Router device after the OpenMPTCP router as shown in diagram below? assuming i'm able to get the /30 and /29 block of IPs from AWS.

![image](https://github.com/Ysurac/openmptcprouter/assets/52835954/2b13d76a-7768-452b-b080-c7a263814df0)

Thanks in advance for your response.

**Comment by ccmks** [comment]
I believe by default, OMR is using NAT mode. Where did you get the IP address from?

**Comment by Ysurac** [comment]
You should be able to use a GRE tunnel for the full subnet.
Or, easier, set all /29 IPs on the VPS on the same interface, then you can with Shadowsocks-libev and the GRE tunnels that are automatically created use them: https://github.com/Ysurac/openmptcprouter/wiki/VPS-Multi-IPs
