### ISSUE TITLE
Can't get public IP from ShadowSocks Rust

### ISSUE THREAD

**Issue by GermanAizek** [Ysurac/openmptcprouter#3202]
![Screenshot_20240310-214643_Mull](https://github.com/Ysurac/openmptcprouter/assets/21138600/79538ee5-f877-48f0-8542-a99a94b22580)

@Ysurac, I try similar issue, but not found. I hope I'm not making duplicate.

**Comment by Ysurac** [comment]
Please use the template.

**Comment by GermanAizek** [comment]
I recheck, but again. I enabled all local instances.
![Screenshot_20240310-222004_Mull](https://github.com/Ysurac/openmptcprouter/assets/21138600/fc874839-f470-498c-8cd5-2ba7a97cee4c)
![Screenshot_20240310-221835_Mull](https://github.com/Ysurac/openmptcprouter/assets/21138600/4a5f62e0-3e4b-4aef-bfcd-dd6ef0ee9b7d)
![Screenshot_20240310-221856_Mull](https://github.com/Ysurac/openmptcprouter/assets/21138600/9f8a024a-261c-46c1-82d2-c73b793f3d91)
![Screenshot_20240310-221920_Mull](https://github.com/Ysurac/openmptcprouter/assets/21138600/33e3f994-cc76-4db4-bced-4ed4acd66037)

**Comment by GermanAizek** [comment]
@Ysurac, is it possible to get technical journal service? something like `systemctl status shadowsocks-rust`
I setup everything as it was written in Wiki->[Minimum configuration](https://github.com/Ysurac/openmptcprouter/wiki/OpenMPTCProuter-configuration)

**Comment by mvmaksnet** [comment]
I have the same problem but on version:
  - OpenMPTCProuter version: OpenMPTCProuter v0.62
  - OpenMPTCProuter VPS version: 0.1032-test 6.12.15-x64v3-xanmod1
  - OpenMPTCProuter VPS provider: Maksnet
  - OpenMPTCProuter platform:  x86_64

What can be problem?

**Comment by Ysurac** [comment]
The version 0.62 is not available. Only v0.62rc1.
This issue is closed, open a new issue with a screenshot of status page.

**Comment by mvmaksnet** [comment]
I have made new issue ticket. Thanks.
