### ISSUE TITLE
Irregular Timeout

### ISSUE THREAD

**Issue by vinc32** [Ysurac/openmptcprouter#3203]
## Expected Behavior
Connection without Timeouts

## Current Behavior
Timeouts irregular (5-6 each Hour), Kernel & System Log are Empty (nothing new when issue comes)
Websites are not reachable anymore for 10-30 Seconds

## Specifications

  - OpenMPTCProuter version: v0.59.1
  - OpenMPTCProuter VPS version: 0.1028 5.4.207-mptcp
  - OpenMPTCProuter VPS provider: IONOS
  - OpenMPTCProuter platform: x86_64 -> ESXi 8, 2vCPU@3.00Ghz, 16GB RAM

## Ping Test google when failure

64 bytes from 142.250.185.99: icmp_seq=693 ttl=54 time=258.716 ms
64 bytes from 142.250.185.99: icmp_seq=694 ttl=54 time=46.216 ms
64 bytes from 142.250.185.99: icmp_seq=695 ttl=54 time=587.149 ms
Request timeout for icmp_seq 696
Request timeout for icmp_seq 697
Request timeout for icmp_seq 698
64 bytes from 142.250.185.99: icmp_seq=696 ttl=54 time=3048.016 ms
Request timeout for icmp_seq 700
Request timeout for icmp_seq 701
Request timeout for icmp_seq 702
64 bytes from 142.250.185.99: icmp_seq=697 ttl=54 time=6427.730 ms
64 bytes from 142.250.185.99: icmp_seq=698 ttl=54 time=5430.873 ms
64 bytes from 142.250.185.99: icmp_seq=699 ttl=54 time=4500.621 ms
64 bytes from 142.250.185.99: icmp_seq=700 ttl=54 time=3508.464 ms
64 bytes from 142.250.185.99: icmp_seq=701 ttl=54 time=3875.157 ms
64 bytes from 142.250.185.99: icmp_seq=702 ttl=54 time=2892.521 ms
64 bytes from 142.250.185.99: icmp_seq=703 ttl=54 time=2011.181 ms
64 bytes from 142.250.185.99: icmp_seq=704 ttl=54 time=1089.646 ms
64 bytes from 142.250.185.99: icmp_seq=705 ttl=54 time=288.934 ms
64 bytes from 142.250.185.99: icmp_seq=706 ttl=54 time=28.604 ms

## Ping Test Client from L->R Google, OMR, USG, ESXi
<img width="2189" alt="Bildschirmfoto 2024-03-11 um 14 27 19" src="https://github.com/Ysurac/openmptcprouter/assets/3858416/331ed5cf-aab8-4815-98af-ccd811c18ef4">

## Config Overview (ignore Starlink, not Attached currently)
<img width="1086" alt="Bildschirmfoto 2024-03-11 um 13 23 07" src="https://github.com/Ysurac/openmptcprouter/assets/3858416/9c3e7005-652b-4da3-92a9-fdcd2fd039d2">

**Comment by vinc32** [comment]
<img width="1690" alt="Bildschirmfoto 2024-03-11 um 20 25 23" src="https://github.com/Ysurac/openmptcprouter/assets/3858416/8c106900-9ba2-48e7-99cb-805b95e01f40">

**Comment by vinc32** [comment]
![WhatsApp Image 2024-03-11 at 20 27 54](https://github.com/Ysurac/openmptcprouter/assets/3858416/aaf1d80e-d742-4bd3-9348-91e92c97f784)

attached

**Comment by Ysurac** [comment]
pppoe-wan1 is a DSL line ? why so much latency sometimes ? You have same if you ping for example 1.1.1.1 with the same ping command?
(When you ping without binding to an interface this use the VPN and may not reflect any real latency, can be better with another VPN but doesn't change anything for TCP traffic)

**Comment by vinc32** [comment]
pppoe-wan1 = vDSL from Telekom -> I'm living in absolutely nowhere - so that's the issue and ping normal.

Client -> OMR pppoe -> OMR eth2 -> OMR tun0
<img width="2201" alt="Bildschirmfoto 2024-03-11 um 20 46 17" src="https://github.com/Ysurac/openmptcprouter/assets/3858416/f7ca1acc-e6af-4726-a8c1-e7fec8dfae0c">

**Comment by Ysurac** [comment]
In any case DSL line should have a stable latency, even with a very bad line (I'm also living absolutely nowhere where vDSL wasn't possible due to line distance...). You seem to lose some packets between your connections and IONOS, this doesn't help.
You can increase the "Multipath TCP SYN retries" and change the TCP Congestion control to Cubic in Network->MPTCP

**Comment by vinc32** [comment]
SYN Retries increased a little, TCP Congestion Control is default in Cubic. Do you mean any other option?

**Comment by vinc32** [comment]
just one thing I've noticed... lots of this messages appear

Tue Mar 12 00:05:56 2024 kern.info kernel: [44125.939797] TCP: too many orphaned sockets
Tue Mar 12 00:06:12 2024 kern.info kernel: [44141.311107] TCP: too many orphaned sockets
Tue Mar 12 00:06:17 2024 kern.info kernel: [44146.417976] TCP: too many orphaned sockets
Tue Mar 12 00:06:22 2024 kern.info kernel: [44151.538606] TCP: too many orphaned sockets
Tue Mar 12 00:06:22 2024 kern.info kernel: [44151.538802] TCP: too many orphaned sockets
Tue Mar 12 00:06:22 2024 kern.info kernel: [44151.539105] TCP: too many orphaned sockets
Tue Mar 12 00:06:22 2024 kern.info kernel: [44151.539797] TCP: too many orphaned sockets

**Comment by vinc32** [comment]
Seems to work now - changed to separate nics for dsl, 5g, star link and changed lan port to E1000 from vmnext.

Thank you for your help :) will donate something next quarter :) 

![image](https://github.com/Ysurac/openmptcprouter/assets/3858416/3feeabf9-1963-42c3-86f3-583899225b0a)
