### ISSUE TITLE
OMR Congestion Detection Mechanisms

### ISSUE THREAD

**Issue by YB1200** [Ysurac/openmptcprouter#3208]
How does OMR handle congestion detection on network links? Does OMR monitor the counters if UDP flows are passing through, and does it analyze retransmissions if TCP flows are passing through? Would this method be sufficient for determining link congestion, and if so, could you explain how OMR implements this process?

**Comment by Ysurac** [comment]
With TCP Congestion Protocols and Smart Queue Management (SQM) for mitigating bufferbloat.
