### ISSUE TITLE
StarLink compatibility ?

### ISSUE THREAD

**Issue by JeedHome44** [Ysurac/openmptcprouter#3212]
Hello,

Can we add Starlink IP 192.168.1.1  in OMR to add it with ethernet adaptator and bypass mode ?

Thank you

**Comment by vinc32** [comment]
Yes, but no need to add the ip. just let it as DHCP.

**Comment by JeedHome44** [comment]
> Yes, but no need to add the ip. just let it as DHCP.

I manage DHCP with OMR.

I don't want StarLink to do DHCP. that's why I want to put it in by-pass mode

Il faut donc bien mettre l'IP du routeur StarLink sur OMR pour le mettre en MacVLan !?

**Comment by JeedHome44** [comment]
@Ysurac 

Hello,

I have a bypass mode in my StarLink routeur.

Can I only change the IP of OMR to 192.168.101.1 for example and leave all devices in 192.168.100.X ?

There will only be OMR in DHCP on the LAN since StarLink will be in bypass !

And like that, 192.168.100.1 will be for the StarLink web interface ! is it ok like that ?

**Comment by JeedHome44** [comment]
![image](https://github.com/Ysurac/openmptcprouter/assets/41892950/aada35be-05b7-4006-8762-30e51ebf6811)

**Comment by vinc32** [comment]
You just need to let the WAN Interface for Starlink in DHCP, the interface will get a Public or DNAT IP (depending on contract) and you're fine.
OMR still acting as DHCP for Clients.

**Comment by Ysurac** [comment]
If you have as a router something with different ethernet card yes, you dedicate one for starlink, it's easy. The problem is more when you use a Raspberry or anything with only one port.

**Comment by JeedHome44** [comment]
> You just need to let the WAN Interface for Starlink in DHCP, the interface will get a Public or DNAT IP (depending on contract) and you're fine.
> 
> OMR still acting as DHCP for Clients.

we cannot leave 2 DHCPs on a single LAN !

I ordered a StarLink ethernet adapter. it will therefore be on the same LAN as the Raspberry OMR.

I just want to know if I can keep all my devices in 192.168.100.X and just change the Raspberry OMR to 192.168.101.1 for example so as not to conflict with the Starlink web interface which is necessarily in 192.168.100.1

**Comment by JeedHome44** [comment]
> If you have as a router something with different ethernet card yes, you dedicate one for starlink, it's easy. The problem is more when you use a Raspberry or anything with only one port.
> 
> 

I only have a Raspberry Pi 4B with OMR which manages all the DHCP in the house

**Comment by dfadev** [comment]
![image](https://github.com/Ysurac/openmptcprouter/assets/17075651/9b0a8787-14c2-42c3-b9eb-393a4670a508)

![image](https://github.com/Ysurac/openmptcprouter/assets/17075651/b866b06e-50b1-4471-b796-55303a4d906b)
![image](https://github.com/Ysurac/openmptcprouter/assets/17075651/75738287-7a0d-4baf-9cb9-03122d4a0bb9)

![image](https://github.com/Ysurac/openmptcprouter/assets/17075651/59776c25-f498-4904-85f8-243dc93446e0)

Static IP with Starlink works in non-bypass "normal" mode.  OMR can service everything through one NIC and devices can be on the same unmanaged switch as long as you use different IP networks and have only one DHCP server.  In my setup the OMR DHCP server serves addresses to clients connecting to the wifi AP.

**Comment by JeedHome44** [comment]
I have difficulty understanding English.

I just want to know if I can keep the IP 192.168.100.1 for OMR if I put StarLink on bypass!

It's going to take me a long time to change all the fixed IPs on my DHCP and especially on Jeedom and Home Assistant with all the devices!

So it would be much simpler to put the StarLink on bypass and put it in MacVLan on OMR?

**Comment by dfadev** [comment]
I think the problem will be your devices will broadcast a DHCP request and both OMR and Starlink will try to answer.  You will need a managed switch with VLAN tagging to control which DHCP server replies.

**Comment by JeedHome44** [comment]
in by-pass mode, StarLink no longer does DHCP!

**Comment by dfadev** [comment]
How else would you get an address?

**Comment by JeedHome44** [comment]
I don't understand ! my 4G router has its DHCP disabled and is on the same LAN as my Free box which also has its DHCP disabled and I manage to have both by pointing the MacVLan to their respective IP!

It’s OMR that does the DHCP for my entire LAN network!

**Comment by dfadev** [comment]
https://www.reddit.com/r/Starlink/comments/158qlzp/using_your_own_router_with_starlink_bypass_mode/

you will need a managed switch.

**Comment by JeedHome44** [comment]
I ordered the Starlink ethernet adapter to have an ethernet port 😉

**Comment by JeedHome44** [comment]
I think I understood ! I need to get a router to put StarLink in by-pass mode on it, deactivate DHCP and make a routing rule so I don't have to change the OMR IP but still have access to the interface StarLink web. Is it possible like that?
