### ISSUE TITLE
opkg update error in RC1

### ISSUE THREAD

**Issue by patimages** [Ysurac/openmptcprouter#3213]
Hi, 
on OMR 0.60RC1, opkg update leads to an error : 

```
Package kmod-natsemi version 5.4.238-1 has no valid architecture, ignoring.
Downloading https://packages.openmptcprouter.com/v0.60rc1-5.4/x86_64/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_luci
Downloading https://packages.openmptcprouter.com/v0.60rc1-5.4/x86_64/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_packages
Downloading https://packages.openmptcprouter.com/v0.60rc1-5.4/x86_64/base/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_base
Downloading https://packages.openmptcprouter.com/v0.60rc1-5.4/x86_64/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_routing
Downloading https://packages.openmptcprouter.com/v0.60rc1-5.4/x86_64/telephony/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_telephony
Downloading https://download.openmptcprouter.com/release/v0.60rc1-5.4/x86_64/targets/x86/64/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openmptcprouter_core
Downloading https://download.openmptcprouter.com/release/v0.60rc1-5.4/x86_64/packages/x86_64/base/Packages.gz
Updated list of available packages in /var/opkg-lists/openmptcprouter_base
Downloading https://download.openmptcprouter.com/release/v0.60rc1-5.4/x86_64/packages/x86_64/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/openmptcprouter_luci
Downloading https://download.openmptcprouter.com/release/v0.60rc1-5.4/x86_64/packages/x86_64/openmptcprouter/Packages.gz
Updated list of available packages in /var/opkg-lists/openmptcprouter_openmptcprouter
Downloading https://download.openmptcprouter.com/release/v0.60rc1-5.4/x86_64/packages/x86_64/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openmptcprouter_packages
Collected errors:
 * parse_from_stream_nomalloc: Missing new line character at end of file!
 * parse_from_stream_nomalloc: Missing new line character at end of file!
 * parse_from_stream_nomalloc: Missing new line character at end of file!
```

Looks as if the package in the first line (kmod-natsemi) as an issue and this prevent the updating process. 

Thanks !

**Comment by Ysurac** [comment]
List are updated. You installed kmod-natsemi yourself ?

**Comment by Ysurac** [comment]
dmidecode is already installed on x86/x86_64. There is also hwinfo installed by default and give some nice results.

**Comment by Ysurac** [comment]
For now, kernel modules packages can give errors because it's not yet a real release and they can be compiled for another image compilation.
For the luci problem, you shouldn't have this. Each time I had this problem was due to a corrupted image/disk or imported backup.

**Comment by patimages** [comment]
Understood, no problem.
Would you advise me to reinstall OMR clean and refill the proper info from scratch rather than using a backup of the settings that has been incremented during years of use (I am one of you "fidèles" ;-D) ?

**Comment by Ysurac** [comment]
Sometimes it's better to restart from clean install, mostly due to some configuration customization changes.
But if it's working, keep it for now and wait for the 0.60 final release.

**Comment by patimages** [comment]
Fair point : it does a fantastic job for now so I ll wait for the final version to reinstall a clean version. Merci encore !

**Comment by patimages** [comment]
Hi, 
FYI : brand new install of the router (openmptcprouter v0.60rc1-5.4 r0+16862-170d9 - VPS : 1029-test), clean, settings entered manually. Going to "status ->realtime graphs->connections" lead to error "/usr/lib/lua/luci/dispatcher.lua:427: /etc/config/luci seems to be corrupt, unable to find section 'main'". Highly reproducible on two different NUC.

**Comment by Ysurac** [comment]
This happen just after boot ? after being logged a long time ? What do you have in your browser developper tools in the console tab ?

**Comment by patimages** [comment]
No : anytime I go to "connections". Here is the console log. 
<img width="1703" alt="image" src="https://github.com/Ysurac/openmptcprouter/assets/6791434/e9acad8a-3ab8-49dd-ac68-f0b230bb22ac">

**Comment by Ysurac** [comment]
I'm not able to reproduce the issue.
How many active connections do you have in Status->Overview ?

**Comment by patimages** [comment]
Shoot ... It occurred on 2 different NUC (an old and a brand new one). I could give you access remotely if you wish. 
Here is the requested info : 
<img width="1140" alt="image" src="https://github.com/Ysurac/openmptcprouter/assets/6791434/06c4ec3a-0677-49f2-ad0b-fd78c4f1094d">

**Comment by Ysurac** [comment]
18337 active connections. I think it's the problem: too many data to display on this page.

**Comment by patimages** [comment]
Where does this come from ??? I have 20 connected items ... Did not happen in the 0.59 version (same setup).

**Comment by Ysurac** [comment]
It's a lot of active connections. No change have been made on this part.
This seems to be a timeout. You can try to increase some in Services->uHTTPd, advanced settings tab.

**Comment by patimages** [comment]
This is indeed a lot for a couple of laptops, few tablets and some IOTs (21 connected objects, half being closed at this time)... Any way for me to check what is going on ? Am I under attack ;-D ? 
Thanks a lot for your time and help !

**Comment by Ysurac** [comment]
You can check with ```conntrack -L``` for example that all connection are legit.

**Comment by patimages** [comment]
It indicates 492 lines most of these related to my orbi router ... kind of : 
`17 146 src=192.168.100.108 dst=192.168.100.1 sport=47300 dport=53 packets=3 bytes=192 src=192.168.100.1 dst=192.168.100.108 sport=53 dport=47300 packets=3 bytes=289 [ASSURED] mark=0 use=1` 
Could this explain the 20k connexions ?

**Comment by patimages** [comment]
A complete reset of my orbi router fixed the issue. A big big thanks for helping me out while the issue was clearly not OMR !!!
