### ISSUE TITLE
Addressing MPTCP Tunnel Challenges: Raspberry Pi to Google Cloud VM Connectivity

### ISSUE THREAD

**Issue by Raquel1L** [Ysurac/openmptcprouter#3216]
## Expected Behavior
I am using OpenMPTCPRouter to create an MPTCP tunnel connecting the gateway (Raspberry Pi) to a Debian 11 Google Cloud VM (with the requested ports open). Connected to the RPI is a computer that sends all packets to it. In this case, I am using two TCP subflows, aggregating WiFi and 5G as shown in the following figure.

![Application](https://github.com/Ysurac/openmptcprouter/assets/102439111/0127df35-6a54-4d26-beb6-d1f2147bc936)

## Current Behavior
In an experiment, testing with just one path, I ran curl -I https://www.example.com in the PC terminal while doing tcpdump, and the capture result was as follows: 

<img width="981" alt="Captura de ecrã 2024-03-19, às 23 31 26" src="https://github.com/Ysurac/openmptcprouter/assets/102439111/0368a797-5acd-4d22-8873-7e5ae6ce8c35">

As you can see in the figure, my problem is that when the Google Cloud VM receives MPTCP packets, it sends a TCP Reset packet (Additionally, aren't all packets sent by RPI supposed to be MPTCP?).

Finally, I leave you with the following figure, which shows the general state of the system.

<img width="1128" alt="Captura de ecrã 2024-03-18, às 10 32 49" src="https://github.com/Ysurac/openmptcprouter/assets/102439111/faa200bb-d369-4071-bc90-7c1c20160292">

## Specifications
  - OpenMPTCProuter version: OpenMPTCProuter v0.60 beta 2
  - OpenMPTCProuter VPS version: 5.10.0-28-cloud-amd64
  - OpenMPTCProuter VPS provider: GCP
  - OpenMPTCProuter platform: RPI4

**Comment by Ysurac** [comment]
Your VPS have a 5.10.0 kernel. It's not supported. You need to install the VPS part. With the 0.59.1 version you are using, this will install a Linux kernel 5.4.

**Comment by Raquel1L** [comment]
Thanks for your quick reply! 

To install the VPS I ran these two commands in the GCP VM terminal:
apt-get update && apt-get upgrade
wget -O - https://www.openmptcprouter.com/server/debian-x86_64.sh | sh

Your suggestion is that I change the debian-x86_64.sh file so that I can install the Linux patched kernel 5.4?

**Comment by Ysurac** [comment]
The correctly executed ? (you get all keys at the end)
You rebooted the VPS after execution ?

**Comment by Raquel1L** [comment]
Yes, after running the second command, I got these keys:

<img width="565" alt="Captura de ecrã 2024-03-20, às 09 42 07" src="https://github.com/Ysurac/openmptcprouter/assets/102439111/208cb77a-d933-4e82-92f3-793f6dc1327c">

Do you think the reboot will change the version problem?

**Comment by Ysurac** [comment]
Reboot is need to use new kernel. If it was not already done, it's the problem.

**Comment by Raquel1L** [comment]
The problem with rebooting the machine is that after doing so I lose the ssh connection to it.
(ssh: connect to host x.x.x.x port 65222: Operation timed out)

**Comment by Ysurac** [comment]
Check that port 65222 is correctly open in GCP firewall.
If it's the case, try to use GCP VM console access.

**Comment by Raquel1L** [comment]
Thank you very much for your help!!!

<img width="692" alt="Captura de ecrã 2024-03-20, às 10 18 35" src="https://github.com/Ysurac/openmptcprouter/assets/102439111/34bdf64a-38f7-4573-8151-c8f701616872">

I'm going to repeat the experiment now and see if everything works!

**Comment by Raquel1L** [comment]
Regarding the server problem, everything has been resolved, thank you. However, the multipath is still not working. The general state of the system is as follows:

<img width="1110" alt="Captura de ecrã 2024-03-20, às 12 10 50" src="https://github.com/Ysurac/openmptcprouter/assets/102439111/d33c35d7-5f18-4470-8a89-866a18749a40">

Do you have any idea what could be causing this?

**Comment by Ysurac** [comment]
A box can block MPTCP or the ISP can block it.
It's often a good idea to try aggregation (so with more than one connection) even if there is the warning.
You can also update to lastest snapshot with 6.1 kernel and check if it's working or not.
If nothing is working, you will have to use MPTCP over VPN checkbox, that use MPTCP over Wireguard.
