### ISSUE TITLE
VPS Install Script Fails at Install "omr-vps-admin".

### ISSUE THREAD

**Issue by chriskinal** [Ysurac/openmptcprouter#3220]
## Expected Behavior
Install script runs to completion and install the OMPTCP VPS server software.
## Current Behavior
Install script fails during Python module install.

## Possible Solution
Not sure.

## Steps to Reproduce the Problem

  1. Create a Debian Linux 11.6 or 12.5 Amazon Lightsail server.
  2. Run VPS install script.

## Context (Environment)
Install script fails with an incorrect version number but I can't version of what?

Created new Lightsail instance with both Debian 11.6 and 12.5. The VPS script fails during Python module install.

## Specifications

  - OpenMPTCProuter version: v0.60RC1 Kernel 5.4
  - OpenMPTCProuter VPS version: Whatever is downloaded by: wget -O - http://www.openmptcprouter.com/server-rc/debian.sh | sh
  - OpenMPTCProuter VPS provider: Amazon
  - OpenMPTCProuter platform: x86_64
  - Country: US

admin@ip-172-26-13-54:~$ sudo su -
root@ip-172-26-13-54:~# wget -O - http://www.openmptcprouter.com/server-rc/debian.sh | sh
--2024-03-23 13:16:17--  http://www.openmptcprouter.com/server-rc/debian.sh
Resolving www.openmptcprouter.com (www.openmptcprouter.com)... 37.19.207.34
Connecting to www.openmptcprouter.com (www.openmptcprouter.com)|37.19.207.34|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 88768 (87K) [application/octet-stream]
Saving to: ‘STDOUT’

-                                       0%[                                                                         ]       0  --.-KB/s               Check user...
Check Linux version...
Check architecture...
Check virtualized environment
Check about broken packages...
Check if OpenMPTCProuter VPS is already installed...
Update mode
Update repo.openmptcprouter.com key
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
--2024-03-23 13:16:17--  https://repo.openmptcprouter.com/openmptcprouter.gpg.key
Resolving repo.openmptcprouter.com (repo.openmptcprouter.com)... 37.19.207.34
Connecting to repo.openmptcprouter.com (repo.openmptcprouter.com)|37.19.207.34|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1241 (1.2K) [application/octet-stream]
Saving to: '/etc/apt/trusted.gpg.d/openmptcprouter.gpg'

/etc/apt/trusted.gpg.d/openmptcproute 100%[========================================================================>]   1.21K  --.-KB/s    in 0s      

2024-03-23 13:16:18 (27.3 MB/s) - '/etc/apt/trusted.gpg.d/openmptcprouter.gpg' saved [1241/1241]

Remove lock and update packages list...
Hit:1 http://deb.debian.org/debian bullseye InRelease
Hit:2 http://deb.debian.org/debian buster-backports InRelease
Get:3 file:/etc/apt/mirrors/debian.list Mirrorlist [38 B]
Get:7 file:/etc/apt/mirrors/debian-security.list Mirrorlist [47 B]
Hit:8 https://repo.openmptcprouter.com next InRelease    
Hit:9 https://repo.openmptcprouter.com buster InRelease  
Hit:4 https://cdn-aws.deb.debian.org/debian bookworm InRelease
Hit:5 https://cdn-aws.deb.debian.org/debian bookworm-updates InRelease
Hit:6 https://cdn-aws.deb.debian.org/debian bookworm-backports InRelease
Hit:10 https://cdn-aws.deb.debian.org/debian-security bookworm-security InRelease
Reading package lists... Done
Install apt-transport-https, gnupg and openssh-server...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
apt-transport-https is already the newest version (2.6.1).
gnupg is already the newest version (2.2.40-1.1).
openssh-server is already the newest version (1:9.2p1-2+deb12u2).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
Add OpenMPTCProuter repo...
Explanation: Prefer OpenMPTCProuter provided packages over the Debian native ones
Package: *
Pin: origin repo.openmptcprouter.com
Pin-Priority: 1001
Explanation: Prefer libuv1 Debian native package
Package: libuv1
Pin: version *
Pin-Priority: 1003
--2024-03-23 13:16:21--  https://repo.openmptcprouter.com/openmptcprouter.gpg.key
Resolving repo.openmptcprouter.com (repo.openmptcprouter.com)... 37.19.207.34
Connecting to repo.openmptcprouter.com (repo.openmptcprouter.com)|37.19.207.34|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1241 (1.2K) [application/octet-stream]
Saving to: '/etc/apt/trusted.gpg.d/openmptcprouter.gpg'

/etc/apt/trusted.gpg.d/openmptcproute 100%[========================================================================>]   1.21K  --.-KB/s    in 0s      

2024-03-23 13:16:21 (71.5 MB/s) - '/etc/apt/trusted.gpg.d/openmptcprouter.gpg' saved [1241/1241]

Install mptcp kernel and shadowsocks...
Get:1 file:/etc/apt/mirrors/debian.list Mirrorlist [38 B]
Get:5 file:/etc/apt/mirrors/debian-security.list Mirrorlist [47 B]                                                           
Hit:6 http://deb.debian.org/debian bullseye InRelease                                                                 
Hit:7 http://deb.debian.org/debian buster-backports InRelease                                                         
Hit:9 https://repo.openmptcprouter.com next InRelease                                                                                 
Hit:10 https://repo.openmptcprouter.com buster InRelease                                                                              
Hit:2 https://cdn-aws.deb.debian.org/debian bookworm InRelease                                       
Hit:3 https://cdn-aws.deb.debian.org/debian bookworm-updates InRelease         
Hit:4 https://cdn-aws.deb.debian.org/debian bookworm-backports InRelease
Hit:8 https://cdn-aws.deb.debian.org/debian-security bookworm-security InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
dirmngr is already the newest version (2.2.40-1.1).
patch is already the newest version (2.7.6-7).
rename is already the newest version (2.01-1).
curl is already the newest version (7.88.1-10+deb12u5).
libcurl4 is already the newest version (7.88.1-10+deb12u5).
unzip is already the newest version (6.0-28).
pkg-config is already the newest version (1.8.1-1).
ipset is already the newest version (7.17-1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
-                                      90%[=================================================================>       ]  78.70K   103KB/s               Set MPTCP kernel as grub default...
--2024-03-23 13:16:26--  https://www.openmptcprouter.com/server-rc/update-grub.sh
Resolving www.openmptcprouter.com (www.openmptcprouter.com)... 37.19.207.34
Connecting to www.openmptcprouter.com (www.openmptcprouter.com)|37.19.207.34|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 746 [application/octet-stream]
Saving to: '/tmp/update-grub.sh'

/tmp/update-grub.sh                   100%[========================================================================>]     746  --.-KB/s    in 0s      

2024-03-23 13:16:26 (20.3 MB/s) - '/tmp/update-grub.sh' saved [746/746]

Install tracebox OpenMPTCProuter edition
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
tracebox is already the newest version (0.4.4).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
Install iperf3
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
iperf3 is already the newest version (3.12-1+deb12u1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
Synchronizing state of iperf3.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable iperf3
--2024-03-23 13:16:30--  https://www.openmptcprouter.com/server-rc/iperf3.override.conf
Resolving www.openmptcprouter.com (www.openmptcprouter.com)... 37.19.207.34
Connecting to www.openmptcprouter.com (www.openmptcprouter.com)|37.19.207.34|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 151 [application/octet-stream]
Saving to: '/etc/systemd/system/iperf3.service.d/override.conf'

/etc/systemd/system/iperf3.service.d/ 100%[========================================================================>]     151  --.-KB/s    in 0.001s  

2024-03-23 13:16:30 (124 KB/s) - '/etc/systemd/system/iperf3.service.d/override.conf' saved [151/151]

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package 'shadowsocks-libev' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
-                                     100%[========================================================================>]  86.69K  9.43KB/s    in 9.2s    

2024-03-23 13:16:31 (9.43 KB/s) - written to stdout [88768/88768]

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
omr-shadowsocks-libev is already the newest version (3.3.5-3).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
Install OpenMPTCProuter VPS Admin
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-openssl is already the newest version (23.0.0-1).
python3-pip is already the newest version (23.0.1+dfsg-1).
python3-setuptools is already the newest version (66.1.1-1).
python3-wheel is already the newest version (0.38.4-2).
python3-dev is already the newest version (3.11.2-1+b1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-passlib is already the newest version (1.7.4-3).
python3-jwt is already the newest version (2.6.0-1).
python3-netaddr is already the newest version (0.8.0-2).
libuv1 is already the newest version (1.44.2-1+deb12u1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-uvicorn is already the newest version (0.17.6-1).
jq is already the newest version (1.6-2.1).
ipcalc is already the newest version (0.42-2).
python3-netifaces is already the newest version (0.11.0-2+b1).
python3-aiofiles is already the newest version (23.1.0-1).
python3-psutil is already the newest version (5.9.4-1+b1).
python3-requests is already the newest version (2.28.1+dfsg-1).
pwgen is already the newest version (2.08-2).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
-- pip3 install needed python modules
If you see any error here, I really don't care: it's about a module not used for home users
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
netjsonconfig 1.0.2 requires jsonschema~=4.4.0, but you have jsonschema 4.21.1 which is incompatible.
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
netjsonconfig 1.0.2 requires jinja2~=3.0.0, but you have jinja2 3.1.3 which is incompatible.
netjsonconfig 1.0.2 requires jsonschema~=4.4.0, but you have jsonschema 4.21.1 which is incompatible.
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package omr-vps-admin is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Version '0.9+20240301' for 'omr-vps-admin' was not found

**Comment by Ysurac** [comment]
You can use snapshot script.

**Comment by chriskinal** [comment]
Where do I find the snapshot script?

**Comment by Ysurac** [comment]
https://github.com/Ysurac/openmptcprouter/wiki/Snapshots

**Comment by chriskinal** [comment]
Thanks. Since this is beta, I suppose this will be fixed in release.

**Comment by Ysurac** [comment]
It's due to an update of the package that removed previous release.
I fixed rc script just now, snapshot script is the same as rc script.
