### ISSUE TITLE
No more internet after wan3 ! Please HELP

### ISSUE THREAD

**Issue by JeedHome44** [Ysurac/openmptcprouter#3221]
Hello,

I received my Ethernet adaptator for StarLink. I activated by-pass in my StarLink routeur and connect it in Ethernet to my home LAN.

I add a wan 3 in OMR with MacVLan but OMR no see 192.168.1.1 to StarLink.

I delete wan 3 and now all wan see like that : 

![image](https://github.com/Ysurac/openmptcprouter/assets/41892950/2cb396b5-0452-4742-837f-33d90bdcda75)

![image](https://github.com/Ysurac/openmptcprouter/assets/41892950/1c6a89f1-52db-4a96-93f8-72de7e5df433)

how to make OMR work again?

**Comment by JeedHome44** [comment]
I can no longer even access my Freebox and my 4G router locally even though I could do so without any problem before!

I do not understand anything anymore

**Comment by Ysurac** [comment]
You fixed the problem ?

**Comment by JeedHome44** [comment]
No I only used a backup.

I don't know why by restoring 2 WANs it no longer worked and with a BackUp yes
