### ISSUE TITLE
Tethering with rpi3

### ISSUE THREAD

**Issue by Palexxxxx** [Ysurac/openmptcprouter#3223]
## Expected Behavior

I connect two Iphones with usb-tethering to omr and use the build in ethernet port of the rpi3b to connect to the client-device. 

## Current Behavior

I am really bad in programming with routers and have crashed the complete omr twice... could anyone tell me how to realize my expections? Thanks
## Specifications
2x Iphone with tethering (possible to change one to an cellular 4g/lte usb)
Rpi 3b
newest version of OMR
 Use another pi as vps server or ionos vps server

**Comment by Ysurac** [comment]
RPI USB is always bad powered, for tethering I don't know if the phone always provides the power or try to charge himself...
This doc can maybe help: https://openwrt.org/docs/guide-user/network/wan/smartphone.usb.tethering
All tools should be already available in OpenMPTCProuter and no need new installation.
