### ISSUE TITLE
Wifi clients connect but can't reach LAN network

### ISSUE THREAD

**Issue by ambro95** [Ysurac/openmptcprouter#3224]
## Expected Behavior
Clients connect via wifi to the wlan0 interface on Rpi4 and can access LuCi interface and navigate on internet

## Current Behavior
Clients can connect on the wireless AP but can't reach anything, not even the administration interface.
I had everything setted up and devices were working flawlessy, I then changed shadowsocks to v2ray for testing purposes and from then I lost access via wifi. I even reflashed the SD card with a clean install.
Logs apparently doesn't say anything relavant to this case.
With eht0 interface everything is working normally.

## Specifications

  - OpenMPTCProuter version: 0.59.1-5.4
  - OpenMPTCProuter VPS version: 0.1028-5.4.207
  - OpenMPTCProuter VPS provider: Hetzner
  - OpenMPTCProuter platform: RPI4

**Comment by Ysurac** [comment]
Change of proxy shouldn't block wifi. What is your wifi configuration ?

**Comment by ambro95** [comment]
Hi Ysurac, sure, this is the wireless settings:
![wireless1](https://github.com/Ysurac/openmptcprouter/assets/20576137/854848ae-2a8c-4a42-aaf0-54b7c514b2e5)
![wireless2](https://github.com/Ysurac/openmptcprouter/assets/20576137/f8b6c570-cecc-438a-bc58-93f162c1be51)
![wireless3](https://github.com/Ysurac/openmptcprouter/assets/20576137/f5cb01f4-0ae8-483f-94d4-cb56aca847ab)
![wireless4](https://github.com/Ysurac/openmptcprouter/assets/20576137/0b7fac83-ad2d-4956-b3ff-6e806a1f2355)
![wireless5](https://github.com/Ysurac/openmptcprouter/assets/20576137/f5618bd4-7a9a-4af7-998a-9b6d8b88a6e5)


And this is the interface settings:
![wifi](https://github.com/Ysurac/openmptcprouter/assets/20576137/ec243d20-14b2-412a-a2f9-3ddd7bab9ca0)
![wifi2](https://github.com/Ysurac/openmptcprouter/assets/20576137/c70e5f8f-5dce-49ef-ad49-02a9ef8c03bb)
![wifi3](https://github.com/Ysurac/openmptcprouter/assets/20576137/65114e7b-8db2-4f1d-a6e8-64c0a55ed23c)

**Comment by ambro95** [comment]
I got it to work again. I set the IPv4 gateway to 192.168.100.0 and now it's working.
I don't understand why on the LAN interface there is no IPv4 GW but it's working fine

**Comment by ambro95** [comment]
When something is changed on the Advanced Settings of the OpenMPTCProuter wizard, interfaces are being reset. Is this an expected behaviour?

**Comment by Ysurac** [comment]
Yes it's expected.

**Comment by ambro95** [comment]
Ok thank you. Can you tell me why it's working fine on the default LAN interface (eth0) even without the GW setted?

**Comment by ambro95** [comment]
Found the problem on IPv4 GW being reset on the interfaces when changing proxy type
