### ISSUE TITLE
Is it better to use 2 ethernet links or one ? 

### ISSUE THREAD

**Issue by patimages** [Ysurac/openmptcprouter#3228]
Hello, 
Just a question concerning OMR : I have it running on a NUC which has 2 ethernet plugs (I am currently using only one). Would there be any benefit in using both plugs or not ? If yes, what would be your advice to distribute the tasks ? 
Many thanks for your advices !
PS: all is working well using the latest snapshot of OMR 0.60

**Comment by Ysurac** [comment]
It's better to use both ethernet: one for LAN and the other one for the WANs.

**Comment by patimages** [comment]
I'll try, thank you !

**Comment by patimages** [comment]
Worked in only few click on the wizard : fantastic ! A little tiny bug (the test is centred on the left) 
<img width="1641" alt="image" src="https://github.com/Ysurac/openmptcprouter/assets/6791434/78bd51f7-7d50-4c57-bff0-e931252ff73d">
