### ISSUE TITLE
openmptcprouter don't start

### ISSUE THREAD

**Issue by Gregg03** [Ysurac/openmptcprouter#3229]
## Expected Behavior

When I install the openmptcprouter on a HP serveur Proliant DL360p Gen8 x86-64 it's not starting.

## Current Behavior
The system stop in the start
And just tell me the name of my keyboard

## Specifications

  - OpenMPTCProuter version: [openmptcprouter-v0.59.1-5.4-r0+16594-ce92de8c8c-x86-64-generic-ext4-combined.img.gz
  - OpenMPTCProuter platform: x86_64

**Comment by patimages** [comment]
Your gear is most likely not supported by 5.4 kernel ...

**Comment by Gregg03** [comment]
I try to install the old version on the 5.1 kernel and a I have same thing

**Comment by Gregg03** [comment]
I have this result 
![Uploading IMG_2751.JPG…]()

**Comment by Gregg03** [comment]
I can't attach a file ?

**Comment by patimages** [comment]
Tou may rather try 6.1 .... https://wiki.debian.org/HP/ProLiant

**Comment by patimages** [comment]
<img width="453" alt="image" src="https://github.com/Ysurac/openmptcprouter/assets/6791434/f53b2a1e-8b2c-40ff-96bb-55437aff7e7f">
Yes you can, but you file seems to not upload

**Comment by Gregg03** [comment]
when i try to upload the picture i have that

**Comment by Gregg03** [comment]
![Uploading 1.JPG…]()

**Comment by patimages** [comment]
Internet issues ? You need Openmptcprouter ;-D !

**Comment by Gregg03** [comment]
<img width="545" alt="Capture" src="https://github.com/Ysurac/openmptcprouter/assets/100905752/787467ff-a37e-431a-943d-62b0e445d3f3">

**Comment by Gregg03** [comment]
i have that when i try to start the server

**Comment by moi6576** [comment]
Try 6.1

**Comment by Gregg03** [comment]
this version ? 
https://download.openmptcprouter.com/release/v0.60beta1-6.1/x86_64/targets/x86/64/openmptcprouter-v0.60beta1-6.1-r0+23789-ce6ad123e7-x86-64-generic-ext4-combined-efi.img.gz

**Comment by patimages** [comment]
try : https://download.openmptcprouter.com/release/v0.60rc2-5.4/
and if no luck : https://download.openmptcprouter.com/release/v0.60rc2-6.1/

Seems as if you are mixing versions : Efi, non Efi ...

**Comment by Gregg03** [comment]
yes sorry it's not support efi

**Comment by Gregg03** [comment]
I tried both and it's still the same

**Comment by Gregg03** [comment]
for 5.4 
<img width="557" alt="Capversion5" src="https://github.com/Ysurac/openmptcprouter/assets/100905752/a1734f8a-bf5f-4036-8830-f3292b5b8e8d">

**Comment by Gregg03** [comment]
and for 6.1 
<img width="565" alt="CapV6" src="https://github.com/Ysurac/openmptcprouter/assets/100905752/a395229e-30b0-4fd0-b952-3fe2fe63707a">

**Comment by Gregg03** [comment]
and for the 6.1 I have this message at the end : 
random: crng init done

**Comment by patimages** [comment]
Not sure whether it is a failure for the latter ... did you connect the different lines to aggregate ? can you access OMR ?

**Comment by Ysurac** [comment]
If you press "Enter" key you have nothing ?

**Comment by Gregg03** [comment]
No i just have a internet connection, what is ORM

**Comment by Gregg03** [comment]
if I press "enter", it's just make a line break like \n

**Comment by Ysurac** [comment]
OMR = OpenMPTCProuter

**Comment by Gregg03** [comment]
no i don't have access

**Comment by patimages** [comment]
Meaning that you tried to connect http://192.168.100.1/ once all is connected properly ? Did you install the VPS ?

**Comment by Gregg03** [comment]
I connect my PC on the server and try to connect on the http://192.168.100.1/ and i don't have access

**Comment by Gregg03** [comment]
no I haven't installed the VPS server yet

**Comment by patimages** [comment]
Did you try to connect on the http://192.168.100.1/ ? Do you know OMR well ?

**Comment by Gregg03** [comment]
yes i tried to connect but it doesn't work

**Comment by patimages** [comment]
Hard to help then ... Lots of possible causes ...

**Comment by Gregg03** [comment]
sometime I have this message : "random: crng init done"

**Comment by Ysurac** [comment]
it's only initialization of random number generator.
Try to remove all USB device as it seems to end on USB.

**Comment by Gregg03** [comment]
I tried to revome all USB equipment and i have same result

**Comment by Gregg03** [comment]
![lastcap](https://github.com/Ysurac/openmptcprouter/assets/100905752/38601a9c-a7b1-45d6-a51b-116f67e27b16)
