### ISSUE TITLE
SDCard System ReadOnly

### ISSUE THREAD

**Issue by MrTheSkream** [Ysurac/openmptcprouter#323]
## Actual Behavior

Hello, I have a problem with the file system, when there is a power failure the system is read-only.

## Steps to Reproduce the Problem

  1. Connect your raspberry
  2. Unplugged the power cable
  3. And restart raspberry

## Specifications

  - OpenMPTCProuter version: ALL VERSION
  - OpenMPTCProuter platform: RPI3

**Comment by Ysurac** [comment]
Power failure can create FS errors. OpenWrt, on what OpenMPTCProuter is based doesn't do a e2fsck on ext4 at boot. I will check if I can add that.

**Comment by MrTheSkream** [comment]
Okey thanks

**Comment by MrTheSkream** [comment]
Would you have the command to run to avoid read-only ?

**Comment by afriza** [comment]
@Ysurac do you know how to manually fix this?

```
root@OpenMPTCProuter:~# e2fsck -p /dev/mmcblk0
/dev/mmcblk0 is in use.
e2fsck: Cannot continue, aborting.
```
