### ISSUE TITLE
IoTs and OMR

### ISSUE THREAD

**Issue by patimages** [Ysurac/openmptcprouter#3231]
Hi, 
Just a basic question : are the IoTs protected by OMR firewall or should I use a dedicated Vlan ? I always wondered what is the issue with IoTs : they connect my wifi network and access internet but the OMR firewall prevent them from being access, right ?

**Comment by Ysurac** [comment]
Yes, there is a firewall blocking traffic from external side.

**Comment by patimages** [comment]
This tool is really fantastic !
