### ISSUE TITLE
Gateway Down Error

### ISSUE THREAD

**Issue by pablodnaarg** [Ysurac/openmptcprouter#3234]
## Expected Behavior
Gateway Working
## Current Behavior

![Captura de pantalla 2024-03-31 000248](https://github.com/Ysurac/openmptcprouter/assets/165534787/bd9b5238-ab90-48fd-a4a7-2572799c4176)

"Personal" is a Huaweii B311 LTE Modem
The modem LAN IP is 192.90.2.1
DHCP Modem is Disable
DIrect conection Modem to PC works fine and i can reach internet
What are the possible causes for this error ? How could I indagate?

## Specifications

  - OpenMPTCProuter version: v0.59.1-5.4]
  - OpenMPTCProuter VPS version: none
  - OpenMPTCProuter VPS provider: none
  - OpenMPTCProuter platform: RP4 x64

**Comment by Ysurac** [comment]
Check that you can ping the gateway you defined via SSH from the router.

**Comment by pablodnaarg** [comment]
Hello Ysurac, thank you very much for responding so quickly. I just solved the problem, it was a LAN port setting on the modem.

**Comment by pablodnaarg** [comment]
For those using a Huawei B311 modem, it must be set up like this. Otherwise, it will not work.

![Captura de pantalla 2024-03-31 000248](https://github.com/Ysurac/openmptcprouter/assets/165534787/8e2086da-1f26-4dba-b38f-acca8548dbcd)
