### ISSUE TITLE
Preventing a LAN client access to WAN

### ISSUE THREAD

**Issue by IVCrossway** [Ysurac/openmptcprouter#3235]
Hello, I currently have OMR installed on my main router. I also have an AP used for the Garage WIFI, this AP is doing nat. So my main network is 192.168.188.0/24 while the Garage AP is giving 192.168.1.x IPs and I would like to keep it this way.
I tried to add to OMR two firewall rules to prevent the AP (and so, the clients connected to it) access to Internet, but it is not working as intended.
Would you help me to fix this?

I also tried to do this rule with the AP static ip address but it didn't work either.

## Expected Behavior
Client 192.168.188.208 should not have WAN/VPN access, only LAN.

## Current Behavior
Client 192.168.188.208 can access Wan/Lan. (solved)

## Specifications

  - OpenMPTCProuter version: openmptcprouter v0.59.1-5.4
  - OpenMPTCProuter VPS version: 0.1028 5.4.207-mptcp
  - OpenMPTCProuter VPS provider: Aruba Network SpA
  - OpenMPTCProuter platform: x86_64

```
config rule
        option name 'test1'
        list proto 'all'
        option dest 'wan'
        option target 'REJECT'
        option src 'lan'
        list src_mac '[redacted]'

config rule
        option name 'test2'
        list proto 'all'
        option dest 'vpn'
        option target 'REJECT'
        option src 'lan'
        list src_mac '[redacted]'
```

**Comment by IVCrossway** [comment]
Following https://github.com/Ysurac/openmptcprouter/wiki/Block-client-Internet-access does not work.
This is what I created: 
`config rule
        option name 'test1'
        option target 'REJECT'
        option src 'lan'
        list src_ip '192.168.188.208'
        list src_ip '192.168.1.0/24'
        list proto 'tcp'

config rule
        option name 'test2'
        option target 'REJECT'
        list src_ip '192.168.188.208'
        list src_ip '192.168.1.0/24'
        list proto 'all'
        option src '*'`

**Comment by Ysurac** [comment]
Can you use the template ? It's not the same on 0.59.1 and 0.60 based on 6.1 kernel.

**Comment by IVCrossway** [comment]
I added the specifications in the first post, if that's what you meant.
