### ISSUE TITLE
rsync transfer low bandwith

### ISSUE THREAD

**Issue by telandgo** [Ysurac/openmptcprouter#3236]
I try an rsync or cp copy from an external server to an NFS storage behind OMR and bandwith is very low and irregulary.

I check system log and found nothing, tun0 seems to stay connected but bandwith during tranfer from external server to NFS storage behind is low. 
I try with NFS storage behind FTTH access and bandwidth is full and stable.

## Specifications

  - OpenMPTCProuter version: 0.1028
  - OpenMPTCProuter VPS version: 0.59.1-5.4
  - OpenMPTCProuter VPS provider: myself on proxmox vm kvm.VPS located in hostelyon
  - OpenMPTCProuter platform: x86 mini pc vm under proxmox 8core 8Gbits RAM

**Comment by telandgo** [comment]
Yes shadowsocks is used by default and other choices are v2ray or none

**Comment by telandgo** [comment]
i can try none and use glorytune vpn for tcp and udp? should i do that?

**Comment by Ysurac** [comment]
No, it's not a good idea.
You can try 0.60rc2, as there is no more change on 0.59.1

**Comment by telandgo** [comment]
With OMR 0.60rc2 6.1 and server 0.1028 bandwith is more stable around 10MB/s (100Mbps) but i have more bandwith on FTTH acess connected on OMR.
Téléverser - Server: ping.online.net - Sender: 247.46Mb/s - Receiver: 246.44Mb/s

I shoud have around 20 to 25MB/s i think but it is stable at 10MB/s

**Comment by Ysurac** [comment]
Check CPU usage on both end. As proxmox is used on server side, check that AES is enabled.

**Comment by telandgo** [comment]
flag aes has been enable but does it have to be enable during install on both side?
both cpu are host + flag aes on

Dring copy cpu load is not a lot. It increase yes but with 4 core on both side 20% is maximum load.

**Comment by Ysurac** [comment]
Shadowsocks-Rust is used ?

**Comment by telandgo** [comment]
yes shadowsocks-rust-2022

**Comment by Ysurac** [comment]
What is the result of ```omr-test-speed``` via SSH on the VPS ?

**Comment by telandgo** [comment]
90.4M 9536M received and send 100% ok

**Comment by Ysurac** [comment]
Seems ok on VPS part.
What is the result of ```omr-test-speed eth1``` (or any interface you set on the router) via SSH on the router ? Ctrl+C to stop after 2 minutes.

**Comment by telandgo** [comment]
root@OpenMPTCProuter:~# omr-test-speed
Select best test server...
host: scaleway.testdebit.info - ping: 22
host: bordeaux.testdebit.info - ping: 
host: aix-marseille.testdebit.info - ping: 20
host: lyon.testdebit.info - ping: 24
host: lille.testdebit.info - ping: 
host: paris.testdebit.info - ping: 30
host: appliwave.testdebit.info - ping: 22
host: speedtest.frankfurt.linode.com - ping: 34
host: speedtest.tokyo2.linode.com - ping: 395
host: speedtest.singapore.linode.com - ping: 468
host: speedtest.newark.linode.com - ping: 112
host: speedtest.atlanta.linode.com - ping: 119
host: speedtest.dallas.linode.com - ping: 142
host: speedtest.fremont.linode.com - ping: 182
host: speed.hetzner.de - ping: 38
host: ipv4.bouygues.testdebit.info - ping: 29
host: par.download.datapacket.com - ping: 35
host: nyc.download.datapacket.com - ping: 106
host: ams.download.datapacket.com - ping: 32
host: fra.download.datapacket.com - ping: 27
host: lon.download.datapacket.com - ping: 37
host: mad.download.datapacket.com - ping: 50
host: prg.download.datapacket.com - ping: 35
host: sto.download.datapacket.com - ping: 48
host: vie.download.datapacket.com - ping: 34
host: war.download.datapacket.com - ping: 67
host: atl.download.datapacket.com - ping: 117
host: chi.download.datapacket.com - ping: 108
host: lax.download.datapacket.com - ping: 163
host: mia.download.datapacket.com - ping: 139
host: nyc.download.datapacket.com - ping: 106
host: speedtest.milkywan.fr - ping: 21
Best server is http://aix-marseille.testdebit.info/10G.iso, running test:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 9536M  100 9536M    0     0  90.2M      0  0:01:45  0:01:45 --:--:-- 91.4M

**Comment by Ysurac** [comment]
Without the interface it's the aggregated speed on the router, here it's 91.4Mo/s so 731Mb/s. This seems to be the max speed of the VPS part.
Else how do you test speed ? With iperf ?

**Comment by telandgo** [comment]
root@OpenMPTCProuter:~# omr-test-speed wan1
Select best test server...
host: scaleway.testdebit.info - ping: 9
host: bordeaux.testdebit.info - ping: 
host: aix-marseille.testdebit.info - ping: 17
host: lyon.testdebit.info - ping: 15
host: lille.testdebit.info - ping: 
host: paris.testdebit.info - ping: 9
host: appliwave.testdebit.info - ping: 9
host: speedtest.frankfurt.linode.com - ping: 17
host: speedtest.tokyo2.linode.com - ping: 257
host: speedtest.singapore.linode.com - ping: 314
host: speedtest.newark.linode.com - ping: 92
host: speedtest.atlanta.linode.com - ping: 105
host: speedtest.dallas.linode.com - ping: 117
host: speedtest.fremont.linode.com - ping: 152
host: speed.hetzner.de - ping: 21
host: ipv4.bouygues.testdebit.info - ping: 9
host: par.download.datapacket.com - ping: 9
host: nyc.download.datapacket.com - ping: 79
host: ams.download.datapacket.com - ping: 19
host: fra.download.datapacket.com - ping: 17
host: lon.download.datapacket.com - ping: 14
host: mad.download.datapacket.com - ping: 32
host: prg.download.datapacket.com - ping: 23
host: sto.download.datapacket.com - ping: 37
host: vie.download.datapacket.com - ping: 29
host: war.download.datapacket.com - ping: 35
host: atl.download.datapacket.com - ping: 103
host: chi.download.datapacket.com - ping: 95
host: lax.download.datapacket.com - ping: 150
host: mia.download.datapacket.com - ping: 115
host: nyc.download.datapacket.com - ping: 79
host: speedtest.milkywan.fr - ping: 9
Best server is http://scaleway.testdebit.info/10G.iso, running test:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:15 --:--:--     0
curl: (28) Failed to connect to scaleway.testdebit.info port 80 after 15816 ms: Error

**Comment by telandgo** [comment]
iperf on omr 
Téléverser - Server: ping.online.net - Sender: 530.58Mb/s - Receiver: 530.58Mb/s

**Comment by Ysurac** [comment]
Speed seems normal with omr-test-speed, iperf often have lower speed than real bandwidth due to default iperf configuration. Did you check with nperf for example ?
With rsync you get full speed and then it go slower ? In this case you may have to enable SQM with download and upload speed set in the wizard.

**Comment by telandgo** [comment]
At begining speed is higher than real bandwidth and it get slower and finally stay around 10 to 12MBs.

i will try SQM but i though i already try it.

rsync speed directly on ftth access give me full stable bandwidth around 90MBs
