### ISSUE TITLE
MANAGEMENT: Client disconnected the lastest VPS 

### ISSUE THREAD

**Issue by fareign** [Ysurac/openmptcprouter#3239]
Apr 02 05:03:16 iZwz9ecl90hv4wg2bwwqqmZ ovpn-tun0[739]: MANAGEMENT: Client disconnected
Apr 02 05:03:16 iZwz9ecl90hv4wg2bwwqqmZ ovpn-tun0[739]: MANAGEMENT: CMD 'status'
Apr 02 05:03:16 iZwz9ecl90hv4wg2bwwqqmZ ovpn-tun0[739]: MANAGEMENT: Client connected from [AF_INET]127.0.0.1:46529

Apr 02 05:02:49 iZwz9ecl90hv4wg2bwwqqmZ ovpn-tun0[739]: MANAGEMENT: Client disconnected
Apr 02 05:02:49 iZwz9ecl90hv4wg2bwwqqmZ ovpn-tun0[739]: MANAGEMENT: CMD 'status'
Apr 02 05:02:49 iZwz9ecl90hv4wg2bwwqqmZ ovpn-tun0[739]: MANAGEMENT: Client connected from [AF_INET]127.0.0.1:40895

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - OpenMPTCProuter version: snap
  - OpenMPTCProuter VPS version: the lastest 0.1029 test 6.1
  - OpenMPTCProuter VPS provider:aliyun
  - OpenMPTCProuter platform: x86_64
  - Country: cn

**Comment by fareign** [comment]
@Ysurac but openvpn ,can aggrate SRT.

**Comment by Ysurac** [comment]
It's not related to this.
I will centralize SRT problems in https://github.com/Ysurac/openmptcprouter/issues/3227
