### ISSUE TITLE
VPN problem

### ISSUE THREAD

**Issue by yoyosm2000** [Ysurac/openmptcprouter#324]
Hello !

and first, thanks for your incredible work !

## Actual Behavior
I can't connect using Glorytun VPN.

In the log, I have this messages:

![image](https://user-images.githubusercontent.com/24657029/51333033-35f51880-1a7d-11e9-8cba-3edc05a77172.png)

![image](https://user-images.githubusercontent.com/24657029/51332475-1a3d4280-1a7c-11e9-979d-b51376b13210.png)

I also have this error "Can't contact server Admin Script": no token

I've checked on the VPS and the script is running
![image](https://user-images.githubusercontent.com/24657029/51332630-5b355700-1a7c-11e9-973c-4c1ddeee5580.png)

## Steps to Reproduce the Problem

  1. OpenMPTCPRouter configured from wizard with 2 Wan connexions. Shadowsocks is OK. IPv6 is disabled.
  2. LAN IP modified from 192.168.100.1 to 192.168.0.254
  3.

## Specifications

  - OpenMPTCProuter version: v0.45.12 r0+9007-529c95cc15
  - OpenMPTCProuter VPS version: 0.89 on FirstHeberg VPS
  - OpenMPTCProuter platform: x86_64

Thanks for your help !

**Comment by Ysurac** [comment]
Check Admin VPS key, if it's correct check VPS log about glorytun or anything strange here.

**Comment by yoyosm2000** [comment]
Thanks for your answer and your help.

I'm sure of the Admin VPS key, I've copy/paste it from the openmptcprouter_config.txt on the VPS.

And even with the specific Glorytun key, the problem is the same.
Where can I check Glorytun on the VPS ? On the syslog file I don't see anything about it.

And now I have this error on the router:

![image](https://user-images.githubusercontent.com/24657029/51343657-28e52300-1a97-11e9-8570-7021d1fbdf14.png)

I didn't have modify the omr6in4 interface....

**Comment by Ysurac** [comment]
The bug with omr6in4 will be fixed in next release.

**Comment by yoyosm2000** [comment]
Thank you for your precious help

I don't understand, it seems that tun0 is started by glorytun if I read the log:
![image](https://user-images.githubusercontent.com/24657029/51344994-2c2dde00-1a9a-11e9-9f9d-5721f699fc83.png)

![image](https://user-images.githubusercontent.com/24657029/51345045-51bae780-1a9a-11e9-8e61-cdb56c525856.png)

but if I check the state, it' shows VPN is down...
![image](https://user-images.githubusercontent.com/24657029/51345096-6c8d5c00-1a9a-11e9-9dc1-b7626ae6e3be.png)

and default VPN is glorytun TCP
![image](https://user-images.githubusercontent.com/24657029/51345140-89299400-1a9a-11e9-8277-bb6ee646d9d0.png)

**Comment by Ysurac** [comment]
VPN is show as UP if the server answer to ping via the VPN. Here this seems to not be the case.

**Comment by yoyosm2000** [comment]
I have this in the kernel log, it should be the cause ?

network card is Intel e1000

![image](https://user-images.githubusercontent.com/24657029/51346730-a82a2500-1a9e-11e9-89a3-524ea057552e.png)

**Comment by yoyosm2000** [comment]
Sorry for this flood but issue can be closed.

I have solved it using Ubuntu 18.04 on FirstHeberg VPS and all is working perfect. I think there is something missing on the Debian 9 distrib provided by First Heberg.

Thanks again for your help
