### ISSUE TITLE
Remotely access router's LAN from VPS

### ISSUE THREAD

**Issue by ceruleanBlazar** [Ysurac/openmptcprouter#3240]
## Expected Behavior
From the VPS I want to be able to connect at port 22 (SSH) to any IP/Device inside the router's LAN (192.168.100.0/24).

## Current Behavior
The VPS can successfully ping any IP within the LAN. However, attempts to SSH into devices within this network are unsuccessful.
I have reviewed threads [#2864](https://github.com/Ysurac/openmptcprouter/issues/2864) and [#1011](https://github.com/Ysurac/openmptcprouter/issues/1011) for potential solutions.
However I tried implementing traffic rules as suggested in the threads, but no success was observed.

I am not sure whether I understand correctly how to implement that. 

Does someone spot what I am missing and tell me what to do?

![Bildschirmfoto 2024-04-02 um 12 17 14](https://github.com/Ysurac/openmptcprouter/assets/108432151/5a2c3ae2-8b92-43eb-ba72-d36a60f73cc4)

![Bildschirmfoto 2024-04-02 um 12 18 07](https://github.com/Ysurac/openmptcprouter/assets/108432151/66e5cf7c-1dc9-423a-a93e-d20c7e3aefae)

## Specifications

  - OpenMPTCProuter version: v0.59.1-5.4 r0+16594-ce92de8c8c
  - OpenMPTCProuter VPS version: 0.1028 5.4.207-mptcp
  - OpenMPTCProuter VPS provider: OVH (Germany)
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
You can try to set vpn input zone to accept.

**Comment by ceruleanBlazar** [comment]
I set the vpn zone input to accept while having the traffic rule, but no sucess:
![grafik](https://github.com/Ysurac/openmptcprouter/assets/108432151/a7c18898-13e7-4e51-b2f8-a35e39c1074b)

![grafik](https://github.com/Ysurac/openmptcprouter/assets/108432151/6c2ecaca-11c7-4501-8970-85c077b9655d)

**Comment by ceruleanBlazar** [comment]
I have also restarted the firewall on OMR: 
> /etc/init.d/firewall restart

```
root@OpenMPTCProuter:~# /etc/init.d/firewall restart
Warning: Section 'zone_vpn' cannot resolve device of network 'omr6in4'
 * Flushing IPv4 filter table
 * Flushing IPv4 nat table
 * Flushing IPv4 mangle table
 * Flushing IPv4 raw table
 * Flushing IPv6 filter table
 * Flushing IPv6 nat table
 * Flushing IPv6 mangle table
 * Flushing IPv6 raw table
 * Flushing conntrack table ...
 * Populating IPv4 filter table
   * Rule 'Allow SSH to LAN from VPS'
   * Rule 'Allow-DHCP-Renew'
   * Rule 'Allow-Ping'
   * Rule 'Allow-IGMP'
   * Rule 'Allow-IPSec-ESP'
   * Rule 'Allow-ISAKMP'
   * Rule 'Allow-All-LAN-to-VPN'
   * Rule 'Allow-All-Ping'
   * Rule 'Allow-VPN-ICMP'
   * Rule 'Allow-Lan-to-Wan'
   * Rule 'Block QUIC Proxy'
   * Rule 'Block QUIC All'
   * Redirect 'Sonicwall Arbelos'
   * Forward 'lan' -> 'wan'
   * Forward 'lan' -> 'vpn'
   * Zone 'lan'
   * Zone 'wan'
   * Zone 'vpn'
 * Populating IPv4 nat table
   * Redirect 'Port forwarding double NAT'
Warning: parse_option(): unknown option '--dport'
Warning: fw3_ipt_rule_append(): Bad argument '1:64999'
Warning: parse_option(): unknown option '--dport'
Warning: fw3_ipt_rule_append(): Bad argument '1:64999'
Warning: parse_option(): unknown option '--dport'
Warning: fw3_ipt_rule_append(): Bad argument '1:64999'
Warning: parse_option(): unknown option '--dport'
Warning: fw3_ipt_rule_append(): Bad argument '1:64999'
Warning: parse_option(): unknown option '--dport'
Warning: fw3_ipt_rule_append(): Bad argument '1:64999'
   * Zone 'lan'
   * Zone 'wan'
   * Zone 'vpn'
 * Populating IPv4 mangle table
   * Zone 'lan'
   * Zone 'wan'
   * Zone 'vpn'
 * Populating IPv4 raw table
   * Zone 'lan'
     - Using automatic conntrack helper attachment
   * Zone 'wan'
   * Zone 'vpn'
 * Populating IPv6 filter table
   * Rule 'Allow-DHCPv6'
   * Rule 'Allow-MLD'
   * Rule 'Allow-ICMPv6-Forward'
   * Rule 'Allow-IPSec-ESP'
   * Rule 'Allow-ISAKMP'
   * Rule 'Allow-All-LAN-to-VPN'
   * Rule 'Allow-All-Ping'
   * Rule 'Allow-VPN-ICMP'
   * Rule 'Allow-Lan-to-Wan'
   * Rule 'ICMPv6-Lan-to-OMR'
   * Rule 'Block QUIC Proxy'
   * Rule 'Block QUIC All'
   * Rule 'Allow IPv6 ICMP'
   * Rule 'Allow DHCPv6 (546-to-547)'
   * Rule 'Allow DHCPv6 (547-to-546)'
   * Forward 'lan' -> 'wan'
   * Forward 'lan' -> 'vpn'
   * Zone 'lan'
   * Zone 'wan'
   * Zone 'vpn'
 * Populating IPv6 nat table
Warning: fw3_ipt_rule_append(): Can't find target 'prerouting_lan_rule'
Warning: fw3_ipt_rule_append(): Can't find target 'postrouting_lan_rule'
Warning: fw3_ipt_rule_append(): Can't find target 'prerouting_wan_rule'
Warning: fw3_ipt_rule_append(): Can't find target 'postrouting_wan_rule'
Warning: fw3_ipt_rule_append(): Can't find target 'prerouting_vpn_rule'
Warning: fw3_ipt_rule_append(): Can't find target 'postrouting_vpn_rule'
Warning: fw3_ipt_rule_append(): Can't find target 'prerouting_rule'
Warning: fw3_ipt_rule_append(): Can't find target 'postrouting_rule'
   * Zone 'lan'
   * Zone 'wan'
   * Zone 'vpn'
 * Populating IPv6 mangle table
   * Zone 'lan'
   * Zone 'wan'
   * Zone 'vpn'
 * Populating IPv6 raw table
   * Zone 'lan'
     - Using automatic conntrack helper attachment
   * Zone 'wan'
   * Zone 'vpn'
 * Set tcp_ecn to off
 * Set tcp_syncookies to on
 * Set tcp_window_scaling to on
 * Running script '/etc/firewall.user'
 * Running script '/etc/firewall.omr-server'
Warning: Section 'zone_vpn' cannot resolve device of network 'omr6in4'
 * Running script '/etc/firewall.gre-tunnel'
 * Running script '/etc/firewall.ttl'
 * Running script '/etc/firewall.v2ray-rules'
 * Running script '/etc/firewall.omr-bypass'
   ! Failed with exit code 1
 * Running script '/usr/share/miniupnpd/firewall.include'
 * Running script '/etc/firewall.ss-rules'
Flush terminated
Warning: Section 'zone_vpn' cannot resolve device of network 'omr6in4'
```

**Comment by Ysurac** [comment]
Try to also set a SNAT rule to rewrite to router IP.

**Comment by ceruleanBlazar** [comment]
Like this?:
![grafik](https://github.com/Ysurac/openmptcprouter/assets/108432151/feeb4d2a-5c48-493f-907c-58c979d16796)

**Comment by Ysurac** [comment]
outbound zone should be LAN and you should also set the destination port

**Comment by ceruleanBlazar** [comment]
I have added this SNAT rule. 
Now when I try to ssh connect from the VPS to any device inside the LAN nothing happens (before I was getting a "Connection refused"). It is the same if I try to connect to the IP of an actual device or if I connect to an IP, which is not in use.
![grafik](https://github.com/Ysurac/openmptcprouter/assets/108432151/d82589b1-da3a-4ce3-bf15-c2af47057b87)

**Comment by Ysurac** [comment]
Check with tcpdump on the router or even better on the destination computer what you have with something like ```tcpdump -vvv - i any port 22```

**Comment by ceruleanBlazar** [comment]
Now I also on the router.
All the packets get forwarded to 192.168.100.144. 
I have also a port forwarding rule of ports 1-64999 to the pfSense 192.168.100.144.

Do you think there is a way to fix this? Or would I need use another port outside the range of 1-64999?

![grafik](https://github.com/Ysurac/openmptcprouter/assets/108432151/a44d8546-36d1-425a-8095-213d50634df2)

**Comment by Ysurac** [comment]
Yes in this case you should reduce the range (Ports 65000-65535 are used by OpenMPTCProuter internal usage like proxy, VPNs, API,...)
You can also try to change rules order but not sure this will work.

**Comment by ceruleanBlazar** [comment]
@Ysurac Thank you for your help! It works now as planned. 

Here are my final settings:

<img width="778" alt="grafik" src="https://github.com/Ysurac/openmptcprouter/assets/108432151/e76c18d2-0b52-4f6c-a88c-aad14f81ad9b">

<img width="788" alt="grafik" src="https://github.com/Ysurac/openmptcprouter/assets/108432151/876e03e9-08a6-4698-94d3-a808e5c3063a">

<img width="781" alt="grafik" src="https://github.com/Ysurac/openmptcprouter/assets/108432151/56427c80-9060-4c5d-b38c-de417cba8492">


<img width="784" alt="grafik" src="https://github.com/Ysurac/openmptcprouter/assets/108432151/bf0b0841-1da7-4c31-946a-ac16c113cbb6">


<img width="701" alt="grafik" src="https://github.com/Ysurac/openmptcprouter/assets/108432151/3eac2c0c-c321-46fc-8906-d15549df536d">

<img width="700" alt="grafik" src="https://github.com/Ysurac/openmptcprouter/assets/108432151/83378f29-a2d4-47c4-bb78-400ab64c1282">
