### ISSUE TITLE
OpenVpn cannot aggrate SRT UDP  by the latest snap shot

### ISSUE THREAD

**Issue by fareign** [Ysurac/openmptcprouter#3246]
OpenVPN cannot aggrate UDP,I wizard settings ,reboot, it steel not work.
I change to glorytuntcp is OK.

## Specifications

  - OpenMPTCProuter version:snap 6.1
  - OpenMPTCProuter VPS version: 0.1029test
  - OpenMPTCProuter VPS provider:aliyun
  - OpenMPTCProuter platform: x86_64
  - Country:cn

**Comment by Ysurac** [comment]
Duplicate of #3233 and #3227

**Comment by fareign** [comment]
not the same problem
