### ISSUE TITLE
Zerotier

### ISSUE THREAD

**Issue by mycanaletto** [Ysurac/openmptcprouter#325]
Hello
Have you thought about integrating Zerotier for MPTCP to offer the SDN / VPN option ?
I have not tested but the package is available for LEDE / OpenWRT.

https://zerotier.atlassian.net/wiki/spaces/SD/pages/7438339/Layer+2+Bridging+with+LEDE+OpenWRT
https://www.zerotier.com

**Comment by Ysurac** [comment]
zerotier can maybe be usable but only with a custom "planet". For now I don't find enough documentation to do that :)
