### ISSUE TITLE
Installing factory image for Rockchip

### ISSUE THREAD

**Issue by Sorab8888** [Ysurac/openmptcprouter#3250]
## Expected Behavior
 I am trying to install OPENMPTCP on a rockchip hardware environement
 I tried to download the factory image but could find sysupgrade images only in the download link

## Current Behavior
 
 I  cannot find the Factory Image

## Specifications

  - OpenMPTCProuter version:  [openmptcprouter-v0.59.1-5.4]
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter VPS provider:
  - OpenMPTCProuter platform:

**Comment by Ysurac** [comment]
When there is no factory image, use the sysupgrade image in the same way.
