### ISSUE TITLE
x86_64 only showing 1 physical interface when there should be 4

### ISSUE THREAD

**Issue by dev-microcosm** [Ysurac/openmptcprouter#3257]
## Expected Behavior

I have a [computer](https://www.ikoolcore.com/products/ikoolcore-r2) with 4 ethernet ports. I am hoping to use all 4, 2 for wireless access points on my lan and 2 for 5G home connections (Verizon and T-Mobile)

## Current Behavior

On a fresh install of the x86_64 image I only see eth0 as a physical interface.

## Specifications

  - OpenMPTCProuter version: 0.59.1-5.4 r0+16594-ce92de8c
  - OpenMPTCProuter VPS version: 0.1028
  - OpenMPTCProuter VPS provider: Linode
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
Try with 0.60 rc2 with kernel 6.1. As it's more updated, it may support your computer.
