### ISSUE TITLE
Support for Mikrotik RBM33G

### ISSUE THREAD

**Issue by dnwk** [Ysurac/openmptcprouter#3261]
If possible, I would love to see support for Mikrotik RBM33G
https://openwrt.org/toh/hwdata/mikrotik/mikrotik_rbm33g
https://openwrt.org/toh/mikrotik/rbm33g

**Describe why you are asking for this support?**
Mikrotik RBM33G has dual slots for Cellular modem and another slot for wifi card. It is ideally setup for the use case of OpenMPTCPRouter and conveniently to aggregate 2 cellular connections.

**Comment by Ysurac** [comment]
16 MB Flash, 256 MB RAM and a 800Mhz CPU. It's quite the same CPU as Edgerouter X, it's really too slow and there is not enough flash for a complete image.

**Comment by dnwk** [comment]
This device has microSD card slot which could potentially allow for full image. But yeah, CPU is the problem. Thanks for commenting.

**Comment by aladdinshammr** [comment]
@dnwk 

Is it possible for openwrt to be installed in any router board or just in these types in the link??

**Comment by dnwk** [comment]
> @dnwk
> 
> Is it possible for openwrt to be installed in any router board or just in these types in the link??

Since this model is specifically mentioned, I think it is possible
