### ISSUE TITLE
Which is the correct version of the VPS update for the final version of OMR 0.60 5.4?

### ISSUE THREAD

**Issue by vempire-ghost** [Ysurac/openmptcprouter#3263]
I saw that the final version of OMR 0.60 was released, but I got confused because on the wiki for version 5.4, the VPS update link is listed as server-test with version 0.129-test, while for version 6.1, it's listed as server with version 0.130. Is it correct that version 5.4 still uses the test VPS?

For the final version of 0.60 5.4 kernel is this link the correct to update the vps?
`wget -O - https://www.openmptcprouter.com/server-test/debian-x86_64.sh | KERNEL="5.4" sh`

Or is this?
`wget -O - https://www.openmptcprouter.com/server/debian-x86_64.sh | KERNEL="5.4" sh`

**Comment by Ysurac** [comment]
I fixed the wiki
