### ISSUE TITLE
Can't Install on VPS Debian 12 kernel 5.4 .that say in photo.

### ISSUE THREAD

**Issue by lusoe302** [Ysurac/openmptcprouter#3266]
## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - OpenMPTCProuter version: 
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter VPS provider:
  - OpenMPTCProuter platform: 
  - Country:

**Comment by Ysurac** [comment]
Maybe a duplicate of https://github.com/Ysurac/openmptcprouter/issues/3265
