### ISSUE TITLE
nano pi r2s not work with kernel 6.1 . it might be port configuration problem , I can't login to OMR 192.168.100.1 . My PC is 192.168.100.100 . It Boot but not blinking on WAN and LAN lights / SYS light is good , beside of rj-45 light are work well , 

### ISSUE THREAD

**Issue by lusoe302** [Ysurac/openmptcprouter#3267]
## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - OpenMPTCProuter version: 
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter VPS provider:
  - OpenMPTCProuter platform: 
  - Country:

**Comment by Ysurac** [comment]
Please complete the template

**Comment by lusoe302** [comment]
thanks , work on now release/v0.60rc2-6.1/
