### ISSUE TITLE
Can I safely update VPS first?

### ISSUE THREAD

**Issue by hairy-dog** [Ysurac/openmptcprouter#3272]
I am running the old version of OMR and it makes sense to move to version 6.0. 

To do that, I need to upgrade the VPS as well as the OMR Router. 

My question is whether I should: 

1. Update the VPS to the new version and leave the router as it is until afterwards

2. Update the router to the new version and update the VPS afterwards

3. Download the new router file, update the VPS, then flash the router whilst the VPS reboots, so they are both updated at the same time. 

In some way, method 3 seems safest, and in other ways it seems most risky.

**Comment by Ysurac** [comment]
You can do as you want, I think I would update VPS and then router but no real reason.
