### ISSUE TITLE
Work incorrect. Wan interfaces are being disabled. Nanopi R4S 4gb ram. v0.60rc2-6.1, kernel 6.1.

### ISSUE THREAD

**Issue by Silvanskii** [Ysurac/openmptcprouter#3277]
Reinstalled debian VPS to version 12 and installed KERNEL="6.1" sh. During operation, the wan ports are interrupted at random all the time. Then I put version v0.59.1 back on and everything started working correctly. I am attaching a log file.
![2024-04-14_10-07-33](https://github.com/Ysurac/openmptcprouter/assets/95954110/47e7da45-9204-4625-952d-d92a38e89f4d)
![2024-04-14_13-17-20](https://github.com/Ysurac/openmptcprouter/assets/95954110/b6064ae1-75ac-4171-bdd0-9b459b505ba3)
[LOG Core.txt](https://github.com/Ysurac/openmptcprouter/files/14970268/LOG.Core.txt)
[LOG openmptcprouter v0.60-6.1 r0+24843.txt](https://github.com/Ysurac/openmptcprouter/files/14970269/LOG.openmptcprouter.v0.60-6.1.r0%2B24843.txt)
[LOG openmptcprouter v0.60rc2-6.1.txt](https://github.com/Ysurac/openmptcprouter/files/14970270/LOG.openmptcprouter.v0.60rc2-6.1.txt)
P.S To remove the error message next to the VPS server - can't get public IP address from ShadowSoks Rust - you need to change the IP and key from the VPS on the 5.4 kernel in the settings, wait a couple of minutes and change the address to the key and IP vps 6.1 and the error disappears.

**Comment by Silvanskii** [comment]
![2024-04-14_13-41-32](https://github.com/Ysurac/openmptcprouter/assets/95954110/a5156f40-4353-4cce-928d-fb62961334cd)
I also noticed that with the new version of nanopi r4s, it began to warm up to 80 degrees in 5-10 minutes of operation and the processor was loaded into idle by 50%. I returned the old version 59.1 and the processor is running about 60 degrees
![2024-04-14_13-33-01](https://github.com/Ysurac/openmptcprouter/assets/95954110/d1f051ac-5ade-4ddb-b539-64955ec49d14)

**Comment by Ysurac** [comment]
Please use the templae.
To check why an interface is show as red, check Status->System log

**Comment by Silvanskii** [comment]
> Please use the templae. To check why an interface is show as red, check Status->System log
Bag only with 0.60+ versoin.
[15.04_dmesg.txt](https://github.com/Ysurac/openmptcprouter/files/14980425/15.04_dmesg.txt)
[15.04_logs.txt](https://github.com/Ysurac/openmptcprouter/files/14980426/15.04_logs.txt)
