### ISSUE TITLE
High ping issues

### ISSUE THREAD

**Issue by darthclide** [Ysurac/openmptcprouter#3282]
## Expected Behavior
If OpenMPTCProuter->Status page show my ping on master connection as 11ms, then doing a ping command on a local machine should show almost exactly the same number.

## Current Behavior
Instead my ping results jump all over from 50ms all the way up to 250ms. Meanwhile the status page shows a steady 11ms.

## Context (Environment)
The problem is that online games show these same ping jumps. And even results in packet drops at times. Even though the status page says everything is fine. This issue started about a month ago even when I was on version .59

## Possible Solution
MTR tests show 0 problems when testing Master connection by itself (I have a separate ethernet port in my PC that connects to the DSL alone). With that being said, I believe that Glorytun TCP is routing my traffic in a weird way. Maybe there is a way to reduce overhead with a different VPN? Anyway to force a recalculation for best route to server?

## Specifications

OpenMPTCProuter version: Version 0.60-6.1
OpenMPTCProuter VPS version: Version 0.1030 6.1.0-18-amd64
OpenMPTCProuter VPS provider: Vultr
OpenMPTCProuter platform: RPI4
Country: USA

**Comment by darthclide** [comment]
And no, even after disabling all interfaces except for the DSL, the status page still shows 11ms ping, but a ping test on local machine has it jumping all over up to 100ms.

**Comment by Ysurac** [comment]
Status page display latency between the connection and the server side, the latency is the minimum latency you can get.
You can use another VPN than glorytun TCP, glorytun TCP doesn't give a really stable ICMP traffic.

**Comment by darthclide** [comment]
> Status page display latency between the connection and the server side, the latency is the minimum latency you can get. You can use another VPN than glorytun TCP, glorytun TCP doesn't give a really stable ICMP traffic.

It is just confusing why there is such a large discrepancy when you would expect the overhead to only add 5-10ms at most. Which VPN works best for lowest ping?

**Comment by darthclide** [comment]
> All VPNs available on OMR cause latency issues in games. I recommend using xray with its UDP management option to achieve low ping in online games.

I don't see any xray option under Luci App drop downs. Is this something you must enable in cli?

**Comment by Ysurac** [comment]
ICMP is low priority.
Your problem is ping (ICMP) or latency on UDP or latency on TCP ?
You can change Proxy/VPN in System->OpenMPTCProuter, wizard tab, advanced parameters checkbox and enable UDP over V2RAY/XRay in advanced settings tab.

**Comment by darthclide** [comment]
Well overnight apparently I am now getting bad ping results in status page. And I can confirm bad pings when testing from VPS -> ISP. (aka, no VPN adding overhead)

Is it possible that these hops are throttling Glorytun traffic?

I would assume that since I am getting slow website load times + sporadic ping in video games, that it is both a UDP and TCP issue. I assume XRay can only help with UDP? There is no solution that helps both TCP and UDP at the same time?

**Comment by vempire-ghost** [comment]
> Well overnight apparently I am now getting bad ping results in status page. And I can confirm bad pings when testing from VPS -> ISP. (aka, no VPN adding overhead)
> 
> Is it possible that these hops are throttling Glorytun traffic?
> 
> I would assume that since I am getting slow website load times + sporadic ping in video games, that it is both a UDP and TCP issue. I assume XRay can only help with UDP? There is no solution that helps both TCP and UDP at the same time?

Xray can handle both TCP and UDP traffic.

**Comment by aladdinshammr** [comment]
@vempire-ghost 

If I set None for the default VPN value, will it work? or do I Have to set one ?

**Comment by vempire-ghost** [comment]
> @vempire-ghost
> 
> If I set None for the default VPN value, will it work? or do I Have to set one ?

If you set "none" for VPN and have selected Xray/V2Ray to handle UDP traffic, only ICMP packets will go directly through your master WAN without passing through the VPS. If you set "none" for VPN but haven't selected Xray/V2Ray to handle UDP traffic, then besides ICMP traffic, UDP traffic will also exit directly through the master WAN without passing through the VPS.

You can set "none" for both VPN and proxy if you wish, just make sure not to set both simultaneously, otherwise, you'll lose aggregation.

**Comment by darthclide** [comment]
> ICMP is low priority. Your problem is ping (ICMP) or latency on UDP or latency on TCP ? You can change Proxy/VPN in System->OpenMPTCProuter, wizard tab, advanced parameters checkbox and enable UDP over V2RAY/XRay in advanced settings tab.

Apparently I already have xray enabled. Any other ideas to help resolve latency spikes?

**Comment by darthclide** [comment]
> > Well overnight apparently I am now getting bad ping results in status page. And I can confirm bad pings when testing from VPS -> ISP. (aka, no VPN adding overhead)
> > Is it possible that these hops are throttling Glorytun traffic?
> > I would assume that since I am getting slow website load times + sporadic ping in video games, that it is both a UDP and TCP issue. I assume XRay can only help with UDP? There is no solution that helps both TCP and UDP at the same time?
> 
> Xray can handle both TCP and UDP traffic.

Am I missing a setting somewhere? The option under advanced settings says "When proxy V2Ray/XRay VLESS, VMESS or Trojan is used, use it for UDP". This would only affect UDP I thought? And I don't see any settings page that says something along the lines of "VPN settings for XRay"?

**Comment by vempire-ghost** [comment]
> > > Well overnight apparently I am now getting bad ping results in status page. And I can confirm bad pings when testing from VPS -> ISP. (aka, no VPN adding overhead)
> > > Is it possible that these hops are throttling Glorytun traffic?
> > > I would assume that since I am getting slow website load times + sporadic ping in video games, that it is both a UDP and TCP issue. I assume XRay can only help with UDP? There is no solution that helps both TCP and UDP at the same time?
> > 
> > 
> > Xray can handle both TCP and UDP traffic.
> 
> Am I missing a setting somewhere? The option under advanced settings says "When proxy V2Ray/XRay VLESS, VMESS or Trojan is used, use it for UDP". This would only affect UDP I thought? And I don't see any settings page that says something along the lines of "VPN settings for XRay"?

It would be just that option indeed. If it's already active and you're still experiencing latency spikes, it could be that your VPS's outbound route is poor. You can log into the VPS via SSH and run a ping to the IP that's causing issues to see if the problem persists when it goes directly from the VPS.

**Comment by darthclide** [comment]
> > > > Well overnight apparently I am now getting bad ping results in status page. And I can confirm bad pings when testing from VPS -> ISP. (aka, no VPN adding overhead)
> > > > Is it possible that these hops are throttling Glorytun traffic?
> > > > I would assume that since I am getting slow website load times + sporadic ping in video games, that it is both a UDP and TCP issue. I assume XRay can only help with UDP? There is no solution that helps both TCP and UDP at the same time?
> > > 
> > > 
> > > Xray can handle both TCP and UDP traffic.
> > 
> > 
> > Am I missing a setting somewhere? The option under advanced settings says "When proxy V2Ray/XRay VLESS, VMESS or Trojan is used, use it for UDP". This would only affect UDP I thought? And I don't see any settings page that says something along the lines of "VPN settings for XRay"?
> 
> It would be just that option indeed. If it's already active and you're still experiencing latency spikes, it could be that your VPS's outbound route is poor. You can log into the VPS via SSH and run a ping to the IP that's causing issues to see if the problem persists when it goes directly from the VPS.

The ping to my VPS is 10ms, so there is something about "real" internet traffic that is causing these ping spikes. I had hoped there was another setting somewhere that could force a reroute. Seeing as MTR tests show some hops adding 50-100ms at times.

Is it possible for these hop owners to detect and throttle glorytun traffic? Is there a way to hide this better?

**Comment by vempire-ghost** [comment]
@darthclide 
Exactly which IP are you experiencing lag spikes with? Because latency to the VPS is just one part of the path. Beyond the VPS, there's the entire route to the game server that might be experiencing latency issues. The problem could lie in this route, so there's nothing the OMR can do to improve it unless you have a VPS as close as possible to your connection location.

**Comment by aladdinshammr** [comment]
@vempire-ghost 

thank you.
not using any VPN at all enhanced the speed .

but I do not know why I lose the connection to the server when I plug in a mikrotik router to OMR router.
now it's complaining about IPv6 or I do not know what is it


Apr 16 03:06:01 Aladdin user.notice post-tracking-001-post-tracking: wan3 (wan3) switched off because check error, interface have no IPv6, interface have no IPv6 gateway and ping from 192.168.4.52 error (1.0.0.1,114.114.115.115,1.2.4.8)
Apr 16 03:06:01 Aladdin user.notice post-tracking-001-post-tracking: Delete default route to 157.175.187.120 dev wan3
Apr 16 03:06:03 Aladdin user.notice post-tracking-001-post-tracking: Change in routes, set ip route replace default scope global nexthop via 192.168.2.1 dev wan1 weight 1 nexthop via 192.168.3.1 dev wan2 weight 100 (omrvpn_intf: tun0)
Apr 16 03:06:06 Aladdin user.notice OMR-VPS: Can't get vps token, try later (can't ping server vps on 157.175.187.120, no server API answer on 157.175.187.120)
Apr 16 03:06:15 Aladdin user.notice post-tracking-001-post-tracking: wan3 (wan3) switched up
Apr 16 03:06:15 Aladdin user.notice post-tracking-001-post-tracking: Interface route not yet set, set route ip r add default via 192.168.4.1 dev wan3 metric 9
Apr 16 03:06:23 Aladdin user.notice OMR-VPS: Can't get vps token, try later (can't ping server vps on 157.175.187.120, no server API answer on 157.175.187.120)
Apr 16 03:06:27 Aladdin user.notice post-tracking-001-post-tracking: wan2 (wan2) switched off because check error, interface have no IPv6, interface have no IPv6 gateway and ping from 192.168.3.10 error (1.0.0.1,114.114.115.115,1.2.4.8)
Apr 16 03:06:27 Aladdin user.notice post-tracking-001-post-tracking: Delete default route to 157.175.187.120 dev wan2
Apr 16 03:06:32 Aladdin user.notice post-tracking-020-status: Check API configuration...
Apr 16 03:06:32 Aladdin user.notice post-tracking-020-status: Check API configuration... Done
Apr 16 03:06:35 Aladdint user.notice post-tracking-001-post-tracking: wan2 (wan2) switched up
Apr 16 03:06:35 Aladdin user.notice post-tracking-001-post-tracking: Change in routes, set ip route replace default scope global nexthop via 192.168.2.1 dev wan1 weight 1 nexthop via 192.168.4.1 dev wan3 weight 1 nexthop via 192.168.3.1 dev wan2 weight 100 (omrvpn_intf: 
Apr 16 03:06:35 Aladdin user.notice post-tracking-001-post-tracking: Interface route not yet set, set route ip r add default via 192.168.3.1 dev wan2 metric 8
Apr 16 03:06:48 Aladdin user.notice OMR-VPS: Can't get vps token, try later (can't ping server vps on 157.175.187.120, no server API answer on 157.175.187.120)
Apr 16 03:06:57 Aladdin user.notice post-tracking-001-post-tracking: wan2 (wan2) switched off because check error, interface have no IPv6, interface have no IPv6 gateway and ping from 192.168.3.10 error (1.1.1.1,4.2.2.1,8.8.8.8)
Apr 16 03:06:57 Aladdin user.notice post-tracking-001-post-tracking: Delete default route to 157.175.187.120 dev wan2
Apr 16 03:07:05 Aladdin user.notice post-tracking-001-post-tracking: wan2 (wan2) switched up
Apr 16 03:07:05 Aladdin user.notice post-tracking-001-post-tracking: Change in routes, set ip route replace default scope global nexthop via 192.168.2.1 dev wan1 weight 1 nexthop via 192.168.4.1 dev wan3 weight 1 nexthop via 192.168.3.1 dev wan2 weight 100 (omrvpn_intf: 
Apr 16 03:07:05 Aladdin user.notice post-tracking-001-post-tracking: Interface route not yet set, set route ip r add default via 192.168.3.1 dev wan2 metric 8

**Comment by darthclide** [comment]
> @darthclide Exactly which IP are you experiencing lag spikes with? Because latency to the VPS is just one part of the path. Beyond the VPS, there's the entire route to the game server that might be experiencing latency issues. The problem could lie in this route, so there's nothing the OMR can do to improve it unless you have a VPS as close as possible to your connection location.

My Master interface which has a ping of 5ms reliably to my ISP. And a ping of 10ms reliably (except for today) to the VPS. At the same time as I encounter ping spikes in game, a ping test to my VPS (through the VPN tunnel) shows spikes of 50-100ms to the VPS. MTR tests also show spikes occurring at certain hops between my ISP and VPS. So the issue isn't occurring beyond the VPS. The issue is happening before my packets even get to the wider web.

Frankly it is a bit frustrating that VPNs add so much overhead to start with and it would be nice if you could tell me how to route UDP traffic over my 5ms DSL connection with no VPN included. This would resolve 25% of the problems in this household. It would then leave the issue of TCP connections failing or being slow whenever these spikes come. But since XRay was supposedly the magic cure to both UDP/TCP, I am unsure what to do now.

**Comment by vempire-ghost** [comment]
> > @darthclide Exactly which IP are you experiencing lag spikes with? Because latency to the VPS is just one part of the path. Beyond the VPS, there's the entire route to the game server that might be experiencing latency issues. The problem could lie in this route, so there's nothing the OMR can do to improve it unless you have a VPS as close as possible to your connection location.
> 
> My Master interface which has a ping of 5ms reliably to my ISP. And a ping of 10ms reliably (except for today) to the VPS. At the same time as I encounter ping spikes in game, a ping test to my VPS (through the VPN tunnel) shows spikes of 50-100ms to the VPS. MTR tests also show spikes occurring at certain hops between my ISP and VPS. So the issue isn't occurring beyond the VPS. The issue is happening before my packets even get to the wider web.
> 
> Frankly it is a bit frustrating that VPNs add so much overhead to start with and it would be nice if you could tell me how to route UDP traffic over my 5ms DSL connection with no VPN included. This would resolve 25% of the problems in this household. It would then leave the issue of TCP connections failing or being slow whenever these spikes come. But since XRay was supposedly the magic cure to both UDP/TCP, I am unsure what to do now.

Unfortunately, virtually all VPNs that operate over TCP have this latency issue, and from what I've seen, it's something that persists for quite some time. Regarding your issue, if I understood correctly, the problem lies between your connection and the VPS. Do these spikes occur only on the master connection or on all the other connections that you're aggregating as well?

**Comment by darthclide** [comment]
> > > @darthclide Exactly which IP are you experiencing lag spikes with? Because latency to the VPS is just one part of the path. Beyond the VPS, there's the entire route to the game server that might be experiencing latency issues. The problem could lie in this route, so there's nothing the OMR can do to improve it unless you have a VPS as close as possible to your connection location.
> > 
> > 
> > My Master interface which has a ping of 5ms reliably to my ISP. And a ping of 10ms reliably (except for today) to the VPS. At the same time as I encounter ping spikes in game, a ping test to my VPS (through the VPN tunnel) shows spikes of 50-100ms to the VPS. MTR tests also show spikes occurring at certain hops between my ISP and VPS. So the issue isn't occurring beyond the VPS. The issue is happening before my packets even get to the wider web.
> > Frankly it is a bit frustrating that VPNs add so much overhead to start with and it would be nice if you could tell me how to route UDP traffic over my 5ms DSL connection with no VPN included. This would resolve 25% of the problems in this household. It would then leave the issue of TCP connections failing or being slow whenever these spikes come. But since XRay was supposedly the magic cure to both UDP/TCP, I am unsure what to do now.
> 
> Unfortunately, virtually all VPNs that operate over TCP have this latency issue, and from what I've seen, it's something that persists for quite some time. Regarding your issue, if I understood correctly, the problem lies between your connection and the VPS. Do these spikes occur only on the master connection or on all the other connections that you're aggregating as well?

Only on Master connection (DSL). And the issue was only happening when pinging from OMR router (aka ping over VPN). Pinging from VPS to my ISP domain (aka ping over no VPN) showed no issues up until 2 days ago. There is no reason to check my connection to ISP, because throughout all my testing the past week, my ping is always 5ms from house to ISP domain. Even when my master interface showed 100ms, or a ping test from my router to VPS showed 100ms.

I am still curious if any of the other VPN options would give better ping (since xray isn't helping any). I don't want to touch anything without advice though because a couple years ago, any time I touched anything with the VPN my router would act weird or sometimes not work/bond traffic.

**Comment by darthclide** [comment]
Another thought I had which might be a suggestion for future update: It would be nice if you could set all UDP traffic to go over an interface, but have a page that you can add domains/ports to that whitelist those as "bondable". It is nigh impossible to find every port/domain that games use, but things like Youtube are very straight forward.

**Comment by darthclide** [comment]
Still hoping someone can tell me what VPN I should try, and if there is an order to disabling one vpn and enabling another to not brick the router.

**Comment by vempire-ghost** [comment]
Unfortunately, I couldn't understand your problem well enough to offer more help.

Regarding the VPN configuration, you can change it on the Wizard page. You can only choose one at a time, so there's no risk of damaging the router.

**Comment by darthclide** [comment]
> Unfortunately, I couldn't understand your problem well enough to offer more help.
> 
> Regarding the VPN configuration, you can change it on the Wizard page. You can only choose one at a time, so there's no risk of damaging the router.

I just want to see my ping from PC -> VPS stay under 50ms, and not jump all the way up to 300 (or even 1000 sometimes) when all my connections report being <=50ms in the status page. I guess I will wait until late at night to try messing with different VPNs.

**Comment by Ysurac** [comment]
OpenVPN TCP offers a quite stable ICMP ping but a slow connection. It's the default VPN in OpenMPTCProuter v0.60
Also, choose as master the connection that is the more stable, that doesn't lost any packets.
Did you try something like a ```ping -B -I eth2 <vpsip>``` (change eth2 by one of your interface and try all) when you have higher latency ?

**Comment by vempire-ghost** [comment]
> > Unfortunately, I couldn't understand your problem well enough to offer more help.
> > Regarding the VPN configuration, you can change it on the Wizard page. You can only choose one at a time, so there's no risk of damaging the router.
> 
> I just want to see my ping from PC -> VPS stay under 50ms, and not jump all the way up to 300 (or even 1000 sometimes) when all my connections report being <=50ms in the status page. I guess I will wait until late at night to try messing with different VPNs.

Is the ping target the address of your VPS? When the test is done directly through your internet, is the latency low, but when you do it through the OMR, the latency is high?

**Comment by darthclide** [comment]
> OpenVPN TCP offers a quite stable ICMP ping but a slow connection. It's the default VPN in OpenMPTCProuter v0.60 Also, choose as master the connection that is the more stable, that doesn't lost any packets. Did you try something like a `ping -B -I eth2 <vpsip>` (change eth2 by one of your interface and try all) when you have higher latency ?

My master is set as eth1 which is my DSL. It has a non-VPN ping of 5ms to my ISP. And a non-VPN ping to my VPS of 10-15ms. I have done ping tests over specific interfaces like you suggested. And up until a couple days ago, even as my ping shot up to 300 or more, the interface itself only had a ping of 10-15 (in the case of DSL) and 45-60 (in the case of my 4G connections)

I haven't touched open-vpn in a long time because I have no idea how to change settings or enable it.

**Comment by darthclide** [comment]
> > > Unfortunately, I couldn't understand your problem well enough to offer more help.
> > > Regarding the VPN configuration, you can change it on the Wizard page. You can only choose one at a time, so there's no risk of damaging the router.
> > 
> > 
> > I just want to see my ping from PC -> VPS stay under 50ms, and not jump all the way up to 300 (or even 1000 sometimes) when all my connections report being <=50ms in the status page. I guess I will wait until late at night to try messing with different VPNs.
> 
> Is the ping target the address of your VPS? When the test is done directly through your internet, is the latency low, but when you do it through the OMR, the latency is high?

Yes it is the IP of my VPS. Yes, I run a ping test from my local PC at the same time as a Putty SSH into my router testing ping over my eth1 (DSL) interface. Local PC sometimes goes up to 300ms. Putty SSH shows 10-15ms at the same time.

**Comment by vempire-ghost** [comment]
> > > > Unfortunately, I couldn't understand your problem well enough to offer more help.
> > > > Regarding the VPN configuration, you can change it on the Wizard page. You can only choose one at a time, so there's no risk of damaging the router.
> > > 
> > > 
> > > I just want to see my ping from PC -> VPS stay under 50ms, and not jump all the way up to 300 (or even 1000 sometimes) when all my connections report being <=50ms in the status page. I guess I will wait until late at night to try messing with different VPNs.
> > 
> > 
> > Is the ping target the address of your VPS? When the test is done directly through your internet, is the latency low, but when you do it through the OMR, the latency is high?
> 
> Yes it is the IP of my VPS. Yes, I run a ping test from my local PC at the same time as a Putty SSH into my router testing ping over my eth1 (DSL) interface. Local PC sometimes goes up to 300ms. Putty SSH shows 10-15ms at the same time.

When your local PC is connected directly to your router (no over OMR) and you test ping to VPS, they show this 10-15ms stable ping too?

**Comment by darthclide** [comment]
If you are asking if I have a 2nd ethernet port in my PC that is connected to my DSL modem, and that the ping test results in 10-15ms stable to my VPS? Then yes.

And before you ask, this connection is disabled in Windows unless I desperately need it and can't be bothered to deal with OMR-bypass rules. So it isn't affecting these ping results since I disable one, and use the other when testing.

**Comment by vempire-ghost** [comment]
> If you are asking if I have a 2nd ethernet port in my PC that is connected to my DSL modem, and that the ping test results in 10-15ms stable to my VPS? Then yes.
> 
> And before you ask, this connection is disabled in Windows unless I desperately need it and can't be bothered to deal with OMR-bypass rules. So it isn't affecting these ping results since I disable one, and use the other when testing.

Great, and if you allow me one more question, what is the purpose of using OMR for online gaming? Is it to increase the resilience of the connection to possible drops by using multiple connections simultaneously? Or to aggregate the speeds of the internet connections?

**Comment by darthclide** [comment]
> > If you are asking if I have a 2nd ethernet port in my PC that is connected to my DSL modem, and that the ping test results in 10-15ms stable to my VPS? Then yes.
> > And before you ask, this connection is disabled in Windows unless I desperately need it and can't be bothered to deal with OMR-bypass rules. So it isn't affecting these ping results since I disable one, and use the other when testing.
> 
> Great, and if you allow me one more question, what is the purpose of using OMR for online gaming? Is it to increase the resilience of the connection to possible drops by using multiple connections simultaneously? Or to aggregate the speeds of the internet connections?

The purpose is to provide reliable high speed bandwidth to everyone in the house. Allow 4k videos to be played, updates to happen in minutes instead of hours, etc.

As for my own computer, I want to be able to watch 4k videos, stream to twitch, and play games at the same time. Otherwise I could just use DSL alone when gaming.

**Comment by darthclide** [comment]
> To use OpenVPN, set it via System->OpenMPTCProuter, Wizard tab, "Advanced settings" checkbox.

Do I select OpenVPN TCP? Or OpenVPN Bonding?

**Comment by Ysurac** [comment]
OpenVPN TCP

**Comment by vempire-ghost** [comment]
> > > If you are asking if I have a 2nd ethernet port in my PC that is connected to my DSL modem, and that the ping test results in 10-15ms stable to my VPS? Then yes.
> > > And before you ask, this connection is disabled in Windows unless I desperately need it and can't be bothered to deal with OMR-bypass rules. So it isn't affecting these ping results since I disable one, and use the other when testing.
> > 
> > 
> > Great, and if you allow me one more question, what is the purpose of using OMR for online gaming? Is it to increase the resilience of the connection to possible drops by using multiple connections simultaneously? Or to aggregate the speeds of the internet connections?
> 
> The purpose is to provide reliable high speed bandwidth to everyone in the house. Allow 4k videos to be played, updates to happen in minutes instead of hours, etc.
> 
> As for my own computer, I want to be able to watch 4k videos, stream to twitch, and play games at the same time. Otherwise I could just use DSL alone when gaming.

I see, you have to consider that the multipath TCP feature is still in the early stages of development and may have difficulties handling everything you are expecting from it.

I use OMR but only for gaming; I leave all other connections on the fastest connection in the house, and I have great results, but it's still something very specific to my use case.

What I suggested worked for me, but my use case is slightly different from yours.

**Comment by darthclide** [comment]
> > > > If you are asking if I have a 2nd ethernet port in my PC that is connected to my DSL modem, and that the ping test results in 10-15ms stable to my VPS? Then yes.
> > > > And before you ask, this connection is disabled in Windows unless I desperately need it and can't be bothered to deal with OMR-bypass rules. So it isn't affecting these ping results since I disable one, and use the other when testing.
> > > 
> > > 
> > > Great, and if you allow me one more question, what is the purpose of using OMR for online gaming? Is it to increase the resilience of the connection to possible drops by using multiple connections simultaneously? Or to aggregate the speeds of the internet connections?
> > 
> > 
> > The purpose is to provide reliable high speed bandwidth to everyone in the house. Allow 4k videos to be played, updates to happen in minutes instead of hours, etc.
> > As for my own computer, I want to be able to watch 4k videos, stream to twitch, and play games at the same time. Otherwise I could just use DSL alone when gaming.
> 
> I see, you have to consider that the multipath TCP feature is still in the early stages of development and may have difficulties handling everything you are expecting from it.
> 
> I use OMR but only for gaming; I leave all other connections on the fastest connection in the house, and I have great results, but it's still something very specific to my use case.
> 
> What I suggested worked for me, but my use case is slightly different from yours.

My "fastest" connection (DSL) tops out at 20 Mbps download and 4 Mbps upload. And gaming through OMR won't work for the online games I play since they are heavily latency dependent. That and with all the wifi calling going on in the house, unfortunately I need great ping, great bandwidth, and great reliability.

**Comment by vempire-ghost** [comment]
I understand. For years, my fastest internet was a 5Mb ADSL, but now I have 200Mb fiber. However, I still use OMR for redundancy with two other Wi-Fi and 4G connections.
Perhaps one solution could be setting up QoS for your computer to ensure the necessary bandwidth for gaming or limiting the bandwidth of other devices, which might be more useful than OMR itself.

**Comment by darthclide** [comment]
> I understand. For years, my fastest internet was a 5Mb ADSL, but now I have 200Mb fiber. However, I still use OMR for redundancy with two other Wi-Fi and 4G connections. Perhaps one solution could be setting up QoS for your computer to ensure the necessary bandwidth for gaming or limiting the bandwidth of other devices, which might be more useful than OMR itself.

Unfortunately QOS and DSCP are almost impossible to setup because many applications use all sorts of ports and domains. And I don't want a call to drop out on someone upstairs just so I can download an update 1 minute faster on my computer. If I had a fiber connection I would simply just use this software for streaming to Twitch. No more pain of OMR-bypass.

Do recall that up until a couple weeks ago, everything was mostly fine. Yes my ping in games wasn't perfect, but manageable. Both my VPS and my ISP have said they won't do anything about hops in between. It is depressing how much of internet issues in USA stem from the "not my problem" attitude combined with 0 government oversight to ensure subsidies are used to make better internet and not buy another 100 foot yacht. Sorry for mini rant....

**Comment by darthclide** [comment]
> > > I understand. For years, my fastest internet was a 5Mb ADSL, but now I have 200Mb fiber. However, I still use OMR for redundancy with two other Wi-Fi and 4G connections. Perhaps one solution could be setting up QoS for your computer to ensure the necessary bandwidth for gaming or limiting the bandwidth of other devices, which might be more useful than OMR itself.
> > 
> > 
> > Unfortunately QOS and DSCP are almost impossible to setup because many applications use all sorts of ports and domains. And I don't want a call to drop out on someone upstairs just so I can download an update 1 minute faster on my computer. If I had a fiber connection I would simply just use this software for streaming to Twitch. No more pain of OMR-bypass.
> > Do recall that up until a couple weeks ago, everything was mostly fine. Yes my ping in games wasn't perfect, but manageable. Both my VPS and my ISP have said they won't do anything about hops in between. It is depressing how much of internet issues in USA stem from the "not my problem" attitude combined with 0 government oversight to ensure subsidies are used to make better internet and not buy another 100 foot yacht. Sorry for mini rant....
> 
> I really understand what you're going through. I had to fight to get 5MB of speed on my old ADSL, and every time Windows decided to download an update, my game would freeze. It's strange that the problem started without changing anything.

Issue was there in .59, so I figured updating to .60 would help. So technically there was a change. But sadly it has not helped (thankfully didn't make the problem worse). I am just really suspicious that my traffic is being shaped in some way. Seeing as recent Net Neutrality laws in USA mean telecom companies can now do whatever they want with 0 repercussions.

**Comment by Ysurac** [comment]
You can try XRay VLESS Reality, it uses port 443 and may bypass some restrictions/shaping. This will not change ping, but can help in TCP and UDP so in games... At least it's an idea to try...

**Comment by darthclide** [comment]
> You can try XRay VLESS Reality, it uses port 443 and may bypass some restrictions/shaping. This will not change ping, but can help in TCP and UDP so in games... At least it's an idea to try...

So I will be testing tonight:
OpenVPN
Rust Shadowsocks
Xray VLESS

Any other suggestions are welcome.

**Comment by darthclide** [comment]
Well I tested with OpenVPN and Xray VLESS Reality. While both did give me lower pings, Xray reported no public IP in status page.

Rust Shadowsocks neither helped nor hurt performance. 

After we resolve my OMR-bypass issues in my other thread, I will decide whether the loss of bandwidth is worth the lower latency (will ask people in household if they notice a difference on calls etc)
