### ISSUE TITLE
Accès local nom de domaine

### ISSUE THREAD

**Issue by Majaxx80** [Ysurac/openmptcprouter#3283]
Bonjour, 

J'ai fait une reinstallation de OpenMTPCRouter en 0.6.0 et depuis je n'arrive plus à acceder à mes services depuis mon nom de domaine en .com 

Depuis un accès externe, pas de problème j'arrive bien à atteindre mes services .
Depuis l'accès local, impossible d'atteindre le service depuis la même résolution de nom .

Une idée ? 

Merci

**Comment by Ysurac** [comment]
Please use template.
Seems duplicate of https://github.com/Ysurac/openmptcprouter/issues/3247

**Comment by Majaxx80** [comment]
Merci beaucoup. 
Résolu via #3247
