### ISSUE TITLE
Changing data 2x, slow speed, no stable...

### ISSUE THREAD

**Issue by MistiqueX** [Ysurac/openmptcprouter#3287]
Hi dear Ysurac
 about many month i try using mptcprouter - and i sad case have many problem with this.......
![image](https://github.com/Ysurac/openmptcprouter/assets/152299331/162705f8-eb32-4a84-944b-eceaee14348b)
i have many errors with configuration - also when u changing something - it needed twice or more cycle to start work, maybe its a programm conflict.
i use raspberry 4pi + 3 em12-g and openmptcprouter v0.60-6.1 r0+24843-acf40c022e
1 - i cant have good speed, its not summ all modems and speed is to slow.
2 - cant see bands on modems
3 - always errors
4 - to much time to loose - about 3-4 month  
5 - does modem cant work more correctly?
6 - no way to aggregate frequency's and 3 modem working at once
7 - its seems that this mptcprouter is working with 1 modem and other 2 is not  - case its speed of 1 modem!
  - OpenMPTCProuter version: v0.60-6.1 r0+24843-acf40c022e
  - OpenMPTCProuter VPS version: 060.-6.1
  - OpenMPTCProuter VPS provider: timeweb
  - OpenMPTCProuter platform: RPI4/

**Comment by aladdinshammr** [comment]
this happens to me sometimes when I install a new version and restore a backup of the older one.

**Comment by lkyddyy** [comment]
The rpi4 platform is like this. After the system makes modifications, it needs to wait for about 30 seconds, otherwise it will not be saved

**Comment by Ysurac** [comment]
Do you have a powered USB switch ? RPI are know to provide low power on USB ports.

**Comment by MistiqueX** [comment]
> powered USB switch ? RPI are know to provid

I think i understand what u meen. maybe i need give more power for modem with power manager, like that way on a picture down... 
![WhatsApp Image 2024-04-18 at 00 58 47](https://github.com/Ysurac/openmptcprouter/assets/152299331/1836e02a-22f9-4586-899a-6a91d816f9ac)

**Comment by MistiqueX** [comment]
> Do you have a powered USB switch

Can u give a link for powered usb switch?

**Comment by Ysurac** [comment]
I don't know this one, but any USB hub with own power supply should be ok.

**Comment by MistiqueX** [comment]
> I don't know this one, but any USB hub with own power supply should be ok.

Will try it, and reply as sonn as it possibly. thank pall

**Comment by MistiqueX** [comment]
Hi Ysurac, with new usb hab with power 12v 3a - manager modem - see only 1 modem. whats wrong?
