### ISSUE TITLE
TCP meltdown

### ISSUE THREAD

**Issue by yue2388253** [Ysurac/openmptcprouter#3288]
Hi,

I am exploring the use of OpenMPTCPRouter for a project and have a question regarding its handling of TCP traffic. Since OpenMPTCPRouter utilizes MPTCP to proxy TCP traffic, I'm concerned about the potential for a TCP meltdown problem. This issue typically arises when TCP-over-TCP connections lead to inefficiencies and stability problems. 

> 1. https://news.ycombinator.com/item?id=25080693
> 2. https://serverfault.com/questions/630837/under-what-circumstances-is-tcp-over-tcp-performing-significantly-worse-than-tcp
> 

Thank you for your assistance and for maintaining this valuable project!

Best regards,
Lin

**Comment by Ysurac** [comment]
By default, OpenMPTCProuter use Shadowsocks-Rust for TCP traffic between router and server, so a socks5 proxy, and no TCP-over-TCP here.
