### ISSUE TITLE
How to remotely upgrade firmware with this? Can I rewrite the firmware with usb?

### ISSUE THREAD

**Issue by suyuan168** [Ysurac/openmptcprouter#329]
How to remotely upgrade firmware with this? Can I rewrite the firmware with usb?

**Comment by Ysurac** [comment]
What firmware are you talking about ?
OpenMPTCProuter is an OS, not a firmware.

**Comment by suyuan168** [comment]
I mean remote upgrade version number

**Comment by suyuan168** [comment]
bpi-r2 squashfs image？

**Comment by renaudguerin** [comment]
Is the luci upgrade from <0.45 still broken ?

**Comment by Ysurac** [comment]
yes
