### ISSUE TITLE
Master interface tierlist 

### ISSUE THREAD

**Issue by Brazzo978** [Ysurac/openmptcprouter#3291]
Like in other routing platform instead of  selecting master and enabled devices it would be better to have like in opnsense /pfsense gateway tiering for example wan1 tier 1 , wan 2 tier 2 wan 3 tier 3 ,  in case wan 1 is down the master becomes wan 2 if both wan 1 and 2 are down master becomes wan 3 . 

**Describe the solution you'd like**
instead of Master and enabled a priority for the master role should be specified

**Comment by Ysurac** [comment]
I think I will make something like a master ordered group, not related to Multipath status.

**Comment by vempire-ghost** [comment]
Having the ability to adjust the weight of the WANs separately from the multipath configuration is a great idea.
