### ISSUE TITLE
Why are the values of min/max/base upload & download of tun0 marked in red?

### ISSUE THREAD

**Issue by aladdinshammr** [Ysurac/openmptcprouter#3293]
## Expected Behavior

I expect them to be set by default like the other interfaces

## Current Behavior

the values of min/max/base upload & download of tun0 marked in red in Smart Queue Management.
do I need to configure them manually? or is this the reason why I always get disconnected from the VPS?

when I set values manually I get this error:

Apr 17 13:51:32 OpenMPTCProuter user.notice cake-autorate.unknown: ERROR: 1713361892.739293 The value of 'dl_owd_delta_thr_ms' in config file: '/root/cake-autorate/config.omrvpn.sh' is not a valid value of type: 'float'.
Apr 17 13:51:32 OpenMPTCProuter user.notice cake-autorate.unknown: ERROR: 1713361892.785215 The value of 'ul_owd_delta_thr_ms' in config file: '/root/cake-autorate/config.omrvpn.sh' is not a valid value of type: 'float'.
Apr 17 13:51:32 OpenMPTCProuter user.notice cake-autorate.unknown: ERROR: 1713361892.829545 The value of 'dl_avg_owd_delta_thr_ms' in config file: '/root/cake-autorate/config.omrvpn.sh' is not a valid value of type: 'float'.
Apr 17 13:51:32 OpenMPTCProuter user.notice cake-autorate.unknown: ERROR: 1713361892.875505 The value of 'ul_avg_owd_delta_thr_ms' in config file: '/root/cake-autorate/config.omrvpn.sh' is not a valid value of type: 'float'.
Apr 17 13:51:34 OpenMPTCProuter user.notice cake-autorate.unknown: ERROR: 1713361894.640346 The value of 'global_ping_response_timeout_s' in config file: '/root/cake-autorate/config.omrvpn.sh' is not a valid value of type: 'float'.
Apr 17 13:51:34 OpenMPTCProuter user.notice cake-autorate.unknown: ERROR: 1713361894.878884 The config file: '/root/cake-autorate/config.omrvpn.sh' contains 5 error(s). Exiting now.
Apr 17 13:51:35 OpenMPTCProuter user.notice cake-autorate.wan1: INFO: 1713361895.159116 Starting cake-autorate with PID: 13111 and config: /root/cake-autorate/config.wan1.sh
Apr 17 13:51:35 OpenMPTCProuter user.notice cake-autorate.wan2: INFO: 1713361895.168339 Starting cake-autorate with PID: 13112 and config: /root/cake-autorate/config.wan2.sh
Apr 17 13:51:35 OpenMPTCProuter user.notice cake-autorate.unknown: INFO: 1713361895.883227 Stopped cake-autorate with PID: 13110 and config: /root/cake-autorate/config.omrvpn.sh

## Specifications

  - OpenMPTCProuter version: 0.60-6.1
  - OpenMPTCProuter VPS version: 0.1030 6.1.0-20-cloud-amd64
  - OpenMPTCProuter VPS provider: AWS
  - OpenMPTCProuter platform: x86_64

![sqm](https://github.com/Ysurac/openmptcprouter/assets/91631145/733de585-e1ea-4f19-b9dd-46feb2c202a6)

**Comment by Ysurac** [comment]
No need to set values here. I will disable it by default.
