### ISSUE TITLE
port forwarding over proxy no longer working 

### ISSUE THREAD

**Issue by Brazzo978** [Ysurac/openmptcprouter#3296]
## Expected Behavior
Using any variant of v2ray and enabling firewall/port forward/rule/advanced setting/ Use V2ray ( Forward a port (not a range) from server using V2Ray proxy (if enabled) instead of VPN)   should use proxy for port forwarding 
## Current Behavior
Rule enabled opened port 80 just for test but from the public ip port 80 isnt reachable 

## Possible Solution
worked in previus version , doesnt on newer 0.60-5.4 and 0.60-6.1

## Specifications

  - OpenMPTCProuter version: 0.60-5.4
  - OpenMPTCProuter VPS version: 1030-5.4
  - OpenMPTCProuter VPS provider: own
  - OpenMPTCProuter platform: x86_64
  - Country:italy

**Comment by sp2003** [comment]
i've same issue!!

**Comment by Brazzo978** [comment]
Hi i updated to snapsot: openmptcprouter v0.61-snapshot-5.4 r0+16862  , and vps: OpenMPTCProuter VPS 0.1031-test 
now if i set use V2Ray/XRay the port keeps working , but if i remove the tunnel and rely only on the proxy the port is not forwareded , and if i disable proxy and enable only the tunnel the port is forwarded , so i think its not using proxy for port forwarding , am i missing something ? 
![image](https://github.com/Ysurac/openmptcprouter/assets/55558507/b51ff4cf-f898-44a7-9260-bda3a1255f5e)
![image](https://github.com/Ysurac/openmptcprouter/assets/55558507/9a1d556e-8a76-4a6f-9a3e-4fd897a5b127)


Log : https://pastebin.com/Tx6RFGvT

**Comment by Ysurac** [comment]
What do you have in ```/etc/shorewall/rules``` on the VPS side ?

**Comment by Brazzo978** [comment]
ok thanks i think i found out , i had enabled Redirects all ports from server to this router , now last rule appeared and 
ACCEPT          net             $FW             tcp     80      # OMR openmptcprouter open router 80 port tcp --- XRay to :80 , i just had to create a new rule and not edit an existing one and then it appeared in the shorewall file
