### ISSUE TITLE
OMR ByPASS not working

### ISSUE THREAD

**Issue by Majaxx80** [Ysurac/openmptcprouter#3297]
## Expected Behavior
Pass the flow through wan1 or wan2
## Current Behavior
After configuring OMRBYPASS the flow always goes via the vps

![Capture d'écran 2024-04-18 211407](https://github.com/Ysurac/openmptcprouter/assets/167097812/4c640c04-d2b5-4b44-b935-89d25d84466c)

> root@OpenMPTCProuter:~# uci show omr-bypass
omr-bypass.all=interface
omr-bypass.m6replay=proto
omr-bypass.m6replay.url='m6web.fr' '6play.fr' '6cloud.fr'
omr-bypass.mycanal=proto
omr-bypass.mycanal.url='mycanal.fr' 'canal-plus.com' 'canalplus.com' 'canalplus-cdn.net' 'canalplus.pro' 'canal-plus.net'
omr-bypass.minecraft=proto
omr-bypass.minecraft.url='authserver.mojang.com'
omr-bypass.lesnumeriques=proto
omr-bypass.lesnumeriques.url='lesnumeriques.com' 'botscorner.com' 'app.botscorner.com'
omr-bypass.disneyplus=proto
omr-bypass.disneyplus.url='bamgrid.com' 'disney-plus.net'
omr-bypass.amazonvideo=proto
omr-bypass.amazonvideo.url='cloudfront.net' 'llnw.net'
omr-bypass.free=proto
omr-bypass.free.url='free.fr' 'freebox.fr' 'oqee.tv' 'oqee.net'
omr-bypass.orange=proto
omr-bypass.orange.url='orange.fr' 'sosh.fr' 'liveperson.net' 'liveperson.com' 'lpsn.net' 'lpsnmedia.net' 'francetelecom.fr'
omr-bypass.eth0=interface
omr-bypass.eth0.id='9999'
omr-bypass.wan1=interface
omr-bypass.wan1.id='7'
omr-bypass.wan2=interface
omr-bypass.wan2.id='8'
omr-bypass.tun0=interface
omr-bypass.tun0.id='1500'
omr-bypass.global=global
omr-bypass.global.vpn_ipv4_md5='68b329da9893e34099c7d8ad5cb9c940'
omr-bypass.global.vpn_ipv6_md5='68b329da9893e34099c7d8ad5cb9c940'
omr-bypass.@lan_ip[0]=lan_ip
omr-bypass.@lan_ip[0].ip='192.168.100.235'
omr-bypass.@lan_ip[0].interface='wan1'
`

> root@OpenMPTCProuter:~# uci show dhcp
dhcp.@dnsmasq[0]=dnsmasq
dhcp.@dnsmasq[0].domainneeded='1'
dhcp.@dnsmasq[0].localise_queries='1'
dhcp.@dnsmasq[0].rebind_protection='1'
dhcp.@dnsmasq[0].rebind_localhost='1'
dhcp.@dnsmasq[0].local='/lan/'
dhcp.@dnsmasq[0].domain='lan'
dhcp.@dnsmasq[0].expandhosts='1'
dhcp.@dnsmasq[0].nonegcache='1'
dhcp.@dnsmasq[0].cachesize='1000'
dhcp.@dnsmasq[0].authoritative='1'
dhcp.@dnsmasq[0].readethers='1'
dhcp.@dnsmasq[0].leasefile='/tmp/dhcp.leases'
dhcp.@dnsmasq[0].localservice='1'
dhcp.@dnsmasq[0].ednspacket_max='1232'
dhcp.@dnsmasq[0].server='127.0.0.1#5353' '/lan/' '/use-application-dns.net/'
dhcp.@dnsmasq[0].noresolv='1'
dhcp.@dnsmasq[0].address='/router.local/192.168.100.1' '/url.com/192.168.100.3'
dhcp.lan=dhcp
dhcp.lan.interface='lan'
dhcp.lan.start='100'
dhcp.lan.limit='150'
dhcp.lan.leasetime='12h'
dhcp.lan.dhcpv4='server'
dhcp.lan.ra_slaac='1'
dhcp.lan.ra_flags='managed-config' 'other-config'
dhcp.lan.force='1'
dhcp.wan=dhcp
dhcp.wan.interface='wan'
dhcp.wan.ignore='1'
dhcp.odhcpd=odhcpd
dhcp.odhcpd.maindhcp='0'
dhcp.odhcpd.leasefile='/tmp/hosts/odhcpd'
dhcp.odhcpd.leasetrigger='/usr/sbin/odhcpd-update'
dhcp.odhcpd.loglevel='4'
dhcp.@host[0]=host
dhcp.@host[0].name='SRV-NAS'
dhcp.@host[0].mac='2C:F0:5D:E0:A0:4C'
dhcp.@host[0].ip='192.168.100.253'
dhcp.@host[1]=host
dhcp.@host[1].name='TV-SALON'
dhcp.@host[1].mac='04:5D:4B:19:23:A5'
dhcp.@host[1].ip='192.168.100.10'
dhcp.@host[2]=host
dhcp.@host[2].name='DOMO-TYDOM'
dhcp.@host[2].mac='00:1A:25:06:46:61'
dhcp.@host[2].ip='192.168.100.100'
dhcp.@host[3]=host
dhcp.@host[3].name='CAM-EXT1'
dhcp.@host[3].mac='EC:71:DB:98:55:F4'
dhcp.@host[3].ip='192.168.100.105'
dhcp.@host[4]=host
dhcp.@host[4].name='DOMO-RPI'
dhcp.@host[4].mac='B8:27:EB:01:71:70'
dhcp.@host[4].ip='192.168.100.101'
dhcp.@host[5]=host
dhcp.@host[5].name='DOMO-ASPI'
dhcp.@host[5].mac='50:EC:50:18:6B:8C'
dhcp.@host[5].ip='192.168.100.106'
dhcp.omr_dscp_cs0=ipset
dhcp.omr_dscp_cs0.name='omr_dscp_cs0_4'
dhcp.omr_dscp_cs1=ipset
dhcp.omr_dscp_cs1.name='omr_dscp_cs1_4'
dhcp.omr_dscp_cs1.domain='download.qq.com' 'steamcontent.com' 'gs2.ww.prod.dl.playstation.net' 'dropbox.com' 'dropboxstatic.com' 'dropbox-dns.com' 'log.getdropbox.com' 'drive.google.com' 'drive-thirdparty.googleusercontent.com' 'docs.google.com' 'docs.googleusercontent.com' 'gvt1.com' 'mmg-fna.whatsapp.net' 'upload.youtube.com' 'upload.video.google.com' 'windowsupdate.com' 'update.microsoft.com'
dhcp.omr_dscp_cs2=ipset
dhcp.omr_dscp_cs2.name='omr_dscp_cs2_4'
dhcp.omr_dscp_cs2.domain='googletagmanager.com' 'googleusercontent.com' 'google.com' 'fbcdn.net' 'akamaihd.net' 'whatsapp.net' 'whatsapp.com' 'zoom.us' 'googleapis.com' '1e100.net' 'hwcdn.net'
dhcp.omr_dscp_cs3=ipset
dhcp.omr_dscp_cs3.name='omr_dscp_cs3_4'
dhcp.omr_dscp_cs4=ipset
dhcp.omr_dscp_cs4.name='omr_dscp_cs4_4'
dhcp.omr_dscp_cs4.domain='googlevideo.com' 'nflxvideo.net' 's3.ll.dash.row.aiv-cdn.net' 'd25xi40x97liuc.cloudfront.net' 'aiv-delivery.net' 'fbcdn.net' 'ttvnw.net' 'vevo.com' 'audio-fa.scdn.com' 'deezer.com' 'sndcdn.com' 'last.fm' 'v.redd.it'
dhcp.omr_dscp_cs5=ipset
dhcp.omr_dscp_cs5.name='omr_dscp_cs5_4'
dhcp.omr_dscp_cs5.domain='tv.milkywan.fr'
dhcp.omr_dscp_cs6=ipset
dhcp.omr_dscp_cs6.name='omr_dscp_cs6_4'
dhcp.omr_dscp_cs7=ipset
dhcp.omr_dscp_cs7.name='omr_dscp_cs7_4'
dhcp.omr_dscp_ef=ipset
dhcp.omr_dscp_ef.name='omr_dscp_ef_4'
dhcp.omr_dst_bypass_eth0=ipset
dhcp.omr_dst_bypass_eth0.name='omr_dst_bypass_eth0_4' 'omr_dst_bypass_eth0_6'
dhcp.omr_dst_bypass_wan1=ipset
dhcp.omr_dst_bypass_wan1.name='omr_dst_bypass_wan1_4' 'omr_dst_bypass_wan1_6'
dhcp.omr_dst_bypass_wan2=ipset
dhcp.omr_dst_bypass_wan2.name='omr_dst_bypass_wan2_4' 'omr_dst_bypass_wan2_6'
dhcp.omr_dst_bypass_tun0=ipset
dhcp.omr_dst_bypass_tun0.name='omr_dst_bypass_tun0_4' 'omr_dst_bypass_tun0_6'
dhcp.omr_dst_bypass_all=ipset
dhcp.omr_dst_bypass_all.name='omr_dst_bypass_all_4' 'omr_dst_bypass_all_6'

## Specifications

  - OpenMPTCProuter version: 0.60-6.1
  - OpenMPTCProuter VPS version: 0.10.30
  - OpenMPTCProuter VPS provider: PulseHeberg
  - OpenMPTCProuter platform: Dell
  - Country: FR

**Comment by Ysurac** [comment]
ByPass all traffic from an IP is now fixed. This will be in next snapshot (it's compiling) so in next release.

**Comment by winkmichael** [comment]
This will be an RC3?

> ByPass all traffic from an IP is now fixed. This will be in next snapshot (it's compiling) so in next release.

**Comment by Ysurac** [comment]
This will be in v0.60.1
