### ISSUE TITLE
OMR-Bypass wan specification

### ISSUE THREAD

**Issue by yoyosm2000** [Ysurac/openmptcprouter#330]
Hello, 

I have a lot of connection reset so I want to use OMR-Bypass for one computer on my network, but it  not seems to work properly if I specify wan1 or wan2, it continues to use VPN.

![image](https://user-images.githubusercontent.com/24657029/51443887-36491a00-1cf0-11e9-81c2-536535176f7e.png)

![image](https://user-images.githubusercontent.com/24657029/51443890-43fe9f80-1cf0-11e9-9275-7a9b0700e656.png)

![image](https://user-images.githubusercontent.com/24657029/51443893-4f51cb00-1cf0-11e9-8392-6d562ea5b5b0.png)

If I choose default, it seems to work...

## Steps to Reproduce the Problem

  1. Specify wan1 or wan2 for an LAN IP in OMR-Bypass: the public IP is the IP of the VPN, it doesn't work
  2. Specify default for the same LAN IP in OMR-Bypass: the public IP is either wan1 or wan2, it works.
  3.

## Specifications

  - OpenMPTCProuter version: openmptcprouter v0.45.15
  - OpenMPTCProuter VPS version: 0.89
  - OpenMPTCProuter platform: x86_64

Thanks for your help !

**Comment by Ysurac** [comment]
This will be fixed in 0.45.16 :)

**Comment by yoyosm2000** [comment]
Thanks for your answer and your work !

**Comment by Ysurac** [comment]
Should be working in latest release.
