### ISSUE TITLE
The ability to define which WAN the proxy will use to initiate the connection?

### ISSUE THREAD

**Issue by vempire-ghost** [Ysurac/openmptcprouter#3301]
Currently, OMR routes all proxy traffic through the master WAN. Is it possible to configure the proxy to use another WAN to initiate connections instead of the master? This would allow keeping the master on one WAN, but having the proxy use another WAN to establish initial connections.

**Comment by Ysurac** [comment]
I don't understand what you mean. Master define interface used for initial connection, it's the default gateway, so why using another connection and what would be master in this case ?

**Comment by vempire-ghost** [comment]
I just want to direct the proxy connection to a WAN without having to define it as the default gateway. Perhaps using some firewall rule for that?

**Comment by aladdinshammr** [comment]
@vempire-ghost 
What I could not understand is "What is the use of backup interface?"
It just stays idle there, and when the master connection goes down backup connection keeps sleeping.

**Comment by Ysurac** [comment]
I don't think it's related to the subject, but backup interface is (or at least should be) used when master and interface set to "on" are down.
