### ISSUE TITLE
Is OpenMPTCPRouter can be use for video livestreaming?

### ISSUE THREAD

**Issue by lkimloong** [Ysurac/openmptcprouter#3312]
Hi Ysurac, wish to check is OpenMPTCPRouter are good to be use as an internet bonding connection for video livestream to platform such as FB, Youtube, Vimeo or etc...? Since video packet are mostly transmit on UDP protocol. Can OpenMPTCPRouter work similar like Speedify for video streaming? Your reply are highly appreciated.
Thank you

**Comment by Ysurac** [comment]
OpenMPTCProuter is far better in TCP than in UDP for now. UDP work but it's slower.
