### ISSUE TITLE
"Help wanted" (not for myself)

### ISSUE THREAD

**Issue by vitaprimo** [Ysurac/openmptcprouter#3318]
(though, I wouldn't say no to it)

## Expected Behavior
Some form of hint in the console or maybe a more permissive initial firewall for remote deployments. It seems that the only thing lacking instructions is for setting OpenMPTCPRouter with OpenMPTCPRouter as its cloud-hosted counterpart.

Since you're providing a full* distribution, it's fair if it receives the same love as the others. Or maybe even just a tiny little more, _it's your baby we get it_, but instead it's the one that goes mostly unmentioned.

## Current Behavior
Steps:
- I created a VM on Fusion to make sure it would work. Turned it off as soon as it started loading
- Exported OVF
- Converted disk to raw for Openstack
- Uploaded

In the VPS, I rebuilt an existing server, which is basically swapping its disk, started it  but it was impossible to access, through a very painful trial an error on an awful Openstack console I found a script that was re-enabling the firewall very quickly which finally let me access it to create a proper rule. I basically broke every config file replacing them with bad versions so if there was something rebuilding them it wouldn't notice. The originals were just renamed, after I made it stop shielding up I created a top-priority rule, from any to any to access the firewall.

When I finally got to the assisted setup, it put in interfaces on its own, both considering and ignoring the first WAN at the same time, it's kinda weird, I'm attaching screenshots. — I blurred static IP addresses, I hope that's OK.:)

A little later from a video embedded on GitHub I believe, I saw later it expects the first interface to be the LAN interface. I've had instances from a lot of cloud providers (3 or 4 of them are on [the list](https://github.com/Ysurac/openmptcprouter/wiki/Install-or-update-the-VPS)) and they don't always have a dummy adapter that could be used for the LAN side dummy of a firewall, which is odd if it's true that it expects it.

Maybe a little less liberal use of the word server would be good too as both sides are servers. Or maybe adding perspectives, for instance: a LAN on-prem is the broadcast network(s) known as the intranet, right? But on the VPS it might be the tunnels to on-prem or none at all. It's one of the many reasons why I believe OpenWRT should get rid of zones, like others firewalls have.

_Néanmoins, j'aimerais vous remercier de partager vôtre travail._ <3

## Specifications

  - OpenMPTCProuter version: v0.60-6.1 r0+24843-acf40c02 **EFI**, on vSphere (proper type 1 hypervisor, not Fusion since I mentioned it earlier)
  - OpenMPTCProuter VPS version: v0.60-6.1 r0+24843-acf40c02
  - OpenMPTCProuter VPS provider: DreamCompute (DreamHost)
  - OpenMPTCProuter platform: x86_64

![Screen Shot 2024-04-25 at 03 01 46](https://github.com/Ysurac/openmptcprouter/assets/18566096/da758a95-f64f-4143-a8f4-ca19a77fa21b)

> _*: for what it needs to do_

**Comment by Ysurac** [comment]
I don't understand what is the help you want here...
In screenshot, you seems to have enabled MPTCPoverVPN in the wizard. Why ?
I don't understand what you have done on server part, you run the script command on Debian (as indicated in the doc) ?
