### ISSUE TITLE
Pakckage update trought the GUI - Good idea ?

### ISSUE THREAD

**Issue by vinceducat** [Ysurac/openmptcprouter#3319]
## Expected Behavior
keep omr router up to date

## Current Behavior
doing okpg update pakages is it allowed to keep the systme up to date ? or not a good thinks to do
## Specifications

  - OpenMPTCProuter version: 0.60
  - OpenMPTCProuter VPS version: 0.1030
  - OpenMPTCProuter VPS provider: milkywan
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
It's not a good thing to do. But in any case, the package repo is not updated after a release.

**Comment by vinceducat** [comment]
ok thanks
