### ISSUE TITLE
Subnet routing

### ISSUE THREAD

**Issue by Kalu01** [Ysurac/openmptcprouter#3320]
## Expected Behavior
What settings do I need to adjust so that the traffic is routed through?

## Current Behavior
First of all, thank you for the openMPTCP router and the help and support.
I have a problem with my setup for which I have not found a solution anywhere.
The VPS server is in the subnet 10.12.0.0, and the network behind the MPTCP router is 192.168.200.0. I want to forward traffic from the subnet 10.12.0.0 to 192.168.200.0. Pinging 192.168.200.x works via the VPS server, but not from other computers connected to the subnet via the VPS. The normal firewall rules should apply for the external IP of the VPS. 

## Specifications

  - OpenMPTCProuter version:  v0.60rc1-5.4 r0+16862-170d9e447d
  - OpenMPTCProuter VPS version: 0.1029-test 5.4.207-mptcp
  - OpenMPTCProuter VPS provider: AZURE VM
  - OpenMPTCProuter platform:  Linux (ubuntu 22.04) x64
  - 3 * Starlink

**Comment by Ysurac** [comment]
On the VPS, firewall is controlled by shorewall in /etc/shorewall/
By default, all connections from outside are blocked (only ICMP ping is always authorized).
You will have to change shorewall configuration.
