### ISSUE TITLE
Is it possible to compile OMR using a forked version of MPTCP 0.96 instead of the official one in kernel 5.4?

### ISSUE THREAD

**Issue by vempire-ghost** [Ysurac/openmptcprouter#3321]
Would it be possible to compile OMR on version 5.4 using a forked version of MPTCP 0.96 where I made some changes? If so, could you guide me on how to do it?
By the way, do you use the final version 0.96 or one with some of your modifications?

**Comment by Ysurac** [comment]
It's 0.96. There is modification only on x86 to allow more subflows.
MPTCP is added as a simple patch, remove it and add another one https://github.com/Ysurac/openmptcprouter/blob/develop/5.4/target/linux/generic/hack-5.4/690-mptcp_v0.96.patch

**Comment by vempire-ghost** [comment]
So I just need to compile the patch and replace it with this file you linked after cloning your repository and before compiling?

**Comment by vempire-ghost** [comment]
Can I just edit your patch by adding the modifications to it before compiling?
