### ISSUE TITLE
Wi-Fi6 LinkStar-H68K-1432

### ISSUE THREAD

**Issue by Esysteme** [Ysurac/openmptcprouter#3331]
I continue my search to have the perfect box for OpenMtcprouteur and the smallest as possible.

Ideally :

- Alimentation with 5V USB-C
- 3 or for 4 RJ 45 with 1 in 2.5G
- 2 routeur 4G
- 2 wifi access point
- powerfull enough !

this box match some points, do you think it's possible to install on it ?

**Comment by Esysteme** [comment]
the new hardware of RUTX50 is supported now ?

**Comment by Ysurac** [comment]
LinkStar-H68K is not really cheap and would need some work to support it. For now it will not work.
RUTX50 is supported with kernel 6.1 (Install procedure is not really easy) and even if this work, support can be better.
