### ISSUE TITLE
mt6323 poweroff support -- add rtc driver support

### ISSUE THREAD

**Issue by suyuan168** [Ysurac/openmptcprouter#334]
Can I integrate BPI-R2 shutdown support under integration? Can refer to the official

https://github.com/BPI-SINOVOIP/BPI-R2-bsp/commit/59a531fe0c52a3f7d0d2ebeb3b12575c592a7ac5
https://github.com/BPI-SINOVOIP/BPI-R2-bsp/commit/61abe96bbc4ebe168cc9abbfe3abef51bfa4468e

**Comment by Ysurac** [comment]
Patches are for kernel 4.4, I'm using kernel 4.14 for now.
