### ISSUE TITLE
two 5G module low bandwidth

### ISSUE THREAD

**Issue by YQW1504040201** [Ysurac/openmptcprouter#3340]
Expected Behavior
OMR may use 2 5G module bandwidth.

Current Behavior
I have two huawei 5G wingle and aggreate. at first, I use one wingle to test speed , the result is download: 60Mbps, upload: 120Mbps. at second, i use two wingle to test , the result is download: 60Mbps, upload: 144Mbps. 
I monitor the [MPTCP]->[bandwidth] , wan1 & wan2 bandwidth is balance( download: 30Mbps, 30Mbps), but omr can't effective use two module's performace.

Specifications

OpenMPTCProuter version: openmptcprouter v0.59.1-5.15 r0+20029-3c06a344e9
OpenMPTCProuter VPS version: 5.4.207-mptcp 0.1028
OpenMPTCProuter VPS provider: alicloud
OpenMPTCProuter platform: x86_64 

![截图 2024-05-09 11-42-49](https://github.com/Ysurac/openmptcprouter/assets/68832284/31746d3b-7455-429d-8d7a-3a36a542f602)
![截图 2024-05-09 11-41-56](https://github.com/Ysurac/openmptcprouter/assets/68832284/3a338a9b-3ff4-4af4-97ad-661253955b5f)

**Comment by Ysurac** [comment]
0.59.1 with 5.15 kernel doesn't work correctly. You should update router and VPS.
