### ISSUE TITLE
speedtest.net HTTP 429 error (too many requests)

### ISSUE THREAD

**Issue by pbonnard** [Ysurac/openmptcprouter#3348]
Hello,

Looks like [http://c.speedtest.net/speedtest-servers-static.php] used in omr-speedtest script can reports HTTP 429 error for many public IPs, including some from VPS/ISP. 
In this case the omr-speedtest script fails.
Shouldn't we have the opportunity to cache the servers list or to have static list to prevent this situation?

**Comment by Ysurac** [comment]
omr-speedtest doesn't work correctly, you should use ```omr-test-speed```
