### ISSUE TITLE
Some problems - Errors and Port Forwarding

### ISSUE THREAD

**Issue by jansiebks** [Ysurac/openmptcprouter#3351]
## Expected Behavior
I installed today the OpenMPTCProuter and isp bonding works. But I have an error notification. And my Port Forwarding settings doesn’t works. Can your help me?

## Current Behavior

![IMG_0028](https://github.com/Ysurac/openmptcprouter/assets/169602729/aad7d27c-1dfe-41f4-aa4c-5de336b27473)

## Specifications

  - OpenMPTCProuter version: 
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter VPS provider: Ionos
  - OpenMPTCProuter platform:

**Comment by Ysurac** [comment]
Filesystem is read only.
You need to reinstall a fresh image or fix filesystem.
