### ISSUE TITLE
Le vpn ne répond pas

### ISSUE THREAD

**Issue by Romain-GUILLEMOT** [Ysurac/openmptcprouter#3354]
## Behavior

Depuis une semaine, je rencontre un problème récurrent avec mon installation OpenMPTCProuter qui fonctionnait sans souci depuis plus d'un an. Le message d'erreur "Le VPN ne répond pas" s'affiche de manière persistante, malgré mes tentatives de résolution.
J'ai procédé à la réinstallation complète du serveur VPS ainsi que du routeur Raspberry Pi 4 exécutant OpenMPTCProuter, mais cela n'a pas permis de résoudre le problème. L'erreur persiste et empêche l'établissement de la connexion VPN nécessaire au bon fonctionnement d'OpenMPTCProuter.
Vous trouverez ci-joint une capture d'écran illustrant le message d'erreur, ainsi que les détails de ma configuration actuelle. 

![image](https://github.com/Ysurac/openmptcprouter/assets/157109040/72daff49-a2c7-4de6-bf72-5290c3b8f930)

https://haste.bagou450.com/witaduramo.apache

## Specifications

  - OpenMPTCProuter VPS provider: LibraHost

**Comment by Ysurac** [comment]
C'est une configuration mise à jour ?
Si vous allez sur ```https://<VPSIP>:65500/``` avec un navigateur qu'est-ce qu'il affiche ?
Dans Système->OpenMPTCProuter, onglet "wizard", en cochant la case "Paramètres avancés", il faudrait ensuite cocher la case "Forcer la récupération des paramètres". En profiter pour mettre le proxy sur "Shadowsocks-Rust" et mettre le VPN sur "OpenVPN TCP".

**Comment by Ysurac** [comment]
Je demandais en fait si c'était une nouvelle installation ou une mise à jour d'une ancienne installation.
