### ISSUE TITLE
OMR not working

### ISSUE THREAD

**Issue by Yessine1200** [Ysurac/openmptcprouter#3357]
## Expected Behavior
OMR works properly.

## Current Behavior
After installing and configuring OMR correctly on both the router and VPS, I found that when I checked the status on the web interface, OMR couldn't detect the two connections I intended to aggregate, as illustrated in the image.

## Specifications

  - OpenMPTCProuter version: 0.60-6.1
  - OpenMPTCProuter VPS version: OpenMPTCProuter VPS 0.1030 (latest)
  - OpenMPTCProuter VPS provider:
  - OpenMPTCProuter platform: x86_64

![omr-error](https://github.com/Ysurac/openmptcprouter/assets/73882523/1d6b7c46-58ed-4a00-9de8-6fd95c22a4d3)

logs: 
May 15 09:54:43 OpenMPTCProuter daemon.warn openvpn(omr)[23726]: Use --help for more information.
May 15 09:54:48 OpenMPTCProuter user.notice OMR-Tracker-Server: Master server Backup_Server down (54.38.70.10)
May 15 09:54:48 OpenMPTCProuter daemon.err openvpn(omr)[24413]: Options error: You must define CA file (--ca) or CA path (--capath) and/or peer fingerprint verification (--peer-fingerprint)
May 15 09:54:48 OpenMPTCProuter daemon.warn openvpn(omr)[24413]: Use --help for more information.
May 15 09:54:53 OpenMPTCProuter daemon.err openvpn(omr)[24567]: Options error: You must define CA file (--ca) or CA path (--capath) and/or peer fingerprint verification (--peer-fingerprint)
May 15 09:54:53 OpenMPTCProuter daemon.warn openvpn(omr)[24567]: Use --help for more information.
May 15 09:54:57 OpenMPTCProuter daemon.err uhttpd[7145]: [info] luci: accepted login on /admin/system/openmptcprouter/wizard for root from 192.168.100.137
May 15 09:54:58 OpenMPTCProuter daemon.err openvpn(omr)[24799]: Options error: You must define CA file (--ca) or CA path (--capath) and/or peer fingerprint verification (--peer-fingerprint)
May 15 09:54:58 OpenMPTCProuter daemon.warn openvpn(omr)[24799]: Use --help for more information.
May 15 09:55:00 OpenMPTCProuter user.notice OMR-VPS: Can't get vps token, try later (can't ping server vps on 193.169.104.0, no server API answer on 193.169.104.0)
May 15 09:55:00 OpenMPTCProuter user.notice OMR-VPS: Can't get Backup_Server token, try later (can't ping server Backup_Server on 54.38.70.10, no server API answer on 54.38.70.10)
May 15 09:55:03 OpenMPTCProuter daemon.err openvpn(omr)[25188]: Options error: You must define CA file (--ca) or CA path (--capath) and/or peer fingerprint verification (--peer-fingerprint)
May 15 09:55:03 OpenMPTCProuter daemon.warn openvpn(omr)[25188]: Use --help for more information.
May 15 09:55:05 OpenMPTCProuter user.notice OMR-VPS: Can't get vps token, try later (can't ping server vps on 193.169.104.0, no server API answer on 193.169.104.0)
May 15 09:55:05 OpenMPTCProuter user.notice OMR-VPS: Can't get Backup_Server token, try later (can't ping server Backup_Server on 54.38.70.10, no server API answer on 54.38.70.10)
May 15 09:55:09 OpenMPTCProuter daemon.err openvpn(omr)[25527]: Options error: You must define CA file (--ca) or CA path (--capath) and/or peer fingerprint verification (--peer-fingerprint)
May 15 09:55:09 OpenMPTCProuter daemon.warn openvpn(omr)[25527]: Use --help for more information.
May 15 09:55:14 OpenMPTCProuter daemon.err openvpn(omr)[25684]: Options error: You must define CA file (--ca) or CA path (--capath) and/or peer fingerprint verification (--peer-fingerprint)
May 15 09:55:14 OpenMPTCProuter daemon.warn openvpn(omr)[25684]: Use --help for more information.
May 15 09:55:19 OpenMPTCProuter daemon.err openvpn(omr)[26276]: Options error: You must define CA file (--ca) or CA path (--capath) and/or peer fingerprint verification (--peer-fingerprint)
May 15 09:55:19 OpenMPTCProuter daemon.warn openvpn(omr)[26276]: Use --help for more information.
May 15 09:55:24 OpenMPTCProuter daemon.err openvpn(omr)[26446]: Options error: You must define CA file (--ca) or CA path (--capath) and/or peer fingerprint verification (--peer-fingerprint)
May 15 09:55:24 OpenMPTCProuter daemon.warn openvpn(omr)[26446]: Use --help for more information.
May 15 09:55:29 OpenMPTCProuter daemon.err openvpn(omr)[26574]: Options error: You must define CA file (--ca) or CA path (--capath) and/or peer fingerprint verification (--peer-fingerprint)
May 15 09:55:29 OpenMPTCProuter daemon.warn openvpn(omr)[26574]: Use --help for more information.
May 15 09:55:34 OpenMPTCProuter daemon.err openvpn(omr)[26747]: Options error: You must define CA file (--ca) or CA path (--capath) and/or peer fingerprint verification (--peer-fingerprint)
May 15 09:55:34 OpenMPTCProuter daemon.warn openvpn(omr)[26747]: Use --help for more information.
May 15 09:55:37 OpenMPTCProuter user.notice firewall.omr-server: Firewall reload, set server part firewall reloading
May 15 09:55:37 OpenMPTCProuter user.notice firewall.omr-server: Firewall reload, set server part firewall reloading
May 15 09:55:37 OpenMPTCProuter daemon.info ModemManager[28216]: hotplug: remove network interface ifb4eth1: event processed
May 15 09:55:37 OpenMPTCProuter daemon.info ModemManager[28306]: hotplug: remove network interface ifb4eth2: event processed
May 15 09:55:37 OpenMPTCProuter daemon.info ModemManager[28380]: hotplug: remove network interface ifb4eth3: event processed
May 15 09:55:37 OpenMPTCProuter daemon.info ModemManager[28558]: hotplug: add network interface SQM_IFB_e349b: event processed
May 15 09:55:38 OpenMPTCProuter daemon.info ModemManager[28651]: hotplug: remove network interface SQM_IFB_e349b: event processed
May 15 09:55:38 OpenMPTCProuter daemon.info ModemManager[28688]: hotplug: add network interface SQM_IFB_c22e9: event processed
May 15 09:55:38 OpenMPTCProuter daemon.info ModemManager[28787]: hotplug: remove network interface SQM_IFB_c22e9: event processed
May 15 09:55:38 OpenMPTCProuter daemon.info ModemManager[28826]: hotplug: add network interface ifb4eth1: event processed
May 15 09:55:38 OpenMPTCProuter daemon.info ModemManager[29050]: hotplug: add network interface SQM_IFB_ab13e: event processed
May 15 09:55:38 OpenMPTCProuter daemon.info ModemManager[29116]: hotplug: remove network interface SQM_IFB_ab13e: event processed
May 15 09:55:38 OpenMPTCProuter daemon.info ModemManager[29155]: hotplug: add network interface SQM_IFB_c0a37: event processed
May 15 09:55:38 OpenMPTCProuter daemon.info ModemManager[29213]: hotplug: remove network interface SQM_IFB_c0a37: event processed
May 15 09:55:38 OpenMPTCProuter daemon.info ModemManager[29254]: hotplug: add network interface ifb4eth2: event processed
May 15 09:55:38 OpenMPTCProuter daemon.err openvpn(omr)[29300]: Options error: You must define CA file (--ca) or CA path (--capath) and/or peer fingerprint verification (--peer-fingerprint)
May 15 09:55:38 OpenMPTCProuter daemon.warn openvpn(omr)[29300]: Use --help for more information.
May 15 09:55:38 OpenMPTCProuter user.notice omr-tracker: Launching...
May 15 09:55:38 OpenMPTCProuter daemon.info ModemManager[29590]: hotplug: add network interface SQM_IFB_fe1bd: event processed
May 15 09:55:38 OpenMPTCProuter daemon.info ModemManager[29682]: hotplug: remove network interface SQM_IFB_fe1bd: event processed
May 15 09:55:38 OpenMPTCProuter daemon.info ModemManager[29709]: hotplug: add network interface SQM_IFB_edadb: event processed
May 15 09:55:38 OpenMPTCProuter daemon.info ModemManager[29779]: hotplug: remove network interface SQM_IFB_edadb: event processed
May 15 09:55:38 OpenMPTCProuter daemon.info ModemManager[29805]: hotplug: add network interface ifb4eth3: event processed
May 15 09:55:38 OpenMPTCProuter user.notice SQM-autorate: Set config for omrvpn
May 15 09:55:38 OpenMPTCProuter user.notice unbound: default memory configuration
May 15 09:55:38 OpenMPTCProuter user.notice firewall.omr-server: Firewall reload, set server part firewall reloading
May 15 09:55:39 OpenMPTCProuter user.notice firewall.omr-server: Firewall reload, set server part firewall reloading
May 15 09:55:39 OpenMPTCProuter daemon.err openvpn(omr)[30743]: Options error: You must define CA file (--ca) or CA path (--capath) and/or peer fingerprint verification (--peer-fingerprint)
May 15 09:55:39 OpenMPTCProuter daemon.warn openvpn(omr)[30743]: Use --help for more information.
May 15 09:55:44 OpenMPTCProuter user.notice OMR-VPS: Can't get vps token, try later (can't ping server vps on 193.169.104.0, no server API answer on 193.169.104.0)
May 15 09:55:44 OpenMPTCProuter daemon.err openvpn(omr)[30885]: Options error: You must define CA file (--ca) or CA path (--capath) and/or peer fingerprint verification (--peer-fingerprint)
May 15 09:55:44 OpenMPTCProuter daemon.warn openvpn(omr)[30885]: Use --help for more information.
May 15 09:55:47 OpenMPTCProuter user.notice omr-tracker: Launched
May 15 09:55:47 OpenMPTCProuter user.notice post-tracking-001-post-tracking: omrvpn down
May 15 09:55:47 OpenMPTCProuter daemon.info vnstatd[7365]: Info: SIGTERM received, exiting.
May 15 09:55:47 OpenMPTCProuter daemon.info vnstatd[31415]: Info: vnStat daemon 2.11 (pid:31415 uid:0 gid:0 64-bit, SQLite 3.41.2)
May 15 09:55:47 OpenMPTCProuter daemon.info vnstatd[31415]: Info: Data retention: 48 5MinuteHours, 4 HourlyDays, 62 DailyDays, 25 MonthlyMonths, -1 YearlyYears, 20 TopDayEntries
May 15 09:55:47 OpenMPTCProuter daemon.info vnstatd[31415]: Info: Monitoring (3): eth3 (1000 Mbit) eth2 (1000 Mbit) eth1 (1000 Mbit) 
May 15 09:55:47 OpenMPTCProuter user.notice post-tracking-001-post-tracking: OpenVPN down, restart it
May 15 09:55:47 OpenMPTCProuter daemon.info ModemManager[31953]: hotplug: remove network interface ifb4eth1: event processed
May 15 09:55:47 OpenMPTCProuter daemon.info ModemManager[32070]: hotplug: remove network interface ifb4eth2: event processed
May 15 09:55:47 OpenMPTCProuter daemon.info ModemManager[32187]: hotplug: remove network interface ifb4eth3: event processed
May 15 09:55:47 OpenMPTCProuter daemon.err openvpn(omr)[32245]: Options error: You must define CA file (--ca) or CA path (--capath) and/or peer fingerprint verification (--peer-fingerprint)
May 15 09:55:47 OpenMPTCProuter daemon.warn openvpn(omr)[32245]: Use --help for more information.
May 15 09:55:48 OpenMPTCProuter daemon.info ModemManager[32348]: hotplug: add network interface SQM_IFB_1a919: event processed
May 15 09:55:48 OpenMPTCProuter daemon.info ModemManager[32390]: hotplug: remove network interface SQM_IFB_1a919: event processed
May 15 09:55:48 OpenMPTCProuter daemon.info ModemManager[32412]: hotplug: add network interface SQM_IFB_1d890: event processed
May 15 09:55:48 OpenMPTCProuter daemon.info ModemManager[32449]: hotplug: remove network interface SQM_IFB_1d890: event processed
May 15 09:55:48 OpenMPTCProuter daemon.info ModemManager[32474]: hotplug: add network interface ifb4eth1: event processed
May 15 09:55:48 OpenMPTCProuter daemon.info ModemManager[32622]: hotplug: add network interface SQM_IFB_c2478: event processed
May 15 09:55:48 OpenMPTCProuter daemon.info ModemManager[32664]: hotplug: remove network interface SQM_IFB_c2478: event processed
May 15 09:55:48 OpenMPTCProuter daemon.info ModemManager[32681]: hotplug: add network interface SQM_IFB_83784: event processed
May 15 09:55:48 OpenMPTCProuter daemon.info ModemManager[32723]: hotplug: remove network interface SQM_IFB_83784: event processed
May 15 09:55:48 OpenMPTCProuter daemon.info ModemManager[32749]: hotplug: add network interface ifb4eth2: event processed
May 15 09:55:48 OpenMPTCProuter daemon.info ModemManager[465]: hotplug: add network interface SQM_IFB_5315b: event processed
May 15 09:55:48 OpenMPTCProuter daemon.info ModemManager[507]: hotplug: remove network interface SQM_IFB_5315b: event processed
May 15 09:55:48 OpenMPTCProuter daemon.info ModemManager[527]: hotplug: add network interface SQM_IFB_47a4e: event processed
May 15 09:55:48 OpenMPTCProuter daemon.info ModemManager[570]: hotplug: remove network interface SQM_IFB_47a4e: event processed
May 15 09:55:48 OpenMPTCProuter daemon.info ModemManager[595]: hotplug: add network interface ifb4eth3: event processed
May 15 09:55:48 OpenMPTCProuter user.notice SQM-autorate: Set config for omrvpn
May 15 09:55:50 OpenMPTCProuter user.notice OMR-VPS: Can't get Backup_Server token, try later (can't ping server Backup_Server on 54.38.70.10, no server API answer on 54.38.70.10)
May 15 09:55:51 OpenMPTCProuter user.notice firewall.omr-server: Firewall reload, set server part firewall reloading
May 15 09:55:51 OpenMPTCProuter user.notice omr-tracker: Launching...
May 15 09:55:53 OpenMPTCProuter daemon.err openvpn(omr)[1971]: Options error: You must define CA file (--ca) or CA path (--capath) and/or peer fingerprint verification (--peer-fingerprint)
May 15 09:55:53 OpenMPTCProuter daemon.warn openvpn(omr)[1971]: Use --help for more information.
May 15 09:55:58 OpenMPTCProuter daemon.err openvpn(omr)[2145]: Options error: You must define CA file (--ca) or CA path (--capath) and/or peer fingerprint verification (--peer-fingerprint)
May 15 09:55:58 OpenMPTCProuter daemon.warn openvpn(omr)[2145]: Use --help for more information.
May 15 09:56:00 OpenMPTCProuter user.notice omr-tracke

**Comment by Ysurac** [comment]
What modems are you using ? Some external box ?
Are you under a VM ?
