### ISSUE TITLE
Some issues and their fix.(linksys wrt3200acm)

### ISSUE THREAD

**Issue by Alison110** [Ysurac/openmptcprouter#3367]
Hi, first; THANK YOU SO MUCH Ysurac,
but next; I've installed and reinstalled opentcprouter over 30 times and this is some issues and their fix.(linksys wrt3200acm)

1- clients couldn't connect to Wi-Fi because Wi-Fi can't get clients IP, so:
go to: interface⇾ devices⇾ add a bridge device, select wan at bridge ports then, in interface tab: LAN⇾ device and select bridge instead of wan.
Now you can connect to Wi-Fi 
but;

2- bypass only works on one of LAN or Wi-Fi, and now bypass only works on Wi-Fi and, not on LAN (wan) (bug).

3- fastest VPN is glorytun UDP and best proxy is xray Trojan.
But:
Xray couldn't get IP from VPS when use chacha20 encryption.
xray doesn't work along with v2ray (in my case) so you can set encryption ⇒ none or AES-256-GCM, to use xray or, use next best proxy which is v2ray with encryption.

4-somethimes gloryton UDP is down; 
I restart router and vps both if it's down, go to system ⇾startup, start and restart glorytun UDP again if it's still down I use gloryton TCP then back, use gloryton UDP

5-Never update the package from the software update, especially v2ray! (it won't able to get IP from VPS anymore)
THANK YOU SO MUCH, Ysurac.

## Specifications

  - OpenMPTCProuter version: 6, 6.1, 6.6
  - OpenMPTCProuter VPS version: 6.1&6.6 1030&1031-test
  - OpenMPTCProuter VPS provider: pq.hosting
  - OpenMPTCProuter platform: Linksys WRT3200acm
  - Country: China

**Comment by QatarMo** [comment]
my testing with latest 6.1 snapshot try useing
XRay VLESS
AES-256-GCM
Glorytun UDP
no SQM

bypass works for me with this config try it out im on x86 btw

**Comment by Alison110** [comment]
> my testing with latest 6.1 snapshot try useing XRay VLESS AES-256-GCM Glorytun UDP no SQM
> 
> bypass works for me with this config try it out im on x86 btw

Bypass works on both interfaces? LAN and WI-FI?
