### ISSUE TITLE
Aggregation Not working as Expected 

### ISSUE THREAD

**Issue by Yessine1200** [Ysurac/openmptcprouter#3371]
## Expected Behavior
Link Aggregation maximizes the capacity across all connections. (35-45M)

## Current Behavior
It seems like connections are always getting slowed down(for 4G SFR and private 5G)

## Lan1 : 4G ORANGE - 10,7M 
![Capture d’écran 2024-05-22 à 12 07 49](https://github.com/Ysurac/openmptcprouter/assets/73882523/104988c1-73e2-4253-837f-56b9d4561dfe)

## Lan2: 4G SFR (very slow)
![Capture d’écran 2024-05-22 à 11 54 24](https://github.com/Ysurac/openmptcprouter/assets/73882523/e287e093-f22a-407a-9ca0-731a5b64b3ff)

## Private 5G - 13,8M
![Capture d’écran 2024-05-22 à 11 56 46](https://github.com/Ysurac/openmptcprouter/assets/73882523/6375833a-88b1-4987-b0de-17f9abc60679)

## Aggregation - 11,4M
![Capture d’écran 2024-05-22 à 12 04 20](https://github.com/Ysurac/openmptcprouter/assets/73882523/49238927-97ee-463f-b4b4-fce4a59e7b17)
![Capture d’écran 2024-05-22 à 12 04 00](https://github.com/Ysurac/openmptcprouter/assets/73882523/68c543a5-1d2f-493c-9321-c5a28a8742ab)
It seems that the aggregation is working fine, but with limited speed for the two connections (SFR and Private 5G)

## Status page
![Capture d’écran 2024-05-22 à 11 49 33](https://github.com/Ysurac/openmptcprouter/assets/73882523/7603dca3-3c31-4395-a102-bd56d576a27b)

## Specifications

  - OpenMPTCProuter version: 6,1
  - OpenMPTCProuter VPS version: 0.1030 6.1 
  - OpenMPTCProuter VPS provider:
  - OpenMPTCProuter platform: BPI-R64

**Comment by Ysurac** [comment]
You seems to have a high load average on the BPI-R64.
You can try to add/remove connections, to check if a connection is not limiting aggregated speed.
What is the proxy used ?

**Comment by Yessine1200** [comment]
high load average is related to the RAM ?
Shadowsocks Rust for the proxy.

**Comment by Ysurac** [comment]
It's related to CPU. Encryption can be CPU intensive.

**Comment by Yessine1200** [comment]
Hello Ysurac
Is it possible that one connection could block the other connection from using all its throughput?

**Comment by Ysurac** [comment]
Should not, but this can happen

**Comment by Yessine1200** [comment]
or can be related to the router ?

**Comment by Ysurac** [comment]
yes this can be. BPI-R64 have a slow CPU.

**Comment by Yessine1200** [comment]
Because for now, when I aggregate two 4G connections, it works perfectly. I get the correct aggregation, and it's stable.
![Capture d’écran 2024-05-29 à 15 30 22](https://github.com/Ysurac/openmptcprouter/assets/73882523/9d1b53f1-ef7f-4556-9c9e-de1fedce6f88)

But when I try to aggregate the private 5G standalone and 4G connection, I notice that the 4G connection blocks the 5G standalone. However, when I run the command omr-test-speed lan2, I can get the correct throughput of the 5G connection which is 130Mpbs.
![Capture d’écran 2024-05-29 à 15 39 49](https://github.com/Ysurac/openmptcprouter/assets/73882523/0071d487-6354-489c-82ee-3909a4e47b26)

This is why I mentioned that one connection might block the other connection based on the results that I got.

**Comment by Ysurac** [comment]
You can try to run ```omr-test-speed lan2``` and ```omr-test-speed the4ginterface``` at the same time, to check the result.

**Comment by Yessine1200** [comment]
I first launched omr-test-speed lan2 for the 5G standalone: 
![Capture d’écran 2024-05-29 à 16 02 05](https://github.com/Ysurac/openmptcprouter/assets/73882523/b77dc248-af8f-4cc1-abc7-e6e637404804)

After 2 minutes, I launched omr-test-speed lan1 for the 4G connection without stopping the speed test for the 5G connection, and I observed that the throughput of the 5G connection decreased as shown below.
![Capture d’écran 2024-05-29 à 16 03 57](https://github.com/Ysurac/openmptcprouter/assets/73882523/17750418-cd62-44ed-bf91-84bb3e32f2e6)

**Comment by Ysurac** [comment]
I think you have a congestion point somewhere on the network.

**Comment by Yessine1200** [comment]
And you know how can I find this problem ?

**Comment by Ysurac** [comment]
by checking where can be the bottleneck on the network, if there is something shared with both network.

**Comment by Yessine1200** [comment]
Doesn't the BBRv3 algorithm prevent this from happening?

**Comment by Ysurac** [comment]
If it's not possible to have a higher speed due to a bottleneck, no algorithm can do anything.

**Comment by Yessine1200** [comment]
> by checking where can be the bottleneck on the network, if there is something shared with both network.

No, there is nothing shared in my network. I am using two different ISPs. It's really weird that I have this issue.

**Comment by Ysurac** [comment]
I don't know what your 5G network is using as source ISP/network type. Difficult to say anything about that.
You can test network using 2 phones or devices connected to both network and check the same way if you have same problem or not.
