### ISSUE TITLE
I want to add a wireless network card to the router

### ISSUE THREAD

**Issue by lkyddyy** [Ysurac/openmptcprouter#3378]
My router is Raspberry Pi CM4

**Comment by Ysurac** [comment]
Many drivers can be installed via System->Software menu.

**Comment by lkyddyy** [comment]
Thank you very much for your prompt reply. If you can find the driver in the software menu, would it be possible to see the wireless option in the network menu after installation, and then set it up to use

**Comment by lkyddyy** [comment]
I'm very sorry to bother you again. I did encounter a problem. I am currently using the MT7921 wireless network card and have installed the driver in the system-software menu. However, the wireless menu still does not appear. I'm not sure where the problem lies. Can you help me，I am using Raspberry Pi cm4
![1](https://github.com/Ysurac/openmptcprouter/assets/166706878/9a0bb21b-1561-4c48-b1d7-feb7817f4f91)
![2](https://github.com/Ysurac/openmptcprouter/assets/166706878/14ed98a9-a869-4b17-aa77-393c084e0697)
![3](https://github.com/Ysurac/openmptcprouter/assets/166706878/22868f6e-a99d-4844-ad57-80c68b71ee68)
