### ISSUE TITLE
@Alison110 it's not related to this issue. And these devices are not supported, you will need to compile it yourself: https://github.com/Ysurac/openmptcprouter/wiki/Create-image-for-unsupported-platform

### ISSUE THREAD

**Issue by Alison110** [Ysurac/openmptcprouter#3382]
@Alison110 it's not related to this issue. And these devices are not supported, you will need to compile it yourself: https://github.com/Ysurac/openmptcprouter/wiki/Create-image-for-unsupported-platform

_Originally posted by @Ysurac in https://github.com/Ysurac/openmptcprouter/issues/3377#issuecomment-2135572831_
            
Hello, I compiled kernel 6.6 for xiaomi 4A Gigabit via dear Ysurac instructions
but for kernel 6.1 , 

THERE ARE 48 ERRORS LIKE THESES:

ERROR: please fix feeds/packages/devel/delve/Makefile - see logs/feeds/packages/devel/delve/dump.txt for details
ERROR: please fix feeds/packages/devel/gitlab-runner/Makefile - see logs/feeds/packages/devel/gitlab-runner/dump.txt for details
.
.
.
ERROR: please fix feeds/openmptcprouter/grpcurl/Makefile - see logs/feeds/openmptcprouter/grpcurl/dump.txt for details.

AND WARNINGS WHICH IS NOTE IMPORTANT I THINK:

WARNING: Makefile 'package/utils/busybox/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/busybox/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/busybox/Makefile' has a build dependency on 'libpam', which does not exist
WARNING: Makefile 'package/feeds/openmptcprouter/openmptcprouter-full/Makefile' has a dependency on 'dnsmasq_full_ipset', which does not exist
.
.
.
WARNING: Makefile 'package/feeds/openmptcprouter/openmptcprouter-full/Makefile' has a dependency on 'kmod-crypto-lib-blake2s', which does not exist
WARNING: Makefile 'package/feeds/openmptcprouter/openmptcprouter-full/Makefile' has a dependency on 'kmod-tcp-bbr2', which does not exist
WARNING: Makefile 'package/feeds/openmptcprouter/openmptcprouter-full/Makefile' has a dependency on 'luci-i18n-base-en', which does not exist
WARNING: Makefile 'package/feeds/openmptcprouter/shadowsocks-v2ray-plugin/Makefile' has a dependency on 'golang-golang-x-crypto-dev', which does not exis

AND FINALLY RESULT:

 WARNING: Image file /home/osboxes/openmptcprouter/myplatform/6.1/source/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/tmp/openmptcprouter-v0.61-snapshot-master-c4bcee8a-r0+24843-acf40c022e-ramips-mt7621-xiaomi_mi-router-4a-gigabit-squashfs-sysupgrade.bin is too big: 44695556 > 15204352

I Have two questions:

 1- Does anyone know how to fix this feed errors?
 2- what is the command to build image from compiled file (in bin folder)?

**Comment by Ysurac** [comment]
WARNING and ERROR are not important here.
The only problem is the last one: the generated file is far too big... This mean that this rooter have a really small flash available.
This device seems to have 16MB flash and 128MB memory with MT7621 @800Mhz... For me it's far too slow with too small flash and memory to make OpenMPTCProuter running on this.

**Comment by Alison110** [comment]
Yest, exactly, the flash is too low. Thank you. Nevertheless, the compilation of Kernel 6.6 was successful, and I am curious what happens after installing mptcprouter on a weak device.
How can I build an image from compiled files (in source/bin)?
