### ISSUE TITLE
OPENMPTCPROUTER can't start 

### ISSUE THREAD

**Issue by Gregg03** [Ysurac/openmptcprouter#3384]
## Expected Behavior
I trying to start my OPENMPTCPROUTER but he can start 

## Current Behavior
I have this error Waiting for root device PARTUUID=Zaf91ce4-288B......
![IMG_2851](https://github.com/Ysurac/openmptcprouter/assets/100905752/915e2ccd-b4b2-4a16-8aac-5e7562d66ed0)

![IMG_2852](https://github.com/Ysurac/openmptcprouter/assets/100905752/4d7d8b60-20d2-49b6-8e94-176bdb880ca7)

## Specifications
  - OpenMPTCProuter version: openmptcprouter-v0.60-6.1-r0+24843-acf40c022e-x86-64-generic-ext4-combined-efi.img.gz)
  - OpenMPTCProuter platform: x86_64)

**Comment by Ysurac** [comment]
Your device only support UEFI ? No Bios legacy mode ? What is the device ?

**Comment by Gregg03** [comment]
I thing he has Bios legacy mode.
It’s a HPE Proliant DL360 Gen10  server

**Comment by Gregg03** [comment]
I think

**Comment by Ysurac** [comment]
If it has legacy bios, enable this and try the image without efi support.

**Comment by Gregg03** [comment]
I tried legacy bios with the good image ans i have that 
![IMG_2855](https://github.com/Ysurac/openmptcprouter/assets/100905752/9f1ef778-be52-4fb9-b9e5-0ffa10a2951c)

**Comment by Ysurac** [comment]
press enter, this may be finished.

**Comment by Gregg03** [comment]
when i press enter, I have nothing

**Comment by Ysurac** [comment]
Strange, this seems to be the end of the boot, when pressing enter you should get "login:"
Can you try to ping it ?

**Comment by Gregg03** [comment]
I can't ping the address 192.168.100.1
