### ISSUE TITLE
Any plan to support Ubuntu as VSP host OS other than Debian?

### ISSUE THREAD

**Issue by kansonkong** [Ysurac/openmptcprouter#3391]
**Is your enhancement proposal related to a problem? Please describe.**

Amzaon AWS doesn't provide Debian as a host OS
**Describe the solution you'd like**

will you please support Ubuntu as VPS other than Debian
**Describe alternatives you've considered**

**Additional context**

**Comment by vempire-ghost** [comment]
![image](https://github.com/Ysurac/openmptcprouter/assets/132581535/9c45a965-9f88-4db5-9ba8-30a8518ca902)
There is Debian 12 as a option in AWS.

**Comment by kansonkong** [comment]
very embarassed,  amazon aws in China doesn't provide Debian OS

**Comment by vempire-ghost** [comment]
> very embarassed, amazon aws in China doesn't provide Debian OS

I use this tutorial to convert Ubuntu to Debian on Oracle Cloud, which also doesn't have Debian as a default option. You can try using it. Although it is specific to Oracle, it might work. Remember that if something goes wrong, it could render the instance unusable, and you would have to recreate it.
https://gist.github.com/ClashTheBunny/8da6f422fc955bfd63ba1b03dd8254c8

**Comment by kansonkong** [comment]
thank you, Sir. AWS is different from OCI, I am not lucky to make it.

**Comment by vempire-ghost** [comment]
Sad to hear that.
