### ISSUE TITLE
Custom build for D-Link DIR 878

### ISSUE THREAD

**Issue by yukebrillianth** [Ysurac/openmptcprouter#3394]
Is it possible to build firmware for D-Link DIR 878 with MediaTek MT7621AT chip?

**Comment by Ysurac** [comment]
DIR 878 A1 can be compiled (other version are not supported).
You can follow https://github.com/Ysurac/openmptcprouter/wiki/Create-image-for-unsupported-platform

**Comment by Ysurac** [comment]
Anything you want, like "dir878a1". You will have to choose really the target after with ```make menuconfig```
