### ISSUE TITLE
ajouter l'option serveur de fichier sur le vps

### ISSUE THREAD

**Issue by constant1010** [Ysurac/openmptcprouter#34]
Bonjour

J'aimerais soumettre l'idée d'ajouter une option de serveur de fichier via upnp ou autre sur le vps, l'histoire d'avoir un mini cloud.

**Comment by Ysurac** [comment]
Ça sort du cadre du projet.

Chacun peut ajouter ce qu'il veut sur le VPS (ça reste une Debian) et installer n'importe quoi dessus, dans la majorité des cas ça posera pas de soucis avec OpenMPTCProuter. Il n'y aura que le firewall (shorewall) à configurer éventuellement.

Sur le routeur j'ajouterais plus tard ce qu'il faut pour installer des paquets optionnels.
