### ISSUE TITLE
Port forwarding and UPnP conflit

### ISSUE THREAD

**Issue by dnwk** [Ysurac/openmptcprouter#340]
## Expected Behavior

UPnP and Port forwarding both works

## Actual Behavior
When using Port Forwarding to hard code a port forwarding, UPnP stop working (port will not be forwarded even though OpenWRT accepted the UPnP config). 

If I did not set any rules in Port Forwarding, UPnP will work. 

## Specifications

  - OpenMPTCProuter version: v0.45.13 r0+9007-529c95cc15
  - OpenMPTCProuter VPS version: 0.89
  - OpenMPTCProuter platform: Linksys WRT32x

**Comment by Ysurac** [comment]
No idea, I don't use UPnP. But I don't know if UPnP can be used at the same time as port forwarding...
I have nothing that can use UPnP (and nobody should this :) )
