### ISSUE TITLE
Offering OpenMPTC as Wifi Hotspot

### ISSUE THREAD

**Issue by nicolaeser** [Ysurac/openmptcprouter#3408]
## Expected Behavior
- .

## Current Behavior
Hey, how can I share the OpenMPTC as Wifi Hotspot?
I would love to share a Hotspot and when you join that Hotspot you get the bonded connection of OpenMPTC!

Regards

## Specifications
- OpenMPTCProuter version: v0.6
- OpenMPTCProuter VPS version: My Console shows: < OpenMPTCProuter VPS 0.1030 >
- OpenMPTCProuter VPS provider: NexoSystems
- OpenMPTCProuter platform: RPI3 (my one), RPI5 (my friends one)

**Comment by nicolaeser** [comment]
![grafik](https://github.com/Ysurac/openmptcprouter/assets/67909777/eeb2b4b8-f58e-404a-a1a8-0d2d422b3342)

It isn't connecting! Nothing happens except it is shown as loading.

**Comment by stwr** [comment]
Have you tried adding the wifi interface to the lan firewall zone?

**Comment by nicolaeser** [comment]
@stwr How would I do that? :)

**Comment by nicolaeser** [comment]
So I can look if i did that

**Comment by Ysurac** [comment]
You can maybe look at this doc: https://github.com/Ysurac/openmptcprouter/wiki/Configure-Wifi

**Comment by nicolaeser** [comment]
@Ysurac Yeah seems like it isnt possible with only one ethernet port. What about Orange Pi? Is there an image for example for the Orange Pi 5+

**Comment by Ysurac** [comment]
This example was made on a RPI, so only one port.
