### ISSUE TITLE
Unable to aggregate routes during UDP transmission

### ISSUE THREAD

**Issue by YQW1504040201** [Ysurac/openmptcprouter#3417]
I used client access to access the server through VPS and found that link aggregation was not possible. The iperf command used is as follows：
iperf3 -s -p 5000
iperf3 -c 47.92.231.171 -p 5000 -t 600  -b 100M -u

![_cgi-bin_mmwebwx-bin_webwxgetmsgimg  MsgID=5892883779822924275 skey=@crypt_1e807b26_d800c6352a054a32b7e7ec9035a66d1b mmweb_appid=wx_webfilehelper](https://github.com/Ysurac/openmptcprouter/assets/68832284/c64f8b68-cbce-4565-a39e-4e040bd1bab3)

From the following, it can be seen that there is only one SIM card, and the other SIM cards do not share the load

![_cgi-bin_mmwebwx-bin_webwxgetmsgimg  MsgID=6290771171096058405 skey=@crypt_1e807b26_d800c6352a054a32b7e7ec9035a66d1b mmweb_appid=wx_webfilehelper](https://github.com/Ysurac/openmptcprouter/assets/68832284/d009f9b8-28b5-4d1c-a082-c96ebeb079e8)

But when I use TCP, multiple SIM cards will evenly share the load, just like changing the command to this：

iperf3 -s -p 5000
iperf3 -c 47.92.231.171 -p 5000 -t 600  -b 100M 
Has anyone encountered a similar problem？

**Comment by Ysurac** [comment]
This was not open in the right category.
Please add the template or open it again in right category and use the template.
The template is need to know release, kernel,...
