### ISSUE TITLE
Stream Inbound VPN

### ISSUE THREAD

**Issue by Majaxx** [Ysurac/openmptcprouter#3418]
## Expected Behavior
Throughput aggregation from remote access (example of service: home assistant, emby, nextcloud)

## Current Behavior
The upload rate from remote access is not aggregated. it uses only one wan

## Specifications

OpenMPTCProuter version: 0.60-6.1
OpenMPTCProuter VPS version: 0.10.30
OpenMPTCProuter VPS provider: PulseHeberg
Country: FR
OpenMPTCProuter platform: Proxmox

**Comment by Ysurac** [comment]
What is the VPN used ? You can try others in System->OpenMPTCProuter, Wizard tab, "Advanced settings" checkbox.

**Comment by Majaxx** [comment]
I use openvpn tcp 
I no longer have the problem, I applied the firewall rules again
