### ISSUE TITLE
Ftp disconnect

### ISSUE THREAD

**Issue by QuaigonSid** [Ysurac/openmptcprouter#342]
## Expected Behavior

Ftp download a entire file with no disconnect

## Actual Behavior

Ftp disconnect after some time of downloading 
(file bigher than 1go)

Error log : mptcp_detect_mapping Mappings do not match!

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - OpenMPTCProuter version: Last
  - OpenMPTCProuter VPS version: Last
  - OpenMPTCProuter platform: rpi 3 b+

    Wan1 : free adsl
     Wan2 : bouygues 4g

  Is the random latency of the 4g the base of the problem?

**Comment by Ysurac** [comment]
You should latest release, v0.46.1

**Comment by QuaigonSid** [comment]
Okay! I will...
It's version 0.46.2 and 0.90 for the vps. 

I will try ftp connection!

++

**Comment by QuaigonSid** [comment]
Nope... Dosen't work anymore... Always the same error : mapping doesn't match...

**Comment by Ysurac** [comment]
I'm not able to reproduce the error.
Can you give me the result of ```uci show network``` via SSH on OpenMPTCProuter ?
