### ISSUE TITLE
MPTCP aggregation does not occur when using iperf

### ISSUE THREAD

**Issue by Raquel1L** [Ysurac/openmptcprouter#3433]
## Expected Behavior
I've used Iperf with TCP, and the VM's packet capture shows only TCP packets. Shouldn't it be showing MPTCP?

The command I ran on the laptop was:
iperf -c <server_ip> -p 59990 -b 5M -t 10

and on the GC VM I ran
iperf -s -p 59990
sudo tcpdump -i any -w packets.pcap

## Current Behavior
How can I use Iperf from a laptop to the VM with MPTCP working as expected?

<img width="765" alt="Captura de ecrã 2024-07-02, às 12 37 59" src="https://github.com/Ysurac/openmptcprouter/assets/102439111/7857deca-aa5c-48c9-9f41-5a392b4704ce">

## Specifications

  - OpenMPTCProuter version: v0.59.1
  - OpenMPTCProuter VPS version: 0.1028
  - OpenMPTCProuter VPS provider: GCP
  - OpenMPTCProuter platform: RPI4

**Comment by Ysurac** [comment]
mptcp is not enabled by default on iperf you need to use the "--mptcp" flag. Not sure if this was available on v0.59.1

**Comment by taylord0ng** [comment]
> mptcp is not enabled by default on iperf you need to use the "--mptcp" flag. Not sure if this was available on v0.59.1

when use "--mptcp" flag return "iperf3: unrecognized option: mptcp", this way is not correct?
any i used "--multipath" flag, the traffic also transfer on one ethernet
OpenMPTCProuter version: v0.60-6.1 x86-64
![image](https://github.com/Ysurac/openmptcprouter/assets/9444710/67a91e76-3f0d-41bc-84ab-472fe7344925)

**Comment by Ysurac** [comment]
You need to have the flag enabled on both side.
