### ISSUE TITLE
How does UDP work at the moment?

### ISSUE THREAD

**Issue by AltayAkkus** [Ysurac/openmptcprouter#3434]
Hey guys,
I have read through a lot of UDP related issues here, and @Ysurac always answered that this is MPTCP and UDP is slower than TCP etc. but pointed to other solutions such as Glorytun or V2ray.

I have read through Glorytun and V2ray, but the documentation of V2Ray is a bit sparse in the English language, and I didn't really get smarter through it.

I have OpenMPTCPRouter installed and my Raspberry Pi, and it works like a charm, but how my UDP Traffic is actually leaving my device is still a mystery to me. Can maybe someone enlighten me, what is the best way to integrate Multi-Path UDP into OpenWRT? V2Ray seems mature and seems to support QUIC, but I really don't know.

Best regards,
Altay

**Comment by Ysurac** [comment]
V2Ray or XRay use quic-go that doesn't support Multipath Quic (that is also still a RFC draft).
By default UDP use the VPN set in wizard that is used as default gateway.
If V2Ray or XRay is used as proxy, they support UDP over TCP and so this can be used.

**Comment by AltayAkkus** [comment]
> V2Ray or XRay use quic-go that doesn't support Multipath Quic (that is also still a RFC draft).

So If I stream 1 Gigabyte of UDP out of my OpenMPTCP it just "flows" over one path? (the master?)
Is UDP over TCP the only option for UDP over multiple WAN legs?

**Comment by Ysurac** [comment]
If you set Quic support on V2Ray or Xray, yes, no multpath support here.
Else with protocols available in OpenMPTCProuter no problem: they are all over TCP.

Glorytun UDP is working in somecase and it's UDP over UDP with multipath support. Same for MLVPN.

**Comment by AltayAkkus** [comment]
Sorry you pester you, you're really doing gods work with this project, but:
What would you recommend for a use-case that is UDP heavy? Huge traffic spikes?
UDP over TCP, or Glorytun or MLVPN?

**Comment by Ysurac** [comment]
I recommend to test. For now there is no ideal solution.
