### ISSUE TITLE
RPI4B is in Read-Only mode, anyway to fix it ?

### ISSUE THREAD

**Issue by viorizz** [Ysurac/openmptcprouter#3435]
## Expected Behavior

RPI4B is supposed to run normally without read-only on the FS

## Current Behavior

RPI4B is running with FS in read-only :

![image](https://github.com/Ysurac/openmptcprouter/assets/124614850/ad3bc19a-9fab-45a3-8363-747e36ebe47d)

## Specifications

  - OpenMPTCProuter version: v0.60-6.1 r0+24843-acf40c022e
  - OpenMPTCProuter VPS version:   v0.1030 6.1.0-21-cloud-amd64
  - OpenMPTCProuter VPS provider: Infomaniak
  - OpenMPTCProuter platform:  RPI4B

## Explanations
I think it might have happend because I unplugged the board. But now I can't make any modifications to the router. And I don't understand why that's happening. If I have to reinstall the whole router. Is there a way I can keep those config file in some way ?

I don't really want to go and redo all my config.

Thanks.

**Comment by fareign** [comment]
use squashfs-factory firmware

**Comment by w453y** [comment]
That happens to me too, when I unplug it directly. But it can be fixed by running the following command.
SSH into the router.
`e2fsck /dev/mmcblk0p2`
then reboot it from the terminal, which will solve the issue.
