### ISSUE TITLE
TCP and UDP Traffic Management

### ISSUE THREAD

**Issue by YB1200** [Ysurac/openmptcprouter#3436]
Will the aggregated traffic (TCP & UDP) be transferred by the tunnel created by the default VPN, or will TCP be transferred through the tunnel created for Shadowsocks and UDP through the tunnel created by the default VPN?
Because as I noticed is the creation of gt-tun0 with the IP address 10.255.255.1 and it's for the default VPN.

**Comment by Ysurac** [comment]
By default, TCP use the proxy (ShadowSocks-Rust in latest release) and everything else use the VPN (OpenVPN TCP in latest release).
gt-tun0 is Glorytun TCP on VPS side, all VPNs server are created and have interfaces. It was the default VPN in previous releases.

**Comment by YB1200** [comment]
Thanks for your reply. Regarding the hardware, the QNAP QHora-301W router seems powerful in terms of CPU. What is the maximum bandwidth that it can aggregate? Additionally, does the Wi-Fi module work with OMR? Would you recommend it?

**Comment by Ysurac** [comment]
No idea, I didn't make much tests on it, and it seems there is issues with 10G interfaces from others issues.
