### ISSUE TITLE
What's difference between Shadowsocks and Shadowsocks-Rust 2022

### ISSUE THREAD

**Issue by longxi0412** [Ysurac/openmptcprouter#3437]
What's difference between Shadowsocks and Shadowsocks-Rust 2022
VPS Setting/Advanced Setting/Proxy Setting/
Shadowsocks can visit internet(it can't visit the internet if i chane the Shadowsock to Shadowsocks-Rust 2022)

![OK](https://github.com/Ysurac/openmptcprouter/assets/33534707/e0b282f1-e7a6-4591-afd3-fe9e4443ba0b)
![BAD](https://github.com/Ysurac/openmptcprouter/assets/33534707/5ab901cf-62f5-4b28-8b9a-7f2e05d16f3c)

**Comment by Ysurac** [comment]
Shadowsocks-Rust use new Shadowsocks 2022 protocol.
It should work, direct output mean an IP from one of  your connection is used.
You can also try Snapshot 0.61 that may fix (or not) the issue.

**Comment by longxi0412** [comment]
> Shadowsocks-Rust use new Shadowsocks 2022 protocol. It should work, direct output mean an IP from one of your connection is used. You can also try Snapshot 0.61 that may fix (or not) the issue.

Thanks for your reply,

**Comment by mrkaffeine92** [comment]
> Shadowsocks-Rust use new Shadowsocks 2022 protocol. It should work, direct output mean an IP from one of your connection is used. You can also try Snapshot 0.61 that may fix (or not) the issue.

I made the decision to try 0.61 and am very pleased with it so far.
