### ISSUE TITLE
Website rejects connection on first load

### ISSUE THREAD

**Issue by Pixelramp** [Ysurac/openmptcprouter#3443]
## Expected Behavior
- Website should load without any issues

## Current Behavior
- Many websites (not all) are rejecting the connection. After refreshing the website, it loads without any issues. (ERR_CONNECTION_REFUSED)
- Some images are not being loaded
- Log gives me many (nftset inet fw4 omr_dscp_cs2_6 Error: Could not resolve hostname: Name has no usable address). But I don't know it this is related
## Specifications

  - OpenMPTCProuter version: v0.61-snapshot-6.6 r0+26695-820823198d
  - OpenMPTCProuter VPS version: 0.1030 6.1.0-18-cloud-amd64
  - OpenMPTCProuter VPS provider: AWS
  - OpenMPTCProuter platform: N100

What i've tried:
 Changing DNS to Google and Cloudflare

**Comment by Ysurac** [comment]
What is the proxy used ?

**Comment by Pixelramp** [comment]
> What is the proxy used ?

Shadowsocks-Rust 2022

**Comment by Ysurac** [comment]
I just fixed an issue on firewall rules for Shadowsocks-Rust, this may be the problem.
A new image is compiling.

**Comment by Pixelramp** [comment]
I switched to only using Shadowsocks, and the problem is no longer present. Are there any disadvantages to using Shadowsocks, or can I just continue using it?


I'll try out the updated image later.

> I just fixed an issue on firewall rules for Shadowsocks-Rust, this may be the problem. A new image is compiling.

**Comment by Ysurac** [comment]
Shadowsocks-Rust use latest Shadowsocks protocol (more secure) and is multi threated (so far better if you have more than one core available). It also give a better speed in most case.

**Comment by Pixelramp** [comment]
Updated to the new image, seems to be fixed. I'll report back if there is any problerm remaining. Thanks for the quick fix!
