### ISSUE TITLE
Cannot write to ‘-’ (Broken pipe)

### ISSUE THREAD

**Issue by mvmaksnet** [Ysurac/openmptcprouter#3445]
## Specifications

  - OpenMPTCProuter version: 
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter VPS provider:
  - OpenMPTCProuter platform:

**Comment by mvmaksnet** [comment]
Don't know what happens with creating issue ticket...
Problem is when I tried to install VPS server on new debian 12 bookworm.
Problem is:

E: Sub-process /usr/bin/dpkg returned an error code (1)
-                    89%[================>   ]  79.16K  --.-KB/s    in 1.8s


Cannot write to ‘-’ (Broken pipe).

**Comment by Ysurac** [comment]
What is the command you use ?
Did you try:
 ```
wget https://www.openmptcprouter.com/server/debian-x86_64.sh
KERNEL="6.1" sh debian-x86_64.sh
```

**Comment by mvmaksnet** [comment]
Yes.

**Comment by Ysurac** [comment]
Sorry for late answer, I would need more log in this case.
