### ISSUE TITLE
Upload speed 

### ISSUE THREAD

**Issue by zicochaos** [Ysurac/openmptcprouter#345]
## Expected Behavior

Upload speed via both interfaces 

## Actual Behavior

Upload is going via one interface 

## Steps to Reproduce the Problem

  1. Any speed test 
  
 

## Specifications

  - OpenMPTCProuter version:  v0.45.16 r0+9007-529c95cc15
  - OpenMPTCProuter VPS version: (Last is not a version)
  - OpenMPTCProuter platform: x86_64)

![screenshot 2019-02-05 14 16 34](https://user-images.githubusercontent.com/23367003/52279170-d9389f80-2950-11e9-83d2-49fd99147ff5.png)

**Comment by Ysurac** [comment]
Speed tests are not really good to check upload speed with MPTCP. You should try by uploading some real data.

**Comment by zicochaos** [comment]
Same result. Is any way to choose interface for upload?
