### ISSUE TITLE
Help understanding better system/OpenMPTCPRouter/Advanced Settings/Master interface selection behaviour

### ISSUE THREAD

**Issue by Brazzo978** [Ysurac/openmptcprouter#3457]
Hi, i am trying to understand how the various option in the Master interface selection work,(correct me if i am wrong ):

**No change**: Master interface is not changed no matter what happens
**Balancing**: Master interface is chosen each X times as the interface with the lowest ping , also in case the vps goes down connection are load balanced.
**Dynamic change**: Master interface is changed only if the actual master has problem (goes down or has high ping ) original master is not restored once is back in this case.
**On wizard change**: Keeps the master interface selected in the wizard (???)

Thanks for the patience

## Specifications

  - OpenMPTCProuter version: 0.60 5.4
  - OpenMPTCProuter VPS version: 1031-test
  - OpenMPTCProuter VPS provider: revoluitionP
  - OpenMPTCProuter platform: x86-64

**Comment by Ysurac** [comment]
On Balancing mode, there is no change, it's a load balancing route to the VPS (or internet when VPS down).
Master is only in fact the default gateway.

In all cases, you should use Balancing mode.
Other modes will be removed in future.
