### ISSUE TITLE
5353 port is in used for unknown process

### ISSUE THREAD

**Issue by dnwk** [Ysurac/openmptcprouter#346]
daemon.info /usr/bin/ss-tunnel[13995]: initializing ciphers... none
Wed Feb  6 07:02:11 2019 daemon.info /usr/bin/ss-tunnel[13995]: listening at 0.0.0.0:5353
Wed Feb  6 07:02:11 2019 daemon.err /usr/bin/ss-tunnel[13995]: bind: Address in use
Wed Feb  6 07:02:11 2019 daemon.err /usr/bin/ss-tunnel[13995]: bind() error

Looks like something is taking up 5353 port so that SS for DNS doesn't work. Can't figure out which process is blocking it. Any idea?

## Specifications

  - OpenMPTCProuter version: (Last is not a version) 0.46.2
  - OpenMPTCProuter VPS version: (Last is not a version) 0.89
  - OpenMPTCProuter platform: (RPI2/RPI3/x86/x86_64) Linksys WRT32X

**Comment by Ysurac** [comment]
Port is already used by dnsmasq. You don't have to enable the ss-tunnel.
