### ISSUE TITLE
Old issue still happening in 0.46.2

### ISSUE THREAD

**Issue by dnwk** [Ysurac/openmptcprouter#347]
Should be fixed in latest release.

_Originally posted by @Ysurac in https://github.com/Ysurac/openmptcprouter/issues/313#issuecomment-453855163_

**Comment by dnwk** [comment]
![s3](https://user-images.githubusercontent.com/3439281/52325745-07db6800-299b-11e9-8300-165f1ec5530f.png)

**Comment by Ysurac** [comment]
Duplicate of #313
