### ISSUE TITLE
Can,t get public IP address from Shadowsocks

### ISSUE THREAD

**Issue by sidelong** [Ysurac/openmptcprouter#3472]
## Expected Behavior
I have been using openmptcprouter for about 3 years now, so I know what the normal behaviour should be
in 'System/openmptcprouter/status' all tick boxes should show green tick, and no error messages should be seen

## Current Behavior

in 'openmptcprouter. the following error message appears: "Cannot get public IP address from Shadowsocks"

## Specifications

  - OpenMPTCProuter version: openmptcprouter-v0.60-6.1-r0+24843-acf40c022e-bcm27xx-bcm2711-rpi-4-ext4-sysupgrade.img.gz
  - OpenMPTCProuter VPS version: wget -O - https://www.openmptcprouter.com/server/debian-x86_64.sh | KERNEL="6.1" sh
  - OpenMPTCProuter VPS provider: Digital Ocean
  - OpenMPTCProuter platform: RPI4

**Comment by sidelong** [comment]
After updating bot VPS (Digital Ocean) and Raspberry Pi (4B, 64 bit) to latest firmware all seems fine, except that this message shows up in VPS details on Dasboard. Is this a problem - everything seems to be working well? What could be causing it?

**Comment by Ysurac** [comment]
Please complete the template.

**Comment by sidelong** [comment]
One additional remark. Having read through some of the discussions on upgrading, having started by using the sysupgrading route and experiencing errors, I upgraded via the 'System/Backup/Flash Firmware' route. this was successful as far as I can assess, except for the error message mentioned above.

**Comment by Ysurac** [comment]
What is the proxy you use ? Shadowsocks-libev or Shadowsocks-Rust ? Shadowsocks-Rust is the new default.
You have still issue if you validate again the wizard ?

**Comment by sidelong** [comment]
Bonjour,

 

Thank you for responding. I changed the default proxy to Shadowsocks-Rust and revalidated the wizard. Now all is fine, the error message no longer appears.

 

Best regards,

Mike Phillips
