### ISSUE TITLE
RUTM52

### ISSUE THREAD

**Issue by Yessine1200** [Ysurac/openmptcprouter#3474]
**Is this request related to a missing driver support for a particular hardware platform, SoC or board? Please describe.**
Hello Ysurac,
I recently received an engineering sample from Teltonika, the RUTM52, which is not yet available for purchase online. This new device features two 5G modems (RG501Q-EU). It has a MediaTek MT7621A CPU, Dual-Core, 880 MHz, MIPS1004Kc (which seems quite slow), 256 MB of DDR3 RAM, and storage consisting of a 16 MB serial NOR flash and a 256 MB serial NAND flash.
I am currently attempting to generate an OMR image for it, but I have been unsuccessful with both kernel versions 6.6 and 6.1.
The Teltonika support team informed me that there is no OpenWrt support for this device. However, there is the RUTOS SDK, which is also based on OpenWrt. I might be able to get it to work by using the RUTOS SDK instead of OpenWrt and making some modifications when building OpenMPTCProuter and now I have no idea what I have to do.
It has nearly the same specifications as the RUTM50 for more information : https://teltonika-networks.com/products/routers/rutm50

**Describe why you are asking for this support?**
It has 2 5G modems, and I think it will be a good choice for the future.

**Comment by Ysurac** [comment]
A really slow CPU... Quite the same as Ubiquiti EdgeRouter X that is already supported but, I think, really too slow for normal usage...
It's not really easy to port. I think they are using an old kernel in RUTOS ?
You will have to add missing kernel patches/dts/... from RUTOS to OpenMPTCProuter and make all necessary changes.

**Comment by Yessine1200** [comment]
Even slow for aggregating two 4G modems? Yes, they use kernel 5.1.
Is it the same as you do for RUTX12/50? Do you have any documentation on how to do that? Which files do I need to modify in OMR? (I don't have much experience with this type of subject.)

**Comment by suyuan168** [comment]
> Even slow for aggregating two 4G modems? Yes, they use kernel 5.1. Is it the same as you do for RUTX12/50? Do you have any documentation on how to do that? Which files do I need to modify in OMR? (I don't have much experience with this type of subject.)

hi：
MediaTek MT7621A CPU, Dual-Core, 880 MHz, this configuration is indeed slow. Even with dual 5G, if successfully ported and adapted using Openmptcprouter, the speed won't exceed 50 Mbps. You can try Shenzhen Zhibotong Electronics Co., Ltd., model Z8102AX, which has already been adapted and is available for direct download. It utilizes the MT7981B solution, ARM Cortex-A53 dual-core CPU clocked up to 1.3 GHz, featuring an independent WIFI6 chip (MT7976CN) with speeds up to 3000 Mbps. It includes high-speed 1GB DDR4 RAM paired with 128MB SPI NAND Flash. It offers 1 WAN + 4 LAN 1000M adaptive Ethernet ports, supporting Auto MDI/MDIX. It supports "one-click flashing mode"; pressing and holding the reset button allows access to rescue flashing mode. It also supports "one-click" MESH networking. It has built-in 2 M.2 standard interfaces for connecting 5G mobile communication modules and an external standard Nano SIM card (mini card) interface.

**Comment by Yessine1200** [comment]
Hi @suyuan168 
It looks like good hardware, especially since it supports two 5G modems. Have you tested it with OpenMPTCProuter? If so, could you provide me with the results you obtained?

**Comment by suyuan168** [comment]
> Hi @suyuan168 It looks like good hardware, especially since it supports two 5G modems. Have you tested it with OpenMPTCProuter? If so, could you provide me with the results you obtained?

![image](https://github.com/user-attachments/assets/8f7831e7-b75c-4c67-9fd9-0ab6544bdbe1)
I have tested it myself using the RM520N-GL module that I purchased. It features the Qualcomm X62 global version, along with custom-designed antennas and casing. I've customized the Openmptcprouter system with the latest snapshot version. My VPS has a speed of 1000 Mbps, and I achieved an aggregation speed of 300 Mbps. I procured their produced motherboard and customized its design in China, including the casing and built-in antennas, to create a portable product.

**Comment by Yessine1200** [comment]
Hi @suyuan168,
The device looks promising! However, I noticed you mentioned achieving an aggregation speed of 300 Mbps—was this with two 5G modems? Is it possible to reach 500 Mbps?
I came across this device on Alibaba: [ZBT Z8102AX-T](https://www.alibaba.com/product-detail/ZBT-Z8102AX-T-Gigabit-Port-dual_1600916406031.html). It seems quite affordable, but does this price not include the 5G modems?
Additionally, if possible, could you share the OMR image for the device? I’m interested in purchasing it soon for testing.
Thank you!

**Comment by Yessine1200** [comment]
Hi @Ysurac 
Do you know how much aggregated throughput the ZBT Z8102AX can achieve?

**Comment by suyuan168** [comment]
> Hi @Ysurac Do you know how much aggregated throughput the ZBT Z8102AX can achieve?

The 5G communication module is not included by default, and the maximum speed can reach 350mbps.
@Ysurac test ok，https://www.openmptcprouter.com/download

**Comment by Yessine1200** [comment]
Hi @suyuan168 
Thank you for your response.
And for WiFi, it works ?

**Comment by Ysurac** [comment]
Wifi works yes. There is 2 radios, one on 2.4Ghz and one on 5.2Ghz

**Comment by Yessine1200** [comment]
Good, I just purchased this one with two 5G RM520 modules: [link](https://www.alibaba.com/product-detail/Unlocked-Industrial-Dual-Sim-1GB-DDR4_1600910150666.html?spm=a2756.trade-list-buyer.0.0.174176e9ijIulA). I will test it and get back to you with feedback.
Any tips before installing OMR on it ?

**Comment by Yessine1200** [comment]
Hello Ysurac,
I also came across this device from ZBT: [ZBT Factory New Issued 5G Router](https://www.alibaba.com/product-detail/ZBT-Factory-New-Issued-5g-Router_1600365408587.html?spm=a2700.details.you_may_like.3.2e6912941LCRdG). It features a powerful CPU: IPQ8072A chipset with a Quad-core ARM Cortex A53 CPU, running at a main frequency of up to 2.2 GHz.
Do you think it can achieve 1 Gbps with aggregation?

**Comment by suyuan168** [comment]
<img width="581" alt="image" src="https://github.com/user-attachments/assets/e2cf5b2e-9eb2-400e-8deb-9ce8f09f80d9">
I have a piece of hardware I developed based on Openmptcprouter, also using ipq8072a, and theoretically I can get 600mbps with the 6.6 kernel currently tested.
I can get 1300mbps with the 5.4 kernel.

**Comment by Yessine1200** [comment]
Hi @suyuan168,
Thanks for your response. And it supports AES instructions ?
Also, I need to generate an image on my own? I can't find it among the images generated by Ysurac.

**Comment by suyuan168** [comment]
You need to find a way to generate the image yourself. Usually, each hardware of openwrt is not universal. Support ASE

**Comment by Yessine1200** [comment]
ok thanks, maybe I will buy one and test it. Any tips on how I can generate the image ?

**Comment by Bernd-that-bread** [comment]
**Dual Power, Unmatched Value: Teltonika RUTM52 5G router Unveiled**
![teltonika-rutm52-dual-5G-router](https://github.com/user-attachments/assets/c8e38452-727d-47f1-8acd-c43af9948379)
As industries become more connected, businesses need reliable, high-speed internet that won’t drain their budgets. Teltonika’s new RUTM52 dual 5G router is here to meet those needs, bringing the full force of dual 5G power to mission-critical applications.

https://voip.world/Teltonika-RUTM52-high-performance-Dual-cellular-5G-industrial-router-with-2x-5G-modem-and-dual-SIM-VoIPDistri-com-European-specialized-distributor

**Comment by tuskydev** [comment]
Hi, by the looks of this thread it seems the hardware in the RUTM52 may be too weak to handle openMPTCProuter. 
Is this the case? It's been a year since this thread, have there been any updates or interest to get an official image out for it? 
Thanks

**Comment by Ysurac** [comment]
Too slow so this will not be supported.

**Comment by tuskydev** [comment]
Why is the RUTM50 supported and not this?

**Comment by tuskydev** [comment]
Okay, RUTX50 it is then! Thanks for your reply.

**Comment by Bernd-that-bread** [comment]
RUTM55 is a brand new router witz I/O interfaces
https://voip.world/Teltonika-RUTM55-Industrial-5G-Cellular-WiFi-Router-WiFi-5-and-GNSS-Positioning-RS232/RS485-I/O-4x-Gigabit-Ethernet-Dual-SIM-eSIM

Am Mi., 9. Juli 2025 um 21:22 Uhr schrieb Mario Fernandez <
***@***.***>:
