### ISSUE TITLE
Remote syslog functionality does not work

### ISSUE THREAD

**Issue by FPi-sh** [Ysurac/openmptcprouter#3475]
## Expected Behavior
After setting log_ip, log_port and log_proto from cli or from gui, logread entries should be sent to remote syslog.

## Current Behavior
Functionality does not work and syslogd daemon does not start because -R flag isn't supported. ("syslogd: unrecognized option: R")

## Possible Solution
Replace syslogd with logd

## Steps to Reproduce the Problem

  1. Set a remote syslog
  2. Check system log (does not work anymore)
  3. Check remote server (no log appears)

## Specifications

  - OpenMPTCProuter version: 0.60
  - OpenMPTCProuter VPS version: 0.1030
  - OpenMPTCProuter VPS provider:
  - OpenMPTCProuter platform: x86_64
  - Country:

**Comment by Ysurac** [comment]
It's available in v0.61 snapshot image, so will be in next release.
