### ISSUE TITLE
Latency

### ISSUE THREAD

**Issue by YB1200** [Ysurac/openmptcprouter#3479]
Is the latency displayed on the status page for the WAN connection measured from OMR to the ISP of the connection?

**Comment by Ysurac** [comment]
It's the latency between WAN to the VPS.

**Comment by YB1200** [comment]
Where exactly I can see the implemented code in omr-feeds ?

**Comment by Ysurac** [comment]
https://github.com/Ysurac/openmptcprouter-feeds/blob/develop/openmptcprouter-api/files/usr/libexec/rpcd/openmptcprouter

**Comment by YB1200** [comment]
And why exactly between WAN to VPS not OMR to WAN ?

**Comment by Ysurac** [comment]
Because we don't really care, should be always near 0 at it's local.
