### ISSUE TITLE
Scheduler Selection and Wireless Configuration Issue in OpenMPTCPRouter

### ISSUE THREAD

**Issue by Raquel1L** [Ysurac/openmptcprouter#3480]
## Current Behavior
In March, I successfully used the image openmptcprouter-v0.59.1-5.4-r0+16594-ce92de8c8c-bcm27xx-bcm2711-rpi-4-ext4-factory.img on my Raspberry Pi. In June, I updated to the current version, openmptcprouter-v0.60-6.1-r0+24843-acf40c022e-bcm27xx-bcm2711-rpi-4-ext4-factory 2.img, and confirmed today that it is functioning correctly.

However, version v0.59.1 includes a feature critical to my needs: the ability to select multiple schedulers. In contrast, version v0.60 offers only a single, default scheduler.
As a result, I reinstalled v0.59.1 from a copy stored in my downloads folder since March. Upon doing so, I encountered the following error on the wireless network configuration page (To get the error I only went to the network/wireless tab):

TypeError: Right-hand side of 'instanceof' is not an object

<img width="1464" alt="Captura de ecrã 2024-08-05, às 17 41 07" src="https://github.com/user-attachments/assets/58a3a86f-df85-4031-8866-2cf5124dd2cd">

This error prevents any further actions on this tab, blocking the addition and configuration of a wireless network.
To resolve this issue, I installed the image openmptcprouter-v0.60-5.4-r0+16862-170d9e447d-bcm27xx-bcm2711-rpi-4-ext4-factory.img, but the same error persisted, and I remained unable to configure a wireless network.
This issue does not occur with the current version openmptcprouter-v0.60-6.1-r0+24843-acf40c022e-bcm27xx-bcm2711-rpi-4-ext4-factory 2.img. However, I require the ability to test with multiple schedulers.

I am trying v0.61 snapshot image, with 6.6 kernel, where the schedulers are back, and for that I run this command on RPi4: wget -O - https://www.openmptcprouter.com/server-test/debian-x86_64.sh | KERNEL="6.6" sh

However, it didn't worked. The openMPTCProuter web interface page doesn't load.

Can you confirm that I'm running the correct command?

## Specifications

  - OpenMPTCProuter version: v0.60
  - OpenMPTCProuter VPS version: 0.1028
  - OpenMPTCProuter VPS provider: GCP
  - OpenMPTCProuter platform: RPI4

**Comment by Ysurac** [comment]
I'm running 0.59.1 on a RPI4 and can't reproduce the issue. Difficult to help here... You don't have any USB dongle ?
What you mean for 6.6 web interface ?

**Comment by Ysurac** [comment]
For snapshots: https://github.com/Ysurac/openmptcprouter/wiki/Snapshots
For 0.59.1: https://download.openmptcprouter.com/release/

**Comment by Raquel1L** [comment]
I've already seen this page https://download.openmptcprouter.com/release/ and I can't find a way to download v0.59.1 image. When I click on the v0.59.1 folder, the option to download the image never appears

**Comment by Ysurac** [comment]
I don't really understand what you mean... For v0.59.1 on RPI4, images are all here: https://download.openmptcprouter.com/release/v0.59.1/rpi4/targets/bcm27xx/bcm2711/
