### ISSUE TITLE
OpenMPTCP shows an red error icon, but no error

### ISSUE THREAD

**Issue by JxnLexn** [Ysurac/openmptcprouter#3486]
## Expected Behavior

Both WAN should have a green checkmark

## Current Behavior

The 5G Connections shows a red cross, as if there is any error, but not showing any specific error.
![Overview](https://github.com/user-attachments/assets/a676bab8-de76-42ae-9759-fdbecfa84f4f)
![Settings](https://github.com/user-attachments/assets/93f6be34-35ee-4186-818d-b337b8efab86)

## Specifications

  - OpenMPTCProuter version: v0.60-6.1 r0+24843-acf40c022e
  - OpenMPTCProuter VPS version: 0.1030 6.1.0-23-cloud-amd64
  - OpenMPTCProuter VPS provider: Strato (DE)
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
What do you have in Status->System log ?
