### ISSUE TITLE
The MPTCP tab in Luci doesn't load.

### ISSUE THREAD

**Issue by vempire-ghost** [Ysurac/openmptcprouter#3487]
## Expected Behavior
The MPTCP tab in Luci loads normally.

## Current Behavior
The MPTCP tab in Luci doesn't load.

/usr/lib/lua/luci/cbi.lua:53: Model 'mptcp' not found!
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/cbi.lua:53: in function 'load'
	/usr/lib/lua/luci/dispatcher.lua:1353: in function '_cbi'
	/usr/lib/lua/luci/dispatcher.lua:1024: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:479: in function </usr/lib/lua/luci/dispatcher.lua:478>

## Specifications

  - OpenMPTCProuter version: openmptcprouter v0.61-snapshot-5.4 r0+16862-1
  - OpenMPTCProuter VPS version: 5.4.207-mptcp 0.1031-test
  - OpenMPTCProuter VPS provider: OCI
  - OpenMPTCProuter platform: x86_64
  - Country:

**Comment by Ysurac** [comment]
It's fixed in latest version, was a 5.4 only bug, revert to old lua MPTCP.
