### ISSUE TITLE
Use domain instead of IP

### ISSUE THREAD

**Issue by Alison110** [Ysurac/openmptcprouter#3489]
dear Ysurac:
I use a domain to hide my IP with the domain and enter the domain instead of the Server IP in OpenMptcprouter and It accepts the domain, but a few minutes after starting to download a file, the speed of the queue suddenly drops.for regular web browsing it's works fine but after start downloading a file ,speed goes to 100 kbs.

Does anyone know how to solve the problem, and how to use a domain instead of IP?

And if I move the domain behind Cloudflare CDN so that the IP is hidden,OpenMPTCProuter can no longer find it, but in the X-UI panel, the V2Ray service uses this method and does not find any problems, and it easily finds the original IP from behind the CDN. 

If dear Ysurac can do something so that instead of the IP, he can use the domain to hide behind CDN cloudflare, no one can block the IP anymore (in the countries of China, Russia, Cuba, Syria, Malaysia, Iran, Indonesia, Vietnam, Turkey, Saudi Arabia and all countries from they use the Chinese filtering system)

  - OpenMPTCProuter version: 6.6.36-x64v4-xanmod1 0.1031-test
  - OpenMPTCProuter VPS version:  1031-test
  - OpenMPTCProuter VPS provider: Hetzner and P.Q
  - OpenMPTCProuter platform:  Linksys WRT3200ACM

**Comment by Ysurac** [comment]
OpenMPTCProuter can't work with a domain behind a CDN  as it's the CDN that answer the request even if redirected then to the original IP, so no more MPTCP support.

**Comment by Ysurac** [comment]
I would need status->System log and a screenshot of status page.
For sing-box, it doesn't support MPTCP, so it would need to be patched.

**Comment by Ysurac** [comment]
Sing-box seems to support multipath, I will check.
