### ISSUE TITLE
no br-lan on interfaces page

### ISSUE THREAD

**Issue by mojo1988** [Ysurac/openmptcprouter#3492]
Hey!!

Maybe i am dumb. But i can't find the br-lan interface!
The Client on the Wifi-Ap get no IP.

Everytime i tried to configure, i locked myself out :(

## Specifications

  - OpenMPTCProuter version: V0.60-6.1-r0
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter VPS provider: selfhosted debian12 
  - OpenMPTCProuter platform: RPI3

**Comment by Ysurac** [comment]
There is no br-lan interface if you don't create it. I'm not exactly sure to understand what you want...
You can follow the doc: https://github.com/Ysurac/openmptcprouter/wiki/Configure-Wifi

**Comment by Ysurac** [comment]
Thanks for the feedback
