### ISSUE TITLE
Connectivity Issue with Round Robin and Red in OpenMTPCProuter v0.61 kernel 6.6

### ISSUE THREAD

**Issue by Raquel1L** [Ysurac/openmptcprouter#3494]
I am currently using the snapshot version 6.1 of OpenMTPCProuter on my router (RPi4) and have encountered an issue: the Round Robin and Red schedulers are not functioning as expected. When I select either option, I lose internet connectivity. In contrast, only the First, Default, and Burst schedulers appear to work properly.

Is anyone else experiencing this issue, or could it be due to an error on my part? Is this a known problem?

**Comment by Ysurac** [comment]
These schedulers are not available on kernel 6.1

**Comment by Raquel1L** [comment]
So what could I do to use the schedulers?

**Comment by Ysurac** [comment]
So this is snapshot 0.61 with kernel 6.6.
The schedulers are not yet tested.

**Comment by Ysurac** [comment]
I just tested both rr and red MPTCP scheduler and I have no connectivity issues.
Do you have something in Status->kernel log or in Status->System log ?

**Comment by ccmks** [comment]
What is red on the MPTCP scheduler? Is it redundant?

**Comment by Ysurac** [comment]
Yes, and rr for round-robin
