### ISSUE TITLE
New public ip detected stops traffic on interface

### ISSUE THREAD

**Issue by dfadev** [Ysurac/openmptcprouter#3497]
## Expected Behavior

Traffic continues on interface.

## Current Behavior

Traffic stops on interface that has new public IP.

## Possible Solution

Don't run `/etc/init.d/mptcp reload [intf]` on interface already in multipath.

## Steps to Reproduce the Problem
See screen recording:

https://github.com/user-attachments/assets/a6a0ebc8-26b8-4ccf-b314-f11db5a770a8

## Context (Environment)

When OMR detects a new public IP it reloads MPTCP on the interface.  This seems to stop existing traffic that was traversing the interface fine prior to reloading MPTCP.

## Specifications

  - OpenMPTCProuter version: v0.60rc2-6.1 r0+24843-acf40c022e
  - OpenMPTCProuter VPS version:  0.1031-test 6.1.0-22-amd64
  - OpenMPTCProuter VPS provider:
  - OpenMPTCProuter platform: x86_64
  - Country: US

**Comment by Ysurac** [comment]
Yes this reload is not needed anymore. I will fix this.
