### ISSUE TITLE
Catastrophic rate since last update

### ISSUE THREAD

**Issue by Roken120** [Ysurac/openmptcprouter#350]
## Expected Behavior

I have Catastrophic rate since last update

root@OpenMPTCProuter:~# omr-test-speed
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  3 10.0G    3  355M    0     0  10.4M      0  0:16:19  0:00:34  0:15:45 7544k^C
root@OpenMPTCProuter:~# omr-test-speed wan1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 10.0G    0 70.9M    0     0  8047k      0  0:21:43  0:00:09  0:21:34 11.0M^C
root@OpenMPTCProuter:~# omr-test-speed wan2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 10.0G    0 79.5M    0     0  10.4M      0  0:16:16  0:00:07  0:16:09 11.2M^C
root@OpenMPTCProuter:~# omr-test-speed wan3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 10.0G    0 25.4M    0     0  3385k      0  0:51:36  0:00:07  0:51:29 3476k^C

## Steps to Reproduce the Problem

  1.Update to last update
  2.Speed test

## Specifications

  - OpenMPTCProuter version: 0.46.3
  - OpenMPTCProuter VPS version: 0.92
  - OpenMPTCProuter platform: x86_64

**Comment by Roken120** [comment]
I have reinstall my system and i have same error

**Comment by Ysurac** [comment]
I need the config. ```uci show``` via SSH (remove server ip settings)

**Comment by Roken120** [comment]
uci show of router : https://pastebin.com/bUT4y6Jc

**Comment by Ysurac** [comment]
Lan, WAN1 and  WAN2 are on the same network. This can't work that way.

**Comment by Roken120** [comment]
Its working before why now it works more

**Comment by Ysurac** [comment]
No idea how this can work ;)

**Comment by Roken120** [comment]
Ok maybe what is the bug ? because my rate speed is max 70mbps...

**Comment by Ysurac** [comment]
There is no bug here.
Lan, and WANs MUST be on separated networks.
Else MPTCP have no idea what the route it can use for each packets.

**Comment by Roken120** [comment]
Ok i change
De : Ycarus (Yannick Chabanois)<mailto:notifications@github.com>
Envoyé le :samedi 9 février 2019 16:49
À : Ysurac/openmptcprouter<mailto:openmptcprouter@noreply.github.com>
Cc : Roken120<mailto:pumadu@hotmail.fr>; Author<mailto:author@noreply.github.com>
Objet :Re: [Ysurac/openmptcprouter] Catastrophic rate since last update (#350)


There is no bug here.
Lan, and WANs MUST be on separated networks.
Else MPTCP have no idea what the route it can use for each packets.

**Comment by Roken120** [comment]
I have change and i have same result

**Comment by Ysurac** [comment]
Can I have the result of ```uci show``` now that changes are made ?
