### ISSUE TITLE
How to Forward GRE Traffic to a Specific Device Connected on the Network

### ISSUE THREAD

**Issue by rickytrevor** [Ysurac/openmptcprouter#3500]
## Question

Could anyone please guide me on how to forward GRE traffic to a specific device connected to the network? Any detailed instructions or settings that need to be configured would be greatly appreciated.

## Specifications

OpenMPTCProuter version: v0.60
OpenMPTCProuter VPS version: v0.1030
OpenMPTCProuter VPS provider: Synthohosting
OpenMPTCProuter platform: x86_64

**Comment by winkmichael** [comment]
Services -> OMR-Bypass, select the protocol GRE. Attached is a screenshot.

![Screenshot 2024-08-24 at 4 15 18 PM](https://github.com/user-attachments/assets/396e384f-e15b-4bc6-8198-907c8b4f2f8a)
