### ISSUE TITLE
Documentation : VPS : how it works and why it is needed

### ISSUE THREAD

**Issue by wlew-via** [Ysurac/openmptcprouter#3510]
Firstly, thank you @Ysurac for this project.
I have an understanding of what the VPS is doing and why it is needed but I am looking for documentation that explains these key points. I looked at your documentation/wiki section of this repository and this information is missing. Can someone point me somewhere where i can find this information or can it be answered here? Maybe it can be added in the FAQ or Wiki?
Thank you!

**Comment by suyuan168** [comment]
see 
<img width="1633" alt="image" src="https://github.com/user-attachments/assets/de03561f-419e-4728-8012-e717d60647ef">
