### ISSUE TITLE
Slow down and disconnect the admin script  after VPS update

### ISSUE THREAD

**Issue by Alison110** [Ysurac/openmptcprouter#3511]
Dear Ysurac;

After updating the VPS(30-Aug), the speed and bandwidth have decreased drastically. Also, the admin script is not able to communicate with OpenMptcpRouter.
 And when the proxy is set in "xray shadosocks" mode, baypass stops working

  - OpenMPTCProuter version: snapshot-6.6-r0+27160-b72c4b5386 (Aug-30-2024)
  - OpenMPTCProuter VPS version: 0.1031-test 6.6.2-x64v2-xanmod1
  - OpenMPTCProuter VPS provider:P.Q - Hetzner
  - OpenMPTCProuter platform: WRT3200acm / Netgear R7800

<img width="837" alt="דאשאוד" src="https://github.com/user-attachments/assets/eb2ec740-8b1f-4510-8e1f-f0eb60d8b7c4">

<img width="1065" alt="logs 2024-09-02 084159" src="https://github.com/user-attachments/assets/3045dcde-f1c4-4d41-b7ec-48778e7a21a6">

<img width="749" alt="journalctl-2024-09-02 085753" src="https://github.com/user-attachments/assets/2761b432-1739-499f-bc93-58f185cfff54">

**Comment by Ysurac** [comment]
You should also use kernel 6.6 on VPS.
For omr-admin, the device eth0 exist ? if not the case you have a problem in firewall config, in /etc/shorewall/params.net

**Comment by Ysurac** [comment]
Without the correct interface set in shorewall this can't work correctly. You must fix this and restart shorewall.

**Comment by Ysurac** [comment]
I just fixed an issue about proxy not enabled correctly on router part.
