### ISSUE TITLE
Free space requirements on SSD for OMR-VPS?

### ISSUE THREAD

**Issue by GermanAizek** [Ysurac/openmptcprouter#3520]
@Ysurac
How much free space do I need on my VPS to install OMR-VPS?

**Comment by GermanAizek** [comment]
On this page don't specify: https://github.com/Ysurac/openmptcprouter/wiki/Install-or-update-the-VPS

**Comment by Ysurac** [comment]
I would say about 1GB max on Debian 12, but I didn't check.

**Comment by GermanAizek** [comment]
> I would say about 1GB max on Debian 12, but I didn't check.

Thanks for lightning-fast response.
