### ISSUE TITLE
编译过程中遇到如下问题

### ISSUE THREAD

**Issue by fdyf520** [Ysurac/openmptcprouter#3525]
Building LLVM for x86_64-unknown-linux-gnu CMAKE_TOOLCHAIN_FILE_x86_64-unknown-linux-gnu = None CMAKE_TOOLCHAIN_FILE_x86_64_unknown_linux_gnu = None HOST_CMAKE_TOOLCHAIN_FILE = None CMAKE_TOOLCHAIN_FILE = None CMAKE_PREFIX_PATH_x86_64-unknown-linux-gnu = None CMAKE_PREFIX_PATH_x86_64_unknown_linux_gnu = None HOST_CMAKE_PREFIX_PATH = None CMAKE_PREFIX_PATH = None CMAKE_x86_64-unknown-linux-gnu = None CMAKE_x86_64_unknown_linux_gnu = None HOST_CMAKE = None CMAKE = None running: cd "/home/xuxinqiang/openmptcprouter/x86_64/5.4/source/build_dir/target-x86_64_musl/host/rustc-1.75.0-src/build/x86_64-unknown-linux-gnu/llvm/build" && CMAKE_PREFIX_PATH="" DESTDIR="" "cmake" "/home/xuxinqiang/openmptcprouter/x86_64/5.4/source/build_dir/target-x86_64_musl/host/rustc-1.75.0-src/src/llvm-project/llvm" "-G" "Ninja" "-DLLVM_ENABLE_ASSERTIONS=OFF" "-DLLVM_UNREACHABLE_OPTIMIZE=OFF" "-DLLVM_ENABLE_PLUGINS=OFF" "-DLLVM_TARGETS_TO_BUILD=AArch64;ARM;BPF;Hexagon;LoongArch;MSP430;Mips;NVPTX;PowerPC;RISCV;Sparc;SystemZ;WebAssembly;X86" "-DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=AVR;M68k;CSKY" "-DLLVM_INCLUDE_EXAMPLES=OFF" "-DLLVM_INCLUDE_DOCS=OFF" "-DLLVM_INCLUDE_BENCHMARKS=OFF" "-DLLVM_INCLUDE_TESTS=OFF" "-DLLVM_ENABLE_TERMINFO=OFF" "-DLLVM_ENABLE_LIBEDIT=OFF" "-DLLVM_ENABLE_BINDINGS=OFF" "-DLLVM_ENABLE_Z3_SOLVER=OFF" "-DLLVM_PARALLEL_COMPILE_JOBS=16" "-DLLVM_TARGET_ARCH=x86_64" "-DLLVM_DEFAULT_TARGET_TRIPLE=x86_64-unknown-linux-gnu" "-DLLVM_ENABLE_WARNINGS=OFF" "-DLLVM_INSTALL_UTILS=ON" "-DLLVM_ENABLE_ZSTD=OFF" "-DLLVM_ENABLE_ZLIB=ON" "-DLLVM_ENABLE_LIBXML2=OFF" "-DLLVM_VERSION_SUFFIX=-rust-1.75.0-stable" "-DCMAKE_INSTALL_MESSAGE=LAZY" "-DCMAKE_C_COMPILER=cc" "-DCMAKE_CXX_COMPILER=c++" "-DCMAKE_ASM_COMPILER=cc" "-DCMAKE_C_FLAGS=-ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_FLAGS=-ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_SHARED_LINKER_FLAGS= " "-DCMAKE_MODULE_LINKER_FLAGS= " "-DCMAKE_EXE_LINKER_FLAGS= " "-DCMAKE_INSTALL_PREFIX=/home/xuxinqiang/openmptcprouter/x86_64/5.4/source/build_dir/target-x86_64_musl/host/rustc-1.75.0-src/build/x86_64-unknown-linux-gnu/llvm" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_BUILD_TYPE=Release" CMake Error at CMakeLists.txt:3 (cmake_minimum_required): CMake 3.20.0 or higher is required. You are running version 3.19.8

-- Configuring incomplete, errors occurred! thread 'main' panicked at /home/xuxinqiang/openmptcprouter/x86_64/5.4/source/staging_dir/target-x86_64_musl/cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.48/src/lib.rs:975:5:

command did not execute successfully, got: exit status: 1

build script failed, must exit now note: run with RUST_BACKTRACE=1 environment variable to display a backtrace finished in 0.005 seconds Build completed unsuccessfully in 0:00:00 make[3]: *** [Makefile:110: /home/xuxinqiang/openmptcprouter/x86_64/5.4/source/build_dir/target-x86_64_musl/host/rustc-1.75.0-src/.built] Error 1 make[3]: Leaving directory '/home/xuxinqiang/openmptcprouter/feeds/openmptcprouter/rust' time: package/feeds/openmptcprouter/rust/host-compile#0.30#0.28#0.57 ERROR: package/feeds/openmptcprouter/rust [host] failed to build. make[2]: *** [package/Makefile:114: package/feeds/openmptcprouter/rust/host/compile] Error 1 make[2]: Leaving directory '/home/xuxinqiang/openmptcprouter/x86_64/5.4/source' make[1]: *** [package/Makefile:110: /home/xuxinqiang/openmptcprouter/x86_64/5.4/source/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2 make[1]: Leaving directory '/home/xuxinqiang/openmptcprouter/x86_64/5.4/source' make: *** [/home/xuxinqiang/openmptcprouter/x86_64/5.4/source/include/toplevel.mk:230：world] 错误 2 遇到这个问题如何处理

**Comment by Ysurac** [comment]
Please use template (it's the wrong category)
There is no more support on 5.4 as it's in legacy but it's still compiling correctly on Github actions: https://github.com/Ysurac/openmptcprouter-feeds/actions/runs/10774235155/job/29875826030
