### ISSUE TITLE
Bypass doesn't work with 

### ISSUE THREAD

**Issue by Alison110** [Ysurac/openmptcprouter#3539]
(In all versions)
When proxy is set to Xray-Shadowsocks 2022, BYPASS is not working. I changed nameservers, but nothing changed, As you can see in the picture.

<img width="822" alt="baypass error-2024-09-17 084818" src="https://github.com/user-attachments/assets/be0c1ed3-7c72-46d5-8f85-9e9a7bc68355">

## Specifications

OpenMPTCProuter version: v0.61rc2 (all versions are same)
OpenMPTCProuter VPS version: v0.61rc
OpenMPTCProuter VPS provider: hetzner, PQ, Cloudzy
OpenMPTCProuter platform: Netgear R7800 and WRT3200acm

**Comment by Ysurac** [comment]
It's working with another proxy ?
