### ISSUE TITLE
NMAP not working

### ISSUE THREAD

**Issue by Scaff31** [Ysurac/openmptcprouter#354]
## Expected Behavior

Hello,

Small problem with nmap, when using it without OMR it responds correctly the state of the remote ports only when passing with OMR it responds that all ports are open
strange situation so if you have any answers as to why I'm a taker.

Thank you for the work you have done.

## Steps to Reproduce the Problem

  1. nmap IP or domain

## Specifications

  - OpenMPTCProuter version: All
  - OpenMPTCProuter VPS version: All
  - OpenMPTCProuter platform: Test on rpi and esxi vm

**Comment by Ysurac** [comment]
True, but I don't think it's really a big problem. So won't fix for now.
