### ISSUE TITLE
Healthy connection ignored until reboot

### ISSUE THREAD

**Issue by bobradamus** [Ysurac/openmptcprouter#3545]
I’m using two Teltonika RUTX50s as modems, a Raspberry Pi4 8GB as the mpTCP router, a tp-link unmanaged switch and an IONOS 2GB RAM VPS.

Both modems are using a 5G cellular connection, one is more stable than the other - the more stable is the master.

We did a live trial for our live stream this evening after some successful tests of the setup.

Occasionally, the more stable connection would degrade, with a shift in the antenna being enough to re-establish and for a stable stream to resume. However, at one point the more stable connection remained with a good cellular connection, but the mpTCP router stopped sending traffic over it, leaving the weaker connection to pick up the stream ~ which wasn’t enough.

No traffic was being sent at all over the more stable connection, with some being received, but in the kbit range. I attempted to reboot the more stable router twice, with no effect, each time the connection returned within 30 seconds, but no traffic would be sent along it.

I then rebooted the mpTCP router with a hard power off/on, the router came back up and immediately began to use both paths and remained stable for two hours with < 0.5% packet drops.

My questions are:-,
When this happens, what is the best recovery to ‘force’ traffic over the known stable connection?
Also, why would the router do this and favour the poor quality connection?
Is there any way to stop it doing this?
Clearly the more connections the better, however am I right in principal, for our use-case of cellular connections in the field, it is better to have two stable connections and a third to take up any remaining slack?

**Comment by Ysurac** [comment]
Please use the template
