### ISSUE TITLE
Open VPN setup

### ISSUE THREAD

**Issue by VisionLabGroup** [Ysurac/openmptcprouter#3548]
Hello, 

Can anyone tell me how to set up openvpn with the router? I can’t set it up

Thank you

Specifications

  - OpenMPTCProuter version: 0.60
  - OpenMPTCProuter VPS version: 0.1028
  - OpenMPTCProuter VPS provider: Serverplan IT
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
You can set it via the interface VPN->OpenVPN. You need to make sure to use as "dev" something else than tun0 (used by OMRVPN).
