### ISSUE TITLE
RTL8168 NIC support

### ISSUE THREAD

**Issue by FermedePommerieux** [Ysurac/openmptcprouter#3552]
## Expected Behavior
RTL8168 NIC support

since 0.61 the second ethernet port of my dfrobot routerboard is not recognized, does RTL8168 kernel module included ?

## Possible Solution

add 8168 to linux kernel

## Context (Environment)

use 0.61 on dfrobot routerboard with CM4

## Specifications

  - OpenMPTCProuter version:.0,61
  - OpenMPTCProuter platform: CM4 dfrobot router board

**Comment by Ysurac** [comment]
This driver was removed because N100 wasn't booting correctly with it (no idea why).
I will add it back for anything that is not x86_64

**Comment by FermedePommerieux** [comment]
top merci

**Comment by Slikpro** [comment]
Good day! Could you please share the compiled r8168.ko module for the latest current x86_64 ext4.efi.img build. Some low-budget industrial computers have an old Realtek RTL8168 network chip on their motherboard. You mentioned that there is instability only with relatively new intel processors. In older builds I found only r8189 but it doesn't fit. and in Ubuntu the network card is detected as and pulls up k8168.ko.
