### ISSUE TITLE
Browser debug console spammed with javascript errors on web ui

### ISSUE THREAD

**Issue by darkman1983** [Ysurac/openmptcprouter#3559]
## Expected Behavior
No javascript errors in debug console of browser.

## Current Behavior
The console of the browser is constantly spammed with errors. This doesn't depend on the theme used.

![image](https://github.com/user-attachments/assets/9be2687f-5f29-4b25-bfd6-c2e81fb0680a)

## Possible Solution
Fixing those errors, eg. upgrading javascript?

## Steps to Reproduce the Problem

  1. Open MPTCPRouter Webinterface
  2. Open debug console of browser
  3. See it spammed with javascript errors

## Context (Environment)
Maybe this causes high memory consumption or other issues regarding pagespeed or responsiveness.

## Specifications

  - OpenMPTCProuter version: openmptcprouter v0.61rc2-6.6 (r0+27346-c7ba5574f5)
  - OpenMPTCProuter VPS version: Version 0.1031-test 6.10.2-x64v3-xanmod1
  - OpenMPTCProuter VPS provider: 1blu.de
  - OpenMPTCProuter platform: x86_64
  - Country: Germany

**Comment by Ysurac** [comment]
No idea from what it's coming from. There is no "lockdown-install.js" script. Are you sure it's not related to a browser plugin ?
