### ISSUE TITLE
firewall on vps

### ISSUE THREAD

**Issue by talitha77** [Ysurac/openmptcprouter#3567]
## Expected Behavior

I am unable to access the vps for other services like web hosting or mqtt broker
## Current Behavior

i think openmptcprouter is only routing through the vpn tunnel as i can only access my web server that way. 
so anyone elsewhere can't

6.1.0-25

**Comment by Ysurac** [comment]
Please use the full template, with version you use, VPS version,...
You mean from internal LAN or from internet ? You have configured shorewall to open services ?
VPS is not really mean to be used for something else than OpenMPTCProuter, in most cae it's not a good idea.

**Comment by talitha77** [comment]
ah ok i suspected that was the case.. thanks
