### ISSUE TITLE
v0.61RC3 Kernel 6.11 VPS install errors/warnings

### ISSUE THREAD

**Issue by datapharmer** [Ysurac/openmptcprouter#3578]
## Expected Behavior

Should install without error...

## Current Behavior

Threw a number of errors and warnings that may impact functionality (impact unknown at this point, but may be tied to the tls handshake issue I reported with 0.61RC2). I understand some of these are likely safe to ignore such as pip3 but included for full context. Others seem they could be problematic such as `Failed to get unit file state for shadowsocks-libev.service: No such file or directory`

## Possible Solution

I'm not sure how any of these should be addressed, but I'm happy to test out anything that seems it should be fixed.

## Steps to Reproduce the Problem

  1. Ran wget -O - https://www.openmptcprouter.com/server-rc/debian-x86_64.sh | KERNEL="6.11" sh
  2. observe output (relevant logs below)

## Context (Environment)

VPS on BuyVM/Frantech running Debian 12

## Specifications

  - OpenMPTCProuter version:  N/A (but 0.61RC2 currently)
  - OpenMPTCProuter VPS version: 0.1031-test 
  - OpenMPTCProuter VPS provider: BuyVM
  - OpenMPTCProuter platform: N/A (but RPI4)
  - Country: USA

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Reading package lists... Done

....

-- pip3 install needed python modules
If you see any error here, I really don't care: it's about a module not used for home users
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
--2024-10-08 09:47:15--  https://www.openmptcprouter.com/server-test/omr-admin.service.in

....

Connecting to www.openmptcprouter.com (www.openmptcprouter.com)|2400:52e0:1a02::974:1|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 386 [application/octet-stream]
Saving to: '/lib/systemd/system/shadowsocks-libev-manager@.service'

/lib/systemd/system 100%[===================>]     386  --.-KB/s    in 0s

2024-10-08 09:47:17 (14.0 MB/s) - '/lib/systemd/system/shadowsocks-libev-manager@.service' saved [386/386]

Failed to get unit file state for shadowsocks-libev.service: No such file or directory
--2024-10-08 09:47:17--  https://www.openmptcprouter.com/server-test/omr-update.service.in

....

(Reading database ... 164388 files and directories currently installed.)
Preparing to unpack /tmp/v2ray-5.7.0-amd64.deb ...
Unpacking v2ray (5.7.0) over (5.7.0) ...
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/bin/geoip.dat', which is also in package xray 1.8.24
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/bin/geosite.dat', which is also in package xray 1.8.24
Setting up v2ray (5.7.0) ...

....

Configuring glorytun@.service using configuration
Build targets in project: 1

Found ninja-1.11.1 at /usr/bin/ninja
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
ninja: Entering directory `build'
[2/19] Compiling C object glorytun.p/mud_mud.c.o
In function 'mud_unmapv4',
    inlined from 'mud_unmapv4' at ../mud/mud.c:306:1,
    inlined from 'mud_localaddr' at ../mud/mud.c:818:13,
    inlined from 'mud_recv' at ../mud/mud.c:1141:9:
../mud/mud.c:316:31: warning: 'local.sin6.sin6_port' may be used uninitialized [-Wmaybe-uninitialized]
  316 |         .sin_port = addr->sin6.sin6_port,
      |                     ~~~~~~~~~~^~~~~~~~~~
../mud/mud.c: In function 'mud_recv':
../mud/mud.c:1139:24: note: 'local' declared here
 1139 |     union mud_sockaddr local;
      |                        ^~~~~
[18/19] Installing files.

....

make[2]: Entering directory '/tmp/mlvpn/src'
  CC       mlvpn-buffer.o
  CC       mlvpn-configlib.o
  CC       mlvpn-config.o
  CC       mlvpn-tool.o
  CC       mlvpn-privsep.o
  CC       mlvpn-privsep_fdpass.o
  CC       mlvpn-wrr.o
  CC       mlvpn-crypto.o
  CC       mlvpn-log.o
  CC       mlvpn-reorder.o
  CC       mlvpn-timestamp.o
  CC       mlvpn-tuntap_generic.o
  CC       mlvpn-mlvpn.o
mlvpn.c: In function 'mlvpn_rtun_read':
mlvpn.c:373:31: warning: comparison of constant '2' with boolean expression is always false [-Wbool-compare]
  373 |             if (! tun->status >= MLVPN_AUTHOK) {
      |                               ^~
mlvpn.c:373:31: warning: logical not is only applied to the left hand side of comparison [-Wlogical-not-parentheses]
mlvpn.c:373:17: note: add parentheses around left hand side expression to silence this warning
  373 |             if (! tun->status >= MLVPN_AUTHOK) {
      |                 ^~~~~~~~~~~~~
      |                 (            )
  CC       mlvpn-vis.o
  CC       mlvpn-closefrom.o
  CC       mlvpn-setproctitle.o
  CC       mlvpn-strlcat.o
  CC       mlvpn-strlcpy.o
  CC       mlvpn-tuntap_linux.o
  CC       mlvpn-systemd.o
  CC       mlvpn-control.o
control.c: In function 'mlvpn_control_write_status':
control.c:462:36: warning: the comparison will always evaluate as 'true' for the address of 'bindaddr' will never be NULL [-Waddress]
  462 |                        t->bindaddr ? t->bindaddr : "any",
      |                                    ^
In file included from control.c:26:
mlvpn.h:142:10: note: 'bindaddr' declared here
  142 |     char bindaddr[MLVPN_MAXHNAMSTR]; /* packets source */
      |          ^~~~~~~~
control.c:463:36: warning: the comparison will always evaluate as 'true' for the address of 'bindport' will never be NULL [-Waddress]
  463 |                        t->bindport ? t->bindport : "any",
      |                                    ^
mlvpn.h:143:10: note: 'bindport' declared here
  143 |     char bindport[MLVPN_MAXPORTSTR]; /* packets port source (or NULL) */
      |          ^~~~~~~~
control.c:464:36: warning: the comparison will always evaluate as 'true' for the address of 'destaddr' will never be NULL [-Waddress]
  464 |                        t->destaddr ? t->destaddr : "",
      |                                    ^
mlvpn.h:145:10: note: 'destaddr' declared here
  145 |     char destaddr[MLVPN_MAXHNAMSTR]; /* remote server ip (can be hostname) */
      |          ^~~~~~~~
control.c:465:36: warning: the comparison will always evaluate as 'true' for the address of 'destport' will never be NULL [-Waddress]
  465 |                        t->destport ? t->destport : "",
      |                                    ^
mlvpn.h:146:10: note: 'destport' declared here
  146 |     char destport[MLVPN_MAXPORTSTR]; /* remote server port */
      |          ^~~~~~~~
  CC       mlvpn-filters.o
  CCLD     mlvpn
make[2]: Leaving directory '/tmp/mlvpn/src'
Making all in man

....

checking for libsodium >= 1.0.4... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: executing depfiles commands
  CC       src/glorytun-common.o
  CC       src/glorytun-main.o
src/main.c: In function 'gt_setup_crypto':
src/main.c:1228:40: warning: passing argument 1 of 'crypto_aead_aes256gcm_beforenm' from incompatible pointer type [-Wincompatible-pointer-types]
 1228 |         crypto_aead_aes256gcm_beforenm(&ctx->read.key, key_r);
      |                                        ^~~~~~~~~~~~~~
      |                                        |
      |                                        uint8_t (*)[512] {aka unsigned char (*)[512]}
In file included from /usr/include/sodium.h:8,
                 from src/main.c:38:
/usr/include/sodium/crypto_aead_aes256gcm.h:118:65: note: expected 'crypto_aead_aes256gcm_state *' {aka 'struct crypto_aead_aes256gcm_state_ *'} but argument is of type 'uint8_t (*)[512]' {aka 'unsigned char (*)[512]'}
  118 | int crypto_aead_aes256gcm_beforenm(crypto_aead_aes256gcm_state *ctx_,
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
src/main.c:1229:40: warning: passing argument 1 of 'crypto_aead_aes256gcm_beforenm' from incompatible pointer type [-Wincompatible-pointer-types]
 1229 |         crypto_aead_aes256gcm_beforenm(&ctx->write.key, key_w);
      |                                        ^~~~~~~~~~~~~~~
      |                                        |
      |                                        uint8_t (*)[512] {aka unsigned char (*)[512]}
/usr/include/sodium/crypto_aead_aes256gcm.h:118:65: note: expected 'crypto_aead_aes256gcm_state *' {aka 'struct crypto_aead_aes256gcm_state_ *'} but argument is of type 'uint8_t (*)[512]' {aka 'unsigned char (*)[512]'}
  118 | int crypto_aead_aes256gcm_beforenm(crypto_aead_aes256gcm_state *ctx_,
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
  CC       src/glorytun-option.o
  CC       src/glorytun-tun.o
  CC       src/glorytun-db.o
  CC       src/glorytun-state.o
  CCLD     glorytun
--2024-10-08 09:48:41--  https://www.openmptcprouter.com/server-test/glorytun-tcp-run

**Comment by Ysurac** [comment]
Nothing to really care about. Real errors block the script execution.
I can hide these warning/errors but this can hide real errors too and will not help debugging.

**Comment by datapharmer** [comment]
no need to hide these if they aren't a concern. Thanks for reviewing to confirm.
