### ISSUE TITLE
Wiki: Technologies, improve description of Glorytun

### ISSUE THREAD

**Issue by lars18th** [Ysurac/openmptcprouter#36]
Hi,

In the Wiki section "Technologies" when commenting about the Glorytun package, please advise that the project uses the "Plain" (aka TCP) version, instead of the "regular" MUD version (aka UDP).

This info is useful when you like to understand how works the Open-MPTCP-Router.

Regards.

**Comment by Ysurac** [comment]
Both are available. Soon both will be supported on the VPS side too.

**Comment by lars18th** [comment]
> Both are available. Soon both will be supported on the VPS side too.

Great! Thank you! :smile:
