### ISSUE TITLE
In post-tracking.d/020-status every wan is flagged as huawei

### ISSUE THREAD

**Issue by FPi-sh** [Ysurac/openmptcprouter#3601]
## Expected Behavior
Flag as Huawei only the WANs where the gateway reply correctly to the SesTokInfo request.

## Current Behavior
`if [ "$proto" != "qmi" ] && [ "$proto" != "modemmanager" ]; then`
`	if [ -n "$OMR_TRACKER_DEVICE_GATEWAY" ] && [ -n "$OMR_TRACKER_DEVICE_IP" ] && [ -n "$(curl --interface $OMR_TRACKER_DEVICE_IP -s -m 2 -X GET http://$OMR_TRACKER_DEVICE_GATEWAY/api/webserver/SesTokInfo)" ]; then`
`		uci -q set openmptcprouter.$OMR_TRACKER_INTERFACE.manufacturer='huawei'`
`	else`
`		uci -q delete openmptcprouter.$OMR_TRACKER_INTERFACE.manufacturer`
`	fi`
`fi`

`-n "$(curl --interface $OMR_TRACKER_DEVICE_IP -s -m 2 -X GET http://$OMR_TRACKER_DEVICE_GATEWAY/api/webserver/SesTokInfo)"` is always true

## Possible Solution
`if [ "$proto" != "qmi" ] && [ "$proto" != "modemmanager" ]; then`
`	if [ -n "$OMR_TRACKER_DEVICE_GATEWAY" ] && [ -n "$OMR_TRACKER_DEVICE_IP" ] && [ $(curl --interface $OMR_TRACKER_DEVICE_IP -s -m 2 -X GET -I http://$OMR_TRACKER_DEVICE_GATEWAY/api/webserver/SesTokInfo | head -n 1 | grep 200) ]; then`
`		uci -q set openmptcprouter.$OMR_TRACKER_INTERFACE.manufacturer='huawei'`
`	else`
`		uci -q delete openmptcprouter.$OMR_TRACKER_INTERFACE.manufacturer`
`	fi`
`fi`

## Specifications

  - OpenMPTCProuter version: 0.61rc1
  - OpenMPTCProuter VPS version:
  - OpenMPTCProuter VPS provider:
  - OpenMPTCProuter platform: 
  - Country:

**Comment by Ysurac** [comment]
Thanks for the bug report
