### ISSUE TITLE
Install VPS KERNEL="6.6"

### ISSUE THREAD

**Issue by Silvanskii** [Ysurac/openmptcprouter#3602]
Сan't install kernel 6.6.
I am using debian 12.
After booting I enter the commands: 
apt-get update && apt-get upgrade
apt-get install -y ca-certificates && sed -i '/^mozilla\/DST_Root_CA_X3/s/^/!/' /etc/ca-certificates.conf && update-ca-certificates -f
wget -O - https://www.openmptcprouter.com/server/debian-x86_64.sh | KERNEL=“6.6” sh
and I get the following error
Maybe I'm doing something wrong?

**Comment by Silvanskii** [comment]
root@vds2642154:~# wget -O - https://www.openmptcprouter.com/server/debian-x86_6                                                                                                   4.sh | KERNEL="6.6" sh
--2024-10-18 13:40:55--  https://www.openmptcprouter.com/server/debian-x86_64.sh
Resolving www.openmptcprouter.com (www.openmptcprouter.com)... 185.131.64.122
Connecting to www.openmptcprouter.com (www.openmptcprouter.com)|185.131.64.122|:                                                                                                   443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 90532 (88K) [application/octet-stream]
Saving to: ‘STDOUT’

-                     0%[                    ]       0  --.-KB/s               C                                                                                                   heck user...
Check Linux version...
Check architecture...
Check about broken packages...
Check if OpenMPTCProuter VPS is already installed...
Update mode
Remove lock and update packages list...
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://security.debian.org/debian-security bookworm-security InRelease
Reading package lists... Done
Install apt-transport-https, gnupg and openssh-server...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
openssh-server is already the newest version (1:9.2p1-2+deb12u3).
The following additional packages will be installed:
  dirmngr gnupg-l10n gnupg-utils gpg gpg-agent gpg-wks-client gpg-wks-server
  gpgconf gpgsm libassuan0 libksba8 libnpth0 pinentry-curses
Suggested packages:
  pinentry-gnome3 tor parcimonie xloadimage scdaemon pinentry-doc
The following NEW packages will be installed:
  apt-transport-https dirmngr gnupg gnupg-l10n gnupg-utils gpg gpg-agent
  gpg-wks-client gpg-wks-server gpgconf gpgsm libassuan0 libksba8 libnpth0
  pinentry-curses
0 upgraded, 15 newly installed, 0 to remove and 1 not upgraded.
Need to get 7906 kB of archives.
After this operation, 16.0 MB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bookworm/main amd64 apt-transport-https all 2                                                                                                   .6.1 [25.2 kB]
Get:2 http://deb.debian.org/debian bookworm/main amd64 libassuan0 amd64 2.5.5-5                                                                                                    [48.5 kB]
Get:3 http://deb.debian.org/debian bookworm/main amd64 gpgconf amd64 2.2.40-1.1                                                                                                    [564 kB]
Get:4 http://deb.debian.org/debian bookworm/main amd64 libksba8 amd64 1.6.3-2 [1                                                                                                   28 kB]
Get:5 http://deb.debian.org/debian bookworm/main amd64 libnpth0 amd64 1.6-3 [19.                                                                                                   0 kB]
Get:6 http://deb.debian.org/debian bookworm/main amd64 dirmngr amd64 2.2.40-1.1                                                                                                    [792 kB]
Get:7 http://deb.debian.org/debian bookworm/main amd64 gnupg-l10n all 2.2.40-1.1                                                                                                    [1093 kB]
Get:8 http://deb.debian.org/debian bookworm/main amd64 gnupg-utils amd64 2.2.40-                                                                                                   1.1 [927 kB]
Get:9 http://deb.debian.org/debian bookworm/main amd64 gpg amd64 2.2.40-1.1 [949                                                                                                    kB]
Get:10 http://deb.debian.org/debian bookworm/main amd64 pinentry-curses amd64 1.                                                                                                   2.1-1 [77.4 kB]
Get:11 http://deb.debian.org/debian bookworm/main amd64 gpg-agent amd64 2.2.40-1                                                                                                   .1 [695 kB]
Get:12 http://deb.debian.org/debian bookworm/main amd64 gpg-wks-client amd64 2.2                                                                                                   .40-1.1 [541 kB]
Get:13 http://deb.debian.org/debian bookworm/main amd64 gpg-wks-server amd64 2.2                                                                                                   .40-1.1 [531 kB]
Get:14 http://deb.debian.org/debian bookworm/main amd64 gpgsm amd64 2.2.40-1.1 [                                                                                                   671 kB]
Get:15 http://deb.debian.org/debian bookworm/main amd64 gnupg all 2.2.40-1.1 [84                                                                                                   6 kB]
Fetched 7906 kB in 1s (6032 kB/s)
Selecting previously unselected package apt-transport-https.
(Reading database ... 35470 files and directories currently installed.)
Preparing to unpack .../00-apt-transport-https_2.6.1_all.deb ...
Unpacking apt-transport-https (2.6.1) ...
Selecting previously unselected package libassuan0:amd64.
Preparing to unpack .../01-libassuan0_2.5.5-5_amd64.deb ...
Unpacking libassuan0:amd64 (2.5.5-5) ...
Selecting previously unselected package gpgconf.
Preparing to unpack .../02-gpgconf_2.2.40-1.1_amd64.deb ...
Unpacking gpgconf (2.2.40-1.1) ...
Selecting previously unselected package libksba8:amd64.
Preparing to unpack .../03-libksba8_1.6.3-2_amd64.deb ...
Unpacking libksba8:amd64 (1.6.3-2) ...
Selecting previously unselected package libnpth0:amd64.
Preparing to unpack .../04-libnpth0_1.6-3_amd64.deb ...
Unpacking libnpth0:amd64 (1.6-3) ...
Selecting previously unselected package dirmngr.
Preparing to unpack .../05-dirmngr_2.2.40-1.1_amd64.deb ...
Unpacking dirmngr (2.2.40-1.1) ...
Selecting previously unselected package gnupg-l10n.
Preparing to unpack .../06-gnupg-l10n_2.2.40-1.1_all.deb ...
Unpacking gnupg-l10n (2.2.40-1.1) ...
Selecting previously unselected package gnupg-utils.
Preparing to unpack .../07-gnupg-utils_2.2.40-1.1_amd64.deb ...
Unpacking gnupg-utils (2.2.40-1.1) ...
Selecting previously unselected package gpg.
Preparing to unpack .../08-gpg_2.2.40-1.1_amd64.deb ...
Unpacking gpg (2.2.40-1.1) ...
Selecting previously unselected package pinentry-curses.
Preparing to unpack .../09-pinentry-curses_1.2.1-1_amd64.deb ...
Unpacking pinentry-curses (1.2.1-1) ...
Selecting previously unselected package gpg-agent.
Preparing to unpack .../10-gpg-agent_2.2.40-1.1_amd64.deb ...
Unpacking gpg-agent (2.2.40-1.1) ...
Selecting previously unselected package gpg-wks-client.
Preparing to unpack .../11-gpg-wks-client_2.2.40-1.1_amd64.deb ...
Unpacking gpg-wks-client (2.2.40-1.1) ...
Selecting previously unselected package gpg-wks-server.
Preparing to unpack .../12-gpg-wks-server_2.2.40-1.1_amd64.deb ...
Unpacking gpg-wks-server (2.2.40-1.1) ...
Selecting previously unselected package gpgsm.
Preparing to unpack .../13-gpgsm_2.2.40-1.1_amd64.deb ...
Unpacking gpgsm (2.2.40-1.1) ...
Selecting previously unselected package gnupg.
Preparing to unpack .../14-gnupg_2.2.40-1.1_all.deb ...
Unpacking gnupg (2.2.40-1.1) ...
Setting up libksba8:amd64 (1.6.3-2) ...
Setting up apt-transport-https (2.6.1) ...
Setting up libnpth0:amd64 (1.6-3) ...
Setting up libassuan0:amd64 (2.5.5-5) ...
Setting up gnupg-l10n (2.2.40-1.1) ...
Setting up gpgconf (2.2.40-1.1) ...
Setting up gpg (2.2.40-1.1) ...
Setting up gnupg-utils (2.2.40-1.1) ...
Setting up pinentry-curses (1.2.1-1) ...
Setting up gpg-agent (2.2.40-1.1) ...
Created symlink /etc/systemd/user/sockets.target.wants/gpg-agent-browser.socket                                                                                                    -> /usr/lib/systemd/user/gpg-agent-browser.socket.
Created symlink /etc/systemd/user/sockets.target.wants/gpg-agent-extra.socket ->                                                                                                    /usr/lib/systemd/user/gpg-agent-extra.socket.
Created symlink /etc/systemd/user/sockets.target.wants/gpg-agent-ssh.socket -> /                                                                                                   usr/lib/systemd/user/gpg-agent-ssh.socket.
Created symlink /etc/systemd/user/sockets.target.wants/gpg-agent.socket -> /usr/                                                                                                   lib/systemd/user/gpg-agent.socket.
Setting up gpgsm (2.2.40-1.1) ...
Setting up dirmngr (2.2.40-1.1) ...
Created symlink /etc/systemd/user/sockets.target.wants/dirmngr.socket -> /usr/li                                                                                                   b/systemd/user/dirmngr.socket.
Setting up gpg-wks-server (2.2.40-1.1) ...
Setting up gpg-wks-client (2.2.40-1.1) ...
Setting up gnupg (2.2.40-1.1) ...
Processing triggers for man-db (2.11.2-2) ...
Processing triggers for libc-bin (2.36-9+deb12u8) ...
Add OpenMPTCProuter repo...
Explanation: Prefer OpenMPTCProuter provided packages over the Debian native one                                                                                                   s
Package: *
Pin: origin repo.openmptcprouter.com
Pin-Priority: 1001
Explanation: Prefer libuv1 Debian native package
Package: libuv1
Pin: version *
Pin-Priority: 1003
--2024-10-18 13:41:03--  https://repo.openmptcprouter.com/openmptcprouter.gpg.ke                                                                                                   y
Resolving repo.openmptcprouter.com (repo.openmptcprouter.com)... 185.131.64.122
Connecting to repo.openmptcprouter.com (repo.openmptcprouter.com)|185.131.64.122                                                                                                   |:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1241 (1.2K) [application/octet-stream]
Saving to: '/etc/apt/trusted.gpg.d/openmptcprouter.gpg'

/etc/apt/trusted.gp 100%[===================>]   1.21K  --.-KB/s    in 0s

2024-10-18 13:41:04 (49.0 MB/s) - '/etc/apt/trusted.gpg.d/openmptcprouter.gpg' s                                                                                                   aved [1241/1241]

Install mptcp kernel and shadowsocks...
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://security.debian.org/debian-security bookworm-security InRelease
Get:3 http://archive.debian.org/debian buster-backports InRelease [51.4 kB]
Get:4 http://deb.debian.org/debian bullseye InRelease [116 kB]
Get:5 https://repo.openmptcprouter.com buster InRelease [2128 B]
Get:6 http://archive.debian.org/debian buster-backports/main amd64 Packages [481                                                                                                    kB]
Get:7 http://archive.debian.org/debian buster-backports/main Translation-en [410                                                                                                    kB]
Get:8 http://deb.debian.org/debian bullseye/main amd64 Packages [8066 kB]
Get:9 https://repo.openmptcprouter.com buster/main amd64 Packages [11.3 kB]
Get:10 http://deb.debian.org/debian bullseye/main Translation-en [6235 kB]
Fetched 15.4 MB in 4s (3567 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
dirmngr is already the newest version (2.2.40-1.1).
dirmngr set to manually installed.
The following additional packages will be installed:
  iptables libip6tc2 libipset13 libnetfilter-conntrack3 libnfnetlink0 libpkgconf3 pkgconf pkgconf-bin
Suggested packages:
  firewalld ed diffutils-doc zip
The following NEW packages will be installed:
  curl ipset iptables libcurl4 libip6tc2 libipset13 libnetfilter-conntrack3 libnfnetlink0 libpkgconf3 patch pkg-config pkgconf
  pkgconf-bin rename unzip
0 upgraded, 15 newly installed, 0 to remove and 1 not upgraded.
Need to get 1673 kB of archives.
After this operation, 5487 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bookworm/main amd64 libcurl4 amd64 7.88.1-10+deb12u7 [390 kB]
Get:2 http://deb.debian.org/debian bookworm/main amd64 curl amd64 7.88.1-10+deb12u7 [315 kB]
Get:3 http://deb.debian.org/debian bookworm/main amd64 libipset13 amd64 7.17-1 [67.5 kB]
Get:4 http://deb.debian.org/debian bookworm/main amd64 ipset amd64 7.17-1 [45.7 kB]
Get:5 http://deb.debian.org/debian bookworm/main amd64 libip6tc2 amd64 1.8.9-2 [19.4 kB]
Get:6 http://deb.debian.org/debian bookworm/main amd64 libnfnetlink0 amd64 1.0.2-2 [15.1 kB]
Get:7 http://deb.debian.org/debian bookworm/main amd64 libnetfilter-conntrack3 amd64 1.0.9-3 [40.7 kB]
Get:8 http://deb.debian.org/debian bookworm/main amd64 iptables amd64 1.8.9-2 [360 kB]
Get:9 http://deb.debian.org/debian bookworm/main amd64 libpkgconf3 amd64 1.8.1-1 [36.1 kB]
Get:10 http://deb.debian.org/debian bookworm/main amd64 patch amd64 2.7.6-7 [128 kB]
Get:11 http://deb.debian.org/debian bookworm/main amd64 pkgconf-bin amd64 1.8.1-1 [29.5 kB]
Get:12 http://deb.debian.org/debian bookworm/main amd64 pkgconf amd64 1.8.1-1 [25.9 kB]
Get:13 http://deb.debian.org/debian bookworm/main amd64 pkg-config amd64 1.8.1-1 [13.7 kB]
Get:14 http://deb.debian.org/debian bookworm/main amd64 rename all 2.01-1 [21.0 kB]
Get:15 http://deb.debian.org/debian bookworm/main amd64 unzip amd64 6.0-28 [166 kB]
Fetched 1673 kB in 1s (2827 kB/s)
Selecting previously unselected package libcurl4:amd64.
(Reading database ... 35727 files and directories currently installed.)
Preparing to unpack .../00-libcurl4_7.88.1-10+deb12u7_amd64.deb ...
Unpacking libcurl4:amd64 (7.88.1-10+deb12u7) ...
Selecting previously unselected package curl.
Preparing to unpack .../01-curl_7.88.1-10+deb12u7_amd64.deb ...
Unpacking curl (7.88.1-10+deb12u7) ...
Selecting previously unselected package libipset13:amd64.
Preparing to unpack .../02-libipset13_7.17-1_amd64.deb ...
Unpacking libipset13:amd64 (7.17-1) ...
Selecting previously unselected package ipset.
Preparing to unpack .../03-ipset_7.17-1_amd64.deb ...
Unpacking ipset (7.17-1) ...
Selecting previously unselected package libip6tc2:amd64.
Preparing to unpack .../04-libip6tc2_1.8.9-2_amd64.deb ...
Unpacking libip6tc2:amd64 (1.8.9-2) ...
Selecting previously unselected package libnfnetlink0:amd64.
Preparing to unpack .../05-libnfnetlink0_1.0.2-2_amd64.deb ...
Unpacking libnfnetlink0:amd64 (1.0.2-2) ...
Selecting previously unselected package libnetfilter-conntrack3:amd64.
Preparing to unpack .../06-libnetfilter-conntrack3_1.0.9-3_amd64.deb ...
Unpacking libnetfilter-conntrack3:amd64 (1.0.9-3) ...
Selecting previously unselected package iptables.
Preparing to unpack .../07-iptables_1.8.9-2_amd64.deb ...
Unpacking iptables (1.8.9-2) ...
Selecting previously unselected package libpkgconf3:amd64.
Preparing to unpack .../08-libpkgconf3_1.8.1-1_amd64.deb ...
Unpacking libpkgconf3:amd64 (1.8.1-1) ...
Selecting previously unselected package patch.
Preparing to unpack .../09-patch_2.7.6-7_amd64.deb ...
Unpacking patch (2.7.6-7) ...
Selecting previously unselected package pkgconf-bin.
Preparing to unpack .../10-pkgconf-bin_1.8.1-1_amd64.deb ...
Unpacking pkgconf-bin (1.8.1-1) ...
Selecting previously unselected package pkgconf:amd64.
Preparing to unpack .../11-pkgconf_1.8.1-1_amd64.deb ...
Unpacking pkgconf:amd64 (1.8.1-1) ...
Selecting previously unselected package pkg-config:amd64.
Preparing to unpack .../12-pkg-config_1.8.1-1_amd64.deb ...
Unpacking pkg-config:amd64 (1.8.1-1) ...
Selecting previously unselected package rename.
Preparing to unpack .../13-rename_2.01-1_all.deb ...
Unpacking rename (2.01-1) ...
Selecting previously unselected package unzip.
Preparing to unpack .../14-unzip_6.0-28_amd64.deb ...
Unpacking unzip (6.0-28) ...
Setting up libip6tc2:amd64 (1.8.9-2) ...
Setting up unzip (6.0-28) ...
Setting up rename (2.01-1) ...
update-alternatives: using /usr/bin/file-rename to provide /usr/bin/rename (rename) in auto mode
Setting up libpkgconf3:amd64 (1.8.1-1) ...
Setting up patch (2.7.6-7) ...
Setting up pkgconf-bin (1.8.1-1) ...
Setting up libipset13:amd64 (7.17-1) ...
Setting up libnfnetlink0:amd64 (1.0.2-2) ...
Setting up libcurl4:amd64 (7.88.1-10+deb12u7) ...
Setting up curl (7.88.1-10+deb12u7) ...
Setting up ipset (7.17-1) ...
Setting up pkgconf:amd64 (1.8.1-1) ...
Setting up pkg-config:amd64 (1.8.1-1) ...
Setting up libnetfilter-conntrack3:amd64 (1.0.9-3) ...
Setting up iptables (1.8.9-2) ...
update-alternatives: using /usr/sbin/iptables-legacy to provide /usr/sbin/iptables (iptables) in auto mode
update-alternatives: using /usr/sbin/ip6tables-legacy to provide /usr/sbin/ip6tables (ip6tables) in auto mode
update-alternatives: using /usr/sbin/iptables-nft to provide /usr/sbin/iptables (iptables) in auto mode
update-alternatives: using /usr/sbin/ip6tables-nft to provide /usr/sbin/ip6tables (ip6tables) in auto mode
update-alternatives: using /usr/sbin/arptables-nft to provide /usr/sbin/arptables (arptables) in auto mode
update-alternatives: using /usr/sbin/ebtables-nft to provide /usr/sbin/ebtables (ebtables) in auto mode
Processing triggers for man-db (2.11.2-2) ...
Processing triggers for mailcap (3.70+nmu1) ...
Processing triggers for libc-bin (2.36-9+deb12u8) ...
-                                  99%[==========================================================> ]  88.00K   106KB/s               -                                             -2024-10-18 13:41:16--  https://dl.xanmod.org/archive.key
Resolving dl.xanmod.org (dl.xanmod.org)... 188.114.96.1, 188.114.97.1, 2a06:98c1:3121::1, ...
Connecting to dl.xanmod.org (dl.xanmod.org)|188.114.96.1|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1702 (1.7K) [application/octet-stream]
Saving to: '/etc/apt/trusted.gpg.d/xanmod.gpg'

/etc/apt/trusted.gpg.d/xanmod.gpg 100%[===========================================================>]   1.66K  --.-KB/s    in 0s

2024-10-18 13:41:16 (15.1 MB/s) - '/etc/apt/trusted.gpg.d/xanmod.gpg' saved [1702/1702]

Hit:1 http://security.debian.org/debian-security bookworm-security InRelease
Hit:2 http://deb.debian.org/debian bookworm InRelease
Hit:3 http://deb.debian.org/debian bullseye InRelease
Hit:4 http://archive.debian.org/debian buster-backports InRelease
Get:5 http://deb.xanmod.org releases InRelease [2091 B]
Hit:6 https://repo.openmptcprouter.com buster InRelease
Err:5 http://deb.xanmod.org releases InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 86F7D09EE734E623
Reading package lists... Done
W: http://security.debian.org/debian-security/dists/bookworm-security/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/xanm                                             od.gpg are ignored as the file has an unsupported filetype.
W: http://deb.debian.org/debian/dists/bookworm/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/xanmod.gpg are ignored as t                                             he file has an unsupported filetype.
W: http://deb.debian.org/debian/dists/bullseye/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/xanmod.gpg are ignored as t                                             he file has an unsupported filetype.
W: http://archive.debian.org/debian/dists/buster-backports/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/xanmod.gpg are                                              ignored as the file has an unsupported filetype.
W: http://deb.xanmod.org/dists/releases/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/xanmod.gpg are ignored as the file                                              has an unsupported filetype.
W: GPG error: http://deb.xanmod.org releases InRelease: The following signatures couldn't be verified because the public key is not av                                             ailable: NO_PUBKEY 86F7D09EE734E623
E: The repository 'http://deb.xanmod.org releases InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: https://repo.openmptcprouter.com/dists/buster/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/xanmod.gpg are ignored as                                              the file has an unsupported filetype.
-                                  99%[==========================================================> ]  88.00K  4.31KB/s    in 20s


Cannot write to ‘-’ (Broken pipe).

**Comment by Ysurac** [comment]
This is stable kernel release, it doesn't support kernel 6.6 yet.
To use kernel 6.6, you need to use Release Candidate or Snapshot script: https://github.com/Ysurac/openmptcprouter/wiki/Snapshots
