### ISSUE TITLE
VPN Tunnel Down, bad config ?

### ISSUE THREAD

**Issue by victorleduc** [Ysurac/openmptcprouter#361]
## Expected Behavior

  VPN should be UP

## Actual Behavior

Hi, I think I have a config issue, but can't really tell what I did wrong.
Here are some screenshots : 
<img width="1038" alt="screenshot 2019-02-14 at 13 12 34" src="https://user-images.githubusercontent.com/4113162/52786575-87340000-305b-11e9-8632-f92e83a21c51.png">
<img width="1126" alt="screenshot 2019-02-14 at 13 13 25" src="https://user-images.githubusercontent.com/4113162/52786587-8e5b0e00-305b-11e9-954b-41e49329de69.png">
<img width="1135" alt="screenshot 2019-02-14 at 13 13 48" src="https://user-images.githubusercontent.com/4113162/52786591-92872b80-305b-11e9-8283-64d493ba1df2.png">
<img width="640" alt="screenshot 2019-02-14 at 13 16 45" src="https://user-images.githubusercontent.com/4113162/52786597-961ab280-305b-11e9-9270-bb3f692bc582.png">

I can't find the OpenVPN key in the VPS, where it is, and is it why it's not working ?

Thanks for the help :)

## Specifications

  - OpenMPTCProuter version: v0.46.3
  - OpenMPTCProuter VPS version: 0.93
  - OpenMPTCProuter platform: Linksys WRT3200ACM

**Comment by victorleduc** [comment]
And here is the logs when I hit "Save and Apply" in the Wizard :
![screenshot 2019-02-14 at 13 40 54](https://user-images.githubusercontent.com/4113162/52787696-ecd5bb80-305e-11e9-9aa7-60407e9984e7.png)

**Comment by victorleduc** [comment]
And here is the result of uci show
[uci_show.txt](https://github.com/Ysurac/openmptcprouter/files/2865045/uci_show.txt)

**Comment by zicochaos** [comment]
disable ipv6

**Comment by victorleduc** [comment]
Hi, if I disable ipv6, it only make the orange message "VPN Ipv6 tunnel down", but I still got "VPN tunnel down"

**Comment by zicochaos** [comment]
setup address for at least two wan's

**Comment by victorleduc** [comment]
It seems strange that it can not work with only one WAN, I wanted to config it waiting for my VDSL line in a few weeks. And I'm not sure but I think I saw screenshot of working VPN with only one WAN.
Can you confirm @yrusac ?

**Comment by victorleduc** [comment]
After searching a little, i saw that my server always had SSH port 22 and not 65222 (and supposedly Shadowsocks/Glorytun too?), so I needed to reboot the VPS and it is now better : 
<img width="997" alt="screenshot 2019-02-14 at 16 35 40" src="https://user-images.githubusercontent.com/4113162/52797821-f703b400-3076-11e9-8255-8fe729b4adce.png">
Can you help me with the last error ?

**Comment by victorleduc** [comment]
I just waited a little and apparently it started working ! 😄
<img width="1026" alt="screenshot 2019-02-14 at 16 51 38" src="https://user-images.githubusercontent.com/4113162/52798813-f66c1d00-3078-11e9-8b81-ea6e7d8715ac.png">

**Comment by Ysurac** [comment]
I'm happy to help to resolve this issue by doing nothing :smile: 
If you don't use them you should disable multipath on wan2 to wan4 interface in Network->MPTCP interface.

**Comment by victorleduc** [comment]
Done :)
