### ISSUE TITLE
can't login ssh with finalshell 3.9.2.2 Algorithm negotiation fail

### ISSUE THREAD

**Issue by fareign** [Ysurac/openmptcprouter#3619]
Algorithm negotiation fail
but can login with putty.
how to change it?

## Specifications

  - OpenMPTCProuter version: 0.61 6.6kernel
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter VPS provider:
  - OpenMPTCProuter platform: x86_64
  - Country:

**Comment by Ysurac** [comment]
I never used filalshell. On OpenMPTCProuter, dropbear is used as SSH server. There is no sftp server and this may be what finalshell want, in this case you need to install ```openssh-sftp``` package.
