### ISSUE TITLE
Nginx or Apacha + MPTCP server ?

### ISSUE THREAD

**Issue by infrarik** [Ysurac/openmptcprouter#362]
Hi,

is it possible to have on the same hosted server nginx or apache2 and openmptcp server ?
I am using a very simple Kimsufi from Ovh with Debian 9 mptcp kernel: openmptcp works fine using a Raspberry PI 3, but I can't find a solution to have incoming connections from the internet : http://mymptcpserver.xx:8181 doesn't give me access to the LAN device I want to reach.

I tested a similar system, using this time an "empty" hosted server (= no nginx, no apache2, just openmptcp server) and it works fine.

Any hints on what I should add to nginx or apache2 config files, or maybe something else ? I'm a real beginner with all this ;-)

**Comment by Ysurac** [comment]
Yes it's possible. You have to open the port in /etc/shorewall and /etc/shorewall6 if you have IPv6.
