### ISSUE TITLE
Incorrect configuration for shadowsocks-rust ss_tunnel

### ISSUE THREAD

**Issue by ShadowOfTheDay** [Ysurac/openmptcprouter#3646]
## Expected Behavior
According to the [configuration](https://github.com/shadowsocks/shadowsocks-rust?tab=readme-ov-file#configuration) of shadowsocks-rust, for tunnel mode, the `forward_address` and `forward_port` should be set. 

## Current Behavior
The current implementation of shadowsocks-rust in OpenMPTCProuter follows the configuration of shadowsocks-libev, forward address and port are configured in `tunnel_address`, which is not used by shadowsocks-rust. As a result, ss_tunnel will not start. 

## Steps to Reproduce the Problem

Keep the default setting of ss_tunnel.dns and it won't start. The following message can be found in the log.
```
daemon.info procd: Instance shadowsocks-rust::ss_tunnel.dns s in a crash loop 6 crashes, 0 seconds since last crash
```

**Comment by Ysurac** [comment]
Thanks, It's fixed. New Snapshot is compiling.

**Comment by Ysurac** [comment]
Fixed again, this time it should work.

**Comment by Ysurac** [comment]
Thanks it's fixed, this explain why it was not working correctly...
