### ISSUE TITLE
Dynamic Master

### ISSUE THREAD

**Issue by its27** [Ysurac/openmptcprouter#365]
## Expected Behavior

When a interface has a lower latency (greater than the threshold) and dynamic master is enabled that interface will be set to master, this change will be visible on the status page.

## Actual Behavior

When a interface has a lower latency (greater than the threshold) and dynamic master is enabled the tracker shows that it is swcthed to be master however the status page still shoes that the previous interface is the master.

Sun Feb 17 11:59:40 2019 user.notice post-tracking-post-tracking: Change master interface from wwan (1000 ms) to wwan2 (81 ms)

After this message I can see the default route was changed (I have no VPN enabled) however the status page still shows wwan is the master.

## Specifications

  - OpenMPTCProuter version: 0.46.3 r09228
  - OpenMPTCProuter VPS version: 0.90
  - OpenMPTCProuter platform: RPI2

**Comment by Ysurac** [comment]
True, dynamic master doesn't commit changes, this give faster result. I don't think it's a real problem.
