### ISSUE TITLE
Port Forwarding

### ISSUE THREAD

**Issue by NovaDavid** [Ysurac/openmptcprouter#367]
## Expected Behavior

  Port forwarding doesn't work

## Actual Behavior

When i try to forward some ports like 8000 or 3389, it doesn't work. I try with to different windows server and two differents gateways (4G and fiber).

I followed documentation for port forwarding and SNAT. Firewall is off on my windows server and access work on local network.

## Steps to Reproduce the Problem

  1. Configure port forwarding and SNAT
  2. Test it with OpenMPTCProuter Server public IP
  3.

## Specifications

  - OpenMPTCProuter version: (0.46.3)
  - OpenMPTCProuter VPS version: (0.93)
  - OpenMPTCProuter platform: (/RPI3/x86_64)
  - Glorytun Enable
  - Router 192.168.100.1 / WebServer 192.168.100.15

![capture](https://user-images.githubusercontent.com/47745901/52959448-815d5800-3396-11e9-8ff7-99187888d3b8.JPG)
![capture1](https://user-images.githubusercontent.com/47745901/52959450-815d5800-3396-11e9-92b0-05c78c31d896.JPG)

**Comment by Ysurac** [comment]
DNAT line at the end of /etc/shorewall/rules on the VPS is not commented ?

**Comment by NovaDavid** [comment]
Yes there is a '#' but when i remove it, it reappear after a reboot of the VPS.

**Comment by NovaDavid** [comment]
It was because in VPS Settings "Redirect all ports" was unchecked.

![capture](https://user-images.githubusercontent.com/47745901/53001544-2de91980-342b-11e9-8846-9bca7cc44075.JPG)

But now i have "Can't get public IP address from ShadowSocks" on VPS

**Comment by Ysurac** [comment]
I would need the result of ```uci show``` on OpenMPTCProuter via SSH (remove at least server ip before pasting)

**Comment by NovaDavid** [comment]
After a reboot of the raspberry and the VPS everything working fine now. Thanks for your help on your work !
