### ISSUE TITLE
SyntaxError Unexpected token '.'

### ISSUE THREAD

**Issue by thindata** [Ysurac/openmptcprouter#3673]
On a fresh x86 install after logging into the gui i get

SyntaxError
Unexpected token '.'
  in http://192.168.100.1/luci-static/resources/uqr.js?v=24.212.79282~65b8002:?
  at http://192.168.100.1/luci-static/resources/luci.js?v=24.212.79282~65b8002:179:29

Firmware Version：openmptcprouter v0.61-6.6 r0+27346-c7ba5574f5

**Comment by Ysurac** [comment]
Please use template.
Refresh your browser cache or try another browser.

**Comment by thindata** [comment]
That fixed it
