### ISSUE TITLE
Aggregate seems doesn't work

### ISSUE THREAD

**Issue by Amrizamaa** [Ysurac/openmptcprouter#3684]
## Expected Behavior

It should work with aggregation and have like 50mbp/s debit minimum

## Current Behavior

on my side it's seems the aggregate doesn't work properly, like for now the vps can't get the public ip address and it seems only have my adsl works as maximum debit
i have a message like the vps  can't get public ip address

![image](https://github.com/user-attachments/assets/c5406f66-3f7a-4656-b289-290fc47f95e2)
![image](https://github.com/user-attachments/assets/76444ef8-b0ff-4768-a4d9-3e166f073215)

When i'm only on wi-fi of my 5G i have 50mbp/s but when i'm wired to openmptcp router i have no more of 5mbp/s

![WhatsApp Image 2024-11-26 à 10 51 08_c3e2a9d8](https://github.com/user-attachments/assets/cb104478-0e37-4f28-925b-784ee4e2112b)

## Specifications

  - OpenMPTCProuter version: 6.6.50
  - OpenMPTCProuter VPS version: 0.1031 / 6.6.36
  - OpenMPTCProuter VPS provider: Iglao / Skorpia (2vps)
  - OpenMPTCProuter platform: x64 theorically

**Comment by Ysurac** [comment]
As indicated on screenshot, fix the time on the router. As there is 1 hour of difference, I think you set the time without setting the timezone in System->System

**Comment by Ysurac** [comment]
Can you take a screenshot of status page when time is fixed ?
What is the result of ```journalctl -u shadowsocks-go``` on the VPS ?

**Comment by Amrizamaa** [comment]
![image](https://github.com/user-attachments/assets/d34d5140-3785-4ca8-b6fa-53e704a825ea)


https://pastebin.com/gpX6eWEZ

only copied last minute sorry for my time response

**Comment by Ysurac** [comment]
What do you have in Status->System log ?

**Comment by Amrizamaa** [comment]
This issue is solved without any modification idk what happened
