### ISSUE TITLE
iptables-restore: setname max 31 chars

### ISSUE THREAD

**Issue by lars18th** [Ysurac/openmptcprouter#370]
- OpenMPTCProuter version: openmptcprouter v0.46.3
 - OpenMPTCProuter VPS version: NA
 - OpenMPTCProuter platform: x86_64

Hi @Ysurac , this is part of my current System Log:
```
...
Wed Feb 20 14:25:58 2019 user.notice omr-bypass: Starting OMR-ByPass...
Wed Feb 20 14:25:58 2019 daemon.err omr-tracker[5511]: ip6tables-restore v1.8.2 (legacy): setname `omr_rules6_dst_bypass_pppoe-wan1' too long, max 31 characters.
Wed Feb 20 14:25:58 2019 daemon.err omr-tracker[5511]: Error occurred at line: 2
Wed Feb 20 14:25:58 2019 daemon.err omr-tracker[5511]: Try `ip6tables-restore -h' or 'ip6tables-restore --help' for more information.
Wed Feb 20 14:25:58 2019 daemon.err omr-tracker[5511]: ip6tables-restore v1.8.2 (legacy): setname `omr_rules6_dst_bypass_pppoe-wan2' too long, max 31 characters.
Wed Feb 20 14:25:58 2019 daemon.err omr-tracker[5511]: Error occurred at line: 2
...
```

Please, note the `ip6tables-restore ...: setname "omr_rules6_dst_bypass_pppoe-wan1" too long, max 31 characters.`
My WAN1 "logical" interface, uses the device called "pppoe-wan1" so the name of the rule is too long.

I suggest to use more short names, like `_dst_bypass_***`, as we don't need to prepend `omr_rules6`.

I hope you agree! :wink:

**Comment by Ysurac** [comment]
This will be fixed in next release
