### ISSUE TITLE
Iperf speed tests

### ISSUE THREAD

**Issue by lars18th** [Ysurac/openmptcprouter#371]
Hi @Ysurac ,
I suggest to add the option for a "custom" server. When connecting to a private network, current servers aren't available.

Thank you!

**Comment by Ysurac** [comment]
OpenMPTCProuter is not designed for private network.

**Comment by lars18th** [comment]
Hi,

As a reference, we can edit the file `/etc/config/iperf` and put in it any "user configured iperf servers".
So, I suggest to include this info in the documentation (perhaps some other user want to use other public servers).

Regards.
