### ISSUE TITLE
VPN Tunnel down after VPS has been restarted (Manual reboot needed)

### ISSUE THREAD

**Issue by 3dzug** [Ysurac/openmptcprouter#3712]
## Expected Behavior

Once the VPS has been restarted the local Openmtcp router should establish the connection to VPS again and should be online again. 

## Current Behavior

Error message vpn-tunnel is down is posted in the overview tab. 

## Possible Solution

Reboot the local server to establish the connection again.

## Steps to Reproduce the Problem

1. Set Proxy to XRay Vless and VPN to Glorytun UDP
2. Restart VPS
3. Try to use the internet connection. 

## Context (Environment)

If the vps has been rebooted (or was offline) I manually have to reboot the local server.

I am facing the issue that the internet connection is not available once the vps server causes a problem. If you need some logs please let me know as this one is easy to test.

## Specifications

OpenMPTCProuter version: 0.61-6.6
OpenMPTCProuter VPS version: 0.1031 6.6.36y64v3-xanmod1
OpenMPTCProuter VPS provider: HT-Hosting
OpenMPTCProuter platform: x86_64
Country: Germany

**Comment by Ysurac** [comment]
I'm not able to reproduce this issue on latest snapshot: https://github.com/Ysurac/openmptcprouter/wiki/Snapshots
Can you try ? If you still have the issue, I would need the log from Status->System log

**Comment by 3dzug** [comment]
The bug doesnt occur on the latest iamge. Thanks for fixing
