### ISSUE TITLE
http for *.openmptcrouter.com does not load, and the https certificate has expired

### ISSUE THREAD

**Issue by Makeshift** [Ysurac/openmptcprouter#3718]
The VPS installer scripts use `http://hostname.openmptcprouter.com` and `http://ip.openmptcprouter.com`. Neither of these currently seem to load and simply time-out. `https` will load, but the certificate expired last month.

I was able to install my VPS yesterday, so I assume this only went down today. Just thought I'd let you know in case you were unaware.

**Comment by Ysurac** [comment]
Fixed. I need to migrate them to another server...
