### ISSUE TITLE
Guidance of expanding nvme to use full drive

### ISSUE THREAD

**Issue by speegs** [Ysurac/openmptcprouter#3730]
Is there a guide for expanding the disk image to use the full nvme?

Or is it possibly to expand/size the .img file before using dd to copy the firmware over?  Which might be easier.  Seeking advice on the best way to go.  Using EFI, EXT4 image on X64 Architecture.

I tried a few openwrt resizing scripts, didn't workout, after the most efficient and pain free way.

**Comment by q2go** [comment]
The non-EFI ext4 image might be slightly easier to handle as it only consists of a single partition, but the general procedure is the same: One usually extracts the downloaded image to the device, makes use of GNU parted to have the ext4 partition span the whole disk, and then invokes resize2fs to spread the ext4 file system over the whole partition.

Google should help you find more detailed instructions. If you come across a web page which covers the topic well, feel free to share it here.

**Comment by speegs** [comment]
For me 2 tools, debian (live iso) to do the download the image and run dd as per the documentation.

Then reboot with gparted live iso to do it's job of the resize.  I'm sure there is probably a way to do it more efficiently, but this worked so recommended it for anyone else who doesn't usually mess around with such things.
