### ISSUE TITLE
Graphical section for shadowsocks (or tunnel) statistics

### ISSUE THREAD

**Issue by lars18th** [Ysurac/openmptcprouter#375]
Hi @Ysurac ,

At time it's difficult to adjust some settings. I miss some statistics about the tunnelling instance.
How I can see/check if the shadowsocks is working right?

Thank you for this good project!

**Comment by Ysurac** [comment]
There is no statistics available for shadowsocks.

**Comment by lars18th** [comment]
So, it's impossible to check if it works right?

**Comment by Ysurac** [comment]
True. Shadowsocks-libev doesn't give any easy way to get statistics for now.

**Comment by Ysurac** [comment]
It's why there is ss-tracker that check if TCP traffic can use shadowsocks.
