### ISSUE TITLE
Is some OpenMPTCPRouter feature relies on OpenMPTCPRouter.com?

### ISSUE THREAD

**Issue by dnwk** [Ysurac/openmptcprouter#379]
While the website of OpenMPTCPRouter.com went down on Sunday, the router won't be able to get public IP and post-tracking-post-tracking:Get status and settings for wan 1 show up failed in system log. 

Is there a way to make calling out to external website optional or configurable? I hope the function of the router should not be depend on an external website.

**Comment by Ysurac** [comment]
ip.openmptcprouter.com is used to detect server public IP (no really other choice to get public IP).
But when the server was done this shouldn't impact any router because other sites should be used in this cas. I will check where the problem is.
I will also make this fully configurable ;)

**Comment by dnwk** [comment]
post-tracking-post-tracking:Get status for wan 1 fail shows up in the log. Is it also related to openmptcprouter.com went down?   Because those warning in the log goes away once site is back up.

**Comment by Ysurac** [comment]
Yes it's related. This script also get IP of each wan.

**Comment by Randdrick** [comment]
Hello,
I think there is also a problem with admin server scripts. (see capture image)
![capture](https://user-images.githubusercontent.com/47564301/53528577-47a0f580-3aea-11e9-9b10-db2623f79080.JPG)

**Comment by flimo44** [comment]
Hello,
I have same problem with admin server script.

**Comment by Ysurac** [comment]
It's not related.

**Comment by user747** [comment]
Does it still call if omr-tracker disabled? 

https://github.com/Ysurac/openmptcprouter-feeds/blob/09b2d20c2f46ac03a2aa861e4df6d84bb2f2b5bf/luci-app-openmptcprouter/luasrc/controller/openmptcprouter.lua#L702

**Comment by Ysurac** [comment]
Yes in status page.
You have to wait for next version to have a checkbox to disable IP check.

**Comment by user747** [comment]
> Yes in status page.
> You have to wait for next version to have a checkbox to disable IP check.

Could also have option to switch server default too. 

`wget -4 -qO- -T 2 http://checkip.dyndns.org/`

**Comment by Ysurac** [comment]
Checkbox available in OpenMPTCProuter v0.47

**Comment by user747** [comment]
On v0.48 rpi3 squashfs

Check
['Disable external check'](https://github.com/Ysurac/openmptcprouter-feeds/blob/cf89a46736334d6aa1957d6fdab2ac36bd35e5ef/luci-app-openmptcprouter/luasrc/view/openmptcprouter/settings.htm#L134) 

Save & Apply
Page refreshes
No change

root@OpenMPTCProuter:/tmp# uci -q get openmptcprouter.settings.external_check
1

I think after change, it should be "0" ? 

Anything but 0 and it runs like default
if uci:get("openmptcprouter","settings","external_check") ~= "0" then

**Comment by Ysurac** [comment]
This will be fixed in next release.

In omr-tracker this doesn't call the website, only check if it can be resolved (and only in the case user want dns check).

**Comment by Ysurac** [comment]
Option to choose between website to check the IP is not so easy: my website return only the IP, for dyndns there is some text, so I would need to parse that...

**Comment by dnwk** [comment]
Try this http://myip.cpanel.net/

**Comment by user747** [comment]
Another one 
`curl ifconfig.co`
