### ISSUE TITLE
Bandwidth monitor

### ISSUE THREAD

**Issue by Ajowan84** [Ysurac/openmptcprouter#380]
Suggestion:

Add a bandwidth monitor like Netlink but with more features.
data quota per day
data quota per users
eMail warning when a certain amount data is used.

A good thing for 4G connection users with limited data

**Comment by alexbidule** [comment]
+1 on this feature !

Also having a quota per week day (Monday, Tuesday, Wednesday...) would be great. On my side I have unlimited data in weekends :-)

**Comment by Gordon0472** [comment]
Hi,
+1 on this feature for 4G users !!!

Is it possible to install Yamon (http://usage-monitoring.com/index.php) for example : ?
It perfectly matches what I'm looking for ...

Best regardes

**Comment by jayanta525** [comment]
> Is it possible to install Yamon (http://usage-monitoring.com/index.php) for example : ?

Yamon is not maintained properly. Targetted for DD-WRT users. OpenWrt has many inferior packages.
For bandwidth monitoring, check out `luci-app-nlbwmon` and `luci-app-wrtbwmon`.

luci-app-nlbwmon provides traffic per host and usage according to protocols. Also supports IPv6.

![image](https://user-images.githubusercontent.com/30702133/58644589-34870700-831f-11e9-8cae-8a7583d47c7f.png)

luci-app-wrtbwmon provides live data usage tracking of clients along with the total usage.

![image](https://user-images.githubusercontent.com/30702133/58644660-597b7a00-831f-11e9-8741-bb78575c8bd6.png)


> Also having a quota per week day (Monday, Tuesday, Wednesday...) would be great. On my side I have unlimited data in weekends :-)

OMR does have monthly quota support. This could easily be adjusted for daily quota.

**Comment by Ajowan84** [comment]
Thank you so much jayanta525 !
I installed both packages.
luci-app-wrtbwmon works perfectly but luci-app-nlbwmon does not display anything.
it stays on "Data Recovery ..."

**Comment by jayanta525** [comment]
Check whether nlbwmon startup script is enabled.

**Comment by Ajowan84** [comment]
How to check this ?

I used this to start nldwmon :
/etc/init.d/nlbwmon enable
/etc/init.d/nlbwmon start

But i don't know if is ok...

**Comment by Ajowan84** [comment]
When i install nldwmon, i have the error "uci - Entry not found"
