### ISSUE TITLE
Add a speedtest from router to server with all interface

### ISSUE THREAD

**Issue by Roken120** [Ysurac/openmptcprouter#381]
Hello,
I have a recommandation you can add a speed monitor from router to server for test the speed of all link and aggregation ?

**Comment by RomanJos** [comment]
Thats what i think too a speedtest on each wan would be awesome !

**Comment by forid786** [comment]
Iperf? It's already installed.

**Comment by Roken120** [comment]
Yes,
It would be nice to be able to test directly with the openmctpvps in order to check the aggregation
Example:
WAN1 -> VPS
WAN2 -> VPS
Aggregation -> VPS
For check the aggregation is correct

**Comment by Ysurac** [comment]
True Iperf is installed on both VPS and OpenMPTCProuter side.
```omr-iperf``` can be used to check aggregation speed, in next version it should be able to test link speed.

**Comment by Ysurac** [comment]
Can be used in fact by using ```omr-iperf vps -B ipofwan``` (and ```omr-iperf vps``` to only check aggregation).
