### ISSUE TITLE
missing dependencies / wrt1900acs

### ISSUE THREAD

**Issue by ahmedibnaser** [Ysurac/openmptcprouter#383]
## Expected Behavior

I am trying to compile a version for my WRT1900acs v2.

I have setup my environment on Mac OS X 10.14.3.

## Actual Behavior

When I run make prereq -j6 V=sc, here is what I see, and it appears it will not compile. I am not sure what do. Can you please guide me?

WARNING: Makefile 'package/utils/busybox/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/busybox/Makefile' has a build dependency on 'libpam', which does not exist
WARNING: Makefile 'package/network/utils/curl/Makefile' has a dependency on 'libgnutls', which does not exist
WARNING: Makefile 'package/network/utils/curl/Makefile' has a dependency on 'libopenldap', which does not exist
WARNING: Makefile 'package/network/utils/curl/Makefile' has a dependency on 'libidn2', which does not exist
WARNING: Makefile 'package/network/utils/curl/Makefile' has a dependency on 'libssh2', which does not exist
WARNING: Makefile 'package/boot/kexec-tools/Makefile' has a dependency on 'liblzma', which does not exist
WARNING: Makefile 'package/network/services/lldpd/Makefile' has a dependency on 'libnetsnmp', which does not exist
WARNING: Makefile 'package/network/utils/nftables/Makefile' has a dependency on 'jansson', which does not exist

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - OpenMPTCProuter version: (Last is not a version)
  - OpenMPTCProuter VPS version: (Last is not a version)
  - OpenMPTCProuter platform: (RPI2/RPI3/x86/x86_64)

**Comment by Ysurac** [comment]
You can ignore these warnings.
And WRT1900ACS is not a supported platform for OpenMPTCProuter : 128Mo Flash is not enough, some packages must be removed for that and generated image size must be defined to 128 instead of 256Mo.
