### ISSUE TITLE
WAN1 (key 4G) near to zero !

### ISSUE THREAD

**Issue by CoSysopK** [Ysurac/openmptcprouter#389]
## Actual Behavior

![network](https://user-images.githubusercontent.com/48426317/54100773-81aea900-43c0-11e9-89ba-43ac3c05b3b0.jpg)

Connexion WAN1 it does not work well !
Often at zero, and from time to time, a peak at 0.1 Mb/s with nperf.
It's hard to analyse the network with WAN1 because the connexion is to 0 and, there is micros connexions
to 0.1 Mb/s

Connexion WAN2 it's WORK !

## Steps to Reproduce the Problem

  1. Raspberry PI 3/3B+ (64-bit) and, ext4 image: https://www.openmptcprouter.com/files/openmptcprouter-v0.46.3-r09228-a3ccac6b1d-brcm2708-bcm2710-rpi-3-ext4-sysupgrade.img.gz
  2. VPS Ubuntu Server 18.04 x86_64 and, VPS script : wget -O - http://www.openmptcprouter.com/server/ubuntu18.04-x86_64.sh | sh
  2. Configure the router with the wan1 static and, wan2 static
  2. Add the IP address VPS and, all the informations (shadowsocks key, glorytun key, MLVPN password and OpenMPTCProuter VPS Admin key) retrived on the VPS
  3. 1 key 4G on usb PI 3B and, 1 key 4g wifi

## Specifications

  - OpenMPTCProuter version: v0.46.3
  - OpenMPTCProuter VPS version: install the 10 march with this link:  https://github.com/Ysurac/openmptcprouter/wiki/Install-or-update-the-VPS
  - OpenMPTCProuter platform: RPI3

**Comment by Ysurac** [comment]
You can try ```omr-test-speed wan1```, ```omr-test-speed wan2``` and ```omr-test-speed```. This will check wan1,wan2 and aggregated speed.

**Comment by CoSysopK** [comment]
I don't have this command.

In the OpenMPTCProuter interface, Services > iPerf :

WAN1: (When WAN1 is the alone connexion)
Upload -
error - control socket has closed unexpectedly
Download -
error - control socket has closed unexpectedly

WAN2: (When WAN2 is the alone connexion)
Upload - 
Server: ping.online.net - Sender: 23.07Mb/s - Receiver: 17.16Mb/s
Download - 
Server: ping.online.net - Sender: 21.89Mb/s - Receiver: 21.17Mb/s
![test](https://user-images.githubusercontent.com/48426317/54105736-4027f900-43d4-11e9-859e-44681f8420f6.jpg)

**Comment by renaudadu** [comment]
Hello, for omr-speed-test command, you use ssh to your openmptcprouter.

**Comment by CoSysopK** [comment]
![test2](https://user-images.githubusercontent.com/48426317/54106836-b0844980-43d7-11e9-8876-df8fa2bf66b6.jpg)

I started doing a test with the following commands but it is necessary to wait for 10 GB of data, it is a lot of data whereas I am in 4G and not in unlimited.
How to make a test that uses less data?

**Comment by renaudadu** [comment]
No wait. Just launch the command for both Wan interface.

**Comment by renaudadu** [comment]
Try with thé second name of the interface. Like eth1 for wan1.

**Comment by CoSysopK** [comment]
WAN1:
![eth1](https://user-images.githubusercontent.com/48426317/54107233-d100d380-43d8-11e9-9ac2-ccfa68df77d5.jpg)

WAN2:
![wlan0](https://user-images.githubusercontent.com/48426317/54107279-f1309280-43d8-11e9-9de7-43cd98a87f83.jpg)

**Comment by CoSysopK** [comment]
After several errors, here is the test:
WAN1:
![test-eth1](https://user-images.githubusercontent.com/48426317/54107999-10302400-43db-11e9-93de-fea46da81853.jpg)

**Comment by renaudadu** [comment]
I have the same speed when my 4g quota is full and my 4g speed pass in low speed.
My connection in low speed mode was not good. Up and down very often.

**Comment by CoSysopK** [comment]
Phew, It's exactly that !
I just changed sim and it's perfect.

Thanks for your work !

Have a good day
