### ISSUE TITLE
Unbound custom settings did not survive system upgrade

### ISSUE THREAD

**Issue by dnwk** [Ysurac/openmptcprouter#392]
(/etc/unbound/unbound_ext.conf) file get wiped during sysupgrade.

**Comment by Ysurac** [comment]
Can you give me, if this doesn't work in latest release, the result of ```sysupgrade -l``` via SSH on OpenMPTCProuter ? Also this file is in the backup made via the interface ?

**Comment by dnwk** [comment]
When I upgraded to 47.1, the settings were kepted.
