### ISSUE TITLE
Glorytun Fixed IP addres not working

### ISSUE THREAD

**Issue by jamesfranck** [Ysurac/openmptcprouter#395]
## Expected Behavior

Add static IP on each Glorytun clients.

## Actual Behavior

DHCP disabled on VPS in /lib/systemd/network/glorytun-tcp.network
Static IP fixed on Glorytun clients (
![glorytun_client](https://user-images.githubusercontent.com/48597122/54443066-2bcf5d80-4740-11e9-823b-af8924678917.JPG)

I have 2 online clients
The first one has 10.255.255.2
The second one I fixed 10.255.255.3

But after reboot the second one takes 10.255.255.2 so there's some conflict and they are not working at the same time

## Specifications

  - OpenMPTCProuter version: v0.46.3
  - OpenMPTCProuter VPS version: 0.87
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
For now multiple OpenMPTCProuter on one VPS is not supported.

**Comment by jamesfranck** [comment]
Is there any way to fix IP for Glorytun ?

**Comment by Ysurac** [comment]
Not for now.
