### ISSUE TITLE
Can't get public IP address from ShadowSocks

### ISSUE THREAD

**Issue by suyuan168** [Ysurac/openmptcprouter#397]
I upgraded the vps script. Has the configuration key changed during the first installation? Or is it different every time？
![1111](https://user-images.githubusercontent.com/3435645/54507676-565a2a00-497d-11e9-8ee8-d27d9426a81a.png)
I used a lot of USB 4G network cards. But now it is not normal.

  - OpenMPTCProuter version: (Last is not a version) 0.47.1
  - OpenMPTCProuter VPS version: (Last is not a version) 0.94
  - OpenMPTCProuter platform: (RPI3B+

**Comment by Ysurac** [comment]
After update there is no key change. But as there is a Kernel update you should reboot to use it.

**Comment by Ysurac** [comment]
You can also check, on the VPS, via ```ps aux | grep omr``` that the script omr-admin.py is running. If not you can check log in /var/log/daemon.log.
