### ISSUE TITLE
Can't reach one website (changeip.com) from VPS

### ISSUE THREAD

**Issue by dhumeau** [Ysurac/openmptcprouter#399]
I tried to run **wget ip.changeip.com** directly from my VPS and it worked fine.

Then I installed MPTCP 0.98 with **sudo sh debian9-x86_64.sh**

Now **wget ip.changeip.com** is falling down in timeout.

Any idea of what can cause this issue?

Best regards and much thanks for you work.

**Comment by Ysurac** [comment]
You could check in _/etc/shorewall/params.net_ that it's the good interface used for internet connection.

**Comment by dhumeau** [comment]
I forgot to say I can reach other website (wget google.fr).

**Comment by Ysurac** [comment]
I'm able to reproduce this strange issue.

**Comment by Ysurac** [comment]
Seems to be related to MPTCP, i have no problem when I disable it: ```sysctl -w net.mptcp.mptcp_enabled=0```, but it is really slow when enabled: ```sysctl -w net.mptcp.mptcp_enabled=1```.

**Comment by dhumeau** [comment]
I confirm it's working with MPTCP disabled.
Thanks for your answer.

**Comment by Ysurac** [comment]
This will be fixed in next release.

**Comment by Ysurac** [comment]
Should be fixed in latest release (else need Multipath TCP SYN retries should be set to 1 or 2).
