### ISSUE TITLE
Vps upgrade

### ISSUE THREAD

**Issue by Roken120** [Ysurac/openmptcprouter#400]
## Expected Behavior

Not upgrade

## Specifications

  - OpenMPTCProuter version: 0.47.1
  - OpenMPTCProuter VPS version: 0.96
  - OpenMPTCProuter platform: x86_64

--------------------------
root@VPS:~# wget -O - http://www.openmptcprouter.com/server/debian9-x86_64.sh | sh
URL transformed to HTTPS due to an HSTS policy
--2019-03-20 22:16:54--  https://www.openmptcprouter.com/server/debian9-x86_64.sh
Résolution de www.openmptcprouter.com (www.openmptcprouter.com)… 94.23.252.192
Connexion à www.openmptcprouter.com (www.openmptcprouter.com)|94.23.252.192|:443… connecté.
requête HTTP transmise, en attente de la réponse… 200 OK
Taille : 24152 (24K) [application/octet-stream]
Sauvegarde en : « STDOUT »

-                   100%[===================>]  23,59K  --.-KB/s    in 0s

2019-03-20 22:16:54 (56,5 MB/s) — envoi vers sortie standard [24152/24152]

Ign:1 http://ftp.fr.debian.org/debian stretch InRelease
Hit:2 http://security.debian.org stretch/updates InRelease
Get:3 http://ftp.fr.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:4 http://deb.debian.org/debian stretch-backports InRelease [91.8 kB]
Hit:5 http://ftp.fr.debian.org/debian stretch Release
Fetched 183 kB in 0s (288 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
dirmngr is already the newest version (2.1.18-8~deb9u4).
patch is already the newest version (2.7.5-1+deb9u1).
The following packages were automatically installed and are no longer required:
  docutils-common docutils-doc libalgorithm-c3-perl libarchive-extract-perl
  libasprintf0c2 libb-hooks-endofscope-perl libbind9-90 libclass-c3-perl
  libclass-c3-xs-perl libclass-method-modifiers-perl libclass-xsaccessor-perl
  libcpan-changes-perl libcpan-meta-perl libdata-optlist-perl
  libdata-perl-perl libdata-section-perl libdevel-caller-perl
  libdevel-globaldestruction-perl libdevel-lexalias-perl libdns100
  libexporter-tiny-perl libfile-slurp-perl libgetopt-long-descriptive-perl
  libimport-into-perl libintl-perl libintl-xs-perl libio-stringy-perl libisc95
  libisccc90 libisccfg90 libjasper1 liblcms2-2 liblist-moreutils-perl
  liblog-message-perl liblog-message-simple-perl liblwres90 libmariadbclient18
  libmodule-build-perl libmodule-implementation-perl
  libmodule-load-conditional-perl libmodule-pluggable-perl
  libmodule-runtime-perl libmodule-signature-perl libmoo-perl
  libmoox-handlesvia-perl libmro-compat-perl libnamespace-autoclean-perl
  libnamespace-clean-perl libpackage-constants-perl libpackage-stash-perl
  libpackage-stash-xs-perl libpadwalker-perl libparams-classify-perl
  libparams-util-perl libparams-validate-perl libpath-tiny-perl
  libperl4-corelibs-perl libpng12-0 libpod-latex-perl libpod-markdown-perl
  libpod-readme-perl libpth20 libregexp-common-perl librole-tiny-perl
  libsoftware-license-perl libstrictures-perl libsub-exporter-perl
  libsub-exporter-progressive-perl libsub-identify-perl libsub-install-perl
  libterm-ui-perl libtext-soundex-perl libtext-template-perl libtry-tiny-perl
  libtype-tiny-perl libtype-tiny-xs-perl libunicode-utf8-perl libuuid-perl
  libvariable-magic-perl libwebp5 libwebp6 libwebpdemux1 libwebpdemux2
  libwebpmux1 libwebpmux2 libxapian22 linux-image-3.16.0-4-amd64
  linux-image-3.16.0-7-amd64 mysql-common python-cffi python-defusedxml
  python-docutils python-ndg-httpsclient python-pil python-ply
  python-pycparser python-pygments python-roman python-soappy python-wstools
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Hit:1 http://security.debian.org stretch/updates InRelease
Ign:2 http://ftp.fr.debian.org/debian stretch InRelease
Hit:3 http://ftp.fr.debian.org/debian stretch-updates InRelease
Hit:4 http://deb.debian.org/debian stretch-backports InRelease
Hit:5 http://ftp.fr.debian.org/debian stretch Release
Reading package lists... Done
--2019-03-20 22:17:01--  https://www.openmptcprouter.com/kernel/linux-image-4.14.105-mptcp-310b683.amd64.deb
Resolving www.openmptcprouter.com (www.openmptcprouter.com)... 94.23.252.192
Connecting to www.openmptcprouter.com (www.openmptcprouter.com)|94.23.252.192|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 37890796 (36M) [application/octet-stream]
Saving to: '/tmp/linux-image-4.14.105-mptcp-310b683.amd64.deb'

/tmp/linux-image-4. 100%[===================>]  36.13M  9.91MB/s    in 3.5s

2019-03-20 22:17:05 (10.2 MB/s) - '/tmp/linux-image-4.14.105-mptcp-310b683.amd64.deb' saved [37890796/37890796]

--2019-03-20 22:17:05--  https://www.openmptcprouter.com/kernel/linux-headers-4.14.105-mptcp-310b683.amd64.deb
Resolving www.openmptcprouter.com (www.openmptcprouter.com)... 94.23.252.192
Connecting to www.openmptcprouter.com (www.openmptcprouter.com)|94.23.252.192|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9091630 (8.7M) [application/octet-stream]
Saving to: '/tmp/linux-headers-4.14.105-mptcp-310b683.amd64.deb'

/tmp/linux-headers- 100%[===================>]   8.67M  12.0MB/s    in 0.7s

2019-03-20 22:17:06 (12.0 MB/s) - '/tmp/linux-headers-4.14.105-mptcp-310b683.amd64.deb' saved [9091630/9091630]

Reading package lists... Done
Building dependency tree
Reading state information... Done
curl is already the newest version (7.52.1-5+deb9u9).
rename is already the newest version (0.20-4).
The following packages were automatically installed and are no longer required:
  docutils-common docutils-doc libalgorithm-c3-perl libarchive-extract-perl
  libasprintf0c2 libb-hooks-endofscope-perl libbind9-90 libclass-c3-perl
  libclass-c3-xs-perl libclass-method-modifiers-perl libclass-xsaccessor-perl
  libcpan-changes-perl libcpan-meta-perl libdata-optlist-perl
  libdata-perl-perl libdata-section-perl libdevel-caller-perl
  libdevel-globaldestruction-perl libdevel-lexalias-perl libdns100
  libexporter-tiny-perl libfile-slurp-perl libgetopt-long-descriptive-perl
  libimport-into-perl libintl-perl libintl-xs-perl libio-stringy-perl libisc95
  libisccc90 libisccfg90 libjasper1 liblcms2-2 liblist-moreutils-perl
  liblog-message-perl liblog-message-simple-perl liblwres90 libmariadbclient18
  libmodule-build-perl libmodule-implementation-perl
  libmodule-load-conditional-perl libmodule-pluggable-perl
  libmodule-runtime-perl libmodule-signature-perl libmoo-perl
  libmoox-handlesvia-perl libmro-compat-perl libnamespace-autoclean-perl
  libnamespace-clean-perl libpackage-constants-perl libpackage-stash-perl
  libpackage-stash-xs-perl libpadwalker-perl libparams-classify-perl
  libparams-util-perl libparams-validate-perl libpath-tiny-perl
  libperl4-corelibs-perl libpng12-0 libpod-latex-perl libpod-markdown-perl
  libpod-readme-perl libpth20 libregexp-common-perl librole-tiny-perl
  libsoftware-license-perl libstrictures-perl libsub-exporter-perl
  libsub-exporter-progressive-perl libsub-identify-perl libsub-install-perl
  libterm-ui-perl libtext-soundex-perl libtext-template-perl libtry-tiny-perl
  libtype-tiny-perl libtype-tiny-xs-perl libunicode-utf8-perl libuuid-perl
  libvariable-magic-perl libwebp5 libwebp6 libwebpdemux1 libwebpdemux2
  libwebpmux1 libwebpmux2 libxapian22 linux-image-3.16.0-4-amd64
  linux-image-3.16.0-7-amd64 mysql-common python-cffi python-defusedxml
  python-docutils python-ndg-httpsclient python-pil python-ply
  python-pycparser python-pygments python-roman python-soappy python-wstools
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
(Reading database ... 155351 files and directories currently installed.)
Preparing to unpack .../linux-image-4.14.105-mptcp-310b683.amd64.deb ...
Ok, aborting, since modules for this image already exist.
dpkg: error processing archive /tmp/linux-image-4.14.105-mptcp-310b683.amd64.deb (--install):
 subprocess new pre-installation script returned error exit status 1
Examining /etc/kernel/postrm.d .
run-parts: executing /etc/kernel/postrm.d/initramfs-tools 4.14.105-mptcp-310b683 /boot/vmlinuz-4.14.105-mptcp-310b683
run-parts: executing /etc/kernel/postrm.d/zz-update-grub 4.14.105-mptcp-310b683 /boot/vmlinuz-4.14.105-mptcp-310b683
Errors were encountered while processing:
 /tmp/linux-image-4.14.105-mptcp-310b683.amd64.deb

**Comment by Ysurac** [comment]
Strange, package should be ignored when correctly installed. Did you have a problem in last run ?
