### ISSUE TITLE
Cannot stream Plex over local network

### ISSUE THREAD

**Issue by 0rsa** [Ysurac/openmptcprouter#409]
## Actual Behavior

Using Plex, it does not detect that I'm using my server's local network.
In result, all my content is streamed using Plex server and Internet with transcoding.

## Expected Behavior

Launch plex.tv and content is streamed over local network if you are on the same local network of your server.

## Specifications

  - OpenMPTCProuter version: 0.45.16
  - OpenMPTCProuter VPS version: 0.45.16
  - OpenMPTCProuter platform: RPI3

**Comment by cron410** [comment]
Upgrade router and VPS. I also use plex, it exists on both my regular LAN (192.168.1.x) directly connected to a standard router and also has an IP on the OpenMPTCProuter LAN (192.168.100.x). Let me know if there is anything specific I can test for you.
