### ISSUE TITLE
DHCP don't work on wifi 

### ISSUE THREAD

**Issue by bosseb** [Ysurac/openmptcprouter#415]
Hello

i have a problem since i use OpenMPTCProuteur, on my PC with WIFI, DHCP don't works at all
  - OpenMPTCProuter version: 0.47.6-r09530-64bb88841f
  - OpenMPTCProuter VPS version: 0.991
  - OpenMPTCProuter platform: x86_64
Thanks

**Comment by Ysurac** [comment]
Do you have DHCP enabled on Wifi interface in OpenMPTCProuter interfaces (Network->Interfaces) ?

**Comment by bosseb** [comment]
i just have these interfaces 
![interfaces](https://user-images.githubusercontent.com/17600769/55347263-ac1dee80-54b4-11e9-9a3b-2342883de090.jpg)

**Comment by Ysurac** [comment]
So you need to configure the wifi interface if you have one, because I think it's not just DHCP that is not working now.

**Comment by bosseb** [comment]
on my INTEL NUC there is not wifi , but the wifi problem is with my 2 BOX (sfr box an 4g box)

**Comment by Ysurac** [comment]
OK.
I don't know what is the configuration of these boxes. Maybe you can enable a DHCP server that listen only on wifi interface, or use DHCP relay.

**Comment by Ysurac** [comment]
You can't also set change wifi network ? else you have to put it on same network as OpenMPTCProuter lan.

**Comment by bosseb** [comment]
no i can't change wifi network on these 2 boxes, i can disable DHCP on them but there is nothing special for wifi dhcp ...

**Comment by bosseb** [comment]
i have this NUC : https://www.intel.fr/content/www/fr/fr/products/boards-kits/nuc/kits/nuc7i3bnh.html
but , it have a wireless but i think OpenMPTCProuter platform: x86_64 don't install the driver ...

**Comment by Ysurac** [comment]
iwl driver that should support this card will be available in next release.
