### ISSUE TITLE
daemon.err /usr/bin/ss-local[11640]: getpeername: Socket not connected

### ISSUE THREAD

**Issue by suyuan168** [Ysurac/openmptcprouter#417]
The system log has a lot of getpeername: Socket not connected with daemon.err /usr/bin/ss-redir[11641]: remote recv: Operation timed out
It is RPI3. It is the latest system. Is it because I have a lot of WANs but one of them without a network will affect the work of openmptcprouter? Causes all networks to be lost.
I found that the operator has intercepted shadowsocks-libev. Enable Enable ShadowSocks Obfuscating MPTCP aggregation without line broadband increase. How can I avoid it?

**Comment by suyuan168** [comment]
Failed to establish connection

**Comment by dnwk** [comment]
I test yesterday when I reduced 3 WAN to 2 WAN, it stabilized the connection.

**Comment by suyuan168** [comment]
Thank you for your reply, I am going to test it.
