### ISSUE TITLE
accès a certains sites internet

### ISSUE THREAD

**Issue by Cmoi20** [Ysurac/openmptcprouter#42]
## Expected Behavior
passer certains domaines par un des WAN pour éviter les soucis de détection d'IP

## Actual Behavior
comme la connexion mptcp passe par un VPS, notre @IP de sortie est une ip de type serveur dédié. de ce fait, certains sites internet ne seront pas totalement disponibles. OVH a contourné le problème en utilisant des pools d'IP déclarés comme des connexions internet (genre ADSL). nous pourrions contourner le problème en définissant une whiteliste d'URL qui utiliseraient un WAN pour sortir.

## Specifications

  - OpenMPTCProuter version: 0.14-6
  - OpenMPTCProuter VPS version: 0.15
  - Platform: Macosx

**Comment by Ysurac** [comment]
Ca sera présent dans la prochaine version.
Il me reste à ajouter une interface et ça sera bon.

**Comment by Ysurac** [comment]
C'est ajouté dans la version 0.15.1, via omr-bypass.
