### ISSUE TITLE
Support Pi-hole

### ISSUE THREAD

**Issue by Ysurac** [Ysurac/openmptcprouter#420]
[Pi-hole](https://github.com/pi-hole/pi-hole) can be installed on VPS side.
It need to listen to vpn interface (gt-tun0, gt-udp-tun0 or tun0) so this need to be changed each time user change the vpn used (or try to listen to all interfaces ?). Same for lighttpd that need to listen only on vpn interfaces.

**Comment by Ysurac** [comment]
Possible to make dnsmasq listen to all interface by adding a file with all interfaces in ```/etc/dnsmsq.d/```.
So this seems easy to add support for that.

**Comment by user747** [comment]
I'm testing local instance of Pi Hole on 2nd rpi 3 with static IP. On OMR I have disabled Unbound, disabled 'Rebind protection' , and DNS forwardings pointing to Pi Hole.

**Comment by Ysurac** [comment]
In next release, this will be possible to install Pi-hole on the VPS and dnsmasq will forward request to it if detected.
