### ISSUE TITLE
ip doorbell out

### ISSUE THREAD

**Issue by bosseb** [Ysurac/openmptcprouter#426]
OpenMPTCProuter version: 0.48
OpenMPTCProuter VPS version: 0.992
OpenMPTCProuter platform: x86_64

Hello
since i have install OPENMPTCProuter, my ip doorbell doesn't work at all

if you could help me

**Comment by Ysurac** [comment]
Model ? By ethernet or wifi ? DHCP or static IP ? Locally or via internet ?

**Comment by bosseb** [comment]
this model : https://home-smart.fr/
DHCP, wifi, locally and via internet

**Comment by Ysurac** [comment]
Check in system log if you see DHCP request from the doorbell.

**Comment by bosseb** [comment]
i have always looking for, but i don't know the doorbell ip

**Comment by Ysurac** [comment]
The doorbell should give a name when requesting an IP (else check the mac address of the doorbell if you have it somewhere).
You can also check in Network->DHCP & DNS if you see the doorbell.

If not check wifi settings and that DHCP server is enabled on wifi interface (if wifi is served by OpenMPTCProuter).

**Comment by bosseb** [comment]
the door bell is in DHCP 192.168.0.149 is name is DEFAULT

**Comment by Ysurac** [comment]
So at least it get an IP.
Maybe some ports need to be open ? I can't help you, the documentation is not available online.

**Comment by bosseb** [comment]
no i think it send video on a specific server in the cloud, like new ipcam, but here i think the system block the video connection

**Comment by Ysurac** [comment]
The server in the cloud can ban IP from VPS.

**Comment by Ysurac** [comment]
You can use OMR-Bypass.

**Comment by bosseb** [comment]
yes but how to find the server adress ??

**Comment by Ysurac** [comment]
You can bypass everything that come from MAC or IP of the doorbell.

**Comment by bosseb** [comment]
I have bypass his MAC address but it doesn't work

**Comment by bosseb** [comment]
i have reboot the NUC and it works ! thank you so much
