### ISSUE TITLE
wlan traffic MPTCP ALL graph missing

### ISSUE THREAD

**Issue by umekzg** [Ysurac/openmptcprouter#428]
MPTCP - Realtime Traffic - all graph
/cgi-bin/luci/admin/network/mptcp/bandwidth?dev=all
wlan0 interface is not shown in the ALL graph traffic, only ethernet & vlans

when i select only wlan the graph shows traffic
/cgi-bin/luci/admin/network/mptcp/bandwidth?dev=wlan0

wan0 is configured with mptcp and works normaly

## Specifications

  - OpenMPTCProuter version: 0.47.6
  - OpenMPTCProuter VPS version: 0.95
  - OpenMPTCProuter platform: (RPI3)

**Comment by Ysurac** [comment]
I would need a screenshot of ```/cgi-bin/luci/admin/network/mptcp/bandwidth``` page

**Comment by umekzg** [comment]
![openmptcp_screen1](https://user-images.githubusercontent.com/33502159/55983522-a1750d80-5c9b-11e9-84b6-b92c375995a2.jpg)
Here you go

**Comment by user747** [comment]
I think maybe you want this graph instead? 
cgi-bin/luci/admin/network/mptcp/bandwidth
