### ISSUE TITLE
shorewall redirect rules re-comment ?

### ISSUE THREAD

**Issue by olaulau** [Ysurac/openmptcprouter#431]
Hi ;
concerning the /etc/shorewall/rules forwarded 2 line we have to uncomment to forward incoming connections to port / make a DMZ, I have a strange behavior.
sometimes, the lines re-comment themselves (and I my forwardings stops working).

Is there any action in the web ui that can regenerate this file with those 2 lines commented ?

**Comment by Ysurac** [comment]
Yes, in System->OpenMPTCProuter, Advanced Settings tab then 
Redirects all ports from server to OpenMPTCProuter checkbox

**Comment by olaulau** [comment]
works well, thanks.
