### ISSUE TITLE
OpenVPN external service

### ISSUE THREAD

**Issue by olaulau** [Ysurac/openmptcprouter#432]
Hi ;

I have to use an OpenVPN external service through my OMR connection.
No problem to connect, but the speed is very slow.
This VPN through a normal connection is fast. The OMR connection itself is fast too.

Is there a problem regarding VPN through OMR VPN ? Is there a thing toadjust to improve performance ? or a workaround ?

**Comment by Ysurac** [comment]
OpenVPN using TCP or UDP ?
You can always bypass the connection.

**Comment by olaulau** [comment]
In this case it is TCP, but it can be changed if you think that it'lll resolve the problem.

**Comment by Ysurac** [comment]
Should work using TCP, but you may have to set MSS setting in openvpn.
