### ISSUE TITLE
When the direct output is active, the default route change takes about one minute 

### ISSUE THREAD

**Issue by manueldev** [Ysurac/openmptcprouter#433]
## Expected Behavior

When the direct output is active, the default route change should take a few seconds.

## Actual Behavior

When the direct output is active, the default route change takes about one minute to go from wan1 (eth0) to wan3 (usb0). Going from wan3 to wan1 only takes a couple of seconds.

## Steps to Reproduce the Problem

  1. Turn off the VPS
  2. Wait for the direct connection to activate
  3. Disconnect the wan for which the direct connection is being made
  4. Wait for the direct connection to be activated by another wan

## Specifications

  - OpenMPTCProuter version: v0.48 r0+9745-b0395cfc56
  - OpenMPTCProuter VPS version: 0.992
  - OpenMPTCProuter platform: RPI3

Is this behavior normal?

![image](https://user-images.githubusercontent.com/3420027/56093298-c54f7380-5e94-11e9-9608-00ebad6ce5ce.png)

![image](https://user-images.githubusercontent.com/3420027/56093311-edd76d80-5e94-11e9-9254-0603d77041aa.png)

https://youtu.be/w0HC_0VqMLM

**Comment by Ysurac** [comment]
All settings are in omr-tracker interface, so this can be modified.

**Comment by manueldev** [comment]
this? 
![image](https://user-images.githubusercontent.com/3420027/56100747-8815d080-5eea-11e9-9c92-15638fd9e313.png)
