### ISSUE TITLE
help build serdisplib-2.01

### ISSUE THREAD

**Issue by kapook007** [Ysurac/openmptcprouter#437]
Hello
i can not build serdisplib-2.01 

git clone https://github.com/Ysurac/openmptcprouter.git
cd openmptcprouter
OMR_TARGET="bpi-r2" ./build.sh

This is my error 
../include/serdisplib/serdisp_connect_usb.h:35:10: fatal error: usb.h: No such file or directory
 #include <usb.h>
          ^~~~~~~
compilation terminated.

my system is debain 9.8  64bit with
apt-get install git-core build-essential libssl-dev libncurses5-dev unzip gawk zlib1g-dev busybox

How to  build serdisplib-2.01 ?

Build bpi-r2 , rpi3 , wrt32x  is same problem !!

**Comment by Ysurac** [comment]
It's why it's not more build in current master for now.

**Comment by kapook007** [comment]
Now working 
Thank you
