### ISSUE TITLE
Is it possible to OMR-Bypass to a secondary Shadowsocks server? [Feature Request]

### ISSUE THREAD

**Issue by dnwk** [Ysurac/openmptcprouter#444]
Is it possible to OMR-Bypass to a secondary Shadowsocks server?  Route traffic to a second Shadowsocks server based on OMR-Bypass rules.

**Comment by dnwk** [comment]
Or is there a way to set different ss-redir rule for different socks server?

**Comment by Ysurac** [comment]
Not possible for now. You can define needed iptables rules in custom firewall rules.

**Comment by dnwk** [comment]
So, I could set d

**Comment by dnwk** [comment]
So, I could set IPtables rules for traffic goes to bypass or traffic goes to secondary SS server?  Could you help me with an example?

**Comment by Ysurac** [comment]
You can use current rules as example.
You can see them using ```iptables-save```, the default rule for shadowsocks use port 1100. You can clone it, omr-bypass use ipset in dnsmasq configuration so you can use also a match-set to redirect some domains like omr-bypass.

**Comment by dnwk** [comment]
Is there a way to batch load IP/CIDR into omr-bypass?

**Comment by Ysurac** [comment]
No. But all configuration use ```uci```, so you write a script and put entries in omr-bypass

**Comment by dnwk** [comment]
how do I use uci to add entries to omr-bypass? It's not clear in the commandline help

**Comment by Ysurac** [comment]
https://oldwiki.archive.openwrt.org/doc/uci

**Comment by dnwk** [comment]
So, I have to run these commands:

	set omr-bypass.ips[-1]=ips
	set omr-bypass.ips[-1].ip=$ip
	set omr-bypass.ips[-1].interface=eth1  
Is it?

**Comment by Ysurac** [comment]
```uci add omr-bypass ips``` as first command

**Comment by dnwk** [comment]
Got it figured out. Thanks

**Comment by dnwk** [comment]
for ip in $(cat '/etc/route.txt'); do
uci add omr-bypass ips
uci set omr-bypass.@ips[-1]=ips
uci set omr-bypass.@ips[-1].ip=$ip
uci set omr-bypass.@ips[-1].interface="eth0.2"
uci commit omr-bypass
done



I have not quite figured out how to use uci batch. But getting close.

**Comment by dnwk** [comment]
It doesn't work at all. There are 8k networks. Seems overload omr-bypass

**Comment by dnwk** [comment]
It worked after reboot after running the command.  There are 8k networks. Seems overload omr-bypass webpage. whenever I try to load omr-bypass web page, it crashed the entire system

**Comment by bournehlm** [comment]
How to take effect immediately after run "uci commit omr-bypass"?
And how to bypass all data traffic? I have try add "0.0.0.0/0" into ips, but not working.
