### ISSUE TITLE
Waiting for root device PARTUUID=

### ISSUE THREAD

**Issue by Nadeistos** [Ysurac/openmptcprouter#448]
## Expected Behavior

Full boot

## Actual Behavior

Stuck at the begining of boot : "Waiting for root device PARTUUID="
The boot goes on if i insert an usb key with omr 

## Steps to Reproduce the Problem

Copied omr on the internal drive on a minipc, dd or etcher same problem

## Specifications

  - OpenMPTCProuter version: 0.48
  - OpenMPTCProuter VPS version: 0.992
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
I really need more info. Like log, platform config,...

**Comment by Nadeistos** [comment]
Beelink Z85 Mini PC 2G Ram+ 64G Rom Intel Atom Z8350
removed win10 and installed Linux mint works fine
lsblk : 
mmcblk0 58,2Go disk
---mmcblk0p1 512Mo part boot
---mmcblk0p1 57,8 part /
mmcblk0boot0 4Mo disk
mmcblk0boot1 4Mo disk

i will try to find the log later ^^

**Comment by Ysurac** [comment]
mmc ? x86_64 release was never tested for that.

**Comment by Nadeistos** [comment]
ok :( i'll post the log tomorrow if you want...

**Comment by Ysurac** [comment]
Yes. To check how I can make it work on that.

**Comment by Nadeistos** [comment]
No logs...
here the screens of the boot

![IMG_20190429_171857-1](https://user-images.githubusercontent.com/44791483/56908041-d6f46600-6aa5-11e9-891e-62bd4cc04e96.jpg)
![IMG_20190429_171928-1](https://user-images.githubusercontent.com/44791483/56908042-d6f46600-6aa5-11e9-8d5f-894db3875dde.jpg)

Missing mmc controler drivers ?

**Comment by bosseb** [comment]
i have the problem with Beelink BT3 Pro Mini PC 4 Go de RAM DDR3 + 64 Go de ROM eMMC Système Windows Processeur: Intel x5-Z8350 GPU: Gen-9 

what can i do to find a solution ??

**Comment by Ysurac** [comment]
You can try to compile it yourself and find what module or changes are needed to make it work ;)

**Comment by bosseb** [comment]
on other forum they writing that is it because there is ROM eMMC

**Comment by Ysurac** [comment]
Yes it's possible that the module needed is not available. But not idea what is needed.

**Comment by bosseb** [comment]
i have find the solution, i have erase the emmc partition and i put an usb disk with OMC image on it, and it's works !!!
