### ISSUE TITLE
Interface monitoring - QMI

### ISSUE THREAD

**Issue by dnwk** [Ysurac/openmptcprouter#457]
There are some instance one of my USB dongle will disconnect (Using QMI Cellular Protocol). A reboot of interface will reconnect. However, there is no way to monitor the interface. How would I monitor that specific interface and issue a reboot command when fail?

**Comment by Ysurac** [comment]
What command do you run to reboot the interface ?

**Comment by dnwk** [comment]
I issue reboot of the interface on the web
