### ISSUE TITLE
Sauvegarde des paramètres ne fonctionne pas

### ISSUE THREAD

**Issue by xslite** [Ysurac/openmptcprouter#46]
## Expected Behavior

When a new firmware is flashed, there is an option to keep configuration, and that should be automatically re-applied after reboot on new version.

## Actual Behavior

Nothing is kept from old configuration, even between minor version update (ie v15.1 to v15.2 )

## Steps to Reproduce the Problem

  1.  flash a new firmware and click on the option "keep configuration"
  2. reboot....
  3. no config is kept

## Specifications

  - OpenMPTCProuter version: v15.1
  - OpenMPTCProuter VPS version: V15
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
Should be fixed in latest release (for update after it, not from any previous releases).
