### ISSUE TITLE
OMRVPN does not work since the last update

### ISSUE THREAD

**Issue by KoRnEr007** [Ysurac/openmptcprouter#463]
Hello,
my vpn is down ... when i see the interface OMRVPN nothing is set ...
COuld you please help me to configure this ?
![Capture3](https://user-images.githubusercontent.com/44002636/57319330-9e373b00-70fc-11e9-809d-320f32056758.PNG)
![Capture2](https://user-images.githubusercontent.com/44002636/57319331-9e373b00-70fc-11e9-9e75-868ac83740b3.PNG)
![Capture1](https://user-images.githubusercontent.com/44002636/57319332-9e373b00-70fc-11e9-9d0c-962fe2b4e37f.PNG)
![Capture4](https://user-images.githubusercontent.com/44002636/57319333-9ecfd180-70fc-11e9-92d7-4aca71cfc37f.PNG)

## Specifications

  - OpenMPTCProuter version: openmptcprouter v0.48 r0+9745-b0395cfc56
  - OpenMPTCProuter VPS version:  v0.992
  - OpenMPTCProuter platform: (/RPI3 x64)

**Comment by Ysurac** [comment]
You should check system log

**Comment by KoRnEr007** [comment]
Tue May  7 19:08:20 2019 daemon.info glorytun-udp: starting glorytun-udp vpn instance vpn
Tue May  7 19:08:20 2019 daemon.notice netifd: Network device 'tun0' link is up
Tue May  7 19:08:20 2019 daemon.notice netifd: Interface 'omrvpn' has link connectivity
Tue May  7 19:08:20 2019 daemon.notice netifd: Interface 'omrvpn' is setting up now
Tue May  7 19:08:20 2019 daemon.notice netifd: Interface 'omrvpn' is now up
Tue May  7 19:08:20 2019 daemon.err glorytun-udp[23500]: running on device tun0 as pid 23500
Tue May  7 19:08:20 2019 kern.info kernel: [185170.267695] IPv6: ADDRCONF(NETDEV_CHANGE): tun0: link becomes ready
Tue May  7 19:08:20 2019 user.notice firewall: Reloading firewall due to ifup of omrvpn (tun0)
Tue May  7 19:08:21 2019 user.notice mptcp: Reloading mptcp config due to ifup of omrvpn (tun0)
Tue May  7 19:08:21 2019 daemon.info omr-tracker-ss: Shadowsocks is up (can contact 1.1.1.1)
Tue May  7 19:08:23 2019 user.notice omr-bypass: Starting OMR-ByPass...
Tue May  7 19:08:49 2019 daemon.info dnsmasq[10524]: read /etc/hosts - 4 addresses
Tue May  7 19:08:49 2019 daemon.info dnsmasq[10524]: read /tmp/hosts/dhcp.cfg01411c - 5 addresses
Tue May  7 19:08:49 2019 daemon.info dnsmasq-dhcp[10524]: read /etc/ethers - 0 addresses
Tue May  7 19:08:49 2019 user.notice omr-bypass: OMR-ByPass is running

**Comment by jwthecolorist** [comment]
Am I mistaken or is the Common Configuration for OMR-Bypass is set to unmanaged rather than DHCP Client?

**Comment by Ysurac** [comment]
It's set as unmanaged in latest release. You can try to set DHCP.

**Comment by KoRnEr007** [comment]
Tue May  7 19:32:14 2019 daemon.notice netifd: Network device 'tun0' link is down
Tue May  7 19:32:14 2019 daemon.notice netifd: Interface 'omrvpn' has link connectivity loss
Tue May  7 19:32:14 2019 daemon.notice netifd: Interface 'omrvpn' is now down
Tue May  7 19:32:14 2019 daemon.notice netifd: Interface 'omrvpn' is disabled
Tue May  7 19:32:14 2019 daemon.notice netifd: Interface 'omrvpn' is enabled
Tue May  7 19:32:14 2019 kern.info kernel: [186604.026288] IPv6: ADDRCONF(NETDEV_UP): tun0: link is not ready
Tue May  7 19:32:14 2019 daemon.info glorytun-udp: starting glorytun-udp vpn instance vpn
Tue May  7 19:32:14 2019 daemon.notice netifd: Network device 'tun0' link is up
Tue May  7 19:32:14 2019 daemon.notice netifd: Interface 'omrvpn' has link connectivity
Tue May  7 19:32:14 2019 daemon.notice netifd: Interface 'omrvpn' is setting up now
Tue May  7 19:32:14 2019 daemon.err glorytun-udp[22088]: running on device tun0 as pid 22088
Tue May  7 19:32:14 2019 daemon.notice netifd: Interface 'omrvpn' is now up
Tue May  7 19:32:14 2019 kern.info kernel: [186604.111285] IPv6: ADDRCONF(NETDEV_CHANGE): tun0: link becomes ready
Tue May  7 19:32:14 2019 user.notice mptcp: Reloading mptcp config due to ifup of omrvpn (tun0)
Tue May  7 19:32:14 2019 daemon.info omr-tracker-ss: Shadowsocks is up (can contact 1.1.1.1)
Tue May  7 19:32:16 2019 user.notice omr-bypass: Starting OMR-ByPass...
Tue May  7 19:32:19 2019 daemon.info dnsmasq[10524]: read /etc/hosts - 4 addresses
Tue May  7 19:32:19 2019 daemon.info dnsmasq[10524]: read /tmp/hosts/dhcp.cfg01411c - 5 addresses
Tue May  7 19:32:19 2019 daemon.info dnsmasq-dhcp[10524]: read /etc/ethers - 0 addresses
Tue May  7 19:32:19 2019 user.notice omr-bypass: OMR-ByPass is running

always down ...

**Comment by KoRnEr007** [comment]
and can't be set DHCP....

**Comment by Ysurac** [comment]
Try to use glorytun TCP instead of glorytun UDP

**Comment by KoRnEr007** [comment]
Tue May  7 19:39:29 2019 daemon.info glorytun: starting glorytun vpn instance vpn
Tue May  7 19:39:29 2019 daemon.err glorytun[31483]: couldn't create tun device
Tue May  7 19:39:59 2019 daemon.err glorytun[32204]: couldn't create tun device
Tue May  7 19:40:29 2019 daemon.err glorytun[359]: couldn't create tun device

**Comment by Ysurac** [comment]
reboot openmptcprouter, there is a bug in current release.

**Comment by jwthecolorist** [comment]
> It's set as unmanaged in latest release. You can try to set DHCP.

Oh ok, I see.

**Comment by KoRnEr007** [comment]
look good :) thanks for the support
