### ISSUE TITLE
suggestion: static preferred WAN

### ISSUE THREAD

**Issue by pyjabox** [Ysurac/openmptcprouter#466]
Hello Yannick,

## Specifications

    OpenMPTCProuter version: 0.48
    OpenMPTCProuter VPS version: 0.992
    OpenMPTCProuter platform: x86_64

## Context

I'm using your solution for some months now and I really enjoy it.
Aggregating ADSL (5Mbit/s) + 4G (3 bands aggregation)
I've changed my 4G provider for a decent one which has limited quota (50G) but has good bandwidth at any time of the day but now I need to find ways to optimize my traffic (SDWAN like).

## Observation

Even if I put my ADSL Wan as static "Master", I understand the scheduler will always prefer the lowest RTT Wan whoever is "Master" or "Active". My 4G having lower RTT, the traffic usually go over this one and sucks all the quota even for basic browsing that wouldn't require usually more than 5 Mbit/s

## Workaround

I've put a linux VM in between on my 4G Wan to add delay with Netem:
tc qdisc change dev ens160 root netem delay 75ms
And now I have the desired behavior :
ADSL is used most of the time for my usual browsing
4G is added on top whenever I need more bandwidth

## Question

Do you see a more elegant way to have this behavior natively from OpenMPTCPRouter itself ? By the way, the above command just doesn't work on my OMR VM

## Bonus

I haven't seen any mention about it anywhere : I use AWS free tier access for 6 months now, and my VPS VM is hosted there. I suppose it is more than enough to host the VPS side, instead of paying a few euros to OVH or else. That could be a suggestion for your users even to try your solution without requiring to subscribe to anything

**Comment by user747** [comment]
http://192.168.100.1/cgi-bin/luci/admin/system/openmptcprouter/settings

What option is set under Master interface selection ?

I think 'No Change' is what you want ?

**Comment by user747** [comment]
Oh maybe you are referring to MPTCP's default scheduler 

> 'default': This scheduler is the default one. It will first send data on subflows with the lowest RTT until their congestion-window is full. Then, it will start transmitting on the subflows with the next higher RTT.

**Comment by pyjabox** [comment]
Yes i'm referring to the default scheduler scheme which is : send first on lowest RTT Wan (whatever the one which is master or active).

I saw this website yes, but I found way easier to implement the proposed workaround above (adding virtually some delay on the 4G connection)

I was wondering if there was a cleaner config already available to achieve the same result ?

On the other hand, I'm quite sure it would be in the interest of a lot of people like in my situation to have a preferred WAN (adsl/vdsl) and use the 4G WAN as a booster when needed which is more than enough for most of scenario (streaming, direct download). We could compare this to a hybrid car where autonomy in electric mode is super low, but you can use it to enhance the comsumption of gas on specific case :)

**Comment by user747** [comment]
I think your solution is the best so far. 
Update [/etc/opkg.conf](https://github.com/Ysurac/openmptcprouter/issues/44#issuecomment-380015743)

```
opkg update
opkg install kmod-netem
```

**Comment by stepanlicevich** [comment]
> ## Bonus
> I haven't seen any mention about it anywhere : I use AWS free tier access for 6 months now, and my VPS VM is hosted there. I suppose it is more than enough to host the VPS side, instead of paying a few euros to OVH or else. That could be a suggestion for your users even to try your solution without requiring to subscribe to anything

Hi, @pyjabox , I'm sorry for bothering but could you please reveal some details concerning your aws ec2 setup: what ami (or what image) and security group rules (or acl) have you used? I suppose that you also definitely use elastic ip and you've chosen aws region the most closest to you in geo terms, right?
I would really appreciate if you could leave a short comment on the questions above! Cheers

**Comment by pyjabox** [comment]
> > ## Bonus
> > I haven't seen any mention about it anywhere : I use AWS free tier access for 6 months now, and my VPS VM is hosted there. I suppose it is more than enough to host the VPS side, instead of paying a few euros to OVH or else. That could be a suggestion for your users even to try your solution without requiring to subscribe to anything
> 
> Hi, @pyjabox , I'm sorry for bothering but could you please reveal some details concerning your aws ec2 setup: what ami (or what image) and security group rules (or acl) have you used? I suppose that you also definitely use elastic ip and you've chosen aws region the most closest to you in geo terms, right?
> I would really appreciate if you could leave a short comment on the questions above! Cheers

I don't have anymore my setup as I have proper connection at home nowadays.
But here is what I had :
- AMI = ubuntu 18.04, and ran "wget -O - http://www.openmptcprouter.com/server/ubuntu18.04-x86_64.sh | sh"
- Security = permit any but you probably can do it better and filter with :

    SSH port is changed to 65222 (TCP)
    Shadowsocks port is 65101 (TCP & UDP)
    Glorytun port is 65001 (TCP & UDP)
    OMR JSON admin is 65500 (TCP)
    OpenVPN port is 65301 (TCP)
    MLVPN ports are 65201-65208 (UDP)
    Iperf3 on port 65400 (TCP & UDP)
    DSVPN port is 65011 (TCP)

- No elastic IP. I only used the IPv4 Public IP of my instance
- Indeed chose the closest region

Just a quick warning : I found myself paying some bucks one month because my total traffic went above 15 GB. That is the free tier enveloppe you have (ingress + egress).
So for testing, light traffic or just to provide a public ip to one of your site, AWS is a good choice. If it's your primary connection at home is may be too short for those 25GB.

Have fun !
