### ISSUE TITLE
Problem with Lastest build

### ISSUE THREAD

**Issue by ThibautBascoulergue** [Ysurac/openmptcprouter#478]
## Expected Behavior

I just installed version 0.49 with a vps in 0.993 and I router does not connect to the vps.

![image](https://user-images.githubusercontent.com/42678960/57723166-58441f00-7688-11e9-9d94-92d7837d92c7.png)

## Steps to Reproduce the Problem

Install new vps with script
Install new router on Esxi

## Specifications

  - OpenMPTCProuter version: (0.49)
  - OpenMPTCProuter VPS version: (0.993)
  - OpenMPTCProuter platform: (x86_64)

**Comment by ThibautBascoulergue** [comment]
With old mptcprouter in version 0.47.6, it work with the latest vps verrsion 0.993. So i think the problem is in the openmptcprouter.
![image](https://user-images.githubusercontent.com/42678960/57723931-0603fd80-768a-11e9-9823-fea6fe0b9bad.png)

**Comment by Ysurac** [comment]
WAN1 is in same network  as OpenMPTCProuter and lan. It's often not a good idea.

**Comment by ThibautBascoulergue** [comment]
ok i check

**Comment by ThibautBascoulergue** [comment]
Ysurac,  pi-hole script will be installed after the vps script or before ?

**Comment by Ysurac** [comment]
after

**Comment by ThibautBascoulergue** [comment]
ok thx

**Comment by ThibautBascoulergue** [comment]
The problem appears as soon as I install pi-hole.
Once the script is launched, the router no longer dialogs with the vps: /
After running the script I have some error msg
![image](https://user-images.githubusercontent.com/42678960/57731277-98140200-769a-11e9-9797-0502d2a82148.png)

**Comment by Ysurac** [comment]
Pi-hole seems to be not installed. How do you run the script ?

**Comment by ThibautBascoulergue** [comment]
I have launch vps script and reboot.
After i have launch the script : wget -O - http://www.openmptcprouter.com/server/omr-pihole.sh | sh

**Comment by Ysurac** [comment]
Strange, on Ubuntu or Debian ?
You can relaunch the script.

**Comment by ThibautBascoulergue** [comment]
Debian

**Comment by ThibautBascoulergue** [comment]
same problem after réinstalle vps
![image](https://user-images.githubusercontent.com/42678960/57733637-440c1c00-76a0-11e9-841e-0ad67fc3c159.png)

**Comment by Ysurac** [comment]
What is the provider ? I'm not able to reproduce the issue that seems to be a crash of Pi-hole official install script...

**Comment by ThibautBascoulergue** [comment]
vps is on Scaleway.

**Comment by ThibautBascoulergue** [comment]
Some news :)

With a new VPS, not Scaleway provider, pi-hole is working good :)

So the problem comes from the sclaeway vps.
