### ISSUE TITLE
pi-hole admin interface

### ISSUE THREAD

**Issue by jayanta525** [Ysurac/openmptcprouter#482]
## Expected Behavior

pi-hole admin interface available only on gt-tun0 interface

## Actual Behavior

pi-hole admin interface accessible from all the interfaces. Also from public IP.

## Steps to Reproduce the Problem

  1. Install pi-hole with the provided script.
  2. Set pi-hole interface as gt-tun0
  3. Open in browser: http://<vps_public_ip>/admin

## Specifications

  - OpenMPTCProuter version: 0.49
  - OpenMPTCProuter VPS version: 0.993
  - OpenMPTCProuter platform: custom-arm

**Comment by Ysurac** [comment]
Fixed in latest omr-pihole script. Thanks.
