### ISSUE TITLE
Enhancement: Add temp in home page

### ISSUE THREAD

**Issue by Dragonox77** [Ysurac/openmptcprouter#493]
Hello,
Thank you for your solution.

I think add cpu temp in the home page is a good idea. It can be easily read from this file: /sys/class/thermal/thermal_zone0/temp for RPI.

Thank you.

**Comment by jayanta525** [comment]
You can use luci-app-statistics to display temperature graphs.

![image](https://user-images.githubusercontent.com/30702133/58428432-11aae780-80c0-11e9-8af8-e5f99de5cdfd.png)

**Comment by Dragonox77** [comment]
Oh didn't see thank you for your answer.

**Comment by jayanta525** [comment]
Don't forget to install collectd-mod-thermal and select the thermal zone in the configuration.

**Comment by Dragonox77** [comment]
How to install luci-app-statistics. I got this error: Unknown package 'luci-app-statistics'.

**Comment by jayanta525** [comment]
`opkg update` followed by `opkg install luci-app-statistics collectd-mod-thermal`

**Comment by Dragonox77** [comment]
Collected errors:
 * opkg_download: Failed to download http://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/luci/Packages.gz, wget returned 4.
 * opkg_download: Check your network settings and connectivity.

 * opkg_download: Failed to download http://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/packages/Packages.gz, wget returned 4.
 * opkg_download: Check your network settings and connectivity.

 * opkg_download: Failed to download http://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/base/Packages.gz, wget returned 4.
 * opkg_download: Check your network settings and connectivity.

 * opkg_download: Failed to download http://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/routing/Packages.gz, wget returned 4.
 * opkg_download: Check your network settings and connectivity.

 * opkg_download: Failed to download http://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/telephony/Packages.gz, wget returned 4.
 * opkg_download: Check your network settings and connectivity.


And then i can't run opkg install luci-app-statistics collectd-mod-thermal

**Comment by manueldev** [comment]
```
uci set network.lan.dns=8.8.8.8
uci commit && service network restart
```

**Comment by Dragonox77** [comment]
> ```
> uci set network.lan.dns=8.8.8.8
> uci commit && service network restart
> ```

Not working either.

**Comment by Dragonox77** [comment]
> ```
> uci set network.lan.dns=8.8.8.8
> uci commit && service network restart
> ```

Not working either.

**Comment by jayanta525** [comment]
wget is trying to download over IPv6 and I guess you don't have IPv6 connectivity. 
In that case, head over to `System > Software > Configuration`

Replace Custom Feeds with a mirror; for France:
```
src/gz openwrt_luci http://gra.mirror.cyberbits.eu/openwrt/snapshots/packages/aarch64_cortex-a53/luci
src/gz openwrt_packages http://gra.mirror.cyberbits.eu/openwrt/snapshots/packages/aarch64_cortex-a53/packages
src/gz openwrt_base http://gra.mirror.cyberbits.eu/openwrt/snapshots/packages/aarch64_cortex-a53/base
src/gz openwrt_routing http://gra.mirror.cyberbits.eu/openwrt/snapshots/packages/aarch64_cortex-a53/routing
src/gz openwrt_telephony http://gra.mirror.cyberbits.eu/openwrt/snapshots/packages/aarch64_cortex-a53/telephony

```
Save configuration and `opkg update`

You can find the list of mirrors here: https://openwrt.org/downloads

**Comment by Dragonox77** [comment]
Nice, thank you, all is working like it should.
