### ISSUE TITLE
Hyper V x64 Image

### ISSUE THREAD

**Issue by VirtualAI** [Ysurac/openmptcprouter#494]
Hello,
would it be possible to provide a Hyper V image to run the router virtual under Windows?
Best regards.

**Comment by Scaff31** [comment]
Hi,
Try to adapt this for hyper-V https://github.com/Ysurac/openmptcprouter/issues/87

**Comment by Ysurac** [comment]
Hyper-V will be available in next release.

**Comment by Ysurac** [comment]
Done since 0.50.1
