### ISSUE TITLE
Netflix OMR-Bypass no longer works

### ISSUE THREAD

**Issue by rubaz100** [Ysurac/openmptcprouter#497]
## Expected Behavior
Netflix Content filtered to wan2

## Actual Behavior
Netflix shows that I use a Proxy
![proxy](https://user-images.githubusercontent.com/33371370/58699456-d2211b80-839d-11e9-832e-6265d6534bd4.PNG)

## Steps to Reproduce the Problem

![192 168 100 1_cgi-bin_luci_admin_services_omr-bypass](https://user-images.githubusercontent.com/33371370/58699656-4c51a000-839e-11e9-8de7-3922d7122b16.png)
![ip](https://user-images.githubusercontent.com/33371370/58701268-ba986180-83a2-11e9-9aae-2efee35178cd.PNG)

## Specifications
  - DNS changed to the OpenMPTCPRouter  (192.168.100.1)
  - OpenMPTCProuter version: 0.49.7
  - OpenMPTCProuter VPS version: 0.994
  - OpenMPTCProuter platform: WRT3200ACM (ARM)
![status_openmptcp](https://user-images.githubusercontent.com/33371370/58699477-dcdbb080-839d-11e9-8210-a7edcc8173ee.PNG)

**Comment by Ysurac** [comment]
When a domain is in both DSCP and omr-bypass then only one is working. This will be solved in next release.

**Comment by rubaz100** [comment]
Oh okay, so we need to wait for the next release? I don't mind... When do you want to publish it?
Do you know how to fix it? :=)

Thank you for everything you did for us.

<3

**Comment by Ysurac** [comment]
It's already fixed in openmptcprouter-feeds tree. Only need to test and tag for release ;)

**Comment by rubaz100** [comment]
I can't build it :(

![Screenshot from 2019-06-01 08-19-27](https://user-images.githubusercontent.com/33371370/58744708-4911ef00-8446-11e9-8828-f5e20d466f42.png)

**Comment by Ysurac** [comment]
Strange.
But I'm building it, this will be OpenMPTCProuter 0.50.
Images will be available here https://www.openmptcprouter.com/release/targets/ if CircleCI can compile it ( https://circleci.com/gh/Ysurac/openmptcprouter-feeds )

**Comment by rubaz100** [comment]
Okay, thank you. I will definitely donate some € for you. Incredible!!!
