### ISSUE TITLE
lan (No gateway defined) & omr6in4 (No IP defined)

### ISSUE THREAD

**Issue by CoSysopK** [Ysurac/openmptcprouter#506]
## Actual Behavior

![network2](https://user-images.githubusercontent.com/48426317/59147141-34aa9500-89f8-11e9-9e4d-6e3f51d55321.png)

![network2b](https://user-images.githubusercontent.com/48426317/59147155-602d7f80-89f8-11e9-98b4-5a074fc3cdbf.png)

## Steps to Reproduce the Problem

  1. Install image for Raspberry PI 3/3B+ (64-bit)
  2. Install VPS Ubuntu Server 18.04 x86_64
  3. Configure the router with the wan1 static and wan2 static
  4. Add the IP address VPS and, all the informations (shadowsocks key, glorytun key, MLVPN
password and OpenMPTCProuter VPS Admin key) retrived on the VPS
  5. 1 key 4G on usb PI 3B and, 1 key 4g wifi

## Specifications

  - OpenMPTCProuter version: Version 0.50.2
  - OpenMPTCProuter VPS version: Version 0.993
  - OpenMPTCProuter platform: RPI3B+ 64 bits

**Comment by Ysurac** [comment]
Lan and omr6in4 should not have multipath enabled.

**Comment by CoSysopK** [comment]
I do not understand ! 
I just do a reinstall today

**Comment by CoSysopK** [comment]
multipath is well on disable

![network2c](https://user-images.githubusercontent.com/48426317/59147626-658dc880-89fe-11e9-9c5a-3a714d37f40e.png)

**Comment by CoSysopK** [comment]
The problem is here :

![network2d](https://user-images.githubusercontent.com/48426317/59147808-7b03f200-8a00-11e9-8c74-119101f407e8.png)

interface parameter, there are LAN and OMR6IN4 !!!
I deleted these 2 interfaces but it caused an error.
So I made an "update" on the router with the same version and it put everything back in the right order.

![network2e](https://user-images.githubusercontent.com/48426317/59147859-39c01200-8a01-11e9-9f40-1d6e7814180e.png)

It Work !
