### ISSUE TITLE
Erreur dans journal system

### ISSUE THREAD

**Issue by bosseb** [Ysurac/openmptcprouter#511]
- OpenMPTCProuter version: 0.50.2
  - OpenMPTCProuter VPS version: 0.995
  - OpenMPTCProuter platform: x86_64

j'ai ces erreurs dans mon journal systeme :

Tue Jun 11 18:29:49 2019 daemon.err miniupnpd[5092]: ioctl(s, SIOCGIFADDR, ...): Address not available
Tue Jun 11 18:29:49 2019 daemon.err miniupnpd[5092]: ioctl(s, SIOCGIFADDR, ...): Address not available
Tue Jun 11 18:29:49 2019 daemon.err miniupnpd[5092]: ioctl(s, SIOCGIFADDR, ...): Address not available
Tue Jun 11 18:29:49 2019 daemon.err miniupnpd[5092]: Failed to get ip address for interface 6in4-omr6in4
Tue Jun 11 18:29:50 2019 daemon.err miniupnpd[5092]: ioctl(s, SIOCGIFADDR, ...): Address not available
Tue Jun 11 18:29:50 2019 daemon.err miniupnpd[5092]: Failed to get ip address for interface 6in4-omr6in4
Tue Jun 11 18:29:51 2019 daemon.err miniupnpd[5092]: ioctl(s, SIOCGIFADDR, ...): Address not available
Tue Jun 11 18:29:51 2019 daemon.err miniupnpd[5092]: ioctl(s, SIOCGIFADDR, ...): Address not available
Tue Jun 11 18:29:51 2019 daemon.err miniupnpd[5092]: ioctl(s, SIOCGIFADDR, ...): Address not available
Tue Jun 11 18:29:51 2019 daemon.err miniupnpd[5092]: Failed to get ip address for interface 6in4-omr6in4
Tue Jun 11 18:29:51 2019 daemon.err miniupnpd[5092]: ioctl(s, SIOCGIFADDR, ...): Address not available
Tue Jun 11 18:29:51 2019 daemon.err miniupnpd[5092]: Failed to get ip address for interface 6in4-omr6in4
Tue Jun 11 18:29:51 2019 daemon.err miniupnpd[5092]: ioctl(s, SIOCGIFADDR, ...): Address not available
Tue Jun 11 18:29:51 2019 daemon.err miniupnpd[5092]: ioctl(s, SIOCGIFADDR, ...): Address not available
Tue Jun 11 18:29:51 2019 daemon.err miniupnpd[5092]: ioctl(s, SIOCGIFADDR, ...): Address not available
Tue Jun 11 18:29:51 2019 daemon.err miniupnpd[5092]: Failed to get ip address for interface 6in4-omr6in4
Tue Jun 11 18:29:51 2019 daemon.err miniupnpd[5092]: ioctl(s, SIOCGIFADDR, ...): Address not available
Tue Jun 11 18:29:51 2019 daemon.err miniupnpd[5092]: Failed to get ip address for interface 6in4-omr6in4
Tue Jun 11 18:29:52 2019 daemon.err miniupnpd[5092]: ioctl(s, SIOCGIFADDR, ...): Address not available
Tue Jun 11 18:29:52 2019 daemon.err miniupnpd[5092]: ioctl(s, SIOCGIFADDR, ...): Address not available
Tue Jun 11 18:29:52 2019 daemon.err miniupnpd[5092]: ioctl(s, SIOCGIFADDR, ...): Address not available
Tue Jun 11 18:29:52 2019 daemon.err miniupnpd[5092]: Failed to get ip address for interface 6in4-omr6in4

**Comment by Ysurac** [comment]
C'est UPnP qui provoque l'erreur (il est fortement recommandé de ne pas activer cette horreur).
Sinon, vu que ça semble lié à l'interface 6in4-omr6in4 est-ce que l'IPv6 est activé ou pas ?

**Comment by bosseb** [comment]
je viens donc de désactiver upnp les erreurs ont disparus .. ipv6 tjrs désactivé

**Comment by Ysurac** [comment]
Il faudrait voir si les commandes suivantes permettent bien de plus avoir d'erreur tout en ayant UPnP qui fonctionne :
```
uci set upnpd.config.external_iface='omrvpn'
uci commit upnpd
```
