### ISSUE TITLE
RPI3 screen flooded with cpu freq Errors

### ISSUE THREAD

**Issue by pankajmishra16** [Ysurac/openmptcprouter#512]
## Expected Behavior

  The Raspberry Pi should get IP at the port without any error

## Actual Behavior
The screen is getting flooded with the cpu frequency error

## Steps to Reproduce the Problem

  1. Connect a usb -> eth adapter in rasp pi 3 b+
  2. RPI3 is loaded with ubuntu 18 ( bionic) server  ( not a desktop)
  3. connect the eth wire,  one end in adapter connected in usbport the other with internet and set the port up

## Specifications

  - OpenMPTCProuter version: (Last is not a version)
  - OpenMPTCProuter VPS version: (Last is not a version)
  - OpenMPTCProuter platform: (RPI3/x86_64)

**Comment by Ysurac** [comment]
It's only OpenMPTCProuter support. Not RPI or Ubuntu support. Sorry.
