### ISSUE TITLE
UDP Timeout

### ISSUE THREAD

**Issue by mycanaletto** [Ysurac/openmptcprouter#513]
Bonjour,

Le SIP OVH nécessite un timeout UDP à 180 mini. Ou faire ce réglage ?

Sur OTB j'ai trouvé ça mais ça date... https://github.com/ovh/overthebox/issues/36

**Comment by Ysurac** [comment]
C'est le réglage par défaut : 
```
net.netfilter.nf_conntrack_udp_timeout = 60
net.netfilter.nf_conntrack_udp_timeout_stream = 180
```
