### ISSUE TITLE
VPN IP (ovh) blocked by service

### ISSUE THREAD

**Issue by audren49** [Ysurac/openmptcprouter#514]
Just a general question. All seem to work fine. But some services, like canal+ are restricting ovh IP.
How to get around this?

Thanks;

**Comment by Ysurac** [comment]
You have to use omr-bypass, this will use a wan directly.

**Comment by audren49** [comment]
It works, thanks.
Is there a way to include all subdomains?
Like *. 1fichier.com?

Thank you

**Comment by Ysurac** [comment]
If you put "example.com" this will also bypass "www.example.com" or "sub.example.com", so any subdomains.

**Comment by audren49** [comment]
Thanks

**Comment by audren49** [comment]
Hi, did some further test.
Subdomains are not bypassed when just the domain is setup.

Easy test is jeuxvideo.com which blocks the OVH IP. the website loads its images on "images.jeuxvideo.com"
If this is not setup explicitely in the bypass table like this :
![image](https://user-images.githubusercontent.com/3305012/59628968-b063ba80-9139-11e9-9213-c0656d552010.png)

Then images will not load with a 403

**Comment by Ysurac** [comment]
subdomains are really bypassed. Check that OpenMPTCProuter is used as DNS.

**Comment by audren49** [comment]
That was the issue indeed. My routeur used 8.8.8.8 as DNS.
When set to OMR local IP, all works fine.

Thank you very much.
