### ISSUE TITLE
IPv6 routing/ OPKG error

### ISSUE THREAD

**Issue by jwthecolorist** [Ysurac/openmptcprouter#517]
I've noticed when I run opkg update, it fails because it cannot route ipv6 (the default address that returns is ipv6 instead of ipv4). My ISP's do not serve ipv6, only ipv4. However, my VPS has both. Is it possible to route ipv6 by routing through the VPS?

It looks like that is supposed to happen with omr6in4 but it didn't seem to be working so I disabled all "Use builtin IPv6-management" on the lan/wan interfaces and that didn't fix it either. I also disabled ipv6 in shadowsocks and that didn't help opkg either.

My preference would be to set up my network so I can have IPV6 on all client routes out the ipv6 via the ipv6 on the vps but I disabled it on the lan DHCP and the interface settings because it didn't seem to be working. Plus I see no traffic on omr6in4

Is that currently available on the release 0.50.2? Do I need to configure something specific to make that happen or is it enabled by default?

I'm very unfamiliar with ipv6 so I may just have a configuration error. Just let me know what you need from me. As far as the issue with opkg, I'm wondering if this is an issue with DNS as it's returning ipv6 instead of ipv4.

Thanks!!

![image](https://user-images.githubusercontent.com/49826973/59629272-7500c600-9110-11e9-9ae6-320c2080c2fd.png)

![image](https://user-images.githubusercontent.com/49826973/59629577-299ae780-9111-11e9-887a-82149fd0623d.png)

![image](https://user-images.githubusercontent.com/49826973/59629806-a7f78980-9111-11e9-87cd-a56b62b86e5c.png)

![image](https://user-images.githubusercontent.com/49826973/59629708-71ba0a00-9111-11e9-931a-ab7c663de29e.png)

![image](https://user-images.githubusercontent.com/49826973/59629898-e55c1700-9111-11e9-950e-3c8dfd87f103.png)

## Specifications

  - OpenMPTCProuter version: 0.50.2
  - OpenMPTCProuter VPS version: 0.995
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
Yes it's available. You need to check ipv6 in the wizard, and if it's configured on the server you should see the IPv6 in OpenMPTCProuter status page.

**Comment by jayanta525** [comment]
Replace `http://downloads.openwrt.org/` with mirrors from `https://openwrt.org/downloads#mirrors` to workaround the IPv6 issue.

**Comment by Ysurac** [comment]
I next release I will force IPv4 for opkg.

**Comment by jwthecolorist** [comment]
Thanks for the feedback! 

I enabled ipv6 (after a fresh install, had disabled ipv6 everywhere and would take too long to re-enable everything) and now it appears to be working fine. Even opkg is updating correctly without changing the repos.

@jayanta525 Thanks for the suggestion! I hadn't seen that option but I had tried changing to a mirror that only resolved to ipv4. That worked but didn't resolve the greater issue. Enabling ipv6 in the wizard did though.

As a side note: I'm currently updating my VPS to 0.996. Looking forward to seeing how it performs.

**Comment by jwthecolorist** [comment]
Incase this is related, I now have lots of these in my log:

![image](https://user-images.githubusercontent.com/49826973/59705652-cec6c600-91cc-11e9-97ce-441e6394e1ad.png)

Any thoughts?

**Comment by Ysurac** [comment]
It's a test in status page that fail. You enabled IPv6 in the wizard ?

**Comment by jwthecolorist** [comment]
Sorry for the late reply! Yes, I had it enabled in the wizard. Just turned it off though because it was causing a strange problem where all the connections would complete drop periodically. Not sure why yet, I don't think it was your software but something with my network. 

That said (this is not a complaint, just an observation), version 0.50.2 does appear to be far more unstable than the previous versions. It appears to drop connections faster, reboots dnsmasq more etc. It could just be something with my system though.
