### ISSUE TITLE
TCP CVE

### ISSUE THREAD

**Issue by dnwk** [Ysurac/openmptcprouter#518]
https://github.com/Netflix/security-bulletins/blob/master/advisories/third-party/2019-001.md
For the multiple CVE related to Linux and TCP, does it has any implication on OpenMPTCPRouter?

**Comment by Ysurac** [comment]
Yes, like all Linux based system. But with OpenMPTCProuter only the VPS part have some ports open on Internet. OpenMPTCProuter VPS script 0.996, released yesterday, use 4.14.127 kernel with fixes for these CVE. The router part will have a new release soon too.
