### ISSUE TITLE
VnStat Graphs  

### ISSUE THREAD

**Issue by nicoz76** [Ysurac/openmptcprouter#52]
Nothing display on VnStat Graph

![image](https://user-images.githubusercontent.com/10829637/39811188-2e6fbdd4-5388-11e8-95e3-9ffed866c9a9.png)

## Specifications

  - OpenMPTCProuter version: openmptcprouter v0.16 r6737-99d9c98748
  - OpenMPTCProuter VPS version: 0.16
  - OpenMPTCProuter platform: Raspberry Pi 3 Model B Rev 1.2

thanks

**Comment by Ysurac** [comment]
Fixed in latest commit.

**Comment by kevin39** [comment]
This problem seems back in last version (clean install). Do you confirm ?

**Comment by Ysurac** [comment]
Yes, after the update of vnstat graph are not visible. This will be fixed in next release.

**Comment by max4186** [comment]
@Ysurac Do you have an ETA for next release? Still broken.
