### ISSUE TITLE
why OMR and LAN show up on status screen 

### ISSUE THREAD

**Issue by dnwk** [Ysurac/openmptcprouter#521]
![d4v](https://user-images.githubusercontent.com/3439281/59970555-0a8bc380-951e-11e9-9ab9-a63f9d42c87c.png)

## Specifications

  - OpenMPTCProuter version: (Last is not a version)
  - OpenMPTCProuter VPS version: (Last is not a version)
  - OpenMPTCProuter platform: (RPI2/RPI3/x86/x86_64)

**Comment by Ysurac** [comment]
Because multipath is undefined on them.

**Comment by dnwk** [comment]
How did that happened? When I go into interface,  multipath is disabled.

**Comment by Ysurac** [comment]
Validate the interface again.
