### ISSUE TITLE
I have an x86 UP2 motherboard but the downloaded x86 firmware can't boot

### ISSUE THREAD

**Issue by suyuan168** [Ysurac/openmptcprouter#523]
It seems that he only supports uefi startup. The X86 version EX4 downloaded with EMMC can't be started.

  - OpenMPTCProuter version: (Last is not a version)
  - OpenMPTCProuter VPS version: (Last is not a version)
  - OpenMPTCProuter platform: (RPI2/RPI3/x86/x86_64) X86

**Comment by Ysurac** [comment]
So why not the x86_64 ext4 with EFI support ?

**Comment by suyuan168** [comment]
I don't know if there are any tips.
