### ISSUE TITLE
forward port problem after change vpn

### ISSUE THREAD

**Issue by Florent4223** [Ysurac/openmptcprouter#526]
## Expected Behavior

Forward port on client behind omr

## Actual Behavior

Configuration forward port on omr
Forward port on firewall
Forward ok

Change type vpn
But nothing forward

## Steps to Reproduce the Problem

  1. Forward port 80 on client behind omr
  2. Try connect with pc on same vps network  ok
  3. Change type vpn
 4.  Try port forward ....nothing

## Specifications

  - OpenMPTCProuter version: (Last is not a version) 0.50.2
  - OpenMPTCProuter VPS version: (Last is not a version)  0.996
  - OpenMPTCProuter platform: (RPI2/RPI3/x86/x86_64) rpi3

**Comment by Ysurac** [comment]
For now you need to wait a little, a script on the VPS detect current VPN.
This will be better in next release.

**Comment by Florent4223** [comment]
Thanks
No Problem
