### ISSUE TITLE
OpenWRT_MPTCP   build error 

### ISSUE THREAD

**Issue by lloovve** [Ysurac/openmptcprouter#53]
when i buid OpenWRT_MPTCP got an error :+1: 

Patch failed!  Please fix /media/lloovve/backup/mptcp/OpenWRT_MPTCP/openwrt/target/linux/generic/pending-4.9/690-mptcp-v4.9-c88d1d56809e.patch!
make[3]: *** [/media/lloovve/backup/mptcp/OpenWRT_MPTCP/openwrt/build_dir/toolchain-mips_24kc_gcc-7.3.0_musl/linux-4.9.96/.prepared] Error 1
make[3]: Leaving directory `/media/lloovve/backup/mptcp/OpenWRT_MPTCP/openwrt/toolchain/kernel-headers'
Command exited with non-zero status 2
time: toolchain/kernel-headers/compile#6.10#2.51#7.61
make[2]: *** [toolchain/kernel-headers/compile] Error 2
make[2]: Leaving directory `/media/lloovve/backup/mptcp/OpenWRT_MPTCP/openwrt'
make[1]: *** [/media/lloovve/backup/mptcp/OpenWRT_MPTCP/openwrt/staging_dir/toolchain-mips_24kc_gcc-7.3.0_musl/stamp/.toolchain_compile] Error 2
make[1]: Leaving directory `/media/lloovve/backup/mptcp/OpenWRT_MPTCP/openwrt'
make: *** [world] 错误 2

**Comment by Ysurac** [comment]
Same as #48
