### ISSUE TITLE
WiFi ap mode not working

### ISSUE THREAD

**Issue by mshost** [Ysurac/openmptcprouter#533]
## Expected Behavior
WiFi ap as access point in PI 3b+
  In English please.

## Actual Behavior
When i am trying to configure pi as WiFi router , it's successfully create the interface in wireless as AP but after couple of minutes it is changed to wireless client mode.

## Steps to Reproduce the Problem

  1.delete wireless interface,
  2.restart
  3.again install , but no luck

## Specifications

  - OpenMPTCProuter version: (0.50)
  - OpenMPTCProuter VPS version: (0.995)
  - OpenMPTCProuter platform: (/RPI3b+)

**Comment by mshost** [comment]
VPS version 0.996

**Comment by Ysurac** [comment]
I'm not able to reproduce this issue.

**Comment by mshost** [comment]
Is it possible to enable WiFi ap in raspberry pi 3b+ ?

**Comment by Ysurac** [comment]
Yes. Set country, canal, ssid and this should work. Else change settings.
