### ISSUE TITLE
Dynamic IP (DDNS) support

### ISSUE THREAD

**Issue by xicciodj** [Ysurac/openmptcprouter#535]
Hello!
I'm currently using a home server as a "VPS" for OpenMPTCP.
The problem is that the IP is dynamic, so it changes if the connection crashes or something.
Now, to solve that problem I tried assigning my no-ip host to the IP address of the VPN in the OpenMPTCPRouter settings, but that didn't work, it threw a lot of errors and it slowed down the RPI.
So, does or will OpenMPTCPRouter support Dynamic IP in the future?

  - OpenMPTCProuter version: 0.50.2
  - OpenMPTCProuter VPS version: 0.996
  - OpenMPTCProuter platform: RPI3

**Comment by Ysurac** [comment]
For now vps part with dynamics ip is not supported . I need to make some code changes and tests if it's possible.

**Comment by suyuan168** [comment]
nrgok  OR frp

**Comment by xicciodj** [comment]
Ok, thanks!
