### ISSUE TITLE
Suggestion: FQDN as VPS "Server IP"

### ISSUE THREAD

**Issue by adrianmace** [Ysurac/openmptcprouter#538]
Similar to #535, this is a suggestion to allow OpenMPTCPRouter to read in an FQDN such as vps.mynetwork.com for the "Server IP" in the setup wizard and resolve this using the master WAN on disconnect/reconnect.

This would allow users to configure their own DDNS support as required.

**Comment by Ysurac** [comment]
Support will be added in next release
