### ISSUE TITLE
Error while building OpenMPTCProuter -Makefile:5039: recipe for target 'gioenumtypes.h' failed 

### ISSUE THREAD

**Issue by ranusha14** [Ysurac/openmptcprouter#542]
I was trying to build openmptcprouter  but found this error while building .please help me to solve this issue

`make[6]: Entering directory '/home/ubuntu/Projects/OpenMPTCProuterBuild/openmptcprouter/x86_64/source/build_dir/hostpkg/glib-2.58.3/gio'
  GEN      gioenumtypes.h
/usr/bin/env: '/home/ubuntu/Projects/OpenMPTCProuterBuild/openmptcprouter/x86_64/source/staging_dir/host/bin/p': No such file or directory
**Makefile:5039: recipe for target 'gioenumtypes.h' failed**
make[6]: *** [gioenumtypes.h] Error 127
make[6]: Leaving directory '/home/ubuntu/Projects/OpenMPTCProuterBuild/openmptcprouter/x86_64/source/build_dir/hostpkg/glib-2.58.3/gio'
Makefile:1254: recipe for target 'all-recursive' failed
make[5]: *** [all-recursive] Error 1
make[5]: Leaving directory '/home/ubuntu/Projects/OpenMPTCProuterBuild/openmptcprouter/x86_64/source/build_dir/hostpkg/glib-2.58.3'
Makefile:881: recipe for target 'all' failed
make[4]: *** [all] Error 2
make[4]: Leaving directory '/home/ubuntu/Projects/OpenMPTCProuterBuild/openmptcprouter/x86_64/source/build_dir/hostpkg/glib-2.58.3'
Makefile:119: recipe for target '/home/ubuntu/Projects/OpenMPTCProuterBuild/openmptcprouter/x86_64/source/build_dir/hostpkg/glib-2.58.3/.built' failed
make[3]: *** [/home/ubuntu/Projects/OpenMPTCProuterBuild/openmptcprouter/x86_64/source/build_dir/hostpkg/glib-2.58.3/.built] Error 2
make[3]: Leaving directory '/home/ubuntu/Projects/OpenMPTCProuterBuild/openmptcprouter/x86_64/source/feeds/packages/libs/glib2'
time: package/feeds/packages/glib2/host-compile#0.29#0.05#0.34
package/Makefile:107: recipe for target 'package/feeds/packages/glib2/host/compile' failed
make[2]: *** [package/feeds/packages/glib2/host/compile] Error 2
make[2]: Leaving directory '/home/ubuntu/Projects/OpenMPTCProuterBuild/openmptcprouter/x86_64/source'
package/Makefile:103: recipe for target '/home/ubuntu/Projects/OpenMPTCProuterBuild/openmptcprouter/x86_64/source/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile' failed
make[1]: *** [/home/ubuntu/Projects/OpenMPTCProuterBuild/openmptcprouter/x86_64/source/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/ubuntu/Projects/OpenMPTCProuterBuild/openmptcprouter/x86_64/source'
/home/ubuntu/Projects/OpenMPTCProuterBuild/openmptcprouter/x86_64/source/include/toplevel.mk:216: recipe for target 'world' failed
make: *** [world] Error 2
`

**Comment by Ysurac** [comment]
mips are not supported and tested.
