### ISSUE TITLE
Ping Jitter Issue

### ISSUE THREAD

**Issue by rubaz100** [Ysurac/openmptcprouter#543]
## Expected Behavior

  Jitter should be between 0-2ms. 

## Actual Behavior
Jitter ping is about 100ms. Sometimes it's 10ms or less

## Specifications

  - OpenMPTCProuter version: 0.50.2
  - OpenMPTCProuter VPS version:  0.996 4.14.127 mptcp
  - OpenMPTCProuter platform: WRT3200ACM

**Comment by xabix** [comment]
The sky should be bleu but sometimes it's white or grey.

Seriously how do you want anyone to be able to help if you don't give more insight. WAN accesses, are you on wireless, I never saw a jitter of 2ms but maybe with fiber.
