### ISSUE TITLE
Glorytun:  Redundant scheduler not initially used {until service restarted / reconnect forced}

### ISSUE THREAD

**Issue by A2Razor** [Ysurac/openmptcprouter#544]
## Expected Behavior
For the "redundant scheduler" option (under Network > MPTCP) to be used for Glorytun VPN on server-startup, and for Glorytun to be force-reconnected on scheduler change. {such that its session uses the newly selected scheduler}

## Actual Behavior
Even if the redundant scheduler is selected, Glorytun's initial-connection is under the default scheduler.  Restarting the Glorytun client (forcing a reconnection) resolves this until the next server start.

## Steps to Reproduce the Problem

-- On a fresh setup: Select the redundant scheduler on the router.
-- Verify that the redundant scheduler is actually selected {e.g, via sysctl on both the client-side and server-side}.
-- Perform an action such as running a ping (e.g, 'ping 10.255.255.1 -t', assuming jitter will be sufficient to discern here).
-- Stop and restart the Glorytun service {force a re-connection}, watch the reduction in jitter after the outage.

{alternatively run a bandwidth-test over Glorytun to make it clear that the initial tunnel was still on the default scheduler}

-- Do a clean-start (restart the server).
-- Perform the above steps a second time. {minus selecting the redundant scheduler on the router}

## Specifications

  - OpenMPTCProuter version: v0.50.2 r0+10127-3209f5ae3d
  - OpenMPTCProuter VPS version: 0.996 4.14.127
  - OpenMPTCProuter platform: RPI 3B+ squashfs & x86_64 squashfs (though likely impacts all builds)

**Comment by Ysurac** [comment]
Should be fixed in next release.
