### ISSUE TITLE
attempt to call global 'view' (a nil value)

### ISSUE THREAD

**Issue by user747** [Ysurac/openmptcprouter#545]
Using (also got same with squashfs)
http://www.openmptcprouter.com/release/4.19/rpi3/targets/brcm2708/bcm2710/openmptcprouter-v0.50.2-67-g855ee2e-r0%2B10493-14e0e4f138-brcm2708-bcm2710-rpi-3-ext4-factory.img.gz

After flashing microsd

`dd bs=4M if=~/Downloads/openmptcprouter-v0.50.2-67-g855ee2e-r0+10493-14e0e4f138-brcm2708-bcm2710-rpi-3-ext4-factory.img of=/dev/sdd conv=fsync`

Then go to 192.168.100.1 and see this

```
/usr/lib/lua/luci/controller/admin/system.lua:10: attempt to call global 'view' (a nil value)
stack traceback:
	/usr/lib/lua/luci/controller/admin/system.lua:10: in function 'v'
	/usr/lib/lua/luci/dispatcher.lua:627: in function 'createtree'
	/usr/lib/lua/luci/dispatcher.lua:279: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:144: in function </usr/lib/lua/luci/dispatcher.lua:143>

```

**Comment by Ysurac** [comment]
It's not a released yet, so no tested yet.
