### ISSUE TITLE
Kernel CONFIG_MEMCG: missing

### ISSUE THREAD

**Issue by dur3x** [Ysurac/openmptcprouter#546]
Can you please apply the fix of this issue 
https://github.com/multipath-tcp/mptcp/issues/321

Currently with your kernel it's impossible to use memory cgroup. 
It's just a flag enabled normally as default. 
It's already fixed in the official MPTCP project but not yet here.

Thanks !

**Comment by Ysurac** [comment]
I think you mean on the VPS ?
I use default Debian config and I don't need cgroup on VPS part, but why not...

**Comment by dur3x** [comment]
Exactly it's for the vps part.
Thanks in advance :-)

**Comment by dur3x** [comment]
@Ysurac Did you get time to add the cgroup?
It will be great if I can directly use your kernel image instead of the one available on https://dl.bintray.com/cpaasch/deb

**Comment by Ysurac** [comment]
This will be available in next release with an updated kernel. Should be out soon (I hope)

**Comment by dur3x** [comment]
> This will be available in next release with an updated kernel. Should be out soon (I hope)

Just a gentle reminder :-)
