### ISSUE TITLE
4G modem same MAC addresses

### ISSUE THREAD

**Issue by Bestle** [Ysurac/openmptcprouter#549]
When connecting multiple Huawei USB 4G dongles, they all have the same MAC address. OMR works correctly with one connected, but does not work properly when two are connected.

Steps to reproduce:

Set up OMR with a single Huawei dongle in NCM mode - verify connection works.
Plug in second Huawei dongle and configure in NCM mode - connection stops working completely (even with second dongle multipath disabled)

https://pastebin.com/Y6xMt6b4

How do I properly assign these devices unique MAC addresses?

## Specifications

  - OpenMPTCProuter version:  openmptcprouter-v0.51
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
You can try to change the mac address using the network->interfaces and advanced parameters on the wan tab.

**Comment by Bestle** [comment]
That tab is not available when using NCM protocol.

**Comment by Ysurac** [comment]
You can try to change it via SSH using ```ip link set wan2 address 02:01:02:03:04:08```

**Comment by Bestle** [comment]
How would I make this persist across reboots and not cause issues with OMR?

**Comment by Ysurac** [comment]
This work or not ?

**Comment by Bestle** [comment]
Yes the change of MAC works but it goes back to original duplicate MAC when router is restarted.

**Comment by Ysurac** [comment]
If you try :
```
uci set network.wan2.macaddr="02:01:02:03:04:08"
uci commit network
```
This work after reboot ?

**Comment by Bestle** [comment]
ifconfig wwan0 shows the original MAC after reboot, but the option is still set in network config

**Comment by Bestle** [comment]
OMR cannot find the device now either

**Comment by Ysurac** [comment]
I can't really help more about that, I don't have any NCM keys. You can check if you find something about that on OpenWrt doc/forum, because that part is not modified at all from OpenWrt version.

**Comment by rstanislav** [comment]
NCM is bad idea@linux.
For mac address part - you can change it using AT commands i think, what model of modems are you using ?

**Comment by Bestle** [comment]
The modems are Huawei E3372-153 LTE/4G non-hilink. Is there a protocol I should be using instead?

**Comment by tranquiliza** [comment]
I'm having issues, that using the Override MAC in the Advanced tab, is not overriding the MAC (Also Duplicate Mac, from 2 Huawei Modems)


![](https://cdn.discordapp.com/attachments/547952211137921046/602960130849374228/unknown.png)

![](https://cdn.discordapp.com/attachments/547952211137921046/602960255760072827/unknown.png)

**Comment by rstanislav** [comment]
Well, i used over 20 of them (3372h) and never saw duplicate mac.. It can be ncm driver problem i think.. Try to flash them with hilink firmware, but it is danger process if you don't know how to do it, if you do something wrong its hard to recover modem.
There is detailed description how to do it with links to all needed tools and firmwares(http://4pda.ru/forum/index.php?showtopic=582284&st=750), but its in russian.. maybe somewhere else there is guide in english..

**Comment by tranquiliza** [comment]
Unfortunately I am not the owner of one of the Modems (LTE Provider's property) So I cannot do this for that one. Besides, I have no clue what this is :(

**Comment by Bestle** [comment]
I can try flashing mine with hi link firmware. Which protocol should I use after that? Will I not have double NAT issues?

**Comment by Bestle** [comment]
If you search your MAC on google @tranquiliza you will see lots of people have devices with the same MAC address... It seems to be a common problem.

**Comment by tranquiliza** [comment]
That's wild. So only fix is buy another Modem? (which is not a Huawei? )

**Comment by Bestle** [comment]
![](https://i.imgur.com/PCrYqXX.png)

I have 4 more modems on the way, I will check the MACs and let you know.

**Comment by karjaj** [comment]
Is it MAC addr 0c:5b:8f:27:9a:64 ? I have E5377T and Vodafone stick wich is rebranded E3372. Both have same MAC, but they working nice with openmptcprouter. They recognized without problem as eth1 and eth2 as cdc-ethernet devices.
