### ISSUE TITLE
how change build Target 

### ISSUE THREAD

**Issue by lloovve** [Ysurac/openmptcprouter#55]
when i use OMR_TARGET="mipsel_24kc" ./build.sh  (MT7621)  got error "Target mipsel_24kc not found !"

is it the arg "mipsel_24kc"  not right for mt7621 ?

**Comment by Ysurac** [comment]
Only x86_64 and rpi3 are supported platform. I can only test and support platform that I own.

If you want to test any other platform, you can use the ```OMR_TARGET="rpi3" ./build.sh``` to create an initial source tree, then in rpi/source you have to use ```make menuconfig``` to set the platform you want.

Not sure the mt7621 is fast enough to get an acceptable result.

**Comment by lloovve** [comment]
thanks ,I'm trying

**Comment by lloovve** [comment]
i use the step 

1. make file  name "config-mt7621"
2. change file (my equipment is youhua_wr1200js) add 

CONFIG_TARGET_ramips=y
CONFIG_TARGET_ramips_mt7621=y
CONFIG_TARGET_ramips_mt7621_DEVICE_youhua_wr1200js=y    

3.  OMR_TARGET="mt7621" ./build.sh -j9
4. cd /mt7621/source    and  make menuconfig     save
5. make  -j9
