### ISSUE TITLE
OpenMPTCPRouter v0.51-r010518 doesn't restore or save settings.

### ISSUE THREAD

**Issue by xicciodj** [Ysurac/openmptcprouter#553]
Hi!
Today I wanted to update my OpenMPTCPRouter on my Raspberry Pi 3B to the latest version (v0.51-r010518), so I backed up my settings from the web interface, then I flashed the factory image to the SD Card. After that, I put my SD into my Raspberry Pi 3 and it booted. At this point, I went to the web interface and tried to restore settings, it rebooted as expected but then all the settings were gone. I thought that maybe the backup was corrupted in some way, so I reflashed again the image on the SD just to be sure and I tried to set up manually everything. But there were problems:
First of all, it says that "Multipath seems to be blocked on the connection", which is an error I've never seen before. And then, what I think is the most important error, is "Filesystem is readonly". After I've read that, I tried to reboot the Raspberry Pi and all the settings were gone again. So it just doesn't save settings.
I also tried another SD Card but it didn't work either.
Here's a screenshot of the error (there is only one wan because I didn't have the second one "handy" at that moment):
![Screenshot_45](https://user-images.githubusercontent.com/32244052/61648700-3aaabb80-acb0-11e9-9868-713ac5ccf4ba.png)

So, how can I fix this?
## Specifications

  - OpenMPTCProuter version: v0.51-r010518
  - OpenMPTCProuter VPS version: 0.9962
  - OpenMPTCProuter platform: RPI3 (64bit image)

**Comment by Ysurac** [comment]
Squashfs or ext4 ?
Using ```dmesg``` via SSH you can find why there is a FS problem.

**Comment by xicciodj** [comment]
Squashfs
I'm seeing this in dmesg, I don't know if this could be the cause:
VFS: Mounted root (squashfs filesystem) readonly on device 179:2.

**Comment by Ysurac** [comment]
squashfs is always readonly, there is a f2fs overlay that must be read/write. Check about F2FS log.

**Comment by xicciodj** [comment]
The only error I'm seeing about F2FS (in dmesg) is this:
`[    6.958099] mount_root: failed to mount -t f2fs /dev/loop0 /tmp/overlay: No such device
[    6.969346] mount_root: overlay filesystem has not been fully initialized yet
[    6.978302] mount_root: switching to f2fs overlay
[    6.984687] mount_root: switching to f2fs failed - fallback to ramoverlay`

**Comment by Ysurac** [comment]
Nothing more before that ?
You can try to run via ssh ```mount_root done```

**Comment by xicciodj** [comment]
I can't see anything related to f2fs before that, but maybe I'm searching for the wrong thing. If needed, I can copy all the dmesg output.
I'm not sure what mount_root done should do, but I tried it. The command gave no output, and there was no new messages in dmesg. I also tried to restore configurations again, but it didn't work.

**Comment by Ysurac** [comment]
You should try to reboot (via reboot command) after that, and check if you see the same message about overlay filesystem not initialized.

**Comment by xicciodj** [comment]
Ok, tried it. Same exact error.

**Comment by Ysurac** [comment]
Use ext4 version ;)

**Comment by xicciodj** [comment]
Ok, the ext4 version is restoring and saving settings correctly!

**Comment by mycanaletto** [comment]
Bonjour, 
Idem sous ESX
openmptcprouter-v0.51-r010518-6d61fcfa9e-x86-64-combined-squashfs.img.gz

La mise à jour provoque un clean de la config et quand on refait la config elle ne résiste pas à un reboot...

Si la solution est de refaire la VM en EXT4 autant virer les images HFS ?

Un conseil sur quoi utiliser sur ESX ? Merci :-)

**Comment by Ysurac** [comment]
La mise à jour efface la config du fait du changement du partitionnement et de la taille de l'image.

ext4 est actuellement plus stable que squashfs.

**Comment by mycanaletto** [comment]
J'ai remonté une VM avec :
openmptcprouter-v0.51-r010518-6d61fcfa9e-x86-64-combined-ext4.vmdk
Et c'est OK

Impossible de le faire en EFI par contre, j'ai peut être loupé qq chose... Le mieux peut être serait à terme de proposer un OVF ?

**Comment by Ysurac** [comment]
C'est prévu, il faut que je prenne les 5 minutes pour le faire :)
