### ISSUE TITLE
Compile for Edge Router X

### ISSUE THREAD

**Issue by iamfreaky** [Ysurac/openmptcprouter#558]
Hi,

A quick question how could i compile openmptcprouter for myself for the Edge Router X ?

The Router is supported by openwrt. 
Device Map https://openwrt.org/toh/hwdata/ubiquiti/ubiquiti_edgerouter_x

**Comment by Ysurac** [comment]
MIPS is not supported by OpenMPTCProuter, and CPU is too slow.
If you really want to try: https://github.com/Ysurac/openmptcprouter/wiki/Create-image-for-unsupported-platform
