### ISSUE TITLE
Graph in luci-app-mptcp

### ISSUE THREAD

**Issue by abilly007** [Ysurac/openmptcprouter#56]
1. when i go into  ...cgi-bin/luci//admin/network/mptcp/bandwidth  website, there are nothing display,should it display all interfaces traffic is a better choice??and sometimes(not ervertime), i clike the wan1 or wan2 button ,there occour a error.because the website turn to ...cgi-bin/luci//admin/network/mptcp/wan1 ,that should be ...cgi-bin/luci//admin/network/mptcp/bandwidth/wan1.

2. in the  ...cgi-bin/luci//admin/network/mptcp/wan1 website there should be two colour polyline,one for input,another for output,but you can see there three colour.

3.in the  ...cgi-bin/luci//admin/network/mptcp/bandwidth/all, i found that the second polyline is base on the first one(that is the small traffic interface colour is higher than the bigger on),why ?

**Comment by Ysurac** [comment]
1. This will be fixed in next release
2. I only see 2 colours
3. I don't understand the problem
