### ISSUE TITLE
Package error

### ISSUE THREAD

**Issue by JorgeMoort89** [Ysurac/openmptcprouter#560]
Doing `opkg update` I recive `Downloading http://openmptcprouter.com:80/release/4.19/targets/x86/64/packages/Packages.gz
*** Failed to download the package list from http://openmptcprouter.com:80/release/4.19/targets/x86/64/packages/Packages.gz`
when I try to wget it directly it work with no problem.

## Specifications

  - OpenMPTCProuter version: 0.51
  - OpenMPTCProuter VPS version: 0.997
  - OpenMPTCProuter platform: x86_64

**Comment by manueldev** [comment]
Maybe same problem #344

**Comment by Ysurac** [comment]
Fixed. This was a rate limit problem on my server.
