### ISSUE TITLE
OVA ESX

### ISSUE THREAD

**Issue by mycanaletto** [Ysurac/openmptcprouter#568]
Merci pour les OVA !

La version EFI ne démarre pas. Par contre la version non EFI EXT4 OK. Il manque juste open-vmware tools... Et on a une erreur non critique sur le choix de l'OS, en acceptant ça passe en other Linux 64 (du au fait que je suis en ESX 5.5).

**Comment by Ysurac** [comment]
Effectivement, j'ai utilisé le même OVF pour les 2 images, j'ai donc oublié de remplacer le "bios" par "efi" :)

**Comment by mycanaletto** [comment]
Merci pour la prochaine release. Ce serait top aussi d'ajouter open-vmaware-tools..

**Comment by Ysurac** [comment]
Il est dispo dans les packages à installer mais je peux pas le mettre par défaut car il plante si il n'est pas dans une VM vmware.

**Comment by mycanaletto** [comment]
C'est bizzare, avant hier suie au problème hfs j'ai rééinstllé une nouvelle vm à partir de ça _openmptcprouter-v0.51-r010518-6d61fcfa9e-x86-64-combined-ext4.vmdk_ et les vmware tools sont déjà présents...

**Comment by Ysurac** [comment]
Oui, j'ai viré dernièrement.

**Comment by mycanaletto** [comment]
C'est du cosmétique. Pas le plus grave :-)
