### ISSUE TITLE
Compile Error on v2ray Plugin

### ISSUE THREAD

**Issue by iamfreaky** [Ysurac/openmptcprouter#569]
So Tried to Compile OpenMptcp for my own Router ( Edge Router X ) but sadly it fails. Does hanybody have a solution for it ?.

The Router is not offical supported by openmptcp but supported from openwrt. 

Cleaning module download cache (golang/go#27455)
go: finding github.com/shadowsocks/v2ray-plugin/.go_work/build latest
go: finding github.com/shadowsocks/v2ray-plugin/.go_work latest
can't load package: package github.com/shadowsocks/v2ray-plugin/.go_work/build: unknown import path "github.com/shadowsocks/v2ray-plugin/.go_work/build": cannot find module providing package github.com/shadowsocks/v2ray-plugin/.go_work/build

make[3]: *** [Makefile:44: /home/chris/drive/edge-router-x/openmptcprouter/myplatform/source/build_dir/target-mipsel_24kc_musl/v2ray-plugin-1e5b3780/.built] Error 2
make[3]: Leaving directory '/home/chris/drive/edge-router-x/openmptcprouter/feeds/openmptcprouter/shadowsocks-v2ray-plugin'
time: package/feeds/openmptcprouter/shadowsocks-v2ray-plugin/compile#17.38#3.90#34.44
make[2]: *** [package/Makefile:109: package/feeds/openmptcprouter/shadowsocks-v2ray-plugin/compile] Error 2
make[2]: Leaving directory '/home/chris/drive/edge-router-x/openmptcprouter/myplatform/source'
make[1]: *** [package/Makefile:103: /home/chris/drive/edge-router-x/openmptcprouter/myplatform/source/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/chris/drive/edge-router-x/openmptcprouter/myplatform/source'
make: *** [/home/chris/drive/edge-router-x/openmptcprouter/myplatform/source/include/toplevel.mk:218: world] Fehler 2

**Comment by iamfreaky** [comment]
@Ysurac You dont have a solution for it ?

**Comment by Ysurac** [comment]
Not for now. There is several problems with compilation for MIPS

**Comment by svdwalt007** [comment]
Any updates to fix this yet ?

**Comment by 2muaddlb** [comment]
Hi, Ysurac!
Did you manage to fix it?

**Comment by Ysurac** [comment]
Shadowsocks v2ray-plugin is not available anymore. Better to use directly V2Ray proxy.

**Comment by 2muaddlb** [comment]
Do you mean there is a V2Ray proxy for OpenWRT/OpenMptcp out there as a standalone proxy server?

**Comment by Ysurac** [comment]
I mean that V2Ray is integrated in OpenMPTCProuter and can be used as proxy instead of ShadowSocks via System->OpenMPTCProuter, and "advanced settings" checkbox in the wizard.
