### ISSUE TITLE
Problème avec 4G Box (Bouygues Télécom)

### ISSUE THREAD

**Issue by Slivikk-fr** [Ysurac/openmptcprouter#570]
## Expected Behavior

Bonjour j'ai reçu ma 4G Box aujourd'hui et j'ai configurer comme indiqué sur le wiki mais ça me met Gateway Down :-( 

Mon raspberry Pi est brancher sur un switch directement avec les deux lignes 

## Steps to Reproduce the Problem

  1. Suivre le wiki
  2. Mettre les mêmes IP avec le DHCP de désactivé
  3.Gateway down

## Specifications

  - OpenMPTCProuter version: (0.51.2)
  - OpenMPTCProuter VPS version: (0.999)
  - OpenMPTCProuter platform: (RPI3B+)

**Comment by Ysurac** [comment]
Le gateway down correspond à un ping vers la passerelle, si elle répond pas on a ce message.
Donc soit la configuration est mauvaise, soit le ping est bloqué sur la box.
Tu peux mettre une capture d'écran de la page status ?

**Comment by Slivikk-fr** [comment]
![Capture](https://user-images.githubusercontent.com/53304251/61970568-5928f380-afdd-11e9-82d3-a4abf1ce7ca3.PNG)

**Comment by Slivikk-fr** [comment]
![Capture](https://user-images.githubusercontent.com/53304251/61970676-92616380-afdd-11e9-8774-aff562fe6174.PNG)

**Comment by Ysurac** [comment]
Donc pour le wwan il arrive à trouver l'adresse WAN, donc le modem ne répond surement pas au ping. Pas forcément de soucis à ce niveau.
Pour l'interface 4GBOX il est fort possible qu'il y a un soucis. Tu peux tester via SSH sur le routeur un ping vers 192.168.10.1 et sinon revérifie ta configuration et tes câbles.

**Comment by Slivikk-fr** [comment]
Dès que je met ma 4G BOX sur mon switch relié au RPI il ce met en rouge (le signale passe en rouge) mais dès que je met mon pc portable c'est bleu ;/ C'est peut être du à la première ligne qui fait chier la 4G Box ?

**Comment by Slivikk-fr** [comment]
La 4G Box ne répond pas au ping :/

**Comment by Slivikk-fr** [comment]
J'ai beau autoriser le ping sur le wan , changer de switch, câble ethernet rien n'y fait ça veut pas du tout

**Comment by Slivikk-fr** [comment]
Quand y'a le raspberry pi sur le switch ça fonctionne pas et dès qu'il n'est plus sur le switch ça fonctionne

**Comment by Ysurac** [comment]
Ca ressemble à un conflit d'IP ça. Tu as bien mis 192.168.10.1 sur la box comme IP fixe et pas .2 ?
Et il n'y a rien déjà présent en 192.168.10.2 ?

**Comment by Slivikk-fr** [comment]
OUI tout est bon de ce côté

**Comment by Breizor** [comment]
si le "wwan" correspond au wifi de la 4G box, l'adresse wan commune entre "wwan" et 4GBOX" pourrait causer le conflit?

Sinon pour dépanner: utilise le wifi de la 4Gbox, le DHCP peut être activé sur wwan (pas le même réseau physique)...pratique si tu partage la connection avec un smartphone.
![Annotation 2019-07-27 115309](https://user-images.githubusercontent.com/53367934/61992929-1ca0da80-b065-11e9-990e-9f066c3351ab.jpg)

![Annotation 2019-07-27 115138](https://user-images.githubusercontent.com/53367934/61992915-e9f6e200-b064-11e9-9441-7e4ca5f38db4.jpg)

**Comment by Slivikk-fr** [comment]
En fait le WWAN c'est mon téléphone :/

**Comment by Slivikk-fr** [comment]
Alors si j'avais la possibilité de mettre mes deux réseaux sur la même carte wifi (Utilisant la bande 5Ghz pour le routeur 4G et la bande 2.4Ghz pour le téléphone) où sur un adaptateur USB j'aimerais bien comme ça ça m'éviterai d'avoir ces problème embêtant :(

**Comment by Slivikk-fr** [comment]
J'ai réussi à tout faire fonctionner mais sérieux problème de débit je devrais être en théorie à 70-100Mbits et je n'atteint pas 10Mbits :(

**Comment by Ysurac** [comment]
Dans _réseau->MPTCP->MPTCP fullmesh_ tu as bien toute tes IPs ?

**Comment by Slivikk-fr** [comment]
J'ai deux adresses IP effectivement

**Comment by Slivikk-fr** [comment]
![image](https://user-images.githubusercontent.com/53304251/61997548-35c87c00-b0a3-11e9-8932-2bef1c199131.png)
ARRRRRRRRRRRRRRRRRRRRRRRRRRRRRRG

**Comment by Ysurac** [comment]
Il arrive pas à utiliser wan1 la, vu le rouge.

**Comment by Slivikk-fr** [comment]
Pourtant tout à l'heure tout étais ok tout à l'heure

**Comment by PierreGranger** [comment]
Bonjour,

Ayant eu un problème équivalent moi même, j'ai pu le régler en allant sur la 4Gbox dans Paramètres réseau > Ethernet > Paramètres Ethernet > Mode de connexion > LAN uniquement.

Il semblerait que le port Ethernet de la box ne soit au départ pas destiné à se relier à un réseau local mais plutôt comme fournisseur de la connexion Internet (un peu comme les box utilisant du Wifimax, dont un port Ethernet est destiné à relier la box à l'antenne).

En passant en LAN uniquement je pense qu'on destine le port Ethernet de la box à une utilisation classique.
