### ISSUE TITLE
bug VPS kernel panic ou fuite mémoire

### ISSUE THREAD

**Issue by cayenne17** [Ysurac/openmptcprouter#572]
Bonjour,
J'ai la dernière version du VPS 0.999 et du routeur 0.51.2 r0+10518-6d61fcfa9e.

Je viens de tester de rajouter une connexion partagé depuis un Google Nexus 5x 4G Bouygues Telecom en plus de la Freebox en VDSL2 et mon modem router Zyxel LTE4506 avec une sim free. 

Quand je lance quelque speedtest nperf, j'ai mon shadowsocks qui coupe. Quand je vais voir sur le VPS (machine virtual proxmox VE) j'ai kernel panique + cpu/RAM à 100%.
j'ai tester et 3 fois kernel panique / cpu/RAM à 100%

j'envoi des screenshots.

![kernel_panique_cpu_mem_100%_2](https://user-images.githubusercontent.com/47927025/61993825-f3d31200-b071-11e9-876c-cfb8573b6237.png)
![kernel_panique_cpu_mem_100%_1](https://user-images.githubusercontent.com/47927025/61993826-f3d31200-b071-11e9-9c65-19f249fe2af6.png)
![kernel_panique](https://user-images.githubusercontent.com/47927025/61993827-f3d31200-b071-11e9-831c-4e6505e25329.png)
![kernel panique](https://user-images.githubusercontent.com/47927025/61993828-f3d31200-b071-11e9-8e1e-213ad346785d.png)

**Comment by Ysurac** [comment]
Un soucis de mémoire, 1Go pour le VPS c'est vraiment pas beaucoup.
Tu peux installer htop et vérifier ce qu'il se passe vraiment.

**Comment by cayenne17** [comment]
j'ai une monté d'un coup et plantage 
voici un htop :
![htop](https://user-images.githubusercontent.com/47927025/61995180-fe4ad700-b084-11e9-8372-b5c712d14fcc.png)


je vais mettre la VM à 2 Go

**Comment by cayenne17** [comment]
htop avec 2 Go de RAM pendant 2 nperf en même temps :
![htop1](https://user-images.githubusercontent.com/47927025/61995303-e07e7180-b086-11e9-8d96-d2bc2ef43f1c.png)

**Comment by cayenne17** [comment]
Kernel panic encore. une fuite mémoire ?

![kernel](https://user-images.githubusercontent.com/47927025/61995454-2f2d0b00-b089-11e9-9275-25670348e3c9.png)

![kernel-paniquer 12](https://user-images.githubusercontent.com/47927025/61995446-09076b00-b089-11e9-9244-961185fbe25f.png)

**Comment by Ysurac** [comment]
What is the result if you stop mlvpn  ? ```systemctl stop mlvpn@mlvpn0```

**Comment by cayenne17** [comment]
Voici ce qui se passe

![mlvpn](https://user-images.githubusercontent.com/47927025/61997434-abcbe380-b0a1-11e9-8413-53db727b880e.png)

![test](https://user-images.githubusercontent.com/47927025/61997465-0f561100-b0a2-11e9-9371-f6f57bfab7fb.png)
 je ne perd pas la connexion. dés que je relance plusieurs nperf, monté en RAM puis crash.

**Comment by Ysurac** [comment]
Plusieurs nperf simultanément ?

**Comment by cayenne17** [comment]
oui, car si j'en lance un seul, il me faut un gros débit comme ce matin pour que ça crash
