### ISSUE TITLE
Upload saturate RAM on router

### ISSUE THREAD

**Issue by JorgeMoort89** [Ysurac/openmptcprouter#579]
When I do a lot of uploads (backup some servers, FTP, ecc.) the RAM on the router gradually is used causing at some point high latency and low speed on aggregation. I monitor it via SNMP and in that moment even that service, and all the natted service, stop working.
In this case the router have 4GB of RAM, if I do `htop` or `top` via SSH I don't see any process using that amount of memory. I've also tried with newest and older version, same issue.

<img width="613" alt="upload" src="https://user-images.githubusercontent.com/51922311/62112698-8282a180-b2b3-11e9-9feb-7e61c1174f50.png">

## Specifications

  - OpenMPTCProuter version: 0.49
  - OpenMPTCProuter VPS version: 0.996
  - OpenMPTCProuter platform: x86_64

**Comment by JorgeMoort89** [comment]
Same problem with version 0.51.5 on the router and version 0.999 on the VPS

**Comment by Ysurac** [comment]
I may have too high network buffer, I will make some tests.

**Comment by JorgeMoort89** [comment]
This cause sometimes blocks on DNS resolution. I have to refresh one or two times the web page to have the domain resolved.
