### ISSUE TITLE
Redirection port pour serveur mail et d'autres ports

### ISSUE THREAD

**Issue by Slivikk-fr** [Ysurac/openmptcprouter#580]
## Actual Behavior
Bonjour,

J'ai un serveur mail qui n'a pas l'air de fonctionner pourtant j'ai les ports qui sont ouvert (en principe) avec les port 19999 et 10000 sur mon autre VPS (Sur mon serveur) comment je peut check ça ?

## Specifications

  - OpenMPTCProuter version: (0.51.4)
  - OpenMPTCProuter VPS version: (0.999)
  - OpenMPTCProuter platform: (RPI3B+)

**Comment by Ysurac** [comment]
la doc https://github.com/Ysurac/openmptcprouter/wiki/Port-forwarding a été suivi ? Notamment l'ouverture des ports sur le VPS ?

**Comment by Slivikk-fr** [comment]
Point de vu VPS rien n'a été touché depuis le système le port pour le serveur web c'est bon

**Comment by Slivikk-fr** [comment]
![image](https://user-images.githubusercontent.com/53304251/62163428-9e6d5e00-b31a-11e9-9627-596d167957b6.png)
![image](https://user-images.githubusercontent.com/53304251/62163462-afb66a80-b31a-11e9-90d7-c0311319a90a.png)

**Comment by Slivikk-fr** [comment]
Point de vu port 10000 et 19999 c'est bon

**Comment by Slivikk-fr** [comment]
C'est bon j'ai réussi finalement :D Merci quand même
