### ISSUE TITLE
Change server via CLI

### ISSUE THREAD

**Issue by JorgeMoort89** [Ysurac/openmptcprouter#584]
Hi Ysurac,
I've only SSH access to a router in my house and I'll be not here for a while.
How can I change VPS IP and key by CLI or NAT the web GUI via SSH?

## Specifications

  - OpenMPTCProuter version: 0.49
  - OpenMPTCProuter VPS version: 0.996
  - OpenMPTCProuter platform: (RPI2/RPI3/x86/x86_64)

**Comment by Ysurac** [comment]
For now it's not a good idea to try to change VPS IP over cli.

To use the web interface over SSH:
```ssh -L 15080:127.0.0.1:80 ipoftherouter```
Then website is available over _http://127.0.0.1:15080/_ on your local computer.

**Comment by JorgeMoort89** [comment]
Thanks a lot!
Instead if I wanted to do a NAT services via CLI anyway?
I'm going to nat a lot o services, it will be so much faster

**Comment by Ysurac** [comment]
All is available using ```uci```, you can check OpenWrt doc about that.

**Comment by JorgeMoort89** [comment]
Thanks, I'll check on it.
