### ISSUE TITLE
Kernel Panic

### ISSUE THREAD

**Issue by Marctraider** [Ysurac/openmptcprouter#588]
## Expected Behavior
No Kernel Panic

## Actual Behavior
Kernel Panic, when I start openspeedtest or something.
Already tried upgrading VPS from 1 to 2GB and 2 core cpu but no dice. Also HDD to SSD. Doesn't seem to be load issue.

## Steps to Reproduce the Problem

  1. Install openmptcprouter-v0.51.5-r010518-6d61fcfa9e-mvebu-cortexa9-linksys_wrt3200acm-squashfs-sysupgrade.bin or factory i guess.
  2. Install VPS on Debian 9 or Ubuntu 18 LTS 
  3. Link 3 WAN's and set up OpenMPTCProuter etc... Start speedtest and kernel panic on VPS side.

Something triggers it because not always have i had this, I had the config running flawlessly for 3 days but I just tried different setups etc...
![vps](https://user-images.githubusercontent.com/29001732/62495470-492bc380-b7d6-11e9-9a26-f42277ac02f8.png)

## Specifications

  - OpenMPTCProuter version: v0.51.5-
  - OpenMPTCProuter VPS version: 0.999?
  - OpenMPTCProuter platform: linksys_wrt3200acm

**Comment by Ysurac** [comment]
You seems to use mptcp redundant scheduler. This seems to be not really stable.

**Comment by Marctraider** [comment]
Correct.

When will there be proper redundant support for lowest latency tho? Thanks!

**Comment by Marctraider** [comment]
> 
> 
> You seems to use mptcp redundant scheduler. This seems to be not really stable.

Is there any version which does work OK with redundant? Thank you!
