### ISSUE TITLE
Online.net VPS

### ISSUE THREAD

**Issue by ctrlx83** [Ysurac/openmptcprouter#597]
Hi everyone,

I try OMR on a scaleway VPS (based on AMS1), web navigation is OK, next I try OMR on a online.net VPS (based on DC5), ssl navigation is DOWN.

MTU are same : 1500
Scaleway VPS AMS1 works on Debian 9
Online.net VPS DC5 works on Debian 10

When I go back to the VPS Scaleway, everything works properly.
In both cases, the IP addresses are correct and all the flags are green.

Thanks

## Specifications

  - OpenMPTCProuter version: v0.51.5
  - OpenMPTCProuter VPS version: 0.999 4.19.56-mptcp
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
There is still online.net VPS ? I can't find them.

**Comment by ctrlx83** [comment]
Hi @Ysurac 

My online.net VPS is : https://www.online.net/fr/serveurs-dedies/start-2-s-sata

**Comment by Ysurac** [comment]
It's a dedicated server, not a VPS :)
I will need to make more test on Debian 10, else I have no real idea...

**Comment by ctrlx83** [comment]
Ok
I will try to downgrade server to Debian 9

feedback soon
thanks

**Comment by ctrlx83** [comment]
Downgrade to Debian 9 resolve problem !! 
DNS works OK
SSL navigation OK

For information :
Server at Amsterdam with online.net have 38ms ping
Server at Paris with online.net have 21ms ping
