### ISSUE TITLE
openmptcprouter/status Network overview, server behind nat blocks icmp pings

### ISSUE THREAD

**Issue by sqerk** [Ysurac/openmptcprouter#599]
My server is behind a router that can't respond or forward pings to its wan (google wifi). So my wans constantly show the orange "No Server ping response after 1 second". Is it possible to use a different detection method, between the wans and server?

**Comment by Ysurac** [comment]
In status page, it's only information. And it's a bad practice to no respond/forward ping.
For omr-tracker, that check if wan are up or down, you can choose other methods.
