### ISSUE TITLE
Find Heavy Data Users or protocols

### ISSUE THREAD

**Issue by iditude** [Ysurac/openmptcprouter#600]
Hello,

As I aggregate ADSL with 4g connections, I am limited by the 4G ISP in terms of data usage (plans). I have a few heavy users or protocols in my home and would like to identify the culprit and route that traffic through OMR bypass to ADSL. 

Is there a log of some kind that reports bandwidth usage per IP, name or protocol over a large period (not real time, but cumulative)?

Thanks

**Comment by Ysurac** [comment]
Maybe by using something like luci-app-nlbwmon

**Comment by iditude** [comment]
Thanks, that could work. I'm unsure how to install it though. Would you be able to clarify?

Thanks

**Comment by Ysurac** [comment]
In System->Software

**Comment by iditude** [comment]
ok Thanks!
