### ISSUE TITLE
vpn 

### ISSUE THREAD

**Issue by jlabre** [Ysurac/openmptcprouter#604]
[google trad]
I am trying to bypass the vpn for mycanal and netflix which solution thank you

je cherche a contourner le vpn pour mycanal et netflix quelle solution merci

**Comment by Ysurac** [comment]
En ajoutant les réseaux suivant dans omr-bypass :
```
194.4.242.0/24
194.4.244.0/23
194.4.246.0/24
```
Et si ça fonctionne j'ajouterais ça dans la liste des "protocoles".

**Comment by jlabre** [comment]
re bonjour 
dans IPs et réseaux

**Comment by jlabre** [comment]
<a href="https://www.noelshack.com/2019-33-6-1566030119-1.jpg"><img src="https://image.noelshack.com/minis/2019/33/6/1566030119-1.png" border="0" alt="1566030119-1.jpg - envoi d'image avec NoelShack" title="1566030119-1.jpg"/></a>

**Comment by Ysurac** [comment]
Ils utilisent peut être d'autres IPs maintenant...
Sinon pour netflix il suffit de choisir le protocol "netflix".

**Comment by jlabre** [comment]
je viens de voir aussi que l agrégation ne donne pas le max de debit de toute les box pourquoi ?

**Comment by Ysurac** [comment]
Pour canal, le VPS est chez qui ? Je viens de prendre un abonnement pour tester tout en ayant un VPS chez scaleway et ça semble fonctionner sans bypass ce qui m'aide pas beaucoup pour trouver les IPs ;)

**Comment by jlabre** [comment]
online.net

**Comment by Ysurac** [comment]
Donc même fournisseur du coup... Ca m'arrange pas pour les tests ça...

**Comment by jlabre** [comment]
oui je comprend pas j ai lui de com sur autre site et il marche eu aussi

**Comment by Ysurac** [comment]
Visiblement les vidéos viennent de "akamaihd.net" donc en ajoutant ce domaine ça doit passer.

**Comment by jlabre** [comment]
non toujour rien bizzar

**Comment by jlabre** [comment]
ok c bon avec un reboot de tout merci

**Comment by Ysurac** [comment]
ok je vais vérifier pourquoi ça s'applique pas sinon.
