### ISSUE TITLE
iPhone USB Tethering

### ISSUE THREAD

**Issue by GENERATION2GEEK** [Ysurac/openmptcprouter#606]
## Expected Behavior

Share the connection of my iPhone in USB to RPI for 4G + ADSL aggregation

## Actual Behavior

I can't share the 4G connection from my iPhone to my RaspBerry Pi 3 on OpenMPTCProuter
The iPhone is not even detected on the list of network interfaces and for him, no device is connected to his sharing.
I tried this guide: https://openwrt.org/docs/guide-user/network/wan/smartphone.usb.tethering
But it is impossible to install the packages (Cannot satisfy the following dependencies for...)
Can someone help me?

![omr](https://user-images.githubusercontent.com/33123296/63254557-3dc7a600-c274-11e9-8cc9-3d7c0dd7de5d.png)

## Steps to Reproduce the Problem

  1. Connect the iPhone via USB to the Pi
  2. Enable connection sharing

## Specifications

  - OpenMPTCProuter version: 0.51.5
  - OpenMPTCProuter VPS version: 0.1000
  - OpenMPTCProuter platform: RPI3/x86_64

**Comment by ArChlOgY** [comment]
can you post the kernel log after you have connected your Iphone to Pi ?

**Comment by Ysurac** [comment]
Packets are already available in OpenMPTCProuter, no need to update them.

**Comment by GENERATION2GEEK** [comment]
Okay but how do I make this connection sharing work via USB then and how do I get the kernel logs (I think I know but it's to be sure)?

**Comment by Ysurac** [comment]
For kernel log, it's in "Status->Kernel log".
For USB tethering, read OpenWrt doc, I can't help more: I don't do that.

**Comment by ArChlOgY** [comment]
Plug you phone (activate connection sharing)

Go to Wizard and add an interface with below params (save & apply)

![iphone_omr](https://user-images.githubusercontent.com/52102123/63368299-e7df2500-c37d-11e9-9ff7-800fdc52c6f5.PNG)

Execute from SSH : /usr/sbin/usbmuxd -v

Unlock your phone and you should see the trust-question , use your unlock code to confirm

You should see the blue line a the top of your phone screen confirming that your are sharing internet

Come back on OMR interface and enjoy

**Comment by GENERATION2GEEK** [comment]
Thank you very much for your help, I solved my problem by installing the following script: https://github.com/LeJeko/OpenWRT-USB-Tethering (beware the script changes the ip of the Raspberry to 192.168.0.254)

**Comment by Ysurac** [comment]
The script, in our case, seems to only change IP and run usbmuxd.

**Comment by GENERATION2GEEK** [comment]
Yes, I don't know why but it worked perfectly with me
