### ISSUE TITLE
Operating by page is not available

### ISSUE THREAD

**Issue by hljsykj** [Ysurac/openmptcprouter#611]
I used our program to install and configure the server and parameters, but now it's not good for me to want a detailed process and setup method.

**Comment by Ysurac** [comment]
I don't understand what you want. All is in documentation: https://github.com/Ysurac/openmptcprouter/wiki

**Comment by hljsykj** [comment]
We configure it according to the document, but it's not good. 
We want to use your solution and commercialize it.
We are willing to provide you with financial support.
