### ISSUE TITLE
openmptcprouter status page not loading

### ISSUE THREAD

**Issue by ranusha14** [Ysurac/openmptcprouter#614]
![openmptcprouter](https://user-images.githubusercontent.com/50132238/63513146-0f132f00-c503-11e9-87a6-4aed3fade27a.png)
system->openmptcprouter->status   not loading properly

**Comment by Ysurac** [comment]
Still not OpenMPTCProuter.
But this error should be fixed in master tree.

**Comment by ranusha14** [comment]
how to check whether it is openmptcprouter or not?

**Comment by Ysurac** [comment]
By downloading image from https://www.openmptcprouter.com/
