### ISSUE TITLE
Package update

### ISSUE THREAD

**Issue by JorgeMoort89** [Ysurac/openmptcprouter#615]
When I try to update packages I receive errors only with the OMR repos.
Can that be a problem with the rate of your server? I had same problem in a older issue.

`opkg_download: Failed to download http://downloads.openwrt.org/snapshots/packages/x86_64/telephony/Packages.gz, wget returned 4.
 * opkg_download: Check your network settings and connectivity.`

**Comment by Ysurac** [comment]
This is not an OMR repos but an openwrt repos.
Do you have IPv6 enabled ?

**Comment by JorgeMoort89** [comment]
Resolved changing the default openwrt repos
