### ISSUE TITLE
Master setting weirdness

### ISSUE THREAD

**Issue by Marctraider** [Ysurac/openmptcprouter#620]
## Expected Behavior

I set my 1st WAN as Master, other two Multipath TCP. I disabled WAN3 and all WAN interfaces seem to reset to Multipath TCP.

## Actual Behavior

WAN1 Sticks at Master when turning WAN3 (or WAN2) interface off.

**Comment by Ysurac** [comment]
Use template when you submit a bug. Without any version information I can do nothing.
