### ISSUE TITLE
GloryTun TCP problem.

### ISSUE THREAD

**Issue by Marctraider** [Ysurac/openmptcprouter#621]
## Expected Behavior

Since I assume Glorytun TCP use MPTCP, I expect UDP streams not to fail (or at least quick redundant failover) when turning a random WAN interface down

## Actual Behavior

With 3 WANs up, I disabled WAN3 and the whole UDP streams all stop for 5+ seconds. terminating all UDP connections and ICMP pings.

Seems like subflows not functioning? All my TCP streams happily continued during this.

  - OpenMPTCProuter version: 0.51.5
  - OpenMPTCProuter VPS version: 0.999 4.19.56-mptcp
  - OpenMPTCProuter platform: WRT3200ACM

**Comment by Ysurac** [comment]
You should look in OpenMPTCProuter system log.
And what is the mode you choose for Master interface ?

**Comment by Marctraider** [comment]
> 
> 
> You should look in OpenMPTCProuter system log.
> And what is the mode you choose for Master interface ?

What do you mean mode for Master interface, isn't the mode 'Master' ?

**Comment by Ysurac** [comment]
In OpenMPTCProuter->Advanced settings tab.

**Comment by Marctraider** [comment]
> 
> 
> In OpenMPTCProuter->Advanced settings tab.

If you mean 'Master Interface selection' I have it set to 'No Change'.

**Comment by Marctraider** [comment]
`Tue Aug 27 18:02:22 2019 user.notice post-tracking-post-tracking: Multipath eth0.3 switched to off
Tue Aug 27 18:02:24 2019 user.notice post-tracking-post-tracking: Multipath eth0.2 switched to off
Tue Aug 27 18:02:24 2019 user.notice post-tracking-post-tracking: Multipath eth0.1 switched to off
Tue Aug 27 18:02:34 2019 user.notice MPTCP: Multipath not defined for lan set to off
Tue Aug 27 18:02:34 2019 user.notice MPTCP: Multipath not defined for wan1 set to on
Tue Aug 27 18:02:34 2019 user.notice MPTCP: Multipath not defined for wan2 set to on
Tue Aug 27 18:02:34 2019 user.notice MPTCP: Multipath not defined for wan3 set to on
Tue Aug 27 18:02:34 2019 user.notice MPTCP: Multipath not defined for omrvpn set to off
Tue Aug 27 18:02:34 2019 user.notice MPTCP: Multipath not defined for omr6in4 set to off
Tue Aug 27 18:02:34 2019 user.notice MPTCP: No master multipath defined, setting it to eth0.1
Tue Aug 27 18:02:34 2019 user.notice omr-tracker: Launching...
Tue Aug 27 18:02:34 2019 user.notice omr-tracker: Launched
Tue Aug 27 18:02:35 2019 daemon.info glorytun: starting glorytun vpn instance vpn
Tue Aug 27 18:02:35 2019 daemon.info omr-tracker-ss: Shadowsocks is up (can contact 1.0.0.1)
Tue Aug 27 18:02:35 2019 daemon.notice netifd: Interface 'wan3' is now down
Tue Aug 27 18:02:35 2019 kern.info kernel: [60104.346038] IPv6: ADDRCONF(NETDEV_UP): eth0.3: link is not ready
Tue Aug 27 18:02:35 2019 daemon.notice netifd: Interface 'wan3' is disabled
Tue Aug 27 18:02:35 2019 daemon.notice netifd: Interface 'wan3' has link connectivity loss
Tue Aug 27 18:02:35 2019 daemon.notice netifd: Interface 'wan3' has link connectivity
Tue Aug 27 18:02:35 2019 daemon.notice netifd: VLAN 'eth0.3' link is down
Tue Aug 27 18:02:35 2019 daemon.notice netifd: Interface 'wan3' has link connectivity loss
Tue Aug 27 18:02:38 2019 user.notice omr-bypass: Starting OMR-ByPass...
Tue Aug 27 18:02:41 2019 user.notice omr-bypass: Restart dnsmasq...
Tue Aug 27 18:02:41 2019 daemon.info dnsmasq[14910]: exiting on receipt of SIGTERM
Tue Aug 27 18:02:41 2019 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Tue Aug 27 18:02:41 2019 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Tue Aug 27 18:02:41 2019 user.notice dnsmasq: Allowing RFC1918 responses for domain plex.direct
Tue Aug 27 18:02:44 2019 daemon.info dnsmasq[11252]: started, version 2.80 cachesize 150
Tue Aug 27 18:02:44 2019 daemon.info dnsmasq[11252]: DNS service limited to local subnets
Tue Aug 27 18:02:44 2019 daemon.info dnsmasq[11252]: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC no-ID loop-detect inotify dumpfile
Tue Aug 27 18:02:44 2019 daemon.info dnsmasq-dhcp[11252]: DHCP, IP range 192.168.100.100 -- 192.168.100.249, lease time 12h
Tue Aug 27 18:02:44 2019 daemon.info dnsmasq[11252]: using local addresses only for domain test
Tue Aug 27 18:02:44 2019 daemon.info dnsmasq[11252]: using local addresses only for domain onion
Tue Aug 27 18:02:44 2019 daemon.info dnsmasq[11252]: using local addresses only for domain localhost
Tue Aug 27 18:02:44 2019 daemon.info dnsmasq[11252]: using local addresses only for domain local
Tue Aug 27 18:02:44 2019 daemon.info dnsmasq[11252]: using local addresses only for domain invalid
Tue Aug 27 18:02:44 2019 daemon.info dnsmasq[11252]: using local addresses only for domain bind
Tue Aug 27 18:02:44 2019 daemon.info dnsmasq[11252]: using nameserver 8.8.8.8#53
Tue Aug 27 18:02:44 2019 daemon.info dnsmasq[11252]: using nameserver 127.0.0.1#5353
Tue Aug 27 18:02:44 2019 daemon.info dnsmasq[11252]: using local addresses only for domain lan
Tue Aug 27 18:02:44 2019 daemon.info dnsmasq[11252]: read /etc/hosts - 4 addresses
Tue Aug 27 18:02:44 2019 daemon.info dnsmasq[11252]: read /tmp/hosts/dhcp.cfg01411c - 3 addresses
Tue Aug 27 18:02:44 2019 daemon.info dnsmasq-dhcp[11252]: read /etc/ethers - 0 addresses
Tue Aug 27 18:02:44 2019 user.notice omr-bypass: OMR-ByPass is running
Tue Aug 27 18:02:51 2019 daemon.info vnstatd[16680]: Info: Interface "eth0.3" disabled.
Tue Aug 27 18:04:09 2019 daemon.info glorytun: starting glorytun vpn instance vpn
Tue Aug 27 18:04:09 2019 user.notice omr-tracker: Launching...
Tue Aug 27 18:04:09 2019 user.notice omr-tracker: Launched
Tue Aug 27 18:04:09 2019 user.notice post-tracking-post-tracking: Multipath eth0.2 switched to off
Tue Aug 27 18:04:09 2019 user.notice MPTCP: Multipath not defined for lan set to off
Tue Aug 27 18:04:09 2019 user.notice MPTCP: Multipath not defined for wan1 set to on
Tue Aug 27 18:04:09 2019 user.notice MPTCP: Multipath not defined for wan2 set to on
Tue Aug 27 18:04:09 2019 daemon.info omr-tracker-ss: Shadowsocks is up (can contact 1.0.0.1)
Tue Aug 27 18:04:09 2019 user.notice MPTCP: Multipath not defined for wan3 set to on
Tue Aug 27 18:04:10 2019 user.notice MPTCP: Multipath not defined for omrvpn set to off
Tue Aug 27 18:04:10 2019 user.notice MPTCP: Multipath not defined for omr6in4 set to off
Tue Aug 27 18:04:10 2019 user.notice MPTCP: No master multipath defined, setting it to eth0.1
Tue Aug 27 18:04:11 2019 daemon.notice netifd: Interface 'wan3' is enabled
Tue Aug 27 18:04:11 2019 daemon.notice netifd: Interface 'wan3' is setting up now
Tue Aug 27 18:04:11 2019 daemon.notice netifd: Interface 'wan3' is now up
Tue Aug 27 18:04:11 2019 daemon.notice netifd: VLAN 'eth0.3' link is up
Tue Aug 27 18:04:11 2019 daemon.notice netifd: Interface 'wan3' has link connectivity
Tue Aug 27 18:04:11 2019 user.notice SQM: Stopping SQM on eth0.3
Tue Aug 27 18:04:11 2019 user.notice SQM: ERROR: cmd_wrapper: tc: FAILURE (2): /usr/sbin/tc qdisc del dev eth0.3 ingress
Tue Aug 27 18:04:11 2019 user.notice SQM: ERROR: cmd_wrapper: tc: LAST ERROR: RTNETLINK answers: No such file or directory
Tue Aug 27 18:04:11 2019 user.notice SQM: ERROR: cmd_wrapper: tc: FAILURE (2): /usr/sbin/tc qdisc del dev eth0.3 root
Tue Aug 27 18:04:11 2019 user.notice SQM: ERROR: cmd_wrapper: tc: LAST ERROR: RTNETLINK answers: No such file or directory
Tue Aug 27 18:04:11 2019 user.notice SQM: Starting SQM script: piece_of_cake.qos on eth0.3, in: 20000 Kbps, out: 15000 Kbps
Tue Aug 27 18:04:11 2019 user.notice SQM: piece_of_cake.qos was started on eth0.3 successfully
Tue Aug 27 18:04:11 2019 user.notice firewall: Reloading firewall due to ifup of wan3 (eth0.3)
Tue Aug 27 18:04:12 2019 user.notice mptcp: Reloading mptcp config due to ifup of wan3 (eth0.3)
Tue Aug 27 18:04:12 2019 user.notice MPTCP: No master multipath defined, setting it to eth0.1
Tue Aug 27 18:04:14 2019 user.notice omr-bypass: Starting OMR-ByPass...
Tue Aug 27 18:04:16 2019 user.notice omr-bypass: Restart dnsmasq...
Tue Aug 27 18:04:16 2019 daemon.info dnsmasq[11252]: exiting on receipt of SIGTERM
Tue Aug 27 18:04:16 2019 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Tue Aug 27 18:04:16 2019 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Tue Aug 27 18:04:16 2019 user.notice dnsmasq: Allowing RFC1918 responses for domain plex.direct
Tue Aug 27 18:04:20 2019 daemon.info dnsmasq[16819]: started, version 2.80 cachesize 150
Tue Aug 27 18:04:20 2019 daemon.info dnsmasq[16819]: DNS service limited to local subnets
Tue Aug 27 18:04:20 2019 daemon.info dnsmasq[16819]: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC no-ID loop-detect inotify dumpfile
Tue Aug 27 18:04:20 2019 daemon.info dnsmasq-dhcp[16819]: DHCP, IP range 192.168.100.100 -- 192.168.100.249, lease time 12h
Tue Aug 27 18:04:20 2019 daemon.info dnsmasq[16819]: using local addresses only for domain test
Tue Aug 27 18:04:20 2019 daemon.info dnsmasq[16819]: using local addresses only for domain onion
Tue Aug 27 18:04:20 2019 daemon.info dnsmasq[16819]: using local addresses only for domain localhost
Tue Aug 27 18:04:20 2019 daemon.info dnsmasq[16819]: using local addresses only for domain local
Tue Aug 27 18:04:20 2019 daemon.info dnsmasq[16819]: using local addresses only for domain invalid
Tue Aug 27 18:04:20 2019 daemon.info dnsmasq[16819]: using local addresses only for domain bind
Tue Aug 27 18:04:20 2019 daemon.info dnsmasq[16819]: using nameserver 8.8.8.8#53
Tue Aug 27 18:04:20 2019 daemon.info dnsmasq[16819]: using nameserver 127.0.0.1#5353
Tue Aug 27 18:04:20 2019 daemon.info dnsmasq[16819]: using local addresses only for domain lan
Tue Aug 27 18:04:20 2019 daemon.info dnsmasq[16819]: read /etc/hosts - 4 addresses
Tue Aug 27 18:04:20 2019 daemon.info dnsmasq[16819]: read /tmp/hosts/dhcp.cfg01411c - 3 addresses
Tue Aug 27 18:04:20 2019 daemon.info dnsmasq-dhcp[16819]: read /etc/ethers - 0 addresses
Tue Aug 27 18:04:20 2019 user.notice omr-bypass: OMR-ByPass is running
`

Ping log:
`2019-08-27 18:02:05.337: From 1.1.1.1: bytes=60 seq=0f60 TTL=57 ID=58f4 time=39.360ms
2019-08-27 18:02:06.331: From 1.1.1.1: bytes=60 seq=0f61 TTL=57 ID=5c70 time=34.625ms
2019-08-27 18:02:07.335: From 1.1.1.1: bytes=60 seq=0f62 TTL=57 ID=5cde time=37.994ms
2019-08-27 18:02:08.336: From 1.1.1.1: bytes=60 seq=0f63 TTL=57 ID=5f01 time=40.264ms
2019-08-27 18:02:09.331: From 1.1.1.1: bytes=60 seq=0f64 TTL=57 ID=6068 time=34.843ms
2019-08-27 18:02:10.338: From 1.1.1.1: bytes=60 seq=0f65 TTL=57 ID=615d time=40.677ms
2019-08-27 18:02:11.313: From 1.1.1.1: bytes=60 seq=0f66 TTL=57 ID=61a0 time=16.359ms
2019-08-27 18:02:12.328: From 1.1.1.1: bytes=60 seq=0f67 TTL=57 ID=61db time=30.982ms
2019-08-27 18:02:13.313: From 1.1.1.1: bytes=60 seq=0f68 TTL=57 ID=61f9 time=16.061ms
2019-08-27 18:02:15.374: From 1.1.1.1: bytes=60 SEQ=0f6a TTL=57 ID=635e time=76.953ms
2019-08-27 18:02:16.511: From 1.1.1.1: bytes=60 seq=0f6b TTL=57 ID=670b time=214.211ms
2019-08-27 18:02:17.338: From 1.1.1.1: bytes=60 seq=0f6c TTL=57 ID=6874 time=40.927ms
2019-08-27 18:02:18.297: Timeout waiting for seq=0f69
2019-08-27 18:02:18.347: From 1.1.1.1: bytes=60 seq=0f6d TTL=57 ID=68d4 time=50.302ms
2019-08-27 18:02:20.369: From 1.1.1.1: bytes=60 SEQ=0f6f TTL=57 ID=6b1d time=72.528ms
2019-08-27 18:02:21.365: From 1.1.1.1: bytes=60 seq=0f70 TTL=57 ID=6e68 time=68.200ms
2019-08-27 18:02:22.297: Timeout waiting for seq=0f6e
2019-08-27 18:02:22.352: From 1.1.1.1: bytes=60 seq=0f71 TTL=57 ID=71b9 time=54.980ms
2019-08-27 18:02:23.739: From 1.1.1.1: bytes=60 seq=0f72 TTL=57 ID=75b4 time=443.094ms
2019-08-27 18:02:26.297: Timeout waiting for seq=0f73
2019-08-27 18:02:28.298: Timeout waiting for seq=0f74
2019-08-27 18:02:28.298: Timeout waiting for seq=0f75
2019-08-27 18:02:30.297: Timeout waiting for seq=0f76
2019-08-27 18:02:32.297: Timeout waiting for seq=0f77
2019-08-27 18:02:32.297: Timeout waiting for seq=0f78
2019-08-27 18:02:34.298: Timeout waiting for seq=0f79
2019-08-27 18:02:34.298: Timeout waiting for seq=0f7a
2019-08-27 18:02:34.298: Timeout waiting for seq=0f7b
2019-08-27 18:02:34.630: From 1.1.1.1: bytes=60 SEQ=0f7c TTL=57 ID=854a time=1332.137ms
2019-08-27 18:02:34.977: From 1.1.1.1: bytes=60 seq=0f7d TTL=57 ID=8562 time=679.671ms
2019-08-27 18:02:35.366: From 1.1.1.1: bytes=60 seq=0f7e TTL=57 ID=87d8 time=69.466ms
2019-08-27 18:02:36.359: From 1.1.1.1: bytes=60 seq=0f7f TTL=57 ID=87fc time=62.496ms
2019-08-27 18:02:37.369: From 1.1.1.1: bytes=60 seq=0f80 TTL=57 ID=8961 time=71.078ms
2019-08-27 18:02:38.373: From 1.1.1.1: bytes=60 seq=0f81 TTL=57 ID=8aab time=77.407ms
2019-08-27 18:02:39.383: From 1.1.1.1: bytes=60 seq=0f82 TTL=57 ID=8b34 time=86.729ms
2019-08-27 18:02:40.358: From 1.1.1.1: bytes=60 seq=0f83 TTL=57 ID=8ecc time=60.938ms
2019-08-27 18:02:41.366: From 1.1.1.1: bytes=60 seq=0f84 TTL=57 ID=9196 time=69.428ms
2019-08-27 18:02:42.360: From 1.1.1.1: bytes=60 seq=0f85 TTL=57 ID=9488 time=63.483ms
2019-08-27 18:02:43.359: From 1.1.1.1: bytes=60 seq=0f86 TTL=57 ID=9803 time=62.785ms
2019-08-27 18:02:44.361: From 1.1.1.1: bytes=60 seq=0f87 TTL=57 ID=9a34 time=63.048ms`

**Comment by Ysurac** [comment]
There is no problem here : you turn off a network interface via enable/disable in network, every change in network reload MPTCP configuration. I don't think it's really a problem.
You ping 1.1.1.1 and if you didn't remove it, it's an IP used to check if interface are up or down in omr-tracker, so ping using this IP can (will) fail.

**Comment by Marctraider** [comment]
So its impossible to disable interface without screwing all up?

All UDP streams disconnected when doing this, the ping log just shows part of it...

**Comment by Ysurac** [comment]
Disabling an interface via the graphical interface yes, this reset all connections. It's the same when we change any network settings.
