### ISSUE TITLE
Master setting weirdness

### ISSUE THREAD

**Issue by Marctraider** [Ysurac/openmptcprouter#622]
## Expected Behavior

I set my 1st WAN as Master, other two Multipath TCP. I disabled WAN3 and all WAN interfaces seem to reset to Multipath TCP.

## Actual Behavior

WAN1 Sticks at Master when turning WAN3 (or WAN2) interface off. 
0.51.5

  - OpenMPTCProuter version: 0.51.5
  - OpenMPTCProuter VPS version: 0.999 4.19.56-mptcp
  - OpenMPTCProuter platform: WRT3200ACM

**Comment by Ysurac** [comment]
Update to latest release.

**Comment by Marctraider** [comment]
Sorry typo, im on last version.

**Comment by Ysurac** [comment]
How do you disable WAN interface ?

**Comment by Marctraider** [comment]
> 
> 
> How do you disable WAN interface ?

Network -> Interfaces -> Stop / Connect

**Comment by Ysurac** [comment]
It's a know issue: settings are removed when an interface is stopped. No idea why for now.

**Comment by Marctraider** [comment]
Ok thanks.
