### ISSUE TITLE
Wrong log server block natted service

### ISSUE THREAD

**Issue by JorgeMoort89** [Ysurac/openmptcprouter#623]
Setting up wrong log server block slow down a lot all the natted services and broken the aggregation.

## Specifications

  - OpenMPTCProuter version: 0.49
  - OpenMPTCProuter VPS version: 0.996
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
I don't understand the problem.

**Comment by JorgeMoort89** [comment]
If you set an IP in the remote logging server and on that IP there is no working logging server, it will constantly fail to send the log generating a lot of issues, all the natted service stop working/slow down a lot and the router will not aggregate more.

**Comment by Ysurac** [comment]
It's the problem when using a TCP logging server.
This may be better by replacing default logd by syslog-ng but I will not do that for now.
