### ISSUE TITLE
Can't add Traffic Rules on RPI4B

### ISSUE THREAD

**Issue by bournehlm** [Ysurac/openmptcprouter#628]
## Expected Behavior

  I can't add Traffic Rules, there is no add button in the Traffic Rules setting page.

## Specifications

  - OpenMPTCProuter version: (0.51.5)
  - OpenMPTCProuter VPS version: (0.997)
  - OpenMPTCProuter platform: (RPI4B 2G 32bit ext4)

**Comment by Ysurac** [comment]
There is forward rules and open ports input at the bottom of the page.
