### ISSUE TITLE
option/documentation for udp through glorytun vpn 

### ISSUE THREAD

**Issue by dur3x** [Ysurac/openmptcprouter#63]
## Expected Behavior

I'm trying to force all my traffic (e.g. QUIC protocol https://ma.ttias.be/googles-quic-protocol-moving-web-tcp-udp/) to go through the glorytun vpn so that I can use all the bandwith by using for example youtube with QUIC

## Actual Behavior
All the UDP traffic goes through the shadowsocks Tproxy (this is done only through one wan interface(the default one set as master), not multiple)

## Steps to Reproduce the Problem

  1. Use chrome (with the default option so that quic protocol is enabled) and watch video on youtube.
  2. Observ that all traffic goes on only one interface (my goal is to use all ones)

## Specifications

  - OpenMPTCProuter version: latest
  - OpenMPTCProuter VPS version: latest
  - OpenMPTCProuter platform: (RPI3/x86_64) all

**Comment by Ysurac** [comment]
You can disable UDP redirection though ShadowSocks in Services->ShadowSocks->Redir Rules and set ss-redir for UDP to unset. This will use Glorytun VPN if enabled, else you Master WAN connection.

**Comment by dur3x** [comment]
Thanks for your reply, I will try that again this evening but I think that
when I checked my settings this parameter was already shown as TCP unset &
UDP unset.
I keep you in touch.

Le 24 May 2018 à 08:51, Ycarus <notifications@github.com> a écrit :

You can disable UDP redirection though ShadowSocks in
Services->ShadowSocks->Redir Rules and set ss-redir for UDP to unset. This
will use Glorytun VPN if enabled, else you Master WAN connection.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Ysurac/openmptcprouter/issues/63#issuecomment-391608333>,
or mute the thread

**Comment by Ysurac** [comment]
True, there is a bug in shadowsocks interface since a change in LuCi.
This will be fixed in next release.

**Comment by dur3x** [comment]
Ok so I just tried by modifying my configuration in  /etc/config/shadowsocks-libev
like that: (remove udp redirection + restart)
https://github.com/Ysurac/openmptcprouter-feeds/commit/9028cc1823715c008fbba60e1e3d8754d70b57c8

but it looks this is not sufficient, for example if I'm trying that it's not working:
`nslookup google.fr 8.8.8.8`

**Comment by Ysurac** [comment]
I forget to create a rules to allow forward from LAN to VPN in firewall...
This will be fixed in next release that should be available in one or two hours.
Thanks.

**Comment by dur3x** [comment]
Thanks a lot ! It's ok with your latest commit https://github.com/Ysurac/openmptcprouter-feeds/blob/75c70fa721bbc4772de231b8eb6a3558302a2900/luci-app-glorytun/root/etc/uci-defaults/40_luci-glorytun
