### ISSUE TITLE
Need advice for a TP-link router ?

### ISSUE THREAD

**Issue by Pokpok-sbo** [Ysurac/openmptcprouter#630]
Hello, I would like to test OpenMPTCProuter. I have a TP-link router, model TL-R480 and I would like to know if I can install OpenMPTCProuter on it.
Here is the manufacturer's link: https://www.tp-link.com/fr/business-networking/load-balance-router/tl-r480t+/

Thanks

**Comment by suyuan168** [comment]
> Hello, I would like to test OpenMPTCProuter. I have a TP-link router, model TL-R480 and I would like to know if I can install OpenMPTCProuter on it.
> Here is the manufacturer's link: https://www.tp-link.com/fr/business-networking/load-balance-router/tl-r480t+/
> 
> Thanks

His flash is too small to fit openmptcprouter

**Comment by suyuan168** [comment]
Moreover, its TL-R480T+ CPU memory configuration is too low, can not run openmptcprouter very well. At least his flash can not be installed,

**Comment by Ysurac** [comment]
True: not supported by OpenWrt, slow CPU, small flash, small memory. This can't be supported.

**Comment by Pokpok-sbo** [comment]
> True: not supported by OpenWrt, slow CPU, small flash, small memory. This can't be supported.

That's a real shame! Thank you for your answers
