### ISSUE TITLE
PiHole DNS over HTTPS (DoH)

### ISSUE THREAD

**Issue by zicochaos** [Ysurac/openmptcprouter#633]
Any chance to add this as option when installing PiHole script 

https://docs.pi-hole.net/guides/dns-over-https/

Thanks 
Sebastian

**Comment by vistman** [comment]
This is actually the same request as mine mentioned here - https://github.com/Ysurac/openmptcprouter/issues/624. It would be a nice thing to have implemented. Thanks.

**Comment by zicochaos** [comment]
if you follow guide from the link PiHole and everything works fine. DOH works great :) Just few manual steps are needed.

**Comment by vistman** [comment]
Thanks for your feedback. Still, DoT as an official standard would be a better option.

**Comment by zicochaos** [comment]
> And this procedure needs to be repeated upon each fw upgrade which is not very practical.

you don't need to repeat the procedure. All works after upgrading VPS :)

**Comment by user747** [comment]
Another option
https://github.com/pi-hole/pi-hole/wiki/DNSCrypt-2.0
