### ISSUE TITLE
Is it possible to guide interface data to a specific device

### ISSUE THREAD

**Issue by ploufe** [Ysurac/openmptcprouter#636]
Hi,
I have a merge DSL/LTE network.
I would like to avoid to use LTE data for one specific internal IP (my NAS IP) or to use only DSL for this specific IP?
Is it possible?

If not, is it possible to priorise DSL data and use LTE only when DSL is not working (because my DSL link is very unstable)

thank's

**Comment by Bestle** [comment]
Sounds like this would be possible with omr-bypass.

**Comment by ploufe** [comment]
thank's!
