### ISSUE TITLE
Kernel error

### ISSUE THREAD

**Issue by JorgeMoort89** [Ysurac/openmptcprouter#638]
I've the syslog full of:
`kern.warn kernel: [  193.435083] bsalg: parser failed`
obv same for the kernel log, how can I resolve it?

## Specifications

  - OpenMPTCProuter version: 0.49
  - OpenMPTCProuter VPS version: 0.997
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
This comes from net/ipv4/netfilter/nf_nat_snmp_basic.c and happens if SNMP requests can not be correctly NATed.
This happen on which side ? VPS or router ?

**Comment by JorgeMoort89** [comment]
Router side

**Comment by Ysurac** [comment]
Do you use SNMP  or not at all ?

**Comment by JorgeMoort89** [comment]
Yes, I have this problem when I enable it on LAN side
