### ISSUE TITLE
Which protocol is better for connecting 4G modules?

### ISSUE THREAD

**Issue by hljsykj** [Ysurac/openmptcprouter#639]
I want to connect multiple 4G minipci-e modules. Which interface protocol is better? How do I set parameters? Thank you!

**Comment by Ysurac** [comment]
No idea. Solutions based on NDIS (QMI mode) seems to be more stable.
For parameters you can refer to OpenWrt documentation.

**Comment by hljsykj** [comment]
In QMI mode, the MAC addresses of 4G network cards are all 0 connection status and gateway down is displayed.

**Comment by Ysurac** [comment]
In QMI MAC address displayed on the host is often a fake one, only used between host and the key. This is announced by the firmware of the key (that can be buggy).
