### ISSUE TITLE
Quastion: How to customize openmptcprouter

### ISSUE THREAD

**Issue by LovingFox** [Ysurac/openmptcprouter#640]
I want to tune openmptcprouter firmware configuration for my project. I do not need ALL components of openmptcprouter. I just need to use only bpi-r2 with MPTCP+OpenVPN, some other OpenWRT components and custom OpenWRT-configuration files (/etc/config/*).

How can I tune openmptcprouter build configuration like OpenWRT "make menuconfig"?
In the openmptcprouter help page I see only the choose of OMR_TARGET and execution of ./build.sh.

**Comment by Ysurac** [comment]
After the ./build.sh execution, you can run make menuconfig in the "$OMR_TARGET/source" directory.
