### ISSUE TITLE
Closing Gateway with 4G Network Card Status Display

### ISSUE THREAD

**Issue by hljsykj** [Ysurac/openmptcprouter#645]
![image](https://user-images.githubusercontent.com/54393248/64484373-9a026200-d243-11e9-94a3-7e1d892586c1.png)
Using 4G network card, the MAC address appears to be 0.
![image](https://user-images.githubusercontent.com/54393248/64484390-c3bb8900-d243-11e9-818e-ef1215f7ec4f.png)
Status display gateway down

**Comment by Ysurac** [comment]
Yes, because with QMI gateway seems to doesn't answer to ping.

**Comment by hljsykj** [comment]
What causes this?

**Comment by hljsykj** [comment]
It's normal to use this network card to test the network at present.

**Comment by Ysurac** [comment]
I don't know if it's an issue with QMI or if it's GSM network that block ICMP to the gateway, but it's often the case but it's not a real issue for OpenMPTCProuter, this only display a warning.

**Comment by hljsykj** [comment]
Aggregation does not work

**Comment by Ysurac** [comment]
This is more an issue ;)
Else everything is green on the status page ?
MPTCP kernel is used on the VPS side ?
I would need the config (in System->OpenMPTCProuter->Show All settings, remove the VPS IP).
I also need the version of OpenMPTCProuter used, the version of the VPS script, the platform used.

**Comment by Ysurac** [comment]
And the result of ```omr-test-speed```, ```omr-test-speed wan1``` (for each interface), via SSH on the router.

**Comment by hljsykj** [comment]
![image](https://user-images.githubusercontent.com/54393248/64484772-9b368d80-d249-11e9-90a5-53bb8f33f381.png)
Raspberry pie 3B+

**Comment by hljsykj** [comment]
![image](https://user-images.githubusercontent.com/54393248/64485145-3aaa4f00-d24f-11e9-8bc5-745a8b41d95a.png)
![image](https://user-images.githubusercontent.com/54393248/64485147-40079980-d24f-11e9-9237-eeb5c987b62d.png)
![image](https://user-images.githubusercontent.com/54393248/64485150-46961100-d24f-11e9-96d5-31f87f5e77f7.png)

**Comment by Ysurac** [comment]
I should say to use it at least 2 minutes

**Comment by hljsykj** [comment]
![image](https://user-images.githubusercontent.com/54393248/64485932-1ce1e780-d259-11e9-8c24-3d40bd2e61b1.png)

**Comment by Ysurac** [comment]
The best speed is with omr-test-speed, so I would say that it's working, even if it's still really slow... (it's in ko/s, so 113ko*8=>904kb/s = 0.9Mb/s)

**Comment by hljsykj** [comment]
Yes, in the actual test, this PCI-E 4G network card does not use too much traffic, but the use of other usb4g network cards does not have this problem. I think it's a QMI protocol issue. Is there a better solution? Thank you very much.

**Comment by hljsykj** [comment]
![image](https://user-images.githubusercontent.com/54393248/64486151-fffae380-d25b-11e9-9139-824a8a17b119.png)
![image](https://user-images.githubusercontent.com/54393248/64486152-04270100-d25c-11e9-985d-bd9bdb35bb63.png)
![image](https://user-images.githubusercontent.com/54393248/64486153-08ebb500-d25c-11e9-936a-077946edd4c5.png)
