### ISSUE TITLE
VPN on VPS

### ISSUE THREAD

**Issue by quanticware** [Ysurac/openmptcprouter#647]
## Actual Behavior

My IP VPS is banned by some servers

## Steps to Reproduce the Problem

 Nothing, it's by default

## Specifications

  - OpenMPTCProuter version: v0.51.5 r0+10518-6d61fcfa9e
  - OpenMPTCProuter VPS version: 0.999
  - OpenMPTCProuter platform: RPI3

Just question.
Is it possible to install on VPS a VPN client connection and redirect all traffic on it? 
I know there is bypass solution, but with VPN client is better I thinking.

Suggestion or other idea?

If I have to install VPN client, which advice? 

Thanks

**Comment by Ysurac** [comment]
Yes it's possible, but this will add latency.
I think you are speaking about VPN services, I have never used them, so I have no idea at all.
