### ISSUE TITLE
change Vlan IP

### ISSUE THREAD

**Issue by teraska47** [Ysurac/openmptcprouter#65]
On OpenMPTCProuter 168.100.1, is it possible to change the Vlan IP to 192.168.0.1,?
I do not want to redo my entire addressing plan.

**Comment by Ysurac** [comment]
You can use the IP you want.

**Comment by dur3x** [comment]
@teraska47 
Click on Network → Interfaces, then click on the Edit button of the LAN Network.
In General Setup tab, in IPv4 address you can easily change the ip 192.168.100.1 to 192.168.0.1

**Comment by teraska47** [comment]
ok that's perfect that's what I wanted to know, really good work
