### ISSUE TITLE
Déconnexion journalier (plus aucune connexion)

### ISSUE THREAD

**Issue by Slivikk-fr** [Ysurac/openmptcprouter#654]
## Actual Behavior
Bonjour, j'ai l'impression d'avoir des déconnexion chaque jour je ne sais pas pourquoi les deux connexion fonctionnent (enfin une sur deux la seconde (box orange) veut pas ce connecté), j'ai une carte réseau spécialement pour OpenMPTCP, quand la connexion saute la carte est toujours connecté. Ça viendrais du routeur ou de la carte réseau ?

## Steps to Reproduce the Problem

  1. Attendre le jour suivant (en général)
  2. Plus de connexion
  3.

## Specifications

  - OpenMPTCProuter version: (0.51.3)
  - OpenMPTCProuter VPS version: (0.xxx (je me souviens plus de la version))
  - OpenMPTCProuter platform: (x86_64 on ESXI 6.7)

**Comment by Ysurac** [comment]
Il faut voir les journaux systèmes.

**Comment by Slivikk-fr** [comment]
Ou ça ? 😅

**Comment by Ysurac** [comment]
Dans Etat->Journal Système

**Comment by Slivikk-fr** [comment]
Le problème à l'air de s'être résolu tout seul merci quand même
