### ISSUE TITLE
Is it possible to access control interface over WiFi or locally ?

### ISSUE THREAD

**Issue by BlackFireAlex** [Ysurac/openmptcprouter#656]
## Expected Behavior

 Using this without ever needing a RJ45 cable

## Actual Behavior

All connectivity deactivated by default in the OS image

## Steps to Reproduce the Problem

  1. Create bootable usb
  2. Access the command line
  3. Have no Ethernet cable

## Specifications

  - OpenMPTCProuter version: 0.51.5
  
  - OpenMPTCProuter platform: /x86/x86_64

**Comment by Slivikk-fr** [comment]
You can control over WiFi or via Ethernet :) If your wifi is the same network of your router 👍

**Comment by Ysurac** [comment]
Connectivity over wifi will not be enabled by default, this would be a security problem.
