### ISSUE TITLE
New image for RPI 3/3b+ (x64) not exist

### ISSUE THREAD

**Issue by Randdrick** [Ysurac/openmptcprouter#659]
## Expected Behavior

 I wish to download image v 0.52 

## Actual Behavior
New image (v.052) for RPI 3/3b+ (x64) not exist. Only image v 0.51.5 can be found.

**Comment by Ysurac** [comment]
Yes, image was badly generated, a new image will be out soon.

**Comment by Ysurac** [comment]
Fixed
