### ISSUE TITLE
Form token mismatch

### ISSUE THREAD

**Issue by nicoz76** [Ysurac/openmptcprouter#66]
## Expected Behavior

I want to add a new interface

## Actual Behavior

![image](https://user-images.githubusercontent.com/10829637/40543232-c0bf9658-6023-11e8-8e8c-8e168af9361d.png)

## Specifications

  - OpenMPTCProuter version: openmptcprouter v0.20-1-g75c70fa r7036-4f442f5f38 
  - OpenMPTCProuter VPS version: last
  - OpenMPTCProuter platform: (RPI3/x86_64) RPI3B+

**Comment by Ysurac** [comment]
Where ? In OpenMPTCProuter wizard ?

**Comment by nicoz76** [comment]
NETWORK >  INTERFACES >  ADD NEWS INTERFACE

**Comment by Ysurac** [comment]
I test my patches and a new release will be available today.

**Comment by Ysurac** [comment]
It's fixed in version 0.20.1
