### ISSUE TITLE
Error 404 on Glorytun stop/start

### ISSUE THREAD

**Issue by pbonnard** [Ysurac/openmptcprouter#662]
## Expected Behavior

No error message

## Actual Behavior

Screen display

404 Pas trouvé

Désolé, l'objet que vous avez demandé n'as pas été trouvé.
Impossible d'envoyer: /cgi-bin/luci/admin/services/glorytun

## Steps to Reproduce the Problem

  1. Stop or start glorytun from VPN menu

## Specifications

  - OpenMPTCProuter version:  v0.52.2 r0+11006-713561a10b 
  - OpenMPTCProuter VPS version: 0.1000 4.19.67
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
Will be fixed in 0.52.3
