### ISSUE TITLE
Error in omr-admin.py

### ISSUE THREAD

**Issue by pbonnard** [Ysurac/openmptcprouter#663]
## Expected Behavior

No error in daemon.log on VPS

## Actual Behavior

Daemon.log shows error like:
omr-admin.py[552]: Invalid option: +times=3

## Steps to Reproduce the Problem

Occur on a regular basis in daemon.log
Can probably be fixed by replacing '+times' by '+time' option

## Specifications

  - OpenMPTCProuter version: v0.52.2 r0+11006-713561a10b 
  - OpenMPTCProuter VPS version: v0.1000
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
Fixed in v0.1001
