### ISSUE TITLE
Error messages on LUCI.

### ISSUE THREAD

**Issue by Marctraider** [Ysurac/openmptcprouter#665]
## Expected Behavior

No error message in luci.

## Actual Behavior

Both System -> System and Network -> DHCP and DNS throw same error.

## Steps to Reproduce the Problem

  1. Clean factory image flash
2. observe error navigating to these luci elements.

## Specifications

    OpenMPTCProuter version: 0.52.2
    OpenMPTCProuter VPS version: 0.1001
    OpenMPTCProuter platform: WRT3200ACM

![call failed](https://user-images.githubusercontent.com/29001732/65103702-4c1df480-d9cf-11e9-949a-f0cc897bb8e2.png)

**Comment by Marctraider** [comment]
Today, I saw it only once, and now i can both access System -> System and Network -> DHCP and DNS without any warning like this.

I have not rebooted since.
Looks like its random bug?

**Comment by Ysurac** [comment]
I think it's more a browser cache issue.

**Comment by Marctraider** [comment]
> 
> 
> I think it's more a browser cache issue.

You might actually be right as it has disappeared completely now. Not the first problem with Openwrt and firefox in general :)

Sorry to bother you with this.
