### ISSUE TITLE
Glorytun settings threw error which got fixed, but applying config still throws similar error.

### ISSUE THREAD

**Issue by Marctraider** [Ysurac/openmptcprouter#666]
Just a heads up, i know i reported this in IRC channel the other day, but it still gives similar error when applying settings.

    OpenMPTCProuter version: 0.52.2
    OpenMPTCProuter VPS version: 0.1001
    OpenMPTCProuter platform: WRT3200ACM

**Comment by Ysurac** [comment]
Same as #662
