### ISSUE TITLE
Quastion: How to left only MPTCP and OpenVPN?

### ISSUE THREAD

**Issue by LovingFox** [Ysurac/openmptcprouter#667]
Is it possible to cut off many components from the build easy way? I need only MPTCP, OpenVPN, and omr-tracker to monitor uplinks. Others (shadowsocs, mlvpn, glorytun, luci etc) I need to remove.

**Comment by Ysurac** [comment]
By not installing OpenMPTCProuter-full package.

**Comment by LovingFox** [comment]
Yes, but if I switch off this checkbox in menuconfig many other omr's components left that I need off manual. And I cannot manual switch off many others completely (for example shadowsocks-libev). Many dependencies prevent to do that.
