### ISSUE TITLE
Glorytun TCP can't start up

### ISSUE THREAD

**Issue by JorgeMoort89** [Ysurac/openmptcprouter#668]
If I install VPS side on fresh installed machine I have no problem at all, on a cloned machine I have this problem:
Connecting OMR with public IP and KEY give me this error:

OMR side
<img width="750" alt="screen" src="https://user-images.githubusercontent.com/51922311/65161216-77d4c500-da37-11e9-91b1-135460e55c5a.png">

VPS side:
<img width="415" alt="screen2" src="https://user-images.githubusercontent.com/51922311/65161250-84f1b400-da37-11e9-9d38-5beeb4b433c8.png">

How can I check the log to fix this problem?

## Specifications

  - OpenMPTCProuter version: 0.49
  - OpenMPTCProuter VPS version: 0.9962
  - OpenMPTCProuter platform: x86_64

**Comment by Marctraider** [comment]
You run on old version?

**Comment by JorgeMoort89** [comment]
Yes, 0.49 on OMR and 0.9962 on VPS

**Comment by Ysurac** [comment]
I don't make support on old release.
Glorytun TCP seems to no be able to start, maybe a problem with your clone but it's not related to OpenMPTCProuter
