### ISSUE TITLE
what is the diff of  wizard   wan  wan1 wan2  interfae wan wan1 wan2

### ISSUE THREAD

**Issue by lloovve** [Ysurac/openmptcprouter#67]
i can understand the diff of  wizard   wan  wan1 wan2  interfae wan wan1 wan2.

is there any diff of that?

why wizard wan must need set ip? it can be dhcp?

**Comment by Ysurac** [comment]
What is the platform used ? on supported platform there is only wan1 and wan2.
You must set IP, you can use DHCP but you will need to use VLAN or connect directly to a port.
