### ISSUE TITLE
Suggestion - port forwarding par plage de ports

### ISSUE THREAD

**Issue by kyliane** [Ysurac/openmptcprouter#671]
Bonjour,

Actuellement dans la zone "Port Forwards" il n'est possible de rediriger les ports que un à un.

Dans mon cas, pour l'utilisation de 3CX (VoIP) j'ai besoin d'ouvrir une plage de ports allant de 9000 à 10999. Ouvrir ces ports un à un serait un enfer.

Est-ce possible de faire comme sur Pfsense par exemple et de permettre d'indiquer le port de début et de fin ? (voir screen ci-dessous)

![Unknown](https://user-images.githubusercontent.com/9253365/65349418-a099bd80-dbe3-11e9-8491-078cd7112710.png)

Merci.

**Comment by Ysurac** [comment]
C'est déjà possible : il suffit d'indiquer 9000-10999.
Pour la doc il faut aller voir du côté d'OpenWrt.
