### ISSUE TITLE
how to check why Glorytun Vpn dwon  

### ISSUE THREAD

**Issue by lloovve** [Ysurac/openmptcprouter#68]
![qq 20180526180027](https://user-images.githubusercontent.com/1198974/40574985-2712ddcc-60cc-11e8-97a5-f68c748899ad.jpg)

i am sure the key right

**Comment by Ysurac** [comment]
You can try to restart glorytun on the VPS.

**Comment by lloovve** [comment]
i wait some time , glorytun will connect.  i am no sure why

**Comment by Ysurac** [comment]
Because glorytun can take some times to connect ;)
