### ISSUE TITLE
Netflix omr-bypass

### ISSUE THREAD

**Issue by Bestle** [Ysurac/openmptcprouter#680]
## Expected Behavior

Enable omr-bypass for Netflix protocol and not have Netflix complain.

## Actual Behavior

I have been using omr-bypass with Netflix for about a month now and it has worked absolutely fine. Today however I got the proxy message and was unable to watch. I logged into my Netflix account and noticed that my VPS IP was in there for my latest attempt, but before it was always my WAN 1 IP.

## Steps to Reproduce the Problem

  1. Enable Netflix omr-bypass
  2. Attempt to watch Netflix
  3. *Sometimes* get message saying proxy detected and VPS IP is showing in Netflix account activity

## Specifications

  - OpenMPTCProuter version: v0.51.5
  - OpenMPTCProuter VPS version: 0.9962
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
Only OpenMPTCProuter IP is used as DNS ?
