### ISSUE TITLE
Google Cast don't work

### ISSUE THREAD

**Issue by zal31** [Ysurac/openmptcprouter#682]
Salut j'ai remis en place OMR chez moi la connexion marche bien (Routeur 4G vers un VPS dans le but d'avoir une ip fixe et m'auto-heberger).
Parcontre je ne peux plus caster de mon telephone vers ma télé android. Mon telephone ne detecte plus la tv comme google cast.
J'ai fouiller dans les options du parefeu sans resultat.

**Comment by Ysurac** [comment]
je ne connais, mais faut peut être voir du côté omr-bypass.
