### ISSUE TITLE
Haute disponibilité disponible ?

### ISSUE THREAD

**Issue by Slivikkus** [Ysurac/openmptcprouter#683]
## Question

Bonsoir j'aimerais savoir si il y a la haute disponibilité ?

**Comment by Ysurac** [comment]
On peut configurer plusieurs VPS et bien entendu plusieurs lignes qui sont par défaut en failover.

**Comment by Slivikkus** [comment]
Enfin je me suis mal exprimé je voulais dire si y'avais de la haute disponibilité point de vue interne ?

**Comment by Ysurac** [comment]
En interne des scripts tournent et relancent shadowsocks ou le VPN si ils sont down. Mais pas de vrai HA, pour ça il faudrait plutôt 2 routeurs pouvant se secourir, mais ce n'est pas prévu.

**Comment by Slivikkus** [comment]
Ah mince ça aurais été très pratique pour mes serveurs
