### ISSUE TITLE
can't get public IP address from shadowsocks

### ISSUE THREAD

**Issue by Yanaem** [Ysurac/openmptcprouter#685]
![can't get public ip](https://user-images.githubusercontent.com/43341980/66262006-41899a80-e7d8-11e9-96b9-37a46fefe806.png)
## Expected Behavior

No having this error.

## Actual Behavior

1) Is that a real problem? how to fix it ?

2) How can i use my Dyndns ? (is there somewhere to configure login/password) ?

## Specifications

  - OpenMPTCProuter version: (v0.52)
  - OpenMPTCProuter VPS version: (0.1001)
  - OpenMPTCProuter platform: RPI364)

**Comment by Ysurac** [comment]
1. Yes it's a problem. You should reboot the VPS, you are on a 4.14 kernel release...
2. You can install " luci-app-ddns" package, but with the VPS you should have a fixed IP. So why ?

**Comment by Yanaem** [comment]
1. Ok i reboot it , but the problem is still there now with two message. Maybe a problem with my keys?


![can't contact server](https://user-images.githubusercontent.com/43341980/66268470-e38f9e00-e83d-11e9-80a6-900db58741ac.png)
![can't get public ip adresss](https://user-images.githubusercontent.com/43341980/66268471-e38f9e00-e83d-11e9-8777-08bf6853cc85.png)

**Comment by Ysurac** [comment]
Yes, it can't contact admin script. "omr-admin" should be running on VPS side and key need to be correct.

**Comment by Yanaem** [comment]
Ok i checked the key , and all is good. 

I also checked the  /var/log/daemon.log. Maybe the error is there , take a look :
![authentification error](https://user-images.githubusercontent.com/43341980/66271283-822af780-e85c-11e9-80bf-d65beb402e32.png)

**Comment by Ysurac** [comment]
Yes it can't authenticate. You use another install of shadowsocks ? You should reinstall VPS.
