### ISSUE TITLE
Wan3 Gateway down alors qu'il fonctionne

### ISSUE THREAD

**Issue by simon88** [Ysurac/openmptcprouter#687]
Je vient d'installer openmtcprouter sur un raspberry 3, j'aggrège 3 modem OVH. Mon soucis est que mon WAN3 est indiqué comme gateway down, alors qu'il fonctionne, si je débranche mes 2 autres modem, j'ai toujours accès à internet alors que mes 3 modem sont indiqué comme étant down. De plus depuis le menu interface je vois bien le TX et RX du WAN3 évoluer
WAN3 est une interface que j'ai rajouté manuellement depuis l'onglet network -> interfaces. J'ai exactement les mêmes réglages que mes 2 autres WAN seulement l'adresse IP qui change.
Mes 3 modems ont les adresses IP statiques suivantes :
192.168.212.11
192.168.213.11
192.168.211.14

## Specifications
 
  - Kernel version 4.19.72
  Firmware openmptcprouter v0.52.3 r0+11006-713561a10b / LuCI Master (git-19.260.67281-bb408f2) 
  - OpenMPTCProuter platform: (Raspberry Pi 3 Model B Rev 1.2)

**Comment by Ysurac** [comment]
Le wan3 est donc bien un macvlan ?
Si le gateway est mis à down, c'est qu'OpenMPTCProuter ne peut pas pinger la passerelle en question.
Pourquoi avoir ajouter l'interface supplémentaire manuellement au lieu d'utiliser le wizard ?

**Comment by simon88** [comment]
> Le wan3 est donc bien un macvlan ?

Oui oui il est bien en macvlan sub interface et j'ai aussi assigné le wan3 à la zone wan.

> Pourquoi avoir ajouter l'interface supplémentaire manuellement au lieu d'utiliser le wiz

Je me suis peut être mal exprimé je pense que l'on parle de la même chose, je n'ai pas rajouté manuellement mon interface dans les fichiers deconf, j'ai tuilisé le bouton _Ajout d'une nouvelle interface_, disponible via ce lien http://192.168.100.1/cgi-bin/luci/admin/network/network, peut être que le soucis vient de ma box qui n'autorise pas le ping...

**Comment by Ysurac** [comment]
Non, je parle de système->openmptcprouter puis Assistant de configuration.
