### ISSUE TITLE
Aggregation speed less 

### ISSUE THREAD

**Issue by abhishek1390** [Ysurac/openmptcprouter#689]
## Expected Behavior
Aggregation speed should be sum of two ISP.

## Actual Behavior
We have connected two Huawei dongles. One is giving the speed around 5 to 6 Mbps, other is giving around 3 to 4 Mbps. But aggregated speed is not as expected, And in status page it is showing all green.And we are using Amazon Web server (AWS) as VPS. For getting more speed we have configured shadow socks encryption to 'none'.

![imageedit_2_4131724212](https://user-images.githubusercontent.com/36364769/66490581-04225700-eacf-11e9-957f-6032071b646c.png)

For reference attached the config file.
[config.txt](https://github.com/Ysurac/openmptcprouter/files/3707761/config.txt)

## Specifications

  - OpenMPTCProuter version: 0.52.3
  - OpenMPTCProuter VPS version: 0.999
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
What is the aggregated speed ?
What is the result of ```omr-test-speed wan1```, ```omr-test-speed wan2``` (replace wan1 and wan2 by real device name, check that using ```ip a```) and the aggregated speed ```omr-test-speed``` ?

**Comment by abhishek1390** [comment]
Here it is...

![oie_g8dx5K9hGBXr](https://user-images.githubusercontent.com/36364769/66542308-e0ebbc00-eb4f-11e9-8d12-144882474bd4.png)

![oie_Dow3zKPLXytZ](https://user-images.githubusercontent.com/36364769/66542328-f234c880-eb4f-11e9-8fe7-0c4dfaffe8ad.png)

**Comment by Ysurac** [comment]
Not really good...
You can try to disable fast-open.
You can also try another TCP congestion control in the Network->MPTCP interface.

**Comment by abhishek1390** [comment]
"fast-open" is enabled on all shadowsocks instance,
Should i disable all?

**Comment by Ysurac** [comment]
Yes, or use checkbox in System->OpenMPTCProuter and Advanced settings tab.

**Comment by abhishek1390** [comment]
ok will try and get back to you. Thanks for quick response.

**Comment by abhishek1390** [comment]
I am getting this error continuously while testing the speed. What does this mean? 
Sometimes this error comes on both interface and VPN tunnel will also be down. 

![oie_O6MnOITzzZXR](https://user-images.githubusercontent.com/36364769/66626309-64231580-ec15-11e9-9447-29bd70ddcf1f.png)

And i have changed the VPS to OVH.

**Comment by Ysurac** [comment]
It means that server doesn't answer to ping in less than 1 second.
I think there a big latency between the server and you.

**Comment by abhishek1390** [comment]
Is this reason VPN tunnel becoming down?
Can i increase that 1 second?

**Comment by Ysurac** [comment]
The 1 seconds is only for status page, it's not a real problem.
If you really want to change it, via SSH on the router:
```
uci set openmptcprouter.settings.status_vps_timeout='10'
uci set openmptcprouter.settings.status_getip_timeout='10'
uci commit openmptcprouter
```

But you should check system log, to see what is the real problem.

**Comment by abhishek1390** [comment]
As i understand omrvpn is getting down..What can be the reason?
Attached the logfile
[log.txt](https://github.com/Ysurac/openmptcprouter/files/3716048/log.txt)

Can you see what could be problem? And after disabling `fast-open` in shadowsocks instances i am not seeing any significant difference in speed.
