### ISSUE TITLE
how to test MPTCP working 

### ISSUE THREAD

**Issue by lloovve** [Ysurac/openmptcprouter#69]
![qq 20180526233521](https://user-images.githubusercontent.com/1198974/40577807-9c1fffe0-60fa-11e8-86e1-df1e15e0d6d1.png)

My router state 

but when i broke up one of them (wan or lte)  ,my voip voice will need some time to continue.
is that mptcp no working?

**Comment by Ysurac** [comment]
There is no gateway defined for lte. Are you sure it's the correct settings ?
VoIP use UDP, so it use glorytun by default, that do UDP over TCP. It's not really the best test for MPTCP...
