### ISSUE TITLE
OMR-Bypass for airlines compagny

### ISSUE THREAD

**Issue by Scaff31** [Ysurac/openmptcprouter#690]
## Expected Behavior

Acces website for airlines compagny (easyjet, airfrance, etc...)

## Actual Behavior

Access denied

## Steps to Reproduce the Problem

  1. try to navigate on www.airfrance.fr
  2. on omr-bypass add airfrance.fr / airfrance.com / klm.com 
  3. try to reserve on website

## Specifications

  - OpenMPTCProuter version: 0.52.3
  - OpenMPTCProuter VPS version: 0.1001
  - OpenMPTCProuter platform: RPI3 + ESXI

**Comment by Ysurac** [comment]
You have problem on access or when you want to pay or at another step ?
You need to find what domain block your VPS IP using the developer mode of your browser.

**Comment by Scaff31** [comment]
Problem for accessing, without OMR-Bypass reservation form not load and with omr-bypass loading can be use but when you want click on search you get and denied access

**Comment by Ysurac** [comment]
What is the VPS provider ?
Do you have an example of public URL that fail ?

**Comment by Scaff31** [comment]
ovh

wwws.airfrance.fr

**Comment by Scaff31** [comment]
Ok i think i've found solution with multiple domains ans subdomains trying 
![omr-bypass](https://user-images.githubusercontent.com/16442430/66598821-2c2eba80-eba2-11e9-9a3a-0200e7cb0d3f.png)

**Comment by Ysurac** [comment]
subdomains are bypassed when domain is set. But you may have also static-kl.com and some others.
Fun: IPs from firstheberg and OVH are blocked but not scaleway and Vultr.

**Comment by Scaff31** [comment]
Great info for IP pool
