### ISSUE TITLE
Wifi error message while Wifi card shall be disabled

### ISSUE THREAD

**Issue by ragefan** [Ysurac/openmptcprouter#694]
## Expected Behavior

Raspberry PI 3B+ wifi card is disabled in the GUI but still spamming messages in logs :

[705680.796418] ieee80211 phy0: brcmf_cfg80211_dump_station: BRCMF_C_GET_ASSOCLIST unsupported, err=-110
[705689.814196] ieee80211 phy0: brcmf_proto_bcdc_query_dcmd: brcmf_proto_bcdc_msg failed w/status -110
....

Impact is unknown.

## Actual Behavior

Wifi errors while Wifi is disabled. Spam in the logs, prevents real errors if any to be shown

## Steps to Reproduce the Problem

  1. Boot on Raspberry pi3B +
  2. Wait 

## Specifications

  - OpenMPTCProuter version: 0.52.3
  - OpenMPTCProuter VPS version: 0.999
  - OpenMPTCProuter platform: RPI3B+

**Comment by Ysurac** [comment]
No real impact I think. This is here since a long time, I think there is already an issue about that.
