### ISSUE TITLE
kmod-usb3 problem

### ISSUE THREAD

**Issue by bournehlm** [Ysurac/openmptcprouter#696]
## Expected Behavior

  It seems the kmod-usb3 packet have problem in rpi2/rpi4/bpi-r2, the size is only 848Bytes, and after install with opkg, there is no ko model in it.
  It's ok for the bpi3 image.

## Specifications

  - OpenMPTCProuter version: (0.52.3)
  - OpenMPTCProuter VPS version: ()
  - OpenMPTCProuter platform: (RPI2/RPI4/BPI-R2)

**Comment by Ysurac** [comment]
You can test with v0.53, if this still doesn't work you can reopen this issue.
