### ISSUE TITLE
Test MLVPN over MPTCP

### ISSUE THREAD

**Issue by Ysurac** [Ysurac/openmptcprouter#70]
Using https://github.com/markfoodyburton/MLVPN/tree/new-reorder
Need to make a package and LuCI interface if it's working well.

**Comment by aredan** [comment]
I was thinking of using MLVPN but read a lot about it and it has a few issues, there is not much activity on the GitHub issues page. 

What are you planning to replace with MLVPN?
Will it be an interchangeable option with Glorytun for example?

I'm looking for a way to use three internet connections (2 x Fiber + 1backup 3G USB) changing the less of internal routing of my network.

**Comment by Ysurac** [comment]
I will make some tests/benchmarks, and if it's usable, this will be interchangeable with Glorytun TCP/UDP.
It's only a test for now.

**Comment by Ysurac** [comment]
MLVPN support is added in latest release. Mark Foody Burton version crash on RPI, will try to investigate that later.

**Comment by aredan** [comment]
I will update to this version to test MLVPN, I'm running on x86_64.

**Comment by nileio** [comment]
can someone report results of using MLVPN instead of glorytun ?

**Comment by Ysurac** [comment]
Master tree use Markfoodyburton MLVPN version. It's working better than previous version but it's still slower than ShadowSocks with MPTCP.

**Comment by beyondhong** [comment]
Hi @Ysurac ,
I tested the MLVPN, using two 4G modules, but it's not working good. Link aggregation did not take effect. It's even worse than single link. I opened an issue here:
https://github.com/zehome/MLVPN/issues/121
Have you got any suggestion? Thanks!

**Comment by Ysurac** [comment]
I'm using https://github.com/markfoodyburton/MLVPN/tree/new-reorder fork in OpenMPTCProuter, but as I said I don't find the result really good.

**Comment by beyondhong** [comment]
> I'm using https://github.com/markfoodyburton/MLVPN/tree/new-reorder fork in OpenMPTCProuter, but as I said I don't find the result really good.

Yeah I'm using that version too. Now I'm trying to test Glorytun, so how will I start with it?
I am testing on a mtk(mt7620) router running dd-wrt.

**Comment by Neustradamus** [comment]
Any news?

**Comment by Neustradamus** [comment]
@Ysurac: It is solved?

**Comment by Ysurac** [comment]
Yes it's solved: MLVPN is no more used.
Too many crash, not usable anymore.
