### ISSUE TITLE
Assigner un VLAN a l'interface WAN

### ISSUE THREAD

**Issue by Scaff31** [Ysurac/openmptcprouter#707]
## Expected Behavior

  Mon ESXI + mon switch tag le WAN1 en 8 le WAN2 en 9 et le LAN en 10, j'aimerais pouvoir dire aux interfaces WAN de l'OMR d'intercepter les trames tagué en 8 et 9 et de tagué LAN en 10

@Ysurac si jamais tu as une doc à me fournir ou une piste à suivre pour y arriver

## Specifications

  - OpenMPTCProuter version: 0.52.3
  - OpenMPTCProuter VPS version: 1001
  - OpenMPTCProuter platform: ESXI, raspberry

**Comment by Ysurac** [comment]
Il faut voir au niveau de la doc d'OpenWrt.
