### ISSUE TITLE
More than 8 wans?

### ISSUE THREAD

**Issue by jordan-richardo** [Ysurac/openmptcprouter#708]
Hello there,

I am just wondering if there is a way of doing more than 8 WAN's and what the limitation might be caused by? 

## Expected Behavior

  In English please.

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - OpenMPTCProuter version: (Last is not a version)
  - OpenMPTCProuter VPS version: (Last is not a version)
  - OpenMPTCProuter platform: (RPI2/RPI3/x86/x86_64)

**Comment by Ysurac** [comment]
It's a limit in MPTCP, that is used by default.
With MPTCP disabled, Glorytun UDP may not have such limit.

**Comment by jordan-richardo** [comment]
Interesting, thank you for getting back to me :)
