### ISSUE TITLE
After ifup command executed the OpenWRT apps lost permitions

### ISSUE THREAD

**Issue by LovingFox** [Ysurac/openmptcprouter#709]
## Expected Behavior

After execution "ifup" OpenWRT applications continue to communicate to the remote hosts successful.

## Actual Behavior

Some applications (for example logread) lost some any permissions and stop sending anything.

## Steps to Reproduce the Problem

  0. load OMR to the working state
  1. try to send logs to the some any host
`/sbin/logread -f -h client1 -r 10.8.0.1 514 -p /var/run/logread.2.pid -u`
Success. Log messages are sent via udp and received on the target.
  2. stop "logread" (Ctrl-C)
  3. just do this
`ifup -a`
  4. try to send logs to the some any again
```
root@client1:~# /sbin/logread -f -h client1 -r 10.8.0.1 514 -p /var/run/logread.2.pid -u
failed to connect: Permission denied
failed to connect: Permission denied
failed to connect: Permission denied
...
```
Failed. Something happened and some any permissions lost. It's not firewall. You can stop it at all (/etc/init.d/firewall stop) or change remote host to which you definitely have access, and got the same. I guess applications lost some kind of "system permissions".
If you send message by "nc" like this:
`nc -u 10.8.0.1 514`
 got success.
## Specifications

  - OpenMPTCProuter version: v0.52.3-5
  - OpenMPTCProuter VPS version: I guess doesn't matter really
  - OpenMPTCProuter platform: I guess doesn't matter really

```
root@client1:~# cat /etc/openwrt_release 
DISTRIB_ID='openmptcprouter'
DISTRIB_RELEASE='v0.52.3-5-g6f9cd2d'
DISTRIB_REVISION='r0+11006-713561a'
DISTRIB_TARGET='mediatek/mt7622'
DISTRIB_ARCH='aarch64_cortex-a53'
DISTRIB_DESCRIPTION='openmptcprouter v0.52.3-5-g6f9cd2d r0+11006-713561a'
DISTRIB_TAINTS='busybox override'

root@client1:~# uname -a
Linux client1 4.19.72 #0 SMP Fri Sep 13 14:40:29 2019 aarch64 GNU/Linux


```

**Comment by Ysurac** [comment]
You can test with v0.53, if this still doesn't work you can reopen this issue.
