### ISSUE TITLE
tun0 not appearing as a MPTCP interface although has multipath enabled.

### ISSUE THREAD

**Issue by Llorx** [Ysurac/openmptcprouter#710]
In the latest version, if I create a `tun0` device (bond to `eth2`) with a static IP in OpenVPN and `multipath` set to `on`, it don't appears in the main status section, and is not used as MPTCP routing. `bmon` shows no traffic when testing MPTCP connections.

`tun0` is MTCP capable, tested with `curl http://multipath-tcp.org/ --interface tun0`, but router status shows only one router (which is `eth1`):
![image](https://user-images.githubusercontent.com/702490/67700790-e863ef80-f9ae-11e9-92bc-d64049d95566.png)

But I think that everything is fine configured:
![image](https://user-images.githubusercontent.com/702490/67700876-19dcbb00-f9af-11e9-8713-fce45bee496c.png)

ifconfig result:
![image](https://user-images.githubusercontent.com/702490/67700918-311ba880-f9af-11e9-9231-22e67c776f65.png)

The MAC is 00:00:00... altough I forced it, so I don't know if this is the problem actually.

**Comment by Llorx** [comment]
Ok, setting a `tap` instead of `tun` it works.

**Comment by Ysurac** [comment]
Tun0 is already used as internal VPN.
But I think interface will not be used in MPTCP routing, at least not like a classic WAN. MPTCP over VPN is available (in alpha state) in current snapshot release: https://github.com/Ysurac/openmptcprouter/wiki/Snapshots

**Comment by Llorx** [comment]
Woah, nice.
