### ISSUE TITLE
VPS server could not be installed

### ISSUE THREAD

**Issue by hljsykj** [Ysurac/openmptcprouter#718]
VPS server can't be installed. I tried several times, but it didn't work

**Comment by hljsykj** [comment]
![12121](https://user-images.githubusercontent.com/54393248/68181551-c67ff380-ffd2-11e9-8f57-e026ffb18a6c.JPG)

**Comment by Ysurac** [comment]
It can't download ```https://github.com/shadowsocks/shadowsocks-libev/releases/download/v3.3.1/shadowsocks-libev-3.3.1.tar.gz```. What is your VPS provider ?

**Comment by hljsykj** [comment]
Alibaba cloud server can be installed before, but it can't be installed recently

**Comment by hljsykj** [comment]
Alibaba cloud server

**Comment by Ysurac** [comment]
You can try to ```wget https://github.com/shadowsocks/shadowsocks-libev/releases/download/v3.3.1/shadowsocks-libev-3.3.1.tar.gz``` and ```tar xzvf shadowsocks-libev-3.3.1.tar.gz```. You should have the same error...
Else maybe a cache/network/GFW error.

**Comment by suyuan168** [comment]
> 阿里云服务器

阿里云目前大多数无法访问shadowsock-libev。你可以尝试其他的运营商。但是目前在中国好像有GFW阻止安装这些软件。
