### ISSUE TITLE
very low speed

### ISSUE THREAD

**Issue by imercier** [Ysurac/openmptcprouter#719]
## Expected Behavior
omr-test-speed ~20MB/s

## Actual Behavior
omr-test-speed ~500KB/s
omr-test-speed wan1 ~10MB/s
omr-test-speed wan2 ~10MB/s

## Steps to Reproduce the Problem

![Capture d’écran du 2019-11-05 18-04-05](https://user-images.githubusercontent.com/7894484/68229066-d3aed980-fff6-11e9-9c3e-4d9b7219bcf4.png)

## Specifications

  - OpenMPTCProuter version: (v0.52.3 r0+11006-713561a10b)
  - OpenMPTCProuter VPS version: (0.1001)
  - OpenMPTCProuter platform: (RPI4)

I've tried to enable/disable *vpn, ShadowSocks.
rpi4 cpu is quite idle when testing.
config file attached.
[config.txt](https://github.com/Ysurac/openmptcprouter/files/3810280/config.txt)

thank you for your help

**Comment by Roken120** [comment]
I have same problem with OVH vps

**Comment by Roken120** [comment]
Maybe i dont use rpi4 i use vm

**Comment by Ysurac** [comment]
You can try to disable fastopen and to set lower MTU

**Comment by imercier** [comment]
I can't disable fast open, when I apply disable option, tick disapear in web interface, and config stay 1:
`shadowsocks-libev.hi1.fast_open='1'
`
Setting all wan interfaces at mtu 1350 doesn't help either.

**Comment by Ysurac** [comment]
True there a bug on interface to disable fast open, it's fixed in develop branch for next release.
I have no idea for now. Did you try to reinstall both ?

**Comment by imercier** [comment]
so how can I disable fast open?
yes I did try reinstall from scratch both.
BTW, overthebox is working properly

**Comment by Ysurac** [comment]
```sysctl -w net.ipv4.tcp_fastopen=0```
You can also disable fastopen on shadowsocks luci interface.
