### ISSUE TITLE
Add possibility to change IP of openmptcprouter

### ISSUE THREAD

**Issue by constant1010** [Ysurac/openmptcprouter#72]
Is possible to add possibility to change IP of router?

It would be practical to have file in .txt on /boot partition with adress ip of router to set, and I just thought why not shadowsocks key ,glorytun key, wan adress, etc.

**Comment by Ysurac** [comment]
You can change IP in **Network->Interfaces**.
I can't really see a case why it would be practical to have a file in /boot. All configuration is in **/etc/config/**.

**Comment by constant1010** [comment]
It would be practical, when you just flash sd card, you don't must to change IP of device to set up IP of router.
There is IP of **Port Redirection** to change, is there other parameter?

**Comment by Ysurac** [comment]
You can have multiple IP on an interface, if you really don't want that you can edit /etc/config/network on the sd card.
In next release no parameters will need to be changed after IP change.
