### ISSUE TITLE
Multiple VPS

### ISSUE THREAD

**Issue by Roken120** [Ysurac/openmptcprouter#723]
Hello,
I have one question is possible to use multiple vps ?

**Comment by Roken120** [comment]
If yes can you explain how to use multiple vps ?

**Comment by Ysurac** [comment]
Yes it's possible.
You have to run the install script on each VPS and to add them via the Wizard in OpenMPTCProuter.

**Comment by Roken120** [comment]
for the part installations on the vps it is good. but how should I do for the wizard.

**Comment by Ysurac** [comment]
You have a "add a server" button, you enter a name and click on this button.

**Comment by Roken120** [comment]
Ok, is done, Maybe i can active on the two VPS the port forwarding ? (like two vps is master)

**Comment by Ysurac** [comment]
No you can't. Port forwarding use the VPN, the VPN can't connect to the two VPS at the same time.

**Comment by flapvhd** [comment]
What is the purpose of adding many servers?

**Comment by Ysurac** [comment]
For VPS failover. If a VPS fail, then a backup VPS is used.
