### ISSUE TITLE
Changing Interfaces

### ISSUE THREAD

**Issue by Bestle** [Ysurac/openmptcprouter#724]
## Expected Behavior

To be able to reboot the router without interfaces changing.

## Actual Behavior

I currently use USB -> Ethernet dongles to supply my connection and have noticed that on reboot, the assignment order is pretty much random.

This means that if I configure eth3 to MPTCP master (which is my strongest connection), on reboot this connection could get assigned to eth1 and now my weakest connection is the master. Same issue with omr-bypass.

**Comment by kevin39** [comment]
See https://unix.stackexchange.com/questions/66901/how-to-bind-usb-device-under-a-static-name
