### ISSUE TITLE
Public MPTCP graph

### ISSUE THREAD

**Issue by JorgeMoort89** [Ysurac/openmptcprouter#727]
Hi,
how can I have public MPTCP graph?

I've tried adding new file in /usr/lib/lua/luci/controller/ but is not working, if I add the module luci.controller.public_stats it ask me for the admin password and I want that graphs public

```
module("luci.controller.mptcp", package.seeall)

function index()
    assign({"bandwidth"}, {"admin", "network", "mptcp", "bandwidth"}, nil)
end
```

**Comment by PRO2XY** [comment]
I am running after this too. Could you work it out?

**Comment by JorgeMoort89** [comment]
Sadly no, I've created this but is not working without admin login

bandwidth.lua

module("luci.controller.bandwidth", package.seeall)

function index()
    assign({"bandwidth"}, {"admin", "network", "mptcp", "bandwidth"}, nil)
end
