### ISSUE TITLE
Petite question technique (AS)

### ISSUE THREAD

**Issue by Slivikkus** [Ysurac/openmptcprouter#729]
## Question

Bonsoir, j'ai juste une simple question (vu que je suis un noob en réseau) et que je vais avoir un AS y'a la possibilité de relié l'AS (enfin les groupes d'ip) au routeur ou c'est encore plus complexe que ça ?

**Comment by Ysurac** [comment]
Ce n'est pas si simple que ça, mais je crois qu'il y a déjà une issue sur le sujet que je n'arrive pas à retrouver pour le moment.

**Comment by Slivikkus** [comment]
Ok :)

**Comment by flapvhd** [comment]
Le bloc d'IP que tu vas utiliser est annoncé par qui?

**Comment by Slivikkus** [comment]
C'est à dire ?

**Comment by flapvhd** [comment]
Le bloc d'IP qui va être associé a ton AS doit être annoncé sur internet par un routeur qui parle BGP.
Qui fait cette annonce? Car c'est depuis c'est ce routeur qui pourra router ces IP vers ton VPS, par un tunnel VPN ou autre...

**Comment by Slivikkus** [comment]
Aucune idée
