### ISSUE TITLE
How to make a DMZ ?

### ISSUE THREAD

**Issue by dougalito** [Ysurac/openmptcprouter#73]
Hi, 

I use since few month OpenMPTCPouter and i would like to know haow to configure MPTCP for a DMZ.

There is a line by default on it ...
Redirect-VPN-to-LAN --- any host in lan

So what should i do to configure a DMZ ?

thanks a lot

**Comment by Ysurac** [comment]
OpenMPTCProuter use OpenWRT, so you can follow OpenWRT documentation about this: https://wiki.openwrt.org/doc/howto/dmz
You only need to use the VPN zone as data source.

**Comment by dougalito** [comment]
thanks
