### ISSUE TITLE
Question: Accès à distance via VPN

### ISSUE THREAD

**Issue by anglepoise86** [Ysurac/openmptcprouter#737]
## Expected Behavior
Bonjour,

Tout d'abord je voudrais vous remercier pour tous les efforts que vous déployez pour nous proposer et maintenir OpenMPTCProuter.

J'ai une question concernant l'accès à distance: est-il possible de se connecter au réseau local de l'extérieur via VPN ? Si oui, le fonctionnement est-il similaire aux outils VPN classiques (tels qu'OpenVPN) nécessitant un certificat/clé privée ?

J'ai vu qu'il y avait une rubrique d'aide intitulée "VPN over OpenMPTCProuter" mais je n'ai malheureusement pas pu aller plus loin.

Merci d'avance.

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - OpenMPTCProuter version: 0.51.5
  - OpenMPTCProuter VPS version: 0.999 4.19.56-mptcp
  - OpenMPTCProuter platform: RPI3

**Comment by Ysurac** [comment]
OpenVPN peut être installé et configuré sur OpenMPTCProuter en mode serveur. Donc en redirigeant les ports du VPS vers OpenMPTCProuter ça fonctionnera.
