### ISSUE TITLE
Question: Raspberry Pi Zero WH Support possible?

### ISSUE THREAD

**Issue by Wlanfr3ak** [Ysurac/openmptcprouter#741]
## Expected Behavior

  Usage of a Raspberry Pi Zero WH

## Actual Behavior
Dont boot from openmptcprouter image, no HDMI only Black, with Raspbian no Problem

## Steps to Reproduce the Problem

  1. Image on microSD 1
  2. Try to boot from microSD 1
  3. Try with Raspbian and it works

## Specifications

  - OpenMPTCProuter version: (openmptcprouter-v0.52.3)
  - OpenMPTCProuter VPS version: (-)
  - OpenMPTCProuter platform: (RPI Zero WH)

**Comment by Ysurac** [comment]
It's a bcm2708. Too slow to be supported. You can compile it yourself if you really want to...
