### ISSUE TITLE
Question: usb hotspots with same Lan-subnet

### ISSUE THREAD

**Issue by rajeevkk32** [Ysurac/openmptcprouter#743]
I have USB-hotspots (4G USB dongle hotspots)
They are locked by the operator with Local IP & subnet.
IP:192.168.1.1
sn: 255.255.0.0

Can I connect multiple devices with the same IP as WAN inputs for the router device?
I am using raspberry pi 3 as the router.

**Comment by Wlanfr3ak** [comment]
Yes, i use 3 Huawei e3372 with the IP-Range: 192.168.8.1/24 and DHCP-Client at the MPTCP-Router at the same time and every ip is the same.

**Comment by Olli69** [comment]
@Wlanfr3ak , did you re-flash e3372 or had to do any other tricks? I'm just trying to get 2 e3372 up with .55beta15 and RPI4 , but it just got eth1 up, no eth2.
