### ISSUE TITLE
Question : When VPS is down no failover i lost internet connection what to check or do ?

### ISSUE THREAD

**Issue by laclastre31** [Ysurac/openmptcprouter#751]
Hello,
thanks for this beautiful (yes!) pakage i used now since 9months...

## Expected Behavior
VPS down or not answering = failover setting to provide access to internet through one of the boxes (wan1 or wan2) then come back to normal setting when vps is up/answering again

## Actual Behavior
VPS down or not answering = no internet any more! (firstheberg)
work arround = shut down RPI3 and turn on dhcp of one box... waiting vps up again to swith back to normal config...

## Steps to Reproduce the Probleme

  1. Sorry i don't know how to reproduce firtheberg.com vps problem of no answering or desynchronisation but not the same than simply remove the server setting in RPI3web interface (in that case internet is ok)
 
## Specifications

  - OpenMPTCProuter version: openmptcprouter-v0.52.3-r011006-713561a10b-brcm2708-bcm2710-rpi-3-ext4-factory.img 
  - OpenMPTCProuter VPS version: OpenMPTCProuter VPS 0.1001 (run update script the 01/12/2019) VPS on FirstHeberg.com
  - OpenMPTCProuter platform: RPI3

thank you,
Stéphane

**Comment by Ysurac** [comment]
Ping is working or not ? What do you have in system log in this case ?
