### ISSUE TITLE
Port forwarding don't work after modification of defaut IP

### ISSUE THREAD

**Issue by buseoti** [Ysurac/openmptcprouter#754]
Hi,

By default when i want use port forwarding it's ok with defaut ip of Openmptcrouter : 192.168.100.1 

I need modify the ip of openmptcrouter, so after this modification, the forwarding port don't work, i don't know where find the solution ????

Thx
Frédéric

**Comment by Ysurac** [comment]
You can test with v0.53, if this still doesn't work you can reopen this issue.

**Comment by zicochaos** [comment]
have same problem. version v0.53.3
