### ISSUE TITLE
openmptcprouter VPS installation error

### ISSUE THREAD

**Issue by 8252610** [Ysurac/openmptcprouter#757]
## Expected Behavior

When running the wget -O - http://www.openmptcprouter.com/server/ubuntu18.04-x86_64.sh | sh
Error occurred
/tmp/shadowsocks-libev-3.3.3.tar 100%[==========================================================>] 1.84M 13.9KB/s in 2m 45s

2019-12-22 11:36:05 (11.4 KB/s) - '/tmp/shadowsocks-libev-3.3.3.tar.gz' saved [1930597/1930597]

--2019-12-22 11:36:05-- https://raw.githubusercontent.com/Ysurac/openmptcprouter-feeds/master/shadowsocks-libev/patches/020-NOCRYPTO.patch
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.228.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.228.133|:443... failed: Connection refused.

My server is alicloud China

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - OpenMPTCProuter version: (Last is not a version)
  - OpenMPTCProuter VPS version: (Last is not a version)
  - OpenMPTCProuter platform: (RPI2/RPI3/x86/x86_64)

**Comment by Ysurac** [comment]
Run it again.
Having a mirror for Asia is in todo list.

**Comment by 8252610** [comment]
thank you
Every time I run, I pray to my God Monkey King
But I've run it 10 times

**Comment by 8252610** [comment]
![微信截图_20191222150820](https://user-images.githubusercontent.com/58301698/71318549-2bcd6c80-24cd-11ea-82ad-75b1ef5c68e4.png)
当我运行乌班图脚本
My operating system Ubuntu 18.04

**Comment by Ysurac** [comment]
I don't see any error here.

**Comment by 8252610** [comment]
It's been on this screen for an hour
I'm installing Python 3.7 for the system and running the script

**Comment by 8252610** [comment]
![微信截图_20191222150820](https://user-images.githubusercontent.com/58301698/71319128-178d6d80-24d5-11ea-96f0-d4d92ca911e7.png)
Error after waiting

**Comment by 8252610** [comment]
![微信截图_20191222150820](https://user-images.githubusercontent.com/58301698/71319141-44da1b80-24d5-11ea-8af7-691ded17e0d8.png)
Error after waiting

**Comment by 8252610** [comment]
![微信截图_20191222150820](https://user-images.githubusercontent.com/58301698/71319313-9edbe080-24d7-11ea-94ed-1ac503758a65.png)
I am ready to replace the local operating system test

**Comment by Ysurac** [comment]
Compiler is killed, check using dmesg why. Maybe a VPS limit.

**Comment by suyuan168** [comment]
hi, 
First, you have to solve your network restrictions. Networks in China do not support shadowsocks. Then you have to check the system for environmental problems. Follow the installation tutorial. Then check your system log and resolve it.

**Comment by 8252610** [comment]
YES, 
I can't speak English. The baidu translation I use may have grammar problems
My purchase of alicloud's French VPS solves the problem of shadowlocks
Now we are solving the environment problem of Alibaba cloud Ubuntu system
My server in Amazon can complete VPS installation
thank you

**Comment by 8252610** [comment]
I successfully installed VPS
Purchase VPS system is Debian 9 (operators do not have Debian 10) and upgrade to Debian 10
Run debian10 VPS installation script
Thank you, author. You're so good

**Comment by diogosilvan** [comment]
Exact same error here. Debian 10 and Ubuntu 18.04 LTS same error.
Problem present in Vultr and Locaweb (in Brazil)

**Comment by Ysurac** [comment]
What is the error ? A "connection refused" to some Github hosted content ?

**Comment by diogosilvan** [comment]
> What is the error ? A "connection refused" to some Github hosted content ?

 Failed building wheel for uvloop
  Running setup.py clean for uvloop
...
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-t09g_o3_/uvloop/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ssgnw5sy/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-t09g_o3_/uvloop/

**Comment by Ysurac** [comment]
With a killed compiler before that ? Check with ```dmesg``` why it's killed.

**Comment by diogosilvan** [comment]
> With a killed compiler before that ? Check with `dmesg` why it's killed.

dmesg does not provide any information about the compiler.
The problem is not directly in the MPTCP installation script.
In a newly installed VPS (installed only the tools needed for python) I try to install "pip3 install uvloop" I have the same error.

**Comment by diogosilvan** [comment]
Solved, the problem was low memory that was killing the compiler.
On a 512MB RAM machine it doesn't work anymore, only on 1GB above.

**Comment by taojiji** [comment]
我也是遇到同一个问题，阿里云主机

**Comment by taojiji** [comment]
I have the same problem, aliyun host
