### ISSUE TITLE
Portforwarding v0.53

### ISSUE THREAD

**Issue by rubaz100** [Ysurac/openmptcprouter#758]
## Expected Behavior

SNAT is in the WEB interface

## Actual Behavior

I can not see any SNAT settings.
![screencapture-192-168-100-1-cgi-bin-luci-admin-network-firewall-rules-2019-12-22-15_47_54](https://user-images.githubusercontent.com/33371370/71323361-81f0de80-24d2-11ea-9def-90aff989bd12.png)

## Steps to Reproduce the Problem

https://github.com/Ysurac/openmptcprouter/wiki/Port-forwarding

## Specifications

  - OpenMPTCProuter version: (0.53)
  - OpenMPTCProuter VPS version: (0.1005)
  - OpenMPTCProuter platform: (WRT3200ACM)

**Comment by zicochaos** [comment]
same problem on x64

**Comment by Ysurac** [comment]
I make a new SNAT section in 0.53.3
