### ISSUE TITLE
Dhcp add static Lease

### ISSUE THREAD

**Issue by flimo44** [Ysurac/openmptcprouter#759]
Impossible to add new Static Lease IP 

## Steps to Reproduce the Problem

  1. DHCP DNS -> Static Release and ADD
  2. when a clic Save Nothing do : ( Roue qui tourne sur le bouton san fin )
  3. 

## Specifications

  - OpenMPTCProuter version: 0.53
  - OpenMPTCProuter VPS version:0.1005
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
It's a know issue from OpenWrt, a new updated image will be available soon.

**Comment by flimo44** [comment]
Thank you.

**Comment by Ysurac** [comment]
Fixed in v0.53.1 now available.
