### ISSUE TITLE
omr-bypass for all UDP traffic

### ISSUE THREAD

**Issue by Bestle** [Ysurac/openmptcprouter#769]
How do I enable omr-bypass for all UDP traffic? It doesn't come up in the list of protocols.

**Comment by Ysurac** [comment]
You can't, but you can disable VPN and use shadowsocks only for TCP traffic.

**Comment by max4186** [comment]
I do this actively, disabling the VPN and using Shadowsocks only does the trick.

**Comment by Bestle** [comment]
Yeah I'm having the issue you had @max4186. When playing games (UDP), I get crazy ping fluctuations when someone else on the network is downloading or watching YouTube.

The bandwidth they are using is nowhere near my box and neither the router nor VPS are constrained for resources, it's very odd.

**Comment by max4186** [comment]
Mine was worst when watching any kind of video, like 2000ms ping. Luckily, just disabling the VPN has solved that problem entirely :)

**Comment by Bestle** [comment]
Hopefully @Ysurac can fix the route cause, but will try that workaround in the meantime.

**Comment by Ysurac** [comment]
There is SQM and you can choose between multiple VPN.

**Comment by Bestle** [comment]
I get the same issue with other VPN. I currently use 4G connections with variable speeds so can't really use SQM.

Disabling the VPN completely fixes the issue, but surely that means it isn't an issue that can be fixed with SQM?

**Comment by Bestle** [comment]
@Ysurac Which WAN is selected for traffic if VPN is off?

**Comment by max4186** [comment]
The master multipath wan, so probably wan1 @Bestle

**Comment by Bestle** [comment]
So with VPN disabled, UDP (game) traffic is flawless with no fluctuations in ping when watching a youtube video at the same time.
