### ISSUE TITLE
USB 3G support?

### ISSUE THREAD

**Issue by aredan** [Ysurac/openmptcprouter#77]
## Expected Behavior

plug and play USB 3G/4G support.

## Actual Behavior

There is no new interface for the USB 3G modem that was plug-in.

## Steps to Reproduce the Problem

  1. a previous OpenWRT working USB 3G modem.
  2. Check for new interface in OMR.
  

## Specifications

  - OpenMPTCProuter version: 0.21
  - OpenMPTCProuter VPS version: 0.20
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
luci-proto-3g is installed by default in latest OMR release
