### ISSUE TITLE
Impossible de mettre le VPS à jour

### ISSUE THREAD

**Issue by Randdrick** [Ysurac/openmptcprouter#772]
Impossible de mettre à jour le VPS en version 0.1006 depuis mon VPS

Dernière lignes avant l'arrêt de la mise à jour du script : 

usermod: no changes
install mlvpn done
Install OpenVPN
Reading package lists... Done
Building dependency tree
Reading state information... Done
easy-rsa is already the newest version (3.0.6-1).
openvpn is already the newest version (2.4.7-1).
The following packages were automatically installed and are no longer required:
  g++-6 guile-2.0-libs irqbalance libbind9-140 libdbus-glib-1-2 libdns162
  libicu57 libirs141 libisc160 libisccc140 libisccfg140 liblwres141
  libmbedcrypto0 libmbedtls10 libnuma1 libperl5.24 libpython3.5
  libpython3.5-dev libpython3.5-minimal libpython3.5-stdlib libstdc++-6-dev
  linux-image-4.9.0-11-amd64 linux-image-4.9.0-8-amd64 python3-pyasn1
  python3.5 python3.5-dev python3.5-minimal rsync runit-helper tcpd
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
cp: cannot create regular file '/etc/openvpn/ca/pki/ca.crt': No such file or directory

**Comment by Ysurac** [comment]
Fixed in latest script release.
