### ISSUE TITLE
[Question] Traffic routing for a specific IP over a specific WAN interface

### ISSUE THREAD

**Issue by anglepoise86** [Ysurac/openmptcprouter#780]
## Expected Behavior
Hello,

First, happy new year to all !

Is it possible to route all traffic for a specific IP over a specific WAN interface ?

Idea here is to allow streaming media devices (such as Fire TV) to use only ADSL interface for example.

Thank you in advance!

## Specifications

  - OpenMPTCProuter version: 0.52.3
  - OpenMPTCProuter VPS version: 0.999 4.19.56-mptcp
  - OpenMPTCProuter platform: RPI3

**Comment by Ysurac** [comment]
OMR-ByPass is made for that.

**Comment by anglepoise86** [comment]
Thanks !
