### ISSUE TITLE
VPS Install on Ubuntu 18.04 fails

### ISSUE THREAD

**Issue by iorudyit** [Ysurac/openmptcprouter#782]
## Expected Behavior
Install on ubuntu 18.04 LTS

## Actual Behavior
The installation fails on easyrsa pki setup

## Steps to Reproduce the Problem
I did:
  1. fresh install openmptcp on vmware (Powered by openmptcprouter v0.53.2 r0+11546-a74095c68c)
  2. fresh install vps on ubuntu 18.04 LTS

## Specifications

  - OpenMPTCProuter version: v0.53.2
  - OpenMPTCProuter VPS version: 0.1006
  - OpenMPTCProuter platform: x86_64

The install script expexts easy-rsa 3,  but the latest on bionic is 2.2

**Comment by Ysurac** [comment]
Fixed in VPS script 0.1007
