### ISSUE TITLE
Since update router to 0.53.2 and vps to 0.1007 the network schema doesn't display

### ISSUE THREAD

**Issue by xillibit** [Ysurac/openmptcprouter#783]
## Expected Behavior

The network schema should be displayed

## Actual Behavior

The network schema doesn't displayed

![Sans titre](https://user-images.githubusercontent.com/876395/71748337-7f976880-2e72-11ea-986b-00d44164aec9.png)

The system log, the ip of VPS has been repalced by IPVPS : https://gist.github.com/xillibit/90045f507670c3335d8e119f296a7deb

## Steps to Reproduce the Problem

  1. Update VPS to 0.1007
  2. Update router to 0.53.2
  
## Specifications

  - OpenMPTCProuter version: 0.53.2
  - OpenMPTCProuter VPS version: 0.1007
  - OpenMPTCProuter platform: RPI4 aarch64

**Comment by tboome33** [comment]
Bonjour et bonne année, même problème ici :-(
Merci pour ce formidable travail
RG

**Comment by Ysurac** [comment]
Should be better with 0.53.3

**Comment by xillibit** [comment]
J'ai mis à jour le routeur en 0.53.3 et ensuite le VPS en 0.1008 mais le problème est toujours là : 

![apercu_0 53 3](https://user-images.githubusercontent.com/876395/71835632-52d19400-30b2-11ea-9632-f1c5077b82cd.png)

**Comment by tboome33** [comment]
Bonsoir, idem toujours le même problème :-(

**Comment by 8252610** [comment]
> J'ai mis à jour le routeur en 0.53.3 et ensuite le VPS en 0.1008 mais le problème est toujours là :
> 
> ![apercu_0 53 3](https://user-images.githubusercontent.com/876395/71835632-52d19400-30b2-11ea-9632-f1c5077b82cd.png)
I'm just like you

**Comment by stanf69** [comment]
Same problem here since upgrade to 53.3.
I've tried factory reset and the NETWORK STATUS schema is still not displayed. What can I do ?

**Comment by stanf69** [comment]
Any update ?

**Comment by Ysurac** [comment]
This happen only when there is an issue, and a check time out. This will be fixed in next update.

**Comment by xillibit** [comment]
Do-you know when is planned your next update of OMR ?

**Comment by Ysurac** [comment]
When it will be ready, this should be soon.

**Comment by xillibit** [comment]
Since the update of VPS to 0.1012 and openmptpcrouteur to v0.54rc7 r0+12300-fc65fae304 the network status is diplaying now
