### ISSUE TITLE
Impossible de contacter le scrip administrateur (no token=

### ISSUE THREAD

**Issue by jfh75** [Ysurac/openmptcprouter#785]
## Expected Behavior

Shadowsoscks shoud be successful contacting administrator script
If not, aggregation should occur.

## Actual Behavior
With new version 53.2, shadowsocks displays "impossible to contact administrator script (no token)" in the OMR sate picture.
Accordingly, it is impossible to use SAVE CONFIGURATION TO VPS

Router log says repeatedly : user.notice OMR-VPS: Can't get token, try later
VPS syslog says encryption problem : 
Jan  3 06:25:11 vps ss-server[23814]: failed to handshake with 109.190.xxx.xxx: authentication error
Jan  3 06:42:57 vps ss-server[23814]: message repeated 71 times: [ failed to handshake with 109.190.xxx.xxx: authentication error]
etc 
## Steps to Reproduce the Problem

  1. ugrade to 53.3 router version
  2.upgrade of VPS
  

## Specifications

  - OpenMPTCProuter version: 53.3
  - OpenMPTCProuter VPS version: kernel 4.19.80-mptcp
  - OpenMPTCProuter platform: x86-64
[syslog.txt](https://github.com/Ysurac/openmptcprouter/files/4022151/syslog.txt)

**Comment by suyuan168** [comment]
You should probably use the setup wizard to double check that your keys are filled in correctly.

**Comment by jfh75** [comment]
Issue is same as "Can't get public IP address from shadowSocks #764"
