### ISSUE TITLE
Add Arch ar71xx

### ISSUE THREAD

**Issue by FollowBlackSheep** [Ysurac/openmptcprouter#786]
Hey, i would like to use a TP-Link WR1043NDv4 for OpenMPTCPRouter is this possible at all?

i was trying to build a image by myself but i'm only getting the Error below:

Target ar71xx not found ! You have to configure and compile your kernel manually.

**Comment by Ysurac** [comment]
CPU too slow with often not enough flash available.
Doc to compile it for not supported platform is here: https://github.com/Ysurac/openmptcprouter/wiki/Create-image-for-unsupported-platform

**Comment by suyuan168** [comment]
> Hey, i would like to use a TP-Link WR1043NDv4 for OpenMPTCPRouter is this possible at all?
> 
> i was trying to build a image by myself but i'm only getting the Error below:
> 
> Target ar71xx not found ! You have to configure and compile your kernel manually.

You can try linksys AC3200 to test. High performance.

**Comment by FollowBlackSheep** [comment]
> linksys AC3200

Yeah but i don't have this Router so i wanted to use something i allready have.
