### ISSUE TITLE
Security Enhancement: Set your own ssh port

### ISSUE THREAD

**Issue by xabix** [Ysurac/openmptcprouter#787]
Hello,

Would it be possible to add a configuration parameter to set the ssh port on the VPS so it gets kept through upgrades and also so people can have their own ssh port vs the default one 65222 for security reasons.

This would have to maintain the ssh config and the firewall entry too.

Thank you

**Comment by Ysurac** [comment]
Modify ssh port in /etc/ssh/sshd_config and in /etc/shorewall/rules for the firewall part.
I will not make a var for that, I don't thinks it's needed and can make some conflict when a port is open on the router.
