### ISSUE TITLE
Bug: VPN Tunnel down

### ISSUE THREAD

**Issue by rubaz100** [Ysurac/openmptcprouter#790]
## Expected Behavior

Everything in the Network overview should have a green check (tick). But after a reboot (Router) I will get the message: "VPN Tunnel down". I need to restart the Glorytun VPN (UDP) everytime to see the green tick.

## Actual Behavior

But after a reboot (Router) I will get the message: "VPN Tunnel down". I need to restart the Glorytun VPN (UDP) everytime to see the green tick.

## Steps to Reproduce the Problem

  1. Reboot router (WRT3200ACM)
  2. Check the network overview 
  3. Restart Glorytun UDP

## Specifications

  - OpenMPTCProuter version: (0.53.3)
  - OpenMPTCProuter VPS version: (0.1007)
  - OpenMPTCProuter platform: (WRT3200ACM)

**Comment by Ysurac** [comment]
I'm not able to reproduce the issue.

**Comment by couili** [comment]
Bonjour, j'ai le même souci. Malgré ce bug d'affichage, l'agrégation fonctionne.

**Comment by Ysurac** [comment]
I don't think it's not a bug in display, if it's displayed as down, then it's down.
You could check in Status->System log why omr-tracker thinks it's down and if glorytun UDP tell something.

**Comment by couili** [comment]
Ce qui est curieux, c'est qu'en allant dans VPN > Glorytun puis en désactivant et réactivant le VPN, ça repasse au vert instantanément. J'avoue que je ne sais pas quelle partie des logs il vous faut.

**Comment by couili** [comment]
Un ami vient de me dire qu'il pourrait y avoir des soucis entre la version 4.19 du kernel de linux, et tout ce qui concerne les VPN. Aujourd'hui, même après avoir tout redémarré, je n'arrive plus à avoir un VPN fonctionnel.
