### ISSUE TITLE
Impossible de se connecter à un vpn Openssl sur routeur fortinet 1500d

### ISSUE THREAD

**Issue by Percy24600** [Ysurac/openmptcprouter#795]
Bonjour,

Je tiens à vous féliciter ainsi qu'a vous encourager votre travail sur cette solution d'agrégation!

Je suis designer cloud computing et je gere des datacenter à distance, en m'y connectant via solution fortinet VPN SSL vers FORTI 1500D.

Depuis dernières mise à jour 0.53.3 et 1008 VPS il m'est impossible de me connecter avec mon client VPN.

Port utilisé : 10443 en udp.

Je ne vais bien sur pas vous demander de debug, j'y aipassé pas mal de temps, pensant à un soucis de mtu mais pas du tout et je ne peux pas plus y passer de temps, mais juste savoir s'il est possible de créer une règle spécifique dans lucy pour obliger un paquet source LAN à passer par un WAN en particulier plutôt que l'agrégation?

Je vous en remercie sincèrement.

Bonne continuation à vous.

Très cordialement,

Guillaume

**Comment by Ysurac** [comment]
En utilisant omr-bypass
