### ISSUE TITLE
Autobckp config on SFTP or FTP 

### ISSUE THREAD

**Issue by jgreenhalgh51** [Ysurac/openmptcprouter#796]
Hi can you develop a autobackup with schedule of configuration on SFTP or FTP or an other system
Best regards 

  - OpenMPTCProuter version: (v0.53.3)
  - OpenMPTCProuter VPS version: (Last)
  - OpenMPTCProuter platform: (x86_64)

**Comment by Ysurac** [comment]
No, but in System->OpenMPTCProuter and "Backup on server" tab you can send backup to the server.
A cronjob can bet set to "openmptcprouter-vps backup_send", and I can add a checkbox to send backup to server in case of change but I'm not sure it's a good idea because I don't keep previous backup.
