### ISSUE TITLE
Netword overview cannot be displayed

### ISSUE THREAD

**Issue by 8252610** [Ysurac/openmptcprouter#797]
Install the latest router after I initialize the disk (0.53.3)
Install the latest VPS after I initialize the disk（1008）
Netword overview cannot be displayed
But vps1007 is all right
![1](https://user-images.githubusercontent.com/58301698/72414257-c65b5b80-37ac-11ea-98b9-eb460c9bad1a.png)
![3](https://user-images.githubusercontent.com/58301698/72414283-d2dfb400-37ac-11ea-8905-8dedfb31e812.png)
![2](https://user-images.githubusercontent.com/58301698/72414289-d5daa480-37ac-11ea-9733-140f06751267.png)
  - OpenMPTCProuter version: (0.53.3)
  - OpenMPTCProuter VPS version: (1008)
  - OpenMPTCProuter platform: (x86_64)

**Comment by Ysurac** [comment]
I will fix the status page but it's not working because you have a config problem. I think it's a problem with the interfaces configurations.

**Comment by 8252610** [comment]
think you very much
