### ISSUE TITLE
IPSEC low bandwitdh

### ISSUE THREAD

**Issue by blainvillem** [Ysurac/openmptcprouter#802]
Good morning, sir,

I have two ipsec tunnels between two pfsense router's.
One that leaves my local network with overthebox and one that leaves my local network with openmptcprouter and both go to an ovh network.

## Expected Behavior

I'd like both tunnels to work equally well. With a higher throughput for the tunnel through mptcprouter.

## Actual Behavior

The tunnel going through overthebox has a throughput of about 8mo/s and the other one going through openmptcprouter is at 300ko/s.

## Specifications

  - OpenMPTCProuter version: version 0.51.5
  - OpenMPTCProuter VPS version: 0.1000 4.19.56-mptcp
  - OpenMPTCProuter platform: x86_64

**Comment by blainvillem** [comment]
EDIT:

When I disable an interface on either WAN on MPTCPROUTER the throughput in my ipsec tunnel becomes good again.
I think the problem comes from the mptcp protocol.

**Comment by Ysurac** [comment]
You can try an other TCP Congestion Control and an other Multipath TCP scheduler in Network->MPTCP

**Comment by blainvillem** [comment]
> You can try an other TCP Congestion Control and an other Multipath TCP scheduler in Network->MPTCP

Hello, I've made all the possible changes with Multipath TCP scheduler and Congestion Control, but nothing improves the situation we remain stuck at about 512kbps.

Do you have another idea?
Knowing that the problem can't come from the tunnel an identical tunnel works to overthebox.

**Comment by blainvillem** [comment]
![MPTCP](https://user-images.githubusercontent.com/46742162/72878534-69572c80-3cfb-11ea-9a74-18594348f5e4.png)
![parametres_des_interfaces](https://user-images.githubusercontent.com/46742162/72878541-6d834a00-3cfb-11ea-9ee1-826db4d2099b.png)

**Comment by slitsevych** [comment]
Hi @blainvillem ! Have you tried to increase fullmesh subflows to 2 or more? Although my infrastructure is not exactly same as yours, we also use pfsense routing. In our case OMR/MPTCP works fine with **fullmesh** path-manager, 2 fullmesh subflows and "**olia**" as congestion control mode. We also switched from Glorytun-TCP to Glorytun-UDP and use "Master interface selection
 - no change" at "_cgi-bin/luci/admin/system/openmptcprouter/settings_". Besides that we've disabled TCP Fast Open and setup all relevant interfaces as bridges over system interfaces: 

![Screenshot from 2020-01-22 11-20-04](https://user-images.githubusercontent.com/57354524/72881314-37e55d80-3d09-11ea-95da-89516c0ba07a.png)

I hope some of these suggestions will be helpful

**Comment by blainvillem** [comment]
> Salut @blainvillem ! Avez-vous essayé d'augmenter les sous-flux fullmesh à 2 ou plus? Bien que mon infrastructure ne soit pas exactement la même que la vôtre, nous utilisons également le routage pfsense. Dans notre cas, OMR / MPTCP fonctionne très bien avec le **gestionnaire de** chemin d'accès **fullmesh** , 2 sous-flux fullmesh et " **olia** " comme mode de contrôle de la congestion. Nous sommes également passés de Glorytun-TCP à Glorytun-UDP et utilisons " _Sélection de l'interface principale - pas de changement_ " dans " _cgi-bin / luci / admin / system / openmptcprouter / settings_ ". En plus de cela, nous avons désactivé TCP Fast Open et configuré toutes les interfaces pertinentes (LAN, WAN1, WAN2) comme ponts sur les interfaces eth du système:
> 
> ![Capture d'écran du 2020-01-22 11-20-04](https://user-images.githubusercontent.com/57354524/72881314-37e55d80-3d09-11ea-95da-89516c0ba07a.png)
> 
> J'espère que certaines de ces suggestions vous seront utiles

Hello, 

Hello, first of all I wanted to thank you for your help.

I tried to change "fullmesh", 2 sub-flow fullmesh and "olia" but it didn't change anything in terms of throughput in the tunnel, still blocked at about 512kbps.

Concerning Glorytun, I'm already in udp without having changed the default configuration.

For the configuration of LAN / WAN 1 / WAN 2 interfaces in bridge it didn't work, I don't have internet in my local network anymore and here are the errors in the preview : 


PS: I couldn't find where to disable "TCP Fast Open".

![image](https://user-images.githubusercontent.com/46742162/72887127-619f8400-3d0b-11ea-83e8-c3455a442d4a.png)

![image](https://user-images.githubusercontent.com/46742162/72887183-7bd96200-3d0b-11ea-89f6-0a46be23f139.png)

![image](https://user-images.githubusercontent.com/46742162/72887218-898ee780-3d0b-11ea-88e1-a24d2d431635.png)

**Comment by blainvillem** [comment]
I think you have at least 3 network cards on your mptcprouter while I have only one.
My mptcprouter is a virtual machine on a "Vmware" ESX.
That's why it's impossible for me to bridge several different cards.

But I can add virtual network cards if needed, if this is the solution to our problem.

After what is weird is the fact that the network throughput works very well from a computer using mptcprouter as default gateway.
But also that the tunnel works pretty well with only one of the two WANs enabled on mptprouter.
The tunnel blocks at about 512kbps when both interfaces are activated with one master and the other one activates "Mptcp".

Translated with www.DeepL.com/Translator (free version)

**Comment by slitsevych** [comment]
Hi again! I'm really sorry to hear that none of the suggestions helped, however I would like to add that in our case we also configured mptcprouter as a VM of KVM type created within local Proxmox cluster. 
Interfaces are being added as virtual NICs: 
![Screenshot from 2020-01-22 13-39-21](https://user-images.githubusercontent.com/57354524/72891504-0bd3d780-3d1d-11ea-955e-f815746579e2.png)
All of them are also bridged from corresponding vlan interfaces added manually in /etc/network/interfaces and configured in Pfsense. 
Not sure if this helps, but I just wanted to add these small nuances. 

p.s: You can disable TCP Fast Open, change master interface selection, etc in Advanced Settings under System --> Openmptcprouter
![Screenshot from 2020-01-22 13-48-59](https://user-images.githubusercontent.com/57354524/72891958-15117400-3d1e-11ea-8e88-adada86959cf.png)

**Comment by blainvillem** [comment]
Thank you. Thank you,
I just tried and no change for the "TCP Fast Open" configuration.
Concerning the bridges with network cards, I don't know if it will change much since the throughput works very well without aggregating connections to access the tunnel.

I'll wait to hear back from Mr Yannick Chabanois, if you have other proposals, I'd be happy to try.

Especially the ipsec configuration of your pfsense "AES CBS encryption..."

Because even on overthebox or directly from my two ISPs I don't get a very high throughput in the tunnel "3 to 8 mbps maximum" for a connection of several hundred mbps.

**Comment by blainvillem** [comment]
After several tests during the day, I realized that the problem probably came more from my "pfsense" firewall routers.
Or compared to the fact that they are hosted in a vmware esx.

I have 1.5 mbps throughput per mptcprouter and 3.5 mbps per overthebox.

**Comment by blainvillem** [comment]
https://forum.netgate.com/topic/149905/ipsec-low-throughput

If you want more informations.

**Comment by blainvillem** [comment]
UP
