### ISSUE TITLE
All Google traffic does NOT go through VPN

### ISSUE THREAD

**Issue by max4186** [Ysurac/openmptcprouter#805]
For some reason, ALL traffic for Google does not go through the VPN. Especially Google Drive. I have no bypass setup for Google whatsoever, is there something else that could cause it? Slow speeds on Drive are annoying :(

**Comment by Ysurac** [comment]
Check that your computer doesn't get an IPv6 from another modem/box.

**Comment by max4186** [comment]
Unfortunately, no IPv6 enabled :(

**Comment by Ysurac** [comment]
How do you know that VPN is not used ?

**Comment by max4186** [comment]
2MB/s internet vs 15MB/s via bonded.

**Comment by Ysurac** [comment]
If you use google chrome I think that Google Drive use QUIC that is based on UDP and use the VPN (by default Glorytun TCP), else it should use HTTP/2 based on TCP that use shadowsocks and should be faster for our case.

**Comment by max4186** [comment]
Ah.... that explains it. I have the UDP VPN turned off completely as it causes latency issues for me - let me see if I can disable QUIC and test again.

**Comment by Ysurac** [comment]
You can disable it in Chrome or block port 443 and 80 in UDP on the firewall of OpenMPTCProuter.

**Comment by max4186** [comment]
This can be closed, it was indeed QUIC.
