### ISSUE TITLE
Installing updates via opkg

### ISSUE THREAD

**Issue by slitsevych** [Ysurac/openmptcprouter#807]
##
It's rather a simple question than an issue:
Is it safe to install any "opkg" updates of packages installed by default? 
I can see that OpenWrt released a new stable version 19.07.0 and "opkg list-upgradable" shows lots of new versions but I'm not sure if it's safe to simply install these updates. 
What do you suggest @Ysurac  ?

Thank you in advance.

## Specifications

  - OpenMPTCProuter version: 0.53.3
  - OpenMPTCProuter VPS version: 0.1008
  - OpenMPTCProuter platform: x86-64 (64-bit) ext4 image (EFI) installed on KVM machine

**Comment by Ysurac** [comment]
For now it's not recommended and not tested.

**Comment by slitsevych** [comment]
Thank you @Ysurac, got it! 

Could you please also specify, have you ever tested or tried implementing any Zabbix monitoring of OpenWRT environment, for example using templates and user parameters like described here:
https://wiki.commotionwireless.net/doku.php/general_resources/documentation/monitoring/zabbix

Thank you in advance again!

**Comment by Ysurac** [comment]
no
