### ISSUE TITLE
Update logiciels

### ISSUE THREAD

**Issue by nicoz76** [Ysurac/openmptcprouter#81]
## Expected Behavior

Problem when MAJ packets.

## Steps to Reproduce the Problem

![image](https://user-images.githubusercontent.com/10829637/41310242-41b55f16-6e81-11e8-8e30-81992fee9310.png)

![image](https://user-images.githubusercontent.com/10829637/41311535-d3d06532-6e84-11e8-976b-06a110131307.png)

## Specifications

  - OpenMPTCProuter version: v0.22 r7161-c8677ca89e
  - OpenMPTCProuter VPS version:   last
  - OpenMPTCProuter platform: Raspberry Pi 2 Model B Rev 1.1

**Comment by Ysurac** [comment]
I'm not able to reproduce the problem. Maybe a small problem with openwrt servers or a download during openwrt snapshots updates.

**Comment by nicoz76** [comment]
after a reboot,  the same : 
![image](https://user-images.githubusercontent.com/10829637/41312568-abb8375c-6e87-11e8-8459-4cb26f11d9f8.png)

**Comment by Ysurac** [comment]
You can try to disable IPv6, in *System->OpenMPTCProuter->advanced settings*

**Comment by nicoz76** [comment]
ok ,  k'ai coché : 
![image](https://user-images.githubusercontent.com/10829637/41313300-e844c404-6e89-11e8-8b9f-6531c8e6bd60.png) 

je teste  :)

**Comment by nicoz76** [comment]
c'est pareil, , même après désactivation IPV6 et reboot.
