### ISSUE TITLE
NAT on single WAN

### ISSUE THREAD

**Issue by JorgeMoort89** [Ysurac/openmptcprouter#811]
Hi Ysurac,
how can I NAT a service in my LAN directly on my WANs?
I have public IPs on my WANs and I wan't to use them to NAT some services

**Comment by Ysurac** [comment]
Use the firewall interface on OpenMPTCProuter.

**Comment by JorgeMoort89** [comment]
How can I NAT the service, for example on WAN1?
I'm trying with the WAN zone but is not working

**Comment by Ysurac** [comment]
Should work, you can check using ```iptables-save``` via SSH that rules are applied and ```tcpdump``` is also available on the router.
