### ISSUE TITLE
Router HA

### ISSUE THREAD

**Issue by JorgeMoort89** [Ysurac/openmptcprouter#812]
Hi Ysurac,
how can I configure VRRP or keepalive to have a proper redundand cofiguration?
Which service I have to stop and start to make sure only one router is connected to the VPS in that moment?

**Comment by Ysurac** [comment]
You mean multiple OpenMPTCProuter ?
Else multiple VPS failover is supported.

**Comment by JorgeMoort89** [comment]
Exactly, multiple OMR or HA on two OMR

**Comment by Ysurac** [comment]
It's not supported for now.
