### ISSUE TITLE
Espressobin support

### ISSUE THREAD

**Issue by JorgeMoort89** [Ysurac/openmptcprouter#814]
Hi Ysurac,
how can I make an image for Espressobin?
Do you have already tested it?

**Comment by Ysurac** [comment]
You need to follow https://github.com/Ysurac/openmptcprouter/wiki/Create-image-for-unsupported-platform
No I've not tested it and it's a ARM A53 so not a really fast CPU.

**Comment by JorgeMoort89** [comment]
On single connection I have very poor performance (40 mbit/s), how can I optimize it?
It have only 2 core 1.2Ghz

**Comment by Ysurac** [comment]
You can try to change or disable encryption on shadowsocks.

**Comment by JorgeMoort89** [comment]
How can I do that? I have to do it on server and OMR both? I need to reboot the router or the VPS?

**Comment by Ysurac** [comment]
On the router in shadowsocks-libev interface.
But you will never get network high speed on slow CPU.

**Comment by JorgeMoort89** [comment]
Without encryption is working great, have you seed the other issue about the public IP? Can you help me about it?

**Comment by JorgeMoort89** [comment]
With ext4 filesystem when there are power loss I corrupt the OS, with squashfs I can't make any edit on configurations becouse the fs is in read only mode, how can I fix this?

**Comment by Ysurac** [comment]
OpenMPTCProuter v0.55 is released. Espressobin v7 is supported.
Fell free to re-open bug if needed.
