### ISSUE TITLE
mptcp over vpn with obfuscation

### ISSUE THREAD

**Issue by BlueWaterCrystal** [Ysurac/openmptcprouter#818]
MPTCP and UDP are blocked on the connection, unfortunately the connection requires http obfuscation for vpns

I've tired relaying openvpn udp via shadowsocks ss-tunnel but not working but does say packets are being filtered?

I've seen a guide people do openvpn over shadowsocks before but TCP over TCP

my guess is i haven't set it up right or its not possible ?

## Expected Behavior

  mptcp over openvpn udp relayed through ss-tunnel  shahowsocks

## Actual Behavior
wan1 (192.168.8.7) and wan2 (192.168.0.7):
shadowsocks with obfuscation works on the other connections that support mptcp
-----------------------------------

wan3 (192.168.7.102):
shadowsocks with obfuscation works without openmptcprouter
-----------------------------------
ovpnwan3:
no ip defined
no gateway defined
---------------------

## Steps to Reproduce the Problem

  1. #mptcp over vpn enabled

  2. #create ss_tunnel in shadowsocks:
 server: SSS0
 local_address: 192.168.7.102
 local_port: 65301
 tunnel_address: 127.0.0.1:65301
 ipv6_first: 1
 fast_open: 1
 no_delay: 1
 reuse_port: 1
 mode: tcp_and_udp
 timeout: 1000
--------------------------------

3. OMR advanced settings:
Enable ShadowSocks Obfuscating
Obfuscating plugin = simple-obfs
Obfuscating type = http
--------------------------------

4. shadowsocks remote servers:
SSS0:
Plugin = obfs-local
Plugin Options =obfs=http;obfs-host=example.com
--------------------------------

## Specifications

  - OpenMPTCProuter version: (0.53)
  - OpenMPTCProuter VPS version: (0.1005)
  - OpenMPTCProuter platform: (x86_64)

**Comment by Ysurac** [comment]
I don't understand your configuration and why ss_tunnel can be used and you shouldn't have to change anything in shadowsocks config.
Also for obfuscation you should use v2ray.

**Comment by BlueWaterCrystal** [comment]
mptcp over vpn keeps getting blocked and native connection doesn't support udp or mptcp, I'm not sure where to go from this.

**Comment by Ysurac** [comment]
So MPTCP and UDP are blocked ? It's not a case i anticipated :)
