### ISSUE TITLE
could you give a showcase how the openmptcprouter connected to the vps is working well?

### ISSUE THREAD

**Issue by abilly007** [Ysurac/openmptcprouter#82]
My environment is as follows：

  - OpenMPTCProuter version:v0.16
  - OpenMPTCProuter VPS version:v0.14（debian 9）
  - OpenMPTCProuter platform: （x86_64)

There are a couple of questions that are confusing me.could you help me?
1. Although there is a configuration wizard here, I still don't know the relationship between shadowsoks and glorytun here. Do they have to be used together?i see shadowsocks and glorytun had being running on both router and VPS ,but there no connection betweet them.

2. int the VMware X86 ,how i should configure the wan1 and wan2 interface ? there's only one Internet port in rpi2/rpi3, so how did wan1 and wan2 come from? Although the document says to connect two models and set static IP, are these two wan ports usb ports?If so, why not use DHCP to connect to two normal routers?

**Comment by Ysurac** [comment]
You should update all versions.

1. Read https://github.com/Ysurac/openmptcprouter/issues/11
2. Ports on RPI are macvlan ports, so no need for additional ports. It's also why DHCP must be disabled.
For VMware you do as you want, one port or more.
