### ISSUE TITLE
System Reboot or VPN Down

### ISSUE THREAD

**Issue by MrTheSkream** [Ysurac/openmptcprouter#820]
Hello,

I have a problem with OpenMPTCPRouter,
When i have more than 20 people connected, the system crash.
The Rapsberry Pi shutdown VPN.

My logs :
https://pastebin.com/bSU4KEuy
https://pastebin.com/7pYejctx

Screenshot :
https://ibb.co/Qfv7tvM
https://ibb.co/sQCkNqZ
https://ibb.co/CHLWvpv

## Steps to Reproduce the Problem

  1. Install OpenMPTCProuter on Raspberry Pi 3B+.
  2. Connect more than 20 people to Wi-Fi or Ethernet.
  3. Use internet.

## Specifications

  - OpenMPTCProuter version: 0.51.3
  - OpenMPTCProuter platform: RPI 3B+

**Comment by Ysurac** [comment]
OpenMPTCProuter v0.55 is released.
Fell free to re-open bug if needed.
