### ISSUE TITLE
Le VPN ne répond pas (VPN does not respond)

### ISSUE THREAD

**Issue by CoSysopK** [Ysurac/openmptcprouter#827]
## Actual Behavior

**I have try with VPN glorytun tcp in the wizard. Here are the results :**
![vpn](https://user-images.githubusercontent.com/48426317/73828325-52d3c980-4801-11ea-9054-38766f12c8a3.png)
Wed Feb  5 10:50:20 2020 daemon.err /usr/bin/ss-redir[7984]: remote recv: Operation timed out
Wed Feb  5 10:50:23 2020 daemon.err /usr/bin/ss-local[7982]: getpeername: Socket not connected
Wed Feb  5 10:50:24 2020 user.notice OMR-VPS: Can't get token, try later
Wed Feb  5 10:50:30 2020 daemon.err /usr/bin/ss-redir[7985]: remote recv: Operation timed out
Wed Feb  5 10:50:31 2020 daemon.err /usr/bin/ss-redir[7983]: remote recv: Operation timed out
Wed Feb  5 10:50:32 2020 daemon.err /usr/bin/ss-redir[7986]: remote recv: Operation timed out
Wed Feb  5 10:50:33 2020 daemon.err /usr/bin/ss-redir[7986]: remote recv: Operation timed out
Wed Feb  5 10:50:33 2020 daemon.err /usr/bin/ss-redir[7985]: remote recv: Operation timed out
Wed Feb  5 10:50:33 2020 daemon.err /usr/bin/ss-redir[7986]: remote recv: Operation timed out
Wed Feb  5 10:50:34 2020 daemon.err /usr/bin/ss-redir[7983]: remote recv: Operation timed out
Wed Feb  5 10:50:34 2020 daemon.err /usr/bin/ss-redir[7985]: remote recv: Operation timed out
Wed Feb  5 10:50:34 2020 daemon.err /usr/bin/ss-redir[7983]: remote recv: Operation timed out
Wed Feb  5 10:50:35 2020 daemon.err /usr/bin/ss-redir[7986]: remote recv: Operation timed out
Wed Feb  5 10:50:35 2020 user.notice OMR-VPS: Can't get token, try later
Wed Feb  5 10:50:35 2020 daemon.err /usr/bin/ss-redir[7983]: remote recv: Operation timed out
Wed Feb  5 10:50:36 2020 daemon.err /usr/bin/ss-redir[7983]: remote recv: Operation timed out
Wed Feb  5 10:50:36 2020 daemon.err /usr/bin/ss-redir[7986]: remote recv: Operation timed out
Wed Feb  5 10:50:36 2020 daemon.err /usr/bin/ss-local[7982]: getpeername: Socket not connected
Wed Feb  5 10:50:36 2020 daemon.err /usr/bin/ss-local[7982]: getpeername: Socket not connected
Wed Feb  5 10:50:36 2020 daemon.err /usr/bin/ss-redir[7983]: remote recv: Operation timed out
Wed Feb  5 10:50:36 2020 daemon.err /usr/bin/ss-redir[7984]: remote recv: Operation timed out
Wed Feb  5 10:50:37 2020 daemon.err /usr/bin/ss-redir[7983]: remote recv: Operation timed out
Wed Feb  5 10:50:37 2020 daemon.err /usr/bin/ss-redir[7983]: remote recv: Operation timed out
Wed Feb  5 10:50:37 2020 daemon.err /usr/bin/ss-redir[7983]: remote recv: Operation timed out

**I have try with VPN glorytun udp in the wizard. Here are the results :**
![vpn](https://user-images.githubusercontent.com/48426317/73828325-52d3c980-4801-11ea-9054-38766f12c8a3.png)
Wed Feb  5 10:15:13 2020 daemon.err /usr/bin/ss-redir[11097]: remote recv: Operation timed out
Wed Feb  5 10:15:14 2020 daemon.err /usr/bin/ss-redir[11097]: remote recv: Operation timed out
Wed Feb  5 10:15:14 2020 daemon.err /usr/bin/ss-redir[11097]: remote recv: Operation timed out
Wed Feb  5 10:15:14 2020 daemon.err /usr/bin/ss-redir[11095]: remote recv: Operation timed out
Wed Feb  5 10:15:15 2020 daemon.err /usr/bin/ss-redir[11097]: remote recv: Operation timed out
Wed Feb  5 10:31:38 2020 daemon.err /usr/bin/ss-redir[11097]: remote recv: Operation timed out
Wed Feb  5 10:31:40 2020 daemon.err /usr/bin/ss-redir[11098]: remote recv: Operation timed out
Wed Feb  5 10:31:40 2020 daemon.err /usr/bin/ss-redir[11098]: remote recv: Operation timed out
Wed Feb  5 10:31:40 2020 daemon.err /usr/bin/ss-redir[11097]: remote recv: Operation timed out

**I have try with VPN dsvpn in the wizard. Here are the results :**
At the beginning, it's perfect. After a few minutes, here is the result :
![vpn](https://user-images.githubusercontent.com/48426317/73828325-52d3c980-4801-11ea-9054-38766f12c8a3.png)
And from time to time, I have this result :
Wed Feb  5 10:43:10 2020 daemon.err /usr/bin/ss-redir[11796]: remote recv: Operation timed out
Wed Feb  5 10:43:11 2020 daemon.err /usr/bin/ss-redir[11797]: remote recv: Operation timed out
Wed Feb  5 10:43:12 2020 daemon.err /usr/bin/ss-redir[11796]: remote recv: Operation timed out
Wed Feb  5 10:43:14 2020 daemon.err /usr/bin/ss-redir[11798]: remote recv: Operation timed out
Wed Feb  5 10:43:15 2020 daemon.err /usr/bin/ss-local[11795]: getpeername: Socket not connected
Wed Feb  5 10:43:16 2020 daemon.err /usr/bin/ss-local[11795]: getpeername: Socket not connected
Wed Feb  5 10:43:17 2020 daemon.err /usr/bin/ss-redir[11797]: remote recv: Operation timed out
Wed Feb  5 10:43:21 2020 daemon.err /usr/bin/ss-redir[11799]: remote recv: Operation timed out
Wed Feb  5 10:43:23 2020 daemon.err /usr/bin/ss-redir[11797]: remote recv: Operation timed out

**I have try with VPN openvpn in the wizard. Here are the results :**
![network](https://user-images.githubusercontent.com/48426317/73836888-908c1e80-4810-11ea-847e-588fde761c73.png)
Wed Feb  5 12:11:09 2020 user.notice post-tracking-post-tracking: Can't find OpenVPN, restart it...
Wed Feb  5 12:11:09 2020 daemon.err openvpn(omr)[26458]: Options error: specify only one of --tls-server, --tls-client, or --secret
Wed Feb  5 12:11:09 2020 daemon.warn openvpn(omr)[26458]: Use --help for more information.
Wed Feb  5 12:11:09 2020 user.notice post-tracking-post-tracking: Can't find OpenVPN, restart it...
Wed Feb  5 12:11:10 2020 daemon.err openvpn(omr)[26544]: Options error: specify only one of --tls-server, --tls-client, or --secret
Wed Feb  5 12:11:10 2020 daemon.warn openvpn(omr)[26544]: Use --help for more information.
Wed Feb  5 12:11:15 2020 daemon.err openvpn(omr)[26669]: Options error: specify only one of --tls-server, --tls-client, or --secret
Wed Feb  5 12:11:15 2020 daemon.warn openvpn(omr)[26669]: Use --help for more information.
![openvpn2](https://user-images.githubusercontent.com/48426317/73837037-dea12200-4810-11ea-88c8-00b9e19c758c.png)

> _I specify that my WAN1 is under SFR with a network which is not top from time to time_

**Can I activate DNSSEC ?**
![dnssec](https://user-images.githubusercontent.com/48426317/73836011-b1537480-480e-11ea-9ce0-0f63970d0d4d.png)

**And can I activate ?**
![brouillage](https://user-images.githubusercontent.com/48426317/73836172-f677a680-480e-11ea-9ec8-19236e3c8d54.png)

Thank you for your information.

## Steps to Reproduce the Problem

 1. Install image for Raspberry PI 3/3B+ (64-bit)
 2. Install VPS Debian 10 Buster x86_64
 3. Configure the router with the wan1 static and wan2 static
 4. Add the IP address VPS and, all the informations retrived on the VPS
 5. Two keys 4G on usb PI 3B

## Specifications

  - OpenMPTCProuter version: Version 0.53.3
  - OpenMPTCProuter VPS version: Version 0.1008
  - OpenMPTCProuter platform: RPI3B+ 64 bits

**Comment by Ysurac** [comment]
Errors from the log are related to shadowsocks to the VPN for Glorytun.
For DNSSEC you can try it if you want, for shadowsocks obfuscation you don't need it if you are not in China or want to hide the use of shadowsocks.
