### ISSUE TITLE
Stabilisation

### ISSUE THREAD

**Issue by Roken120** [Ysurac/openmptcprouter#829]
## Expected Behavior

Hello,
I have two 100mbps fiber and one 4G when i download i not up more than 160mbps when i remove 4g i up to 200mbps
The speed of down to 120mbps and up to 220mbps i not stable connection do you have an idea for patch this

## Steps to Reproduce the Problem

  1. Two 100mbps connection
  2. One 4G connection

## Specifications

  - OpenMPTCProuter version: 0.53.3
  - OpenMPTCProuter VPS version: 0.1008
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
A bad connection can sometimes slow all connections.
What is the interface defined as Master ?
Everything use own dedicated ethernet port (no macvlan) ?
In Network->MPTCP you can try another Multipath TCP scheduler.
