### ISSUE TITLE
key exchange failed

### ISSUE THREAD

**Issue by CoSysopK** [Ysurac/openmptcprouter#837]
## Actual Behavior

From time to time, I have a connection problem.

**Log of router:**
Fri Feb 14 02:00:00 2020 cron.err crond[3198]: USER root pid 30903 cmd /etc/init.d/vnstat_backup backup
Fri Feb 14 02:00:00 2020 cron.err crond[3198]: USER root pid 30904 cmd /etc/init.d/omr-bypass bypass_asn
Fri Feb 14 02:01:11 2020 daemon.err glorytun[5778]: read: Operation timed out
Fri Feb 14 02:01:11 2020 daemon.info glorytun[5778]: STOPPED tun0
Fri Feb 14 02:01:12 2020 daemon.err glorytun[5778]: 34.77.160.206.65001: connected
Fri Feb 14 02:01:20 2020 user.notice post-tracking-post-tracking: omrvpn down. Replace default route by 192.168.101.1 dev eth1
Fri Feb 14 02:01:20 2020 user.notice post-tracking-post-tracking: omrvpn down because gateway down
Fri Feb 14 02:01:21 2020 user.notice post-tracking-post-tracking: Tunnel down use ShadowSocks for UDP
Fri Feb 14 02:01:21 2020 user.notice Shadowsocks: Rules DOWN
Fri Feb 14 02:01:21 2020 daemon.info omr-tracker-ss: Reload Shadowsocks rules
Fri Feb 14 02:01:22 2020 user.notice Shadowsocks: Rules UP
Fri Feb 14 02:01:22 2020 user.notice post-tracking-post-tracking: Master up : Replace default route by 192.168.102.1 dev eth2
Fri Feb 14 02:01:22 2020 daemon.err glorytun[5778]: 34.77.160.206.65001: key exchange failed
Fri Feb 14 02:01:22 2020 daemon.info glorytun[5778]: STOPPED tun0
Fri Feb 14 02:01:23 2020 user.notice Shadowsocks: Reload omr-bypass rules
Fri Feb 14 02:01:23 2020 user.notice omr-bypass: Starting OMR-ByPass...
Fri Feb 14 02:01:23 2020 daemon.err glorytun[5778]: 34.77.160.206.65001: connected
Fri Feb 14 02:01:25 2020 user.notice omr-bypass: Reload dnsmasq...
Fri Feb 14 02:01:26 2020 daemon.info dnsmasq[22413]: read /etc/hosts - 4 addresses
Fri Feb 14 02:01:26 2020 daemon.info dnsmasq[22413]: read /tmp/hosts/dhcp.cfg01411c - 2 addresses
Fri Feb 14 02:01:26 2020 daemon.info dnsmasq-dhcp[22413]: read /etc/ethers - 0 addresses
Fri Feb 14 02:01:26 2020 user.notice omr-bypass: OMR-ByPass is running
Fri Feb 14 02:01:33 2020 daemon.err glorytun[5778]: 34.77.160.206.65001: key exchange failed
Fri Feb 14 02:01:33 2020 daemon.info glorytun[5778]: STOPPED tun0
Fri Feb 14 02:01:34 2020 daemon.err glorytun[5778]: 34.77.160.206.65001: connected
Fri Feb 14 02:01:44 2020 daemon.err glorytun[5778]: 34.77.160.206.65001: key exchange failed
Fri Feb 14 02:01:44 2020 daemon.info glorytun[5778]: STOPPED tun0
Fri Feb 14 02:01:45 2020 daemon.err glorytun[5778]: 34.77.160.206.65001: connected
Fri Feb 14 02:01:55 2020 daemon.err glorytun[5778]: 34.77.160.206.65001: key exchange failed
Fri Feb 14 02:01:55 2020 daemon.info glorytun[5778]: STOPPED tun0
Fri Feb 14 02:01:56 2020 daemon.err glorytun[5778]: 34.77.160.206.65001: connected
Fri Feb 14 02:02:06 2020 daemon.err glorytun[5778]: 34.77.160.206.65001: key exchange failed
Fri Feb 14 02:02:06 2020 daemon.info glorytun[5778]: STOPPED tun0
Fri Feb 14 02:02:07 2020 daemon.err glorytun[5778]: 34.77.160.206.65001: connected
Fri Feb 14 02:02:17 2020 daemon.err glorytun[5778]: 34.77.160.206.65001: key exchange failed
Fri Feb 14 02:02:17 2020 daemon.info glorytun[5778]: STOPPED tun0
Fri Feb 14 02:02:18 2020 daemon.err glorytun[5778]: 34.77.160.206.65001: connected
Fri Feb 14 02:02:28 2020 daemon.err glorytun[5778]: 34.77.160.206.65001: key exchange failed
Fri Feb 14 02:02:28 2020 daemon.info glorytun[5778]: STOPPED tun0
Fri Feb 14 02:02:29 2020 daemon.err glorytun[5778]: 34.77.160.206.65001: connected
Fri Feb 14 02:02:39 2020 daemon.err glorytun[5778]: 34.77.160.206.65001: key exchange failed
Fri Feb 14 02:02:39 2020 daemon.info glorytun[5778]: STOPPED tun0
Fri Feb 14 02:02:40 2020 daemon.err glorytun[5778]: 34.77.160.206.65001: connected
Fri Feb 14 02:02:50 2020 daemon.err glorytun[5778]: 34.77.160.206.65001: key exchange failed
Fri Feb 14 02:02:50 2020 daemon.info glorytun[5778]: STOPPED tun0
Fri Feb 14 02:03:00 2020 daemon.err glorytun[5778]: 34.77.160.206.65001: connected
Fri Feb 14 02:03:06 2020 daemon.info glorytun[5778]: STARTED tun0
Fri Feb 14 02:03:15 2020 user.notice post-tracking-post-tracking: Tunnel up : Replace default route by 10.255.255.1 dev tun0
Fri Feb 14 02:03:15 2020 user.notice post-tracking-post-tracking: Tunnel up disable use of ShadowSocks for UDP
Fri Feb 14 02:03:15 2020 user.notice Shadowsocks: Rules DOWN
Fri Feb 14 02:03:15 2020 daemon.info omr-tracker-ss: Reload Shadowsocks rules
Fri Feb 14 02:03:15 2020 user.notice Shadowsocks: Rules UP
Fri Feb 14 02:03:16 2020 user.notice Shadowsocks: Reload omr-bypass rules
Fri Feb 14 02:03:16 2020 user.notice omr-bypass: Starting OMR-ByPass...
Fri Feb 14 02:03:18 2020 user.notice omr-bypass: Reload dnsmasq...
Fri Feb 14 02:03:19 2020 daemon.info dnsmasq[22413]: read /etc/hosts - 4 addresses
Fri Feb 14 02:03:19 2020 daemon.info dnsmasq[22413]: read /tmp/hosts/dhcp.cfg01411c - 2 addresses
Fri Feb 14 02:03:19 2020 daemon.info dnsmasq-dhcp[22413]: read /etc/ethers - 0 addresses
Fri Feb 14 02:03:19 2020 user.notice omr-bypass: OMR-ByPass is running
Fri Feb 14 02:03:50 2020 daemon.err /usr/bin/ss-local[15973]: getpeername: Socket not connected
Fri Feb 14 02:04:34 2020 daemon.err uhttpd[3535]: luci: accepted login on / for root from 192.168.100.228
Fri Feb 14 02:05:05 2020 daemon.info glorytun[5778]: STOPPED tun0
Fri Feb 14 02:05:06 2020 daemon.err glorytun[5778]: 34.77.160.206.65001: connected
Fri Feb 14 02:05:06 2020 daemon.info glorytun[5778]: STARTED tun0
Fri Feb 14 02:05:41 2020 daemon.err /usr/bin/ss-redir[15976]: remote recv: Operation timed out
Fri Feb 14 02:06:52 2020 daemon.err /usr/bin/ss-redir[15975]: remote recv: Operation timed out
Fri Feb 14 02:07:12 2020 daemon.err /usr/bin/ss-redir[15977]: remote recv: Operation timed out
Fri Feb 14 02:07:12 2020 daemon.err /usr/bin/ss-redir[15977]: remote recv: Operation timed out
Fri Feb 14 02:07:17 2020 daemon.err /usr/bin/ss-redir[15975]: remote recv: Operation timed out
Fri Feb 14 02:09:51 2020 daemon.err /usr/bin/ss-redir[15975]: remote recv: Operation timed out
Fri Feb 14 02:10:32 2020 daemon.err /usr/bin/ss-redir[15975]: remote recv: Operation timed out
Fri Feb 14 02:11:13 2020 daemon.err /usr/bin/ss-redir[15975]: remote recv: Operation timed out
Fri Feb 14 02:11:39 2020 daemon.err /usr/bin/ss-redir[15975]: remote recv: Operation timed out
Fri Feb 14 02:11:54 2020 daemon.err /usr/bin/ss-redir[15975]: remote recv: Operation timed out
Fri Feb 14 02:11:54 2020 daemon.err /usr/bin/ss-redir[15974]: remote recv: Operation timed out

**Log of VPS:** (gmt time)
Feb 14 00:58:29 instance-1 ss-server[387]: getpeername: Transport endpoint is not connected
Feb 14 00:58:54 instance-1 ss-server[387]: getpeername: Transport endpoint is not connected
Feb 14 00:59:01 instance-1 ss-server[387]: getpeername: Transport endpoint is not connected
Feb 14 00:59:33 instance-1 ss-server[387]: getpeername: Transport endpoint is not connected
Feb 14 01:00:05 instance-1 ss-server[387]: getpeername: Transport endpoint is not connected
Feb 14 01:00:37 instance-1 ss-server[387]: getpeername: Transport endpoint is not connected
Feb 14 01:01:08 instance-1 ss-server[387]: getpeername: Transport endpoint is not connected
Feb 14 01:01:40 instance-1 ss-server[387]: getpeername: Transport endpoint is not connected
Feb 14 01:02:12 instance-1 ss-server[387]: getpeername: Transport endpoint is not connected
Feb 14 01:02:12 instance-1 ss-server[387]: getpeername: Transport endpoint is not connected
Feb 14 01:02:16 instance-1 ss-server[387]: getpeername: Transport endpoint is not connected
Feb 14 01:02:16 instance-1 ss-server[387]: getpeername: Transport endpoint is not connected
Feb 14 01:02:16 instance-1 ss-server[387]: getpeername: Transport endpoint is not connected
Feb 14 01:02:16 instance-1 ss-server[387]: getpeername: Transport endpoint is not connected
Feb 14 01:02:49 instance-1 ss-server[387]: getpeername: Transport endpoint is not connected
Feb 14 01:02:56 instance-1 glorytun-tcp-run[13334]: read: Connection timed out
Feb 14 01:02:57 instance-1 glorytun-tcp-run[13334]: 37.165.27.180.43550: connected
Feb 14 01:02:57 instance-1 glorytun-tcp-run[13334]: 37.165.27.180.43550: key exchange failed
Feb 14 01:02:58 instance-1 glorytun-tcp-run[13334]: 37.165.27.180.43555: connected
Feb 14 01:02:58 instance-1 glorytun-tcp-run[13334]: 37.165.27.180.43555: key exchange failed
Feb 14 01:02:59 instance-1 glorytun-tcp-run[13334]: 37.165.27.180.43510: connected
Feb 14 01:02:59 instance-1 glorytun-tcp-run[13334]: 37.165.27.180.43510: key exchange failed
Feb 14 01:03:00 instance-1 glorytun-tcp-run[13334]: 37.165.27.180.43504: connected
Feb 14 01:03:00 instance-1 glorytun-tcp-run[13334]: 37.165.27.180.43504: key exchange failed
Feb 14 01:03:01 instance-1 glorytun-tcp-run[13334]: 37.165.27.180.43514: connected
Feb 14 01:03:01 instance-1 glorytun-tcp-run[13334]: 37.165.27.180.43514: key exchange failed
Feb 14 01:03:02 instance-1 glorytun-tcp-run[13334]: 37.165.27.180.43501: connected
Feb 14 01:03:02 instance-1 glorytun-tcp-run[13334]: 37.165.27.180.43501: key exchange failed
Feb 14 01:03:03 instance-1 glorytun-tcp-run[13334]: 37.165.27.180.43559: connected
Feb 14 01:03:03 instance-1 glorytun-tcp-run[13334]: 37.165.27.180.43559: key exchange failed
Feb 14 01:03:04 instance-1 glorytun-tcp-run[13334]: 37.165.27.180.43520: connected
Feb 14 01:03:04 instance-1 glorytun-tcp-run[13334]: 37.165.27.180.43520: key exchange failed
Feb 14 01:03:05 instance-1 glorytun-tcp-run[13334]: 37.165.27.180.43523: connected
Feb 14 01:03:05 instance-1 glorytun-tcp-run[13334]: 37.165.27.180.43523: key exchange failed
Feb 14 01:03:06 instance-1 glorytun-tcp-run[13334]: 37.165.27.180.43524: connected
Feb 14 01:03:21 instance-1 ss-server[387]: getpeername: Transport endpoint is not connected
Feb 14 01:03:24 instance-1 ss-server[387]: getpeername: Transport endpoint is not connected
Feb 14 01:03:56 instance-1 ss-server[387]: getpeername: Transport endpoint is not connected
Feb 14 01:04:00 instance-1 ss-server[387]: getpeername: Transport endpoint is not connected
Feb 14 01:04:32 instance-1 ss-server[387]: getpeername: Transport endpoint is not connected
Feb 14 01:05:05 instance-1 glorytun-tcp-run[13334]: INITIALIZED gt-tun0
Feb 14 01:05:05 instance-1 glorytun-tcp-run[13334]: STARTED gt-tun0
Feb 14 01:05:05 instance-1 glorytun-tcp-run[13334]: STOPPED gt-tun0
Feb 14 01:05:05 instance-1 glorytun-tcp-run[13334]: STOPPED gt-tun0
Feb 14 01:05:05 instance-1 glorytun-tcp-run[13334]: STOPPED gt-tun0
Feb 14 01:05:05 instance-1 glorytun-tcp-run[13334]: STOPPED gt-tun0
Feb 14 01:05:05 instance-1 glorytun-tcp-run[13334]: STOPPED gt-tun0
Feb 14 01:05:05 instance-1 glorytun-tcp-run[13334]: STOPPED gt-tun0
Feb 14 01:05:05 instance-1 glorytun-tcp-run[13334]: STOPPED gt-tun0
Feb 14 01:05:05 instance-1 glorytun-tcp-run[13334]: STOPPED gt-tun0
Feb 14 01:05:05 instance-1 glorytun-tcp-run[13334]: STOPPED gt-tun0
Feb 14 01:05:05 instance-1 glorytun-tcp-run[13334]: STOPPED gt-tun0
Feb 14 01:05:05 instance-1 glorytun-tcp-run[13334]: STARTED gt-tun0
Feb 14 01:05:05 instance-1 glorytun-tcp-run[13334]: STOPPED gt-tun0
Feb 14 01:05:05 instance-1 systemd-networkd[13340]: gt-tun0: Lost carrier
Feb 14 01:05:05 instance-1 systemd[1]: Stopping Glorytun TCP on tun0...
Feb 14 01:05:05 instance-1 systemd[1]: glorytun-tcp@tun0.service: Succeeded.
Feb 14 01:05:05 instance-1 systemd[1]: Stopped Glorytun TCP on tun0.
Feb 14 01:05:05 instance-1 systemd[1]: Started Glorytun TCP on tun0.
Feb 14 01:05:05 instance-1 systemd[1]: Stopping Network Service...
Feb 14 01:05:05 instance-1 systemd[1]: systemd-networkd.service: Succeeded.
Feb 14 01:05:05 instance-1 systemd[1]: Stopped Network Service.
Feb 14 01:05:05 instance-1 systemd[1]: Starting Network Service...
Feb 14 01:05:05 instance-1 systemd-udevd[4418]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
Feb 14 01:05:05 instance-1 systemd-networkd[4427]: dsvpn0: Gained IPv6LL
Feb 14 01:05:05 instance-1 systemd-networkd[4427]: omr-6in4: Gained IPv6LL
Feb 14 01:05:05 instance-1 systemd-networkd[4427]: gt-udp-tun0: Gained IPv6LL
Feb 14 01:05:05 instance-1 systemd-networkd[4427]: tun0: Gained IPv6LL
Feb 14 01:05:05 instance-1 systemd-networkd[4427]: tun1: Gained IPv6LL
Feb 14 01:05:05 instance-1 systemd-networkd[4427]: tun0: Gained IPv6LL
Feb 14 01:05:05 instance-1 systemd-networkd[4427]: tun1: Gained IPv6LL
Feb 14 01:05:05 instance-1 systemd-networkd[4427]: mlvpn0: Gained IPv6LL
Feb 14 01:05:05 instance-1 systemd-networkd[4427]: ens4: Gained IPv6LL
Feb 14 01:05:05 instance-1 systemd-networkd[4427]: Enumeration completed
Feb 14 01:05:05 instance-1 systemd[1]: Started Network Service.
Feb 14 01:05:05 instance-1 systemd-networkd[4427]: gt-tun0: Gained carrier
Feb 14 01:05:05 instance-1 systemd-networkd[4427]: gt-tun0: Gained IPv6LL
Feb 14 01:05:06 instance-1 glorytun-tcp-run[4420]: 37.173.179.230.38587: connected
Feb 14 01:05:15 instance-1 ss-server[387]: getpeername: Transport endpoint is not connected
Feb 14 01:05:17 instance-1 systemd-networkd[4427]: gt-udp-tun0: Configured
Feb 14 01:05:17 instance-1 systemd-networkd[4427]: mlvpn0: Configured
Feb 14 01:05:17 instance-1 systemd-networkd[4427]: gt-tun0: Configured
Feb 14 01:06:34 instance-1 ss-server[387]: remote recv: Connection reset by peer
Feb 14 01:06:36 instance-1 ss-server[387]: remote recv: Connection reset by peer
Feb 14 01:06:37 instance-1 ss-server[387]: remote recv: Connection reset by peer
Feb 14 01:06:38 instance-1 ss-server[387]: remote recv: Connection reset by peer
Feb 14 01:06:40 instance-1 google-accounts: INFO Adding user co_sysop_k to the Google sudoers group.
Feb 14 01:06:50 instance-1 systemd[1]: Created slice User Slice of UID 1000.
Feb 14 01:06:50 instance-1 systemd[1]: Starting User Runtime Directory /run/user/1000...
Feb 14 01:06:50 instance-1 systemd[1]: Started User Runtime Directory /run/user/1000.
Feb 14 01:06:50 instance-1 systemd[1]: Starting User Manager for UID 1000...
Feb 14 01:06:50 instance-1 systemd[4720]: Listening on GnuPG cryptographic agent and passphrase cache (restricted).
Feb 14 01:06:50 instance-1 systemd[4720]: Listening on GnuPG cryptographic agent (ssh-agent emulation).
Feb 14 01:06:50 instance-1 systemd[4720]: Reached target Timers.
Feb 14 01:06:50 instance-1 systemd[4720]: Listening on GnuPG cryptographic agent and passphrase cache.
Feb 14 01:06:50 instance-1 systemd[4720]: Listening on GnuPG network certificate management daemon.
Feb 14 01:06:50 instance-1 systemd[4720]: Reached target Paths.
Feb 14 01:06:50 instance-1 systemd[4720]: Listening on GnuPG cryptographic agent and passphrase cache (access for web browsers).
Feb 14 01:06:50 instance-1 systemd[4720]: Reached target Sockets.
Feb 14 01:06:50 instance-1 systemd[4720]: Reached target Basic System.
Feb 14 01:06:50 instance-1 systemd[1]: Started User Manager for UID 1000.
Feb 14 01:06:50 instance-1 systemd[1]: Started Session 259 of user co_sysop_k.
Feb 14 01:06:50 instance-1 systemd[4720]: Reached target Default.
Feb 14 01:06:50 instance-1 systemd[4720]: Startup finished in 37ms.
Feb 14 01:06:52 instance-1 ss-server[387]: getpeername: Transport endpoint is not connected
Feb 14 01:07:23 instance-1 ss-server[387]: getpeername: Transport endpoint is not connected
Feb 14 01:07:44 instance-1 ss-server[387]: getpeername: Transport endpoint is not connected
Feb 14 01:07:44 instance-1 ss-server[387]: getpeername: Transport endpoint is not connected
Feb 14 01:07:49 instance-1 ss-server[387]: getpeername: Transport endpoint is not connected
Feb 14 01:07:52 instance-1 ss-server[387]: getpeername: Transport endpoint is not connected
Feb 14 01:07:55 instance-1 ss-server[387]: getpeername: Transport endpoint is not connected
Feb 14 01:08:16 instance-1 ss-server[387]: getpeername: Transport endpoint is not connected
Feb 14 01:08:16 instance-1 ss-server[387]: getpeername: Transport endpoint is not connected
Feb 14 01:08:24 instance-1 ss-server[387]: getpeername: Transport endpoint is not connected
Feb 14 01:08:27 instance-1 ss-server[387]: getpeername: Transport endpoint is not connected

## Steps to Reproduce the Problem

1. Installer l'image pour Raspberry PI 3 / 3B + (64 bits)
2. Installateur VPS Debian 10 Buster x86_64
3. Configurez le routeur avec le wan1 statique et le wan2 statique
4. Ajoutez l'adresse IP VPS et, toutes les informations récupérées sur le VPS
5. Deux clés 4G sur USB PI 3B

## Specifications

- Version OpenMPTCProuter: version 0.53.3
- Version VPS OpenMPTCProuter: Version 0.1008
- Plateforme OpenMPTCProuter: RPI3B + 64 bits

**Comment by Ysurac** [comment]
When the interface defined as master is down the tunnel go down. I think the interface also changed IP, so glorytun TCP doesn't known it and doesn't allow it before some time. You can try another VPN.

**Comment by CoSysopK** [comment]
So, my WAN1 and WAN2 connections must be with a static IP.
4G keys are with dynamic IP. But the IP does not change if the 4G key has not been OFF/ON.

**Better to use dsvpn or openvpn so that this error does not happen again ?**

For information, there was an update on the google cloud VPS server. I did it.

**Comment by CoSysopK** [comment]
When there are WANs with dynamic IP. Some options may need to be added to address this IP change concern. With **DynDNS** or **No-IP**. This will allow you to have a static IP and thus not suffer any untimely disconnection.

**Comment by Ysurac** [comment]
DynDNS or No-IP doesn't give a static IP, but a domain or subdomain.
You can use another VPN.

**Comment by CoSysopK** [comment]
I have my WAN1 which changes IP by itself and without rebooting. All VPN are causing me an error.
I tried: Glorytun tcp et udp, dsvpn, openvpn.
