### ISSUE TITLE
Router install on vm esxi

### ISSUE THREAD

**Issue by Scaff31** [Ysurac/openmptcprouter#84]
Hello,

Can you explain how to install the router on an ESXI 6.5 virtual machine

Thank you for your work.
By thanking you.

**Comment by Scaff31** [comment]
It's good I succeeded, just specify the disk vmdk in ide and not scsi

**Comment by Ysurac** [comment]
ok
Anyway I can't provide any help on ESXI, I don't use it :)

**Comment by Scaff31** [comment]
ok no work on esxi but idk why on pi => OK vbox => OK but on esxi not work i'll try another day :)
