### ISSUE TITLE
EspressoBin filesystem isssue

### ISSUE THREAD

**Issue by JorgeMoort89** [Ysurac/openmptcprouter#847]
Hi Ysurac,
I've manually build OMR for Espressobin, with ext4 filesystem when there are power loss I corrupt the OS, with squashfs I can't make any edit on configurations because the filesystem is in read only mode, how can I fix this?

**Comment by Ysurac** [comment]
It's not a supported platform, so no support on this.
And I think that the issue is a design flaw from Espressobin like no capacitor to flush memory when there is a power loss.
