### ISSUE TITLE
Two openmtcprouter for one vps

### ISSUE THREAD

**Issue by constant1010** [Ysurac/openmptcprouter#85]
Is it possible to connect 2 routers, with different location, with one vps server? Maybe it's a good idea to reduce the cost when we have two location.

**Comment by Scaff31** [comment]
i think it's possible if your vps've two public IP

**Comment by Ysurac** [comment]
It's possible even with one public IP, but it's not supported by the OpenMPTCProuter VPS script, you would have to make many modifications.
But a VPS is not really expensive this would limit the available bandwidth (that is often low for a VPS...)

**Comment by Scaff31** [comment]
And if vps are two public ip can you explain how setup vps ?

**Comment by Ysurac** [comment]
This would need to have shadowsocks and glorytun listen on each IP and to configure shorewall.
For now this will not be a supported setup.

**Comment by xabix** [comment]
Hello, I was wondering if we are supposed to be able to upgrade the packages? I can easily to an 'updade' but I can't seem to be able to upgrade any of the packages as it says the filesystem is in read only with 0.51-5. Any idea if we are suppose to be able to upgrade the packages or not?

**Comment by Ysurac** [comment]
You shouldn't upgrade packages but filesystem shouldn't be read only.
But this is not related to the main issue...

**Comment by RealVaVa** [comment]
> It's possible even with one public IP, but it's not supported by the OpenMPTCProuter VPS script, you would have to make many modifications.
> But a VPS is not really expensive this would limit the available bandwidth (that is often low for a VPS...)

I really need to get quality on few locations (for SIP), the bandwich for each is <1-2Mbps, it should be available for many VPS.
I would like to save compilation of your scheme (openmtcp router and VPS), because it really works (thanks a lot).  But could you share what kind modifications  I need to make for multiple connections (2 and more)?
