### ISSUE TITLE
Question: Can an OMR VPS also host a low-volume server like an MQTT Broker?

### ISSUE THREAD

**Issue by bnhf** [Ysurac/openmptcprouter#850]
## Expected Behavior

Hopefully, that I can use my OMR VPS (1v core, 1GB RAM, 25GB SSD on Vultr.com) to host another server or two like an MQTT Broker, and/or a Ubiquiti UniFi Cloud Controller. Both would just be for my personal use, so would have modest traffic

## Actual Behavior

Don't know. I'm hoping somebody else has tried this.

## Steps to Reproduce the Problem

  1. Install VPS
  2. Install Mosquito
  3. Install Unifi Cloud Controller

## Specifications

OpenMPTCProuter version: v0.53.3 r0+11546-a74095c68c
OpenMPTCProuter VPS version: 0.1008
OpenMPTCProuter platform: RPi4

**Comment by Ysurac** [comment]
Yes, this should work even if not recommended.

**Comment by Dragonox77** [comment]
I think you should change the server.
This is my vps with only OMR installed on it.
http://prntscr.com/r716yc

**Comment by bnhf** [comment]
Thanks for the replies. I can see now that putting the MQTT broker on the OpenMPTCProuter side of things (with appropriate port forwarding), rather than installing it on the VPS, is a better solution. Alternatively, if the traffic ever gets to be more than I want to have on my cellular links, I'll spin-up another virtual server on Vultr.
