### ISSUE TITLE
Unable to install new version VPS server....

### ISSUE THREAD

**Issue by Randdrick** [Ysurac/openmptcprouter#856]
## Specifications

  - OpenMPTCProuter VPS version: 0.1008

Beacuse of this error .... 

--2020-02-25 21:12:23--  https://www.openmptcprouter.com/server/multipath
Resolving www.openmptcprouter.com (www.openmptcprouter.com)... 94.23.252.192
Connecting to www.openmptcprouter.com (www.openmptcprouter.com)|94.23.252.192|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3400 (3.3K) [application/octet-stream]
Saving to: '/usr/local/bin/multipath'

/usr/local/bin/mult 100%[===================>]   3.32K  --.-KB/s    in 0s

2020-02-25 21:12:23 (35.9 MB/s) - '/usr/local/bin/multipath' saved [3400/3400]

debian10-x86_64.sh: 703: debian10-x86_64.sh: **~wget: not found**

**Comment by Ysurac** [comment]
Fixed
