### ISSUE TITLE
Problème installation script VPS

### ISSUE THREAD

**Issue by Slivikkus** [Ysurac/openmptcprouter#857]
## Problème

Bonjour,

J'ai ce problème quand je veux installer le script côté VPS  (VPS chez Sapinet)
![image](https://user-images.githubusercontent.com/53304251/75290537-d8570200-5820-11ea-8118-2ca5d6f6037a.png)

Quel serais le problème ?

**Comment by Slivikkus** [comment]
D'après le président de l'association, le script modifie mal l'eth0 ce qui fait merder partiellement le VPS

**Comment by Slivikkus** [comment]
étonnamment même erreur chez OVH

**Comment by Ysurac** [comment]
C'est corrigé.
Je n'avais pas enlever l'exécution d'un script de démarrage devenu inutile.
