### ISSUE TITLE
redirect all router traffic to one host

### ISSUE THREAD

**Issue by Scaff31** [Ysurac/openmptcprouter#86]
How can I redirect all incoming vpn traffic on the router to a single host?

This is the network I wish I had:

LAN ===> PFsense ==> OpenMPTCP  ==> VPN1and2 ==> VPS ==> Internet

so I manage my firewall rules with pfsense

**Comment by Ysurac** [comment]
No idea what VPN1and2 mean ;)
But else yes you can, you only have to redirect all traffic to OpenMPTCProuter from the VPS and then 
from OpenMPTCProuter to PFsense. You can follow this :  https://github.com/Ysurac/openmptcprouter/wiki/Port-forwarding (this should be the same without matching a specific port)
