### ISSUE TITLE
OpenMPTCProuter v0.54 Release Candidate

### ISSUE THREAD

**Issue by Ysurac** [Ysurac/openmptcprouter#864]
In this new release:
* Signal power for some mobile router/dongle
* Fix disconnect when master down
* Many fixes and small changes

This release need server part v0.1012

You can download images here: https://www.openmptcprouter.com/release/4.19/

Latest version: v0.54rc15

**Comment by vinceducat** [comment]
hello i m in OMR 0.53.3 stable and VPS 1010 must have  to go in 0.54rc5 and 1011 ?

**Comment by vinceducat** [comment]
not a godd idea i try update OMR and VPS

now in state view i have on OMR "le vpn ne r2pond pas" :-(

**Comment by Ysurac** [comment]
What is the VPN used ?

**Comment by vinceducat** [comment]
I dont change any vpn so i think is the default vpn glorytun... where can i find this info...

**Comment by Ysurac** [comment]
In System->OpenMPTCProuter and advanced setting checkbox.

**Comment by vinceducat** [comment]
go to 0.54 rc7 and 1012 all seem ok now

**Comment by vinceducat** [comment]
VPN is OPen VPN...

**Comment by Ysurac** [comment]
No. OpenVPN is the slowest available VPN.

**Comment by vinceducat** [comment]
So glorytun tcp?

**Comment by Ysurac** [comment]
Yes or glorytun UDP. You can make tests. The VPN is used only for anything that is not TCP.

**Comment by vinceducat** [comment]
ok thanks

**Comment by vinceducat** [comment]
ok i change vpn to glorytun tcp seems to be ok to...

**Comment by Slivikkus** [comment]
Pour l'instant cette version fonctionne parfaitement avec moi, je remettrais un message pour confirmer que ça tient bien dans le temps :)

**Comment by Slivikkus** [comment]
![image](https://user-images.githubusercontent.com/53304251/76141319-4393a600-6063-11ea-8e45-47977c65957e.png)
C'est le seul problème j'ai eu pour l'instant, sois côté VPS ou VPN down

**Comment by Ysurac** [comment]
You have some high load on both router and VPS. What is the usage ? some p2p or really slow arch ?

**Comment by Slivikkus** [comment]
I use several vps for redundancy, however the connection looks more stable than on the old version

**Comment by Ysurac** [comment]
v0.54 is released.

**Comment by vinceducat** [comment]
Thanks...
