### ISSUE TITLE
J'ai de nouveau le problème comme le #834

### ISSUE THREAD

**Issue by Slivikkus** [Ysurac/openmptcprouter#866]
## Actual Behavior
Bonjour, j'ai exactement le même problème que sur le #834 

J'ai tout réinstaller (VPS et routeur), ça à fonctionner pendant quelques heures après ça me refait la même chose, ça commence à bien impacté mes serveurs (qui tournent un peu dans le vide pour l'instant, j'en ai même du éteindre certains serveurs puisque la connexion fonctionne très mal)

![image](https://user-images.githubusercontent.com/53304251/75629011-b5409f80-5bde-11ea-8d14-e5cd95b5faed.png)
(et encore là j'ai reboot le VPS ça me fait ça)

## Specifications

  - OpenMPTCProuter version: (0.53.3 (ESXI)
  - OpenMPTCProuter VPS version: (Inconnue)
  - OpenMPTCProuter platform: (x86_64)

**Comment by Slivikkus** [comment]
Des fois ça peux être comme ça aussi (ça change presque rien en sois)

**Comment by Ysurac** [comment]
Déjà il faudrait savoir la version du VPS, si ce n'est la v0.1012 il faut mettre à jour.
Tu peux aussi tester la dernière RC de la v0.54 d'OMR https://github.com/Ysurac/openmptcprouter/issues/864

**Comment by jgreenhalgh51** [comment]
i haven't change config  just active upnp

**Comment by Slivikkus** [comment]
J'ai la 0.1011 côté vps je met à jour tout à l'heure

**Comment by Slivikkus** [comment]
Et où je peux trouver pour ESXI pour la version 0.54 ? :)

**Comment by Slivikkus** [comment]
VPS à jour rien ne change pour l'instant

**Comment by Slivikkus** [comment]
J'ai l'impression que je perd la connexion au VPS toutes les 30 secondes ...

**Comment by Archana7700** [comment]
how to check the VPS version? i have flashed the new firmware and OMR version is now v0.54rc9 

but issue is the same as shown in pic "cant get the ip address from the shadowsocks cant contach the server "how to resolve this

**Comment by Ysurac** [comment]
VPS release is available in ```/etc/motd```
