### ISSUE TITLE
Renew all VPN keys on VPS -- not an issue 

### ISSUE THREAD

**Issue by vinceducat** [Ysurac/openmptcprouter#867]
## Expected Behavior

 renews all keys on VPS

## Actual Behavior
not realy an issue

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - OpenMPTCProuter version: 0.54 rc7
  - OpenMPTCProuter VPS version: 1012
  - OpenMPTCProuter platform: rpi3

how to renew keys on VPS ?
how to stop unused VPN on VPS ?

**Comment by Ysurac** [comment]
It's no possible easily for now.
