### ISSUE TITLE
shadowsocks-libev not running 

### ISSUE THREAD

**Issue by Archana7700** [Ysurac/openmptcprouter#869]
shadowsocks when i m seeing at server side its throwing an error 

 /etc/init.d/shadowsocks-libev status
● shadowsocks-libev.service - Shadowsocks-libev Default Server Service
   Loaded: loaded (/lib/systemd/system/shadowsocks-libev.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2020-03-02 17:52:42 IST; 8s ago
     Docs: man:shadowsocks-libev(8)
  Process: 7564 ExecStart=/usr/bin/ss-server -c $CONFFILE $DAEMON_ARGS (code=exited, status=255)
 Main PID: 7564 (code=exited, status=255)

Mar 02 17:52:42 mantis systemd[1]: Started Shadowsocks-libev Default Server Service.
Mar 02 17:52:42 mantis systemd[1]: shadowsocks-libev.service: Main process exited, code=exited, status=255/n/a
Mar 02 17:52:42 mantis systemd[1]: shadowsocks

**Comment by Ysurac** [comment]
shadowsocks-libev service is not used on server side.
shadowsocks-libev-manager service is used.
