### ISSUE TITLE
Static route through one isp

### ISSUE THREAD

**Issue by salchris** [Ysurac/openmptcprouter#872]
Hi Ysurac,
first of all, thank you for your work.
I was doing everything by hand, but then i discovered openpmtcp ..

Everything goes fine! 400mbps down, 90 up! with a pair of 4g connections.

Is there a way through LUCI to route a LAN ip through one ISP, instead of the tunnel?

I tried "by hand" and i can route non tcp-traffic, but TCP redirect rules catches my tcp packects :)

Is there a simple way to perform what i need, or i have to exclude it from redirects rules?
Thank you

**Comment by Ysurac** [comment]
There is OMR-ByPass for that. In services->omr-bypass.

**Comment by salchris** [comment]
oops..

Thank you again!
