### ISSUE TITLE
Squashfs RPI3 and RPI4

### ISSUE THREAD

**Issue by MrTheSkream** [Ysurac/openmptcprouter#874]
Hello,

I have a problem with raspberry pi 4 squashfs.

With Raspberry pi 3 squashfs the system is on RW and with RPI 4 squashfs the system is in RO.

It's normal ?

Thanks.

**Comment by Ysurac** [comment]
No, but this happen often. It's why ext4 is recommended.

**Comment by MrTheSkream** [comment]
Yes i know but ext4 is is sensitive to power failure.
And my system instantly shuts down the raspberry when I press the button..

**Comment by Ysurac** [comment]
True, but in fact squashfs doesn't really work better on a RPI.

**Comment by MrTheSkream** [comment]
Okey thanks.
It works perfectly on raspberry pi 3 with squashfs so I will continue to use with the old version of raspberry, as long as it works.

**Comment by Ysurac** [comment]
maybe you can test the release candidate, this should be the latest and I hope to release a new final version tomorrow.
