### ISSUE TITLE
VPN tunnel down

### ISSUE THREAD

**Issue by Slivikkus** [Ysurac/openmptcprouter#878]
## VPN TUNNEL DOWN

J'ai le "VPN tunnel down", suite à la mise à jour du VPS, le problème viens du script ?
![image](https://user-images.githubusercontent.com/53304251/76337926-58d53280-62f8-11ea-8765-51c7defafd09.png)

## Specifications

  - OpenMPTCProuter version: (0.54
  - OpenMPTCProuter VPS version: (0.1013)
  - OpenMPTCProuter platform: (x86_64 ESXI)

**Comment by Ysurac** [comment]
Quel est le VPN utilisé ?

**Comment by Slivikkus** [comment]
"A Dead Simple VPN"

**Comment by Slivikkus** [comment]
Il faut pas que je mette "Glorytun TCP" plutôt ?

**Comment by Slivikkus** [comment]
Ah oui c'est bon x)

**Comment by Ysurac** [comment]
Il y avait un bug avec DSVPN, j'ai corrigé. En relançant le script sur le VPS ce VPN refonctionnera.

**Comment by Slivikkus** [comment]
D'accord, et pour l'IPv6 y'a plus de problème ? (d'ailleurs ça ce configure automatiquement maintenant ?)

**Comment by Ysurac** [comment]
Normalement plus de soucis, il faut cocher la case dans le wizard et le tunnel fonctionne.
Il y a encore des améliorations possibles quand un /48 est dispo sur le VPS.

**Comment by Slivikkus** [comment]
La configuration ce fait toujours sur le VPS ou le routeur le fait ?

**Comment by Ysurac** [comment]
Le VPS doit avoir une IPv6 configurée correctement, sinon tout se fait sur le routeur.

**Comment by Slivikkus** [comment]
Et encore une dernière question après j'en ai plus, j'ai le routeur sur une tour maintenant et j'aimerais savoir comment que ça ce passe pour configurer le wifi (via une clé wifi en USB)

**Comment by Ysurac** [comment]
En la branchant et en allant dans Réseau->Wifi si le driver est déjà présent. Sinon il faut trouver le driver et l'installer.

**Comment by Slivikkus** [comment]
Je vois pas la section wifi mais la clé est bien détecté par le routeur avec le nom suivant "wlan0"
