### ISSUE TITLE
VPN TUNNEL DOWN DEPUIS VPS 0.1013

### ISSUE THREAD

**Issue by bosseb** [Ysurac/openmptcprouter#879]
- OpenMPTCProuter version: 0.54 officielle
  - OpenMPTCProuter VPS version: 0.1013 chez milkywan
  - OpenMPTCProuter platform: x86_64

depuis que j'ai mis à jour le VPS en 0.1013 j'ai un VPN tunnel DOWN, j'ai fais le test avec un autre VPS resté en 0.1012 tout refonctionne
![vpn down depuis 0 1013](https://user-images.githubusercontent.com/17600769/76341753-c33ca180-62fd-11ea-9507-e1ae53a7a245.jpg)

**Comment by Ysurac** [comment]
Quel est le VPN utilisé ?
Le VPS doit être redémarré après la mise à jour et ça semble pas être le cas la.

**Comment by bosseb** [comment]
GLORYTUN TCP

**Comment by Ysurac** [comment]
Pas de changements après redémarrage du VPS ?

**Comment by bosseb** [comment]
j'utilise MILKYWAN et comme le vps n'est pas en mode root de base je ne pouvais pas rebooter

je les ai contactés et maintenant cela marche parfaitement

merci de ton aide

bonne soirée
