### ISSUE TITLE
passage sur GLORYTUN UDP : VPN Tunnel DOWN

### ISSUE THREAD

**Issue by bosseb** [Ysurac/openmptcprouter#882]
- OpenMPTCProuter version: 0.54 Officiel
  - OpenMPTCProuter VPS version: 0.1013 (vps MILKYWAN)
  - OpenMPTCProuter platform: x86_64

quand je passe sur glorytun udp, je passe en VPN tunnel DOWN, et l'accès distant de mon plex ne fonctionne plus ...
j'ai redémarré vps et OMR et pas mieux !

![vpn down](https://user-images.githubusercontent.com/17600769/76459555-b2169200-63dc-11ea-9843-28aa118e4985.png)

**Comment by Ysurac** [comment]
Il faut voir dans Etat->Journal Système ce qu'il y a.
Et sur le VPS, un ```ps aux | grep glory``` permettra de savoir si glorytun-udp est bien lancé.

**Comment by bosseb** [comment]
ci dessous le journal système


[journal syst.txt](https://github.com/Ysurac/openmptcprouter/files/4320715/journal.syst.txt)

**Comment by bosseb** [comment]
sebastien@sebastieng:~$ ps aux | grep glory
root       429  0.0  0.0   2692   904 ?        SLs  21:03   0:00 glorytun bind 0                .0.0.0 65001 keyfile /etc/glorytun-udp/tun0.key dev gt-udp-tun0 chacha persist
root       437  0.0  0.0   2960   928 ?        Ss   21:03   0:00 glorytun-tcp li                stener keyfile /etc/glorytun-tcp/tun0.key dev gt-tun0 port 65001 mptcp chacha20                 retry count -1 const 5000000 timeout 10000 keepalive count 5 idle 20 interval 2                 buffer-size 32768 multiqueue
sebasti+ 22144  0.0  0.0   6144   892 pts/0    S+   21:24   0:00 grep glory
sebastien@sebastieng:~$

**Comment by flimo44** [comment]
Bonjour , 
j'ai le problème inverse depuis la 0.54. J'ai dû passer en UDP car ça ne montait plus en TCP.

**Comment by Ysurac** [comment]
Il me faudrait la config, sans les clefs (dans Système->OpenMPTCProuter, onglet "tous les paramètres")

**Comment by Ysurac** [comment]
@flimo44 ouvre ta propre issue du coup (et vérifie que tu utilises bien la dernière version du script VPS)

**Comment by bosseb** [comment]
[tous parametres.txt](https://github.com/Ysurac/openmptcprouter/files/4320847/tous.parametres.txt)

j'ai remplacé les keys par key
password par password et token par token

;)

**Comment by Ysurac** [comment]
Je ne vois pas de soucis dans la config la.
Il faudrait voir le contenu de ```/etc/glorytun-udp/tun0``` (la clef doit correspondre, et il doit indiquer chacha20)
tu peux tester un ```ping 10.255.254.1``` depuis le routeur via SSH aussi ou un ```ping 10.255.254.2``` depuis le VPS.

**Comment by bosseb** [comment]
pour tune0
BIND=0.0.0.0
BIND_PORT=65001
DEV=tun0
OPTIONS="chacha persist"

**Comment by bosseb** [comment]
root@OpenMPTCProuter:~# ping 10.255.254.1
PING 10.255.254.1 (10.255.254.1) 56(84) bytes of data.

**Comment by Ysurac** [comment]
Etrange, je ne vois pas où peut être le soucis...
Sur le routeur, que donne ```glorytun-udp path``` via SSH ?

**Comment by bosseb** [comment]
path UP
  status:  DEGRADED
  bind:    192.168.6.5 port 5000
  public:  - port 0
  peer:    45.13.104.175 port 65001
  mtu:     0 bytes
  rtt:     0.000 ms
  rttvar:  0.000 ms
  rate:    fixed
  beat:    100 ms
  tx:
    rate:  125000000 bytes/sec
    loss:  0 percent
    total: 2365 packets
  rx:
    rate:  125000000 bytes/sec
    loss:  0 percent
    total: 0 packets
path UP
  status:  DEGRADED
  bind:    192.168.2.5 port 5000
  public:  - port 0
  peer:    45.13.104.175 port 65001
  mtu:     0 bytes
  rtt:     0.000 ms
  rttvar:  0.000 ms
  rate:    fixed
  beat:    100 ms
  tx:
    rate:  125000000 bytes/sec
    loss:  0 percent
    total: 2365 packets
  rx:
    rate:  125000000 bytes/sec
    loss:  0 percent
    total: 0 packets
path UP
  status:  DEGRADED
  bind:    192.168.4.5 port 5000
  public:  - port 0
  peer:    45.13.104.175 port 65001
  mtu:     0 bytes
  rtt:     0.000 ms
  rttvar:  0.000 ms
  rate:    fixed
  beat:    100 ms
  tx:
    rate:  125000000 bytes/sec
    loss:  0 percent
    total: 2365 packets
  rx:
    rate:  125000000 bytes/sec
    loss:  0 percent
    total: 0 packets

**Comment by bosseb** [comment]
tu m'indiquais dans un message précédent : Il faudrait voir le contenu de /etc/glorytun-udp/tun0 (la clef doit correspondre, et il doit indiquer chacha20)
cependant dans ce fichier pas de clé et pas de chacha20 regarde : 
BIND=0.0.0.0
BIND_PORT=65001
DEV=tun0
OPTIONS="chacha persist"

**Comment by Ysurac** [comment]
La clef est bien dans tun0.key.
La configuration est bonne.
Que donne un ```ip a show gt-udp-tun0``` ?

**Comment by bosseb** [comment]
je fais ça où ? VPS ou OMR ?

**Comment by Ysurac** [comment]
sur le VPS pardon

**Comment by bosseb** [comment]
sebastien@sebastieng:~$ ip a show gt-udp-tun0
4: gt-udp-tun0: <POINTOPOINT,MULTICAST,NOARP,80000> mtu 1500 qdisc noop state DO                                                                                                                                   WN group default qlen 500
    link/none

**Comment by Ysurac** [comment]
Ah bah voila le soucis.
Le fichier ```/etc/glorytun-udp/post.sh``` est bien présent ?
Tu peux me donenr le contenu du ```/lib/systemd/system/glorytun-udp@.service``` ?
Tu peux tenter un ```systemctl daemon-reload``` puis un ```systemctl restart glorytun-udp@gt-udp-tun0``` ?

**Comment by bosseb** [comment]
1//etc/glorytun-udp/post.sh est bien présent ? oui il est présent

**Comment by bosseb** [comment]
/lib/systemd/system/glorytun-udp@.service

[Unit]
Description=Glorytun UDP on %I
After=network.target network-online.target

[Service]
Type=simple
Restart=always
EnvironmentFile=/etc/glorytun-udp/%i
ExecStart=/usr/local/bin/glorytun-udp-run /etc/glorytun-udp/%i
ExecStartPost=-/etc/glorytun-udp/post.sh /etc/glorytun-udp/%i
CapabilityBoundingSet=CAP_NET_ADMIN

[Install]
WantedBy=multi-user.target

**Comment by bosseb** [comment]
j'oublie un détail, depuis hier soir j'ai repassé ma config en GLORYTUN TCP ... ça foire les éléments que je t'envoie ?

**Comment by Ysurac** [comment]
Non. Tout est bon jusque là.

**Comment by bosseb** [comment]
sebastien@sebastieng:~$ systemctl daemon-reload
Failed to reload daemon: The name org.freedesktop.PolicyKit1 was not provided by                                                                                                                                    any .service files

**Comment by Ysurac** [comment]
```sudo systemctl daemon-reload``` si tu es pas root

**Comment by bosseb** [comment]
pas de message d'erreur sur les 2 dernières avec sudo

**Comment by Ysurac** [comment]
et que donne ```ip a show gt-udp-tun0``` maintenant ?

**Comment by bosseb** [comment]
4: gt-udp-tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP,80000> mtu 1500 qdisc fq state UP group default qlen 500
    link/none
    inet 10.255.254.1/30 brd 10.255.254.3 scope global gt-udp-tun0
       valid_lft forever preferred_lft forever
    inet6 fe80::8adb:63fe:29b3:3400/64 scope link stable-privacy
       valid_lft forever preferred_lft forever

**Comment by Ysurac** [comment]
C'est beaucoup mieux.

**Comment by bosseb** [comment]
donc je dois faire quoi pour que cela marche en GLORYTUN UDP ?

**Comment by Ysurac** [comment]
Tu peux essayer de repasser dessus

**Comment by bosseb** [comment]
pas mieux il y a  tjrs marqué vnp tunnel down

**Comment by Ysurac** [comment]
Je sèche la... Tu utilises bien le wizard pour changer de VPN ?

**Comment by bosseb** [comment]
yes

**Comment by bosseb** [comment]
oh attends ça viens de passer en OK (je suis connecté à distance)

**Comment by bosseb** [comment]
donc tout est ok maintenant avec glorytun udp , donc je dois faire quoi en fait pour que cela marche ? j'ai une autre agrégation au bureau et j'ai le même soucis

**Comment by Ysurac** [comment]
```sudo systemctl daemon-reload``` puis un ```sudo systemctl restart glorytun-udp@tun0```
J'ai ajouté le daemon-reload dans le script d'installation du VPS.

**Comment by bosseb** [comment]
il faut relancer une MAJ du VPS ?

**Comment by Ysurac** [comment]
Soit le daemon-reload, soit màj. Mais autant faire le daemon reload si elle est déjà à jour.

**Comment by bosseb** [comment]
en tout cas merci beaucoup pour l'aide c'est top !!!

**Comment by RH2WTF** [comment]
Bonjour,

pour info je rencontre exactement le même problème, la solution proposer ci dessus fonctionne : 

sudo systemctl daemon-reload puis un sudo systemctl restart glorytun-udp@tun0

cependant à chaque redémarrage du VPS, le problème survient de nouveau.

y a t'il une solution définitive pour résoudre cette problématique ?

Merci pour le support @Ysurac , t'es au top !!!

**Comment by Ysurac** [comment]
C'est corrigé dans le script VPS v0.1014 (un script tourne en permanence pour vérifier l'état de glorytun-udp).

**Comment by Eltarius** [comment]
> 
> 
> C'est corrigé dans le script VPS v0.1014 (un script tourne en permanence pour vérifier l'état de glorytun-udp).

Je rajoute une petite question sur cette issue que j'ai également depuis le passage à la dernière version. J'ai egalement eu besoin de relancer le daemon et de restart glorytun-udp après la mise à jour en VPS v0.1014 alors que d'après toi un script tourne en permanence pour vérifier.
Maintenant j'ai:
`mtu 1500 qdisc fq state UP group default qlen 500`

Cependant sur mon routeur j'ai toujours tun0 DOWN.
![image](https://user-images.githubusercontent.com/15571859/76654561-87a70f00-656b-11ea-9d73-d2637936bbb8.png)

Si tu veux que j'ouvre une autres issue n'hésite pas.

**Comment by Ysurac** [comment]
Il me faudrait le résultat de ```ip a show gt-udp-tun0``` et de ```glorytun-udp show dev gt-udp-tun0```

**Comment by Eltarius** [comment]
`8: gt-udp-tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP,80000> mtu 1500 qdisc fq state UP group default qlen 500
    link/none
    inet 10.255.254.1/30 brd 10.255.254.3 scope global gt-udp-tun0
       valid_lft forever preferred_lft forever
    inet6 fe80::28ad:f2f1:e4f5:1622/64 scope link stable-privacy
       valid_lft forever preferred_lft forever`

`-bash: glorytun-udp : commande introuvable`

**Comment by Ysurac** [comment]
oui pardon, c'est ```glorytun show dev gt-udp-tun0``` sur le VPS

**Comment by Eltarius** [comment]
`server gt-udp-tun0:
  pid:    20679
  bind:   0.0.0.0 port 65001
  mtu:    0
  cipher: chacha20poly1305`

**Comment by Ysurac** [comment]
Visiblement glorytun-udp tourne correctement.

**Comment by Eltarius** [comment]
Donc ceci est un bug d'affichage coté routeur:
![image](https://user-images.githubusercontent.com/15571859/76679882-76e6af80-65e4-11ea-85f2-ee33026abdfd.png)

**Comment by xillibit** [comment]
Je viens de passer le router en 0.56 et le VPS en 0.1015 et j'ai aussi le VPN tunnel down

Sur le VPS quand je fais un `glorytun show dev gt-udp-tun0` ça m'affiche : 

![image](https://user-images.githubusercontent.com/876395/76985367-6a45bc80-6940-11ea-8f98-e92143e16312.png)

**Comment by Ysurac** [comment]
En 0.54.6 Glorytun UDP est mis à jour vers la dernière version. Est-ce que le débit de chaque interface est bien présent dans le wizard sur le routeur ?

**Comment by xillibit** [comment]
C'est ça le wizard ? Pour LAN2 et WAN3 je voudrais les supprimer mais je n'y arrive pas

![image](https://user-images.githubusercontent.com/876395/76991103-56eb1f00-6949-11ea-8e9c-57c049c66eee.png)

**Comment by Ysurac** [comment]
Non, ça c'est l'affichage de l'état/status, le wizard c'est l'onglet juste avant.
Pour LAN2 et wan3 il suffit de désactiver le multipath sur ces interfaces dans Réseau->MPTCP

**Comment by xillibit** [comment]
J'ai 0 : 

![image](https://user-images.githubusercontent.com/876395/77011769-e2c27280-696c-11ea-9280-888a0e97019c.png)

J'ai ça maintenant dans l'état en ayant voulu rajouter des étiquettes sur chaque interface, donc j'ai fait Sauvegarder et appliquer sur le wizard : 

![image](https://user-images.githubusercontent.com/876395/77011923-3208a300-696d-11ea-947e-383ab75dddd9.png)

**Comment by Ysurac** [comment]
Essaye en définissant les valeurs.

**Comment by xillibit** [comment]
J'ai mis les valeurs suivantes et en en redémarrant le routeur j'ai plus le VPN down, hier soir j'avais aussi redémarré l'instance du serveur : 

![image](https://user-images.githubusercontent.com/876395/77059349-12a66000-69d7-11ea-863b-7ec0e799e31d.png)

**Comment by philoun8** [comment]
Bonjour a tous
Pour moi c'est des jours VPN tunnel DOWNet d'autres jours non!
le hic c'est que quand c'est tunnel down, les ports ne sont plus ouverts depuis l'exterieur!!!

**Comment by Ysurac** [comment]
Ouvre ta propre issue, car il me faudra toute les infos du template (versions etc...).
