### ISSUE TITLE
Port forwarding can't be configured anymore 0.54

### ISSUE THREAD

**Issue by xabix** [Ysurac/openmptcprouter#883]
## Expected Behavior

Hello,

I don't seem to be able to select an IP port but even IP adresses are not showing correctly
https://github.com/Ysurac/openmptcprouter/wiki/Port-forwarding

![image](https://user-images.githubusercontent.com/394407/76459473-8e534c00-63dc-11ea-82e4-e951b36047bb.png)

## Specifications

  - OpenMPTCProuter version: 0.54
  - OpenMPTCProuter VPS version:  0.1013
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
Refresh browser cache.
