### ISSUE TITLE
Wireguard support

### ISSUE THREAD

**Issue by xabix** [Ysurac/openmptcprouter#884]
## Expected Behavior

Hello Ysurac,

Is there a plan to enhance OMR to support https://www.wireguard.com/ ?

It seems that this would use less ressources and be easier to setup than IPsec etc...
This may not be a priority but just curious if you were thinking to add this as a supported protocol.

From a closed previous issue it seems that the protocol didn't support aggregation. Is it still the same ?
https://github.com/Ysurac/openmptcprouter/issues/266

Merci
XabiX

**Comment by Ysurac** [comment]
Wireguard is installed on OpenMPTCProuter, but it's based on UDP so no aggregation support with it.

**Comment by anton000** [comment]
@xabix  have you tried looking at  https://github.com/wangyu-/udp2raw-tunnel

**Comment by Ysurac** [comment]
udp2raw do some fake TCP traffic, this doesn't work with Multipath TCP. At least from my tests.
