### ISSUE TITLE
Impossible to activate MLVPN support using scripts

### ISSUE THREAD

**Issue by denisvic** [Ysurac/openmptcprouter#89]
## Expected Behavior

Automatic script with MLVPN option should download a script to activate MLVPN support.

## Actual Behavior

Automatic script doesn't like right URL (error 404)
if [ "$MLVPN" = "yes" ]; then
	cd /tmp
	wget -O /tmp/debian9-x86_64-mlvpn.sh http://www.openmptcprouter.com/server/debian-x86_64-mlvpn.sh
	sh debian9-x86_64-mlvpn.sh
fi

It should be 
if [ "$MLVPN" = "yes" ]; then
	cd /tmp
	wget -O /tmp/debian9-x86_64-mlvpn.sh http://www.openmptcprouter.com/server/debian9-x86_64-mlvpn.sh
	sh debian9-x86_64-mlvpn.sh
fi

Script "debian9-x86_64-mlvpn.sh" doesn't work here's last error : 
checking whether to enable remote control system (cli and http)... yes
checking whether to enable libpcap support for filters... yes
checking for libpcap... no
checking pcap.h usability... no
checking pcap.h presence... no
checking for pcap.h... no
configure: error: "pcap.h not found"

**Comment by Ysurac** [comment]
Should be fixed now.
