### ISSUE TITLE
Quota broke WAN interface

### ISSUE THREAD

**Issue by Eltarius** [Ysurac/openmptcprouter#890]
## Before activate Quota
![image](https://user-images.githubusercontent.com/15571859/76577854-d9498e00-64c6-11ea-9205-0b7a6c908e73.png)

## After activate Quota on WAN2 for example
![image](https://user-images.githubusercontent.com/15571859/76577887-f0887b80-64c6-11ea-9494-74cdbbc918c8.png)
![image](https://user-images.githubusercontent.com/15571859/76578054-9f2cbc00-64c7-11ea-9721-197c2e8b7359.png)

## Steps to Reproduce the Problem

  1. Activate Quota
  2. Wan broken, "noip defined" but ok in assistant wizard
  3. Deactivate Quota
  4. Wan always broken
  5. Reboot, and now ok

## Specifications

   - OpenMPTCProuter version: 0.54.1
   - OpenMPTCProuter VPS version: 0.10.14
   - OpenMPTCProuter platform: x86_64 (VM)

Thx in advance ;)

**Comment by Ysurac** [comment]
This will be fixed in next release.
