### ISSUE TITLE
MPTCP over VPN not working

### ISSUE THREAD

**Issue by ccmks** [Ysurac/openmptcprouter#891]
## Expected Behavior
Expect to get MPTCP work over VPN for MPTCP blocked connection
  

## Actual Behavior
Doesn't get MPTCP to work over VPN, or I might be missing some settings

## Steps to Reproduce the Problem

  1. Flash my Banana Pi R2 with v0.53.3 r0+11546-a74095c68c (I never get to work with v0.54 because the device will be in reboot loop when flashing to v0.54)
  2. Put the server key and VPS IP address and set all WAN to be DHCP
  3. 1st WAN works with MPTCP, but the 2nd WAN is not working with MPTCP, however, it doesn't say the MPTCP is being blocked on the status page. But still doesn't do aggregation when check on bandwidth while performing download test on PC

## Specifications

  - OpenMPTCProuter version: v0.53.3 r0+11546-a74095c68c
  - OpenMPTCProuter VPS version: 0.1014 4.19.104-mptcp
  - OpenMPTCProuter platform: Banana Pi R2

![image](https://user-images.githubusercontent.com/49300986/76638512-edbb7400-6522-11ea-853d-9677f2850c88.png)

**Comment by Ysurac** [comment]
No support on old release, so I'm checking why OpenMPTCProuter reboot on BPI-R2.

**Comment by ccmks** [comment]
I got the MPTCP working over VPN, just didn't see the extra setting on each
WAN in the first place.

But still I can't flash the v0.54 to Banana Pi R2.

Keeps rebooting in loop

**Comment by ccmks** [comment]
Any news?

**Comment by Ysurac** [comment]
I work on free time, so no. For now I can't make it work with current kernel.
