### ISSUE TITLE
DMZ - Forward all port from VPS directly to client behind OpenMPTCPRouter

### ISSUE THREAD

**Issue by ccmks** [Ysurac/openmptcprouter#894]
How can I forward all port from VPS directly to a client behind OpenMPTCPRouter?

Usually, on consumer router, we will just look for DMZ which open all port for specific client behind the router.

OpenMPTCProuter version: v0.53.3 r0+11546-a74095c68c
OpenMPTCProuter VPS version: 0.1014 4.19.104-mptcp
OpenMPTCProuter platform: Banana Pi R2

**Comment by Eltarius** [comment]
Like this ????
![image](https://user-images.githubusercontent.com/15571859/76703883-695d2280-66d5-11ea-8f0c-16ce715bfe33.png)

(Network > Firewall > Port forwards)

Try it, it seem work

**Comment by ccmks** [comment]
Doesn't work for me. I don't have option to select protocol as "any"

**Comment by Eltarius** [comment]
For me:
![image](https://user-images.githubusercontent.com/15571859/76705652-ef7f6600-66e1-11ea-9ec3-be60660ad2cf.png)

Can you print your screen?
I'm on v0.54.2, perhaps v0.53.3 does not have this option

**Comment by ccmks** [comment]
Here is mine

![image](https://user-images.githubusercontent.com/49300986/76705812-bfee4f00-671d-11ea-90f5-6f471102d949.png)


I can update to v0.54 because I am on Banana Pi R2 which will keep booting in loop after flashing the v0.54

**Comment by maxou56** [comment]
If "Any" is not available.
Select for example: TCP + UDP and for external port "1-64999"
And check "Redirects all ports from server to OpenMPTCProuter" (System - OpenMPTCProuter - advanced settings)

**Comment by ccmks** [comment]
Tried that too, still not working. I guess the Banana Pi version is not
working well
