### ISSUE TITLE
Best DCHP V6 setting for LAN -advice - 

### ISSUE THREAD

**Issue by vinceducat** [Ysurac/openmptcprouter#897]
## Expected Behavior

what is the best dhcpv6 setting for LAN in case off the WAN1 is a FAI router that is supporting IPV6 and not disableable ...

![dhcpipv6LAN](https://user-images.githubusercontent.com/18363979/76687844-0a8d9f80-6628-11ea-9b7a-35e87d9a3b5f.jpg)

  - OpenMPTCProuter version: 054.4
  - OpenMPTCProuter VPS version: 1006-test1
  - OpenMPTCProuter platform: RPI3

**Comment by Ysurac** [comment]
It's not related to any IPv6 that the FAI can give.
What you want to do ?

**Comment by vinceducat** [comment]
Could it be possible that : 
device on LAN receive ipv6 global adresse from FAI router (ipv6 /64 block) but use the agregrate link throught OMR ... 

perhaps it is not possible .... 




De: "Ycarus (Yannick Chabanois)" <notifications@github.com> 
À: "Ysurac/openmptcprouter" <openmptcprouter@noreply.github.com> 
Cc: "vincentmeunier" <vincentmeunier@free.fr>, "Author" <author@noreply.github.com> 
Envoyé: Samedi 14 Mars 2020 19:22:24 
Objet: Re: [Ysurac/openmptcprouter] Best DCHP V6 setting for LAN -advice - (#897) 





It's not related to any IPv6 that the FAI can give. 
What you want to do ?

**Comment by Ysurac** [comment]
If a device receive IPv6 from ISP and use it as default gateway,  then the device will not use the aggregated link.
So IPv6 from any ISP must be disabled or IPv6 from OpenMPTCProuter must used as default gateway.
