### ISSUE TITLE
how to edit the code

### ISSUE THREAD

**Issue by zulu14** [Ysurac/openmptcprouter#898]
## Expected Behavior

hi first thanxs for creating this awsome router, 
can i modify the code? 
how can i edit it ? 
have a nice day 
## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - OpenMPTCProuter version: (Last is not a version)
  - OpenMPTCProuter VPS version: (Last is not a version)
  - OpenMPTCProuter platform: (RPI2/RPI3/x86/x86_64)

**Comment by Ysurac** [comment]
All code is on github under GPL3 licence for most part.
All links are available on www.openmptcprouter.com.
