### ISSUE TITLE
VPS TCP and UDP failover

### ISSUE THREAD

**Issue by Ysurac** [Ysurac/openmptcprouter#9]
HAproxy only work for tcp.
Nginx can work for TCP and UDP.

Replace HAproxy by Nginx and create a LuCI interface

**Comment by Ysurac** [comment]
Nginx is used now instead of HAProxy.

Need to make a better interface.

**Comment by Ysurac** [comment]
Tests and documentation needed for that.

**Comment by Ysurac** [comment]
For now it's not working at all...
Need to find why it's not working with Nginx now...

**Comment by Neustradamus** [comment]
@Ysurac; Any news?

**Comment by Ysurac** [comment]
New method will be used in 0.55
