### ISSUE TITLE
OpenMPTCPRouter commands

### ISSUE THREAD

**Issue by rubaz100** [Ysurac/openmptcprouter#906]
## Expected Behavior

I want to to test the aggregation and I want to test the WANs speed

How can I do it? Are there commands for the OpenMPTCPRouter and VPS?

Where can I find all commands for testing

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - OpenMPTCProuter version: (all)
  - OpenMPTCProuter VPS version: (all)
  - OpenMPTCProuter platform: (all)

**Comment by Ysurac** [comment]
You can use ```omr-test-speed``` to test aggregated speed, and ```omr-test-speed wan1``` to test speed on wan1 via SSH on the router. ctrl+c to stop the test. This download a file from OVH.
There is also iperf available via ```omr-iperf``` on the router
