### ISSUE TITLE
Constant need to restart the interface on 4G router

### ISSUE THREAD

**Issue by G000R000** [Ysurac/openmptcprouter#918]
## Expected Behavior

Having bonded internet connections 24/7 (ADSL + 4G)

## Actual Behavior

After some time (i can't really say when), my connection is only the ADSL (wan1). I found that i have to manually restart the network>interface of my 4G router in order to have both connections bonded. I do that once a day i'd say, or when i need to download faster

Both routers have standard configurations and i do not mess with them. Maybe i'm missing something quite simple, but if you have any tips, please help

## Steps to Reproduce the Problem

  1. Test my internet speed -> connections are not bonded anymore
  2. Restart the network interface on WAN2 (my 4G router)
  3. Profit the powerful internet

## Specifications

  - OpenMPTCProuter version: 0.54.6
  - OpenMPTCProuter VPS version: 0.1015
  - OpenMPTCProuter platform: RPI3

**Comment by Ysurac** [comment]
When you have the problem, check in Network->MPTCP and MPTCP fullmesh tab that all wan IPs are here, check also using the ```multipath``` command via SSH on the router that all WANs interfaces are set as default (everything else should be set as deactivated). Check also in State->System Log and kernel log that you have no errors.

**Comment by G000R000** [comment]
Hello,
I have the problem right now (seeing only 6mb on speedtest (it's my dsl limit) :

- MPTCP and MPTCP fullmesh tab that all wan IPs are here : both connections IP are there 
![image](https://user-images.githubusercontent.com/46853280/77248913-8ba6f100-6c3d-11ea-9f39-2fbbf3e962b7.png)

 - system log :  
![image](https://user-images.githubusercontent.com/46853280/77248935-b2652780-6c3d-11ea-985c-1edefeb29842.png)

- kernel log : not sure what to give you, as theres a lot of lines
![image](https://user-images.githubusercontent.com/46853280/77248966-0ec84700-6c3e-11ea-8d11-e29917c79836.png)

- command via SSH on the router that all WANs interfaces are set as default : 
![image](https://user-images.githubusercontent.com/46853280/77249019-767e9200-6c3e-11ea-87db-ca1517fc3f45.png)


I can restart the interface to give you the "after" if  you want, or more details if needed

**Comment by Ysurac** [comment]
I see no errors...
You can try another Multipath TCP scheduler in Network->MPTCP like BLEST.

**Comment by gnosoz** [comment]
i am finding the best results for hybrid connections 4g + cabled to be
achieved by fullmesh + ECF + bbr

**Comment by G000R000** [comment]
Thanks to you both, i'll try BLEST and ECF : here are my new settings (i'll try BLEST later), i can keep you posted if you want.

Maybe something else in wrong in these settings ? WAN1 is DSL, WAN2 is 4G :

![image](https://user-images.githubusercontent.com/46853280/77249383-032a4f80-6c41-11ea-8b12-bcf20334e934.png)

![image](https://user-images.githubusercontent.com/46853280/77249387-0b828a80-6c41-11ea-91d8-b1c9346c586c.png)

**Comment by G000R000** [comment]
After a few days, i tried both TCP scheduler but it didn't work, i still have to restart the wan2 interface manually to have both connections "up"
