### ISSUE TITLE
Adding ip address(+port definition) to DNS forwarders does not work

### ISSUE THREAD

**Issue by Olli69** [Ysurac/openmptcprouter#919]
## Expected Behavior
Network / DHCP and DNS / DNS forwarders configuration should allow adding ip or ip#port definition.

(I do not understand yet DNS forwarding in detail, but I suppose that you should be able to add the same definition what was found in the default config. For me, it looks like invalid UI validation ). 
Default config:
<img width="424" alt="Screenshot 2020-03-22 at 9 58 01-default-config" src="https://user-images.githubusercontent.com/1752838/77246170-3d89f180-6c2d-11ea-9ef2-e649b66e45e0.png">

## Actual Behavior
There  "127.0.0.1#5353" in the default config, but if you remove it you cannot add the same definition any more. UI gives an error "Expecting: valid hostname" when you try to add it.

## Steps to Reproduce the Problem

  1. Restore existing config or edit config so that "127.0.0.1#5353" is not in the list of DNS forwards 
  2. Add (try to) "127.0.0.1#5353" to list of DNS forwarders
  3. User interface shows a message: "Expecting: valid hostname" and does not allow adding a new DNS forwarder
<img width="427" alt="Screenshot 2020-03-22 at 10 39 44-ip-not-ok-without-prefix" src="https://user-images.githubusercontent.com/1752838/77246169-3c58c480-6c2d-11ea-95c9-afa3e182decd.png">
  4. With a prefix you can add it.
<img width="408" alt="Screenshot 2020-03-22 at 10 43 17--with-prefix-ok" src="https://user-images.githubusercontent.com/1752838/77246165-3a8f0100-6c2d-11ea-8ec2-43161bb49a1e.png">
  

## Specifications

  - OpenMPTCProuter version: 0.54.7 RPi 
  - OpenMPTCProuter VPS version: 0.1015 
 - OpenMPTCProuter platform: RPI4 x86_64

**Comment by Ysurac** [comment]
It's a new limit of this OpenWrt interface. But the same value can be put in "Local server" and this will work in the same way.
