### ISSUE TITLE
Cant't add a new port forward

### ISSUE THREAD

**Issue by artiflo** [Ysurac/openmptcprouter#920]
## Expected Behavior

After upagrade to 0.54.7 and 0.1015 I cant't add a new port forward.

## Actual Behavior

Can't add a new port forward because when I try to select an Internal IP Adress I have object call [object DocumentFragment]

Same issue when I try to edit a existent one.
![object DocumentFragment](https://user-images.githubusercontent.com/14591424/77253932-1992d400-6c5e-11ea-9e2a-cf3e3fd0f208.PNG)

## Steps to Reproduce the Problem

  1. Go to Network> Firewall > Port Forwards
  2. Click on add to add new port Forward
  3. Click on dropdown menu "Internal IP adress"

## Specifications

  - OpenMPTCProuter version: 0.54.7
  - OpenMPTCProuter VPS version: 0.1015
  - OpenMPTCProuter platform: RPI3/x86_64)

**Comment by Ysurac** [comment]
Refresh browser cache.

**Comment by artiflo** [comment]
Sorry, indeed that was browser cache.
