### ISSUE TITLE
Technical documentation: optimize Shadowsocks

### ISSUE THREAD

**Issue by xabix** [Ysurac/openmptcprouter#926]
## Expected Behavior

Hello,

I found the below page referred in some earlier posts in order to optimize Shadowsocks http://mptcp.zugaina.com/

My VPS is running on Buster.

Is it safe to apply those optimizations?

VPS: An example of working /etc/sysctl.d/local.conf:
> # max open files
> fs.file-max = 51200
> # max read buffer
> net.core.rmem_max = 67108864
> # max write buffer
> net.core.wmem_max = 67108864
> # default read buffer
> net.core.rmem_default = 65536
> # default write buffer
> net.core.wmem_default = 65536
> # max processor input queue
> net.core.netdev_max_backlog = 4096
> # max backlog
> net.core.somaxconn = 4096
> # resist SYN flood attacks
> net.ipv4.tcp_syncookies = 1
> # reuse timewait sockets when safe
> net.ipv4.tcp_tw_reuse = 1
> # turn off fast timewait sockets recycling
> net.ipv4.tcp_tw_recycle = 0
> # short FIN timeout
> net.ipv4.tcp_fin_timeout = 30
> # short keepalive time
> net.ipv4.tcp_keepalive_time = 1200
> # outbound port range
> net.ipv4.ip_local_port_range = 10000 65000
> # max SYN backlog
> net.ipv4.tcp_max_syn_backlog = 4096
> # max timewait sockets held by system simultaneously
> net.ipv4.tcp_max_tw_buckets = 5000
> # turn on TCP Fast Open on both client and server side
> net.ipv4.tcp_fastopen = 3
> # TCP receive buffer
> net.ipv4.tcp_rmem = 4096 87380 67108864
> # TCP write buffer
> net.ipv4.tcp_wmem = 4096 65536 67108864
> # turn on path MTU discovery
> net.ipv4.tcp_mtu_probing = 1
> # for high-latency network
> net.ipv4.tcp_congestion_control = iloa

Router:

> # max open files
> fs.file-max = 51200
> # max read buffer
> net.core.rmem_max = 67108864
> # max write buffer
> net.core.wmem_max = 67108864
> # default read buffer
> net.core.rmem_default = 65536
> # default write buffer
> net.core.wmem_default = 65536
> # max processor input queue
> net.core.netdev_max_backlog = 4096
> # max backlog
> net.core.somaxconn = 4096
> # resist SYN flood attacks
> net.ipv4.tcp_syncookies = 1
> # reuse timewait sockets when safe
> net.ipv4.tcp_tw_reuse = 1
> # turn off fast timewait sockets recycling
> net.ipv4.tcp_tw_recycle = 0
> # short FIN timeout
> net.ipv4.tcp_fin_timeout = 30
> # short keepalive time
> net.ipv4.tcp_keepalive_time = 1200
> # outbound port range
> net.ipv4.ip_local_port_range = 10000 65000
> # max SYN backlog
> net.ipv4.tcp_max_syn_backlog = 4096
> # max timewait sockets held by system simultaneously
> net.ipv4.tcp_max_tw_buckets = 5000
> # turn on TCP Fast Open on both client and server side
> net.ipv4.tcp_fastopen = 3
> # TCP receive buffer
> net.ipv4.tcp_rmem = 4096 87380 67108864
> # TCP write buffer
> net.ipv4.tcp_wmem = 4096 65536 67108864
> # turn on path MTU discovery
> net.ipv4.tcp_mtu_probing = 1
> # for high-latency network
> net.ipv4.tcp_congestion_control = iloa

## Actual Behavior

Are the optimizations set by default or is there anything that is worth doing still?

Merci
XabiX

**Comment by Ysurac** [comment]
They are already applied by default
