### ISSUE TITLE
Edit or add a new port forwarding is not possible

### ISSUE THREAD

**Issue by tboome33** [Ysurac/openmptcprouter#927]
Pare-feu - Redirections de ports : nouvelle redirection et modification impossible
Edit or add a new port forwarding is not possible

Hi,

I can't edit or create new port forwarding.

If you edit a port forwarding, you can't find the port field and all internal ip addresses are not displayed. Instead the ip adresses an [object Document Field] token is displayed 

You can't also add a new port forwarding. It's the same problem

Go to Network/Firewall/Port forwarding (second tab) to see the problem

Great regards

Roland

  - OpenMPTCProuter version: openmptcprouter v0.54.7 r0+12509-04a21c26a0
  - OpenMPTCProuter VPS version: Debian 10 Buster x86_64   
  - OpenMPTCProuter platform: Pi 4

**Comment by Ysurac** [comment]
Refresh browser cache
