### ISSUE TITLE
Difference and Use of ip.openmptcprouter.com vs hostname.openmptcprouter.com

### ISSUE THREAD

**Issue by xabix** [Ysurac/openmptcprouter#928]
## Expected Behavior

Hello Ysurac,

I see in my Pi-hole on the VPS a lot of queries to ip or hostname @ openmptcprouter.com.
I assume one of them is for OMR to check for a newer release but I am surprised to see both of them on my top 3.

Any explication of the difference between ip. and hostname. and is it correct that they both go to the same IP or could it be that something is not right in my setup.

![image](https://user-images.githubusercontent.com/394407/77449029-c9e51180-6df1-11ea-9ae4-449a44cf08cc.png)

In terms of frequency, this is what I see:
![image](https://user-images.githubusercontent.com/394407/77449464-3eb84b80-6df2-11ea-9aa8-8e609404ac16.png)

> dig hostname.openmptcprouter.com
> ; <<>> DiG 9.16.0-Ubuntu <<>> hostname.openmptcprouter.com
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 39266
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 65494
> ;; QUESTION SECTION:
> ;hostname.openmptcprouter.com.  IN      A
> ;; ANSWER SECTION:
> hostname.openmptcprouter.com. 4634 IN   A       94.23.252.192
> ;; Query time: 0 msec
> ;; SERVER: 127.0.0.53#53(127.0.0.53)
> ;; WHEN: mar. mars 24 17:02:37 CET 2020
> ;; MSG SIZE  rcvd: 73

> dig ip.openmptcprouter.com
> ; <<>> DiG 9.16.0-Ubuntu <<>> ip.openmptcprouter.com
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 44107
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 65494
> ;; QUESTION SECTION:
> ;ip.openmptcprouter.com.                IN      A
> ;; ANSWER SECTION:
> ip.openmptcprouter.com. 5186    IN      A       94.23.252.192
> ;; Query time: 0 msec
> ;; SERVER: 127.0.0.53#53(127.0.0.53)
> ;; WHEN: mar. mars 24 17:02:45 CET 2020
> ;; MSG SIZE  rcvd: 67

## Specifications

OpenMPTCProuter version: v0.54.7
OpenMPTCProuter VPS version: 0.1015
OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
ip.openmptcprouter.com is used to get IP of WANs and to get actual exit IP from the router.
hostname.openmptcprouter.com is used to get the reverse from the API script, this is used by obfuscation. I will remove this call and add it as variable in API conf.

**Comment by xabix** [comment]
Thank you so it's all OK with my setup (aka getting the same DNS resolution on both) as well as in terms of frequency?

Have a good evening

**Comment by Ysurac** [comment]
Yes, no problems.
