### ISSUE TITLE
Plusieurs problèmes avec openmptcrouter

### ISSUE THREAD

**Issue by jeandelamarquise** [Ysurac/openmptcprouter#929]
## Expected Behavior

I'm trying to put an ip adress on specific device (like amazon fire stick) because netflix and prime video blocked me with ovh... (i think)
Need to find solution for netflix, prime video and freebox tv.

## Actual Behavior
I think i found where to do so but openmptcrouter said change not apply. I click on the button and wait... but nothing happened and there is always some changes not applied.

## Steps to Reproduce the Problem

  1. put a mac adress with specific ip with specific wlan
  2. click on change not apply
  3. not working...

## Specifications

  - OpenMPTCProuter version:  v0.54.2 r0+12464-a017773a92
  - OpenMPTCProuter VPS version: 0.1015
  - OpenMPTCProuter platform: openmptcprouter v0.54.2 r0+12464-a017773a92

**Comment by jeandelamarquise** [comment]
![omr2](https://user-images.githubusercontent.com/53608408/77471061-f577f400-6e11-11ea-8990-92f4b42c5a92.png)
![omr](https://user-images.githubusercontent.com/53608408/77471064-f6a92100-6e11-11ea-99cd-aac7886cfb53.png)
![omr3](https://user-images.githubusercontent.com/53608408/77471065-f6a92100-6e11-11ea-87e0-b3174d1ebcc8.png)
![image](https://user-images.githubusercontent.com/53608408/77471073-f90b7b00-6e11-11ea-83a0-c12ac83c9e97.png)

**Comment by Ysurac** [comment]
The filesystem is read only so changes can't be saved.
This happen when filesystem is corrupted after power is unplugged or when SD card is died.
You can try a reboot, if it can be repaired this will be done.

**Comment by jeandelamarquise** [comment]
Ok, i reboot and dont have the filesystem read only.I don't find how to Do for Netflix, prime video and freebox tv and my fire stick.Can you help me ? In french ? :DThanks for all. This changes my life :) need to steak it with your help.BillyLe 24 mars 2020 21:26, "Ycarus (Yannick Chabanois)" <notifications@github.com> a écrit :
The filesystem is read only so changes can't be saved.
This happen when filesystem is corrupted after power is unplugged or when SD card is died.
You can try a reboot, if it can be repaired this will be done.

**Comment by Ysurac** [comment]
Use OMR-ByPass and set Protocol/Services. OpenMPTCProuter must be used as DNS on clients.

**Comment by jeandelamarquise** [comment]
I think that and i try to out for example my firestick on the same lan adresses that my freebox and set to wlan1.I put à screenshot about that. Is that ok ?How can i do to make freebox tv to work ?Le 24 mars 2020 21:44, "Ycarus (Yannick Chabanois)" <notifications@github.com> a écrit :
Use OMR-ByPass and set Protocol/Services. OpenMPTCProuter must be used as DNS on clients.
