### ISSUE TITLE
DHCP exclude MAC

### ISSUE THREAD

**Issue by gaalos** [Ysurac/openmptcprouter#932]
## Expected Behavior
Hi want to exlude MAC adress from DHCP openmptcprouter
For exemple i'm using Orange Router with Orange TV
My Orange TV must use ORANGE Router only

  - OpenMPTCProuter version: v0.54.7 r0+12509-04a21c26a0

Maybe it's request feature like 
Static DHCP with other gateway 
Or Exclude mac 

I can use external DHCP server but i prefer manage it there

Best regards

**Comment by bnhf** [comment]
Having multiple gateways on the same LAN requires some specialized setup on your part:

First, you don't want more than one active DHCP server, so turn off DHCP on your Orange router. Second, set a static address on the Orange TV that's within the range of the Orange router's subnet.

Do those two things and your Orange TV will use the Orange router, and everything else on your network will get IP addresses from the DHCP server on your OpenMPTCProuter.

**Comment by gaalos** [comment]
I can't use static ip on my orange TV :/ and the orange TV refuse other DHCP :/ 
Best regards

**Comment by bnhf** [comment]
Maybe you could do something like this:

https://bokunokeiken.wordpress.com/2015/06/27/how-to-block-device-on-openwrt-based-on-mac-address/

But aren't you still going to have a problem with the Orange router's DHCP competing with the OpenMPTCProuter's DHCP? You didn't say, but I'm assuming everything is Ethernet connected here?    The other option that comes to mind would be to use a managed switch and VLANs to keep your traffic separated.

**Comment by gaalos** [comment]
@bnhf 
unfortunatly i don't have L2 switch ^^ 
The orange box block all DHCP except the orange router (Yes this is Sh*t)

**Comment by bnhf** [comment]
Worth a try to block the MAC address of the Orange TV on the OpenMPTCProuter using the technique in the link I sent you, no?

**Comment by gaalos** [comment]
@bnhf this is exactly what i want ;) i'll reply soon ;)

**Comment by cron410** [comment]
@gaalos please let us know how it worked out.
