### ISSUE TITLE
vnstat complains about tun0 speed of 10Mbit

### ISSUE THREAD

**Issue by xabix** [Ysurac/openmptcprouter#935]
## Expected Behavior

Hello,

I have such error messages:
![image](https://user-images.githubusercontent.com/394407/77635194-7f2edb00-6f52-11ea-8699-7c8b5f5eee4d.png)

From this thrread it looks like some tweaking should be done to be solved:
https://github.com/vergoh/vnstat/issues/81

Is there anything to be done in OMR sw or should it be done manually?

Merci

**Comment by Ysurac** [comment]
```tun0``` shouldn't be added to vnstat. You added it manually ?

**Comment by xabix** [comment]
No, the issue came to the fact that I added a wan4 through "Setting Wizard" with SQM and then I deleted it but it looks like than in SQM menu the entry stayed but was then referring to tun0 instead of wan4.
Not a big issue but it took me some time to figure out and had instabilities.
