### ISSUE TITLE
wan2 (slave) is barely utilized

### ISSUE THREAD

**Issue by gitxmax** [Ysurac/openmptcprouter#942]
## Expected Behavior
total speed is close to wan1 +wan2

  In English please.

## Actual Behavior
wan2 is not really utilized, when wan1 is set as master and wan2 as enabled

## Steps to Reproduce the Problem

  1. Clean install of both router and vpn firmwares
  2. wan1 is eth0 wan2 is usb0 (both set in Macvlan)
  3. Running various speed tests

## Specifications

  - OpenMPTCProuter version: openmptcprouter v0.54.7 r0+12509-04a21c26a0
  - OpenMPTCProuter VPS version: v0.1015
  - OpenMPTCProuter platform: x86_64

Hello,
my wan1 is a broadband connection, attached to eth0 in macvlan, maxiing out at 4mbps, but unlimited
wan2 is a 4g router, connected via usb, macvlan set to usb0 but limited to 14gb/month

My idea is to use wan2, as a backup, when the wan1 speed is not sufficient.

the problem is, whatever connection I set to "Master"  is giving a full speed, the other "slave" connection is almost not used, perhaps 10% at maximum.

So, if I set wan1 as master and wan2 as enabled, I get total speed ~=wan1 speed
if I set wan2 as master and wan1 as enabled, I get total speed ~=wan2 speed

openmptcprouter/status shows everything GREEN
VPS is installed on 1gb ram google cloud instance with all ports open

Tried running the built-in speed test, it confirm the situation, wan2 is running at 10% of the real speed, when wan1 is master.

**Comment by bnhf** [comment]
Macvlan may be your problem here. Since each of your WANs is on a separate physical interface it's not required and may be causing issues. Macvlan is used when you have a single Ethernet port and you'd like to share it using an unmanaged switch.

Try deleting the Macvlan entries, and then check your interface assignments under Network - Interfaces to be sure wan1 and wan2 are assigned to the correct physical interfaces rather than the virtual Macvlan interfaces. It's worth checking that each remains assigned to the wan firewall zone too.

Couldn't hurt to reboot the router after making the changes.

**Comment by gitxmax** [comment]
Thanks.
I removed all the instances from Macvlan and made sure everything is correct in Interfaces. Multiple reboots done also. Sadly, nothing has really changed, still only the Master deals with all the traffic...

![image](https://user-images.githubusercontent.com/34851333/78167821-b4bb5300-7481-11ea-838c-224177a33a9a.png)
![image](https://user-images.githubusercontent.com/34851333/78167847-bc7af780-7481-11ea-8bc7-f0e2db3d9b21.png)
![image](https://user-images.githubusercontent.com/34851333/78167861-c3096f00-7481-11ea-8955-5fe365a72829.png)

**Comment by Ysurac** [comment]
Check in Network->MPTCP and MPTCP fullmesh that you have all WAN IPs.
Check also in State->System log if you have no error.

**Comment by bnhf** [comment]
Do you have a monthly Quota set on either interface -- or are you trying to use SQM?
Are download speed and upload speed both set to 0 for both interfaces in the OMR Wizard?

**Comment by gitxmax** [comment]
Haven't really change any default settings, so yes, no quotas, no sqm..

![image](https://user-images.githubusercontent.com/34851333/78181159-7bd9a900-7496-11ea-98cb-9f4e80443e2e.png)
![image](https://user-images.githubusercontent.com/34851333/78181178-8136f380-7496-11ea-9e4b-e99ccfae8c1a.png)
![image](https://user-images.githubusercontent.com/34851333/78181201-87c56b00-7496-11ea-9f6b-ebd06d2f5b6e.png)
![image](https://user-images.githubusercontent.com/34851333/78181219-8f850f80-7496-11ea-8de1-cd15b87d7d7c.png)

Errot log: https://drive.google.com/open?id=1vo53nDmIp6lK7u7qVoDsuv9Rvg6RzIwp
Full settings: https://drive.google.com/open?id=1dBW0XzFGSa3P3Z-OoQpNZfBlyhT54Vox

**Comment by gitxmax** [comment]
Just want to post an update
I tried the second eth2 connection, instead of the usb0 and all seems to work fine.
I guess, it has something to do with the usb connection..

**Comment by Ysurac** [comment]
How did you test eth2 ? The router have a eth connection ?

**Comment by gitxmax** [comment]
nope, attached a different broadband router, using a different ISP
