### ISSUE TITLE
Error compiling firmware

### ISSUE THREAD

**Issue by cybercraft-fr** [Ysurac/openmptcprouter#947]
Hi,

I tried compiling an image for Mediatek 7620 (Dlink-DWR118), kernel compilations ended with patching error:

Hunk #4 FAILED at 1710.
1 out of 4 hunks FAILED -- saving rejects to file net/core/sock.c.rej
...

Patch failed!  Please fix /home/vps/openmptcprouter/myplatform/source/target/linux/generic/hack-4.14/690-mptcp_v0.94.patch!
make[3]: *** [Makefile:115: /home/vps/openmptcprouter/myplatform/source/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/linux-4.14.172/.prepared] Error 1
make[3]: Leaving directory '/home/vps/openmptcprouter/myplatform/source/toolchain/kernel-headers'
time: toolchain/kernel-headers/compile#13.58#5.90#23.38

**Comment by Ysurac** [comment]
It's not a supported platform and it's on 4.14 kernel, you will have to make the change to the patch yourself.
