### ISSUE TITLE
Bad upload via openmtpcprouter

### ISSUE THREAD

**Issue by kevin39** [Ysurac/openmptcprouter#949]
Hi

## Expected Behavior
Stable and good upload. At least similar than without openmtcprouter.

## Actual Behavior
Using openmtcprouter, my upload is poor/unstable.

## Steps to Reproduce the Problem
I'm using two 4G connections.
Using 1 box my upload is better than with OpenMTCPRouter.

## Specifications

  - OpenMPTCProuter version: openmptcprouter v0.52.3 r0+11006-713561a10b
  - OpenMPTCProuter VPS version: 0.1001 4.19.67-mptcp
  - OpenMPTCProuter platform: Raspberry Pi 4 Model B Rev 1.2
Note : I know I'm not on the last release but it's a professional usage and due to covid-19 I do not want increase my risk to lost my connection is case of upgrade problems. I hope you understand.

## Screenshots :
With openmtcprouter : (connected to two 4g connections)
![Screenshot1](https://user-images.githubusercontent.com/976058/78233787-8f0c6900-74d6-11ea-9cdd-5675b60e012c.jpeg)

Without openmtcprouter : (using one 4g connection)
![Screenshot2](https://user-images.githubusercontent.com/976058/78233783-8ddb3c00-74d6-11ea-959c-ab1e149c4a5b.jpeg)

**Comment by Ysurac** [comment]
Please use Issue template...

**Comment by kevin39** [comment]
Sorry. Fixed.

**Comment by Ysurac** [comment]
You can try in Network->MPTCP another Multipath TCP scheduler like BLEST and try other TCP Congestion Control.

**Comment by kevin39** [comment]
I'm already using BLEST.
Anyway, I tried once again all settings. All are having same behavior with my upload.

**Comment by bnhf** [comment]
Given the modest increases you're seeing on the download side, and the instability you're reporting on the upload side, perhaps there's not really that much risk in upgrading? Falling back to a single connection looks to be better than what you have going now. It's always best to be on the latest release with a leading-edge package like this.

**Comment by kevin39** [comment]
FYI : 
- Bad upload test using nperf.com
- Upload speed using speedtest.net and test.my/upload are OK

Anyway, I was having a bad upload (~1mbs).
I improved my antenna positionning and my upload is now ~8mbs (anyway, nperf test is still very unstable).
