### ISSUE TITLE
Discord Voice and video not work

### ISSUE THREAD

**Issue by vinceducat** [Ysurac/openmptcprouter#951]
## Expected Behavior

  Discord soft for used by my children for contact there friend during game party doesnt work
https://discordapp.com
## Actual Behavior

voice and video dont work : saying probleme of UDP connexion

## Steps to Reproduce the Problem

  1. OMR active
  2. discord soft install on a computer on the lan
  3.

## Specifications

  - OpenMPTCProuter version: 0.54.8
  - OpenMPTCProuter VPS version: 1015
  - OpenMPTCProuter platform: RPI3

Please help ;-)

try OMR bypass for discordapp.com it doesnt work

**Comment by Ysurac** [comment]
Never tested discord...
This doesn't work in which side ? send, receive or both ?

**Comment by vinceducat** [comment]
Both :-(

**Comment by vinceducat** [comment]
Discord seems to be base on Webrtc ... https://support.discordapp.com/hc/fr/articles/115001310031-Erreurs-avec-la-connexion-vocale

**Comment by vinceducat** [comment]
make the test on test.webrtc ... pb of reflexivity

some information but not qn expert https://github.com/webrtc/testrtc/issues/176 perhaps can help you

**Comment by Ysurac** [comment]
Maybe some port to open for discord. I have no idea how I can test discord.

**Comment by vinceducat** [comment]
i will check for discord port ..

you think opening port in OMR or VPS ?

i think test could me made using the https://test.webrtc.org/

**Comment by Ysurac** [comment]
redirecting port from the VPS to OMR. But I have really no idea.

**Comment by vinceducat** [comment]
Paramètres du VPS
vps
Rediriger tous les ports du server vers ce routeur
Désactiver les redirections de ports définis dans la partie pare-feu du serveur vers ce routeur

the 2 options must be on ?

**Comment by Ysurac** [comment]
no and it's better to define the port that need to be redirected instead of redirecting all ports.

**Comment by vinceducat** [comment]
ok ;-)
 

in witch menu can i do this ?

**Comment by Ysurac** [comment]
Network->Firewall
You can follow doc: https://github.com/Ysurac/openmptcprouter/wiki/Port-forwarding

**Comment by vinceducat** [comment]
thanks i will check that...

doc says that discord need large range of udp port 50000-65535 :-(

**Comment by Ysurac** [comment]
Port 65000 to 65535 are reserved for OMR API, VPN,....

**Comment by vinceducat** [comment]
oups ... 

that s the problem .

i made some test, i have a french ISP from Free Freebox V5 and when i in direct not throught OMR all is ok.
with OMR i have no problem with putting my computer lan ip in omr bypass by ip source..


perhaps need to define something in port or in protocole section ... to restrict bypass only for Discord...

**Comment by Ysurac** [comment]
in status page all is green and the VPN was not disabled ?

**Comment by vinceducat** [comment]
yes all is good.

**Comment by vinceducat** [comment]
perhaps test other vpn than Glory TCP ?

**Comment by cron410** [comment]
Have you tried putting `gateway.discord.gg` in OMR-Bypass?

**Comment by vinceducat** [comment]
> 

> 
> 
> Have you tried putting `gateway.discord.gg` in OMR-Bypass?

in "Domain" sub menu in OMR-Bypass ??

**Comment by vinceducat** [comment]
i try to add it in domain sub menu discord voice et audio doesnt work.

**Comment by Ysurac** [comment]
Do you know a way I can test without having any friend on discord ?

**Comment by vinceducat** [comment]
not really... il will think about that ..

**Comment by vinceducat** [comment]
if you have an account on discord i have one too .. we could be friend for test :-)

**Comment by vinceducat** [comment]
@Ysurac always my problem with discord

global omr-bypass work but i will try to limite bypass to "discord" so i find that perhaps this could help me to set-up the omr-bypass or to find a solution 

https://medium.com/tenable-techblog/lets-reverse-engineer-discord-1976773f4626

**Comment by vinceducat** [comment]
new test - new info

video and audio ok when i m disabling ShadowSocks and leave glorytun tcp on ....

**Comment by vinceducat** [comment]
@Ysurac discord seems to used port 50000-65535 is it possible to change shadowsocks port ? ie 49999 to make a test ?

**Comment by Ysurac** [comment]
This test is working or not: https://support.discordapp.com/hc/en-us/articles/360020641332-Mic-Testing ?

**Comment by vinceducat** [comment]
yep it s good ;-)

**Comment by Th0rGer** [comment]
![image](https://user-images.githubusercontent.com/29820906/83143206-e05d6100-a0f1-11ea-8ef4-f137ac3ace22.png)
have you tried to let rtp traffic bypass mptcp?

**Comment by vinceducat** [comment]
yes i try dont change anything but i will retry

**Comment by vinceducat** [comment]
retry doesnt work...
