### ISSUE TITLE
Upload speed cap on 4 Mbps on VPS

### ISSUE THREAD

**Issue by mshost** [Ysurac/openmptcprouter#955]
## Expected Behavior
Normally VPS speed it should be 100 Mbps Download and 100 Mbps Upload 
  In English please.

## Actual Behavior
Before Installing the VPS Script getting Internet Speed on VPS with speedtest-cli 130 Mbps download and 110 Mbps upload speed but after installing MPTCP VPS Script the download speed remain same upload speed is cap on 4 Mbps . 

## Steps to Reproduce the Problem

  1. reinstalling or update VPS script but no improvment
  2.checking different speed test server but no improvment
  3.from DC end enginners told me that there is no cap on etwork

## Specifications

  - OpenMPTCProuter version: 54.7
  - OpenMPTCProuter VPS version: 0.1015
  - OpenMPTCProuter platform: (RPI4B

**Comment by Ysurac** [comment]
It's an issue with old release of ```speedtest-cli``` and BBR TCP Congestion Control, fixed in latest release.
