### ISSUE TITLE
unable to access mptcprouter page at 192.168.100.1

### ISSUE THREAD

**Issue by rajava2010** [Ysurac/openmptcprouter#957]
## Expected Behavior

Expects to open the mptcprouter web page for further configuration @ https://192168.100.1

## Actual Behavior

Downloaded VirtualBox mptcprouter image and started in Mac OS X host 10.13.6,  with 2 adapters 1) with bridged / promiscous mode 2) Host-Only Adapter with 192.168.100.1/24 , after booting not able to access the https://192.168.100.1 from the host. 

## Steps to Reproduce the Problem

  1. check above in actual behaviour.
  2.
  3.

## Specifications

  - OpenMPTCProuter version:  openmptcprouter-v0.54.7-r012509-04a21c26a0-x86-64-combined-ext4-efi.vdi 
  - OpenMPTCProuter VPS version: 0.1013
  - OpenMPTCProuter platform: x86_64

**Comment by Ysurac** [comment]
Why this host only adapter ?

**Comment by rajava2010** [comment]
Even tried without host-only adapter but still failed which is why I created the adapter and tried but both fails.

**Comment by Ysurac** [comment]
Set one interface as bridge, promiscous as Intel PRO/1000 MT and add an IP in the 192.168.100.0/24 network, like 192.168.100.2 to your local computer.

**Comment by rajava2010** [comment]
It worked now after manually setting my wifi en0 interface to 192.168.100.2  and VirtualBox VM Adapter to Bridged Adapter with Promiscous Mode - Allow All. Thanks for your help.
