### ISSUE TITLE
can't reach pi-hole admin interface (Glorytun UDP)

### ISSUE THREAD

**Issue by ArChlOgY** [Ysurac/openmptcprouter#963]
## Expected Behavior
Web interface will be available on 10.255.254.1 if you use Glorytun UDP.

## Current Behavior
Can't reach the admin panel by using 10.255.254.1
From browser : ERR_CONNECTION_REFUSED

## Steps to Reproduce the Problem

  1. Fresh install with OpenMPTCProuter Version 0.54.7 --- VPS Version 0.1015 4.19
  2. All green in Network overview from OpenMPTCProuter with Glorytun UDP
  3. Install Pi-hole on VPS tutorial + Save & Apply' the wizard + Reboot
4.Pi-hole seems to run on VPS server but the admin interface is not reachable

## Specifications

  - OpenMPTCProuter version:  0.54.7
  - OpenMPTCProuter VPS version: 0.1015 4.19
  - OpenMPTCProuter platform: RPI4
  -VPS OVH (Debian 10)

**Comment by lolo31660** [comment]
Hi,
I had the same issue on my side. lighttpd not not starting automatically at VPS reboot (systemctl start lighttpd) . I've started it manually and it worked. Maybe some conflicts because the service is activated to launch at reboot.
