### ISSUE TITLE
Désinstallation de Pi-Hole

### ISSUE THREAD

**Issue by mathchab** [Ysurac/openmptcprouter#964]
## Expected Behavior
Supprimer Pi-Hole.

## Current Behavior
Plus d'accès internet.
GloryTun s'arrête.

"DNS issue"
"No output"

## Possible Solution
Script pour désinstaller Pi-Hole et reset OpenMPTCPRouter

## Steps to Reproduce the Problem

  1. Connexion SSH au VPS
  2. Sudo pihole uninstall
  3. Reset manuellement des DNS
  4. Quand on rapplique l'assistant OpenMPTCPRouter, le DNS redeviens l'IP de Pi-Hole
## Specifications

  - OpenMPTCProuter version: 54.7
  - OpenMPTCProuter VPS version: 1015.4.19104
  - OpenMPTCProuter platform: Pi3+

**Comment by Ysurac** [comment]
Pour vérifier que Pi-Hole est installé sur le serveur, l'API regarde si le fichier ```/etc/pihole/setupVars.conf``` existe. Je ne sais pas ce que fait "pihole uninstall", j'ai jamais essayé.

**Comment by mathchab** [comment]
Du coup, pas de procédure pour revenir en arrière et supprimer Pi-Hôle pour l'instant ?
À l'instant T, obligé de réinstaller Pi-Hôle pour ne pas tout cassé.
J'ai vu votre message trop tard.

**Comment by Ysurac** [comment]
Si donc, en supprimant le fichier ```/etc/pihole/setupVars.conf``` si il est bien toujours présent après l'uninstall de pihole qui serait incomplet donc.

**Comment by notloged** [comment]
Pour moi pihole uninstall a bien fonctionné
