### ISSUE TITLE
Memory Leak ?

### ISSUE THREAD

**Issue by Dragonox77** [Ysurac/openmptcprouter#968]
## Expected Behavior
No memory leak

## Current Behavior
Hello,
I don't know if this behaviour is normal,
http://prntscr.com/rz3a9i (vps side)
Only OMR is installed on it.

## Steps to Reproduce the Problem

  1. Let server run 1 month.

## Specifications

  - OpenMPTCProuter version: 0.54.7
  - OpenMPTCProuter VPS version: 0.1015 4.19.104-mptcp
  - OpenMPTCProuter platform: RPI3 x86_64

**Comment by Ysurac** [comment]
I don't have this memory leak. Nothing special is installed on the the VPS ?
What is the VPN used ?

**Comment by Dragonox77** [comment]
Thanks for your reply.
Only OMR is installed on this vps.
I'm using glorytun TCP.

**Comment by Dragonox77** [comment]
If you need credentials, feel free to ask.

**Comment by Ysurac** [comment]
I only need the result of a ```ps aux``` on the VPS.

**Comment by Dragonox77** [comment]
https://pastebin.com/jkgc2Rcc

**Comment by Dragonox77** [comment]
Sorted by MEM on htop:
http://prntscr.com/rz3w0u

**Comment by Ysurac** [comment]
Looks like an issue with my API script. I'm looking on that.

**Comment by Dragonox77** [comment]
oright.
