### ISSUE TITLE
Question about MTU

### ISSUE THREAD

**Issue by kevin39** [Ysurac/openmptcprouter#970]
Hi,
By default the MTU seems detected by OpenMTCPRouter. Is it a good behavior or tuning it may be required?

I've two 4G connections.
First is currently having a MTU of 1282
Second is currently having a MTU of 1455

I'm wondering if a such difference can decrease multipath performance and if a low MTU of 1282 is a normal behavior ?

**Comment by Ysurac** [comment]
1282 is really low. MTU test should be done every hours, so it's always the same or it's fixed after some times ?

**Comment by kevin39** [comment]
Hi,
This morning, same MTU.

![image](https://user-images.githubusercontent.com/976058/79420475-4914d200-7fb9-11ea-9263-1470e49cd6a0.png)

**Comment by Ysurac** [comment]
MTU is calculated again only if it is not set in Network->Interfaces and for the interface.

**Comment by kevin39** [comment]
I understand but the calculated MTU is 1282 it seems too low... Do you recommend to set it manually ?

**Comment by Ysurac** [comment]
yes

**Comment by kevin39** [comment]
Thank you. I'll try differents values to find the best settings.
