### ISSUE TITLE
Question: Aggregated speed on current connections not restored on one WAN failure recovery

### ISSUE THREAD

**Issue by ghost** [Ysurac/openmptcprouter#974]
Downloading an ubuntu image from the official website on 10mbps(LTE)+(4mbps WDSL) results in perfect 14mbps, manually disconnecting LTE and reconnecting results in speed of 4mbps and no load on the LTE connection from the realtime page. However stopping and restarting the download after this effect restores the full speed, and torrents aren't affected.
Sometimes but rarely it does work however and it does restore the speed on replug.
The question is raised as we have frequent (every 15min) disconnections 24/7.
Both links have similar latency of 80ms.

Am I expecting a different behavior?

The status page in System>OMR is all green, and the performance including VoIP is perfect when manually cutting off one connections.

Config: Wizard setup + Glorytun TCP enabled + DSVPN disabled, using softVlan (e.g eth0.40).

I'm unaware of any possible fix.

## Specifications

  - OpenMPTCProuter version: openmptcprouter v0.52.3-107-g62584c3 r0+11546-a74095c68c / LuCI Master git-19.323.39847-15816e6
  - OpenMPTCProuter VPS version: 0.1015 4.19.104-mptcp
  - OpenMPTCProuter platform: Orange Pi R2 build unofficial (also happens with an official vmware machine)

Thanks!

**Comment by Ysurac** [comment]
Do you have the same issue when you use ```omr-test-speed``` via SSH on the router ?

**Comment by talalmash** [comment]
Yes, I just tried, and its the same behavior, however I tried disconnecting the other WAN (unplug) based on PPPoE and replug and the issue did not happen!
![mptcp2](https://user-images.githubusercontent.com/63075655/79683963-74f0bb80-8236-11ea-8486-65a40897110e.PNG)

**Comment by talalmash** [comment]
Oddly, running in this sequence:

1. Disconnect WAN1
2. Run omr-speed-test = 400kb/s
3. Connect WAN1, speed becomes = 1000+kb/s
4. Disconnect WAN1 = 400kb/s
5. Connect WAN1 still = 400kb/s
6. Restarting omr-speed-test = 1000+kb/s

WAN1 connection:  Openwrt router -> Wifi client conn. to Android AP -> relay bridge with vlan -> OMR

**Comment by Ysurac** [comment]
I will check if I can reproduce the issue, and if changes I made solve it in develop branch.

**Comment by Ysurac** [comment]
And for the bypass this seems strange... And I don't understand how you can get an empty response without that.

**Comment by talalmash** [comment]
> And for the bypass this seems strange... And I don't understand how you can get an empty response without that.

Neither SSH or HTTP respond after the tunnel is up without this option. I'll try on VMware again. I've just ordered rpi4b seeing this potential, thank you.

**Comment by talalmash** [comment]
> > And for the bypass this seems strange... And I don't understand how you can get an empty response without that.
> 
> Neither SSH or HTTP respond after the tunnel is up without this option. I'll try on VMware again. I've just ordered rpi4b seeing this potential, thank you.

Changing the IP address of the LAN back to stock 192.168.100.1 fixed it, no need for bypass, perhaps this should be opened for another issue. I'll retest the setup, however, do I have to disable multipath in config/network of the macvlan as it's showing "X" red, I'm using PPPoE. Thank you!

**Comment by Ysurac** [comment]
I don't understand what you mean in your last sentence: "Using eth0 directly works, setting other in the wizard then changing the macvlan created wan1 to pppoe resets to static.."

**Comment by talalmash** [comment]
> I don't understand what you mean in your last sentence: "Using eth0 directly works, setting other in the wizard then changing the macvlan created wan1 to pppoe resets to static.."

Sorry for the confusion, if I set a macvlan created interface in the Wizard -> Protocol to Other, then go to the Interface page, choose desired interface that was set to "Other" in the Wizard, then change the Protocol to PPPoE. Hit save and apply, it would reset to static. So I removed the macvlan and manually setup interface with eth0 instead of wan1. 

However, I just reset the firmware (re-import vmware image) and redone everything, but this time I've set the desired interface to PPPoE using CLI UCI, instead of LuCI and its working great.

**Comment by Ysurac** [comment]
Macvlan are set in network->macvlan menu. And a macvlan interfaces can't be set as PPPoE, only DHCP or Static because it's a "virtual" interface based on a real interface.
Why are you using macvlan ?

**Comment by talalmash** [comment]
> Macvlan are set in network->macvlan menu. And a macvlan interfaces can't be set as PPPoE, only DHCP or Static because it's a "virtual" interface based on a real interface.
> Why are you using macvlan ?

It was running without macvlan before, I thought that would be an issue as it was outside the wizard configuration, I'll set it up without macvlan as you said then. Should I try and compile the devel branch? Thank you.

**Comment by Ysurac** [comment]
No, the devel branch is still in dev :)

**Comment by Ysurac** [comment]
I found the issue and this will be solved in next release.
