### ISSUE TITLE
Not a bug - Personal record (using rpi4)

### ISSUE THREAD

**Issue by kevin39** [Ysurac/openmptcprouter#984]
Hi,
Not a bug, just a proof it working very great :)

My environment : 
- 1x 4G with Huawei B528s-23a + external antenna
- 1x 4G with Huawei B715s-23c with embed antenna
- 1x DSL
- OpenMTCPRouter on Rpi4
- TCP Scheduler : BLEST
- Congestion Control : Cubic
( FYI my external antenna is https://www.amazon.fr/gp/product/B01N11WV54/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1 )

I just got a personal record, using speedtest.net : 
![image](https://user-images.githubusercontent.com/976058/80065564-9c979a80-853a-11ea-81cd-9465afe35aa7.png)

And peak saved by OpenMTCPRouter :
![image](https://user-images.githubusercontent.com/976058/80065461-7245dd00-853a-11ea-91cc-710d7512ef14.png)
(from up to down : Free 4G, Free DSL, Bouygues 4G)

Thank you @Ysurac for your works. Before OpenMTCP I was depend of my unstable DSL connection and a slow Satellite connection. Thanks to your project I can work more effeencitly and during Covid19 it changed my life :)

**Comment by gwarf** [comment]
You are in France, right? What ISP are you using for 4G? I'm currently using 3 ADSL (around 10-12Mbps each), didn't yet considered moving to some 4G.

**Comment by kevin39** [comment]
Bouygues (my best Wan) and Free
(Free is also my DSL provider with its AliceADSL offer)
