### ISSUE TITLE
Vmtools sur version vmware

### ISSUE THREAD

**Issue by Percy24600** [Ysurac/openmptcprouter#989]
## Expected Behavior
Vmtools install on esxi version

## Current Behavior
Hi,
Is-it possible to install the vmtools on the router?

## Specifications

  - OpenMPTCProuter version: 
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter platform:

**Comment by Ysurac** [comment]
No.
It was available for OpenMPTCProuter, but too many bugs and too many memory/cpu usage, so it's no more available.
