### ISSUE TITLE
daemon.err openvpn(omr)[9315]: Options error

### ISSUE THREAD

**Issue by nileio** [Ysurac/openmptcprouter#99]
## Expected Behavior
no errors - bind tun0 (omrvpn) activated
## Actual Behavior
system error log
daemon.warn openvpn(omr)[7848]: disabling NCP mode (--ncp-disable) because not in P2MP client or server mode
daemon.err openvpn(omr)[6658]: Options error: --nobind doesn't make sense unless used with --remote

## Steps to Reproduce the Problem

  1. VPS install of openVPN
  2. vpn key upload
  3. choose OpenVPN as default VPN

## Specifications

  - OpenMPTCProuter version: .024
  - OpenMPTCProuter VPS version: 029
  - OpenMPTCProuter platform: (RPI3/x86_64) rpi 2

**Comment by Ysurac** [comment]
Not the same error in latest version, but solved warning and some other bugs.
Working in master tree, will be available in next version.
