### ISSUE TITLE
VPS master/backup - What is monitored ?

### ISSUE THREAD

**Issue by kevin39** [Ysurac/openmptcprouter#997]
Hi,
I just setup a backup VPS but the wiki is missing some information about it.

What is the rule to monitor the master VPS ? Is "enable server ping" mandatory ? 
What is the delay between switching master to backup  ? Is the rollback automated once the master is back ?

Edit : What is the best way to test my setup ? How force backup VPS to be used ?

Thanks

**Comment by Ysurac** [comment]
Parameters are in Services->Nginx High Availability.
Enable server ping is not needed (even if it's always better).
To test setup you can shutdown one VPS if possible.

**Comment by kevin39** [comment]
Ok thank you. And If I can't shutdown my VPS ?

**Comment by kevin39** [comment]
Fixed. I killed shadowsocks and glorytun :D 
Thank. This works beautifully.
